### ISSUE TITLE
moment() always generates an invalid date

### ISSUE THREAD

**Issue by fenfe1** [moment/moment#1015]
Hi, using moment.js 2.1.0 I don't seem to be able to create a valid date.

I've made a jsFiddle\* - http://tinker.io/ebb94 - which exhibits the same problem I have in my code.

I get the same error on Chrome (29.0) and Firefox (22.0) on Mac OS X 8.4 (in case it's relevant)

*jsFiddle was incredibly slow to do anything so I used an alternative provider

**Comment by sinhashalaka** [comment]
getting almost same bug as @imorti .. 

`time=datetime.datetime(2016, 11, 21, 5, 34, 38, 826339, tzinfo=<UTC>)` 

moment(time).format('MMMM Do YYYY, h:mm:ss a') gives Invalid date.

**Comment by MathieuAA** [comment]
Hi, I solved the issue by using this syntax `moment(<MY_UGLY_DATETIME>, 'YYYY-MM-DD').format(<WHAT_I_WANT>)`. As @imorti said, passing the format seems to work.

**Comment by jhcastellanos** [comment]
In my case I have a DateTime value, and I want to parse the SAME ELEMENT, I do not want to convert based on the LocalTime or any kind of converssion. However I could not find a concrete example by using moment.js

That is what I have: "2017-03-22T14:55:05Z", the expected result is: 03/22/17 02:55 pm... BUT the result is  03/22/17 10:55 am (4 hours less).

Any help???

**Comment by xehpuk** [comment]
@jhcastellanos You didn't post any code so this is just a guess: You are _displaying_ it in local time (no conversion happening here). Use `moment.utc("2017-03-22T14:55:05Z")` to switch to [UTC mode](https://momentjs.com/docs/#/parsing/utc/).

**Comment by anupammaurya** [comment]
moment('') || moment(null)
`_d : Invalid Date {}`

------------
moment(new Date())
`_d:Tue Oct 23 2018 17:44:53 GMT+0530 (India Standard Time) {}`

**Comment by meysambostak** [comment]
moment('1398-02-29').format()

**Comment by meysambostak** [comment]
moment('1398-02-29').format()

_d : Invalid Date {}
