### ISSUE TITLE
toString() should use default format rather than fixed?

### ISSUE THREAD

**Issue by ShawnTalbert** [moment/moment#1018]
Since a _default format_ is supported I propose it logical that toString() would use this default format if defined rather than the hardcoded format "ddd MMM DD YYYY HH:mm:ss [GMT]ZZ"?

**Comment by carlos-algms** [comment]
@ichernev Your solution is very accurate. But is very difficult to find as well.
Maybe this information should be in the Documentation.

**Comment by icambron** [comment]
@carlos-algms It's not really about Moment; that's just overwriting a Javascript function, and you can do it to any library for any function. I don't think it belongs in the docs.

**Comment by carlos-algms** [comment]
@icambron 
I think that is a moment documentation because I'm replacing a function inside `moment.fn` and not under the date prototype

**Comment by icambron** [comment]
Yes, you're overriding a Moment function, but my point is that you can always do that to any function in JS in any of a zillion ways. @ichernev's code does is simply say, "I'd like this function to do something other than what it's defined to do". We can't start documenting every possible way to do that or the docs would turn into a mess; users should take it for granted that if they define a function to do something new, it will do that new something because that's how JS works.

**Comment by ironside** [comment]
I generally agree with icambron above...monkey patching moment's toString() not only shouldn't be _documented_, it shouldn't even be done.

Even though I still think my original request has merit, I still stick to the published api and use .format() as needed.

**Comment by adambuczynski** [comment]
A valid use case would be that if you use moments in your app, but for communication with your server you want to pass the dates as a string with a specific format, then you have to call `someMoment.format(MY_DEFAULT_FORMAT)` in *every place* where you send a date to the server. This is very cumbersome and hard to maintain. So I can see the appeal of being able to set a default format for `toString` or at least `toJson`.

**Comment by damianobarbati** [comment]
+1

**Comment by ichernev** [comment]
Or add .toServerString() and use that instead. toString is for debugging, i cant imagine why someone will use it for something else when there is format. And you can change the default format.

**Comment by loopmode** [comment]
My use case is this. I put moment objects in a `alt` store. The library has a devtools extension that displays state values, much like redux devetools do. 
When those devtools display the objects, they implicitly do either toString or toJson, and I don't get to choose whether to apply format myself.

Critical in my case: I am working on a complex media player, the current focus is on tv programs that were broadcasted across midnight, e.g. 23:15 - 00:45, and it's just very annoying and confusing to work like this:

![image](https://user-images.githubusercontent.com/623225/36719701-2679819c-1ba6-11e8-8275-76bdf4c307c0.png)
