### ISSUE TITLE
Show localized date format based on computer settings

### ISSUE THREAD

**Issue by philfreo** [moment/moment#1044]
Apologies for using an Issue for a question like this - didn't see another channel, and this might qualify as a feature request.

I see in http://momentjs.com/docs/#/displaying/format/ the "Localized formats" options such as `L`. 

(In the browser) I expected this might change the display of a date from mm/dd/yyyy to dd/mm/yyyy depending on the user's computer/browser locale settings, however this doesn't seem to be the case. (I changed my OS X settings to test, and didn't see any browser-specific settings). 
- Is there a way to accomplish this in Moment currently? I'm not looking to display different languages/translations, but rather just different date formats based on the user's country/locale settings.
- If not, is this possible/practical at all? I'm not sure of the reliability/usefulness of stuff like `toLocaleDateString`

**Comment by bartclaeys** [comment]
Any update on this? How is support in 2018 for toLocaleDateString()?

**Comment by icambron** [comment]
@bartclaeys I think it basically tracks [this](https://caniuse.com/#search=intl) so pretty good.

Moment still has `m.toDate().toLocaleString()`, so no update there. Luxon has broad support for it.

**Comment by tomaszczechowski** [comment]
it may help https://gist.github.com/tomaszczechowski/3da9b55fb12cfb2b725fe558ece55219
