### ISSUE TITLE
ISO8601 UTC Support?

### ISSUE THREAD

**Issue by longlivetheux** [moment/moment#107]
Looking to replace Date.js and a bunch of hacks in a JS Application. Does moment.js support (cross-browser) parsing of and conversion to the ISO8601 UTC Format? 2011-12-16T06:00:00.000Z

**Comment by jameskleeh** [comment]
@jefffriesen I know this is absolutely ancient, however I had the same problem and this works:

`a.format("YYYY-MM-DDTHH:mm:ss\\Z")`

**Comment by jefffriesen** [comment]
@jameskleeh I don't need it anymore but it's nice to create working examples for everyone to reference. Thanks.
