### ISSUE TITLE
Would be really great if moment.js had a precise setInterval function

### ISSUE THREAD

**Issue by dbkaplun** [moment/moment#1073]
According to this [SO page](http://stackoverflow.com/questions/985670/will-setinterval-drift) (not the best source, I know), setInterval and a naive setTimeout recursion can drift. I see on your home page you have a clock showing the current time (lines 82-85 [here](http://momentjs.com/static/js/core-home.js)). Would be silly if someone came back to the computer some time later and saw the second hand off.

**Comment by SeverinDK** [comment]
I put this together over the last few days https://github.com/SeverinDK/moment-timer
Think that's what you guys were talking about.
