### ISSUE TITLE
Requirejs module name: make it empty so that we can use a different one?

### ISSUE THREAD

**Issue by Anomen** [moment/moment#1095]
Hi,

I'm just integrating moment.js in my requirejs project. I'm having an issue because I want to include momentjs independently from the general config.js (so I don't want the rest of the application to know that I'm including this lib).

So, here is my code for my project:

``` javascript
define(function(require, exports, module){
    'use strict';

    var moment = require('./moment.min');
    // ...
```

This does not work, because moment.js define a requirejs module, named "moment", and not "./moment.min" (or whatever I want to call it). Although a "path" config makes it work, it's something that I want to avoid.

Just changing ( here: https://github.com/moment/moment/blob/develop/moment.js#L1777 ):

``` javascript
    if (typeof define === "function" && define.amd) {
        define("moment", [], function () {
            return moment;
        });
    }
```

by:

``` javascript
    if (typeof define === "function" && define.amd) {
        define([], function () {
            return moment;
        });
    }
```

makes it work.

My question is: is there a particular reason why a name is explicitely defined? Does it break anything?

Thanks!
Kev

**Comment by wyantb** [comment]
@radekn  @cowwoc etc

https://github.com/moment/moment/pull/1963

**Comment by cowwoc** [comment]
@wyantb Hurray! Thank you!
