### ISSUE TITLE
moment.js validating invalid date “2013-10-311”

### ISSUE THREAD

**Issue by grahampcharles** [moment/moment#1128]
Dates with extraneous characters are sometimes being validated; sometimes not. In one case, the behavior changes when extra format strings are offered. To wit:

```
moment("2010-10-319", ["YYYY-MM-DD"]).isValid() // true
moment("2010-10-31a", ["YYYY-MM-DD"]).isValid(); // true
moment("2010-10-319", ["MM/DD/YYYY", "MM-DD-YYYY", "YYYY-MM-DD"]).isValid(); // true
moment("2010-10-3199", ["MM/DD/YYYY", "MM-DD-YYYY", "YYYY-MM-DD"]).isValid(); // false (!!!)
moment("2010-10-319qr", ["MM/DD/YYYY", "MM-DD-YYYY", "YYYY-MM-DD"]).isValid(); // true (!)
```

Here's the fiddle: http://jsfiddle.net/grahampcharles/r42jg/6/  and the [SO question](http://stackoverflow.com/questions/18997388/moment-js-validating-invalid-date-2013-10-311) link.

**Comment by ketankulkarni** [comment]
if i check moment("121212").isValid()
it returns true
but if i try to convert like      
alert(moment("121212").format("YYYY-MM-DD"))
it gives output - 121212-01-01
can anyone tell me why this is happening
