### ISSUE TITLE
Moment.format does not work properly with line-break [\n]

### ISSUE THREAD

**Issue by goodlime** [moment/moment#1151]
`moment().format("ddd\nDD\nMMM")`
results in string:
Mon30Sep

`moment().format("ddd[\n]DD[\n]MMM")`
results in string:
Mon[
]30[
]Sep

**Comment by guptasaumya** [comment]
What is the fix exactly? Did you get a solution?

**Comment by icambron** [comment]
@guptasaumya I don't remember, but that PR was merged with a test case, so it looks like it was fixed.

**Comment by guptasaumya** [comment]
Uh, no. It doesn't work.

**Comment by icambron** [comment]
@guptasaumya This ticket was closed as fixed 5 years ago. Sounds like you've found a fresh problem. I suggest you file a new issue.

**Comment by seajean** [comment]
I have the same problem, open this issue again?

**Comment by jonaslagoni** [comment]
Using the html breakline syntax works - moment().format("ddd[</br>]DD[</br>]MMM")

**Comment by icambron** [comment]
please, y'all, file a new issue
