### ISSUE TITLE
Adding day across DST fails

### ISSUE THREAD

**Issue by ricardobeat** [moment/moment#1231]
Calling `.add('days', 1)` across the DST transition causes the date to not change at all:

```
var d = moment('2013-10-19T00:00:00')
d.format() // 2013-10-19T00:00:00-03:00
d.add('days', 1)
d.format() // 2013-10-19T00:00:00-03:00
```

But this works:

```
d.add('hours', 24)
d.format() // 2013-10-20T01:00:00-02:00
```

Local time BRST (GMT-3 / GMT-2).

Seen in dangrossman/bootstrap-daterangepicker/issues/176, might be related to #1161 and #1210

**Comment by ryanirilli** [comment]
Another solution my team is trying to to simply use America/Fortaleza timezone instead of Sao Paulo which has the same UTC offset but no DST.
