### ISSUE TITLE
New getter/setter: moment().weekOfMonth()

### ISSUE THREAD

**Issue by OlsonDev** [moment/moment#1232]
It would be convenient to have a new getter/setter called `weekOfMonth()`. I've been maintaining an [answer](http://stackoverflow.com/a/9608670/221867) on StackOverflow for a while now on how to calculate a date's week of month using vanilla JavaScript. However, it would be nice if `moment`s had this property.

As far as implementation goes, mine is reasonably flexible. If you want to remove the flexibility in favor of consistency with other methods, I'm perfectly fine with that.
If one were to use the setter, I would think it could mean two different things:
 1. Start of week specified
 2. Maintain the day of week and time of day but just adjust the date

I would think you'd go with option 2; it seems more consistent with other setters.

I'm not sure what out-of-bounds values should indicate. Say you pass in `7`... does that mean the 1st week of the next month? Or should an error be thrown?

I'm also indifferent on the setter behavior -- I'll let the experts agree on a decision! :-)

**Comment by csvan** [comment]
+1

**Comment by icambron** [comment]
See #2965
