### ISSUE TITLE
Spanish: don't add . after short month/day names

### ISSUE THREAD

**Issue by DamianFekete** [moment/moment#1234]
A format **DD-MMM-YYYY** for Spanish will translate in **29-nov.-2013** but in **29-nov-2013** in Windows (and Java).

```
monthsShort : "ene._feb._mar._abr._may._jun._jul._ago._sep._oct._nov._dic.".split("_"),
weekdaysShort : "dom._lun._mar._mié._jue._vie._sáb.".split("_"),
```

**Comment by iori57** [comment]
I am seeing this for German locale as well.. maybe it's a good idea to fan out the fix to all locales that has a dot in it's monthsShort names?

And also it not only applies to -MMM-, the dot also looks weird when using formats like DD.MMM.YYYY (results in 29-nov.-2013) and DD/MMM/YYYY (results in 29/nov./2013) too.

**Comment by sylv3r** [comment]
Same in French for all shorted strings... Why are you adding this dot everywhere ?
