### ISSUE TITLE
Romanian: months/days should start with lowercase, etc

### ISSUE THREAD

**Issue by DamianFekete** [moment/moment#1235]
Lowercase for months, monthsShort and weekdays. Proper format for longDateFormat (we don't write 29/10/2013, but instead 29.10.2013)

```
months : "ianuarie_februarie_martie_aprilie_mai_iunie_iulie_august_septembrie_octombrie_noiembrie_decembrie".split("_"),
monthsShort : "ian_feb_mar_apr_mai_iun_iul_aug_sep_oct_noi_dec".split("_"),
weekdays : "duminică_luni_marți_miercuri_joi_vineri_sâmbătă".split("_"),

L : "DD.MM.YYYY",
```

weekdays: Marți instead of Marţi. There is a small visual difference, but there is one:
https://en.wikipedia.org/wiki/Romanian_alphabet#Comma-below_.28.C8.99_and_.C8.9B.29_versus_cedilla_.28.C5.9F_and_.C5.A3.29

**Comment by hangorazvan** [comment]
Why lowercase for monts and week days?

**Comment by gurdiga** [comment]
> Why lowercase for monts and week days?

Why not? 🤔

**Comment by DamianFekete** [comment]
@hangorazvan, because they are common nouns, not proper nouns, and you don't always capitalize them.

Example: http://legislatie.just.ro/Public/DetaliiDocumentAfis/221908
> din 8 ianuarie 2020
> București, 6 ianuarie 2020.

**Comment by hangorazvan** [comment]
OK, anyway for may project I use

```
		moment.updateLocale("ro", {
			months : [
				"Ianuarie", "Februarie", "Martie", "Aprilie", "Mai", "Iunie", "Iulie",
				"August", "Septembrie", "Octombrie", "Noiembrie", "Decembrie"
			],
			weekdays : [
				"Duminică", "Luni", "Marți", "Miercuri", "Joi", "Vineri", "Sâmbătă"
			]
		});
```
