### ISSUE TITLE
Collaboration with Globalize on CLDR?

### ISSUE THREAD

**Issue by jzaefferer** [moment/moment#1241]
This is not a code issue, but StackOverflow is inappropriate for this request and I didn't yet want to email committers individually.

I'm on the jQuery Team, and we're working on a project called Globalize. Globalize has a lot of overlap with Moment.js. One major difference is the source for locales. As far as I can tell, Moment builds on user-contributed translations, by now 63 in total. Globalize started by importing locale data from .Net, giving as about 350 "cultures" (naming is hard...). So far not too interesting.

We're currently in the process of [moving to CLDR](https://github.com/jquery/globalize/pull/172), using their database of locales as the new base for Globalize. This requires a lot of groundwork to make the data usable in JavaScript. We're also reporting back issues to them, like missing documentation.

I've had a bit of communication with Tim Wood in the past (see #315) about using CLDR. That was a year ago, since then it looks like the project is now standing on more shoulders, so hopefully adopting CLDR, along with some form of collaboration with the jQuery Team is something worth revisiting.

On our end, @rxaviers and @scottgonzalez are the other two people most involved. We're generally around on IRC (Freenode/#jqueryui-dev) for some ad-hoc discussions. I can also make introductions per email, if that is preferred over this issue tracker (my email address is in my github profile).

**Comment by Nate-Wilkins** [comment]
@ichernev @jzaefferer Does anyone know how far along this is?

If nobody has started work on this I might be able to take a look?

**Comment by rxaviers** [comment]
@ichernev can give better details, but he started https://github.com/ichernev/moment-cldr

**Comment by Nate-Wilkins** [comment]
Great thanks! @rxaviers Do you know if the intent of this issue was to also combine Globalize's date formatter?

**Comment by rxaviers** [comment]
Yes, the intent was not to duplicate efforts by using Globalize as an underlying CLDR layer provider (or more precisely, i18n library that leverage CLDR). But, again @ichernev can provide better details.

**Comment by Boycce** [comment]
Be awesome if moment took JSON like objects for parsing new locales in. eg. http://amsul.ca/pickadate.js/date/#translations
Any logic that a particular language needs, such as pluralisation would be detected by what is parsed into moment by conforming to CLDR naming conventions.

This will allow us to package our locales in our build processes from CLDR, and reuse the same locale data for every aspect of our software.

**Comment by marwahaha** [comment]
it looks like Globalize has been out for some time: https://github.com/globalizejs/globalize

I'm not sure how Moment.js would collaborate at this time.

If people have ideas, they can post here or in a new issue.
