### ISSUE TITLE
Julian Day support missing

### ISSUE THREAD

**Issue by bartolsthoorn** [moment/moment#1276]
I think Moment.js is missing a method to convert a datetime to a [Julian Day](http://en.wikipedia.org/wiki/Julian_day). The JD-system is used by astronomers.

**Comment by rhyolight** [comment]
I would have used this feature if it existed today.

**Comment by boriskogan81** [comment]
+1

**Comment by michaelKurowski** [comment]
+1 useful for astronomical purposes

**Comment by jacobbogers** [comment]
old ticket, but is it implemented?
