### ISSUE TITLE
Short versions of from/fromNow

### ISSUE THREAD

**Issue by blixt** [moment/moment#1331]
It would be really great to have a short version of the `from` and `fromNow` methods. So in addition to:

``` js
var a = moment([2007, 0, 29]);
var b = moment([2007, 0, 28]);
a.from(b) // "a day ago"
a.from(b, true) // "a day"
```

…you could call this:

``` js
a.fromShort(b) // "1d ago"
a.fromShort(b, true) // "1d"
```

**Comment by ScottBeeson** [comment]
This would be awesome.  I'm doing a metrics dashboard and I want to overlay the time since last transaction on the chart but I'd rather it say "3s" instead of "a few seconds ago"

**Comment by ScottBeeson** [comment]
So it was a pretty easy change:

    var defaultRelativeTime = {
        future : 'in %s',
        past   : '%s',
        s  : '%ds',
        m  : 'a minute',
        mm : '%d minutes',
        h  : 'an hour',
        hh : '%d hours',
        d  : 'a day',
        dd : '%d days',
        M  : 'a month',
        MM : '%d months',
        y  : 'a year',
        yy : '%d years'
    };
