### ISSUE TITLE
Two-digit year format for localized formats?

### ISSUE THREAD

**Issue by blixt** [moment/moment#1332]
The current `l` and `L` formats return a 4-digit year. Would it be possible to have additional formats to indicate that the year should be 2-digit? Something like:

``` js
// Existing:
moment().format('l'); // 9/4/1986
moment().format('L'); // 09/04/1986
// New:
moment().format('lx'); // 9/4/86
moment().format('Lx'); // 09/04/86
```

(Note: I don't know what character would make sense to put after `l`, so I just put `x` to show what I mean.)

**Comment by lizzzzard** [comment]
Would love to see this too.
