### ISSUE TITLE
Timezone offsets flipped?

### ISSUE THREAD

**Issue by drinks** [moment/moment#139]
I'm pretty sure I must be doing something wrong here. it _appears_ that parsing `2012-01-21T17:08:01-05:00` (EST) with or without the pattern `YYYY-MM-DDTHH:mm:ssZ` is subtracting 5 hours to get to UTC, rather than adding. As a result, my times when written back with format() are 10 hours behind. I get the expected result by flipping the comparison at line 301:

```
// reverse offsets
if (a[0] === '+') {
    timezoneHours = -timezoneHours;
    timezoneMinutes = -timezoneMinutes;
}
```

Surely this isn't right, am I parsing incorrectly?

**Comment by enapupe** [comment]
Sorry to resurrect this issue, but my question is relative to this subject:
When I call format() it automagically converts the input datetime to local datetime, using `Date.prototype.getTimezoneOffset` as difference from input datetime to user's time? Is that assumption correct?
If is, how do I override that behavior? Say the user chose its own tz.. How would moment NOT use `Date.prototype.getTimezoneOffset`, but instead, use the specified offset.

**Comment by mj1856** [comment]
@enapupe - That actually happens much earlier than formatting.

Just call `.utcOffset(...)` if you have a fixed offset.  It is inverted from `getTimezoneOffset` to align with ISO8601.  [See the docs](http://momentjs.com/docs/#/manipulating/utc-offset/).

If you're not dealing with fixed offsets, but rather a non-local time zone that may use different offset depending on whether or not DST is in effect, then you'll need to use the [moment-timezone](momentjs.com/timezone/) addon.

**Comment by enapupe** [comment]
I'm not dealing with fixed offset. Any user may have its own setting on which the datetimes are displayed and converted back to UTC before hitting the API.

**Comment by enapupe** [comment]
So, I have to use moment-timezone and convert all the dates, right? Now I must figure a way to do this at some low level to avoid code duplication.
Thanks for your input, it was very useful.

**Comment by mj1856** [comment]
@enapupe - If all your users only need to deal with their own local time zone, then you don't need moment-timezone.  Moment can handle conversion between utc and "local" by itself.

It's only if your users need to convert to some *other* time zone that you need moment-timezone.

For example:

```javascript
// two ways of utc-to-local
moment("2015-10-26T01:23:45Z")
moment.utc("2015-10-26T01:23:45").local()

// to a fixed offset:
moment("2015-10-26T01:23:45Z").utcOffset('-08:00')

// to a named time zone (requires moment-timezone)
moment("2015-10-26T01:23:45Z").tz('Amerca/Los_Angeles')
```

**Comment by enapupe** [comment]
The users have to deal only with their local time zone, but their tz is not necessarily what `getTimezoneOffset()` reports. It may be something different, set from their profile.. 
Does that makes sense? Am I gonna have to use moment-tz?
I'm very thankful for your attention.

**Comment by mj1856** [comment]
Assuming you are asking them to choose a named time zone, such as `America/Los_Angeles`, then yes, you will need moment-timezone.

**Comment by enapupe** [comment]
I see.. 
They will choose a named timezone. So, I need `moment-timezone` mostly because it solves DST, right? Otherwise we could just map a timezone to a offset and done.

**Comment by mj1856** [comment]
Yes, but if you map a fixed offset then you ignore the realities of DST and will have incorrect conversions for a subset of your user base.  This can only be solved with named time zones and a time zone database, such as the one used with moment-timezone.

**Comment by enapupe** [comment]
Yeah.. I got that..
Thanks man, the tz issue is now  **fixed**!
