### ISSUE TITLE
Be careful when falling back to Date constructor

### ISSUE THREAD

**Issue by ichernev** [moment/moment#1407]
If you clicked on the warning link and landed here:

`moment` construction using a non-iso string is deprecated. What this means is you **can safely do**

``` javascript
> moment("2014-04-25T01:32:21.196Z");  // iso string, utc timezone
> moment("2014-04-25T01:32:21.196+0600");  // iso string with timezone
> moment("2014 04 25", "YYYY MM DD"); // string with format
```

but you **can't do reliably** (therefore its being deprecated)

``` javascript
> moment("2014/04/25");
> moment("Thu Apr 24 2014 12:32:21 GMT-0700 (PDT)");
> moment("some random string that looks like date");
```

In the upcoming releases a few more well defined formats might be added, but the general idea of using any random string to construct a date is no more. If you really want that behavior just do `moment(new Date("random string that contains date"))`, but `moment` won't be responsible for such convertions. Read below for the rationale about the change
# 

As described in https://github.com/moment/moment/issues/1403#issuecomment-31961590, but also recent debugging c4d9f6e and 94d6c90 caused by https://travis-ci.org/moment/moment/builds/16672288 brings me to the conclusion that 

> using `Date` to create a moment from string, passed from the user is extremely unpredictable, and it turns out to work somewhat and then bite you in an edge case when you're not careful

So I think we need an option to disable it, for tests at the very least. I've debugged that numerous times thank to our old friend IE6 and friends.

You'd pass a string only, hoping that it would hit one of the predefined formats, but instead it hits Date and it sort-of works, sometimes. I think it should be clear to users when they're hitting this case, and that it might not work well on all browsers.

The only use-case for using Date to parse input is when a) it is entered by a web user (moment's user's user :)) and b) the web user can see how we're interpreting the date entered. Every other case is just silently waiting to break at some point.

**Comment by kashban** [comment]
I browsed the whole thread, but nowhere the most common use case is mentioned: Creating a moment with the current date and time.

Since using new Date() is warned about, what's the supported and recommended way to create a moment with the current datetime?

**Comment by rluba** [comment]
@kashban `var now = moment();` will give you a moment object representing the current date/time.

**Comment by Geddard** [comment]
I'm clueless about why am i getting this warning now... i had it fixed but now it's back again...

can anyone guess whats the problem? Here's the code, i'm getting the warning at line "'mild-red-card': (Moment(date... "

```javascript
getPicClasses: function () {
        var twoWeeks = Moment().subtract(2, 'weeks').format('MM/DD/YYYY');
        var threeWeeks = Moment().subtract(3, 'weeks').format('MM/DD/YYYY');
        var fourWeeks = Moment().subtract(4, 'weeks').format('MM/DD/YYYY');
        var date = this.props.date;

        return cx({
            'pic': true,
            'mild-red-card': (Moment(date, 'MM/DD/YYYY').isBetween(threeWeeks, twoWeeks)) || Moment(date, 'MM/DD/YYYY').isSame(twoWeeks),
            'red-card': (Moment(date, 'MM/DD/YYYY').isBetween(fourWeeks, threeWeeks)) || Moment(date, 'MM/DD/YYYY').isSame(threeWeeks),
            'red-glowing-card': (Moment(date, 'MM/DD/YYYY').isBefore(fourWeeks) ) || Moment(date, 'MM/DD/YYYY').isSame(fourWeeks)
        });
    },
```

**Comment by crobinson42** [comment]
Moment produces this date : "Thu Jan 01 2015 00:00:00 GMT-0800 (PST)"
yet, Moment warns me that the date that IT PRODUCED is wrong... this seems broken - some logic from anyone please?!


monthStart = moment().startOf('month')._d
moment( monthStart ).format('MMMM YYYY')

"Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info."

**Comment by mikermcneil** [comment]
Just a thought- what about grabbing a stack trace with `new Error()` and stuffing it in the deprecation warning?  It took me a while to hunt down where this was happening (it was one of our dependencies, https://github.com/urish/angular-moment).  I've just started using the same approach in sails/node-machine and it's been pretty effective so far.  I'll send a PR- feel free to close or accept, no pressure :+1:

**Comment by mikermcneil** [comment]
@ichernev @icambron here's a link to that: https://github.com/moment/moment/pull/2175

**Comment by simonh1000** [comment]
This is rather confusing. I'm using `var now = new Date();` and then `now.toString()` to put dates into a database, and when I try to read afterwards through `moment(item.value.date).format("D MMM YY")` I'm getting the deprecation message. Surely moment works with dates created by javascript?

**Comment by thuff** [comment]
@simonh1000 I am running into a similar issue, using the original suggested solution of parsing my server created strings through a `new Date()` constructor. I would greatly appreciate @mikermcneil's contribution as it would easily allow me to find where the errors occur.

**Comment by jonathanong** [comment]
can you add a stack trace to where the deprecation notice is being called? i can't figure out where it's coming from.

https://github.com/dougwilson/nodejs-depd

**Comment by rey-wright** [comment]
Let me hopefully help someone else who is confused (I know it was answered but it wasn't immediately obvious): all you have to do to avoid the deprecation error, having to use new Date & avoiding the unreliability, is to just specify the format of the string that is passed in.

**Comment by jhiver** [comment]
Yeah, but the ability to make a "best effort" guess in date parsing was
actually really useful.

2015-04-01 19:15 GMT+04:00 rey-wright <notifications@github.com>:

**Comment by rey-wright** [comment]
you can still do that if you use new Date(). They're deprecating it because it's unreliable.

**Comment by kbooe** [comment]
I had been using moment().subtract(1, "day") to get the current date minus one day. Now I am getting the deprecation warning. What is the best way to do this now?

**Comment by warrendodsworth** [comment]
Issue when using this fix with MomentJs TimeZones

Converting from UTC to an IANATimeZone
    moment.utc( 'Apr 8, 2015 4:15 PM' ).tz('Australia/Perth')  // Success + Console Error

With Fix
    moment.utc( new Date( 'Apr 8, 2015 4:15 PM' )).tz('Australia/Perth')  // Failure + No Console Error

The result with the fix just stays in UTC time and does not get converted.

**Comment by merriam** [comment]
So, just to be clear:

1.   It's not possible to always parse every date like string reliably.
2.   There are dates that work, that sometimes work, and that never work.
3.   Moment doesn't want the blame for dates that sometimes or never work.
4.   Instead of being able to toss warnings on those dates in the future, or to
      explicitly tell moment to do the best it can, e.g., 'moment(something, error:...)' or
      moment(something, guess: true, errror: ...), we tell users to do
      moment(new Date(something)).
5.   This will be much less prone to giving complaints to moment, errors like 
      moment(Date(something)) are clearly the users fault, and new versions of JavaScript
     might someday fix the Date function.

Is this the plan?

**Comment by jmenashe** [comment]
It probably makes sense to update the documentation *before* adding deprecation warnings. For example, the top of the primary moment.js docs page provides this example:

```
var day = moment("1995-12-25");
```

Per the discussion, this initialization method should be avoided and should probably not be suggested by the primary documentation.

**Comment by KaduAmaral** [comment]
This does not make any sense. I use the plugin just to not have to parse date, I want him to do it for me. Now I have to parse to the format that the plugin wants to him parse for the format I want? I better make directly to the format I want.

I'm saying exactly the format that the date is:

`moment('Thu, 30 Apr 2015 3:01 pm', 'ddd, DD MMM YYYY H:mm a')`

Why it can not validate it?

**Comment by zackgilbert** [comment]
@KaduAmaral You want 'ddd, DD MMM YYYY h:mm a' for your format. Lowercase h, not uppercase H. I assume that's why it's not working for you.

**Comment by KaduAmaral** [comment]
Hi @zackgilbert still not working. 

`moment('Mon, 04 May 2015 8:01 am', 'ddd, DD MMM YYYY h:mm a').isValid()` 

The result is `false`.

**Comment by jasonfreier** [comment]
Erm, so what about when you are trying to create Moments in UTC using timestamps?  How exactly would you pass a format string for a timestamp?

**Comment by jasonfreier** [comment]
@KaduAmaral 
if you look at the parsing/string-format section of the docs, there isn't even a reference to anything that would give you the day name.  If you take that portion out of your string and try again, it will probably work:

`moment('04 May 2015 8:01 am', 'DD MMM YYYY h:mm a').isvalid()`

**Comment by scottybrown** [comment]
I have the same question as @Izhaki and @elliotf. How do you check if something is valid without constructing a moment object which gives the warning?

I feel like this is a valid use case.

**Comment by philwig** [comment]
This is a confusing error message. I'm sure that the people who put this into my console are very clever and very pleased to demonstrate this to everyone. I'm sorry but I think you've misunderstood why people like me want to use this - I do not want a lecture on software engineering, thanks.

I can see how to hack the stupid warning out of moment well enough - that is likely easier than working out which bit of code here is causing some dumb error which obviously has no effect on users. Thanks for wasting my time.

**Comment by lzilioli** [comment]
The following line of code, *really* should not throw this warning...

```javascript
// This throws the warning
moment( moment().toString() );
```

Why should I have to provide a string to a library explicitly for the purpose of telling it to return to me something that said library deems acceptable?

This is a simplified test case for what I imagine is a common use case of moment:

- get the current time
- save it to a database by invoking toString
- ...later, get the current time and compare it to what was in the database using moment's compare features
- decide what to do depending on how much time has elapsed

**Comment by quocnguyen** [comment]
Same here, the stack trace is useless for me.

**Comment by cspotcode** [comment]
@lzilioli: Why not use `moment().toISOString()` instead?  This solves the problem and is the same as calling `moment.toJSON()`.  This means if you call `toISOString()` or `toJSON()` then your database version of the date will be the same, unambiguous ISO string as would be sent over the wire in a RESTful service.

**Comment by wolgamj** [comment]
```JavaScript    
var isoDateString = "2015-05-29T12:37:00.000Z";
var utcDateString = "Fri, 30 Jul 2010 15:05:00 UTC";
var test1 = moment(isoDateString, 'MM/DD/yyyy').isValid(); //test1 = false;
var test2 = moment(utcDateString, 'MM/dd/yyyy').isValid();  //test2 = false;
```
So neither the native JS ISO or UTC date formats are valid??  I'm not sure that this approach is the best idea... these are after all widely accepted standard formats to express date/time values in JS.

**Comment by cspotcode** [comment]
It's because you're passing a format string that isn't ISO, so you're
explicitly telling moment *not* to parse the input as an ISO string.  If
you stop doing that, moment will parse an ISO string just fine.

```
var isoDateString = "2015-05-29T12:37:00.000Z";
var test1 = moment(isoDateString).isValid(); //test1 = true;
```

**Comment by juliomac** [comment]
I am using moment.js to handle i18n and got this deprecated warning:
```Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.```

It is quite useful to use the locale to properly to "translate" one date to another. As in the example below:

    console.log("01-02-2003 + en = ", moment("01/02/2003","en").format()); \\ month = January, day 2
    console.log("01-02-2003 + pt-BR= ", moment("01/02/2003", "pt-BR").format());``` \\month=February, day1

I don't see any risk of parsing it wrongly when we are using the locale. In fact, I think it is preferable than using "hard" formats and extra logical code to interpret from one format to another.

**Comment by defel** [comment]
ok, I have to override a method implemented by moment.js (createFromInputFallback) to disable this warning in my test. when I explicit want to test for `moment("invalid-date").isValid()==false`? This does not feel good. A simple config-option would be better.

**Comment by cspotcode** [comment]
@defel: you can pass a format string to the moment constructor to avoid the deprecation warning.  Since construction with non-ISO strings is deprecated anyway, this code is essentially equivalent.

```
moment("invalid-date", "ISO").isValid()==false
```

**Comment by defel** [comment]
@cspotcode thanks, that works. I had to do something like this:

```js
var startDate = is.date(request.payload.startDate) ? 
    moment(request.payload.startDate) : 
    moment(request.payload.startDate, "ISO");
```

**Comment by scottybrown** [comment]
@cspotcode thanks, you've answered my question as well as those by @Izhaki and @elliotf.

**Comment by jsilverMDX** [comment]
Yes, this is an annoying warning and it is hard to debug. Whether or not if it is worthwhile, I have no idea. But I just wanted to provide some additional info. Since moment is used in some plugins, code like

```javascript
    $('.datePicker').datetimepicker({
        defaultDate: "11/1/2013",
        format: 'MM/DD/YYYY'
    });
```

Can cause the warning. To solve it, fix defaultDate to be an ISO string or whatever or just take it out.

**Comment by bettiolo** [comment]
Docs should be updated: http://momentjs.com/docs/#/parsing/date/

**Comment by alexserver** [comment]
I saw in the next major version the warning message will be removed when you use isValid after the constructor:
```
moment('some invalid string').isValid(); //throws warning.
```
This is still happening in version 2.10.6

**Comment by scottybrown** [comment]
@alexserver in case you missed it, @cspotcode's answer above provides a nifty work-around for using isValid() :)

**Comment by mitar** [comment]
I opened a ticket for RFC2822 dates: #2530

**Comment by blinkus** [comment]
Hi guys,

I got this message as well. I found my code which was causing it which was

timeinbound = moment.tz('RcvTimestampUtc', 'Australia/Melbourne').format('DD MMMM YYYY hh:mm:ss A');

I then changed it to include the format of the 'RcvTimestampUtc' string so moment didn't complain about the issue.

timeinbound = moment.tz('RcvTimestampUtc', 'YYYY-MM-DD hh:mm:ssZ', 'Australia/Melbourne').format('DD MMMM YYYY hh:mm:ss A');

Hope this helps someone else.

**Comment by warrendodsworth** [comment]
Issue - using javascript Date() constructor dosent work with moment.utc() constructor and moment timezones

```javascript
var datetime = 'Aug 7, 2015 9:00 AM';
moment.utc ( datetime ).tz( timezone )         // Works perfectly (except for the warning)
moment.utc ( new Date( datetime ) ).tz( timezone )     // Fails to convert to timezone
```

**Comment by teneketo** [comment]
Hi all I could really use some help. This issue above is now causing js errors that Chrome doesn't actually detect. I'm trying to get the current date in fullCalendar, the following function doesn't work:
 function getCalDate() {
  var moment = $('#calendar').fullCalendar('getDate');
  alert(moment.format());
}
(It's worth nothing it USED to work, I even reverted back to an older working backup, same problem as bellow)
I get Uncaught [TypeError: moment.format is not a function]. I do have moment.format() in few of the other functions in that page. Basically alert() doesn't work, does not alert... Can't debug because of this, some of my JS works, some does not any fix suggestion would be much appreciated.

**Comment by Radagaisus** [comment]
Is there a way to silence this warning? It's driving me insane.

**Comment by brunocoelho** [comment]
@Radagaisus What about this?

 
![screen shot 2015-09-08 at 15 40 58](https://cloud.githubusercontent.com/assets/827445/9744070/2161e916-5640-11e5-93ec-7533c3f47c1e.png)

**Comment by Radagaisus** [comment]
@brunocoelho Thanks! Do you know of a way to silence it in Node.js? Our tests output are spammed with these warnings.

**Comment by jsilverMDX** [comment]
Fork the library, search the text. Disable the output. Then use your fork.
Is what I recommend.

**Comment by brunocoelho** [comment]
@Radagaisus I'm afraid not, I don't use Node.js that much.

@jsilverMDX And remembering to merge with the original one every time a new version is released? I don't think it's a good idea.

**Comment by pmolaro** [comment]
For what its worth, I was getting the same warning and was initially confused at why I was getting it. After reading through several of the comments here and some trial and error, this seems to work for me, and I no longer get the error.  So moving forward, is this the way moment intends for us to pass in dates?  It seemed more useful to have it handling that for users:

`return (moment(new Date(data)).isValid() ? moment(new Date(data)).format('MM/DD/YYYY h:mm A') : ' -- '); `

In the example above if I have a valid date, I format that, otherwise I return 2 dashes as a placeholder.  So "September, 22 2015 17:17:33 -0400"  gets converted to "09/22/2015 5:17 PM"

**Comment by cspotcode** [comment]
@pmolaro: Moment can do that, too.  You just need to [give it a format string](http://momentjs.com/docs/#/parsing/string-format/).  For example:

    var d = moment(data, 'MMMM Do YYYY, h:mm:ss a'); // don't forget your format string
    return (d.isValid() ? d.format('MM/DD/YYYY h:mm A') : ' -- ');

You can specify an array of formats, and moment will try them all.

**Comment by jetzhou** [comment]
For everyone following @cspotcode's workaround, note that the second argument should actually be `moment.ISO_8601`, ie

    moment("invalid-date", moment.ISO_8601).isValid()==false

relating to #2036

**Comment by auluckh23** [comment]
What if my date is in this format: "2015-10-06 00:00:00.0" and in my function I am doing this:

moment("2015-10-06 00:00:00.0").format("D MMM YYYY");

Is this fine or will it stop working?

**Comment by nitulkukadia** [comment]
@ichernev Could you please add the final conclusion, As comments in this issue is too long.

**Comment by adrianaguirre** [comment]
I'm sorry guys I'm having a hard time understanding. How can I modify this code so that I am compliant?

```javascript
var Benchmark = require('benchmark'),
    moment = require("./../moment.js"),
    base = moment('2013-05-25');

module.exports = {
  name: 'clone',
  onComplete: function(){console.log('done');},
  fn: function(){base.clone();},
  async: true
};
```

**Comment by warrendodsworth** [comment]
By using the default JavaScript Date constructor to construct your date object before sending it in to moment. So moment doesn't have to be responsible for parsing your Date string.

```
moment(new Date('2013-05-25'));
```

**Comment by ipsita93** [comment]
I get the same error as @imsobear. I am trying to convert from "9:00 AM" format to "00:00:00" format so I can store it as a TIME type in MySQL database. But how to do so?


Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Error
    at Function.createFromInputFallback (http://localhost:3000/javascripts/vendor/moment.js:746:36)
    at configFromString (http://localhost:3000/javascripts/vendor/moment.js:826:32)
    at configFromInput (http://localhost:3000/javascripts/vendor/moment.js:1353:13)
    at prepareConfig (http://localhost:3000/javascripts/vendor/moment.js:1340:13)
    at createFromConfig (http://localhost:3000/javascripts/vendor/moment.js:1307:44)
    at createLocalOrUTC (http://localhost:3000/javascripts/vendor/moment.js:1385:16)
    at local__createLocal (http://localhost:3000/javascripts/vendor/moment.js:1389:16)
    at utils_hooks__hooks (http://localhost:3000/javascripts/vendor/moment.js:16:29)
    at Object.$.validate.submitHandler (http://localhost:3000/javascripts/addstudentform.js:620:35)
    at d (http://localhost:3000/javascripts/vendor/jquery.validate.min.js:4:885)
addstudentform.js:621 Invalid date

**Comment by iamstarkov** [comment]
I started getting deprecation warning, but cannot see how I can use both locale and strictness without using this going-to-be-deprecated feature:

```js
moment('23 December 2015', 'DD MMMM YYYY', 'en', true).isValid();
```

@ichernev  what is the migration path for this feature?

**Comment by adambuczynski** [comment]
I seem to be getting this warning after feeding a string to moment() on the server, which was generated by the client through moment().toJSON(). It seems to me that at least the output from toJSON() should be compatible with the input for the moment constructor?

**Comment by mj1856** [comment]
@adambuczynski looks like url encoding.  Moment won't do that, must be coming from elsewhere.

**Comment by mj1856** [comment]
@iamstarkov - That code is fine and odes not produce the deprecation error, nor will it be removed.

**Comment by mj1856** [comment]
@ipsita93 
```javascript
moment("9:00 AM","h:mm a").format("HH:mm:ss");
```

**Comment by iamstarkov** [comment]
@mj1856 actually, its [producing error](https://travis-ci.org/iamstarkov/jsunderhood/builds/90392917#L973-L985), while im [using momentjs in `get-md-date`](https://github.com/iamstarkov/get-md-date/blob/master/index.js#L6) in exactly that way

**Comment by mj1856** [comment]
@warrendodsworth  - yuck - no, please avoid that.  The `Date` constructor will parse differently depending on implementation.  In most current browsers, `moment(new Date('2013-05-25'))` would produce the local equivalent of the UTC midnight of that date, similar to if you used `moment.utc('2013-05-25').local()`.

Just do `moment('2013-05-25')`, which is not deprecated.  Or, to be absolutely certain, use `moment('2013-05-25','YYYY-MM-DD')`, which will do the same thing.

**Comment by mj1856** [comment]
@adrianaguirre - Your code is already compliant, at least the code you showed here. `2013-05-25` is one of the recognized ISO 8601 formats.

**Comment by mj1856** [comment]
@auluckh23  - Yes, that is fine.  Fractional seconds are valid by ISO8601.

**Comment by mj1856** [comment]
@pmolaro, and all others trying to just remove the deprecation warning.  Yes, `moment(new Date(string))` will stop the deprecation warning, but then you are entirely missing the point.

The point is, parsing dates via the `Date` object is unreliable an inconsistent across platforms.  There are different implementations and different behaviors.  Sometimes you may get local time. Sometimes you may get UTC.  Sometimes you may get `Invalid Date`.  Sometimes you will get different results near DST transitions.

Don't try to defeat the error.  Instead, follow our guidelines.  Either use a known format or supply a format string.

The known formats are [the ISO8601 forms listed here](http://momentjs.com/docs/#/parsing/string/), and [the older ASP.NET JSON Date form shown here](http://momentjs.com/docs/#/parsing/asp-net-json-date/).  **Anything else needs a format string.**

**Comment by mj1856** [comment]
I've locked this thread.  If after reading this thread and looking at your code carefully you still don't understand, then [chat with me on Gitter](https://gitter.im/moment/moment).   There's nothing more to talk about here. Thanks.
