### ISSUE TITLE
Add usage instructions with webpack

### ISSUE THREAD

**Issue by fernandoacorreia** [moment/moment#1435]
Add to the section [Where to use it](http://momentjs.com/docs/#/use-it/) instructions for properly integrating Moment.js with [webpack](http://webpack.github.io/docs/).

`require('momentjs/moment.js')` causes several errors like this:

```
ERROR in ./app/bower_components/momentjs/lang/ar-ma.js
Module not found: Error: Cannot resolve module moment in /home/fernando/work/myproject/myproject-manage-app/app/bower_components/momentjs/lang
 @ ./app/bower_components/momentjs/lang/ar-ma.js 8:8-35

ERROR in ./app/bower_components/momentjs/lang/ar.js
Module not found: Error: Cannot resolve module moment in /home/fernando/work/myproject/myproject-manage-app/app/bower_components/momentjs/lang
 @ ./app/bower_components/momentjs/lang/ar.js 8:8-35
```

`require ('momentjs/min/moment-with-langs.js')` causes this warning:

```
WARNING in ./app/bower_components/momentjs/min/moment-with-langs.js
Module not found: Error: Cannot resolve file or directory ./lang in /home/fernando/work/myproject/myproject-manage-app/app/bower_components/momentjs/min
 @ ./app/bower_components/momentjs/min/moment-with-langs.js 808:24-46
```

**Comment by full-of-foo** [comment]
Bit late on this, but now one can use the provide plugin 
```
    plugins: [
        new webpack.ProvidePlugin({
           "window.moment": "moment"
        }),
        new BowerWebpackPlugin()
    ]
```

**Comment by kadishmal** [comment]
As @sokra suggested, I have added the following plugin in order to require only the necessary locale. Also notice that `lang` directory in `moment` has been changed to `locale`.

```javascript
plugins: [
	new webpack.ContextReplacementPlugin(/moment[\\\/]locale$/, /^\.\/(en|ko|ja|zh-cn)$/)
]
```

**Comment by electrobabe** [comment]
still getting:

**Comment by mj1856** [comment]
Added doc item as moment/momentjs.com#269

**Comment by grbush** [comment]
I'm using es6, typescript, and very tight tslint rules. This is what I ended up doing to get moment into the project:

import "expose?moment!imports?this=>window&exports=>false&define=>false!exports?window.moment!moment";

**Comment by neyer** [comment]
I just created an empty 'locale' folder in the same folder as 'moment.min.js', so that it includes all of the js files in that folder. 

It's a hack but it works.

**Comment by zdila** [comment]
To load languages in Webpack **dynamically** you can use with `bundle-loader`:

Step 1 - in webpack configuration:
```javascript
new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/), // to not to load all locales
```

Step 2 - in the client code:
```javascript
require('bundle!moment/locale/' + locale + '.js')(function () {
  moment().locale(locale).format('lll');
  // note that now you can use the locale even outside of this callback
});
```

**Comment by micheleb** [comment]
In my case (webpack + `npm install moment`) the issue was with webpack looking for locales inside the `src/lib/locale` folder, because that's where `moment.js` was being picked up.

I removed the `node_modules/moment/src` folder altogether, and import moment setting its locale using e.g.:

    import moment from 'moment';
    import 'moment/locale/en';
    moment.locale('en');

Everything works perfectly, no warnings, and only the locales I import explicitly are included in the build (even without using the `webpack.ContextReplacementPlugin` as explained in [this comment](https://github.com/moment/moment/issues/1435#issuecomment-187100876), which I added at first)

**Comment by Kovensky** [comment]
@micheleb the actual cause for looking in that subfolder is the incorrect setting of `jsnext:main` in momentjs's `package.json`, which is respected by webpack 2.

`jsnext:main` should _not_ point to the raw source code, but to a build of the module that does use ES6 module syntax.

This can be worked around by aliasing `'moment'` to `'moment/moment.js'` (the commonjs "main") in your webpack config (`resolve: { alias: { moment: 'moment/moment.js' } }`).

**Comment by leebenson** [comment]
was this fixed? if not, should it be re-opened?

**Comment by ajohnsonRH** [comment]
Why was this closed? This is still an occurring issue.

**Comment by butterflyhug** [comment]
@ajohnsonRH

["I believe that updating the documentation would resolve this issue."](https://github.com/moment/moment/issues/1435#issuecomment-35380948)

["Added doc item as moment/momentjs.com#269. Will track there."](https://github.com/moment/moment/issues/1435#issuecomment-188084288)

So, the issue was closed here because it's been superseded by an issue in Moment's documentation website.  We'd love for someone to write a PR there to resolve moment/momentjs.com#269.

**Comment by ajohnsonRH** [comment]
@butterflyhug 

This fix worked for me:
1. do the npm install
2. open vendor.ts and add the line `import 'moment'`

For reference:
Using Angular2 v2.0.0, Webpack ^1.13.0

**Comment by orditeck** [comment]
Is it possible to not includes all the locale without adding configurations to webpack? I'm using [create-react-app](https://github.com/facebookincubator/create-react-app) and I don't have the ability to edit the webpack config file. 

I search everywhere and it always seems to come back to adding a config line in webpack.
https://github.com/moment/moment/issues/2373
https://github.com/moment/moment/issues/2416

**Comment by vperron** [comment]
Agreed, I think requiring the locales should be explicit only, never implicit.

**Comment by trsh** [comment]
@ajohnsonRH 

I installed npm packs, but when I do 

import moment from 'moment-timezone';

moment is always undefined. How that?

**Comment by johnjameshopley** [comment]
I am having this same problem using Angular 2 CLI project. Has anyone found a working solution yet?

**Comment by FlawaCLV** [comment]
Any clues for Angular CLI ?

**Comment by Lakston** [comment]
As you can see I asked 4 months ago about the CLI and no answers, our solution was to simply replace moment with date-fns, and since we are also using chartjs in our project and it has a moment dependency we are in the process of replacing that too.

**Comment by plandem** [comment]
quite nice solution
https://github.com/moment/momentjs.com/pull/489

**Comment by dwilches** [comment]
How can this be solved for Angular CLI without ejecting the Webpack config?
