### ISSUE TITLE
Add option to default to highest possible date

### ISSUE THREAD

**Issue by treet** [moment/moment#1452]
When parsing incomplete dates such as '2014' or '2014-05' moment will always default to the lowest possible date, so '2014' becomes 2014-01-01 00:00 etc. Would it be sensible to add an option to instead default it to the highest possible value? So that '2014' becomes '2014-12-13 23:59:59' and '2014-06' becomes '2014-06-30 23:59:59' etc.

One use case I have in mind in mind is when you have deadlines in various date formats and of various completeness, and you want to order them by earliest deadline first. In this case if when someone says deadline 'May, 2014' it probably makes more sense (at least for sorting) to interpret it as 2014-05-31 instead of as 2014-05-01.

Perhaps this is outside the scope of momentjs though, just an idea.

**Comment by maggiepint** [comment]
Closing because of age. If it's still important, feel free to reopen the issue.

**Comment by jeffg2k** [comment]
I just worked around it in my code by comparing what moment gives me against some regex expressions to see if I'm really only looking at a year.  It's hackish.  It would be better to have the option in moment not to guess a month day.  If it is given a year, then just give a year back leaving day / month null.

**Comment by maggiepint** [comment]
@jeffg2k , I think pull request #3045 could largely clean up what you have going on. It exposes an array of date parts that were actually parsed by the parser, so you can differentiate those from the ones that were defaulted. You could conceivably use that to explicitly set parsed date parts using 'endOf'. That's staged for release in 2.13 whenever we decide to get to it.
