### ISSUE TITLE
Add a strip function to remove non-critical moment properties

### ISSUE THREAD

**Issue by ichernev** [moment/moment#1455]
We've been adding properties to the moment object here and there and now most of them are used only at the parsing stage, revealing information about what exactly got parsed and how, but most users don't care and if you happen to have a big array of objects this also leads to higher memory footprint.

So lets add a function `moment.fn.strip()`, that would remove all unnecessary properties,  and keep only: `_isAMomentObject`, `_isUTC`, `_l`, `_d`. `_offset`.

**Comment by maggiepint** [comment]
So, two years later now, I think there is quite a bit of code that relies on parsing flags and other variables being the way they are, and this change doesn't make sense. As such, I'm going to close this for the sake of cleaning house on issues. I'll assign a v3 milestone in case we want to find it down the road when considering total rewrite style scenarios.
