### ISSUE TITLE
Sort Comparison Function

### ISSUE THREAD

**Issue by schinckel** [moment/moment#1493]
When sorting a list of moment objects (or objects that have an attribute that is a moment, and should be the sort key), it would be great if there was a comparison function included. So that we could do things like:

```
array.sort(m.compare)
```

**Comment by robertmassaioli** [comment]
With typescript, this is not as simple. The typings don't allow you to say `a - b`.

Instead, I just say something like:

    a.isBefore(b) ? -1 : 1

Not sure if I got that 1 and -1 the right way around.

**Comment by libinvarghese** [comment]
> With typescript, this is not as simple. The typings don't allow you to say a - b.

You can explicitly call the moment#valueOf as `a.valueOf() - b.valueOf()`

**Comment by miso440** [comment]
I'm partial to:

```js
momentsArray.sort((a, b) => a.diff(b));
```

myself.

**Comment by WORMSS** [comment]
@robertmassaioli be careful with your code, 
```
a.isBefore(b) ? -1 : 1
```
if a is the same, it would swap them, rather than keep them in place. I know it doesn't sound like much but it could be unexpected for some.
