### ISSUE TITLE
zh language file missing

### ISSUE THREAD

**Issue by gdibble** [moment/moment#1494]
setting language to "Chinese [zh]" in firefox throws a ENOENT error in node when zh tries to require. 

as far as i can tell, zn-ch == zn. (ref @ http://en.wikipedia.org/wiki/Wikipedia_talk:Chinese_interlanguage_links)

solution is to simply copy the zh-cn.js --> zh.js 
(thus resulting in lang. being required and no server error.)

---

![image](https://f.cloud.github.com/assets/906846/2252918/4c5eeef4-9db2-11e3-9c67-a44c0f363d0a.png)

**Comment by alongoles** [comment]
Why is this closed?
The 'zh' file should be available in the moment-with-locales.js and it should be the fallback for "zh-XX".
