### ISSUE TITLE
Add flag to isAfter and isBefore to be inclusive

### ISSUE THREAD

**Issue by rbriank** [moment/moment#1512]
date1.isAfter(date2, {inclusive: true}) returns true if date1 == date2.

Removes the need to do something like:

date1.isSame(date2) || date1.isAfter(date2)

**Comment by sylvainpolletvillard** [comment]
the easiest way to do that is : 
date1.isSameOrAfter(date2) <==> !date1.isBefore(date2)

**Comment by adamreisnz** [comment]
For people googling... 

https://momentjs.com/docs/#/query/is-same-or-after/
https://momentjs.com/docs/#/query/is-same-or-before/
