### ISSUE TITLE
introduce isOnOrAfter, and isOnOrBefore

### ISSUE THREAD

**Issue by rbriank** [moment/moment#1513]
These are inclusive versions of isAfter, and isBefore to avoid having to use 2 checks to determine if a date is on the boundary of your range.

**Comment by adamreisnz** [comment]
It's worth noting that they eventually buckled and implemented this in the form of [`isSameOrAfter`](https://momentjs.com/docs/#/query/is-same-or-after/) and [`isSameOrBefore`](https://momentjs.com/docs/#/query/is-same-or-before/) 😉

**Comment by rbriank** [comment]
Hahaha. Cheers.
