### ISSUE TITLE
Deprecate then eliminate max/min

### ISSUE THREAD

**Issue by icambron** [moment/moment#1548]
moment().min and moment().max were a good idea for helper functions, but combined with the mutability that most moment() methods have it turned out disasterously confusing.

So we're deprecating those two in favor of `moment.min` and `moment.max`, which are non-mutating and work on any number of objects:

``` javascript
// if a, b, c, d are moments ordered in time
moment.min(a, b);  // a
moment.min(a, b, c, d);  // a 
moment.min([a, b, c, d]);  // a
moment.max(a, b);  // b
moment.max(a, b, c, d);  // d
moment.max([a, b, c, d]);  // d
```

**Comment by ypresto** [comment]
`moment().min(start).max(end)` was useful for clamping.
How about adding `moment().clamp(start, end)`?

**Comment by icambron** [comment]
That seems easy enough to add from userspace. Untested, but:

```js
moment.fn.clamp = function(start, end){
   return moment.max(start, moment.min(end, moment());
}
```

Since I suspect this is relatively rare use case and it's easy to do from userspace, I'd prefer to keep out of the lib in the name of limiting the surface area.
