### ISSUE TITLE
30 of March 2014 returns a very weird result

### ISSUE THREAD

**Issue by tsouloftas** [moment/moment#1568]
Unfortunately for very mistaken reason we're using Moment.js for our companies' calendar and I came up with this date being strangely wrong and messing up with our entire schedule for the wrong date:

30 March 2014.

This: moment("2014/03/30").format("DD") 
returns: 29

This issue is only on Chrome 33 as far as I am aware of. The bug does not happens on Firefox.

**Comment by dmitryguesty** [comment]
Same issue is still relevant
