### ISSUE TITLE
Content missing from cdnjs?

### ISSUE THREAD

**Issue by dcormier-work** [moment/moment#1600]
There's a [note](http://momentjs.com/docs/#/use-it/browser/) for using Moment in a browser that states:

> Moment.js is available on [cdnjs.com](http://cdnjs.com/). Remember though, cool kids concatenate their scripts to minimize http requests.

There's another a [note in the i18n docs for loading languages into a browser](http://momentjs.com/docs/#/i18n/loading-into-browser/) that states:

> **Note:** the files in the `/lang/` folder are optimized for use in Node.js. If you want to use language files in the browser, use the minified version that are included in `/min/lang/`.

However, `/min/lang/` is not included on cdnjs; only `/lang/`. Here's a [direct link](http://cdnjs.com/libraries/moment.js/) to the cdnjs listing for Moment so you can see for yourself.

Should browsers be using `/lang/` or `/min/lang/`? If the docs referencing the latter are correct, can this please be added to cdnjs?

**Comment by marwahaha** [comment]
The new intent of this ticket should be:

> Enhancement: Add minified language files to cdnjs.

**Comment by marwahaha** [comment]
We don't ship individually minified versions of our locale files. We could, but you can also make them yourself with the grunt transpiler ([and the docs show how](http://momentjs.com/docs/#/i18n/loading-into-browser/). 

Please re-open if people still really want this.
