### ISSUE TITLE
Does moment().day(-5) become last 'Friday' or does it simply subtract 5 days?

### ISSUE THREAD

**Issue by ghost** [moment/moment#1613]
Hi...

In the docs: http://momentjs.com/docs/#/get-set/day/

Say it's Monday 14 April 2014, I understand the docs as indicating that if you do this:

moment().day(-5)

You'll get last Friday 11 April 2014.

But in the code:

https://github.com/moment/moment/blob/2.5.1/moment.js#L1940

day() is returning: this.add({ d : input - day })

With a day = 1 (Monday) and input of -5, moment().day(-5) returns Tues 08 April 2014, i.e. -6 days from the current Monday.

Should moment().day(-5) give you 'Last Friday' or should it give you 'Last Tues'?

Am I simply misunderstanding the docs?

**Comment by vutranHS** [comment]
u
