### ISSUE TITLE
Unable to find timezone abbreviation from Date.prototype.toString()

### ISSUE THREAD

**Issue by ghost** [moment/moment#162]
Hello I came across the moment.js site via a forum and clicked my way through it, when I came across the unit test - which failed 2 tests what I want to report here:

UserAgent:
**Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.7 (KHTML, like Gecko) Chrome/16.0.912.77 Safari/535.7** (Chrome 16.0.912.77 m)

Timezone:
**UTC+1**

Failed tests (# 28):
**http://pastebin.com/bQsDuxdH**

*Title edited by timrwood

**Comment by chris-martin** [comment]
So, asking just to make sure I understand: There is no replacement for the deprecated 'z' format?

**Comment by mrhwick** [comment]
If I have a timestamp in the ISO-8601 format, such as:

    2014-07-25T18:00:00-04:00

And I want to display this timestamp as the following:

    6:00 PM EST

Does moment no longer support this formatting? All of the timezone data is included in my timestamp, and I only want to display it directly without transforming the timezone in any way.

**Comment by DeadMG** [comment]
That does not actually include the timezone. There can be several timezone names that correspond to the same UTC offset, especially when considering the possibilities of varying DST. You cannot infer from "UTC-4:00" that the timezone is EST.

**Comment by mj1856** [comment]
For clarification, the `z` formatter still works when using [moment-timezone](http://momentjs.com/timezone) with a specific zone - since the abbreviation can be pulled from the time zone data.

**Comment by themakshter** [comment]
Just mentioning this now - if you use 
`new Date().toTimeString()`
you get the same result across all browsers as far as I have tried.

**Comment by Shobana16** [comment]
Hi I see above that format('z') is deprecated. also in moment docs, i see it is been deprecated from 1.6.0. I am using 2.11.0 now, i can use the 'z' to display timezone (PST/PDT) based on offset. 
Should i not to use this 'z' in my code now? can you please tell exact alternative to display PST instead of -/+8

**Comment by mj1856** [comment]
@themakshter - no, you do not get the same result across all browsers.  OS, browser version, and language play into it heavily - and there is no consistency requirement in the spec.

**Comment by mj1856** [comment]
@Shobana16 - If you just do `moment().format('z')`, it will always return `""`.

If you're using moment-timezone, and do something like `moment.tz('America/Los_Angeles').format('z')`, then you will get a valid response.

`z` is fine with moment-timezone.  It does nothing on a plain moment.

**Comment by Shobana16** [comment]
Thank you for the comments MJ. Yeah i am using 'z' with moment-timezone only. Ok cool will remain my code with 'z'. !

**Comment by mj1856** [comment]
Just a note to add, as of moment-timezone 0.5.0, you can *guess* at the local time zone, which opens the door for:

```javascript
var abbreviation = moment.tz(moment.tz.guess()).format('z');
```

This is ok, but be aware that:
1. It's just a guess.  It might guess wrong.
2. If it does guess wrong, there's still a possibility that the abbreviation could be correct, as many similar time zones will use the same abbreviations, such as how `Europe/Paris` and `Europe/Berlin` both use `CET` and `CEST`.
3. However, there's no guarantees.  If it guesses wrong, you might present the wrong abbreviation.

We might also consider adapting moment.js such that if moment-timezone is available that it could try to do this automatically to re-enable the `z` formatter.  Though this is not happening currently.

**Comment by ryancwalsh** [comment]
`var abbreviation = moment.tz(moment.tz.guess()).format('zz');` doesn't seem to work (with two `z`s). Am I only able to retrieve "EDT" and not "Eastern Daylight Time"?

Thanks!

**Comment by ryancwalsh** [comment]
Ahhh, I found that http://momentjs.com/timezone/docs/#/using-timezones/formatting/ says: To provide long form names, you can override `moment.fn.zoneName` and use the `zz` token.
`[and much more...]`
Thanks.

**Comment by jeserkin** [comment]
One thing is confusing though. In current version (or as it is stated "as of **1.6.0**") there is no way to show timezone without using separate moment-timezone. But when I do `moment(...).toString()` it shows for example `GMT` in the end. So is it a bug, or one solution contradicts another functionality?

**Comment by StevenDufresne** [comment]
> One thing is confusing though. In current version (or as it is stated "as of **1.6.0**") there is no way to show timezone without using separate moment-timezone. But when I do `moment(...).toString()` it shows for example `GMT` in the end. So is it a bug, or one solution contradicts another functionality?

I think the problem is reliability. Moment can't reliably extract the correct timezone from the local date object so it no longer supports `z/zz` in its formatting. 

Discussed above: 
https://github.com/moment/moment/issues/162#issuecomment-4060027

**Comment by arvi** [comment]
This is what worked for us to get the "GMT" text since `z` has been deprecated

```js
const dateGenerated = moment("2020-05-20 08:15:25");
const localDateGenerated = dateGenerated.local().format('DD MMM YYYY hh:mm A') + ' ' + String(dateGenerated.local()._d).split(' ')[5];
```

It will generate `20 May 2020 08:15 AM GMT+0300"`

**Comment by SENPAY98K** [comment]
How do i add +1 to hours ??

Iam using this: `var time = moment().format('yyyy-MM-DD, HH:mm');`
The output i.e: `2021-06-07, 23:02`

but i want to add +1 to hours to match my local time
ie: `2021-06-07, 00:02`

**Comment by alexbu92** [comment]
> How do i add +1 to hours ??
> 
> Iam using this: `var time = moment().format('yyyy-MM-DD, HH:mm');`
> The output i.e: `2021-06-07, 23:02`
> 
> but i want to add +1 to hours to match my local time
> ie: `2021-06-07, 00:02`

This has nothing to do with the timezone display format. You need to use local() as in moment().local().format('');

**Comment by SENPAY98K** [comment]
well it does not work in my code at all, i use loop for many accounts, so the muldule only print the first time and keep repeating it no update.

**Comment by cristearazvanh** [comment]
I confirm that `moment.tz("Europe/Bucharest").format('z')` work very well with moment 2.29.4 and timezone 0.5.37

**Comment by matthewbordas** [comment]
Using:
```json
"moment": "^2.29.4",
"moment-timezone": "^0.5.43"
```

This works:
```js
const timezone = "America/New_York";
const timezoneAbbreviation = moment.tz(timezone).zoneAbbr();
const formattedDate = moment(date, timezone).format('...') + timezoneAbbreviation;
```
