### ISSUE TITLE
fromNow() returns the wrong number of years

### ISSUE THREAD

**Issue by aepton** [moment/moment#1620]
Until this is fixed, fromNow() should be considered broken and unreliable. It should certainly not be so prominent on the front page of momentjs.com, given that it is guaranteed to return incorrect results.

There's a stackoverflow thread documenting the bug: http://stackoverflow.com/questions/14057497/moment-js-how-do-i-get-the-number-of-years-since-a-date-not-rounded-up

But here's a quick demonstration of it:

moment().format();
"2014-04-23T10:49:03-05:00"  // So we know what "now" is

moment('11-30-1983', 'MM-DD-YYYY').fromNow();
"30 years ago"  // This is correct

moment('10-30-1983', 'MM-DD-YYYY').fromNow();
"31 years ago"  // This is incorrect, and very dangerous behavior for a date-manipulation library

**Comment by papaDrakon** [comment]
Hi!
Still have same problem)
moment().to(moment('02.04.1984', 'DD.MM.YYYY'), true) = 36 years

**Comment by jarizast** [comment]
I believe this function (from/fromNow) work like this:
 < 1 Mo, will show X Days
 >= 1 Mo and < 1 year, will show X months
 >= 1 year and <= 1year 6mo = 1y
 >= 1.5 year  and <= 2.5 yr = 2y
 etc..
![image](https://user-images.githubusercontent.com/34106843/212969581-fa83f95c-da67-429c-b833-d1444fa9ecf7.png)

**Comment by jarizast** [comment]
It looks like the total year difference are greater 30.5 years and that why returns 31, as you see in the documentation example:
See also than a month ago is less than 45 days, and a year ago start at 10+ months (320 days)
![image](https://user-images.githubusercontent.com/34106843/212988994-8a08688e-8bb3-4b38-843d-6f230f4b38a3.png)
