### ISSUE TITLE
Accept singular object in setter

### ISSUE THREAD

**Issue by jeron-diovis** [moment/moment#1623]
It would be very convenient to pass single units hash to 'set' method, same as with add/subtract:
```JavaScript
moment().set({'hour': 1, 'minute': 1})
```

Is it possible to implement?

**Comment by johnmcase** [comment]
The [online documentation](http://momentjs.com/docs/#/get-set/set/) clearly states that this is a valid usage of set, but it does not look like this is implemented.  Has a PR been submitted for this?

**Comment by maggiepint** [comment]
Implemented long ago.
