### ISSUE TITLE
moment(undefined).isValid() return true?

### ISSUE THREAD

**Issue by alexhornbake** [moment/moment#1639]
I realize this may be intentional/philosophical issue, but since it is a Date() wrapper, I expected an undefined Date to be invalid. Happy to make a pull request if maintainers agree?

> moment(undefined).isValid()
> true
> 
> new Date(undefined)
> Invalid Date

**Comment by MiguelMadero** [comment]
`arguments.length === 0` means no argument, undefined means undefined. 

This would likely introduce a big regression, but I think it would've been more intuitive for consumers if `moment` checked the arity instead of the value.

**Comment by vproman** [comment]
On one hand, this can be a huge problem when passing in variables which are uninitialized.

On the other hand, it sounds like moment is simply providing a default value in the case where an input argument is not defined, akin to `input = input || new Date();` though in the actual source it's done differently.

The lesson I'm learning is that you should initialize your variables with a default value, otherwise other libraries are going to provide a default value for you.

**Comment by rapilabs** [comment]
Yep I have to disagree with you @ichernev this has cause some annoying bugs for me.  Libraries should be written defensively; if someone passes an argument that was assumed to be defined but was undefined then that should be communicated back to the dev to alert the presence of a bug.

@MiguelMadero's method is the correct way of detecting no arguments.

It shouldn't be up to the user to define default values... it's counter-intuitive for a library to silently progress with incorrect values if invalid input is passed.  It's also inconsistent with the way `null` is dealt with.  Additionally there are more checks & noise I now have to put in my code.

**Comment by kohenkatz** [comment]
I see both sides here, and I don't think a change needs to be made.  *However,* it would be very nice if this behavior was documented somewhere.

**Comment by leothorp** [comment]
Wanted to also chime in that this is counter-intuitive; a single argument with a value of 'undefined' is not synonymous with 'no arguments'.

**Comment by brian-kilpatrick** [comment]
Definitely should at least be documented if not changed....

**Comment by just2evil** [comment]
This would have to be worst piece of programming and this is no logically argument to treat an undefined value not entered. This needs to be fixed and should be fixed.

var date = undefined;
moment(date).isValid() //returns true
moment(data.assignedRole.startDate, "L").isValid() //returns false.

Both of the above should return the same value of false. Any one trying to do isValid() on date make sure you format the date. That is the only way to correct check if date is valid.

**Comment by slaughtr** [comment]
This is STILL a thing, and STILL is not in the documentation. This just about double screwed me, because not only does `moment(undefined).isValid()` evaluate to true, but `moment(undefined).isAfter(moment().format())` also returns true. Thankfully I was testing something only tangentially related and caught it.

**Comment by iursevla** [comment]
And its still there all this years later...

**Comment by jay-jlm** [comment]
Love this lib but I guess someone did not do their home work on this one. 
Cf.  https://en.wikipedia.org/wiki/Principle_of_least_astonishment

This was my in-a-hurry solution:

```
  const safeUndef = v => (v === undefined ? null : v);

  const disableButtons = !moment(
    safeUndef(serverResponse.paymentConfirmationDate)
  ).isValid();
```

**Comment by vuki656** [comment]
How is this still not fixed? 


> Javascript... undefined means no argument. No arguments means now. Now is valid.


Definitely moving away from Moment. Too many of these little inconsistencies.

**Comment by jay-jlm** [comment]
@vuki656 , maybe this could help:  https://www.npmjs.com/package/patch-package
But yeah, unless you depend on it for legacy projects or something Date-fns is highly recommended.

**Comment by vuki656** [comment]
> @vuki656 , maybe this could help: https://www.npmjs.com/package/patch-package
> But yeah, unless you depend on Moment for legacy projects or something Date-fns is highly recommended.

It would definitely be an option but I think patch package is more suitable for something that you don't want to wait until its fixed.

This issue was open 6 years ago and they probably won't fix it. So Date-fns it is.

But thanks for the suggestion.

**Comment by adt-hgkim** [comment]
```js
moment(someString || null).isValid()
```
