### ISSUE TITLE
Proposal for new parsing api

### ISSUE THREAD

**Issue by ichernev** [moment/moment#1686]
Currently `moment`s can only be created through one overloaded function to support all input methods (string, string + format, object, formats). When a format (or a list of formats) is present the situation is simple, but we need different functions for the single-string-argument case.

So lets add a few more methods for the particular use cases:

``` javascript
// assume strict -- well we don't have the official ISO document
// but we should be as strict as possible here
moment.fromIso(input);

// will try to parse with loose iso or
// http://tools.ietf.org/html/rfc2822#page-14
moment.parse(input, [lang]);

// same as parse, but will try Date constructor at the end
moment.fromAny(input);  
```

About `parse` -- we need a function that is dependable (stable across browsers) but also handles more user-friendly formats. I only found the rfc2822 link in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse), but browsers parse a whole lot more than that -- we need to read some browser code and fetch a few formats that make sense. Not sure about localized versions -- we can try to parse `L{1,4}` presets of the selected language.

I guess for backwards compatibility we can assume `fromAny`, and urge users to use the more descriptive format so there is less shooting in the foot. Not sure how the lang/strict arguments will play with the absence of a format.

---
### For extra credit

Also it makes sense to add those two special forms of parsing (iso, moment-human-formats (for parse), and Date constructor), and let the user select them as formats in the format case (#1680 explains this well).

``` javascript
moment("2014-02-24", moment.formats.ISO)
moment("2014-02-24", moment.formats.INTERNAL)
moment("2014-02-24", moment.formats.JS_DATE)
```

Of course this can be made extensible, so others can add formats that are not mere tokens, but list of formats or even code.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
