### ISSUE TITLE
moment.duration("P30D").toIsoString() == "P1M"

### ISSUE THREAD

**Issue by eldavido** [moment/moment#1697]
In general, ISO durations of months and days aren't comparable due to the varying number of days in a month.

The culprit is the _bubble() function, which gets called on duration construction. Can anyone explain the rationale for why 30-day periods always get bubbled into a month? Is there some piece of the library or use case that depends on this?

**Comment by NobodysNightmare** [comment]
I already wrote in another issue (https://github.com/moment/moment/issues/2162), but I think this might also be apropriate.

> What if you have `moment.duration("PT30H")` should this give `P30H` back or `P1DT6H`? Currently it gives `P1DT6H`, but I'm not sure if we should safely bubble (without crossing month boundaries) at all.

To my understanding you should return `PT30H`, because you can't safely bubble from hours to days in edge-cases (clock change). Otherwise this works *most of the time™*

**Comment by ichernev** [comment]
@NobodysNightmare I know it has been forever, but the current duration keeps 3 quantities: milliseconds, days and months. The reason is that one can not bubble to the other (for obvious reasons). So we could add a flag to toISOString (or a separate method), that does not bubble MS -> D -> M and we'll be good.

**Comment by eldavido** [comment]
Hi after 3 years...

My thinking on this has changed. I think days should never bubble to months. As you said, it's indeterminate how to do it and confusing. If someone wants to implement their own version of this, go ahead and let them; there are simply too many things to worry about, including which month it is, leap years, etc. to implement this in a general way.

Accountants have the highly Procrustean (https://en.wikipedia.org/wiki/Procrustes) convention of assuming a year is twelve equal months of thirty days. That's one way of handling it...please don't do this.

**Comment by marwahaha** [comment]
This is no longer the case (tested in 2.22.0)
```
> moment.duration("P30D").toISOString()
"P30D"
```

Please re-open if there are still issues.
