### ISSUE TITLE
Duration format meta-overview

### ISSUE THREAD

**Issue by ichernev** [moment/moment#1698]
Duration format has been requested multiple times.

#1436, #1048 https://github.com/jsmreese/moment-duration-format #892 #463 

The main problem is localization. Almost any hack/api can be made to work on English, but proper translation can be impossible (even cldr doesn't provide joining information -- how do you concatenate 2 hours and 5 minutes for example).

On the other hand something that just lets you format (without locale) should be fairly straight forward (check this https://github.com/moment/moment/issues/1048#issuecomment-24492305).

The plugin listed above seems to do that, it has some weird issues and not a whole lot of stars/forks, so I'm not sure if its worth reimplementing/merging into moment. We might make it an official plugin (like timezone), because as #463 there are a lot of `+1` for it.

@icambron @Oire what do you think?

**Comment by maggiepint** [comment]
I don't think this needs to exist along with #1048 - we really had three issues open for the same thing. Closing unless someone really wants to reopen it.
