### ISSUE TITLE
date/day inconsistent between constructor and getter

### ISSUE THREAD

**Issue by bblack** [moment/moment#1705]
```
var m = moment({
  year: 2063,
  month: 3,
  day: 4
});
```
`m.year()` returns what was passed in the `year` key.
`m.month()` returns what was passed in the `month` key.
`m.day()` returns the day of week. `m.date()` returns what was passed in the `day` key.

If an upcoming version is okay with introducing breaking changes, I would suggest changing date/day so that the getters correspond to the constructor keys.

**Comment by maggiepint** [comment]
Closing as duplicate of #1753
