### ISSUE TITLE
Duration missing toJSON feature

### ISSUE THREAD

**Issue by lfnavess** [moment/moment#1714]
Hi, i detected that the moment object don't implement the standar to JSON function

http://en.wikipedia.org/wiki/ISO_8601#Durations

in this link stated that it should return a iso8601 format `PnYnMnDTnHnMnS`
https://google-styleguide.googlecode.com/svn/trunk/jsoncstyleguide.xml#Time_Duration_Property_Values

so for example:
```js
var aaa = [1,"some string", moment.duration(123,'m')];
JSON.stringify(aaa);
//"[1,"some string",{"_milliseconds":7380000,"_days":0,"_months":0,"_data":{"milliseconds":0,"seconds":0,"minutes":3,"hours":2,"days":0,"months":0,"years":0}}]"
```

it could be corrected like this

```js
moment.duration.fn.toJSON = function(){ return this.toIsoString();}
JSON.stringify(aaa);
//"[1,"some string","PT2H3M"]"
```

**Comment by jstnlef** [comment]
Looks like this Issue is closed since #1825 was merged.
