### ISSUE TITLE
Support for HTTP Dates (RFC 2616) ?

### ISSUE THREAD

**Issue by blackcoat** [moment/moment#1722]
Issue #1407 mentions that non-ISO dates are deprecated, but what about other ubiquitous date formats defined by standards? [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.3)—which defines the date format used in HTTP headers—does not appear to be supported by Moment at this time. Is support for this format on the roadmap?

**Comment by mj1856** [comment]
We'll track this in #2530.   (RFC 822, 2616, 2822 and several others are all pretty much the same.)

**Comment by FaeezBorman** [comment]
Still getting a deprecation warning for RFC2616 on moment 2.18.1
