### ISSUE TITLE
Arabic (ar) relative time not using correct plurals?

### ISSUE THREAD

**Issue by josidhe** [moment/moment#1724]
We've been getting feedback from a small number of Arabic-speaking end-users that relative time display isn't being written appropriately for some integers. I looked at the library, and the 'ar' logic doesn't include CLDR-style plural tests to support the different ways relative time might be written for different numbers.

The Russian relative time does this, though I don't think it can be easily adapted to how Arabic would work. Russian always assumes an integer will be in the returned string, which isn't the case for Arabic (I'm told sometimes it's just words).

For contributors to the Arabic support here, do you have any thoughts on this feedback? We're right on the edge of this being called a bug in our system, but I'm sure this must've crossed someone else's mind here at least once in the past. If there's a reason why Arabic uses simple =1/other plurals here, it'd be helpful info to have.

Thanks!

**Comment by Oire** [comment]
@forabi, any feedback please?

**Comment by forabi** [comment]
Actually I myself implemented the correct CLDR-compliant pluralization function for Arabic.
You can verify that it is being used here https://github.com/moment/moment/blob/develop/locale/ar.js#L38
But I only did this for the generic Arabic locale, your users might be using other variants like [ar-tn](https://github.com/moment/moment/blob/develop/locale/ar-tn.js), [ar-sa](https://github.com/moment/moment/blob/develop/locale/ar-sa.js) or [ar-ma](https://github.com/moment/moment/blob/develop/locale/ar-ma.js) which I did not touch.

**Comment by Oire** [comment]
@forabi, thanks! So can we consider this issue as fixed?

**Comment by forabi** [comment]
I checked the demo page with Arabic and everything looks good to me. The
tests are good too.

**Comment by Oire** [comment]
Fixed.
