### ISSUE TITLE
Array of formats parsing order.

### ISSUE THREAD

**Issue by eddielee6** [moment/moment#1746]
The documentation for parsing a date with an array of formats states...

> Starting in 2.3.0, Moment uses some simple heuristics to determine which format to use. In order:
> - Prefer formats resulting in valid dates over invalid ones.
> - Prefer formats that parse more of the string than less and use more of the format more of the format than less, i.e. prefer stricter parsing.

So I would expect the following to return "05/05/2045" as the first format does not match the input, but the second one does.
`moment("05/05/45", ["DD/MM/YYYY", "DD/MM/YY"]).format("DD/MM/YYYY")`

However the date is incorrectly parsed as "05/05/0045".

**Comment by ichernev** [comment]
This works in 2.20.1 (and possibly much earlier) ;-)
