### ISSUE TITLE
i18n - Vietnamese language (vi) with format() method

### ISSUE THREAD

**Issue by theking-laptop** [moment/moment#1747]
I wrote the code:
```
moment().lang('vi').format("dddd, MMMM Do YYYY, h:mm:ss a");
>> "thứ hai, tháng 6 30 2014, 11:27:58 pm"
```
It's correct, but in Vietnamese, when display a date, first letter of the day of week at the beginning should be capitalized, like this:
```
>> "Thứ hai, tháng 6 30 2014, 11:27:58 pm"
```
I think it's better.

**Comment by Oire** [comment]
Closed via #2889. Friends from Vietnam, sorry for such a huge delay :(.
