### ISSUE TITLE
Should be an option to return local times from toISOString

### ISSUE THREAD

**Issue by icambron** [moment/moment#1751]
`toISOString` always returns UTC times. We should support a flag that lets you return the local time instead of requiring the user to do:

``` js
moment().format('YYYY-MM-DD[T]HH:mm:ss.SSSZ');
```

**Comment by marwahaha** [comment]
This was done in 2.20.0:
```
moment().toISOString(true)
```
https://momentjs.com/docs/#/displaying/as-iso-string/

**Comment by Haider8** [comment]
> This was done in 2.20.0:
> 
> ```
> moment().toISOString(true)
> ```
> https://momentjs.com/docs/#/displaying/as-iso-string/

I am doing this but still not able to get local time. Can somebody help me please :)

Doing this:
```
moment().subtract(1, 'Y').toISOString(true)
```

**Comment by pironim** [comment]
moment().toISOString(true) not working as expected for 2.7.0 . not sure about latest version but flag does not help.
