### ISSUE TITLE
Moment unparsable date

### ISSUE THREAD

**Issue by geaden** [moment/moment#1756]
We use moment on server side. Sometimes (actually when services called in parallel) we get 3 types of errors:

``` javascript
TypeError: Cannot find function call in object -. (moment.min.js#5)
```

``` javascript
Unable to parse '2015-0902' using format 'yyyy-MM-dd' message Unparseable date: "2015-0902"
```

``` javascript
 'org.mozilla.javascript.EvaluatorException: Unable to parse '2013-05
function (c) {
    return l(a.call(this, c), b);
}
' using format 'yyyy-MM-dd' message Unparseable date: "2013-05
function (c) {
    return l(a.call(this, c), b);
}
"'
```

Is it a problem with mozilla javascript evaluator?

Thanks.

**Comment by andrejpiatnica** [comment]
I have the exact problem (rhino/moment.js) - looks like momentjs has a problem in multi-threaded environment. @geaden, did you find any solution for that? 

Moment is a great library, I would like to stick with this one as it is very easy to use (in comparison to other Java Date utils which I can use in Rhino)

Thanks!

**Comment by geaden** [comment]
@andrejpiatnica, unfortunately not. I just created wrapper for Joda time. It solved the issue. Calling moment from node.js simultaneously didn't produce any errors.

**Comment by wadahiro** [comment]
@andrej800 @geaden I encountered the same problem. After some investigation, I found that a variable is shared in multiple threads. Please refer to my pull request (#3109) for more information if you are interested.

**Comment by ichernev** [comment]
Well, it's not thread safe. Rhino is probably the only framework letting you run js multithreaded. So I'd be surprised to find a thread safe lib not designed for rhino. Not to mention the beauty of js comes from message passing / event loops, not mutexes and other thread crap.

**Comment by wadahiro** [comment]
>Rhino is probably the only framework letting you run js multithreaded.

@ichernev Nashorn which is default javascript engine in latest JDK is too. Developers must be careful if they want to run scripts in multi threads. There is [a good article](https://blogs.oracle.com/nashorn/entry/nashorn_multi_threading_and_mt) about Nashorn multi threading.

By the way, could you accept my pull request (#3109) ?
I think this patch helps who want to run Moment on server-side Java.

**Comment by wadahiro** [comment]
Thank you for your acceptance!

**Comment by icambron** [comment]
I think making sure vars are appropriately scoped is good on its own, but I'll echo @ichernev in saying that Moment makes no attempt to be threadsafe overall. We don't do much global state wackiness, but in you should generally not expect an individual Moment object to work when shared across threads; almost none of the mutators make any attempt to update atomically. You'll find no stronger proponent of immutability than me, but thread safety is one of the few traditional arguments for it that I have *not* been deploying. Thread safety, as far as I know, just isn't a design goal.

In practice, if you don't share Moment objects across threads or muck with what little global state there is, you'll probably be fine.

**Comment by maggiepint** [comment]
@icambron @ichernev perhaps we should explicitly state in the docs about Rhino (http://momentjs.com/docs/#/use-it/other/) that we make no guarantees that it's thread safe.
