### ISSUE TITLE
Replace fallback deprecation link with an FAQ

### ISSUE THREAD

**Issue by icambron** [moment/moment#1773]
Using #1407 is maybe not the best way to handle this. I'm going to write up an FAQ that explains why the change is happening and what end-users should do about it. I'll then just replace the link in the code. Doesn't matter too much if we don't do another pre-3.0 release, but I'm guessing we will in order to have some of the other deprecations in the wild for a bit.

**Comment by marwahaha** [comment]
The deprecation has a link to http://momentjs.com/guides/#/warnings/js-date/

The guides http://momentjs.com/guides/ have info on Mutability, Parsing, locales, and we point to http://momentjs.com/docs/#/plugins/duration-format/, and we have info about DST http://momentjs.com/docs/#/query/is-daylight-saving-time/.

Of course, improvements to these are always welcome.
