### ISSUE TITLE
Add moment().to(moment, opts) returning duration

### ISSUE THREAD

**Issue by ichernev** [moment/moment#1793]
Currently the following methods create a duration and then call a method on it:
- `diff`
- `from`
- `fromNow`

But there is no method to actually create a duration from two moments.

We should add a method (named `to` or similar), that returns a duration object given two moments. Also it can support both ways of interpreting the difference: human and exact. Human will try to extract month and day information accurately (as `duration({from, to})`), where exact would just get the number of milliseconds and bubble up. The two would yield the same result for durations less than one month.

**Comment by marwahaha** [comment]
The output of `diff` can be passed into the duration constructor:
```
var a = moment([2007, 0, 29]);
var b = moment([2007, 0, 28]);
a.diff(b, 'days') // 1
moment.duration(a.diff(b))
```
