### ISSUE TITLE
Fix up defineLocale for 3.0

### ISSUE THREAD

**Issue by icambron** [moment/moment#1796]
Continued from #1761, we want to clean up locale setting for 3.0:
- Make `defineLocale` not set the global locale
- Remove the hack around lazy-loaded locales in Node
- Remove the hack to set the locale back to English in the `embedLocales` task

**Comment by ichernev** [comment]
I know this is a bit outdated, but if we remove the `hack` for locale autoloading, what will happen with node users? Should we release a node-only version that autoloads, or not autoload, or have a one liner plugin that autoloads?

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
