### ISSUE TITLE
Latest update causes errors

### ISSUE THREAD

**Issue by jaredly** [moment/moment#1814]
This is the error I'm getting, and it goes away if I downgrade to 2.7.0. The call that's causing problems is just a moment instantiation with an ISO date string.

```sh
TypeError: Cannot call method 'postformat' of undefined
    at Moment.extend.format (/clone/jaredly.github.io/node_modules/moment/moment.js:2129:38)
...
```

**Comment by mj1856** [comment]
Closing.  If you can still reproduce it, please let us know exactly how and we will reopen.
