### ISSUE TITLE
nodewebkit support

### ISSUE THREAD

**Issue by TrevorMurphy** [moment/moment#1828]
version": "2.7.0

globalscope definition does not work on node-webkit

suggest you change to the following, or equivalent

```
    globalScope = typeof global !== 'undefined' ? (typeof process == "object" ? this : global) : this,
```

Thanks for the great work guys.

**Comment by EladBezalel** [comment]
:+1: Any progress?

**Comment by brannondorsey** [comment]
For folks looking to use moment w/ NW.js before this issue gets resolved, here is a quick fix. Just include this right after including `moment.js`:

```javascript
 if (typeof process !== 'undefined' && 
     typeof process.versions !== 'undefined' &&
     'node-webkit' in process.versions) {
        moment = global.moment;
 }
```

**Comment by marwahaha** [comment]
Is this still used? @TrevorMurphy @b1rdex

**Comment by marwahaha** [comment]
Closing because I'm not sure anyone still wants this.
Please re-open if you still have concerns.
