### ISSUE TITLE
Handling of empty dates

### ISSUE THREAD

**Issue by rquantz** [moment/moment#184]
Thanks so much for this library, it really has been very helpful. That being said, it would be nice if various versions of creating empty dates could be handled similarly. Currently:

```
moment('');
>> Invalid Date

moment(null);
>> null

moment('', 'YYYY-MM-DD');
>> TypeError: i is null

moment('').format('YYYY-MM-DD');
>> "NaN-NaN-NaN"
```

This has produced problems for me in passing date values back and forth with the server, when the date field is nullable. Obviously it can be dealt with, but more consistency would be helpful. Or is this the intended functionality?

Thanks!

**Comment by th3fallen** [comment]
i know this is a *very* old Ticket, but is this still supposed to be the case? when i do `moment(null)` i get back invalid date instead of current date... @timrwood did this logic change in the future and i just cant locate it?

**Comment by theNotoriousHxc** [comment]
yup, it seems like this was reset just like what @th3fallen has said.

**Comment by spideyinf** [comment]
Yes I do have the same problem with `moment('')`, now getting `Invalid date`

**Comment by squarewave24** [comment]
just installed 

```
"moment": "^2.24.0",
"react-moment": "^0.8.4",
```

doing this with optional endDate field:

```
<Moment format="MMM DD YYYY HH:MM">
    {`${r.endDate}`}
</Moment>
```

results:

> moment.js:299 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

**Comment by burzumumbra** [comment]
> i know this is a _very_ old Ticket, but is this still supposed to be the case? when i do `moment(null)` i get back invalid date instead of current date... @timrwood did this logic change in the future and i just cant locate it?

If you need the current date, moment(undefined) should work.

**Comment by coder8keyboard** [comment]
in version 2.29.1, null and empty string gives you invalid date and undefined gives you current date.  Do your error checking before you pass the value to moment.
E.g.:
```
function getDateValue(value) {
    if (value === undefined) {
      return '';
    } else if (value === null) {
      return '';
    } else if (value == '') {
      return '';
    }
    return moment(value).format('YYYY-MM-DD');
}
```
