### ISSUE TITLE
Don't guess date and month

### ISSUE THREAD

**Issue by jeffg2k** [moment/moment#1849]
Would be nice to have some way to tell it not to guess the day and month.  If I enter a year of 1685, I don't want it to tell me the date is the 1st and the month is January.  A year is a range, a month is a range.  These values should be empty, null, or -1 when doing a get("month").  I'm parsing Genealogy data, and if I enter a year and then ask for the date, it is hugely important that I don't suggest a full date.  If I only know the year, then I don't want it to make up the rest.

Alternatively, if there is any way to identify that it is defaulting these values and not something specified, such as providing that it matched on my formatting of "YYYY" or "MMM YYYY" and not "MMM D YYYY".  Looks like the "unusedTokens" might contain this, but not sure how to check this.

**Comment by icambron** [comment]
The information-providing part of this was fixed by #3045.
