### ISSUE TITLE
Loading moment into a namespace

### ISSUE THREAD

**Issue by micpringle** [moment/moment#1888]
Hello!

Is it possible to contain moment.js within a _namespace_, rather than have it made available globally, when used within a regular js script?

For instance:

``` Javascript
var myObject = {};
(function(namespace) {
  /* include "../vendor/moment/min/moment.min.js" */
  namespace.getMoment = function() {
    return moment;
  };
})(myObject);

var m = myObject.getMoment();
console.log(m());

console.log(moment());
```

_Note: I'm using the [grunt-includes](https://github.com/vanetix/grunt-includes) Grunt plugin to actually insert the contents of the source file directly into the namespace_

Ideally the first log statement should print the date, but the second should fail.

This approach works seems to work fine with other js libraries, but not for moment.js

The reason I need to do this is because I'm writing a browser extension and can't guarantee that an existing version of moment (_either newer or older_) doesn't exist in the page the extension injects into.

**Comment by marwahaha** [comment]
I'm not sure if this issue is still relevant. 
If this is still desired, please open a new issue.
