### ISSUE TITLE
Duration .asYears and .asMonths still results in floating point errors

### ISSUE THREAD

**Issue by mjsalinger** [moment/moment#1906]
The moment.duration.asYears() and moment.duration.asMonths() methods still result in floating point errors in 2.8.3.  

Example:

moment.duration(365, 'days').asYears();

Expected Result:  1
Actual Result:       0.9993360575508051

moment.duration(45, 'days').asMonths();

Expected Result:  1.5
Actual Result:        0.9993360575508051

**Comment by icambron** [comment]
I'm not sure--perhaps the Moment changed. But I don't see how 30 is more "exact" in any way than what it returns now. There just isn't an exact answer to "how many days are in a month?" I think Moment has the right behavior here; months are on average 30.437 days.
