### ISSUE TITLE
relativeTime styleable output

### ISSUE THREAD

**Issue by enapupe** [moment/moment#1914]
How do you configure momentjs to output something that would look like this:
![ago](https://cloud.githubusercontent.com/assets/291082/4208062/c46f6230-385c-11e4-811e-55e75a4da48b.jpg)
I thought maybe changing the l18 file to something like:

```
relativeTime : {
      future : "in <sometag>%s</sometag>",
      past : "<sometag>%s</sometag> ago",
      s : "a few seconds",
      m : "a minute",
      mm : "<sometag>%d</sometag> minutes",
      h : "an hour",
      hh : "<sometag>%d</sometag> hours",
      d : "a day",
      dd : "<sometag>%d</sometag> days",
      M : "a month",
      MM : "<sometag>%d</sometag> months",
      y : "a year",
      yy : "<sometag>%d</sometag> years"
  }
```

But that is not the way as they get *html notation* encoded..

**Comment by maggiepint** [comment]
Closing since this is years old at this point. If you need anything fell free to let us know!
