### ISSUE TITLE
fromNow() for days

### ISSUE THREAD

**Issue by georg90** [moment/moment#1924]
Hi!
Thanks for this great piece of work!
I want to use moment to count down my calendar appointments.
Now I have appointments that are full day appointments..but with fromNow() it will count down to the start  date. 

So if I have an appointment on Sunday (fullDay) it will count down to midnight `Sunday at 00:00h`

How can I format fromNow() to only count down full days until the start day?

I googled for hours now..and substring etc. doesn't help me :/

**Comment by nmussy** [comment]
The way that I see it (and need it) is that there could be `fromDay()` and `fromToday()` methods, that not only ignore the time when calculating the difference, but also make `relativeTime()` behave differently. 

Say I have a Date, not a DateTime, and want to compare it to today, I'll do this:

```javascript
moment(origin, moment.ISO_8601).fromNow(); // returns 'n hours ago'
moment(origin, moment.ISO_8601).from(moment().startOf('day')); // returns 'a few seconds ago'
```

Of course, you can always check if `origin` is today, and don't use `from()` in that case, but these two functions could be interesting when not manipulating anything past days.

**Comment by reustle** [comment]
I've been hitting this a few times too. My thought was an optional param for `fromNow` or `from` which is a granularity like `add` has. So, it could look something like `.fromNow(null, 'days')` (today, yesterday, 5 days ago) or `.fromNow(null, 'years')` (this year, last year, 81 years ago)
