### ISSUE TITLE
Change case  _invalidDate: 'Invalid date' to 'Invalid Date'

### ISSUE THREAD

**Issue by cthurston** [moment/moment#1937]
I expected:

```
String(new Date('fail')) === String(moment('fail'));
```

However, "Invalid Date"  does not equal "Invalid date".

Was the lowercase "date" an intentional choice?

**Comment by frsimond** [comment]
As the docs says :
> From version 2.10.3, if the target moment object is invalid the result is the localized Invalid date string.
So, did you change your minds about the immutability of the "Invalid date" string ?

Note : If that was the case, the "Invalid date" is not localized in the 2.10.6 i18n files. Is that intended ?
