### ISSUE TITLE
[locale] use globalScope instead of window. to bind locales

### ISSUE THREAD

**Issue by mcbain** [moment/moment#1946]
Moment is bound to globalscope when no AMD or require:

    globalScope = typeof global !== 'undefined' ? global : this,

The else case for the locales but uses the window object directly. 

    factory(window.moment); // Browser global

When using moment on server side locales cannot be loaded. 
Maybe the same globalScope detection could be used for the locales too?

**Comment by maggiepint** [comment]
I think this can be closed due to the merge of #1974
