### ISSUE TITLE
Add / subtract workdays

### ISSUE THREAD

**Issue by daaain** [moment/moment#1947]
Hey,

I needed a way to step over weekends and created a small helper method to achieve this.

Tried to make it into a pull request, but found the code a bit intimidating on the first sight, so thought I should ask first if this is something that has its place in the library?

Ideally I guess it should be available as moment.add(2, 'workdays') or so.

Let me know if this is useful or maybe already covered somehow?

JSfiddle demo: http://jsfiddle.net/dain/5xrr79h0/

``` js
  moment.fn.addWorkdays = function (days) {
    var increment = days / Math.abs(days);
    var date = this.clone().add(Math.floor(Math.abs(days) / 5) * 7 * increment, 'days');
    var remaining = days % 5;
    while(remaining != 0) {
      date.add(increment, 'days');
      if(date.isoWeekday() !== 6 && date.isoWeekday() !== 7)
        remaining -= increment;
    }
    return date;
  };
```

**Comment by jmeas** [comment]
> The algorithm for adding/subtracting (without holidays) should be pretty straight forward and work in constant time, the one outlined here is taking O(N).

I worked on this last night. My solution is as follows:

- Finding the number of workdays, or weekends, is a *composition* of a more fundamental problem
- The fundamental problem is "How many of a particular day exist between two days?"
- More abstractly, the fundamental problem is "How many solutions of a periodic function exist within some interval?"

In light of that, finding the weekends (in the USA) is solved by:

"How many Saturdays are in this interval **AND** how many Sundays are in this interval?"

The week days, excluding Holidays, is the inverse operation.

This problem could be generalized to any other regular system, such as cultures with a different set of weekend days.

Not sure if this would help anyone, but it's the solution I'm going with in my app. I should have it abstracted into a library in the next day or two.

**Comment by jmeas** [comment]
@ichernev is this the correct fixture data for add/subtract?

https://gist.github.com/jmeas/0a713e0b9901a25a32f1

**Comment by loostro** [comment]
Thanks @daaain. Based on your solution I've created this [gist](https://gist.github.com/loostro/6dd2487999c31527ee2e) with `add/subtract(x, 'workdays')`and `isWorkday()`. Uses `moment.easter` (included in gist). Polish National Holidays are included, but you can easily modify script to add your own.

**Comment by jmeas** [comment]
@loostro, your add/subtract algorithms will be much slower than [the constant-time solutions](https://github.com/jmeas/moment-business/blob/master/src/moment-business.js#L21-L52) in moment-business when adding large numbers of days.

**Comment by loostro** [comment]
@jmeas in my current use case, thats not a problem, as i need to "add" or "subtract" 2 workdays only, but it would be nice to see a better solution

**Comment by jmeas** [comment]
> as i need to "add" or "subtract" 2 workdays only, 

Ah, okay.

> it would be nice to see a better solution

I linked to one in the above comment :stuck_out_tongue:

**Comment by loostro** [comment]
@jmeas you mean `moment.fn.addWeekDays` ? or the libraries from previous posts?

**Comment by jmeas** [comment]
> you mean moment.fn.addWeekDays ? or the libraries from previous posts?

Both. `moment.fn.addWeekDays` is from a library in a previous post, `moment-business`.

**Comment by loostro** [comment]
ah.. i see :) i'll study your solution and fix my gist for Polish workdays to be more efficient, thanks!

**Comment by amakhrov** [comment]
This is how a similar problem (getting difference in week days) is solved in the Carbon library (PHP):
`diffFiltered()` method: [link](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php#L2069)
`diffInWeekdays` [link](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php#L2099) (basically a wrapper over `diffFiltered`)

This interface allows a developer to specify a custom filter function - thus enabling to use the library with arbitrary weekends/holidays

**Comment by jmeas** [comment]
Here's a working constant time solution to this problem for western work weeks:

[moment-business](https://github.com/jmeas/moment-business)

atm it's hard coded to support the western work week, but the underlying algorithms should be generic enough to be tweaked to support any weekend, so long as it's periodic (repeats week to week) and simple (every week is structured the same in terms of what's a week and what's not a week; it doesn't go back and forth between two patterns, for instance)

**Comment by SuperManfred** [comment]
Instead of hard coded western work week and weekend, wouldn't it be easier for moment to incorporate if easily configurable workdays and non-workdays, and easy to set work time hh:mm

**Comment by jmeas** [comment]
Most likely, which is one of the reasons why I made the underlying algo's in moment-business accept any periodic pattern of "holes" (weekends) along an interval (a week). This should make it fairly simple to build an API to work with configurable work days and non-work days. I didn't put in that effort because I only needed western work week support for my use case.

I never made a PR into moment directly because I'd prefer there be some confirmation from the core team that the PR wouldn't just get closed, but I never heard back.

**Comment by icambron** [comment]
@jmeas seems like it makes the most sense as a plugin, just as you have it. We'd be happy to list it under the [plugins section of the docs](http://momentjs.com/docs/#/plugins/) you make a PR to that effect on the [docs repository](https://github.com/moment/momentjs.com).

**Comment by maggiepint** [comment]
To me, this is a permanent plugin. We don't have the ability to determine work days for every locale, especially including holidays. I'm going to close this one.

**Comment by jmeas** [comment]
Thanks for the updates @icambron & @maggiepint !

**Comment by stevenlovegrove** [comment]
FYI, @daaain 's method is also O(1) - it may look as though it iterates over all days between the start and end, but it does not. It only iterates over the modulo which is bounded < 5.
