### ISSUE TITLE
99 tests failed. isBefore:is before month (172.9) isSame:is same month (182.7) endStartOf:start of quarter (279.4) endStartOf:start of quarter (279.5) endStartOf:start of quarter (279.6) endStartOf:start of quarter (279.7) endStartOf:end of quarter (280.7) locale:af:format month (375.4) locale:ar-ma:format month (396.4) locale:ar-sa:format month (417.4) locale:ar:format month (438.7) locale:ar:format month (438.8) locale:az:format month (459.4) locale:be:format month (481.4) locale:be:format month case (482.7) locale:be:format month case (482.8) locale:bg:format month (503.4) locale:bn:format month (524.4) locale:bo:format month (546.4) locale:br:format month (568.4) locale:bs:format month (582.4) locale:ca:format month (602.4) locale:cs:format month (623.4) locale:cv:format month (646.4) locale:cy:format month (667.4) locale:da:format month (687.4) locale:de-at:format month (704.4) locale:de:format month (724.4) locale:el:format month (745.4) locale:en-au:format month (766.4) locale:en-ca:format month (787.4

### ISSUE THREAD

**Issue by MohammadYounes** [moment/moment#1955]
### Client info
```
Date String   : Thu Oct 02 2014 12:19:11 GMT+0300 (Jordan Daylight Time)
Locale String : 10/2/2014 12:19:11 PM
Offset        : -120
User Agent    : Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
```

====

### isBefore:is before month (172.9) 

start of next month

```javascript
// Expected true
// Actual   false
false == true
```

====

### isSame:is same month (182.7) 

start of next month

```javascript
// Expected false
// Actual   true
true == false
```

====

### endStartOf:start of quarter (279.4) 

keep the quarter

```javascript
// Expected 2
// Actual   1
1 == 2
```

====

### endStartOf:start of quarter (279.5) 

strip out the month

```javascript
// Expected 3
// Actual   2
2 == 3
```

====

### endStartOf:start of quarter (279.6) 

strip out the day

```javascript
// Expected 1
// Actual   31
31 == 1
```

====

### endStartOf:start of quarter (279.7) 

strip out the hours

```javascript
// Expected 0
// Actual   23
23 == 0
```

====

### endStartOf:end of quarter (280.7) 

set the hours

```javascript
// Expected 23
// Actual   22
22 == 23
```

====

### locale:af:format month (375.4) 

April Apr

```javascript
// Expected April Apr
// Actual   Maart Mar
"Maart Mar" == "April Apr"
```

====

### locale:ar-ma:format month (396.4) 

أبريل أبريل

```javascript
// Expected أبريل أبريل
// Actual   مارس مارس
"مارس مارس" == "أبريل أبريل"
```

====

### locale:ar-sa:format month (417.4) 

أبريل أبريل

```javascript
// Expected أبريل أبريل
// Actual   مارس مارس
"مارس مارس" == "أبريل أبريل"
```

====

### locale:ar:format month (438.7) 

نيسان أبريل

```javascript
// Expected نيسان أبريل
// Actual   آذار مارس
"آذار مارس" == "نيسان أبريل"
```

====

### locale:ar:format month (438.8) 

نيسان أبريل

```javascript
// Expected نيسان أبريل
// Actual   آذار مارس
"آذار مارس" == "نيسان أبريل"
```

====

### locale:az:format month (459.4) 

aprel apr

```javascript
// Expected aprel apr
// Actual   mart mar
"mart mar" == "aprel apr"
```

====

### locale:be:format month (481.4) 

красавік крас

```javascript
// Expected красавік крас
// Actual   сакавік сак
"сакавік сак" == "красавік крас"
```

====

### locale:be:format month case (482.7) 

1 красавіка

```javascript
// Expected 1 красавіка
// Actual   31 сакавіка
"31 сакавіка" == "1 красавіка"
```

====

### locale:be:format month case (482.8) 

1 красавік

```javascript
// Expected красавік
// Actual   сакавік
"сакавік" == "красавік"
```

====

### locale:bg:format month (503.4) 

април апр

```javascript
// Expected април апр
// Actual   март мар
"март мар" == "април апр"
```

====

### locale:bn:format month (524.4) 

এপ্রিল এপর

```javascript
// Expected এপ্রিল এপর
// Actual   মার্চ মার্চ
"মার্চ মার্চ" == "এপ্রিল এপর"
```

====

### locale:bo:format month (546.4) 

ཟླ་བ་བཞི་པ ཟླ་བ་བཞི་པ

```javascript
// Expected ཟླ་བ་བཞི་པ ཟླ་བ་བཞི་པ
// Actual   ཟླ་བ་གསུམ་པ ཟླ་བ་གསུམ་པ
"ཟླ་བ་གསུམ་པ ཟླ་བ་གསུམ་པ" == "ཟླ་བ་བཞི་པ ཟླ་བ་བཞི་པ"
```

====

### locale:br:format month (568.4) 

Ebrel Ebr

```javascript
// Expected Ebrel Ebr
// Actual   Meurzh Meu
"Meurzh Meu" == "Ebrel Ebr"
```

====

### locale:bs:format month (582.4) 

april apr.

```javascript
// Expected april apr.
// Actual   mart mar.
"mart mar." == "april apr."
```

====

### locale:ca:format month (602.4) 

abril abr.

```javascript
// Expected abril abr.
// Actual   març mar.
"març mar." == "abril abr."
```

====

### locale:cs:format month (623.4) 

duben dub

```javascript
// Expected duben dub
// Actual   březen bře
"březen bře" == "duben dub"
```

====

### locale:cv:format month (646.4) 

ака ака

```javascript
// Expected ака ака
// Actual   пуш пуш
"пуш пуш" == "ака ака"
```

====

### locale:cy:format month (667.4) 

Ebrill Ebr

```javascript
// Expected Ebrill Ebr
// Actual   Mawrth Maw
"Mawrth Maw" == "Ebrill Ebr"
```

====

### locale:da:format month (687.4) 

april apr

```javascript
// Expected april apr
// Actual   marts mar
"marts mar" == "april apr"
```

====

### locale:de-at:format month (704.4) 

April Apr.

```javascript
// Expected April Apr.
// Actual   März Mrz.
"März Mrz." == "April Apr."
```

====

### locale:de:format month (724.4) 

April Apr.

```javascript
// Expected April Apr.
// Actual   März Mrz.
"März Mrz." == "April Apr."
```

====

### locale:el:format month (745.4) 

Απρίλιος Απρ

```javascript
// Expected Απρίλιος Απρ
// Actual   Μάρτιος Μαρ
"Μάρτιος Μαρ" == "Απρίλιος Απρ"
```

====

### locale:en-au:format month (766.4) 

April Apr

```javascript
// Expected April Apr
// Actual   March Mar
"March Mar" == "April Apr"
```

====

### locale:en-ca:format month (787.4) 

April Apr

```javascript
// Expected April Apr
// Actual   March Mar
"March Mar" == "April Apr"
```

====

### locale:en-gb:format month (808.4) 

April Apr

```javascript
// Expected April Apr
// Actual   March Mar
"March Mar" == "April Apr"
```

====

### locale:en:format month (829.4) 

April Apr

```javascript
// Expected April Apr
// Actual   March Mar
"March Mar" == "April Apr"
```

====

### locale:eo:format month (850.4) 

aprilo apr

```javascript
// Expected aprilo apr
// Actual   marto mar
"marto mar" == "aprilo apr"
```

====

### locale:es:format month (871.4) 

abril abr.

```javascript
// Expected abril abr.
// Actual   marzo mar.
"marzo mar." == "abril abr."
```

====

### locale:et:format month (892.4) 

aprill apr

```javascript
// Expected aprill apr
// Actual   märts märts
"märts märts" == "aprill apr"
```

====

### locale:eu:format month (913.4) 

apirila api.

```javascript
// Expected apirila api.
// Actual   martxoa mar.
"martxoa mar." == "apirila api."
```

====

### locale:fa:format month (934.4) 

آوریل آوریل

```javascript
// Expected آوریل آوریل
// Actual   مارس مارس
"مارس مارس" == "آوریل آوریل"
```

====

### locale:fi:format month (955.4) 

huhtikuu huhti

```javascript
// Expected huhtikuu huhti
// Actual   maaliskuu maalis
"maaliskuu maalis" == "huhtikuu huhti"
```

====

### locale:fo:format month (976.4) 

apríl apr

```javascript
// Expected apríl apr
// Actual   mars mar
"mars mar" == "apríl apr"
```

====

### locale:fr-ca:format month (993.4) 

avril avr.

```javascript
// Expected avril avr.
// Actual   mars mars
"mars mars" == "avril avr."
```

====

### locale:fr:format month (1013.4) 

avril avr.

```javascript
// Expected avril avr.
// Actual   mars mars
"mars mars" == "avril avr."
```

====

### locale:gl:format month (1032.4) 

Abril Abr.

```javascript
// Expected Abril Abr.
// Actual   Marzo Mar.
"Marzo Mar." == "Abril Abr."
```

====

### locale:he:format month (1053.4) 

אפריל אפר׳

```javascript
// Expected אפריל אפר׳
// Actual   מרץ מרץ
"מרץ מרץ" == "אפריל אפר׳"
```

====

### locale:hi:format month (1074.4) 

अप्रैल अप्रै.

```javascript
// Expected अप्रैल अप्रै.
// Actual   मार्च मार्च
"मार्च मार्च" == "अप्रैल अप्रै."
```

====

### locale:hr:format month (1096.4) 

travanj tra.

```javascript
// Expected travanj tra.
// Actual   ožujak ožu.
"ožujak ožu." == "travanj tra."
```

====

### locale:hu:format month (1118.4) 

április ápr

```javascript
// Expected április ápr
// Actual   március márc
"március márc" == "április ápr"
```

====

### locale:hy-am:format month (1141.4) 

ապրիլ ապր

```javascript
// Expected ապրիլ ապր
// Actual   մարտ մրտ
"մարտ մրտ" == "ապրիլ ապր"
```

====

### locale:hy-am:format month case (1142.7) 

1 ապրիլի

```javascript
// Expected 1 ապրիլի
// Actual   31 մարտի
"31 մարտի" == "1 ապրիլի"
```

====

### locale:hy-am:format month case (1142.8) 

1 ապրիլ

```javascript
// Expected ապրիլ
// Actual   մարտ
"մարտ" == "ապրիլ"
```

====

### locale:hy-am:format month short case (1143.7) 

1 ապր

```javascript
// Expected 1 ապր
// Actual   31 մրտ
"31 մրտ" == "1 ապր"
```

====

### locale:hy-am:format month short case (1143.8) 

1 ապր

```javascript
// Expected ապր
// Actual   մրտ
"մրտ" == "ապր"
```

====

### locale:id:format month (1164.4) 

April Apr

```javascript
// Expected April Apr
// Actual   Maret Mar
"Maret Mar" == "April Apr"
```

====

### locale:is:format month (1185.4) 

apríl apr

```javascript
// Expected apríl apr
// Actual   mars mar
"mars mar" == "apríl apr"
```

====

### locale:it:format month (1206.4) 

aprile apr

```javascript
// Expected aprile apr
// Actual   marzo mar
"marzo mar" == "aprile apr"
```

====

### locale:ja:format month (1225.4) 

4月 4月

```javascript
// Expected 4月 4月
// Actual   3月 3月
"3月 3月" == "4月 4月"
```

====

### locale:ka:format month (1246.4) 

აპრილი აპრ

```javascript
// Expected აპრილი აპრ
// Actual   მარტი მარ
"მარტი მარ" == "აპრილი აპრ"
```

====

### locale:km:format month (1267.4) 

មេសា មេសា

```javascript
// Expected មេសា មេសា
// Actual   មិនា មិនា
"មិនា មិនា" == "មេសា មេសា"
```

====

### locale:ko:format month (1289.4) 

4월 4월

```javascript
// Expected 4월 4월
// Actual   3월 3월
"3월 3월" == "4월 4월"
```

====

### locale:lb:format month (1309.4) 

Abrëll Abr.

```javascript
// Expected Abrëll Abr.
// Actual   Mäerz Mrz.
"Mäerz Mrz." == "Abrëll Abr."
```

====

### locale:lt:format month (1318.4) 

balandžio bal

```javascript
// Expected balandžio bal
// Actual   kovo kov
"kovo kov" == "balandžio bal"
```

====

### locale:lv:format month (1340.4) 

aprīlis apr

```javascript
// Expected aprīlis apr
// Actual   marts mar
"marts mar" == "aprīlis apr"
```

====

### locale:mk:format month (1361.4) 

април апр

```javascript
// Expected април апр
// Actual   март мар
"март мар" == "април апр"
```

====

### locale:ml:format month (1382.4) 

ഏപ്രിൽ ഏപ്രി.

```javascript
// Expected ഏപ്രിൽ ഏപ്രി.
// Actual   മാർച്ച് മാർ.
"മാർച്ച് മാർ." == "ഏപ്രിൽ ഏപ്രി."
```

====

### locale:mr:format month (1404.4) 

एप्रिल एप्रि.

```javascript
// Expected एप्रिल एप्रि.
// Actual   मार्च मार्च.
"मार्च मार्च." == "एप्रिल एप्रि."
```

====

### locale:ms-my:format month (1426.4) 

April Apr

```javascript
// Expected April Apr
// Actual   Mac Mac
"Mac Mac" == "April Apr"
```

====

### locale:my:format month (1447.4) 

ဧပြီ ပြီ

```javascript
// Expected ဧပြီ ပြီ
// Actual   မတ် မတ်
"မတ် မတ်" == "ဧပြီ ပြီ"
```

====

### locale:nb:format month (1468.4) 

april apr

```javascript
// Expected april apr
// Actual   mars mar
"mars mar" == "april apr"
```

====

### locale:ne:format month (1489.4) 

अप्रिल अप्रि.

```javascript
// Expected अप्रिल अप्रि.
// Actual   मार्च मार्च
"मार्च मार्च" == "अप्रिल अप्रि."
```

====

### locale:nl:format month (1511.4) 

april apr.

```javascript
// Expected april apr.
// Actual   maart mrt.
"maart mrt." == "april apr."
```

====

### locale:nn:format month (1533.4) 

april apr

```javascript
// Expected april apr
// Actual   mars mar
"mars mar" == "april apr"
```

====

### locale:pl:format month (1554.4) 

kwiecień kwi

```javascript
// Expected kwiecień kwi
// Actual   marzec mar
"marzec mar" == "kwiecień kwi"
```

====

### locale:pt-br:format month (1575.4) 

abril abr

```javascript
// Expected abril abr
// Actual   março mar
"março mar" == "abril abr"
```

====

### locale:pt:format month (1595.4) 

abril abr

```javascript
// Expected abril abr
// Actual   março mar
"março mar" == "abril abr"
```

====

### locale:ro:format month (1615.4) 

aprilie apr.

```javascript
// Expected aprilie apr.
// Actual   martie mart.
"martie mart." == "aprilie apr."
```

====

### locale:ru:format month (1638.4) 

апрель апр

```javascript
// Expected апрель апр
// Actual   март мар
"март мар" == "апрель апр"
```

====

### locale:ru:format month case (1639.7) 

1 апреля

```javascript
// Expected 1 апреля
// Actual   31 марта
"31 марта" == "1 апреля"
```

====

### locale:ru:format month case (1639.8) 

1 апрель

```javascript
// Expected апрель
// Actual   март
"март" == "апрель"
```

====

### locale:ru:format month short case (1640.7) 

1 апр

```javascript
// Expected 1 апр
// Actual   31 мар
"31 мар" == "1 апр"
```

====

### locale:ru:format month short case (1640.8) 

1 апр

```javascript
// Expected апр
// Actual   мар
"мар" == "апр"
```

====

### locale:sk:format month (1662.4) 

apríl apr

```javascript
// Expected apríl apr
// Actual   marec mar
"marec mar" == "apríl apr"
```

====

### locale:sl:format month (1685.4) 

april apr.

```javascript
// Expected april apr.
// Actual   marec mar.
"marec mar." == "april apr."
```

====

### locale:sq:format month (1707.4) 

Prill Pri

```javascript
// Expected Prill Pri
// Actual   Mars Mar
"Mars Mar" == "Prill Pri"
```

====

### locale:sr-cyrl:format month (1728.4) 

април апр.

```javascript
// Expected април апр.
// Actual   март мар.
"март мар." == "април апр."
```

====

### locale:sr:format month (1749.4) 

april apr.

```javascript
// Expected april apr.
// Actual   mart mar.
"mart mar." == "april apr."
```

====

### locale:sv:format month (1770.4) 

april apr

```javascript
// Expected april apr
// Actual   mars mar
"mars mar" == "april apr"
```

====

### locale:ta:format month (1791.4) 

ஏப்ரல் ஏப்ரல்

```javascript
// Expected ஏப்ரல் ஏப்ரல்
// Actual   மார்ச் மார்ச்
"மார்ச் மார்ச்" == "ஏப்ரல் ஏப்ரல்"
```

====

### locale:th:format month (1811.4) 

เมษายน เมษา

```javascript
// Expected เมษายน เมษา
// Actual   มีนาคม มีนา
"มีนาคม มีนา" == "เมษายน เมษา"
```

====

### locale:tl-ph:format month (1832.4) 

Abril Abr

```javascript
// Expected Abril Abr
// Actual   Marso Mar
"Marso Mar" == "Abril Abr"
```

====

### locale:tr:format month (1852.4) 

Nisan Nis

```javascript
// Expected Nisan Nis
// Actual   Mart Mar
"Mart Mar" == "Nisan Nis"
```

====

### locale:tzm-latn:format month (1873.4) 

ibrir ibrir

```javascript
// Expected ibrir ibrir
// Actual   marˤsˤ marˤsˤ
"marˤsˤ marˤsˤ" == "ibrir ibrir"
```

====

### locale:tzm:format month (1894.4) 

ⵉⴱⵔⵉⵔ ⵉⴱⵔⵉⵔ

```javascript
// Expected ⵉⴱⵔⵉⵔ ⵉⴱⵔⵉⵔ
// Actual   ⵎⴰⵕⵚ ⵎⴰⵕⵚ
"ⵎⴰⵕⵚ ⵎⴰⵕⵚ" == "ⵉⴱⵔⵉⵔ ⵉⴱⵔⵉⵔ"
```

====

### locale:uk:format month (1916.4) 

квітень квіт

```javascript
// Expected квітень квіт
// Actual   березень бер
"березень бер" == "квітень квіт"
```

====

### locale:uk:format month case (1917.7) 

1 квітня

```javascript
// Expected 1 квітня
// Actual   31 березня
"31 березня" == "1 квітня"
```

====

### locale:uk:format month case (1917.8) 

1 квітень

```javascript
// Expected квітень
// Actual   березень
"березень" == "квітень"
```

====

### locale:uz:format month (1937.4) 

апрель апр

```javascript
// Expected апрель апр
// Actual   март мар
"март мар" == "апрель апр"
```

====

### locale:vi:format month (1958.4) 

tháng 4,Th04

```javascript
// Expected tháng 4,Th04
// Actual   tháng 3,Th03
"tháng 3,Th03" == "tháng 4,Th04"
```

====

### locale:zh-cn:format month (1978.4) 

四月 4月

```javascript
// Expected 四月 4月
// Actual   三月 3月
"三月 3月" == "四月 4月"
```

====

### locale:zh-tw:format month (2000.4) 

四月 4月

```javascript
// Expected 四月 4月
// Actual   三月 3月
"三月 3月" == "四月 4月"
```

**Comment by mj1856** [comment]
Can no longer test since Chrome 37 is commonly available.  However, Testing in this time zone on Windows found similar problems.

Closing this in favor of #2474
