### ISSUE TITLE
handle i18n for component 1.x

### ISSUE THREAD

**Issue by timaschew** [moment/moment#1966]
I open this issue due to closing #1731

Summary:  
component provides a require implementation and then using a locale this line will be executed: [line 9](https://github.com/moment/moment/blob/2b685e46dd7565b942cef5769c782b905887d9f6/locale/af.js#L9)

So it seems that it's only used for Node.js (and maybe browserify). For component it doesn't work, because the locales are not listed as `scripts` in the `component.json` (if they would, the require path would be resolved at build time, but there is another issue, because of a dynamic require in moment.js: [line 769](https://github.com/moment/moment/blob/1f22b266c2411d1e06d7e518d5dd866fa40d107d/moment.js#L769)  

---

There are some solutions to get i18n working in component:
1. ~~Put all language files into `scripts` of `component.json` and remove the dynamic require, this is acutally what was changed in #1731. But it was rejected, and furthermore it's not a good idea to put all language files into the build output, because you may want to keep the output small and use only one language per page request.~~
2. ~~https://github.com/moment/moment/pull/1731#issuecomment-57089309 solution of @anton-ryzhov need a manual copy step. And it's like **1.** not dynamic if you want to support multiple languages.~~
3. ~~**current behaviour:** Only moment is registed as a component script, the locales are just copied as files into the build directory. But you need to expose moment to get the locale working. And this is very ugly, because you need to put this line between embed the build and the locale file.~~
   
   ``` html
   <script src="build/build.js"></script>
   <script>
     window.moment = require("moment"); // need to pollute it to window to use some locale
   </script>
   <script src="build/moment/moment/2.8.3/locale/de.js"></script>
   ```
4. **Change in each locale file the require part:**

``` js
} else if (typeof exports === 'object') {
      module.exports = factory(require('moment')); // CommonJS: node.js, component, browserify
}
```

Because component uses its own namespacing to require remote modules, we need to create an alias in the `moment.js` files. Then we can do `require('moment')` for every CommonJS environment: node, component and browserify.

``` js
  (function (factory) {
    // create component alias for `moment` 
    require.register("moment", function(exports, module) { module.exports = require.latest("moment~moment")});

    if (typeof define === 'function' && define.amd) {
        define(['moment'], factory); // AMD
    } else if (typeof exports === 'object') {
        module.exports = factory(require('moment')); // CommonJS: node, component, browserify
    } else {
        factory(window.moment); // Browser global
    }
```

With this solution you are flexible to include any languages, just one or multiple (per request). And you don't need to expose moment to the window object. We can do this:

``` html
  <script src="build/build.js"></script>
  <script src="build/moment/moment/2.8.3/locale/de.js"></script>
```

or load multiple locals (the last script set the global locale):

``` html
  <script src="build/build.js"></script>
  <script src="build/moment/moment/2.8.3/locale/de.js"></script>
  <script src="build/moment/moment/2.8.3/locale/ru.js"></script>
```

And you can still change the global locale via `moment.locale('en')` to locales, which are already loaded (in this case `en` is loaded by default)

**Comment by marwahaha** [comment]
I'm not sure if this issue is still relevant. 
If this is still desired, please re-open or open a new issue.
Sorry we never got around to this.
