### ISSUE TITLE
Pivot year is arbitrary and hardcoded

### ISSUE THREAD

**Issue by fernandezpablo85** [moment/moment#1969]
The pivot year for momentjs is arbitrarily defined at `68`[1], it should be configurable.

[1] https://github.com/moment/moment/blob/2b685e46dd7565b942cef5769c782b905887d9f6/moment.js#L2060-2062

**Comment by eddiemonge** [comment]
> This function is intended to be modified by users - its attached to moment. If you want to handle 5 cases - just change the function and then put the old one back, packing this in a function. Js is single threaded so no race conditions apply.

This is a bad UX. This requires using more memory and CPU cycles vs just allowing another arg.
```
    moment.parseTwoDigitYear = function (input, cutoff) {
        return toInt(input) + (toInt(input) > cutoff ? 1900 : 2000);
    };
```
