### ISSUE TITLE
Encoding issue while integrating library

### ISSUE THREAD

**Issue by chiru0307** [moment/moment#1970]
For languages such as Japanese/Chinese/Korean, faced encoding issue with IE and junk characters were shown sometimes.

A simple charset="UTF-8" in the script tag solved the problem.
Maybe the documentation could be changed a bit, so that it'd help newbies like me.

SO link: http://stackoverflow.com/questions/26215002/encoding-issue-while-integrating-moment-js-library

**Comment by marwahaha** [comment]
This is up-for-grabs. Best place to update is probably around here:
https://github.com/moment/momentjs.com/blob/master/docs/moment/06-i18n/04-loading-into-browser.md

**Comment by maggiepint** [comment]
closing in favor of moment/momentjs.com#444
