### ISSUE TITLE
Add localization for Swahili

### ISSUE THREAD

**Issue by saraid** [moment/moment#1984]
Any chance of this? I don't have the translations myself and will keep looking, but if anyone can find an appropriate localization, it would be helpful for my current project.

**Comment by jspear29** [comment]
I don't if this is still an active item, but I saw it on up-for-grabs.net . So I reached out to the Swahili Flagship Center at Indiana University asking if they could give me the days of the week.  Here's the reply I received.  Let me know if there's anything else that you need to get.


Hi,

Good luck with the project. 

Saturday-Jumamosi
Sunday- Jumapili 
Monday- Jumatatu 
Tuesday- Jumanne
Wednesday- Jumatano 
Thursday- Alhamisi 
Friday- Ijumaa

 
http://www.glcom.com/hassan/lessons/useful_swahili_words.html

Will Kanyi
Assistant Director
Swahili Flagship Center
Indiana University
Eigenmann Hall 1134
(812) 855-3411

swahili.indiana.edu
facebook.com/swahiliflagship
twitter.com/swahiliflagship

**Comment by saraid** [comment]
It looks like someone pulled in a Swahili translation with abbreviations 7 days ago, so I'm closing. Thanks also to @jspear29 for finding someone to reach out to.
