### ISSUE TITLE
startOf('hour') advances to the next hour during DST fall back

### ISSUE THREAD

**Issue by leonyu** [moment/moment#1990]
When in DST timezone, `.startOf('hour')` advances to the next hour during DST fall back
![screen shot 2014-10-16 at 3 52 37 pm](https://cloud.githubusercontent.com/assets/304902/4669401/0226112c-556e-11e4-803a-81544b80f894.png)

**Comment by jamesdixon** [comment]
hi, any update or workaround for this? just ran into this issue with the recent shift from MST to MDT.  Using `startOf` causes the offset to shift forward by 1 hour.

**Comment by rntdrts** [comment]
I'm not sure if it is related to this topic, but as you can see on the displayed image below setting the hour to one in the morning automatically increases up to one hour.

![moment_bug](https://cloud.githubusercontent.com/assets/3099777/24017554/7093ff08-0a88-11e7-8fb8-bc3900f52c55.png)

**Comment by darakeon** [comment]
@leonyu , test again, seems like it's fixed.

**Comment by darakeon** [comment]
@leonyu , test again, the endOf problem seems fixed.

**Comment by leonyu** [comment]
Still bugged in Moment 2.20.1, at least on Chrome & Firefox when current local time is in EST (winter North American timezone). 

Firefox attempted a fix awhile a few months ago, which appear to have only fixed the issue when current local time is in EDT (summer North American timezone).

Here's my test case using Moment 2.20.1 (require your local timezone to observe DST, as it attempts to find the "DST fallback" programmatically): 
https://jsfiddle.net/voidvector/yqsu73nq/7/

**Comment by rnyberg** [comment]
I'm seeing some related weirdness with startOf('day') and adding hours to it: https://vgy.me/XRPcS9.png

**Comment by leonyu** [comment]
I had further back-and-forth on Mozilla's Bugzilla board since my last post a month ago. 

The spec contains pseudo-code which all the browsers implement. The logic of the pseudo-code doesn't account for DST (missing hour/overlapping hour). 

Mozilla developers' position is that they are following the spec.  So IMO this problem is unlikely to resolve on browser vendor's end.
