### ISSUE TITLE
Strip 'Uhr' of localized german time

### ISSUE THREAD

**Issue by kleinph** [moment/moment#2006]
Is it possible to strip the 'Uhr' part of the LT format option which is shown when the locale is german (de).
In my opinion the 'Uhr' is not part of the time like 'AM'/'PM' would be* but only an addition which is sometimes added.

(*) I don't know but maybe it is specified in some standard (ISO, DIN), but it is definitely not always useful.

**Comment by mj1856** [comment]
I think this was already completed.
