### ISSUE TITLE
locale is not loaded automatically with browserify

### ISSUE THREAD

**Issue by janmarek** [moment/moment#2007]
With browserify (http://browserify.org/) setting locale does not work.

```js
var moment = require('moment');
moment.locale('cs');
console.log(moment.locale()); // en
```

I have found this workaround:
```js
var moment = require('moment');
require('moment/locale/cs');
moment.locale('cs');
console.log(moment.locale()); // cs
```

It is probably not easily fixable, but at least it can be mentioned in docs.

**Comment by timaschew** [comment]
And it's still not in the docs after 6 months.

@janmarek  you don't need to call the locale after the require

```js
var moment = require('moment');
require('moment/locale/cs');
console.log(moment.locale()); // cs
```

But this behaviour and the common js requiring in moment is totally horrible.

**Comment by alesanabria** [comment]
It works thanks, even if is not pretty. It should be in the docs.

**Comment by mj1856** [comment]
Please send a PR to https://github.com/moment/momentjs.com.  Thanks.

**Comment by albertorestifo** [comment]
This is long overdue.

It might not be the pretties solution, but it's the best one.

**Comment by mj1856** [comment]
Merged the PR in the docs repo.  Thanks, and sorry for the delay.

**Comment by muhgumus** [comment]
let trLocale = require('moment/locale/tr');
moment.locale('tr',trLocale)

**Comment by VarshaBawari** [comment]
Was able to fix with this one https://github.com/moment/moment/issues/3624#issuecomment-406451318

**Comment by fgagneten** [comment]
Solution for me was removing the following lines:

    LocaleConfig.locales.locale = i18n.t("calendar")

    LocaleConfig.defaultLocale = "locale"
