### ISSUE TITLE
Issue getting month and day printed as in blog post type 

### ISSUE THREAD

**Issue by josleow** [moment/moment#2020]
App.js

```
function updatePost(){
    last_updated = new Date()
    ...
}
```

Jade template (HTML)
    .date
     .day #{last_updated}
     .month.uppercase #{last_updated}

JQuery in jade template

```
var date = $('.month, .day').text()
alert(date)
var convertMonth = moment(date, "DD MMM YYYY").format("MMM")
$('.month').html(convertMonth)
var convertDay = moment(date, "DD MMM YYYY").format("D")
$('.day').html(convertDay)
```

Alert(date) returns 

Thu Oct 30 2014 14:16:28 GMT+0800 (SGT)Thu Oct 30 2014 14:16:28 GMT+0800 (SGT)Thu Oct 30 2014 12:42:51 GMT+0800 (SGT)Thu Oct 30 2014 12:42:51 GMT+0800 (SGT)Wed Oct 29 2014 15:45:00 GMT+0800 (SGT)Wed Oct 29 2014 15:45:00 GMT+0800 (SGT)

The result prints repeatedly:
Invalid date
Invalid date

Everytime user saves post, the date is also updated. 
On the listing, the day and month should be reflected upon updating or creating post.

I searched invalid date on google for answers but still it wasn't solved even with answers I found.
Help appreciated!

**Comment by marwahaha** [comment]
`moment({})` will default to `moment()`, and most other objects will emit a deprecation warning.

One way to solve this is to pass the string back through a Date constructor, and pass the result to moment. 
```
var date = $('.month, .day').length;
var count = 0
for (var i = 0; i < date; i++){
var myDate = moment(new Date(date[i].textContent));
var convertMonth = myDate.format("MMM")
$('.month').html(convertMonth)
var convertDay = myDate.format("D")
$('.day').html(convertDay)
}
```

If you don't have `textContent` (i.e. IE8), there's a polyfill here: https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

Please re-open if you have other issues.
