### ISSUE TITLE
Improve support for ISO8601 compact format

### ISSUE THREAD

**Issue by szechyjs** [moment/moment#2025]
Can't parse this ISO timestamp without specifying a format string.

`2014-10-02T1526Z`

**Comment by mj1856** [comment]
Bump.

Looks like we do not support the compact format with either `moment#string` or when using `moment.ISO8601`.

We can only support them via explicit format string, such as `moment(s, "YYYYMMDDTHHmmssZ")`

**Comment by mj1856** [comment]
This was completed with #2641

**Comment by mj1856** [comment]
To clarify - we now fully support the *compact* and *extended* formats.  The mixed format from the top of this request would still have to be parsed with a format string.
