### ISSUE TITLE
1 test failed. locale:el:calendar last week (462.6)

### ISSUE THREAD

**Issue by io41** [moment/moment#2028]
### Client info

```
Date String   : Sat Nov 01 2014 00:27:29 GMT+0100 (CET)
Locale String : 1 November 2014 00:27:29 CET
Offset        : -60
User Agent    : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25
```
# 
### locale:el:calendar last week (753.18)

Today - 6 days one o clock

``` javascript
// Expected την προηγούμενη Κυριακή στη 2:30 ΠΜ
// Actual   την προηγούμενη Κυριακή στις 2:30 ΠΜ
"την προηγούμενη Κυριακή στις 2:30 ΠΜ" == "την προηγούμενη Κυριακή στη 2:30 ΠΜ"
```

**Comment by BexAnn** [comment]
I also got this error. The time th test was run was around 9:16AM  BST

### Client info
```
Date String   : Wed Apr 01 2015 09:11:11 GMT+0100 (GMT Daylight Time)
Locale String : 4/1/2015, 9:11:11 AM
Offset        : 0
User Agent    : Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
```

====

### locale:el:calendar last week (879.6) 

Today - 3 days one o clock

```javascript
// Expected την προηγούμενη Κυριακή στη 2:30 ΠΜ
// Actual   την προηγούμενη Κυριακή στις 2:30 ΠΜ
"την προηγούμενη Κυριακή στις 2:30 ΠΜ" == "την προηγούμενη Κυριακή στη 2:30 ΠΜ"
```

**Comment by mj1856** [comment]
I can still reproduce this when the clock is changed to April 1st 9am.

### Client info
```
Date String   : Wed Apr 01 2015 09:00:24 GMT+0100 (GMT Daylight Time)
Locale String : 4/1/2015, 9:00:24 AM
Offset        : 0
User Agent    : Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36
```

====

### locale:el:calendar last week (462.6) 

Today - 3 days one o clock

```javascript
// Expected την προηγούμενη Κυριακή στη 2:30 ΠΜ
// Actual   την προηγούμενη Κυριακή στις 2:30 ΠΜ
"την προηγούμενη Κυριακή στις 2:30 ΠΜ" === "την προηγούμενη Κυριακή στη 2:30 ΠΜ"
```

**Comment by mj1856** [comment]
Testing further, on Windows with time zone set for London and varying the clock.  The error starts occurring at `2015-03-31T00:00:00+01:00` and stops at `2015-04-05T00:00:00+01:00`.   Very strange, since this time zone's DST transition was on March 29th.  This error pops up 2 days later until 7 days later.  :confused:

**Comment by mj1856** [comment]
Ok, I think [this line](https://github.com/moment/moment/blob/eef69fc7842d0c35900f639792c2f782024143ab/src/test/locale/el.js#L225) has the issue.  The modulo on the hours doesn't match the `m.calendar()` output.

I'm not sure which is incorrect, the test or the calendar localization.

Note the `for (i = 2; i < 7; i++)` - which explains the results of my earlier experimentation.

**Comment by mj1856** [comment]
[Here's the calendar function for this locale](https://github.com/moment/moment/blob/eef69fc7842d0c35900f639792c2f782024143ab/src/locale/el.js#L61).  They both do the same `hours % 12 === 1 ? 'στη' : 'στις'`, but I think one of them is not getting the right hour due to the DST transition.
