### ISSUE TITLE
Importing moment.js into a QML project in Qt 5.2

### ISSUE THREAD

**Issue by Nicd** [moment/moment#2031]
Hey moment.js devs!

This isn't a real 'issue' in the sense that there was something wrong in moment.js itself. I'm posting this here merely because I thought you might find it interesting, and hoping that it might help someone that might be googling for this same thing in the future.

I'm using moment.js in my QML app because it enables me to do fun stuff with timestamps, but the QML Javascript engine is not really friendly to the library. There are three issues:
1. The Javascript engine does not support modifying the global object so the exported `moment` variable must be put into a local variable which will then be automatically exposed to callers by the Javascript engine.
2. The Javascript engine does not support IIFEs without some work. The gist I've linked later in this post shows one way to fix it.
3. The Javascript engine, since Qt 5.2, does not allow the word 'as' in identifiers. This means the moment.js function `as` results in a parse error. I fixed this by renaming `as` into `asUnit`.

I've written about this matter on Google+ [here](https://plus.google.com/+MikkoAhlroth/posts/c5gnV9kiy1L) and I've created a [gist](https://gist.github.com/Nicd/6dac64ba3b97c714a65b#file-moment-js-diff) which contains the diff between the original and the modified library which works with the QML Javascript engine.

So, it's not an issue with moment.js, but rather a curiosity of the QML Javascript engine. :) Of course I'm open to hearing any ideas or if someone has dealt with this in a more elegant way.

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.
Sorry this was not a success for you.

**Comment by guruz** [comment]
There is a QML port @jryannel by here at https://github.com/jryannel/qmlmoment (But last update was 5y ago) which is based on the diff in the now-deleted gist by @Nicd 

It would indeed be cool to have momentjs be compatible with QML as per https://bugreports.qt.io/browse/QTBUG-40275 the timezone stuff in QML is not really existing...
(hm, but this would also need moment-timezone ...)

**Comment by Nicd** [comment]
This gist is still alive btw: https://gist.github.com/Nicd/03ad7ca2599bf3d0c533#file-moment-js-diff

Nice to see that some people have benefited from my research. I myself have no use for this anymore.
