### ISSUE TITLE
Setting ISO week year sometimes results in wrong year

### ISSUE THREAD

**Issue by Pumpuli** [moment/moment#2033]
moment('2012-12-31T00:00:00.000Z').isoWeekYear(2013).isoWeekYear();  // 2013
    moment('2012-12-31T00:00:00.000Z').isoWeekYear(2012).isoWeekYear();  // 2011
    moment('2012-12-31T00:00:00.000Z').isoWeekYear(2011).isoWeekYear();  // 2010
    moment('2012-12-31T00:00:00.000Z').isoWeekYear(2010).isoWeekYear();  // 2009
    moment('2012-12-31T00:00:00.000Z').isoWeekYear(2019).isoWeekYear();  // 2009

**Comment by mj1856** [comment]
Bumping priority on this for visibility.

**Comment by christiaanwesterbeek** [comment]
Maybe this was already done before, but I've written a test for calculating the last week of the first 400 years of this century. Here it is:

https://gist.github.com/christiaanwesterbeek/67afdaef3533b6e575016350eb95f32d
