### ISSUE TITLE
Showing server time not client time on the browser

### ISSUE THREAD

**Issue by Ethaan** [moment/moment#2039]
Actually im working with moment.js and showing weeks days on client side, i have this code (im using meteor),

```javascriptTemplate.main.helpers({
  'showLunes' : function(){
  moment.locale("es");
    var lunes = moment().startOf('week').add(0,'days').format('LLLL');
  return lunes;
});
```

and calling this helper simply like ```{{showLunes}}```

This works for me, but when other partner open the web page and he have different hour or date or whatever, the browser take client time and instead show current day, its show another day

**Comment by maggiepint** [comment]
I'm going to close this issue since it has been a year and a half, but if you need help, let us know.
