### ISSUE TITLE
.fromNow() does not respect current locale setting

### ISSUE THREAD

**Issue by s-a** [moment/moment#2042]
```.fromNow()``` always use first locale set by ```moment.locale('LNG')```
.So it is not possible to change current language at runtime,

I have created a reproducable example at http://jsfiddle.net/s__a/ceu9kqt6/2/

**Comment by maggiepint** [comment]
Closing due to age. Let us know if this is still an issue and you would like it re-opened.

**Comment by C0deZLee** [comment]
This is still an issue! This bug haven't been fixed 4 years later.

**Comment by AudereSemper** [comment]
Hello we are using fromnow() and this is still an issue, has someone find a solution ?

**Comment by mkhoussid** [comment]
+1

**Comment by mkhoussid** [comment]
This has been answered [here](https://stackoverflow.com/a/62161490/2891356)

**Comment by pacosw1** [comment]
Importing the specific locale didn't work for me but this did:


```
import moment from "moment/min/moment-with-locales";

export const timeSinceNowString = (utcDate: Date): string => {
  return moment.utc(utcDate).local().locale("es").fromNow();
};
```
