### ISSUE TITLE
Prevent Bubbling when setting DOY/hours/minutes/etc

### ISSUE THREAD

**Issue by Gillingham** [moment/moment#2046]
We have a form that lets users input the value for minutes, seconds, DOY, etc to then build date objects used elsewhere, and having everything bubble-up by default is rather unexpected to most users.

Moment having an option to disable this or bypass the bubbling up, event saying it's invalid etc would be great.

**Comment by mszczepanczyk** [comment]
@ichernev 

+1 for a switch to disable bubbling or turn on "strict" bubbling e.g. 0h67m -> 1h07m, 15d ->2w1d etc.

For me the current semantics is counterintuitive. Without grepping through the code I'm not sure if a duration like ```moment.duration({weeks: 80})``` is going to represent exactly 80 weeks or something around 1.5 year when added to some moment.

Then, correct me if I'm wrong, but to be able to read the exact value of a duration I have to access its private members, which is not covered by official docs/api:

```
moment.duration({weeks: 5}).weeks()  // 0
moment.duration({weeks: 5}).months() // 1
moment.duration({weeks: 5}).days()   // 4
moment.duration({weeks: 5})._days    // 35 <- that's what I wanted. At least sort of
```

**Comment by marwahaha** [comment]
I know this is an old ticket but I'd like to help out.

@mszczepanczyk to get the exact value of a duration, you can use:
```
moment.duration({weeks: 5}).asDays()
```
[This is in the docs; let me know if they're unclear! ](http://momentjs.com/docs/#/durations/days/)

@Gillingham Probably, the "error" depends on the particular application, so @ichernev 's suggestion seems like it would work for you.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/ . We will not make substantial changes to Moment.js going forward.
