### ISSUE TITLE
Extra white-space in localized format for Serbian, Croatian, Bosnian, and Slovenian

### ISSUE THREAD

**Issue by cebence** [moment/moment#2070]
For the locales listed below there should be no white-space in the localized date string (`'L'`), i.e. `25. 11. 2014` should be `25.11.2014`.

Historically, all these *inherit* from the German locale.

- Serbian `sr` [at line 46](https://github.com/moment/moment/blob/develop/locale/sr.js#L46) and `sr-cyrl` [at line 46](https://github.com/moment/moment/blob/develop/locale/sr-cyrl.js#L46)

- Croatian `hr` [at line 78](https://github.com/moment/moment/blob/develop/locale/hr.js#L78)

- [Bosnian](http://en.wikipedia.org/wiki/Bosnia_and_Herzegovina) `bs` [at line 77](https://github.com/moment/moment/blob/develop/locale/bs.js#L77)

- [Slovenian](http://en.wikipedia.org/wiki/Slovenia) `sl` [at line 84](https://github.com/moment/moment/blob/develop/locale/sl.js#L84)

Macedonian locale has the correct date format.

**Comment by bmarkovic** [comment]
Perhaps @milan-j is right for Serbian. But the DD.MM.YYYY. form is commonly used and correct in Croatian, and AFAIK Bosnian as well.

**Comment by maggiepint** [comment]
I'm going to close this due to age. If it is still an issue, feel free to re-open. If the locale files are wrong, we would definitely accept a pull request.

**Comment by scrnjakovic** [comment]
@milan-j and @cebence the correct way to write Serbian dates according to Serbian orthography **is with spaces** i.e. 1. 2. 2017. **Alternatively**, you can write like what @milan-j mentioned as primary way to write (with leading zero), which is used in accounting and business correspondency.

On top of that, there **must** be dot at the end except if there is another punctuation mark following the dot, in which case the dot is omitted.

https://ciklopea.com/sr/језичка-грешка/jezicka-greska-br-40-pisanje-datuma-u-srpskom-jeziku/
https://www.opismenise.com/nedoumice/kako-se-pise-datum-u-srpskom-jeziku/
https://www.pismenica.rs/kako-se-pise/pravilno-pisanje-datuma-nula-ispred-jednocifrenih-brojeva/
http://kakosepise.com/rec/12-12-2013-ili-12-12-2013/

**Comment by scrnjakovic** [comment]
I created #4741 and #4742 to fix this
