### ISSUE TITLE
fromNow: Letting window open on FIREFOX in the background cause unresponsive javascript error

### ISSUE THREAD

**Issue by sunilsd** [moment/moment#2077]
I am calling "moment(dateString).fromNow();" every 30 seconds to update the time-since in firefox and leave it in the background. After approximately 7-10 minutes, observe the following error pop up.

"A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: js/moment.js:599"

The issue seems similar to the one listed here but in my case, there is no crash but a unresponsive script error: https://code.google.com/p/chromium/issues/detail?id=336129

Versions used:
moment.js version : 2.8.3
moment-timezone.js: version : 0.2.2

**Comment by sunilsd** [comment]
Hi,
   Would appreciate it if you could take a quick look at this.

**Comment by sunilsd** [comment]
Knock knock ..... Anybody home ?

**Comment by sunilsd** [comment]
Thanks Matt ... hoping someone can figure out a workaround :)

**Comment by icambron** [comment]
Sorry for the slow response, but we were never going to be able to help you with this. Certainly Moment isn't itself locking up your whole script. Likely something else in your script was wrong.
