### ISSUE TITLE
Missing locale files en and en-US

### ISSUE THREAD

**Issue by danieljsinclair** [moment/moment#2081]
I appreciate this may be the default language, but it would be convenient if the source had reference files (even empty ones) for these two locales.

At best one could expect a 404 for some implementations that dynamically switch locales, but in my case I'm having to create a list of the locale subset supported by both AngularJS and MomentJS - unfortunately, "en" and "en-US" don't make the of course.

How about a couple of blank files with the simple text /\* default */ ?

**Comment by codemole986** [comment]
Where I can check default configuration set for "en" locale?
