### ISSUE TITLE
Moment doesn't always attach to window.

### ISSUE THREAD

**Issue by vxsx** [moment/moment#2092]
Hello guys.

There's this line in moment.js
```js
globalScope = typeof global !== 'undefined' ? global : this,
```
If there's an element on the page that has `id="global"` then moment will be attached to this element and not to window because unfortunately this http://www.w3.org/html/wg/drafts/html/master/browsers.html#named-access-on-the-window-object

I cannot provide jsfiddle because it's not happening in jsfiddle (not sure why), but it happens with simple test page like this.

```html
<!doctype html>
<html>
<head>
    <title>Moment test</title>
</head>
<body>
    <div id="global"></div>
    <script src="http://momentjs.com/downloads/moment.min.js"></script>
    <script>
       console.log(document.getElementById('global').moment); //works
       console.log(moment); //moment is undefined
    </script>
</body>
</html>
```

**Comment by icambron** [comment]
Fixed by #2117.
