### ISSUE TITLE
Date diff in months returning possible incorrect value - less for later date

### ISSUE THREAD

**Issue by awbacker** [moment/moment#2109]
I am using moment for some date duration validation, and got a failing test around a month border.  We are trying to get the `months` difference, and a later date is showing a smaller difference.  Is the months difference something we shouldn't rely on, or is this a bug, or expected behavior due to the annoying month of February?

``` javascript
// notice how the diff for 01-Feb to 01-May goes DOWN from 30-Apr.  It goes back up 
moment('2014-02-01').diff(moment('2014-04-30 23:59:59'), 'months', true);  // -3.034482359514687
moment('2014-02-01').diff(moment('2014-05-01 23:59:59'), 'months', true);  // -3.0338979127432517
moment('2014-02-01').diff(moment('2014-05-02 23:59:59'), 'months', true);  // -3.0677962178279974
```

Doing the same without times results in -3 for two different dates:

``` javascript
moment('2014-02-01').diff(moment('2014-04-30'), 'months', true);  // -3
moment('2014-02-01').diff(moment('2014-05-01'), 'months', true);  // -3
```

Edit: Downloaded `moment.min.js` yesterday, `v2.8.4`

**Comment by Chipintoza** [comment]
here is bag!
just try

```
var a = moment([2019, 10, 1]);
var b = moment([2019, 10, 11]);
console.log(a.diff(b, 'months', true))
console.log(b.diff(a, 'months', true))

```
its log difference values

**Comment by Chipintoza** [comment]
Sorry. i understand how you calculate diff
