### ISSUE TITLE
ISO 8601 YYYYMMDD format not valid

### ISSUE THREAD

**Issue by marc-gist** [moment/moment#2112]
for some reason (i'm using v 2.8.3) moment gives an invalid error when you pass in a string in the ISO 8601 format of YYYYMMDD
according to the ISO, the '-' are not required and subject is valid under the standard.

**Comment by javaknight** [comment]
Can we reopen this issue until someone provides a patch? This functionality is quite important and is part of the base ISO8601 spec.
