### ISSUE TITLE
moment(String, Format) not working correctly 

### ISSUE THREAD

**Issue by almogdesign** [moment/moment#2116]
If I do the following 

moment(this.organicFieldStatusTo, "MM-DD-YYYY"); 
I get the full date with the time 

The following works great but I get the Deprecation warning: moment construction falls back to js

moment(this.organicFieldStatusTo).format('MMMM DD, YYYY');

I would like to return just the date. this.organicFieldStatusTo = ISODate("2015-01-03T15:06:43.000Z")

**Comment by kashifshamaz21** [comment]
@almogdesign The reason you are getting the deprecation warning is because while creating the moment, you didn't specify the format of your input string.
More details on this subject are in this issue: #1407 

With what you are trying to accomplish, following should work:
```
var a = moment(this.organicFieldStatusTo, 'MM-DD-YYYY').format('MMMM DD, YYYY');
```
