### ISSUE TITLE
Date diff

### ISSUE THREAD

**Issue by OxCom** [moment/moment#2130]
```
var diff1 = moment([1981, 4, 4]).from(moment([2014, 9, 4]));
var diff2 = moment([1981, 4, 4]).from(moment([2014, 10, 4]));
var diff3 = moment([1981, 4, 4]).from(moment([2015, 4, 4]));

console.log(diff1); // "33 years ago"
console.log(diff2); // "34 years ago"
console.log(diff2); // "34 years ago"
```
v.2.8.4

As I understand we should have something like this:
33 years ago
33 years ago
34 years ago

**Comment by icambron** [comment]
Yes, that's expected: it's rounding the 33.5 years to 34 years in the diff2 case. That code isn't super flexible, so you'd have to spin your own. If you just need years, I think this what you're looking for:

```js
Math.floor(moment([2014, 10, 4]).diff(moment([1981, 4, 4]), 'y', true)); //=> 33
```
