### ISSUE TITLE
1 test failed. isBefore:is before day (175.10) 

### ISSUE THREAD

**Issue by Youzardos** [moment/moment#2138]
### Client info

```
Date String   : Thu Jan 01 2015 17:55:27 GMT+0000 (WET)
Locale String : 1/1/2015 17:55:27
Offset        : 0
User Agent    : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0
```
# 
### isBefore:is before day (175.10)

exact end of day

``` javascript
// Expected false
// Actual   true
true == false
```

**Comment by ichernev** [comment]
This timezone is problematic. Not to mention that a few versions of FF back, there are 4 errors, not intersecting with this one. If you can debug it that would be awesome, otherwise I might give it a try at some later point in time.
