### ISSUE TITLE
moment.isDSTShifted() not reporting expected values

### ISSUE THREAD

**Issue by fardog** [moment/moment#2141]
I'm having issues with `isDSTShifted()` working as expected. Please see the following fiddle:

http://jsfiddle.net/natewittstock/s2uf18ea/1/

**My Output:**
```
// Chrome
2015-03-08 1:30:
	2015-03-08T01:30:00-08:00	false
2015-03-08 2:30:
	2015-03-08T03:30:00-07:00	false
2015-03-08 3:30:
	2015-03-08T03:30:00-07:00	false

// Firefox
2015-03-08 1:30:
	2015-03-08T01:30:00-08:00	false
2015-03-08 2:30:
	2015-03-08T01:30:00-08:00	false
2015-03-08 3:30:
	2015-03-08T03:30:00-07:00	false

// nodejs (entered in REPL as below)
> moment('2015-03-08 1:30', 'YYYY-MM-DD HH:mm').format()
'2015-03-08T01:30:00-08:00'
> moment('2015-03-08 2:30', 'YYYY-MM-DD HH:mm').format()
'2015-03-08T01:30:00-08:00'
> moment('2015-03-08 3:30', 'YYYY-MM-DD HH:mm').format()
'2015-03-08T03:30:00-07:00'
> moment('2015-03-08 1:30', 'YYYY-MM-DD HH:mm').isDSTShifted()
false
> moment('2015-03-08 2:30', 'YYYY-MM-DD HH:mm').isDSTShifted()
false
> moment('2015-03-08 3:30', 'YYYY-MM-DD HH:mm').isDSTShifted()
false
```

I'd expect the calls with `2015-03-08 2:30` to show `true` for calls to `isDSTShifted()`

I'm seeing this issue on:

- nodejs v0.10.35
- Chrome 39.0.2171.95 (64-bit)
- Firefox 34.0.5

…all on Mac OS X 10.10.1; reproducible across varying systems of relatively the same spec (either OS X 10.9 or 10.10; latest-ish of Chrome, as confirmed by my co-workers)

My system's timezone is being set automatically by the Apple preference pane, and reports "Time Zone: Pacific Standard Time" and "Closest City: Portland, OR - United States"

Can confirm the Javascript date object thinks I'm in PST, via 

```
> new Date()
Fri Jan 02 2015 14:25:10 GMT-0800 (PST)
```

Let me know if there's any other information I can give you. Thanks!

**Comment by icambron** [comment]
Looks like a bug to me. `isDSTShifted()` doesn't really have test coverage because we can't make a reproducible test for it. @ichernev: looks like this broke because we no longer leave `_a` attached to the moment object.

**Comment by fardog** [comment]
Thanks for the confirmation @icambron!
