### ISSUE TITLE
Z does not parse ISO8601 +-HH

### ISSUE THREAD

**Issue by syranide** [moment/moment#2142]
[ISO8601](http://en.wikipedia.org/wiki/ISO_8601) allows `+01` in addition to `+0100` and `+01:00` as timezone offset. Is there any reason why this isn't parsed by moment.js? It is trivial enough to fix, but perhaps there are other considerations I'm unaware of?

**Comment by ichernev** [comment]
Hm, I though we supported that. The funny part is that the parsing function (you mention in https://github.com/moment/moment/issues/2143) handles that case, but the regex doesnt (so it won't match in the full string).

We need to change `parseTokenTimezone`, so last two digits are optional.

**Comment by syranide** [comment]
@ichernev Yeah I noticed that, I could submit my PR if you'd like, I decided against just in-case this was intentional (i.e. to work with `ZHHMM` or whatever stupid stuff people shouldn't do ;)).

**Comment by ichernev** [comment]
We're currently in the middle of a rewrite, so don't bother with a PR, we'll have to redo it anyway.

**Comment by ichernev** [comment]
About `ZHHMM` -- regexes are greedy by default, so it would match more if it can. Also if you don't separate your tokens properly its your fault.

**Comment by mj1856** [comment]
@ichernev - I double checked.  We cannot currently parse offsets containing only hours, and they are indeed part of the ISO8601 spec.

The default parser (without format string) doesn't recognize them either.

**Comment by icambron** [comment]
Consolidating to #1723
