### ISSUE TITLE
Incorrect fallback value?

### ISSUE THREAD

**Issue by syranide** [moment/moment#2143]
I stumbled across this while browsing the code...
https://github.com/moment/moment/blob/2.8.4/moment.js#L1167

Specifically `... || []` at the end of `tzChunk`, shouldn't it be `... || ''`?
It doesn't actually matter because `'' + [] === ''`, but it seems like a mistake.

**Comment by ichernev** [comment]
You're right, thank you! We'll fix that in next release.

**Comment by mj1856** [comment]
@ichernev  - I think this one is no longer applicable, right?

**Comment by ichernev** [comment]
@mj1856 yes, I think the existing code is correct.

**Comment by syranide** [comment]
It seems to me that it just moved to another place:
https://github.com/moment/moment/blob/master/moment.js#L1505

Same thing, the result of `match` is an array of strings. It picks a string out of the array and has a fallback array for when there is no string. That can't be right.
