### ISSUE TITLE
.diff takes same two values with same date as being 1 day apart

### ISSUE THREAD

**Issue by lbdi** [moment/moment#2145]
Hi

I have some code which takes the current date and compares it to a value retrieved from a variable

	function readUptime(tenant, status, service, element, uptimeText, statusText) {
		var lastStateChangeTime = moment(status.extinfo.service_info.last_state_change).format("YYYY-MM-DD HH:mm:ss");
		var currentTime = moment().format("YYYY-MM-DD HH:mm:ss");
		var diff = moment(currentTime).diff(lastStateChangeTime); 
		var toInnerHTML = moment(diff).format("DD[d ]HH[h ]mm[m ]ss[s]");
		element.innerHTML = toInnerHTML;

Provided the value YYYY-MM-DD of variable lastStateChangeTime matches the value of variable currentTime, the output of toInnerHTML will always display as follows:

01d 00h 00m 00s

where it should display as

00d 00h 00m 00s

Please advise.

Thanks

**Comment by lbdi** [comment]
To follow up the output out diff is correct, it is the conversion to DD HH:mm:ss which is producing the extra day

**Comment by ichernev** [comment]
Moment doesn't support duration format (what you're trying to do). What you have is a timestamp 1 day after 1970 1st Jan, and then you try to format it as a date.

I suggest you use this plugin made explicitly for the purpose of duration format: https://github.com/jsmreese/moment-duration-format
