### ISSUE TITLE
.fromNow() of future unix timestamp

### ISSUE THREAD

**Issue by Jakobovski** [moment/moment#2146]
Using `.fromNow()`  on a timestamp in the future give the result "a few seconds ago"

**Comment by ichernev** [comment]
```javascript
> moment().add(5, 'h').fromNow()
'in 5 hours'
```

This works in version `2.8.4`. What is your setup?

**Comment by Jakobovski** [comment]
Thanks ichernev. It seems like I can no longer reproduce the bug so I am going to close this issue.

**Comment by objectiveSee** [comment]
I always get "a few seconds ago" if it's less than 1 minute. The docs say it should print "X seconds ago"

**Comment by Jakobovski** [comment]
@objectiveSee I had the same problem. I think its something wrong in the way you are calling it. Are you sure you are using moment objects and not JS Date objects?
