### ISSUE TITLE
Date parsing bug?

### ISSUE THREAD

**Issue by christopherdebeer** [moment/moment#215]
In both Firefox 10.0.2 and Chrome 17 typing the following:

```
moment("Wed Mar 21 2012 11:32:01 GMT+0000 (GMT Standard Time)").toDate()
```

returns:

```
"Thu Dec 21 1899 00:00:00 GMT+0000 (GMT Standard Time)"
```

The Date string passed into `moment()` is obtained by typing `(new Date()).toString()` in the javascript console of the browser. I've checked my system and all the dates are set correctly, but moment interprets the string as 112 years in the past.

Is this a bug in moment.js or is there somethign I've done wrong (I dont think what I've done on my side leaves much room for human error).

This appears when using the version of moment on the homepage of `momentjs.com`

**Comment by nicolashedoire** [comment]
I have a question with moment.js
why the date is not good with the conversion ???

example : user.date = input value = 07/10/1995

var formated_date = moment(user.date).format('DD/MM/YYYY');

formated_date =  06/10/1995

I have the same problem with the tenth month on all lower dates to 1995
it's normal ???? a bug ?
