### ISSUE TITLE
Moment.js Locale & Timezone on Atmosphere.js

### ISSUE THREAD

**Issue by boustanihani** [moment/moment#2151]
Could you also provide (for **Meteor**) an official Moment.js package which includes all translations (**locale**) and mabye also a seperate package for **Moment-Timezone** ?

It would be nice to find all popular moment packages on your Atmosphere channel:
https://atmospherejs.com/momentjs

**Comment by awhitford** [comment]
+1 for `moment-timezone`

I added an issue for that project:  https://github.com/moment/moment-timezone/issues/178

**Comment by cedricmay** [comment]
+1

**Comment by dalgard** [comment]
+1

It would be lovely if we could soon change to the official packages, once and for all. A package like `aldeed:autoform` – one of the most used – is using Timezone in the form of `mrt:moment-timezone` which still relies on `mrt:moment`.

As a result, both packages with each their version of Moment.js are being bundled with my project :/

**Comment by fknipp** [comment]
+1

**Comment by CloneXpert** [comment]
+1

**Comment by mj1856** [comment]
There's some stuff here: https://github.com/rzymek/meteor-moment

But I know literally nothing about Meteor.  Is an external package the right way to handle this, or should it be supported out of the box?

**Comment by tsega** [comment]
@dalgard it looks like the package `aldeed:autoform` is now using the official `momentjs:moment` package as a dependency but it also has [two other "weak" dependencies](https://github.com/aldeed/meteor-autoform/blob/devel/package.js#L16-L18) on `mrt:moment-timezone` and `aldeed:moment-timezone`. These two should be replaced by an official `momentjs:moment-timezone` which should be using the [moment-timezone](https://github.com/moment/moment-timezone) library.

@mj1856 as for the [rzymek:meteor-moment](https://atmospherejs.com/rzymek/moment) package it has the official [momentjs:moment](https://atmospherejs.com/momentjs/moment) package as a dependency (see [es locale](https://github.com/rzymek/meteor-moment/blob/master/locales/es/package.js#L10)) so it should work without any issues.

**Comment by tsega** [comment]
Some good news with the new release of :tada:  **Meteor 1.3** :fireworks:  NPM packages are now 1st class citizens in Meteor! It is actually encouraged now to use [NPM alternatives of popular packages such as Moment](https://youtu.be/7d0xTR-eYh0?t=20m35s) than to use wrapper Atmosphere packages.

**Comment by ichernev** [comment]
@tsega that sounds pretty good. Are there any steps to take to "migrate" the existing moment package from athosphere to pure npm? I had issues publishing the last release anyway, so the smaller the number of individual repositiories to push to on release, the better.

**Comment by jdnichollsc** [comment]
Any example using locale globally with Meteor and ES2015? :)

**Comment by gabimoncha** [comment]
I am using `moment` with Meteor 1.6 and it works just fine. Install it using `npm` not atmosphere. Soon, Meteor will not support atmosphere anytime soon

**Comment by marwahaha** [comment]
Seems like this is done. Regardless, `npm` is the preferred installation method.

If there are still questions or issues, please re-open!
