### ISSUE TITLE
Converting current time to PST using moment.js

### ISSUE THREAD

**Issue by prachicsa** [moment/moment#2152]
I am using the following code to change the current time to PST like this:

var now = moment().tz("America/Los_Angeles").format('YYYY-MM-DD HH:mm:00');
console.log(now);

On an IST machine, it gives me the current time.

But on a machine which has GMT+7, it gives different current time.

On the IST time: 2015-01-09 13:00:00 
it returns: 2015-01-08 23:30:00 (which is correct)

Where as, on GMT+7 machine,
current time: 2015-01-09 07:28:09
it returns: 2015-01-09 06:28:00 (which should have been 2015-01-08 23:30:00)

**Comment by icambron** [comment]
I know this is old, but FWIW, you definitely want to put this ticket in the [moment-timezone](https://github.com/moment/moment-timezone) project, not the moment core one.
