### ISSUE TITLE
How to create customized calendar

### ISSUE THREAD

**Issue by ankitoodles** [moment/moment#2153]
I want to develop a calendar in which user can have much options for marking his availability,non availability,events,others availability,birthdays,meetings,venue details and so many things.

I want to develop it in angularjs.

I have two options :

 1.   Use angular ui calendar and customize html and js files.

    Here I think it will consume so much efforts in customizing the calendar and at some time I may stuck and I will not be available to add more features.

 2.   Develop my own calendar and implement all what I want.

    Here the only problem is I am not sure about how complex the development of calendar is,Because I have to write whole logic like time zone handling,day light savings etc.

So which option is better?

The main thing is calendar will be too complex and flexible.

**Comment by icambron** [comment]
This stuff is outside the scope of Moment, but I'd recommend *not* building your own from scratch. Calendars are complicated and there are a lot of edge cases to handle.
