### ISSUE TITLE
Localized MM/DD/YY

### ISSUE THREAD

**Issue by benbro** [moment/moment#2158]
In some use cases like in HTML table it might be better to use two digit year to save some space.
It will be useful to have a localized MM/DD/YY in addition to the existing 'DD/MM/YYYY'.
Something like LY or LSY could be used.

Thanks

**Comment by philfreo** [comment]
+1

Gmail's inbox view uses this date format, for example.

**Comment by tarang9211** [comment]
Is this issue still open? I'm new around here and would love to learn and help out!

**Comment by tarang9211** [comment]
Hey everyone! Is this still up for grabs?

**Comment by maggiepint** [comment]
This is up for grabs, but it will take some research. I'm honestly not sure if having 2 digit year makes sense in every locale.

**Comment by scottybrown** [comment]
Hi Maggie,
Would you be able to elaborate on your concerns? Wikpedia's page on locales (despite being Wikipedia) seems comprehensive enough. It has some crazy stuff in there, but the year field seems to be either 2 or 4 characters and that's it.
Thus, to me, it seems simple enough to cut the first two characters and call it a day.

**Comment by rheh** [comment]
One assume it is a case of adding the LY an LYS options to each local and adding the default to src/lib/locale/formats.js?  Assuming the LY and LYS options suggested above are acceptable?   What other parts would need updating?  Tests?

**Comment by kylekatarnls** [comment]
What about: `m.format('l').replace(/(\d{2})(\d{2})/, '$2')`? :)

**Comment by ryekerjh** [comment]
@ichernev Are you still the maintainer of this project and as such the dev to contact if we want to contribute? If so, I'd be interested in taking this one on if it hasn't been addressed.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

We will not add any new tokens.

Thanks for all your ideas.
