### ISSUE TITLE
longDateFormat does not fully convert LLL and LLLL tokens

### ISSUE THREAD

**Issue by Eonasdan** [moment/moment#2163]
I use moment in my Bootstrap datepicker plugin. A user brought this to my attention.

Shouldn't `LLL` and `LLLL` tokens get converted to include the time format? As it is `LLL` returns `MMMM D, YYYY LT` instead of the expected `MMMM D, YYYY h:mm A`

```
log(moment().localeData().longDateFormat("LT"));
log(moment().localeData().longDateFormat("LLL")); //<-- should return "MMMM D, YYYY h:mm A"
log(moment().localeData().longDateFormat("LLLL"));//<-- should return "dddd, MMMM D, YYYY h:mm A"
```

http://jsfiddle.net/Eonasdan/5Ld0ycLr/

**Comment by Eonasdan** [comment]
@ichernev any thoughts on this?

**Comment by Eonasdan** [comment]
any response at all would be great

**Comment by Eonasdan** [comment]
@mj1856 ??

**Comment by mj1856** [comment]
Sorry for the delay.  Yes, I agree - this should be fixed.

**Comment by mj1856** [comment]
In the meantime, you can work around it with something like this:

    var localeData = moment.localeData();
    console.log(localeData.longDateFormat("LLLL").replace("LT",localeData.longDateFormat("LT")));

**Comment by ichernev** [comment]
I agree moment doesn't handle the presets very well. It should have date only time only and mixed. But won't this affect all existing users expecting a date only output from LLL and LLL? If you really need just a date, it would be bad to display some random hour next to it or even 00:00 (12am).

I'd be more in favor of adding L*H tokens for that, then we also need time only tokens.

**Comment by jisaacks** [comment]
@ichernev unless I have misunderstood the OP, I believe he was more so just pointing out that `longDateFormat("LLL")` was not fully expanding because it's definition contained another appreviated format `LT`. I don't think he was suggesting changing the actual behavior of the tokens.

However, I do agree with your points.

**Comment by Eonasdan** [comment]
yes my point was that `LLLL` returns another token instead of full expanded. This means that people using the library's longdate tokens must parse LLLL twice.

**Comment by Eonasdan** [comment]
w00t! Thanks for the fix.
