### ISSUE TITLE
Support Intl support

### ISSUE THREAD

**Issue by ichernev** [moment/moment#2167]
There is finally an official JavaScript way to do localization, its called [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) and its pretty well supported [caniuse](http://caniuse.com/#search=Intl).

We might add an `moment.fn.intl` that accepts tokens, and coverts them to `options` argument of `toLocale(Date/Time)String`. We can even fall back to moment locales in case the returned string is empty.

**Comment by jods4** [comment]
+1 including locales is what makes the bulk of the size of moment.

Even with Intl, it's still useful to simplify dates manipulation but it would be great if it used browser APIs and data to localize dates.

Moreover, I know IE uses Win locale data, which is a lot more complete than moment (and also sometimes more accurate).

**Comment by DaSchTour** [comment]
And for the small number of browsers not support Intl there is a pollyfill.
https://github.com/andyearnshaw/Intl.js/
Maybe the i18n part of momentJS could work with the current implementation or Intl depending on configuration?

**Comment by alanhamlett** [comment]
Would also improve accuracy of `moment.tz.guess()` so we don't have to use https://github.com/joeybaker/guess-timezone

**Comment by iilei** [comment]
any updates on this?

**Comment by fourthnen** [comment]
Maybe comment or close this?

**Comment by marwahaha** [comment]
@ichernev  ?

**Comment by Mihailoff** [comment]
NodeJS v14 (LTS from October 2020) has now full-ICU (better Intl support) by default https://nodejs.org/docs/latest-v14.x/api/intl.html

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
