### ISSUE TITLE
moment.locale() throws TypeError

### ISSUE THREAD

**Issue by ewamarciniak** [moment/moment#2170]
I am using moment,js as a bootstrap datimepicker dependency. Unfortunately am getting 
```TypeError: undefined is not a function``` in the console which ultimately prevents the datetimepicker from working correctly. Can you please have a look at this?. Thanks
p.s. I am using gem momentjs-rails for Rails which implements moment.js version 2.9.0.

**Comment by icambron** [comment]
I know this is a super old ticket (I just drop by every once a while, and it looks like the other contributors have been busy too), but we'd need a jsfiddle to have much chance of helping you.

**Comment by mj1856** [comment]
Closing for now.  If you can show us your implementation in a jsfidle, let us know and we'll reopen.
