### ISSUE TITLE
GMT format and timezone

### ISSUE THREAD

**Issue by ferrannp** [moment/moment#2172]
Hello,

I have a REST call giving me timestamps like follows (GMT format)

    "timestamp" : "2015-01-19T16:20:52.000Z",

And then I use 

     moment(timestamp).format('MM/DD/YY hh:mm:ss')

To me the output is different than somebody in a different timezone, I personally see 05:20:52. I want to show the date as it is so... I am not sure, is this converting to my timezone automatically? Is there a way to prevent that conversion?

**Comment by mj1856** [comment]
Yes.

```javascript
moment.parseZone(timestamp).format('MM/DD/YY HH:mm:ss')
```

Note also that you should probably use `HH` (24-hour) and not `hh`  (12-hour)

**Comment by mj1856** [comment]
See also [the docs for `parseZone`](http://momentjs.com/docs/#/parsing/parse-zone/), which describes this behavior.
