### ISSUE TITLE
Format with timezones doesn't work as expected

### ISSUE THREAD

**Issue by MiguelSR** [moment/moment#2173]
Hello, I'm having an issue with moment.js.

I have this in my code:

`moment.tz.setDefault('UTC');`

Then I fetch a date field from my backend and try to convert it to local timezone in the front this way:
`moment(this.model.get('start_date')).tz(USER_TIME_ZONE).format(this.momentDateFormat)`

But it still gives me the same hour as in UTC.

If I do this, it works correctly:
`moment.utc(this.model.get('start_date')).tz(USER_TIME_ZONE).format(this.momentDateFormat)`

So it seems that moment is ignoring the default UTC settings... Writing the prefix function "utc" everytime seems a bit strange so maybe I'm doing something wrong.

Thank you for your amazing library.

Miguel.

**Comment by operf** [comment]
Hi Miguel,

I was having a similar problem and found I was parsing the date wrong. See if this change works for you:

```javascript
var format = 'YYYY-MM-DD HH:mm:ss'; // Your date format used
moment.tz(this.model.get('start_date'), format, USER_TIME_ZONE).format(this.momentDateFormat);
```

See also:
* [Moment Timezone Docs: Parsing in Zone](http://momentjs.com/timezone/docs/#/using-timezones/parsing-in-zone/)

**Comment by ichernev** [comment]
Well, setDefault changes the timezone after the moment is created, and you want to specify that the input string/moment is in utc, for which you have to use moment.utc. Also you might consider what @operf said :)
