### ISSUE TITLE
Suggest optional arguments for setters

### ISSUE THREAD

**Issue by warmsea** [moment/moment#2174]
If it doesn't conflict with the concept of this lib, I hope the setters could have additional optional arguments as the builtin `Date` do. It could be convenient in some cases.

For example,

```javascript
moment().year(yearValue[, monthValue[, dayValue]])
moment().hour(hoursValue[, minutesValue[, secondsValue[, msValue]]])
```

**Comment by ichernev** [comment]
Why not moment().year(y).month(m).day(d). That should work exactly the same as what you're describing. If not -- then its a bug with the individual setters that should be fixed.

**Comment by warmsea** [comment]
There's no bug.

I was just wondering whether a shorter way could be more convenient. I think it won't be confusing since JS Date has already provided them.

```javascript
moment().year(y).month(m).day(d);
moment().year(y, m, d);
```

Please close this issue if it's not necessary. Thank you!

**Comment by icambron** [comment]
There's also moment.set({y: year, M: month, d: day})

**Comment by warmsea** [comment]
Oh, this one is good. Thank you!
