### ISSUE TITLE
How can I display actual seconds instead of 'a few seconds ago'?

### ISSUE THREAD

**Issue by domenicop** [moment/moment#2182]
Is this currently possible?
If not, what function should I look into, to add this behavior?

Bonus question: If I want one minute to be displayed only when it's passed exactly one minute, should I set `moment.relativeTimeThreshold('s', 59);` or `moment.relativeTimeThreshold('s', 60);`?

Thanks.

**Comment by ichernev** [comment]
The code as is right now does not support printing seconds. You have to change https://github.com/moment/moment/blob/2.9.0/moment.js#L1758 also you have to add `ss` to relative time tokens and to relativeTimeThreshold.

If you make it work optionally (i.e. preserve current behavior but make it possible, through changing the thresholds to display seconds, then we can merge it in). Also note that we're in the middle of a refactoring now, so if you write it for the current codebase you might need to rewrite it after we port (next version of moment).
