### ISSUE TITLE
Globals undefined when 'use strict' is applied to locale/*.js files

### ISSUE THREAD

**Issue by abhustoft** [moment/moment#2185]
Browser usage. We do not wish to include all 80 translations in moment-with-locales.min.js, but rather include only a handful of files in locales/*.js These files are minified and are put in a 'use strict' environment.
The locale/*js files in moment.js are not 'use strict' safe. When minified, the code is in a use strict environment and the 'this' object is undefined (and 'global'). This fix adds 'window' as a parameter to the ifees in locale/*js files.

**Comment by ichernev** [comment]
You can package your own by downloading the repo and issuing

```bash
# you'd need node.js installed
# issue from inside the moment.js repo, after you clone it from github.
npm install
grunt embedLocales --embedLocales=fr,de
# check min/moment-with-customlocales.js -- you might want to minify it
```
