### ISSUE TITLE
Strict parser failed on month abbreviation with trailing period 

### ISSUE THREAD

**Issue by Grygir** [moment/moment#2186]
Parser can not deal with trailing period in the token
```javascript
moment.lang('fr', {
    monthsShort : "janv._févr._mars_avr._mai_juin_juil._août_sept._oct._nov._déc.".split("_")
});
var month = moment().format('MMM'); // returns 'janv.'
moment(month, 'MMM', true).isValid(); // returns false

**Comment by ichernev** [comment]
You're right. I once tried making this work and it was tougher than I expected :) You can give it a go after we finish the ES6 port (moment 2.10).

**Comment by ichernev** [comment]
Close in favor of #2782.

**Comment by Grygir** [comment]
Hello,

I see that issues #2782 and #3078 are closed as fixed. And have checked my case with moment 2.15.2, that initially posted here. 

```javascript
moment.lang('fr', {
    monthsShort : "janv._févr._mars_avr._mai_juin_juil._août_sept._oct._nov._déc.".split("_")
});
var month = moment().format('MMM'); // "oct."
moment(month, 'MMM', true).isValid(); // false
moment.version // "2.15.2"
```

Strict date parsing still returns false for months with trailing period.
