### ISSUE TITLE
Creating moment with object/array results in incremented month

### ISSUE THREAD

**Issue by michael-ygt** [moment/moment#2187]
```
var date = moment({ year: 2015, month: 1, day: 1 });
date.month(); // => 1 (zero-based so this should be 0)
date.format("YYYY-MM-DD"); // => 2015-02-01
date.toISOString(); // => 2015-02-01T00:00:00.000Z
```

Same result if using `moment([2015, 1, 1]);` Anyone else notice this?

**Comment by ichernev** [comment]
Well, unfortunately we're backwards compatible with Date here, which treats months from 0 to 11. I don't think we can do anything about that without breaking a lot of code.
