### ISSUE TITLE
moment().set(Object(String, Int)); fails in normalizeUnit

### ISSUE THREAD

**Issue by Crypth** [moment/moment#2189]
As per the documentation i tried to use:
```javascript
moment().set({'year': 2001, 'month': 11}); 
```
which fails in normalizeUnit when trying to lowerCase the object. (undefined is not a function)
```javascript
moment().set('year', 2001).set('month', 11);
```
works as intended though.

**Comment by ichernev** [comment]
It works for me in `2.9.0`. Did you try the latest version?
