### ISSUE TITLE
Omit option to add/subtract

### ISSUE THREAD

**Issue by jmeas** [moment/moment#2196]
I have no idea if this is *actually* a good idea. In fact, it's probably terrible. But I thought I'd suggest it in case anyone thinks it's a good one.

There are [numerous](https://github.com/moment/moment/issues/1281) [requests](https://github.com/moment/moment/issues/1947) to support work days in Moment, but it's a technically challenging problem. The constant-time solution itself is interesting [in and of itself](https://twitter.com/tkellen/status/561392005373509632), but more importantly, work days and week ends aren't the same for every country.

One way to handle this would be a way to omit values when adding or subtracting. This you could simply specify what values you want to include or not include. It could even work for time scales other than days.

I kno, I kno. Bad idea. But I just had to put it out there. :speak_no_evil:

**Comment by ichernev** [comment]
Well, I'm perfectly fine somebody implementing a plugin, that can be fed working days and then handles addWorkdays and subtractWorkdays. This is fairly trivial to implement, but I don't think it has place in core for now.

So you can write one and share it on github ;-)

**Comment by jmeas** [comment]
I made [moment-business](https://github.com/jmeas/moment-business) to do this (-ish). It only works for western work weeks, and only 1/2 of the methods are general enough to be abstracted to be as general as what this issue is describing.
