### ISSUE TITLE
atom-shell html script moment.js is undefined

### ISSUE THREAD

**Issue by polarathene** [moment/moment#2197]
`Uncaught ReferenceError: moment is not defined` appears in the devTools console when I try to use moment within an html page via [atom-shell](https://github.com/atom/atom-shell)(node.js + chromium).

I've tried including the js with these locations:
`<script src="js/moment.min.js"></script>`
`<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>`

Oddly other libs like jQuery and TweenLite work perfectly fine. If I load the html file via the browser moment works like it should, so I'm assuming there is some sort of conflict going on? Or for some reason in atom-shell it has been defined differently?

Still very new to atom-shell, it seems to let you require() node modules via js in the browser/html end. I can probably just use the node package for moment though I'm curious what's causing the issue, would it be similar to the require.js one described on the docs?

**Comment by ichernev** [comment]
I'm not familiar with atom-shell, so you can try to play around with the way moment is exported (amd, nodejs or browser style). The code is at the bottom of moment.js. The new version will use proper UMD wrapper, so hopefully that would work too.

**Comment by ritcoder** [comment]
Just had the same error. The hasModule variable is set to true when running in atom-shell and that causes this error. I swaps the if statement to check for the amd define instead and it worked

**Comment by maggiepint** [comment]
Since we haven't heard back from you and this issue is a year old, i'm going to close it. Feel free to let us know if something needs to be done. We would be happy to re-open.
