### ISSUE TITLE
Validate units

### ISSUE THREAD

**Issue by jmeas** [moment/moment#2199]
Is there a recommended way to validate units? My application accepts a scale as a query param, and I want to handle the user typing invalid scales.

I considered trying to leverage `normalizeUnits` for this, but I'm not sure if it will work:

```js
moment.normalizeUnits('pasta');
// => pasta

moment.normalizeUnits('day');
// => day
```

At the moment I'm hardcoding the accepted values, then seeing if the input value is in the array.

**Comment by ichernev** [comment]
Note that normalizeUnits is also going to handle tokens like `GG` which you probably don't want handled :)

Just write it yourself, and use this list as a reference:

```javascript
['millisecond', 'second', 'minute', 'hour', 'day', 'date', 'week', 'isoWeek', 'month', 'quarter', 'year', 'dayOfYear', 'weekday', 'isoWeekday', 'weekYear', 'isoWeekYear']
```

try removing an `s` at the end and then search case insentitive.
