### ISSUE TITLE
moment(undefined).format("LLL") gives a date 2 days back

### ISSUE THREAD

**Issue by saiyeek** [moment/moment#2200]
This should not be an expected result.

**Comment by mattgrande** [comment]
Strange, I just tried this, and it gave me the current time (which makes sense, kinda). Calling `moment(undefined).isValid()` returns `true`, which seems wrong to me.

**Comment by sudheer594** [comment]
it work fine when it tried, gave the current date.
```JavaScript
moment(undefined).format('LLL')
"February 8, 2015 6:00 PM"
```
@mattgrande `moment(undefined)` returns a valid moment object .
see the line 1690, https://github.com/moment/moment/blob/develop/moment.js
`moment(undefined).isValid()` is correct.

**Comment by ichernev** [comment]
I think this was a PEBCAK :)
