### ISSUE TITLE
Relative Time - Question

### ISSUE THREAD

**Issue by bondz** [moment/moment#2206]
Using MomentJs 2.9.0

```javascript
moment.locale('en', {
    relativeTime : {
        future: "in %s",
        past:   "%s ago",
        s:  "seconds",
        m:  "a minute",
        mm: "%d minutes",
        h:  "an hour",
        hh: "%d hours",
        d:  function (number, withoutSuffix, key, isFuture) {
          return "yesterday";
        }
        dd: "%d days",
        M:  "a month",
        MM: "%d months",
        y:  "a year",
        yy: "%d years"
    }
});
```
I've tried a couple other things too, returning a function inside that function but nothing I've tried works.

How do I get it to return "yesterday" without adding a suffix to it after?

**Comment by ichernev** [comment]
You can just use humanize(false) to prevent the suffix/prefix (`in ...`, `... ago`). You can also overwrite the `pastFuture` function inside the locale to be a no-op (in case you don't have access to the `humanize` call.

```javascript
moment.locale('en', {
  pastFuture: function (diff, output) { return (outtput == "yesterday" ? output : origPostFormat(diff, output); }
});
```
where you can find `origPostFormat` inside `moment.js` (under the name `postFormat`).

**Comment by bondz** [comment]
:+1: Thank you.
