### ISSUE TITLE
businessAdd need attention

### ISSUE THREAD

**Issue by dipeshnepal** [moment/moment#2212]
function getBusinessDate(startDate, daysToAdd) {

        var mStartDate = moment(startDate)
        
        if (mStartDate.isValid() && jQuery.isNumeric(daysToAdd) && isNaN(daysToAdd) == false) {
            var mBDays = mStartDate.businessAdd(daysToAdd);
            return mBDays.format('ddd') + ', ' + mBDays.format('d') + ' ' + mBDays.format('MMM') + ' ' + mBDays.format('YYYY');
        } else
            return "DATE NOT SET"

    }

If I getBusinessDate('2/10/2015',10) i get today's date. Not sure what am I missing. I have tested it before and it looked like it worked right. I am using version 2.9.0.

**Comment by mj1856** [comment]
`businessAdd` is not part of moment.js.  Perhaps you meant to file this as a bug to some plugin?  Please use the issue tracker for that plugin.  Thanks.
