### ISSUE TITLE
moment.utc() is missing .isMoment(obj)

### ISSUE THREAD

**Issue by dotnetCarpenter** [moment/moment#2213]
I'm developing a component and would like to have one reference to moment that I can use in all of my code. It's a calendar that depends on every moment being moment.utc.
Having one reference, prevents calls to moment() _without utc_ to creep in. But moment.utc does not have a isMoment function and perhaps others. So I have to differentiate and watch my step.

``` js
var m1 = moment("1981-04-10");
var m2 = moment.utc("1981-04-10");
console.log(
   moment.isMoment(m1)
  ,moment.utc.isMoment(m1) // throws error
  ,moment.isMoment(m2)
  ,moment.utc.isMoment(m2) // throws error
);
```

**Comment by ichernev** [comment]
That makes sense. We're in the middle of a code rewrite now, so don't write a patch. After we're done (2.10 probably) you can give it a go. For now you can iterate and put the functions you need inside `moment.utc`.

**Comment by dotnetCarpenter** [comment]
@marwahaha honestly it has been 3 years since I had the issue. I don't know how it is with the current version of moment but the issue was about not being able to write a thin wrapper that direct calls to `moment.utc.whatever` but I needed to only use the `.utc.` calls. So the moment API was not that nice to work with since a lot of errors came from a cognitive overhead of remembering when to use `moment.utc.method` or `moment.method`.

**Comment by marwahaha** [comment]
Cool, thanks for the explanation. We have a plan for the next major release of Moment, and hopefully it will resolve some of these issues.

If you'd like this ticket to stay open, just re-open.
