### ISSUE TITLE
Localize time (3:00 pm) using LT into Chinese says 下午3点00

### ISSUE THREAD

**Issue by lucozhao** [moment/moment#2215]
In Chinese, usually it says 下午3点 or 下午3点整 for this case.

Also for the same LT pattern, if the date is 3:06pm, it says 下午3点06, but better to say下午3点06分.

For iPhone in Chinese, it says
下午3:00
下午3:06

**Comment by goodseller** [comment]
I am a Hong Kong person. This is the case for chinese saying.

However, it is better to display it in the written / formal way, i.e.:
"2015年2月14日星期六下午2時44分" / "2015年2月14日星期六下午2時44分", 
for time "Sat, Feb 14, 2015 2:44 PM",

Current version in moment is "2015年2月14日星期六下午2點44" (Chinese Traditional) / "2015年2月14日星期六下午2点44" (Chinese Simplified) are the way we speak.

Thanks.


FYI.

"下午3:00" in english is "3:00pm".
下午 == pm

**Comment by ichernev** [comment]
This is a very hot topic, and there is a pending PR: https://github.com/moment/moment/pull/1911
