### ISSUE TITLE
12-hour clock format isValid with military time?

### ISSUE THREAD

**Issue by stoltene2** [moment/moment#2216]
I'm seeing a strange issue where

`moment('21:35 pm', 'h:mm a', true).isValid()` evaluates to true.

I checked this against
`new Date('2015/01/01 21:35 pm')` which yields an `invalid date`

I feel it should return `false` in this case

I'm seeing this issue in 2.8.3

**Comment by mj1856** [comment]
Agreed

**Comment by ichernev** [comment]
Fixed in 2.8.4: https://github.com/moment/moment/pull/2003
