### ISSUE TITLE
Override moment.parseTwoDigitYear

### ISSUE THREAD

**Issue by arecker** [moment/moment#2219]
I'm trying to change the two year cuttoff from ```68``` to ```16```.

The documentation says

> By default, two digit years above 68 are assumed to be in the 1900's and years below 68 are assumed to be in the 2000's. **This can be changed by replacing the moment.parseTwoDigitYear method.**

This was my attempt:

```javascript
moment.parseTwoDigitYear = function (input) {
    return toInt(input) + (toInt(input) > 16 ? 1900 : 2000);
};
var parsedDate = moment($(id).val());
if (parsedDate.isValid()) {
    $(id).val(parsedDate.format('MM/DD/YYYY'));
};
```

i'm not hitting the breakpoint inside my ```parseTwoDigitYear``` override.  Does anyone have a working example of this?

**Comment by arecker** [comment]
Nevermind.  I was on an older version of moment.  Sorry!

**Comment by arecker** [comment]
I cannot get it to work with version 2.9

**Comment by kashifshamaz21** [comment]
@arecker Following works:
```
moment.parseTwoDigitYear = function (input) {
    return toInt(input) + (toInt(input) > 16 ? 1900 : 2000);
};
moment("20-04-15", "DD-MM-YY").format();
moment("20-04-17", "DD-MM-YY").format();
```
But make sure you define the `toInt` function, it is a moment internal function right now. 
You can close the issue if the above works for you.

**Comment by arecker** [comment]
Thanks for your time!  Works great.

**Comment by kashifshamaz21** [comment]
@arecker awesome :thumbsup: !

**Comment by sapabg** [comment]
Hello, I have a similar problem with parseTwoDigitYear but in Angular 6:

import * as moment from 'moment';

moment.parseTwoDigitYear = function (yearString) {
  return parseInt(yearString) + (parseInt(yearString) > 19 ? 1900 : 2000);
}

And I get "Cannot assign to 'parseTwoDigitYear' because it is a read-only property" :(
