### ISSUE TITLE
Problem with Etc/GMT+X

### ISSUE THREAD

**Issue by IvanGuardado** [moment/moment#2223]
Hi guys! I bring you a problem I'm getting using the library in the client side:

My local time is GMT+1 and I'm experimenting using the Etc/GMT+X transformation. For example:

```js
var d = new Date();
//> d
//< Wed Feb 18 2015 13:15:58 GMT+0100 (CET)
moment(d).tz('Etc/GMT+1').format('h');
//< 11
```
The expected ouput is `1` but I get two hours less. However, if a try with the negative offset:
```js
moment(d).tz('Etc/GMT-1').format('h');
//< 1
```
Is this a bug or am I missing something?

Thanks in advance

**Comment by mj1856** [comment]
This is by design in the tzdb.  See the last paragraph under "Area" in [the Wikipedia article](http://en.wikipedia.org/wiki/Tz_database#Area).  See also [the comments in the tzdb itself](https://github.com/eggert/tz/blob/bc19e5a1e2bd285dbc345016c21250f03bfa6646/etcetera#L29-L35)

**Comment by IvanGuardado** [comment]
Thanks for the info, very useful :)

**Comment by IvanGuardado** [comment]
BTW this is very confusing and you could point it in your documentation IMHO

**Comment by mj1856** [comment]
@IvanGuardado  See also moment/moment-timezone#179
