### ISSUE TITLE
Library conflict

### ISSUE THREAD

**Issue by ggmendez** [moment/moment#2224]
Hi everyone!

I just started to use your library (such an amazing work!) in combination with [fabric.js](http://www.fabricjs.com) on Chrome. For some reason that I still don't understand, the following line of the **makeFormatFunction** function was not working: 

``` output += array[i] instanceof Function ? array[i].call(mom, format) : array[i]; ```

According to my debugging process, the call to the function stored in the array was never executed and, thus, the resulting output was a String concatenating the function definitions and the tokens of the received format string. 

To solve the problem, I had to change this line for: 
``` output += typeof array[i] == "function" ? array[i].call(mom, format) : array[i]; ```

Hope this helps. Again, congrats on the work you have done. This library is amazing!

Cheers,
Gonzalo Gabriel

**Comment by ichernev** [comment]
* So if you remove fiber.js from the project does it work?
* Can you check if `Function` is not redefined?
* Can you execute `var f = function(){}; f instanceof Function` inside fiber.js environment.
* Have you tried latest moment.js 
* have you tried changing the browser?

**Comment by ggmendez** [comment]
There was, indeed, a definition of the Function object. That's why ``` array[i] instanceof Function ``` was always false.

**Comment by icambron** [comment]
Closing. Overwriting `Function` is not a good idea.
