### ISSUE TITLE
Problem with time zone conversions 

### ISSUE THREAD

**Issue by arivazhagan** [moment/moment#2229]
I am having the start and end date as below,

    Start Date: "2015-02-19T00:00:00-08:00"
    End Date: "2015-02-19T17:00:00-08:00"
as you see the date format is in PST so the date is fine in PST time zone,the snippet i am using as below,
```` Javascript
    moment(StartDate).format("MMM Do");
````
 but when i view the same page in IST it shows as below, 

    Start Date: "Feb 19th"
    End Date: "Feb 20th"

Please help me out on this, let me know is there anything i am missing. Thanks in advance.

**Comment by mj1856** [comment]
[Already answered on StackOverflow](http://stackoverflow.com/a/28711673/634824)
