### ISSUE TITLE
Singular for relative times

### ISSUE THREAD

**Issue by bluepioupiou** [moment/moment#2231]
Hi, I use the great feature moment(date).fromNow(), but I would like to display something like "1 hour, 1 month, etc" instead of "one hour, one month". 
I now I can customize this, but I will have to do it for each and every langage ...

Is there another way than customize every langage or can we expect a parameter in the livrary or in the method to choose beetween singular pronoun and just "1" ?

Thanks in advance

**Comment by maggiepint** [comment]
Going to close this due to age. Let us know if you still need help.
