### ISSUE TITLE
Valid date for Feb 31

### ISSUE THREAD

**Issue by epeschier** [moment/moment#2233]
moment([2015, 2, 31]).isValid() returns true

**Comment by kashifshamaz21** [comment]
@epeschier Moment constructor using array, uses 0-based indexing.
From the moment docs: http://momentjs.com/docs/#/parsing/array/ 
```
Note: Because this mirrors the native Date parameters, months, hours, minutes, seconds, and milliseconds are all zero indexed. Years and days of the month are 1 indexed.
```
