### ISSUE TITLE
Two instances that give exactly the same string aren't the same!

### ISSUE THREAD

**Issue by hanifbbz** [moment/moment#2235]
a = moment().set('hour', 2).set('minute', 0).set('second', 0);
    b = moment('020000', 'HHmmss');
    a.format() === b.format();  //true
    a.isSame(b);  //false

A colleague pointed out that `isSame()` compares the dates up to milliseconds when called without an extra parameter. (https://github.com/moment/moment/blob/develop/moment.js#L2438)

So I did a little test:

    a.get('ms');   //123 or some other millisecond at the time 'a' was created
    b.get('ms');   //0

But nevertheless, this is the wrong behavior because:

When b is created, it *takes* the current year, month and day to fill in the missing bits. So it would be unexpected if it doesn't take the milliseconds. Milliseconds are missing from the provided pattern. No big `"S"` in `"HHmmss"`.

**Comment by Jervelund** [comment]
I disagree with your conclusion.

Date is always fetched, but time is never set when you create from string with "time" precision:
If you create with ``b = moment('02', 'HH');`` minutes and seconds are set to 0.
Creating with ``b = moment('02', 'ss');`` leaves hours and minutes set to 0.

Why should only milliseconds be fetched?


In regards to above example:
```
a = moment().set('hour', 2).set('minute', 0).set('second', 0);
b = moment('020000', 'HHmmss');
a.isSame(b,'minute');  //false
a.isSame(b,'second');  //true
a.isSame(b,'mili');  //false -- same comparison as a.isSame(b);
```
And (as provided by your edit)
```
a = moment().set('hour', 2).set('minute', 0).set('second', 0).set('millisecond', 0);
b = moment('020000', 'HHmmss');
a.format() === b.format();  //true
a.isSame(b);  //true
```

**Comment by hanifbbz** [comment]
ok. fair enough. I agree with that logic. Closing it.
