### ISSUE TITLE
Is it possible to set the timezone globally for all moment methods?

### ISSUE THREAD

**Issue by oevna** [moment/moment#2238]
Is it possible, upon page load, to set the timezone (e.g. America/New_York) for moment so that for any of moment's methods from that point have properly adjusted times even if the client computer timezone is set differently?

**Comment by mj1856** [comment]
Yes.  Use the moment-timezone addon, and refer to [these docs](http://momentjs.com/timezone/docs/#/using-timezones/default-timezone/).
