### ISSUE TITLE
[Documentation] Daylight Savings Time is not the correct spelling

### ISSUE THREAD

**Issue by GiraffeSlacks** [moment/moment#2240]
Hello,

This is a minor issue but thought I would report it anyway. The documentation uses both the correct spelling and incorrect spelling for the period known as Daylight Saving Time. The common mistake is to pluralize Saving by adding an `S`.

The incorrect usage appears three times.

**Comment by mj1856** [comment]
Agreed.  I'll correct it.  Thanks.
