### ISSUE TITLE
Allow locale aliases

### ISSUE THREAD

**Issue by NatashaCh** [moment/moment#2241]
Hello, 

Thanks for a great library!!!
Did you consider adding an option for locale aliases? 
(For example, in my application I'm using zh (instead of zh-cn) and would like to use the same name for momentjs by setting an alias for zh-cn)

Thanks!!!

**Comment by icambron** [comment]
This is probably outdated information, but we decided a while back that managing that was too much work (see #896). #1935 is more recent and seems to imply it might eventually be a thing, but honestly, I'm guessing it won't happen. Sorry!
