### ISSUE TITLE
How to convert just the hour from local to UTC and back

### ISSUE THREAD

**Issue by SciGno** [moment/moment#2242]
Hello all and thanks for any help...

I need to convert the day and hour combination from local to UTC and back.  I am getting unexpected results when converting from UTC to local.

Here is the [jsfiddle](http://jsfiddle.net/SciGno/akfeeor2/)

I have read that _d should not be used but that's the only way I've been able to convert from UTC to local.

Any help will be greatly appreciated.

**Comment by mj1856** [comment]
There's very little need to ever pass a `moment` object back into the moment constructor.

To convert from local to utc:

    moment(<some local input>).utc()

To convert from utc to local:

    moment.utc(<some utc input>).local()

**Comment by SciGno** [comment]
Thanks a lot for your help.
