### ISSUE TITLE
Moment with locale return nothing in strict mode parsing

### ISSUE THREAD

**Issue by dsys** [moment/moment#2243]
v 2.9

    var x = moment("26 февраля 2015", "DD MMMM YYYY", true);

x is undefined.

without strict mode its ok.

**Comment by mj1856** [comment]
This appears to be specific to Russian locale.  I tried with English and it works.  Verified it fails with Russian.

**Comment by ichernev** [comment]
Ok, this is problem is pretty serious and touches `sk`, `cs` and `ru` locales.

The short version is: if you add a `monthsParse` function to the locale, you also need to add `longMonthsParse` and `shortMonthsParse`. All 3 locales have only the `monthsParse` function. We might change moment core, but it won't be accurate (because the reason `monthsParse` was added was because there were variants, that a stupid regex won't catch), and it will make all locales a bit slower (one if :-P).

@k2s @petrbela can you please fix the `sk` locale
@petrbela can you please fix the `cs` locale
@Viktorminator, @Oire can you please fix the `ru` locale

**Comment by Oire** [comment]
@ichernev, sorry, didn't get it properly: should I add `longMonthsParse` and `shortMonthsPrrse` functions also?

**Comment by ichernev** [comment]
@Oire yes, you should also add `longMonthsParse` and `shortMonthsParse`.

**Comment by petrbela** [comment]
@ichernev I can't seem to find any reference to `long`/`shortMonthsParse` methods in the code. There's only default [monthsParse](https://github.com/petrbela/moment/blob/master/moment.js#L642-671) which parses the string into `_monthsParse`, `_longMonthsParse` and `_shortMonthsParse`. The `monthsParse` methods in our locales only set `_monthsParse`, so I'm assuming to resolve this issue we need to also assign the other two in the `monthsParse` method?

**Comment by ichernev** [comment]
@petrbela yes, nobody uses short/long month parse, but everyone who uses month parse, should. That is why this issue is created.

**Comment by iamstarkov** [comment]
hi @Oire @ichernev @petrbela, thank you for contribution on this issue. I just came from #2527 and want to ask what is progress for this issue and how can I help you?

**Comment by petrbela** [comment]
@iamstarkov You could fix the Russian locale. And bonus points if you figure out how to fix the strict parse tests. :)

**Comment by iamstarkov** [comment]
@petrbela okie, will try. what about other locales? do you know how many of them has the same issue?

**Comment by iamstarkov** [comment]
few question about testing, I is there any way to run only several tests like in mocha `describe.only` or `it.only`? and is there any mode to run tests in endless watching mode like `mocha --watch`? sorry if it’s stupid questions

**Comment by iamstarkov** [comment]
Why do you need to test moment in the browsers? moment is not using any browsers-specific features

**Comment by iamstarkov** [comment]
Proposing explicit
```
// src/lib/locale/locales.js:49
moment.defineLocale(name, require('./locale/' + name));
// src/locale/en-au.js:6
export default {}
```
instead of emplicit one
```
// src/lib/locale/locales.js:49
require('./locale/' + name);
// src/locale/en-au.js:6
export default moment.defineLocale('en-au', {

**Comment by iamstarkov** [comment]
im stucked =( will try tomorrow again

**Comment by iamstarkov** [comment]
can anybody help me with testing momentjs? and what anybody think about changing implicit require to explicit one

**Comment by petrbela** [comment]
@iamstarkov For the proposed change open a separate issue.

About testing, I'm just running `grunt test`.

**Comment by iamstarkov** [comment]
how do you isolate and run only several tests?

**Comment by ichernev** [comment]
Close in favor of #2634.
