### ISSUE TITLE
Bug in Firefox, time returned as "Invalid Date"

### ISSUE THREAD

**Issue by davesierra** [moment/moment#2244]
I've been trying to parse a timestamp that I get back from Twitter through moment, it works fine in Chrome but fails in Firefox. Instead, my wording for all the tweets in Firefox are shown as "a few seconds ago".

I tried the following in Chrome:
```javascript
moment().format()
|-> "2015-02-27T10:58:55-05:00"
moment('2015-02-27 10:03:06 -0500').format() // a sample timestamp for a tweet returned by Twitter
|->"2015-02-27T10:03:06-05:00"
```
However in Firefox I get:
```javascript
moment().format()
|-> "2015-02-27T10:58:55-05:00"
moment('2015-02-27 10:03:06 -0500').format()
|->"Invalid date"
```

So the question is, is this a Firefox bug? Or should I be formatting the time properly before running it through moment, and if so how?

Thanks.

**Comment by davesierra** [comment]
Looking into it further, I think the problem lies with how the Twitter gem is returning the date (if I try directly on the Twitter API I get a proper format "Fri Feb 27 16:29:23 +0000 2015"). So I'm going to go knock some heads over there.

I suppose this issue could be closed, unless anyone has any other thoughts.

Still it's interesting how the invalid timestamp is parsed correctly in Chrome but not in Firefox.

**Comment by mj1856** [comment]
Since you know the value is returned in a specific format, I recommend you supply the format string.  That will remove all ambiguity and will parse using moment itself, rather than falling back to the browser.

Depending on how you want the output value, use one of the following:

    moment('2015-02-27 10:03:06 -0500','YYYY-MM-DD HH:mm:ss ZZ').format() 
    moment.parseZone('2015-02-27 10:03:06 -0500','YYYY-MM-DD HH:mm:ss ZZ').format() 
    moment.utc('2015-02-27 10:03:06 -0500','YYYY-MM-DD HH:mm:ss ZZ').format() 

Or, if you're coming directly from the Twitter API:

    moment('Fri Feb 27 16:29:23 +0000 2015','ddd MMM DD HH:mm:ss ZZ YYYY').format()
    moment.parseZone('Fri Feb 27 16:29:23 +0000 2015','ddd MMM DD HH:mm:ss ZZ YYYY').format()
    moment.utc('Fri Feb 27 16:29:23 +0000 2015','ddd MMM DD HH:mm:ss ZZ YYYY').format()
