### ISSUE TITLE
Object doesn't support this action - IE8

### ISSUE THREAD

**Issue by bompi88** [moment/moment#2248]
I get this error: "Object doesn't support this action" refering to moment/meteor/export.js at line 3.

I suggest to change this line to something like this:

```js
try {
    delete this.moment;
} catch(e) {
    this['moment'] = undefined;
}
```

@dandv.

**Comment by dandv** [comment]
Funnily enough, @alethes submitted a [patch for that](https://github.com/alethes/moment/commit/80601b93c7c9a3bd4c817779ea74db5abf03214a) two days ago.

**Comment by bompi88** [comment]
Ok, awesome!
