### ISSUE TITLE
Getting wrong offset for the date objects which descends from Nov 2014 

### ISSUE THREAD

**Issue by manihoney** [moment/moment#2255]
For 1 DEC 2014 if convert the date object using moment.tz() it is giving correct offset //example EST -05:00

For 1Nov 2014 if convert the date object using moment.tz() it is giving offset with difference of less than 1 hour. // example EST -04:00

**Comment by icambron** [comment]
That's daylight saving. US Eastern time changes between UTC-5 (EST) and UTC-4 (EDT). In particular, on Nov 2, 2014, it changed -4 to -5. See here:

http://www.timeanddate.com/time/change/usa/new-york?year=2014

DST is crazy, but what you're seeing is correct.

**Comment by manihoney** [comment]
Thanks for the clarification icambron...
