### ISSUE TITLE
Cloning moment object changes date

### ISSUE THREAD

**Issue by Rambomst** [moment/moment#2258]
Using the clone method is causing the date to change in Safari 8.0.3

This is an example of the code I am using.
```
var firstDay = startDate.clone();
var lastDay = endDate.clone();
console.log(startDate);
console.log(firstDay);
console.log(endDate);
console.log(lastDay);
```

This is what it returns:

```
[Log] Moment (daterangepicker.js, line 1095)
_d: Tue Jan 27 2015 00:00:00 GMT+1100 (AEDT)
_i: 1422277200000
_isAMomentObject: true
_isUTC: false
_locale: Locale
_pf: Object
__proto__: Moment

[Log] Moment (daterangepicker.js, line 1096)
_d: Mon Jan 26 2015 12:00:00 GMT+1100 (AEDT)
_i: 1422277200000
_isAMomentObject: true
_isUTC: false
_locale: Locale
_pf: Object
__proto__: Moment

[Log] Moment (daterangepicker.js, line 1097)
_d: Thu Apr 02 2015 00:00:00 GMT+1100 (AEDT)
_i: 1427893200000
_isAMomentObject: true
_isUTC: false
_locale: Locale
_pf: Object
__proto__: Moment

[Log] Moment (daterangepicker.js, line 1098)
_d: Mon Apr 06 2015 01:59:59 GMT+1000 (AEST)
_i: 1427893200000
_isAMomentObject: true
_isUTC: false
_locale: Locale
_pf: Object
__proto__: Moment
```

Am I doing something horribly wrong or is something wrong with moment js?

**Comment by icambron** [comment]
@Rambomst Can you create a jsFiddle that shows this error?

**Comment by danieltartarottisobrosa** [comment]
Only the timezone is not being preserved, but the date is the same, see the _i property. Could you post the _locale property here, so we could see what is the locale that moment is using in the clones.

**Comment by maggiepint** [comment]
I'm going to close this since we haven't heard back from you. Feel free to reopen with us if you're able to reproduce. We would be happy to look at it.

**Comment by dmitin-bv** [comment]
I have the same issue in Chrome. Here is code snippet
var endTime = moment(startTime).add(obj.duration, 'm');
startTime is changed after this. Thanks

**Comment by dmitin-bv** [comment]
Probably I should use something like moment.tz(startTime) since startTime was created using moment.tz? Thanks

**Comment by jnelken** [comment]
@dmitin-bv the .add() method mutates the moment obj it's called on. You should instead do
`moment(startTime).clone().add(obj.duration, 'm');`

**Comment by Cubelaster** [comment]
Similar problem. I am using clone() to clone the object and preserve the value. I am trying to dynamically generate date ranges inside a for loop.
While doing so, I noticed that _d property is correct, however, the _i property remains as old one. 
This can be "hacked" by using next trick:
`var newDate = moment(AppSettings.Formatting.minDate.clone().add(i, 'M').format(AppSettings.Formatting.dateFormat), AppSettings.Formatting.dateFormat);`
Only AFTER explicitly applying format does the new moment.js object acquire new values. 
Using only `AppSettings.Formatting.minDate.clone()` DOES NOT set _i property to correct value. 
![image](https://user-images.githubusercontent.com/14044616/69821289-85f74c80-1203-11ea-8808-a9aa560c6cbf.png)

Am I doing something wrong and what?
