### ISSUE TITLE
daylight saving different results between safari/chrome

### ISSUE THREAD

**Issue by pgherveou** [moment/moment#2260]
Hello

I ran this line in chrome and Safari and I get different result:
Safari seems to be wrong is there a workaround?

In Safari 
moment("2015-03-08 07:30").toDate() => Sun Mar 08 2015 08:30:00 GMT-0700 (PDT)

In Node or Chrome
moment("2015-03-08 07:30"). toDate() => Sun Mar 08 2015 07:30:00 GMT-0700 (PDT)

**Comment by pspEgg** [comment]
Same issue. Using moment.utc("2015-03-08 07:30") fixes this.

**Comment by icambron** [comment]
Looks like a bug in Safari:

```
> new Date(2015, 2, 8, 7, 30) 
< Sun Mar 08 2015 08:30:00 GMT-0700 (PDT)
```

Not much we can do about that, unfortunately; Moment is reliant on the underlying browser knowing what time it is. Safari is chalk full of DST bugs.
