### ISSUE TITLE
Why moment(1000*60*60).format('HH:mm:ss') returns "02:00:00" instead of "01:00:00"?

### ISSUE THREAD

**Issue by adriano-di-giovanni** [moment/moment#2263]
According to [docs](http://momentjs.com/docs/#/parsing/unix-offset/), moment constructor should interpret an integer argument as milliseconds.

```javascript
var
  formatted = moment(1000*60*60).format('HH:mm:ss');

console.log(formatted); // 02:00:00
```

Why `.format()` returns `02:00:00` instead of `01:00:00`?

**Comment by radakovich** [comment]
Take a look at the [UTC](http://momentjs.com/docs/#/parsing/utc/) documentation.  

By default, moment parses and displays in the local time.  My guess is that you are in UTC+01:00.  

`moment.utc(1000*60*60).format('HH:mm:ss')` will give you the `01:00:00` you are looking for.

**Comment by adriano-di-giovanni** [comment]
Thanks, @radakovich
