### ISSUE TITLE
Time zone offset changed by adding a day (but not an hour)

### ISSUE THREAD

**Issue by aj0strow** [moment/moment#2266]
Sorry to add another issue seeing there's so many. One of my unit tests for a countdown timer failed. Adding a day (but not an hour) seems to change the timezone offset. 

```javascript
log( new Date )
log( moment().toDate() )
log( moment().add({ days: 1 }).toDate() )   // here
log( moment().add({ hours: 1 }).toDate() )
```

```
LOG: Sat Mar 07 2015 16:40:51 GMT-0500 (EST)
LOG: Sat Mar 07 2015 16:40:51 GMT-0500 (EST)
LOG: Sun Mar 08 2015 16:40:51 GMT-0400 (EDT)  *** and here
LOG: Sat Mar 07 2015 17:40:51 GMT-0500 (EST)
```

I assume this is unexpected behavior. Let me know what info I can provide, and would be happy to prepare a PR with a little guidance of where to look. Thank you.

**Comment by aj0strow** [comment]
Interestingly enough, now that daylight savings has passed, the problem has disappeared. Not sure what to make of all this.

**Comment by kashifshamaz21** [comment]
@aj0strow Yes, it is due to switch in timezone from Standard to Daylight Saving, happens on second sunday of March - which is Mar 08!
You can close the issue if this is resolved for you. Thanks.
