### ISSUE TITLE
Month representation in arrays seems to start at 0, whereas days start at 1

### ISSUE THREAD

**Issue by datfinesoul** [moment/moment#2270]
When using arrays with moment, or the toArray() method, it seems like months start at 0, whereas days start at 1.  Is this intentional, or a bug?

```javascript
require('moment')([2015, 12, 31]).format()
'Invalid date'
require('moment')([2015, 11, 31]).format()
'2015-12-31T00:00:00-08:00'
> require('moment')('2015-01-31T00:00:00-08:00').toArray()
[ 2015, 0, 31, 0, 0, 0, 0 ]
> require('moment')('2015-01-01T00:00:00-08:00').toArray()
[ 2015, 0, 1, 0, 0, 0, 0 ]
```

**Comment by icambron** [comment]
Yeah, it's unfortunate but intentional. From the documentation:

> Note: Because this mirrors the native Date parameters, months, hours, minutes, seconds, and milliseconds are all zero indexed. Years and days of the month are 1 indexed.
