### ISSUE TITLE
parse natural language

### ISSUE THREAD

**Issue by freder** [moment/moment#2273]
I'm working on s.th. where `moment.duration()` comes in handy, but my input is natural language.

while this works:

```javascript
(moment().subtract( moment.duration({ hours:1 }) )).format();
"2015-03-09T17:04:11+01:00"
```

```javascript
(moment().subtract( moment.duration("1:00") )).format();
"2015-03-09T17:04:11+01:00"
```

this doesn't:

```javascript
(moment().subtract( moment.duration("1 hour") )).format();
"2015-03-09T18:04:11+01:00"
```

it would be nice if this was supported. a bit like [later.js](http://bunkat.github.io/later/parsers.html#text) does it.

**Comment by icambron** [comment]
Hi @freder -- this has come up a few times, and we've consistently decided this kind of natural language parsing is outside the scope of Moment. It would make a great plugin, though!

**Comment by xpepermint** [comment]
It would still be very very nice if we could have english only parser like this: http://bunkat.github.io/later/parsers.html#text

**Comment by mj1856** [comment]
Sugar.js has one.  Thus far, nobody has stepped up to write one for moment.

**Comment by xpepermint** [comment]
Well... they all modify native Date object globally and I had many issues because of that. That's one reason why I like `moment`.

**Comment by mj1856** [comment]
Agreed it would be useful, but it is clearly out of scope for moment core.  A plugin would be welcome.  NLP is difficult, and requires dedication from someone who will maintain it.
