### ISSUE TITLE
How can I force format MMMM to use accusative form in Russian language?

### ISSUE THREAD

**Issue by Yankovsky** [moment/moment#2274]
![html layout](http://i.imgur.com/KLytdwj.png)

I have html layout shown above and I want format month in accusative form, so in this example it should show "марта", instead of "март". I checked source code for ru locale and found this code

```
nounCase = (/D[oD]?(\[[^\[\]]*\]|\s+)+MMMM?/).test(format) ?
    'accusative' :
    'nominative';
```

Can we somehow change regexp here or add param to `format` method?

**Comment by Oire** [comment]
So it does not show in accusative (well, it should be genitive actually) because you have something between `30` and `марта`, right? @mj1856, can we handle such cases somehow?

**Comment by Yankovsky** [comment]
Yes, that's right. Maybe we can add some prefix, check it in regexp and then ignore it during formatting?

**Comment by Yankovsky** [comment]
e.g. `moment().format('genitive#MMMM')`

**Comment by sarman** [comment]
if no other way
moment(dayInfo).format('D MMMM').split(' ')[1];

**Comment by marwahaha** [comment]
@Menelion @Oire - thoughts?

**Comment by marwahaha** [comment]
I'm not sure if this issue is still relevant. 
If this is still desired, please open a new issue with examples.
