### ISSUE TITLE
Parsing months in PL locale in strict mode

### ISSUE THREAD

**Issue by szwacz** [moment/moment#2275]
Hello,

This is the issue I stumbled upon: http://jsfiddle.net/oo0v17xy/
In Polish language there are actually two ways of writing month, both correct (22 march could be '22 marca' or '22 marzec'), and both should be considered valid in strict mode parsing. 

As I can see those variations are already defined in moment.js codebase for polish locale, but not taken into account while parsing.

**Comment by macqm** [comment]
@szwacz : Just wanted to note that '22 marzec' is [not correct either](http://www.pwsz.chelm.pl/poradnia_jezykowa/index_2.php?id_k=4&id_p=111). Only '22 marca' is correct in this example.

There also seems to be an issue with calendar dates. It says 'W niedziela' instead of 'W niedzielę'.

**Comment by szwacz** [comment]
I wasn't even aware that one of those forms is incorrect. BTW, it's not about what is correct, is about what people use.

But still. Form '22 marzec', even though not correct, is very often used in computer world (because Polish language nuances are so difficult to implement).

**Comment by Oire** [comment]
Closed via #2278.

**Comment by savchenkoto** [comment]
I think this issue should be reopened because now when we just want to get months with `pl` locale like that:
```javascript
moment.months()
```
we get this:
```javascript
["(stycznia|styczeń)", "(lutego|luty)", "(marca|marzec)", "(kwietnia|kwiecień)", "(maja|maj)", "(czerwca|czerwiec)", "(lipca|lipiec)", "(sierpnia|sierpień)", "(września|wrzesień)", "(października|październik)", "(listopada|listopad)", "(grudnia|grudzień)"]
```

**Comment by kevinpapst** [comment]
For the next person running into this issue that @savchenkoto reported, you can get the data via `moment.localeData().months();`

**Comment by kevinpapst** [comment]
Any chance that the original author @szwacz could have a look at the bug report #5369?
Fixing it seems to be a no-brainer, but I don't speak polish and should not decide which month names should be taken. Otherwise the original patch should be reverted completely.

**Comment by szwacz** [comment]
Ok, the fix might be easy, but it suggests there is no test coverage for `moment.localeData().months();`? Otherwise I'd get it right the first time.
