### ISSUE TITLE
zh-cn / zh-tw short date format match with CLDR's 

### ISSUE THREAD

**Issue by lreis** [moment/moment#2276]
Hi folks,

I know there has been some discussion [0] around the possible adoption of CLDR data in moment.js, but until that happens, would it be possible to make some changes to bring more consistency? 

Specifically, it would be great if the short date format for zh-cn and zh-tw were updated to:
yy/mm/dd , e.g. 15/3/10

Thanks,
Leandro Reis

[0] https://github.com/moment/moment/issues/315

**Comment by Oire** [comment]
@suupic, @ben-lin, any feedback, please?

**Comment by ben-lin** [comment]
@Oire @lreis I have not worked on this for a while. Would you point out which part of the code you are talking about?

**Comment by Oire** [comment]
@ben-lin, please read the first comment :). @lreis is talking about changing the short date for `zh-cn` and `zh-tw` to `yy/mm/dd`.

**Comment by ben-lin** [comment]
@Oire Yes I saw the first comment but I could not find where the short date comes from in the i18n code base here https://github.com/moment/moment/blob/develop/locale/zh-tw.js 
Or am I missing something?

**Comment by Oire** [comment]
@ben-lin, it's this part:
```js
        L : 'YYYY年MMMD日',
        // ...
        l : 'YYYY年MMMD日',
```

**Comment by ben-lin** [comment]
I don't think it's a good idea to change from `YYYY年MMMD日` to `yy/mm/dd`. It's the whole point of this locale file to have Chinese characters instead of arabic.

**Comment by Oire** [comment]
@ben-lin, OK, thanks! Closing this so far. // cc @ichernev @mj1856
