### ISSUE TITLE
Adding an image to the string date returns invalid date

### ISSUE THREAD

**Issue by andresan21** [moment/moment#2277]
I am getting the date as: ex: 3/11/2011

I am assigning a bunch of dates into an array "U" and then dumping it into a datable.
var resolution = moment(data.d.results[u].Resolution_x0020_Due).format('l hh:mm A');

data.d.results[u].Resolution_x0020_Due = resolution + " < img style='padding-left: 20px;' title='SLA is currently on time' src='sla_good.png'/ > ";

When I want to add and image to that string it returns invalid date. Is there a way to add an image without getting invalid date back?

**Comment by icambron** [comment]
No, the HTML text for displaying an image is pretty much always going to parse to an invalid date. I suggest keeping the image in separate property of `results[u]`.
