### ISSUE TITLE
Uses 'today' when converting to utc using .utc()

### ISSUE THREAD

**Issue by JRMalherbe** [moment/moment#2284]
var date1 = moment().utc("2015-03-11T08:17:26.65") //changes the date to today!
var date2 = moment("2015-03-11T08:17:26.65").utc() //works as expected

**Comment by Karl-Gustav** [comment]
I'm betting that in the first line you're creating a new date for now, and afterwards you're converting it to utc with an string argument that is ignored since the utc function doesn't take arguments.

**Comment by icambron** [comment]
Yeah, I think you mean this:

```js
moment.utc("2015-03-11T08:17:26.65");
```

Notice there's no `()` after the `moment`. What you meant was "create a moment in UTC with this string" but what you said was "create a moment with no args (which means now) and convert it to UTC". Like, @Karl-Gustav said, it ignores the extraneous argument and you end up with today in UTC.

**Comment by JRMalherbe** [comment]
I have read in the release notes that that moment were not going to be
exported as a global anymore, so I used moment() instead on moment. This is
probably where the confusion came in, Sorry, my mistake!
