### ISSUE TITLE
fromNow() wrong if relativeTimeThreshold gets changed? 

### ISSUE THREAD

**Issue by pogopaule** [moment/moment#2289]
Take a look at [this fiddle](http://jsbin.com/wuxitufaqe/2/edit?js,console)

I would expect the third output `"1 minutes ago"` to be `"a minute ago"` instead.

Is this a bug? Should/can I fix it?

**Comment by pogopaule** [comment]
The problem is in [this line](https://github.com/moment/moment/blob/develop/moment.js#L1767). I'm currently working on a PR.

**Comment by icambron** [comment]
A PR would be welcome

**Comment by ichernev** [comment]
Close in favor of #2635.
