### ISSUE TITLE
Should moment.duration constructor support ISO8601?

### ISSUE THREAD

**Issue by jnfeinstein** [moment/moment#2290]
This works:
```javascript
a = moment.duration(26, 'minutes');
b = moment.duration(a.toISOString())
a.asMilliseconds() == b.asMilliseconds() => true
```
If the constructor specifically supports this, can it be added to the documentation?

**Comment by icambron** [comment]
As far as I know, it works well and should be added to the docs. You can submit a PR to them here: https://github.com/moment/momentjs.com

**Comment by mj1856** [comment]
This was added to the docs in moment/momentjs.com/pull/174
