### ISSUE TITLE
moment().set() should accept date formatting

### ISSUE THREAD

**Issue by albertorestifo** [moment/moment#2291]
I have a database that is storing absolute times, in the format `HH:mm`.

When transforming the relative timings to date-specific times, I have to do the following:

``` js
var time = '10:30'; // I would get this from the database
var day = moment();

time = time.split(':');
day.set({
  hours: time[0],
  minutes: time[1]
})
```

Sure it works and it's not such a big deal, but it would be nice if I could use `set` as follows:

``` js
var time = '10:30';

var day = moment().set(time, 'HH:mm');
```

**Comment by ichernev** [comment]
Pull requests welcome

**Comment by albertorestifo** [comment]
:+1: Will look into it

**Comment by albertorestifo** [comment]
@ichernev One thing I'm stuck on, can you point me to the function I need to call internally in order to parse the formatting string? I'm not sure if it's this one: https://github.com/moment/moment/blob/develop/src/lib/format/format.js#L76

**Comment by jtfairbank** [comment]
+1

**Comment by mauron85** [comment]
+1

**Comment by Hugheth** [comment]
+1

**Comment by DRSDavidSoft** [comment]
+1

**Comment by lennerd** [comment]
@albertorestifo Any success?

**Comment by albertorestifo** [comment]
@lashad I stopped working on it in a long time. Particularly now with ES2017 syntax, it's quite clean to do anyway:

```js
const time = '10:30';
[hours, minutes] = time.split(':');
day.set({ hours, minutes })
```

**Comment by lennerd** [comment]
See. Doing the same now. Still think it's nicer to have a set method with a format string. Anyway. Looks like this is somehow solved. 😉

**Comment by sheiktwilight** [comment]
shall i use the following way.?
var time = "10:30";
var day = moment(time, "hh:mm" );

**Comment by albertorestifo** [comment]
@sheiktwilight beware that your example is creating a new date, which by default will be set to today. If that's what you want, then sure, it'll work perfectly.

However this thread is to deal with a difference scenario, where you have an already existing date and want to set a time on it:

```js
const day = moment('2017-08-01');
day.set({ hours: 10, minutes: 30 });
```

**Comment by marwahaha** [comment]
This is available!
https://momentjs.com/docs/#/get-set/set/

**Comment by chrisspiegl** [comment]
@marwahaha I don't see how the initially requested format is now available. It's still a workaround and not a format based input like the question above:

Parsing like the following would indeed be nice (even though easily done otherwise):

```
let time = '12:33';
let mom = moment.set(time, 'HH:mm');
```
