### ISSUE TITLE
Make use of simple-factory

### ISSUE THREAD

**Issue by bmullan91** [moment/moment#2296]
Re: https://github.com/moment/moment/blob/develop/moment.js#L1713-L1716

I have created a module that combats this issue [simple-factory](https://github.com/bmullan91/simple-factory); it might be useful just to create one top-level date factory and reuse it throughout.

If this is something that you agree with I'd be happy to help, and submit a PR.

**Comment by icambron** [comment]
Thanks for the offer to contribute, but Moment doesn't depend on external modules like that. We prefer to keep the lib self-contained, even if it means there's some ugly code in there.
