### ISSUE TITLE
ru locale raises TypeError when parsing date string which includes month name

### ISSUE THREAD

**Issue by hjarvard** [moment/moment#2297]
Hi!
I'm trying to parse date using russian locale, but it raises `TypeError: this._longMonthsParse is undefined`. This error occurs only with month names: `MMM` or `MMMM` format, `MM` format seems to work fine.
Here is [jsfiddle](http://jsfiddle.net/dtpahykx/).

**Comment by mj1856** [comment]
Thanks.  This appears to be a duplicate of #2243
