### ISSUE TITLE
[question] convert to full timeago "x years, y months, z days ago" not only "years/months/days" ago

### ISSUE THREAD

**Issue by flashios09** [moment/moment#2298]
Hi,
Thank you @ichernev for this awesome plugin :+1: 
sorry for my bad english :(

Is it possible to convert a given **datetime** to **full timeago in words** using **Moment.js** like this :

**2015-01-25 03:37:46** to "**2 months, one day, 5 hours and 10 minutes ago**"

Thanks

**Comment by icambron** [comment]
There is not, but there are two plugins to Moment that can help:

https://github.com/jsmreese/moment-duration-format/
https://github.com/icambron/moment-countdown
