### ISSUE TITLE
Cursor option to pre-process results

### ISSUE THREAD

**Issue by paha77** [moment/moment#2299]
Hi,

Is there a way to say to pass a function to the #find method "pre-process" returned documents?

I'd need to convert the result documents to my own Javascript object instead of having them as a standard Object created fron JSON.

Thank you.

**Comment by icambron** [comment]
Moment is a date/time library and doesn't have a `find` method, nor do its methods return documents. Perhaps you created the ticket in the wrong place?

**Comment by paha77** [comment]
I'm so sorry, wanted to post into another repo. :)
