### ISSUE TITLE
Humanize parsing error

### ISSUE THREAD

**Issue by mattiLeBlanc** [moment/moment#2307]
Hi,

I ran into a small issue with duration:

moment.duration( 1025, "seconds" ).humanize()
and
moment.duration( "1025", "seconds" ).humanize()
show different results.
I have to do 
moment.duration( "1025"*1, "seconds" ).humanize()
or parseInt to my value to make sure it is an int.
However, if you set duration to seconds, moment could do this for you.

Cheers

**Comment by mattiLeBlanc** [comment]
I have added a fix: https://github.com/mattiLeBlanc/moment/commit/f56347c3f7236a11f69bf575d989dbe733d333ae

**Comment by ichernev** [comment]
@mj1856 I don't think this is a bug. We do not support string in place of integers in other places in the code (for example month setter in moment). Also we don't have a setter for duration objects, so its not inconsistent with anything.

@mattiLeBlanc I would suggest you make a plugin (for your own project/personal use) that creates duration object after first trying to do `parseInt` on the arguments. That way you won't touch base moment code, so upgrading moment will be hassle free.
