### ISSUE TITLE
Time localization issue

### ISSUE THREAD

**Issue by erdevanshusharma** [moment/moment#2309]
Moment changes "one day" to "a day" and "one hour" to "an hour" while localizing for different languages.
But many apps may not want that and for them can we have a flag or something like that not get this change? Where we can keep "one hour" to "one hour" and not an hour?

**Comment by mj1856** [comment]
You can customize the localization for `relativeTime`, [as shown in the docs](http://momentjs.com/docs/#/customization/relative-time/).  For example:

```javascript
moment.locale('en', {
    relativeTime : {
        future: "in %s",
        past:   "%s ago",
        s:  "seconds",
        m:  "one minute",
        mm: "%d minutes",
        h:  "one hour",
        hh: "%d hours",
        d:  "one day",
        dd: "%d days",
        M:  "one month",
        MM: "%d months",
        y:  "one year",
        yy: "%d years"
    }
});
```

Example after the above change
```javascript
moment().subtract(1, 'day').fromNow();   // "one day ago"
```
