### ISSUE TITLE
moment.duration.fn is missing in 2.10.0

### ISSUE THREAD

**Issue by boskee** [moment/moment#2310]
It seems that moment.duration.fn was removed from 2.10.0 without prior deprecation and yet source code still mentions it:

moment/src/lib/duration/humanize.js:

// helper function for moment.fn.from, moment.fn.fromNow, and moment.duration.fn.humanize

This now breaks a 3rd party plugin and I can't see any workaround to extend duration?

**Comment by ichernev** [comment]
Sorry about that, I guess we didn't have a test for that. I'll fix that and release 2.10.1.

**Comment by boskee** [comment]
No worries :) It didn't seem to be widely used, I guess, but jsmreese/moment-duration-format relies on it.

Thank you.

**Comment by icambron** [comment]
This breaks Twix too.

**Comment by icambron** [comment]
Fixed, thanks @ichernev
