### ISSUE TITLE
Issue with time manipulation / possible daylight saving in safari/mobile safari

### ISSUE THREAD

**Issue by paulduran** [moment/moment#2315]
I have an odd issue with Safari - when I have a date of 2015-04-04 and I try to set the hour to 16, it actually sets it to 17.

this basic example:

```
var m = moment('2015-04-04');
m.hour(16);
console.log(m.format());
```

prints out

```
2015-04-04T17:00:00+11:00
```

I've created a jsbin here: http://jsbin.com/yematocemi/1/edit?html,js,console,output

I suspect that it is related to daylight savings - I'm in Australia (AEST) and the clocks go back an hour at 3am, (back to 2am) on 5/4/2015.

I've reproduced against latest moment.js on both Safari and Mobile Safari and it works fine in Chrome and Firefox

**Comment by paulduran** [comment]
I should also note that, additionally, console.log(moment('2015-04-04T16:00:00').format()); will output "2015-04-04T17:00:00+11:00" in Safari. Replacing the time with T15 (and below) correctly outputs T15 but T16+ are incorrect.

**Comment by icambron** [comment]
Yeah, Safari and Australia are not friends; I suspect this is an underlying bug in Safari. See #1145 (which is more complicated because of the additional iOS twist) and [this](http://stackoverflow.com/questions/14839244/why-is-safari-confused-about-date-getday-for-dst-start-in-sydney-aus-time-zon) SO question.

Can you verify that:

```js
var d = new Date(2015, 3, 4);
d.setHour(16);
d.toString();
```

Also gives you the same issue?

**Comment by paulduran** [comment]
@icambron Yep, it gives the same issue unfortunately.

```
> var d = new Date(2015,3,4)
< undefined
> d.toString()
< "Sat Apr 04 2015 00:00:00 GMT+1100 (AEDT)"
> d.setHours(16)
< 1428127200000
> d.toString()
< "Sat Apr 04 2015 17:00:00 GMT+1100 (AEDT)"
```

I don't suppose there is any fix that moment can do for an underlying safari issue. Shall we just close this issue down?

**Comment by icambron** [comment]
Yeah, unfortunately Moment is completely dependent on the platform's ability to handle dates correctly. The only thing to do is report a bug to Apple.
