### ISSUE TITLE
Error when initializing datetimepicker with defaultDate and inline:true

### ISSUE THREAD

**Issue by christophe** [moment/moment#2316]
Hi there,

When initializing datetimepicker with defaultDate and inline:true, it generates the following error:
"Uncaught TypeError: Cannot read property 'trim' of undefined" at "bootstrap-datetimepicker.js:1492".

Probably because it attempts to test the value of input while it does not have an input in inline-mode.

Best regards,

Christophe

**Comment by icambron** [comment]
Hi @christophe - this is the repository for Moment.js, not a a date/time picker. Perhaps you meant to post this [here](https://github.com/Eonasdan/bootstrap-datetimepicker)?

**Comment by christophe** [comment]
Yes, indeed. Sorry for the mix-up.
