### ISSUE TITLE
Please do not unpublish old versions from the NPM registry

### ISSUE THREAD

**Issue by moretti** [moment/moment#2318]
Hi, I just noticed that moment `2.10.0` and `2.10.1` do not longer exist in the NPM registry. 
I suspect it is because you unpublished them from the registry.
Please don't do that, because it might break some workflows (i.e. `npm shrinkwrap`). 
Perhaps you can use `npm deprecate` instead?

**Comment by icambron** [comment]
Not in charge around here, but I'm guessing the reason is that they broke some user code.

**Comment by ichernev** [comment]
Sorry for that. If they were removed, they were seriously broken. I'll use deprecate from now on.

**Comment by moretti** [comment]
Thanks, @ichernev. :+1: 
I'm closing the issue.
