### ISSUE TITLE
Moment.js deprecation (global state) is breaking on 10.0

### ISSUE THREAD

**Issue by merriam** [moment/moment#2322]
The deprecation of the global object for moment.js should be marked "Here there be dragons".

Moving from the 0.9 to 0.10 means that things break for our complicated build system which uses moment from None in the GruntFile and lots of ecmascript that is occasionally translated to older javascript.  Aside from reverting to 0.9.0 to go back to running, we haven't played with all the moving parts.

One odd spot, is that the GruntFile.js, which has just a  `var moment = require("moment");` suddenly stopped being able to find moment .  We are running a couple outdated grunt plugins, but I doubt that's the cause:

─┬ grunt@0.4.5
│ ├─┬ grunt-legacy-log@0.1.1
│ ├── grunt-legacy-util@0.2.0
├─┬ grunt-connect-proxy@0.1.10
├─┬ grunt-contrib-clean@0.6.0
├─┬ grunt-contrib-compress@0.12.0
├─┬ grunt-contrib-connect@0.8.0
├─┬ grunt-contrib-copy@0.7.0
├─┬ grunt-contrib-less@0.11.3
├─┬ grunt-contrib-watch@0.6.1
├── grunt-cordovacli@0.5.1
├── grunt-express-server@0.4.19
├── grunt-less-imports@0.9.1
├─┬ grunt-notify@0.3.1

The second are those odd deprecation warnings in the browser.  We are running a SPA with CanJS, Steal.JS, Bower, and a host of players.   We get the "Accessing Moment through the global scope is deprecated, and will be removed in an upcoming release" error, which might be related.  The files generally grab moment using `import moment from 'moment';`   We often use it like `return ((now - moment(value)) < check);` or `moment.duration(20, 'minutes').asMilliseconds()`.  

So, why does a minor release break things?   How exactly is a deprecation originally tagged as something for the node global space causing issues?  I don't know.  It takes a human-hour just to get the systems into a state with an upgraded moment@2.10 to run tests; so I pass on experiences here without detailed diagnostics.

Given the behavior, anything is possible.  Watch for dragons.

**Comment by wyantb** [comment]
I don't really understand.  I performed the following steps and saw no error.  Can you be more specific?

$ **echo "var mom = require('moment');console.log(mom().format('LLLL'));" > index.js**
$ **node index.js**
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/brian/repos/pie/index.js:1:73)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```
$ **npm install moment --save**
```
npm http GET http://registry.npmjs.org/moment
npm http 304 http://registry.npmjs.org/moment
moment@2.10.2 node_modules/moment
```
$ **node index.js**
Friday, May 8, 2015 8:48 PM

-----

(That is to say, I navigated to a new/empty folder, created a JS file which loaded moment and demonstrated that the load failed, installed moment into that folder, reran the script, and it printed out something intelligible)

**Comment by marwahaha** [comment]
Let us know if there's something we can help with @merriam

**Comment by merriam** [comment]
Thank yiou marwahaha.  This is now two years old.   I've long sense moved on.
