### ISSUE TITLE
Year changing between 20** and 19** when formatting

### ISSUE THREAD

**Issue by liam-swinney** [moment/moment#2324]
Hi there,

I was experiencing issues with the year format within a date of birth field I have set up.  Years between 97-69 would output correclty, however 68 and below would output 2068 etc.

I tested this in the console as well:
var test = moment('25/02/69', 'DD/MM/YY');
test.format();
output: "1969-02-25T00:00:00+00:00"

var test1 = moment('25/02/69', 'DD/MM/YY');
test1.format();
output: "2068-02-25T00:00:00+00:00"

I've been able to change our expected format to YYYY which is working fine,  but for some people that might not be able to change the data coming in this might be a big problem

**Comment by heroldvandervegt** [comment]
Look for parseTwoDigitYear(). The 'break year' between 19xx and 20xx is defined there as 68. If you change it to 20, your conversion period will change to 1921-2020 in stead of 1969-2068

**Comment by icambron** [comment]
Yeah, the trouble with "YY" is that it doesn't tell us the century; the best we can do is guess. Right now that guess is that dates under 68 are this century, not the last one.

Fortunately, like @heroldvandervegt said, it's pluggable:

```js
moment.parseTwoDigitYear = function (input) {
  return +input + (+input > 15 ? 1900 : 2000);
};
```

**Comment by liam-swinney** [comment]
ok fair does, thanks for getting back to me
