### ISSUE TITLE
addRegexToken

### ISSUE THREAD

**Issue by lockedscope** [moment/moment#2325]
Androd 2.3.3 stock browser reports typeof Regex object(/../) as function and so its added to regexes array by addRegexToken and tried to be called as a function which fails and whole moment parsing from a valid iso string fails. I heard there are some browsers that also report typeof Regex object as function.(http://stackoverflow.com/questions/5054352/why-use-typeof-for-identifying-a-function)
So, this needs to be fixed.

 function addRegexToken (token, regex, strictRegex) {
        regexes[token] = typeof regex === 'function' ? regex : function (isStrict) {
            return (isStrict && strictRegex) ? strictRegex : regex;
        };
    }

**Comment by mj1856** [comment]
Not sure I'm following.  What precisely is the proposed change?

**Comment by lockedscope** [comment]
it must be checked if it is really a regex object.

**Comment by lockedscope** [comment]
And if it is really callable.

**Comment by lockedscope** [comment]
So, it should be like this;
```javascript
function addRegexToken (token, regex, strictRegex) {
	regexes[token] = typeof regex === 'function' && !isRegExp(regex) ? regex : function (isStrict) {
		return (isStrict && strictRegex) ? strictRegex : regex;
	};
}

function isRegExp(input) {
	return Object.prototype.toString.call(input) === '[object RegExp]';
}
```

**Comment by lockedscope** [comment]
So,following calls could be distinguished from RegExps reported as function.
'''javascript
    addRegexToken('Do', function (isStrict, locale) {        return isStrict ? locale._ordinalParse : locale._ordinalParseLenient;    });
'''

**Comment by mj1856** [comment]
Got it.  So this is primarily for compat with older browsers that incorrectly report regex as `function` instead of `object`.  Sounds reasonable to me, though I'd suggest a single function:

```javascript
function isFunction(input) {
    return typeof input === 'function' && Object.prototype.toString.call(input) === '[object Function]';
}
```

**Comment by ichernev** [comment]
@lockedscope can you please double check if the change mj1856 proposed fixes your problem? If yes, we'll merge it, if no -- we'll have to work around in some other way (different `addRegexToken` functions, a boolean flag, etc).

**Comment by lockedscope** [comment]
yeah the change proposed by mj1856 fixes the problem.
