### ISSUE TITLE
German dates and timezones

### ISSUE THREAD

**Issue by meivin123** [moment/moment#2326]
Hello,
I'm trying to use moment.js with german dates but the following problem occurs:
For example I use the Date (YYYY-MM-DD) 2015-05-15 and the following code:
```html
<script type="text/javascript" src="bower_components/moment/moment.js"></script>
<script type="text/javascript" src="bower_components/moment/locale/de.js"></script>
```
```javascript
var d = moment("2015-05-15", "Y-m-d", "de", true);
d.format("YYYY/mm/DD");
```
Format outputs: 2015-05-12
Im using PHP to calculate the date (PHP uses timezone "Europe/Berlin").

How can i fix this?

**Comment by mj1856** [comment]
Pay close attention to the input and output format strings.  They are case sensitive, and different than PHP.


    var d = moment("2015-05-15", "YYYY-MM-DD");
d.format("YYYY/MM/DD");
