### ISSUE TITLE
toDate() Ignores time zone

### ISSUE THREAD

**Issue by ykurtbas** [moment/moment#2327]
Unfortunately setting the time zone global for moment objects does not affect the JS date since it uses timestamp to create the time, so we lose the timezone

```javascript
moment()
Moment {_isAMomentObject: true, _isUTC: false, _pf: Object, _locale: Locale, _d: Tue Apr 14 2015 16:13:14 GMT+0100 (GMT Summer Time)…}
moment.tz.setDefault('Europe/Istanbul');
global.js:15 function utils_hooks__hooks() {
        return hookCallback.apply(null, arguments);
    }
moment()
Moment {_isAMomentObject: true, _isUTC: true, _pf: Object, _locale: Locale, _d: Tue Apr 14 2015 19:13:26 GMT+0100 (GMT Summer Time)…}
moment().toDate()
Tue Apr 14 2015 16:13:33 GMT+0100 (GMT Summer Time)
```

https://github.com/moment/moment/blob/develop/src/lib/moment/to-type.js#L10

```javascript
export function toDate () {
    return this._offset ? new Date(+this) : this._d;
}
```
workaround

```javascript
moment.fn.toJsDateWithTimezone = function() {
  return new Date(this.year(), this.month(), this.date(), this.hour(), this.minute(), this.second(), this.millisecond());
};
```

**Comment by mj1856** [comment]
The workaround is invalid, and can get you into serious trouble.

The `Date` object is *always* in the time zone of the machine where it is running.  No amount of manipulation will change that.  Moment has a distinct advantage in that it can encapsulate custom functionality with JavaScript, but `Date` is a *native* object.  It's behavior cannot be changed.

Mutating the values passed into the date object will just make the object represent a *different* moment in time.  The time zone rules of the local time zone will still impact that time.
