### ISSUE TITLE
Add dates to changelog?

### ISSUE THREAD

**Issue by philfreo** [moment/moment#2330]
Just a minor request: start adding dates next to the version numbers in https://github.com/moment/moment/blob/develop/CHANGELOG.md. Can be helpful when you know roughly when you last upgraded but don't remember version numbers.

**Comment by mj1856** [comment]
The dates are already available [on the releases tab](https://github.com/moment/moment/releases), but I agree - having them in the changelog would be helpful as well.

**Comment by pranjalk** [comment]
Hi! I added release dates in the changelog and created pull request [#3322](https://github.com/moment/moment/pull/3322)

**Comment by marwahaha** [comment]
This has been resolved :-)
