### ISSUE TITLE
moment().fromNow() for age verification inaccurate

### ISSUE THREAD

**Issue by jgoldsmith83** [moment/moment#2331]
It seems fromNow() only calculates the difference based on the year? This is providing inaccurate difference. Is there a parameter I'm missing?
Check my method here: https://github.com/jgoldsmith83/7-Crimes/blob/master/index/index-scripts.js
Let me know if I'm using it wrong or missing something.

**Comment by mj1856** [comment]
`fromNow` is for a human-readable estimation string.  I strongly recommend against using it for calculating age from a date of birth.

I wrote about this awhile back from a C# perspective: [Handling Birthdays, and Other Anniversaries](http://codeofmatt.com/2014/04/09/handling-birthdays-and-other-anniversaries/).

For JavaScript with moment, this should work well:

```javascript
function calculateAge(s)
{
  var bday = moment(s + " 12:00", "YYYYMMDD HH:mm");
  var today = moment().startOf('day').hour(12);
  var age = today.year() - bday.year();
  if (bday > today.subtract(age, 'years'))
    age = age - 1;
  return age;
}

var age = calculateAge('19760827'); // my age!
```

The trick of using noon is to avoid implementation variations with regard to daylight saving time.

If you read my blog carefully, you'll realize I said you needed a time zone.  But in this case, the code is running in the user's browser, so it is already reflecting the user's time zone.

**Comment by mj1856** [comment]
FYI - the above is essentially a JS port of [this post](http://stackoverflow.com/a/1404/634824).

**Comment by mj1856** [comment]
Here's a cleaner form of the function above:

```javascript
moment.fn.calculateAge = function()
{
  var date = this.startOf('day').hour(12);
  var today = moment().startOf('day').hour(12);
  var age = today.year() - date.year();
  if (date > today.subtract(age, 'years'))
    age = age - 1;
  return age;
}
```

Example usage:

```javascript
moment('1976-08-27').calculateAge()   // 39
```
