### ISSUE TITLE
Numerical Values to handle "MMM-DD-YYYY" format

### ISSUE THREAD

**Issue by MassielCuba** [moment/moment#2332]
Hello,

This is the issue I ran into: http://jsfiddle.net/Massiel/ns4dj4oL/4/
Even though the moment for ("5-5-2015" , ["MMM-DD-YYYY"]) is recognized as valid, the month on the actual object is always set to January.

Are you guys supporting this case; or maybe there is a bug with the parseTokenWord regex to handle it, so the month's value is not being added properly to the token array. 

Best Regards,

Massiel

**Comment by mj1856** [comment]
`MMM` maps to a month abbreviation, such as `May`, or `Jan`.  For numerical months, you should pass `M` or `MM`.

For parsing, it doesn't matter if you use `M` or `MM`.  But for formatting, the second letter would indicate you wanted the output to pad a zero for single-digit months.  The same applies to `D` and `DD`.
