### ISSUE TITLE
create moment-with-customlanguages is failing

### ISSUE THREAD

**Issue by webmutation** [moment/moment#2335]
On 2.9 the following command works ´
grunt uglify embedLocales --embedLocales pt

Running "uglify:main" (uglify) task

> > 3 files created.

Running "uglify:customlocales" (uglify) task

> > 1 file created.

Running "embedLocales" task

Done, without errors.

but on 2.10.2 using the same command, returns the following 

Running "embedLocales" task
Warning: Cannot read property 'targetLocales' of undefined Use --force to continue.

using --force does not create a moment-with-customlanguages

**Comment by HenriqueSilverio** [comment]
Same here. +1

**Comment by wyantb** [comment]
In 2.10, you'll want the transpile tasks, mentioned in https://github.com/moment/moment/blob/develop/CONTRIBUTING.md#grunt-tasks

For good measure, something like `grunt transpile:de,es,fr update-index uglify` should do the trick from a clean repo.

**Comment by Techbrunch** [comment]
Thanks, this page should be updated then: http://momentjs.com/docs/#/i18n/loading-into-browser/

**Comment by marwahaha** [comment]
Closing due to age. Hopefully everyone has what they need now and the docs discuss the `transpile` task.
