### ISSUE TITLE
How to set datetimepicker range title with variables

### ISSUE THREAD

**Issue by bilaliqbalr** [moment/moment#2339]
I want to set variable in place of range JSON key (titles). Like
ranges: {
			today : [moment(), moment()],
			yesterday : [moment().subtract('days', 1), moment().subtract('days', 1)],
			lastSevenDays : [moment().subtract('days', 6), moment()],
			lastThirtyDays : [moment().subtract('days', 29), moment()],
			thisMonth : [moment().startOf('month'), moment().endOf('month')],
			lastMonth : [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
		}
There all keys are variables. And i want the values of that variables to show...

**Comment by AustinBGibbons** [comment]
Hey, you might be interested in this library for working with range in moment: https://github.com/gf3/moment-range

**Comment by bilaliqbalr** [comment]
No, Let me clear it again.
I set variable for ranges like
var today = 'Today';   // For english
var today = '(today in french)';  // For french
means i use "today" variable to display title in different languages. But jquery fetch variable "today" as title in dropdown. Not value of that variable.
