### ISSUE TITLE
moment().unix() works in Chrome but not in Firefox

### ISSUE THREAD

**Issue by arian-hosseinzadeh** [moment/moment#2340]
^^
Try this: moment('Jul 2015').unix() under both chrome and firefox

**Comment by mj1856** [comment]
This is by design.  Anything other than the standard ISO formats fall back to the browser's implementation unless you provide a format string.

```Javascript
moment('Jul 2015','MMM YYYY').unix()
```

**Comment by mj1856** [comment]
The above reference was a typo in the issue number.  This is not related to 205.
