### ISSUE TITLE
duration parsing question 

### ISSUE THREAD

**Issue by amit777** [moment/moment#2341]
I wanted to parse strings like this from youtube and vimeo's time duration:
"7:52"  = 7 minutes, 52 seconds

moment.duration("7:52") assumes 7 hours and 52 minutes.  Is there a simple built in way where the following would convert:
"15" = 15 seconds
"12:15" = 12 minutes, 15 seconds
"7:12:15" = 7 hours, 12 minutes and 15 seconds.

I'm using the latest nodejs npm package (2.10.2)

**Comment by icambron** [comment]
Moment doesn't offer duration parsing except for ISO strings or ASP.net strings. I recommend just doing it yourself, like

```js
var s = "7:52".split(":");
moment.duration(m: s[0], s: s[1]);
```
