### ISSUE TITLE
There doesn't seem to be a way to handle either 2 or 4 digit years

### ISSUE THREAD

**Issue by stewartml** [moment/moment#2343]
I feel that the following snippet:

    moment('23/4/14', 'D/M/YYYY')

ought to return the date `2014-04-23` (using ISO for the avoidance of doubt), but instead it returns `0014-04-23`, which is pretty unlikely to have been what the user intended.  

The opposite way round:

    moment('23/4/2014', 'D/M/YY')

gives you `2020-04-23`, which isn't likely to have been what the user meant either...

To maintain backwards compatibility, perhaps there should be another format specifier, e.g. a single `Y` that doesn't care whether it gets a 2 digit year or a 4 digit year, and returns something sensible either way.

I.e., I want to be able to parse the user input and not care whether they used a 4 digit year or a 2 digit year, and use some sensible rules to return the date the user expected.

**Comment by mj1856** [comment]
:+1: This would be a very good feature.

**Comment by stewartml** [comment]
Cool, thanks.  Any idea when it might appear?

**Comment by mj1856** [comment]
We're all volunteers here, so its hard to pin a timeline on anything.  If it's urgent for you, feel free to make the modifications yourself and send a pull request.  Thanks.

**Comment by stewartml** [comment]
Sorry if that sounded like hassling, it wasn't my intention.  Yes, I normally would have made a pull request already actually, but it's going to take me a little while to understand what to change on this one!

If I get there before you I'll submit a pull request :)

**Comment by mj1856** [comment]
:smile:

**Comment by icambron** [comment]
Very odd; I could have sworn this would default to use 2000.

**Comment by mj1856** [comment]
If we are to take that approach, then should't it use the `moment.parseTwoDigitYear` function?  Currently, only `YY` will enter that function at all.  We would need to change the parser to call whenever a two-digit year is present, regardless of being used with `YY` or `YYYY`.   This may also have a small perf impact.

**Comment by ppoisson** [comment]
In Firefox using moment("6/12/15").format("M/D/YYYY h:mm:ss A") I get 6/12/1915 in stead of 2015?  How do I fix this?

**Comment by icambron** [comment]
@ppoisson parse it with an explicit format string as the second arg; right now you're just using the native `Date` constructor.

**Comment by ppoisson** [comment]
Thanks!

**Comment by lizzzzard** [comment]
Would love to see it to, maybe as an additional langue-aware format. I'm currently using "l" and "L", but both use 4-digit-years, so I have to do manual checks for those formats additionally - which makes the locale-aware-formats kind of useless to me.
