### ISSUE TITLE
How do I convert iso-8601 duration to seconds?

### ISSUE THREAD

**Issue by alexbooker** [moment/moment#2346]
Hello. I have a small question, but before I ask, I just want to let you guys know that this is an awesome library - great work!

My question is: How can I convert an iso-8601 duration ("PT15M51S") into seconds? I tried this:

```JavaScript
var moment = require('moment');
var duration = 'PT15M51S';
var x = moment(duration, moment.ISO_8601);
console.log(x.seconds());
```
But it prints "NaN". Any ideas? Thank you.

**Comment by alexbooker** [comment]
Never-mind. I figured it out:

```JavaScript
var moment = require('moment');
var duration = 'PT15M51S';
var x = moment.duration(duration, moment.ISO_8601);
console.log(x.asSeconds()); // => 951
```

**Comment by farooqahmedkhan** [comment]
Correction, in case someone like me lands on this for conversion help

```moment.duration('PT01', moment.ISO_8601.__momentBuiltinFormatBrand).asSeconds()```
