### ISSUE TITLE
UTC hours() reports unexpected hours

### ISSUE THREAD

**Issue by mscappini** [moment/moment#2348]
Hello all! I'm sure you get a bunch of these questions all the time, but I'm sort of stumped. And I would guess I'm missing something simple.

Here's my simple code:

    var expiryMoment = moment.utc(new Date(expiry));
        
    // Set the beginning of the day.
    var expiryBegin = expiryMoment.clone();
    expiryBegin.hours(0);

`expiry` variable is a string with no time and no timezone--only a month/day/year. But I am using utc and that gives me 0 hours. So far, so good.

However, calling `expiryMoment.hours()` gives me 7. I am UTC-08:00.

Before setting the hours, `expiryMoment.format()` gives me "04/17/2015 00:00:00". After setting the hours to 0, the `expiryMoment.format()` method gives me "04/16/2015 17:00:00". Shouldn't it just do nothing?

Many thanks.

**Comment by mj1856** [comment]
Assuming you are in the Pacific time zone, it's currently UTC-07:00 due to daylight saving time.  We will return to UTC-08:00 on November 1st.

Also, I'd recommend not using the `Date` constructor.  Instead, let moment parse the string for you directly, and supply a format specifier.   For example, if the input is in UTC already, then use `moment.utc('4/27/2015','M/D/YYYY')`.  Or, if the string is in local time and you want to *convert* to UTC, use `moment('4/27/2015','M/D/YYYY').utc()`.

**Comment by mj1856** [comment]
Also, I couldn't reproduce your last statement.  Calling `hours(0)` on the clone did not affect the original.

![image](https://cloud.githubusercontent.com/assets/1396388/7350971/43ac1d68-ecb7-11e4-81ae-2caa40abb74a.png)

**Comment by mscappini** [comment]
Hi Matt, thanks for responding.

Concerning the UTC-07:00, I understand this to be correct.

Concerning the `hours()`, it looks like I said the wrong variable. I was going for the fact that setting executing `expiryBegin.hours(0)` causes `expiryBegin.hours()` to return 7. But I double checked that just now and it seems it was *always* returning 7. This appeared to be happening because of how I was constructing the `moment`. Changing it as you suggested now forces the moment into UTC. However, it was really weird because the constructor I *was* using was causing the `moment` to report that it was still in UTC mode, but returned 7. I'm guessing it used `Date.parse()` to parse the date into local timezone, then `moment` picked up that local date as UTC when I told it to do so. Which all makes sense.

I didn't realize I could use that constructor. When I tried to pass the string with no date format, it gave me a warning to switch away from that method. Thanks for pointing out the correct constructor.

My only question now is: how do I get the date out of `moment` as UTC? I would like to pass that into Mongo as UTC (since Mongo just uses UTC), but doing `expiryBegin.toDate().toString()` gives me the local day/hour.

**Comment by mj1856** [comment]
No problem.  Glad to help! :)

The easiest way to get what you're looking for is `expiryBegin.toISOString()`.

In general, try to resist the temptation to use the `Date` object whenever possible. :)
