### ISSUE TITLE
html time element use case

### ISSUE THREAD

**Issue by kaihendry** [moment/moment#2349]
Be good if there was a canonical example how to use it in conjunction with uses of https://html.spec.whatwg.org/multipage/semantics.html#the-time-element

For example is there a non-jquery example that simply presents any time element with dateTime= defined in a web page? Something better than my own: view-source:http://bus.dabase.com/

**Comment by mj1856** [comment]
Sounds like a good topic for a blog article.  Feel free to write one. :)

**Comment by mitar** [comment]
Yes, I am also curious how to use moment.js to represent only time.

**Comment by marwahaha** [comment]
Closing due to age. please re-open if you would still like this.
