### ISSUE TITLE
The code generator has deoptimised the styling of moment.js as it exceeds the max of "100KB"

### ISSUE THREAD

**Issue by ppiekarczyk** [moment/moment#2350]
Moment.js comes OOTB in [KeystoneJS](http://github.com/keystonejs/keystone)

This error started cropping up after the ES6 switch. I've found this SO link for reference:
https://stackoverflow.com/questions/29576341/what-does-the-code-generator-has-deoptimised-the-styling-of-some-file-as-it-e

Is there anything I can do to avoid this from happening?

**Comment by ichernev** [comment]
The SO link has a solution, it doesn't work? I haven't seen this from happening, and I'm not completely sure how to reproduce. So maybe you can debug yourself, contact KeystoneJS and figure out what change should we do to moment to fix it (if any).

But if you suggest we reduce the size of the library down ... I don't see how this can happen :) Another approach will be to tell the library to chill.

**Comment by ppiekarczyk** [comment]
I think this has been figured out. Thanks
