### ISSUE TITLE
`Infinity`as a date

### ISSUE THREAD

**Issue by blakmatrix** [moment/moment#2351]
<sub><sup>I know this might seem counter intuitive to the library as is and you may not decide to do anything about it, but I was surprised to find that you don't support `Infinity` type, I know in some cases in this library that could prove to be problematic, such as format, etc.. </sup></sub>

If you pull down from PostgreSQL a date value of `Infinity`, The use case I was hoping to use is as such; `moment(myVal).isBefore(Date.now())` where `myVal` could be any date from `-Infinity` to `Infinity`.

What we get though right now is:
```js
> moment(Infinity).isBefore(Date.now())
false
> moment(Infinity).isAfter(Date.now())
false
> moment(-Infinity).isBefore(Date.now())
false
> moment(-Infinity).isAfter(Date.now())
false
```
Expected:
```js
> moment(Infinity).isBefore(Date.now())
false
> moment(Infinity).isAfter(Date.now())
true
> moment(-Infinity).isBefore(Date.now())
true
> moment(-Infinity).isAfter(Date.now())
false
```

**Comment by icambron** [comment]
Moment is a wrapper for the native date library, so we need to be able to translate any date into a JS date. JS's date time libraries don't do infinity (or beyond!):

```js
> new Date(1430527548018)
Fri May 01 2015 20:45:48 GMT-0400 (EDT)
> new Date(Infinity)
Invalid Date
```

Hence:

```js
>moment(Infinity).isValid()
false
> moment(Infinity).format()
"Invalid date"
```

I suppose it would be possible for Moment to have special dates that don't correspond to underlying JS dates. But that would require a lot of code to support, and I'm pretty confident it's out of scope for Moment.

**Comment by fatuhoku** [comment]
... I too would like to work with Infinite dates :/

**Comment by scipper** [comment]
What about a small work around.

Define a global variable `var Infinite = 1e15` and use it instead of `Infinity`. With 1e15 you will get the last valid date of `Fri Sep 27 33658 03:46:40 GMT+0200` (in my case).

```javascript
> moment(Infinite).isValid()
true
```

**Comment by mindfullsilence** [comment]
To expand on this, I too am looking to deal with infinity for dates for a caching method `remember(value, expires)` vs `rememberForever(value)`. Plenty of ways for me to get passed this but found the following interesting:

```js
let x = new moment()
let y = new moment(x)

y.add(Number.POSITIVE_INFINTITY, 'years')

x.isBefore(y) // false
x.isAfter(y) // false
x.isSame(y) // false
x.diff(y) // NaN
```
