### ISSUE TITLE
duration parsing is giving incorrect value in 2.10.2

### ISSUE THREAD

**Issue by shishirdwivedi** [moment/moment#2352]
moment.duration({months: 2}).asDays() -> 61
moment.duration({months: 3}).asDays() -> 91
moment.duration({months: 4}).asDays() -> 122

and so on....

**Comment by icambron** [comment]
That's actually working as expected. Moment reckons that months are, on average, 30.436875 days long (this comes from dividing the length of a year by 12). That gets rounded to the nearest whole day on each conversion, so 2 months gets rounded up to 61 but 1 month gets rounded down to 30.
