### ISSUE TITLE
Add constructor argument to the deprecation warning

### ISSUE THREAD

**Issue by brianmhunt** [moment/moment#2356]
I feel it would be helpful if the #1407 deprecation warning printed to the console also indicated the failing argument passed to the constructor – particularly for cases where `moment.js` is minified in a production build and debugging is not readily available.

I would guess this would be changing [`warn(msg)`](https://github.com/moment/moment/blob/ce233cecf3d07aa15869a1db0fd8a8c43efccfcd/moment.js#L722) to also print the constructor argument passed, but it's not clear what effect that may have on other deprecation warnings.

:beers:

**Comment by icambron** [comment]
I think that makes sense. Would take a PR!

**Comment by aysark** [comment]
This issue should be closed, its been resolved in #2723

**Comment by brianmhunt** [comment]
Thanks @aysark —  I'll close this on the basis of your comment, but of course please feel free to re-open if I'm mistaken or there's a need.

Cheers.

**Comment by aysark** [comment]
Well... i was going to work on it and then checked the code and looks like @calebcauthon solved it.

It may not be in the production release yet however.
