### ISSUE TITLE
Cannot submit builds to the App Store in a PhoneGap application

### ISSUE THREAD

**Issue by kayzee** [moment/moment#2358]
I have been experiencing an issue submitting an Ionic/PhoneGap build to the App Store that uses angular-moment. The error is below. My solution was to exclude the MOMENT library from the included library and just include moment.min.js directly.

The same issue is report here: https://github.com/AppGyver/steroids/issues/918

> ERROR ITMS-90035: “Invalid Signature. Code object is not signed at all. The binary at path [myapp.app/Application/build/components/moment/scripts/npm_prepublish.sh] contains an invalid signature. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose ”Clean All“ in Xcode, delete the ”build“ directory in the Finder, and rebuild your release target. For more information, please consult developer.apple.com/…/Introduction.html”

**Comment by icambron** [comment]
I'm a little confused. How were you providing Moment's code to your application before?

**Comment by kayzee** [comment]
Moment was actually a included through Angular-Moment and bower:

**Comment by icambron** [comment]
Maybe I'm missing something, but I'm guessing Angular-Moment shouldn't be doing that. We certainly don't expect applications to keep around all of that stuff. I recommend filing a bug with Angular-Moment

**Comment by kayzee** [comment]
Okay, will do. I partly wanted to add this here just in case it helps someone in the future.
