### ISSUE TITLE
moment format problem

### ISSUE THREAD

**Issue by sirzxj** [moment/moment#2359]
moment('2015-5-5') in chrome has no problem, but failed in safari and firefox, need sransfer moment('2015-05-05')

![image](https://cloud.githubusercontent.com/assets/1269254/7466684/b8f66484-f31a-11e4-8009-1661a197c0b7.png)

left is chrome and right is safari

**Comment by icambron** [comment]
Using `moment(string)` uses the native date parser in most cases, including this one, so you're getting browser-defined behavior. (We have deprecated this.) Instead, parse the date explicitly:

```js
> var m = moment('2015-5-5', 'YYYY-M-D');
undefined
> m.format()
'2015-05-05T00:00:00-04:00'
```
