### ISSUE TITLE
moment.min returns different results depending on the order

### ISSUE THREAD

**Issue by cwohlman** [moment/moment#2362]
If I try to get the min of two moments, one of which is invalid, then the result I get depends on the order in which I specify the moments:

```javascript
moment.min(moment(""), moment()).toDate()
// Invalid Date
moment.min(moment(), moment("")).toDate()
// Wed May 06 2015 14:52:20 GMT-0500 (CDT)
```

I'm not sure what the expected behavior should be, but what I expected is something like this:
```javascript
function getMin() {
  var dates = Array.prototype.slice.call(arguments);
  dates = dates.filter(function (a) {return a.isValid();});
  // etc.
}
```

**Comment by cwohlman** [comment]
Here's a fiddle: http://jsfiddle.net/4cnm5vod/

**Comment by mj1856** [comment]
Consider:

- Moments are compared based on their value.
- `moment("").valueOf()` returns `NaN`
- `Math.min(NaN,0)` and `Math.min(0,NaN)` return `NaN`

Therefore, I would expect any moment compared to an invalid moment to return the invalid moment.

**Comment by cwohlman** [comment]
That sounds right to me, not necessarily what I would expect, but certainly logical and predictable.

**Comment by ichernev** [comment]
Well, PRs is welcome :)

**Comment by ichernev** [comment]
Close in favor of #2438

Note that you still have to filter out invalid moments yourself, or you'll get some invalid result (one of the args).
