### ISSUE TITLE
Can't change only some locales

### ISSUE THREAD

**Issue by davidkmenta** [moment/moment#2363]
I tried to change only some locales this way: http://jsfiddle.net/xr9nshft/ but this throws error ```Uncaught TypeError: Cannot read property 'replace' of undefined```. In this case it's because of missing locale for the ```mm``` variable.
I suppose the correct way is replace only locales those are named.
If I had to set all the variables, then I had to copy the whole logic for the localization (for example inflection in cs.js).

**Comment by ichernev** [comment]
@davidkmenta unfortunately we don't support locale inheritance at the moment (making a locale that is based on another, but slightly different). Right now you have to basically copy the locale file, modify it and use another key to plug it back in.
