### ISSUE TITLE
can't validate date in 'it' locale

### ISSUE THREAD

**Issue by idej** [moment/moment#2364]
I'm trying to validate date in it locale 
```javascript
moment.locale('it');
var a = "13/12/2015";
moment(a).isValid(); //return false, but should true
moment().format('L'); //return "08/05/2015"
moment(a,["DD/MM/YYYY"]).isValid(); //return true
```
How I can validate other locales dates without putting format in params?

Thank you!

**Comment by icambron** [comment]
Using Moment with only one argument invokes the native date constructor (unless the string is ISO), and the native date constructor doesn't know about Moment's locales. Instead, use the Moment's parsing facilities directly: 

```js
> moment.locale('it')
'it'
> var m = moment('13/12/2015', 'L');
undefined
> m.isValid()
true
> m.format()
'2015-12-13T00:00:00-05:00'
```

**Comment by idej** [comment]
thanks!
