### ISSUE TITLE
Moment month zero-based, format output of month is one-based

### ISSUE THREAD

**Issue by peterver** [moment/moment#2365]
When outputting a moment object as a string, for example say May 5th 2015 formatted with 'YYYY-MM-DD' would be '2015-05-05'. 

If this string is split and then fed into a moment object like so 

```
var m = moment();
var mydateString = m.format('YYYY-MM-DD');

var tmp = mydateString.split('-');
m = moment([tmp[0],tmp[1],tmp[2]]);
//  Moment object is one month ahead here
```

The corresponding date would become June 5th 2015. 

For some reason the month is zero-based in input, and one-based in output ?

**Comment by peterver** [comment]
For the moment a quick fix is doing the following

```
m = moment([tmp[0], parseInt(tmp[1]) - 1, tmp[2]]);
```

**Comment by peterver** [comment]
a colleague of mine just notified me that i can also do the following 

```
m = moment(myDateString, 'YYYY-MM-DD');
```

which seems more reasonable.

However i am still bugged about the docs not reflecting the zero-based month index :[

**Comment by alburthoffman** [comment]
The output should be one-based, because it's human readable. It would be odd if zero-based.

When input, zero based input is compitible with unix date functions. So I guess it's kind of tradional design.....

**Comment by peterver** [comment]
yes but the days however are one-based in input ?

**Comment by caijz** [comment]
I think it is confusing to expose interface to user using zero-based month, It doesn't matter how the code parse the input, but the exposed interface to user should be general.

**Comment by ahfarmer** [comment]
The Javascript Date() object also takes a 0-based month and a 1-based day of the month.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by dailytabs** [comment]
If Javascript Date() object were to jump off a bridge, moment.js should, too, then? ;-)

**Comment by ahfarmer** [comment]
Well, moment.js would be useless without Javascript Date(), so... maybe?. :wink:

**Comment by dailytabs** [comment]
Despite my smart-ass remark, I do agree with keeping the 2 api's in sync - which means, unfortunately, keeping the 0-based month. Making the 2 APIs different would harm moment's (mostly) drop-in replacement-ability.

@caijz Moment doesn't expose anything to the user, you as the dev have done that. Your code should be adding/subtracting the 1 from the month. If you are using select tags, this is easy: `<option value="0">1</option>`, etc. If using a jQuery calendar, they should be able to spit out `Date()` objects, which don't have this issue and can be sent straight into `moment()`. If using input tags, then it is up to you, again, as the dev, to make it user-friendly (add 1 for display, then remove 1 when going into moment (which is exactly what you would have to do if you used the Date() object).

@peterver seems to be OK with the 0-based month and would just like the docs to reflect it. However, the current docs do reflect this: "You can create a moment with an array of numbers that mirror the parameters passed to new Date()"

Appears like this issue can be closed.

**Comment by merlinpatt** [comment]
Perhaps a function could be added to get the one based month? moment has `weekday` (Sunday is 0) and isoWeekday (Sunday is 7), so I think something similar could be done here.

**Comment by hyurl** [comment]
Leaving 0-based month in Moment as `Date` would do is a very bad design due to the later is actually a mistaken copied from Java, which by the way, Java has fixed that since introducing the new API `java.time` in Java 8.
