### ISSUE TITLE
Consider zone formatting token for normalizing +00:00 to Z

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2366]
Originally moment/moment-timezone#213

```javascript
var m = // any moment
var s = m.format("YYYY-MM-DD HH:mm:ss " + (m.utcOffset() === 0 ? '[Z]' : 'Z'));
```

It would be nice to have a formatting token that already had this behavior.  Perhaps `ZZZ`.

The intended behavior is that *if* the offset is `+00:00` that it outputs `Z`, otherwise, it would output the offset.

We might also consider variants, where `ZZZ` has a colon, and `ZZZZ` does not.

**Comment by ichernev** [comment]
I think we should make it possible to add new tokens in general. This one looks not-so-useful for the general user. Also we have a million tokens already, and incompatible with any other system. Not to mention I haven't seen such a token elsewhere. Displaying timezone name is what you use `ZZZ` for, and we don't support that unfortunately :(

**Comment by jisaacks** [comment]
> I think we should make it possible to add new tokens in general.

I have thought about the idea of the API supported specifying a custom token with a custom formatting. By I am wondering what the potential drawbacks could be.
