### ISSUE TITLE
moment-with-locales.custom.js uses last defined locale by default

### ISSUE THREAD

**Issue by wyantb** [moment/moment#2367]
For example, run `grunt transpile:fr,ru` then load up moment and start using it.

* Expected: like previous releases, the english locale is manually set after all locales are defined.  `moment().format('LLLL')` formats in English.
* Actual: `moment().format('LLLL')` doesn't format in English.

**Comment by mj1856** [comment]
@ichernev - It looks like this started in the last release.  Please take a look asap.  Thanks.

**Comment by ichernev** [comment]
I guess this is fixed in #2393, will close after the release.

**Comment by deizel** [comment]
Resolved for me in 2.10.5 and 2.10.6 - don't need `moment.locale('en')` anymore.

/cc @ichernev
