### ISSUE TITLE
toJSON() and toISOString() does not handle weeks

### ISSUE THREAD

**Issue by martindanielson** [moment/moment#2372]
`moment.duration('P1W').toJSON()` returns `P7D` and I would like it to return `P1W` instead. This shold be according to the ISO spec, even if I could understand that we need to set a specific setting for this.

Is there a way to do this or will I have to add a rather ugly hack to accomplish this myself?

**Comment by martindanielson** [comment]
Perhaps something like this:

Need someone who is better used to the code to verify though. I.e. I do not know if this is used for something else than durations. `weeks()` and `asWeeks()` gives me an int vs a float, which I use to determine if I should display weeks instead of days. Also, I am not really sure if you can have both W and D in there. 

```
var abs = Math.abs;

export function toISOString() {
    // inspired by https://github.com/dordille/moment-isoduration/blob/master/moment.isoduration.js
    var Y = abs(this.years());
    var M = abs(this.months());
    var W = (!(this.asDays() % 7) ? abs(this.asWeeks()) : 0);
    var D = abs(this.days());
    var h = abs(this.hours());
    var m = abs(this.minutes());
    var s = abs(this.seconds() + this.milliseconds() / 1000);
    var total = this.asSeconds();

    if (!total) {
        // this is the same as C#'s (Noda) and python (isodate)...
        // but not other JS (goog.date)
        return 'P0D';
    }

    return (total < 0 ? '-' : '') +
        'P' +
        (Y ? Y + 'Y' : '') +
        (M ? M + 'M' : '') +
        (W ? W + 'W' : (D ? D + 'D' : '')) +
        ((h || m || s) ? 'T' : '') +
        (h ? h + 'H' : '') +
        (m ? m + 'M' : '') +
        (s ? s + 'S' : '');
}
```

**Comment by mj1856** [comment]
Yes, it's valid ISO to have both weeks and days.  However, given `moment.duration("P1W3D").toISOString()`, your function returns `"P0D"` so it's something's not quite right.

**Comment by mj1856** [comment]
Not sure whether this is a bug or would be an enhancement, so marking as both.  :stuck_out_tongue_winking_eye: 

I do notice that the duration constructor ([source](https://github.com/moment/moment/blob/develop/src/lib/duration/constructor.js)) tracks a few items separately.  It would probably have to keep a `_weeks` variable also to do this properly.

**Comment by ichernev** [comment]
We should handle parsig of weeks in ISO duration. About saving weeks in the constructor I'm against. Just add a flag to put 7d to 1w in the json function.

**Comment by mj1856** [comment]
So then, we're ok with `moment.duration("P1W15D").toISOString() === "P3W1D"` ?

**Comment by ichernev** [comment]
Well they are equivalent :) so unless somebody protests... Also we should use days for output by default. Weeks only on request (true as arg toISOString)

**Comment by ichernev** [comment]
@mj1856 what if you say `PT90S`, when you output it will be `PT1M30S`? I mean if you really want to preserve weeks, we shall as well preserve everything. I think formatting it canonically (as we do now) is good, so no need for preservation.

**Comment by mj1856** [comment]
Sounds ok to me, though I've seen other implementations that do preserve each field - at least for date fields.

I don't feel strongly about it either way.  As long as we document the behavior, I'm good. :smile:

**Comment by martindanielson** [comment]
An argument to the `toISOString()` method that defaults to current behavior but when specified gives an option to get the result in "week format" would be the best option I think. Then people who rely on this will not be affected and those of us who wants this behavior can use it.

As for preserving the information I have no set thought on that. All I want is to be able to format it.

The code I provided is not well tested; I apologize. But the parsing of `moment.duration('P1W1D').toISOString()` is not me; it works that way today. I think, according to the spec you either specify it according to PxYxMxDTxHxMxS **or** `PxW` - so this might suggest when returning in week format it will remove days and only parse whole weeks, and whole weeks only.

**Comment by ichernev** [comment]
We do support parsing `PxW` right now, we even do the right thing and forbid mixing `W` with the other tokens (as the spec says).

If you create a duration object with `PxW` and then display it ... you might want to get back `PxW`. But what if you add 1 hour and then display it? It should be `P7D1H`. What if you add and then subtract an hour? `P7D` or `P1W`?

What if you have `P1D1H` and want to display it using weeks? Should it:
* return an error
* display `P1D1H`
* display `P0W` (rounded to nearest integer ??)

To be remotely useful, we need 2 functions:
* `isWeeksOnly()` -- true iff the object is a whole number of weeks (hours won't bubble to days, so this means 0 months, 7*K days (a number divisible by 7) and 0 milliseconds (no fractional day)
* `toWeekISOString()` -- display `PxW` if weeks-only or regular iso-string, if its not weeks-only

@martindanielson how does this sound?

**Comment by AnielloFalcone** [comment]
Hi all!

I know this is quite old, but there is any update on supporting weeks so far?

**Comment by marwahaha** [comment]
Probably, we will not support displaying weeks anytime soon.

https://momentjs.com/docs/#/-project-status/
