### ISSUE TITLE
Two digit years aren't parsed well

### ISSUE THREAD

**Issue by philpee2** [moment/moment#2374]
Currently, `moment("10-10-10")` fails to be parsed and falls back to using `Date`, which ignores the logic in `parseTwoDigitYear`, which makes sense. 

Using  `moment("10-10-10", "MM DD YY")` works, but this is somewhat inflexible, since I want `"10-10-2010"` to also work and ignore the `parseTwoDigitYear` logic. Currently, `moment("10-10-2010", "MM DD YY")` will turn `"2010"` into `"20"` and  run `parseTwoDigitYear`, turning `"20"` into 1920 or 2020.

There isn't a good way to check whether a date's year is given with 2 digits or 4. Strict validation is too strict, and would require checking all different kinds of punctuation. In general, a "middle" strictness, which ignored punctuation but enforced format, would be great.

**Comment by dailytabs** [comment]
You can pass an array of formats.

`moment("10-10-10", ["MM DD YY", "MM DD YYYY"])`
`moment("10-10-2010", ["MM DD YY", "MM DD YYYY"])`

For more information on which format is used, check out http://momentjs.com/docs/#/parsing/string-formats/.

**Comment by mj1856** [comment]
@dailytabs  :+1:
