### ISSUE TITLE
Mess with formats

### ISSUE THREAD

**Issue by ivan-kleshnin** [moment/moment#2375]
MomentJS does some dirty tricks with empty function `Moment.ISO_8601`.
I wonder why not just provide ISO string constants instead?
There is a *buggy* behavior here:

```js
import Moment from "moment";

// this can be used for parsing
Moment("2015-01-02", Moment.ISO_8601); // ok 

// but not formatting
Moment("2015-01-02", Moment.ISO_8601).format(Moment.ISO_8601); // exception
```

```
.../node_modules/moment/moment.js:455
        var array = format.match(formattingTokens), i, length;
                           ^
TypeError: undefined is not a function
```

**Comment by icambron** [comment]
`ISO_8601` was [never meant](https://github.com/moment/moment/issues/2078#issuecomment-88373075) to be passed as an argument to `format`. Possibly we should have a formatting token for it and retire the constant from use altogether, but AFAIK, we do not. But do not despair! Simply use `toISOString()`

**Comment by ivan-kleshnin** [comment]
> Simply use toISOString()

This is not acceptable for library code where you will have to deal with multiple formats as a constants and should be agnostic to them. I can workaround of course, just hope this will be cleaned in the future.

**Comment by icambron** [comment]
It's fair to ask for a format string for ISO-8601. @ichernev - do you agree? If so, what string?
