### ISSUE TITLE
Calendar Support

### ISSUE THREAD

**Issue by mkhahani** [moment/moment#2378]
I found `Moment` very useful but it unfortunately does not support other calendars (e.g. Jalali) natively. The way people currently add their calendars by writing plugins (e.g. moment-jalaali) is not good. A better solution is to add support for custom calendars so developers can write and add their own calenders easily. The main benefit of this approach is that the API and function names are the same and you can switch between calendars by a line of code:
```javascript
setCalendar('Jalali');
```
I can provide more details if it is not clear.

**Comment by icambron** [comment]
See #1454 :)
