### ISSUE TITLE
jspm locale not working

### ISSUE THREAD

**Issue by emilcardell** [moment/moment#2379]
First installed with  jspm install moment (version 2.10.3 gets installed)

Moment gets imported
import moment from 'moment';

Later when moment is used i.e.
moment().locale('sv').fromNow();

the local is still en.

Are we doing something wrong or missing something? Or is it broken?

**Comment by ichernev** [comment]
@emilcardell can you try to troubleshoot that a little bit. Try setting the global locale. Check the locale property inside the object (print the raw moment object).

**Comment by orhan-swe** [comment]
Having the same problem. Tried to debug it. It tries to load it in loadLocale(name) but exception is thrown and it fails (NOTE: var temp = e was added by me):

![tmp](https://cloud.githubusercontent.com/assets/10519489/9059833/0e35886e-3aae-11e5-8b91-effc25a286f2.JPG)

As a WA I added this in my file and worked:
var local = require('moment/locale/fr');

I could not find any doc on this so I do not understand how more people are not seeing this.

NPM version 2.5.1
moment 2.10.6

**Comment by JamesReate** [comment]
Same issue here... I'm guessing we need to manually import the locale we need?

**Comment by LuckY1** [comment]
How do I import the locale file with jspm?

**Comment by adrianhara** [comment]
I have the same question. If I just insert the locale file as a <script> in the page it doesn't work. It looks like the moment object reference inside the locale file is different from the one in the jspm loaded file which uses moment later. By this I mean that if I set a breakpoint in the locale file after the `.defineLocale()` call and evaluate `moment.locale()` it returns "de", however in my jspm loaded file `moment.locale()` still returns "en" and even calling `moment.locale('de')` still returns "en.

**Comment by tcurdt** [comment]
same here

**Comment by specimen151** [comment]
me too

**Comment by balakj75** [comment]
You have to import your locales explicitly with a require statement like require('moment/locale/es'). This will work if you are working with static locales. If you want dynamic locales i.e., you want to switch moment locales based on browser language you have to use System.import to import the locales. It is kind of pain to do it. Once you import a locale, moment automatically sets the locale internally to the imported one. I wish jspm would release a version with the locales included.

**Comment by icambron** [comment]
Closing this based on @balakj75's comment. It sounds like jspm just doesn't give you a way to give Moment a way to find the locale files. 

>  I wish jspm would release a version with the locales included.

This is the most obvious fix I can think of without knowing more about jspm.
