### ISSUE TITLE
Allow to synchronize time with server (set offset)

### ISSUE THREAD

**Issue by fracz** [moment/moment#2384]
MomentJS relies on current browser time (OS time). If it is set to different time than the server's, unexpected behavior may happen.

I have noticed it when I had used `fromNow` method of momentjs for displaying comment add time:

1. Browser time: 3:00pm, server time: 3:05pm.
1. Add comment (creation time is taken from server during database insert).
1. Date is passed back to frontend (3:05pm).
1. MomentJS displays "comment added in 5 minutes"

I would expect momentJS to allow configuring "current time". It should then calculate offset between given "now" and browser time and respect it on all operations, i.e.:

```js
var time = getCurrentTimeFromBackendWithAjaxOrSomething();
moment.setCurrentTime(time);
```

Related:
* [how to sync the date with the server time (Moment.js)](http://stackoverflow.com/questions/26924843/how-to-sync-the-date-with-the-server-time-moment-js)
* [Moment.js set the base time from the server](http://stackoverflow.com/questions/19629561/moment-js-set-the-base-time-from-the-server)

**Comment by mj1856** [comment]
Dup #2337
