### ISSUE TITLE
.add() doesn't work with parsed moment?

### ISSUE THREAD

**Issue by JulianKingman** [moment/moment#2385]
Consider this: 
`var date = moment('07/10/1986').add(1,'days')`

I expect date to be a moment object referencing 07/**11**/1986, but for some reason when I enter the date this way it doesn't add the day, but gives me the same moment object.

**Comment by alburthoffman** [comment]
this might be a timezone issue. this is my testing code, it works in +08:00 timezone:
https://jsfiddle.net/amr8zp4m/

**Comment by JulianKingman** [comment]
Strange, it's working now. I must have had something else off in my code somewhere.

**Comment by alireza-saberi** [comment]
@alburthoffman : I pasted your codes in angular2/4 environment, it did not work
