### ISSUE TITLE
diff() bug

### ISSUE THREAD

**Issue by saffabook** [moment/moment#2386]
Hi 

There seems to be a bug. I have the dates
var a = moment([2015, 6, 30]); // last day of june 2015
var b = moment([2015, 7, 1]); // first day of july 2015
var totaldays = b.diff(a, 'days'); // 2 but should be 1
I have the link to demo. 

http://plnkr.co/edit/X8E78NR9hJzWipau2i3m?p=preview

**Comment by mj1856** [comment]
Like `Date`, months are 0-11 for this function.  So that's actually July 30 and August 1.
See:  http://momentjs.com/docs/#/parsing/array/

**Comment by saffabook** [comment]
Thank you for pointing me in the right direction.
Much appreciated.
