### ISSUE TITLE
does en locale should display time in 12 hours format ?

### ISSUE THREAD

**Issue by beastsergey** [moment/moment#2388]
I`m using Moment.js 2.10.3.
In according to moment-with-locales.js : 
```javascript
    var defaultLongDateFormat = {
        LTS  : 'h:mm:ss A',
        LT   : 'h:mm A',
        L    : 'MM/DD/YYYY',
        LL   : 'MMMM D, YYYY',
        LLL  : 'MMMM D, YYYY LT',
        LLLL : 'dddd, MMMM D, YYYY LT'
    };
```
Does it mean en locale should display time in 12 hours format with LTS format ?

[a jsfiddle demonstrating the issue](http://jsfiddle.net/ezoqkgca/4/)
Sorry, my English is not very good now...

**Comment by icambron** [comment]
Yes. `en` means `en-us`. If you want 24-hours, consider `en-uk`.

**Comment by beastsergey** [comment]
but in my example en = 24h format =(
7:16:51 PM
elLocale (should be 12 h format) : 7  :   16  :   51
enLocale (should be 12 h format) : 19  :   16  :   51
beLocale (should be 24 h format) : 7  :   16  :   51
