### ISSUE TITLE
UTC to Local fails after subsequent converts...

### ISSUE THREAD

**Issue by dabrave** [moment/moment#2392]
Hi!
first of all, congrats for such amazing framework! :+1: 

What i'm trying to do is:
- I have a huge (around 90) date inputs on page
- I have UTC times on Database
- I want to show the local time to the user, instead of the UTC time

Problem:
First UTC to local conversion, works good, (I'm in spain, so +2h to UTC) BUT, after that first one, the subsequent dates add +1h instead of +2h...

So this is an example of the dates 
![2015-05-28_0113](https://cloud.githubusercontent.com/assets/1419525/7849598/6883a83a-04d7-11e5-9b29-61cd3716c807.png)

And here is the code (alerts are commented):
![2015-05-28_0119](https://cloud.githubusercontent.com/assets/1419525/7849630/aaa195ba-04d7-11e5-93f4-7f39e5b5d3e0.png)

I'm sure i'm doing something wrong, but I've being looking for into all Docs but nothing like utc flushing, or forcing format again...

**Comment by mj1856** [comment]
Spain has a standard offset of +1, and switches to +2 for daylight saving time.  Looking at the dates in question, it is converting properly.

However, do keep in mind #831, which may convert some of those older values incorrectly.
