### ISSUE TITLE
Cannot set property 'moment' of undefined

### ISSUE THREAD

**Issue by iWader** [moment/moment#2395]
Issue #1179 seems to have reared its ugly head again today.

jQuery uses this approach which I think moment should adopt as well

```javascript
typeof window !== "undefined" ? window : this
```

**Comment by jisaacks** [comment]
> Issue #1179 seems to have reared its ugly head again today.

How? Under what circumstances?

I do not think using `window` makes sense for moment since it targets multiple environments and not all have a window object.

**Comment by mj1856** [comment]
@iWader - Please provide supporting details so we can reproduce the failure.  Thanks.

**Comment by oliviertassinari** [comment]
I just had the same issue by using `babel-loader` instead of `jsx-loader`.
I'm using v2.5.1. To fix this, I used:
```js
global = typeof window !== "undefined" ? window : this,
```

**Comment by yagudaev** [comment]
Just hit this error too in production. Has this been fixed? Seems to happen on 2.12.0

**Comment by icambron** [comment]
@yagudaev we still don't have reproducible steps for this, so it's hard to say.

**Comment by yagudaev** [comment]
@icambron I hear you. A little though as it is part of a chrome extension work for a client. But not to worry created a repo for it and been able to isolate the problem for you.

Check it out at: https://github.com/yagudaev/moment-bug

**Comment by icambron** [comment]
Cool, I'll take a look soon.

**Comment by yagudaev** [comment]
@icambron thanks appreciate it and the awesome jobs you guys are doing with moment.js :)

**Comment by icambron** [comment]
I took a look. It looks like you're running into this: http://stackoverflow.com/questions/34973442/how-to-stop-babel-from-transpiling-this-to-undefined

For example, if you replace all of `vendor/moment.js` with just the line `console.log(this)`, you'll see that compiles to `console.log(undefined)`.

Basically, Moment is assuming `this` is bound to the appropriate global, in this case the `window` variable. That works fine in general, but violates some of Babel's assumptions. We will soon be building Moment itself with Babel/Rollup, so you might soon have more options to go back to the raw source instead, but in the meantime you'll need to configure Babel to know it's not compiling an ES6 module. I suspect that one of the workarounds in that SO ticket will do the trick.

**Comment by helal-khan** [comment]
gh
