### ISSUE TITLE
Adding locales js forces language to zh-tw

### ISSUE THREAD

**Issue by designbyadrian** [moment/moment#2399]
Tried the files downloaded form the server, min, non-min, and same files form bower. My LLLL strings show Chinese localisation.

V: 2.10.3

**Comment by designbyadrian** [comment]
If I add locale files separately, the last file I add will be used as the main lang, even if I don't configure Moment to any particular language.

**Comment by brianwyantora** [comment]
See also #2367

**Comment by designbyadrian** [comment]
Apologies, I was searching for "Chinese".

Please mark this as dupe in favour of #2367

**Comment by designbyadrian** [comment]
:+1:
