### ISSUE TITLE
Duration Keeps Decimal as Days

### ISSUE THREAD

**Issue by sup3rb0wlz** [moment/moment#2402]
I want to create a duration, and then add it to a moment. The reason is because Delphi stores dates in the format <Days from 12/30/1899>.<fraction of day> and moment doesnt know how to parse this. So my solution was going to be to create a duration and add it to the moment.

The problem is that duration keeps the days in a decimal format. Shouldnt this reduce it down all the way to the millisecond spot?

```
    var base = moment("12/30/1899");
	console.log(base.format("dddd, MMMM Do YYYY, h:mm:ss a"))
	var dur = moment.duration(42156.4710896412, "days");
	console.log(dur.years() + " " + dur.days() + " " + dur.hours() + " " + dur.minutes() + " " + dur.seconds() + " " + dur.milliseconds())
	base.add(dur);
	console.log(base.format("dddd, MMMM Do YYYY, h:mm:ss a"))
```

if not does anyone have any alternatives to getting the hours minutes seconds and milliseconds from a decimal like that (besides doing it manually, which is also an option, just looking for an easier way)

**Comment by mj1856** [comment]
Consider adding a function to simply convert to unix-based milliseconds:

```javascript
function DephiToUnix(ts) {
    return (ts - 25569) * 864e5;
}
```

Now you'll can simply:

```javascript
moment(DephiToUnix(42156.4710896412)).format()  // "2015-06-01T04:18:22-07:00"
```
or
```javascript
moment.utc(DephiToUnix(42156.4710896412)).format()  // "2015-06-01T11:18:22+00:00"
```

etc...

**Comment by sup3rb0wlz** [comment]
Looks good! Thank you!

**Comment by sup3rb0wlz** [comment]
Looks good! Thank you!
