### ISSUE TITLE
'Invalid Format' error when trying to convert one date format to another

### ISSUE THREAD

**Issue by armyofda12mnkeys** [moment/moment#2403]
I want to take a data format and convert it to another format...
I heard 'new Date' syntax will be depreciated at some point so can't use this at some point (I see that in the logs as well) so cant do this at some point:
```
moment(new Date("Wednesday, June 3, 2015 17:25:34")).format('YYYY-MM-DD')
```
I see a warning in the browser when using the implicit syntax below which im guessing calls the same 'new Date' as above:
```
moment("Wednesday, June 3, 2015 17:25:34").format('YYYY-MM-DD')
```

Im trying to supply the format so I can get passed the depreciated 'new Date' code by doing something like this:
```
moment('Wednesday, June 3, 2015 17:25:34', 'dddd, MMMM D, YYYY HH:mm:ss').format('YYYY-MM-DD') //should output 2015-06-03
```
but Im getting 'Invalid Format' but the initial format I set looks fine to me.

Can anyone tell me why?
Thanks,
Ari

**Comment by alburthoffman** [comment]
actually the above code is working fine for me. 
you might use the latest momentjs version.

here is what I get:
moment('Wednesday, June 3, 2015 17:25:34', 'dddd, MMMM D, YYYY HH:mm:ss').format('YYYY-MM-DD')
"2015-06-03"

**Comment by armyofda12mnkeys** [comment]
I just used the latest momentjs and the doesn't work:
Here is an example of the implicit format working (first alert) and explicit format not working (2nd alert):
http://jsfiddle.net/4mgp3c6s/

Am I doing something wrong in that jsfiddle's explicit example?

**Comment by philjohnson789** [comment]
Interesting, when I use the non-locacle version of Moment.js it works fine:

Locale (broken): http://jsfiddle.net/5zn0L60d/
Non-locale (works): http://jsfiddle.net/kagdvm37/

**Comment by armyofda12mnkeys** [comment]
Hmmm, if i explicitly set a locale before the format then it works. 
Not sure if thats a bug or not that a locale has to be set.
I'd just assume there would be a default locale like 'en' but adding moment.locale('en'); works:
http://jsfiddle.net/4mgp3c6s/1/

**Comment by alburthoffman** [comment]
something wrong with moment-with-locales.js
when I changed it to moment.js, it will work.

**Comment by mj1856** [comment]
#2367 explains it.  Closing as duplicate. Though it presents differently, it's the same issue.
