### ISSUE TITLE
C# port

### ISSUE THREAD

**Issue by Eonasdan** [moment/moment#2406]
This isn't really an issue, but I wanted you to know that I've ported your library to C# at https://github.com/Eonasdan/MomentSharp

I love using this library in my javascript code and I wanted to be able to do some DateTime operations from this library in my C#.

Thanks for your hard work!

**Comment by mj1856** [comment]
Looks like a good start, though there are some errors.  I sent you one already in  Eonasdan/MomentSharp#1

A few other things to consider:
- .Net's `DateTime` is significantly different than JavaScript's `Date` object.
- Understand `struct` vs `class` in C#, mutability vs immutability, etc.
- Consider the memory footprint of a class with multiple properties vs. a struct with a single field.
- Consider that even moment doesn't keep each date/time component in separate variables.
- Review moment's local mode vs utc mode, and understand how it interact with time zones - with or without moment-timezone.
- Think carefully about parsing and formatting, and localization.  It's trickier than it may appear on the surface.

Also consider the intended audience. In general, my experience has shown that most .NET developers are either happy using the built-in framework objects (`DateTime`, `DateTimeOffset`, `Timespan`, `TimeZoneInfo`), or are looking for a more sophisticated and complete API such as that offered by [Noda Time](http://nodatime.org).   Moment's API fits JavaScript, but it's simplification would actually be a step backwards from what is currently available in .NET today.

If you enjoy date/time, perhaps consider contributing to an existing effort instead?  Noda Time is 100% community driven, and there are other efforts such as the one I'm working on [to add a couple of new types to .NET Core](https://github.com/mj1856/corefx-dateandtime).
