### ISSUE TITLE
Improperly parsing negative durations

### ISSUE THREAD

**Issue by timuralp** [moment/moment#2408]
moment properly parses duration of type ```-P1D```, however, ```P-1D``` is not parsed correctly:

    moment.duration('P-1D').days()
    0
    moment.duration('-P1D').days()
    -1

I couldn't find the actual ISO 8601 standard, but found a Java Duration description that implies this is [allowed](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-):
> "P-6H3M"    -- parses as "-6 hours and +3 minutes"
> "-P6H3M"    -- parses as "-6 hours and -3 minutes"
> "-P-6H+3M"  -- parses as "+6 hours and -3 minutes"

**Comment by mj1856** [comment]
The ISO 8601 spec itself only says one thing about negative durations, in the Terms and Definitions section for "duration"

> 2.1.6
> duration
> ***non-negative quantity*** attributed to a time interval, the value of which is equal to the difference between the time points of the final instant and the initial instant of the time interval, when the time points are quantitative marks 

The actual detailed spec of the duration format doesn't mention negativity at all.

However, I have indeed encountered other implementations that support both of the formats you provided.  Specifically, Java 8, Joda Time, Noda Time (.net) and .NET's built-in XML converter:

```csharp
 string s = System.Xml.XmlConvert.ToString(TimeSpan.FromHours(-2))  // "-PT2H"
```

Then again, `XmlConvert` isn't necessarily following ISO8601 - it's following the [`xs:duration`](http://www.w3.org/TR/xmlschema-2/#duration) data type (w3c XSD) - which is *based* on ISO8601, but specifically calls out that it deviates from ISO8601 by allowing negative values.

Anyway, I think it would be reasonable to support them.

**Comment by mj1856** [comment]
Oh, and note that XSD only allows the entire duration to be negative, as in `-PT2H`.  It does not allow each component to be negative, such as `PT-2H`.  Still, since there are implementations in other languages that do allow for it, I see no harm in supporting both.

**Comment by mj1856** [comment]
We'll track in PR #2955.  Thanks.
