### ISSUE TITLE
Add a way to parse relative date

### ISSUE THREAD

**Issue by Delgan** [moment/moment#2409]
From what I know, there is no way to parse a relative date, `moment("19 years ago")` returns `Invalid date` and it does not exist any token that we could use as second parameter to format such a date.

Yet it would be very helpful, is it possible to consider implementing this feature, please?

**Comment by mj1856** [comment]
Dup of #1909 and several others.

We've decided that moment is not to be a natural language parser.  You might consider libraries such as [Sugar](http://sugarjs.com/dates) instead.
