### ISSUE TITLE
1974 timezone issue

### ISSUE THREAD

**Issue by dailytabs** [moment/moment#2411]
Local tz - `moment()._d.getTimezoneOffset()`:
&nbsp;&nbsp;&nbsp;&nbsp;240 (-4 hours, EDT)

In PostgreSQL 'date' column (as viewed in pgadmin):
&nbsp;&nbsp;&nbsp;&nbsp;1974-01-23

Hibernate populates Entity, column is java.util.Date property type, which sets a time of midnight in local tz.

Entity is returned as JSON, property shows as timestamp:
&nbsp;&nbsp;&nbsp;&nbsp;128145600000

unixtimestamp.com for 128145600:
&nbsp;&nbsp;&nbsp;&nbsp;01/23/1974 @ 4:00am (UTC)

Appears Java has done it's job correctly: daylight saving time started early in 1974 (http://www.timeanddate.com/time/dst/1974.html), so -4 is correct and would make it midnight EDT.

Now, let's see what moment does with this.

`moment.utc(128145600000)._d.getTimezoneOffset()`:
&nbsp;&nbsp;&nbsp;&nbsp;300

This offset is incorrect, 300 (5 hours) implies no daylight saving time, which is wrong. This extra hour causes the day to shift to the 22nd.

`moment.utc(128145600000).local().format("MM/DD/YYYY HH:mm:ss")`:
&nbsp;&nbsp;&nbsp;&nbsp;"01/22/1974 23:00:00"

Further Info:
http://www.timeanddate.com/worldclock/converted.html?iso=19740123T04&p1=0&p2=77: "Midnight between Tuesday, January 22, 1974 and Wednesday, January 23, 1974" (not 11pm the 22nd, as moment shows).

**Comment by mj1856** [comment]
Yes, this is due to the issue described in #831, which is a flaw of JavaScript, not of moment.

You can work around it by using [moment-timezone](http://momentjs.com/timezone/).  You will have to know the specific time zone you are interested in - which looks like `"America/Detroit"` from the link you gave.

**Comment by mj1856** [comment]
Also consider that even without that flaw in JavaScript - while Linux and Mac use IANA time zones, Windows does not.  The history of time zones on Windows machines would not be accurate in 1974, as  Windows time zone history only goes back about 10 years or so (it varies).  IANA zones go back to at least 1970, or earlier in many cases.
