### ISSUE TITLE
Make today/tomorrow/yesterday/last usable standalone

### ISSUE THREAD

**Issue by synotna** [moment/moment#2415]
moment-with-locales includes the translations of today/tomorrow/yesterday/last but only in fixed formats

Please make it possible to use the translations by themselves like for day/month

**Comment by mj1856** [comment]
Hmmm... well, the locale data doesn't really contain those words separately, but rather it contains those words as part of a format string.  In other words, it doesn't have the string `"Today"` separately from the string `"[Today at] LT"`.

You can get at those strings from the `moment.localeData()._calendar` object.

It would take significant work to revise all of the local data files to extract the specific words, and in some cases it might not result in the best word choice for the intended context.

Can you elaborate on the use case you have in mind?  What would you expect the API to look like?  Can you provide some examples with data in a couple of languages?

Thanks.

**Comment by synotna** [comment]
e.g. at the moment you can do

moment().format("dddd, MMMM Do YYYY, h:mm:ss a"); // "Sunday, February 14th 2010, 3:25:50 pm"

it would be nice to be able to do e.g.

moment().format("ddddh, MMMM Do YYYY, h:mm:ss a"); // "Today, February 14th 2010, 3:25:50 pm"

Where ddddh (for example, h for humanized) will display Yesterday/Today/Tomorrow (if applicable) or day of the week like it does now, in the localized language

Currently, if you want to show Yesterday/today/tomorrow with your own format, you must format the string, then afterwards add the respective "identifier" yourself that is hooked to a separate translation system, and have them translated

**Comment by mj1856** [comment]
Ok, I can see the value in that.  It would require some rework of the locale files and associated code, but it is a possibility.

A pull request would be welcome. :smile:

**Comment by synotna** [comment]
If you decide on how to store the data, I don't mind spending a couple of hours doing the grunt work of splitting the current translations into fragments :)

**Comment by mj1856** [comment]
@ichernev, @timrwood - I'd appreciate your thoughts on this one.  Thanks.

**Comment by ichernev** [comment]
First of all, using "custom format" with translations is ... impossible. That is -- if you're using the "low level" `ddd`/`MMM` tokens, even by themselves, in a locale you don't fully control (know), than the results would be broken. The only safe thing to do is use `l`,`ll`..`L`, `LH`..., because these are predefined and known to be correct.

Better i18n frameworks (based on CLDR) provide API to say stuff like "display hours, seconds and day of week" and that figures out a format that is appropriate, but nothing like separating those tokens with comma and calling it a day.

What you're currently doing for a few languages (custom "translation framework") is actually what you're supposed to do to translate it properly in the current system, and it can't be helped unless we rewrite translations on top of CLDR (which is a project you that can be worked on, but not a small one for sure).

**Comment by raleksandar** [comment]
I agree with @ichernev that it's not possible to have custom formats with translation but I would still find useful an API to return 'Yesterday', 'Today' and 'Tomorrow' APIs. In fact I have a need for that in the app I'm working on right now. I need to group events by day and to name those groups (if today is Thursday) as Today, Yesterday, Tuesday, Monday, Sunday, Saturday, Friday

Right now I'm using following hack to extract Today/Yesterday strings:

````js
return date.localeData()
    .calendar(relativeDay) // relativeDay being 'sameDay' or 'lastDay'
    .replace(/^.*\[(.+)\].*$/, (_, s) => {
        return s.split(/\s+/).sort((a, b) => a.length - b.length)[1];
    });
````
Which in essence takes the longest word found in between the brackets. And I'm sure that this will break with some languages (CJK probably) but for now it works.

I would like to have this feature baked in into moment, something like:

````js
localeData.dayName(day); // day is one of lastDay, sameDay, nextDay
````

I know that this is not a small change but it does have valid use cases.

**Comment by ichernev** [comment]
@raleksandar the way to do this is to add a property to all language files, and appropriate getters. I can merge a PR that has tests and everything.

**Comment by raleksandar** [comment]
@ichernev great, I'll get to that PR asap!

**Comment by louisameline** [comment]
+1, thank you. I find it most surprising not to be able to write just "Today". Even without getters, a "dictionnary" property in language files with the correct translations would be good enough for me.

And by the way, it would be useful to have also "the day before yesterday" (and "the day after tomorrow") in the translations, as some languages have a specific name for this : "avant-hier" in French, "Vorgestern" in German, "anteayer" in Spanish, etc.

**Comment by wmertens** [comment]
Very specific use case: In a date input widget, be able to label buttons "Today", "Yesterday" etc without having to provide your own translations.

**Comment by LorrisSaintGenez** [comment]
Got the same needs to build a calendar (ie: headers with 'today', 'tomorrow', 'monday', etc..). @synotna @mj1856 Any update ?

**Comment by chren-de-large** [comment]
is there any "not hack" solution for that?

**Comment by stgogm** [comment]
Maybe it would be more intuitive to add it to the `calendar` method as an argument:

```js
moment().calendar('days'); // 2 days ago, yesterday, today, tomorrow, 2 days from now, etc...
moment().calendar('weeks'); // 2 weeks ago, last week, this week, next week, 2 weeks from now, etc...
moment().calendar('months'); // 2 months ago, last month, this month, next month, 2 months from now, etc...
moment().calendar('years'); // 2 years ago, last year, this year, next year, 2 years from now, etc...
```

**Comment by Alevale** [comment]
I think this issue has been lost in time, but i just bumped into it, is there anything I could do to fix this? https://stackoverflow.com/questions/45954432/convert-string-tomorrow-to-momentjs 

Even if it requires to make a PR, I don't mind improving code for everyone :)

**Comment by marwahaha** [comment]
If you can get something working across all languages, with tests, we'll look at a PR.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

There may be Moment.js plugins to achieve this functionality.
