### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2418]
From: http://stackoverflow.com/q/30832920/634824

```javascript
var m = moment('06/14/2015 123PM', 'MM/DD/YYYY hmmA');
m.hour()   // 12
m.minute() // 3
```

Even though one digit is specified for hours, and two are specified for minutes, the number is read left-to-right, taking two digits for the hour and leaving the remaining digit for the minute.

I would expect hour `13` (1 pm) and minute `23`.

**Comment by AustinBGibbons** [comment]
related: #677

**Comment by ichernev** [comment]
This has come up before and is relatively hard to fix. We need to consider the token `hmm` a separate one (for parsing purposes), and/or `hmmss`, so that there can be special code to handle this case. The way tokenizing/parsing is done at the moment, it is impossible.
