### ISSUE TITLE
Get last day of the month?

### ISSUE THREAD

**Issue by mb-dev** [moment/moment#242]
Will be great to be able to get/set moment instance to last day of the month - similar to eod.

**Comment by cerkit** [comment]
Related: you can also use `moment().daysInMonth()` to get an integer representing the last day in the month.

**Comment by gideonapollob** [comment]
Related:

>Deprecation warning:
>`moment().add(period, number) is deprecated. Please use moment().add(number, period).`

So a little change to the code would be: `moment().add(1, 'months').date(1).subtract('days', 1)`

**Comment by maggiepint** [comment]
@gideonapollob , yep. You would need to reverse in your ``.subtract()`` as well.

But ``.endOf()`` is almost for sure the best choice for what you're doing.

**Comment by holic158** [comment]
You may get last day of month. like this.
`moment().endOf('month').format('DD')`

**Comment by jojo-joseph** [comment]
which substract the one month basis of last month 


moment().subtract(1, 'months').endOf('month').format('DD-MM-YYYY')

**Comment by pramodjb** [comment]
> Related: you can also use `moment().daysInMonth()` to get an integer representing the last day in the month.

here last day 31 wont getting

**Comment by cerkit** [comment]
> > Related: you can also use `moment().daysInMonth()` to get an integer representing the last day in the month.
> 
> here last day 31 wont getting

Without context, it's hard to know which month your trying to get a result for, but there are only 30 days in November, the current month.
