### ISSUE TITLE
dd, ddd, and dddd strict parsing is not working appropriately

### ISSUE THREAD

**Issue by ccorcos** [moment/moment#2423]
`date = moment('a', 'dddd', true).isValid()` will return true, along with any gibberish input

**Comment by mj1856** [comment]
Same with `dd` and `ddd`.  Strangely, it also sets `"2014-12-28T00:00:00-08:00"` local time.  Not sure where that comes from...

**Comment by ccorcos** [comment]
Any progress here?

**Comment by ichernev** [comment]
Close in favor of #2456
