### ISSUE TITLE
Klingon locale

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2431]
I recently stumbled upon this most excellent resource:

### [A Quick Reference to Time Expressions in Klingon](http://klingonska.org/ref/time.html)

There would appear to be enough detail in here to create a Klingon locale for moment.js.

IMHO, this would be a fun addition to the library!  I've not got the time to do it myself, but perhaps someone would like to pick it up?

Related:
- [The Klingon Language Institute](http://www.kli.org/)
- [Bing Translator](https://www.bing.com/translator/) (has two Klingon settings)

**Comment by jisaacks** [comment]
:+1:

**Comment by ichernev** [comment]
Klingon is definitely known by more people that half the locales we support, so why not adding it in.

**Comment by amaranthrose** [comment]
I would be happy to help. In fact, I've already started preparing tlh locale along with tests, but stumbled upon a problem. Klingons most probably call our months like "te­ra’ jar vagh" (Terran month May), which makes it three words. That doesn't pass parsing tests so I wanted to ask if there is a reason only arabic three word months are supported?

**Comment by victorherraiz** [comment]
:+1:

**Comment by amaranthrose** [comment]
I've created a locale, just need to get some parsing tests to pass.

**Comment by mj1856** [comment]
Cool! Go ahead and submit a PR with what you have and we can look at it from there.

BTW - I'm not super concerned with this one being perfect.  I see it as more of a fun addition.

> :star2: *OMG - It's even got Klingon!!!* :star2:

If not all features work, that's fine by me.

**Comment by mj1856** [comment]
![image](https://cloud.githubusercontent.com/assets/1396388/10382644/dac85af0-6dda-11e5-84db-d8f1de4716e2.png)

**Comment by avindra** [comment]
This should be closed out now with the 2.11.0 release.
