### ISSUE TITLE
Get months and monthsShort arrays for locale without changing the global locale

### ISSUE THREAD

**Issue by arqex** [moment/moment#2433]
Hi,

I am creating a calendar with i18n support using moment.js and it works nice for main languages but Spanish. In every locale file `monthsShort` is defined as an array but in Spanish it is a function, and I can't access to the list of short months names.

It seems to the single language to have that function, that only serves to add a point at the end of the month ( can't that be done by the user of moment.js? )

Cheers,
Javi

**Comment by mj1856** [comment]
I'm not sure what exactly you mean.  `monthsShort` is always exported as a function from the locale file, though it's up to each locale to implement that function however it chooses.

Ultimately it's intended to be invoked as a function from `moment` like this:

![image](https://cloud.githubusercontent.com/assets/1396388/8289212/cc7d738c-18cf-11e5-88ca-ee451ad32206.png)

**Comment by arqex** [comment]
Hi @mj1856 

Thanks for the prompt reply. Getting the shortnames from the global local is not a problem, The problem is getting the shortnames from a single moment object with a locale defined:

```js
// Global locale is 'en'
var m = moment().locale('de');

// Now I will try to get the weekdays,
// With current API I just can have the current day
m.localeData().monthsShort(m); // "Jun."

// But I can use the private property to get the list
m.localeData()._monthsShort; // All the german month names

// Now in spanish
var mEs = moment().locale('es');

// I can't get the names at once
mEs.localeData()._monthsShort; // I get the names in English, because it was defined as a function
```

I know that I shouldn't use private properties, but I don't want my calendar to set the global locale for moment.js, it would be great that it can be shown in whatever language is its specific moment object.

**Comment by mj1856** [comment]
We can't expect private properties to meet any particular contract across locales, but I do agree with you that you should be able to easily get an array of month names (long or short) for a specific locale without having to change the global locale.

Come to think of it, I'm really not sure why `.months()` and `.monthsShort()` need a moment passed as an argument anyway.  I would expect them to *always* return an array of all month names.  If one wants a single value, they should either pick out an item from the array, or just use the regular `moment().format()` function with the `MMM` or `MMMM` tokens.

Though, removing the existing functionality would be a breaking change, so perhaps leave that intact.  I don't see anything wrong with having it return an array when no parameters are passed instead of the error it gives currently.

**Comment by mj1856** [comment]
For clarity, proposed API is:

```javascript
moment.localeData('es').months()   // ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]
moment.localeData('es').monthsShort()  // ["Ene.", "Feb.", "Mar.", "Abr.", "May.", "Jun.", "Jul.", "Ago.", "Sep.", "Oct.", "Nov.", "Dic."]
```

And it would also work given a moment *instance*, or without a parameter to `localeData` (to use the global locale).

The results are identical to the `moment.months()` and `moment.monthsShort()` functions, but work without changing the global locale.

Alternatively (or additionally), we could use this API:

```javascript
moment.months('es')
moment.monthsShort('es')
```

Which does the same thing, but takes a locale as a parameter to the existing functions.

**Comment by mj1856** [comment]
@arqex - In the meantime, you can use a hack like this:

```javascript
function forLocale(locale, fn) {
    var temp = moment.locale();
    moment.locale(locale);
    var result = fn();
    moment.locale(temp);
    return result;
}

var a1 = forLocale('es', moment.months);
var a2 = forLocale('es', moment.monthsShort);
// etc...
```

**Comment by arqex** [comment]
Hi @mj1856 

Good idea the one of changing the global locally temporary, I'll use it in the meanwhile :+1: 

As for the proposed methods for the API, any of both would be great.

Thanks

**Comment by ichernev** [comment]
The proposed API makes sense. I'll merge a PR.

**Comment by mj1856** [comment]
Cool.  Thanks!

**Comment by maciej-gurban** [comment]
I couldn't find any mention of such API in the docs. Did it ever get merged?

**Comment by vzaidman** [comment]
Hey!
Where does it stand?

**Comment by ichernev** [comment]
Those work in `2.20.1` and possibly much earlier :)

```
moment.localeData('es').months()
moment.localeData('es').monthsShort()
```
