### ISSUE TITLE
Formatting with more than three S tokens repeats

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2436]
We don't want to support finer precision than milliseconds, but we do need to contend with working with strings containing such precision, even if we truncate.

Parsing is already supported, with any number of decimal places. But formatting has some weirdness is that it repeats the value in the formatting.

```javascript
moment('2014-07-30 02:59:32.123456789','YYYY-MM-DD HH:mm:ss.SSSSSSSSS').format('YYYY-MM-DD HH:mm:ss.SSSSSSSSS')
// returns: "2014-07-30 02:59:32.1231231"
// expected: "2014-07-30 02:59:32.1230000"
```

See also #2022

**Comment by ichernev** [comment]
I agree, its a bug, and its easy to fix. Will merge a PR.

**Comment by mj1856** [comment]
Thanks!

**Comment by ichernev** [comment]
Docs currently state only `S`, `SS` and `SSS`, code support `SSSS`, which does the same as `SSS`. I think I'll have to add for up to 9 `S`s.

**Comment by ichernev** [comment]
Close in favor of #2448
