### ISSUE TITLE
how can i set number to chinese character

### ISSUE THREAD

**Issue by david43** [moment/moment#2437]
Hi,
is it possible set number to chinese character
2015/06/25 = 貳零壹伍/零陸/貳伍
0,1,2,3,4,5,6,7,8,9,10
零、壹、貳、叄、肆、伍、陸、柒、捌、玖、拾
Thanks

**Comment by ichernev** [comment]
Well, if these characters are not used to designate things (like minutes, months), then its possible to support parsing (and printing, but I don't think people want that).

**Comment by mj1856** [comment]
Do we even have facilities in moment to support this?  I would think we'd need something in the locale API to support this.

Also note that even in the above example, 0 and 10 have different symbols in Chinese.  I do not speak it, but I would guess that there may be other specific symbols for 11, 12, etc. and higher numbers, and other languages would have to be handled differently.

So the API would have to be a function that exchanged a *number* for a symbol, not a single digit.

**Comment by mj1856** [comment]
Funny, If I run that array through Google Translate, I get:

> Zero, one, two, three, wantonly, Wu Lu, Qi, eight, Nine, pick up

**Comment by mj1856** [comment]
And if I run "one, two, three, four, five, six, seven, eight, nine, ten" through, I get different symbols:

> 一二三四五六七八九十

I'm sure there are cultural or contextual reasons why one set of symbols would be preferred over the other.

Still, I think asking for this feature is similar to asking for natural language parsing in English and other languages, which we've rejected many times before.   My vote is to close.

**Comment by mj1856** [comment]
@hanzzhang - care to comment since you are fluent in Chinese?

**Comment by hanzzhang** [comment]
Regard the questions:
is it possible set number to chinese character
 2015/06/25 = 貳零壹伍/零陸/貳伍
0,1,2,3,4,5,6,7,8,9,10
零、壹、貳、叄、肆、伍、陸、柒、捌、玖、拾
those above Chinese characters are not used for date time. they are used for currency.

To represent 2015/06/25 in Chinese, you can do the following:
1. casual: 2015/25/06 , or 25/06/2015.       Note that date is before the month
2. a little formal: 2015年6月25日                       (年=year； 月=month， 日=day)
3. more formal: 二零一五年六月二十五日

I would say, 1 is used 20% of time, 2 is used 60% of time and 3 is used 20% of time.

**Comment by mj1856** [comment]
Thanks @hanzzhang!

**Comment by david43** [comment]
thanks for the help
now ,
I just use a array replace the time
var chinese_word = ['零', '壹', '貳', '叁', '肆', '伍', '陸', '柒', '捌', '玖', '拾'];

**Comment by ichernev** [comment]
Just add a preparse function, like here: https://github.com/moment/moment/blob/develop/src/locale/my.js#L69

Pull requests welcome.

**Comment by Oire** [comment]
@david43, would you submit a PR to get this fixed, please? Or it isn't needed at all if used only 20% of time? Thanks!

**Comment by iojw** [comment]
https://github.com/moment/moment/pull/3952 adds support for both 1 and 2, which I believe is sufficient as a Chinese speaker myself. Even articles published in Chinese newspapers (eg. http://politics.people.com.cn/n1/2018/1106/c1024-30383446.html, https://tw.appledaily.com/politics/realtime/20181106/1461431) use the format shown in 2. The format using all Chinese characters for the numerals (shown in 3) is rare.

**Comment by marwahaha** [comment]
Closing as per @iojw .

Please re-open if you still have issues.
