### ISSUE TITLE
Expose function to return parsed format

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2441]
Consider:

```javascript
var m = moment("29-06-1995", ["MM-DD-YYYY", "DD-MM", "DD-MM-YYYY"]);
```

How does one determine *which* format was used?  Currently, the only way is by checking the `_f` private field.   It would be useful if there was a function that returned this as part of the public API.

Ref: http://stackoverflow.com/q/31101657/634824

**Comment by ichernev** [comment]
Lets implement it like this: https://github.com/moment/moment/issues/2443#issuecomment-129930609

**Comment by maggiepint** [comment]
This has worked for a year!
