### ISSUE TITLE
Feature request: public API for getting _i

### ISSUE THREAD

**Issue by jamesarosen** [moment/moment#2443]
I have a use-case where module A (at the data layer) parses user-inputted strings into `moment` objects and module B (at the UI layer) needs to emit error messages if the string can't be parsed.

```js
feztober3 = moment('3 Feztober, 1992');
feztober3.isValid(); // false, good
feztober3.format('YYYY-MM-DD'); // 'Invalid Date', good
```

But I can't get `'3 Feztober, 1992'` back out of `feztober3` without using the private `._i`. I'd love something like `moment.source()` so I could do

```js
date(moment) {
  if (moment.isValid()) {
    return `<time datetime="${moment.format('X')}">${moment.format('YYYY-MM-DD')}</time>`;
  } else {
    return `<span class='invalid-date'>Invalid Date: ${moment.source()}</span>`;
  }
}
```

**Comment by ichernev** [comment]
Pull requests welcome. Make a function `creationData()`, that returns an object with `input`, `format`, `isUTC`, `locale`.

**Comment by jamesarosen** [comment]
Will do!

**Comment by mj1856** [comment]
Completed in 2.11.0 with #2443.
