### ISSUE TITLE
isSame returns false when using same ISO src string

### ISSUE THREAD

**Issue by cdaringe** [moment/moment#2447]
Hi all:

```js
d.sometime === t1.format() //=> true
t1.format() //=> "2015-07-04T15:16:23-07:00"
t1.isSame(d.sometime) //=> false
```

For an actual test bed, you can ref: https://github.com/cdaringe/ampersand-state-mixin-datatype-iso-date/blob/master/test/test.js#L42.

I would expect `.isSame(...)` to return `true` in this example.  If I am mistaken, please let me know!

Thanks!

**Comment by mj1856** [comment]
Probably a precision issue.  `t1` has milliseconds?

**Comment by cdaringe** [comment]
that's gotta be it.  closing, under the high likelihood that that will be the case
