### ISSUE TITLE
Circular dependency when using i18n via RequireJS?

### ISSUE THREAD

**Issue by riddla** [moment/moment#2466]
I`m having a problem that is mentioned in the comments of http://stackoverflow.com/a/17242839/341983: how do you load a 'translated' version of moment.js via RequireJS (correctly)?

```
require.config({
    paths      : {
        'moment'                : '../bower_components/moment/moment',
        'momentDE'              : 'vendor/moment/locale/de'
    },
    shim       : {
        'moment': ['momentDE']
    }
});

define(function (require) {
    var moment = require('moment');
});
```

I ended up with a circular dependency when I set the localization as a dependency. (I guess the `moment` requirement within `de.js` causes this.)

My current workaround:

```
require.config({
    paths      : {
        'moment'                : '../bower_components/moment/moment',
        'momentDE'              : 'vendor/moment/locale/de'
    }
});

define(function (require) {
    var moment = require('momentDE');
});
```

I made a change within the locale file (`vendor/moment/locale/de.js`) to make this construct work. Instead of `return de` I use `return moment` to loop the moment object/library trough.

Is there a better way?

**Comment by marwahaha** [comment]
@riddla - do you still have this issue?

**Comment by riddla** [comment]
Sorry, my RequireJS days are long over and can't (re-)test it :)

**Comment by marwahaha** [comment]
Ok, closing. For those reading, please open a new issue if you are having trouble with this.
