### ISSUE TITLE
locale-specific longDateFormat (without the year)

### ISSUE THREAD

**Issue by saifelse** [moment/moment#2468]
Currently, I see there is a way to access the longDateFormat for a particular locale, but no way to get that same format without the year, e.g. there are cases when I want to show the full date, as YYYY/MM/DD or DD/MM//YYYY (depending on the locale), which I can do with the longDateFormat, but there are times where this is too verbose (ie, YYYY is the current year), and I'd prefer MM/DD or DD/MM.

As [suggested on StackOverflow](http://stackoverflow.com/q/27360102), one could perform some "surgery" to produce the desired result, but it would be nice for there to be an officially supported way of the longDateFormatWithoutTheYear.

**Comment by mj1856** [comment]
:+1:

**Comment by ichernev** [comment]
Well, this requires changes to all locales to actually provide the data. The surgery is a mathematical way to solve a non-mathematical problem. Its plain wrong. It might work, but it might as well not.

If you need custom formats you can fetch them from CLDR and use them as a workaround for now.

**Comment by marwahaha** [comment]
closing in favor of https://github.com/moment/moment/issues/4325
