### ISSUE TITLE
help with date pattern validation

### ISSUE THREAD

**Issue by iamstarkov** [moment/moment#2470]
As far as [I cannot rely explicitly on `new Date` validation](http://stackoverflow.com/q/30964943/1057730), I decided to validate input dates with date patterns. But it still not work for me.

* `D DD` is for Day of month
* `MMM MMMM` is for Month name in locale set by moment.locale()
* `YYYY` is for 4 digit year
```js
var pattern = 'DD MMMM YYYY';
moment(new Date('asd qw 101'), pattern).isValid(); // false and it is okay
moment(new Date('21 June 2015'), pattern).isValid(); // false and it is actually, "why?"
```

I helplessly lurked documentation and its not worked for me. Can anybody help me and explain why second check return false, while passed String is valid Date string?

**Comment by mj1856** [comment]
Try using the moment constructor directly, and enable strict mode.

```javascript
var pattern = 'DD MMMM YYYY';
moment('asd qw 101', pattern, true).isValid()  // false
moment('21 June 2015', pattern, true).isValid()  // true
```

**Comment by iamstarkov** [comment]
Thanks

**Comment by iamstarkov** [comment]
@mj1856 thank you It really helped, but I also found one strange bug with strict validation for locale dates #2527
