### ISSUE TITLE
deprecate function slow down Firefox 10

### ISSUE THREAD

**Issue by Xaar37** [moment/moment#2479]
The call to "new Error()).stack" in the "deprecate" function slow down Firefox 10 (even if you don't use any deprecated function). Moving "new Error()).stack" where it is used is a possible fix: 

```javascript
function deprecate(msg, fn) {
        var firstTime = true;

        return extend(function () {
            if (firstTime) {
                warn(msg + '\n' + (new Error()).stack);
                firstTime = false;
            }
            return fn.apply(this, arguments);
        }, fn);
    }
```

Momentjs version is 2.10.3.

**Comment by mj1856** [comment]
Performance complaints should have some benchmarks.  Can you provide some idea of how much this actually affects performance?

Also, this might be better as a pull request, so we can see the exact change you are proposing.

Thanks.

**Comment by Xaar37** [comment]
You can see the performance issue on those two screens:

Original:
![original](https://cloud.githubusercontent.com/assets/13312987/8717701/18d1471e-2b9e-11e5-93ba-df9fa3c26761.png)

With modification:
![modified](https://cloud.githubusercontent.com/assets/13312987/8717706/247a49ee-2b9e-11e5-8a56-05998f73e953.png)

I just created a pull request #2489.

**Comment by mj1856** [comment]
Thanks!

**Comment by ichernev** [comment]
Closing, #2489 is merged.
