### ISSUE TITLE
subtract and add a bit confusing

### ISSUE THREAD

**Issue by Polopollo** [moment/moment#2481]
//In chrome
now = moment();
now.subtract(1, 'day').toDate() === now.add(-1, 'day').toDate(); //true
now.subtract(-1, 'day').toDate() === now.add(-1, 'day').toDate(); //true
now.subtract(-1, 'day').toDate() === now.subtract(1, 'day').toDate(); //true!!!
now.subtract(1, 'day').toDate() === now.add(1, 'day').toDate(); //true!!!
now.add(1, 'day').toDate() === now.add(-1, 'day').toDate(); //true!!!

Shouldn't it be false at one point?!

**Comment by mj1856** [comment]
`add`, `subtract`, and many other functions *mutate* the moment object.  Moments are not immutable.

Also, you can't compare `Date` objects directly.  Consider `new Date(0) !== new Date(0)`.   With `Date` objects, you can call either `.valueOf()` or `.getTime()`, which both return the same result as calling `.valueOf()` on a moment object.

**Comment by mj1856** [comment]
Small clarification, you can *compare* date objects using `>`, `<`, `>=`, and `<=`.  You just can't *equate* them with `==`, `!=`, `===`, or `!===`.

Javascript is weird.
