### ISSUE TITLE
merge/overwrite only parsed values to existing moment

### ISSUE THREAD

**Issue by s-light** [moment/moment#2482]
hey i hope this is the right place for a feature request.
eventually it is already possible to accomplish this - but i did not find the right way.

if i have a valid moment - is it possible to merge a user .format(UserInput, formatstring, strict_parsing)?
so that only the parts that are given in the formatstring and successfully parsed are merged?
that would make it easier if you want to merge two user-inputs to one date object.
(for example in this [angular.js date/time input formater directive](http://plnkr.co/edit/I87YcH?p=preview))

**Comment by mj1856** [comment]
Sorry, but I'm not sure I am fully understanding the request.

It sounds like you just want to do something like this?

```javascript
var s1 = '2015-07-17';
var s2 = '12:34:55';

var f1 = 'YYYY-MM-DD';
var f2 = 'HH:mm:ss';

var moment = moment(s1 + ' ' + s2, f1 + ' ' f2, true);
```

If so, I'm not sure why we need a function for that built-in.  Or is there more to your request?

**Comment by ichernev** [comment]
@mj1856  Well, if you have multiple `YYYY` in the formats, what will happen? It is a reasonable hack, that might work in some cases, though :)

@s-light this feature that you're describing is pretty specific. Maybe if you patch the parser (it should be `.parse`, not `.format` btw), and expose information about what got parsed, you can then proceed and merge them. But what if they conflict? What if one is in week-weekday-weekyear, and the other is in month-day-year and they mismatch? What if there are conflicting token values (YYYY with 2015 and 2016). All of these you should ultimately decide for yourself, and I don't think this has place in moment.

Making the parser a bit more abstract and usable standalone -- this is something I might merge, but you have to implement it, and it has to not make the existing code smell.

**Comment by s-light** [comment]
@ichernev you are right - parsing is the right word and there are some more things to consider...
i have done a version with fixed merging:
```javascript
// global definition (example for date input type - differs for time input type)
    var mergeParts = ['year', 'month', 'date'];
// in my userinput parsing function
    // momentjs with strict parsing
    var tempDate = moment(viewValue, formatString, true);
    angular.forEach(mergeParts, function(value, key) {
        modelValueMoment.set(value, tempDate.get(value));
    });
```
this is working. but with this merging only works for date OR time and is not based on the user formating string.
 
the idea was be able to do something like this:
```javascript
// global definitions/declarations
var formatDate = 'YYYY-MM-DD';
var formatTime = 'HH:mm:ss';
// initialize to now
var myDate = moment();

// for example in a onClick handler
// merge userinput for date
var userInputDate = '2015-07-17';
myDate.mergeIn(userInputDate, formatDate, true);

// different event/part of code
// merge userinput for time
var userInputTime = '12:34:55';
myDate.mergeIn(userInputTime, formatTime, true);

```
the merge will overwrite only the parts that are given in the format string and only do this if the userInput can be parsed successfully.
so 'internally' something like (pseudo code)
```javascript
// Method Signature could be the same as
// http://momentjs.com/docs/#/parsing/string-format/
function merge(input, format, strict) {
    // parsing
    ...
    // now set date with parsed parts:
    if(parsed_parts contain 'year')
        internalDate.set('year', parsed_year);
    if(parsed_parts contain 'month')
        internalDate.set('month', parsed_month);
    ..
    if(parsed_parts contain 'millisecond')
        internalDate.set('millisecond', parsed_millisecond);
    // some finalizing
    ...
}
```
hopefully i have made it in someway clearer what i try to do?

**Comment by ichernev** [comment]
You can expose info about what got parsed. And then use it in your custom merge fn.

**Comment by marwahaha** [comment]
Closing due to age. Please re-open if you still have questions.
