### ISSUE TITLE
Time zone on UTC time works incorrectly

### ISSUE THREAD

**Issue by fyodorvi** [moment/moment#2483]
```javascript
moment.utc('2015-07-05T23:16:00Z').tz('Europe/Warsaw').format() // 2015-07-06T01:16:00+02:00
```

01:16:00+02:00 is incorrect, it should be 23:16:00+02:00

**Comment by mj1856** [comment]
How could it be 23:16?  That's the same time you started with?

The ISO8601 standard format says that when an offset is given, the corresponding time is the *local* time associated with that offset.  In other words, the offset has already been applied.

[Conversion below, as verified here:](http://www.timeanddate.com/worldclock/converted.html?iso=20150705T2316&p1=0&p2=262)

![image](https://cloud.githubusercontent.com/assets/1396388/8710214/faa7978a-2afc-11e5-8457-915a5cc9cafe.png)
