### ISSUE TITLE
Cannot parse short monthnames with periods

### ISSUE THREAD

**Issue by s1738berger** [moment/moment#2488]
In some locales the short monthnames have a trailing period. In german ('de') for example 'Jan._Febr._....'
When I try to parse something like this: '20 Jan. 2013' with the format 'DD MMM YYYY' I cannot get true from the isValid() function in strict mode. Without strict it is valid, but a lot of other crap too.

`<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>`
`<script type="text/javascript" src="http://momentjs.com/downloads/moment-with-locales.js"></script>`
`<script type="text/javascript">`
var date = '20 Jan. 2013';
var format = 'DD MMM YYYY';
var locale = 'de'
var valid = 0;
moment.locale(locale);
document.writeln(moment.monthsShort(0));
moment(date, format, locale, true).isValid() ? valid = 'true' : valid = 'false';
document.writeln(date + ' ' + format + ' ' + locale  + ' ' + 'Valid: ' + valid);
`</script>`

**Comment by mj1856** [comment]
Agreed.

```javascript
moment.locale('de');
var s = moment().format('ll');  // "16. Jul. 2015"
moment(s,'ll').isValid(); // true
moment(s,'ll',true).isValid(); // false <=== should be true
```

**Comment by mj1856** [comment]
Dup #2186

**Comment by s1738berger** [comment]
right, I wasn't aware of this duplicate.
For my 'german-date' problem I found a workaround:
 var s = moment().format(['DD. MMM. YYYY HH:mm','DD. MMM YYYY HH:mm']);
not nice, but until moment.js will be fixed this is a working solution.
Thanks for the great work on dates
