### ISSUE TITLE
Using fromNow() with interval multiple times

### ISSUE THREAD

**Issue by aHumanBeing** [moment/moment#2495]
Hi,

I have a table which grows / shrinks dynamically (usually max 50 - 60 records).  Within each row, I am using fromNow() to display the amount of time elapsed from a specific date. I'm trying to understand how I get the time to update using interval and in an efficient way so that I don't take a hit on performance by doing something wrong.  Can anyone help?

Thanks

**Comment by mj1856** [comment]
Do you have a specific question?  It's difficult to answer without seeing any code.  Are you experiencing a performance problem?

**Comment by aHumanBeing** [comment]
I actually found A solution today using http://timeago.yarp.com/

I needed to display time continuously from a specific date on multiple rows in my table. Thanks for reaching out.
