### ISSUE TITLE
.isoWeeks does not retain year

### ISSUE THREAD

**Issue by stefanmajoor** [moment/moment#2496]
From the docs: (http://momentjs.com/docs/#/get-set/iso-week/)

> Gets or sets the ISO week of the year.

This suggests that:

```
var date = moment(2016, 'YYYYY');
date.isoWeeks(1);
console.log(date.format('YYYY-MM-DD'));
```

Calculates the first week of 2016, however the result is:

2015-01-02

**Comment by mj1856** [comment]
The first line should use `moment("2016","YYYY")`, but yes - there is a bug here.

There's something strange going on...

```javascript
for (var i = 1990; i <= 2020; i++)
{
  var m = moment([i,0,1]).isoWeek(1);
  if (m.year() != i)
    console.log(i + " => " + m.format("YYYY-MM-DD"))
}
```

```
1993 => 1992-01-03
1994 => 1993-01-09
1995 => 1994-01-09
1999 => 1998-01-02
2000 => 1999-01-09
2005 => 2004-01-03
2006 => 2005-01-09
2010 => 2009-01-02
2011 => 2010-01-09
2012 => 2011-01-09
2016 => 2015-01-02
2017 => 2016-01-10
```

As you can see, only certain years are affected.

**Comment by mj1856** [comment]
This may or may not be related to #2033

**Comment by ichernev** [comment]
Yes, these are related; yes, its a bug. I'm accepting patches as usual. If not I might patch it some day :)

**Comment by julienboulay** [comment]
Same issue with week() function.

Using 
```var date = moment(2016, 'YYYY');
date.add(1, 'weeks');```
works for me.

**Comment by mj1856** [comment]
Closing in favor of #2033.  Same bug.
