### ISSUE TITLE
Month names and day names should not be capitalized in Spanish

### ISSUE THREAD

**Issue by mattbailey** [moment/moment#2497]
These should all be downcased

https://github.com/moment/moment/blob/develop/locale/es.js

source: http://spanish.about.com/od/writtenspanish/a/capitalization.htm

**Comment by ichernev** [comment]
@julionc can you comment on this, please?

**Comment by ichernev** [comment]
@mattbailey can you make a PR (after julionc approves), you also need to change tests. Check https://github.com/moment/moment/blob/develop/CONTRIBUTING.md

**Comment by mattbailey** [comment]
@ichernev does @StevenHeinrich's PR #2498 not cover the tests?

**Comment by wind39** [comment]
In Brazillian Portuguese, it is the same case.

**Comment by julionc** [comment]
Thank you for the notice @ichernev @mattbailey
That's correct.
In Spanish, names of months and weekdays are written in lower case.
[Source here] (http://www.rae.es/consultas/mayuscula-o-minuscula-en-los-meses-los-dias-de-la-semana-y-las-estaciones-del-ano), and the PR #2498 is OK

**Comment by ichernev** [comment]
Thank you everyone. Close in favor of #2498.
