### ISSUE TITLE
locale-specific shortDateFormat (with 2 digit year)

### ISSUE THREAD

**Issue by lukapopovic** [moment/moment#2499]
Hello there! 

I am currently working on a project, where moment.js saved days and days of my life. I must say it is a great library, and I really appreciate the work that you guys have done. I recently run into one small problem which is, I hope, solvable. The locale specific shortDate format looks like this now: 09/04/1986. I was wondering if it is possible to have the version of date with the 2 digit year representation, like 09/04/86? Thank you guys in advance, and keep up the good work!

Luka

**Comment by mj1856** [comment]
Thanks.

This has already been requested in #2158.
