### ISSUE TITLE
Is isBetween active unexpectedly?

### ISSUE THREAD

**Issue by krzkrzkrz** [moment/moment#2501]
Whats going on here? its clear that `deliverAt` is between `timeNow`and `timeNow + 2 hours`.

Am I doing something wrong?

    console.log(deliverAt); // Moment {_isAMomentObject: true, _i: Thu Jul 23 2015 04:20:51 GMT+0800 (SGT), _isUTC: false, _locale: Locale, _d: Thu Jul 23 2015 04:20:51 GMT+0800 (SGT)}
    console.log(timeNow);   // Moment {_isAMomentObject: true, _i: Thu Jul 23 2015 03:41:38 GMT+0800 (SGT), _isUTC: false, _locale: Locale, _d: Thu Jul 23 2015 03:41:38 GMT+0800 (SGT)}
    console.log(timeNow.add(2, 'h')); // Moment {_isAMomentObject: true, _i: Thu Jul 23 2015 03:41:38 GMT+0800 (SGT), _isUTC: false, _locale: Locale, _d: Thu Jul 23 2015 05:41:38 GMT+0800 (SGT)}
    console.log(deliverAt.isBetween(timeNow, timeNow.add(2, 'h'))); // false

**Comment by mj1856** [comment]
Moments are mutable.  If you want to retain the original moment, you need to clone it before adding.  You can use either `moment(timeNow).add(2,'h')`, or the more explicit `timeNow.clone().add(2,'h')`.  Both do the same thing.
