### ISSUE TITLE
unicode string returned from add subtract startOf endOf functions

### ISSUE THREAD

**Issue by emergingdzns** [moment/moment#2502]
I'm using momentjs 2.4.0.

I have a need to be able to get the start of the current day and end of current day, start of previous day and end of previous day, start of previous week and end of previous week etc.

So in my code I have:
```
$(document).on('change', '#date-range-select', function() {
	var m = moment();
	switch($(this).val()) {
		case 'today':
			start = m.startOf('day').fromNow();
			end = m.endOf('day').fromNow();
			break;
		case 'yesterday':
			start = m.startOf('day').subtract(1, 'days').calendar();
			end = m.endOf('day').subtract(1, 'days').calendar();
			break;
		case 'lastweek':
			start = m.startOf('week').subtract(7, 'days').calendar();
			end = m.endOf('week').subtract(7, 'days').calendar();
			break;
	}
	console.log(start);
	console.log(end);
});
```
When I change the field to any one of these options, the resulting console.log is something like this:
```
昨天早上12點00分
上星期二晚上11點59分
```

If I change the function for `today` to:
```
start = m.hours(0).minutes(0).seconds(0).milliseconds(0);
end = m.hours(23).minutes(59).seconds(59).milliseconds(0);
```
When I run the function, I get moment objects, which according to the documentation, I should also get from the startOf and endOf functions.

I tried to change the `lastweek` functionality to do the longer method like in `today` but with the subtract function. It still results in the asian characters in the console.log.

I can't for the life of me figure out why this is happening.

Appreciate the help!

**Comment by mj1856** [comment]
This is already covered in #2367.  Until the fix is released in the next version, you can simply be sure to set the locale explicitly.

```javascript
moment.locale('en');
```

**Comment by mj1856** [comment]
FYI - 2.10.5 was released today, which fixes this issue.  Thanks.
