### ISSUE TITLE
moment iso date parsing difference between 2.10.3 and 2.10.5

### ISSUE THREAD

**Issue by timbell** [moment/moment#2512]
Hello,

Using 2.10.3 I was parsing likely ISO 8601 dates like this:

    var m = moment(datestr, moment.ISO_8601);
    if (m.isValid()) {
        ...

and things worked as expected when passing **invalid** dates. On updating to 2.10.5 this is no longer the case  - I get an exception in the moment call. The exception is thrown here:

    function Moment(config) {
        copyConfig(this, config);
        this._d = new Date(config._d.getTime());
        
because config._d is undefined.

Should I be doing things differently or is this a regression?

Jsfiddle showing the 2.10.3 behaviour here: http://jsfiddle.net/xnvofgrm/

Thanks,

Tim

**Comment by vsumner** [comment]
+1

**Comment by Zehapokihe** [comment]
+1

**Comment by ichernev** [comment]
I'll cut a new version today. Thanks for the report.

**Comment by ichernev** [comment]
2.10.6 release. Sorry for the trouble.
