### ISSUE TITLE
possible duration bug for calculating days

### ISSUE THREAD

**Issue by amccarthyMatchbook** [moment/moment#2513]
"2.10.3"
moment.duration(123456, 'minutes').asDays()
85.73333333333333
moment.duration(123456, 'minutes').days()
25

"2.10.5"
moment.duration(123456, 'minutes').asDays()
85.73333333333333
moment.duration(123456, 'minutes').days()
24

should this be 25 days?

**Comment by ichernev** [comment]
This has months in it, so depends on how you count them. The logic changed for the better. So its a feature.

**Comment by ioloie** [comment]
Isn't this inconsistent with how the other similar methods in durations work?

```
moment.duration(1234567, 'minutes').asMonths()
=> 28.167746999139837 (2 years + 4 months)
moment.duration(1234567, 'minutes').months()
=> 4 

moment.duration(12345, 'minutes').hours()
=> 13
moment.duration(12345, 'minutes').asHours()
=> 205.75 (8 days + 13 hours)
```

**Comment by ichernev** [comment]
@ioloie I don't get your comment. 28.16 is 24 + 4 (2 years and 4 months), and 205 is 8 * 24 + 13, so what is your point exactly, and what is inconsistent.

Those examples are from `2.10.5`. To be fair, the exact same examples produce the exact same result in `2.10.3` :)

**Comment by ichernev** [comment]
@amccarthyMatchbook to be more accurate, `moment.duration(123456, 'minutes').asDays() // 85 days` is 2 months and 24 days in 2.10.5 and 2 months and 25 days in 2.10.3, so in one case 60 days is two months (less accurate), in the other its 61 (more accurate).

All of those are approximations, so I don't think changing the values a bit should affect anybody (they are just displayed for convenience). If you have 2 date difference -- use the special duration constructor `{ from, to }`. It will preserve number of months and days exactly.

**Comment by ioloie** [comment]
The inconsistency occurs in the case of `days` where the output is one less than the remainder of the output of `asDays`:

```
moment.duration(123456, 'minutes').asDays()
=> 85.73333333333333 (2 months + 25 days)
moment.duration(123456, 'minutes').days()
=> 24 (1 less than 25)
```

**Comment by ichernev** [comment]
If you count 2 months as 60 days. It can be more / less.
