### ISSUE TITLE
How to load only locales i want?

### ISSUE THREAD

**Issue by schovi** [moment/moment#2517]
I am using Webpack and your npm package. Unfortunately it require all locales at once.
Webpack knows they are optional

    [252] ./~/moment/locale/bs.js 4.59 kB {0} {1} [optional] [built]
    [253] ./~/moment/locale/ca.js 2.85 kB {0} {1} [optional] [built]
    [254] ./~/moment/locale/cs.js 5.79 kB {0} {1} [optional] [built]

but for some reason they are not droped. Is there any way how to require just core with selected locales?

**Comment by mj1856** [comment]
You can always take individual locale files [from here](https://github.com/moment/moment/tree/develop/locale).

The docs describe [how to load them](http://momentjs.com/docs/#/i18n/loading-into-nodejs/)

But I think what you're asking is how to load them individual via npm?  I'm not sure if that's possible without having a separate npm package for each locale.

**Comment by schovi** [comment]
I described my problem badly. Another try :)

In my app I installed momentjs with `npm install moment` and require it `var moment  = require('moment')`
Then it automatically require all locales for some reason. In Webpack log it is described 

    [239] ./~/moment/moment.js 104 kB {0} {1} [built]
    [240] ./~/moment/locale ^\.\/.*$ 2.06 kB {0} {1} [optional] [built]
    [241] ./~/moment/locale/af.js 2.58 kB {0} {1} [optional] [built]
    [242] ./~/moment/locale/ar.js 4.52 kB {0} {1} [optional] [built]

For some reason and I cant find in momentjs source why it require all locales with this `./~/moment/locale ^\.\/.*$`

What i want is to require only `moment` and separatly `moment/locale/cs` and `moment/locale/en-gb`

Any suggestion?

**Comment by ichernev** [comment]
@schovi I'm not familiar with webpack, but you can do the following experiment. 

1) Put a console.log into one of the locale files.

```patch
--- /home/iskren/src/moment/locale/fr.js	2015-07-27 21:37:05.000000000 -0700
+++ locale/fr.js	2015-07-30 21:53:41.833619994 -0700
@@ -8,6 +8,8 @@
    factory(global.moment)
 }(this, function (moment) { 'use strict';
 
+    console.log("hello world");
+
 
     var fr = moment.defineLocale('fr', {
         months : 'janvier_février_mars_avril_mai_juin_juillet_août_septembre_octobre_novembre_décembre'.split('_'),
```

2) Require moment.js (via node command line) and verify it is NOT printed

```bash
$ node
> require("./moment")
// prints moment properties, but no "hello world"
```

3) Optionally require the locale to see that it IS printed
```bash
$ node
> require("./locale/fr.js")
hello world
{}
```

So this means Webpack is at fault and not the way we package moment. `jspm` and `spm` sections in `package.json` list locale as a thing, maybe it is related. Check Webpack source code, ask in their bug trackers ... etc :)

**Comment by ichernev** [comment]
@mj1856 just to be clear, the locale files are shipped with npm, so he should find them in his `node_modules/moment/locale` directory at best, not in the git repo (they are also in the git repo, but for npm users that is irrelevant).

**Comment by schovi** [comment]
Thanks for answer, will try to dig in webpack.

**Comment by rattrayalex** [comment]
FWIW, the size of the "moment" package shrinks from 364.36kB to 101.97kB (second-largest to fourth-largest package, going from twice-as-large to half-as-big as our company codebase itself) when I don't include the locales (done hackily by commenting out `require('./locale/' + name);` in `moment.js`). We don't use this feature at our company, so I'd love a supported way not to include these in our webpack bundle.

**Comment by mrberggg** [comment]
I suggest reopening this as it's not fixed. For anyone else looking for a fix, I found one [here](http://stackoverflow.com/questions/25384360/how-to-prevent-moment-js-from-loading-locales-with-webpack). In your webpack config, add the following to your plugins array: 

`new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en/)`

This is pretty hacky, dependent on that particular include not changing. An official method would be ideal. Could you perhaps add a `moment` section to the `package.json` file for config options, with an array of desired locales?

**Comment by mj1856** [comment]
Reopening per @mrberggg's feedback.  @ichernev, please take a look.  Thanks.

**Comment by mj1856** [comment]
Actually, closing this as dup of #1435.  Didn't see this before somehow.

**Comment by metamaker** [comment]
> Actually, closing this as dup of #1435. Didn't see this before somehow.

They are relevant, but absolutely different issues. The problem that people face here is not documenting moment.js behavior, but how to load only required locales and not all at once (how it is done in moment.js by default).

**Comment by balexandre** [comment]
jut to make a reference to an old topic about this exact issue on in webpack project

https://github.com/webpack/webpack/issues/87

**Comment by pbrain19** [comment]
The solution proposed looks great if you only use english. but what about the scenario you want to support all the moment js but only want to load the one you need to the browsers. The Dynamic loading works but it is inefficient in that it bundles all the locales to one bundle. When the bundle is requested it is essentially downloading the entire file. Has anyone found a good way such that that we only dynamically load the one you need? The only solution I see is making a locales.js file and that being a giant if else statement with one branch for each language file. tedious but would solve the issue of only loading the file I need.

**Comment by exoer** [comment]
import "moment/locale/fr"
    import "moment/locale/de"

**Comment by pbrain19** [comment]
For anyone that cares in the future. The solution which resulted to be the least hacky was to use the suggested `new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en/)` to only load my default language and then have my builder copy the moment files into a public folder. My browser app then requests the one it before it loads.

**Comment by mikegleasonjr** [comment]
@pbrain19 see this answer to include languages other than english: 
https://github.com/moment/moment/issues/1435#issuecomment-187100876

**Comment by pbrain19** [comment]
From a browsers perspective it will still bundle and load it to the browser. This is not the ideal behavior we want in the browser. The answer there only explains how to bundle the locales you want. What I was looking for was an ability to support all locales without loading them all to the browser.

**Comment by Mat-thieu** [comment]
Moment uses [dynamic requires](https://webpack.github.io/docs/context.html), Webpack can't know which locales you want to require during compile time so it loads the entire directory just in case it's required during runtime (where locale usage is defined).

```javascript
// moment.js:1837
function loadLocale(name) {
    var oldLocale = null;
    // TODO: Find a better way to register and load all the locales in Node
    if (!locales[name] && (typeof module !== 'undefined') &&
            module && module.exports) {
        try {
            oldLocale = globalLocale._abbr;
            var aliasedRequire = require;
            aliasedRequire('./locale/' + name);
            getSetGlobalLocale(oldLocale);
        } catch (e) {}
    }
    return locales[name];
}
```

**Comment by eigood** [comment]
The following snippet keeps the default en.js, en-*.js, and moment source in the primary bundles/entry points, while mapping all other locale files into a separate async loaded bundle.

Before:

```
         common-lazy-main.0.86c95acc47616cc81c89.bundle.js.gz     102 kB
```

After:

```
   locale-not-en-main.1.8f31af252992c69da121.bundle.js.gz    46.8 kB
     common-lazy-main.0.603eebddcd2bcf32c0d3.bundle.js.gz    54.5 kB
```


```
10:51:22 -0600 adam@tooz(MLO-63|REBASE-i):XXXX/react-player-prototype$ git diff HEAD^ HEAD
diff --git a/webpack.config.js b/webpack.config.js
index a11d0ed..395b7b3 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -79,9 +79,22 @@ let plugins = [
     'analyzer',
     'srcReplacement',
 ]
+const momentNotEnLocales = /node_modules\/moment\/locale\/(?!en-?).*\.js$/
 const splittingPlugins = [
     new webpack.optimize.AggressiveMergingPlugin(),
     new webpack.optimize.CommonsChunkPlugin({
+        async: 'locale-not-en',
+        minChunks(module) {
+            const {context, resource} = module
+            if (resource) {
+                if (resource.match(momentNotEnLocales)) {
+                    return true
+                }
+            }
+            return false
+        },
+    }),
+    new webpack.optimize.CommonsChunkPlugin({
         name: 'vendor',
         minChunks(module) {
             return module.context && module.context.indexOf("node_modules") !== -1
```

**Comment by JamesPlayer** [comment]
The solution here looks a little cleaner: https://medium.com/@michalozogan/how-to-split-moment-js-locales-to-chunks-with-webpack-de9e25caccea

```
# webpack config
...
plugins: [
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
],
...
```

**Comment by peterpeterparker** [comment]
It's me or the webpack "solution" like `new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /a^/)` isn't applicable anymore with Angular v6 (since webpack can't be ejected)?

**Comment by jvanderbiest** [comment]
@peterpeterparker for Angular-CLI see: https://github.com/angular/angular-cli/issues/6137#issuecomment-419822929

**Comment by peterpeterparker** [comment]
@jvanderbiest cool I may give a try. In the meantime I just remove all the unnecessary locales (the one I don't use) straight in node_modules after each install. Ugly but does the job

**Comment by kievsash** [comment]
For Angular cli 6 + moment-timezone - this article worked well: https://medium.jonasbandi.net/angular-cli-and-moment-js-a-recipe-for-disaster-and-how-to-fix-it-163a79180173

**Comment by pnowy** [comment]
See that: https://github.com/jmblog/how-to-optimize-momentjs-with-webpack

**Comment by arcataroger** [comment]
For anyone still dealing with this issue in 2020, there is now a webpack plugin that lets you define which locales you need (defaults to "en" only) and removes the rest:
https://www.npmjs.com/package/moment-locales-webpack-plugin

It has a sister package to strip out unnecessary timezones from moment-timezone:
https://www.npmjs.com/package/moment-timezone-data-webpack-plugin

Between the two, we shaved off 800 kB of unnecessary size.

**Comment by brendon** [comment]
Just wondering if there is anything equivalent to [moment-locales-webpack-plugin](https://www.npmjs.com/package/moment-locales-webpack-plugin) in Vite land?

**Comment by phil294** [comment]
@brendon regarding **Vite**:

I'm not sure why, but this seems to simply not be necessary. Nothing is bundled in the output module, unless you explicitly import it. https://github.com/moment/moment/issues/5926

```js
import moment from 'moment'
import 'moment/dist/locale/fr'

console.log(moment('2012 juillet', 'YYYY MMM', 'fr').format())
```

**Comment by brendon** [comment]
Thanks @phil294, that's interesting. Perhaps the tree shaking is good enough to drop what's unused.

Looks like I must have subbed moment.js out for something else in the end as we no longer have this in our codebase but I hope it helps others. Looks like there were a few people hoping for something :)
