### ISSUE TITLE
setting with object notation sets erroneous date

### ISSUE THREAD

**Issue by mattbailey** [moment/moment#2518]
```
> var date = moment({year:1998,month:7,day:29})
undefined
> date.calendar()
'08/29/1998'
```

**Comment by mattbailey** [comment]
I realize now that this probably means month: in an object is 0 indexed; I don't think this is very obvious in the documentation.

**Comment by ichernev** [comment]
All of moment is js Date compatible in terms of months -- all methods work with 0 indexed months, except parsing and formatting (human readable).
