### ISSUE TITLE
Mode of week operations

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2523]
It's confusing to have so many similar separate functions depending on what kind of weeks you're using.
- `day`, `weekday`, and `isoWeekday`
- `week`, and `isoWeek`
- `weekYear` and `isoWeekYear`
- `weeksInYear` and `isoWeeksInYear`
- Potential new functions proposed in #2522 

IMHO, it would make more sense to have a "week mode" getter/setter, similar to how we have local and UTC mode.

**Comment by ichernev** [comment]
That is a good observation. We could add the mode and make the local methods follow it, and deprecate the iso methods.

**Comment by alexpineda** [comment]
Would an additional argument make this more transparent to the programmer?

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
