### ISSUE TITLE
Website refers to English (England) rather than English (United Kingdom)

### ISSUE THREAD

**Issue by meh-uk** [moment/moment#2526]
Your website refers to *English (England)* - what about Scotland, Wales and Northern Ireland? Can we use *English (United Kingdom)* please? See for example [this](http://gouk.about.com/od/Practical-UK-Visitor-Tips/ss/Things-To-Never-Do-In-The-United-Kingdom.htm#step5) for why this is an issue.

**Comment by meh-uk** [comment]
On a similar note *English* should probably be *English (United States)* and *Chinese* should probably be *Chinese (Simplified)*.

**Comment by ichernev** [comment]
Thank you! Fixed.

**Comment by meh-uk** [comment]
Thanks for sorting this so quickly!
