### ISSUE TITLE
moment.min is broken in 2.10.6 (works in 2.10.3)

### ISSUE THREAD

**Issue by chbrown** [moment/moment#2529]
var moment = require('moment');
    var oct = moment("20111031", "YYYYMMDD");
    var nov = moment("20111131", "YYYYMMDD");
    var longest_ago = moment.min([oct, nov])

I would expect `longest_ago === oct`, but it does not.

Works just fine in the last stable moment version!

**Comment by mj1856** [comment]
There are only 30 days in November, so `nov.isValid() === false`.

Previously, the behavior when an invalid moment was compared to a valid moment was undefined, and inconsistent.  See #2362.

This was fixed with #2438 in the last release, which explains your results.
