### ISSUE TITLE
use requirejs configuration to customize Moment

### ISSUE THREAD

**Issue by absolux** [moment/moment#2531]
hi,
is there a possibility to pass customization config to moment via requirejs config, like noGlobal option.
per example :
```javascript
requirejs.config({
    ...
    config:{
        'moment': {
            noGlobal: true,
            locale: {
                'en': {
                    calendar: { ... },
                    months: { ... }
                },
                'fr': { ... }
            }
        }
        ...
    }
    ...
});
```
Thank you.

**Comment by ichernev** [comment]
Um, `noGlobal` -- yes. Anything else is not supported at the moment. If you want to modify existing language check this proposed feature: https://github.com/moment/moment/issues/2551

**Comment by ichernev** [comment]
Why would you write your code in requirejs.config section anyway? Just put it in a file and load that.
