### ISSUE TITLE
Option to use "ceil" instead of "round" for duration humanization?

### ISSUE THREAD

**Issue by hanfeisun** [moment/moment#2532]
Currently the `humanize` method of duration works like this:

    moment.duration(25, "hours").humanize();
    > "a day"
    moment.duration(35, "hours").humanize();
    > "a day"
    moment.duration(36, "hours").humanize();
    > "2 days"

However, sometimes `ceil` may be needed instead of `round`, which means the humanized text will be "2 days" when the duration is larger than 24 hour and less than 48 hours..

Is it possible for moment to add an option to use "ceil" instead of "round" for duration humanization?

**Comment by ichernev** [comment]
You can just change the thresholds: http://momentjs.com/docs/#/customization/relative-time-threshold/
