### ISSUE TITLE
Only number without unit and suffix

### ISSUE THREAD

**Issue by tony0918** [moment/moment#2533]
Is it possible to get only number without any suffix or unit?
For instance, using `fromNow()` will get simple result `xxx days ago`.
But just need `xxx` without ~~`days ago`~~

**Comment by mj1856** [comment]
How would you know what that number represents?  `fromNow` doesn't always return days.  It might return minutes, hours, etc.

**Comment by mj1856** [comment]
If you know you want a specific unit, then use [`subtract`](http://momentjs.com/docs/#/manipulating/subtract/).
