### ISSUE TITLE
Minimized locale files are corrupted

### ISSUE THREAD

**Issue by diomed** [moment/moment#2537]
`//! author : Bojan Marković : https://github.com/bmarkovic
function s(a,b,c){var d=a+" ";switch(c){case"m":return b?"jedna minuta":"jedne minute";case"mm":return d+=1===a?"minuta":2===a||3===a||4===a?"minute":"minuta";case"h":return b?"jedan sat":"jednog sata";case"hh":return d+=1===a?"sat":2===a||3===a||4===a?"sata":"sati";case"dd":return d+=1===a?"dan":"dana";case"MM":return d+=1===a?"mjesec":2===a||3===a||4===a?"mjeseca":"mjeseci";case"yy":return d+=1===a?"godina":2===a||3===a||4===a?"godine":"godina"}}function t(a,b,c,d){var e=a;switch(c){case"s":return d||b?"néhány másodperc":"néhány másodperce";case"m":return"egy"+(d||b?" perc":" perce");case"mm":return e+(d||b?" perc":" perce");case"h":return"egy"+(d||b?" óra":" órája");case"hh":return e+(d||b?" óra":" órája");case"d":return"egy"+(d||b?" nap":" napja");case"dd":return e+(d||b?" nap":" napja");case"M":return"egy"+(d||b?" hónap":" hónapja");case"MM":return e+(d||b?" hónap":" hónapja");case"y":return"egy"+(d||b?" év":" éve");case"yy":return e+(d||b?" év":" éve")}return""}function u(a){return(a?"":"[múlt] ")+"["+Fa[this.day()]+"] LT[-kor]"}`

you better check this out, because after last croatian word : godina

everything else is hungarian apparently.

bosnian:

`//! based on (hr) translation by Bojan Marković
function k(a,b,c){var d=a+" ";switch(c){case"m":return b?"jedna minuta":"jedne minute";case"mm":return d+=1===a?"minuta":2===a||3===a||4===a?"minute":"minuta";case"h":return b?"jedan sat":"jednog sata";case"hh":return d+=1===a?"sat":2===a||3===a||4===a?"sata":"sati";case"dd":return d+=1===a?"dan":"dana";case"MM":return d+=1===a?"mjesec":2===a||3===a||4===a?"mjeseca":"mjeseci";case"yy":return d+=1===a?"godina":2===a||3===a||4===a?"godine":"godina"}}function l(a){return a>1&&5>a&&1!==~~(a/10)}function m(a,b,c,d){var e=a+" ";switch(c){case"s":return b||d?"pár sekund":"pár sekundami";case"m":return b?"minuta":d?"minutu":"minutou";case"mm":return b||d?e+(l(a)?"minuty":"minut"):e+"minutami";break;case"h":return b?"hodina":d?"hodinu":"hodinou";case"hh":return b||d?e+(l(a)?"hodiny":"hodin"):e+"hodinami";break;case"d":return b||d?"den":"dnem";case"dd":return b||d?e+(l(a)?"dny":"dní"):e+"dny";break;case"M":return b||d?"měsíc":"měsícem";case"MM":return b||d?e+(l(a)?"měsíce":"měsíců"):e+"měsíci";break;case"y":return b||d?"rok":"rokem";case"yy":return b||d?e+(l(a)?"roky":"let"):e+"lety"}}`

same goes here, minutou, minutami ... etc. that is not bosnian language, neither is anything after that.

**Comment by mj1856** [comment]
Hmmm...  Yes, this appears to be a build issue.  The locales.min.js file appears to have blended several languages together and omitted others.  @ichernev please look asap.  Thanks.

**Comment by ichernev** [comment]
I'll take look later today.

**Comment by ichernev** [comment]
@diomed first I assume you talk about `min/locales.min.js`. Functions are reordered, correct. If you search for `defineLocale("hr"` you'll find the croatian locale code.

Is there any particular issue and code that reproduces it?

**Comment by mj1856** [comment]
@ichernev - As an example, examine [the minified hr from from locales.min.js](https://github.com/moment/moment/blob/f3fbef9d9875bbff340b527dbe3f1c447a942f69/min/locales.min.js#L36).  Note it contains the string `"néhány másodperc"`, which is not found in [/locale/hr.js](https://github.com/moment/moment/blob/develop/locale/hr.js), but rather in [/local/hu.js](https://github.com/moment/moment/blob/develop/locale/hu.js)

**Comment by ichernev** [comment]
```javascript
$ node
> moment = require('./moment')
> require('./min/locales.min.js')
> moment.locale('hr')
> moment().format('LLLL')
'srijeda, 12. kolovoz 2015 12:44'
```

Try without requiring the minified version, and it will load it from locales, and print the same thing:

```javascript
$ node
> moment = require('./moment')
> moment.locale('hr')
> moment().format('LLLL')
'srijeda, 12. kolovoz 2015 12:44'
```

**Comment by mj1856** [comment]
Ok, I dug a bit deeper, and you're right - there is no problem.

The confusion comes from the fact that the minimized file still contains the comments for each language interlaced throughout the file. However, not all of the code following the comment belongs to that language.  The minification process is just putting as much as it can together without line breaks, but that doesn't necessarily give one language per line.

So for example, I mentioned `"néhány másodperc"` as looking like it was in the `hr` locale, because it landed on line 36 with the other code for `hr`.  But actually, the minified function got the name `t`, and I can see way down at the bottom of the file that the `t` function is only used within the `hu` language.

So there is no issue, but perhaps we could consider omitting comments from the minified locale files?

**Comment by ichernev** [comment]
@mj1856 yes, if you just search for defineLocale, you'll see that the code passed to the function has the right locale, but the code on the line after the comment is a defineLocal for another locale.

Yes, I agree its confusing, but  I don't think we can do much about how uglify works.

**Comment by mj1856** [comment]
We actually could, since [the `preserveComments` option](https://www.npmjs.com/package/grunt-contrib-uglify#preservecomments) can take a function.

Or we could just not use the `//!` syntax in the locale file headers.
