### ISSUE TITLE
potential moment.duration() bug

### ISSUE THREAD

**Issue by Jackyjjc** [moment/moment#2538]
```
> var moment = require('moment');

> moment.duration(120, 'minutes')
{ [Number: 7200000]
  _milliseconds: 7200000,
  _days: 0,
  _months: 0,
  _data:
   { milliseconds: 0,
     seconds: 0,
     minutes: 0,
     hours: 2,
     days: 0,
     months: 0,
     years: 0 },

> moment.duration('120', 'minutes')
{ [Number: 0]
  _milliseconds: 0,
  _days: 0,
  _months: 0,
  _data:
   { milliseconds: 0,
     seconds: 0,
     minutes: 0,
     hours: 0,
     days: 0,
     months: 0,
     years: 0 },
```

When I pass in the number 120, it construct a correct duration. However, when I pass in the string '120', it creates a duration with all the fields initialized to 0. Is that the desired behaviour?

**Comment by alburthoffman** [comment]
moment.duration requires these inputs:

moment.duration(Number, String);
moment.duration(Number);
moment.duration(Object);
moment.duration(String);

When it checks the first argument is string, then it will use the last one. Then it will require a ASP.NET style timespan format, something like "2:30:00".

The second argument will be ignored in this case.
You can confirm this by checking moment.duration("2:30:00", "minutes")

**Comment by Jackyjjc** [comment]
Thanks!
