### ISSUE TITLE
Inconsistent localisation formatting for Japanese

### ISSUE THREAD

**Issue by moneytree-doug** [moment/moment#2539]
There seems to be away to get the month with it's counter particle 月, but it's impossible to get the day and year counter particle.
```
moment().format('M-Y-D')
"8-Y-7"　
moment().format('MM-YY-DD')
"08-15-07" 
moment().format('MMM-YYY-DDD')
"8月-15Y-219" // Expected for DDD: 07日
moment().format('MMMM-YYYY-DDDD')
"8月-2015-219" // Expected for YYYY: 2015年
moment().format('MMMM-YYYYY-DDDD')
"8月-02015-219"
moment().format('MMMM-YYYY-DDDD')
"8月-2015-219"
```

Is there a way for me to add my own custom keys? For example, as a sibling of ```LLL```, I want like ``hello`` for example.

**Comment by ichernev** [comment]
You can not slightly modify a language. We'll probably implement language inheritance in the near future.

About the missing token -- `YYYY` is always numerical year. Moment has never had the option of changing those tokens in a language. If you do use the presets (`L`, `LL`...), then you'll get those.

**Comment by ichernev** [comment]
You can put your particle in the format strings. Currently we don't support custom tokens, and even if we do it won't be per language.
