### ISSUE TITLE
Client's timezone lost on toJSON

### ISSUE THREAD

**Issue by mdsharpe** [moment/moment#2540]
I'd like to ask whether there's any way moment could retain timezone information when serializing to JSON.

Assuming an application with international use, and a viewmodel containing a `moment` that is serialized before being POSTed to the server, the information of the user's local timezone is lost because of moment's `toJSON` behaviour.

My current workaround is to call `.format()` on moments before POST (since that retains the timezone), but it'd be more convenient if I could simply convert the entire viewmodel (including `moment`) to JSON.

Is it currently possible to affect this behaviour to retain timezone information, or could moment be made configurable to allow this behaviour to be changed across an entire application?

n.B. not keen on overriding moment's `toJSON` unless that is the suggested workaround.

**Comment by mj1856** [comment]
Yes, the suggested workaround is to override the `toJSON` function.

```javascript
moment.fn.toJSON = function() { return this.format(); }
```

Then you can stringify an object with a moment like so:

```javascript
var o = { m : moment() };
var json = JSON.stringify(o); //  '{"m":"2015-08-09T14:43:15-07:00"}'
```

**Comment by mj1856** [comment]
Also, I [answered a similar question](http://stackoverflow.com/a/31104671/634824) recently, wanting similar output from serializing a `Date` object.  The main difference is that you get at `toJSON` through `Date.prototype.toJSON` instead of `moment.fn.toJSON`.

**Comment by mj1856** [comment]
I've updated the docs to reflect this, in moment/momentjs.com@11cacb2

**Comment by mdsharpe** [comment]
That's brilliant, thank you for your help.

Matt





On Sun, Aug 9, 2015 at 2:54 PM -0700, "Matt Johnson" <notifications@github.com> wrote:












I've updated the docs to reflect this, in moment/momentjs.com@11cacb2
