### ISSUE TITLE
Precision of .fromNow() and related methods?

### ISSUE THREAD

**Issue by jasonmendes** [moment/moment#2542]
`moment().fromNow()` and related methods (`.from()`, `.toNow()`, `.to()`) as outlined in the documentation return an approximate value of the time since. How can an exact value be returned? 

E.g. 

```
> moment('2015-06-27T00:00:00.000Z').fromNow()
'a month ago'
```

But what I'd like is the exact amount of time since, and as an example, the spaghetti way I found to do this is:

```
> moment.duration(moment().diff(moment('2015-06-27T00:00:00.000Z')))._data
{ milliseconds: 44,
  seconds: 41,
  minutes: 6,
  hours: 23,
  days: 10,
  months: 1,
  years: 0 }
```

**Comment by mj1856** [comment]
That's how you do it.  You calculate the difference, and create a duration.

The only thing you're doing that you probably shouldn't is using the `_data` property.  In general, underscored properties are internal and are not guaranteed for future compatibility.  Instead, assign the duration to a variable and call each property separately.

```javascript
var d = moment.duration(moment().diff(moment('2015-06-27T00:00:00.000Z')));
d.hours() // 23
d.minutes() // 6
// etc.
```

Or, if you want total duration as a single unit, use the "as" versions of the functions:

```javascript
d.asHours()  // 1074.4133527777778
```

**Comment by mj1856** [comment]
Also, note you could shorten the code slightly, since you're using an ISO string.

```javascript
var d = moment.duration(moment().diff('2015-06-27T00:00:00.000Z'));
```
