### ISSUE TITLE
Warning with formatting today's date moment().format(...)

### ISSUE THREAD

**Issue by stevewillard** [moment/moment#2550]
Anyone know why the following gives me a deprecation warning?
```
moment().format("MM/DD/YYYY")
```

```
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
```

I read through the thread, but I don't really see how pass in "nothing" into the moment constructor gives me this error.

I'm just trying to get today's date in a certain format

**Comment by ichernev** [comment]
Which version / environment? It doesn't happen on `2.10.6` in node / browser.

**Comment by stevewillard** [comment]
Whoops -- Turns out that the example I gave is working as expected. My issue is that I'm putting this value into https://github.com/Eonasdan/bootstrap-datetimepicker/ as a "maxDate". So, the error is actually coming from this datetimepicker, and how it uses moment, not directly through my code.
