### ISSUE TITLE
Implement language inheritance

### ISSUE THREAD

**Issue by ichernev** [moment/moment#2551]
This has been requested over and over.

The idea is to enable creating a language by specifying the differences with another language. This will only be used by user code, not in the build-in locales (so that they remain independent).

To do this properly we need to:
* have a `not-specified` value, that would mean it wasn't specified in the current description
* wrap all locale token access with methods (in `Language` class) -- two implementations -- return value directly, or check for `not-specified` and fall back to parent language.

**Comment by mj1856** [comment]
Hmmm... might this actually be good for built-in locales as well?  For example, perhaps `en-us` and `en-gb` would inherit from a common `en` locale.  CLDR works like this, BTW.

**Comment by ichernev** [comment]
Built in locales should be as standalone as possible, you know what clients will try to do...

**Comment by mj1856** [comment]
This was completed in #2774
