### ISSUE TITLE
Parsing Issue with single digits days and months in strict mode

### ISSUE THREAD

**Issue by mkhanal** [moment/moment#2554]
When parsing in Strict mode to get all the benefits of it, one would expect

```javascript
moment('10-1-2015', ['DD-MM-YYYY'], true)
```

to be true. (notice the single digit month). the same goes for single digit date. Because they are valid dates and I believe the intention is universally accepted where one does not need to append a '0' before single digit numbers in date and month value.

To work around, right now I need to do

```javascript
moment('10-1-2015', ['DD-MM-YYYY','DD-M-YYYY','D-MM-YYYY','D-M-YYYY'], true)
```

**Comment by mj1856** [comment]
Actually, the exact opposite is true.  The single digit formatters will work with either one or two digits.  The double-digit formatters always work with two digits.  This is true for both parsing and formatting, and holds up in strict mode.

```javascript
moment('1-1-2015', 'D-M-YYYY', true).isValid() // true
moment('01-01-2015', 'D-M-YYYY', true).isValid() // true
moment('10-10-2015', 'D-M-YYYY', true).isValid() // true
```

**Comment by mkhanal** [comment]
:+1: 
thanks
