### ISSUE TITLE
LDML yyyy produces weird results with no warning

### ISSUE THREAD

**Issue by StevenACoffman** [moment/moment#2555]
I didn't realize that Moment didn't use LDML, and applied MM/dd/yyyy format. I didn't get an error message, just a weirdly wrong date (and one that was randomly correct). I know, my bad for not thoroughly reading the docs. However, it would be good if invalid moment date format strings, but commonly used, valid LDML formats would produce an error message of some sort, even if they proceeded to execute.

Alternatively, it would be nice if YYYY/yyyy were both supported, since I don't think this would break anyone's existing code and move closer to LDML. Since you use 'ddd' instead of 'eee', maybe supporting both DD/dd would be problematic?

I don't know if there's a LDML to moment translation layer like moment-tokens.js does for strftime. That might be nifty too.

**Comment by mj1856** [comment]
I don't think moment's formatters are aligned with anything in particular, but I'm not sure of the reasoning why.

While there's no conflict with `yyyy`, there are other conflicts.  We currently use `dd` to represent a two-letter day-of-week abbreviation.  (Su, Mo, Tu, We, Th, Fr, Sa)

I'd be fine with switching to LDML for moment 3.0, though it would be a significantly major breaking change.

In the meantime, a function could be written to translate between LDML and moment's formatters, but it would have to be explicitly called, as in `moment().format(ldml_to_moment('MM/dd/yyyy'))`.  I'd prefer this be an external 3rd-party plugin.
