### ISSUE TITLE
relativeTime Seconds

### ISSUE THREAD

**Issue by randdusing** [moment/moment#2558]
I'm using relativeTime and noticed the "s" equals "a few seconds" rather than "seconds" as shown in the documentation (http://momentjs.com/docs/#/customization/relative-time/). Is it possible to add a "seconds" and "second" value? I was hoping to use these as part as custom humanize implementation with multilingual support, and "a few seconds" isn't granular enough. Thanks!

**Comment by ichernev** [comment]
@randdusing you have to change all locales, and also make a global flag / thresholds to control when to use the `few seconds` and when to use `N seconds`. If you do this in a PR I'll merge it, I'm not doing it though :)

**Comment by ichernev** [comment]
@randdusing the "documentation" is about customizing it. The semantics is that we don't have a `N seconds` string, so we don't have code to support it. So I'm dropping the Documentation flag from here.

**Comment by randdusing** [comment]
Ahh ok, I misunderstood the documentation. I may be able to get to it one day ;)

**Comment by marwahaha** [comment]
As of Moment 2.18.0, we have a `ss` Relative Time Threshhold that controls when to use `N seconds` vs `a few seconds`.
http://momentjs.com/docs/#/customization/relative-time-threshold/

Is this granular enough for you? :) @randdusing

**Comment by randdusing** [comment]
@marwahaha Perfect, thanks!
