### ISSUE TITLE
isValid() => true & strange flags with use of "Post or ante meridiem"

### ISSUE THREAD

**Issue by CharlesNo** [moment/moment#2563]
Hello,

Here is just an example of the issue : 
(But I just figured out that the problem was more with the 'a' or 'A' formatting)
(I'm adaptating the issue exemple)

________________________________________________________
```javascript
moment('text here TUESDAY text there','DD-MM-YYYY HHa').isValid()
true
```
________________________________________________________
```javascript
moment('text here TUESDAY text there','DD-MM-YYYY HHa').parsingFlags()
unusedInput: Array[3]
0: "text"
1: "here TUESD"
2: "Y text there"
unusedTokens: Array[4]
0: "DD"
1: "MM"
2: "YYYY"
3: "HH"
```
________________________________________________________

So as far as I can understand, it says it's valid because the 'A' of 'TUESDAY' is matching with the meridiem 'a' (that doesnt appear in the unused tokens.

Don't know if it matters, but from what I wrote in the format, I expected at least that the hours are linked to the meridiem like 10am 12pm (maybe 12noon but it doesnt matter since it's understood as 12am so it's fine). But not sure if I' using the tool right.

Using the latest version of moment (moment.version = "2.10.6") in a Meteor environnment.

**Comment by mj1856** [comment]
Sorry, but Moment is not designed to scan a string of text for date/time keywords.  You would have to have already isolated the text you intended to parse as a date, and matched the format accordingly.
