### ISSUE TITLE
2.10.3: "Cannot read property 'preparse' of null" when parsing dates using Swedish locale

### ISSUE THREAD

**Issue by rzetterberg** [moment/moment#2566]
I was planning to use `moment` to parse dates from an API that uses Swedish locale.

The problem is that when I parse using language code 'sv' I get an internal error in `moment`.

Here's the simple functionality I have:

```javascript
var moment = require('moment');
var raw_input = "20 maj 2013 09:01";
var format    = "D MMMM YYYY HH:mm";
console.log(moment(raw_input, format, "en").isValid());
console.log(moment(raw_input, format, "sv").isValid());
```

I adapted the code from the official docs `moment('2012 juillet', 'YYYY MMM', 'fr');` 

The expected output of this should be:

```
false
true
```

But the output I'm getting is:

```
false
Uncaught TypeError: Cannot read property 'preparse' of null
```

I have traced the error to the function `prepareConfig` (see "Error here"):

```javascript
    function prepareConfig (config) {
        var input = config._i,
            format = config._f;

        config._locale = config._locale || locale_locales__getLocale(config._l);

        if (input === null || (format === undefined && input === '')) {
            return valid__createInvalid({nullInput: true});
        }

        if (typeof input === 'string') {
            config._i = input = config._locale.preparse(input); <--- Error here
        }
```

I have installed `moment-2.10.3` using npm.

Tested on Firefox and Chrome with same error on both.

Here's a screenshot of the config object printed to the log:

![Log print](http://i.imgur.com/joyXSaG.png)

**Comment by rzetterberg** [comment]
By explicitly adding the locale solved the problem for me.

Here's the updated test code:

```javascript
var moment = require('moment');
var sv = require('moment/locale/sv');
var raw_input = "20 maj 2013 09:01";
var format    = "D MMMM YYYY HH:mm";
console.log(moment(raw_input, format, "en").isValid());
console.log(moment(raw_input, format, "sv").isValid());
```

Sorry for the noise!

**Comment by 0x70b1a5** [comment]
That's pretty dumb, locale should be optional.
