### ISSUE TITLE
Russian locale: capitalized first cahracters in names

### ISSUE THREAD

**Issue by RomeroMsk** [moment/moment#2569]
Why month and weekday names are in lower case in `ru` locale, not with capitalized first character (like in other locales and anoter datepickers, Windows calendar etc)?
For example, `Январь`, `Понедельник` and `Пн` is more habitual for calendar than `январь`, `понедельник` and `пн`.
First of all, question is for @Viktorminator, author of locale file.
Can I make a PR to fix this?

**Comment by RomeroMsk** [comment]
Some screenshots of another datepickers:
![image](https://cloud.githubusercontent.com/assets/4639951/9378074/fef61184-4737-11e5-8d5a-8919c8442933.png)
![image](https://cloud.githubusercontent.com/assets/4639951/9378080/095e1edc-4738-11e5-95e3-0a00376053ab.png)
![image](https://cloud.githubusercontent.com/assets/4639951/9378090/1f406ee4-4738-11e5-82a3-103e7f0ed991.png)

**Comment by ichernev** [comment]
@RomeroMsk -- you can make a pull request and ask the original author inside to review it. Or you can give some proof (official Russian time formats ... whatever :)). Also you just gave examples of the shortest versions being capitalized in a header column. If in general weekdays are written in lower case you can just capitalize the results yourself.

English is capitalized, because in the USA everything is capitalized :)

I'm closing this for now (open a PR if you want to).

**Comment by RomeroMsk** [comment]
@ichernev, I already have a [PR](https://github.com/RomeroMsk/moment/commit/ca1223d8b1a12da9e7887166846f6248bc3c03ac).
I've found that as a proof: http://lh.2xlibre.net/locale/ru_RU/. I see that short month names are lower-cased in this document, so I can change it in my PR.
BTW, second screenshot is from Windows. Isn't it a good proof? :)

**Comment by despawnerer** [comment]
Can we review and revert this change? This breaks most date formatting. Month names and weekdays are **not** generally capitalized in Russian. Sure, if it's the beginning of the sentence or a calendar widget, they should be, but in most cases, i.e. formatting a date, they are not. This change makes dates show up as "12 Января", which is incorrect Russian, plain and simple. See, for example: http://russianlearn.com/grammar/category/capitalization or really any language guide.

**Comment by RomeroMsk** [comment]
@despawnerer, yes, you are right. Damn, I'm really sorry, guys, that's my fault. Was confused by using moment in datepicker lib for displaying months and weekdays labels.

Here is the good proof-link for date/time standarts in Russian lang: http://www.unicode.org/cldr/charts/28/verify/dates/ru.html

@ichernev, revert the PR, please.

**Comment by socketpair** [comment]
Please revert.  http://lh.2xlibre.net/locale/ru_RU/ is WRONG

**Comment by socketpair** [comment]
see http://new.gramota.ru/spravka/rules/139-prop

**Comment by socketpair** [comment]
I have crated PR that correctly reverts this issue.
