### ISSUE TITLE
Adding a success callback on loading of locales

### ISSUE THREAD

**Issue by louisameline** [moment/moment#2574]
Hello and thanks for your work.

Is there a way to be notified when locales have finished loading ? When the locale takes time to load, I end up having the dates displayed in the wrong language (English). Thank you.

**Comment by alburthoffman** [comment]
You can run setTimeout function to check if some locale variables and functions have been set. If yes, then you can trigger ur logic, otherwise recheck it after a while.

**Comment by louisameline** [comment]
Thanks, so there's no built-in solution. I suggest the function accepts an optional third parameter, a callback function. I'm not sure I have the time to make the PR, but would you accept it if I did (with tests) ?

**Comment by alburthoffman** [comment]
you mean something like:
    var mm = moment("", function() {......})
?

**Comment by louisameline** [comment]
I'm referring to something like `moment.locale(String, Object, callback);`, would that be ok ?

**Comment by alburthoffman** [comment]
why not use moment-with-locales.js? will load all available locales for you. then there will be no need for one callback function.

**Comment by louisameline** [comment]
Why should I load all languages when I only need one ?
IMHO, the moment.locale() function is just not reliable as it is, it has to be fixed with a callback parameter.

**Comment by ichernev** [comment]
@louisameline can you give more information about your stack (package managers, browser/node, etc etc). Its all different.

If you're loading locales asynchronously (the only way currently is via AMD), then it (AMD) gives you a "callback" when the thing is loaded. Everything else does either load all locales, or none (so you have to load locales one by one). So you can just serve the locale file (if you know in advance), or fetch it dynamically (with callback), so I don't really get your question/problem.

**Comment by louisameline** [comment]
Hi, I'm in the browser using require.js. I load the user data asynchronously so I don't know his language on startup time. Yes, I can load the language file as an AMD module, but not having to deal with paths myself would be slightly better, and `moment.locale()` does that, minus the callback. I don't understand why wrote that function if it's not for asynchronous purposes.

**Comment by alburthoffman** [comment]
So you want one solution, like this:
```javascript
moment.locale('fr', callback);
```

And dont need to provide any of these script paths manually or use requirejs:
```html
<script src="locale/fr.js"></script>
<script src="min/locales.js"></script>
```

This is truely one new feature. My silly question is whether we have to do this. What's the strong reason? 

I mean the file moment-with-locales.min.js is about 167KB. If you use gzip in webserver, then it would be much less. In most cases, you will only need to support few locales, so you can build your own locale min file. It should not be an overhead for loading even you want to load one locale dynamically. 

But still, I can think of the benefits. One is we can put all locale files together, and add new locale files or update them, and dont need to build the min file each time. The other one is we dont want to store the locale files, but use the offical ones or other cdn networks. then this is good.

So overall, I think this feature is quite cool. The following APIs will work fine:
```javascript
moment.locale(string, function);
moment.locale(string, function, string); // the third one is the path, you can provide something like "http://cdn.net/moment/locales/"
moment.locale(string, object, function);
moment.locale(string, object, function, string);
```

**Comment by maggiepint** [comment]
This is a very old issue at this point, but it was answered by the require team last week. They instructed us to advise you do do the following:

```js
define(function(require) {
  // Inside some module after the locale is detected. This is the 
  // case where the locale is not known before module load time.
  require(['moment/locale/de'], function(localeModule) {
    moment.locale('de');
    // Use moment now that the locale has been properly set.
  });
```

See requirejs/requirejs#1554

**Comment by louisameline** [comment]
Hi, that's an obvious option, didn't need their answer. My whole point is that either:
- introduce a callback option  
OR
- stop telling people to use `moment.locale('en')` altogether because it DOES NOT WORK AS EXPECTED as it's subject to a RACE CONDITION

No offense guys but you're driving me nuts here lol.

**Comment by louisameline** [comment]
If you don't want to add a callback option, which I would understand, keep it simple: stop loading the locale file in `moment.locale()` and just tell us to load the file ourselves beforehand. It would be a breaking change but at least it will be clear that we're in charge of doing it right, because you're doing it wrong. This issue is not closed but I did my best to explain it, now it's up to you to decide to keep this buggy behavior or not. Thank you anyway.
