### ISSUE TITLE
Different DST offsets between windows and linux

### ISSUE THREAD

**Issue by sLite** [moment/moment#2575]
We are running into issues where moment returns different DST offsets for dates in the past whether it runs on linux or windows.

The following fiddle http://jsfiddle.net/Nq3KD/49/ prints the following

Linux:

    (index):29 Tue Jan 01 1980 00:00:00 GMT+0100
    (index):31 Wed Oct 01 1980 00:00:00 GMT+0100
    (index):33 Fri Oct 24 1980 00:00:00 GMT+0100
    (index):35 Sun Jul 24 1977 00:00:00 GMT+0100

Windows:

    (index):29 Tue Jan 01 1980 00:00:00 GMT+0100
    (index):31 Wed Oct 01 1980 00:00:00 GMT+0200
    (index):33 Fri Oct 24 1980 00:00:00 GMT+0200
    (index):35 Sun Jul 24 1977 00:00:00 GMT+0200

**Comment by alburthoffman** [comment]
what about ur browsers? all in chrome? or firefox?

**Comment by sLite** [comment]
Oh sorry, above results apply for firefox and chrome.
IE11 also produces the wrong results, obviously can't compare that to linux ;)

This really seems like a OS dependent issue.

**Comment by mj1856** [comment]
There are several issues at play here.  First, consider #831 and the details I wrote up in [this blog post](http://codeofmatt.com/2013/06/07/javascript-date-type-is-horribly-broken/).  This still applies to most browsers out there.

Then consider that Windows itself does not have very good historical time zone data.  Most Windows time zones only go back a few years, or early 2000's at the best.  You can check the time zone data in the registry at `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones`.  Each zone is different, and even some of the data it does claim to have is not accurate.  In general, Microsoft doesn't fix historical time zone mistakes to the same degree that the TZDB does.

If accurate time zone history is important to your JavaScript app (such as an astrology program), then you shouldn't rely on the OS to provide time zones.  When you just use moment.js plain, that's what you're doing.  Instead, use the [moment-timezone](http://momentjs.com/timezone/) plugin, which provides it's own data from the TZDB sources.
