### ISSUE TITLE
Firefox(37.0.2) moment is not a function

### ISSUE THREAD

**Issue by yordis** [moment/moment#2576]
I have no idea what's going on, Chrome have function and Firefox is wrapping the moment into an object.  I wish I can tell you more but I have no idea how I should debug this

Firefox
![screen shot 2015-08-24 at 4 50 50 pm](https://cloud.githubusercontent.com/assets/4237280/9452093/666da5b6-4a80-11e5-9679-691ad90db116.png)

Chrome
![screen shot 2015-08-24 at 4 51 15 pm](https://cloud.githubusercontent.com/assets/4237280/9452092/666af730-4a80-11e5-9235-debe23c6e7d0.png)

**Comment by yordis** [comment]
This is happening because I am using SystemJS bundled file.

**Comment by ichernev** [comment]
Is your code expecting ES6 module for moment or ES5. If you expect ES6, then this was already discussed in https://github.com/moment/moment/issues/2608

Now that I think about it, is JSPM only for ES6, if its not we can't just break moment for jspm/es5 users.

**Comment by ichernev** [comment]
Close in favor of #2577
