### ISSUE TITLE
Unexpected reserved word in Moment.js 2.10.6

### ISSUE THREAD

**Issue by liamlundy** [moment/moment#2578]
I found this issue in an angularjs project. My project fails all tests because of an "Unexpected reserved word."

Karma output:

    Chrome 44.0.2403 (Linux 0.0.0) ERROR
      Uncaught SyntaxError: Unexpected reserved word
      at /mnt/DATA/Documents/Web_Development/Projects/buzzweb/vendor/moment/src/moment.js:7

This issue on stackoverflow also describes the same error http://stackoverflow.com/questions/29977553/uncaught-syntax-error-with-moment-js

I'm not a javascript expert, but it appears to be an issue with the switch to ES6

**Comment by alburthoffman** [comment]
You only use moment as a third party library, right?
you can try the min version in min/moment.min.js

**Comment by mj1856** [comment]
@liamlundy - How are you loading moment?  You should not get this error unless you are using the ES6 sources directly.  The releases contain the ES5 transpiled output.

**Comment by liamlundy** [comment]
I'm using it in an angularjs app with angular ui calendar. i use bower to get moment and then load the unminified js file in a script tag.

**Comment by liamlundy** [comment]
Using the minified version is working for me right now. i'd prefer to use the unminified version and minify it when i need to so that i can debug my app. it also seemed like a strange issue that could be reproed. i can close it if there isn't a resolution and it isn't being experienced by other users. it also might be an issue with my setup and/or angular.

**Comment by ichernev** [comment]
@liamlundy show us the place where you "pick" the moment file (minified or not). You should either use `min/moment.min.js` or `moment.js`, NOT `src/moment.js`.

**Comment by nani282828** [comment]
yes, your are correct by using min/moment.min.js problem is solved
