### ISSUE TITLE
Wrong IsValid

### ISSUE THREAD

**Issue by MojoDK** [moment/moment#2582]
Hi

How can the myDate...

var myDate = moment("1s", "DD-MM-YYYY");

... be valid?

**Comment by mj1856** [comment]
Because moment's default parsing mode is very forgiving.  It ignores the "s", and applies the "1" to the first field encountered - the *day* in this case.  The other components are defaulted.

To avoid this, use "strict parsing" by passing `true` as the third argument.

```javascript
moment("1s", "DD-MM-YYYY", true).isValid()  // false
```
