### ISSUE TITLE
moment.locale('zh-cn') dose not work in Meteor ?

### ISSUE THREAD

**Issue by hojas** [moment/moment#2584]
moment.locale('zh-cn') dose not work in Meteor ?

**Comment by mj1856** [comment]
Do you have any supporting details?  Perhaps you just don't have the locale loaded?

**Comment by hojas** [comment]
How to load the locale ?

**Comment by mj1856** [comment]
I'm not sure about Meteor, as I don't use it.  But loading locales is covered for other environments in the docs.

Ultimately, either one or more of the individual local files [from here](https://github.com/moment/moment/tree/master/locale) need to be loaded, or one uses the moment+locales files from the momentjs.com main site.

**Comment by monbro** [comment]
Same issue here for 'de' language. The meteor community provides a easier package so far where the language files are included: https://atmospherejs.com/jeeeyul/moment-with-langs (which I tested just now and it works).

I suggest you try to included these into your meteor port, as you need to include the language files there to have all the functions to work out of the box.

**Comment by monbro** [comment]
I guess @ichernev should have a look at this here.

**Comment by digitalfrost** [comment]
**+1** on *include these into your meteor port to have all the functions to work out of the box*.

**Comment by ichernev** [comment]
@monbro I don't understand meteor very well, but can you export two different bundles from the same project? So people who need locales can get them, the ones who need the core can get only the core.

Or we can just publish two separate meteor packages by changing package.js and then re-pushing?

Are you interested on working on a PR for that.

**Comment by monbro** [comment]
In generalI think it would be more handy to use a single meteor package only. It is possible to export two different global variables (or bundles) within one meteor package. But the naming would be different e.g. 'moment' and 'moment-locals' which is not ideal I guess.

I will try to do a pull request anytime soon.

**Comment by EvilJohnny** [comment]
Would it be too crazy to release one meteor package per locale? Like 'moment-locale-[locale]'?
That way users can add only the languages they need, avoiding to load unused data...

**Comment by alexschomb** [comment]
This has been done already by https://github.com/rzymek/meteor-moment, but is outdated and only works if you remove `momentjs:moment` from your project. Maybe you can adopt/fork his locale implementation?

**Comment by tsega** [comment]
@alexschomb, I don't know what you mean about outdated since the [rzymek:meteor-moment](https://github.com/rzymek/meteor-moment) package seems to be working just fine with the current Meteor version. Besides it depends the official `momentjs:moment` package internally as well. So for those who require locale it's a good package to use.

**Comment by alexschomb** [comment]
In a way it is outdated. It does use the official package, but for a defined release (v2.9.0):

```
Package.onUse(function(api) {
    api.use('momentjs:moment@2.9.0'); 
    api.addFiles('server.js','server');
    api.addFiles('client.js','client');
    api.addFiles('locale.js');
    api.imply('momentjs:moment');
});
```

You could always build your own package, but why not provide an official package? This makes things easier for all of us.

**Comment by mj1856** [comment]
Looks like perhaps this package will work?  Just guessing here, I know nothing about Meteor.

https://atmospherejs.com/rzymek/moment-locales

**Comment by Sornii** [comment]
Install the moment package using npm `npm install moment`, inside the `Meteor.startup` method you use `moment.locale('pt-BR')` to set the language. All this is done by importing the correct files. In the same file you call these methods you need to import `import moment from 'moment'` and `import 'moment/locale/pt-br'`.

**Comment by marwahaha** [comment]
@hojas and others - is there a good solution now?

**Comment by marwahaha** [comment]
Closing due to age. If you still have questions please re-open.
