### ISSUE TITLE
To support the Taiwan year format

### ISSUE THREAD

**Issue by bradwoo8621** [moment/moment#2586]
Dear reader,

In Taiwan,, the year format is 4 digits year minus 1911. eg. 2015, displayed as 104.

and maybe like this,  
```javascript
    addFormatToken(0, ['YYY', 3], 0, function () {
        return this.year() - 1911;
    });
    addRegexToken('YYY', match1to3, match3);
    addParseToken('YYY', function (input, array) {
        array[YEAR] = hooks.parseThreeDigitYear(input);
    });
    hooks.parseThreeDigitYear = function (input) {
        return toInt(input) + 1911;
    };
```

 but these methods are not published. so is there any other way to add a new date format?

thank you very much

**Comment by mj1856** [comment]
Moment doesn't directly support non-Gregorian calendar systems.  There are some plugins, such as:

https://github.com/behrang/moment-jalaali
https://github.com/xsoh/moment-hijri

Perhaps something similar could be created for the Taiwanese calendar.

**Comment by bradwoo8621** [comment]
thanks for your reply.

I've learned these two plugins. seems it's the only way to extend the formatting support.

thanks again.

**Comment by bradwoo8621** [comment]
Hi, I've submit the Taiwan format in https://github.com/bradwoo8621/moment-taiwan.

thanks. :)

**Comment by mj1856** [comment]
Thanks @bradwoo8621 !
