### ISSUE TITLE
Wrong parsing when month is overflown and there is MMM in one of the formats

### ISSUE THREAD

**Issue by igoryan-k** [moment/moment#2592]
HI. 
Getting really strange parse result, when passing formats and there is a month overflow in input string and one of the formats is with MMM.
Example (http://jsfiddle.net/igoryan/yyx0j6os/4/):
moment('01/15/80 3:34', ['DD/MM/YY h:mm']) works correctly
but
moment('01/15/80 3:34', ['DD/MM/YY h:mm', 'DD-MMM-YY hh:mm']) will result in "Thu Jan 01 2015 03:34:00 GMT-0600"  instead of invalid value. 

Looks like in first case the isValid() is 'false', because _pf.overflow = 1, and then second format is accepted, even though 'MMM' and '/80' are not matched.

**Comment by mj1856** [comment]
Use strict mode for this (pass `true` as a third parameter).

```javascript
moment('01/15/80 3:34', ['DD/MM/YY h:mm', 'DD-MMM-YY hh:mm'], true)
```

**Comment by igoryan-k** [comment]
Thanks.
Not really an option for me to use "strict" mode though, i would have to pass like 200 formats. 
"Non strict" works just fine in all other cases and forgives using different separators, for instance. 
Should it not be checking the input for 3 characters and not use MMM masks if there are none?

**Comment by mj1856** [comment]
On second thought, I'm going to re-open this - as I can see how the promise of being able to scan for more than one possible format is broken here.

Your workaround sounds reasonable, though consider the string detected by `MMM` may not always be three digits long in all locales.

**Comment by ichernev** [comment]
@igoryan-k works correctly? What about the month being 15, which is greater than 12. Moment doesn't  support overflows (results in invalid moments), like Date does. Maybe adding a flag to allow them makes sense, but for now they are not.

Use a base time and then `m.add(14, 'months')` instead of this.

**Comment by igoryan-k** [comment]
@ichernev my intention was not to make it to parse a wrong value (like month being 15), but return an invalid value instead. This situation is what we getting when users typing in a wrong month in US culture, for instance. It chooses 'MMM' formats and parses it as some 'valid' value. I still don't see how is this a right behavior.

**Comment by ichernev** [comment]
Put a date picker. People can't read instructions or use the keyboard. Also you can check the parsing flags and ignore the result of you don't like it. In your case there will be unused tokens/input.
