### ISSUE TITLE
Wrong parsing of time when using format with H or h and no separators

### ISSUE THREAD

**Issue by igoryan-k** [moment/moment#2593]
Hi,
Found an issue when parsing with formats like 'hmm' or 'Hmm'.

E.g. moment('334', ['hmm']); results in invalid value, because despite of the passed format, it considers h=33, mm =4.

Example: http://jsfiddle.net/igoryan/koqe5m5f/

**Comment by BtM909** [comment]
It only works if you pass in moment('0344', 'hmm'). Seems like h (or H) always is looking for 2 characters.

**Comment by igoryan-k** [comment]
Yep, I expect formats to match user input correctly. H or h should look for 1 chars also.

**Comment by creage** [comment]
I double that.

```javascript
moment("20160831", "YYYYMMDD")
```

results into

```
Sun Apr 20 831 00:00:00 GMT+0300 (FLE Daylight Time)
```

**Comment by mj1856** [comment]
Closing in favor of #2418.

@creage - Yours is not the same issue, nor can I reproduce it.  If you can repro it consistently, please open a different issue and include details like time zone and browser.  Thanks.
