### ISSUE TITLE
moment.Duration humanize

### ISSUE THREAD

**Issue by MrBubbleSquare** [moment/moment#2595]
I try to display some durations but there is something wrong.
Start date is 01.01.2015
Stop date is 05.02.2015
I Iterate over and created everytime durations. But then on 25 happen this....
```
Duration { _milliseconds=0,  _days=25,  _months=0,  more...} => 25 days
Duration { _milliseconds=0,  _days=26,  _months=0,  more...} => one month
```
25 Days are not a month. That are 25 days ?
Here is my [Fiddle](http://jsfiddle.net/mah23cvf/6/)

**Comment by BtM909** [comment]
Isn't this simply something that's configured like this by default: http://momentjs.com/docs/#/customization/relative-time-threshold/

You can actually set these as general options, to the timeframes that will suit you better.

HTH

**Comment by mj1856** [comment]
Yes, @BtM909 is correct.  Please refer to those docs.  Thanks.
