### ISSUE TITLE
Trivial(?) miscalculations with diff method and months as unit

### ISSUE THREAD

**Issue by friday** [moment/moment#2598]
`diff()` is sometimes off by a very small margin of error using the `months`unit (and hence also year).

(all example below are using floating point number, as floored results would "fix" the error in most cases)

Diffing `2016-02-29T00:00:00.000Z` with `2016-02-28T23:59:59.999Z` should yield the same result as `1 / 1000 / 60 / 60 / 24 / 29` (1 ms in a leap month) which is `3.991060025542784e-10`, but instead I'm getting `3.7335722819593786e-10`

That's the result of a month with 31 days, not 29. Funny enough, if I reverse the order I get the correct result: `-3.991060025542784e-10`

The same thing happens with `2015-03-29T06:00:00.000Z` and `2015-03-28T06:00:00.000Z`. Given the longer time span the error is larger, but still trivial. The expected result should yield the same result as `1/31` (1 day in a month with 31 day), which is `0.03225806451612903`, but I'm getting `0.034482758620689655` (`1/29`).

Again, reversing the order yields the correct result.

In this [codepen](http://codepen.io/fullkornslimpa/pen/BoyJpP) I have compared the results with a custom method (UTC only).

**Comment by mj1856** [comment]
Some notes in "Month and year diffs" : http://momentjs.com/docs/#/displaying/difference/

See also discussion in #571

**Comment by mj1856** [comment]
And #2133  (not sure if docs were updated to reflect that or not)

**Comment by friday** [comment]
I think part of the difference could be leap day compensation. `moment.utc("2015-02-29").diff("2015-02-28", "years", true)` seems to produce "1" (which I still think is a bug since it's not documented).

This still doesn't explain why `2016-02-29T00:00:00.000Z` vs `2016-02-25T22:59:59.999Z` is `3.0416666782407407` days, but years are not `3.0416666782407407 / 29` and several other differences.

**Comment by ichernev** [comment]
These things are not well defined, and we've made sure with a lot of iterations, bug reports, etc to make it as close to human reasoning as possible (not to math). So its beyond me why you'd diff 2 dates 1ms apart in months, and expect it to make sense. Just do the math yourself, if you know what you're doing, but so far I see no good reason to change the existing code.

We've already made decisions to make things like 5th Jan to 5th Feb to be always one month, and 5th Jan to 4th Feb to be less than a month, no matter what. So this has some implications to the mathematical correctness. Basically the output is for direct human consumption, `3.7335722819593786e-10` is not.

**Comment by friday** [comment]
I wrote the reference function for the upcoming `date_diff()` in ArangoDB, and then used moment to test if my output was right. I expecting the differences to be my bugs, but when I hand-calculated it turned out to be moments. They may not be significant, but they're there.

@ichernev 
> We've already made decisions to make things like 5th Jan to 5th Feb to be always one month, and 5th Jan to 4th Feb to be less than a month, no matter what. So this has some implications to the mathematical correctness.

I know. I'm doing the same thing. I even rewrote my function in the codepen to be more similar to moment.diff before submitting this issue, so you could more easily duplicate my tests and fix your miscalculation.

> So its beyond me why you'd diff 2 dates 1ms apart in months, and expect it to make sense.

This is a strange way of reasoning to me. This was just the diff I got to after narrowing down the error, and I posted that one because I thought it would be more helpful for you to locate the error. It obviously adds up with a longer span (but won't effect the floored value). The link contains more examples, and I posted one in a comment. Here's another example of how it adds up:

```js
var expectedResult = 15/30; // span of 15 days in a month of 30 days
var momentResult = moment("2015-04-16T00:00:00.000Z").diff("2015-04-01T00:00:00.000Z", "months", true);
console.log("Difference in `months` between april 1 and april 16");
console.log("Expected result:", expectedResult);
console.log("Result using moment.js:", momentResult);
console.log("Expected rounded result:", Math.round(expectedResult));
console.log("Rounded moment.js result:", Math.round(momentResult));
```

Result:

> Difference in `months` between april 1 and april 16
Expected result: 0.5
Result using moment.js: 0.4845222072678331
Expected rounded result: 1
Rounded result using moment.js: 0

Seems I'm not the only one rounding instead of flooring the diff either:

> "ichernev closed this 4 days ago"

(Actually Sept 21 6:22 AM GMT+2, hence less than 4 days ago)
