### ISSUE TITLE
Can i subtract moment from moment 

### ISSUE THREAD

**Issue by a-x-** [moment/moment#2599]
i have, for example: `moment('2000-12-01')` and `moment('2015-09-01')`
i want calc difference in months

thank you!

**Comment by Strajk** [comment]
@a-x- There is a lot of questions & answers on this topic on SO http://stackoverflow.com/search?q=%5Bmomentjs%5D+diff

**Comment by mj1856** [comment]
```javascript
var a = moment('2000-12-01');
var b = moment('2015-09-01');
b.diff(a, 'months') // 177
```
