### ISSUE TITLE
Incorrect time difference display when using "hh:mm:ss" instead of "mm:ss"

### ISSUE THREAD

**Issue by silentwarrior** [moment/moment#2605]
Hello, I have encountered this, i am not sure if its intended behavior, I assume its not because it does not make much sense.

```
moment(airplanes[5].arrival_time - airplanes[5].departure_time).format("mm:ss")
"01:10"
```
```
moment(airplanes[5].arrival_time - airplanes[5].departure_time).format("hh:mm:ss")
"12:01:10"
```

**Comment by ichernev** [comment]
First of all, this looks like a duration, not a timestamp. Second, moment doesn't support formatted duration prints. You can use .to / from:

```javascript
moment(airplanes[5].arrival_time).from(airplanes[5].departure_time)
```

Try this plugin: https://github.com/jsmreese/moment-duration-format
