### ISSUE TITLE
correctly parses 24hr input with ante/post merdiem format, except for midday

### ISSUE THREAD

**Issue by justinTNT** [moment/moment#2606]
I'm guessing the 'solution' to this might be to note it in the docs.

```
> moment('1:00', 'HH mm a').format('hh:mm a')
'01:00 am'

> moment('13:00', 'HH mm a').format('hh:mm a')
'01:00 pm'

> moment('0:00', 'HH mm a').format('hh:mm a')
'12:00 am'

> moment('12:00', 'HH mm a').format('hh:mm a')
'12:00 am'
```

**Comment by ichernev** [comment]
@justinTNT what do you expect?

1. Why you parse with `a` and don't pass AM/PM:
```javascript
// either
moment('1:00 am', 'hh:mm a')
// or
moment('1:00', 'HH:mm')
```
Note that `HH` means 0-23 hour, and `hh` means 1-12 hour, to be used with `a`.

Also try strict parsing: `moment('1:00 am', 'hh:mm a', true)`, if the above doesn't help.
