### ISSUE TITLE
Simple Parsing in March 2015 results in wrong results

### ISSUE THREAD

**Issue by schamese** [moment/moment#2609]
See https://jsfiddle.net/pep85n1d/

    moment('2015-03-27 08:00').format()
    moment('2015-03-28 08:00').format()
    moment('2015-03-29 08:00').format()
    moment('2015-03-30 08:00').format()

results in

    2015-03-27T08:00:00+01:00
    2015-03-28T08:00:00+01:00
    2015-03-29T08:00:00+02:00 // here
    2015-03-30T08:00:00+02:00 // here

but should be

    2015-03-27T08:00:00+01:00
    2015-03-28T08:00:00+01:00
    2015-03-29T08:00:00+01:00 // here
    2015-03-30T08:00:00+01:00 // here

![screen](https://cloud.githubusercontent.com/assets/14015079/9861349/ff66ef22-5b31-11e5-8bd5-96a8ac10d68d.png)

Am I missing something important? Or is this a bug?

**Comment by mattgrande** [comment]
Based on your time zone, I'm guessing you're in the UK? According to [this site](https://www.gov.uk/when-do-the-clocks-change), the time changed on March 29, 2015 in the UK.

**Comment by ichernev** [comment]
@schamese you're missing the concept of timezone changes / daylight saving time: https://en.wikipedia.org/wiki/Daylight_saving_time
