### ISSUE TITLE
isValid doesn't respect format 

### ISSUE THREAD

**Issue by bobiblazeski** [moment/moment#2610]
Why does isValid returns true when I explicitly give string format ?
 (moment('2011/11/10',"DD/MM/YYYY")).isValid() //=>  true

**Comment by ichernev** [comment]
Try strict parsing:
```javascript
moment('2011/11/10',"DD/MM/YYYY", true).isValid() // false
```

What happened was it parsed `20/11/10` as `DD/MM/YYYY` and it said that `11` (from `2011`) is extra, and non-strict parsing is ok with that.
