### ISSUE TITLE
Incorrect date returned when "\" is used in date format

### ISSUE THREAD

**Issue by foflade** [moment/moment#2611]
Hi,

I'd like to parse a date string where date parts are delimited by "\", so I tried the following.

moment("10\10\2015", "DD\MM\YYYY").isValid() returned true

moment("10\10\2015", "DD\MM\YYYY").toDate() returned Sun May 10 2015 00:00:00 GMT+0100 (GMT Daylight Time) when I expected Sat Oct 10 2015 00:00:00 GMT+0100 (GMT Daylight Time)

Is this a bug or is there a special convention for using "\" delimiter?

Thanks,
Funmi

**Comment by mj1856** [comment]
The backslash (`\`) is a special character in JavaScript.  if you intent to represent a backslash character in a hard-coded string, you need to escape it with another backslash

```javascript
moment("10\\10\\2015", "DD\\MM\\YYYY")
```

If you're just taking a string from somewhere else, then you don't need to replace within that string.  Just within hard-coded strings.

```javascript
moment(value, "DD\\MM\\YYYY")
```

**Comment by drfunfan** [comment]
Thanks for the clarification. Yes, indeed the "\" is a special character in JavaScript. But from the following you can see that the returned date is incorrect.

moment("10\\10\\2015", "DD\\MM\\YYYY").toDate()
returned
Thu Sep 10 2015 00:00:00 GMT+0100 (GMT Daylight Time)

I expected Oct 10 2015. Is this a bug or am I missing something with the use of "\" from your example?

Thanks.

**Comment by mj1856** [comment]
Test those strings separately and you will find:

```javascript
"10\10\2015" === "105"
"DD\MM\YYYY" === "DDMMYYYY"
```

Therefore, you're actually doing:

```javascript
moment("105", "DDMMYYYY").toDate()
```

Since there are no delimiters, this gets interpreted left-to-right.  `DD` as 10, `MM` as 5 (May), and `YYYY` is absent, so it defaults to the current year.

**Comment by mj1856** [comment]
Also, it's rare to actually see a backslash in a date. Usually, it's a forward slash `/`, or a hyphen `-`, or sometimes a period `.`, but I don't know of any real-world case of backslashes as date part separators.

**Comment by mj1856** [comment]
Actually, it's slightly different than what I wrote above.  I was looking in Chrome.  Firefox shows it better.

![image](https://cloud.githubusercontent.com/assets/1396388/9978691/573a215c-5ef6-11e5-957e-a1666a145525.png)

So what's actually happening is that `"\10"` and `\"201"` are being interpreted as special characters. Read "Octal escape sequences" in [this article](https://mathiasbynens.be/notes/javascript-escapes).  The characters are Octal 010 and 201, which are Hexadecimal 0x08 and 0x81, or decimal 8 and 129.  These are unprintable characters.

You can check this also using the `charCodeAt` function.

```javascript
var s = "10\10\2015";
for (var i = 0; i < s.length; i++) { console.log(s.charCodeAt(i) + " == '" + s.charAt(i) + "'"); }
```

Output:
```
49 == '1'
48 == '0'
8 == ''
129 == ''
53 == '5'
```

The unprintable chars are ignored by moment, so it's the same result.
