### ISSUE TITLE
Getting Invalid Day in Date when using moment.js in Mozilla Firefox

### ISSUE THREAD

**Issue by frooodo** [moment/moment#2612]
Hello! Found a issue when trying to use the .add(x, days) in Mozilla Firefox, it's really weird.

I Described the entire process in StackOverflow, take a look: 
http://stackoverflow.com/questions/32573951/getting-invalid-day-in-date-when-using-moment-js-in-mozilla-firefox

When using a current time instance (var variable = moment()) it seems to work, but when using a ISO8601 coded date, it presents '2015-10-17' twice!

Any help apreciated :)

**Comment by mj1856** [comment]
[Answered on StackOverflow](http://stackoverflow.com/a/32641251/634824)
