### ISSUE TITLE
Moment should provide consistent DST behavior

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2618]
_(updated)_

When a moment is created or manipulated to a value that is either invalid or ambiguous due to daylight saving time, the results should be consistent across implementations.  Currently, we rely strictly on the `Date` object, which may not always provide the same behavior.

Specifically, when a local time is invalid, we should advance by the DST bias (2:30 becomes 3:30).  When a local time is ambiguous, we should pick the _first_ occurrence _1:30 is 1:30 *daylight_ time, not standard time).

---

_(originally reported)_

The issue described in #2612 is explainable, but what I find strange is that the behavior isn't the same in other time zones.

For Brazil, Firefox always goes backwards instead of forwards like Chrome.

But for other time zones, moment always goes forwards - even in Firefox.

Example in Firefox in Brazil:

``` javascript
moment("2015-10-17").add(1, 'days').format()
"2015-10-17T23:00:00-03:00"
moment("2015-10-18").add(1, 'days').format()
"2015-10-18T23:00:00-02:00"
```

Example in Firefox in Pacific Time:

``` javascript
moment("2015-03-08 02:00").add(1, 'days').format()
"2015-03-09T03:00:00-07:00"
moment("2015-03-07 02:00").add(1, 'days').format()
"2015-03-08T03:00:00-07:00"
```

Given Brazil's behavior, I would expect Pacific time to also roll back to 1:00, but it jumps forward to 3:00.

It's good if moment makes it consistent for Pacific. But then it's not clear why Brazil is still inconsistent if we're trying to compensate.

**Comment by vilterpanitz** [comment]
I'm with a very similar problem, but it occurs when I format my date.

```javascript
moment('2015-10-18').format('YYYY-MM-DDTHH:mm:ss-0300')
```
It's happening on Firefox 41.0.1. In Chrome it´s working fine.

**Comment by mj1856** [comment]
@vilterpanitz - That's not the same issue.  You just have an offset hardcoded in your format string.  You should use `ZZ` instead, as in `'YYYY-MM-DDTHH:mm:ssZZ'`

**Comment by vilterpanitz** [comment]
Hello @mj1856, tnks for reply!. I've tried as you suggested but it doesn't work too.

```javascript
moment('2015-10-18').format('YYYY-MM-DDTHH:mm:ssZZ')
```

I'm usign **moment-with-locales.js** at **2.10.6**.

My DST is GMT-3:00 (Brazil)
Here is the [link](http://codepen.io/vilterpanitz/pen/RWVvBE) to my CodePen

**Comment by mj1856** [comment]
Yes, now that the offset isn't hardcoded, you get the same issue I described earlier.

```javascript
moment('2015-10-18').format('YYYY-MM-DDTHH:mm:ssZZ')
// Chrome: "2015-10-18T01:00:00-0200"
// FireFox: "2015-10-17T23:00:00-0300"
```

This is a browser inconsistency that is *supposed* to be compensated for by moment.js, but it isn't in this particular case.  It compensates correctly in other time zones, so I think it has to do with the transition time at midnight screwing with the date.

**Comment by icambron** [comment]
@mj1856 are you sure it's not that Firefox just behaves differently for Brazil? It's news to me that Moment compensates for browsers doing inconsistent things on DST boundaries.

**Comment by mj1856** [comment]
It's possible.  I know FF has been bad in the time zone department.

I haven't had time to investigate further, but moment *should* compensate for this if it doesn't.  I thought it did.

**Comment by icambron** [comment]
@mj1856 I'll be surprised. Here's a sketch of how it could work, FWIW:

```js
momentToUse = function() {
  if (this.isDSTShifted()){
    var offset =  this.clone().subtract(3, 'hours').zone(); //assuming we want the "before" time
    return this.clone().utc().zone(offset);
 }
 else return this;
};

format = function(whateverFormatsArgsAre, justUse) {
  if (!justUse) {
    momentToFormat = momentToUse();
    return format(whateverFormatsArgsAre, true);
 }
 //rest of format code
}
```   
That's not terrible, but it's also not great to have to check if we're in a shift all the time.

**Comment by mj1856** [comment]
It should be handled when creating or manipulating a moment object, not during formatting.

Also `isDSTShifted` only helps in the spring, and it doesn't tell you which direction it was shifted.  It's also broken when time zone is used (see moment/moment-timezone#131)

**Comment by mj1856** [comment]
I dug in a bit further, and I can't find anywhere that moment tries to apply consistent DST adjustment behavior. In my original example, calling `add` ultimately just invokes the date setter functions.  So I guess the behavior I observed is still a browser quirk.  I'll switch this over to an enhancement request.

**Comment by mj1856** [comment]
Updated the issue description as well.

**Comment by mj1856** [comment]
Related: http://stackoverflow.com/questions/35879043/chrome-and-firefox-exhibit-different-handling-of-an-invalid-dst-time

**Comment by mj1856** [comment]
[A similar failure](https://github.com/moment/moment-timezone/issues/121#issuecomment-246753825) occurs with just `add`:

```js
var m = moment.tz('2016-10-15', 'America/Sao_Paulo');
m.format(); // "2016-10-15T00:00:00-03:00"
m.add(1, 'day');
m.format(); // "2016-10-15T23:00:00-03:00"
```
One would expect `"2016-10-16T01:00:00-02:00"`

**Comment by marwahaha** [comment]
I can no longer reproduce the `add` failure.
