### ISSUE TITLE
moment-transform, plugin to manipulate dates through patterns

### ISSUE THREAD

**Issue by A----** [moment/moment#2620]
I've finally decided to do something with that plugin of mine, here it is:
http://a----.github.io/moment-transform/

It allows simple operations (set / add / substract) to parts (year, day, hour, …) from a string.

```javascript
moment().transform("YYYY-MM-+01 06:00:00.000"); // Tomorrow at 6am
```

Some options are available like defining your own patterns.

**Comment by mj1856** [comment]
Interesting!  Please create a PR in the [moment/momentjs.com](https://github.com/moment/momentjs.com) repo to add this to the plugins section of the documentation.  Thanks.

**Comment by A----** [comment]
Thanks. PR done.
