### ISSUE TITLE
Detect default locale

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2621]
**Why** do we default the locale to US English? 

Per [this S.O. answer](http://stackoverflow.com/a/25842472/634824) we can detect the user's locale with:

``` javascript
window.navigator.userLanguage || window.navigator.language
```

Why not set the default locale to match the user's locale?

Alternatively, consider adding this as a new function, or as a special parameter to pass into `moment.locale` ?

**Comment by ichernev** [comment]
I guess we can add `moment.locale("default")` which would detect and set the language.

**Comment by maciejmyslinski** [comment]
Hi @ichernev! I'd love to help with this new feature.
I'm new to this codebase so please let me know if you have any suggestions that could help me out.

**Comment by maggiepint** [comment]
closing in favor of #3786 - assuming that will get resolved

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

Thanks for all the discussion here.
