### ISSUE TITLE
Cannot use callbacks in formats parameter to moment#calendar function

### ISSUE THREAD

**Issue by timothyfstephens** [moment/moment#2623]
Using a callback in the formats parameter to moment#calendar function results in an error (format.replace is not a function, in expandFormat function), which is allowed when setting calendar options on the locale.

I have created a pull request [here](https://github.com/moment/moment/pull/2622) with a fix, based on the code from the locale version.

**Comment by ichernev** [comment]
Close in favor of #2622.
