### ISSUE TITLE
possible 2.10 regression in date string construction

### ISSUE THREAD

**Issue by paulfalgout** [moment/moment#2626]
Sorry if this is a duplicate post or some behavior change that I don't recognize, but from `2.9.0` -> `2.10.x` the following behaves differently:

`moment('2015-09-21 18:30:17', "YYYY-MM-DD HH:mm:ss.SSSSS ZZ").format();`

In `2.9.0` I get the date formatted in my local timezone (the inputed one being in UTC), but in .10 it's returning the same date string.

**Comment by paulfalgout** [comment]
https://jsfiddle.net/yrtfgj2f/ with 2.10.6
http://jsfiddle.net/yrtfgj2f/1/  with 2.9.0

**Comment by ichernev** [comment]
First link looks good, second looks bad. So its improvement (unless you swapped the versions). I'll investigate when at  a computer.

**Comment by mj1856** [comment]
How is it an improvement?  The new behavior would suggest that `ZZ` defaults to `+00:00` when not found in the input string.  IMHO, it should only do that if parsed in UTC mode by `moment.utc`.  Otherwise, it should parse it in local mode, as if `ZZ` wasn't provided.

**Comment by ichernev** [comment]
On my machine
```javascript
> moment.version
'2.10.6'
> moment('2015-09-21 18:30:17', "YYYY-MM-DD HH:mm:ss.SSSSS ZZ").format()
'2015-09-21T18:30:17-07:00'
```
```javascript
> moment.version
'2.9.0'
> moment('2015-09-21 18:30:17', "YYYY-MM-DD HH:mm:ss.SSSSS ZZ").format()
'2015-09-21T11:30:17-07:00'
```

Same as your fiddle.

The first one is correct (2.10.6), because my local time is -7:00, so the time is also in localtime, the second one assumes the time to be zulu for some reason, so its 11 o'clock -7 which is 18h UTC, but the input should be local.

**Comment by mj1856** [comment]
Nevermind my earlier comment.  It's the *new* behavior that is correct.  No time zone provided matches the mode being parsed, which is the expected behavior.

I must have mixed up my fiddles.  The 2.9.0 behavior would have been a bug.

@paulfalgout - if your input is in UTC, then you should use `moment.utc` to parse it.  You don't need `ZZ` in the format string unless the input actually contains an offset.

```javascript
moment.utc('2015-09-21 18:30:17', "YYYY-MM-DD HH:mm:ss").format();
```
