### ISSUE TITLE
date format in the gantt-tooltip

### ISSUE THREAD

**Issue by amitchandavale** [moment/moment#2627]
I want to display the date in tooltip in the 'MMM DD' format. i tried like this date-format="moment().format("MMM DD");" but this is not working if i dont use date-format attribute it displays date in default format i.e. MMM DD, HH:mm and for moment().format(); only it displays the date in default format YYYY-MM-DDTHH:mm:ssZ please help me to resolve this

**Comment by ichernev** [comment]
Elaborate "not working". It should work

**Comment by amitchandavale** [comment]
elaboration for not working is after using  date-format="moment().format("MMM DD");" this in the angular-gantt div in the HTML file it is not displaying the tooltip. And if i only use date-format="moment().format();" this line then it displays tooltip with default date format i.e. YYYY-MM-DDTHH:mm:ssZ

**Comment by amitchandavale** [comment]
sorry not anular-gantt div it is gantt-tooltips div

**Comment by amitchandavale** [comment]
This line is also not working " gantt-tooltips enabled="true" date-format="MMM DD" gantt-tooltips"
