### ISSUE TITLE
APA formatting for AM/PM

### ISSUE THREAD

**Issue by besartbytyqi** [moment/moment#2628]
Per [APA formatting standards](https://owl.english.purdue.edu/owl/resource/593/01/) under the **Time of Day** heading the proper formatting for AM/PM is either A.M./P.M or a.m./p.m.

**Comment by paulfalgout** [comment]
I think you just want to setup APA formatting as a locale.  You can customize am/pm to behave and to be formatted however you want.

http://momentjs.com/docs/#/customization/am-pm/

**Comment by ichernev** [comment]
This will break too much code if we change it. Customize a locale as @paulfalgout

**Comment by gabn88** [comment]
Does this mean doing this:

moment.updateLocale('en', {
    meridiem : {
        am : 'a.m.',
        AM : 'A.M.',
        pm : 'p.m.',
        PM : 'P.M.'
    }
});
?

**Comment by besartbytyqi** [comment]
@gabn88, yes.
