### ISSUE TITLE
Issue with the setDefault timezone.

### ISSUE THREAD

**Issue by michplunkett** [moment/moment#2629]
Upon switching form 2.09 to 2.10 I noticed that the setDefault timezone was no longer adjusting all of the moments like it was previously. Is there a known bug with the default timezone feature?

**Comment by paulfalgout** [comment]
Could be related https://github.com/moment/moment/issues/2626

**Comment by mj1856** [comment]
`setDefault` is part of the moment-timezone API.

There's one open issue on this in moment/moment-timezone#208.  If your scenario is different, then please log a new issue at https://github.com/moment/moment-timezone/issues
