### ISSUE TITLE
moment.utc().isSame(moment.utc().toArray()) fails

### ISSUE THREAD

**Issue by joelmukuthu** [moment/moment#2633]
```javascript 
var dateUtc = moment.utc();
dateUtc.isSame(dateUtc.toArray()) === true; // this fails

var dateLocal = moment();
dateLocal.isSame(dateLocal.toArray()) === true; // this doesn't
```
I guess since creating a moment from an array (for comparison) creates it in local time because the array doesn't contain timezone information. Is this expected behaviour?

**Comment by mj1856** [comment]
Yes, this is expected behavior.  When you call `toArray`, the results take the mode and offset into account.  If the moment is in UTC mode, then the array will represent the UTC values.

To go back to a moment, you'd have to pass that array back in to `moment.utc`.  In your comparison example:

```javascript
dateUtc.isSame(moment.utc(dateUtc.toArray())) === true
```
