### ISSUE TITLE
moment.diff in months around Feb 28th is wrong

### ISSUE THREAD

**Issue by JamesSkinner** [moment/moment#2642]
When using `moment.diff` with 28th Feb, the results wrong. The function reports exactly 1 month difference with any date where the day of the month is 28 or more.

```
moment('2015-03-28').diff(moment('2015-02-28'),'months',true); // 1
moment('2015-03-29').diff(moment('2015-02-28'),'months',true); // 1
moment('2015-03-30').diff(moment('2015-02-28'),'months',true); // 1
moment('2015-03-31').diff(moment('2015-02-28'),'months',true); // 1

// Different result when switching the dates around
moment('2015-02-28').diff(moment('2015-03-31'),'months',true); // -1.0955585464333781
```
I can't see a situation where this result would be expected.

http://jsfiddle.net/vjqa50dy/

**Comment by alburthoffman** [comment]
The third argument indicates if it can return float or not. when you set it true, then it will return float number when needed.

set it false, it will only return integer.

**Comment by JamesSkinner** [comment]
Yes I know, but in my example I'm setting it to `true` and it is returning an integer. The following returns exactly 1:
```
moment('2015-03-30').diff(moment('2015-02-28'),'months',true);
```

**Comment by alburthoffman** [comment]
This is correct, right? the diff days is 30 days, then it would be one month.

**Comment by JamesSkinner** [comment]
I can see that could make sense but I think it in inconsistent due to the following:

1. `moment('2015-03-30').diff(moment('2015-02-28'),'months',true);` is 1 but `moment('2015-02-28').diff(moment('2015-03-30'),'months',true);` (the inverse) is -1.06325...

2. The following 4 all return exactly 1 month:
```
moment('2015-03-28').diff(moment('2015-02-28'),'months',true); // 1
moment('2015-03-29').diff(moment('2015-02-28'),'months',true); // 1
moment('2015-03-30').diff(moment('2015-02-28'),'months',true); // 1
moment('2015-03-31').diff(moment('2015-02-28'),'months',true); // 1
```
Which can't be right - certainly in my thinking you can't have more than one answer for the question "which day is exactly 1 month after day x"?

**Comment by mj1856** [comment]
This has been discussed several times before.  The latest is in #2598.

The fact is, a month is not a fixed unit of time (neither is a year).  Since a moment tracks time in absolute instantaneous time (as opposed to calendar time), there are various compromises to be made, and there are bound to be inconsistencies.

In particular, it does matter which direction you are moving when adding/subtracting/differencing months.  `x + 1 - 1 == x` doesn't hold true for calendar math in all cases.

**Comment by JamesSkinner** [comment]
Ok thanks. From a user's point of view though I would intuitively assume the following:

1. `m1.diff(m2) == m2.diff(m1)`
2. `moment('2015-03-31').diff(moment('2015-02-28'),'months',true) > 1`

Potentially a note in the docs would be useful on these points.
