### ISSUE TITLE
String dates containing ordinals are treated as invalid

### ISSUE THREAD

**Issue by JamesDonnelly** [moment/moment#2643]
```moment("30th September 2015").format()```

Returns ```"Invalid date"```. I'd expect Moment to detect and correctly handle ordinals (especially when valid).

**Comment by icambron** [comment]
Moment isn't an NL parser: when you call it with no format string, it just let's the native `Date()` constructor parse the input string, and that format isn't one your browser happens to handle. That feature is actually even deprecated and probably warned you.

Try this instead:

```js
moment("30th September 2015", "Do MMMM YYYY").format();
```
