### ISSUE TITLE
Change "a few seconds ago" to "seconds ago"

### ISSUE THREAD

**Issue by MorrisJobke** [moment/moment#2644]
Is this something you want/would accept?
How are translations then updated?
How is the process of such a change?

If you don't want this in moment.js this is also fine. Feel free to close this ticket then.

Related ticket: owncloud/core#18627 - we can also maintain a wrapper, but having it upstream would be the ideal way to solve this ;)

**Comment by mj1856** [comment]
No patch is required.  If you just want to change the one string, then:

```javascript
moment.localeData('en')._relativeTime.s = 'seconds';
```

Otherwise, refer to the section on [customizing the relative time](http://momentjs.com/docs/#/customization/relative-time/) in the docs.

**Comment by salihsalumon** [comment]
Sensitive media

**Comment by salihsalumon** [comment]
Active
