### ISSUE TITLE
Define default english locale instead of using it only.

### ISSUE THREAD

**Issue by zlorf** [moment/moment#2653]
In the source, `'en'` locale is activated via `getSetGlobalLocale`.
This means that when I load other locale and change to it (e.g. `moment.locale('pl')`), then I cannot simply go back to english (`moment.locale('en')` return still `'pl'`, because en locale is not defined).

I propose to change `getSetGlobalLocale` to `defineLocale` when setting `'en'` locale. This way english would still be active, but also it will be available later as defined locale.

**Comment by mj1856** [comment]
The `en` locale is always defined.  Where are you seeing that's it's not?

![image](https://cloud.githubusercontent.com/assets/1396388/10314892/07b27904-6c0c-11e5-81fe-9f513f2ba29a.png)

**Comment by mj1856** [comment]
One thing you might be getting caught up on.  The locale that a moment is created with gets copied into the instance of the moment object.  So changing locales globally doesn't affect moment objects you've already created.

![image](https://cloud.githubusercontent.com/assets/1396388/10315047/abf6680e-6c0c-11e5-9c56-76bc28225e9d.png)

You can always call `.locale('en')` on a specific moment object to change that moment's locale.

**Comment by zlorf** [comment]
Right, when I test now, it looks exactly as you posted.
But this morning the locale stayed `'pl'` even after `moment.locale('en')` (in the first example), I swear. I tested it well before posting an issue here.
It must have been a strange browser bug, then. Sorry for taking your time.

**Comment by zlorf** [comment]
Ah, I found now. Some part of my code was calling `moment.locale('en', null)` (null as a result of other function call), which deletes `'en'` locale. That's why `moment.locale('en')` didn't work after.

**Comment by mj1856** [comment]
No problem.  Glad you found the bug.

**Comment by zlorf** [comment]
It seems that docs don't say a word about locale-deleting behaviour of `null`.
I thought (now obviously wrong) that `moment.locale('en', null)` works just like `moment.locale('en', undefined)` which is equivalent of `moment.locale('en')`.

**Comment by mj1856** [comment]
Sure, I can see how that could be confusing.  If you like, you can open a PR against the docs here: https://github.com/moment/momentjs.com

**Comment by zlorf** [comment]
PR opened: https://github.com/moment/momentjs.com/pull/238
