### ISSUE TITLE
add/subtract by business days

### ISSUE THREAD

**Issue by craigryan** [moment/moment#2655]
moment().add(N, 'businessdays')

which increments forward by N business days (defined as mon-fri).

similarly with subtract()

**Comment by mj1856** [comment]
Dup #1947 & #1281

**Comment by craigryan** [comment]
Curious why this has been closed as the duplicates appear to have dropped
this rather than implement any solution?

There are plenty of scenarios for a default workday add/subtract without
any holiday consideration or weekends other than Sat/Sun.

If really necessary then why not a variant method add(N, "days", [0, 6]) if
you really need to specify particular days to skip.

Craig.

**Comment by mj1856** [comment]
#1947 is still open. Just nothing's been done on it.  Feel free to create a PR and reference either issue.
