### ISSUE TITLE
if unsupported locale is set, null error is thrown, instead should fall back to default language

### ISSUE THREAD

**Issue by alexkli** [moment/moment#2657]
[chooseLocale returns null](https://github.com/moment/moment/blob/49f88864ff411003bfe0550c36defcc75f30d93e/src/lib/locale/locales.js#L37) if no matching locale dictionary can be found, which leads to `this._locale` being `null` and subsequent calls using it throwing errors like

    TypeError: null is not an object (evaluating 'this.localeData().postformat')

It should instead fall back to a default that's always present, either English:

    return locales["en"];

 or something configurable:

    return locales[defaultLocale];

In our case, we set the locale dynamically passed in the body's `lang` attribute using `moment().locale(document.documentElement.lang)`, coming from our server. If a new language pops up on the server that isn't yet supported in moment.js or we don't have it included yet (we have a custom moment.js build with only the languages we need), we don't want the error but a safe default fallback until we can include the right locale.

**Comment by jisaacks** [comment]
What version are you using, this is not what I am seeing. I just tested on `2.10.6` and got this:

```javascript
moment.locale('en'); // set to english
moment.locale(); // returns 'en'
moment.locale('fr'); // set to french
moment.locale(); // returns 'fr'

moment.local('ss'); // not found so returns current 'fr'
moment.local(); // still 'fr'
```

**Comment by alexkli** [comment]
Seen with version `2.8.2`.

When looking at the current master's code, I couldn't see a difference. We fixed it by having `chooseLocale()` at the end do this

    return loadLocale('en');

instead of the `return null;`.

**Comment by jisaacks** [comment]
Here is a [codepen](http://codepen.io/jisaacks/pen/gaKJeE?editors=001) using moment `2.8.2` where I am setting the locale based on the `document.documentElement.lang` property which is an empty string. Afterwards moment's locale is still __en__.

Is this not what you are seeing?
Are you doing something different?

**Comment by alexkli** [comment]
Sorry for the late reply!

We are not using `moment-with-locales.js` but the bare bones `moment.js` and register custom locales (with customized translations).

[Here is a codepen](http://codepen.io/anon/pen/VaRPdY?editors=001) using `2.8.2` that reproduces the issue (make sure to look at the js console for the error).

However, I checked with the newer versions [2.10.6](https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.js) and [2.13.0](https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.js) (change script URL in codepen under Settings > Javascript) and with these the issue seems fixed.

**Comment by hardy12994** [comment]
:thumbsup:
