### ISSUE TITLE
Adding own longDateFormats not possible

### ISSUE THREAD

**Issue by antpaw** [moment/moment#2658]
Why is it not possible to add more formats to the longDateFormats array?

**Comment by mj1856** [comment]
Assuming you mean [`locale#longDateFormat`](http://momentjs.com/docs/#/customization/long-date-formats/), it's not a simple array. Each key value of the object corresponds to one of the recognized tokens moment supports in its parsing and formatting functions.  See [Localized Formats](http://momentjs.com/docs/#localized-formats).

Adding additional formats is not impossible, but would have to be done by:

 1. Creating support for new tokens in the parsing and formatting code.
 2. Adding values in for *all* locale files.
 3. Updating the documentation to reflect the new token.

It's not possible within the current design to just add a single new token to a single locale.
