### ISSUE TITLE
Possible bug in unix()

### ISSUE THREAD

**Issue by PhilPJL** [moment/moment#2660]
not sure if this is a bug or not, but Resharper doesn't like

    function unix () {
        return Math.floor(+this / 1000);
    }

Is ‘this/1000’ valid javascript?  

Other methods seem to use this._offset

**Comment by mj1856** [comment]
When `this` is coerced to a number by `+this`, it's equivalent to calling `this.valueOf()`.  So any logic that needs to involve `_offset` or `_d` is already handled by the `valueOf` function.  The `unix` function just trims it from milliseconds to whole seconds.

The `valueOf` function is special in JavaScript, as it's overridden from the base `Object` prototype that all other objects are derived from.
https://github.com/moment/moment/blob/master/src/lib/moment/to-type.js

So yes, this is valid Javascript.
