### ISSUE TITLE
fromNow() not rounding correctly for birthday use case

### ISSUE THREAD

**Issue by AaronLlanos** [moment/moment#2661]
when I create a moment date of Jan 26th 1993, date.fromNow() should return 22 years instead of 23 years.

Example from a pen: http://codepen.io/AaronLlanos/pen/zvzwJz

**Comment by jisaacks** [comment]
Oct 8 1993 would be 22 years ago. So Jan 26 1993 would be closer to 22 years 9 months ago. Which would be rounded to 23. moment doesn't just subtract the year.

If you look at:
```jacascript
moment('04/26/1993', 'MM/DD/YYYY').fromNow(); //"22 years ago"
```

**Comment by AaronLlanos** [comment]
But it shouldn't be rounded up. It should always be rounded down. I think that this is a  horrible substitute of code: 
```javascript
var birthday = moment('01/26/1993', 'MM/DD/YYYY'); //The date string comes from an API
var birthyear = birthday.get('year');
birthday = moment("1993", "YYYY").fromNow(); //22 Years
```

**Comment by jisaacks** [comment]
@AaronLlanos calculating birthdays is just one use case. Yes, in that use case flooring would make sense, but that is not the only use case for this, and in just about every other use case rounding would generally be more appropriate.

**Comment by AaronLlanos** [comment]
@jisaacks is there a possible work around that I am just not aware of?

**Comment by jisaacks** [comment]
However, I would not be personally opposed as to have some way of telling `fromNow` to round or ceil.

**Comment by AaronLlanos** [comment]
If that were implemented that would solve my problem!

**Comment by jisaacks** [comment]
As for a workaround, this should at least solve the problem:

```javascript
function birthdaysSince(mObj) {
  return Math.floor((moment().unix() - mObj.unix()) / 3.15569e7);
};
birthdaysSince(moment('01/26/1993', 'MM/DD/YYYY')); // 22
```

**Comment by mj1856** [comment]
This is a dup of #2331 - which has the correct solution.

@jisaacks - Any approach that is diff divided by constant is going to get age wrong around various edge cases.  Common mistake.
