### ISSUE TITLE
Unquoted property name caused renaming issue with Google Closure Compiler

### ISSUE THREAD

**Issue by jacobcui** [moment/moment#2664]
Hi,

Can these property be defined using quoted string literal?
https://github.com/moment/moment/blob/d5262a01beec4f6ed1b0ad73ba2da66782b2f60b/lib/locale/relative.js#L2-L14

When I tried to compile moment.js with Google Closure Compiler and moment js externs, these property name is renamed. I think it's better to use string literal like:

    var defaultRelativeTime = {
        'future' : 'in %s',
        'past'   : '%s ago',
        's'  : 'a few seconds',
        'm'  : 'a minute',
        'mm' : '%d minutes',
        'h'  : 'an hour',
        'hh' : '%d hours',
        'd'  : 'a day',
        'dd' : '%d days',
        'M'  : 'a month',
        'MM' : '%d months',
        'y'  : 'a year',
        'yy' : '%d years'
    };

**Comment by mj1856** [comment]
This should not be required, as these are all valid JavaSCript identifiers.  See http://stackoverflow.com/questions/4348478/what-is-the-difference-between-object-keys-with-quotes-and-without-quotes
