### ISSUE TITLE
isValid() method does not seem to be working accurately

### ISSUE THREAD

**Issue by jerryjohnjacob** [moment/moment#2668]
The date `100110/09/2015` is invalid.

But running `moment("100110/09/2015", 'L').isValid();` returns `true`.

Please see the [jsfiddle](http://jsfiddle.net/sore2ynm/2/).

This does not look like expected behaviour.

**Comment by alburthoffman** [comment]
moment uses \d{4} to filter the digits and ignore extra parts. It might need to check if there are extra digits or not when parsing.

**Comment by mj1856** [comment]
It works in strict mode:

```javascript
moment("100110/09/2015", 'L').isValid() // true
moment("100110/09/2015", 'L', true).isValid() // false
```

The docs say this:

> Moment's parser is very forgiving, and this can lead to undesired behavior. As of version 2.3.0, you may specify a boolean for the last argument to make Moment use strict parsing. Strict parsing requires that the format and input match exactly.

@ichernev - I'm really not sure exactly *how* forgiving is "very" supposed to be.  Should this sort of input be always invalid? Or only in strict mode?

**Comment by nhitchins** [comment]
Any way to enforce strict parsing to reject repeated unit tokens (rather than just validating the captured data matches the unit)? Or provide a token format validation method? 

In this example, the fractional seconds have been expressed as 'sss' instead of 'SSS' but the resulting moment will use the last 2 digits of the fractional seconds as the actual seconds:
```javascript
moment("2015/11/19 04:45:45.007", "YYYY/MM/DD HH:mm:ss.sss", true).isValid() // true
```

**Comment by icambron** [comment]
@mj1856 this needs to have its current behavior in non-strict mode. Basically the parser says "I'll leave out stuff that doesn't work", and in this case that's "0110". That's sorta odd, but to the parser it's no different than that text being any other string stuck between matching tokens. If that makes you shake your head and say, "forgiving parsing kinda sucks" then that makes two of us.

@nhitchins I think it should be possible to detect contradictory information in the parsing. It's not super easy (e.g. totally fine to specify redundant weekday/dayOfMonth or quarter/month, but only if they agree, so need to check that the month is in the quarter, etc). But if you can make that practical and compact, I think that could be a good PR.
