### ISSUE TITLE
Rendering calendar option by invocation using function instead of string

### ISSUE THREAD

**Issue by piernik** [moment/moment#2678]
Since 2.10.5 we can define calendar options by invocation - http://momentjs.com/docs/#/displaying/calendar-time/

But defining option using function seems not to work.
Here is my example - I want to render only date - without hours.

	moment().calendar(null, {
		sameDay: '[Dziś]',
		nextDay: '[Jutro]',
		nextWeek: '[W najbliższy] dddd',
		lastDay: '[Wczoraj]',
		lastWeek: function () {
			switch (this.day()) {
				case 0:
					return '[W zeszłą niedzielę]';
				case 3:
					return '[W zeszłą środę]';
				case 6:
					return '[W zeszłą sobotę]';
				default:
					return '[W zeszły] dddd';
			}
		},
		sameElse: 'L'
	});

**Comment by mj1856** [comment]
Indeed, you can pass a function when customizing the locale globally, but not when overriding the locale for a specific instance.  A function should be allowed in either scenario.

**Comment by piernik** [comment]
Thanks - waiting for update

**Comment by kepta** [comment]
Hello, I am new to open source community 
and would love to resolve this.
@mj1856 can you please help me getting started with this?

**Comment by kepta** [comment]
After studying the source code,
```Javascript
// calendar.js:16
return this.format(formats && formats[format] || this.localeData().calendar(format, this, createLocal(now)));
```
passes formats as an argument to format function.
```Javascript
// format.js:24
export function format (inputString) {
    var output = formatMoment(this, inputString || hooks.defaultFormat);
    return this.localeData().postformat(output);
}
```
expects it to be a string, I think the problem lies here @mj1856 . What do you suggest on this?

**Comment by mj1856** [comment]
@kepta - Welcome, and thanks for offering to help!

Before starting with this issue, make sure to read the [contributor guide](https://github.com/moment/moment/blob/develop/CONTRIBUTING.md), which has instructions for building and testing the project.

Also be sure you understand how to use Git and send [a pull request](https://help.github.com/articles/using-pull-requests/), as Git and GitHub are well documented in other channels.

This particular issue is that the [`calendar`](http://momentjs.com/docs/#/displaying/calendar-time/) function's second parameter should have all the same features and behavior as offered through [customization of calendar output in the locale](http://momentjs.com/docs/#/customization/calendar/).  Specifically, the docs say:

> Each of the `Locale#calendar` keys can also be a callback function...

This works when customizing the locale, but not when passing an object to the `calendar` function's second parameter.

You will need to modify [/src/lib/moment/calendar.js](https://github.com/moment/moment/blob/develop/src/lib/moment/calendar.js) with similar implementation as found in [/src/lib/locale/calendar.js](https://github.com/moment/moment/blob/develop/src/lib/locale/calendar.js#L12), where it tests if it's a function or not.

You'll also need to include test for this.  The other tests for `calendar` are in the [/src/test/locale/en.js](https://github.com/moment/moment/blob/7d121f205f070162a353e7f303490fd85ee31031/src/test/locale/en.js#L162-L211) default English locale file, and are also found in all of the other locale-specific files.  However, I don't think you need to test all locales.  It would probably make more sense to add a new test file called `calendar.js` under [/src/test/moment](https://github.com/moment/moment/tree/master/src/test/moment), which would hold these specific tests for the new functionality.  You should then put a comment in that file explaining that the rest of the calendar tests are located in the locale files.

Feel free to open a pull request at any stage, even if you're not done.  Just state "work in progress" near the top so we know it's not ready to be merged.  Then if you have questions we can review the PR with what you've done so far.  You can always [rebase](https://help.github.com/articles/using-git-rebase/) before the final merge, so don't be afraid to make mistakes.

**Comment by mj1856** [comment]
Close in favor of #2691.  We'll track progress there.  Thanks!
