### ISSUE TITLE
Format Times Depending on Age

### ISSUE THREAD

**Issue by realph** [moment/moment#2680]
How would one go about formatting times with angular-moment, depending on their age.

For example:

Within the last 24 hours: Yesterday at 9:18pm
Outside the last 24 hours: Oct 10, 10:15am
Outside the current year: Dec 4, 2012, 12:07pm
Is something like this possible?

Any help is appreciated. Thanks in advance!

**Comment by mj1856** [comment]
It sounds like you're looking for the [`calendar`](http://momentjs.com/docs/#/displaying/calendar-time/) function.  It can be customized as shown in the docs.

If you were asking specifically about angular-moment, not just moment, then you should look [in their repo](https://github.com/urish/angular-moment).  I believe they have an `amCalendar` filter.
