### ISSUE TITLE
endOf('week') returns incorrect value on midnight DST transition

### ISSUE THREAD

**Issue by irvingreid** [moment/moment#2681]
I'm getting what I think is an incorrect result with the Brazilian time zones, specifically with moment.endOf('week') on Chrome (46) and Firefox (43.0a2)

```javascript
d = moment.tz('2015-10-16 20:00:00-0400', 'America/Cuiaba');
d.endOf('week').format()
  -> "2015-10-17T22:59:59-04:00"
```
The 'missing hour' in this transition is actually 00:00:00-04:00 to 01:00:00-03:00, so `endOf('week')` should be 23:59:59-0400. `startOf('week')` in the subsequent week correctly reports 2015-10-18 01:00:00-0300.

**Comment by irvingreid** [comment]
Oops, looks like it also misses `endOf('week')` in the following week:

```javascript
d = moment.tz('2015-10-23T20:00:00-03:00', 'America/Cuiaba');
d.startOf('week').format()
   -> "2015-10-18T01:00:00-03:00"
d.endOf('week').format()
   -> "2015-10-25T00:59:59-03:00"

**Comment by mj1856** [comment]
This appears to be a moment-timezone bug.  I can reproduce your results only when using `moment.tz(..., 'America/Cuiaba')`.   If instead I set my local time zone for the same location and just use `moment(...)`, then I get the correct results.

Would please be so kind to open a new issue at: https://github.com/moment/moment-timezone/issues

Thanks.

**Comment by irvingreid** [comment]
https://github.com/moment/moment-timezone/issues/260

**Comment by mj1856** [comment]
Thanks.
