### ISSUE TITLE
Leap Year Test / Doc Typo

### ISSUE THREAD

**Issue by SkydiverFL** [moment/moment#2686]
Okay, now I really think I'm losing my mind!  Is there a typo in the docs...

`moment([2010, 1, 29]).isValid();  // false (not a leap year)`

The [possibly] ironic part is this same logic appears on a StackOverflow answer from 2013:

http://stackoverflow.com/questions/16353211/check-if-year-is-leap-year-in-javascript

Leap years are when February (month 2) has 29 days (known as the "leap day").  Shouldn't we be checking `2010, 2, 29`?

Normally I'd think this was a typo, but the same logic is in two places.  So, either there's a interesting irony here, or I'm about to publically humiliate myself twice.

**Comment by mj1856** [comment]
Months on the JavaScript `Date` object are numbered 0 through 11, not 1 through 12, so February is month 1.

For compatibility reasons, moment uses the same conventions when passing values by array as you showed here, or when using the `month` function.

**Comment by mj1856** [comment]
Of course, you could also use the [`isLeapYear`](http://momentjs.com/docs/#/query/is-leap-year/) function.

**Comment by SkydiverFL** [comment]
Good to know. Thanks!
