### ISSUE TITLE
Parser should not return a valid date for strings only containing "a" or "p" with "a" format

### ISSUE THREAD

**Issue by nrabinowitz** [moment/moment#2687]
The following permissive parser returns a "valid" date:
```
moment('help yourself to pork pies', [
  'MM/DD/YYYY h:mma'
]).isValid()
// true
```
This appears to be true for any non-numeric string containing either `a` or `p`, which are accepted by the `"a"` formatting string. The date is midnight of the current day.

This is nonsensical behavior - I'd suggest that no string should be judged valid solely on the basis of the `"a"` token. Obviously strict mode would help, but strict mode isn't desirable when parsing user input.

**Comment by mj1856** [comment]
Strict mode won't help?
