### ISSUE TITLE
Change the weekend days to Friday and Saturday

### ISSUE THREAD

**Issue by heavenchains** [moment/moment#2689]
Hi, I want to change the weekend days from Saturday and Sunday to be Friday and Saturday , Please if you can tell me how to do it would be nice.

**Comment by mj1856** [comment]
Moment doesn't have any API that describes things in terms of weekends.

Different locales may have a different starting day of week, but whether or not it's the weekend is not given.  For example:

```javascript
moment().locale('en').startOf('week').format('dddd')  // "Sunday"
moment().locale('en-GB').startOf('week').format('dddd') // "Monday"
```

Both locales consider Saturday and Sunday to be the weekend, but they differ on if the week begins in the middle of the weekend or at the end of it.

Also recognize that the ISO week is culture independent.

```javascript
moment().startOf('isoWeek').format('dddd')  // "Monday"  (always)
```
