### ISSUE TITLE
Day that have 25 hours. Daylight savings.

### ISSUE THREAD

**Issue by mauron85** [moment/moment#2699]
Check this js fiddle.

http://jsfiddle.net/mauron85/aujyeacc/

**Comment by jisaacks** [comment]
I am seeing both specs pass, what am I supposed to be looking at?

**Comment by mauron85** [comment]
Sorry I forgot to mention that your OS timezone has to be one of those where daylight saving switch occurs on today (25.10.2015). Like most EU countries.

**Comment by jisaacks** [comment]
OK, modified the gist to be 11/01 which is when the time changes where I am (Atlanta) and I see what you are pointing out, but I am curious why you think it should be 24? 

We gain an hour in the fall so the day the time changes on actually does have 25 hours.

The opposite happens in the spring and we have a 23 hour day.

**Comment by mauron85** [comment]
To be honest. Maybe because lack of real experience with DST. Just get slapped with it in my app. Also the other thing is how can we detect these days to act accordingly? There is isDST method, but doesn't seem working for me.

moment('2015-25-10 2:00', 'YYYY-MM-DD HH:mm').isDST() === false
moment('2015-25-10 3:00', 'YYYY-MM-DD HH:mm').isDST() === false

**Comment by jisaacks** [comment]
@mauron85 

Not sure what time zone you are in but for where I am I get this:

```javascript
moment('2013-11-03 2:00', 'YYYY-MM-DD HH:mm').isDST() // false
moment('2013-11-03 1:59', 'YYYY-MM-DD HH:mm').isDST() // true
```

I do see you have your date and month backwards though. I would guess that is the problem.

**Comment by mj1856** [comment]
Moment is behaving as designed.  Today really does have 25 hours in time zones that are falling back today.  In the spring, there will be a day that has 23 hours as well.

The reason the above lines both return false is because you specified `2015-25-10` instead of `2015-10-25`.  You'll also notice that `.isValid() === false` for those.  If you specify them correctly, they return correctly.
