### ISSUE TITLE
order of quarter token is affecting date output

### ISSUE THREAD

**Issue by mhedrick** [moment/moment#2703]
`moment("Q1 March 2015", "[Q]Q MMMM YYYY")` will return an expected date of Sun Mar 01 2015 00:00:00 GMT-0500 (US Eastern Standard Time), but `moment("March Q1 2015", "MMMM [Q]Q YYYY")` returns Thu Jan 01 2015 00:00:00 GMT-0500 (US Eastern Standard Time).

Actually formatting (`moment().format("MMMM [Q]Q YYYY")`) an already made moment object works just fine and as expected.  As such the workaround `moment("March Q1 2015", "MMMM [Q1][Q2][Q3][Q4] YYYY")` is (technically) valid.

documented here: http://jsfiddle.net/3o631puy/

**Comment by icambron** [comment]
Yeah, this is a hard one for Moment. Quarters are basically month aliases; see [here](https://github.com/moment/moment/blob/develop/src/lib/units/quarter.js#L20). So it's getting contradictory information about what month it should be, and in practice it takes the last one. Compare to:

```js
moment("Q1 March 2015", "[Q]Q MMM YYYY").format(); //=> '2015-03-01T00:00:00-05:00'
```

I'm open to suggestions on how to reconcile that information, but it's not obvious to me how you'd do it. I mean, what would, for example, "December Q2" mean?

**Comment by marwahaha** [comment]
For reference, a permanent URL to what @icambron was talking about is here:
https://github.com/moment/moment/blob/20bdc7d236577d47006040cac6cf381a538fbbff/src/lib/units/quarter.js#L20

Closing as wontfix. I echo the concern that `Q` and `M` don't make sense together. 

Feel free to comment/re-open if folks have other ideas.
