### ISSUE TITLE
Multiple moment versions in node project can cause problems

### ISSUE THREAD

**Issue by parisholley** [moment/moment#2708]
I was running into this error when trying to format an incoming date that is a moment object from a different version:

```
moment(possibleExistingMomentObjectFromAnotherVersion).utc().format('YYYY-MM-DD HH:mm:ss')
```

```
TypeError: Cannot read property 'postformat' of undefined
    at Moment.format (/var/app/current/node_modules/mantis-reporting/node_modules/moment/moment.js:1951:33)
```

**Comment by ichernev** [comment]
Well, not much we can do about it, except make the code twice as long for an if statement around every function call.

**Comment by ichernev** [comment]
go through milliseconds or js Date, so the old moment object is not used in any way.

```javascript
moment(+oldMoment);
moment(oldMoment.toDate());
```

**Comment by parisholley** [comment]
@ichernev i've been using isMoment and toDate() to work around, just opened issue incase it is a problem or if some type of error could be thrown instead of accepting the object and breaking. perhaps moment could autogenerate a unique id when the module is required for the first time, and the moment constructor can check for differences and throw an exception when it does not match?

also, not sure if it is related to me using moment-timezone as well or not.

**Comment by marwahaha** [comment]
I'm not sure we would make a unique ID for this. You should have a single version of Moment installed. I am open to discussion here.

Closing due to age. Please re-open if you still have questions.
