### ISSUE TITLE
Locale Calendar - Capitalization 

### ISSUE THREAD

**Issue by 3LOK** [moment/moment#2710]
Hi,

When using the .calendar() function inside a sentence, the resulting text looks bad due to capitalization. For example: "We're open Today at 12:00". "We're open Tomorrow at 1:00 pm".

Possible hacking solutions have different problems:
- Uncapitalize the first letter won't work if the resulting string is "Thursday at 12:00".
- Uncapitalize specifically the words "Today", "Tomorrow", "Next week" won't work for different languages unless we have a long search-replace list for all languages.

I suggest adding another sent of calendar locale definitions for the case were the calendar needs to be mid-sentence, and a parameter to the calendar function.

Thanks.

**Comment by marwahaha** [comment]
I don't think this is a great idea. If you would like to use this mid-sentence, you can lowercase the output from moment, and capitalize only the first letter of the sentence.

It seems like a lot of extra weight in moment to have both uppercase and lowercase versions of `Today`, `Tomorrow`, etc.

Please re-open if you feel strongly about this.

**Comment by decademoon** [comment]
> If you would like to use this mid-sentence, you can lowercase the output from moment, and capitalize only the first letter of the sentence.

You can't do this because some words must always be capitalized like "Thursday" but words like "Tomorrow" should only be capitalized at the start of a sentence, like OP said.

**Comment by decademoon** [comment]
Note `date-fns` does it [correctly](https://date-fns.org/v2.27.0/docs/formatRelative).
