### ISSUE TITLE
Locale Calendar - Today at xxxx

### ISSUE THREAD

**Issue by 3LOK** [moment/moment#2711]
Hi,

Another request in the .calendar() function's locale definition. For "Today at 12:00" you simply want sometime to just write "at 12:00". For example, "We'll open at 12:00".

Can we add another locale calendar definition for just [at], and an option in the .calendar() function to use that definition for today?

Thanks!

**Comment by mj1856** [comment]
Why do you need to do this through the `calendar` function, rather than through `format` and your own logic?

**Comment by 3LOK** [comment]
tl;dr
Well, basically, since momentjs locale already have all the translation to the "at" syntax. 

The longer answer:
I don't really need to go through the format, I just need to configure calendar with a different syntax for "Today". However holding my own translations to that syntax in ALL languages seems like something that should be shared to all, no?

**Comment by marwahaha** [comment]
Thanks for opening this request.
For now, we will not take this change.
Please re-open if you still have concerns.
