### ISSUE TITLE
Improve the moment-timezone interface

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2714]
This is a design change proposal for a future version (ie. 3.0)

Currently, moment-timezone works by monkey-patching several moment functions.  This has led to inconsistent behavior and several bugs in moment-timezone.

It would be preferred if moment had an explicit interface for moment-timezone to plug into.

**Comment by maggiepint** [comment]
See moment/moment-rfcs#1

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
