### ISSUE TITLE
Function to get next/last DST transitions

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2715]
See moment/moment-timezone#266.  This issue tracks the moment part.

It needs to scan the local environment by interrogating the offsets for various dates.  @timrwood  and I both did something similar working on time zone detection, so we can repurpose that here.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

**Comment by marwahaha** [comment]
Re-opening in case it is a simple change.
