### ISSUE TITLE
Fix deperecation warnings caught by travis ci

### ISSUE THREAD

**Issue by paladox** [moment/moment#2719]
Please fix deprecation warnings caught by travis ci https://travis-ci.org/moment/moment/builds/88308563

355Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period).

356Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period).

357Deprecation warning: toIsoString() is deprecated. Please use toISOString() instead (notice the capitals)

358Error

359    at Duration.toIsoString (/home/travis/build/moment/moment/build/umd/moment.js:750:36)

360    at Object.<anonymous> (/home/travis/build/moment/moment/build/umd/test/moment/duration.js:322:42)

361    at Object.Test.run (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:136:18)

362    at /home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:279:10

363    at process (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:1277:24)

364    at null._onTimeout (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:383:5)

365    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

366Deprecation warning: years accessor is deprecated. Use year instead

367Error

368    at Moment.years (/home/travis/build/moment/moment/build/umd/moment.js:750:36)

369    at Object.<anonymous> (/home/travis/build/moment/moment/build/umd/test/moment/getters_setters.js:86:11)

370    at Object.Test.run (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:136:18)

371    at /home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:279:10

372    at process (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:1277:24)

373    at null._onTimeout (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:383:5)

374    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

375Deprecation warning: months accessor is deprecated. Use month instead

376Error

377    at Moment.months (/home/travis/build/moment/moment/build/umd/moment.js:750:36)

378    at Object.<anonymous> (/home/travis/build/moment/moment/build/umd/test/moment/getters_setters.js:87:11)

379    at Object.Test.run (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:136:18)

380    at /home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:279:10

381    at process (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:1277:24)

382    at null._onTimeout (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:383:5)

383    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

384Deprecation warning: dates accessor is deprecated. Use date instead.

385Error

386    at Moment.dates (/home/travis/build/moment/moment/build/umd/moment.js:750:36)

387    at Object.<anonymous> (/home/travis/build/moment/moment/build/umd/test/moment/getters_setters.js:88:11)

388    at Object.Test.run (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:136:18)

389    at /home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:279:10

390    at process (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:1277:24)

391    at null._onTimeout (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:383:5)

392    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

393Deprecation warning: moment.lang is deprecated. Use moment.locale instead.

394Error

395    at Function.lang (/home/travis/build/moment/moment/build/umd/moment.js:750:36)

396    at Object.<anonymous> (/home/travis/build/moment/moment/build/umd/test/moment/locale.js:195:16)

397    at Object.Test.run (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:136:18)

398    at /home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:279:10

399    at process (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:1277:24)

400    at null._onTimeout (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:383:5)

401    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

402Deprecation warning: moment.langData is deprecated. Use moment.localeData instead.

403Error

404    at Function.langData (/home/travis/build/moment/moment/build/umd/moment.js:750:36)

405    at Object.<anonymous> (/home/travis/build/moment/moment/build/umd/test/moment/locale.js:198:29)

406    at Object.Test.run (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:136:18)

407    at /home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:279:10

408    at process (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:1277:24)

409    at null._onTimeout (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:383:5)

410    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

411Deprecation warning: moment().lang() is deprecated. Instead, use moment().localeData() to get the language configuration. Use moment().locale() to change languages.

412Error

413    at Duration.lang (/home/travis/build/moment/moment/build/umd/moment.js:750:36)

414    at Object.<anonymous> (/home/travis/build/moment/moment/build/umd/test/moment/locale.js:289:40)

415    at Object.Test.run (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:136:18)

416    at /home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:279:10

417    at process (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:1277:24)

418    at null._onTimeout (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:383:5)

419    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

420Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779

421Error

422    at Moment.zone (/home/travis/build/moment/moment/build/umd/moment.js:750:36)

423    at Object.<anonymous> (/home/travis/build/moment/moment/build/umd/test/moment/utc.js:63:15)

424    at Object.Test.run (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:136:18)

425    at /home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:279:10

426    at process (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:1277:24)

427    at null._onTimeout (/home/travis/build/moment/moment/node_modules/qunit/node_modules/qunitjs/qunit/qunit.js:383:5)

428    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

**Comment by icambron** [comment]
Well, we do have to test deprecated functionality. The best thing to do would be to mock the console and assert that the right thing was printed (this is a bit tricky because we only issue a given deprecation warning once). In the absence of that, since we don't test the printing part at all, if you just want to silence the tests, adding a `moment.dontWarnDeprecated` boolean and then calling it at the start of the test seems OK - PR would likely be accepted.

**Comment by maggiepint** [comment]
Fixed by #3065

**Comment by paladox** [comment]
Thanks.
