### ISSUE TITLE
When initializing an invalid date by using constructor with format, toISOString() returns current date

### ISSUE THREAD

**Issue by Fensterbank** [moment/moment#2727]
Hello,

during app development I noticed a confusing issue.
If an invalid date is initialized by using the constructor with the format parameter, the method `toISOString()` returns the current date.

![bug momentjs](https://cloud.githubusercontent.com/assets/1684826/10911672/31ac4ae6-8246-11e5-8841-03527027ed91.png)

**Comment by icambron** [comment]
Yeah, that should clearly be consistent. What's not clear to me what the right behavior is, though: it really ought to return a date that won't totally confuse an ISO parser. My guess the right thing to do is to have both the `toISOString()` calls return `null`.

**Comment by ichernev** [comment]
#2624 fixed that, current default it works as expected (`Invalid Date`).
