### ISSUE TITLE
September should be abbreviated as Sept.

### ISSUE THREAD

**Issue by Aweary** [moment/moment#2728]
Currently `moment` uses Sep for the September abbreviation, but per the OED it should be Sept.

http://public.oed.com/how-to-use-the-oed/abbreviations/#s

**Comment by mj1856** [comment]
Many other sources site that either are valid.

http://linguapress.com/grammar/dates.htm
https://en.wikipedia.org/wiki/September
http://forum.wordreference.com/threads/abbreviation-of-september-sep-or-sept.929631/
https://www.quora.com/Which-is-the-formal-abbreviation-of-September-Sept-or-Sep

Other than it being OED's preference, is there a good reason to change this?

**Comment by Aweary** [comment]
The OED is the most authoritative source listed for english language grammar/syntax. Your third source also seems to overwhelmingly recommend Sept. over Sep
>In American English, Sept. is more common.
 
>I've never seen "Sep." for the abbreviation, and Cambridge also recommends "Sept." as the correct abbreviation. :)
 
>Sept. is the most common abbreviation for September in North America
 
> I think I would probably tend towards "Sept.".
 
> I would generally use Sept.

And the highest voted answer on Quora concurs with the OED. So I'd say that while either is *technically valid* that Sept. is preferred.

**Comment by mj1856** [comment]
Ok by me.

**Comment by mj1856** [comment]
This should also be validated for the other locale-specific English files.

**Comment by rishijain** [comment]
This issue should be closed now via https://github.com/moment/moment/pull/2746.

**Comment by ichernev** [comment]
We merged this in, but I'll revert it because it breaks too much code.

Unfortunately too many people use the format strings to pass dates between programs, and most programs / languages / frameworks out there understand `Sep` but not `Sept`.

Until we figure out a better way to do this (like specify human vs machine friendly) we're stuck to `Sep`.

**Comment by MaxPRafferty** [comment]
@mj1856 @ichernev Sorry to necro, but this issue comes up as the top result for `moment format "sept"`, and I was looking for a little clarity. At this point, is the preferred method of achieving this to modify the english locale manually? e.g.
```
moment.updateLocale('en', {
    monthsShort :  'jan_feb_mar_apr_may_june_july_aug_sept_oct_nov_dec'.split('_')
});
```
