### ISSUE TITLE
Loading moment twice discards extensions

### ISSUE THREAD

**Issue by TimvdLippe** [moment/moment#2736]
Consider the following use-case:
1. Project loads `moment`
2. Project loads an extension (for example https://github.com/moment/moment-timezone)
3. Project loads another dependency which loads `moment`

This causes the extension to be discarded, as moment is redefined. Trying to use the extension causes `moment.extension is undefined`-error.

**Expected behaviour**
When moment loads, it checks if it is already loaded. If it is already loaded, it returns silently. Resulting extensions to remain defined and usable.

**Proposed fix**

``` javascript
if (global.moment !== undefined) {
  // Moment is already loaded, don't redefine
  return;
}
```

I think this should be inserted before https://github.com/moment/moment/blob/develop/moment.js#L8

**Comment by JeremybellEU** [comment]
@ichernev could you please give an indication when this issue can be solved? It is blocking me from installing certain dependencies.

**Comment by mj1856** [comment]
@TimvdLippe - A complete (minimal) example would be appreciated here.

**Comment by TimvdLippe** [comment]
@mj1856 I have created the jsbin: http://jsbin.com/xemidereza/edit?html,console

**Comment by mj1856** [comment]
@ichernev @timrwood - I'm a bit out of my area of expertise here, but would it be possible to only load the moment global if it is not already loaded?

**Comment by TimvdLippe** [comment]
Ping, still encountering this issue.

**Comment by icambron** [comment]
What environment is this? i.e. what are you using to load Moment?

**Comment by TimvdLippe** [comment]
I am using webcomponent that have moment as dependency. Since the element embeds moment in the code, it could be that moment is loaded twice. This does not throw any errors, but does throw away previously loaded extensions.

**Comment by icambron** [comment]
I think we'd take that fix, yeah. The reason everyone is moving slowly on this is that we support like a zillion different module loaders and don't have good  testing around them. That makes us all nervous about changing that stuff; this might fix your use case but break others. But I've managed to convince myself this one is OK.

The fix actually goes [here](https://github.com/moment/moment/blob/b135bf1a6d58ff94287f0a21455bfa6a1ddc7226/templates/default.js#L4) and probably also [here](https://github.com/moment/moment/blob/b135bf1a6d58ff94287f0a21455bfa6a1ddc7226/templates/globals.js#L5).

**Comment by TimvdLippe** [comment]
I have submitted the suggested changes in #3138 

I tried to test the changes with the jsbin posted above, but could not figure out how to do that. Sorry for that, hopefully you can give me some pointers or test it for me. Thank you for your time!

**Comment by butterflyhug** [comment]
So, it sounds like the underlying issue is that there's not a very good way for a reusable web component to load its own copy of moment without relying on or affecting the global namespace?

**Comment by TimvdLippe** [comment]
Completely missed the comment of @butterflyhug, sorry about that. Yes that is the underlying issue. Normally you can load moment twice in different web components and be fine, that is not a problem. However, the following example is currently broken:

You have 2 web components, `my-date-picker` and `my-local-time`. `my-date-picker` only loads `moment` and `my-local-time` loads `moment` plus an extension like `moment-timezone`. There is a difference in behavior when you reverse the loading of these web components. E.g. if you load `my-date-picker` first and then `my-local-time`, `moment-timezone` will be loaded. However if you reverse the load order, `moment-timezone` will be loaded AND discarded immediately. Therefore the end-result is that `moment-timezone` is unavailable and can not be relied on.

My expectation would be that even if `moment` is loaded twice, it copies the previously hooked extensions and hooks them to the second load of `moment`.

**Comment by TimvdLippe** [comment]
Closing this as it does not seem to happen and I have since dropped my usage of `moment`.
