### ISSUE TITLE
Customisable day length for .humanize()

### ISSUE THREAD

**Issue by freman** [moment/moment#2737]
Hi there.

Someone naievely tossed moment.humanize calls all through our application which has resulted in some epic confusion.

it'd be super awesome to be able to define that a day is "8 hours" or "7.5 hours"

Not super urgent, just would be a nifty feature.

**Comment by gdurelle** [comment]
+1
The 8 hours are a business day so yes, it would be super awesome.

**Comment by marwahaha** [comment]
i don't think we will take a change like this. 
But, you can set relative time thresholds to show things in hours instead of days.
https://momentjs.com/docs/#/durations/humanize/

Best of luck with your projects!
