### ISSUE TITLE
month the return is different

### ISSUE THREAD

**Issue by newmesiss** [moment/moment#2745]
I'm doing a test object moment, but the return is different from my country admitted to give me 1 month apart, I'm doing wrong

  $scope.horaReal =moment({  years:2015, months:11, date:10,hour:12, minute:00 });
//HTML  ->  hora: "2015-12-09T18:10:00.000Z" 

http://embed.plnkr.co/zML9HoAEm7q3cwk27PQt/preview

**Comment by quentindemetz** [comment]
Hi @newmesiss 
months are indexed from 0 and acceptable values go from 0 (january) to 11 (december), this is explained in the <a href="http://momentjs.com/docs/#/get-set/month/">docs</a>.

This means that when you specify `months: 11` you are in fact asking for december.

**Comment by icambron** [comment]
Yup, what @quentindemetz said.
