### ISSUE TITLE
isAfter() returns wrong boolean result

### ISSUE THREAD

**Issue by jlnbuiles** [moment/moment#2748]
I could be mistaken but I think there is a bug in the isAfter(...) method. Here's what I've got:

```javascript
var clientDate = moment('2015-11-11T17:37:00')// 5:37pm
var openingDate = moment().hours(17).minutes(00).seconds(0).milliseconds(0)// 5pm
if (clientDate.isAfter(openingDate)) {
    console.log('is after')
} else {
    console.log('is not after')
    }
```

This prints `is not after` for me.

I also tried the `toString()` method and received the following:

```
open date: Wed Nov 11 2015 17:00:00 GMT+0000
client date: Wed Nov 11 2015 17:37:00 GMT+0000
```

*disclaimer: I am using this in `Parse.com` cloud code but I imported the latest master library (2.10.0) from your repo.*

**Comment by icambron** [comment]
Altering your code with the current date in the `clientDate` definition, I get the expected behavior:

```js
> moment('2015-11-26T17:37:00').isAfter(moment().hours(17).minutes(00).seconds(0).milliseconds(0))
true
```

What browser? Can you update to the latest point release and retry?

**Comment by icambron** [comment]
Closing for lack of info. Happy to reopen if you can help me reproduce the issue.
