### ISSUE TITLE
moment.utc(string) parses ISO8601 as local time when timezone is missing

### ISSUE THREAD

**Issue by timrwood** [moment/moment#275]
See this comment: https://github.com/timrwood/moment/issues/272#issuecomment-5095486

**Comment by rubenspgcavalcante** [comment]
Same problem here:
 moment().valueOf() and moment().utc().valueOf()
return the same value! :disappointed:

So to get the utc milliseconds I need to:
moment().valueOf() - (moment().utcOffset() * 60 * 1000)

**Comment by mj1856** [comment]
@rubenspgcavalcante - I'm not sure what you're asking.  Those two are *supposed* to return the same value, both of which are in milliseconds since the unix epoch.

The snippet you wrote actually returns a different moment in time.

**Comment by james-hoegerl** [comment]
I'm having  similar issue where the UTC flag is set to true but when I cal format(); It returns the local time. Here is a screenshot.

<img width="876" alt="screen shot 2016-07-10 at 8 50 15 am" src="https://cloud.githubusercontent.com/assets/3597266/16713951/728947a4-467b-11e6-8913-a448ebaccebf.png">

The line after the object is a console.log of the var after I call format(); on it.

Am I doing something wrong?

**Comment by maggiepint** [comment]
@james-hoegerl it looks like the internal date object is July 5 2016 at 19:00 central. Add five hours to that to get to UTC, and it is July 6, which is what appears to be logging, so in short, I don't see anything wrong.
It does look like you're using fullcalendar. It does some extension/monkey patching of moment that may cause unusual behavior.

**Comment by james-hoegerl** [comment]
Ok maybe I'm just confused about uct. I thought I would get "2016-05-07 07:00:00" then I could store that in the DB and then get local time for each end user computer via moment.

**Comment by maggiepint** [comment]
So, first of all I will assume you meant 6016-07-05 (July 5th, not May 7th). Your local time is July 5th at 19:00. Adjusted for US Central Daylight, we add five hours. That yields July 6th at midnight.

If you mean to get July 5th, then I think what you actually want is local time, not UTC. You could call .local() on the moment to get it back to local time.

You may find this helpful: https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/

**Comment by james-hoegerl** [comment]
Thanks very much for your help @maggiepint

**Comment by swetha21** [comment]
Hi, To convert UTC to user time, do we need to provide format.
for example : let utcTime = moment({ hour : 10, minute : 20).format('YYYY-MM-DD HH:mm:ss');
    let stillUtc = moment.utc(utcTime).toDate();
    let localTime = moment(stillUtc).local();
Now i can able to get localTIme. But if i remove format i can still UTC format . here 10:20 is UTC timeZone which is coming from backend. I want to show this to user in user timezone.

Please help me.

**Comment by beebase** [comment]
> Same problem here:
moment().valueOf() and moment().utc().valueOf()
return the same value! 😞
So to get the utc milliseconds I need to:
moment().valueOf() - (moment().utcOffset() * 60 * 1000)

>@rubenspgcavalcante - I'm not sure what you're asking. Those two are supposed to return the same value, both of which are in milliseconds since the unix epoch.

@mj1856  I don't understand how moment().valueOf() and moment().utc().valueOf() are supposed to return the same value ??

**Comment by bearoutthere** [comment]
I must add to the expression of confusion around the UTC functionality.  The most intuitive expectation of moment.utc() would be that it would return a Moment object representing the now date/time in UTC time.  But according to this discussion it's not the case and it just sets the flag.  It still unclear what that flag does.  None of this is mentioned in the documentation, which makes it woefully inadequate.  Please add clarification of this topic with examples to your backlog with a high priority.  Thank you.
