### ISSUE TITLE
fromNow and toNow

### ISSUE THREAD

**Issue by rightaway** [moment/moment#2751]
If I understand this right then one of these `fromNow` and `toNow` functions should be used for dates in the past and the other for dates in the future? Could there be a new function like `relative` or something that determines which to use based on if the date provided is in the past or future? Would simplify the application logic.

**Comment by icambron** [comment]
No, the two functions just express opposite relationships:`fromNow` tells you the *date relative to now* whereas `toNow` tells you how to express *now relative to the date*. IOW, what you're calling `relative` is just `fromNow`:

```js
> moment("2016-05-25").fromNow()
'in 6 months'
> moment("2015-10-14").fromNow()
'a month ago'
```

I suspect `toNow` is rarely used...
