### ISSUE TITLE
How to format a Duration

### ISSUE THREAD

**Issue by nicolabortignon** [moment/moment#2752]
Hello everyone,
I saw this was requested before, but didn't manage to find if since there there are any new solutions.

I have a moment.duration()  and I'd like to format it as  hh:mm:ss. 

Specifically I'd like to use the format() function, so I don't have to take care of padding 0s as well as missing part of the time:

61000ms  -->    01:01   (and not 00:01:01, or 1:1)
59000 ms -->   59

In the past I wrote something like this: 
```
return function(seconds) {
    const hours = Math.floor(this.props.length / (60 * 60));
    const reminderFromHours = this.props.length % (60 * 60);
    const minutes = Math.floor(reminderFromHours / 60);

    const reminderFromMinutes = reminderFromHours % 60;
    const seconds = Math.ceil(reminderFromMinutes);

      // add leading zero and start concatenating the string
    let timeString = (seconds < 10) ? ('0' + seconds) : seconds;
    if (minutes > 0) {
      timeString = ((minutes < 10) ? ('0' + minutes) : minutes) + ':' + timeString;
    }
    if (hours > 0) {
      timeString = hours + ':' + timeString;
    }
    return timeString;
};
```

But as I said, I'd prefer to leverage the built in functions of the library :)

**Comment by icambron** [comment]
Please see discussion at #1048
