### ISSUE TITLE
Handle incomplete locale on initialization

### ISSUE THREAD

**Issue by ichernev** [moment/moment#2754]
Make sure locales have all/none of monthsParse and weekdaysParse, so #2634 doesn't happen again.

**Comment by joelmheim** [comment]
I would like to take a crack at this one. Can you give a bit more description of what is required?

**Comment by joelmheim** [comment]
Is the issue that all locales need to have either no extra parsing of months/weeks or if it implements monthsParse/weekParse, it also need the short/long version of those two as well?

**Comment by joelmheim** [comment]
Working on adding missing tests for strict parsing to all locales. Will submit PR shortly.

**Comment by marwahaha** [comment]
I don't think this is an issue with weekdays, since most files (except br.js) simply have weekdaysParseExact = ...
