### ISSUE TITLE
the spanish translation file is not in UTF-8

### ISSUE THREAD

**Issue by novia713** [moment/moment#2759]

**Comment by icambron** [comment]
Yes it is. Are you sure it's not just that the editor you're looking at in *thinks* it's in some other encoding?

**Comment by novia713** [comment]
well, yes, i double checked it and the file is correct.
seems something weird happened with my webserver and the encoding serving that file :/

sorry for the false alarm

**Comment by icambron** [comment]
NP. One issue is that JS doesn't have a way to specify its encoding in the file, the way, say HTML does. So often to get browsers/servers/whatever to behave, you have specify it explicitly. If you're having trouble with it in a browser, you can use a header on the server or an attribute in the script tag. Here's an example from a similar discussion: https://github.com/moment/moment/issues/1712#issuecomment-48077545

**Comment by novia713** [comment]
nice tip. thanks for it :)
