### ISSUE TITLE
Trigger an error if desired date is out of range

### ISSUE THREAD

**Issue by 9dev** [moment/moment#2760]
It looks like Moment silently falls back to some value instead of triggering an error when we pass a date out of range as an argument. Is there any way of checking if the date is correct?

`isValid()` does not work here - it returns `true` even for dates out of range.

Demo of the problem:
http://jsfiddle.net/8bd0z9jn/

**Comment by icambron** [comment]
I think the only way would be to add explicit bounds to `isValid()`. Specifically, setting the `overflow` flag here: https://github.com/moment/moment/blob/01dee764d512eb77287e67687e75932bb92f6c47/src/lib/create/check-overflow.js#L10. I think we'd accept a PR for that.

**Comment by marwahaha** [comment]
Maybe I'm confused here.

I think what the tokens are doing (i.e. `YYYY`) is capturing the first four digits of the year input. So, if you pass `10000`, it will match as `1000`. Changing the tokens to `YYYYY` or something will fix that. 

What would we change to `isValid()`? @9dev

**Comment by marwahaha** [comment]
Closing due to age and lack of response. Please open if you are still interested in this.
