### ISSUE TITLE
2.10.7

### ISSUE THREAD

**Issue by talgautb** [moment/moment#2761]
When will be 2.10.7 release ?!
we can't wait it, we want to use `kk.js` :)

**Comment by mj1856** [comment]
Moment has no corporate sponsorship and thus no guaranteed release cycle.  We are all volunteers here, and most of us have other day jobs.  @ichernev  does the releases, when he feels its ready and has the time to do it.

If you need something before release - you can always build your own copy.  In the case of a locale, just grab the locale file from source and include it in your project.  No need to wait for a full release.

**Comment by talgautb** [comment]
@mj1856 i certainly understand, thanks for all :+1: 
Just think you have some plans.
