### ISSUE TITLE
Format token to emit hours 01-24 instead of 00-23

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2762]
We can currently *parse* a value with `24` in the hours field, representing midnight at the end of a day.  However, we cannot currently emit such a value when *formatting*.

Parsing was added in #1965
Formatting was discussed recently in #2758

Suggest `k` (1-24) and `kk` (01-24) to match Java and iOS APIs.

Important: This requires some pre-processing, as combination of `hours == 0` and `k` or `kk` being present in the format must subtract a whole day from the output of all other tokens.

Example:

```javascript
moment('2015-12-01T00:00:00').format('YYYY-MM-DD HH:mm') // 2015-12-01 00:00
moment('2015-12-01T00:00:00').format('YYYY-MM-DD kk:mm') // 2015-11-30 24:00
```

**Comment by mj1856** [comment]
Note `k` & `kk` also matches [CLDR/LDML](http://unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table).

**Comment by not-an-aardvark** [comment]
Hello. I've been looking into implementing this, but I'm a bit confused about the expected behavior, specifically when a format string contains both the `HH` and the `kk` tokens.

```js
// (assuming these are being run at midnight on the start of the 6th day of the month)

moment().format('[The day is] DD, [the HH-hour is] HH')
// Expected: 'The day is 06, the HH-hour is 00'

moment().format('[The day is] DD, [the kk-hour is] kk')
// Expected: 'The day is 05, the kk-hour is 24'

moment().format('[The day is] DD, [the HH-hour is] HH, [the kk-hour is] kk')
// Expected: 'The day is __, the HH-hour is 00, the kk-hour is 24'
// Should the day above be 05 or 06?
```

**Comment by maggiepint** [comment]
I think that last scenario just isn't supported. If someone uses kk, then take one day off. There really isn't a good alternative that I can think of.

**Comment by not-an-aardvark** [comment]
Thanks for the clarification.

It might be worth noting that other date-formatting APIs that implement the `kk` token actually don't actually touch the day at all -- they just output the hour and day as-is. ([Example in Java](https://gist.github.com/not-an-aardvark/3bc31a0e357d953fbd91cee8fa7b4590))

Also, use of `24` as an hour is supported for times other than midnight (e.g. 24:59), whereas `moment.format('2016-04-08T24:30')` is invalid with the current parsing behavior.

This is not to say that Moment.js needs to be completely consistent with all other APIs, but people might end up confused if their format string is unexpectedly parsed to a different day.

**Comment by maggiepint** [comment]
@mj1856 why did you want it to take a day off? It's definitely true that Java doesn't do that. From a programmatic standpoint, your code is going to be a lot less crazy if the kk token just +1s the result of the HH token. 
We don't currently really have format tokens that affect other format tokens. That sets a whole precedent that I'm not sure if I like. If it's the right way to do it, then it's the right way to do it. But if, in fact, there is no right way, let's pick the way that messes up the code the least.
Would be happy to hear from @icambron or @ichernev  on this one too.

**Comment by icambron** [comment]
Yeah, I'm with Maggie and NAA here -- let's keep it simple and just format the hours independent of anything else. It doesn't really make a lot of sense to use in combination with dates anyway.
