### ISSUE TITLE
Question : Can moment generate timestamp in format 2015-11-20T03:11:55Z ?

### ISSUE THREAD

**Issue by sasikanthnimmagadda** [moment/moment#2764]
Can moment generate timestamp in format 2015-11-20T03:11:55Z ?

Tried below..

````
console.log(moment.utc().format('YYYY-MM-DDTHH:mm:ss'));
// 2015-11-20T03:11:55	
	
console.log(moment.utc().format('YYYY-MM-DDTHH:mm:ssZ'));
// 2015-11-20T03:11:55+00:00

console.log(moment.utc().format('YYYY-MM-DDTHH:mm:ssz'));
// 2015-11-20T03:11:55UTC

console.log(moment.utc().format('YYYY-MM-DDTHH:mm:sszz'));
// 2015-11-20T03:11:55Coordinated Universal Time

`````

I had to append 'Z' to the string. **Is there any cleaner way supported by moment ?**
`````
console.log(moment.utc().format('YYYY-MM-DDTHH:mm:ss')+'Z');
// 2015-11-20T03:11:55Z    //need this.
`````

Thanks,
Sasi

**Comment by mj1856** [comment]
With the format method, you would switch to UTC mode and add the `Z` as an escaped character `[Z]`.  Technically, the `[T]` should also be like that, but `T` isn't a format specifier so it carries through unchanged.

However, it's much easier just to call `.toISOString()`, which already has the desired output.  You don't need to switch to UTC mode when doing that.

```javascript
console.log(moment().toISOString());  // note that this includes milliseconds
console.log(moment.utc().format('YYYY-MM-DD[T]HH:mm:ss[Z]');
```

**Comment by sasikanthnimmagadda** [comment]
the toISOString() does not help in this case because it has milli seconds.

This formatting helps and makes it clear.. 
```Javascript
console.log(moment.utc().format('YYYY-MM-DD[T]HH:mm:ss[Z]');
```

Thanks,
Sasi
