### ISSUE TITLE
Not working : unless you specify a timezone offset, parsing a string will create a date in the current timezone

### ISSUE THREAD

**Issue by florian-renaut** [moment/moment#2768]
Hello,

On my local computer (timezone +01:00) :

moment("2015-01-01 00:00 +05:00", "YYYY-MM-DD HH:mm Z").endOf("month").diff(moment("2015-01-01 00:00 +05:00", "YYYY-MM-DD HH:mm Z"), "days") = 0

so it seems that the date is automatically converted in my local timezone, documentation says otherwise.

**Comment by mj1856** [comment]
The docs are pretty clear about this.

Use `moment.parseZone` when you want to retain the offset in the input string.
