### ISSUE TITLE
.month() didn't work

### ISSUE THREAD

**Issue by h16bit** [moment/moment#2769]
Hi, i try to set month trough .month() method or by .set('month', 1), but it's didn't make any changes.

**Comment by mj1856** [comment]
`.month(1)`

**Comment by h16bit** [comment]
When i write month() i mean month with digit, so month(1) didn't work for me

**Comment by mj1856** [comment]
![image](https://cloud.githubusercontent.com/assets/1396388/11601935/84f3d5e0-9a8b-11e5-86ea-071d75d72466.png)

Works fine.  Keep in mind that months here are 0-11, so 1 is February.
