### ISSUE TITLE
Allow locale as second argument to moment

### ISSUE THREAD

**Issue by tjcrowder** [moment/moment#2770]
The documentation says you can supply a locale as the _third_ argument to `moment`. It would be really handy to have it supported in the _second_ argument:

```
moment("24/11/2015 00:00:00", 'en-gb');
```

That runs and gives a date, but the date is wrong. In contrast, of course, this throws the deprecation notice about falling back to `Date`, and fails to parse because it's not in U.S. format (on my UK-locale machine, because `Date` always assumes U.S. format when it sees `/`, as you know):

```
moment("24/11/2015 00:00:00",);
```

The request is to allow using the locale as the second, not just third, argument. E.g., to use locale-specific date patterns when parsing.

**Comment by Skintkingle** [comment]
This would be very handy. or at least when Locale is set on the static locale() it should use the given formats for that locale as parsing options before handing off to Dates parse.

**Comment by tjcrowder** [comment]
Skintkingle came up with a workaround in the meantime:
http://stackoverflow.com/a/33895639/157247

**Comment by icambron** [comment]
I understand this request in principle but not in practice: how will Moment know to treat the second argument as a parsing string or as a locale?

**Comment by Skintkingle** [comment]
I would prefer not having to supply the locale when I give it a string to parse. It would make a lot more sense that when parsing a given string it includes the current locales formats as parsing options before falling back to the Date objects default behaviour. Example if I set moment.locale('en-GB'); then when I do moment("24/11/2015 00:00:00") the en-GB format of "DD/MM/YYYY HH:mm:ss" is one of the format options tried (and succeeds, as you can see from my work around on SO)

**Comment by mattgrande** [comment]
Can we allow the second parameter to be an options object? Something like this?

    moment("24/11/2015 00:00:00", { locale: 'en-gb', format: 'LTS' });

**Comment by icambron** [comment]
In general, I'm pro-options-object, but Moment doesn't really use them, so it would be a style departure.

**Comment by Skintkingle** [comment]
Then using the locale formats as parsing options is more sensible instead of having to pass anything specifically in at the time of the parse?

**Comment by icambron** [comment]
> Then using the locale formats as parsing options is more sensible instead of having to pass anything specifically in at the time of the parse

I like that idea, though I'm a little scared of it as a breaking change.

Would it suffice if you could pass `null` or `undefined` as the second arg and leave the rest as is?

**Comment by marwahaha** [comment]
Closing due to age. Options objects are cool, but I don't think we will implement this anytime soon.

Please re-open if there are still questions.
