### ISSUE TITLE
Function to() not return the total of days after 25 days

### ISSUE THREAD

**Issue by flpms** [moment/moment#2771]
I'm using to function, and I founded the follow bug. Follow code and results tested at console in 
Chrome.

 ```javascript
var init = moment("2015-09-13T00:00:00.000-03:00");
var end = moment("2015-10-08T00:00:00.000-03:00");
init.to(end, true); //result 25 days
````

But when type 9 as day the result will be a month.

````javascript
var init = moment("2015-09-13T00:00:00.000-03:00");
var end = moment("2015-10-09T00:00:00.000-03:00");

init.to(end, true); //result a month
`````

And a suggestion is a option to return return month and day combined to precision on date range.

**Comment by rheh** [comment]
I believe this is the intend result as the "to" function returns an interval.  From the manual the examples given are:

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Range</th>
      <th>Key</th>
      <th>Sample Output</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0 to 45 seconds</td>
      <td>s</td>
      <td>in seconds</td>
    </tr>
    <tr>
      <td>45 to 90 seconds</td>
      <td>m</td>
      <td>in a minute</td>
    </tr>
    <tr>
      <td>90 seconds to 45 minutes</td>
      <td>mm</td>
      <td>in 2 minutes ... in 45 minutes</td>
    </tr>
    <tr>
      <td>45 to 90 minutes</td>
      <td>h</td>
      <td>in an hour</td>
    </tr>
    <tr>
      <td>90 minutes to 22 hours </td>
      <td>hh</td>
      <td>in 2 hours ... in 22 hours</td>
    </tr>
    <tr>
      <td>22 to 36 hours</td>
      <td>d</td>
      <td>in a day</td>
    </tr>
    <tr>
      <td>36 hours to 25 days</td>
      <td>dd</td>
      <td>in 2 days ... in 25 days</td>
    </tr>
    <tr>
      <td>25 to 45 days</td>
      <td>M</td>
      <td>in a month</td>
    </tr>
    <tr>
      <td>45 to 345 days</td>
      <td>MM</td>
      <td>in 2 months ... in 11 months</td>
    </tr>
    <tr>
      <td>345 to 547 days (1.5 years)</td>
      <td>y</td>
      <td>in a year</td>
    </tr>
    <tr>
      <td>548 days+</td>
      <td>yy</td>
      <td>in 2 years ... in 20 years</td>
    </tr>
  </tbody>
</table>

**Comment by icambron** [comment]
Yes, it's very hard to please everyone with this and of course the cutoffs are a little arbitrary. But you can customize them: http://momentjs.com/docs/#/customization/relative-time-threshold/.

> And a suggestion is a option to return return month and day combined to precision on date range.

That opens a big can of worms (e.g. not all months are the same length, etc). Best to think of this a something useful and abbreviated to show your users. If you want precision, go with duration functions like `moment.duration(moment.diff(otherMoment))`.
