### ISSUE TITLE
isoWeeksInMonth and isoMonthStartWeek

### ISSUE THREAD

**Issue by iandevlin** [moment/moment#2772]
I would like to request the addition of the folllowing functions:

`isoWeeksInMonth(month)` which would return the number of weeks in a month.

`isoMonthStartWeek(month)` which would return the week number that the requested month starts in.

**Comment by icambron** [comment]
On the first one, do you mean number of full weeks or number of weeks that make an appearance? I'm thinking the latter. Could you explain a little more about why these functions would be useful?

**Comment by iandevlin** [comment]
I would say the full number of weeks, although perhaps a boolean could be passed in to allow configuration.

Getting the number of weeks in a month is useful for building a calendar week by week, for looping purposes, or the method could return all the days for a particular month on a per week basis. This would allow a developer to label each week correctly.

As for the second method, I had a use case in mind but I have completely forgotten what is was, which probably points at it not being needed.

**Comment by marwahaha** [comment]
Thanks for opening this request.
For now, we will not take this change.
Please re-open if you still have concerns.
