### ISSUE TITLE
Milliseconds are not parsed correctly

### ISSUE THREAD

**Issue by jochenberger** [moment/moment#2775]
This affects 2.10.6.
`moment("2000-01-01T00:00:00.12Z", 'YYYY-mm-DDTHH:mm:ss.SZ')` is parsed as ` 2000-01-01T00:00:00.120Z`, but should be ` 2000-01-01T00:00:00.012Z` (12 milliseconds, not 120).
Same result for `'YYYY-mm-DDTHH:mm:ss.SSZ'` and `'YYYY-mm-DDTHH:mm:ss.SSSZ'`.
`"2000-01-01T00:00:00.012Z"` is parsed correctly.

**Comment by mj1856** [comment]
Milliseconds are 1/1000 of a second.  0.12 seconds is 120 milliseconds, not 12 milliseconds.

We follow standard decimal math and support fractional seconds in the same manner as covered by ISO8601 and RFC3339.

(Additionally, note that your format string is incorrectly using `mm` for months, it should use `MM`.)

Thanks.

**Comment by mj1856** [comment]
Also note that in the documentation it is clear that `S` represents tenths, `SS` is hundredths, and `SSS` is thousandths.

**Comment by jochenberger** [comment]
Okay, thanks. Maybe the documentation should emphasize that Moment.js handles `S` different than Java's `SimpleDateFormat` and encourage people to use `SSS` on both ends.

**Comment by mj1856** [comment]
It's not the format that is wrong, it's the data.  Even if you use `SSS`, `.12` is still 120 milliseconds, not 12.  The interpretation is compliant with ISO8601.

The number of `S` characters doesn't really have any effect on parsing.  It only matters when *formatting*.  I supposed the docs should reflect that.

In general though, don't expect that moment's parsing tokens are aligned with any particular language.  Java developers may have one set of expectations, .NET developers will have another, PHP will have another, etc.  Always look at the list of tokens in the docs.

**Comment by mj1856** [comment]
I made a couple of changes to the docs.  See moment/momentjs.com#247
