### ISSUE TITLE
Feature Request: fuzzy time formatting

### ISSUE THREAD

**Issue by sluedecke** [moment/moment#2780]
I am using the fuzzy clock KDE provides on Linux and it nicely formats the time in a less accurate way, for example

* Five to nine
* Twenty-five to two
* Half past six
* Noon
* Middle of the week

depending on the configured level of fuzziness.  I'd love to use it in the Atom editor (see https://github.com/b3by/atom-clock/issues/5#event-472791628), but somehow it appears to be a suitable feature request for moment.

There already is an implementation in C++ which includes a lot of locale definitions (MIT licensed):

https://github.com/m66n/fuzzyclock

So if it is not too much work and a considered a useful feature, please implement it.

**Comment by mj1856** [comment]
This might be useful to some, but IMHO it would be better implemented as a plugin, rather than a core feature.  

If you (or someone else) care to author it, we can list it at http://momentjs.com/docs/#/plugins/

Thanks.
