### ISSUE TITLE
isSame behaves differently with null and undefined

### ISSUE THREAD

**Issue by MattKunze** [moment/moment#2783]
```javascript
moment().isSame(null, 'year') // -> false
moment().isSame(undefined, 'year') // -> true
```

The latter case seems wrong to me, I would expect false for both. Seems to behave the same for any unit.

**Comment by mshwery** [comment]
I think this is because the underlying methods used behave the same as when you do `moment(undefined)` vs `moment(null)`. Null produces an invalid date object, while undefined is no different than doing `moment()` which produces the current datetime wrapped as a moment object.

**Comment by MattKunze** [comment]
I guess that makes sense, it just leads to unexpected behavior in cases where you have a parameter being passed to a function and it gets coerced to "now" in these cases. I guess I'll just add an explicit check

**Comment by mshwery** [comment]
@MattKunze I agree that these comparator methods shouldn't have this hidden gotcha.

**Comment by MattKunze** [comment]
Maybe I'll take a quick peek at some point and try to put together a PR, looking at the source it doesn't seem terribly difficult. Perhaps just defaulting the input value to `null` in cases where the default coercion is undesired would work.

I guess the question would be coming up with the list of functions where `undefined` should be explicitly handled as input

**Comment by jabadia** [comment]
I was bitten by this as well: m.isSame(x,'day') returned true for x===undefined... spent some time finding the issue in my code
