### ISSUE TITLE
utcOffset < 16

### ISSUE THREAD

**Issue by manveru** [moment/moment#2784]
There seems to be no official way to set UTC offsets smaller than ±16.
I'm setting `_offset` myself now as a workaround hack for that case, and I realize that doing it via Integers to `utcOffset` would break backwards compatibility.

How about removing the < 16 check when a string is in the "+00:05" format? I could write a PR for that if there's interest.

**Comment by mj1856** [comment]
Yeah, that's a bug:

```javascript
moment().utcOffset("-00:16").format("Z")  // "-00:16"
moment().utcOffset("-00:15").format("Z")  // "-15:00"  // should be "-00:15"
moment().utcOffset("+00:15").format("Z")  // "+15:00"  // should be "+00:15"
moment().utcOffset("+00:16").format("Z")  // "+00:16"
```

In string format, it should not use the < 16 logic.  That's only for numeric format so one can pass the offset in terms of either hours or minutes, as in:

```javascript
moment().utcOffset(-8).format("Z") // "-08:00"
moment().utcOffset(-480).format("Z") // "-08:00"
moment().utcOffset(5.5).format("Z") // "+05:30"
moment().utcOffset(330).format("Z") // "+05:30"
```

A PR would be welcome.  Please include unit tests.

**Comment by mj1856** [comment]
Close in favor of PR #2786
