### ISSUE TITLE
72 tests failed on half hour timezone

### ISSUE THREAD

**Issue by sushantdhiman** [moment/moment#2787]
Tests fails on half hour offset based timezone like +5:30 (IST).

```
Module: create Test: parsing iso
moment should be able to parse specified ISO 2011281 180420+05 with +0530
    at Object.<anonymous> (/var/www/html/github/moment/build/umd/test/moment/create.js:636:20)
Actual value:
2011-10-08T18:34:20.000+05:30
Expected value:
2011-10-08T18:04:20.000+05:30

Module: create Test: parsing iso
moment should be able to parse specified strict ISO 2011281 180420+05 with +05
    at Object.<anonymous> (/var/www/html/github/moment/build/umd/test/moment/create.js:638:20)
Actual value:
2011-10-08T18:34:20.000+05:30
Expected value:
2011-10-08T18:04:20.000+05:30
```
I can trace it back to this test in [src/tests/moment/create.js](https://github.com/moment/moment/blob/develop/src/test/moment/create.js#L416)

Moment always converts to correct +5:30 based offset in all cases but test value to compare with are incorrect. 

For instance when asked to convert ``ISO 2011281 180420+05`` 

```
Actual Value: 
2011-10-08T18:34:20.000+05:30
(OK)
```
```
Expected value:
2011-10-08T18:04:20.000+05:30
(Not OK)
(It should be compared with +5 => UTC => +5:30)
(But test compares it with +5 => UTC => +5)
```

**Comment by icambron** [comment]
Yeah, it's unfortunate that the tests always fail like that in India and other 30-mins-off offsets. We would definitely merge a fix for that.

**Comment by sushantdhiman** [comment]
Confirmed the fix. Thanks for fixing that @SwamWithTurtles .

I was really hoping to start contributing to this library and now I really can :)
