### ISSUE TITLE
Days Diff Returning Floats

### ISSUE THREAD

**Issue by chrisrng** [moment/moment#2790]
```
var today = moment("2015-12-24T17:45:00");
var tomorrow = moment("2015-12-25T05:21:00");

today.diff(tomorrow, "days") // -0
today.diff(tomorrow, "days", true) // -0.48333333333333334
```

I don't think it makes sense to have a result of negative zero. I do understand that without the third argument the value gets rounded but in the case of days difference it's not intuitive that we would get floating point numbers.

**Comment by icambron** [comment]
I don't understand what you'd expect an unrounded number to return. The whole point of the argument is to allow you to get fractional units. What do you expect here?

As for `-0`, that's a funny JS thing, but you can just treat it as 0. See [here](http://stackoverflow.com/questions/7223359/are-0-and-0-the-same) for a full explanation. I believe we're correct to return it. Why do you think it doesn't make sense?

**Comment by chrisrng** [comment]
You've got a point in the second argument (returning fractional units), my bad. But...I was expecting the first line `today.diff(tomorrow, "days") // -0` to return `1` as it has changed a day. Or is there another way to do this intuitively? I don't see why today diff tomorrow would not be 1 when counting "days"

**Comment by icambron** [comment]
Diff is returning differences in time as expressed in the unit specified; it doesn't pay any attention to how those units are aligned with the calendar. The best way I can think of to what you're looking for is to just align the times to the calendar yourself:

```js
today.startOf('day').diff(tomorrow.startOf('day'), "days") //=> -1
```
