### ISSUE TITLE
3 tests failed. create:string with format - years (2104.4) week day:weekday first day of week Sunday (dow 0) (2449.5) weeks:count years with iso week 53 (2472.1) 

### ISSUE THREAD

**Issue by pmarki** [moment/moment#2793]
### Client info

```
Date String   : Sat Dec 05 2015 12:53:42 GMT+0000 (GMT)
Locale String : 05/12/2015, 12:53:42
Offset        : -60
User Agent    : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0
```
# 
### create:string with format - years (2104.4)

70 > 1970

``` javascript
// Expected 1970
// Actual   1969
"1969" === "1970"
```
# 
### week day:weekday first day of week Sunday (dow 0) (2449.5)

Jan  1 1970 is Thursday  -- 4th day

``` javascript
// Expected 4
// Actual   3
3 === 4
```
# 
### weeks:count years with iso week 53 (2472.1)

Should have 71 years in 400-year cycle with iso week 53

``` javascript
// Expected 71
// Actual   110
110 === 71
```

**Comment by marwahaha** [comment]
@pmarki - have you had any problems since?

You can try at http://momentjs.com/tests/

**Comment by marwahaha** [comment]
Closing due to age.
