### ISSUE TITLE
moment.duration can't parse weeks and days simultaneously

### ISSUE THREAD

**Issue by Vladimir-Purple** [moment/moment#2797]
Hi. I was trying to parse YouTube video duration which is 500+ hours long, however, moment gave me wrong value.
For string ```"P3W3DT20H31M21S"```, moment gave me result of:
```
_data: {days: 0, hours: 0, milliseconds: 0, minutes: 0, months: 0, seconds: 0, years: 0}
```

Is weeks supported by moment?
Thanks.

**Comment by JohnAnthony** [comment]
It looks like you're trying to create a duration using an ISO 8601 string (as mentioned at the bottom of http://momentjs.com/docs/#/durations/creating/), but I can't see weeks as a part of the standard (https://en.wikipedia.org/wiki/ISO_8601#Time_intervals).

**Comment by mj1856** [comment]
It looks like there is indeed a bug here:

```javascript
moment.duration("P3W").asDays() // 21
moment.duration("P3D").asDays() // 3
moment.duration("P3W3D").asDays() // 0  - should be 24
```

Combining weeks and days doesn't work.  This needs to be fixed, and needs a unit test.

**Comment by JohnAnthony** [comment]
I'd be happy to take this one on.

A quick look shows that the ISO-8061 regex on line 13 of a47bc4ea7f5951e9129e8bee9de0388ac0a13e72 isn't matching "P3W3D", so it isn't being recognised as an ISO-8061 string.

**Comment by mj1856** [comment]
Closing in favor of PR #2818.  Thanks!
