### ISSUE TITLE
Add setting for hooks.parseTwoDigitYear

### ISSUE THREAD

**Issue by VitaliyZheleznov** [moment/moment#2798]
Hi,

We make a service, where users can enter date in different formats.
But As I find out when moment parse date with 2 digit year, it's choosing 19YY year if YY > 68.

It will be great, if we can configure this. May be override hooks.parseTwoDigitYear function.
For example: if we work with date of birth, it should be always less then current date (55 = 1955 in this case)

**Comment by mj1856** [comment]
Yes, you can simply replace the `moment.parseTwoDigitYear` function with whatever you like.

This is actually in the docs:

> Parsing two digit years
>
>By default, two digit years above 68 are assumed to be in the 1900's and years 68 or below are assumed to be in the 2000's. This can be changed by replacing the `moment.parseTwoDigitYear` method.
