### ISSUE TITLE
Checkmarx Issue - Divide by Zero

### ISSUE THREAD

**Issue by callmekatootie** [moment/moment#2803]
Hello,

We are using momentjs in our application (with data) and we ran [Checkmarx](https://www.checkmarx.com/) against it. It returned a security issue with the minified script:

Issue Type: Divide by Zero
Code in question: `a[b - 1] = 1 / 0`

Note that this is in the minified version - the actual source code makes use of `Infinity` instead of dividing by zero.

We just wish to check if this is a valid issue or a false positive.

**Comment by ichernev** [comment]
I don't find any usage of `Infinity` in our code, I also fail to find `1 / 0` in the minified code. Even if there is `Infinity` in our code, I don't see how this is a security issue. Also, if `1/0` is something coming from `Infinity` by the minifier its the minifier to blame, not us.

**Comment by callmekatootie** [comment]
Yes, sorry. I notice that I created the issue in the wrong repository. This should be in the moment-timezone repo. Sorry about that. Closing ticket.
