### ISSUE TITLE
Error in formatting moment

### ISSUE THREAD

**Issue by debopamsengupta** [moment/moment#2805]
I have a moment object  ```a```
![image](https://cloud.githubusercontent.com/assets/9649659/11651482/fc4d9d7c-9dcb-11e5-904a-9b3856200de4.png)

On calling ```a.format('YYYYMMDD')``` , I get this 

```TypeError","stack":"TypeError: this.localeData(...).postformat is not a function```

**Comment by icambron** [comment]
Can you provide a JSFiddle that shows this issue?

**Comment by debopamsengupta** [comment]
Been a while now and haven't been able to recreate it. Thanks though.

**Comment by skolsuper** [comment]
+1 :(

**Comment by christopherbalz** [comment]
+1

**Comment by christopherbalz** [comment]
My issue turned out to be the result of using a non-Moment clone on the Moment object.  Using `Moment.clone()` fixed it.

**Comment by kecskesadam** [comment]
@nottoseethesun I'm having the same issue. Can you pls share a bit more info about how you fixed it?

**Comment by rockneverdies55** [comment]
In my case, setting the locale by `.locale('en')` call has fixed the problem.
