### ISSUE TITLE
Google Chrome search page

### ISSUE THREAD

**Issue by pcnate** [moment/moment#2806]
Searching the page for text works, but something is updating the content and breaking the highlighting. Only happens on this site.

Steps to reproduce:
1. Press <kbd>CTRL</kbd>+<kbd>F</kbd>
2. Type any text such as .format
3. Wait a few seconds for the highlighting to disappear

First second after searching:
![image](https://cloud.githubusercontent.com/assets/621940/11728237/56140336-9f4e-11e5-8c25-126129edc2ac.png)

A few moments later:
![image](https://cloud.githubusercontent.com/assets/621940/11728268/7eb3b5a2-9f4e-11e5-89f9-820f5fa88cbc.png)

**Comment by ichernev** [comment]
Well, the text on the right side changes every second, so yes, it is updating the content. Its a feature. This is not happening on the docs page, which is where you might want to search.
