### ISSUE TITLE
Day marker character is missing for Japanese

### ISSUE THREAD

**Issue by XueWei** [moment/moment#2807]
For Japanese: moment().format('MMMM Do YYYY, h:mm:ss a'); // // 12月 10 2015, 4:58:09 午後
It miss "日" after 10. It expect to 12月 10日 2015, 4:58:09 午後.

Japanese date format should be 
“The most commonly used date format in Japan is "year month day (weekday)", with the Japanese characters meaning "year", "month" and "day" inserted after the numerals. 
Example: 2008年12月31日 (水) for "Wednesday, December 31, 2008". “
FYI: https://en.wikipedia.org/wiki/Date_and_time_notation_in_Japan

Btw, For S,Chinese, T Chinese, Korean, they all include day marker character with moment().format('MMMM Do YYYY, h:mm:ss a');

**Comment by icambron** [comment]
@baryon - any thoughts on this?

**Comment by baryon** [comment]
XueWei is Right. any patch?

**Comment by icambron** [comment]
Not yet, but we'd accept one (from @XueWei or anyone else), now that you've said it's OK.

**Comment by XueWei** [comment]
OK. I'll try to give a patch.

**Comment by XueWei** [comment]
I commit patch pull request. Please review and merge it.

**Comment by Oire** [comment]
This issue can be closed via #2829.

**Comment by mj1856** [comment]
Thanks, we'll track it there.
