### ISSUE TITLE
duration format fails for YouTube's duration output

### ISSUE THREAD

**Issue by vBm** [moment/moment#2811]
Checking via `https://developers.google.com/youtube/v3/docs/videos/list` and using `contentDetails` for `part` section and `04cF1m6Jxu8` as `id` for longest video on youtube we get this output:

```json
{
 "kind": "youtube#videoListResponse",
 "etag": "\"3WIcRE7IJ70nCYemJJIi1L7dYAg/o7GK6h95_J4cZbzd-eZOVGC9ZAM\"",
 "pageInfo": {
  "totalResults": 1,
  "resultsPerPage": 1
 },
 "items": [
  {
   "kind": "youtube#video",
   "etag": "\"3WIcRE7IJ70nCYemJJIi1L7dYAg/iIaJv70njXPPGD1Q-3NFr8AXvUk\"",
   "id": "04cF1m6Jxu8",
   "contentDetails": {
    "duration": "P3W3DT20H31M21S",
    "dimension": "2d",
    "definition": "sd",
    "caption": "false",
    "licensedContent": false
   }
  }
 ]
}
```

`duration` value is `P3W3DT20H31M21S` which when parsed by `moment.duration(duration).format()` always returns `0`.

Shouldn't this be supported since it seems like a valid [ISO 8601#Duration](https://en.wikipedia.org/wiki/ISO_8601#Durations)

**Comment by mj1856** [comment]
Dup #2797

**Comment by vBm** [comment]
Even thou I've tried searching for existing bug, I have failed to see it. I'm sorry. Thanks for flagging as dupe and confirming in other ticket :)

**Comment by mj1856** [comment]
No problem. Just want to track it in one place.  Thanks!
