### ISSUE TITLE
use moment.js in angular and require.js but get a "moment is not defined" error

### ISSUE THREAD

**Issue by anotherten** [moment/moment#2813]
first I define path in require:

```js
require.config({
       paths: {
          'moment':'js/moment/2.10.6/moment'
       }
})
```

then
 
```js
define(['moment'],function(moment){
......
})
```

when I use moment in my angular js code 

```js
eventData = {
    		id:data[i].eId,
		title: data[i].name,
		start: new moment(data[i].startDate),
		end: new moment(data[i].endDate)
}
```

but the chrome give me a "ReferenceError: moment is not defined"
what's wrong with my code?

**Comment by icambron** [comment]
I'm not sure, but I'd be very surprised if `require` is broken in general for moment. It sounds like maybe require can't find Moment at that path?

**Comment by maggiepint** [comment]
Closing since this issue hasn't had activity in a long time. We're more than happy to help you if you wish to re-open it.
