### ISSUE TITLE
Format ddd gives wrong day of week

### ISSUE THREAD

**Issue by hollyrobson** [moment/moment#2817]
Using ddd gives the wrong day of the week ( by + 1 ). 

The formatting using dd or dddd works fine so it's just an issue with the abbreviation of 3 letters!

e.g. 
var date = "2015-12-15"
var formattedDate = moment(date, "YYYY-MM-DD").format('ddd D MMM');
console.log( formattedDate );

Expected output:
Tue 15 Dec

Actual output:
Wed 15 Dec

**Comment by mj1856** [comment]
Is this the current version of moment, or an old one?

**Comment by hollyrobson** [comment]
Hi,

We are using version 2.10.6.

Thanks,
Holly

**Comment by hollyrobson** [comment]
This is the statement:

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js" type="text/javascript">

From: Holly Robson <hrobson@andigital.com<mailto:hrobson@andigital.com>>
Date: Tuesday, 15 December 2015 at 14:59
To: moment/moment <reply@reply.github.com<mailto:reply@reply.github.com>>, moment/moment <moment@noreply.github.com<mailto:moment@noreply.github.com>>
Subject: Re: [moment] Format ddd gives wrong day of week (#2817)

Hi,

We are using version 2.10.6.

Thanks,
Holly

**Comment by mj1856** [comment]
I can't reproduce the problem you describe

![image](https://cloud.githubusercontent.com/assets/1396388/11816535/aea57b78-a305-11e5-8168-d2d88dbbe3ec.png)

Could you give the output of `navigator.appVersion`, double check `moment.version == "2.10.6"` and also tell me what the time zone setting of your computer is?  Thanks.

**Comment by hollyrobson** [comment]
Hi,

Here is my output:
[cid:04904C5C-6A15-4897-85F1-A3F342690B61]
My time zone is set to GMT London.

This is on https://www.hubhotels.co.uk.

[cid:FE2E44EB-60FE-46EE-8784-B4F65705AE95]

I have just checked and when running on another project I do not get this problem so I guess there must be some setup issue in our project. I find it strange how there is no issue with the 2 char format or the full day name format.

Is this a problem on our side or your side?

Many thanks,
Holly Robson
Product Developer AND Scuba Diver
m: 07411 835653 | t: 0207 484 5049 | hrobson@andigital.com<mailto:hrobson@andigital.com>
ANDigital<http://www.andigital.com/> | Golden Cross House, 8 Duncannon St, London, WC2N 4JF

[http://andigital.com/wp-content/themes/ANDigital/img/header/red/logo.png]

We’re hiring! Click here to find out about our hot jobs!<https://andigital.com/join-us/>

[cid:FDB67C64-D06A-46AF-B7E0-7EB048307FD4]<https://www.linkedin.com/company/andigital> [cid:1CC5E240-5EB8-4657-81C7-5E01E2822C21] <https://twitter.com/andigital>  [cid:0569E0AA-7D52-41DA-B7B3-DCA432CED7A9] <https://www.facebook.com/andigital>

**Comment by mj1856** [comment]
Sorry, but that didn't come through, or if it did, I'm not sure what that cid guid is referring to.  Could you update via GitHub instead of email?  Thanks.

**Comment by bcw104** [comment]
hi @hollyrobson , Have you use https://sensortower.github.io/daterangepicker and set the firstDayOfWeek to 1 ?

**Comment by mj1856** [comment]
Closing due to no response.  If you still need help, let us know and I'll re-open.
