### ISSUE TITLE
Adding time to an invalid moment and then comparing it using .after causing weird behavior

### ISSUE THREAD

**Issue by evansiroky** [moment/moment#2819]
See fiddle:  http://jsfiddle.net/8jb95uhs/

This code produces interesting results:

    var d =  moment('abcd', 'YYYY-MM-DD HH:mm:ss')
    console.log(d.isAfter(moment()))  // false
    console.log(d.add(50, 'minutes').isAfter(moment()))  // true!?

I only observed this around a change of day though (midnight), so the behavior might not be consistent.

**Comment by icambron** [comment]
Right, even though Moment knows that the date is invalid (e.g. `isValid()` returns false), it still internally ends up with a date and uses it in those comparisons. In your case, that secret date was such that adding 50 minutes to it made it after now. I think we'd accept a PR that guards `isAfter` and `isBefore` with an `isValid` check.

**Comment by sushantdhiman** [comment]
This issue is already fixed in develop branch. `isValid` checks are [on this line](https://github.com/moment/moment/blob/develop/src/lib/moment/compare.js#L8). Fiddle used `2.10.6` which doesn't have this fix.

**Comment by icambron** [comment]
Ah, cool. Going to close this then.
