### ISSUE TITLE
Moment Fails to specify week when advancing over year

### ISSUE THREAD

**Issue by MichaelFBA** [moment/moment#2820]
Imagine the date is a proper date object
moment('Fri Jan 01 2016 12:00:00 GMT+0100 (CET)').add(2, 'days').format('YYYY-WW');

This outputs `2016-53` when it should be `2016-01`

**Comment by alburthoffman** [comment]
Yeah，I also got this in my chrome browser. It's truly a bug.

**Comment by alburthoffman** [comment]
After some investigation, 53 might be the right week, but 2016 is wrong. 
Please refer to https://en.wikipedia.org/wiki/ISO_week_date#First_week

**Comment by icambron** [comment]
Not a bug. There are two issues here:

 1. Like @adambrunner points out, it really is ISO week 53, but of the 2015 week year
  2. But you're not asking for the week year with YYYY; you're asking for the calendar year, which is 2016. The formatter is pretty literal.

If you want the ISO week year year, you need to tell the parer that. Use "GGGG-WW":

```js
> moment('Fri Jan 01 2016 12:00:00 GMT+0100 (CET)').add(2, 'days').format('GGGG-WW');
"2015-53"
```

If the ISO stuff isn't what you want, check out "gggg" and "ww":

```js
> moment('Fri Jan 01 2016 12:00:00 GMT+0100 (CET)').add(2, 'days').format('gggg-ww');
"2016-02"
```

Neither give you week 1 (the local one thinks the week starts on Sunday unless you set the locale, so it's the start of the second week, and the ISO one is a standard that's not up to us)
