### ISSUE TITLE
Inconsistencies/docs missing between format() and toISOString()

### ISSUE THREAD

**Issue by cyberwombat** [moment/moment#2821]
The 2 top answers and comment on this [SO post](http://stackoverflow.com/questions/25725019/how-do-i-format-a-date-as-iso-8601-in-moment-js/28641878#28641878) illustrate this minor issue:

Basically `format()` outputs in local time without milliseconds and `toISOString` converts to UTC and outputs milliseconds. The docs seem to indicate they are equivalent. Perhaps a note should be added to clarify that `toISOString` will convert to UTC or better yet, maintain the timezone and also make both formats use/not use milliseconds.

**Comment by icambron** [comment]
Agree about the docs. See also #1751

**Comment by mj1856** [comment]
I don't recommend changing the behavior, as that would be a breaking change for many folks.  We can clarify in the docs though.

**Comment by mahalingaiahhr** [comment]
Im new here. I would like to contribute. Please let me know if I allowed to open PR here.

**Comment by butterflyhug** [comment]
@mahalingaiahhr Welcome!  Yes, we're always interested in having folks contribute PRs to fix documentation issues like this.  Note that our docs are in the [moment/momentjs.com](https://github.com/moment/momentjs.com) repository.

**Comment by sameer1994** [comment]
cdff

**Comment by sameer1994** [comment]
Hello, I want to contribute to this, Do I just go to this [link](http://momentjs.com/docs/#/displaying/as-iso-string/) and click edit and modify and submit a pull request. I want to add that toISOString outputs milliseconds too by default.

Sorry for the noob question :)
