### ISSUE TITLE
Moment no longer exporting global when require.js is present

### ISSUE THREAD

**Issue by jimsimon-cengage** [moment/moment#2831]
As of version 2.10.0, the moment global is no longer available if a module system is detected.  This was previously working in 2.9.0.  This is causing a headache for us as we have newer code written with Polymer that is HTML Importing moment, and we're integrating it with older code written with require.js.  Moment detects require.js and doesn't add the global, which causes our elements to fail at runtime.  Our tests and demo pages still work because they do not have require.js present, and the Polymer elements themselves don't need require.js to function.

Fiddle is below, but please note that it appears to be freezing for a short period before dumping out to the console.  You'll ultimately get "moment is not defined" error and a "Mismatched anonymous define() module" error from require.js.
Fiddle: https://jsfiddle.net/f5xu1cho/1/

**Comment by mj1856** [comment]
Marking as bug, but I think it may have been intentional.  Need to explorer further.

**Comment by icambron** [comment]
This was definitely on purpose. Here's where we deprecated require-but-also-globals https://github.com/moment/moment/pull/1220/files. This is one of those damned-if-we-do-damned-if-we-don't things. Some things break in requirejs environments if we do export it (which is why we provided a `noGlobal` in that patch), and mixed environments break if we don't.

**Comment by mj1856** [comment]
Since this was intentional, I'm marking it as "troubleshooting" instead of "bug".  Perhaps someone can offer a workaround.

**Comment by maggiepint** [comment]
The require team kindly explained what to do in this situation with requirejs/requirejs#1554 so I'm closing this.
