### ISSUE TITLE
Use a different end-of-day value than midnight for relative date strings

### ISSUE THREAD

**Issue by dorshay6** [moment/moment#2832]
Hii,

I have an app that works in the nightlife industry, in order to make saneness at night we time shift and consider 00:00 until 06:00 as the day before so that a party on sunday night will be showen as 'today' even after midnight.

There is an option to work with moment.js and configure it to time shift the days only?

**Comment by mj1856** [comment]
We don't have this feature, but it's not a bad idea.  At least when it comes to the way that relative dates are displayed.  Though perhaps it should say "tonight" instead of "today".

**Comment by ichernev** [comment]
You can special case past dates. If it's same night you display tonight, otherwise you say its past event (or even use moments description, but if the party is over who cares was it yesterday or 3 days ago)

**Comment by AmitMY** [comment]
Did you perhaps find a workaround for this? I need the same thing, saying like "Tonight at 1am"

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
