### ISSUE TITLE
moment().year(2015).week(52)  ==    year 2016, week 52

### ISSUE THREAD

**Issue by FallenMax** [moment/moment#2834]
```javascript

var date = moment().year(2015).week(52)

console.log("year:", date.year())   // = 2016
console.log("week:", date.week()) // = 52

```
pen: http://codepen.io/anon/pen/wMzQgv

Is this a problem or I misunderstood something?

**Comment by lespacedunmatin** [comment]
I’m strugling right now with that. 

See thoses
```javascript
console.log(moment("12-29-2015", "MM-DD-YYYY").format('LLLL')); // Tuesday, December 29, 2015 12:00 AM
console.log(moment("12-29-2015", "MM-DD-YYYY").week()); // 1
console.log(moment("12-29-2015", "MM-DD-YYYY").isoWeek()); // 53
console.log(moment("12-29-2015", "MM-DD-YYYY").year(2015).format('LLLL')); //Tuesday, December 29, 2015 12:00 AM
console.log(moment("12-29-2015", "MM-DD-YYYY").year(2015).week(52).format('LLLL')); // Tuesday, December 20, 2016 12:00 AM
console.log(moment("12-29-2015", "MM-DD-YYYY").year(2015).isoWeek(52).format('LLLL')); // Tuesday, December 22, 2015 12:00 AM
```

Interestingly, US and ISO norms differ for weeknumber in 2016, starting now.
So 12-29-2015 is in Week 1 of year 2016. You jump to week 52. Of year 2016.
And 12-29-2015 is in isoWeek 53 of year 2015. You jump to isoWeek 52. Of year 2015.

**Comment by lespacedunmatin** [comment]
Oh, and your issue will happen only this week. Last week, that wasn’t an issue yet, and next week it will not be an issue anymore.

**Comment by FallenMax** [comment]
@lespacedunmatin Yes, I noticed this issue only as my web app broke last week (it runs with no problem before). 
I replaced  `.week()` / `.year()`  with `.isoWeek()` / `.isoWeekYear()`, it seems that fixed the problem for now (though still not sure what the problem is).

**Comment by lespacedunmatin** [comment]
Oh, isoWeekYear ! Thanks, missed that :-)

**Comment by FallenMax** [comment]
@lespacedunmatin No problem :) You might want to look into docs a bit as they are semantically different from week/year, and that might cause trouble for existing data.

**Comment by lespacedunmatin** [comment]
Yes. But docs lacks examples that would explain such differences.

**Comment by FallenMax** [comment]
update: as @lespacedunmatin mentioned, the original test no longer produce `year 2016, week 52` if run on this week (today is 2016-01-03T23:47:51+08:00).

To reproduce this problem, I changed first `moment()` to `moment('2015-12-27')`, and issue still exist:

pen: http://codepen.io/anon/pen/wMzQgv

**Comment by FallenMax** [comment]
See #2853 which is clarified by @icambron ,  `week` only make sense with `weekYear` (instead of `year`).
