### ISSUE TITLE
Maybe try to parseInt the parameter when it's in ms

### ISSUE THREAD

**Issue by dban0001** [moment/moment#2836]
I spent 10 minutes about find out what was wrong with my code:

    <script>
    var variableFromAjaxCall; // this variable is "1451234747583"
    var time = moment(variableFromAjaxCall);
    </script>

This gave me a warning pointing to this thread https://github.com/moment/moment/issues/1407. 
The solution was simply parsing an int from variableFromAjaxCall:

    <script>
    var variableFromAjaxCall;
    var time = moment(parseInt(variableFromAjaxCall));
    </script>

Would it be possible if this could be done automatically, when the parameter is something like the time in ms (1451234747583)?

**Comment by mj1856** [comment]
Sorry, but no.  This would be a breaking change.  It is expected that a value in milliseconds is passed as a number, not as a string.  Strings are for parsing.
