### ISSUE TITLE
Chinese Traditional Encoding (Big5) Regex

### ISSUE THREAD

**Issue by YoavGivati** [moment/moment#2838]
Found by [@nosekbk](https://twitter.com/nosekbk)
Tested with moment.js 2.10.6
1. Make my browser use Chinese Traditional Encoding (Big5)
2. refresh site
3. see error in console `Uncaught SyntaxError: Invalid regular expression: missing /`
4. see file for Arabic Saudi Arabia (ar-sa) has a broken regex

**Suggested fix**: use `String.fromCharCode(000)` where `000` is the character code for all the unicode characters you're currently using as literals. Since javascript executes in UTF-16 this will ensure all your characters are transferred in ascii _ie: the int param for `fromCharCode`_ and generated as unicode at runtime as expected.
<img width="591" alt="screen shot 2015-12-29 at 18 16 33" src="https://cloud.githubusercontent.com/assets/707633/12045468/ff8cc65a-ae58-11e5-89e3-dfb83c6d0fee.png">

<img width="459" alt="screen shot 2015-12-29 at 18 16 52" src="https://cloud.githubusercontent.com/assets/707633/12045471/069ef3dc-ae59-11e5-8ed3-8539d6e3a0f0.png">
missing closing bracked in regex ^ due to hard coded non-ascii string literals

**Comment by ichernev** [comment]
Should we use fromCharCode only for chars that don't fit in 2 bytes, or for all non-ascii? People are using Unicode in js, so you're suggesting everyone should stop?

**Comment by marwahaha** [comment]
Thanks for this request.
Sorry this caused you trouble.
For now, we will not take this change.
Please re-open if you still have concerns.
