### ISSUE TITLE
2015-W53-7 Invalid Date

### ISSUE THREAD

**Issue by wleecarter** [moment/moment#2839]
http://jsfiddle.net/wlc3/ht2xbh68/2/

moment('2015-W53-1') gives the expected value: "2015-12-28T05:00:00.000Z"  
moment('2015-W53-7') does not: "__2015__-01-03T05:00:00.000Z" - shouldn't it be "__2016__-01-03..."?

also:

moment('2015-W53-1').format('dddd, MMMM Do'); // Monday, December 28th

but:

moment('2015-W53-7').format('dddd, MMMM Do'); // __Invalid Date__

If this really _is_ a bug, and not just my lack of understanding, I'd be happy to work on a fix

**Comment by mcroba** [comment]
Accordingly to https://en.wikipedia.org/wiki/ISO_week_date it seems there is a bug.

```
ISO year 2009 has 53 weeks and ends three days into Gregorian year 2010.
Thu 31 Dec 2009	2009-12-31	2009-W53-4
Fri 1 Jan 2010	2010-01-01	2009-W53-5
Sat 2 Jan 2010	2010-01-02	2009-W53-6
Sun 3 Jan 2010	2010-01-03	2009-W53-7
```

```javascript
moment('2009-W53-7'); // 2009-01-02T23:00:00.000Z
moment('2009-W53-7').format('dddd, MMMM Do'); // Invalid date
```

It's the same with 2015.

Is there someone working on the fix?

**Comment by icambron** [comment]
I can't reproduce this:

```js
moment('2015-W53-7').format('dddd, MMMM Do, YYYY') //=> "Sunday, January 3rd, 2016"
```

are you on 2.11.0?

**Comment by wleecarter** [comment]
I _was_ on 2.10.2, but when I change to 2.11.0 it's no longer an issue:  http://jsfiddle.net/wlc3/ht2xbh68/3/

**Comment by wleecarter** [comment]
Thanks.
