### ISSUE TITLE
parsing bug for MMM

### ISSUE THREAD

**Issue by ericremoreynolds** [moment/moment#2841]
```
> moment('1-jan-2016', 'D-MMM-Y', true).isValid()
    true
> moment('1-jan-2016', 'D-MMM-Y', true).year()
    2015
> moment.version
    "2.10.6"
```

**Comment by dantman** [comment]
I get 2016 in the same version of moment. My timezone is -08:00. Perhaps this is related to moment default parsing and displaying in local time.

**Comment by ericremoreynolds** [comment]
My timezone is +1:00

I haven't had time to debug the code yet.

**Comment by icambron** [comment]
This looks like a bug to me.

```js
moment('1-Jan-2016', 'D-MMM-YYYY', true).parsingFlags().invalidMonth
"Jan-"
```

so I think the parser is improperly eating the "-" after the month.

**Comment by ichernev** [comment]
This was introduced in https://github.com/moment/moment/pull/2548, and a way to solve it is to make it possible for locales to define custom month parsing regexes. That will solve the issue of patching the base one for additional locales, and will help us support klingon parsing (https://github.com/moment/moment/pull/2666), which was turned down for exactly the same reason.

Not to mention the `matchWord` regex is getting hairier with each release.

**Comment by ichernev** [comment]
Close in favor of #2869
