### ISSUE TITLE
Expose helper function to test strings for ISO string validity

### ISSUE THREAD

**Issue by adambuczynski** [moment/moment#2846]
Would it be possible to expose a helper function to test a string against the ISO date regexes as defined in https://github.com/moment/moment/blob/develop/src/lib/create/from-string.js#L8-L9?

My use case is that I am implementing auto-detection for valid ISO date strings coming out of JSON data, and if they match, they are automatically converted to moment objects in my models. 

Currently, I use the following work around to extend moment, but it would be helpful if this function is refactored into a standalone utility and exposed via the moment API:

```javascript
//ISO regexes taken from moment source code
//See: https://github.com/moment/moment/blob/develop/src/lib/create/from-string.js#L8-L9
var extendedIsoRegex = /^\s*((?:[+-]\d{6}|\d{4})-(?:\d\d-\d\d|W\d\d-\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?::\d\d(?::\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?/;
var basicIsoRegex = /^\s*((?:[+-]\d{6}|\d{4})(?:\d\d\d\d|W\d\d\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?:\d\d(?:\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?/;

//Add helper function to check if a string is a valid ISO date string
moment.isValidISOString = function(string) {
  return (extendedIsoRegex.exec(string) || basicIsoRegex.exec(string));
};
```

Since Moment already uses this internally, it would be cleaner to expose this via the public API rather than have to duplicate the regexes and hack it in.

If this is something that seems sensible, I would be happy to try and create a pull request for it.

**Comment by mj1856** [comment]
I believe you can already do this with:

```javascript
moment(stringToTest, moment.ISO_8601, true).isValid()
```

Does that not work for your use case?

**Comment by adambuczynski** [comment]
Excellent, thanks that should do the trick. I wasn't aware of moment's new strict parsing ability by specifying `true`.
