### ISSUE TITLE
Add support for brazilian date time format

### ISSUE THREAD

**Issue by llagerlof** [moment/moment#2851]
**Date**: "dd/mm/yyyy" or "dd/mm/yy" (eg: "01/12/2016" or "01/12/16")

**Expanded date**: "dd de mmmm de yyyy" (eg: "31 de janeiro de 2016" or, if it's first day of month: "1º de janeiro de 2016")

**Time**: hh:mm:ss (eg: "23:59:59")

**Short time**: hh:mm (eg: "23:59")

**Comment by mj1856** [comment]
We already have support for this.

See the moment.com home page:

![image](https://cloud.githubusercontent.com/assets/1396388/12225059/012fb2f4-b7b6-11e5-8f88-03099fdff2d5.png)

![image](https://cloud.githubusercontent.com/assets/1396388/12225061/1540a15e-b7b6-11e5-8713-756e201ef693.png)

Just set the `pt-br` locale code via `moment.locale`, or as an parameter where supported.
