### ISSUE TITLE
month format for locale en and en_au

### ISSUE THREAD

**Issue by lifeifei** [moment/moment#2854]
We pulled the latest version of moment.js and noticed the 'monthsShort' for 'September' in the most of 'en' locale files have been changed.   Before it was 'Sep' and now it becomes 'Sept', all the other months still stay with three letters.  Is there any specific reason for this change?

Thank you.

**Comment by mattgrande** [comment]
It was decided (and I agree) that "Sept" is much more common than "Sep."

https://github.com/moment/moment/issues/2728

Anecdotally, I don't think I've ever seen "Sep" before.

**Comment by estorski** [comment]
Shouldn't there be any kind of a standard for shortenings?
How could it be just "decided"? For the TS, parsing just stopped working, suddenly

**Comment by mattyod** [comment]
It would be nice to be able to choose. As this decision seems to have an American bias and personally I would expect MMM to return consistent 3 letter abbreviations.

http://www.isb.nhs.uk/use/baselines/datedisplaydesign.pdf

**Comment by lennym** [comment]
> Anecdotally, I don't think I've ever seen "Sep" before.

FYI:

```javascript
var d = new Date(2016, 8, 1);
console.log(d.toString());
// 'Thu Sep 01 2016 00:00:00 GMT+0100 (BST)'
```

(In Node 4.2.3 at the very least)

This change will break a lot of existing date parsing functionality which expects MMM to match 'Sep', and the fact that #2746 required "fixes" for existing parsing tests should have been enough to indicate that.

**Comment by shihabuddin** [comment]
AFAIK "Sep" is a requirement for "RFC 1123" date format for HTTP date headers.

**Comment by mrlannigan** [comment]
This completely breaks the date format used in our Oracle queries.

For example:
`2015-09-28` when output to oracle date we get `28-SEP-15` using format `DD-MMM-YY`

Post 2.11 release
`2015-09-28` when output to oracle date we get `28-SEPT-15` using format `DD-MMM-YY` which is an invalid date format.

**Comment by hamnis** [comment]
@shihabuddin Seconded. If you use moment to parse HTTP Date headers this stopped working now. See https://tools.ietf.org/html/rfc7231#section-7.1.1.1

**Comment by Dirrk** [comment]
This is a breaking change, increase the version number or revert this.

**Comment by ichernev** [comment]
I'll revert this in 2.11.1, there is too much backlash :)

Sept is the official human version, Sep is used by all software, for legacy reasons mostly, and its hard to change (as you can see).

**Comment by SamFromDaUk** [comment]
I agree with keeping this as a 3 letter abbreviation. This caused my tests to fail and help up a release until we found this issue.

**Comment by marlonbernardes** [comment]
I just had a problem with this new format as well. I didn't see this issue opened, so I opened a new one #2873 with examples in several languages.

**Comment by akonyer** [comment]
This is definitely a breaking change. .NET does not recognize "Sept" as a valid shorthand month.

**Comment by ichernev** [comment]
Close in favor of #2881.

**Comment by mj1856** [comment]
Apologies to all for the breaking change.  We should think about what the right way to handle this is though.  Should we perhaps have a default "invariant culture" language that is suitable for machine interaction, with US English being separate?

Or do we just let those that want Sept. rely on locale customization?

**Comment by marlonbernardes** [comment]
> Or do we just let those that want Sept. rely on locale customization?

This is the best approach, IMO. Those who want to abbreviate September as Sept could simply customize `Locale#monthsShort` - it is pretty straightforward to do so.
