### ISSUE TITLE
Broke MockDate

### ISSUE THREAD

**Issue by nowells** [moment/moment#2857]
Something in the 2.11.0 release broke [MockDate](https://www.npmjs.com/package/mockdate) support. I believe it was the commit https://github.com/moment/moment/commit/f54a32f4c62c12a710335211a73cb002a7249646 and the follow on refactoring https://github.com/moment/moment/commit/b1d686ed481e2211cb81a1c60eca850fcea93f21. I am not certain if this is something that you care to support, or if you view this as the responsibility of MockDate to fix, however, since MockDate simply patches the global Date object, it would seem breaking this generic mocking lib is a bad thing. Let me know what you think.

This used to work, but now breaks.

```js
const moment = require('moment'),
    mockdate = require('mockdate'),
    frozenTime = moment();

mockdate.set(frozenTime);
console.log('Frozen time: ', frozenTime.toISOString());

setTimeout(function() {
    console.log('Moment time: ', moment().toISOString());
}, 1000);
```

```bash
$ node index.js
Frozen time:  2016-01-04T14:21:55.335Z
Moment time:  2016-01-04T14:21:56.355Z
```

**Comment by Burgov** [comment]
Same here, but using sinonjs

**Comment by nowells** [comment]
I have a fix in the making, will submit a PR in a minute.

**Comment by NickHeiner** [comment]
:+1: for fixing this.

**Comment by nowells** [comment]
I just opened a PR to fix this issue: https://github.com/moment/moment/pull/2858

**Comment by mj1856** [comment]
Closing in favor of the PR #2858.  We'll track it there.  Thanks!
