### ISSUE TITLE
Issue when parsing single 'Y' format

### ISSUE THREAD

**Issue by michaelgeorgeattard** [moment/moment#2859]
Hi,

moment('5.12.2015', 'D.M.Y').year() is giving 2016 (incorrect)

while

moment('5.12.2015', 'D.M.YYYY').year() is giving 2015 (correct)

Is single character year unsupported? Or is it a bug?

We are using locale strings from angular, and noticed the bug because of the year change.

Thanks.

**Comment by michaelgeorgeattard** [comment]
Seems that the regexes object contains an entry for "Y" while formatTokenFunctions does not.

**Comment by ellenhutchings** [comment]
The docs would suggest that 'Y' isn't a valid input for year. You should use 'YY' or 'YYYY'.

**Comment by digitalgears** [comment]
Im also seeing bugs with formatting in v2.11.0. When doing 

moment(1441065600000).format('MMM')

I get 'sept' returned which is wrong. It should be 'sep'. (all other months work fine)

**Comment by ichernev** [comment]
@michaelgeorgeattard you're absolutely right. The problem is that `Y` is not a format token, and this basically means its useless as a parse token.

@digitalgears this is completely unrelated. There are other discussions for `Sep` vs `Sept`, and I'll revert the code to using `Sep` in 2.11.1

**Comment by ichernev** [comment]
Close in favor of #2868.
