### ISSUE TITLE
module is not defined on 2.11.0

### ISSUE THREAD

**Issue by realmx** [moment/moment#2862]
error on firefox

![module is not defined](https://cloud.githubusercontent.com/assets/6071313/12101050/9f8018d8-b36d-11e5-80e2-5630937114d2.jpg)

**Comment by zavan** [comment]
Same here.

**Comment by Bogatinov** [comment]
Same issue on Firefox, Chrome, Safari, IE, Edge.

Reverted back to 2.10.6 and it works as it should.

This commit broke it @rclanan 
https://github.com/moment/moment/commit/5f691b1cf83c388edb2938a8c032ad0cbb2e6505

**Comment by rclanan** [comment]
I will look into this shortly!

**Comment by ichernev** [comment]
We'll fix that and release soon.

**Comment by ichernev** [comment]
Close in favor of #2865
