### ISSUE TITLE
Format for output and parsing works inconsistently, strict mode

### ISSUE THREAD

**Issue by estorski** [moment/moment#2863]
Hello everyone,

I apologize if this issue is a duplicate for another active one.

For "en" locale:
When I format a date like that "YYYY-MMM-DD", I get "2016-Jan-05", however parsing it back (strict mode) gives _invalid date_.

console.log(moment(moment("2016-01-05").format("YYYY-MMM-DD"), "YYYY-MMM-DD", true));

Is it the expected behavior?

**Comment by mj1856** [comment]
Yes, dup of #2861.  Thanks.
