### ISSUE TITLE
v2.11.0 parses not valid ISO-8601 strings 

### ISSUE THREAD

**Issue by gswatowski** [moment/moment#2872]
After updating to v 2.11.0 invalid ISO strings are parsed and isValid() returns true. Bad formatted part and next ones are set to 0.

    // moment 2.10.6
    var m = moment.utc("2013-11-21T15:5:18", moment.ISO_8601);
    console.log(m.isValid()) //false
    console.log(m.format("D-MMM-YYYY H:mm:ss z")); //'Invalid date'

    //moment 2.11.0
    var m = moment.utc("2013-11-21T15:5:18", moment.ISO_8601);
    console.log(m.isValid()) //true
    console.log(m.format("D-MMM-YYYY H:mm:ss z")); //'21-Nov-2013 15:00:00 UTC'

**Comment by ichernev** [comment]
First of all, if you use strict parsing (pass `true` as a third argument) it is indeed marked as not valid.

Then, you can see its only parsed up to the hour component, and in fact ISO does define a date + 2 digit hour as valid ISO, so there is just some unused input, which is normal in non-strict parsing.

So `':5:18'` is correctly reported as unused input:
```javascript
> moment.utc("2013-11-21T15:5:18", moment.ISO_8601).parsingFlags()
{ empty: false,
  unusedTokens: [],
  unusedInput: [ ':5:18' ],
  overflow: -1,
  charsLeftOver: 5,
  nullInput: false,
  invalidMonth: null,
  invalidFormat: false,
  userInvalidated: false,
  iso: true }
```

I would say this is a bugfix and not a regression. @icambron @mj1856 what do you think

**Comment by icambron** [comment]
Yeah, I think the behavior is correct. It made its best effort given the input. As long as strict parsing rejects it, I think it's behaving correctly.

**Comment by ichernev** [comment]
Thanks @icambron !

**Comment by mj1856** [comment]
Agreed.  Perhaps non intuitive, but it seems that strict-parsing is almost always required when testing for validity.

**Comment by icambron** [comment]
Ideally, we'd just get rid of non-strict parsing.
