### ISSUE TITLE
Invalid date and format arguments fail silently

### ISSUE THREAD

**Issue by indiesquidge** [moment/moment#2874]
I was unable to find any other issue relating directly to this (other than [this issue]ªhttps://github.com/moment/moment/issues/1805) talking about things failing silently maybe), so I apologize if this is already a known issue.

Here is what I'm concerned with. Let's say you want to create and format a new `moment` instance, only instead of passing a string for the date argument, we simply pass a `Date` instance

```javascript
let dateObj = new Date();
let ISOStringFormat = 'YYYY-MM-DD[T]HH:mm:ss.SSS[Z]';

let invalidValue = moment(dateObj, ISOStringFormat); // invalid date arg, valid format arg
invalidValue.constructor // "valid" Moment instance created
invalidValue.format('MM YYYY'); // returns "Invalid date"
```

Another case where this could be an issue is if you pass a correct date argument but a non-ISO format argument

```javascript
let invalidFormat = moment(dateObj.toISOString(), 'MM YYYY'); // valid date arg, invalid, non-ISO format arg
invalidFormat.constructor // "valid" Moment instance created
invalidFormat.format('MM YYYY'); // returns "Invalid date"
```

Notice how close both of these cases are to a valid `moment` instance
```javascript
let valid = moment(dateObj.toISOString(), ISOStringFormat);
valid.format('MM YYYY'); // returns '01 2016', as expected
```

It may seem trivial, but the fact that `moment` returns a valid instance when it is created with incorrect arguments (fails silently) and then just simply returns `"Invalid date"` whenever you try to call any methods on it makes it difficult for one to know where they messed up, especially people (like myself) who haven't used the library very much before.

With that said, this is an awesome library and I appreciate the fact that you guys are adding to it and maintaining it. If this issue is something you would like to pursue fixing, I would be more than happy to help and contribute as best I can, just let me know :)

**Comment by indiesquidge** [comment]
Interestingly, if you pass _both_ arguments as "invalid", then it will be parsed correctly and methods can be called on it. Depending on the source code of this library (I haven't looked at it just yet), this makes some sense since the underlying code may know how to parse a date object when given a no-so-restrictive, non-ISO format with which to handle it. _However_, the library does not seem to be able to parse the date object correctly, as calling it gives back incorrect information.

```javascript
let invalidBoth = moment(dateObj, 'MM YYYY'); // invalid date arg, non-ISO format arg
invalid.format('MM YYYY'); // returns '07 2016' when it should be '01 2016'.
```

**Comment by ichernev** [comment]
Use `moment("str", "fmt").isValid()` if you care. Its not silent. That is how NaNs behave, that is how we decided to do it for moment. Exceptions that break your application are not an option.

**Comment by indiesquidge** [comment]
Hey @ichernev, thanks for the reply. I didn't see the `isValid()` method, that is indeed helpful.

> _That is now NaNs behave, that is how we decided to do it for moment._

Would you mind going into more detail as to what you mean by this? Are you suggesting that `moment()` is an intentionally poisonous function? And if so, may I ask why this is the case? I am genuinely interested and curious :)
