### ISSUE TITLE
Issues with 'loadLocale()'

### ISSUE THREAD

**Issue by Damo1155** [moment/moment#2876]
A couple of days ago v2.11.0 was released and fixed a number of bugs but most notably the problem which resulted in the default language being 'zh-tw' ( #2735 ). At the time it was the first time I'd seen this particular bug and after some searching noticed it was resolved in v2.11.0, so I upgraded our installed version to the latest. However, in doing so it's brought in a number of issues in for our JS Unit Tests and some areas of the the live code where we have to override the default language for various reasons.

Whenever I run the Code/Unit Tests since upgrading to v2.11.0 a number of errors get thrown, this is an example of one such error (to be honest most of them are pretty much the same error):

`ReferenceError: module is not defined at w (file:///C:/Users/Source/Repos/--Solution Directory Name--/Scripts/moment-with-locales.min.js:1:2581)`

After doing a bit of digging through the source code and referring to the errors which are thrown the issue is with `loadLocale()` and `Module` not being instantiated correctly. I've tried a number of fixes locally (without modifying the plugin source) to resolve the issue because we need to define the locale.

The only way I've found to resolve this issue is to downgrade to v2.10.6 as this was the last point where `module` was instantiated without issue. Unfortunately, in doing so it's brought back the `zh-tw` locale issues but we've decided to live with this for the time being. However, it's likely we'll come across this issue again in the future and not be able to just 'deal with it', so I was wondering if anyone is aware of a fix for this? If not, are the developers aware of this issue and is there potential to fix this in the next update?

**Comment by ichernev** [comment]
fixed in #2865, I'll release that soon as `2.11.1`.
