### ISSUE TITLE
Variable parseTwoDigitYear

### ISSUE THREAD

**Issue by mleduque** [moment/moment#2878]
I have cases when parsing and formatting two digits dates, when the cut-off date changes based on which legacy database the information comes from.

I can imagine a way to keep switching the moment.parseTwoDigitYear function, but that does seem error-prone.

What I would need is have multiple 'moment' objects, then I'd be able to have each of them have their own configuration, but that doesn't seem possible.

Is the parseTwoDigitYear given a context parameter which could serve as discriminant in the function ?

**Comment by ichernev** [comment]
Why don't you just add a few methods to moment (only in your code), that switch this for you:

```javascript
moment.parseOne = function () {
  var old = moment.parseTwoDigitYear;
  moment.parseTwoDigitYear = function () {/**/};
  var res = moment.apply(null, arguments);
  moment.parseTwoDigitYear = old;
  return res;
}

moment.parseTwo = function() { /**/ }

/* */
var m1 = moment.parseOne(/**/);
var m2 = moment.parseTwo(/**/);
```

**Comment by mleduque** [comment]
Yes, that should work. i'll probably do the

moment.parseTwoDigitYear = old;

inside a finally though.

Thank you.


2016-01-09 10:18 GMT+01:00 Iskren Ivov Chernev <notifications@github.com>:

**Comment by ichernev** [comment]
Sure, put a `finally` there for good measure :)
