### ISSUE TITLE
Parsing ASP.NET JSON Dates (WCF format) is not working correctly.

### ISSUE THREAD

**Issue by themakshter** [moment/moment#2879]
As mentioned in the Moment.js documentation [here](http://momentjs.com/docs/#/parsing/asp-net-json-date/), the parsing is supposed to work. However, there seems to be a problem with it. Using the example given there, 
```javascript
moment("/Date(1198908717056-0700)/"); // 2007-12-28T23:11:57.056-07:00
```
The time calculated should be `Fri Dec 28 2007 23:11:57 GMT+0000`. Instead, using 
```javascript
moment("/Date(1198908717056-0700)/");
```
give us `Sat Dec 29 2007 06:11:57 GMT+0000`. This is the same as callinng
```javascript
moment("/Date(1198908717056)/");
```
This means, that the offset is not being parsed correctly and included in the calculation, which needs to be done so. This bug can easily be recreated using the console on this website. If you want to parse the WCF format correctly, the following snippet might be useful:
```javascript
Date.parseWcfDate = function(str) {
  var regex = str.match(/\/Date\(([0-9]+)([-+])([0-9]+)\)\//);
  var millisecs = parseInt(regex[1]);
  var offset = parseFloat(regex[2] + regex[3]) / 100;
  var utcMillsecs = millisecs + offset * 3600 * 1000;
  return new Date(utcMillsecs);
};
```

EDIT:

corresponding [jsfiddle](https://jsfiddle.net/themakshter/jpu6x5o6/) has been added.

**Comment by themakshter** [comment]
Right, I think the regex is not entirely correct. 
```javascript
var aspNetJsonRegex = /^\/?Date\((\-?\d+)/i;
```

is the current regex, whereas you might want it to be something like 
```javascript
var regex = str.match(/\/Date\(([0-9]+)([-+])([0-9]+)\)\//);
```

**Comment by mj1856** [comment]
No, that's actually how this format works.  The offset is extraneous data.  It is not intended to be reflected in the time stamp.  That's opposite of what you might expect from more sensible formats like ISO8691, but that's just how this format was designed.

If you want to use the offset information, pass it to `moment.parseZone`.

**Comment by themakshter** [comment]
Okay, that makes sense. Thank you very much!

**Comment by themakshter** [comment]
When using parseZone, the time is calculated correctly. However, when we use duration on a moment object calculated like so, it doesn't seem to be working correctly, it just considers the time without the zone value. Is that correct behaviour? So let's say something like
```javascript
var someTime = moment.parseZone("/Date(1452631233400-0500)/");
var currentTime = moment();
var duration = moment.duration(escTime.diff(currentTime));
```
The duration for this is calculated the same as if I called moment without parsing the zone. Is that the correct behaviour?

 [Corresponding JS Fiddle](https://jsfiddle.net/themakshter/rf7r0oz8/)

**Comment by mj1856** [comment]
Yes, that is the correct behavior. Each moment object internally tracks the UTC time, and in both cases the input is unambiguous.

The difference between any two instants in universal time is the same, regardless of any time zone information on either side.

**Comment by themakshter** [comment]
In such a case, what would be your recommendation of the best approach to calculate duration while considering the zone? In my case, I pass the parsed timezone into another moment object like
```javascript
moment(moment.parseZone(date).format("lll"))
```

**Comment by mj1856** [comment]
I'm not sure I understand your request.  The duration between two points in time has everything to do with their UTC-based values, and nothing at all to do with their time zone.  In fact, if all you have is two local wall-time values, you have to convert them to UTC to get the correct duration between them - even if they are in the *same* time zone.

Consider:
```javascript
moment("2016-03-13 06:00:00").diff("2016-03-13 00:00:00", 'hours') 
```

Even though it looks like the answer should be 6, when run in my time zone (US Pacific Time), the answer is 5.  This is because of *daylight saving time*, which is just one of several things that can influence comparing local-time values.  There are actually only 5 hours elapsed, which you can only figure out by differencing the UTC equivalents - which is what moment does internally.

Now consider if those two timestamps were from opposite sides of the world.  There would be a *considerable* difference between them in elapsed time, even though their local wall-time values still looked like they were 6 hours apart.

**Comment by themakshter** [comment]
I think most of my confusion stems from the ASP.NET JSON Date format. The second part is the extraneous data as you say. So the first part is the time in UTC?

**Comment by mj1856** [comment]
Yes.

**Comment by mj1856** [comment]
If at all possible, I recommend you avoid that format.  Best practice for JSON is to use ISO8601 formatting.

**Comment by mj1856** [comment]
ISO8601 is the default in most .NET projects these days.  It's only the older ones that are still using it.  See also http://www.hanselman.com/blog/OnTheNightmareThatIsJSONDatesPlusJSONNETAndASPNETWebAPI.aspx

**Comment by themakshter** [comment]
Yes, that makes sense. Thank you very much on all your help in this matter!
