### ISSUE TITLE
Feature Request: Easier to Read (ie. Longer) Formatting Tokens

### ISSUE THREAD

**Issue by machineghost** [moment/moment#2880]
The Sugar library is ... not a great library.  It does have one great feature though, its date formatter, which allows you to do the following:

```
var someDate = new Date();
someDate.format('{Weekday} {d} {Month}, {yyyy}');
```

Now, compare that to equivalent Moment code:

```
var someDate = moment(new Date());
someDate.format('dddd D MMMM, YYYY');
```

Obviously moment's syntax is more concise, and for people who do a lot of date formatting I'm sure it's extremely intuitive (much like regular expressions).

However, I'd imagine that most developers don't format dates frequently, which means they have to write date formatting strings while simultaneously reading the Moment documentation page.  If they (or a co-worker) ever has to revisit that code, they have to return to the documentation page to translate each token one by one.

Now, I would never suggest getting rid of those tokens, just as I wouldn't want to get rid of regular expressions.  But at the same time, whenever possible I do try to avoid regular expressions in favor of more readable alternatives (eg. `indexOf`, `contains`, custom functions, etc.).

Imagine if Moment provided alternative **human-friendly** formatting tokens, and one could write:

```
var someDate = moment(new Date());
someDate.easyFormat('{weekday} {dayOfMonthZeroPadded} {monthUnpadded}, {fullYear}');
```

Even if you've never heard of Moment, and were somewhere remote without internet access, you could still understand that code _instantly_ (and perhaps even be able modify it).

I realize this may seem like a pointless request to someone who uses the Moment tokens on a daily basis, just as it would seem pointless to ask a regular expression expert to write a `contains` method for you ("why bother, just use a regex!").  But just as `contains` methods are a lot easier to read, understand, and maintain than regular expressions, an "easy" set of formatting tokens in Moment would be very valuable to many.

**Comment by ichernev** [comment]
I've been thinking about this myself. The main problem is how to do it without breaking existing code (that might use `{` `}` in a format).

Also it will enable us (and all users) to add custom tokens when they see fit. The number of things people want to put in a format is greater than the variation of all letters in the alphabet repeated a few times :)

I'll let this issue stay for now. If we come across releasing 3.0 it will definitely go in.

**Comment by machineghost** [comment]
Great to hear!

BTW, the reason I proposed `easyFormat`, as opposed to `format`, was precisely so that no existing code would be broken.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
