### ISSUE TITLE
setting month as a string number fails without notice

### ISSUE THREAD

**Issue by estorski** [moment/moment#2884]
Hey,

Consider this code:

```javascript
var d = moment();
console.log(d.year('2055')); // works as expected
console.log(d.date('2')); // works as expected
console.log(d.month('7')); // does nothing, and does not throw any errors either
console.log(d.month(7)); // works as expected
```

In my opinion it's worth to somehow handle a string number value for month, either parse it (0-11 basis), or throw a parsing error. Otherwise, it's a hidden pitfall for applications using _moment_

**Comment by mj1856** [comment]
Agreed.  This should be relatively simple, and a PR would be much appreciated from anyone looking to lend a hand.  Thanks!

**Comment by johnBartos** [comment]
Has anyone taken this? If not I will!

I've never made an OSS contribution before (found this on up-for-grabs) but I've been a developer for a while and know the PR deal.

**Comment by mj1856** [comment]
@johnBartos - go for it!  That's what up-for-grabs is all about.

Be sure to read [moment's contributing guidelines](https://github.com/moment/moment/blob/develop/CONTRIBUTING.md), and we'll be happy to help if you get stuck.  Thanks!

**Comment by mj1856** [comment]
be sure to include a unit test in your PR. :)

**Comment by mj1856** [comment]
Additionally, make sure you don't break the existing behavior as described [here in the docs](http://momentjs.com/docs/#/get-set/month/), which allows passing a month as a locale-based string, as in `.month("March")`.  The change here should work *in addition* to that.

**Comment by ichernev** [comment]
You have to make sure the entire string is a number, some locales have months starting with number and then a fancy character follows.

**Comment by johnBartos** [comment]
Great, thanks!

**Comment by mj1856** [comment]
Closing issue, in favor of PR #2897.

Thanks!

**Comment by mj1856** [comment]
@johnBartos  - Looks like @andrewkolesnikov beat you to it!  But don't get discouraged - we have many other items that need help. :)
