### ISSUE TITLE
Momentjs does not parse date with Chinese format

### ISSUE THREAD

**Issue by raajamalik** [moment/moment#2888]
This is regarding an issue we are facing with Chinese date format. 
I used a format - yyyy'年'mm'月'dd'日' 
Date - any date

It gives me - 2015'年'12'月'24'日'

but it should give me 2015年12月24日 - notice there are no single quotes in the date. I formatted using this format with java or other jqx formatting - it gives me correct result.

Can you please see, what is to be done. Does moment work well with Chinese timezone.

**Comment by ichernev** [comment]
I don't understand. You put '' in format and it ends up in the string. ' are preserved. Just remove them from your format string if you don't like them.

**Comment by raajamalik** [comment]
I completely agree with you. But this seems to be a format specific to Chineese or simplified chineese. As mentioned in the orignal issue, if we give same format using jqx formatting or java formatting, it simply works. 
This is strange to me also. If you try to format using java(I used http://www.fileformat.info/tip/java/simpledateformat.htm for testing), here is the output it gives:

![formatting chineese with java](https://cloud.githubusercontent.com/assets/7651626/12317600/9e31b7c8-bab8-11e5-99df-3e51b0128c91.PNG)

Please share your thoughts.

**Comment by mj1856** [comment]
Moment's formatter specifiers are not 100% aligned with those from other languages, be it Java, .NET, PHP, C, Ruby, or others.  Please read the documentation to carefully choose the correct format specifiers.

Specifically, moment's escape sequence characters are square brackets `[` and `]`, not single quote marks.

**Comment by mj1856** [comment]
Also note that they are case sensitive.  We use upper-case `YYYY`, `MM` and `DD` for the year, month, and day components.
