### ISSUE TITLE
`moment(ms).isSame()` doesn't work without same timezone

### ISSUE THREAD

**Issue by viki53** [moment/moment#2889]
Hi,

I just encountered a weird bug while using the `isSame()` method (`unit` was day, week, month or year, it doesn't really matter).

Here is some code that didn't work on the server (but worked fine on my machine):

``` javascript
var now = moment();

if (obj && obj.date && moment(obj.date).isSame(now, 'day')) {
    // Some code never executed (condition is false) on the server (but works fine locally)
}
```

`obj.date` being a number of milliseconds representing the beginning of a day (retrieved from a database, calculated by a mobile app, gone through `moment` before saving).

Now, here is the code that works everywhere:

``` javascript
var now = moment().tz('Europe/Paris');

if (obj && obj.date && moment(obj.date).tz('Europe/Paris').isSame(now, 'day')) {
    // Some code properly executed when needed everywhere
}
```

Just by specifying the timezones and these dates, everything works fine.

The server in on *CST (GMT-6)* timezone, my local machine in on *CET (GMT+1)*.

I'm guessing the dates are not on the same timezone somehow, even though the `moment` objects are created basically at the same time.

---

NB: Specifying globally the timezone (`moment.tz.setDefault('Europe/Paris')`) also seems to do the trick.

**Comment by ichernev** [comment]
isSame works in a very specific way. It checks if he passed moment is whithin the unit of the origibal (left hand side) moment. So when you ask isSame 'day', that is computed on the left moment (via startOf and endOf) and then checked if the right moment is inside that time range.

**Comment by mj1856** [comment]
You do realize that "today" is not the same for the whole world, right?  It's quite possible that two different time zones are on different dates simultaneously.  See [everytimezone.com](http://everytimezone.com) for a vizualization of this.

**Comment by viki53** [comment]
I know, but considering that I use milliseconds, I should get consistent results.

Also, the bug doesn't appears with day, it also occurred with week, month and year comparison (on the day I posted, so far enough from January 1st).

**Comment by mj1856** [comment]
When you create a moment object using `moment(...)` that is going to use the *local* time zone of the environment where the code is running.  It doesn't matter whether you pass in milliseconds or some other input format.  The resulting moment object is in "local mode".

So, without specifying a time zone, you're using the server's concept of a day (in US Central time).  If the day you care about is the day observed by france, then indeed you should specify the `Europe/Paris` time zone.

**Comment by viki53** [comment]
Okay, but if I don't specify the timezone for any of the moment objects, why do I get different results?

And why doesn't the comparison of week, month and year work?

**Comment by mj1856** [comment]
You're comparing a fixed timestamp to a local time.  The time stamp can easily fall onto different local days.  Give me an example input value that gives you different results and i can elaborate.

**Comment by viki53** [comment]
I'll do it as soon as I get to work.

In the meantime, I apologize for the trouble. We just couldn't get our heads around how it could fail, except for the `day` test.

It's just a matter of understanding now, considering we fixed it with the timezone.

**Comment by mj1856** [comment]
No problem - glad to help.  But it is just a misunderstanding I think.  There's no bug demonstrated here.

Time zones are hard - who knew! :)
