### ISSUE TITLE
Can't change locale with NativeScript on Android

### ISSUE THREAD

**Issue by nikolajskov** [moment/moment#2892]
I'm using the [Moment](http://momentjs.com/) plugin to handle dates in my app and it works well... apart from one thing: I can't get any other locale than English (en) to work on Android; on iOS I can change to whatever locale I want.

I have installed Moment in my project

```npm install moment```

and this is what I'm doing

```javascript
var moment = require("moment");

moment.locale("fr");
console.log(moment.locale()); // Prints "fr" on iOS but "en" on Android!!!
var m = moment();
m.locale("da");
console.log(m.locale()); // Prints "da" on iOS but "en" on Android!!!
```

What is going wrong? Any ideas?

Best Regards,
Nikolaj

**Comment by mj1856** [comment]
It seems like we'd need to know more about your environment.  Perhaps someone else familiar with NativeScript can lend a hand.

It's likely the locale data files are not being loaded or included.

**Comment by nikolajskov** [comment]
Got a solution: https://groups.google.com/d/msg/nativescript/AkUxmZBXZ5M/uc_o_35xDAAJ

**Comment by mj1856** [comment]
Glad to hear it!  Closing this issue then.  Thanks!
