### ISSUE TITLE
GMT+03:00 Asia/Baghdad instead of Europe/Moscow

### ISSUE THREAD

**Issue by alealex** [moment/moment#2893]
I have 
moment.js  version : 2.11.1 
moment-timezone.js  version : 0.5.0
os windows 7

If I set timezone to UTC+3 Moscow, St.Petersburg, Volgograd (RTZ 2) then the following code
`"GMT" + moment().format('Z') + ":" + moment.tz.guess()`
will produce `GMT+03:00:Asia/Baghdad`

expected result is `GMT+03:00:Europe/Moscow`

http://jsfiddle.net/3javhx7k/2/

**Comment by mj1856** [comment]
This should be logged in the [moment-timezone issue tracker](https://github.com/moment/moment-timezone/issues).  When you do, please include the output of `console.log(navigator.appVersion)`
Do keep in mind that it is just a guess though.
