### ISSUE TITLE
LT format is not correct for many locales

### ISSUE THREAD

**Issue by aaronjpitts** [moment/moment#2895]
Why are the time locales all the same other than EN locale which is correct? For example the LT format in French should be 12h00 and not 12:00 which is what is outputted. It seems none of the locales have the proper time formats, dates are all correctly translated. Why is this?

Thanks

**Comment by mj1856** [comment]
Probably just oversight.  I believe you're correct about France.  [Wikipedia agrees](https://en.wikipedia.org/wiki/Date_and_time_notation_in_France).

I'm not sure about other locales.  Feel free to submit PRs to correct.  These should be one PR per language, so we can track discussion / debate / approvals separately.  Be sure to update the unit test, or add one if there isn't one for the LT format.

**Comment by mj1856** [comment]
I'm also marking this with Up-For-Grabs - Though I don't expect a single contributor to check all locales.  I'll update here as they are corrected.

Also note that many of these already use a locale specific format - though there are quite a lot that use `HH:mm` even though something else may be more appropriate.

locale |  original LT format |  updated LT format |  PR#
---|---|---|---
af |  HH:mm |   |  
ar-ma |  HH:mm |   |  
ar-sa |  HH:mm |   |  
ar-tn |  HH:mm |   |  
ar |  HH:mm |   |  
az |  HH:mm |   |  
be |  HH:mm |   |  
bg |  H:mm |   |  
bn |  A h:mm সময় |   |  
bo |  A h:mm |   |  
br |  h[e]mm A |   |  
bs |  H:mm |   |  
ca |  H:mm |   |  
cs |  H:mm |   |  
cv |  HH:mm |   |  
cy |  HH:mm |   |  
da |  HH:mm |   |  
de-at |  HH:mm |   |  
de |  HH:mm |   |  
dv |  HH:mm |   |  
el |  h:mm A |   |  
en-au |  h:mm A |   |  
en-ca |  h:mm A |   |  
en-gb |  HH:mm |   |  
en-ie |  HH:mm |   |  
en-nz |  h:mm A |   |  
eo |  HH:mm |   |  
es |  H:mm |   |  
et |  H:mm |   |  
eu |  HH:mm |   |  
fa |  HH:mm |   |  
fi |  HH.mm |   |  
fo |  HH:mm |   |  
fr-ca |  HH:mm |   |  
fr-ch |  HH:mm |   |  
fr |  HH:mm |   |  
fy |  HH:mm |   |  
gd |  HH:mm |   |  
gl |  H:mm |   |  
he |  HH:mm |   |  
hi |  A h:mm बजे |   |  
hr |  H:mm |   |  
hu |  H:mm |   |  
hy-am |  HH:mm |   |  
id |  HH.mm |   |  
is |  H:mm |   |  
it |  HH:mm |   |  
ja |  Ah時m分 |   |  
jv |  HH.mm |   |  
ka |  h:mm A |   |  
kk |  HH:mm |   |  
km |  HH:mm |   |  
ko |  A h시 m분 |   |  
lb |  H:mm [Auer] |   |  
lo |  HH:mm |   |  
lt |  HH:mm |   |  
lv |  HH:mm |   |  
me |  H:mm |   |  
mk |  H:mm |   |  
ml |  A h:mm -നു |   |  
mr |  A h:mm वाजता |   |  
ms-my |  HH.mm |   |  
ms |  HH.mm |   |  
my |  HH:mm |   |  
nb |  HH:mm |   |  
ne |  Aको h:mm बजे |   |  
nl |  HH:mm |   |  
nn |  HH:mm |   |  
pl |  HH:mm |   |  
pt-br |  HH:mm |   |  
pt |  HH:mm |   |  
ro |  H:mm |   |  
ru |  HH:mm |   |  
se |  HH:mm |   |  
si |  a h:mm |   |  
sk |  H:mm |   |  
sl |  H:mm |   |  
sq |  HH:mm |   |  
sr-cyrl |  H:mm |   |  
sr |  H:mm |   |  
sv |  HH:mm |   |  
sw |  HH:mm |   |  
ta |  HH:mm |   |  
te |  A h:mm |   |  
th |  H นาฬิกา m นาที |   |  
tl-ph |  HH:mm |   |  
tlh |  HH:mm |   |  
tr |  HH:mm |   |  
tzl |  HH.mm |   |  
tzm-latn |  HH:mm |   |  
tzm |  HH:mm |   |  
uk |  HH:mm |   |  
uz |  HH:mm |   |  
vi |  HH:mm |   |  
zh-cn |  Ah点mm分 |   |  
zh-tw |  Ah點mm分 |   |

**Comment by arntj** [comment]
The LT and LTS formats are already correct for locales nb and nn.

**Comment by amandine-perichon** [comment]
I have submitted PR #3407 to change the time format for the fr locale.

**Comment by rangelke** [comment]
I'm new around here, am I as well allowed to open up PR's. It would be a nice way to start contributing to moment.js, as I've used it in a couple projects and want to give back to the community. Even though my knowledge isn't that great.

**Comment by maggiepint** [comment]
@rangelke you are more than welcome to make a pull request. that's how open source works :-)

**Comment by mlukjanska** [comment]
I was thinking of picking this one up and going through some of the locales. 
Is the best way to create a separate PR for each locale, that I am planning to work on? 
And as the 'requirements' reference best is to use [CLDR](http://www.unicode.org/cldr/charts/29/summary/af.html) where:
- LT = Date & Time --> Gregorian --> Formats - Standard - Time Formats --> Short
- LTS = Date & Time --> Gregorian --> Formats - Standard - Time Formats --> Medium

Thanks!

**Comment by joelmheim** [comment]
I have started to look into this again. Working on an overview of the LT/LTS format for all locales.

**Comment by joelmheim** [comment]
This table is what I have been able to find out from some quick research. Have only submitted PR's for the locales that I'm sure about. Other PR's are welcome. And of course any corrections.

| locale     | original LT format |  CLDR            	|  PR#  |
|-------------|-------------------------|--------------------------|----------|
| af           | HH:mm                 | a hh:mm                 |            |
| ar-dz      | HH:mm                 | HH:mm                  | OK      |
| ar-kw     | HH:mm                 | a h:mm            |       |
| ar-ly       | HH:mm              | a h:mm            |       |
| ar-ma     | HH:mm              | HH:mm             | OK    |
| ar-sa      | HH:mm              | a h:mm            |       |
| ar-tn       | HH:mm              | HH:mm             | OK    |
| ar           | HH:mm              | a h:mm            |       |
| az          | HH:mm              | HH:mm             | OK    |
| be          | HH:mm              | HH:mm             | OK    |
| bg          | H:mm               | H:mm              | OK    |
| bm         | HH:mm              | HH:mm             | OK    |
| bn          | A h:mm সময়          | h:mm a            | OK    |
| bo          | A h:mm             | h:mm a            | OK    |
| br           | h[e]mm A           | HH:mm             |       |
| bs           | H:mm               | HH:mm             | OK    |
| ca           | H:mm               | H:mm              | OK    |
| cs           | H:mm               | H:mm              | OK    |
| cv           | HH:mm              | HH:mm             | OK    |
| cy           | HH:mm              | HH:mm             | OK    |			
| da           | HH:mm              | HH:mm             | OK    | 			
| de-at       | HH:mm              | HH:mm             | OK    |
| de-ch      | HH.mm              | HH:mm             | #4200 |
| de           | HH:mm              | HH:mm             | OK    |
| dv           | HH:mm              | HH:mm             | OK    |
| el            | h:mm A             | h:mm a            | OK    |
| en-au      | h:mm A             | h:mm a            | OK    |
| en-ca      | h:mm A             | h:mm a            | OK    |
| en-gb      | HH:mm              | HH:mm             | OK    |
| en-ie       | HH:mm              | HH:mm             | OK    |
| en-nz      | h:mm A             | h:mm a            | OK    |
| eo           | HH:mm              | HH:mm             | OK    |
| es-do      | h:mm A             | h:mm a            | OK    |
| es-us      | H:mm               | h:mm a            | #4209 |
| es           | H:mm               | H:mm              | OK    |
| et            | H:mm               | H:mm              | OK    |
| eu           | HH:mm              | HH:mm             | OK    |
| fa            | HH:mm              | H:mm              | OK    |
| fi             | HH.mm              | H.mm              | OK    |
| fo            | HH:mm              | HH:mm             | OK    |
| fr-ca        | HH:mm              | HH:mm             | OK    |
| fr-ch        | HH:mm              | HH:mm             | OK    |
| fr             | HH:mm              | HH:mm             | OK    |
| fy            | HH:mm              | HH:mm             | OK    |
| gd           | HH:mm              | HH:mm             | OK    |
| gl            | H:mm               | H:mm              | OK    |
| gom-latn | A h:mm [vazta]     | N/A               | OK    |
| gu       | A h:mm વાગ્યે        |	hh:mm a           |       |
| he       | HH:mm              | HH:mm             | OK    |
| hi       | A h:mm बज          | h:mm a            | OK    |
| hr       | H:mm               | H:mm              | OK    |
| hu       | H:mm               | H:mm              | OK    |
| hy-am    | HH:mm              | H:mm              |       |
| id       | HH.mm              | HH.mm             | OK    |
| is       | H:mm               | HH:mm             |       |
| it       | HH:mm              | HH:mm             | OK    |
| ja       | HH:mm              | H:mm              |       |
| jv       | HH.mm              | HH.mm             | OK    |
| ka       | h:mm A             | H:mm              |       |
| kk       | HH:mm              | HH:mm             | OK    |
| km       | HH:mm              | HH:mm             | OK    |
| kn       | A h:mm             | HH:mm             |       |
| ko       | A h:mm             | a h:mm            | OK    |
| ky       | HH:mm              | HH:mm             | OK    |
| lb       | H:mm [Auer]        | HH:mm             | OK    |
| lo       | HH:mm              | H:mm              | OK    |
| lt       | HH:mm              | HH:mm             | OK    |
| lv       | HH:mm              | HH:mm             | OK    |
| me       | H:mm               | HH:mm             | OK    |
| mi       | HH:mm              | HH:mm             | OK    |
| mk       | H:mm               | HH:mm             | OK    |
| ml       | A h:mm -ന         | h:mm a            | OK    |
| mr       | A h:mm वाजता        | h:mm a            | OK    |
| ms-my    | HH.mm              | h:mm a            | Deprecated |
| ms       | HH.mm              | H:mm              |       |
| my       | HH:mm              | HH:mm             | OK    |
| nb       | HH:mm              | HH:mm             | OK    |
| ne       | Aको h:mm बजे        | h:mm a            | OK    |
| nl-be    | HH:mm              | HH:mm             | OK    |
| nl       | HH:mm              | HH:mm             | OK    |
| nn       | HH:mm              | HH:mm             | OK    |
| pa-in    | A h:mm ਵਜੇ          | h:mm a            | OK    |
| pl       | HH:mm              | HH:mm             | OK    |
| pt-br    | HH:mm              | HH:mm             | OK    |
| pt       | HH:mm              | HH:mm             | OK    |
| ro       | H:mm               | HH:mm             | OK    |
| ru       | HH:mm              | H:mm              | #4210 |
| sd       | HH:mm              | HH:mm             | OK    |
| se       | HH:mm              | HH:mm             | OK    |
| si       | a h:mm             |                   |       |
| sk       | H:mm               | H:mm              | OK    |
| sl       | H:mm               | H:mm              | OK    |
| sq       | HH:mm              | HH:mm             | OK    |
| sr-cyrl  | H:mm               | H:mm              | OK    |
| sr       | H:mm               | H:mm              | OK    |
| ss       | h:mm A             |                   |       |
| sv       | HH:mm              | HH:mm             | OK    |
| sw       | HH:mm              | HH:mm             | OK    |
| ta       | HH:mm              | HH:mm             | OK    |
| te       | A h:mm             | h:mm a            | OK    |
| tet      | HH:mm              | HH:mm             | OK    |
| th       | H นาฬิกา m นาที	    | H:mm              | #2899 |
| tl-ph    | HH:mm              | HH:mm             | OK    |
| tlh      | HH:mm              | N/A               | OK    |
| tr       | HH:mm              | HH:mm             | OK    |
| tzl      | HH.mm              | N/A               | OK    |
| tzm-latn | HH:mm              | HH:mm             | OK    |
| tzm      | HH:mm              | HH:mm             | OK    |
| uk       | HH:mm              | HH:mm             | OK    |
| ur       | HH:mm              | h:mm a            | OK    |
| uz-latn  | HH:mm              | HH:mm             | OK    |
| uz       | HH:mm              | HH:mm             | OK    |
| vi       | HH:mm              | HH:mm             | OK    |
| x-pseudo | HH:mm              | N/A               | OK    |
| yo       | h:mm A             | h:mm a            | OK    |
| zh-cn    | HH:mm              | H:mm              |       |
| zh-hk    | HH:mm              | H:mm              |       |
| zh-tw    | HH:mm              | HH:mm             | OK    |

**Comment by marwahaha** [comment]
It looks like most locales are OK. if there are issues with specific locales we can open new issues.

Thanks to everyone involved!
