### ISSUE TITLE
Bug when calculating a week that start in 2015 and ends on 2016

### ISSUE THREAD

**Issue by caioreis** [moment/moment#2896]
Hi,

I've found a bug that is probably related to different years in the same week. Let's take a look:

    moment().hour(0).minutes(0).seconds(0).week(51).year(2015).unix()
    1450749600

    moment().hour(0).minutes(0).seconds(0).week(52).year(2015).unix()
    1451354400

    moment().hour(0).minutes(0).seconds(0).week(53).year(2015).unix()
    1420423200

But with this it works 

     moment().year(2015).week(53).startOf('week').unix();
     1451268000

Was this was already seen before?

**Comment by mj1856** [comment]
If you're going to set values with individual properties, you need to do so from largest to smallest units.  Otherwise, you risk things not quite being what you expect.  That's not a bug, that's just how calendars work.  You can do similar things by setting the day before setting the month.

**Comment by caioreis** [comment]
@mj1856 , thanks for the explanation. But that doesn't explain why it works with all other weeks.
