### ISSUE TITLE
9 tests failed. diff:diff across DST (2396.17) diff:diff across DST (2396.19) duration from moments:pure year diff (2444.1) duration from moments:pure year diff (2444.2) start and end of units:start of quarter (2663.7) start and end of units:end of quarter (2664.4) start and end of units:end of quarter (2664.5) start and end of units:end of quarter (2664.6) start and end of units:end of quarter (2664.7) 

### ISSUE THREAD

**Issue by slimfadi** [moment/moment#2898]
### Client info
```
Date String   : Fri Jan 15 2016 12:04:38 GMT+0200 (EET)
Locale String : 1/15/2016, 12:04:38 PM
Offset        : -120
User Agent    : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
```

====

### diff:diff across DST (2396.17) 

month diff across DST, lower bound

```javascript
// Expected true
// Actual   false
false === true
```

====

### diff:diff across DST (2396.19) 

year diff across DST, lower bound

```javascript
// Expected true
// Actual   false
false === true
```

====

### duration from moments:pure year diff (2444.1) 

year moment difference

```javascript
// Expected 1
// Actual   1.0001140794586245
1.0001140794586245 === 1
```

====

### duration from moments:pure year diff (2444.2) 

negative year moment difference

```javascript
// Expected -1
// Actual   -1.0001140794586245
-1.0001140794586245 === -1
```

====

### start and end of units:start of quarter (2663.7) 

strip out the hours

```javascript
// Expected 0
// Actual   1
1 === 0
```

====

### start and end of units:end of quarter (2664.4) 

keep the quarter

```javascript
// Expected 2
// Actual   3
3 === 2
```

====

### start and end of units:end of quarter (2664.5) 

set the month

```javascript
// Expected 5
// Actual   6
6 === 5
```

====

### start and end of units:end of quarter (2664.6) 

set the day

```javascript
// Expected 30
// Actual   1
1 === 30
```

====

### start and end of units:end of quarter (2664.7) 

set the hours

```javascript
// Expected 23
// Actual   0
0 === 23
```

**Comment by mj1856** [comment]
Tracking DST issue in #3021.  Will leave open for others for now.

**Comment by mj1856** [comment]
Actually, others are timezone related also, so closing.  Tracking in #3021
