### ISSUE TITLE
Since 2.11.0 week numbers are not calculated correctly

### ISSUE THREAD

**Issue by farlop** [moment/moment#2900]
I noticed that since updated to 2.11.0 week numbers (more precisely using format('w')) are not calculated correctly on my fullCalendar. I'm using spanish locale. For example, the week number for date 28/12/2015  should be 53 which is right in version 2.10.6. Starting 2.11.0, moment says it's 44.

**Comment by mj1856** [comment]
Hmmm. I tried:

```javascript
moment('2015-12-28').locale('es').format('w')
```
Under both 2.11.0 and 2.11.1,  I get week 53.   Please test again, and provide a code snippet that reproduces the problem.  Thanks.

FYI, Week 44 by the Spanish locale is from `2015-10-26` through `2015-11-01`.

**Comment by farlop** [comment]
OK. I managed to reproduce it, but it involves fullCalendar, so I doubt if it's a moment.js bug or a fullCalendar...

In this jsfiddle: https://jsfiddle.net/xwyqq4rg/4/ 

If the 'firstDay' argument is provided as a string, the issue occurs, but if it is provided as int it works fine. I thought it was a moment.js because rolling back the version solved the problem, but now I don't know if I should create a new issue in fullCalendar...

**Comment by mj1856** [comment]
I'll investigate and get back to you.  Thanks.

**Comment by mj1856** [comment]
Seems like the easy answer is to always pass it as a number.

I'm not sure precisely what allowed you to pass it as a string in previous versions.

If fullcalendar wants to allow a string in their API, they can do that.

XRef fullcalendar/fullcalendar#3014
