### ISSUE TITLE
Wrong capital letters in Russian

### ISSUE THREAD

**Issue by polkovnikov-ph** [moment/moment#2902]
moment().subtract(6, 'days').calendar();  // В Понедельник в 23:27
    moment().subtract(3, 'days').calendar();  // В Четверг в 23:27

These should be `В понедельник в 23:27` and `В четверг в 23:27`. Russian doesn't employ capitalization of weekdays.

**Comment by artem-malko** [comment]
This is true for Months too.

**Comment by mj1856** [comment]
Dup #2882
