### ISSUE TITLE
Setting or changing locale data per instance

### ISSUE THREAD

**Issue by hendrul** [moment/moment#2903]
I need to change the first day of week according to user profile; currently I could register my own locales or change already loaded locales but in the moment class!, I need to change only some aspects of the locale data per moment instance, not sharing the locales. I couldn't even create a new locale base on the current one because I see no way of getting the locale data in a valid format so I could change de "dow".
And no way I think on doing it programatically with startOfWeek or so.

What I wish is something like:
```javascript
var date = moment().locale('en');
date.locale({ week: { dow: 1 }}); //Only for this instance override/merge current localeData with this one
console.log(data.locale()); //en
console.log(data.localeData().firstDayOfWeek()); //1 

//This instance will use the plain globally loaded english locale
date = moment().locale('en');
console.log(data.locale()); //en
console.log(data.localeData().firstDayOfWeek()); //0 
```

**Comment by mj1856** [comment]
You can define a new locale based on the current one like this:

```javascript
moment.locale('en-custom', moment.localeData('en'));
```

Then just customize the new locale as desired and use it.

**Comment by hendrul** [comment]
This turns unscalable when customizing locales per user, where each have their own detailed customizations.

**Comment by mj1856** [comment]
I'm not sure why.  You can do the customization on-the-fly, per user. It doesn't have to be done globally ahead of time.
