### ISSUE TITLE
ISO_8601 and parsing YYYY-MMTHH:mm

### ISSUE THREAD

**Issue by aahoughton** [moment/moment#2905]
I'm hoping for clarification; this isn't necessarily an issue.  Wikipedia (yes yes, not necessarily the best source, please point me at a better one) appears to imply that the following is true:

1. `YYYY-MM` is a valid "calendar date"
2. any "complete" `<date>T<time>` is a valid combined date time, where the date part is calendar, ordinal, or week

.. am I misreading this?  moment doesn't appear to treat, e.g., `2016-01T12:34` as strictly valid:

```
> moment('2016-01T12:34', moment.ISO_8601, true).isValid();
false
> moment('2016-01-12T12:34', moment.ISO_8601, true).isValid();
true
```

I'm happy to provide a patch, assuming this isn't a misreading on my part.

**Comment by mj1856** [comment]
Let me whip out the ancient sacred texts....  (yes, I have a legal copy of the ISO 8601 spec)

> 4.1.2.3 Representations with reduced accuracy 
> ...
>  a) A specific month
>        Basic format:   `YYYY-MM`   Example: `1985-04`

So yes, that part is acceptable, but later...

> 4.3.3 Representations other than complete 
> 
> For reduced accuracy, decimal or expanded representations of date and time of day, any of the representations in 4.1.2 (calendar dates), 4.1.3 (ordinal dates) or 4.1.4 (week dates) followed immediately by the time designator [T] may be combined with any of the representations in 4.2.2.2 through 4.2.2.4 (local time), 4.2.4 (UTC of day) or 4.2.5.2 (local time and the difference from UTC) provided that 
> ...
> c) the date component shall not be represented with reduced accuracy;
> ...

So, by 4.3.3(c), the *combined* representation of `2016-01T12:34` is not valid, because the date component has reduced accuracy.

**Comment by aahoughton** [comment]
Sweet!  Ancient sacred texts FTW.
