### ISSUE TITLE
Multiple date with commas how can i convert it

### ISSUE THREAD

**Issue by sidaurukfreddy** [moment/moment#2909]
Please refers to <a href="http://codepen.io/sidaurukfreddy/pen/oboOMz">Here</a>

I don't know how to start convert it  with long date sperate with commas, i have also post in stackoverflow.com here is my post is <a href="http://stackoverflow.com/questions/34890798/change-group-concat-in-mysql-date-to-indonesia-date-using-moments-js">Here</a>

Thanks

**Comment by mj1856** [comment]
From the first link, it seems like you just need to learn [`split`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split), [`map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map), and [`join`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join).

```javascript
var input = '2016-02-14,2016-02-16,2016-02-17,2016-02-18';
var dates = input.split(',');
var formatted = dates.map(function(d) { return moment(d).format('DD-MM-YYYY'); });
var merged = formatted.join(',');
console.log(merged); // "14-02-2016,16-02-2016,17-02-2016,18-02-2016"
```

No idea what your asking for in the StackOverflow post.  Sorry.
