### ISSUE TITLE
moment().calendar(referenceTime) shows "Tomorrow " while expected "Yesterday", etc.

### ISSUE THREAD

**Issue by laukstein** [moment/moment#2913]
How come

> moment().calendar(new Date() - 100000000)

shows **Tomorrow at 4:38 PM** when expected **Yesterday ...**,

and both

> moment().calendar(new Date() - 10000000)
> moment().calendar(new Date() + 10000000000)

shows **Today at 4:38 PM**?

It is totally wrong.

**Comment by laukstein** [comment]
Another test show failed results

> moment().calendar(moment().add(24, 'h')); // "Yesterday at 9:57 AM"
> moment().calendar(moment().add(-24, 'h')); // "Tomorrow at 9:57 AM"

must return opposite results.

**Comment by below9k** [comment]
Seems to be a bug from several version ago. I had v2.8.4, ran into this issue, then upgraded, to 2.11.1, and found the issue still persists.

Seems next and last have been swapped.

Temporary fix for en defaults:
```moment.locale('en', {
    calendar: {
        lastDay: '[Tomorrow at] LT',
        sameDay: '[Today at] LT',
        nextDay: '[Yesterday at] LT',
        lastWeek: '[Next] dddd [at] LT',
        nextWeek: '[Last] dddd [at] LT',
        sameElse: 'L'
    }
});```

**Comment by icambron** [comment]
That's not how the API works. See http://momentjs.com/docs/#/displaying/calendar-time/. The `this` -- the one you created with `moment()` is the time being shown, e.g.:

```js
> moment(new Date() - 100000000).calendar()
'Yesterday at 1:01 PM'
```

Which I think is what you're trying to do.

`calendar()` takes an optional argument that changes the anchor from now to the specified date. So when you pass yesterday into that and use `moment()` (which means now) as the "to" date, you're asking what today would be called by someone yesterday, which is "tomorrow". Hope that helps!

**Comment by laukstein** [comment]
This would respond correctly:
```
> moment().add(24, 'h').calendar()
"Tomorrow at 11:58 PM"
> moment().add(-24, 'h').calendar()
"Yesterday at 11:58 PM"
```

**Comment by icambron** [comment]
I'm not sure I followed that -- are you saying that doesn't work as you expect?

**Comment by laukstein** [comment]
I would expect

    moment().calendar(moment().add(24, 'h')) === moment().add(24, 'h').calendar()

and

    moment().calendar(moment().add(-24, 'h')) === moment().add(-24, 'h').calendar()

but it doesn't. @icambron, does documentation differs them?

**Comment by icambron** [comment]
Very much different:

`moment().add(24, 'h').calendar()` == "What is tomorrow called today?"
`moment().calendar(moment().add(24, 'h'))` == "What will today be called tomorrow?"

In the first case, the "today" comes from `calendar()`'s default and in the second case it comes from `moment()`. That's what the docs mean by:

> Calendar time displays time relative to a given referenceTime (defaults to now)

Terms like "tomorrow" and "yesterday" are directional; they're what one day is called vis-a-vis another day.
