### ISSUE TITLE
Non-strict parsing of "1/1/1970" returns date of Dec 31 1969 if 'x' format is included

### ISSUE THREAD

**Issue by dalelotts** [moment/moment#2918]
This is not what I expected...

```JavaScript
moment("1/1/1970", ['M/D/YYYY h:mm A','x'], 'en', false).toDate()
```
returns Wed Dec 31 1969 18:00:00 GMT-0600 (CST)

but
```JavaScript
moment("1/1/1970", 'M/D/YYYY h:mm A', 'en', false).toDate()
```
returns Thu Jan 01 1970 00:00:00 GMT-0600 (CST)

**Comment by mj1856** [comment]
Not sure if we'll be able to do anything about that.  At a certain point, formats will clash - especially in forgiving mode.

**Comment by dalelotts** [comment]
I understand that formats will clash. I didn't expect these formats to clash.

Is "1/1/1970" being treated as an expression at some point in order to match with x?

**Comment by icambron** [comment]
Yeah, this is happening because of this:

```js
> moment("11970", "x").format()
'1969-12-31T19:00:11-05:00'
```

because the forgiving parser ignores the "/"s. Why does it win over the other format? Because it has fewer unused tokens and that weighs against it in the "which of these fits better" heuristics.
