### ISSUE TITLE
Locale change event

### ISSUE THREAD

**Issue by andreialecu** [moment/moment#2919]
I've been looking for an event to subscribe to for when the locale changes, but there doesn't seem to be any.

The use case is that I'm developing a custom (reusable) component that displays a calendar. I would like to automatically refresh the calendar when some outside code changes the locale.

Is there any other way other than monkey patching `moment.locale()` to tap into this?

**Comment by mj1856** [comment]
No, we don't have any events like this built in - that I'm aware of.

Feel free to submit a PR if it's lightweight enough to include in the core.  Thanks.

**Comment by icambron** [comment]
I'm a bit hesitant about opening the callbacks floodgates here, but I guess if we restrict it to global state, it's reasonable enough.

**Comment by marwahaha** [comment]
Thanks for this suggestion.
We will not implement this at this time.
Please re-open if you still have concerns.
