### ISSUE TITLE
defineLocale doesn't inherit form the main locale

### ISSUE THREAD

**Issue by antpaw** [moment/moment#2923]
this code doesn't work. 'de-short' will use weekdays from 'en'

    moment.defineLocale 'de',
      months: 'Januar_Februar_März_April_Mai_Juni_Juli_August_September_Oktober_November_Dezember'.split('_')
      monthsShort: 'Jan._Febr._Mrz._Apr._Mai_Jun._Jul._Aug._Sept._Okt._Nov._Dez.'.split('_')
      weekdays: 'Sonntag_Montag_Dienstag_Mittwoch_Donnerstag_Freitag_Samstag'.split('_')
      weekdaysShort: 'So._Mo._Di._Mi._Do._Fr._Sa.'.split('_')
      weekdaysMin: 'So_Mo_Di_Mi_Do_Fr_Sa'.split('_')
      longDateFormat:
        LT: 'HH:mm [Uhr]'
        L: 'DD.MM.YYYY'
        LL: 'D. MMMM YYYY'
        LLL: 'D. MMMM YYYY LT'
        LLLL: 'dddd, D. MMMM YYYY LT'

    moment.defineLocale 'de-short',
      calendar:
        lastDay: '[Gestern,] LT'
        sameDay: '[Heute,] LT'
        nextDay: '[Morgen,] LT'
        lastWeek: '[letzten] dd[,] LT'
        nextWeek: '[nächsten] dd[,] LT'
        sameElse: 'll'
      longDateFormat:
        l: 'DD.MM.'
        LT: 'HH:mm'
        L: 'DD.MM.YYYY'
        LL: 'D. MMMM YYYY'
        LLL: 'D. MMMM YYYY LT'
        LLLL: 'dddd, D. MMMM YYYY LT'

am I doing something wrong?

**Comment by mj1856** [comment]
Your sample appears to be missing a lot of punctuation   `(`, `)`, `,`, `{`, `}`, etc.

Also, `defineLocale` is usually used from a language definition file within moment itself.  you might just be looking for [locale customization](http://momentjs.com/docs/#/customization/).

**Comment by antpaw** [comment]
sorry it's coffescript.

i've cloned the repo and wrote this test to clear things up a bit:

```js
test('moment().locale inherited', function (assert) {
    var months, monthsShort, processRelativeTime, weekdays, weekdaysMin, weekdaysShort;

    processRelativeTime = function(number, withoutSuffix, key) {
      var format;
      format = {
        m: ['eine Minute', 'einer Minute'],
        h: ['eine Stunde', 'einer Stunde'],
        d: ['ein Tag', 'einem Tag'],
        dd: [number + ' Tage', number + ' Tagen'],
        M: ['ein Monat', 'einem Monat'],
        MM: [number + ' Monate', number + ' Monaten'],
        y: ['ein Jahr', 'einem Jahr'],
        yy: [number + ' Jahre', number + ' Jahren']
      };
      if (withoutSuffix) {
        return format[key][0];
      } else {
        return format[key][1];
      }
    };

    months = 'Januar_Februar_März_April_Mai_Juni_Juli_August_September_Oktober_November_Dezember'.split('_');
    monthsShort = 'Jan._Febr._Mrz._Apr._Mai_Jun._Jul._Aug._Sept._Okt._Nov._Dez.'.split('_');
    weekdays = 'Sonntag_Montag_Dienstag_Mittwoch_Donnerstag_Freitag_Samstag'.split('_');
    weekdaysShort = 'So._Mo._Di._Mi._Do._Fr._Sa.'.split('_');
    weekdaysMin = 'So_Mo_Di_Mi_Do_Fr_Sa'.split('_');

    moment.defineLocale('de', {
      longDateFormat: {
        LT: 'HH:mm [Uhr]',
        L: 'DD.MM.YYYY',
        LL: 'D. MMMM YYYY',
        LLL: 'D. MMMM YYYY LT',
        LLLL: 'dddd, D. MMMM YYYY LT'
      },
      calendar: {
        lastDay: '[Gestern um] LT',
        sameDay: '[Heute um] LT',
        nextDay: '[Morgen um] LT',
        lastWeek: '[letzten] dddd',
        nextWeek: 'dddd [um] LT',
        sameElse: 'LL'
      },
      relativeTime: {
        future: 'in %s',
        past: 'vor %s',
        s: 'ein paar Sekunden',
        m: processRelativeTime,
        mm: '%d Minuten',
        h: processRelativeTime,
        hh: '%d Stunden',
        d: processRelativeTime,
        dd: processRelativeTime,
        M: processRelativeTime,
        MM: processRelativeTime,
        y: processRelativeTime,
        yy: processRelativeTime
      },
      ordinalParse: /\d{1,2}\./,
      ordinal: '%d.',
      week: {
        dow: 1,
        doy: 4
      }
    });

    moment.locale('de-long', {
      longDateFormat: {
        LT: 'HH:mm [Uhr]',
        L: 'DD.MM.YYYY',
        LL: 'D. MMMM YYYY',
        LLL: 'D. MMMM YYYY LT',
        LLLL: 'dddd, D. MMMM YYYY LT'
      }
    });

    var mLong = moment();
    mLong.locale('de-long');
    assert.equal(mLong.format('dddd'), moment().locale('de').format('dddd'));
});

````

result is:

````
Module: locale Test: moment().locale inherited
    at Object.<anonymous> (/Users/antpaw/Projects/github/moment/build/umd/test/moment/locale.js:587:16)
Actual value:
Wednesday
Expected value:
Mittwoch
````

looks like mLong is not inheriting the de locales

**Comment by antpaw** [comment]
Thanks 2.12.0 solved this with `parentLocale `
