### ISSUE TITLE
(Simple) bug in parsing a date with 3 vs 4 years

### ISSUE THREAD

**Issue by Karolusrex** [moment/moment#2924]
Using moment 2.11.1:

```
new moment('04/02/201', 'DD/MM/YYYY').isValid()
true
```

Is this expected behavior? I also get:

```
new moment('Marbrary', 'MMMM').isValid()
true
```

**Comment by mj1856** [comment]
On the first one - yes, this is valid, as year 201 is acceptable in the proleptic Gregorian calendar.  You could use the strict parsing mode to enforce four digits:

```javascript
moment('04/02/201', 'DD/MM/YYYY', true).isValid()  // false
```

For the second one, I get false in my tests.

Also, don't use the `new` operator.  Just call `moment` as a function.
