### ISSUE TITLE
Locale-aware weekdays are not working

### ISSUE THREAD

**Issue by polkovnikov-ph** [moment/moment#2926]
In `ru_ru` locale `moment().day(0).format();` shows the last Sunday, while in Russia week starts in Monday.

**Comment by mj1856** [comment]
Per [the docs](http://momentjs.com/docs/#/get-set/day/), the `day` function always numbers Sunday as 0 through Saturday as 6.

Use `weekday` instead, which [is locale aware](http://momentjs.com/docs/#/get-set/weekday/).
