### ISSUE TITLE
Locale-aware moment.weekdays* methods

### ISSUE THREAD

**Issue by polkovnikov-ph** [moment/moment#2927]
How do I get list of weekdays in proper locale-aware order?

**Comment by sokolovstas** [comment]
+1 for now I have only this workaround
```
this.weekdays = moment.weekdaysMin();
this.weekdays.push(this.weekdays.shift());
```

**Comment by mj1856** [comment]
Seems like there should be an option to pass a boolean `true` to `moment.weekdays()` (and similar functions.  The docs even call this out:

> Note: Currently, weekdays always have Sunday as index 0, regardless of the local first day of the week.

You can use `moment.localeData().firstDayOfWeek()` to determine the first day of the week, but it seems like this should be a built-in option.

**Comment by mj1856** [comment]
Note to potential implementers: Existing setter functionality must be preserved.  Test if value is a boolean or a number.

**Comment by Changron** [comment]
I'll take this one.
Just to make sure,
```
moment.weekdays(boolean, index)
```
Is it ok to let the boolean be the first parameter?
Btw, should I add a unit test of it?

**Comment by komalg** [comment]
I am using 2.14.1 version of moment in my AngularJs project.
I tried moment.localeData().firstDayOfWeek() to get first day of week for a region (being local specific). firstDayOfWeek() method cannot be recognised it seems.

**Comment by seven-cd** [comment]
Not sure how to implement this?
This gives error:

`moment().locale('hr').localeData().weekdays(true)`

**Comment by seven-cd** [comment]
I just saw it was never merged.
