### ISSUE TITLE
Moment in and require ('node-xlsx') with the use of a problem

### ISSUE THREAD

**Issue by thinkive** [moment/moment#2930]
I use require ('node-xlsx') to read the xlsx file, the file contains the date, and now the problem is:
If xlsx document as a whole there is only a date column, then parsed using moment no problem, if the document inside more than two columns, then all dates are resolved to 1970-01-01 format, I would like to ask is what causes?
For example:
2015/12/1 2015/12/1
Moment (param[0]).Format ('YYYY-MM-DD') parameter param[1] for the acquisition of the cell date
If the entire document is only one column, then no problem
If used again
Moment (param[1]).Format ('YYYY-MM-DD') on the emergence of 1970-01-01 as

**Comment by thinkive** [comment]
There is only one date format in the document, then there is no problem to deal with, if more than one column, then all the dates are treated as 1970-01-01

**Comment by mj1856** [comment]
Try `console.log(param[1])` and see what the output is.

**Comment by mj1856** [comment]
Also note JavaScript is case sensitive.  Please post the real code, with the real example value.  Thanks.

**Comment by thinkive** [comment]
code:	console.log("~~~~~~~"+param[1]+"~~~~~~~"+moment(param[1]).format('YYYY-MM-DD'))
	       console.log("!!!!!"+param[2]+"!!!!!!!!"+moment(param[2]).format('YYYY-MM-DD'))

console:    server-0 [2016-02-03 15:41:07.729] [INFO] console - ~~~~~~~41459~~~~~~~1970-01-01
                  server-0 [2016-02-03 15:41:07.731] [INFO] console - !!!!!41462!!!!!!!!1970-01-01

**Comment by maggiepint** [comment]
Is this still an issue?

**Comment by thinkive** [comment]
Yes, it's still a issue.

**Comment by mj1856** [comment]
Sorry for the delayed response.  Missed my inbox somehow.

Since your values (`41459`, `41462`, etc.) look like OLE Automation Dates, you should probably use the [MSDate Plugin](http://momentjs.com/docs/#/plugins/msdate/).  This plugin also properly accounts for nuances with how time is represented as decimals.

```javascript
moment.fromOADate(41459)
```

Though if you're only ever working with whole dates, it may be reasonable enough to use:

```javascript
moment('1899-12-30').add(41459, 'days')
````
