### ISSUE TITLE
Possible to get week number relative to month?

### ISSUE THREAD

**Issue by raistlinthewiz** [moment/moment#2934]
week() returns the week number according to year, what i'd like to get is week number relative to month. Is it possible?

**Comment by mj1856** [comment]
It's not built-in, but basically you can subtract the week number of the start of the month from the week number of the date in question.

```javascript
function weekOfMonth(m) {
  return m.week() - moment(m).startOf('month').week() + 1;
}
```

Note that `week` function is locale specific, so in some cases you might want to use `isoWeek` instead.  (See the docs).

**Comment by mj1856** [comment]
If someone wants to add this to moment, a PR with the above function (or similar) and related unit tests would be appreciated.

**Comment by mj1856** [comment]
Tracking in PR #2965.  Thanks!

**Comment by InstanceOfMichael** [comment]
What about adding this ability to `format` function?

**Comment by Knjaz89** [comment]
> It's not built-in, but basically you can subtract the week number of the start of the month from the week number of the date in question.
> 
> ```js
> function weekOfMonth(m) {
>   return m.week() - moment(m).startOf('month').week() + 1;
> }
> ```
> 
> Note that `week` function is locale specific, so in some cases you might want to use `isoWeek` instead. (See the docs).
moment("2018-12-31") -> weekOfMonth = -48

**Comment by eitanfr** [comment]
In some years `week()` will return 1 for the last days of the year, see [#4019](https://github.com/moment/moment/issues/4019). So it messes up the calculations as @Knjaz89 mentioned.

Therefore the right way to calculate the weekOfMonth is:

```javascript
function weekOfMonth(date) {
  let weekInYearIndex = date.week();
   if (date.year() !== date.weekYear()) {
	weekInYearIndex = date.clone().subtract(1,'week').week() + 1;
    }
    const weekIndex = weekInYearIndex - moment(date).startOf('month').week() + 1;
  }

weekOfMonth(moment('2018-12-31T00:00:00.000Z')); // return 6
weekOfMonth(moment('2019-01-01T00:00:00.000Z')); // return 1
```

**Comment by samslow** [comment]
It up a 2020, weekly index it was difficult to calculate the number,
but settled with the help of the @eitanfr 
Thank you.

**Comment by M7Arman** [comment]
I did it in this way:
```js
const weekOfMonth = (date) => {
    const dayInMonth = moment(date).date();
    return Math.floor(dayInMonth / 7);
}
```

**Comment by M7Arman** [comment]
> In some years `week()` will return 1 for the last days of the year, see [#4019](https://github.com/moment/moment/issues/4019). So it messes up the calculations as @Knjaz89 mentioned.
> 
> Therefore the right way to calculate the weekOfMonth is:
> 
> ```js
> function weekOfMonth(date) {
>   let weekInYearIndex = date.week();
>    if (date.year() !== date.weekYear()) {
> 	weekInYearIndex = date.clone().subtract(1,'week').week() + 1;
>     }
>     const weekIndex = weekInYearIndex - moment(date).startOf('month').week() + 1;
>   }
> 
> weekOfMonth(moment('2018-12-31T00:00:00.000Z')); // return 6
> weekOfMonth(moment('2019-01-01T00:00:00.000Z')); // return 1
> ```

For 02.01.2020 it will return -52, so I fixed that case:
function getWeekOfMonth(dateObj) {
    const date = m(dateObj);
    const weekInYear = date.isoWeek();
    const result = weekInYear - date.startOf('month').isoWeek();

    return result < 0 ? weekInYear : result;
}

**Comment by daniaaalarshad** [comment]
> It's not built-in, but basically you can subtract the week number of the start of the month from the week number of the date in question.
> 
> ```js
> function weekOfMonth(m) {
>   return m.week() - moment(m).startOf('month').week() + 1;
> }
> ```
> 
> Note that `week` function is locale specific, so in some cases you might want to use `isoWeek` instead. (See the docs).

Awesome (y)

**Comment by michaelhayman** [comment]
FYI @M7Arman doesn't work for `2020-08-30`, your function reports week 4, but we're in week 6.

**Comment by daniaaalarshad** [comment]
> FYI @M7Arman doesn't work for `2020-08-30`, your function reports week 4, but we're in week 6.

@michaelhayman you mean we are in week 5 ?

**Comment by Assem-Hafez** [comment]
This doesn't work if the last week of month is common with next yeah e.g. 31 Dec 2020 is Tuesday  and its is considered week 1 in the new year.
this was my solution to the problem
`
function getWeekIndexInMonth(day) {
  const startOfMonth = moment(day).startOf('month');
  const endOfMonth = moment(day).endOf('month');

  let currentMomentDate = moment(startOfMonth);
  const weeks = [];
  while (currentMomentDate.isBefore(endOfMonth)) {
    weeks.push(currentMomentDate.week());
    currentMomentDate.add(1, "weeks").startOf("week");
  }
  return weeks.indexOf(day.week())
}
`

**Comment by behrangsa** [comment]
> ```js
> function weekOfMonth(m) {
>   return m.week() - moment(m).startOf('month').week() + 1;
> }
> ```

Just FYI, if I don't set the locale I get unexpected results.

Here's an example where I don't set the locale and I get unexpected results (negative week of months):

```js
import moment from "moment";

function weekOfMonth(m) {
    return m.week() - moment(m).startOf('month').week() + 1;
}

const m = moment();
m.set({year: 2021, month: 11, date: 1}); // (months are 0-based, days are 1-based)

const decNumDays = m.daysInMonth();
console.log("Number of days in December:", decNumDays);

const result = [];
for (let date = 1; date <= decNumDays; date++) {
    m.set('date', date);
    result.push({
        dayName: m.format("dddd"),
        dayOfMonth: date,
        weekOfMonth: weekOfMonth(m)
    })
}

console.log(result)
```

Result:

```js
[
  { dayName: 'Wednesday', dayOfMonth: 1, weekOfMonth: 1 },
  { dayName: 'Thursday', dayOfMonth: 2, weekOfMonth: 1 },
  { dayName: 'Friday', dayOfMonth: 3, weekOfMonth: 1 },
  { dayName: 'Saturday', dayOfMonth: 4, weekOfMonth: 1 },
  { dayName: 'Sunday', dayOfMonth: 5, weekOfMonth: 2 },
  { dayName: 'Monday', dayOfMonth: 6, weekOfMonth: 2 },
  { dayName: 'Tuesday', dayOfMonth: 7, weekOfMonth: 2 },
  { dayName: 'Wednesday', dayOfMonth: 8, weekOfMonth: 2 },
  { dayName: 'Thursday', dayOfMonth: 9, weekOfMonth: 2 },
  { dayName: 'Friday', dayOfMonth: 10, weekOfMonth: 2 },
  { dayName: 'Saturday', dayOfMonth: 11, weekOfMonth: 2 },
  { dayName: 'Sunday', dayOfMonth: 12, weekOfMonth: 3 },
  { dayName: 'Monday', dayOfMonth: 13, weekOfMonth: 3 },
  { dayName: 'Tuesday', dayOfMonth: 14, weekOfMonth: 3 },
  { dayName: 'Wednesday', dayOfMonth: 15, weekOfMonth: 3 },
  { dayName: 'Thursday', dayOfMonth: 16, weekOfMonth: 3 },
  { dayName: 'Friday', dayOfMonth: 17, weekOfMonth: 3 },
  { dayName: 'Saturday', dayOfMonth: 18, weekOfMonth: 3 },
  { dayName: 'Sunday', dayOfMonth: 19, weekOfMonth: 4 },
  { dayName: 'Monday', dayOfMonth: 20, weekOfMonth: 4 },
  { dayName: 'Tuesday', dayOfMonth: 21, weekOfMonth: 4 },
  { dayName: 'Wednesday', dayOfMonth: 22, weekOfMonth: 4 },
  { dayName: 'Thursday', dayOfMonth: 23, weekOfMonth: 4 },
  { dayName: 'Friday', dayOfMonth: 24, weekOfMonth: 4 },
  { dayName: 'Saturday', dayOfMonth: 25, weekOfMonth: 4 },
  { dayName: 'Sunday', dayOfMonth: 26, weekOfMonth: -47 },
  { dayName: 'Monday', dayOfMonth: 27, weekOfMonth: -47 },
  { dayName: 'Tuesday', dayOfMonth: 28, weekOfMonth: -47 },
  { dayName: 'Wednesday', dayOfMonth: 29, weekOfMonth: -47 },
  { dayName: 'Thursday', dayOfMonth: 30, weekOfMonth: -47 },
  { dayName: 'Friday', dayOfMonth: 31, weekOfMonth: -47 }
]

```

And here's an example where I get correct results when I set the locale:

```js
import moment from "moment";

moment.locale('en-au');

function weekOfMonth(m) {
    return m.week() - moment(m).startOf('month').week() + 1;
}

const m = moment();
m.set({year: 2021, month: 11, date: 1}); // (months are 0-based, days are 1-based)

const decNumDays = m.daysInMonth();
console.log("Number of days in December:", decNumDays);

const result = [];
for (let date = 1; date <= decNumDays; date++) {
    m.set('date', date);
    result.push({
        dayName: m.format("dddd"),
        dayOfMonth: date,
        weekOfMonth: weekOfMonth(m)
    })
}

console.log(result)
```

Result:

```js
[
  { dayName: 'Wednesday', dayOfMonth: 1, weekOfMonth: 1 },
  { dayName: 'Thursday', dayOfMonth: 2, weekOfMonth: 1 },
  { dayName: 'Friday', dayOfMonth: 3, weekOfMonth: 1 },
  { dayName: 'Saturday', dayOfMonth: 4, weekOfMonth: 1 },
  { dayName: 'Sunday', dayOfMonth: 5, weekOfMonth: 2 },
  { dayName: 'Monday', dayOfMonth: 6, weekOfMonth: 2 },
  { dayName: 'Tuesday', dayOfMonth: 7, weekOfMonth: 2 },
  { dayName: 'Wednesday', dayOfMonth: 8, weekOfMonth: 2 },
  { dayName: 'Thursday', dayOfMonth: 9, weekOfMonth: 2 },
  { dayName: 'Friday', dayOfMonth: 10, weekOfMonth: 2 },
  { dayName: 'Saturday', dayOfMonth: 11, weekOfMonth: 2 },
  { dayName: 'Sunday', dayOfMonth: 12, weekOfMonth: 3 },
  { dayName: 'Monday', dayOfMonth: 13, weekOfMonth: 3 },
  { dayName: 'Tuesday', dayOfMonth: 14, weekOfMonth: 3 },
  { dayName: 'Wednesday', dayOfMonth: 15, weekOfMonth: 3 },
  { dayName: 'Thursday', dayOfMonth: 16, weekOfMonth: 3 },
  { dayName: 'Friday', dayOfMonth: 17, weekOfMonth: 3 },
  { dayName: 'Saturday', dayOfMonth: 18, weekOfMonth: 3 },
  { dayName: 'Sunday', dayOfMonth: 19, weekOfMonth: 4 },
  { dayName: 'Monday', dayOfMonth: 20, weekOfMonth: 4 },
  { dayName: 'Tuesday', dayOfMonth: 21, weekOfMonth: 4 },
  { dayName: 'Wednesday', dayOfMonth: 22, weekOfMonth: 4 },
  { dayName: 'Thursday', dayOfMonth: 23, weekOfMonth: 4 },
  { dayName: 'Friday', dayOfMonth: 24, weekOfMonth: 4 },
  { dayName: 'Saturday', dayOfMonth: 25, weekOfMonth: 4 },
  { dayName: 'Sunday', dayOfMonth: 26, weekOfMonth: 5 },
  { dayName: 'Monday', dayOfMonth: 27, weekOfMonth: 5 },
  { dayName: 'Tuesday', dayOfMonth: 28, weekOfMonth: 5 },
  { dayName: 'Wednesday', dayOfMonth: 29, weekOfMonth: 5 },
  { dayName: 'Thursday', dayOfMonth: 30, weekOfMonth: 5 },
  { dayName: 'Friday', dayOfMonth: 31, weekOfMonth: 5 }
]
```
