### ISSUE TITLE
Error to format 'GGGG'

### ISSUE THREAD

**Issue by hucharal** [moment/moment#2937]
The error occurs when we show the following dates in format 'GGGG':

- moment('2015-01-01', 'YYYY-MM-DD') 

- moment('2015-01-02', 'YYYY-MM-DD')

- moment('2015-01-03', 'YYYY-MM-DD')

fiddle: https://jsfiddle.net/sa4axxkx/

**Comment by mattgrande** [comment]
> moment('2015-01-01', 'YYYY-MM-DD').format('GGGG')
    "2015"

Not sure what the issue is?

**Comment by MrGeneric** [comment]
`moment('2016-01-01', 'YYYY-MM-DD').format('GGGG')`

I'm seeing the above display 2015 as the year, rather than 2016.

**Comment by hucharal** [comment]
Yes, @MrGeneric you are sure. The erros occurs for the following examples:

`moment('2016-01-01', 'YYYY-MM-DD').format('GGGG');`
`moment('2016-01-02', 'YYYY-MM-DD').format('GGGG');`
`moment('2016-01-03', 'YYYY-MM-DD').format('GGGG');`

In all of these, the result is 2015, instead of 2016

**Comment by mattgrande** [comment]
I _believe_ this is expected. `GGGG` is the ISO week number. From here: https://en.wikipedia.org/wiki/ISO_week_date

> The first week of a year is the week that contains the first Thursday of the year (and, hence, always contains 4 January). ISO week year numbering therefore slightly deviates from the Gregorian for some days close to 1 January.

The first, second, and third day of 2016 were therefore in 2015 by week number. If you want the "true" year, use `YYYY`.

**Comment by hucharal** [comment]
Ok @mattgrande thanks!

**Comment by mj1856** [comment]
Yes.  Thanks @mattgrande.
