### ISSUE TITLE
Language Telugu is spelt incorrectly in http://momentjs.com/

### ISSUE THREAD

**Issue by grbbabu** [moment/moment#2941]
![screen shot 2016-02-03 at 12 22 52 pm](https://cloud.githubusercontent.com/assets/13711648/12770037/1918ff60-ca71-11e5-9259-314de3735604.png)
Hi,

Please change 'Tegulu' to 'Telugu'.

Thanks,
Ramesh

**Comment by kcthota** [comment]
Yes, in fact I also came here to log the same issue.

**Comment by mj1856** [comment]
Fixed in moment/momentjs.com#262

Thanks.

**Comment by mj1856** [comment]
(Will go live in the next website build)
