### ISSUE TITLE
Getting NaN when asking for the week of the year.

### ISSUE THREAD

**Issue by sandokanelcojo** [moment/moment#2944]
Hi, I'm getting NaN when doing the following:

`
let year = 2014;
let lastWeek = moment([year, 12, 31]).week();
// lastWeek = NaN;
`

But this works instead:
`
let year = 2014;
let lastWeek = moment().year(year).endOf('year').week();
// lastWeek = 1;
`

To solve the last week of the year being 1 I just do the following, but this is actually out of the scope of the bug report...
`
lastWeek = (lastWeek < 3) ? moment().year(year).endOf('year').add(-7, 'days').week() : lastWeek ;
// lastWeek = 51;
`

Note that I'm in the GMT +1 Zone and for me the week starts on Monday

Cheers

**Comment by mj1856** [comment]
Like the `Date` object, months are 0-11 when passed as an array of values, or through the `month` function.  December is month 11.
