### ISSUE TITLE
moment().format('wo') doesn't work correctly

### ISSUE THREAD

**Issue by VeraWei** [moment/moment#2949]
I update the latest version (2.11.~) andformat('wo') doesn't work correctly in local 'zh'

```javascript
function makeFormatFunction(format) {
    var array = format.match(formattingTokens), i, length;

    for (i = 0, length = array.length; i < length; i++) {
        if (formatTokenFunctions[array[i]]) {
            array[i] = formatTokenFunctions[array[i]];
        } else {
            array[i] = removeFormattingTokens(array[i]);
        }
    }

    return function (mom) {
        var output = '';
        for (i = 0; i < length; i++) {
          output += array[i] instanceof Function ? array[i].call(mom, format) : array[i];
        }
        return output;
    };
}
```

I think this code here has some thing wrong. see the console panel. Please checkout. Thanks.
![screen shot 2016-02-05 at 10 31 01 am](https://cloud.githubusercontent.com/assets/7732663/12836622/a437be6c-cbf5-11e5-938e-62a3fe9f3e07.png)

**Comment by mj1856** [comment]
A couple of things:
- What specific version of moment are you running?  You said `2.11.~` do you mean 2.11.0, 2.11.1, or 2.11.2?  Did you try in the current version?
- Instead of posting code from moment and screenshots, please post code that reproduces the problem.  I tried `moment().locale('zh').format('wo')` and it worked.  I can't tell from your screenshot how the `mom` variable was created.

Thanks.

**Comment by TheVirtualMachinist** [comment]
`moment('12/31/2015','MM/DD/YYYY').format('YYYY-ww');`

**Result in console:**
`"2015-01"`

This is clearly not correct...

**Comment by mj1856** [comment]
Sorry for the delayed response.

Take a look at the chart here: http://momentjs.com/docs/#/displaying/format/

When working with week numbers, you should be using the "week year" formats.

```javascript
moment('12/31/2015','MM/DD/YYYY').format('gggg-ww');  // locale-based weeks
moment('12/31/2015','MM/DD/YYYY').format('GGGG-WW');  // ISO weeks

moment('12/31/2015','MM/DD/YYYY').format('gggg-wo');  // locale-based weeks
moment('12/31/2015','MM/DD/YYYY').format('GGGG-Wo');  // ISO weeks
```
