### ISSUE TITLE
Allow moment.calendar to support more options

### ISSUE THREAD

**Issue by amk221** [moment/moment#2952]
Often I want to display a date with more detail as it gets progressively older.
```javascript
moment.calendar(null, {
  sameDay:   '[Today]',          // Today
  lastDay:   '[Yesterday]',      // Yesterday
  nextDay:   '[Tomorrow]',       // Tomorrow
  sameMonth: 'ddd, D',           // Fri, 5
  sameYear:  'ddd, D MMM',       // Fri, 5 Feb
  sameElse:  'ddd, D MMM YYYY'   // Fri, 5 Feb 2015
});
```

**Comment by mj1856** [comment]
Yes, I agree.  Adding `sameMonth` and `sameYear` options make sense.

A PR would be appreciated.  Please include unit tests.

**Comment by niklabh** [comment]
PR for issue

https://github.com/moment/moment/pull/2996

please discuss.

**Comment by niklabh** [comment]
@mj1856 Please have a look.

**Comment by maggiepint** [comment]
Closing this issue in favor of open pull request #2996
