### ISSUE TITLE
weekYear and isoWeekYear getters both return the year

### ISSUE THREAD

**Issue by mheitzibm** [moment/moment#2957]
I'm using version 2.11.2.  The weekYear and isoWeekYear getters both return the year.

```
var moment = require('moment');
var feb8 = moment(new Date('Feb 8 2016'));
console.log(feb8.year() + ' ' + feb8.weekYear() + ' ' + feb8.isoWeekYear());
```
This prints 2016 2016 2016

**Comment by mj1856** [comment]
Yes, that's correct.  See the description [in the docs](http://momentjs.com/docs/#/get-set/week-year/).

You may have been looking for the week *number* of the year, which are `week()` and `isoWeek()` ([docs here](http://momentjs.com/docs/#/get-set/week/).)

**Comment by mheitzibm** [comment]
Thanks, sorry I missed that.  You're right I was looking for isoWeek.  For what it's worth, I did look at the docs for isoWeekYear before opening this, but it's just a link to a Wikipedia page that covers a lot of topics.  Might help unobservant people like me if you add a sentence to define the term.
