### ISSUE TITLE
diff between hours in the same timezone

### ISSUE THREAD

**Issue by fredguth** [moment/moment#2960]
I have a variable called **now** that is

`o {_isAMomentObject: true, _isUTC: false, _pf: Object, _locale: t, _d: Thu Feb 11 2016 18:22:36 GMT-0200 (BRST)…}`

an another called **then** 

`o {_isAMomentObject: true, _i: Thu Feb 11 2016 18:20:29 GMT-0200 (BRST), _isUTC: false, _pf: Object, _locale: t…}

I am trying to diff this 2 moments:

```
moment(now.diff(then)).format('HH:mm:ss')
"21:02:07"
```
Why 21? shouldn't it be only 00:02:07?  What is my mistake?

**Comment by mj1856** [comment]
There's not enough detail in what you provided to say, as most of the values are collapsed.  The underscore-prefixed fields are internal anyway.  Could you either fully expand the objects, or preferably, give example code that reproduces the problem using only the public API.  Thanks.

**Comment by mj1856** [comment]
Closing due to lack of response, but will reopen if you can provide more detail.  Thanks.
