### ISSUE TITLE
locale changes does'nt work

### ISSUE THREAD

**Issue by titimoby** [moment/moment#2962]
When I try to change the locale value, nothing happens, not even error.

```
      this.$log.log(moment.locale()); // returns 'en'
      this.$log.log(moment.locale('fr')); // set to french but returns 'en'
      this.$log.log(moment.locale()); // of course, still returns 'en' instead of 'fr'
```
I also tried from the Chrome developer tools console:
```
> moment.locale('fr')
-> "en"
```

**Comment by elwynelwyn** [comment]
Are you using a module loader that may be giving you a different instance of moment?

    import m from 'moment';

    this.$log.log(m.locale());
    this.$log.log(m.locale('fr'));
    this.$log.log(m.locale());

    this.$log.log(window.moment.locale());
    this.$log.log(window.moment.locale('is'));
    this.$log.log(window.moment.locale());

**Comment by titimoby** [comment]
I'm in an angular project, modules are handles with JSPM.
I don't understand what you mean by " that may be giving you a different instance of moment"

The 3 lines are real code I tried, using the same moment in the same method.
I have the same result if I use a specific variable.

```
import * as moment from 'moment';

export function registerDateFormatService(appModule: angular.IModule) {
   appModule.service('dateFormatService', DateFormatService);
}

export class DateFormatService {
   constructor(private $log: ng.ILogService) {
   }

   public format(value: moment.Moment, displayFormat: string): string {
      this.$log.log(value.locale());
      this.$log.log(value.locale('fr'));
      this.$log.log(value.locale());
      return value.format(displayFormat);
   }
}
```

results are : 
```
en
angular.js:13239 Moment {_isAMomentObject: true, _i: "2010-10-20 4:30", _f: "YYYY-MM-DD", _isUTC: false, _pf: Object…}_d: Wed Oct 20 2010 00:00:00 GMT+0200 (CEST)_f: "YYYY-MM-DD"_i: "2010-10-20 4:30"_isAMomentObject: true_isUTC: false_isValid: true_locale: Locale_abbr: "en"_ordinalParse: /\d{1,2}(th|st|nd|rd)/_ordinalParseLenient: /\d{1,2}(th|st|nd|rd)|\d{1,2}/ordinal: (number)__proto__: Locale_pf: Object__proto__: Moment
angular.js:13239 en
```

**Comment by mj1856** [comment]
Are you importing the locale data? Which .js file(s) are you using?

**Comment by titimoby** [comment]
Do you mean adding another import after the line:
import * as moment from 'moment';

or import in the module sens, here with JSPM.
(I have moment.js and a lot of what looks  like localexx.js like fr.js in my case.)

**Comment by mj1856** [comment]
Read through the ["Where to use it"](http://momentjs.com/docs/#/use-it/) section of the docs and see if any of those scenarios apply to you.  In general, you either need to be using `moment-with-locales.js`, or have loaded the locale data separately.  Most loaders will not automatically pick up the language file, so you may need to import them separately.

Basically, if you try to switch to a locale that's not loaded, moment will revert to the `en` locale.

**Comment by mj1856** [comment]
See also ["Loading locales in the browser"](http://momentjs.com/docs/#/i18n/loading-into-browser/).

**Comment by titimoby** [comment]
I'll experiment what I can whith this.
I'm using a simple line added to package.json with is then used by jspm through npm install
`"moment": "github:moment/moment@^2.11.2"`

I then use it with a single import:
`import * as moment from 'moment';`

I write it in this comment to keep a track for future users who may have the same usage.
I'll post the result of my experiments.
Thanks

**Comment by titimoby** [comment]
I added:
`import 'moment/locale/fr';`

and using:
`moment.locale('fr')`

now sets properly the locale to french.
It is not dynamic but it will do the job for now.

I can close it I think and thanks for all people who answered.
Hope this issue will help people using TypeScript/Angular/Jspm.

**Comment by sbaechler** [comment]
Maybe add this to the documentation. I had the same issue and more and more people start using jspm instead of Bower.

**Comment by mj1856** [comment]
Glad you got it working!  I added an issue to the docs repo.  Feel free to send a PR there.

**Comment by younss** [comment]
import like that
import 'moment/src/locale/fr-ca';
import 'moment/src/locale/en-ca';

**Comment by vanjiminster** [comment]
Thanks @younss, your method worked for me. I'm using Ionic 2 RC 2.

**Comment by dialnco** [comment]
@younss you are my savior! it's 10/10/2017 and the docs don't specify this change! updated from moment 2.18 to 2.19.0 and locales imports completely crashed :(
Using React.
Thanks again!

**Comment by sgj0** [comment]
I had the same problem when I upgraded to the 2.19.1
Maybe this could help:

Remove :
- node_modules folder
- package-lock.json

Re-launch: 
npm install

This worked for me.

**Comment by Vitegor** [comment]
@younss, thanks , works for me, i am using parcel-bundler

**Comment by javiersm79** [comment]
This Solution Worked for me.. [Here](https://github.com/moment/moment/issues/2962#issuecomment-185637815)

**Comment by Hypenate** [comment]
Did this change again?
I installed:
```
npm i moment-with-locales-es6
npm i moment
```

I created a class with one function:
```
import * as moment from 'moment';
import 'moment/locale/pt-br';
import 'moment/locale/fr-ca';

export class DatetimeFormatPipe
    transform(date: string): string {
        moment.locale('pt-BR');
        console.log(moment.locale()); 
        console.log('pt-BR', moment(date).toLocaleString());

        moment.locale('fr-CA');
        console.log(moment.locale());
        console.log('fr-CA', moment(date).toLocaleString());

        return "";
    }
}
```
The logs are as follows:

> pt-br
> pt-BR Tue Dec 20 2016 10:45:12 GMT+0100
> fr-ca
> fr-CA Tue Dec 20 2016 10:45:12 GMT+0100

**Comment by JeongtaekLim** [comment]
> import like that
> import 'moment/src/locale/fr-ca';
> import 'moment/src/locale/en-ca';

It works for me thanks!

**Comment by ligne13** [comment]
I use:
```
import moment from 'moment/dist/moment';
import fr from 'moment/dist/locale/fr';

moment.locale('fr', fr);
```
and it works.
Other solutions did not work for me.

**Comment by socketpair** [comment]
```js
import moment from 'moment/dist/moment';
import 'moment/dist/locale/ru';

moment.locale('ru');
```

The only works for me.

moment 2.25.2

**Comment by pbrissaud** [comment]
Hi,

When using 'import 'moment/locale/fr';' in my Node/Express App, I got this error : **"SyntaxError: Cannot use import statement outside a module"**. 

I googled this and I try to add **--experimental-modules --es-module-specifier-resolution=node** flags but now my app is a mess. 

If I can't add this import, is there another way to change the locale ? 

Thanks

Paul

<hr>

**Specs :**
- OS : Ubuntu 20.04 through WSL2
- Node : 12.18.3
- NPM : 6.14.6
- Express : 4.16.1
- MomentJS : 2.27

**Comment by keatans** [comment]
merci pour info j'ai juste galéré pour les perme je me permet de partager mon exemple pour les moins doué comme moi lol
redemres est le nom de la ressource qui à le .lua avec un fichier resource.lua ou fxmanifest.lua (evidament pas vide 
      server_scripts { 'main.lua',} )
permission dans le  .cfg  j'ai préférais ajouter en admin en plus ( celons future projet)
add_ ace resource.redemres groupe.admin
add_ace resource.redemres command.restart allow
add_ace resource.redemres command.start allow
add_ace resource.redemres command.stop allow
                                     le main.lua
local delay = 1000 * 60 * 0,5 -- modifiez simplement ceci selon votre délai nécessaire (30 minutes dans cet exemple)
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(delay) 
        ExecuteCommand("restart  esx_ownedcarthief")
    end
end)
en tous cas merci ça fonctionne très bien si quelqu'un aurai une soluce pour lier avec la date et l heur du serveur (vps) pourrait permettre de créé des even't  programmé même absent il s 'allumerait a heurs et date et couperait de la même façon 
alors que la j allume à X min  et prévois X min avant le stop mais tous dois être prés avant redémarrage du serveur que l'autre soluce serai plus simple merci encor.
merci d avance a celui qui me trouvera cette soluce

**Comment by PandukaNandara** [comment]
Form 2022 onward you have to import as follows.

`import 'moment/dist/locale/si';`

**Comment by uanish** [comment]
using import 'moment/dist/locale/de', I get an error when reloading the page(export default hooks;SyntaxError: Unexpected token 'export')

**Comment by Dilshan97** [comment]
> import 'moment/locale/fr';

this is work for me

**Comment by StephanusDarellRanahita** [comment]
> I use:
> 
> ```
> import moment from 'moment/dist/moment';
> import fr from 'moment/dist/locale/fr';
> 
> moment.locale('fr', fr);
> ```

This one worked for me, thank you very much

**Comment by jose920405** [comment]
> > I use:
> > ```
> > import moment from 'moment/dist/moment';
> > import fr from 'moment/dist/locale/fr';
> > 
> > moment.locale('fr', fr);
> > ```
> 
> This one worked for me, thank you very much

```
node_modules/moment/dist/locale/de.js:7
import moment from '../moment';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
```

**Comment by Nikitoring** [comment]
> > > I use:
> > > ```
> > > import moment from 'moment/dist/moment';
> > > import fr from 'moment/dist/locale/fr';
> > > 
> > > moment.locale('fr', fr);
> > > ```
> > 
> > 
> > This one worked for me, thank you very much
> 
> ```
> node_modules/moment/dist/locale/de.js:7
> import moment from '../moment';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at internalCompileFunction (node:internal/vm:77:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1288:20)
>     at Module._compile (node:internal/modules/cjs/loader:1340:27)
> ```

I have same error
