### ISSUE TITLE
Russian day of week lowercase names

### ISSUE THREAD

**Issue by timeking** [moment/moment#2963]
In Russian language we use only lowercase day of week names. 
To fix it, need to change 2 lines:
https://github.com/moment/moment/blob/develop/locale/ru.js#L45
```
standalone: 'Воскресенье_Понедельник_Вторник_Среда_Четверг_Пятница_Суббота'.split('_'),
format: 'Воскресенье_Понедельник_Вторник_Среду_Четверг_Пятницу_Субботу'.split('_'),
```
with 
```
standalone: 'воскресенье_понедельник_вторник_среда_четверг_пятница_суббота'.split('_'),
format: 'воскресенье_понедельник_вторник_среду_четверг_пятницу_субботу'.split('_'),
```
For short names it possible to write day of week with uppercase letter. So, following two lines with shortnames can be unchanged.

**Comment by mj1856** [comment]
Dup #2882.  Thanks.
