### ISSUE TITLE
Suddenly getting 'Deprecation warning: moment construction falls back to js Date.' calculating difference

### ISSUE THREAD

**Issue by johnRivs** [moment/moment#2967]
It links to an issue here on the repo. I've read about it and from what I understood, it should work with the value my code is providing.

Here's what I'm doing:
```js
moment().subtract(moment("2016-02-17T02:57:59Z"))
```
That has been working perfectly, up until today. I haven't changed the version in `package.json`. I tried with the latest version just in case. I haven't changed my code either.

Why is it throwing the error now? Isn't that string supposed to be valid?

By the way, it doesn't stop the script from executing.

Edit: the stack trace is
```
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (/project/node_modules/moment/moment.js:850:105)
    at configFromInput (/project/node_modules/moment/moment.js:1485:32)
    at prepareConfig (/project/node_modules/moment/moment.js:1456:13)
    at createFromConfig (/project/node_modules/moment/moment.js:1423:44)
    at createLocalOrUTC (/project/node_modules/moment/moment.js:1505:16)
    at local__createLocal (/project/node_modules/moment/moment.js:1509:16)
    at create__createDuration (/project/node_modules/moment/moment.js:1870:41)
    at Moment.subtract (/project/node_modules/moment/moment.js:1940:19)
    at /project/commands/uptime.js:16:35
    at Request._callback (/project/node_modules/tmi.js/lib/api.js:49:13)
```

**Comment by MrGeneric** [comment]
```
> moment("2014-04-25T01:32:21.196Z");  // iso string, utc timezone
```

It looks like your date needs to be wrapped in quotes and possibly have a millisecond value preceding the Z to be considered valid.

**Comment by johnRivs** [comment]
Oh sorry, I copied it wrong. It comes from a variable.

The thing is, it's been working fine so far. I wonder why it changed just now.

**Comment by FrOz3n-** [comment]
+1 with the same problem on subtract()

**Comment by mj1856** [comment]
`subtract` is used with *elapsed time*, such as subtracting 5 minutes from now.

```javascript
moment().subtract(5, 'minutes')
```

It doesn't make sense to subtract one moment from another.  You probably want `diff`

```javascript
moment().diff(moment("2016-02-17T02:57:59Z"))
moment().diff("2016-02-17T02:57:59Z")
moment().diff(moment("2016-02-17T02:57:59Z"), 'seconds')
moment().diff("2016-02-17T02:57:59Z", 'seconds')
```

Any of the above are valid.  The default units are *milliseconds* when not specified.

**Comment by mj1856** [comment]
See docs:

http://momentjs.com/docs/#/manipulating/subtract/

http://momentjs.com/docs/#/displaying/difference/

**Comment by johnRivs** [comment]
Yeah, I went a second time through the docs and found about duration, now I'm doing `moment.duration(moment().diff("2016-02-17T02:57:59Z"))` which works fine.

I just found it weird, that it started throwing errors just now, after months of it working fine.

**Comment by jeffijoe** [comment]
I am getting the same deprecation warning, but when using `moment().subtract(Duration)`.

**Comment by zeeshanalisyed** [comment]
+1 having the same problem.

**Comment by richfergus** [comment]
I too am getting a warning but with isBefore() on "2014-04-25T01:32:21.196Z"
