### ISSUE TITLE
moment and es6

### ISSUE THREAD

**Issue by berdof** [moment/moment#2968]
I import module like this
`import moment from 'moment';`
So I am wondering if I can import only one function not a whole module. 
I mean something like this 
`import {diff, format} from 'moment';` . 
And also for me stays unclear how to change locale using es6? 
Is it possible with latest version of this library?

**Comment by twoixter** [comment]
@berdof I think it's not possible, mainly because of how moment works. Most of the functions are methods of the `moment()` object.

As for including locales, this is what I'm doing:

```javascript
import moment from "moment";
import locale_es from "moment/locale/es";

moment.locale("es", locale_es);
```

I think currently it's not possible to load all locales at once, which would be nice.

**Comment by mj1856** [comment]
See #2373.  Thanks.
