### ISSUE TITLE
Add 'date' as alias to 'day' unit for startOf() and endOf()

### ISSUE THREAD

**Issue by fastfedora** [moment/moment#2974]
The `startOf()` and `endOf()` functions take a unit of time, but don't accept `'date'` as a valid unit, instead using `'day'` to refer to the day of the month. This is inconsistent with other parts of the API that use `'date'` to refer to the day of the month. This inconsistency requires a special case when creating higher level functions that use both the `startOf()` function and other functions like `set()` where `'date'` is the appropriate unit.

**Comment by icambron** [comment]
Would accept a patch that makes both `date` and `day` work for those.

**Comment by datyayu** [comment]
Is anyone else working on this? If not, I would like to contribute.

**Comment by mj1856** [comment]
Tracking in PR #2982.  Thanks!
