### ISSUE TITLE
Remove tests from published NPM package

### ISSUE THREAD

**Issue by dthree** [moment/moment#2976]
The published NPM package is huge, > `4MB`.

When looking into this, the tests (2.5MB) are published!

Is there a reason for that? If not, can we ignore this from the NPM publish?

**Comment by mj1856** [comment]
Tests should have been ignored per #2528.  Can you verify you're talking about the current release (2.11.2)?

**Comment by dthree** [comment]
Whoops! It was `^2.0.0` release, so I assumed it was close to latest. Sorry about that!

**Comment by mj1856** [comment]
See also #2972 - with an additional exclusion to be made in the current release.  Thanks.

**Comment by dthree** [comment]
Thank you, that's great.
