### ISSUE TITLE
Feature request: ES6 have RegExp.escape(). So don't reinvent wheel.

### ISSUE THREAD

**Issue by socketpair** [moment/moment#2980]
I mean `src/lib/parse/regex.js` file

**Comment by mj1856** [comment]
A PR would be welcome.

**Comment by icambron** [comment]
Er...would still need a polyfill, right?

**Comment by socketpair** [comment]
Yes. Using babel is always require polyfill. Babel is configurable, so when nodejs/Chrome/FF/etc will support features without polyfill, we can configure Babel not to use polyfills/transformations for some features.

**Comment by maggiepint** [comment]
I"m removing up-for-grabs. At the moment Babel isn't in the project, so I don't know how this could be done before Tim gets done with that.

**Comment by icambron** [comment]
@ichernev mentioned elsewhere (I forget where) that we weren't using non-ES6 features other than modules. I took that to mean that we wouldn't use the Babel-supplied polyfills for those features; i.e. that the source code should be valid ES5+modules. I'm not sure I agree with that, but we should clear up what the rules are before doing this.

**Comment by ashsearle** [comment]
This issue should probably be closed.  The proposal for `RegExp.escape` was [rejected by TC39 a while ago](https://github.com/benjamingr/RegExp.escape/issues/37).
