### ISSUE TITLE
Tips to test for overlapping times

### ISSUE THREAD

**Issue by aHumanBeing** [moment/moment#2984]
I have 4 moments (start time 1 , end time 1, start time 2, end time 2).  Is there a simple solution using moment to test if the time from the first group overlaps with the time from the second group?  The time would be in YYYY-MM-DD hh:mm:ss.SSS A format btw.

Thanks

**Comment by icambron** [comment]
You could do it pretty easily with a couple of comparisons, but there's also [Twix](https://github.com/icambron/twix.js) for all your time range needs, including [overlaps()](http://isaaccambron.com/twix.js/docs.html#overlaps):

```js
var range1 = moment(startTime1).twix(endTime1);
var range2 = moment(startTime2).twix(endTime1);

range1.overlaps(range2);
```

**Comment by aHumanBeing** [comment]
Thank you.
