### ISSUE TITLE
Validate format strings

### ISSUE THREAD

**Issue by mj1856** [moment/moment#2987]
In [the docs for string + format](http://momentjs.com/docs/#/parsing/string-format/), we give an example of the forgiving parser using the format string, `h:hh A`.  The example should probably be changed to `h:mm A`, but it brings up an interesting point.  Since there's no possible _valid_ input that would have two separate hours components, then we should probably raise an error.  It's not that the input is invalid, it's that the format string is invalid.

Similarly, we could raise an error any time a format string matches conflicting or obviously absent elements.  This would catch common mistakes such as:

``` javascript
moment(input, 'YYYY-MM-DD HH:MM')  // used MM twice
moment(input, 'HH:mm A')  // used 24-hour time with a 12-hour meridem
moment(input, 'hh:mm')  // used 12-hour time without a meridem
moment(input, 'HH:mm:SS')  // used fractional seconds without whole seconds
```

etc...

We should probably only do this for parsing input, as it's perfectly valid to built output strings with the same element presented more than once.   If we do want to validate output format strings, it should be a much more minimal set of validation rules.

**Comment by icambron** [comment]
-1. This seems unnecessarily complicated. I get that there are some common confusions about the tokens (M vs m), but I think this will both be an implementation/maintenance burden and make managing users' expectations even harder.

**Comment by astorije** [comment]
To a lesser extent, I think it would be interesting to have a way to validate a string format on its own.

Right now, I am trying to check the validity of a format to be able to raise an error if it's invalid. Is there a way to do something like `moment.isFormatValid("HH:mm")`?

(Hey @icambron, hello from Cambridge! 👋😅)

**Comment by icambron** [comment]
@astorije :wave: I guess I'm wondering what conditions would make a format invalid?

**Comment by astorije** [comment]
I would say that if something is not [listed here](https://momentjs.com/docs/#/displaying/format/), it would be invalid. For example, `'hh:nm'` (likely typo) would be invalid.
Note that this comes with the following caveats:
- It might be very relevant to some given use cases (for example validating user-provided formats) but not to others (e.g. internal checks for the library itself?)
- I did a poor job at RTFM. In particular, if this format is based on a norm (ISO 8601?), I don't know it, and therefore I don't know if any character is considered valid per spec, and say, ignored, or used as literal characters.

Does that make more sense?

My current use case is pretty mild right now (adding a unit test that some format in the code is always valid) so I understand if I'm just misguided, but in the case of validating user inputs, I think this would be a reasonable thing to check (and in that case, maybe `moment` isn't the right place for it).

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
