### ISSUE TITLE
[Date validation] Bad validation on 3 digits year

### ISSUE THREAD

**Issue by mcharron** [moment/moment#2993]
Hi there,

I detect a problem with validation on a 3 digit year and parsing strict, with multiple date formats. Here's what I test : 

var dateFormats = ['YYY', 'YYY-YYY', 'MM/YYY', 'MM/YYY-MM/YYY', 'JJ/MM/YYY', 'JJ/MM/YYY-JJ/MM/YYY', 'YYYY', 'YYYY-YYYY', 'MM/YYYY', 'MMMM YYYY', 'MM/YYYY-MM/YYYY', 'MMMM YYYY-MMMM YYYY', 'DD/MM/YYYY', 'DD MMMM YYYY', 'DD/MM/YYYY-DD/MM/YYYY', 'DD MMMM YYYY-DD MMMM YYYY', 'DD MMM. YYYY', 'DD MMM. YYYY-DD MMM. YYYY', 'MMM. YYYY', 'MMM. YYYY-MMM. YYYY'];
var date = moment('01/02/933', dateFormats, locale, true); // locale is 'fr', I defined it in another file
console.log(date); // With use strict, return date with "MMM. YYYY-MMM. YYYY" formats (so the last format of my array)
console.log(date.isValid()); // returns false

Am I doing it wrong, or is it a real bug ? I thought it takes the 5th format of my list, but it appears not. I need to use strict usage to avoid bad date in fields, in french format.

Thanks by advance for your help

**Comment by maggiepint** [comment]
You have quite a few things going on here, but I think it all basically boils down to this:
```js
moment('04/02/933', 'DD/MM/YYYY', true).format()
"Invalid date"
```
This is with the default locale.

I believe what you are seeing is a an issue where there is no good way to parse three digit years in strict mode without zero-padding them.

It would be up to one of the other maintainers to make the call on whether that is a bug or an enhancement request.

I think you are maybe misinterpreting something with your format tokens. 
YYY is not a valid format token in moment. It is interpreted as two digit year with an extraneous token.
JJ is also not a format token in moment. While outputs are localized, parse tokens are not. This should be DD.
Finally, moment can't parse a date range into one moment object, so formats like 'MMM. YYYY-MMM. YYYY' aren't meaningful. See #2987.

Based on what I'm seeing here, you probably need to do some pre-parsing of your data, at the very least to separate the ranges. If you can zero-pad your three digit years, that would also be helpful.

If you were to give us a better idea of the kind of inputs you have, and what you are expecting them to parse as, we may be able to help you further.

**Comment by mcharron** [comment]
Thanks for your answer. So I have to rework my way to parse date ranges, and I have to preprocess my data to check if year is only 3 digits long, put a 0 in front of it to avoid 'Invalid date' error.

The fact is that I can have any input :/ it's in a form, with many date inputs, and user can enter whatever he wants. I just have to check if it's a date, and if it's not, cancel form submission until each inputs are valid.

For example, I can have : 
- aaaa
- 1993
- 11/1993
- 15/11/1993
- 1/2/3
- 15/8/985
- 1995-1996
- 15/10/1914-05/01/1918
- Primidi 1 Vendémiaire an I (it's a date from the french revolutionnary calendar, I use moment-revolution and a rework of me to check it's a valid date)
- 0
- null
- hello

etc.... It's because the form is used in a Archive Managing System (used in archival services in France and several countries). So the date could be from year **150 before Christ** to **today**. If you have an idea on how to check any of it, I'll check it !

**Comment by maggiepint** [comment]
Right now, it sounds like you are taking a reactive approach to validation. The user enters some inputs, and then you try to figure out if they're any good.

In your situation, I think you need to move to more proactive validation methods that push the user to enter good data.
Something like [jquery.inputmask](https://github.com/RobinHerbots/jquery.inputmask) could be immensely helpful to you
Ultimately I think you want to create a user interface where the user can choose if they are entering a range or a single date, and then pushes the user into using DD/MM/YYYY format to enter that date.

**Comment by maggiepint** [comment]
I just checked in with the team, and there was a single Y token added just a couple weeks ago that does 3 digit and negative year.
```js
moment('01/02/933', 'DD/MM/Y', true)
```
We will get it documented soon.
I think that you still need to address some of the issues with user input as I suggested, but I'm going to close this for now.
