### ISSUE TITLE
moment.set wrong date if set object

### ISSUE THREAD

**Issue by nusson** [moment/moment#2994]
I have some random month when i set a date by passing an object and then format the date.
``` moment.set({...}).format(...) ```
For no reason, for some dates the mounth is not the good one

It happend when y set date within year, month AND day
but if I don't setr the day it's always correct

Here some exemples :

if i set 2016/10 i get "**11** 2016"
```
moment().set({
  year: 2016,
  month: 10,
  day: 2
}).format('MM YYYY')    // "11 2016"
```

But the same code in 2017 will output "**10** 2017"
```
moment().set({
  year: 2017,
  month: 10,
  day: 2
}).format('MM YYYY')    // "10 2017"
```

And if i don't specify the day it will output "**11** 2017"
```
moment().set({
  year: 2017,
  month: 10
}).format('MM YYYY')    // "11 2017"
```

**Comment by maggiepint** [comment]
You are dealing with the (admittedly confusing) difference between day and date.
Day is actually a setter for day of week. The way that the object setter is implemented, it simply iterates over each setter in the list one by one, so in your errant second case your code is equivalent to saying:

```js
var a = moment();
a.year(2017);
"2017-03-01T18:07:07-06:00"
a.month(10);
"2017-11-01T18:05:00-05:00"
```
Now the critical point - November 1 2017 is a Wednesday.
If you set to day 2 of this week, you're going to get Tuesday October 31st.
```js
a.day(2);
"2017-10-31T18:14:00-05:00"
```

Alternately the result of this:
```js
moment().set({
  year: 2017,
  month: 10,
  date: 2
}).format()
"2017-11-02T18:14:34-05:00"
```
Is exactly what you're looking for.

**Comment by nusson** [comment]
Ohhh ok my bad ;)
thank you !
