### ISSUE TITLE
1 test failed. week year:week numbers 2012/2013 (2446.7) 

### ISSUE THREAD

**Issue by lazypen555** [moment/moment#2998]
### Client info

```
Date String   : Wed Mar 02 2016 16:24:00 GMT+0800 (中国标准时间)
Locale String : 2016/3/2 下午4:24:00
Offset        : -480
User Agent    : Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
```
# 
### week year:week numbers 2012/2013 (2446.7)

moment()

**Comment by mj1856** [comment]
Hmmm... This is Chrome 45 on Windows 7, Chinese Standard Time time zone, and Chinese OS language setting.  Though the error and code section has nothing to do with locale or time zone at all.  Worth investigating.

**Comment by marwahaha** [comment]
Haven't seen this in over a year. I'm going to close this
