### ISSUE TITLE
Moment.day() goes backwards instead of forwards!

### ISSUE THREAD

**Issue by joshribakoff** [moment/moment#2999]
Here's the documentation I see:
![selection_304](https://cloud.githubusercontent.com/assets/4021306/13514927/df4528ce-e161-11e5-82b4-a4805b7e6278.png)

If I ask what is the "Next monday" from August 1st 2015, I expect it to go forwards & give me 08-03-2015 which is the first Monday *after* the given date. Instead, it went backwards to "last monday" even though I passed in a *positive* integer for "next monday"....
```js
moment('2015-8-01', 'YYYY-MM-DD').day(1).format('YYYY-MM-DD')
// gives "2015-07-27"
// I expect "2015-08-03"
```

If I tell it to give me "last Monday", its returning a date that isn't even a Monday. I'd expect to get 2015-07-27
```js
moment('2015-8-01', 'YYYY-MM-DD').day(-1).format('YYYY-MM-DD')
// Gives "2015-07-25"
// Expected "2015-07-27"
```

Since Moment isn't working as I expected, I've written the logic myself, here's how I expect it to behave:
```js
while(myMoment.format('dddd') != 'Monday') {
 myMoment.add(1, 'days');
}
```

**Comment by MhMadHamster** [comment]
Hi, @joshribakoff 

I think when you're trying to get access with [0-6] indexes, you will get day of the **current** week for a given date, as a result, so for example if you want to get "next *day" you need take the number of day (for example 1 as a Monday) and add 7 to it. So it's 7 for the next Sunday and 8 for the next Monday etc.
Therefore this code:
`moment('2015-8-01', 'YYYY-MM-DD').day(8).format('YYYY-MM-DD')`
returning 2015-08-03 as expected

**Comment by maggiepint** [comment]
I think you have gotten good advice here. Thanks @MhMadHamster. I'm going to close this out, but let us know if you need anything else.

**Comment by joshribakoff** [comment]
The documentation says nothing about the method being dependent on today's date. Perhaps the documentation is lacking.
