### ISSUE TITLE
Remove the YYYY to YY implicit matching

### ISSUE THREAD

**Issue by Thinkscape** [moment/moment#3002]
Docs state that:

> YYYY from version 2.10.5 supports 2 digit years, and converts them to a year near 2000 (same as YY).

I believe it should not take place. When matching against multiple formats, I order formats from most specific to most ambiguous. That includes full 4-digit year format vs 2-digit year. For example:

````js
formats = [
  'YYYY/M/D',  # most specific, leading 4-digit year
  'D/M/YYYY',  # also very specific, trailing 4-digit year
  'D/M/YY'     # trailing ambiguous 2-digit year
];

date = moment("1/5/16", formats);  # This will produce year 0001 (!?)
````
The above will produce year `0001` because the first rule will applies, even with explicit `YYYY` declaration.

Fiddle: https://jsfiddle.net/Thinkscape/xats4pcy/

**Comment by maggiepint** [comment]
If you switch to strict mode, everything works as expected:
```js
moment('2016/05/01', [
  'YYYY/M/D',
  'D/M/YYYY',
  'D/M/YY'
], true).format()
"2016-05-01T00:00:00-05:00"
moment('1/5/2016', [
  'YYYY/M/D',
  'D/M/YYYY',
  'D/M/YY'
], true).format()
"2016-05-01T00:00:00-05:00"
moment('1/5/16', [
  'YYYY/M/D',
  'D/M/YYYY',
  'D/M/YY'
], true).format()
"2016-05-01T00:00:00-05:00"
```

**Comment by maggiepint** [comment]
As an additional follow up, we recommend using strict mode for parsing if at all possible. I am working on some documentation to make that more clear. Since strict mode solves this issue, I am going to close the item.
