### ISSUE TITLE
Support seasons, like summer ('2016-SU')

### ISSUE THREAD

**Issue by aristidesfl** [moment/moment#3006]
http://requirebin.com/?gist=69ab4683611aed6d5456

**Comment by maggiepint** [comment]
I appreciate what you're going for here, but in practice I don't think this is tenable.
Seasons are a geographical concern. Summer in France runs June-August, but summer in Madagascar runs December - February.

At first glance, it seems possible to define the seasonal months in the locale files, but locale != geographical region. For instance, both France and Madagascar have French as an official language. Thereby, the french locale could potentially be used in either, and any preset season dates would be wrong in one or the other.

See #2180
