### ISSUE TITLE
Adding hours to March 13th is incorrect?

### ISSUE THREAD

**Issue by djorgji** [moment/moment#3009]
This is probably because of the timezone change (America/New_York),

So I have a date on mid night of March 13th (Sun Mar 13 2016 00:00:00 GMT-0500), when I add more than 4-5 hours it is returning an extra hour, so say I add 6 hours it is returning 7AM.

```
date = moment.tz("2016-03-13","America/New_York"); // Sun Mar 13 2016 00:00:00 GMT-0500
var minutes = 360;
date.add (minutes, 'minutes') // Sun Mar 13 2016 07:00:00 GMT-0400
```

My question is there a way to tell if it is a special timezone changing date so I can handle it correctly. or is there a method to "just add", the hours?

**Comment by maggiepint** [comment]
With the DST transition that night, 7 am is exactly 6 hours after midnight, so this math is correct.

If you're trying to just have the date result in 6 AM every time, why not just set hours?
```js
moment.tz("2016-03-13","America/New_York").hours(6).format()
"2016-03-13T06:00:00-04:00"
```
If you're trying to always increment the hours unit in the date by 6, no matter how much actual time has passed you could use the hours setter like this:
```js
var a = moment.tz("2016-03-13","America/New_York"); a.hours(a.hours() + 6); a.format();
"2016-03-13T06:00:00-04:00"
```
If you do that though, beware of situations like this:
```js
var a = moment.tz("2016-03-13 22:30","America/New_York"); a.hours(a.hours() + 6); a.format();
"2016-03-14T04:30:00-04:00"
```
The overloaded set will push you into the next day when you least expect it, so I don't generally recommend it.
Does any of that help you?

**Comment by djorgji** [comment]
I clearly understand what moment is doing is correct, it is just not what I need in this case(I love the library otherwise). I am fairly new to using it so I don't know its ins and outs just yet. I am was mostly looking for advice for the correct way to achieve what I need, as I could not find an answer in the documentation.

What you said was helpful I am posting this to see if you have a suggestion for the right way to accomplish this.

so I simply changed it to:
date = moment.tz("2016-03-13","America/New_York"); // Sun Mar 13 2016 00:00:00 GMT-0500
var minutes = 360;
date.minutes (minutes) // Sun Mar 13 2016 06:00:00 GMT-0400

Thank you.
