### ISSUE TITLE
2 tests failed. diff:diff across DST (1965.17) diff:diff across DST (1965.19) 

### ISSUE THREAD

**Issue by AlexVega** [moment/moment#3010]
### Client info
```
Date String   : Mon Mar 07 2016 16:09:05 GMT-0600 (CST)
Locale String : 7/3/2016 16:09:05
Offset        : 360
User Agent    : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
```

====

### diff:diff across DST (1965.17) 

month diff across DST, lower bound

```javascript
// Expected true
// Actual   false
false === true
```

====

### diff:diff across DST (1965.19) 

year diff across DST, lower bound

```javascript
// Expected true
// Actual   false
false === true
```

**Comment by maggiepint** [comment]
@mj1856 do we want to leave this open, or do we want to close it in favor of #2904, which is the same tests failed? Debating on how to consolidate these things.

**Comment by mj1856** [comment]
Oops, labeled the wrong issue...

Yes, we can consolidate to a single issue.  However, double check they are indeed the same first.  The numbers are different, but may just be due to version they were reported.

**Comment by mj1856** [comment]
Tracking in #3021
