### ISSUE TITLE
Grunt build fails on Windows

### ISSUE THREAD

**Issue by mj1856** [moment/moment#3011]
In `.jscs.json` we have:

```json
    "validateLineBreaks": "LF",
```

This causes a ton of `Invalid line break` warnings with the default git configuration on Windows.

We can either change the git line ending handling with a `.gitattributes` file, or we can remove line ending validation from JSCS.

Personally, I'd prefer removing this line, as changing git line ending behavior so late into the repo history can lead to lots of commits with only line-ending changes.

Any objections?

**Comment by maggiepint** [comment]
+ about 1000
Drives me nuts.
I'd remove the jscs.json line

**Comment by mj1856** [comment]
Opened PR #3013.

**Comment by Oire** [comment]
Where is my handshaking emoticon? :) +1000 more, it's really annoying. Thanks @mj1856!
