### ISSUE TITLE
1 test failed. locale:zh-cn:calendar next week (1848.1) 

### ISSUE THREAD

**Issue by timritzer** [moment/moment#3016]
### Client info
```
Date String   : Tue Mar 08 2016 10:40:04 GMT-0600 (CST)
Locale String : 3/8/2016, 10:40:04 AM
Offset        : 360
User Agent    : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36
```

====

### locale:zh-cn:calendar next week (1848.1) 

Today + 7 days beginning of day

```javascript
// Expected 下周一凌晨12点整
// Actual   本周一凌晨12点整
"本周一凌晨12点整" === "下周一凌晨12点整"
```

**Comment by timritzer** [comment]
Macintosh OSX (El Capitan) 
Chrome Version 49.0.2623.75 (64-bit)

**Comment by mj1856** [comment]
I can reproduce this on 2.12.0 in Chrome latest on Windows 10.  I think all browsers are affected.  Not sure why it didn't get caught in tests.

**Comment by mj1856** [comment]
Looks like the `nextWeek` and `lastWeek` implementations in [zh-cn.js](https://github.com/moment/moment/blob/2.12.0/src/locale/zh-cn.js#L67-L78) use `moment()` in their calculations, so the time that the test runs could affect the output.

Not sure why this is showing up just now, as it's been there for awhile.  Something else must have surfaced it.

**Comment by mj1856** [comment]
Ok, so I know why it's failing now.  It's DST related.  Run it in a time zone without DST (or a non-US time zone) and it will work.  It's failing now because it's testing a week out and we're approaching the start of DST in the US this coming Sunday.

Fix pending...

**Comment by mj1856** [comment]
We'll track this in #3028.  Thanks.
