### ISSUE TITLE
Duration object of moment.duration(stringISO) with wrong days value

### ISSUE THREAD

**Issue by santosguilherme** [moment/moment#3017]
The object moment.duration('P59D') returns differents values.

![selecao_004](https://cloud.githubusercontent.com/assets/8635147/13614681/71c4a016-e550-11e5-81dd-45895a7195d3.png)

**Correct value: 59**

**Comment by mj1856** [comment]
Use `.asDays()` to get the total number of days.  The `.days()` method is the number of days not fitting into `.years()` and `.months()`

**Comment by mj1856** [comment]
You could also use `.as('days')`.
