### ISSUE TITLE
Date is expected to be in ISO 8601 format yyyy-MM-ddTHH:mm:ss.fffffff-HH:MM

### ISSUE THREAD

**Issue by brandonros** [moment/moment#3018]
Just putting this here for somebody else Googling for it. It's a common error message, apparently? Respective to the niche I guess.

**Comment by brandonros** [comment]
Excuse me if I'm wrong, but I think the magic bit of goods is `moment.utc().format('YYYY-MM-DDTHH:mm:ss.0000000Z')`

**Comment by mj1856** [comment]
Without context, I'm not sure how valuable this is.  Moment can parse dates in many different formats.  If there's something more you think should be explained, the documentation repo also takes pull requests.  ;)
