### ISSUE TITLE
Formatting as ISO8601 should use a Z when in UTC mode

### ISSUE THREAD

**Issue by mj1856** [moment/moment#3020]
Currently, a moment in UTC mode (such as `moment.utc()`, or `moment().utc()`, etc.) is formatted with a `+00:00` offset when `.format()` is called with no parameters.

Example:
![image](https://cloud.githubusercontent.com/assets/1396388/13615875/3c467172-e52c-11e5-838c-9a0f4e6d5b14.png)

For best conformance to ISO8601/RFC3339, when the time zone is *explicitly* UTC then we should use `Z` instead of `+00:00`.

The difference is semantic only, though important in some contexts.  For example, `+00:00` might be from London in the winter, or from several places in Africa.  But `Z` is always UTC.

**Comment by icambron** [comment]
See #2078

**Comment by icambron** [comment]
Also #2375

**Comment by theotow** [comment]
@mj1856 i would like to help, i have the enviroment up, can you give me another hint how to proceed, thanks

**Comment by maggiepint** [comment]
Tracked by #3098
