### ISSUE TITLE
test suite failing on node v0.10 and v0.12 on ubuntu

### ISSUE THREAD

**Issue by TheAlphaNerd** [moment/moment#3022]
We've found a failing test in our smoke testing suite for moment on both v0.10 and v0.12.

https://ci.nodejs.org/job/thealphanerd-smoker/108/nodes=ubuntu1204-64/tapTestReport/smoker%2Ftest.tap-28/

It seems to have to do with 
`# Module: locale:zh-cn Test: calendar next week`

**Comment by mj1856** [comment]
Yes, we are tracking that in #3016.  It is a minor issue with the Chinese locale, that somehow got past our automated tests.
