### ISSUE TITLE
Serialize locale data

### ISSUE THREAD

**Issue by suprMax** [moment/moment#3025]
I'm trying to have language bundles that have all application language strings as JSON, along with modules language strings too.

Currently I have to load all moment locales upfront, in browserify it looks like a bunch of `require('moment/locale/xx')` calls.

Looks like these modules return an empty object. Would be totally awesome if they returned locale data that I could somehow serialize and include in my JSON (or JSON-like https://github.com/yahoo/serialize-javascript) bundles and then load on demand when locale changes. Is there a way to somehow extract this data from moment instance perhaps?

**Comment by mj1856** [comment]
Some of the locales have custom functions in them, so they're more than just raw data.  We could consider changing this in a far future version, but I don't see how this could be accommodated in the current design.

**Comment by suprMax** [comment]
If those are just simple pure functions perhaps they're still serializable with the serialize-javascript module I linked to. They'd have to all be contained in one object though. Is there any chance to gain access to at least semi-raw locale data? Or is it all encapsulated in locale modules atm?

**Comment by mj1856** [comment]
`moment.localeData(localeCode)` will give you back most of what you're looking for.

**Comment by mj1856** [comment]
Consider:

```javascript
JSON.stringify(moment.localeData('fr'), null, '\t')
```
```json
{
	"_months": [
		"janvier",
		"février",
		"mars",
		"avril",
		"mai",
		"juin",
		"juillet",
		"août",
		"septembre",
		"octobre",
		"novembre",
		"décembre"
	],
	"_monthsShort": [
		"janv.",
		"févr.",
		"mars",
		"avr.",
		"mai",
		"juin",
		"juil.",
		"août",
		"sept.",
		"oct.",
		"nov.",
		"déc."
	],
	"_weekdays": [
		"dimanche",
		"lundi",
		"mardi",
		"mercredi",
		"jeudi",
		"vendredi",
		"samedi"
	],
	"_weekdaysShort": [
		"dim.",
		"lun.",
		"mar.",
		"mer.",
		"jeu.",
		"ven.",
		"sam."
	],
	"_weekdaysMin": [
		"Di",
		"Lu",
		"Ma",
		"Me",
		"Je",
		"Ve",
		"Sa"
	],
	"_longDateFormat": {
		"LT": "HH:mm",
		"LTS": "HH:mm:ss",
		"L": "DD/MM/YYYY",
		"LL": "D MMMM YYYY",
		"LLL": "D MMMM YYYY HH:mm",
		"LLLL": "dddd D MMMM YYYY HH:mm"
	},
	"_calendar": {
		"sameDay": "[Aujourd'hui à] LT",
		"nextDay": "[Demain à] LT",
		"nextWeek": "dddd [à] LT",
		"lastDay": "[Hier à] LT",
		"lastWeek": "dddd [dernier à] LT",
		"sameElse": "L"
	},
	"_relativeTime": {
		"future": "dans %s",
		"past": "il y a %s",
		"s": "quelques secondes",
		"m": "une minute",
		"mm": "%d minutes",
		"h": "une heure",
		"hh": "%d heures",
		"d": "un jour",
		"dd": "%d jours",
		"M": "un mois",
		"MM": "%d mois",
		"y": "un an",
		"yy": "%d ans"
	},
	"_ordinalParse": {},
	"_week": {
		"dow": 1,
		"doy": 4
	},
	"_abbr": "fr",
	"_config": {
		"months": [
			"janvier",
			"février",
			"mars",
			"avril",
			"mai",
			"juin",
			"juillet",
			"août",
			"septembre",
			"octobre",
			"novembre",
			"décembre"
		],
		"monthsShort": [
			"janv.",
			"févr.",
			"mars",
			"avr.",
			"mai",
			"juin",
			"juil.",
			"août",
			"sept.",
			"oct.",
			"nov.",
			"déc."
		],
		"weekdays": [
			"dimanche",
			"lundi",
			"mardi",
			"mercredi",
			"jeudi",
			"vendredi",
			"samedi"
		],
		"weekdaysShort": [
			"dim.",
			"lun.",
			"mar.",
			"mer.",
			"jeu.",
			"ven.",
			"sam."
		],
		"weekdaysMin": [
			"Di",
			"Lu",
			"Ma",
			"Me",
			"Je",
			"Ve",
			"Sa"
		],
		"longDateFormat": {
			"LT": "HH:mm",
			"LTS": "HH:mm:ss",
			"L": "DD/MM/YYYY",
			"LL": "D MMMM YYYY",
			"LLL": "D MMMM YYYY HH:mm",
			"LLLL": "dddd D MMMM YYYY HH:mm"
		},
		"calendar": {
			"sameDay": "[Aujourd'hui à] LT",
			"nextDay": "[Demain à] LT",
			"nextWeek": "dddd [à] LT",
			"lastDay": "[Hier à] LT",
			"lastWeek": "dddd [dernier à] LT",
			"sameElse": "L"
		},
		"relativeTime": {
			"future": "dans %s",
			"past": "il y a %s",
			"s": "quelques secondes",
			"m": "une minute",
			"mm": "%d minutes",
			"h": "une heure",
			"hh": "%d heures",
			"d": "un jour",
			"dd": "%d jours",
			"M": "un mois",
			"MM": "%d mois",
			"y": "un an",
			"yy": "%d ans"
		},
		"ordinalParse": {},
		"week": {
			"dow": 1,
			"doy": 4
		},
		"abbr": "fr"
	},
	"_ordinalParseLenient": {}
}
```

**Comment by suprMax** [comment]
That just might work! Thanks! I'll try it tomorrow

**Comment by suprMax** [comment]
It seems to work, although in a hacky way. Perhaps this could be improved in future versions.

Here's the recipe:

1. Serialize data on the server with [serialize-javascript](https://github.com/yahoo/serialize-javascript): `var momentLocale = {{{serialize(moment.localeData('de'))}}}`
2. Load on the client and access "private" `_config` property
`moment.locale('de', momentLocale._config)`

The `_config` part seems hacky. Otherwise all good!

**Comment by icambron** [comment]
It would probably a little cleaner to do the `._config` part on the server

**Comment by suprMax** [comment]
Good call, works ok too

**Comment by icambron** [comment]
I thought about this a bit, and while the `._config` part is a little gross, I'm not sure it's bad enough to change for a case I assume is pretty rare. I'm going to close this one.
