### ISSUE TITLE
DST started on March 8th instead of March 13th for 2016

### ISSUE THREAD

**Issue by GarrettWaitr** [moment/moment#3026]
On v2.12.0 I noticed that moment considers 03/08/2016 08:00:00 UTC to be the start of DST.
However, DST starts at 03/13/2016 08:00:00 UTC.

Example:
var orderTimeField = '03/08/2016 08:30:00';
var orderDate = moment.utc(orderTimeField, 'MM/DD/YY hh:mm:ss'); 

Gives a date object with my local time of 03/08/2016 03:30:00 CDT -05:00
Javascript Date object gives a local time of 03/08/2016 02:30:00 CST -06:00

**Comment by maggiepint** [comment]
The problem here is that you're using a two digit year token for a four digit year. It's parsing the first two digits of your year and putting you in the year 2020 instead of the year 2016:
```js
var orderTimeField = '03/08/2016 08:30:00';
var orderDate = moment.utc(orderTimeField, 'MM/DD/YY hh:mm:ss');
orderDate.toDate().toString()
"Sun Mar 08 2020 03:30:00 GMT-0500 (Central Daylight Time)"
```
If you use a 4 digit year token, everything works fine:
```js
var orderTimeField = '03/08/2016 08:30:00';
var orderDate = moment.utc(orderTimeField, 'MM/DD/YYYY hh:mm:ss');
orderDate.toDate().toString()
"Tue Mar 08 2016 02:30:00 GMT-0600 (Central Standard Time)"
```

In 2020, DST does in fact begin on March 8th.

**Comment by GarrettWaitr** [comment]
Thanks Maggie
