### ISSUE TITLE
jQuery DatePicker href #

### ISSUE THREAD

**Issue by techouse** [moment/moment#3027]
Moment.js v2.12.0 combined with jQuery UI v1.11.4 will produce a DatePicker that will open a new page with a # href link when a date is clicked in the calendar. I guess one could suppress it with event.preventDefault() but I do not observe this behavior in Moment.js v2.11.2.

**Comment by ichernev** [comment]
I highly doubt this is an issue in moment :) We do nothing related to windows, events, clicks, globals etc etc etc. Just the js `Date` object.

I'd rerun the experiment and look for other changes.

**Comment by mj1856** [comment]
Agreed.  There's nothing in moment that could possibly affect that.  If you can reproduce a snippet somewhere (such as jsFiddle), then I'll help you track down the problem.
