### ISSUE TITLE
"Time from" and "Time to" doesn't work properly

### ISSUE THREAD

**Issue by JJBocanegra** [moment/moment#3033]
If I get the time from 1989-06-15 to today (2016-03-13) with `moment(birthDate, 'YYYY-MM-DD').toNow()` it will say that 27 years passed but that's wrong, it's 26 years. The problem is that the number is rounded to the nearest integer and I think it shouldn't be rounded. 

Here is an example:
https://jsfiddle.net/8z9m6mwe/1/

**Comment by mj1856** [comment]
The `toNow`, `fromNow`, and similar functions are for relative time, which indeed has rounding behavior, and should be used only for approximations.  For exact age requirements, use `diff` instead.

```javascript
moment().diff('1989-06-15', 'y') // 26

moment('2016-06-14').diff('1989-06-15', 'y')  // 26  (day before birthday)
moment('2016-06-15').diff('1989-06-15', 'y')  // 27  (day of birthday)
```
