### ISSUE TITLE
112 tests failed. locale:af:calendar day (15.4) locale:ar-ma:calendar day (34.4) locale:ar-sa:calendar day (53.4) locale:ar-tn:calendar day (73.4) locale:ar:calendar day (92.4) locale:az:calendar day (113.4) locale:be:calendar day (134.4) locale:bg:calendar day (153.4) locale:bn:calendar day (172.4) locale:bo:calendar day (192.4) locale:br:calendar day (212.4) locale:bs:calendar day (231.4) locale:ca:calendar day (250.4) locale:cs:calendar day (270.4) locale:cv:calendar day (290.4) locale:cy:same day (308.4) locale:de-at:calendar day (341.4) locale:de:calendar day (359.4) locale:el:calendar day (388.4) locale:en-au:calendar day (407.4) locale:en-ca:calendar day (426.4) locale:en-gb:calendar day (445.4) locale:en-ie:calendar day (464.4) locale:en-nz:calendar day (483.4) locale:en:calendar day (502.4) locale:eo:calendar day (522.4) locale:es:calendar day (541.4) locale:et:calendar day (560.4) locale:eu:calendar day (579.4) locale:fa:calendar day (598.4)

### ISSUE THREAD

**Issue by Zbee** [moment/moment#3035]
### Client info
```
Date String   : Sat Mar 12 2016 20:50:11 GMT-0700 (Mountain Standard Time)
Locale String : 3/12/2016, 8:50:11 PM
Offset        : 420
User Agent    : Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
```

====

### locale:af:calendar day (15.4) 

tomorrow at the same time

```javascript
// Expected Môre om 02:00
// Actual   Môre om 03:00
"Môre om 03:00" === "Môre om 02:00"
```

====

### locale:ar-ma:calendar day (34.4) 

tomorrow at the same time

```javascript
// Expected غدا على الساعة 02:00
// Actual   غدا على الساعة 03:00
"غدا على الساعة 03:00" === "غدا على الساعة 02:00"
```

====

### locale:ar-sa:calendar day (53.4) 

tomorrow at the same time

```javascript
// Expected غدا على الساعة ٠٢:٠٠
// Actual   غدا على الساعة ٠٣:٠٠
"غدا على الساعة ٠٣:٠٠" === "غدا على الساعة ٠٢:٠٠"
```

====

### locale:ar-tn:calendar day (73.4) 

tomorrow at the same time

```javascript
// Expected غدا على الساعة 02:00
// Actual   غدا على الساعة 03:00
"غدا على الساعة 03:00" === "غدا على الساعة 02:00"
```

====

### locale:ar:calendar day (92.4) 

tomorrow at the same time

```javascript
// Expected غدًا عند الساعة ٠٢:٠٠
// Actual   غدًا عند الساعة ٠٣:٠٠
"غدًا عند الساعة ٠٣:٠٠" === "غدًا عند الساعة ٠٢:٠٠"
```

====

### locale:az:calendar day (113.4) 

tomorrow at the same time

```javascript
// Expected sabah saat 02:00
// Actual   sabah saat 03:00
"sabah saat 03:00" === "sabah saat 02:00"
```

====

### locale:be:calendar day (134.4) 

tomorrow at the same time

```javascript
// Expected Заўтра ў 02:00
// Actual   Заўтра ў 03:00
"Заўтра ў 03:00" === "Заўтра ў 02:00"
```

====

### locale:bg:calendar day (153.4) 

tomorrow at the same time

```javascript
// Expected Утре в 2:00
// Actual   Утре в 3:00
"Утре в 3:00" === "Утре в 2:00"
```

====

### locale:bn:calendar day (172.4) 

tomorrow at the same time

```javascript
// Expected আগামীকাল রাত ২:০০ সময়
// Actual   আগামীকাল রাত ৩:০০ সময়
"আগামীকাল রাত ৩:০০ সময়" === "আগামীকাল রাত ২:০০ সময়"
```

====

### locale:bo:calendar day (192.4) 

tomorrow at the same time

```javascript
// Expected སང་ཉིན མཚན་མོ ༢:༠༠
// Actual   སང་ཉིན མཚན་མོ ༣:༠༠
"སང་ཉིན མཚན་མོ ༣:༠༠" === "སང་ཉིན མཚན་མོ ༢:༠༠"
```

====

### locale:br:calendar day (212.4) 

tomorrow at the same time

```javascript
// Expected Warc'hoazh da 2e00 AM
// Actual   Warc'hoazh da 3e00 AM
"Warc'hoazh da 3e00 AM" === "Warc'hoazh da 2e00 AM"
```

====

### locale:bs:calendar day (231.4) 

tomorrow at the same time

```javascript
// Expected sutra u 2:00
// Actual   sutra u 3:00
"sutra u 3:00" === "sutra u 2:00"
```

====

### locale:ca:calendar day (250.4) 

tomorrow at the same time

```javascript
// Expected demà a les 2:00
// Actual   demà a les 3:00
"demà a les 3:00" === "demà a les 2:00"
```

====

### locale:cs:calendar day (270.4) 

tomorrow at the same time

```javascript
// Expected zítra v 2:00
// Actual   zítra v 3:00
"zítra v 3:00" === "zítra v 2:00"
```

====

### locale:cv:calendar day (290.4) 

tomorrow at the same time

```javascript
// Expected Ыран 02:00 сехетре
// Actual   Ыран 03:00 сехетре
"Ыран 03:00 сехетре" === "Ыран 02:00 сехетре"
```

====

### locale:cy:same day (308.4) 

tomorrow at the same time

```javascript
// Expected Yfory am 02:00
// Actual   Yfory am 03:00
"Yfory am 03:00" === "Yfory am 02:00"
```

====

### locale:de-at:calendar day (341.4) 

tomorrow at the same time

```javascript
// Expected morgen um 02:00 Uhr
// Actual   morgen um 03:00 Uhr
"morgen um 03:00 Uhr" === "morgen um 02:00 Uhr"
```

====

### locale:de:calendar day (359.4) 

tomorrow at the same time

```javascript
// Expected morgen um 02:00 Uhr
// Actual   morgen um 03:00 Uhr
"morgen um 03:00 Uhr" === "morgen um 02:00 Uhr"
```

====

### locale:el:calendar day (388.4) 

tomorrow at the same time

```javascript
// Expected Αύριο στις 2:00 ΠΜ
// Actual   Αύριο στις 3:00 ΠΜ
"Αύριο στις 3:00 ΠΜ" === "Αύριο στις 2:00 ΠΜ"
```

====

### locale:en-au:calendar day (407.4) 

tomorrow at the same time

```javascript
// Expected Tomorrow at 2:00 AM
// Actual   Tomorrow at 3:00 AM
"Tomorrow at 3:00 AM" === "Tomorrow at 2:00 AM"
```

====

### locale:en-ca:calendar day (426.4) 

tomorrow at the same time

```javascript
// Expected Tomorrow at 2:00 AM
// Actual   Tomorrow at 3:00 AM
"Tomorrow at 3:00 AM" === "Tomorrow at 2:00 AM"
```

====

### locale:en-gb:calendar day (445.4) 

tomorrow at the same time

```javascript
// Expected Tomorrow at 02:00
// Actual   Tomorrow at 03:00
"Tomorrow at 03:00" === "Tomorrow at 02:00"
```

====

### locale:en-ie:calendar day (464.4) 

tomorrow at the same time

```javascript
// Expected Tomorrow at 02:00
// Actual   Tomorrow at 03:00
"Tomorrow at 03:00" === "Tomorrow at 02:00"
```

====

### locale:en-nz:calendar day (483.4) 

tomorrow at the same time

```javascript
// Expected Tomorrow at 2:00 AM
// Actual   Tomorrow at 3:00 AM
"Tomorrow at 3:00 AM" === "Tomorrow at 2:00 AM"
```

====

### locale:en:calendar day (502.4) 

tomorrow at the same time

```javascript
// Expected Tomorrow at 2:00 AM
// Actual   Tomorrow at 3:00 AM
"Tomorrow at 3:00 AM" === "Tomorrow at 2:00 AM"
```

====

### locale:eo:calendar day (522.4) 

tomorrow at the same time

```javascript
// Expected Morgaŭ je 02:00
// Actual   Morgaŭ je 03:00
"Morgaŭ je 03:00" === "Morgaŭ je 02:00"
```

====

### locale:es:calendar day (541.4) 

tomorrow at the same time

```javascript
// Expected mañana a las 2:00
// Actual   mañana a las 3:00
"mañana a las 3:00" === "mañana a las 2:00"
```

====

### locale:et:calendar day (560.4) 

tomorrow at the same time

```javascript
// Expected Homme, 2:00
// Actual   Homme, 3:00
"Homme, 3:00" === "Homme, 2:00"
```

====

### locale:eu:calendar day (579.4) 

tomorrow at the same time

```javascript
// Expected bihar 02:00etan
// Actual   bihar 03:00etan
"bihar 03:00etan" === "bihar 02:00etan"
```

====

### locale:fa:calendar day (598.4) 

tomorrow at the same time

```javascript
// Expected فردا ساعت ۰۲:۰۰
// Actual   فردا ساعت ۰۳:۰۰
"فردا ساعت ۰۳:۰۰" === "فردا ساعت ۰۲:۰۰"
```

====

### locale:fi:calendar day (617.4) 

tomorrow at the same time

```javascript
// Expected huomenna klo 02.00
// Actual   huomenna klo 03.00
"huomenna klo 03.00" === "huomenna klo 02.00"
```

====

### locale:fr-ca:same day (650.4) 

tomorrow at the same time

```javascript
// Expected Demain à 02:00
// Actual   Demain à 03:00
"Demain à 03:00" === "Demain à 02:00"
```

====

### locale:fr-ch:same day (668.4) 

tomorrow at the same time

```javascript
// Expected Demain à 02:00
// Actual   Demain à 03:00
"Demain à 03:00" === "Demain à 02:00"
```

====

### locale:fr:same day (686.4) 

tomorrow at the same time

```javascript
// Expected Demain à 02:00
// Actual   Demain à 03:00
"Demain à 03:00" === "Demain à 02:00"
```

====

### locale:fy:calendar day (705.4) 

tomorrow at the same time

```javascript
// Expected moarn om 02:00
// Actual   moarn om 03:00
"moarn om 03:00" === "moarn om 02:00"
```

====

### locale:gd:calendar day (725.4) 

tomorrow at the same time

```javascript
// Expected A-màireach aig 02:00
// Actual   A-màireach aig 03:00
"A-màireach aig 03:00" === "A-màireach aig 02:00"
```

====

### locale:gl:calendar day (744.4) 

tomorrow at the same time

```javascript
// Expected mañá ás 2:00
// Actual   mañá ás 3:00
"mañá ás 3:00" === "mañá ás 2:00"
```

====

### locale:he:calendar day (763.4) 

tomorrow at the same time

```javascript
// Expected מחר ב־02:00
// Actual   מחר ב־03:00
"מחר ב־03:00" === "מחר ב־02:00"
```

====

### locale:hi:calendar day (782.4) 

tomorrow at the same time

```javascript
// Expected कल रात २:०० बजे
// Actual   कल रात ३:०० बजे
"कल रात ३:०० बजे" === "कल रात २:०० बजे"
```

====

### locale:hr:calendar day (802.4) 

tomorrow at the same time

```javascript
// Expected sutra u 2:00
// Actual   sutra u 3:00
"sutra u 3:00" === "sutra u 2:00"
```

====

### locale:hu:calendar day (822.4) 

tomorrow at the same time

```javascript
// Expected holnap 2:00-kor
// Actual   holnap 3:00-kor
"holnap 3:00-kor" === "holnap 2:00-kor"
```

====

### locale:hy-am:calendar day (846.4) 

tomorrow at the same time

```javascript
// Expected վաղը 02:00
// Actual   վաղը 03:00
"վաղը 03:00" === "վաղը 02:00"
```

====

### locale:id:calendar day (864.4) 

tomorrow at the same time

```javascript
// Expected Besok pukul 02.00
// Actual   Besok pukul 03.00
"Besok pukul 03.00" === "Besok pukul 02.00"
```

====

### locale:is:calendar day (883.4) 

tomorrow at the same time

```javascript
// Expected á morgun kl. 2:00
// Actual   á morgun kl. 3:00
"á morgun kl. 3:00" === "á morgun kl. 2:00"
```

====

### locale:it:calendar day (901.4) 

tomorrow at the same time

```javascript
// Expected Domani alle 02:00
// Actual   Domani alle 03:00
"Domani alle 03:00" === "Domani alle 02:00"
```

====

### locale:ja:calendar day (919.4) 

tomorrow at the same time

```javascript
// Expected 明日 午前2時0分
// Actual   明日 午前3時0分
"明日 午前3時0分" === "明日 午前2時0分"
```

====

### locale:jv:calendar day (937.4) 

tomorrow at the same time

```javascript
// Expected Mbenjang pukul 02.00
// Actual   Mbenjang pukul 03.00
"Mbenjang pukul 03.00" === "Mbenjang pukul 02.00"
```

====

### locale:ka:calendar day (956.4) 

ხვალ ამავე დროს

```javascript
// Expected ხვალ 2:00 AM-ზე
// Actual   ხვალ 3:00 AM-ზე
"ხვალ 3:00 AM-ზე" === "ხვალ 2:00 AM-ზე"
```

====

### locale:kk:calendar day (975.4) 

tomorrow at the same time

```javascript
// Expected Ертең сағат 02:00
// Actual   Ертең сағат 03:00
"Ертең сағат 03:00" === "Ертең сағат 02:00"
```

====

### locale:km:calendar day (994.4) 

tomorrow at the same time

```javascript
// Expected ស្អែក ម៉ោង 02:00
// Actual   ស្អែក ម៉ោង 03:00
"ស្អែក ម៉ោង 03:00" === "ស្អែក ម៉ោង 02:00"
```

====

### locale:ko:calendar day (1014.4) 

tomorrow at the same time

```javascript
// Expected 내일 오전 2시 0분
// Actual   내일 오전 3시 0분
"내일 오전 3시 0분" === "내일 오전 2시 0분"
```

====

### locale:lo:calendar day (1046.4) 

tomorrow at the same time

```javascript
// Expected ມື້ອື່ນເວລາ 02:00
// Actual   ມື້ອື່ນເວລາ 03:00
"ມື້ອື່ນເວລາ 03:00" === "ມື້ອື່ນເວລາ 02:00"
```

====

### locale:lt:calendar day (1066.4) 

tomorrow at the same time

```javascript
// Expected Rytoj 02:00
// Actual   Rytoj 03:00
"Rytoj 03:00" === "Rytoj 02:00"
```

====

### locale:lv:calendar day (1085.4) 

tomorrow at the same time

```javascript
// Expected Rīt pulksten 02:00
// Actual   Rīt pulksten 03:00
"Rīt pulksten 03:00" === "Rīt pulksten 02:00"
```

====

### locale:me:calendar day (1104.4) 

tomorrow at the same time

```javascript
// Expected sjutra u 2:00
// Actual   sjutra u 3:00
"sjutra u 3:00" === "sjutra u 2:00"
```

====

### locale:mk:calendar day (1123.4) 

tomorrow at the same time

```javascript
// Expected Утре во 2:00
// Actual   Утре во 3:00
"Утре во 3:00" === "Утре во 2:00"
```

====

### locale:ml:calendar day (1142.4) 

tomorrow at the same time

```javascript
// Expected നാളെ രാത്രി 2:00 -നു
// Actual   നാളെ രാത്രി 3:00 -നു
"നാളെ രാത്രി 3:00 -നു" === "നാളെ രാത്രി 2:00 -നു"
```

====

### locale:mr:calendar day (1162.4) 

tomorrow at the same time

```javascript
// Expected उद्या रात्री २:०० वाजता
// Actual   उद्या रात्री ३:०० वाजता
"उद्या रात्री ३:०० वाजता" === "उद्या रात्री २:०० वाजता"
```

====

### locale:ms-my:calendar day (1182.4) 

esok pada waktu yang sama

```javascript
// Expected Esok pukul 02.00
// Actual   Esok pukul 03.00
"Esok pukul 03.00" === "Esok pukul 02.00"
```

====

### locale:ms:calendar day (1201.4) 

esok pada waktu yang sama

```javascript
// Expected Esok pukul 02.00
// Actual   Esok pukul 03.00
"Esok pukul 03.00" === "Esok pukul 02.00"
```

====

### locale:my:calendar day (1220.4) 

မနက်ဖြန် ဒီအချိန်

```javascript
// Expected မနက်ဖြန် ၀၂:၀၀ မှာ
// Actual   မနက်ဖြန် ၀၃:၀၀ မှာ
"မနက်ဖြန် ၀၃:၀၀ မှာ" === "မနက်ဖြန် ၀၂:၀၀ မှာ"
```

====

### locale:nb:calendar day (1239.4) 

tomorrow at the same time

```javascript
// Expected i morgen kl. 02:00
// Actual   i morgen kl. 03:00
"i morgen kl. 03:00" === "i morgen kl. 02:00"
```

====

### locale:ne:calendar day (1258.4) 

tomorrow at the same time

```javascript
// Expected भोलि रातिको २:०० बजे
// Actual   भोलि बिहानको ३:०० बजे
"भोलि बिहानको ३:०० बजे" === "भोलि रातिको २:०० बजे"
```

====

### locale:nl:calendar day (1278.4) 

tomorrow at the same time

```javascript
// Expected morgen om 02:00
// Actual   morgen om 03:00
"morgen om 03:00" === "morgen om 02:00"
```

====

### locale:nn:calendar day (1298.4) 

tomorrow at the same time

```javascript
// Expected I morgon klokka 02:00
// Actual   I morgon klokka 03:00
"I morgon klokka 03:00" === "I morgon klokka 02:00"
```

====

### locale:pa-in:calendar day (1317.4) 

tomorrow at the same time

```javascript
// Expected ਕਲ ਰਾਤ ੨:੦੦ ਵਜੇ
// Actual   ਕਲ ਰਾਤ ੩:੦੦ ਵਜੇ
"ਕਲ ਰਾਤ ੩:੦੦ ਵਜੇ" === "ਕਲ ਰਾਤ ੨:੦੦ ਵਜੇ"
```

====

### locale:pl:calendar day (1349.4) 

tomorrow at the same time

```javascript
// Expected Jutro o 02:00
// Actual   Jutro o 03:00
"Jutro o 03:00" === "Jutro o 02:00"
```

====

### locale:pt-br:calendar day (1367.4) 

tomorrow at the same time

```javascript
// Expected Amanhã às 02:00
// Actual   Amanhã às 03:00
"Amanhã às 03:00" === "Amanhã às 02:00"
```

====

### locale:pt:calendar day (1385.4) 

tomorrow at the same time

```javascript
// Expected Amanhã às 02:00
// Actual   Amanhã às 03:00
"Amanhã às 03:00" === "Amanhã às 02:00"
```

====

### locale:ro:calendar day (1404.4) 

tomorrow at the same time

```javascript
// Expected mâine la 2:00
// Actual   mâine la 3:00
"mâine la 3:00" === "mâine la 2:00"
```

====

### locale:ru:calendar day (1428.4) 

tomorrow at the same time

```javascript
// Expected Завтра в 02:00
// Actual   Завтра в 03:00
"Завтра в 03:00" === "Завтра в 02:00"
```

====

### locale:se:calendar day (1447.4) 

Tomorrow at the same time

```javascript
// Expected ihttin ti 02:00
// Actual   ihttin ti 03:00
"ihttin ti 03:00" === "ihttin ti 02:00"
```

====

### locale:si:calendar day (1466.4) 

tomorrow at the same time

```javascript
// Expected හෙට පෙ.ව. 2:00ට
// Actual   හෙට පෙ.ව. 3:00ට
"හෙට පෙ.ව. 3:00ට" === "හෙට පෙ.ව. 2:00ට"
```

====

### locale:sk:calendar day (1485.4) 

tomorrow at the same time

```javascript
// Expected zajtra o 2:00
// Actual   zajtra o 3:00
"zajtra o 3:00" === "zajtra o 2:00"
```

====

### locale:sl:calendar day (1505.4) 

tomorrow at the same time

```javascript
// Expected jutri ob 2:00
// Actual   jutri ob 3:00
"jutri ob 3:00" === "jutri ob 2:00"
```

====

### locale:sq:calendar day (1525.4) 

tomorrow at the same time

```javascript
// Expected Nesër në 02:00
// Actual   Nesër në 03:00
"Nesër në 03:00" === "Nesër në 02:00"
```

====

### locale:sr-cyrl:calendar day (1544.4) 

tomorrow at the same time

```javascript
// Expected сутра у 2:00
// Actual   сутра у 3:00
"сутра у 3:00" === "сутра у 2:00"
```

====

### locale:sr:calendar day (1563.4) 

tomorrow at the same time

```javascript
// Expected sutra u 2:00
// Actual   sutra u 3:00
"sutra u 3:00" === "sutra u 2:00"
```

====

### locale:sv:calendar day (1582.4) 

tomorrow at the same time

```javascript
// Expected Imorgon 02:00
// Actual   Imorgon 03:00
"Imorgon 03:00" === "Imorgon 02:00"
```

====

### locale:sw:calendar day (1601.4) 

tomorrow at the same time

```javascript
// Expected kesho saa 02:00
// Actual   kesho saa 03:00
"kesho saa 03:00" === "kesho saa 02:00"
```

====

### locale:ta:calendar day (1620.4) 

நாளை  02:00

```javascript
// Expected நாளை ௦௨:௦௦
// Actual   நாளை ௦௩:௦௦
"நாளை ௦௩:௦௦" === "நாளை ௦௨:௦௦"
```

====

### locale:te:calendar day (1639.4) 

tomorrow at the same time

```javascript
// Expected రేపు రాత్రి 2:00
// Actual   రేపు రాత్రి 3:00
"రేపు రాత్రి 3:00" === "రేపు రాత్రి 2:00"
```

====

### locale:th:calendar day (1658.4) 

tomorrow at the same time

```javascript
// Expected พรุ่งนี้ เวลา 2 นาฬิกา 0 นาที
// Actual   พรุ่งนี้ เวลา 3 นาฬิกา 0 นาที
"พรุ่งนี้ เวลา 3 นาฬิกา 0 นาที" === "พรุ่งนี้ เวลา 2 นาฬิกา 0 นาที"
```

====

### locale:tl-ph:same day (1676.4) 

tomorrow at the same time

```javascript
// Expected Bukas sa 02:00
// Actual   Bukas sa 03:00
"Bukas sa 03:00" === "Bukas sa 02:00"
```

====

### locale:tlh:calendar day (1694.4) 

tomorrow at the same time

```javascript
// Expected wa’leS 02:00
// Actual   wa’leS 03:00
"wa’leS 03:00" === "wa’leS 02:00"
```

====

### locale:tr:calendar day (1713.4) 

tomorrow at the same time

```javascript
// Expected yarın saat 02:00
// Actual   yarın saat 03:00
"yarın saat 03:00" === "yarın saat 02:00"
```

====

### locale:tzl:calendar day (1732.4) 

tomorrow at the same time

```javascript
// Expected demà à 02.00
// Actual   demà à 03.00
"demà à 03.00" === "demà à 02.00"
```

====

### locale:tzm-latn:calendar day (1751.4) 

tomorrow at the same time

```javascript
// Expected aska g 02:00
// Actual   aska g 03:00
"aska g 03:00" === "aska g 02:00"
```

====

### locale:tzm:calendar day (1770.4) 

tomorrow at the same time

```javascript
// Expected ⴰⵙⴽⴰ ⴴ 02:00
// Actual   ⴰⵙⴽⴰ ⴴ 03:00
"ⴰⵙⴽⴰ ⴴ 03:00" === "ⴰⵙⴽⴰ ⴴ 02:00"
```

====

### locale:uk:calendar day (1790.4) 

tomorrow at the same time

```javascript
// Expected Завтра о 02:00
// Actual   Завтра о 03:00
"Завтра о 03:00" === "Завтра о 02:00"
```

====

### locale:uz:calendar day (1809.4) 

tomorrow at the same time

```javascript
// Expected Эртага 02:00 да
// Actual   Эртага 03:00 да
"Эртага 03:00 да" === "Эртага 02:00 да"
```

====

### locale:vi:calendar day (1828.4) 

tomorrow at the same time

```javascript
// Expected Ngày mai lúc 02:00
// Actual   Ngày mai lúc 03:00
"Ngày mai lúc 03:00" === "Ngày mai lúc 02:00"
```

====

### locale:zh-cn:calendar day (1846.4) 

tomorrow at the same time

```javascript
// Expected 明天凌晨2点整
// Actual   明天凌晨3点整
"明天凌晨3点整" === "明天凌晨2点整"
```

====

### locale:zh-cn:calendar next week (1848.1) 

Today + 7 days beginning of day

```javascript
// Expected 下周一凌晨12点整
// Actual   本周一凌晨12点整
"本周一凌晨12点整" === "下周一凌晨12点整"
```

====

### locale:zh-tw:calendar day (1866.4) 

tomorrow at the same time

```javascript
// Expected 明天早上2點00分
// Actual   明天早上3點00分
"明天早上3點00分" === "明天早上2點00分"
```

====

### preparse and postformat:calendar day (2230.4) 

tomorrow at the same time

```javascript
// Expected Tomorrow at @:)) AM
// Actual   Tomorrow at #:)) AM
"Tomorrow at #:)) AM" === "Tomorrow at @:)) AM"
```

====

### utc offset:utc to local, keepLocalTime = true (2309.1) 

utc to local failed to keep local time

```javascript
// Expected 2016-13-03 03:50:10
// Actual   2016-13-03 04:50:10
"2016-13-03 04:50:10" === "2016-13-03 03:50:10"
```

====

### utc offset:zone to local, keepLocalTime = true (2311.12) 

utcOffset(-1:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 02:50:10
// Actual   2016-13-03 03:50:10
"2016-13-03 03:50:10" === "2016-13-03 02:50:10"
```

====

### utc offset:zone to local, keepLocalTime = true (2311.13) 

utcOffset(0:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 03:50:10
// Actual   2016-13-03 04:50:10
"2016-13-03 04:50:10" === "2016-13-03 03:50:10"
```

====

### utc offset:zone to local, keepLocalTime = true (2311.14) 

utcOffset(1:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 04:50:10
// Actual   2016-13-03 05:50:10
"2016-13-03 05:50:10" === "2016-13-03 04:50:10"
```

====

### utc offset:zone to local, keepLocalTime = true (2311.15) 

utcOffset(2:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 05:50:10
// Actual   2016-13-03 06:50:10
"2016-13-03 06:50:10" === "2016-13-03 05:50:10"
```

====

### utc offset:zone to local, keepLocalTime = true (2311.16) 

utcOffset(3:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 06:50:10
// Actual   2016-13-03 07:50:10
"2016-13-03 07:50:10" === "2016-13-03 06:50:10"
```

====

### utc offset:zone to local, keepLocalTime = true (2311.17) 

utcOffset(4:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 07:50:10
// Actual   2016-13-03 08:50:10
"2016-13-03 08:50:10" === "2016-13-03 07:50:10"
```

====

### utc offset:zone to local, keepLocalTime = true (2311.18) 

utcOffset(5:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 08:50:10
// Actual   2016-13-03 09:50:10
"2016-13-03 09:50:10" === "2016-13-03 08:50:10"
```

====

### zone switching:utc to local, keepLocalTime = true (2360.1) 

utc to local failed to keep local time

```javascript
// Expected 2016-13-03 03:50:10
// Actual   2016-13-03 04:50:10
"2016-13-03 04:50:10" === "2016-13-03 03:50:10"
```

====

### zone switching:zone to local, keepLocalTime = true (2362.8) 

zone(-5:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 08:50:10
// Actual   2016-13-03 09:50:10
"2016-13-03 09:50:10" === "2016-13-03 08:50:10"
```

====

### zone switching:zone to local, keepLocalTime = true (2362.9) 

zone(-4:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 07:50:10
// Actual   2016-13-03 08:50:10
"2016-13-03 08:50:10" === "2016-13-03 07:50:10"
```

====

### zone switching:zone to local, keepLocalTime = true (2362.10) 

zone(-3:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 06:50:10
// Actual   2016-13-03 07:50:10
"2016-13-03 07:50:10" === "2016-13-03 06:50:10"
```

====

### zone switching:zone to local, keepLocalTime = true (2362.11) 

zone(-2:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 05:50:10
// Actual   2016-13-03 06:50:10
"2016-13-03 06:50:10" === "2016-13-03 05:50:10"
```

====

### zone switching:zone to local, keepLocalTime = true (2362.12) 

zone(-1:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 04:50:10
// Actual   2016-13-03 05:50:10
"2016-13-03 05:50:10" === "2016-13-03 04:50:10"
```

====

### zone switching:zone to local, keepLocalTime = true (2362.13) 

zone(0:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 03:50:10
// Actual   2016-13-03 04:50:10
"2016-13-03 04:50:10" === "2016-13-03 03:50:10"
```

====

### zone switching:zone to local, keepLocalTime = true (2362.14) 

zone(1:00) to local failed to keep local time

```javascript
// Expected 2016-13-03 02:50:10
// Actual   2016-13-03 03:50:10
"2016-13-03 03:50:10" === "2016-13-03 02:50:10"
```

**Comment by mj1856** [comment]
Pending fix in #3034
