### ISSUE TITLE
Duration does not appear to accept milliseconds

### ISSUE THREAD

**Issue by JonForest** [moment/moment#3039]
When setting a custom format duration, I seem to be losing my milliseconds

```
> bob = moment.duration('0012:34:12.34', 'HHHH:mm:ss.SS')
{ [Number: 45252000]
  _milliseconds: 45252000,
  _days: 0,
  _months: 0,
  _data:
   { milliseconds: 0,
     seconds: 12,
     minutes: 34,
     hours: 12,
     days: 0,
     months: 0,
     years: 0 },
  _locale:
   Locale {
     _ordinalParse: /\d{1,2}(th|st|nd|rd)/,
     ordinal: [Function],
     _abbr: 'en',
     _config:
      { ordinalParse: /\d{1,2}(th|st|nd|rd)/,
        ordinal: [Function],
        abbr: 'en' },
     _ordinalParseLenient: /\d{1,2}(th|st|nd|rd)|\d{1,2}/ } }
```

Note the `milliseconds: 0`
I'm fairly sure I'm setting correctly in line with: http://momentjs.com/docs/#/displaying/format/

**Comment by icambron** [comment]
There's no duration parser that lets you pass in arbitrary tokens like that. See [here](http://momentjs.com/docs/#/durations/creating/). What's actually happening in your code that Moment is trying to use one of its built-in parsers on the string and then ignoring your second argument. And the parser it ends up using is this one (from the docs):

```js
moment.duration('23:59:59.999');
```

So all you need to do is switch to having three digits of precision in your milliseconds:

```js
moment.duration('0012:34:12.034').milliseconds(); //=> 34
```

It would certainly be nice if we had a token-based duration parser and formatter, but we don't and no one has offered to build one.
