### ISSUE TITLE
Problem with leap year (2016)

### ISSUE THREAD

**Issue by chrimas1** [moment/moment#3041]
var cal = moment(); 
cal.dayOfYear(100);
cal.year(2015);
var millis = cal.valueOf();

The millis will be one whole day before the actual millis for that specific day of year!
but only if moment() is initialized in a leap year and if the dayOfYear > Feb 29

**Comment by maggiepint** [comment]
This sort of behavior is documented here:
http://momentjs.com/docs/#/get-set/date/

Moment is not retaining the values passed to the setters and tracking them over time. Every time you do a set, it simply changes the date. For the same reason you are seeing this behavior, this can happen:

```js
var a = moment('2016-05-31'); 
a.month(3); 
a.format()
//the date has changed to the 30th because April doesn't have a 31
"2016-04-30T00:00:00-05:00"
//july has 31 days!
a.month(6); 
a.format()
//still on the 30th
"2016-07-30T00:00:00-05:00"
```

The best advice we can give is to call set in order of size, from largest date part to smallest.
