### ISSUE TITLE
get end of month April 2016

### ISSUE THREAD

**Issue by HDaghash** [moment/moment#3042]
Hello There ,
many thanks for the awesome things here , 
also i have some problem when i get the end of month in April 2016 ,
it gives me 5-1-2016 instated of 4-29-2016 : 
` new Date(moment('04/04/2016').endOf('month'));`
Thanks in advance.

**Comment by maggiepint** [comment]
I guess I'm not sure why you're passing a moment into the javascript date constructor. You can just use toDate() on the moment if you happen to need a date:

```javascript
moment('04/04/2016').endOf('month').toDate()
```
This is resulting in April 30th for me.
Note that with the way you are parsing this date, you get a deprecation warning about falling back to JS date construction. It would be better to specify a format:
```js
moment('04/04/2016', 'MM/DD/YYYY').endOf('month').toDate()
```
