### ISSUE TITLE
"Year" marker character is missing for Chinese/Japanese/etc

### ISSUE THREAD

**Issue by hokei** [moment/moment#3044]
In the Japanese language, `moment().format('YYYY MMM')` should return something like "2016年 3月", but it returns "2016 3月"

It seems like examples on the site have this problem as well:  
`moment().format('MMMM Do YYYY, h:mm:ss a');  // 三月 15日 2016, 4:56:42 下午
moment().format("MMM Do YY");               // 3月 15日 16`

This issue is very similar to https://github.com/moment/moment/issues/2807.

**Comment by mj1856** [comment]
@baryon @suupic @zenozeng @XueWei - Thoughts?

**Comment by baryon** [comment]
hokei is right, patch please

**Comment by mj1856** [comment]
I see.  Yes, that seems correct, as the local-specific formatters already include this.

![image](https://cloud.githubusercontent.com/assets/1396388/13862686/078ca636-ec52-11e5-8710-0690b5ddcde9.png)

**Comment by hokei** [comment]
Thank you, that's what I will do!

**Comment by peterromero** [comment]
Is there any update on this issue?

**Comment by peterromero** [comment]
How about some more locale-specific formatters to cover this case? If I could call `moment().format('LY')` to get the year with or without the 年, without my having to manually parse the locale and decide whether or not to add it?
