### ISSUE TITLE
Invalid date for format "YYYYMMDDHHMMSS"

### ISSUE THREAD

**Issue by vaske** [moment/moment#3047]
I'm trying something like this 
`$moment(date_from_db,'YYYYMMDDHHMMSS').format('YYYY-MM-DD');`
where `date_from_db` is `20160307133625` it fails with Invalid date error, if date from db is like
`20160307073625` then I do not have any issue, seems like there is problem with HH?

**Comment by DaSchTour** [comment]
Just a guess. It has something todo with 12 and 24 hour format.

**Comment by maggiepint** [comment]
I think the format that you want is 'YYYYMMDDHHmmss'

Right now you're using the months token (MM) twice, and the second token is parsing and setting months a second time, as a number greater than 12, ergo your date is invalid. The proper token for minutes is 'mm'.
In addition SS is a token for fractional seconds, but I believe you have whole seconds which are represented by 'ss'.

The following works fine:
```js
moment('20160307133625','YYYYMMDDHHmmss').format()
"2016-03-07T13:36:25-06:00"
```

**Comment by luoye00** [comment]
> I think the format that you want is 'YYYYMMDDHHmmss'
> 
> Right now you're using the months token (MM) twice, and the second token is parsing and setting months a second time, as a number greater than 12, ergo your date is invalid. The proper token for minutes is 'mm'. In addition SS is a token for fractional seconds, but I believe you have whole seconds which are represented by 'ss'.
> 
> The following works fine:
> 
> ```js
> moment('20160307133625','YYYYMMDDHHmmss').format()
> "2016-03-07T13:36:25-06:00"
> ```

This ok for me
