### ISSUE TITLE
Rename Filipino locale

### ISSUE THREAD

**Issue by maggiepint** [moment/moment#3054]
Technically Tagalog Philippines and Filipino are pretty much the same language.

Now that locale inheritance is possible, it would be good to create a Filipino locale that inherited from the Tagalog Philippines locale, effectively creating an alias. I think ideally these would be built together.

PR #2824 includes further details.

**Comment by mj1856** [comment]
As I understand it, the IETF BCP47 language tag for Filipino is indeed `fil`, not `tl-ph`.  CLDR also uses `fil`.   We should rename the existing file such that `fil` is primary.

But yes, we should use locale inheritance to continue to support `tl-ph` so we don't break folks.

**Comment by ichernev** [comment]
@mj1856 @maggiepint https://github.com/moment/moment/pull/4239#issuecomment-621235627

The parent-child locale mechanic was initially intended for user additions that reduce unnecessary copy pasting. I didn't consider it's use in the core locales before. But now I did, and without a compile time merger, I don't think it is worth the effort, and even then, the difference from copy-pasting will be minimal (mostly documentational)
