### ISSUE TITLE
Unit test failing when using moment.js

### ISSUE THREAD

**Issue by ellenchristine** [moment/moment#3062]
I have the following code in one of my controllers:

```
          controller.date = {
              startDate: moment().subtract(1, "days").hour(0).minute(0).second(0),
              endDate: moment()
          };
```

It works great until I try to unit test this controller. I'm including moment.js in my karma.conf.js file. I know it's being picked up properly because moment() is defined, but it fails when it hits the .subtract part of the chain. (If I remove everything after moment(), all tests pass.)

TypeError: 'undefined' is not a function (evaluating 'moment().subtract(1,'days')')

Any ideas why I'm getting this error? Do I need to include a separate dependency for the subtract() method?

**Comment by mj1856** [comment]
I assume this is the same as http://stackoverflow.com/q/36164782/634824.  As I just mentioned there, it would help if you put a minimal and complete example together that demonstrates the problem.
