### ISSUE TITLE
Why is string splitting used to create arrays in the locale files?

### ISSUE THREAD

**Issue by stijnherreman** [moment/moment#3064]
I wanted to create a new locale, and while looking at existing locales I noticed string splitting is done to create arrays:

```
'January_February_March_April_May_June_July_August_September_October_November_December'.split('_')
```

This pattern was introduced in https://github.com/moment/moment/commit/ae5916e56c58c3568961816914b25440d600fde1 but the commit message does not explain *why* this was done.

What purpose does it serve? Must I follow the same style when creating a new locale?

**Comment by timrwood** [comment]
It is a hack to save bytes. The splitting version is 98 chars, whereas the array literal is 122 characters.
