### ISSUE TITLE
locale issue

### ISSUE THREAD

**Issue by pablougas** [moment/moment#3066]
Any idea when this will be fixed? Or any workarounds currently available?

**Comment by maggiepint** [comment]
I guess I'm not sure what you're asking about. What is wrong with the locales?

**Comment by pablougas** [comment]
I am using[ Bootstrap3 datetime picker](https://github.com/TrevorS/bootstrap3-datetimepicker-rails)

Anytime I try to add the //= require moment/<locale> to my application it' saying that it cannot find the file. Am I using this incorrectly?

**Comment by pablougas** [comment]
correction: //= require moment/<locale>

**Comment by mj1856** [comment]
You probably just need to actually take a locale file [from here](https://github.com/moment/moment/tree/master/locale)

**Comment by mj1856** [comment]
Or just use `moment-with-locales.js` if you want them all.  See http://momentjs.com/
