### ISSUE TITLE
Parse object bug

### ISSUE THREAD

**Issue by ljanecek** [moment/moment#3067]
I have trouble with following code:
`moment({years:1998, months:1, date:1, hours:1, minutes:1, seconds:3, milliseconds:123}).unix()`
Result is: 886291263
`moment.unix(886291263).toString();`
Result is: "Sun Feb 01 1998 01:01:03 GMT+0100"

**Comment by ljanecek** [comment]
Ok, sorry:
Note that like moment(Array) and new Date(year, month, date), months are 0 indexed.

**Comment by mj1856** [comment]
Yep.  Just like the `Date` object, we use 0-indexed months whenever month is passed as a number.  When parsed or formatted into a string, it's 1-based.
