### ISSUE TITLE
Is Buddha Calendar support ?

### ISSUE THREAD

**Issue by yuucharawae** [moment/moment#3068]
I use bootstrap.datetimepicker and I dont know how to set calendar to Buddah format .
anyone can teach me how to do.
Thanks you so much

**Comment by icambron** [comment]
Moment doesn't support a the Buddist Calendar. Here's a discussion from last time it came up, and a discussion of  how to work around it. I know some of the work for 3.0 involves a cleanly pluggable Date implementation, so maybe it will be a good option then. In the meantime I'm going to close this.
