### ISSUE TITLE
Remove spm

### ISSUE THREAD

**Issue by puranjayjain** [moment/moment#3069]
Spm (Static package manager) has been removed and so should be removed from the moment's website and other relevant places.

**Comment by maggiepint** [comment]
I have removed the references to spm from our website and made a pull request, as it is clear to me that the spm people intend to shut down.

Knowing only English, and nothing about spm, I'm having some trouble discerning what the implications of this shutdown are. Can we remove all spm related code from Moment and stop publishing releases? Or does spm still work, and they're just phasing it out? In that case we would, I suppose, want to continue to publish for a while as people moved off.

**Comment by puranjayjain** [comment]
@maggiepint I guess the moment's maintainers can remove spm supporting code from the repo but it may induce a breaking change and might be possible at the next major release (if they follow semver)
