### ISSUE TITLE
.add(NaN, 'ms') returns moment with valid: true

### ISSUE THREAD

**Issue by jedwards1211** [moment/moment#3071]
Not sure if this is the intended behavior, but I would certainly expect/want for adding NaN of anything to make the moment invalid.

![screen shot 2016-03-28 at 10 14 52 am](https://cloud.githubusercontent.com/assets/1448194/14081023/06cff714-f4ce-11e5-8b8c-8dd7bd26ed22.png)

**Comment by icambron** [comment]
I suppose, sure.

**Comment by maggiepint** [comment]
I feel like, while it makes sense, it's kind of a breaking change. I won't say don't do it, but probably someone's code relies on this working this way.

If someone does change this, it should probably also be changed for:
```
moment().add(undefined, 'hour').isValid()
true

moment().add('', 'hour').isValid()
true

moment().add('asdfsadf', 'hour').isValid()
true
```

**Comment by jedwards1211** [comment]
Perhaps I shouldn't rely on this as a shortcut for getting an invalid moment either...but it's more consistent with the philosophy that NaN/undefined are contagious.

**Comment by maggiepint** [comment]
If you just want to get an invalid moment, little known fact:

```js
moment.invalid()
```

http://momentjs.com/docs/#/utilities/invalid/

I will agree that in general NaN should be contagious, but I'm not sure about the implications of changing it at this point.

**Comment by cmbankester** [comment]
I just want to point out that the this happens when using the day/hour/minute/etc. setters with `NaN`. E.g:
```javascript
moment().hour(NaN).isValid() // => true
moment().hour(NaN).format() // =>"-0NaN--NaN--NaNT-NaN:-NaN:-NaN+00:00"
```

My two cents: regardless of the implications of changing it, the current functionality is very non-obvious and objectively broken (i.e. `#isValid()` returns true when the value is, in fact, not valid).

**Comment by mjomble** [comment]
Perhaps a change for v3.0?
Current behavior seems definitely buggy, just stumbled onto it myself.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

We will not release a Moment v3.
