### ISSUE TITLE
Days from months other than current one display as 'NaN' when using moment-with-locales.js

### ISSUE THREAD

**Issue by lreis** [moment/moment#3072]
When using moment-with-locales.js, days of months other than the one currently in focus display as 'NaN':

![screen shot 2016-03-28 at 2 58 34 pm](https://cloud.githubusercontent.com/assets/509658/14091515/925b4f78-f4f5-11e5-89cc-0e052ca0cbca.png)

This was tried with version 2.12.0.

**Comment by icambron** [comment]
I don't know what that UI widget it is -- can you show us a simple reproduceable case where a call to Moment doesn't return what you expect?

**Comment by icambron** [comment]
I'm going to close this. If you come up with that simple reproduceable case, feel free to open a fresh ticket.
