### ISSUE TITLE
how to calculate time

### ISSUE THREAD

**Issue by mqliutie** [moment/moment#3074]
Like this
```js
var time = moment('2016-04-30 02:10') - moment();
```
I want make it to `hh:mm:ss `
How could i do this ? thank you

**Comment by NKjoep** [comment]
http://momentjs.com/docs/#/displaying/difference/ 

```
moment().diff(Moment|String|Number|Date|Array);
moment().diff(Moment|String|Number|Date|Array, String);
moment().diff(Moment|String|Number|Date|Array, String, Boolean);
```

To get the difference in milliseconds, use `moment.diff` like you would use `moment.from`.

```js
var a = moment([2007, 0, 29]);
var b = moment([2007, 0, 28]);
a.diff(b) // 86400000
```

**Comment by icambron** [comment]
Thanks @NKjoep

**Comment by mqliutie** [comment]
Thanks @NKjoep @icambron

**Comment by mqliutie** [comment]
Actually , I want make milliseconds to` hour : minutes : seconds ` to achieve a countdown

**Comment by icambron** [comment]
@mqliutie Have a look at [Countdown.js](http://countdownjs.org/). There's even a Countdown-Moment bridge [here](https://github.com/icambron/moment-countdown)

**Comment by mqliutie** [comment]
OK, Thanks
