### ISSUE TITLE
Display ISO8601 date only 

### ISSUE THREAD

**Issue by sebhoss** [moment/moment#3077]
Calling `moment("2016-03-30").format();` will return both date and time although only the date was initially specified. We have to specify the ISO8601 date format ourselves in order to display only the date, e.g. `moment("2016-03-30").format("YYYY-MM-DD");`

How about having something like `toISODateString()` (similar to `toISOString`) that only displays the date part?

IMHO this is related to #2450 (support ISO8601), #3019 (formatting ISO8601) and maybe #3020 (again formatting ISO8601).

**Comment by icambron** [comment]
> Calling moment("2016-03-30").format(); will return both date and time although only the date was initially specified

That's definitely always going to be true; JS doesn't have a real Date type in that sense.

> How about having something like toISODateString() (similar to toISOString) that only displays the date part?

I guess I don't understand what's problems having to do `format("YYYY-MM-DD")` creates. It's true that Moment formats to a really specific form of ISO8601, but I'd to have to implement every version of it (like without the seconds or without the seconds and minutes, and so on). I think the main use case for the `toISOString()` function is to make sure another ISO parser can parse it. `format("YYYY-MM-DD")` seems obvious an explicit, and really seems better in almost every way. You can always wrap it in a function if you're tired of typing it out.

@ichernev do you agree?

**Comment by maggiepint** [comment]
I"ll agree with @icambron. I"m not seeing the benefit VS the cost of having yet another way to do something in the API.

**Comment by icambron** [comment]
OK, I'm going to close it. Iskren can reopen if he disagrees.

**Comment by captbaritone** [comment]
Having a way to do this via the moment API has the advantage that it would allow code to communicate intent.

Here is how the two options "self document":

    // Express my moment as a string. I happen to have chosen YYYY-MM-DD. You don't know why.
    myMoemnt.format("YYYY-MM-DD");

    // Express my moment as an ISO date string. You can expect that consumers of this string 
    // are expecting an ISO formatted string.
    myMoemtn.toISODateString();

I would probably end up with a solution like this to achieve readable code:

    var ISO_DATE_FORMAT = 'YYYY-MM-DD";
    myMoemtn.format(ISO_DATE_FORMAT);

**Comment by icambron** [comment]
"ISO date string" could mean any of these:
 
 * YYYY-MM-DD
 * YYYYMMDD
 * YYYY-Www-D
 * YYYYWwwD

And arguably even:

 * YYYY-MM	
 * YYYY-[W]WW
 * YYYY-[W]WWEE

So you'd want something like `ISO_CALENDAR_EXTENDED_FORMAT` or the less jargony `ISO_YEAR_MONTH_DATE_DASHES_FORMAT`. Otherwise, whomever you're communicating to will need to break open `ISO_DATE_FORMAT` and understand exactly what you had in mind. `YYYY-MM-DD`, on the other hand, is much clearer and no less ambiguous.

**Comment by sebhoss** [comment]
"ISO (date) string" having multiple meanings is/was actually the reason I opened this ticket: One of our devs told me that we are not using a standard format and should only rely on ISO8601(C)(TM)(R) format. I told him that there is more than one of those, however the moment.js docs usually refers to date+time when talking about ISO8601 (e.g. http://momentjs.com/docs/#/displaying/as-iso-string/). I tried pointing to something like wikipedia in order to convince him that YYYY-MM-DD is part of ISO8601 as well, but did not succeed. His reasoning simply is/was that there is a method called `toISOString` and nothing else that produces ISO compatible strings.

**Comment by icambron** [comment]
@sebhoss Your devs using Moment's docs as their source for standards is...probably unwise. I certainly sympathize, but documenting external standards doesn't seem like a great reason to add features to Moment.

FWIW, I agree our ISO parser should *accept* those other formats (it doesn't currently accept all of them in practice, but it's reasonable to expect that it would, and it certainly handles YYYY-MM--DD). That way people trying to use Moment to parse a different ISO string than Moment would itself produce will be OK.
