### ISSUE TITLE
Creating a date for February of non leap years gives incorrect date.

### ISSUE THREAD

**Issue by cam31007** [moment/moment#3084]
If you try to create a date passing the month first for non leap years (e.g. `moment.month(1).year(2015)`) it will return an incorrect date. This only happens when creating February on non leap years. The expected date is the last day of February, instead we got the first day of March.

BUUT, it works just fine if you pass the year first. (e.g. `moment.year(2015).month(1)`).

Js Fiddle example: https://jsfiddle.net/41h64bor/2/

**Comment by maggiepint** [comment]
This is working as expected. It's just a side effect of the way calendar math works, and there's no great way around it. 
We actually have it in the docs, though it is admittedly a little buried:
http://momentjs.com/docs/#/get-set/date/
