### ISSUE TITLE
April 2016 isSame as empty object

### ISSUE THREAD

**Issue by dzx11** [moment/moment#3085]
https://jsfiddle.net/u71dx24a/1/

When comparing dates, if you compare Apr 2016 to an empty moment object, the isSame method returns true. This is not the case with March 2016, or April 2015.

**Comment by icambron** [comment]
It's actually just that `moment({})` is returning the beginning of today, which is the same date as the beginning of April.

```
moment("april 2016").format()
"2016-04-01T00:00:00-04:00"
moment({}).format()
"2016-04-01T00:00:00-04:00"
```

It's fair to ask why `moment({})` returns today's date instead of the current MS; I think that's a bit unexpected as far as undefined behaviors go.

**Comment by Changron** [comment]
Should we modifiy it to make the default value become current MS?

**Comment by ottoliar** [comment]
I'd like to take a closer look at this if possible. I think it's reasonable to expect calling `moment({})` or `moment([])` would result in the same as just calling `moment()`

**Comment by icambron** [comment]
I agree. Would accept a PR.

**Comment by jakeaaron** [comment]
Hello,

I would like to take a crack at this for my first contribution!
What source should I be looking at?
So should moment check if an empty object is passed and return the same value as if no parameter was passed?

Thanks!

**Comment by maggiepint** [comment]
@jakeaaron there is actually already an open PR on this, #3111. We have a few more up-for-grabs that we would love for you to take a look at. 

My bad for not closing this earlier, doing so now.

**Comment by jakeaaron** [comment]
Ok, no problem!
Thanks!
