### ISSUE TITLE
Parsing of invalid string changed to valid from 2.9.0 to 2.12.0

### ISSUE THREAD

**Issue by Aukhan** [moment/moment#3094]
Hi Guys,
Not sure if this is an issue or an enhancement made during the course of things,
somehow we were stuck on 2.9 and updated to 2.12 recently

earlier(2.9) we would parse things like `moment("2016-04-06Tnull").isValid() // gives false`
but now(2.12) this kind of parsing returns true with the time set to `00:00:00`

Mostly just sharing my experience after the upgrade.

Great work by all of you !

**Comment by maggiepint** [comment]
If it's okay with you, I'm going to call this the same as #2985 and close this. 

I know it doesn't look exactly the same, but I believe it's basically the same issue.
Thanks for letting us know.

**Comment by Aukhan** [comment]
@maggiepint thanks
