### ISSUE TITLE
JSPM and MomentJS

### ISSUE THREAD

**Issue by carlosagsmendes** [moment/moment#3095]
Hi,

We are experiencing problems with Moment and SystemJS when creating bundles.

The problems are caused by the project's package.json. Namely:

1) Setting the main 

`"main": "./moment.js",`

From JSPM's documentation: This is the module name of the main entry point of the package. It isn't necessary to include the .js extension, or start the name with relative syntax (./), although this will still work. [JSPM Documentation](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#main)

https://github.com/moment/moment/blob/develop/package.json#L25

2) Mapping moment to the current folder

Map configuration will rewrite internal requires to point to different local or external modules. Why is it being used in moment's package.json?

```
"map": {
            "moment": "./moment"
        }
```
https://github.com/moment/moment/blob/develop/package.json#L76

Would you accept a PR to fix the package.json or are there any reasons for having it as is?

Thanks in advance

**Comment by guybedford** [comment]
@carlosagsmendes can you clarify further at all exactly what bundling issues these were?

(1) here isn't a concern, and including the extension is generally advised anyway these days, and I believe (2) helps compatibility with jspm as it allows moment to require its own index file by name.

**Comment by carlosagsmendes** [comment]
Hi @guybedford, we were having some issues when bundling. We add to include a package override at the time resetting the main just to "moment"

```
        "main": "moment"
```

I tried it now, without the package override and bundling is working without any issues. It may have been a transient issue. Thanks
