### ISSUE TITLE
Identify if I am now in US zone UK zone

### ISSUE THREAD

**Issue by qbAnu** [moment/moment#3096]
Hi,

Please help me find out a better way to recognize which zone is the current date in.

`moment.tz(myDate).format('z')` gives me GMT, EST etc.. But How can I exactly differentiate if it is US or UK or else, as I have read that abbreviations alone doesn't determine the nation.

I really need to do this. :'( Please help!

**Comment by icambron** [comment]
Moment Timezone has its own repository [here](https://github.com/moment/moment-timezone); you'll get better support for TZ-specific issues there than here.
