### ISSUE TITLE
No least specific fallback of locale 'zh'

### ISSUE THREAD

**Issue by CTOJoe** [moment/moment#3099]
When setting a moment locale to `zh-hk` or `zh-mo`, the least specific locale of `zh` should be used. Since `zh-cn` and `zh-tw` are the only two locales included that start with `zh`, there is no fallback to just a `zh` locale. Google translate for example falls back to `zh` as an alias to `zh-cn`. This seems to be the only language in the locale folder that does not have a root fallback. I think a simple fix would be to rename `zh-cn` to just `zh`.

**Comment by icambron** [comment]
We resisted doing this for a while because we didn't love the idea of trying to decide which versions of languages are the canonical ones. But it looks like we do it for Arabic anyway and it seems pretty obvious for Chinese, so I think I'm OK with that rename.

**Comment by CTOJoe** [comment]
Should i modify the file in `src/locale` and create a PR? It looks like Travis does the final build, am I correct?

**Comment by icambron** [comment]
@ichernev should probably weigh in on this first

**Comment by icambron** [comment]
Reupping my @ichernev mention.

**Comment by CTOJoe** [comment]
Any updates?

**Comment by jjlueck-tock** [comment]
Hey Isaac. Just wanted to let you know that I ran into this issue this morning.

Glad to know we have the smart people on moment i18n changes.

**Comment by carlholloway** [comment]
Setting 'de-de' doesn't fallback to the less-specific 'de', is this related/expected?
The docs gives me the impression it should fallback, but I may have misunderstood.

**Comment by gwynjudd** [comment]
How does the language fallback in momentjs actually work? For instance we would like to provide zh-HANS (simplified)/zh-HANT (simplified) localizations that would cover all locales which used traditional and simplified chinese.

Just using zh-TW or zh-CN in this case isn't really appropriate. If I request (say) zh-SG, would it try to fallback to zh-HANS, or just go straight to zh?

**Comment by gwynjudd** [comment]
>I think a simple fix would be to rename zh-cn to just zh.

I agree that this might be a simple fix, but I think it would be very controversial. Coming from where I work, we have a lot (a LOT) of localization work, and falling back to traditional chinese characters in a simplified locale would be considered unpopular

**Comment by gwynjudd** [comment]
>Just using zh-TW or zh-CN in this case isn't really appropriate. If I request (say) zh-SG, would it try to fallback to zh-HANS, or just go straight to zh?

To answer my own question, it looks like it uses chooseLocale (https://github.com/moment/moment/blob/develop/moment.js#L1766) - it will keep trying to "lop off" the last bit of the locale and try to load that locale until it runs out of "-" characters, so it would go from zh-SG to zh.

**Comment by timmcintosh** [comment]
There's no neutral language for Chinese. "zh" is not a valid language. Simplified Chinese and Traditional Chinese cannot fall back to each other.

zh-SG should fall back to zh-CN ; both use simplifed Chinese (zh-Hans)
zh-MO and zh-HK should fall back to zh-TW ; all use traditional Chinese (zh-Hant)

zh-Hans and zh-Hant are newer names in the  ISO 15924 standard, which may not be supported by some older platforms.

**Comment by carlholloway** [comment]
@timmcintosh I agree. If there's no valid 'neutral' language then there should be no fallback.

But what about when there is a valid neutral language? Shouldn't a more specific locale ID fall back to the neutral language?

It seems fair to expect passing a valid locale ID (in the format of language code - country code, such as 'de-DE') should fall back to simply 'de', but currently momentjs does not behave this way.

**Comment by timmcintosh** [comment]
@carlholloway I tested de-CH (Swiss German) and it-CH (Swiss Italian) and they seemed to fall back to their neutral languages without problems. May I ask why it wasn't working for you and what locale you ended up getting? Thanks.

**Comment by carlholloway** [comment]
@timmcintosh apologies for the delay in replying. You're right, it does work. I was passing some custom properties (like specifying the first day of the week) - it was this that prevented the fallback from working as I thought it would.

Thankfully it is possible to have the locale fall-back and set some custom properties with moment.updateLocale() (introduced in 2.12.0).

For those interested, I've put together a jsfiddle to demonstrate:
https://jsfiddle.net/xc0m9Luv/1/

**Comment by marwahaha** [comment]
I'm going to close this due to age. I think it's ok that some locales don't have a least-specific fallback. I'm open to discussion on this.
