### ISSUE TITLE
Loading moment as module and add to window

### ISSUE THREAD

**Issue by olee** [moment/moment#3101]
I'm using SystemJS to load moment as a dependency.
However I also require another library which depends on moment being defined as window.moment.
Is there a way to achieve this without this type of hack?
````
System.import('moment').then(function (moment) {
	window.moment = moment;
	System.import('./app');
});
````

**Comment by icambron** [comment]
That hack is probably the right thing to do, TBH. Some module systems break when we *do* export the global. We'd have to make it some kind of  option that gets passed in, which feels just as hacky and seems like it would be hard to get right across all the different module loaders.

**Comment by olee** [comment]
So checking if window is defined and only registering it in that case is not a viable solution?

**Comment by icambron** [comment]
Apparently that causes issues for certain RequireJS scenarios. We used to always set it on the window no matter what and got a lot of pushback. I could certainly be convinced that when we changed it, we caused more problems than we fixed, but for better or for worse, it was a really explicit decision and switching it back seems painful in itself. We deprecated the require-but-also-global stuff in #1214 and #1220, where we logged that `window.moment=` stuff was deprecated in the presence of `require` and added an option to the require args to turn it off. The next release, we removed that option and made its behavior the default.

One option we could almost certainly support is a `forceGlobal` option in the require args. Basically the opposite of the change we made when we deprecated the global set (see [here](https://github.com/moment/moment/pull/1220/files)). I don't know enough about SystemJS to know if it could take advantage of that. 

See also #2831.

**Comment by olee** [comment]
A force global flag would be nice.
But I don't know yet if SystemJS can also pass these require flags - I will need to take a look at the docs.

**Comment by guybedford** [comment]
You can enforce moment to be loaded as a global by SystemJS with the meta configuration:

```javascript
System.config({
  meta: {
    'moment': { format: 'global' }
  }
});
```

Alternatively, if Moment isn't running as a global, you can configure in SystemJS moment to be a global for the global that is running:

```javascript
System.config({
  meta: {
    'path/to/global-file.js': {
      globals: {
        moment: 'moment'
      }
    }
  }
});
```

both cases are handled through SystemJS, and not concerns for Moment itself though.

**Comment by olee** [comment]
@guybedford This is awesome! Thanks for the info!

**Comment by maggiepint** [comment]
@olee how are you initially loading moment? I don't know anything about System.js but I've been getting a lot of questions about it lately so I'm trying to add this information to the docs. 

Looking at the system.js docs, it looks like it's just 
```
System.import('moment.js')
```
or
```
System.import('moment-with-locales.js')
```

That right?

**Comment by maggiepint** [comment]
This has been documented in PR moment/momentjs.com#310.

@guybedford  - did I get this one right? I'm just going off of your docs and what was said here.

Otherwise I think we're good to go.

**Comment by guybedford** [comment]
Thanks @maggiepint, it looks great to me.
