### ISSUE TITLE
moment object is not clonable

### ISSUE THREAD

**Issue by toporchillo** [moment/moment#3107]
https://jsfiddle.net/oo5w4s71/

var d1 = moment().hour(12).minute(0);
var d2 = _.clone(d1).add(1, 'hour');
alert(d1.format('HH:mm')+' - '+d2.format('HH:mm'));
//13:00 - 13:00 WTF?!!!

**Comment by maggiepint** [comment]
I don't know lodash clone super well, but I believe it only clones enumerable properties and does not recurse. You could try ``_.deepClone`` if you wanted to, but there are no guarantees that that has the desired behavior either.
That being said, moment has a built in clone function, and we know that works.

```js
var d1 = moment().hour(12).minute(0);
var d2 = d1.clone().add(1, 'hour');
alert(d1.format('HH:mm')+' - '+d2.format('HH:mm'));
```
