### ISSUE TITLE
Incorrect parsing glued hours/minutes 

### ISSUE THREAD

**Issue by brettdewoody** [moment/moment#3108]
The docs state:

> From version 2.10.7 parsing hmm, Hmm, hmmss and Hmmss is supported:
> 
> `moment("123", "hmm").format("HH:mm") === "01:23"`
> `moment("1234", "hmm").format("HH:mm") === "12:34"`

However, in testing the above statements I get:

    moment("123", "hmm").format("HH:mm") === "12:03"
    moment("1234", "hmm").format("HH:mm") === "12:34"

and:

    moment("130", "hmm").format("HH:mm") === "13:00"

Using `moment@2.11.0`.

**Comment by maggiepint** [comment]
Using 2.12.0 in chrome and firefox, I get:

```js
moment("123", "hmm").format("HH:mm")
"01:23"

moment("1234", "hmm").format("HH:mm")
"12:34"

moment("130", "hmm").format("HH:mm")
"01:30"
```

What happens if you upgrade to 2.12? Or do I need to be trying Node or Edge or something?

**Comment by brettdewoody** [comment]
I also tried 2.12. Both in Node.

**Comment by brettdewoody** [comment]
False alarm, it was a rebuild error. Closing this issue, thanks for making me look into it deeper @maggiepint.
