### ISSUE TITLE
isValid allows invalid dates

### ISSUE THREAD

**Issue by 3amprogrammer** [moment/moment#3110]
```javascript
moment("1.1.2001", "YYYY-MM-DD").isValid()
true
moment("1.13.2001", "YYYY-MM-DD").isValid()
false
moment("13.1.2001", "YYYY-MM-DD").isValid()
true
moment("1.13.2001", "YYYY-MM-DD").isValid()
false
moment("1.13.2001", "YYYY-DD-DD").isValid()
true
moment("1.13.2001", "YYYY-DD-MM").isValid()
false
```

At the moment moment.js is doing his best to give us true. I think **it shouldn't round parts of date** (this is my guess) like: 2001 to 20 and 13 month to 0.

**Comment by maggiepint** [comment]
Moment is doing it's best to give you a valid date. If you don't like that, you can use strict parsing mode. Just pass ``true`` as the third parameter on all of those calls:

```js
moment("1.1.2001", "YYYY-MM-DD", true).isValid()
false
moment("13.1.2001", "YYYY-MM-DD", true).isValid()
false
moment("1.13.2001", "YYYY-DD-DD", true).isValid()
false
```

There's some discussion of making a global state flag that has the parser always use strict, and possibly of defaulting to strict mode, but there is a pull request that needs to be released before we can go down that road.

More information on strict mode: http://momentjs.com/guides/#/parsing/strict-mode/

**Comment by dwdkls** [comment]
So, I have to pass third parameter with constant value equals 'true' to force moment.js to use the second parameter, otherwise second parameter is not used? 
What is the point of this?
