### ISSUE TITLE
got the same fromNow()

### ISSUE THREAD

**Issue by myserver368** [moment/moment#3114]
var ws=1459619605812;
var wd=1459583299182;
document.getElementById("cc").innerHTML=moment(ws).fromNow()+'==='+moment(wd).fromNow();

we got 14 days ago===14 days ago
why?

**Comment by maggiepint** [comment]
```js
moment(1459619605812).format()
"2016-04-02T12:53:25-05:00"

moment(1459583299182).format()
"2016-04-02T02:48:19-05:00"
```

Both of these timestamps are on the same day (at least in my time zone). When you ran this code, they were both 14 days ago.

What were you expecting to have happen?

**Comment by maggiepint** [comment]
Closing since I haven't heard from you.
