### ISSUE TITLE
dddd always returns `dow` after using `updateLocale`

### ISSUE THREAD

**Issue by mdibaiee** [moment/moment#3121]
Hey,

There's something pretty weird with `updateLocale` and setting `week: { dow: 6 }`.

```javascript
moment.updateLocale('en', { week: { dow: 6 } });
moment.locale('en');
moment('Sunday', 'dddd').weekday(); // 6
moment('Friday', 'dddd').weekday(); // 6
moment('Monday', 'dddd').weekday(); // 6
```

**Comment by mdibaiee** [comment]
I found a workaround, this just works fine:

```javascript
moment().day('Saturday').weekday(); // 0
moment().day('Sunday').weekday(); // 1
```

**Comment by maggiepint** [comment]
Yep, that's not right.
See below:
```js
moment.updateLocale('en', { week: { dow: 6 } });
moment.locale('en');
moment('Tuesday', 'dddd').format()
"2016-01-01T00:00:00-06:00" //this is a friday
```

Things start to work if I specify the ``week.doy`` property as well. Before updateLocale this was a known issue. I thought that after updateLocale it should have been fixed. Will investigate.

**Comment by ichernev** [comment]
@mdibaiee this is related to the fact that updateLocale('en', ...) doesn't work like updateLocale for all other locales. This is also reported in #3137, and fixed in #3235.

For now just specify both dow and doy and it should work.

**Comment by ichernev** [comment]
Closing this in favor of #3137 and #3235, I just ran this example with the PR and it produces (correctly):
```javascript
>  moment.updateLocale('en', { week: { dow: 6 } })
...
> moment.locale('en');
'en'
> moment('Sunday', 'dddd').weekday();
1
> moment('Friday', 'dddd').weekday();
6
> moment('Monday', 'dddd').weekday();
2
```

**Comment by mdibaiee** [comment]
@ichernev alright, thank you!
