### ISSUE TITLE
[Meteor package] Problem updating to latest 2.13.0 version in windows

### ISSUE THREAD

**Issue by tcastelli** [moment/moment#3130]
I get this when trying to update the package in a windows 10 machine with Meteor 1.3.2.2
```

=> Errors while upgrading packages:

While checking for momentjs:moment@2.13.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it
for your platform.
```

**Comment by logvik** [comment]
+1

**Comment by nickshen** [comment]
+1

**Comment by JackAdams** [comment]
Same for Mac at the moment.

**Comment by logvik** [comment]
Error does not influence on behaviour. My code is working like before...

**Comment by vitalyrotari** [comment]
Same problem on Mac OS X

```
While checking for momentjs:moment@2.13.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it
for your platform.
```

**Comment by FunkySamuel37** [comment]
+1

**Comment by taorg** [comment]
+1

**Comment by jlourenco** [comment]
+1

**Comment by bartezr8** [comment]
+1

**Comment by trakkif** [comment]
+1 (on ubuntu)

**Comment by maggiepint** [comment]
We are aware of this issue. When @ichernev publishes, he is told the publish was successful. In addition, the website shows that it was published yesterday: https://atmospherejs.com/momentjs/moment

There are no meteor developers on the Moment team. If any of you can tell us what we need to do, we will certainly take the advice.

**Comment by martinwh99** [comment]
+1

**Comment by De-Lac** [comment]
just installed meteor for the first time ever, on OS X 10.11.4.
Same error here

**Comment by rose-s** [comment]
I am also getting this error on my mac. But am able to successfully install moment with

`meteor add mrt:moment`

My limited understanding is that this meteorite command is obsolete. But I am not sure why/if using moment in this way will bring me trouble later on.

**Comment by ichernev** [comment]
I pushed 2.13.1 to meteor. It couldn't take 2.13.0 for some reason.
