### ISSUE TITLE
.format displays improper data when given a negative duration less than its maximum.

### ISSUE THREAD

**Issue by abascueomni** [moment/moment#3136]
Sorry if the title is vague. In specific when calling moment.duration any argument given like this
`moment.duration(argument1, argument2).format(argument3)`
Where argument 1 is a negative duration of lesser length than arguemnt 3 knows how to format such as
`moment.duration(-0.77, 'h').format('h[h] m[m] s[s]');`
returns the positive duration and loses the negative sign.
I have confirmed that the same happens for minutes and second like this as well
`moment.duration(-0.0077, 'h').format('m[m] s[s]');`

My boss suggested I report this despite the fact that we may be on an outdated release. 
If this has already been fixed in a newer version I'd be happy to know that and will happily look at upgrading when we next have time between releases.

**Comment by maggiepint** [comment]
So, ``.format()`` is not a built in function for moment durations. Are you using https://github.com/jsmreese/moment-duration-format?

**Comment by abascueomni** [comment]
Oops good call maggie. It seems like that project is also abandoned so I suppose this can be closed anyway. Thanks
