### ISSUE TITLE
Very specific bug when formatting a dutch date

### ISSUE THREAD

**Issue by Zjaaspoer** [moment/moment#3139]
Take a look at [this codepen](http://codepen.io/Zjaaspoer/pen/EKpBvW) (open the console to see the result)

I expect to see `31 mrt`, but I'm seeing `31 mrt.`

When I input an other date I do see the expected result (tried only a few other dates)

Very specific! :)

**Comment by Zjaaspoer** [comment]
Correction, the other dates are also giving me the extra dot.

**Comment by Oire** [comment]
@maggiepint, it seems, this one is related to #3088.

**Comment by maggiepint** [comment]
Is there something I'm missing here? This locale has . in the short month names. That being the case, isn't everything here working as it should? The ``MMM`` token is displaying short months with ``.`` as the locale file specifies.

**Comment by Zjaaspoer** [comment]
Ah, I get it. Apparently this locale indeed always had the dot. Only my
code didn't use the dot, and because of
commit fc5a352e9ca30e32a96875810604ad981d1442c3 the months are being parsed
exact, so I started getting errors.

This indeed isn't a bug. Sorry for the trouble!

2016-04-24 22:46 GMT+02:00 Maggie Pint <notifications@github.com>:

> Is there something I'm missing here? This locale has . in the short month
> names. That being the case, isn't everything here working as it should? The
> MMM token is displaying short months with . as the locale file specifies.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/moment/moment/issues/3139#issuecomment-214032455>
>



-- 

With kind regards,

Jasper Schulte | 06-24569166 | jasperschulte.nl
<http://www.jasperschulte.nl>

**Comment by maggiepint** [comment]
No worries!
