### ISSUE TITLE
startOf('particular date')????

### ISSUE THREAD

**Issue by nasr18** [moment/moment#3142]
`moment.utc().startOf('day').toDate()`
gives today's date with start and end time. Likewise i wanna get particular date with start and end time, say for `Sun Apr 24 2016 15:18:54 GMT+0530 (IST)`

is this possible??? pls reply me as soon as possible.

**Comment by icambron** [comment]
You want the start time for that date? `moment('2016-04-24T15:18:54').startOf('day')`

**Comment by nasr18** [comment]
I got it by passing that particular date inside `utc()`.
