### ISSUE TITLE
Time zone incorrect for Asia/Baku

### ISSUE THREAD

**Issue by Darrelk** [moment/moment#3144]
Hello

I have noticed that the time sone map for moment regarding Asia/Baku is incorrect.

According to Google the time-zone for Asia/Baku is GMT+4, but using moment code below gives GMT+5 which is incorrect. Am I doing something wrong? Where do you get your time-zone map from?

`moment().tz("Asia/Baku")._offset /60 `

I have not tested with all time zones, will do a test later today and attach my findings.

Kind regards,
Darrel K

**Comment by maggiepint** [comment]
Don't use any variable prefixed with an _. It does not necessarily reflect what you think it should. 

The public method for getting the timezone offset of a moment is ``.utcOffset()``.

When I run that function using the latest version of moment timezone, I get the +4 that you are describing:

```js
moment().tz("Asia/Baku").utcOffset()
240
```

In addition, formatting to ISO8601 gives me +4

```js
moment().tz("Asia/Baku").format()
"2016-04-25T17:38:53+04:00"
```

If this isn't what you are getting, I would check your moment timezone version.

**Comment by Darrelk** [comment]
Thank you, I updated and tested and all is working as expected. Will also use the public methods.

**Comment by Darrelk** [comment]
Hello @shaowin16 ,

Here is a small sample code that works. https://jsfiddle.net/spvg6apa/4/
Does any other moment functions work?

Also make sure to include moment-timezone.js:
https://momentjs.com/timezone/

Kind regards,
Darrel k

**Comment by shaowin16** [comment]
Thank you,I used the moment-timezone.js and all is working as expected.@Darrelk
