### ISSUE TITLE
toISOString ignores UTC offset

### ISSUE THREAD

**Issue by joebandenburg** [moment/moment#3145]
`moment#toISOString()` ignores any UTC offset applied to the moment. This differs from the behaviour of `moment#format()`.

```javascript
moment().utcOffset(0).format()
> "2016-04-25T19:10:01Z"
moment().utcOffset(-420).format()
> "2016-04-25T12:10:03-07:00"
moment().utcOffset(0).toISOString()
> "2016-04-25T19:10:13.495Z"
moment().utcOffset(-420).toISOString()
> "2016-04-25T19:10:16.639Z"
```

[JSFiddle](https://jsfiddle.net/89jctagx/)

**Comment by maggiepint** [comment]
Yep. There is some discussion around changing this, but at this time this is how it works. See #2821.

The documentation is unclear. I just assigned #2821 to myself and I'll get to documentation clarifications this week. Since this is a duplicate, I'm going to close it.
