### ISSUE TITLE
Explore CLDR for locale database

### ISSUE THREAD

**Issue by jzaefferer** [moment/moment#315]
The Unicode Common Locale Data Repository, CLDR (http://cldr.unicode.org/), contains a ton of locale data that Moment could use, instead of maintaining its own database, avoiding the many tickets that just deal with new locales or fixing existing ones. They've got a few overview slides of what the CLDR covers: https://docs.google.com/present/view?id=dfqr8rd5_303ckth2zhn

For now this is just an invitation to explore the CLDR, I don't really know if it can be of use here. Though I'd be very interested in any research and potential collaboration in that area, as the Globalize project (https://github.com/jquery/globalize) deals with very similar issues. Globalize and Moment actually have a good bunch in common, while Globalize lacks the DSL for creating dates.

If there's interest in collaboration between Moment and Globalize, let me, @rdworth or @scottgonzalez know.

**Comment by lreis** [comment]
Hi folks, 

What's the status on this initiative? I'm working on a project here at Adobe that uses moment and it would be great if CLDR data was used, since we base our internationalization testing on it across the company. 

I'd also be willing to help with this effort.

Best Regards,
Leandro

**Comment by jzaefferer** [comment]
As an update to my earlier comments, Globalize is now fully running on top of CLDR and our 1.0.0 release is right around the corner (1.0.0 pre-releases are also super stable). That makes no difference for Moment for now, though we're still interested in collaborating. We've had discussed with @ichernev that Moment might be able to use Globalize for its locale-dependent date parsing and formatting. Maybe its time to look into that again?

@lreis you're also welcome to check out the latest Globalize release, maybe the supported features cover your needs? Afaik there are other Adobe teams already using Globalize, or are at least in the process of adopting it.

**Comment by rxaviers** [comment]
@ichernev had started a port at https://github.com/ichernev/moment-cldr. But, it got stalled. There is a recent PR (https://github.com/ichernev/moment-cldr/pull/2) bumping the dependencies up and making according adjustments, which demonstrates traction of one more interested person at least.

**Comment by Spenhouet** [comment]
What is the status here? Is this still comming?
