### ISSUE TITLE
Yesterday's date labeled as tomorrow

### ISSUE THREAD

**Issue by ayyobro** [moment/moment#3151]
When using the calendar method:

```javascript
    var date = moment().calendar(value, {
        sameDay: '[Today]',
        nextDay: '[Tomorrow]',
        nextWeek: 'dddd',
        lastDay: '[Yesterday]',
        lastWeek: '[Last] dddd',
        sameElse: 'DD/MM/YYYY'
    }); // here u modify data 

```
Any date that I insert that is before the current date gets labeled as 'Tomorrow';

So if I put in a value of: 2016-04-27 14:22:26 ( my current time when writing this ), it will come out saying "Today..." which is good, but once I put in: 2016-04-26 14:22:26 ( the day before today ) it comes out saying "Tomorrow...". 

Any idea as of what could be causing this?

**Comment by maggiepint** [comment]
You have your value date and your reference date reversed. The reference date is by default now, and that's generally speaking how you want to keep it. Instead, you should be taking value and passing it into the moment constructor.

```js
moment('2016-04-26 14:22:26').calendar(null, {
        sameDay: '[Today]',
        nextDay: '[Tomorrow]',
        nextWeek: 'dddd',
        lastDay: '[Yesterday]',
        lastWeek: '[Last] dddd',
        sameElse: 'DD/MM/YYYY'
    });
"Last Tuesday"
```

That's more like what you want right?

**Comment by ayyobro** [comment]
Yes, awesome, thank you for clearing that up for me. It works very well now.
