### ISSUE TITLE
Strict parsing

### ISSUE THREAD

**Issue by raja-i4** [moment/moment#3154]
Hi,

I would like to enforce string parsing for date. This is what i tried, it is giving wrong results. Even though passed date is wrong, it is saying it is valid. It is assuming missing information. I wouldn't want to have that behavior. pls advice how i would go about it? 

> var d1 = moment("20161a", "YYYYMMDD");
undefined
> d.isValid();
true
> d.toString();
'Tue Nov 01 2016 00:00:00 GMT+0530'

**Comment by raja-i4** [comment]
> var d2 = moment("20161a", "YYYYMMDD");
undefined
> d2.isValid();
true
> d2.toString();
'Fri Jan 01 2016 00:00:00 GMT+0530'

**Comment by maggiepint** [comment]
http://momentjs.com/guides/#/parsing/strict-mode/

You need true.
```js
moment("20161a", "YYYYMMDD", true).isValid()
false
```

**Comment by nasr18** [comment]
may i know whats this `20161a' here?

**Comment by rasmuslp** [comment]
@nasr18 It's meant to trigger a parsing error.
