### ISSUE TITLE
Clone function over invalid date returns unequal object

### ISSUE THREAD

**Issue by jurcovicova** [moment/moment#3156]
A clone of an invalid moment results in non-equivalent object. 

Sample code [in fiddle](http://jsfiddle.net/42qq23so/2/):
````js
var something = moment('0000-00-00') // incorrect date
console.log(_.isEqual(something, something.clone()))
````

* Expected result: true
* Actual result: false

It matters to us, because we are using it inside a datastructure that is supposed to be immutable.

**Comment by maggiepint** [comment]
I don't think there is really anything we can do about this, for the following reasons:

If I iterate through all of the enumerable properties on the moment and it's clone, what I find is that the property that is unequal is ``_d`` - the JS Date object that Moment wrappers. If you run the following code, you will find this to be true:

```js
var something = moment('0000-00-00')
for( var i in something )
{
  if(!_.isEqual(something[i], something.clone()[i])) {
     console.log(something[i]);
     console.log(i);
    }
}
```

So, now we know that it is the internal date object that is unequal. As an experiment, I tried creating two invalid dates with the exact same data to construct them:
```js
var a = new Date(NaN);

var b = new Date(NaN);

console.log(_.isEqual(a,b)) 
```

The result is false.

If creating two invalid dates with the exact same input evaluates as unequal to LoDash, I don't think we can really be of any help. You could ask the LoDash team if they have any ideas, but it may be the case that this is just a limitation of date.

**Comment by jurcovicova** [comment]
Interesting, thank you for detailed answer.

**Comment by jdalton** [comment]
I'll update Lodash to treat invalid dates as equiv to `_.isEqual`. (I'll post back with the patch reference).

**Comment by jdalton** [comment]
https://github.com/lodash/lodash/commit/72a4f40125baec916bae83bfb084a388743a697f

**Comment by jurcovicova** [comment]
@jdalton That is great, thank you.
