### ISSUE TITLE
Setting a default timezone breaks Unix timestamp parsing.

### ISSUE THREAD

**Issue by westy92** [moment/moment#3158]
Found with:

- moment.js: 2.13.0
- moment-timezone: 0.5.3

Steps to reproduce:
```javascript
// 1. Try parsing a Unix timestamp
console.log(moment("1461906597", "X").isValid()); // true
// 2. Set the default timezone
moment.tz.setDefault("America/Chicago");
// 3. Try parsing the same Unix timestamp
console.log(moment("1461906597", "X").isValid()); // false
```

The expected result for step 3 is `true`.

See this in action: [Plunker](https://plnkr.co/edit/PfucT48BJqQm78LcUxDv)

**Comment by maggiepint** [comment]
Yep, that's wrong. It's actually a bug in moment timezone, so I'm going to move it over to that repository.

**Comment by maggiepint** [comment]
Closing in favor of moment/moment-timezone#338
