### ISSUE TITLE
Version/Author comment on top of moment-with-locales.js missing

### ISSUE THREAD

**Issue by XitasoChris** [moment/moment#3159]
In the most recent version, the moment-with-locales.js file does not have a version/author comment. This makes it hard to see which version of moment.js is included in a project. Could you please add the same header comment as for moment.js?

**Comment by icambron** [comment]
Pretty sure we'd take a PR for this.

**Comment by mj1856** [comment]
Note that `moment.version` will always return the version number.

But yeah, it looks like there's a problem with the build process for `moment-with-locales`.

**Comment by mj1856** [comment]
To be clear on requirements, the block:

```
    //! moment.js
    //! version : 2.13.0
    //! authors : Tim Wood, Iskren Chernev, Moment.js contributors
    //! license : MIT
    //! momentjs.com
```

should always come at the top of the file.  Somehow it's being put in the middle of the file for the `moment-with-locales` distributables.

**Comment by XitasoChris** [comment]
After having a quick look at the code: It seems this is because the transpiler just adds all locale files first and then adds the content of moment.js which contains the block in question. The transpiler should probably be changed to add the block itself.

I didn't really check how #3090 is coming along, but if this makes it into the next release, maybe it should be done together with that refactoring.

**Comment by ichernev** [comment]
Close in favor of #3234.
