### ISSUE TITLE
Library uses code from stackoverflow.com

### ISSUE THREAD

**Issue by Karankang007** [moment/moment#3161]
This library uses code snippets from StackOverflow.com.

As per StackOverflow, all code shared on the site comes under CreativeCommons license. Does this means that this library also has to distribute code under CreativeCommons license?

Source:
http://blog.stackoverflow.com/2008/05/now-licensed-under-creative-commons/
http://creativecommons.org/licenses/by-sa/3.0/

**Comment by icambron** [comment]
Not a lawyer, but I think it means that the specific code derived from SO answers is distributed under Creative Commons, not the whole library. Perhaps we need to do a) a better job with attribution and b) a better job of specifying the license for those specific pieces of code, and we'd welcome qualified help for sorting that out. But that's different from Moment as a whole being CC. All that out of the way, is there a specific reason that the MIT license doesn't fit your needs?

**Comment by Karankang007** [comment]
MIT works for me, i was just curious to see if this will affect my product
license in future.

On Thursday, May 5, 2016, Isaac Cambron <notifications@github.com> wrote:

> Not a lawyer, but I think it means that the specific code derived from SO
> answers is distributed under Creative Commons, not the whole library.
> Perhaps we need to do a) a better job with attribution and b) a better job
> of specifying the license for those specific pieces of code, and we'd
> welcome qualified help for sorting that out. But that's different from
> Moment as a whole being CC. All that out of the way, is there a specific
> reason that the MIT license doesn't fit your needs?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/moment/moment/issues/3161#issuecomment-217076938>
>


-- 
*Karanvir Kang*

*Software Developer*
M : (226) 339-7083 | <http://ca.linkedin.com/in/karanvirkang> LinkedIn
<http://ca.linkedin.com/in/karanvirkang>
E : Karankang007@gmail.com

**Comment by mj1856** [comment]
It will not affect your license.  We are licensing all code in this project under the MIT license.  All contributions to this project are released by their contributors under that license.  It does not matter where the technique was learned from.

With regard to actual code snippets, those are being used in accordance with the fair use doctrine.

Additionally, Creative Commons is a *content* license.  It only applies to the *publication* of the material, such as when viewing the source code. If you took large chunks of code from a CC licensed project and pasted them on your blog without any attribution, then you would be in violation.  But you can put that same source code into your project and ship your product under whatever license you wish without any attribution whatsoever.

At least that's my interpretation. I am not a lawyer.

There are plenty of discussions on this on StackOverflow's Meta site.

**Comment by mj1856** [comment]
Also see: http://blog.stackoverflow.com/2009/06/attribution-required/  Which says in part:

> So let me clarify what we mean by attribution. **If you republish this content**, we require that you...

(emphasis mine)

**Comment by gmpuran** [comment]
Hi Team,

Just wanted to touch base on this issue again, as per legal page on the StackOverflow site:

https://stackoverflow.com/legal/terms-of-service/public#licensing

It basically says that the "Subscriber Content" is licensed under CC-By-SA as well. 

Would it then affect the license for this library and the license of any commercial applications using this library?

Please advise.

Thanks in advance!
