### ISSUE TITLE
add sorting of dates

### ISSUE THREAD

**Issue by fehergeri13** [moment/moment#3163]

**Comment by maggiepint** [comment]
I assume this is a feature request. Can you provide some more details of what you want?

**Comment by icambron** [comment]
@fehergeri13 Is this what you're looking for?

```js
someArray.sort(function(a, b){return a - b;});
```

**Comment by fehergeri13** [comment]
I had to do a date interval display, and the interval boundaries can be ascending like [3;4] as well as descending like [4;3] but for the display it had to be sorted ascendingly.

For this problem I created a little solution:

```
var x = moment(),y = moment().add(-1,'days'); // the original values
var a, b;

if(x.isAfter(y)) {
    a = y;
    b = x;
}
else {
    a = x;
    b = y;
}
```

I found this really confusing, and hardly understandable, so I created a little function, `sort()`:

```
function sort() {
	var dates = Array.prototype.slice.call(arguments);
	dates.sort(function(a, b) {
		if(a.isAfter(b))
			return 1;
		if(a.isBefore(b))
			return -1;
		return 0;
	});
	return dates;
}
```

So I can have my boundaries like that:

```
var sortedDates = sort(x,y);
var a = sortedDates[0];
var b = sortedDates[1];
```

This is was the motivation of the sorting function. I find this useful (maybe for others as well), and would be easily accessible as `moment.sort()` so I created a feature request.

**Comment by icambron** [comment]
I'm pretty confident that `[x, y].sort(function(a, b){return a - b;})` meets your needs. It works because arithmetic operations automatically call `valueOf`, which for Moment objects return timestamps.

**Comment by mj1856** [comment]
Closing the issue.  If @icambron's suggestion doesn't work for you, let us know.  Thanks.

**Comment by davidperrenoud** [comment]
Not the most elegant solution, but in case you have empty dates you could sort them at the end of the list so:
```js
[x, y].sort(function(a, b) {
  var dateA = moment(a || '10000-01-01');
  var dateB = moment(b || '10000-01-01');
  return dateA.diff(dateB);
});
```
