### ISSUE TITLE
Moment Not Defined When Using With Angular

### ISSUE THREAD

**Issue by artforlife** [moment/moment#3164]
I am trying to use Moment in my MEAN stack app (actually need it to get the [Angular-Bootstrap-Calendar](https://github.com/mattlewis92/angular-bootstrap-calendar#installation) to work)

My angular app declaration is as follows: 

`var app = angular.module('MyApp',['ngRoute', 'ngResource','colorpicker.module', 'mwl.calendar']);`

Below I define a controller that will be responsible for doing the calendar-related things:

```
app.controller('Calendar', function(moment) {
    var vm = this;
    
    vm.calendarView = 'month';
    
    console.log(typeof(moment));
    
    vm.viewDate = moment.startOf('month').toDate();
    vm.isCellOpen = true;

  });
```

When I go to the route corresponding to the Calendar, I get the following error:

> TypeError: Cannot read property 'startOf' of undefined

Is there something simple that I am missing? Or is there a know issue when trying to use Moment with AngularJS?

**Comment by maggiepint** [comment]
I can see in your code that you are calling:
```js
moment.startOf('month').toDate();

```
This syntax is wrong - it should be:

```js
moment().startOf('month').toDate();
```
This is the most likely cause of your error, provided that you have loaded moment into the global namespace.

Regardless of your syntax error, you should be using some methodology to wrap moment and inject it. This will help you with any unit testing you wish to do in the future. One way of doing this is described here:

http://stackoverflow.com/questions/23727411/how-to-get-full-momentjs-api-inside-angular-view

In addition, this example uses loDash, but moment would be possible to use in this way as well.

http://www.jvandemo.com/how-to-properly-integrate-non-angularjs-libraries-in-your-angularjs-application/

That help?

**Comment by artforlife** [comment]
>  I can see in your code that you are calling:
> 
> moment.startOf('month').toDate();
> This syntax is wrong - it should be:
> 
> moment().startOf('month').toDate();

I tried it both ways after noticing in moment.js file some comments about deprecating moment(). Either way, I did not make a difference. 

I shall look through your links and see if they can get me going.

**Comment by artforlife** [comment]
I was able to get it working by running

> npm install angular-moment

and including it in my Angular application's dependencies.

Lastly, this is how I injected the moment:

```
app.controller('Calendar', function($scope, moment) {
    var vm = this;
    
    $scope.calendar = new moment();
    
    vm.calendarView = 'month';
    
    console.log(typeof(moment));
    
    vm.viewDate = moment().startOf('month').toDate();
    vm.isCellOpen = true;

  });
```
This can be closed now.
