### ISSUE TITLE
Problem typescript + momentjs + redux dev tools

### ISSUE THREAD

**Issue by dimangulov** [moment/moment#3165]
```javascript
function valid__isValid(m) {
        if (m._isValid == null) {
            var flags = getParsingFlags(m);
            var parsedParts = some.call(flags.parsedDateParts, function (i) {
                return i != null;
            });
            m._isValid =
               **m._d != null &&**
                !isNaN(m._d.getTime()) &&
           ...
```

Without bold text (i wrote it), i had error when open chrome redux dev tools window

ERROR: cannot call getTime of undefined.
I think error happened when redux dev tools tries to call moment toJSON method.

**Comment by decnorton** [comment]
Also getting a similar error when trying to convert to JSON:

```
"TypeError: m._d.getTime is not a function
    at valid__isValid
    at Moment.moment_valid__isValid [as isValid]
    at Moment.toJSON 
    at Object.stringify (native)
```

**Comment by dimangulov** [comment]
adding of **m._d != null && **, helps me, code snippet above

**Comment by maggiepint** [comment]
I"m honestly not sure what's going on but I can tell you that the isValid function you are looking at is called basically every time you do anything with a moment, so if the error is in there you will see it all over the place.

The _d variable is the JS Date object that moment wrappers.

With the code you are adding to null check _d, you are going to cause basically all moments to be invalid, so I wouldn't expect much to work, even if it does take care of the error. Presumably, _d is null for some reason. And that's weird.

How are you constructing this moment? Are you passing a Date in? Are you using a string?

**Comment by decnorton** [comment]
I'm converting a timestamp from the server for use on a model:

```js
import * as moment from 'moment';

model.created_at = moment(model.created_at, 'YYYY-MM-DD HH:mm:ss');
```
And converting to JSON for posting back to the server.

Just noticed this when inspecting the object I'm posting:
<img width="522" alt="screen shot 2016-05-06 at 15 17 21" src="https://cloud.githubusercontent.com/assets/1168092/15075735/e28fa856-139d-11e6-96f3-1ee2ff161a31.png">

`updated_at._d` is an instance of `Locale`?

**Comment by maggiepint** [comment]
My best guess is that you are mutating updated_at inadvertently.

The _f and _i parameters indicate that it is being constructed normally using string+format. At some point later, _d is getting overwritten with a locale. As to how _d gets overwritten with a locale - no idea whatsoever. I would need an MCVE to really be able to know what was going on.

**Comment by dimangulov** [comment]
I found the problem.
In my case, i used angular.
- i injected $window service in controller
- i created redux reducer by combineReducers({myReducer, router}), where router from ng-redux
- i created a store
When i opened redux dev tool window, dev tool tries to serialize $window object (which is controller field), i don`t know why, yet. In $window object exists link to Systemjs modules, one of which is momentjs.
I will try to reproduce this behavior in small project.

"$.actionsById.1.action.payload.evt.targetScope["$$childTail"]["$$childTail"]["$$childTail"].ctrl.localeService["$window"].SystemJS._loader.modules["http://localhost:7000/App/node_modules/moment/min/moment-with-locales.js"].module.fn"

redux dev tools failed path

**Comment by maggiepint** [comment]
I'm going to close this one for now. if you need it re opened let us know.

**Comment by kdubuc** [comment]
I have the same problem 😞 
I using Angular and ```import * as moment from 'moment'``` .
When I call moment.fn.format() (weird syntax to access moment with import ..), I got :
```
ionic.bundle.min.js:150 TypeError: Cannot read property 'getTime' of undefined
    at valid__isValid (moment.js:116)
    at Moment.moment_valid__isValid [as isValid] (moment.js:2505)
    at Moment.isUtc (moment.js:2017)
    at Moment.format (moment.js:2345)
    at _class.getDateHumanized (controller.js:18)
    at fn (eval at <anonymous> (ionic.bundle.min.js:260), <anonymous>:4:257)
    at ionic.bundle.min.js:159
    at m.$digest (ionic.bundle.min.js:174)
    at m.$apply (ionic.bundle.min.js:177)
    at ionic.bundle.min.js:190
```

ps: I use webpack to bundle my app.

**Comment by dimangulov** [comment]
Try
import moment from 'moment'
...
moment().format(...)

**Comment by kdubuc** [comment]
Thanks ! 

With ```import * as moment from 'moment'```, I just discover we can use ```moment.utc().format()``` too to force the moment config. But, to use moment().duration(), it's okay with import * (```moment.duration(-1, "minutes").humanize(true)```), but not with ```import moment from 'moment'``` (```moment().duration()``` throw an error)

Thanks for your help

**Comment by bob360** [comment]
I have been struggling just to Add 30 days to today's date (new Date()),Any help would be appreciated.

**Comment by bob360** [comment]
*moment().add(30, 'days') ,does it but Mongodb would give me an Invalid date, on the updated field.
