### ISSUE TITLE
undefined 'this'

### ISSUE THREAD

**Issue by kostaspapas** [moment/moment#3172]
Hello there,
I use 
fullcalendar 2.7.1
moment.js 2.13 ( the one which comes with fullcalendar)
jQuery 2.2.2 
and 
Chrome  50.0.2661.94 m

This is the order of my javascript files
        https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js
	bootstrap3.js
	jquery.dataTables.min.js
	jquery.dataTables.responsive.js
        moment.js
        fullcalendar.min.js
       ... other js

when i use drop, i get the error 
Cannot read property '_calendar' of undefined      moment.js:1111

the undefined object is 'this' !
I added a 
console.dir(this) 
after "use strict"; (in moment.js)
and i get undefined

What am I doing wrong?
thank you

**Comment by mj1856** [comment]
Hi.  We're happy to help, but I'm unsure what you mean by "when i use drop".

Could you post a jsFiddle that demonstrates the issue?  Thanks.

**Comment by icambron** [comment]
@kostaspapas Closing just to clear up tickets. Feel free to post more here and @ me or mj1856

**Comment by rapid3642** [comment]
@kostaspapas @icambron @mj1856 Hello I am running into a similar issue with the same error, I made a stackoverflow question, are you able to try and take a look at it? https://stackoverflow.com/questions/46026957/cannot-read-property-calendar-of-undefined-in-moment-js
