### ISSUE TITLE
startOf('week') jumps 1 day too far back in leap year for week #9

### ISSUE THREAD

**Issue by alpengeist** [moment/moment#3174]
moment('2016-3-1').startOf('week').calendar() -> "02/28/2016"

The correct start of week #9 is 02/29/2016.

**Comment by maggiepint** [comment]
I think you might be conflating locale based weeks with ISO Weeks. The ISO week starts on Monday at all times, but using the default moment locale (en), the regular week will start on Sunday, as that is how things work in the US.

Instead of your code, use:

```js
moment('2016-03-01').startOf('isoWeek').format()
"2016-02-29T00:00:00-06:00"
```

**Comment by alpengeist** [comment]
Thanks for the suggestion!

That's interesting. I am in Germany and use Chrome with language set to English (United States). I assumed that this would not affect the locale, which is not the same thing as the language. Chrome prints dates according to my timezone, so it actually knows where I am.

**Comment by maggiepint** [comment]
Note that if you were to use Deutsch, you would get the expected result.

```js
moment('2016-03-01').locale('de').startOf('week').format()
"2016-02-29T00:00:00-06:00"
```

**Comment by alpengeist** [comment]
Sure there is no confusion between language and locale here? A locale consists of two parts, language and country. The language is lower case and the country upper case. Like en_EN (separator may vary with platforms). The language must not interfere with the calendar. Only the country does. So, if I was to speak german in the US that'll be de_US. The week starts on Sunday, but Monday is called Montag. If I speak English in Germany, that's en_DE. Week starts on Monday, and Monday is called Monday.

I realized that older versions of Moment had lang instead of locale. However, one cannot replace the other. They have different effects on date calculations.

This stuff is terrible, I know :-)

**Comment by maggiepint** [comment]
I know what you're talking about, and in a perfect world, we would do what
you are suggesting. As is though, we don't, and I think a lot of libraries
don't. If you wanted to, you could actually override the English locale
with German week data using locale customization:
http://momentjs.com/docs/#/customization/

**Comment by alpengeist** [comment]
Ok, thanks a bunch for your patience. It is important to understand how a specific date libraries works. This date business is mind bending. Now I understand how Moment does it.

Cheers!
