### ISSUE TITLE
add setter for moment.defaultFormat

### ISSUE THREAD

**Issue by leon** [moment/moment#3176]
When using typescript I want to be able to set default format

```
import * as moment from 'moment';
moment.locale('sv-SE');
moment.defaultFormat = 'YYYY-MM-DD';
```

defaultFormat is defined as

```
export var defaultFormat: string;
```

But because of how es6 modules work, it will convert all `var` and `let` variables to read-only.
See https://github.com/Microsoft/TypeScript/issues/6751

Which means that I cannot set the defaultFormat with typescript.
It says:

```
error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
```

Maybe we should add a function to set the property,

```
export function setDefaultFormat(format: string) {}
```

or use setters and getters

```
set defaultFormat(format: string): void
```

**Comment by leon** [comment]
Workaround is to use require instead of es6 module import

```
const moment = require('moment');
moment.locale('sv-SE');
moment.defaultFormat = 'YYYY-MM-DD';
```

**Comment by maggiepint** [comment]
I think we'd take a ``.setDefaultFormat()`` function pull request.
We _technically_ support IE8 (we WILL get rid of it soon). As such though, the setter is a no go.

**Comment by marwahaha** [comment]
@leon - do you still see this issue with recent versions of TS? 

@maggiepint - how would `setDefaultFormat` break IE8?

**Comment by tiandongmao** [comment]
I got it to work by this way:

import * as moment from "moment";

export class MyApp {
    Moment: any;
    ...
   this.Moment = moment;
   this.Moment.defaultFormat = "YYYY-MM-DDTHH:mm:ss.SSSZ";
  ...
}

**Comment by jarbitlira** [comment]
I solved the issue using as type any
(moment as any).defaultFormat = 'YYYY-MM-DD'

**Comment by zielinskikamil** [comment]
any update on this?

**Comment by bleuscyther** [comment]
+1

**Comment by jenswet** [comment]
+1

**Comment by temaisgod** [comment]
+1

**Comment by Alanscut** [comment]
The following code works fine. 

React@16.9.0 + typescript@3.9.3 + moment@2.26.0
```
import moment, { Moment } from "moment";
import "moment/locale/zh-cn";

moment.defaultFormat = "YYYY-MM-DDTHH:mm:ss.SSSZ";
```

**Comment by marwahaha** [comment]
There seem to be code workarounds for this.
See https://momentjs.com/docs/#/-project-status/
