### ISSUE TITLE
Different result of day(0) and day(1)

### ISSUE THREAD

**Issue by majaode** [moment/moment#3182]
moment.locale('en', { week : { dow : 0 } });
var $week;
$week = moment("05-08-2016", "MM-DD-YYYY").day(0).format('WW');
//"18"
$week = moment("05-08-2016", "MM-DD-YYYY").day(1).format('WW');
//"19"

**Comment by icambron** [comment]
Correct. From the [docs](http://momentjs.com/docs/#/get-set/day/):

> This method can be used to set the day of the week, with Sunday as 0 and Saturday as 6.
