### ISSUE TITLE
incorrect offset

### ISSUE THREAD

**Issue by manojwtb** [moment/moment#3184]
I am using moment().format('Z'); to get current offset. When I change my system's timezone, it's working for some of the timezone while for some others its giving me incorrect figure. In fact its adding +1 for some timezone while -1 for some others.
For example : -9,-8,-7,-6,-5,-3.30,-2,1,2,7,9 for these offset its not working correctly.

**Comment by maggiepint** [comment]
Are you accounting for Daylight Saving Time?
For instance, if you are on Windows, the offsets that you see in the time zone drop down apply only during standard time. During daylight saving time, the times will be off by an hour.

**Comment by icambron** [comment]
Closing just to clear up tickets. Feel free to post more here and @ me or maggiepint
