### ISSUE TITLE
Date.prototype.getYear

### ISSUE THREAD

**Issue by cancerberoSgx** [moment/moment#3185]
You are using Date.prototype.getYear which is obsolete and not supported by standar js engines, in my particular case https://github.com/cesanta/v7/. Please use Date.prototype.getFullYear as suggested in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getYear

**Comment by icambron** [comment]
Pretty sure we'd take this as a PR that passed all the tests.

In case you haven't, note that you can retrofit your date object like this:

```js
Date.prototype.getYear = function(){return this.getFullYear() - 1900;};
```

**Comment by mj1856** [comment]
Where specifically do you see this in moment?

**Comment by maggiepint** [comment]
Yeah, I tried a couple ways to reproduce this, using ``moment().year()`` and ``moment().get('year')`` and ``moment().set('year',2016)`` all very clearly fall back to the FullYear function. 
Adding and subtracting will change years to months before performing the operation. 
Formatting will fall back to the tested get functions internally.
Don't know where this would be.

**Comment by icambron** [comment]
Ha, I didn't even think to verify that we actually use it. Switching this to troubleshooting.

**Comment by icambron** [comment]
Yeah, my quick review of the code agrees with Maggie's.

**Comment by icambron** [comment]
Going to close this for lack of response. @cancerberoSgx if you have more information on where you think Moment is using that function (and have confirmed you're using the latest version), then let us know and we'll reopen.

**Comment by cancerberoSgx** [comment]
I double check and I was using an old moment version (1.1.6). The fault was that working with npm I was doing "npm install momentjs" instead of "npm install moment". https://www.npmjs.com/package/momentjs has that old version, I will ask the author to change the name or remove this package cause is confusing. Thanks and sorry for the trouble.
