### ISSUE TITLE
Moment methods using/returning the wrong date

### ISSUE THREAD

**Issue by djorgji** [moment/moment#3187]
Parsing "2016-05-17T15:20:00.000" with 
```
moment.tz("2016-05-17T15:20:00.000", "America/New_York")

returns a Moment {
	_a:Array[7]
	_d:Tue May 17 2016 11:20:00 GMT-0400 (Eastern Daylight Time)
	_f:"YYYY-MM-DDTHH:mm:ss.SSSSZ"
	_i:"2016-05-17T15:20:00.000-04:00"
	_isAMomentObject:true
	_isUTC:true
	_offset:240
	_tzm:240
}
```

The _d is correct but all the methods (toDate, format(), diff()) return or use 15:20 rather than the 11:20 time.

I have tried `moment("2016-05-17T15:20:00.000").tz("America/New_York")` with the same results.

My main need is to do a diff with "now" (moment ()), however the diff method is using the 15:20 time.

for example time now Tue May 17 2016 12:10 EDT:
`moment.tz("2016-05-17T15:20:00.000", "America/New_York").diff(moment(), 'minute') // returns 190, should be 50`

**Comment by maggiepint** [comment]
Can give you a more detailed answer later but:
https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/

http://momentjs.com/guides/#/parsing/local-utc-zone/

**Comment by djorgji** [comment]
It still seams like the wrong behavior when doing a diff, between a moment that I have specified the timezone for and "now", which is in the local timezone, especially since the _d attribute seams correct, I guess I can use that attribute to reinitialize a moment object and then run the diff but that feels wrong in a way.

**Comment by maggiepint** [comment]
Ignore the _d object. It is a private variable and when used with moment timezone it is wrong.

I think you mean to interpret the time as UTC, and then convert it to America/New_York. To do that your code would be:
```
moment.utc("2016-05-17T15:20:00.000").tz('America/New_York').format()
"2016-05-17T11:20:00-04:00"
```

**Comment by djorgji** [comment]
That worked, thank you.
