### ISSUE TITLE
Getting "invalid Date" if the date field is blank

### ISSUE THREAD

**Issue by devolper102** [moment/moment#3188]
I have a form where I have a date field.When I enter the date it will show correct date but when i left the field blank its giving "Invalid Date".

**Comment by maggiepint** [comment]
We would need to know exactly what data is being passed to the moment constructor to be able to help you with this.

**Comment by icambron** [comment]
IIRC, empty form fields contain blank strings. Blank strings aren't valid dates:

```js
> moment("").format()
'Invalid date'
```

What do you expect it to do?

**Comment by icambron** [comment]
Closing for age.
