### ISSUE TITLE
Random guid parses as a valid date

### ISSUE THREAD

**Issue by AvionNasserMuhammad** [moment/moment#3189]
moment("E5CC4D0A-20BC-4E12-A41F-0CC82CA0B371", "MM/D/YYYY hh:mm:ss A").isValid() returns true. 

Is this a bug?

**Comment by maggiepint** [comment]
It's a side effect of being in forgiving mode. Use strict mode instead.

```js
moment("E5CC4D0A-20BC-4E12-A41F-0CC82CA0B371", "MM/D/YYYY hh:mm:ss A", true).format()
```

http://momentjs.com/guides/#/parsing/
