### ISSUE TITLE
Wrong parsing of date

### ISSUE THREAD

**Issue by 19Gerhard85** [moment/moment#3190]
Hello guys,

my code is following:

```html
<input type="text" name="battery_ir[measured_at]" value="2016-05-10" class="form-control" id="battery_ir_measured_at">

<script type="text/javascript">
$('#battery_ir_measured_at').val(moment($('#battery_ir_measured_at').val(), ['YYYY-MM-DD', 'DD.MM.YYYY']).format('L'));

$('#battery_ir_measured_at').datetimepicker({
    locale: "de",
    format: "L",
    useCurrent: false,
    calendarWeeks: true,
    showTodayButton: true
});
</script>
```

moment seems to parse the date **2016-05-10** (YYYY-MM-DD) wrong and outputs **05.10.2016**.

If I change the parsing format from `'YYYY-MM-DD', 'DD.MM.YYYY'` to `'YYYY-DD-MM', 'MM.DD.YYYY'` it works as expected.

In a previous version, the parsing worked fine. At the moment I'm using version 2.13.0

Any suggestions to fix that?

**Comment by icambron** [comment]
You're passing formatting the date as a US-localized string and then having datetimepicker parse it out as a German string. That reverse the date and the month. Try the parts by themselves and see:

```js
//moment parses the original string correctly
> moment("2016-05-10", ['YYYY-MM-DD', 'DD.MM.YYYY']).format()
'2016-05-10T00:00:00-04:00'

//moment correctly formats it as a US slash-delimited string
> moment("2016-05-10", ['YYYY-MM-DD', 'DD.MM.YYYY']).format("L")
'05/10/2016'

//I think you meant to do this:
> moment("2016-05-10", ['YYYY-MM-DD', 'DD.MM.YYYY']).locale("de").format("L")
'10.05.2016'

//now you pass that result to the datepicker, asking it to do this:
> moment("05/10/2016", "L", "de").format("L")
'05.10.2016'

//whereas you meant to ask it to do this
> moment("10.05.2016", "L", "de").format("L")
'10.05.2016'
```

FFR, this ticket would have been a lot easier for me to parse and help with if you'd narrowed it to just the part where you were using Moment, with a clear and simple explanation of its inputs, outputs, and expected outputs. Once you stripped out the datetimepicker and looked at the output of your Moment call, you probably could have figured it out.
