### ISSUE TITLE
Display time range (start and end date/time)

### ISSUE THREAD

**Issue by Programie** [moment/moment#3198]
I would like to use Moment.js for displaying time ranges.

For example calling calendar() should show something like "Tomorrow from 9:00 PM till 10:00 PM".

Is it possible to implement something like that?

**Comment by nasr18** [comment]
yeah its possible. you have to make your custom string "Tomorrow, from, till" and get time from momentjs.

**Comment by icambron** [comment]
It doesn't do exactly what you want, but check out [Twix.js](http://isaaccambron.com/twix.js/). Outside of that, you have lots of options on how to construct it with Moment's API, but, like @nasr18 says, you'll have to glue the string together yourself.

**Comment by Programie** [comment]
Twix.js does exactly what I was looking for! Thanks 👍

**Comment by nasr18** [comment]
Twix.js is awesome man. I too looking for that. @icambron :+1:
