### ISSUE TITLE
Why is there no way to set an existing Moment object in the same manner as when you create one?

### ISSUE THREAD

**Issue by kenmorechalfant** [moment/moment#3199]
I would expect this to work:
```
var selectedDate = moment();
...
selectedDate.set('01/01/1999', 'MM/DD/YYYY');
```
But it doesn't. It doesn't even display an error or anything.

Using `set()` the intended way is fine if you just want set 1 aspect of the date, e.g.:
`selectedDate.set('year', 1999);`

But if you want to set the whole thing to a different date with `set()` it gets verbose. So I do it this way:
`selectedDate = moment('01/01/1999', 'MM/DD/YYYY');`

But then you are creating a whole new moment object. Is this inefficient? In my case I'm sure that it doesn't impact performance, but I reckon in some cases it might... or am I overthinking it?

Either way, I'm just curious why it's designed this way.

**Comment by amonger** [comment]
Moment objects are immutable. It makes debugging easier if you're not changing an objects state frequently.

**Comment by icambron** [comment]
@amonger:

> Moment objects are immutable

Moment objects *are* mutable (though many people, including me, think they shouldn't be). Those setters really are setters.

@kenmorechalfant 

> or am I overthinking it?

Yes. I don't think you'd save much perfwise if you had that feature; under the covers, it would have to do all the same work, and you'd just save yourself one allocation of `Date`. Creating new objects for created-from-scratch data makes perfect sense; even in the world of mutable objects, if there's no logical connection between the old object and the new one, you might as well create a new object.
