### ISSUE TITLE
NodeJS: Setting locale does not work

### ISSUE THREAD

**Issue by matthijs110** [moment/moment#3201]
I have installed Moment by using the `npm install moment --save` command. Next I `require()` Moment inside my gulp file and set the locale:

```javascript
window.moment = require('moment'); 
moment.locale('nl');
```

When I want to try it out with 'human readable' time (`moment("2016-05-18 13:03:08").fromNow()` it still says '* days ago' in English. I want it to be Dutch (nl). But for some reason it does not change.

I did import the `moment-with-locales.js` file inside my HTML file (is there an option to do this within a JS file?)

**Comment by icambron** [comment]
From the node REPL:

```
> var moment = require("moment")
undefined
> moment.locale('nl');
'nl'
> moment("2016-05-18 13:03:08").fromNow()
'11 dagen geleden'
>
```

So I'm pretty sure it works but there's something wrong with your setup. I'm not super familiar with Gulp, but why are you assigning `moment` to `window.moment`? I'm not sure what `window` would be in a Gulp script.

You don't need `moments-with-locales`; in Node, Moment knows how to find the locale files on-demand.

**Comment by matthijs110** [comment]
When I try your comments with the `node` command, I get the same result. This is my setup inside:
```javascript
var moment = require('moment');
moment.locale('nl');

Vue.filter('moment', function(value) {
    return moment(value).fromNow();
});
```

I did use `window.moment` in the beginning. But `var` did not help.

**Comment by icambron** [comment]
Very strange - are you sure you're using the latest version of Moment?

**Comment by matthijs110** [comment]
Yes. I installed it using `npm`.

**Comment by maggiepint** [comment]
Why are you setting this in your gulp file? If you want to set the locale in moment, you set it at run time, not build time. Unless you want to use moment as part of your build process. I'm a little confused.

**Comment by matthijs110** [comment]
This is not my gulp file. This is the Javascript file which will be parsed with Browserify (gulpfile.js).

**Comment by icambron** [comment]
Wait, I thought this *was* your gulp file. It says so right at the top. It also says "NodeJS" in the title. But now it's a file that you're building with Browserify? IOW, the actual `moment.locale('nl');` is being executed in a browser? That would have been helpful information. Using NPM as a repository of JS files is different than running your code in Node.

If that's all true, please take a look at this: http://momentjs.com/docs/#/use-it/browserify/

**Comment by matthijs110** [comment]
Now it works :) My bad..
