### ISSUE TITLE
Performance problem in comparing strings as dates

### ISSUE THREAD

**Issue by gabrielenosso** [moment/moment#3204]
Hi, I need to sort strings as dates.

I wrote the following comparator:
```js
export function stringDatesComparator(dateFormat, a, b) {
  const dateA = moment(a, dateFormat);
  const dateB = moment(b, dateFormat);

  if (dateA.isBefore(dateB)) return -1;
  if (dateA.isAfter(dateB)) return 1;
  return 0;
}
```

The problem is that there is a method which takes a lot of time: configFromStringAndFormat().
Maybe Moment is invoking it everytime you pass a dateFormat?
Is there a way to avoid it?

**Comment by icambron** [comment]
How big of a list are you sorting? It's true that parsing is not super fast.

One thing you could do is to parse each entry in the list first, and then have the comparator just compare the Moments. That will get you from `n log n` to something closer to `n`.

Finally, note that you can make your comparator a little simpler:

```js
> ['2017-05-25', '2015-05-25', '2016-05-25']
    .map(function(s){return moment(s);})
    .sort(function(m1, m2){return +m1-m2;})
    .map(function(m){return m.format();});

//returns
[ '2015-05-25T00:00:00-04:00',
  '2016-05-25T00:00:00-04:00',
  '2017-05-25T00:00:00-04:00' ]
```

**Comment by icambron** [comment]
I'm going to close this. I hope my suggestion helps. In general, we'd accept small PRs with demonstrable perf improvements, should you choose to write one.
