### ISSUE TITLE
Case control in format string

### ISSUE THREAD

**Issue by AntonRand** [moment/moment#3208]
Would it be worthwhile to allow case formatting to be specified in the format string? I need the month to be in uppercase and whilst it's simple enough for me to uppercase the result in my own code I would have benefitted from something like:

^ for uppercase
_ for lowercase

Where:
`"DD ^MMM^" would return 02 JUN`
`"DD _MMM_" would return 02 jun`

Not thought about the solution in great deal and I know capitalisation has been mentioned in other issues but just after some feedback?

Does this seem like asking moment to do too much?

**Comment by icambron** [comment]
I've thought about this a bit and I think this is right on:

> Does this seem like asking moment to do too much?

The feature request totally makes sense, but formatting is complicated enough already.
