### ISSUE TITLE
Ability to change rounding used in humanize

### ISSUE THREAD

**Issue by huan086** [moment/moment#3211]
I'm running into the same issue as https://github.com/moment/moment/issues/1620

The current implementation of humanize is "*about* x units ago"

It would be great if humanize has a callback for rounding, so that we can implement Math.floor for "*more than* x units ago" (i.e. age calculation), and Math.ceil for "in *less than* x units" (i.e. countdown to an event)

**Comment by icambron** [comment]
There isn't a callback, but in the develop branch there is a global setting for the rounder:

```js
> var moment = require("./build/umd/moment")
> moment().subtract(38, 'h').fromNow()
'2 days ago'
> moment.relativeTimeRounding(Math.floor)
> moment().subtract(38, 'h').fromNow()
'a day ago'
```

That's a bit of blunt approach, but does it suit your needs?

**Comment by huan086** [comment]
Yup! `moment.relativeTimeRounding` does takes a callback (as Math.floor in your example), that's exactly what I need

**Comment by icambron** [comment]
Right, but it's global, not an argument to the humanize functions. But if it suits your needs, that's great!
