### ISSUE TITLE
Incorrect Week returned

### ISSUE THREAD

**Issue by stephanbochet** [moment/moment#3212]
Performing the "YYYY-WW" format on the following dates returns the incorrect week of the year.

Examples:
moment(1483243200000).format('YYYY-WW') = "2017/52"
moment("2017-01-01").format('YYYY-WW') = "2017/52"
moment("2017-01-01", ["YYYY-MM-DD"]).format('YYYY-WW') = "2017/52"

They should be 2017/01 or 2016/53 depending on whatever the start date is.

Here is a fiddle:
https://jsfiddle.net/17xcpvgx/

**Comment by icambron** [comment]
The formatter considers tokens individually, so it doesn't know to use special rules for "YYYY" when there happen to be weeks in the format. You shouldn't use calendar years in combination with weeks; instead should use week-years: "GGGG" with "WWWW" (ISO) and "gggg" with "wwww" (local). See also  #2853
