### ISSUE TITLE
Wrong short locale date (month) parsing

### ISSUE THREAD

**Issue by Climenty** [moment/moment#3214]
Example (wrong):

> moment.utc('2016 01 июл', 'YYYY DD MMM', 'ru').toISOString() // july
> "2016-**01**-01T00:00:00.000Z"
> or
> moment.utc('2016 01 июн', 'YYYY DD MMM', 'ru').toISOString() // june
> "2016-**01**-01T00:00:00.000Z"

But (right):

> moment.localeData('ru').monthsParse('июн')
> **5**
> and
> moment.localeData('ru').monthsParse('июл')
> **6**

**Comment by Stefan2505** [comment]
Same issue for german localization.

let date = moment('21 Jul 2016', 'DD MMM YYYY', 'de').format('YYYY/MM/DD'); -> Invalid date
let date = moment('21 Jul. 2016', 'DD MMM YYYY', 'de').format('YYYY/MM/DD'); -> With dot Notation (Jul.) works.

**Comment by ichernev** [comment]
@Viktorminator @Oire @socketpair can you comment on `moment.utc('2016 01 июл', 'YYYY DD MMM', 'ru')` -- more precisely, is `июл` a valid month, and should we parse it. The fix is easy -- just change the months*Regex variables. Same goes for `июн`.

@Stefan2505 german has officially dots in the names. Dots are something weird to parse in general, so we only allow the dot version (as if parsing is always strict). How valid is a shortened month name in german without the dot -- I don't know. If there is official evidence that it is valid we can patch the locale files. @lluchs @Oire @mik01aj what do you think?

**Comment by socketpair** [comment]
As I think:
1. We must accept (while parsing) as correct strings `фев`, `февр`, `фев.` and `февр.`
2. We must generate (while printing) only `февр.` as it is clarified in Russian dictionary. ( http://new.gramota.ru/spravka/buro/search-answer?s=242637 )

**Comment by socketpair** [comment]
See https://github.com/moment/moment/pull/3127

**Comment by Climenty** [comment]
I agree with prvious comment,
'июн', 'июл' are valid shortenings for 'июнь', 'июль' while parsing, but not for grammatical printing.

**Comment by mik01aj** [comment]
@ichernev I think that month names without dots should be fine, but note I'm not a native German speaker.

**Comment by lluchs** [comment]
For correct usage, you definitely need the dots in German. On the other hand, it's really not common to see abbreviated month names - you'd either want to use the full written name or the numbered form. The dotted form is only used if you want to show the full name, but there is not enough space for the longer month names. So you would probably write Mai, Juni, Juli, but abbreviated Jan., Feb. etc.

**Comment by tommck** [comment]
I'm getting incorrect parsing of US dates.
```
PS D:\temp> node
> var moment = require('moment')
var moment = require('moment')
undefined
> var d = moment('2012-05-25', 'YYYY-MM-DD');
undefined
> d.year()
2012
> d.month()
4  <======================= WHAT??
> d.day()
5 <======================= WHAT??
>
```

**Comment by maggiepint** [comment]
@tommck months in JavaScript index from zero. In Moment.js ``.day()`` returns day of week.

As such, the month call is fine, but you want ``d.date()``

**Comment by tommck** [comment]
ah!  well, the zero-indexed months is just weird, but the rest makes sense. Thanks @maggiepint

**Comment by lstarky** [comment]
I'm having the same problems with the Spanish locale.  Moment parses `29-ene-2016` as `Invalid date` but `29-ene.-2016` is parsed correctly as January 29, 2016.  In our context, it is perfectly acceptable to abbreviate the months **without** the dot in English and in Spanish.  Please allow moment to parse month names with or without the dot.

**Comment by jdnichollsc** [comment]
I have the same issue with **spanish** locale:
```
moment.locale('es');
moment.locale(); //Returns "es" (Correct)
```

But the following conversion is incorrect:
```
moment("2017-Abr-28", "YYYY-MMM-DD").toDate(); 
```
Returns Sat **Jan** 28 2017 00:00:00 GMT-0500 //wrong month, **Jan** instead of **Apr**

Thanks in advance, Nicholls

**Comment by jdnichollsc** [comment]
Guys, my temporal solution is:
```
var getMomentDate = (date) => {
  var dateParts = date.split('-');
  dateParts[1] = /^.+\.$/i.test(dateParts[1]) ? dateParts[1] : dateParts[1] + ".";
  var date = dateParts.join('-');
  return moment(date, 'YYYY-MMM-DD');
}
```

Regards, Nicholls

Regards, Nicholls

**Comment by marwahaha** [comment]
Summarizing:
* Original (Russian) issue with @Climenty has been resolved.
* German issue with @StefanWegener has been discussed and adjusted in #3829 
* en-us issue was confusion over zero-indexing on months.
* Spanish issue has moved to #3629
