### ISSUE TITLE
backward compatibility broken in move from 2.12 to 2.13

### ISSUE THREAD

**Issue by osher** [moment/moment#3215]
once I got 2.13.0 all my date related tests started breaking the following way:

```
     AssertionError: expected '2015-01-13T00:00:00Z' to be '2015-01-13T00:00:00+00:00'
     + expected - actual

     +"2015-01-13T00:00:00+00:00"
     -"2015-01-13T00:00:00Z"

```

As you can see, it's the format suffix that broke the deal.
All tests were passing in 2.12.0

Can you please help me isolate the relevant change and adjust my part accordingly?

**Comment by mj1856** [comment]
See https://github.com/moment/moment/pull/3098#issuecomment-221373686
