### ISSUE TITLE
Document add(time, key = 'milliseconds')

### ISSUE THREAD

**Issue by Moeriki** [moment/moment#3219]
The `.add` function is documented as follows.

```
moment().add(Number, String);
moment().add(Duration);
moment().add(Object);
```

Regarding `.add(Number, String)`, if you omit the second parameter it defaults to `'milliseconds'`. This is a great default, but it is not documented.

Would you mind a pull request with additional tests and documentation that cover this so I can safely use it.

**Comment by maggiepint** [comment]
Yeah, I think we would take this. At least, I can't see why we would want to change it.

**Comment by icambron** [comment]
Yeah, I'm +1 on this too.

**Comment by maggiepint** [comment]
Closing in favor of #3236
