### ISSUE TITLE
Missing files when installing with JSPM 0.17.0-beta.14

### ISSUE THREAD

**Issue by k7sleeper** [moment/moment#3221]
When installing Moment.js via JSPM v0.17.0-beta.14 by `jspm install moment` I miss the following files in the downloaded package:

```
moment.d.ts
package.json
```

and the `min` folder's empty.

I suggest to add these files to `package.json`:

```
  "jspm": {
    "buildConfig": {
      "uglify": true
    },
    "files": [
      "package.json",
      "moment.js",
      "moment.d.ts",
      "locale",
      "min"
    ],
    "map": {
      "moment": "./moment"
    }
  },
```

Thanks!

P.S.: PR?

**Comment by maggiepint** [comment]
@guybedford makes sense to me given the typescript definition is new. You?

**Comment by guybedford** [comment]
@maggiepint it may actually be worth leaving out the `files` array entirely and the `buildConfig` option has been deprecated so can be removed as well.

We then have an override in the jspm registry itself at https://github.com/jspm/registry/blob/master/package-overrides/npm/moment%402.0.0.json.

So I would actually suggest altering the jspm override to read:

```javascript
"jspm": {
    "jspmNodeConversion": false,
    "map": {
      "moment": "./moment"
    }
  },
```

**Comment by maggiepint** [comment]
@k7sleeper does this make sense to you? Want to take it?

**Comment by k7sleeper** [comment]
This absolutely makes sense to me!

But will it be enough?
I'm wondering if the downloaded (by JSPM) moment package will contain the minified builds, the locales, the type definitions and `package.json`.

**Comment by GBarthos** [comment]
I can say that it's still a problem with JSPM 0.17.0-beta.32.  
the _min_ folder's empty.

for now each time I do `jspm install`, I'm also moving the _min_ folder from my npm install to the jspm install

**Comment by guybedford** [comment]
@GBarthos yes this hasn't been resolved - it would still be advisable to make the change suggested in https://github.com/moment/moment/issues/3221#issuecomment-225867915, removing the current config at https://github.com/moment/moment/blob/develop/package.json#L74.

**Comment by GBarthos** [comment]
ok so after I made some tests, here's what I've been able to see...

If i install with ```jspm install moment```:
- the `min` folder is empty
- the `locale` folder is **not** empty
- the `src` folder is **not** empty
- `moment.js` and `moment.d.ts` are available

if I install with ```jspm install moment -o '{"jspmNodeConversion":false, "map":{"moment":"./moment"}, "files":["moment.js", "moment.d.ts", "locale", "min"]}'```:
- the `min` folder is **not** empty
- the `locale` folder is **not** empty
- the `src` folder is **not** empty
- `moment.js` and `moment.d.ts` are available

Now question is, why everything is fine except for the `min` folder ? and is it necessary to pass all those other files and folders to the 'files' attribute override ?

**Comment by marwahaha** [comment]
Any update here? @GBarthos @guybedford  @k7sleeper ? Sorry we dropped the ball here.

**Comment by k7sleeper** [comment]
No. I dont need that feature any longer because I dont use JSPM anymore.

Thanks!

2017-12-20 4:52 GMT+01:00 Kunal Marwaha <notifications@github.com>:

**Comment by marwahaha** [comment]
Closing due to age. We can re-open if this is still an issue.
