### ISSUE TITLE
Korean format longDateFormat 'L' is 'YYYY-MM-DD'

### ISSUE THREAD

**Issue by imappak** [moment/moment#3222]
Korean longDateFormat 'L' is not 'YYYY.MM.DD' but 'YYYY-MM-DD'.

**Comment by maggiepint** [comment]
@jeeeyul it looks like you are our point of contact for the Korean locale. Is this correct?

**Comment by bigtone1284** [comment]
@imappak @maggiepint @jeeeyul @kyungw00k, I just submitted a pull request.  Please review when you can.

**Comment by say8425** [comment]
https://en.wikipedia.org/wiki/Date_and_time_notation_in_South_Korea
You can find this format is standard.

**Comment by bigtone1284** [comment]
@say8425 thanks for confirming.

**Comment by kyungw00k** [comment]
@bigtone1284 👍

**Comment by mj1856** [comment]
We'll track this in the PR #3271

**Comment by mj1856** [comment]
er... #3350 now
