### ISSUE TITLE
I want to add Lao Language (lo.js)

### ISSUE THREAD

**Issue by teenking** [moment/moment#3223]
How to add lo.js to your project locale ?

// This is lo.js file
//! moment.js locale configuration
//! locale : lao (lo)
//! author : Thin Siphachanh : https://github.com/teenking

(function (global, factory) {
   typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('../moment')) :
   typeof define === 'function' && define.amd ? define(['moment'], factory) :
   factory(global.moment)
}(this, function (moment) { 'use strict';

    var lo = moment.defineLocale('lo', {
        months : 'ມັງກອນ_ກຸມພາ_ມີນາ_ເມສາ_ພຶດສະພາ_ມິຖຸນາ_ກໍລະກົດ_ສິງຫາ_ກັນຍາ_ຕຸລາ_ພະຈິກ_ທັນວາ'.split('_'),
        monthsShort : 'ມັງກອນ_ກຸມພາ_ມີນາ_ເມສາ_ພຶດສະພາ_ມິຖຸນາ_ກໍລະກົດ_ສິງຫາ_ກັນຍາ_ຕຸລາ_ພະຈິກ_ທັນວາ'.split('_'),
        weekdays : 'ອາທິດ_ຈັນ_ອັງຄານ_ພຸດ_ພະຫັດ_ສຸກ_ເສົາ'.split('_'),
        weekdaysShort : 'ອາທິດ_ຈັນ_ອັງຄານ_ພຸດ_ພະຫັດ_ສຸກ_ເສົາ'.split('_'), // yes, three characters difference
        weekdaysMin : 'ອທ._ຈ._ອຄ._ພ._ພຫ._ສຸ._ສ.'.split('_'),
        longDateFormat : {
            LT : 'H ໂມງ m ນາທີ',
            LTS : 'H ໂມງ m ນາທີ s ວິນາທີ',
            L : 'YYYY/MM/DD',
            LL : 'D MMMM YYYY',
            LLL : 'D MMMM YYYY ເວລາ H ໂມງ m ນາທີ',
            LLLL : 'ວັນddddທີ D MMMM YYYY ເວລາ H ໂມງ m ນາທີ'
        },
        meridiemParse: /ກ່ອນທ່ຽງ|ຫຼັງທ່ຽງ/,
        isPM: function (input) {
            return input === 'ຫຼັງທ່ຽງ';
        },
        meridiem : function (hour, minute, isLower) {
            if (hour < 12) {
                return 'ກ່ອນທ່ຽງ';
            } else {
                return 'ຫຼັງທ່ຽງ';
            }
        },
        calendar : {
            sameDay : '[ມື້ນີ້ ເວລາ] LT',
            nextDay : '[ມື້ອື່ນ ເວລາ] LT',
            nextWeek : 'dddd[ໜ້າ ເວລາ] LT',
            lastDay : '[ມື້ວານນີ້ ເວລາ] LT',
            lastWeek : '[ວັນ]dddd[ຜ່ານມາ ເວລາ] LT',
            sameElse : 'L'
        },
        relativeTime : {
            future : 'ອີກ %s',
            past : '%sຜ່ານມາ',
            s : 'ບໍ່ຮອດວີນາທີຜ່ານມາ',
            m : '1 ນາທີ',
            mm : '%d ນາທີ',
            h : '1 ຊົ່ວໂມງ',
            hh : '%d ຊົ່ວໂມງ',
            d : '1 ມື້',
            dd : '%d ມື້',
            M : '1 ເດືອນ',
            MM : '%d ເດືອນ',
            y : '1 ປີ',
            yy : '%d ປີ'
        }
    });

    return lo;

}));

**Comment by maggiepint** [comment]
I guess I'm not sure what you're asking here. We already have Lao in moment. If there is something wrong with the file that we have, we would take a pull request to correct it. Can you clarify what you are asking?

Thanks!

**Comment by icambron** [comment]
Closing for lack of response. @teenking please comment if you have a specific need that goes beyond the Lao locale we have and we can reopen.
