### ISSUE TITLE
moment.duration(NaN).humanize() returns "a few seconds"

### ISSUE THREAD

**Issue by pkovac** [moment/moment#3225]
Expected result: Some indication that the value is invalid.

Might this be related to #3071?

**Comment by icambron** [comment]
Yeah, agreed. Seems very similar to #3071.

**Comment by marwahaha** [comment]
would love a review at #3611 !

**Comment by marwahaha** [comment]
This is fixed in the next release:
```
moment.duration(NaN).humanize() // 'Invalid date'
```
