### ISSUE TITLE
Can moment handle BCE and CE dates?

### ISSUE THREAD

**Issue by lancejpollard** [moment/moment#324]
In relation to this question:

http://stackoverflow.com/questions/10848878/how-do-you-store-datetimes-in-a-database-on-the-scale-of-the-history-of-the-univ

... can moment handle dates like:
- 13.7 billion years ago: origin of the universe
- Photon epoch: Between 10 seconds and 380,000 years after the Big Bang (so 13.7 Billion years - 10 seconds ago)
- 8,000 BCE: end of last ice age
- 356 BCE: Alexander the Great's birth

If not, any point in the right direction on how to do this would be awesome.  Thanks!

**Comment by mohsincynexis** [comment]
Hello lancejpollard,

So how did you managed to handle 13.7 billion years ago.
Because I have to create a timeline that can go back to 13.7 billion years ago and for this I am using vis js.

**Comment by mattgrande** [comment]
@mohsincynexis: Does your timeline need to know things down to the minute/second that occurred 13+ billion years ago? If not, consider just storing the year as an integer.
