### ISSUE TITLE
Use null instead - moment.js

### ISSUE THREAD

**Issue by olama** [moment/moment#3240]
Hi there, 
I executed an analisys static with sonarQube on "moment.js", and i found a best practice call "Use null instead" on this block of code:

" if (typeof format === 'number') {
                index = format;
                format = undefined;"   <<<<<--------- Use null instead

SonarQube says:
undefined is the value you get for variables and properties which have not yet been created. Use the same value to reset an existing variable and you lose the ability to distinguish between a variable that exists but has no value and a variable that does not yet exist. Instead, null should be used, allowing you to tell the difference between a property that has been reset and one that was never created.

Noncompliant Code Example
---------------------------------------------------------
var myObject = {};

// ...
myObject.fname = undefined;  // Noncompliant
// ...

if (myObject.lname == undefined) {
  // property not yet created
}
if (myObject.fname == undefined) {
  // no real way of knowing the true state of myObject.fname
}

Compliant Solution
------------------------------------------------------
var myObject = {};

// ...
myObject.fname = null;
// ...

if (myObject.lname == undefined) {
  // property not yet created
}
if (myObject.fname == undefined) {
  // no real way of knowing the true state of myObject.fname
}

Best regards,

Oscar Lama S.

**Comment by icambron** [comment]
Thanks, but I'm going to leave this. While either would work, I think `undefined` is fine here.

**Comment by jamees** [comment]
thanks @olama in my project I got the same issue... maybe is better skip that from the static analysis
