### ISSUE TITLE
Dutch parsing of abbreviated month name with dash does not work

### ISSUE THREAD

**Issue by middagj** [moment/moment#3242]
Dutch locale removes the dot from the abbreviated if it is used in a dashed notation: `DD-MMM-YYYY`. However, it doesn't work the other way around, which I think should be possible.

See https://jsfiddle.net/ztroj5zv/ for an example

I was trying to create custom regular expressions in the locale for the month, but this doesn't work because the remapping is always done using the normal month name:

```javascript
for (i = 0; i < 12; ++i) {
    mom = createUTC([2000, i]);
    this._shortMonthsParse[i] = this.monthsShort(mom, '').toLocaleLowerCase();
    this._longMonthsParse[i] = this.months(mom, '').toLocaleLowerCase();
}
```

If you have any thought what would be a good general approach to fix this. My first idea was to pass the context of the token (thus `-MMM-`) to `handleStrictParse` such that it can be passed again to `monthsShort` again. I am happy to help implementing.

@mention jjupiter
A side node is probably that both ways of writing the abbreviated month names are accepted (even if not surrounded by dashes). See also: http://taaladvies.net/taal/advies/vraag/1727/afkortingen_van_de_namen_van_de_maanden/
I am used to never write it with a dot. If it is possible to pass configuration options when setting the locale, we can also choose that approach, and don't have to rewrite the parsing logic.

**Comment by icambron** [comment]
This may be easier than that. I haven't dug into the details, but there are some additional options you can add to the NL locale that modifying month parsing. See [Russian](https://github.com/moment/moment/blob/d6651c21c6131fbb5db891b60971357739015688/src/locale/ru.js) for an example. Not completely sure, but I suspect you can use something in there to solve this.

**Comment by middagj** [comment]
I see, you can also reconfigure the parsing logic if you put the `monthsParseExact` to `false`. I have created a pull request #3259.
