### ISSUE TITLE
require.js support for locale bootstrapping

### ISSUE THREAD

**Issue by joelharkes** [moment/moment#3243]
i've been trying for a long while to make requirejs load in moment js properly. I had it working but i wanted to add that whenever moment.js is loaded in the locale is set properly (based on language setting of the website).

since my website will have plugins from third parties i want `require(['moment']..` to directly export the moment with the right locale set. 

First i made a wrapper js file. but this didnt work since momentjs needs to be required with the alias `moment`.

I tried the init function but this one is not called since momentjs uses require.js's define.amd

For now i made the hack  that one of the first scripts sets the moment locale appropriately. but it could still mean (since everything is loaded async) that this will fire later than another script using moment.js.

Can you not give us require.js developers some slack providing a better way to boostrap the right locale onto momentjs?

I also don't want to expose moment js with alias `moment` because this might lead to miss use by third party developers.

The scenarios i described i tested on v 2.10.6 of momentjs

**Comment by maggiepint** [comment]
Want to try to help you with this, but we have no require expertise on the moment team. Because we have quite a few Require.js issues, I just put an issue on their repo asking for help. See requirejs/requirejs#1554

**Comment by maggiepint** [comment]
@joelharkes if you look at that issue on the Require repo, they give a very good explanation of how to do this.

**Comment by joelharkes** [comment]
I see yes, read this morning about require.js's map functionality. it ain't neat but it will do the trick. Thanks
