### ISSUE TITLE
Locale aware format without time

### ISSUE THREAD

**Issue by Padam87** [moment/moment#3245]
Hi,

I would like to use the `LLLL` format, without the time being displayed. I can't seem to find an appropriate format in docs.

Is this possible to do?

Currently I'm using a hacky way:
`moment(date).format('LLLL').replace(moment(date).format('LT'), '')`

Thanks!

**Comment by icambron** [comment]
Unfortunately, your hack is your only option now. Closing this in favor of #2505.
