### ISSUE TITLE
moment,fromNow returns "2 days ago" even though it's only been 36-48 hours

### ISSUE THREAD

**Issue by jimmaay** [moment/moment#3246]
Why does it round up so much? It should be 2 days ago once it's been 48 hours since. I have it show relative and calendar time and it sometimes says "2 days ago yesterday at 1:00am" from certain times between 36-48 hours.

**Comment by icambron** [comment]
No, it's useful for a lot of use cases that it rounds; most people are only showing "2 days ago" by itself, where it makes a lot more sense than showing "a day ago" for 47 hours and 59 minutes.

**Comment by jimmaay** [comment]
Is there an option to disable the rounding? 2 days ago is not technically correct nor would most people consider 36 hours to be "2 days ago". If it is 8:01pm and the event was yesterday at 8am (which is a very common scenario) most people would definitely say it was a day ago. At least tighten up the rounding.

**Comment by icambron** [comment]
If you're willing to build the head of the `develop` branch, you can do this:

```js
> var moment = require("./build/umd/moment")
> moment.relativeTimeRounding(Math.floor)
> moment().subtract(38, 'h').fromNow()
'a day ago'
```

**Comment by gordonbisnor** [comment]
I've noticed the same issue where I'm providing a date only eg "2016-08-01" and it's coming out as 2 days ago, I guess because it's interpreting my date as datetime. Could be useful if there was a date only option, such that 2016-08-1 would remain 1 day ago until 2016-08-03.
