### ISSUE TITLE
Retrieve just the oridinal

### ISSUE THREAD

**Issue by carbontwelve** [moment/moment#3249]
I am using this on a site where I need to format the date in html to be `21<sup>st</sup> December 2016` but I can't seem to find a way of getting just the ordinal from moment.

**Comment by icambron** [comment]
Moment's ordinals come from a per-locale function that takes in a number and returns the ordinalized number. We do it that way to maximize the flexibility afforded to each locale (e.g. [this one](https://github.com/moment/moment/blob/develop/locale/en-gb.js#L51)]. So there isn't a way to just get the suffix (Moment doesn't even require that it be a suffix). You'd have to parse it out yourself, unfortunately.
