### ISSUE TITLE
Moment is not defined - version 2.13.0

### ISSUE THREAD

**Issue by professorDante** [moment/moment#3250]
Just trying out moment, so downloaded latest min version 2.13.0. Running in Chrome browser, so add this in, as per the docs. Seems simple:

    <script src="<path-to-js-dir>/moment.min.js"></script>
    <script>
      moment().format();
    </script>

Doesn't work, just keep getting the error 'moment is not defined'.

**Comment by maggiepint** [comment]
What is the value of <path-to-js-dir>? Is that where you have the moment.min.js file? 

What happens if you use cdnjs instead of a local path?
https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js

**Comment by professorDante** [comment]
Good idea on cdn - it works if you access file from there. 

How can the remote build be different to the downloaded file?

**Comment by maggiepint** [comment]
I wouldn't think it is. My best guess is that your path is wrong - maybe a typo or something.

**Comment by professorDante** [comment]
No, path is correct.
