### ISSUE TITLE
Persian Locale problem

### ISSUE THREAD

**Issue by MehdyKarimpour** [moment/moment#3253]
When using Persian locale dates are not converted by Jalali Calendar and only the captions are translated.

**Comment by icambron** [comment]
To see dates in Jalali Calendar, you need to use the [Jalaali calendar plugin](https://github.com/jalaali/moment-jalaali).

**Comment by m-farahmand** [comment]
this plugin ain't implement all methods and introduce new functions it makes others library to malfunction.
I use this module to localizing mat-datepicker and after rewriting some function to force it to use jalaali moment understood which jalaali isn't support this use case and just  support jalali calendar when we call explicit methods like jYear().
