### ISSUE TITLE
date formating for different locales return name of months and days in small instead of camel case

### ISSUE THREAD

**Issue by sanjaybhagia** [moment/moment#3257]
The formatting for the names of days and months are in small alphabet instead of camel strings, as it is in English language. 

moment.locale('sv')
moment().format('MMMM') // returns juni
moment().format('dddd)  // return onsdag

moment.locale('en')
moment().format('MMMM') // returns June
moment().format('dddd)  // return Wednesday

It should be consistent in my opinion. 

/Sanjay

**Comment by maggiepint** [comment]
This is the choice of the person who wrote the locale file. Different cultures have different rules for the casing of dates. If you are able to, for a specific locale, provide us with a native speaker who believes the casing should be different, we are willing to take pull requests for changes. In general though, every culture does things differently, so there is no way to consistently case anything in the locale files.

**Comment by sanjaybhagia** [comment]
Hej maggie, 

Fair enough, thanks for the explanation.
