### ISSUE TITLE
moment.isValid: inconsistent behaviour

### ISSUE THREAD

**Issue by gkubisa** [moment/moment#3260]
https://jsfiddle.net/9vodk57t/

**Comment by ichernev** [comment]
Currently `isValid` only handles creation. All other operations, if the moment is already valid try to keep it valid. So passing a weird value like `NaN` should just be ignore, other than make it invalid.

**Comment by Jecoms** [comment]
Would this be a possible fix? 6d2ef540937c230d9ded54493c85c4bea55970d9
If I understand it correctly, this would check for NaN and return the get function if the value isn't null, but is NaN. Would there be a better way to go about ignoring invalid input?

**Comment by kishoreaoe** [comment]
![image](https://user-images.githubusercontent.com/6896519/34401124-826f6570-eba9-11e7-969f-6bf44b4ae997.png)

I am getting Invalid Date when i am trying to use below code:

var m = moment(AUGUST-2017); // Problem is occuring only in IE.
Could you please help me out with this issue.

**Comment by marwahaha** [comment]
I see this as more of a documentation concern.
