### ISSUE TITLE
Belgian Dutch locale (nl-be)

### ISSUE THREAD

**Issue by ThomasVandenbon** [moment/moment#3264]
As also mentioned by @dietergeerts in #1803, a Belgian-Dutch locale is missing.
The only difference with the dutch locale (as far as I know), is the fact that the separator used in Belgium is "/" rather than "-".

Example: 26**/**06**/**2016

The Belgian-Dutch locale could be a nearly exact copy of the Dutch locale, which was made by @jorisroling.

**Comment by maggiepint** [comment]
Closing in favor of #3264
