### ISSUE TITLE
moment.isValid ignoring extra characters

### ISSUE THREAD

**Issue by mikeresult** [moment/moment#3268]
Extra characters added anywhere in the date string are ignored, most alarmingly ignoring numerals beyond the expected number of digits. All of the following return true:

`moment("1234567890/1234567890", "MM/DD/YYYY").isValid()`
`moment("1234567890-1234567890-12345678900-1234567890", "MM-DD-YYYY").isValid()`
`moment("///1234567890///invalid////12345678900///1234567890///", "MM/DD/YYYY").isValid()`

**Comment by maggiepint** [comment]
Yep, that's how it works. Use strict mode and you will get the result you want:

```js
moment("1234567890/1234567890", "MM/DD/YYYY", true).isValid()
false
moment("1234567890-1234567890-12345678900-1234567890", "MM-DD-YYYY", true).isValid()
false
moment("///1234567890///invalid////12345678900///1234567890///", "MM/DD/YYYY", true).isValid()
false
```

http://momentjs.com/guides/#/parsing/strict-mode/
