### ISSUE TITLE
moment(s).parseZone() not documented

### ISSUE THREAD

**Issue by tiljanssen** [moment/moment#3270]
It took me quite some time and digging in issues to discover that parseZone  without any arguments can be used in the same manner as "local()" and "utc()".

Documentation will be improved if you include this use case.

I just want one timestamp that I want to display in the original and local time. A formatter would have been nice, but now at least I can do ts.parseZone().format() and ts.local().format()

**Comment by icambron** [comment]
Yeah, there should be a section for that in the `Manipulate` section of the docs. Want to write us a PR for the [docs site](https://github.com/moment/momentjs.com)?

**Comment by maggiepint** [comment]
I'm going to close this since you raised an issue on docs, which is really more appropriate moment/momentjs.com#333
