### ISSUE TITLE
Duration of any October in weeks is 0

### ISSUE THREAD

**Issue by kuzzmi** [moment/moment#3274]
### Issue details

moment version: 2.13.0
node: 6.2.0, 6.2.2

```javascript
const getTotalWeeksInMonth = date => {
    const endOf = moment(date).endOf('month');
    const startOf = moment(date).startOf('month');
    const duration = moment.duration(endOf - startOf);
    
    return duration.weeks() + 1;
}
```

Here is a function I use for detecting amount of weeks in a month. It looks OK, until we need to deal with October.

For some reason the duration object looks really weird if we pass any year's October:

```
Duration
    _data: Object
        days: 0
        hours: 0
        milliseconds: 999
        minutes: 59
        months: 1
        seconds: 59
        years: 0
```

Whereas any other month looks OK:

```
Duration
    _data: Object
        days: 29
        hours: 23
        milliseconds: 999
        minutes: 59
        months: 0
        seconds: 59
        years: 0
```

[Here is an isolated and runnable code](https://tonicdev.com/577837db9e5cf213007762e2/577837db9e5cf213007762e3)

I've just started looking into moment's sources, will try to make a test for that. If anybody knows how to workaround that - would like to know.

I'll try to fix this, but if anybody wants to do this instead - go for it.

**Comment by maggiepint** [comment]
Also, I think you are conflating ``asWeeks`` and ``weeks``.

You probably want ``asWeeks``. That gets you the total number of weeks in a duration, as defined by a week being 7 days. ``weeks`` is the weeks part of the duration, if it were broken into pieces. This is best illustrated with the following code:

```js
moment.duration(moment('8 Dec 2016', 'D MMM YYYY') - moment('1 Oct 2016', 'D MMM YYYY')).months() //this duration is two months
2
moment.duration(moment('8 Dec 2016', 'D MMM YYYY') - moment('1 Oct 2016', 'D MMM YYYY')).weeks() //and one week
1
moment.duration(moment('8 Dec 2016', 'D MMM YYYY') - moment('1 Oct 2016', 'D MMM YYYY')).asWeeks() //or 9.72 weeks
9.720238095238095
```

**Comment by kuzzmi** [comment]
Hi, try to run the [following](https://tonicdev.com/577837db9e5cf213007762e2/577867d29f199c13001bb931):

```
var moment = require("moment");

moment.duration(moment('1 Oct 2016', 'D MMM YYYY').endOf('month') - moment('1 Oct 2016', 'D MMM YYYY').startOf('month')).weeks() // 0
```

Weird... This outputs 0 for me, but 4 for you.

It just makes no sense to me to have 0 weeks, but 1 month difference between 1 Oct and 31 Oct. And, just to make it clear, it's applicable to any other year's October.

`asWeeks` was the only way to go, but it's not accurate at all for this case. As the amount of full or partial weeks between 1 Oct and 31 Oct is 6, but the numeric result of `asWeeks` is the same as when the actual number is 5.

**Comment by maggiepint** [comment]
The reason why your code and mine differ is that Switzerland (where you appear to be based on your github profile) is on Central European Time, and does a daylight saving time transition in the month of October. Meanwhile where I am (United States Central) does not. This means that the number of milliseconds in October where you are is different than the number of milliseconds in October where I am. This is also why you are seeing October as a special case in your code.

Durations have no knowledge of the actual calendar - they are just a mechanism for converting milliseconds to other units. What your code is doing is taking the number of milliseconds between October 1 and October 31 (which varies based on time zone), and then figuring out how many seven day units it has, assuming a day is 24 hours (which is in and of itself not always true). It's using simple arithmetic and has no concept of partial weeks.

If you want to get the number of calendar weeks in a month, including partial weeks, I would suggest doing this instead:

```js
moment('1 Oct 2016', 'D MMM YYYY').endOf('month').week() - moment('1 Oct 2016', 'D MMM YYYY').startOf('month').week()
5
```
That will take the week number of the end of the month, and subtract it from the week number of the start of the month, which I think is really what you want here.

**Comment by maggiepint** [comment]
This might also be worthwhile reading: http://momentjs.com/guides/#/lib-concepts/date-time-math/

**Comment by kuzzmi** [comment]
It does make sense to me now. I still sometimes struggle to wrap my head with the date and time maths.

I assume that my issue is not even an issue, so may be it's worth to close it.
