### ISSUE TITLE
moment.d.ts 2.14.0 - issues (perhaps noImplicitAny related)

### ISSUE THREAD

**Issue by johnnyreilly** [moment/moment#3278]
There appear to be some issues with `moment.d.ts` that ships with 2.14.0.  I started noticing errors like this in my build:

```
ERROR in C:\projects\proverb-angular\node_modules\moment\moment.d.ts
(526,58): error TS1144: '{' or ';' expected.
ERROR in C:\projects\proverb-angular\node_modules\moment\moment.d.ts
(526,19): error TS7010: 'calendarFormat', which lacks return-type annotation, implicitly has an 'any' return type.
ERROR in C:\projects\proverb-angular\node_modules\moment\moment.d.ts
(526,61): error TS2304: Cannot find name 'string'.
```

I'm reverting back to 2.13.0 for now (no problem with that version that I can tell)

**Comment by urzhumskov** [comment]
line 526 `export function calendarFormat(m: Moment, now: Moment) => string;`

should be: `export function calendarFormat(m: Moment, now: Moment): string;`

**Comment by ichernev** [comment]
Close in favor of #3280
