### ISSUE TITLE
2.14.0: No compatible binary build found for this package.

### ISSUE THREAD

**Issue by hg-stolle** [moment/moment#3279]
Hi!

When I try to update Moment.js to the newest version I get the following error:
    $ meteor update
    This project is already at Meteor 1.3.4.1, the latest release.
    => Errors while upgrading packages:           
                                              
    While checking for momentjs:moment@2.14.0:
    error: No compatible binary build found for this package. Contact the package
    author and ask them to publish it for your platform.

Not sure whether this is a problem of atmospherejs.com or a problem mit the momentjs package, but someone should definitely look into it. For the moment I'll just stick with the 2.13.1 release instead.

PS: Not sure if that matters, but I'm using Meteor and momentjs on a 64-bit Linux machine (Debian 8.5).

**Comment by aboire** [comment]
for me the same mistake this morning

**Comment by stereonom** [comment]
+1

**Comment by icambron** [comment]
Yikes, I have no idea. @splendido, any pointers?

**Comment by ichernev** [comment]
Which env are you in? Windows, linux? I tried to push from the vms they provide but it failed because its already pushed... I have no idea what is and isnt any more.

**Comment by hg-stolle** [comment]
@ichernev: 64-bit Linux with Debian 8.5.

**Comment by cvax** [comment]
@ichernev I am getting the same issue on Windows.
Windows 7, 64-bit
Trying to update momentjs:moment 2.13.1 to 2.14.2 fails with "No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform."

Thanks.

**Comment by ichernev** [comment]
I'm trying to fix the issue : https://github.com/meteor/meteor/issues/7403

**Comment by hg-stolle** [comment]
@ichernev:
I've just tried to update to version 2.14.4, and that version seems to work again. Thanks for fixing it.
