### ISSUE TITLE
moment.min.js download contains comments

### ISSUE THREAD

**Issue by Knagis** [moment/moment#3283]
The download from http://momentjs.com/downloads/moment.min.js does not have the comments removed while the previous versions had.

**Comment by icambron** [comment]
Hmm, thanks.

@ichernev just a guess, but is this an unexpected consequence of #3234?

**Comment by jdalton** [comment]
Uglify.js has an option to preserve header comments (It can even be customized with a regexp). See https://github.com/mishoo/UglifyJS2#keeping-copyright-notices-or-other-comments.

**Comment by skfd** [comment]
I think that's an [issue](https://github.com/gruntjs/grunt-contrib-uglify/issues/426) in grunt-contrib-uglify. Here's a PR #3337.

**Comment by Knagis** [comment]
This is still actual in version 2.17.1

**Comment by marwahaha** [comment]
This is resolved.
2.17.1: https://github.com/moment/moment/blob/2.17.1/min/moment.min.js 
2.18.0: https://github.com/moment/moment/blob/2.18.0/min/moment.min.js
