### ISSUE TITLE
Weekdays() is not localised and does not return days in the ISO week day order

### ISSUE THREAD

**Issue by curiosity101** [moment/moment#3284]
It seems like these are probably two separate but related issues.

moment.weekdays() is not localised even though the docs imply it should be.
See this section: http://momentjs.com/docs/#/i18n/locale-data/

I tried moment.locale('en-gb').weekdays() and got 'weekdays is not a function'.

Also moment.weekdays() does not return the days in the ISO week day order. Even if it is localised I'd have though it makes more sense that by default the order should follow the ISO week day order.

**Comment by icambron** [comment]
Hmm, it should be:

```js
moment.localeData('en-gb').weekdays()
```

but that also throws an error.

**Comment by curiosity101** [comment]
Sorry that was a typo on my part. I did mean I tried:
`moment.localeData('en-gb').weekdays()`

Thanks for looking into it

**Comment by sibennayak** [comment]
Doing a `moment.localeData('en-gb').weekdays() ` simply throws `TypeError: Cannot read property 'day' of undefined`.

**Comment by github-polymer-user** [comment]
now moment.weekdays is actually localized, but switching locales does not change formatting fo the day of week in format:

date.format('dddd DD.MM.YYYY');

Temp workaround:

moment.weekdays(parseInt(date.format('E'))) + ' ' + date.format('DD.MM.YYYY');

**Comment by icambron** [comment]
So I think what happened here is that we changed an internal signature change but failed to change the apparently untested static locale listing functions like `weekdays()` to use that new signature. A PR fixing them would be gladly accepted.

**Comment by sibennayak** [comment]
Should this be changed in the documentation or the code? The documentation surely is misleading (the method signatures).

**Comment by icambron** [comment]
> Or the code? weekdays() should return an array with all days of week for that locale?

The code, I think.

**Comment by mj1856** [comment]
Tracked in #3312
