### ISSUE TITLE
Locale formatting not working.

### ISSUE THREAD

**Issue by trichner** [moment/moment#3286]
Hi, I'm getting a weird error from moment.js during `moment(..).format('dd DD. MMM YYYY')`.
Sometimes it seems to work fine but in other cases it throws a `TypeError` (see below).

I tried to track down the underlying problem with no success, as far as I can see it's related to locales. Hence I used the `with-locales` version (previously I included only the necessary locales).

I am using the latest (`2.14.1`) `min/moment-with-locales.js` from bower. Older versions such as `2.11` also didn't work properly.

```
angular.js:13708 TypeError: this.localeData(...).weekdaysMin is not a function
    at Moment.<anonymous> (moment-with-locales.js:1230)
    at Object.dd DD. MMM YYYY (moment-with-locales.js:612)
    at formatMoment (moment-with-locales.js:627)
    at Moment.moment_format__format [as format] (moment-with-locales.js:3057)
```

Which is thrown here:
```
addFormatToken('dd', 0, 0, function (format) {
        return this.localeData().weekdaysMin(this, format); // <--- TypeError
});
```
Due to `this._locale._weekdaysMin = ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"]` being an array.

This is the moment object I'm trying to format: https://gist.github.com/trichner/f2d3ff0a7e6c2b3d668ded52cf69f245#file-gistfile1-txt

Is there anything I missed? Or could it be a library bug?

**Comment by trichner** [comment]
I found the issue, apparently `angular.merge` and `moment` don't mix well.

**Comment by github-polymer-user** [comment]
Currently, moment.weekdays is actually localized, but switching locales does not change formatting fo the day of week in moment.format using week format specifier dddd:

moment.locale('ru');
date.format('dddd DD.MM.YYYY');
moment.locale('fr');
date.format('dddd DD.MM.YYYY');

Temp workaround:

moment.weekdays(parseInt(date.format('E'))) + ' ' + date.format('DD.MM.YYYY');

**Comment by icambron** [comment]
Oops, didn't mean to label that a bug.

See #3080
