### ISSUE TITLE
Drop IE 8 Support

### ISSUE THREAD

**Issue by maggiepint** [moment/moment#3288]
For 3.0 we should drop support for IE 8. There are several shims in the code that can be removed at this time. Notably, several things in the utils folder can go. This will be helpful for reducing library size.

**Comment by Alanscut** [comment]
@maggiepint  Is this proposal still in progress? I am happy to contribute a pull request 😄.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
