### ISSUE TITLE
Showing Invalid Date in Firefox..

### ISSUE THREAD

**Issue by VenkatRamNDD** [moment/moment#3289]
console.log(moment("30-Jun-2016").format("DD-MM-YYYY"))
     In Chrome it is showing correctly but coming to Firefox it is showing invalid date....

**Comment by not-an-aardvark** [comment]
You're not specifying a format for parsing the string `30-Jun-2016`, so moment falls back to the native `Date` object, which is inconsistent across different browsers.

To parse the date consistently, include a format string along with it.

e.g.

```js
moment("30-Jun-2016", "DD-MMM-YYYY")
```

Then if you want to format the moment object as a string, you can do what you were doing before:

```js
moment("30-Jun-2016", "DD-MMM-YYYY").format("DD-MM-YYYY")
```

...which returns the string `30-06-2016` in both browsers.

**Comment by maggiepint** [comment]
@not-an-aardvark is correct, so closing.

**Comment by anilljoshi** [comment]
@not-an-aardvark thanks that's what i was looking for

**Comment by anilljoshi** [comment]
@not-an-aardvark  thank you very much

**Comment by narutoo9x** [comment]
@not-an-aardvark Thank you. It works like a charm.

**Comment by arishvns** [comment]
@not-an-aardvark thank you bro....
