### ISSUE TITLE
moment(string) default year 2001

### ISSUE THREAD

**Issue by levdavid** [moment/moment#3295]
I am getting 2001 as a default year if i don't specify it in the input.

**Comment by levdavid** [comment]
it seems like this kind of input is being depreciated though.

**Comment by maggiepint** [comment]
If you are getting the 'moment construction falls back to JS date' warning, there is nothing we can do to help you. You are not using Moment's parser to parse the date, you are using the browser's date parser. Specify a known format for your date instead.

**Comment by arlowhite** [comment]
My vote is to re-open this.
"3 Mar" is valid **RFC 2822 Date time** but the year defaults to 2001.
Users should have a way to specify the default year or a way to check if the year was not specified within the input.

**Comment by maggiepint** [comment]
@arlowhite - this issue predates Moment having RFC2822 support - that only came out a couple months ago. If you think that we aren't adequately handling RFC2822 in the most recent version, then please raise a new issue with the exact version you are running, and the exact code and date string you are passing.
