### ISSUE TITLE
Using moment to find the next time / event

### ISSUE THREAD

**Issue by mscreenie** [moment/moment#3297]
Does moment.js have a function to determine the next time / date out of an array of times.

Example: 

Current Time: **10/07/2016 15:19**

Array: {
1: "10/07/2016 10:20",
2: **"10/07/2016 15:21",**
3: "10/07/2016 15:40",
4: "11/07/2016 11:40",
}

Output: 

The next time is 10/07/2016 15:21 and begins in x (120) seconds.

I am willing to write a plugin to do this if there is no way of achieving this in moment.

**Comment by icambron** [comment]
There's no built-in way, no. It should be relatively easy to do in userspace though. This seems to work:

```js
var next = [
  "05/07/2016 10:20",
  "10/07/2016 10:20",
  "10/07/2016 15:21",
  "10/07/2016 15:40"
].map(function(s){
  return moment(s, "MM/DD/YYYY HH:mm");
})
.sort(function(m){
  return m.valueOf();
})
.find(function(m){return m.isAfter();});

if (next) {
  console.log("Next time is", next.format("MM/DD/YYYY HH:mm"), "which is", next.fromNow());
}
else {
  console.log("No next event");
}
```

Plugins always welcome for the plugin list.

**Comment by mscreenie** [comment]
Thanks. That's a beautiful solution.

**Comment by mscreenie** [comment]
I parsed the dates with moment and converted to timestamp in the end. Split the events with > < before before and after and selected the closest ones to represent next and previous. Thanks.

**Comment by SalmanKarim42** [comment]
> There's no built-in way, no. It should be relatively easy to do in userspace though. This seems to work:
> 
> ```js
> var next = [
>   "05/07/2016 10:20",
>   "10/07/2016 10:20",
>   "10/07/2016 15:21",
>   "10/07/2016 15:40"
> ].map(function(s){
>   return moment(s, "MM/DD/YYYY HH:mm");
> })
> .sort(function(m){
>   return m.valueOf();
> })
> .find(function(m){return m.isAfter();});
> 
> if (next) {
>   console.log("Next time is", next.format("MM/DD/YYYY HH:mm"), "which is", next.fromNow());
> }
> else {
>   console.log("No next event");
> }
> ```
> 
> Plugins always welcome for the plugin list.

Thanx for this one you saved my day 👍

**Comment by ZgodaRafal** [comment]
> ```js
> .sort(function(m,n){
>   return m.valueOf() - n.valueOf();
> })
> ```
