### ISSUE TITLE
conflicting two moment.js on the same page

### ISSUE THREAD

**Issue by manojwtb** [moment/moment#3298]
Hi,

We are using moment.js globally (in compiled form) and some of our client also using moment.js on the same page as globally. We have updated our js file recently and replaced locale()  with updateLocale()  to avoid depreciation warning  while client's moment seems to be old and doesn't contains  updateLocale(), that's why its throwing following error:
TypeError: moment.updateLocale is not a function.

 is there any option in moment.js jquery i.e. 
var jQ = jQuery.noConflict();
or what should I do to remove this confliction? Please advice.

**Comment by icambron** [comment]
No, that's not possible. Note, for example, that jQuery's noConflict() doesn't allow multiple things to be assigned the global name `jQuery`; it just prevents jQuery from aliasing `$` to `jQuery`. Two values can't share the same global name; that's more or less what "global" means.

You can rename the global if you want, though:

```html
<script src="moment.js"></script>
<script>
  window.supermoment = window.moment
</script>

//downstream imports here
```

Or you can import it non-globally using requirejs or similar.
