### ISSUE TITLE
Calling add/subtract mutates the original instance of moment

### ISSUE THREAD

**Issue by brianmmorton** [moment/moment#3300]
Hey moment team,

Thanks for the library, I love it. Ran into this bug and it took me 3 hours to realize what was happening. Sorry for the poor title.

var a = moment("Tue Jul 12 2016 23:02:04 GMT-0700 (PDT)")
var b = a.add(120, 'm')

a.format('hh:mm')
// "01:02"
b.format('hh:mm')
// "01:02"

momentStart should be the original GMT time put in as a string. Instead, it is equal to the value of adding 120 mins (only momentEnd should hold the result of that operation).

I am proposing that the original instance should not be modified when calling the add method. 

Thoughts?

**Comment by maggiepint** [comment]
Yes it does. See this: https://maggiepint.com/2016/06/24/why-moment-js-isnt-immutable-yet/
And this: http://momentjs.com/guides/#/lib-concepts/mutability/

In addition, I should have another blog post out in the next couple days about immutability. We are moving forward with an official plugin that will allow a person to construct moments with an immutable API. Hopefully we get this out soon, but it's a bigger project.
