### ISSUE TITLE
Timezone converting to UTC is wrong

### ISSUE THREAD

**Issue by HamzaLJ** [moment/moment#3301]
By creating a date object using `hour:20` in timezone `Africa/Casablanca` I expect the UTC  hour to be `19`, but it's showing `20`.

Demo: https://jsfiddle.net/pojt2r99/

```js
moment.tz.add("Africa/Casablanca|LMT WET WEST CET|u.k 0 -10 -10|0121212121212121213121212121212121212121212121212121212121212121212121212121212121212121212121212121|-2gMnt.E 130Lt.E rb0 Dd0 dVb0 b6p0 TX0 EoB0 LL0 gnd0 rz0 43d0 AL0 1Nd0 XX0 1Cp0 pz0 dEp0 4mn0 SyN0 AL0 1Nd0 wn0 1FB0 Db0 1zd0 Lz0 1Nf0 wM0 co0 go0 1o00 s00 dA0 vc0 11A0 A00 e00 y00 11A0 uM0 e00 Dc0 11A0 s00 e00 IM0 WM0 mo0 gM0 LA0 WM0 jA0 e00 Rc0 11A0 e00 e00 U00 11A0 8o0 e00 11A0 11A0 5A0 e00 17c0 1fA0 1a00 1a00 1fA0 17c0 1io0 14o0 1lc0 11A0 1o00 11A0 1qM0 WM0 1qM0 WM0 1qM0 11A0 1o00 11A0 1o00 11A0 1qM0 WM0 1qM0 WM0 1qM0 WM0 1qM0 11A0 1lc0 14o0 1fA0|32e5");
      
      
    alert(moment.tz({ year: 2016, month: 6, date: 13, hour: 20 }, "Africa/Casablanca")._d.toUTCString());
````

**Comment by IonicaBizau** [comment]
By using the `toDate` method, that will work:

```js
alert(moment.tz({ year: 2016, month: 6, date: 13, hour: 20 }, "Africa/Casablanca").toDate().toUTCString());
```

[**JSFiddle**](https://jsfiddle.net/pojt2r99/4/)

**Comment by maggiepint** [comment]
@IonicaBizau we do not recommend using the JS date object with moment. Moment is a complete API and date should not be required unless you need to pass a date to a third party that expects one.

@HamzaLJ the _d variable is internal, and it will not be accurate - see documentation here: http://momentjs.com/guides/#/lib-concepts/internal-properties/

To display the date in UTC, do the following:

```js
moment.tz({ year: 2016, month: 6, date: 13, hour: 20 }, "Africa/Casablanca").utc().format()
"2016-07-13T19:00:00Z"
```

For more information on this see: http://momentjs.com/docs/#/parsing/utc/

This blog post may also be helpful: https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/

**Comment by IonicaBizau** [comment]
> unless you need to pass a date to a third party that expects one.

Exactly 👍
