### ISSUE TITLE
Meteor / Atmospherejs 2.14.3

### ISSUE THREAD

**Issue by flean** [moment/moment#3304]
While checking for momentjs:moment@2.14.3:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

**Comment by Dubbedge** [comment]
I second that.

**Comment by ichernev** [comment]
https://github.com/moment/moment/issues/3279

**Comment by ichernev** [comment]
I'm working on it. I'll try to release later today without depending on `package.json`
