### ISSUE TITLE
Detect changes to system clock

### ISSUE THREAD

**Issue by robmcm** [moment/moment#3305]
If you have a moment and have rendered it to screen in a local format, then the user changes their timezone (they could remote into a machine after traveling internationally, app running over DST change, etc) the rendered date needs to be re-formatted. 

Currently I can't see any way for moments to notify of the change, is it intended that the user of the moment would detect underlying timezone/clock changes (potentially on interval compare a stored and current date)?

Thanks

**Comment by icambron** [comment]
Yeah, I think of that as something the user should do, something like this (untested):

```js
var time = moment(),
      now;
setInterval(function(){
   now = moment();
   if (time.diff(now, 'h') > 1) { //for example
     goRerenderStuff();
   }
   time = now;
}, 10);
```

That's definitely something we don't want to do in Moment itself; it's a little too invasive for this kind of library and it seems easy enough to do for Moment users.

**Comment by robmcm** [comment]
Thanks for the response.

My only concern is that if you have multiple inputs and components that have rendered dates you don't want to have multiple timers or duplicated code. This could potentially be performed by a single static instance inside moment, that could dispatch an event (or similar) when a change was detected. Currently I expect most applications using moment won't anticipate this potential issue, but then perhaps most uses aren't long lived applications.
