### ISSUE TITLE
Calendar call produces gibberish

### ISSUE THREAD

**Issue by eatonphil** [moment/moment#3306]
I'm trying to format a date and moment produces gibberish. [Here](https://jsfiddle.net/yxhonbov/) is a jsfiddle reproducing the issue.

```javascript
const calendar = {
  sameDay: '[Today]',
  nextDay: '[Tomorrow]',
  nextWeek: 'dddd',
  lastDay: 'Yesterday',
  lastWeek: 'dddd',
  sameElse: moment.ISO_8601,
}

const m = moment('2016-07-14T18:33:07');
console.log(m.calendar(null, calendar)); // prints 201647t4r4pmy
```

**Comment by icambron** [comment]
I just ran your fiddle and it print "Thursday" to my console. What browser are you using to run it?

**Comment by eatonphil** [comment]
Running that same exact JSFiddle produces "Thursday", you are right. I just switched it to yesterday though ("2016-07-16T18:33:07") and it now produces "201667t6r6pmy". I am running Chrome 51.0.2704.106 (64-bit) on OS X 10.11.5 (15F34).

**Comment by icambron** [comment]
You want '[Yesterday]', not 'Yesterday' which Moment is considering a series of formatting tokens, like the 'Y' means the year, etc.
