### ISSUE TITLE
Not updating moment locale on same page

### ISSUE THREAD

**Issue by kamalmlk** [moment/moment#3309]
Hello, I am trying to display time in abbreviated and not abbreviated on same page usin moment.js. But not getting success.  
Is there any solution so that I could reset the moment object and update it on same page?

**Comment by icambron** [comment]
I'm not sure I understand. It sounds like you're formatting out a string and then trying to update the string? You want something like this:

```js
var m = moment();
var abbreviated = moment().format("LLL");
var longer = moment().format("LLLL");
```

**Comment by kamalmlk** [comment]
I am trying to use relative time in both  abbreviated form and  non-abbreviated form on same page. But the relative time doesnot get updating If I am using locale_lang ((var locale_lang = window.navigator.userLanguage || window.navigator.language;)) instead of particular language ("english").

**Comment by icambron** [comment]
I don't know what you mean by "updating". Can you create a jsfiddle and show me?

**Comment by icambron** [comment]
Going to close this b/c lack of response. If you can create a reproducible example of the problem you're seeing, post it here @-mentioning me and I'll reopen it.
