### ISSUE TITLE
How often is the "isDST()" function tweaked/reworked?

### ISSUE THREAD

**Issue by danbartoninc** [moment/moment#3311]
We are currently only using moment.js with other plugins, just to try and accurately guess as much as possible if the timezone in the US is in DST or just Standard Time.

Based on those in the know, even though best practice are always we should keep the library up to date at all times, if that is the only function we are utilizing, how often is that function being tweaked?

Should we be updating the library with every release or since DST change only occurs here in the US twice a year, would we be fine updating the library once or twice a year?

Thanks guys!

**Comment by icambron** [comment]
`isDST()` not based on data that knows when DSTs are; it's based on noting that if it's currently DST, there exists a winter month in which the DST is off and so the UTC offset is lower then than it is now. We check both January and June to cover both the norther and southern hemispheres:

```js
    function isDaylightSavingTime () {
        return (
            this.utcOffset() > this.clone().month(0).utcOffset() ||
            this.utcOffset() > this.clone().month(5).utcOffset()
        );
    }
```

That makes some assumptions, like that DST could not plausibly be in effect in the same timezone for both January and June. I can imagine some outlandish scenarios where these assumptions could break (e.g. getting rid of DST and changing the zone's base offset at the same time), but for almost everyone everywhere in the world, they should be robust. For the US in particular, it's hard to imagine the DST date shifting far enough to break that code. 

So for sure, update Moment whenever you can't, but you needn't do it on account of the DST details.
