### ISSUE TITLE
Documentation locale as array

### ISSUE THREAD

**Issue by denisname** [moment/moment#3313]
The documentation point out that [`moment.locale`](http://momentjs.com/docs/#/i18n/changing-locale/) may receive an array. However, other functions taking a local value are not documented as being able to receive an array. Although it works well: [jsfiddle](https://jsfiddle.net/t22krgLw/).

Therefore, I wonder if you are not missing the following definitions in your documentation and typescript declaration.

For [changing locales locally](http://momentjs.com/docs/#/i18n/instance-locale/), add
````
moment().locale(String[]);
````

For [string+format](http://momentjs.com/docs/#/parsing/string-format/), add
````
moment(String, String, String[], [Boolean]);
moment(String, String[], String[], [Boolean]);
````

For [utc](http://momentjs.com/docs/#/parsing/utc/), add
````
moment.utc(String, String, String[]);
````

**Comment by icambron** [comment]
Yes, that makes sense. Want to write a pull request to the [https://github.com/moment/momentjs.com](documentation repository)?

**Comment by maggiepint** [comment]
I'm going to port this issue to the docs repo. I'll remember it there.
