### ISSUE TITLE
Moment.min not working correctly with requirejs

### ISSUE THREAD

**Issue by JJBocanegra** [moment/moment#3314]
I've found a problem with _moment.min.js_ where it didn't work like the unminified version should do.

Using **moment.min.js** I can't use the loaded locale:

```
requirejs.config({
  packages: [{
    name: 'moment',
    location: '/node_modules/moment',
    main: 'min/moment.min',
  }],
  deps: [
    'moment/locale/es',
    'app',
  ],
});

......

// == App.js ==

moment.locale('es');
console.log(moment.locales()); // Shows ['en']
console.log(moment.locale()); // Shows en
```

But using the unminified version I can use the loaded locale without any problem:

```
requirejs.config({
  packages: [{
    name: 'moment',
    location: '/node_modules/moment',
    main: 'moment',
  }],
  deps: [
    'moment/locale/es',
    'app',
  ],
});

......

// == App.js ==

moment.locale('es');
console.log(moment.locales()); // Shows ['en', 'es']
console.log(moment.locale()); // Shows es
```

In both cases the locale file loads after momentjs, so is not a loading problem.

PD: I tried to do it in **jsfiddle** but I don't know how to replicate the same example without using _node_modules_.

**Comment by mj1856** [comment]
Does it work any better if you load the locale in the manner described [here in the docs](http://momentjs.com/docs/#/use-it/require-js/)  (in the "core with single locale")?

I'm not a requirejs expert, but I don't think you need it in `deps` based on what I've read.

**Comment by JJBocanegra** [comment]
@mj1856 I tried that way too and nothing, it's really strange.

**Comment by farhd** [comment]
@JJBocanegra , here is the link to a runkit with the test (https://runkit.com/farhd/589f7e5548544f001416baae). I get the following:
`Array (2 items)
0: "en"
1: "es"`
`"es"`

**Comment by icambron** [comment]
I'm closing this out due to age.
