### ISSUE TITLE
local to UTC to local date time conversion giving wrong time

### ISSUE THREAD

**Issue by ovarunendra** [moment/moment#3318]
Hi,
I am trying to convert the local time to UTC for saving in DB and again to getting the same UTC saved string and converting it to local time but its giving the wrong time.

Please find the jsfiddle for same
[https://jsfiddle.net/t50kqmLs/](https://jsfiddle.net/t50kqmLs/)

Code:
```
var localDate = "07/22/2016 03:00 pm";
var utcFormat = moment(localDate).utc().format('YYYY-MM-DD HH:MM:SS');
var localFormat = moment.utc(utcFormat, 'YYYY-MM-DD HH:MM:SS').local().format('MM/DD/YYYY hh:mm a');
console.log('LocalDate: ', localDate);
console.log('utcFormat: ', utcFormat);
console.log('localFormat: ', localFormat);

var localDate2 = "07/22/2016 03:30 pm";
var utcFormat2 = moment(localDate2).utc().format('YYYY-MM-DD HH:MM:SS');
var localFormat2 = moment.utc(utcFormat2, 'YYYY-MM-DD HH:MM:SS').local().format('MM/DD/YYYY hh:mm a');
console.log('LocalDate: ', localDate2);
console.log('utcFormat: ', utcFormat2);
console.log('localFormat: ', localFormat2);
```

Thanks.

**Comment by mj1856** [comment]
Format tokens are case sensitive.  You have months (`MM`) and minutes (`mm`) being swapped, and also you have fractional seconds (`SS`) where you probably meant whole seconds (`ss`).

**Comment by mj1856** [comment]
In other words.  Instead of `YYYY-MM-DD HH:MM:SS` you should have `YYYY-MM-DD HH:mm:ss`.

**Comment by ovarunendra** [comment]
Thanks @mj1856 it saved my day.
