### ISSUE TITLE
Local time doesn't work

### ISSUE THREAD

**Issue by idansh** [moment/moment#3321]
.NET webservice returns the following date: "/Date(1469271646000)/"

I save the date as UTC date in MySQL database. 

When I pass the date to moment.utc(value.Planet.when) or moment(value.Planet.when) I get the same time on both. It shows me the time 14:00 when it has to be 17:00 to where I live.

Why the conversion doesn't work. The time in the database appear at the correct UTC time, but whatever I do in moment on the client side doesn't reflect the +3GMT time different and show 17:00 as the correct hour?

I use the latest version of moment.

**Comment by icambron** [comment]
Can you show me exactly what string you are passing into Moment?

**Comment by icambron** [comment]
I'm going to close this for lack of response. If you're able to show me exactly what you pass into Moment, reply here with it and @-mention me so I can reopen the ticket.
