### ISSUE TITLE
Error: Log data

### ISSUE THREAD

**Issue by RS-de-Jong** [moment/moment#3325]
Error: i is null t.getMonthData 
![schermafbeelding 2016-07-25 om 18 00 34](https://cloud.githubusercontent.com/assets/5844859/17107991/e0efecb2-5291-11e6-983c-320c99119701.jpg)

**Comment by icambron** [comment]
You'll need to provide us more details. How can we reproduce this error? Can you create a jsFiddle?

**Comment by mj1856** [comment]
Given that there's no actionable information here, I'm closing this issue.  I'll re-open If you can give us more to go on.  Thanks.
