### ISSUE TITLE
No way to get following day of the week

### ISSUE THREAD

**Issue by OmeGak** [moment/moment#3328]
I'm trying to get the next occurrence of a day of the week. With this I mean that if today is **Wednesday** and I pass Thursday I should get this week's Thursday, but if I pass Monday I should get next week's Monday.

I understand that `day()` modifies the date within the current week, so I have no straightforward way to always get the closest next date with the specified day of the week. 

Assuming this:
```
moment()._d
Wed Jul 27 2016 12:57:43 GMT+0200 (CEST)
```

`moment().day(1)` will give me a Monday that is in the past.
```
moment().day(1)._d
Mon Jul 25 2016 12:59:55 GMT+0200 (CEST)
``` 

`moment().day(7 + 1)` will give me the correct Monday.
```
moment().day(7 + 1)._d
Mon Aug 01 2016 13:00:32 GMT+0200 (CEST)
```

But always passing `7 +` is not the solution either. `moment().day(7 + 4)` will give me not the day after today, but the Thursday of the next week.
```
moment().day(7 + 4)._d
Thu Aug 04 2016 13:01:17 GMT+0200 (CEST)
```

I can of course do something like this but I was expecting a less obscure way.
```js
    function nextDay(day) {
        var now = moment();
        var day = day < now.day ? 7 + day : day
        return now.day(day);
    }
```

Am I missing something?

**Comment by icambron** [comment]
I don't think that's obscure; that logic looks just like your description of what you want to do. Though you could write a bit more simply:

```js
function nextDay(m, day){
  return m.day(day < m.day() ? 7 + day : day);
}

//call like
nextDay(moment(), 4);
```

If you want to monkey patch Moment:

```js
moment.fn.nextDay = function(day){
  return this.day(day < this.day() ? 7 + day : day);
}

//call like
moment().nextDay(4);
```

I think that's a straightforward enough reflection of your intent to be the recommended way to do that.
