### ISSUE TITLE
Format date for SR, BS and HR

### ISSUE THREAD

**Issue by topguss** [moment/moment#3329]
Long data format:
Replace L : 'DD. MM. YYYY' with L : 'DD.MM.YYYY'.
Spaces between dot and next digit are unnecessary - we never write it.

**Comment by icambron** [comment]
CLDR agrees on all counts.

**Comment by mj1856** [comment]
A PR would be welcome.

**Comment by marwahaha** [comment]
Is this issue closed?

**Comment by icambron** [comment]
@marwahaha no

**Comment by gautamkrishnar** [comment]
I think this issue can be closed since its PR merged in https://github.com/moment/moment/pull/3356#issuecomment-244529289

**Comment by icambron** [comment]
OK thanks
