### ISSUE TITLE
Invalid Date on Firefox

### ISSUE THREAD

**Issue by lelis718** [moment/moment#3330]
moment is giving "Invalid Date" in firefox when using a string like "2016-07-26T17:00:00.000z" .

When converted to uppercase "2016-07-26T17:00:00.000Z" the date is recognized correctly.

Could this be considered a valid utc value? 
(If not the bug is in .Net framework that generates json date as this  :S )

Regards Andre

![error](https://cloud.githubusercontent.com/assets/477538/17180041/82c6e670-53f1-11e6-9bb7-16358a26e78a.png)

**Comment by mj1856** [comment]
Works for me...
![image](https://cloud.githubusercontent.com/assets/1396388/17180504/908132ea-53d1-11e6-9e9e-d8e7830ee56e.png)

What version of moment are you running?

**Comment by lelis718** [comment]
The version is 

2.10.6

I have temporary fixed using a touppercase in variable before send it to moment in my code

but i will change the moment version soon

Thanks

**Comment by maggiepint** [comment]
I'm going to close this. If you can replicate the issue in 2.14, feel free to re-open.
