### ISSUE TITLE
Duration#get('hours') is inconsistent w/ Duration#as('hours')

### ISSUE THREAD

**Issue by Inkata** [moment/moment#3334]
moment.version
    "2.14.1"

    moment.duration('55:43','hours').as('hours')
    55.71666666666667

    moment.duration('55:43','hours').as('days')
    2.321527777777778

    moment.duration('55:43','hours').get('days')
    2

    moment.duration('55:43','hours').get('hours')
    7 <--this should be 55

tested in (linux / ubuntu 14.04):
 * Chrome 52.0.2743.82 (64-bit) 
 * Firefox 47

BTW thanks for this awesome library! 🙏

**Comment by icambron** [comment]
The difference isn't supposed to be just the rounding. `get` does something very different; it's really just the arg-driven version of `Duration#days`, `Duration#hours`, etc. Check it out:

```js
var dur = moment.duration('55:43', 'hours');
dur.get('days'); //=> 2
dur.get('hours'); //=> 7
dur.get('minutes') //=> 43
dur.get('seconds')  //=> 0
```

i.e. 55:43 is 2 days, 7 hours, and 43 minutes. So `get` is closer to "Once you've 'reduced' this duration, what is the value for each unit?", whereas `as` asks for the duration as expressed in that unit.

**Comment by Inkata** [comment]
awesome, thanks for the clarification!
