### ISSUE TITLE
Beef up formatting tests to communicate ```moment(undefined, <your favorite format>).toISOString()``` won't work

### ISSUE THREAD

**Issue by jfarid27** [moment/moment#3338]
Slightly related to #3180. On one hand...

```code
var k = moment(undefined);
k.toISOString()  /// This returns ok.
```

On the other hand...

```code
var k = moment(undefined, "YYYY-MM-DD");
k.toISOString()  /// This returns "invalid date".
```

It's unintuitive that ```moment(undefined)``` behaves as ```moment()```, but ```moment(undefined, <your favorite format>)``` is really trying to format undefined and is failing. To help with this, let's add a test to make sure people understand this behavior.

**Comment by maggiepint** [comment]
We'll take this, sure.

**Comment by mj1856** [comment]
Tracking in PR #3339
