### ISSUE TITLE
Arbitrary time offset (client-server time synchronization)

### ISSUE THREAD

**Issue by Machiaweliczny** [moment/moment#3346]
Im facing the issue of desynchronized client machine time with server machine time.
I can calculate time delta between them but (un?)fortunately I'm using `moment` everywhere to get time on client.

I'm wondering if I've to replace every call to `moment` to custom function or if there's some non-invasive way to adjust receiving of current time from `moment` by my time delta?

**Comment by Machiaweliczny** [comment]
Ok I found it in the docs :) - http://momentjs.com/docs/#/customization/now/

**Comment by mj1856** [comment]
The primary purpose for that was to help with unit testing, but sure - I can see it being useful to apply a client/server delta.  Calculating that delta is tricky though - as true NTP is not possible in JavaScript.  So, be careful. :)

**Comment by Machiaweliczny** [comment]
I will get fine with just adjusting for half of roundtrip time.
Maybe excluding too laggy request also.
