### ISSUE TITLE
toISOString() creates two different times

### ISSUE THREAD

**Issue by blogcraft** [moment/moment#3348]
When I have 2 dates: '2015-01-06T00:00:00' and '2014-06-06T00:00:00'

```
moment('2015-01-06T00:00:00').toISOString(): "2015-01-06T03:00:00.000Z"
moment('2014-06-06T00:00:00').toISOString(): "2014-06-06T04:00:00.000Z"
```

What I don't understand is, why moment uses different time for each date? (T03 vs T04) This is the output of the same console in the same computer in the same regional configuration.

**Comment by skfd** [comment]
It could be Day light saving. It's usually in March. For me it's between these two dates:

```
moment('2014-03-30T00:00:00').toISOString()
"2014-03-29T22:00:00.000Z"

moment('2014-03-31T00:00:00').toISOString()
"2014-03-30T21:00:00.000Z"
```

**Comment by maggiepint** [comment]
This is almost certainly DST since you're looking at the difference between January and June. Closing, but let me know if you want it reopened.

**Comment by blogcraft** [comment]
Si there a way to disable DST? In my country the day when we change saving time varies almost with no warning so is very unreliable.

**Comment by skfd** [comment]
[Moment Timezone](http://momentjs.com/timezone/) has an up to date datebase of DST rules. I've not tested it for Chile, but I'm pretty sure it will do appropriate calculations.

**Comment by blogcraft** [comment]
Either way, I need to disable it. I get a date from the server and then moment adds an hour to it and the date I get is no longer usefull.

**Comment by skfd** [comment]
For DST-less logic I'd switch to using [UTC dates](http://momentjs.com/docs/#/parsing/utc/). Send from server something like `2014-03-31T00:00:00Z` and process with `moment.utc()`.

**Comment by maggiepint** [comment]
@blogcraft you have been given good advice so far, but I think we need to better understand your use case. I'm guessing that you are dealing with what we would call a 'local time' or a time with no relation to the global timeline. If so, then using moment.utc to parse and display is probably your best bet. I would suggest that you check out a few resources to get your head around what is going on.

This is me doing an introductory talk on date and time in programming:
https://www.youtube.com/watch?v=ieIzNP6gKqU

This is a blog post about moment's factory functions and how they work:
https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/

This is a pluralsight course on date and time in programming that is probably the most comprehensive resource on the topic on the web:
https://www.pluralsight.com/courses/date-time-fundamentals
