### ISSUE TITLE
Allow non-strict parsing to specify minimally allowed precision

### ISSUE THREAD

**Issue by mj1856** [moment/moment#3349]
Issue #3168 demonstrates how specifying multiple input formats while in strict mode can get out of hand and lead to performance problems.

It would be good if there was some way to stay in non-strict mode, while retaining control of the required precision of input.

For example:

```
moment('2016 foo', 'YYYY-MM-DD HH:mm:ss').isValid() // true, though probably undesired
moment('2016-08-04', 'YYYY-MM-DD HH:mm:ss').isValid() // true, and probably ok
```

Not sure what the API would look like.  Perhaps pass a string of required tokens like `'YMD'` as another parameter?  Or perhaps just indicate the required portion inline with some chosen characters, as in:

```
moment('2016-08-04', '{YYYY-MM-DD} HH:mm:ss')
```

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
