### ISSUE TITLE
Converting "Jul 31 2016" Date object gives "July 0"

### ISSUE THREAD

**Issue by kurisubrooks** [moment/moment#3354]
Date Object: `Sun Jul 31 2016 16:43:45 GMT+1000 (AEST)`
Formatted with `moment(stats.mtime).format("MMM d, YYYY")`
Outputs `Jul 0, 2016`

Version `2.14.1`
Node `6.3.0`

**Comment by skfd** [comment]
`d` is a day of the week. It's a zero-based index. `0` is Sunday.

**Comment by kurisubrooks** [comment]
Ah, you're right. Sorry, I just assumed... Didn't check the docs.
Thanks so much @skfd!
