### ISSUE TITLE
Allow Decimals to bubble down in setters.

### ISSUE THREAD

**Issue by xMrWhite** [moment/moment#3355]
Example of desirable behaviour:
`moment().hour(3.5).minute() === 30`
`moment().set('second', 2.5).millisecond == 500`
Similar to the duration setter:
`moment.duration(2.5, 'hours').minutes() === 30`

**Comment by maggiepint** [comment]
I"m not sure if I like this, because it only works for certain unit types. Because days and above cannot be subdivided, this creates an unintuitive api. @mj1856 @icambron @butterflyhug ?

**Comment by butterflyhug** [comment]
Decimal setter support implies to me that setting a unit will always reset all smaller units.  E.g. `moment().hour(3.5).seconds()` needs to return `0`.  It would be ludicrous for `moment().hour(3.5)` to keep the existing the seconds value, but then have `moment.hour(3.4999)` set it to a new value.  Hello, floating point.

For consistency, we'd also need to reset all smaller units even when setting to an integer -- so `moment().hour(3).minutes()` would also be 0.  Anything else is too hard to reason about, especially if that number is a variable that's sometimes an integer and sometimes not.

Resetting all smaller units when setting a larger unit breaks existing code patterns such as `moment().minute(30).hour(3)`.  So, if we do this then I think it has to be a major-version change.

Personally I think the feature only makes intuitive sense for durations anyway -- what does it even mean to set the hour component of a date/time type to 3.5?  I mean, it's clear what's intended from these examples, but I don't find that this behavior maps easily to a familiar way of talking about timestamps or times on a clock or whatever.  This idea does make lots of intuitive sense for durations, but I'm not sure it's a good idea to have moment setters work fundamentally differently from duration setters.

So I personally don't think the feature is worth breaking compatibility with existing behavior, given the existing API.  If we get ever get rid of setters on `moment` instances while keeping `duration#as`, then I'd definitely favor implementing this on durations -- but that doesn't feel like a near-term change.

**Comment by xMrWhite** [comment]
A separate setter similar to the `asHours` getter would retain compatibility, resetting the seconds and such is actually desirable in my use case, though maybe there is a better way.

I want to set the time of a moment from an hour stored as a decimal. 
A current solution is: 
`moment().set({'hour': Math.floor(myHour), 'minute': myHour % 1 * 60, 'second': 0, 'millisecond': 0});` but I feel like wanting to at lease clear the smaller units is a useful thing.

Maybe a good alternative would be `moment.setTime('HH:mm:ss.sss')` that could take an ISO time string. @butterflyhug

**Comment by butterflyhug** [comment]
If you're happy supplying input as a partial ISO string and you're always trying to construct a specific time of day on the current date, then `moment(stringToParse, 'HH:mm')` should already do what you want.

On the original question -- if this would be new API instead of modifying existing setter behavior then I withdraw my objection.  I've never personally found setters on moments to be very useful (in contrast to setters on durations, which I've found very useful) so I don't have a good intuition about whether this is a common use case or not.  I'd still worry slightly about whether we can clearly explain two different types of setter to new users, though.

**Comment by xMrWhite** [comment]
My use case is some moment between 9am and 5pm today, now that I know I can create that with `moment(str, 'HH:mm')` I'm all settled. I still think set Time would be useful to some, especially if you want to set the time on an existing moment, I have what I need.

**Comment by xMrWhite** [comment]
I think it's safe to say that decimals in the current API would be confusing so I'm closing this.
