### ISSUE TITLE
moment().startOf('day') returns yesterday

### ISSUE THREAD

**Issue by guillaumewuip** [moment/moment#3357]
Hi, I'm trying to use `moment().startOf('day')` but it gives me the date of yesterday : 

```js
const moment = require('moment-timezone');

moment.tz.setDefault('Europe/Paris');

const
    TODAY           = moment().startOf('day'),
    TOMORROW = moment().add(1, 'day').startOf('day');

console.log('now', moment().format()); // now 2016-08-07T02:01:00+02:00
console.log('today', TODAY.format()); // today 2016-08-06T00:00:00+02:00 <-- why ?
console.log('tomorrow', TOMORROW.format()); // tomorrow 2016-08-07T00:00:00+02:00 <-- why ?
``` 

My server is in UTC and runs this code at 00:01 (UTC) / 02:01 (Europe/Paris) every day.
If I run this locally by hand now at 07:28 (Europle/Paris), I see no error. What could be the reason ?

Thanks 🙌

**Comment by mj1856** [comment]
I believe this is the same as moment/moment-timezone#208, or related.

**Comment by guillaumewuip** [comment]
Ok, maybe we can close this if it's the same cause.

**Comment by icambron** [comment]
I'm going to close this because it's a bug in moment-timezone and not moment core and seems to be covered there.
