### ISSUE TITLE
Feb 29 0000 is invalid

### ISSUE THREAD

**Issue by metasansana** [moment/moment#3358]
Hello,

Consider this:

``` javascript

    moment({year:0, month:1, date:29}).isValid(); //false
    //vs    
    moment({year:0, month:1, date:28}).add(1, 'd').isValid(); //true
```

:/

Is this expected behavior? Seems inconsistent.

**Comment by mj1856** [comment]
Year 0 on the Proleptic Gregorian calendar that we use is indeed a leap year, so Feb 29th should be allowed.

    moment([0]).isLeapYear() // true
    moment('0000-02-29').isValid() // false

**Comment by mj1856** [comment]
I believe this is because internally it's hitting the `Date` constructor's mapping of year 00-99 to 1900-1999 before compensating.  1900 is *not* a leap year, so the initial step fails on Feb 29th.

**Comment by icambron** [comment]
@mj1856 Almost. It's using Moment's ISO parser, which correctly interprets the date as 0, But to check whether the date is valid, it compares 29 to `getDaysInMonth`, which looks like this:

```js
function daysInMonth(year, month) {
    return new Date(Date.UTC(year, month + 1, 0)).getUTCDate();
}
```

*That* is interpreting 0 as 1900 and returning 28, which causes Moment to decide the day of the month overflowed.

**Comment by mj1856** [comment]
We can do that more efficiently without the `Date` object.  We already have `isLeapYear`.  Just need an array of days in the month.  Probably is more efficient anyway, and can reuse it elsewhere.

**Comment by mj1856** [comment]
Actually, don't even need an array
http://www.dispersiondesign.com/articles/time/number_of_days_in_a_month

**Comment by ichernev** [comment]
@mj1856 that is obfuscated. I don't think we care that much about bytes.

**Comment by mj1856** [comment]
Either algorithm should work.  I'll see if there's any perf benefit.  But an intial try of either gave some interesting errors.  It would appear that there are some code paths that pass months < 0 or > 11 to  `daysInMonth` function.  Our current algorithm would overflow, but I'm not entirely certain why we're doing that in the first place.  Will dig in deeper.

**Comment by mj1856** [comment]
One interesting part is that sometimes one or both parameters to `daysInMonth` are `NaN`.  I think this happens with something like `moment([2010, null, null])` which exists in the tests.  When the `checkOverflow` function is called, it assumes that if `_a` is present that it is also fully populated - which it might not be.

**Comment by mj1856** [comment]
To get all tests to pass without using a `Date` object here, I have to currently do:

```javascript
export function daysInMonth(year, month) {

    // account for NaN
    if (isNaN(year) || isNaN(month)) {
      return NaN;
    }

     // account for underflow
    while (month < 0) {
      year--;
      month += 12;
    }

    // account for overflow
    while (month > 11) {
      year++;
      month -= 12;
    }

    // then I can do the real calculation
    return month === 1 ? (isLeapYear(year) ? 29 : 28) : (31 - month % 7 % 2);
}
```

Using the array of days in months approach is no different.

I'm not going to check that in.  Instead, I'm going to see if I can unwind what's passing these conditions through to begin with.

**Comment by marwahaha** [comment]
Perhaps I'm playing code golf, but here's a solution that's not too long.
