### ISSUE TITLE
Formatting: format('x') and format('X') return 'x' / 'X'

### ISSUE THREAD

**Issue by ollie314** [moment/moment#3360]
Hi,
First of all, thanks for your amazing effort ! That's a pretty convenient lib :D !!!!!

I'm actually issuing a small bug (I suppose that, actually not sure). When I'm trying to get the unix timestamp from a moment object, I just get back the string format. For instance, if I'm passing ```'x'``` as ```format``` argument, I'm getting back the ```'x'```.

## Configuration : ##
* OS: Linux debian jessie
* nodejs: v6.3.1
* momentjs: 1.1.14

## installation command ##
To install moment, I'm using the following command:
```npm install --save momentjs```

## Issue description ##
The format output is an 'x' for ```moment().format('x')``` and an 'X' for ```moment().format('X')```.

## How to reproduce ##

1. install momentjs with the command presented above
2. launch a terminal then enter in a node shell
3. enter the following code
``` javascript
var now = moment(),
ts = now.format('x');
console.log(ts);
// it will output 'x'
```

**Comment by mj1856** [comment]
`moment` is the official npm package name.  Not `momentjs`.  The current version is 2.14.1.  There has never been a 1.1.14 release.

Please use the official release, and I'm sure the problem will go away.  If not, let me know and I'll reopen, but I tested your code and it is fine.

**Comment by mj1856** [comment]
FYI - That other package isn't even our code.  I've asked npm if they can take it down to prevent confusion.

**Comment by ollie314** [comment]
Ok,
Thanks for your help !

**Comment by ianfoulds** [comment]
I've experienced a similar problem with moment 2.4.0 which I needed because of other restrictions with DataTables. Using format('x') doesn't work in 2.0.0 through at least 2.4.0 where only the 'X' format method exists.

If you are using the Datatbles.net datetime-sorting pluging you will need to change format('x') to format('X') to make it work. See https://datatables.net/plug-ins/sorting/datetime-moment
