### ISSUE TITLE
moment.duration.days returns radically different result than asDays

### ISSUE THREAD

**Issue by gamecubate** [moment/moment#3364]
There's something I'm not getting. Either that or it's a bug. Tested with latest (2.14.1) version in Chrome 51.0.2704.103 on iOS 10.11.5.
```
var now = moment(),
      later = moment("20161023", "YYYYMMDD"),
      diff_ms = later.diff(now),
      dur = moment.duration(diff_ms, "ms");

console.log(dur.days());    // 11
console.log(dur.asDays());  // 72.06...
```

**Comment by mj1856** [comment]
`.asDays()` returns the total duration, in units of whole and fractional days.

`.days()` returns the number of days that are remaining after accounting for `.years()` and `.months()`.
