### ISSUE TITLE
Incorrect week addition calculations over year boundary

### ISSUE THREAD

**Issue by bluematt** [moment/moment#3367]
There seems to be some discrepancy as to how week addition (e.g. `moment().add(1, 'week')`) works when it occurs over a year boundary.

On some occasions it overflows correctly to the next year, and on others it revert back to the same year as the original date.

Examples in this [jsFiddle](http://jsfiddle.net/tnqeba5q/)

Note: some years have 53 weeks. This is expected.

**Comment by ichernev** [comment]
@bluematt use `GGGG` or `gggg` tokens for year instead of `y`
