### ISSUE TITLE
Incorrect week setters with non english locales

### ISSUE THREAD

**Issue by ntkoopman** [moment/moment#3380]
Something strange is happening with non english locales when setting weeks:

```js
moment({year: 2023}).week(1).format() // "2023-01-01T00:00:00+01:00"
moment.locale('nl') // which locale doesn't seem to matter
moment({year: 2023}).week(1).format() // "2022-01-09T00:00:00+01:00"
```

Obviously I expect both of them to give the same result.

**Comment by icambron** [comment]
From the [docs](http://momentjs.com/docs/#/get-set/week/):

> The week of the year varies depending on which day is the first day of the week (Sunday, Monday, etc), and which week is the first week of the year.

> For example, in the United States, Sunday is the first day of the week. The week with January 1st in it is the first week of the year.

> In France, Monday is the first day of the week, and the week with January 4th is the first week of the year.

If you want to them to be all the same, use `isoWeek`.

**Comment by ntkoopman** [comment]
Ok, using isoWeek the result is the same, but the year is still incorrect.

**Comment by icambron** [comment]
What do you mean that the year is incorrect?

**Comment by ntkoopman** [comment]
Woops, I'm sorry. I should not be making sleep deprived bug reports.
