### ISSUE TITLE
With no argument, or an empty list argument, both .min() and .max() return “now”

### ISSUE THREAD

**Issue by coox** [moment/moment#3386]
I have found the following behaviour of both `.min()` and `.max()` to be surprising, and potentially unintended.

All of the calls below return a valid “now” Moment object, just as if simply invoking `moment()`:
- `moment.min()` ⇔ `moment()`
- `moment.max()` ⇔ `moment()`
- `moment.min([])` ⇔ `moment()`
- `moment.max([])` ⇔ `moment()`

I wouldn't expect that looking for the min/max value of an empty set would result in a brand new and valid object being returned.

For this edge case, wouldn't it be better to return a value that is easier to process, such as `undefined`? Or maybe, if these functions are expected to stay close to their `Math` counterpart, an `Infinity`?

For reference:
- `Math.min()` → `-Infinity`, `Math.min([])` → `0`
- `Math.max()` → `Infinity`, `Math.max([])` → `0`
- Underscore: `min()`, `min([])` → `-Infinity`, `max()`, `max([])` → `Infinity`
- Lodash: `_.min()`, `_.max()`, `_.min([])`, `_.max([])` → `undefined`

Apologies if this has been discussed and decided before, I couldn't find any evidence of this in the issues that I have searched (and this particular edge case seems [untested](https://github.com/moment/moment/blob/develop/src/test/moment/min_max.js)).

**Comment by mj1856** [comment]
We'll take this into consideration for the future, but I'm not sure that it really matters.  Is there a valid use case for calling the functions in the way you described?

I'd be more concerned with breaking changes that would be created from the behavior differences than just in being correct.

**Comment by coox** [comment]
Thanks Matt.

I share your concerns regarding breaking changes that might be created from behavior differences. I also agree than invoking `moment.min()` or `moment.max()` without any argument is a little silly :)

However, I believe that there is at lease one use case (precisely the one that has bitten me) that I'd consider valid for calling the functions with an empty array and not expecting a `moment` or date-like as a result. Consider this:

```js
function getListOfDates() {
  // Return an array of Date objects
}

function filterListOfDates() {
  // Do arbitrary stuff with an array of dates,
  // potentially returning an empty array
}

// Expect a single date out of an initial array of Date objects
var maxDate = moment.max(filterListOfDates(getListOfDates()));
```

In the example above, `maxDate` will unconditionally be populated with a `moment` object, which I find unexpected in the case where the filtered list comes back empty.

I hope this will suffice for consideration in modifying the behaviour in a future version, semantic versioning permitting.

**Comment by ichernev** [comment]
@coox If you propose a PR and we merge it, it will be in a next major release. I agree it's a bit odd. We can return an invalid moment. But that can be in the list, so it's not clear what caused it. If it's another value like null it will need more checks, so I lean for an invalid one.

**Comment by JemarJones** [comment]
This is pretty unusual behaviour. I think the logical expectation here would be that the return value is simply `undefined` in this case.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
