### ISSUE TITLE
Month names not correct in fa locale

### ISSUE THREAD

**Issue by mehrdaad** [moment/moment#3390]
In https://github.com/moment/moment/blob/develop/locale/fa.js month names are being cited as
`` months : 'ژانویه_فوریه_مارس_آوریل_مه_ژوئن_ژوئیه_اوت_سپتامبر_اکتبر_نوامبر_دسامبر'.split('_'),``
although they are Persian form of Gregorian month names differ in Jalali calendar. 
For example January is equal to فرودین instead of ژانویه.

I can correct month names and send you a pr. Or we can discuss here further.
Thanks.

**Comment by maggiepint** [comment]
Are you saying that this uses Persian Gregorian month names? If so I would say that is correct. Moment only supports the Gregorian calendar. If you want Jalali calendar support, there is a plugin for it: http://momentjs.com/docs/#/plugins/jalaali/

**Comment by mehrdaad** [comment]
Yes didn't know existence of this plugin tnx.
