### ISSUE TITLE
Meteor with moment and heroku won't build

### ISSUE THREAD

**Issue by clemyoh** [moment/moment#3391]
Hi there, 

When I use this package with heroku and meteor, the build always fails. When I remove the package, everything works. I'm not sure why this is happening.

Has anyone else experienced this issue?

Cheers,
Clement

**Comment by icambron** [comment]
Can you provide more details, like error messages, commands run, etc?

**Comment by clemyoh** [comment]
I just tried using the package again and it all worked just fine. I'm not sure what's changed because it has been failing for the past week. Since it worked, I can't recreate the error message, but it used to say something along the lines of npm-gyp-rebuild error.
