### ISSUE TITLE
moment doesn't compile with closure compiler

### ISSUE THREAD

**Issue by lookfirst** [moment/moment#34]
Thanks for a nice library.

Using: http://code.google.com/closure/compiler/

Around line 403 is this:

```
    native : function () {
        return this._d;
    },
```

http://en.wikibooks.org/wiki/JavaScript/Reserved_Words

native is a reserved word in ECMAScript v3.

Commenting out the above code makes things compile.

**Comment by polkovnikov-ph** [comment]
Just add to the docs that the user needs to pass `--language_in=ECMASCRIPT5` to Closure Compiler, so that it doesn't complain on old ES3 features.
