### ISSUE TITLE
In Portuguese first day of the week should be Sunday, not Monday

### ISSUE THREAD

**Issue by vdewinter** [moment/moment#3400]
In moment-with-locales.min.js for locale pt-br, the first day of the week is specified as Monday. It should be Sunday. This dow override is not present in the unminified moment-with-locales.js.
``
kg.defineLocale("pt-br", ... {dow:1,// Monday is the first day of the week.
doy:4}})
``

**Comment by icambron** [comment]
CLDR agrees:

```
          <firstDay day="sun"  territories="
			AG AR AS AU
			BR BS BT BW BZ
			CA CN CO
			DM DO
			ET
			GT GU
			HK HN
			ID IE IL IN
			JM JP
			KE KH KR
			LA
			MH MM MO MT MX MZ
			NI NP NZ
			PA PE PH PK PR PY
			SA SG SV
			TH TN TT TW
			UM US
			VE VI
			WS
			YE
			ZA ZW"
          />
```

So I think we'd take a pull request for this.

**Comment by Salasar** [comment]
I have written local test for it and the first day of the week in 'pt-br' locale is Domingo (Sunday).
So,  by default, it takes the first day of the week from configuration string, doesn't it?

**Comment by vdewinter** [comment]
Yep, user error. I will close this issue.
