### ISSUE TITLE
Fix typings for startOf, endOf to support 'isoweek'

### ISSUE THREAD

**Issue by annael** [moment/moment#3402]
**Issue:**

Since 2.2.0, moment#startOf('isoWeek') support has been added. However, this no longer works in 2.14.1, since type has been changed to `startOf(unitOfTime: UnitOfTime): Moment` and 'isoweek' is not listed as a supported value for UnitOfTime.

Breaking change:
https://github.com/moment/moment/commit/171ce25542ffbbb6bb8f905093b4fae39e1c7b50

**Environment:**

_Moment 2.14.1, Nodejs 4.50, npm 3.10.6_

**Comment by jesussobrino** [comment]
Related with #3319 (PR included)

**Comment by marwahaha** [comment]
2.18.1 has `isoWeek` as an option for `UnitOfTime`.

https://github.com/moment/moment/blob/2.18.1/moment.d.ts#L293
