### ISSUE TITLE
Unix timestamps .fromNow()

### ISSUE THREAD

**Issue by theobouwman** [moment/moment#3403]
Hello,

I have a problem with parsing Unix timestamps from the Hacker News API.

When I do `moment(unix).fromNow()` where `unix` is `1472435880` is will return `47 years ago` with every value.

I'm probably doing something wrong, but can;t find the problem.

Thanks in advance.

Theo

**Comment by butterflyhug** [comment]
Moment parses integers as the number of milliseconds since epoch for consistency with the native Date object in Javascript.  Unix timestamps are the number of seconds since epoch.  Thus, your sample code should be `moment(unix * 1000).fromNow()`

**Comment by mj1856** [comment]
Alternatively, you can use the `unix` function:

```javascript
moment.unix(unix).fromNow()
```

**Comment by damianobarbati** [comment]
Both `moment(timestamp, 'X')` and `moment.unix(timestamp)` return the warning:
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
```

Is this intended? How to get rid of it?

**Comment by zouboyun** [comment]
try using

`moment(moment(unix).format('YYYYMMDDkkmmss'), 'YYYYMMDDkkmmss').fromNow()`

works for momentjs v 2.22.2

**Comment by tominou** [comment]
> moment(1551881459259 * 1000).fromNow();

`moment(1551881459259).fromNow();` should work fine

**Comment by sourcevault** [comment]
> moment(moment(1551881459259).format('YYYYMMDDkkmmss'), 'YYYYMMDDkkmmss').fromNow()

this works, other options doesn't
