### ISSUE TITLE
moment(unix_timestamp).format('YYYY-MM-DD') bug?

### ISSUE THREAD

**Issue by pingfengafei** [moment/moment#3405]
```js
   for (let i = 0; i <= 1000; i++) {
            let a = moment(1472551404).format('YYYY-MM-DD');
            console.log(i);
        }
```
in Chrome console : 
![moment_bug](https://cloud.githubusercontent.com/assets/6243826/18085204/bf56415c-6edc-11e6-8e18-a7e9f878289d.png)

when loop 392，it stop to continue. bug or I use in a wrong way？

**Comment by mj1856** [comment]
Sorry, I don't see how this is a bug in moment.  

A cursory search found this: http://stackoverflow.com/questions/35193296/chrome-48-devtools-was-disconnected-from-the-page-error
