### ISSUE TITLE
Strict parsing (`moment(dateString, format)`) is failing

### ISSUE THREAD

**Issue by titarenko** [moment/moment#3409]
```js
moment('moldovka2', 'YYYY-MM-DDTHH:mm:ss.SSSZ').toDate()
// Tue Jan 01    2 00:00:00 GMT+0200 (EET)
moment('moldovka2', 'YYYY-MM-DDTHH:mm:ss.SSSZ').isValid()
// true
```

How to reproduce:

1. Go to http://momentjs.com/ (Chrome Version 52.0.2743.116 (64-bit) in Ubuntu 16.04)
2. Open dev console
3. Enter code from example above

(Time and date when this was run is `Wed Aug 31 2016 14:48:48 GMT+0300 (EEST)`)

```
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
VM83:1 Wed Aug 31 2016 14:49:18 GMT+0300 (EEST)
VM83:2 8/31/2016, 2:49:18 PM
VM83:3 -180
VM83:4 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
VM83:5 2.14.1

**Comment by mj1856** [comment]
That is not strict parsing.  The default is non-strict.  You have to pass `true` as a third parameter to turn on strict parsing.

**Comment by titarenko** [comment]
Thank you for explanation, indeed, having read complete [section](http://momentjs.com/docs/#/parsing/) I found this. But could you please consider adding (changing) it to section menu (right sidebar), something like "String + Format + Strictness", or probably adding some warning (note) [here, at String+Format subsection](http://momentjs.com/docs/#/parsing/string-format/), since it's very easy to miss that during brief read.
