### ISSUE TITLE
utcOffset method missing in 2.14.1 

### ISSUE THREAD

**Issue by guillermosnipegb** [moment/moment#3411]
**Description of the Issue and Steps to Reproduce:**
```javascript
moment().utcOffset(-3);
moment.utcOffset(-3);

let date_from = moment(cart.deliveries[0].calendar.date_from);
date_from.format("DD [de] MMMM [de] YYYY [entre las] HH:mm").utcOffset(-3)
```
The examples above won´t work.

Error: utcOffset is not a function (Alerted in the server).

*Please include the values of all variables used.*

**Environment:**
Chrome Latest on OSX el capitan. Node V6.4.0. Moment.js 2.14.1 installed via npm.

**Comment by mj1856** [comment]
In line 1, you are simply not capturing the result anywhere.
In line 2, you are trying to change the offset without working from an *instance* of a moment object.  This is invalid.

In line 4, you're using `format`, which produces a string.  Then you try to call the `utcOffset` function on the string - which isn't going to be there.  You're also not capturing the result again.

You might simply want to change the offset *before* calling `format`.

var output = date_from.utcOffset(-3).format("DD [de] MMMM [de] YYYY [entre las] HH:mm");

**Comment by guillermosnipegb** [comment]
@mj1856 Thanks so much, it worked. I was already using moment js client side, and it worked as moment().utcOffset(-3) 

`        //setting moment.js offset
        moment().utcOffset(-3);`

I was trying to get the same result, but I was unable to do that. Followed your advice and it worked great. Thanks again.
