### ISSUE TITLE
Date Exclusion Array issue

### ISSUE THREAD

**Issue by jsh562** [moment/moment#3417]
**Description of the Issue and Steps to Reproduce:**

Whenever I use the date calculations in a loop, if, or another type of method, the array that I use for exclusions seems to always lose its values unless I initialize the array again within that same loop, if, or whatever method that is being used.
I have noticed that when I remove the moment() function from within the loop, if, or other method, then the inclusion array still remembers its values. When I add the moment() function back, it forgets the values unless I re-initialize them within that loop, if, or other method being used.

**WITHOUT moment():**
```

var date_calculation__working_day_array = [1,2,3,4,5];
var date_calculation__date_exclusion_array = ['2013-01-01',
			'2013-05-27',
			'2013-07-04',
			'2013-07-05',
			'2013-09-02'];
var date_calculation__date_inclusion_array = [];

$("#submit").on("click", function(){
   console.log(date_calculation__working_day_array );
   console.log(date_calculation__date_exclusion_array );
});
```
Output:
```
[1, 2, 3, 4, 5]
["2013-01-01", "2013-05-27", "2013-07-04", "2013-07-05", "2013-09-02"]
```
AS EXPECTED.

--------------------------------------------

**WITH moment():**
```

var date_calculation__working_day_array = [1,2,3,4,5];
var date_calculation__date_exclusion_array = ['2013-01-01',
			'2013-05-27',
			'2013-07-04',
			'2013-07-05',
			'2013-09-02'];
var date_calculation__date_inclusion_array = [];

$("#submit").on("click", function(){
   console.log(date_calculation__working_day_array );
   console.log(date_calculation__date_exclusion_array );

   var driven_to_date = moment(date).addWeekdaysFromSet({ 
				'workdays': current_tid__days_from_driver_date, //required, it is also possible to use 'days' alias  
				'weekdays': date_calculation__working_day_array, //optional  
				'exclusions': date_calculation__date_exclusion_array, //optional  
				'inclusions': date_calculation__date_inclusion_array //optional  
			}).format("YYYY-MM-DD");
});
```
Output:
```
[1, 2, 3, 4, 5]
undefined
```
exclusion array is undefined

**Environment:**
Chrome on Windows 7

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
```
Fri Sep 02 2016 15:54:29 GMT-0700 (Pacific Daylight Time)
9/2/2016, 3:54:29 PM
420
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
2.13.0
```

**Comment by icambron** [comment]
`addWeekdaysFromSet` comes from https://github.com/andruhon/moment-weekday-calc, not from Moment itself. Perhaps it's modifying the array unexpectedly? You should file a bug in that repository.
