### ISSUE TITLE
typescript issues

### ISSUE THREAD

**Issue by ichernev** [moment/moment#3419]
Given the large number of "fix this small typescript definition issue" I want to create a large "fix all typescript issues" and get over with it. People that have some typescript experience are encouraged to help with patches, comments, PRs.

The META Issue list:
- [x] moment global functions
- [x] moment prototype
- [x] duration prototype
- [x] locale prototype
- [ ] any other prototype?
# Issues from moment global functions
- [ ] moment.fn is marked as Moment --> isn't object more accurate (people will be mostly adding stuff here, not using existing functions IMHO)
- [ ] moment.min/max marked as taking Moment[] --> it takes all things that the constructor takes (in array)
- [ ] `moment.now()` -> returns time in ms (missing)
- [ ] `moment.utc()` --> make sure its the same as moment(), also can we define the signature and reuse it?
- [ ] `moment.createInvalid(Object?: flags): Moment` (maybe use parsing flags definition, this can be a subset) (missing)
- [ ] `moment.duration`
  - UnitOfTime can only be from the regular units (ones in MomentInput) -- so maybe another UnitOfTime?
  - there is no object option --> it can be {from?: AnyMomentInput, to?: AnyMomentInput} (at least one should be present)
  - it can be string
  - it can be Duration
  - it can be null, undefined (same as not there)
- [ ] `moment.isMoment` and `moment.isDuration` can NOT take no args -- only possibly `null`/`undefined`
- [ ] `moment.parseZone(AnyMomentInput*)` --> can take many args also
- [ ] `moment.localeData`
  - can take nothing
  - string
  - string array
- [ ] `moment.defineLocale`, `moment.updateLocale` are in the wrong scope, also locale could be null, also its `MomentLanguageData` not `MomentLanguage`
- [ ] `moment.locales` in the wrong scope
- [ ] `moment.normalizeUnits` takes `UnitOfTime` (by definition) not string
# moment prototype functions
- [ ] moment.fn.add moment.fn.subtract
  - take all args that moment duration takes (up to 2)
  - including string instead of number as first argument
- [ ] moment.fn.calendar
  - also all arguments can be marked as optional '?'
  - MomentCalendar can have additional properties, not sure if there is a way to specify that
- [ ] moment.fn.diff
  - 2nd 3rd argument optional
- [ ] moment.fn.format
  - optional first argument
- [ ] moment.fn.from moment.fn.to
  - first arg is any single thing that is acceptable in moment constructor --
    we need an interface/type for that?
- [ ] moment.fn.isAfter isBefore isBetween isSame isSameOrAfter isSameOrBefore
  - can we define a lambda and just declare these as being that lambda?
  - use moment-constructible + UnitOfTime
- [ ] moment.fn.lang - accepts 0 or 1 argument (string) and returns LocaleData or Moment
  - the string can also be a moment obj
- [ ] moment.fn.locale - doesn't accept the boolean flag
- [ ] moment.fn.localeData -- doesn't accept arguments, !its different than the moment.localeData one
- [ ] moment.fn.min max -- take exactly same args as constructor
- [ ] moment.fn.set get -- the UnitOfTime are all the defined functions on moment.fn
  - the MomentInput takes also all defined functions, possibly more than the actual MomentInput has
- [ ] moment.fn.startOf -- recheck UnitOfTime
- [ ] moment.fn.toString -- missing, should it be defined or its 'inherited'
- [ ] moment.fn.creationData -- the MomentCreationData should not have '?'
- [ ] moment.fn.quarters get/set is missing
- [ ] moment.fn.days get/set is missing
- [ ] moment.fn.utcOffset is missing the optional second boolean arg keepLocalTime
- [ ] moment.fn.utc is missing the first optional boolean arg keepLocalTime
- [ ] moment.fn.local is missing first optional boolean arg keepLocalTime
- [ ] moment.fn.parseZone is missing (no args)
- [ ] moment.fn.hasAlignedHourOffset is missing (optional single arg moment-constructible)
- [ ] moment.fn.isLocal is missing (no args)
- [ ] moment.fn.isUtc, isUTC, isUtcOffset are missing (no args, return boolean)
- [ ] moment.fn.zoneAbbr and zoneName are missing (no args, return string)
- [ ] dates,monts,years,zone,isDSTShifted are deprecated and missing but zone is declared
# Duration prototype
- [ ] duration.fn.abs is missing (no arg, returns Duration)
- [ ] duration.fn.add,subtract accept 2 arg duration constructible (missing are (str), (null/undef), ({from,to}), (obj -- that goes through normalizeObjectUnits))
- [ ] duration.fn.as -- takes units that go thru normalizeUnits, but only day,week,month,year + ms,s,m,h
- [ ] duration.fn.valueOf is missing (no arg, returns number)
- [ ] duration.fn.get is missing (takes normalizeUnits, but also one accepted by as/full-name getter)
- [ ] duration.fn.locale and localeData are missing (same iface as moment.fn.locale ... even same functions :-D)
- [ ] duration.fn.lang and toIsoString are deprecated and missing
# Locale
- [ ] all typescript types about locales are wrong -- there are only 2 things LocaleSpec and Locale. LocaleSpec is used to create a locale (updateLocale, defineLocale) and Locale is returned in localeData() for example. The current situation (in the d.ts) is a complete disaster and needs to be redone 
# misc
- [ ] wtf moment.fn.weekday doesn't support string input, but isoWeekday, day, days does
- [ ] refactor setOffsetToParsedOffset in units/offset.js
- [ ] moment.fn.hasAlignedHourOffset is missing from docs. Without args it checks if the current offset is aligned to the hour (no 30 minute zones), with argument it checks if the 2 moments are aligned with respect to each other (so unless the local time is moving by 30 minutes I can't see this returning false)
- [ ] wtf is duration.fn._bubble and why is it there

**Comment by marwahaha** [comment]
@ichernev  - Is this still relevant?

I am thinking we give back the typings to some other place, so someone else can maintain it.

**Comment by marwahaha** [comment]
https://momentjs.com/docs/#/-project-status/
