### ISSUE TITLE
updating locale doesn't work like expected

### ISSUE THREAD

**Issue by thorinisme** [moment/moment#3422]
**Description of the Issue and Steps to Reproduce:**

- import last `moment-with-locales.js` (v 2.14.1)
- execute some code
```javascript
function test(locale) {
  console.group(locale);
  console.log(`updating locale to "${locale}"`, moment.updateLocale(locale));
  console.log('moment.locale()', moment.locale());
  console.log('moment().fromNow()', moment().fromNow());
  console.groupEnd();
}

['es','fr','de'].forEach(test);
```
- result will be KO
```text
es
updating locale to "es" => undefined
moment.locale() => en
moment().fromNow() => a few seconds ago
fr
updating locale to "fr" => undefined
moment.locale() => en
moment().fromNow() => a few seconds ago
de
updating locale to "de" => undefined
moment.locale() => en
moment().fromNow() => a few seconds ago
```

**Environment:**

tested on Windows 7 64bit
[KO] Chrome Version 53.0.2785.101 m (64-bit)
[KO] Firefox Version 48.0.2

**Other information that may be helpful:**
* The time zone: **UTC + 1**
* The time and date at which the code was run: **now**
* Other libraries: **none**

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

```text
Thu Sep 08 2016 13:39:30 GMT+0200 (Romance Daylight Time)
08/09/2016 à 13:39:30
-120
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36
2.14.1
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*
It is
[codepen](http://codepen.io/Thorien/pen/EgjRdq?editors=1010) to test it

**Comment by thorinisme** [comment]
solved !
`updateLocale` need the second parameter even if we doesn't want to change setting.
```javascript
moment.updateLocale(locale, {});
```
It would be probably a good idea:

- to change how `updateLocale work` to doesn't select english when options is **null** like when option is an empty object.

OR

- to update documentation

**Comment by icambron** [comment]
You don't want `updateLocale` at all, actually. Just use `locale`:

```js
function test(locale) {
  console.group(locale);
  console.log(`updating locale to "${locale}"`, moment.locale(locale));
  console.log('moment.locale()', moment.locale());
  console.log('moment().fromNow()', moment().fromNow());
  console.groupEnd();
}
```

<img width="381" alt="screen shot 2016-09-08 at 1 36 08 pm" src="https://cloud.githubusercontent.com/assets/244988/18359731/3e3d6a34-75c9-11e6-89fd-2db16774b7d0.png">

I can't quite see what part of the docs lead you to use `updateLocale`--which is meant for customizing a locale--instead of just `locale`, but we'd be happy to take changes to the documentation meant to clarify that.

**Comment by thorinisme** [comment]
My bad. i searched a lot before use `updateLocale`. I searched terms like "change" "language".

I didn't look "i18n" part. I didn't know that numeronym. I didn't even know the word "numeronym" before you answered me and then i make a deeper search on moment.locale().

If it was as obvious as you say, i wouldn't have taken the time to detail my problem.
