### ISSUE TITLE
Support for ordinal indicators in English?

### ISSUE THREAD

**Issue by mvolz** [moment/moment#3423]
Ordinal numbers, but not ordinal indicators, seem to not be supported (they are not supported in the native Date.parse() either). I came here looking for a library that would support those, wondering if it would be in scope of the project to add it? 

Example:

```
> var d = moment('May 1st, 2010'); // date with ordinal indicator
> d.toString();
'Invalid date'
> var d = moment('May first, 2010'); // date with ordinal number
> d.toString();
'Sat May 01 2010 00:00:00 GMT+0100'
````

**Comment by icambron** [comment]
Passing a non-ISO string into Moment like that is just using the underlying `Date()` constructor. To get Moment to parse an arbitrary format, do this:

```js
> moment('May 1st, 2010', 'MMMM Do, YYYY').toString();
"Sat May 01 2010 00:00:00 GMT-0400"
```

**Comment by mvolz** [comment]
That doesn't solve the issue as we don't know what format we'll be getting
ahead of time.  (It's for a web scraper.) We'd like to be able to input a
string of that format, or any of the other accepted formats, in the style
of Date.parse().

I guess we could try Date.parse, and if it fails, do

moment('May 1st, 2010', 'MMMM Do, YYYY').toString();
and then maybe moment('May 1st, 2010', 'MMMM Do YYYY').toString();

etc., but it would be nice for this to be handled by moment.

Is extending the functionality of Date.parse() to accept other formats
within scope?

**Comment by icambron** [comment]
Moment doesn't do any natural language parsing at all. When you pass a string with no formats, it checks to see if it's an ISO8601 string and if not just hands it to `Date.parse()` to see if it knows what to do (and we've even deprecated that handoff!). So just at a sort of fundamental scoping level we're not going to start adding code of the "figure out what this string means" variety.

One thing you can do is pass an array of strings and Moment. So if you tried `Date.parse()` and didn't get anything, you can do:

```js
moment(str, ['MMMM Do, YYYY', 'MMMM DD YYYY', etc]
```
