### ISSUE TITLE
#Locale seems not work on PhantomJS with Karma

### ISSUE THREAD

**Issue by w4-steve** [moment/moment#3428]
Hi,
Our team CI is broken after 2.15.0 which uses Karma with PhantomJS.
From investigating, moment(new Date()).locale('ko') does not change its locale and seems only happens on this environment, Karma and PhantomJS.
NodeJS is just fine.

Here is the source code we are using now:

```js
let formatter = moment(date);
if (locale) {
  formatter = formatter.locale(locale);
}
// Check if locale is one of Korean locales.
if (formatter.locale() === 'ko') {
  return formatter.format('YYYY년 MMM Do a h:mm');
}
return formatter.format('LLL');
```

And the result of the following code
```js
console.log((new Date()).toString());
console.log((new Date()).toLocaleString());
console.log((new Date()).getTimezoneOffset());
console.log(navigator.userAgent);
console.log(moment.version);
```

is

```
LOG: 'Mon Sep 12 2016 19:51:41 GMT+0900 (KST)'
LOG: 'September 12, 2016 at 7:51:41 PM GMT+9'
LOG: -540
LOG: 'Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1'
```

Thanks!

**Comment by andreboekhorst** [comment]
Noticed a problem with our builds as well. The locales didn't seem to be included in the build. 
For now, a downgrade to 2.14.1 in our package.json did the trick.

**Comment by maggiepint** [comment]
I just did an upgrade to 2.15 on my code at work and the npm build looks totally fine to me. I can see that a lot of people are having this issue though. Can I get more details on how you are installing moment? Are you using the npm package and then pulling the min/moment-with-locales.js or min/moment-with-locales.min.js file?

**Comment by andreboekhorst** [comment]
I'm using node as a npm package loaded with webpack. With the 2.15 version, I don't see the strings withing moment.defineLocale (eg; weekdays : 'zondag_maandag_dinsdag_woensdag_donderdag_vrijdag_zaterdag'.split('_') );

**Comment by ichernev** [comment]
If you have a command line that fais just runa git bisect. Or share it.

**Comment by Nickman87** [comment]
@andreboekhorst We had the same problem, locale not working anymore. Seems like the new version does not import locales automatically, instead you have to import the locale(s) you want to use.

`
import Moment from 'moment';
import 'moment/locale/nl';
`

**Comment by w4-steve** [comment]
Once again, it only happens on the environment with Karma and PhantomJS.

The result of
```js
console.log(moment.locales());
const formatter = moment().locale('ko');
console.log(formatter.locale());
```

is

```
LOG: ['en']
LOG: 'en'
```

I am trying to find what change causes this problem but seems not easy since I am not familiar with the momentjs project structure...

**Comment by icambron** [comment]
Can y'all check if this is fixed in 2.15.1?

**Comment by w4-steve** [comment]
Okay, seems work for me :)
Thanks!

**Comment by w4-steve** [comment]
I would
