### ISSUE TITLE
v2.15.0 has a breaking change.

### ISSUE THREAD

**Issue by ljharb** [moment/moment#3431]
**Description of the Issue and Steps to Reproduce:**

git clone https://github.com/airbnb/react-dates - `npm install && npm install moment@2.15` - and `npm run tests-karma`. Tests fail. `npm install moment@2.14`. Tests pass.

This constitutes a breaking change in a minor version. I'll try to narrow down the reproduction steps.

**Comment by ljharb** [comment]
https://travis-ci.org/airbnb/react-dates/jobs/159465698 also has the failures.

**Comment by icambron** [comment]
Pretty sure you're having some sort of issue where your locale's aren't loading. This is probably the same thing as #3428

**Comment by icambron** [comment]
Actually, I just posted #3432, which fits the bill perfectly.

**Comment by ljharb** [comment]
I agree that looks very similar.

**Comment by ichernev** [comment]
@ljharb can you try reverting https://github.com/moment/moment/pull/3344/files to see if it helps?

**Comment by ichernev** [comment]
@ljharb cloned, `npm install` hangs :
```
extract:sinon-sandbox: sill doParallel extract 919
```
in a loop of SIGSEGV

node 6.5.0.

killed, `npm install` -- same thing.

**Comment by ljharb** [comment]
@ichernev  I've definitely never seen that - I think that might just be npm issues? (they're having issues right now)

**Comment by ljharb** [comment]
@ichernev I'll test reverting that PR now (which imo is horribly wrong and should never have been merged in the first place anyways)

**Comment by ljharb** [comment]
@ichernev yes, reverting that fixed the issue.

**Comment by ljharb** [comment]
@ichernev any update? whatever bug that PR was fixing is not worth a breaking change in a non-major version - it'd be great to get this reverted ASAP.

**Comment by ichernev** [comment]
@ljharb it kind of makes sense if you use require to test if its there. Also we're talking about the weird environments here, there is only solutions that work and that don't, and there is no way for us to figure this out beforehand.

**Comment by ljharb** [comment]
@ichernev you can certainly figure out beforehand that not using the incredibly standard `require()` will break things - i could have told you that instantly. 

As a rule, nearly every workaround for a webpack bug that's not in webpack breaks things. It's happened tons of times before.

**Comment by ljharb** [comment]
At any rate, you now know that people that worked on 1.14 are broken on 1.15, so by the semver contract, you must revert the PR and publish a patch. If you still want that change, you can certainly include it in a major version bump, although I discourage it.

**Comment by ljharb** [comment]
Closed in #3438.
