### ISSUE TITLE
Global locale setter not working?

### ISSUE THREAD

**Issue by icambron** [moment/moment#3432]
Open the momentjs.com homepage and run these from the console:

```js
> moment().locale('es').format('LLLL')
"martes, 13 de septiembre de 2016 4:16" //ok, locales are available
> moment.locale()
"en" //yup, just default global
moment.locale('es')
"es" //cool
moment.locale()
"en" //what?
```

I tested this with Chrome 53 on OSX. I think this a likely cause of #3431 and possibly #3428.

**Comment by ichernev** [comment]
We're rendering the snipets with the clock every second. That is why the locale is reset to whatever is chosen in the selector at the bottom of the page.

**Comment by icambron** [comment]
Ah, I should have thought of that.

**Comment by mj1856** [comment]
I usually switch to the docs page before opening the console, which doesn't switch with the clock tick.
