### ISSUE TITLE
Feature request: moment.utcOffset

### ISSUE THREAD

**Issue by benjycui** [moment/moment#3433]
Sorry to trouble you, this is not an issue, but a feature request.

Now, we can set locale globally:

```js
moment.locale('zh-cn');
```

But, it seems that we cannot set UTC offset globally. I had found moment-timezone, but it is too large to use in browser.

So, could moment provide something like `moment.utcOffset` to set UTC offset globally? What's more, most of programs just need one timezone...

**Comment by mj1856** [comment]
I can see the desire to set it globally would be useful.  A PR would be welcome.

I'll say though that even though many programs may just need one time zone, that time zone may need multiple offsets to handle DST.  Though for countries like India or China, or other places that have relatively stable single-offset time zones, it might be desired to set the offset globally.

**Comment by maggiepint** [comment]
@benjycui you are aware that you can manually package only the timezones you need for moment timezone? You don't have to pull them all in.

Also, you are aware that if you use moment by itself, it will handle the time zone of the browser without the moment timezone add on?

Finally, as Matt pointed out, this doesn't work in many time zones because they observe DST. If this would fix your problem, may I ask, what problem does it fix?

**Comment by mj1856** [comment]
Before anyone starts work on this - I'd like a poll from the community on whether this would be a useful feature for you, and why.  Please +1 or -1 this comment appropriately. :)

**Comment by mj1856** [comment]
Keep in mind also that you can *always* set the offset on a per-instance basis.  In fact, there's a second parameter on the `utcOffset` function that is useful for this.  (We need to document it)  For example:

```js
moment([2016,0,1,12,30]).utcOffset('+08:00', true)  // true makes sure the original local time values persist
```

**Comment by benjycui** [comment]
@maggiepint yep, I knew that we can import `moment-timezone/moment-timezone`.

But, for Chinese, or other countries that don't need to handle DST, `moment.utcOffset` is enough and this will reduce bundle size.

Thanks 😄

**Comment by butterflyhug** [comment]
This is purely a personal reaction (not representing Moment), but I'm mildly -1 on this (at least until the deprecated `#zone` API is gone).

I can see the potential value, so I'm not strongly against it.  But many developers already conflate UTC offset with "timezone", and so I think it might invite developer error if we build an API that makes it easier to apply an offset globally than a DST-sensitive timezone.  I suppose this concern could be ameliorated somewhat if we also added a global default timezone setter in Moment Timezone, but then this starts to feel like a bigger implementation project.

**Comment by maggiepint** [comment]
I'm -1 on this. Lucas covered it.

**Comment by icambron** [comment]
-1; why not just implement a wrapper function to generate Moments with that fixed offset?

```js
function zhMoment(){
  return moment.apply(null, arguments).utcOffset('+08:00', true);
}
```

**Comment by icambron** [comment]
Well, the jury is in. We're not going to implement this.
