### ISSUE TITLE
Get date and time from n milliseconds from now

### ISSUE THREAD

**Issue by dibenso** [moment/moment#3441]
I'm looking for a way to get a date and time that is n milliseconds in the future. For example, 5 days in milliseconds is 432,000,000. Say the date and time now is **2013-02-08 20:00:00.000**. When I add **432,000,000 milliseconds** to that, I should get something like: **2013-02-08 20:00:00.000**. What is the best approach to this?

**Comment by icambron** [comment]
I don't understand why you'd expect to add 5 days and get the same date; do you mean 02-13? I'm going to assume that you do:

```js
> moment('2013-02-08T20:00:00.000').parseZone().add(432000000).format()
'2013-02-13T20:00:00Z'

//this is slightly different than

> moment('2013-02-08T20:00:00.000').parseZone().add(5, 'days').format()
'2013-02-13T20:00:00Z'

//which will account for the DST and return 20:00 whether that's really 432,000,000 ms later or not.
```

If I've misunderstood your question, mention me and I'll reopen.

**Comment by dibenso** [comment]
Shoot, I mistyped the second date. Yes I did mean 2-13. And this is exactly what I was looking for :thumbsup: Thanks for the quick response!
