### ISSUE TITLE
website bug.

### ISSUE THREAD

**Issue by mesqueeb** [moment/moment#3450]
Moment's website has two times "Japanese" as selection on the landing page at the bottom.

**Comment by icambron** [comment]
One is Japanese with Latin characters and the other is Japanese with Japanese characters. They should be labeled differently, of course, but it seems OK.

**Comment by mesqueeb** [comment]
I'm sorry, but it's clearly not Japanese with roman letters... it's not even close to Japanese. Did you actually look at it?

// 5 taun ingkang kepengker
 // 4 taun ingkang kepengker
 11 jam ingkang kepengker
 // wonten ing 13 jam

Please keep the issue open until it gets fixed because this is not Japanese.

**Comment by icambron** [comment]
ah, you're right, it's Javanese. Ticket is open here: https://github.com/moment/momentjs.com/issues/360
