### ISSUE TITLE
moment().add() doesn't work on 2.15.0.

### ISSUE THREAD

**Issue by roccomuso** [moment/moment#3452]
Node.js v4.4.6 on Raspbian, using Moment 2.15.0:

```javascript
var moment = require('moment');
var a = moment();
var b = a.add(9, 'hours');
console.log(a.format(), b.format());
```
Simply, It doesn't work.

**Comment by mj1856** [comment]
You were probably seeing the same value for both a and b because you didn't create a clone, so add mutated a.  Use either `moment(a).add...` or `a.clone().add...`
