### ISSUE TITLE
How to represent dates (without time) and times (without date)?

### ISSUE THREAD

**Issue by DanielSWolf** [moment/moment#3455]
A Moment.js object (like its underlying Date object) always represents an exact point in time.

Sometimes, however, I just want to store a *date* (say 2016-09-19). This is *not* a point in time, but a calendar day. Depending on my time zone, this calendar day may represent different intervals in time. Representing it using a Moment.js object (say, `moment('2016-09-19T00:00+00:00')`) is a hack at best.

A related concept is that of a *time of day* (say, 9:30 AM). A time of day has no date or time zone attached to it. So storing a time of day as something like `moment('0001-01-01T09:30+00:00')` again seems rather hackish to me.

So I wonder: *What is the idiomatic way of representing dates and times in JavaScript code that uses Moment.js?* Ideally, this approach should allow combining a date, a time, and a time zone back into a Moment.js object.

**Comment by maggiepint** [comment]
This question has sort of been asked before many times. We've never really had a good answer. The API simply doesn't model the JodaTime sort of thing that you are asking for. @mj1856 this is up your alley - ideas?

**Comment by mj1856** [comment]
Right, you are correct that there are differences in those values, but moment doesn't model date-only or time-only values from a _representational_ standpoint.

You can only instantiate `moment` object from a date-only or time-only value, and you can format date-only or time-only outputs.  Idiomatically in moment, you would do this:

```js
var date = moment("2016-09-19", "YYYY-MM-DD");
date.add(1, 'month'); // date operations follow date-math logic
var s = date.format("YYYY-MM-DD");

var time = moment("09:25", "HH:mm");
time.add(20, 'hours'); // time operations follow time-math logic
var s = time.format("HH:mm");
```

For more about date math vs time math logic, see [the moment user guide](http://momentjs.com/guides/#/lib-concepts/date-time-math/).

But fundamentally, a `moment` is tied to an instant in time, in the same way that the JavaScript `Date` object is.  If you want a JavaScript API that models the entire domain of date and time, look to the [js-joda](https://js-joda.github.io/js-joda/) project.  A similar API can be found in Joda Time and the `java.time` Java 8 package, as well as Noda Time for .NET.

For comparison, a `moment` object is most closely related to a `ZonedDateTime` object in these other APIs.  The zone is either local, UTC, a fixed offset, or a specific time zone if you're using the moment-timezone add-on.  The default is local time, just like the JS `Date` object.  However, the JS `Date` object can *only* use the local time zone, whereas moment's can vary as needed.

**Comment by mj1856** [comment]
I made a small edit to the samples above, to use `moment.utc` instead of just `moment`.  The reason for this is because the local time zone may have discontinuities around time zone offset transitions, such as those associated with daylight saving time.  If you're working with date-only or time-only values, it makes more sense to use UTC than local time, such that you do not encounter these discontinuities.

In a Joda-like API, you'd have `LocalDate` and `LocalTime` types that are not tied to any time zone in particular.  Since Moment does not have separate types for these, then use UTC as a surrogate.

**Comment by dskrvk** [comment]
Related: https://github.com/moment/moment/issues/1167
