### ISSUE TITLE
[BUG]moment check format bug

### ISSUE THREAD

**Issue by TianyiXia** [moment/moment#3457]
newValue = '2016-08-21 01:48P';
moment(newValue, "YYYY-MM-DD hh:mmA", true).isValid();

This should return false, but it returns ture

see:
http://jsfiddle.net/b6549hzw/

**Comment by icambron** [comment]
I don't understand. Why should that return false? That string looks OK to me.

Your JS Fiddle doesn't pass `true` as a third argument, so that explains those.

**Comment by TianyiXia** [comment]
shouldn't it reject "P"? Is there way to require it to be "PM"?

**Comment by icambron** [comment]
Not according to the docs:

>Post or ante meridiem (Note the one character a p are also considered valid)

I suppose one could challenge the wisdom of that, but that ship sailed long ago.
