### ISSUE TITLE
Minify JavaScript (remove comments)

### ISSUE THREAD

**Issue by r0b-** [moment/moment#3461]
PageSpeed Insights states that the size of moment.min.js (from CDN) can be reduced by 23%...
If I look at the code it's uglified and minimized but a lot of (all?) comments are still included.

Thanks
Rob

**Comment by skfd** [comment]
#3337 🕙

**Comment by maggiepint** [comment]
closing

**Comment by r0b-** [comment]
Unfortunately the problem still exists...
https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.0/moment.min.js

**Comment by westy92** [comment]
The problem still exists with 2.17.1 as well.  This should be reopened.
https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js

**Comment by ichernev** [comment]
Repoening while the PR is not merged.

**Comment by icambron** [comment]
But now the PR is merged, so closing again.
