### ISSUE TITLE
Moment().utcOffset(`${utcOffset}`) always considers it hours.

### ISSUE THREAD

**Issue by shawngong** [moment/moment#3462]
Seems like the value passed into the utcOffset function is always taken as hours, even though in the docs it says it should be taken as minutes if above 16 or below -16.

```
const utcTime = new moment.utc();
const currentTimeZone = utcTime.clone();
currentTimeZone.utcOffset('-60');
console.log(currentTimeZone.format());
```

What's logged:
`2016-09-23T08:25:00-60:00`

**Comment by icambron** [comment]
Your input is not below -16 because it's a string. From the docs:

```
Passing a string that does not start with + or - will be interpreted as if it were "+00:00".
```

You just want

```js
currentTimeZone.utcOffset(-60);
```
