### ISSUE TITLE
Missing signatures for utcOffset in typescript definition file

### ISSUE THREAD

**Issue by fredgate** [moment/moment#3464]
When using momentjs in a TypeScript project, we can not call for the `Moment` interface the `utcOffset` method with the `keepLocalTime` argument because in the typescript definition file there is no signatures with two arguments.

Call examples :

```
moment().utcOffset(0);          // OK
moment().utcOffset(0, true);    // compile time error
```

**Comment by marwahaha** [comment]
This has been resolved.
