### ISSUE TITLE
Adding 1 day on 2011-12-29 while in Pacific/Apia yields the same day

### ISSUE THREAD

**Issue by octurion** [moment/moment#3468]
**Description of the Issue and Steps to Reproduce:**

On 2011-12-29 23:59:59, [Samoa changed its time zone from UTC-11 to UTC+13, thus completely skipping 2011-12-30](http://www.timeanddate.com/news/time/samoa-dateline.html).

However, when executing the following ([relevant JSFiddle](https://jsfiddle.net/hpuwtfos/)):

```js
var t = moment.tz("2011-12-29 00:00:00", "YYYY-MM-DD HH:mm:ss", true, "Pacific/Apia");

console.log(t.format());
console.log(t.clone().add(1, "day").format());
console.log(t.clone().add(2, "days").format());
```

The following is outputted on the console:

```
2011-12-29T00:00:00-10:00
2011-12-29T00:00:00-10:00
2011-12-31T00:00:00+14:00
```

**Environment:**

Reproduced on Firefox 49 and Chromium 52 on Ubuntu 14.04 (although it's highly unlikely this issue is browser-specific).

**Comment by icambron** [comment]
This should go in the [moment-timezone repo](https://github.com/moment/moment-timezone). I don't know its rules on historic zone changes so I'd just be guessing.
