### ISSUE TITLE
Empty exception cath

### ISSUE THREAD

**Issue by rafaelsotelomeza** [moment/moment#3470]
Hi in this library there is an empty catch, and my security team is marking me this as a concern, do you have any plans to handle any exception on this code, or just let it bubble up ?

File name: moment-with-locales.js

function loadLocale(name) {
        var oldLocale = null;
        // TODO: Find a better way to register and load all the locales in Node
        if (!locales[name] && (typeof module !== 'undefined') &&
                module && module.exports) {
            try {
                oldLocale = globalLocale._abbr;
                require('./locale/' + name);
                // because defineLocale currently also sets the global locale, we
                // want to undo that for lazy loaded locales
                locale_locales__getSetGlobalLocale(oldLocale);
<b>            } catch (e) { }</b>
        }
        return locales[name];
    }

**Comment by icambron** [comment]
Nope, it's there on purpose. Moment allows users to provide third-party locale files so it doesn't know whether it can load a locale or not until it tries to do it. For better or worse, Moment doesn't throw exceptions, so it just no-ops here. To make that no-op work, it has to bury the exception it gets from trying to require a missing file.

It would be fair to argue that Moment *should* throw an exception when the user tries to load a locale that doesn't exist, but the don't-throw-exceptions boat sailed long ago.
