### ISSUE TITLE
Build failing due to moment.js

### ISSUE THREAD

**Issue by GeekAb** [moment/moment#3471]
Hi, 

I am getting following error while crating my build using babel, 

Error transforming 
/picker.js/node_modules/moment/src/lib/locale/locales.js with 'babel' plugin: /picker.js/node_modules/moment/src/lib/locale/locales.js: 'import' and 'export' may only appear at the top level (4:0)

I am not sure what is the issue, I had checked all possible things which might create problem. NPM version is fine, mode version is fine, all required plugins are included. 

**Environment:**
Ubuntu 16.04
Node v6.6.0
npm v3.10,3
moment.js 2.15.1

**Comment by icambron** [comment]
Yeah, we don't yet support Babel compilation against the source. We're working on it, though! Perhaps in the meantime it would work better to build against our compiled code?
