### ISSUE TITLE
Problem injecting moment as dependency in angular 1 and TypeScript

### ISSUE THREAD

**Issue by mortenamby** [moment/moment#3476]
moment 2.13.0
angular 1.5.8
typescript 2.0.3

Since the latest version of moment that contains type definitions, there is an issue when injecting moment as dependency for an angular 1 component.

Earlier the moment object could be referenced using moment.MomentStatic but with the new definitions, MomentStatic no longer exists.

Importing moment like this:

```
import * as moment from "moment"

class MyComponent {
   constructor(myAngularMomentVar: moment) { }
}
```

causes the typescript compiler to complain that it cannot find the type moment.

**Comment by alex-pl** [comment]
I'm using Ionic 2 and TypeScript 2.

My solution is:

    import { default as moment } from 'moment';

**Comment by mortenamby** [comment]
@alex-pl I tried that but without luck. It still complains about missing type.

**Comment by alex-pl** [comment]
In the meantime I've found a better way. You can try:

    import moment from 'moment';

Or, if you get namespace errors:

    import Moment from 'moment';

But at the end the best solution will be when #3419 is solved.
Since TypeScript 2 I'm not able to use languages anymore.

**Comment by mortenamby** [comment]
@alex-pl Thanks for the suggestions, but the issue remains

**Comment by blakeembrey** [comment]
The correct way to use the types is `typeof moment`. Otherwise you're just referencing a value and not a type, hence the "no type" error.

**Comment by alex-pl** [comment]
Have you tried to enable synthetic imports?
eg. https://stackoverflow.com/a/38050854

**Comment by marwahaha** [comment]
Closing due to age. If you still have questions, please re-open.
