### ISSUE TITLE
Bug in function from()

### ISSUE THREAD

**Issue by cesguerra** [moment/moment#3478]
Wrong year number in the result of function **from()**

```
var birthdate = moment("26/11/1983", "DD/MM/YYYY");
var today = moment("30/09/2016", "DD/MM/YYYY");
// expected: 32 years
var age = birthdate.from(today);
// produces: 33 years
```
**Environment:**
Chrome 53, Windows 10, Moment.js 2.15.1
UTC -3 (São Paulo - Brazil)

**Comment by icambron** [comment]
Not a bug: `from` rounds. Anything over 32.5 years will be result in "33 years".

You can override that behavior globally like this:

```js
moment.relativeTimeRounding(Math.floor);
```

Or you can use `diff` to compute the years.
