### ISSUE TITLE
moment().isSame produce unexpected result

### ISSUE THREAD

**Issue by jeffrey008** [moment/moment#3479]
**Description of the Issue and Steps to Reproduce:**
When comparing 2 different times, eg. 16:00 and 16:05, the result is false.
When 2 times are equal, the result is also false.
I do the comparison in Chrome inspector 
`moment("16:00").isSame("16:05") //false`

Please take a look and let me know if I made a mistake. Thank you.

Mon Oct 03 2016 17:37:32 GMT+0800 (HKT)
10/3/2016, 5:37:32 PM
-480
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
2.9.0

**Comment by maggiepint** [comment]
You need to specify a format for both times. What you are doing right now is causing a warning that says 'moment construction falls back to JS Date`. When you are getting this warning, your dates may not be parsing correctly. Instead do the following:

```js
moment("16:00", 'HH:mm').isSame(moment("16:00", 'HH:mm') )
true
```
