### ISSUE TITLE
Feature request: A more accurate .humanize

### ISSUE THREAD

**Issue by FGRibreau** [moment/moment#348]
.humanize isn't really accurate when it comes to seconds.

``` javascript
moment.duration(40, 's').humanize() === "a few seconds" // expected "40 seconds"
moment.duration(45, 's').humanize() === "a minute" // expected "45 seconds"
```

I understand that we don't often want this level of accuracy but sometimes we do want the exact value in a human readable way.

I suggest a change to the API (which seems backwards compatible from what I actually see) to support this feature: 

``` javascript
moment.duration(40, 's').humanize() === "a few seconds"
moment.duration(40, 's').humanize(true) === "in a few seconds"

moment.duration(40, 's').humanize({precise:true}) === "40 seconds"

moment.duration(40, 's').humanize({suffix:true, precise:true}) === "in 40 seconds"
moment.duration(40, 's').humanize({precise:false, suffix:true}) === "in a few seconds"
```

What do you think ?

**Comment by doingweb** [comment]
In my mind, this needs to go the other way; the core humanize should be precise, and the different (arbitrary) levels of *fuzziness* should be achieved through options or plugins.

**Comment by bborowin** [comment]
Would love to see an "accurate humanize" option, having to use an additional library on top of moment is a little clunky..

**Comment by dannyid** [comment]
+1 on precise humanize!

**Comment by Jamie452** [comment]
+1 for precise humanize!

**Comment by iambibhas** [comment]
Really disappointed to see that there is no option to get the precise humanized duration. :|

**Comment by Envek** [comment]
There is some plugin called [Precise Range] referenced in the docs. Have anyone tried it?

[Precise Range]: http://momentjs.com/docs/#/plugins/preciserange/

**Comment by marseille** [comment]
Precise Range technically works, but it seems to return a string instead of a moment object, so I can't pick out specifically what date parts I might like.

The language (imo) is a bit off too, one result was - 'an hour 19 minutes a few seconds' . I'd prefer to see something like 1 hour 19 minutes and a few seconds. Mixing words and numbers has always been a bit of a grammatical no-no (as far as I know).

+1 for precise moment humanize

**Comment by topaxi** [comment]
@Envek Precise Range seems nice, doesn't support any i18n/l10n though...

Official support by moment.js would be nice as I needed this in at least two or three of my projects.

**Comment by patgod85** [comment]
@topaxi +1

**Comment by nikulinsanya** [comment]
+1

**Comment by Offirmo** [comment]
@doingweb I confirm that the HumanizeDuration.js module works pretty well !

**Comment by pboulet** [comment]
+1 for precise moment humanize

**Comment by ismarslomic** [comment]
+1 for more precise moment humanize

**Comment by Dbuggerx** [comment]
+1

**Comment by Aaronmsv** [comment]
+1

**Comment by MichaelTSS** [comment]
+1

**Comment by mansa-dev** [comment]
+1

**Comment by sebtoun** [comment]
+1

**Comment by magicdawn** [comment]
+1

**Comment by benaich** [comment]
+1

**Comment by waterplea** [comment]
Why is this getting closed all the time? This is the most obvious feature that must be implemented in moment.js. I was actually shocked that it isn't in already. Humanize is plain useless anywhere other than some vague time display like in posts on forums without it.

**Comment by vbardales** [comment]
+1

**Comment by Assitan** [comment]
+1

**Comment by RTulenov** [comment]
+1

**Comment by mattgrande** [comment]
-1. I like humanize how it works now. It's supposed to give a "human friendly" version of a duration.

"Hey Frank, when did you send that email?"  
"About a minute ago."

"Hey Frank, when did you send that email?"  
"Forty three seconds ago."

Which seems more "human?"

**Comment by inca** [comment]
More accurate version wasn't supposed to replace the current one. It's a request for new feature.

**Comment by lukeferguson** [comment]
+1, whilst what we have now is great for describing the duration of something in the past, it's not appropriate for describing, say for example the length of an appointment, e.g. "1 hour, 30 minutes".

**Comment by lukeferguson** [comment]
+1, @mattgrande whilst what we have now is great for describing the duration of something in the past, it's not appropriate for describing, say for example the length of an appointment, e.g. "1 hour, 30 minutes".

**Comment by weedorbeat** [comment]
+1

**Comment by mikila85** [comment]
+1

**Comment by quantumew** [comment]
+1

**Comment by praveenaj** [comment]
+1

**Comment by mariano-aguero** [comment]
+1

**Comment by staff0rd** [comment]
+1

**Comment by stephanbarrett** [comment]
+1

**Comment by basicsciencemichael** [comment]
+1

**Comment by BrandonMurnane** [comment]
+1

**Comment by andresgleztelo** [comment]
+1

**Comment by sburton84** [comment]
+1 for this from me. Making a new language definition, or modifying an existing one, is really not a solution. It looks like there are 108 languages currently supported by Moment, so we either have to modify 108 definitions manually (and hope we get them all grammatically correct), or just forget about any users who don't speak English? Neither of those is really acceptable.

**Comment by Nerian** [comment]
I am using this:

````javascript
var humanizeDuration = function(eventDuration){
  eventMDuration = moment.duration(eventDuration, 'seconds');
  eventDurationString = ""
  if (eventMDuration.days() > 0)
      eventDurationString += " " + moment.duration(eventMDuration.days(), 'days').humanize()
  if (eventMDuration.hours() > 0)
      eventDurationString += " " + moment.duration(eventMDuration.hours(), 'hours').humanize()
  if (eventMDuration.minutes() > 0)
      eventDurationString += " " + moment.duration(eventMDuration.minutes(), 'minutes').humanize()

  return eventDurationString.trim()
}
````

**Comment by ImLoaD** [comment]
+1

**Comment by OR13** [comment]
+1 without this feature, time tracking is not possible.

**Comment by flippyhead** [comment]
I'm surprised this hasn't been mentioned: https://codebox.org.uk/pages/moment-date-range-plugin

**Comment by ImLoaD** [comment]
Why issue is closed?

**Comment by sebastianhaas** [comment]
+1

**Comment by mariotsi** [comment]
+1

**Comment by joshdance** [comment]
+1

The ability to optionally add a more precise, while still 'human' option would be super valuable.

**Comment by RichardLindhout** [comment]
+1

**Comment by decklord** [comment]
+1

**Comment by yakirgot** [comment]
+1

**Comment by lightbringer1991** [comment]
+1

**Comment by funwithtriangles** [comment]
+ 1

**Comment by Fingel** [comment]
The current implementation is so human as to be basically useless.

**Comment by amitailanciano** [comment]
+1

**Comment by sproot** [comment]
> ```duration.humanize``` has thresholds which define when a unit is considered a minute, an hour and so on. For example, by default more than 45 seconds is considered a minute, more than 22 hours is considered a day and so on. To change those cutoffs use ```moment.relativeTimeThreshold(unit, limit)``` where unit is one of ```ss```, ```s```, ```m```, ```h```, ```d```, ```M```.

https://momentjs.com/docs/#/customization/relative-time-threshold/

**Comment by kokizzu** [comment]
+1

**Comment by boydy12** [comment]
+1

**Comment by juliekoubova** [comment]
+1, please reconsider opening this issue 😍

**Comment by msartorius** [comment]
+1

**Comment by purell** [comment]
+1

**Comment by DonovanCharpin** [comment]
+1

**Comment by nextsoftpl** [comment]
+1

**Comment by liyuankui** [comment]
+1

**Comment by liyuankui** [comment]
https://momentjs.com/docs/#/plugins/preciserange/

**Comment by cogwirrel** [comment]
I use something like this:
```es6
function stringifyDuration(duration) {
    // Return a human readable string representing the given moment duration

    // Split the duration into parts, and drop the most significant parts with a value of 0
    const durationParts = _.dropWhile([
        { value: duration.years(), unit: 'year' },
        { value: duration.months(), unit: 'month' },
        { value: duration.days(), unit: 'day' },
        { value: duration.hours(), unit: 'hour' },
        { value: duration.minutes(), unit: 'minute' },
        { value: duration.seconds(), unit: 'second' },
        { value: duration.milliseconds(), unit: 'millisecond' },
    ], (part) => part.value === 0);

    // Display up to two of the most significant remaining parts
    return _.take(durationParts, 2).map((part) => (
        `${part.value} ${pluralize(part.unit, part.value)}`
    )).join(', ');
}
```
```javascript
> stringifyDuration(moment.duration(26, 'hours'))
"1 day, 2 hours"
```
Uses [lodash](https://lodash.com/) and [pluralize](https://github.com/blakeembrey/pluralize).

**Comment by TWiStErRob** [comment]
@timrwood a case for implementing this:
1. @rockymeza's https://github.com/moment/moment/issues/348#issuecomment-6535794 solution means we (every single developer out there) have to re-implement this in every language they support, even though you and your contributors have already done the amazing job of translating to many languages
2. @mattgrande https://github.com/moment/moment/issues/348#issuecomment-237830415 argument that it's already human enough, is just plain wrong. Consider this conversation:
    > Hey Frank, I'm going to grab lunch, how much time do I have till next meeting?
    > an hour

    Now, let's see what that "hour" can mean in `moment`:

    ```js
    moment.duration({hours: 0, minutes: 45}).humanize() === "an hour"
    moment.duration({hours: 1, minutes: 29}).humanize() === "an hour"
    ```
    This means that if we understand things differently I could be ~45 minutes early or late for that meeting.

3. Thanks to @sproot for [calling out RTFM](https://github.com/moment/moment/issues/348#issuecomment-307134213)

    ```js
    moment.relativeTimeThreshold('m', 60);
    moment.duration({hours: 0, minutes: 45}).humanize() === "45 minutes"
    moment.duration({hours: 0, minutes: 59}).humanize() === "59 minutes"
    moment.duration({hours: 0, minutes: 60}).humanize() === "an hour"
    moment.duration({hours: 1, minutes: 29}).humanize() === "an hour"
    ```
    It's a bit better, but still problematic when the break length is longer than 60 minutes. That ~30 minute difference can mean I can go home, eat and come back, or I have to grab something nearby.

4. Workarounds of @Nerian https://github.com/moment/moment/issues/348#issuecomment-279819773 and @cogwirrel https://github.com/moment/moment/issues/348#issuecomment-346233713 combined with @sproot's tip gets a "good enough" implementation without needing an additional library (_ parts can be implemented using plain JS), but it's hack for something that could be supported directly:
    ```js
	var el = document.createElement('script');
	el.src = "https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.js";
	document.head.appendChild(el)
	moment.relativeTimeThreshold('s', 60);
	moment.relativeTimeThreshold('ss', 0); // must be after 's', disables "few seconds"
	moment.relativeTimeThreshold('m', 60);
	moment.relativeTimeThreshold('h', 24);
	moment.relativeTimeThreshold('d', 31);
	moment.relativeTimeThreshold('M', 12);
	/**
	 * Return a precize human readable string representing the given moment duration.
	 *
	 * @param {Moment.Duration} duration
	 * @param {{mostPreciseUnit: string, numberOfSignificantParts: integer}} options
	 */
	moment.duration.fn.humanizePrecisely = function(options = {}) {
		// Split the duration into parts to be able to filter out unwanted ones
		const allParts = [
			{ value: this.years(), unit: 'years' },
			{ value: this.months(), unit: 'months' },
			{ value: this.days(), unit: 'days' },
			{ value: this.hours(), unit: 'hours' },
			{ value: this.minutes(), unit: 'minutes' },
			{ value: this.seconds(), unit: 'seconds' },
			// cannot format with moment.humanize()
			//{ value: duration.milliseconds(), unit: 'milliseconds' },
		];

		return _(allParts)
			// only use the first parts until the most precise unit wanted
			.take(_.findIndex(allParts, {unit: options.mostPreciseUnit || 'seconds'}) + 1)
			// drop the most significant parts with a value of 0
			.dropWhile((part) => part.value === 0)
			// skip other zeroes in the middle (moment.humanize() can't format them)
			.reject((part) => part.value === 0)
			// use only the significant parts requested
			.take(options.numberOfSignificantParts || allParts.length)
			// format each part
			.map((part) => moment.duration(part.value, part.unit).locale(this.locale()).humanize())
			.join(' ');
	}
	moment.duration({hours: 2, minutes: 3, seconds: 4}).locale('de').humanizePrecisely()
        // === "2 Stunden 3 Minuten 4 seconds"
    ```
(Note: There is something wrong with seconds formatting and locales, that'll be fixed by #3981 in #4183.)

**Comment by mercmobily** [comment]
For what it's worth, I just found this from the official documentation:

https://momentjs.com/docs/#/plugins/preciserange/

My own code looks like this -- and it works perfectly:

        var d1 = new Date()
        var d2 = new Date(durationInMinutes * 60 * 1000)
        return moment.preciseDiff(d1 - d2)

I guess this effectively closes this issue...?

**Comment by TWiStErRob** [comment]
@mercmobily for AU, US (CA), UK: yes, ROW: not really; maybe when https://github.com/codebox/moment-precise-range/issues/6 is fixed.

(Sidenote: using `moment` and `*60*1000` looks a bit strange to me, have you considered `moment().add(durationInMinutes, 'minutes')`?)

**Comment by mercmobily** [comment]
Ah, I am not very well versed in Moment! What does `moment().add(durationInMinutes, 'minutes')` add to?
I think once that issue is closed, that's "the" solution to this issue...

**Comment by TWiStErRob** [comment]
`moment()` is "now" (similar to `new Date()`), and [`add`](https://momentjs.com/docs/#/manipulating/add/) increases that by `n` minutes. Any moment object can be used though, not limited to "now". *(In order to keep this already long discussion focused, let this be the last comment related to this sidenote ;)*

**Comment by aosin** [comment]
+1

**Comment by cameronlowry** [comment]
+2

**Comment by vicdup** [comment]
+1

**Comment by ichirkin** [comment]
+1

**Comment by tsdaemon** [comment]
+1

**Comment by vynmera** [comment]
Please reopen this. My software would like to show any sort of time interval correctly, and changing "every 12 seconds" to "every few seconds" or changing "every 54 seconds" to "every minute" is not acceptable.

**Comment by marcelothebuilder** [comment]
+1

**Comment by m4l3vich** [comment]
+1

**Comment by BitBrit** [comment]
I'm doing:

`moment.duration('PT5S').humanize();`

And I would like it to say: '5 seconds' but instead it says 'a few seconds'.  When can we add this support?

**Comment by talkingnews** [comment]
+1

**Comment by srowhani** [comment]
Here's a small utility function based on @cogwirrel's that doesn't use lodash

```
import { pluralize } from '...'

export function humanize (duration) {
  const durationComponents = [
    { value: duration.years(), unit: 'year' },
    { value: duration.months(), unit: 'month' },
    { value: duration.days(), unit: 'day' },
    { value: duration.hours(), unit: 'hour' },
    { value: duration.minutes(), unit: 'minute' },
    { value: duration.seconds(), unit: 'second' },
    { value: duration.milliseconds(), unit: 'millisecond' }
  ]
  return durationComponents
    .filter(({ value }) => value !== 0)
    .slice(0, 3)
    .map(({ unit, value }) => pluralize(value, unit))
    .join(', ')
}
```

**Comment by tomkiss** [comment]
+1

(I'd argue that if you're going to have a humanize() method, then converting "1.51 hours" to "2 hours" is not particularly human-y).

**Comment by LazyCompiler** [comment]
+1 😞 
Other libraries does not support such a big variety of languages like Moment.js does. Please reconsider!

**Comment by xinthose** [comment]
+1

**Comment by nixxholas** [comment]
+1

**Comment by morfair** [comment]
+1

**Comment by stychu** [comment]
+1 

P.S. unbelievable it's not yet implemented ;(

**Comment by Tyguy7** [comment]
+1 really, this still isn't here?!

**Comment by inca** [comment]
I'm finally unsubscribing (it's been roughly 7 years already, but I think I finally had it with all those +1s)

**Comment by schnetzi** [comment]
I still don't understand why this is not implemented yet. The alternative given with a plugin which wasn't updated in over 2 years (moment-precise-range) is only partly helpful.
In my case I need the translations which moment already has but when using the plugin I have to translate everything by myself.

**Comment by schnetzi** [comment]
I found a package which solves my problems 🎉 
https://github.com/EvanHahn/HumanizeDuration.js

Maybe it is useful for anyone else as well.

**Comment by kanikag** [comment]
Would be nice to have this fixed.

**Comment by pavelzubov** [comment]
+1

**Comment by denmasyarikin** [comment]
+1

**Comment by dmacompton** [comment]
+1

**Comment by cassiebrooks** [comment]
+1

**Comment by koenig-dominik** [comment]
My take on that problem:
```typescript
const units: Array<{unit: moment.unitOfTime.Base, key: moment.RelativeTimeKey}> = [
  {unit: 'y', key: 'yy'},
  {unit: 'M', key: 'MM'},
  {unit: 'd', key: 'dd'},
  {unit: 'h', key: 'hh'},
  {unit: 'm', key: 'mm'},
  {unit: 's', key: 'ss'},
];
function accurateHumanize(duration: moment.Duration, accuracy: number = 2): string {
  let beginFilter = false;
  let componentCount = 0;

  return units
    .map(({unit, key}) => ({value: duration.get(unit), key}))
    .filter(({value, key}) => {
      if (beginFilter === false) {
        if (value === 0) {
          return false;
        }
        beginFilter = true;
      }
      componentCount++;
      return value !== 0 && componentCount <= accuracy;
    })
    .map(({value, key}) => moment.localeData().relativeTime(value, true, key, true))
    .join(', ');
}
```

**Comment by mirague** [comment]
This makes a lot of sense, would love to see a precise formatting of a duration.

**Comment by iShotFT** [comment]
Would love the option to humanize without rounding
+1

**Comment by HendrikPetertje** [comment]
+1 on this

**Comment by yojona** [comment]
+ 1

**Comment by alzaabi98** [comment]
+1

**Comment by nathan818fr** [comment]
+1

**Comment by hossam-magdy** [comment]
+1

**Comment by hossam-magdy** [comment]
Just in case anyone lands here after googling, this config/workaround was sufficient in my case:

```js
moment.relativeTimeRounding((t) => {
  const DIGITS = 2; // like: 2.56 minutes
  return Math.round(t * Math.pow(10, DIGITS)) / Math.pow(10, DIGITS);
});
moment.relativeTimeThreshold('y', 365);
moment.relativeTimeThreshold('M', 12);
moment.relativeTimeThreshold('w', 4);
moment.relativeTimeThreshold('d', 31);
moment.relativeTimeThreshold('h', 24);
moment.relativeTimeThreshold('m', 60);
moment.relativeTimeThreshold('s', 60);
moment.relativeTimeThreshold('ss', 0);

console.log(moment.duration(89, 's'));
// Output: "1.48 minutes"
// … without configuring the moment.relative*(), output was: "a minute"
```

because accuracy in my particular use case is much more important than a nice looking text.

Ans this is a comparison before and after configuring/invoking `moment.relative*()` methods:

| duration  | before          | after          |
| --------- | --------------- | -------------- |
| `3s`      | `a few seconds` | `3 seconds`    |
| `44s`     | `a few seconds` | `44 seconds`   |
| `45s`     | `a minute`      | `45 seconds`   |
| `1m 29s`  | `a minute`      | `1.48 minutes` |
| `1m 30s`  | `2 minutes`     | `1.5 minutes`  |
| `1m 59s`  | `2 minutes`     | `1.98 minutes` |
| `44m`     | `44 minutes`    | `44 minutes`   |
| `45m`     | `an hour`       | `45 minutes`   |
| `1h 29m`  | `an hour`       | `1.48 hours`   |
| `1h 30m`  | `2 hours`       | `1.5 hours`    |
| `21h`     | `21 hours`      | `21 hours`     |
| `22h`     | `a day`         | `22 hours`     |
| `35h`     | `a day`         | `35 hours`     |
| `35h 30m` | `a day`         | `35.5 hours`   |
| `36h`     | `2 days`        | `36 hours`     |

**Comment by Gredys** [comment]
Holy cow... That's still not fixed!? ._.

**Comment by digitaltoast** [comment]
@Gredys - and it won't be! As per the README for "moment":
> Moment.js is a legacy project, now in maintenance mode. In most cases, you should choose a different library.

I now use dayjs + https://www.npmjs.com/package/humanize-duration which works well for me

**Comment by Gredys** [comment]
@digitaltoast thats the reasion why I am not going to use anymore in my projects. (yeah, using same bundles as u)

**Comment by divyanshrws** [comment]
This should be included in the moment library instead of giving it as a separate plugin

**Comment by satarovbekzhan** [comment]
Let our grandsons do the implement this feature
