### ISSUE TITLE
Parsing AM/PM Broken

### ISSUE THREAD

**Issue by tracker1** [moment/moment#3480]
**Description of the Issue and Steps to Reproduce:**

    moment('12/30/1975 12:59 PM','MM/dd/YYYY hh:mm A').toString()
    // Invalid Date

*Please include the values of all variables used.*

**Environment:**

Chrome 53, Windows 10 Pro

```
> moment.version
"2.15.1"
> moment('12/30/1975 12:59','MM/dd/YYYY HH:mm').toString()
"Mon Dec 01 1975 12:59:00 GMT-0700"
> moment('12/30/1975 12:59 PM','MM/dd/YYYY hh:mm A').toString()
"Invalid date"
```

**Comment by maggiepint** [comment]
You need uppercase D.

```js
moment('12/30/1975 12:59 PM','MM/DD/YYYY hh:mm A').toString()
"Tue Dec 30 1975 12:59:00 GMT-0800"
```
