### ISSUE TITLE
Duration typing not accepting string

### ISSUE THREAD

**Issue by adambuczynski** [moment/moment#3482]
```
const period = 'week';
const date = moment().startOf(period);
```

`Argument of type 'string' is not assignable to parameter of type "year" | "years" | "Y" | "quarter" ....`

How to bypass this limitation? `const date = moment().startOf('week');` doesn't bark.

**Comment by mj1856** [comment]
Define your `period` type as a `UnitOfTime`.

    const period : UnitOfTime = 'week';
    const date = moment().startOf(period);

**Comment by adambuczynski** [comment]
@mj1856 thanks, is `UnitOfTime` exported from moment?

**Comment by mj1856** [comment]
Hmmm..  I think you just import `moment` then qualify the type with the namespace.  Try this:

```typescript
const period: moment.UnitOfTime = 'week';
```

**Comment by adambuczynski** [comment]
I've resorted to using it as such, which seems to work:

```js
import * as moment from 'moment';
import { UnitOfTime } from 'moment';
```

**Comment by mj1856** [comment]
I think either approach would work, if I'm understanding typescript imports correctly.

**Comment by chat-du-cheshire** [comment]
import * as moment from 'moment';

let type : moment.UnitOfTime = "week";

Namespace 'moment' has no exported member 'UnitOfTime'.

**Comment by ovangle** [comment]
Urgh... The actual type you want is `moment.unitOfTime.StartOf`. `unitOfTime` is a namespace for some unknown reason.

```typescript
let type: moment.unitOfTime.StartOf = week;
moment().startOf(type);
```

As far as importing in typescript, you can import types _only_ using the `import {<identifiers>} from 'moment'` syntax, but moment declares itself as a default export, so you can't use that syntax for importing values, so 

So the following will type check fine:

```typescript
import moment from 'moment';
import {unitOfTime} from 'moment';

let period: string;
moment().startOf(period as unitOfTime.StartOf);
```

**Comment by chat-du-cheshire** [comment]
Oh, thank you!
