### ISSUE TITLE
moment diff and subtract in one equation is giving unpredictable results.

### ISSUE THREAD

**Issue by tvsudhir3** [moment/moment#3484]
**Description of the Issue and Steps to Reproduce:**
We have the below line of code to calculate 31 (as of today):
Math.ceil(moment().diff(moment().subtract(2, 'months'), 'days') / 2)
It gives 30 sometimes and 31 sometimes. Absolutely unpredictable.
I could see consistency with below code.
moment()
Math.ceil(moment().diff(moment().subtract(2, 'months'), 'days') / 2)
So calling moment() once, just before problematic code, kind of resolved my issue so there is some unpredictable nature.
Please look into it.

*Please include the values of all variables used.*

**Environment:**
OS: Ubuntu 16.04 LTS, Chrome: 52.0.2743.116 (64-bit), Node: 6.3.1

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
Los Angeles Timezone
* The time and date at which the code was run
Run the code between Oct/4/2016, 11:30 -- Oct/4/2016, 13:00
* Other libraries in use (TypeScript, Immutable.js, etc)
Mocha

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
Tue Oct 04 2016 13:09:57 GMT-0700 (PDT)

console.log((new Date()).toLocaleString())
10/4/2016, 1:09:57 PM

console.log( (new Date()).getTimezoneOffset())
420

#console.log( navigator.userAgent)

console.log(moment.version)
2.14.1

```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*
I do believe that issue is within moment library.

**Comment by mjf-chi** [comment]
Also running into the same error on Mac OS X 10.11.6, Node 6.2.2, Moment 2.14.1. Adding moment() to the line above also fixed it for me.

**Comment by tvsudhir3** [comment]
I could reproduce this issue in the latest version of moment i.e. 2.15.1

**Comment by tvsudhir3** [comment]
I think, I pressed the trigger little early.
A small brain-storm session with my colleagues revealed the solution to be:
now = moment()
Math.ceil(moment(now).diff(moment(now).subtract(2, 'months'), 'days') / 2)

Closing this bug. 
If you have invested anytime into this then thanks a lot.
