### ISSUE TITLE
Strict parsing on valid strings in "ar" and "ar-ly" locales results in an invalid date

### ISSUE THREAD

**Issue by FrankManns** [moment/moment#3487]
**Description of the Issue and Steps to Reproduce:**

When I try to parse a valid string using `utc` with strict parsing and an `ar` or `ar-ly` locale, the resulting `moment` is invalid.

I created a [jsfiddle](https://jsfiddle.net/wLuq5eg2/1/) which shows it working with various locales like `en` and `ar-sa` but not working with `ar` or `ar-ly`. I've also included a small code snippet.

My thought is that these locales include [Right-to-Left marks](https://en.wikipedia.org/wiki/Right-to-left_mark) which could be throwing off the parsing.

``` js
const m = moment().locale('ar');
const formattedDate = m.format('l');
console.log(moment.utc(formattedDate, 'l', 'ar', false).toISOString()); // Valid date
console.log(moment.utc(formattedDate, 'l', 'ar', true).toISOString());  // Invalid date
```

**Environment:**
- Chrome 53.0.2785.143 (64-bit) on OSX
- Firefox 49.0 on OSX

**Other information that may be helpful:**

``` js
console.log((new Date()).toString()) // Fri Oct 07 2016 11:17:44 GMT-0400 (EDT)
console.log((new Date()).toLocaleString()) // 10/7/2016, 11:17:44 AM
console.log((new Date()).getTimezoneOffset()) // 240
console.log(navigator.userAgent) // Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
console.log(moment.version) // 2.15.1
```

**Comment by icambron** [comment]
I agree with your diagnosis:

```js
> moment.utc(formattedDate, 'l', 'ar', true).parsingFlags().unusedTokens[0].charCodeAt(0)
8207
```

Where 8207 is the RTL mark. So somehow the parser isn't matching those.

**Comment by marwahaha** [comment]
related to https://github.com/moment/moment/issues/2867
