### ISSUE TITLE
Proposal: Human durations

### ISSUE THREAD

**Issue by doodadjs** [moment/moment#3489]
**Description of the Issue and Steps to Reproduce:**

That will be great if we could parse human sentences to represent a positive or negative Duration object.

By example :
"1 year 2 days"
"2 years 5 weeks 1 day less"
"1 hour 30 minutes more"
"10 days 5 hours less"
....

I suggest : moment.duration.human("...")

**Please include the values of all variables used.**
N/A

**Environment:**
All

**Other information that may be helpful:**
Should be localized

**The time zone setting of the machine the code is running on**
N/A

**The time and date at which the code was run**
N/A

**Other libraries in use (TypeScript, Immutable.js, etc)**
N/A

EDIT: Changed "after" and "before" to "more" and "less"

**Comment by alisd23** [comment]
Something like this: https://github.com/philbooth/vagueTime.js?

**Comment by maggiepint** [comment]
This is basically asking for natural language processing, and that's really outside of the scope of moment. We've discussed this before, and it's not something we can reasonably implement.
