### ISSUE TITLE
Unimplemented weeks() method on localeData() object

### ISSUE THREAD

**Issue by jeserkin** [moment/moment#3491]
**Description of the Issue:**
I was looking at the object returned by `localeData()` method, described here http://momentjs.com/docs/#/i18n/locale-data/ and seems there is inconsistency in description. On top there seems to be a method `weeks()`, but in more detailed description below, there is a method `localeData.week(aMoment);  // returns week-of-year of aMoment`, but no **weeks**.

**Comment by ichernev** [comment]
So do you need method weeks (what should it do) or you want to report the bug so we fix weeks to week in the list?

**Comment by jeserkin** [comment]
Second. Is think it is a typo or maybe old functionality, that wasn't refactored in the documentation. I think changing to week would suffice. Maybe issue title a bit misleading.

**Comment by kevinzwhuang** [comment]
Can confirm there is no `weeks()` method functionality with this jsFiddle: https://jsfiddle.net/uznmzu3k/

The correct one is `week()` - I went ahead and opened https://github.com/moment/momentjs.com/pull/364 to address this

**Comment by maggiepint** [comment]
Docs PR merged
