### ISSUE TITLE
Unclear how to use custom data from extended locales

### ISSUE THREAD

**Issue by jeserkin** [moment/moment#3493]
**Description of the Issue:**
Took a peek at the [Customization](http://momentjs.com/docs/#/customization/) section. As far as I understand first part, it allows to set own locale properties to the existing ones, but it is unclear how to use them. Doesn't seems to be reachable through `moment.localeData()`. Thank you.

**Comment by mj1856** [comment]
You can update only the existing properties to different values.  You cannot add new properties.  Even if you could, moment wouldn't know what to do with them.

After updating existing properties, you just use them as you would as if they were not modified.  For example:

```js
moment.locale() // "en"

// before modification
moment().format("dddd")         // "Thursday"
moment.localeData().weekdays()  // ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

// modification
moment.updateLocale('en', {
    weekdays : ["Foo", "Bar", "Baz", "Qux", "Quux", "Corge", "Grault"]
});

// after modification
moment().format("dddd")         // "Quux"
moment.localeData().weekdays()  // ["Foo", "Bar", "Baz", "Qux", "Quux", "Corge", "Grault"]
```

**Comment by jeserkin** [comment]
I see. Thank you.
