### ISSUE TITLE
Update global moment object with custom date

### ISSUE THREAD

**Issue by dolftax** [moment/moment#3494]
Is there a way to update the moment object globally with custom time?

FYI, we pass the server time object to client when initiating the websocket connection.

**Comment by icambron** [comment]
Moment just uses the browser's built-in Date functionality. You can override that functionality directly and Moment will pick it up transparently. For example, you could:

 1. Take the time from the server
 2. Diff it with the browser's time
 3. Override Date to add that diff to current time

I don't know of any tools that can do that off-the-shelf, so you might have to do some hacking. There *are* tools that let you override the time and fiddle with it for testing purposes, like Sinon and Timekeeper. Maybe looking at those projects will point you in the right direction.

**Comment by dolftax** [comment]
@icambron Umm. The tricky part is changing/patching the global date object and not an instance.

**Comment by icambron** [comment]
By "global date object", you mean the Date prototype? And what do you mean by "not an instance"?

**Comment by maggiepint** [comment]
Do you just want to change the time moment "sees"? Look at the docs for moment.now - this is meant to be overridden for testing, but you could do all kinds of weird stuff with it. http://momentjs.com/docs/#/customization/now/

**Comment by dolftax** [comment]
@maggiepint Precisely what I wanted. :+1:

**Comment by dolftax** [comment]
@maggiepint Oops. Didn't help! @icambron My use case is, the client might have say actual time - 30 seconds. On connection, server emits the server time which should adjust the time in the client and continue to tick until the session is over.

**Comment by icambron** [comment]
Yeah, that's what I meant: you need to override the Date (either through plugging it into Moment as Maggie suggests or by overriding it for the whole browser) in a way that continues to tick. That why I was suggesting a sort of proxy time prototype that diffed the native time with the server time; that gives you a baseline from which you can subtract from the native time to get your server time + ticks.
