### ISSUE TITLE
Using moment.tz(date_string, timezone) constructor changes timezone

### ISSUE THREAD

**Issue by Kamilius** [moment/moment#3495]
**Description of the Issue and Steps to Reproduce:**
While parsing two date strings with same timezone specification, one of dates switches timezone.
We have two date strings:
`2016-10-12T12:00:00` and  `2016-07-14T12:00:00`, which are representing time in `'Pacific/Apia'` (+14).

I need to create two momentjs objects with those dates and a timezone:

```js
const timezone = 'Pacific/Apia';
let startDate = moment.tz('2016-07-14T12:00:00', timezone);
let endDate = moment.tz('2016-10-12T12:00:00', timezone);
```

After parsing, result of format as well as value of '_offset' property, I'm getting following results:
```js
startDate.format(); // "2016-07-14T12:00:00+13:00"
endDate.format(); // "2016-10-12T12:00:00+14:00"

startDate._offset; // 780
endDate._offset; // 840
```

As you can see, offset and a timezone in formatted string differs by one hour, which is totally blowing my mind. I've tried checking DST dates, it seems not to fall into those dates range.

Why this is happening and how to keep both values in same timezone?

**Environment:**

Chrome 53.0.2785.143 (64-bit), momentjs website's dev console.

Console.logs output:
```js
Wed Oct 12 2016 13:05:03 GMT+0300 (EEST)
10/12/2016, 1:05:03 PM
-180
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
2.10.6
```

**Comment by rajeevnaikte** [comment]
The difference is due to Day Light Saving effect.

**Comment by maggiepint** [comment]
This seems correct if you reference timeanddate.com (which should be quite accurate): https://www.timeanddate.com/time/zone/samoa/apia

This time zone is on DST September thru April. I think perhaps your confusion is that Samoa is in the southern hemisphere - July is Winter.

**Comment by jyywhw** [comment]
why I can't use moment.tz.

I use 2.18.1
