### ISSUE TITLE
Incorrect rounding when adding durations

### ISSUE THREAD

**Issue by jimothyhalpert7** [moment/moment#3497]
**Issue:**
Adding a duration of 10 and 15 minutes results in a duration of 24.999999999999996 minutes.

**Steps to reproduce:**

```
var minutesTen = moment.duration(10, 'minutes').asHours();
var minutesFifteen = moment.duration(15, 'minutes').asHours();
moment.duration(minutesTen + minutesFifteen, 'h').asMinutes();
// Expecting 25
// Actual result 24.999999999999996
```

**Environment:**

Chrome 53 on Windows 10

``` js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

->

```
Thu Oct 13 2016 10:40:04 GMT+0200 (W. Europe Daylight Time)
-120
Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
2.15.1
```

**Notes**
Suspecting that the issue is caused by:

```
0.25 + 0.16666666666666666
// expected: 0.41666666666666666
// actual: 0.41666666666666663
```

And then:

```
moment.duration(0.41666666666666663, 'h').asMinutes()
// result: 24.999999999999996
moment.duration(0.41666666666666666, 'h').asMinutes()
// result: 25
```

This heavily screws up the _duration formatter_ plugin:

```
moment.duration(minutesTen + minutesFifteen, 'h').format('hh:mm', {trim: false});
// expected: '00:25'
// actual: '00:24'
```

**Comment by mj1856** [comment]
Well, we can't fix how JS floating point numbers work.  But we could consider rounding durations to the nearest millisecond internally.  We don't really provide support for sub-millisecond timing in the API anyway.  @ichernev, does that sound reasonable?

**Comment by jimothyhalpert7** [comment]
We thought that rounding off the decimals to 4 decimal digits. But this issue now shows up in a more striking way:
```
moment.duration(0.08333333333333333, 'h').asMinutes()
// result: 5
moment.duration(0.0833333333333333, 'h').asMinutes()
// result: 4.999999999999998
```

**Comment by maggiepint** [comment]
I"m going to close this as it's marked troubleshooting. If you want to re-open with a clear feature request, that's fine.
