### ISSUE TITLE
Implement toLocaleTimeString from Date()

### ISSUE THREAD

**Issue by basiclines** [moment/moment#3499]
This is extremly useful when you don't want to manage winter/summer time and also you don't want to show the locla time of the user,

```js
var date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));

// formats below assume the local time zone of the locale;
// America/Los_Angeles for the US

// US English uses 12-hour time with AM/PM
console.log(date.toLocaleTimeString('en-US'));
// → "7:00:00 PM"

// British English uses 24-hour time without AM/PM
console.log(date.toLocaleTimeString('en-GB'));
// → "03:00:00"

// Korean uses 12-hour time with AM/PM
console.log(date.toLocaleTimeString('ko-KR'));
// → "오후 12:00:00"

// Arabic in most Arabic speaking countries uses real Arabic digits
console.log(date.toLocaleTimeString('ar-EG'));
// → "٧:٠٠:٠٠ م"

// when requesting a language that may not be supported, such as
// Balinese, include a fallback language, in this case Indonesian
console.log(date.toLocaleTimeString(['ban', 'id']));
// → "11.00.00"
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString

**Comment by mj1856** [comment]
Not sure what you're asking for here.  We already have similar functionality.  In many ways our API is more capable than `toLocale...` from the Intl spec.  This is covered heavily in the documentation.

**Comment by basiclines** [comment]
You're absolutely right. I'd misunderstood the behaviour of `toLocaleTimeString`.
What i was looking for is https://github.com/moment/moment-timezone
