### ISSUE TITLE
utcOffset is not a function in karma/jasmine tests

### ISSUE THREAD

**Issue by jankoprowski** [moment/moment#3511]
**Description of the Issue and Steps to Reproduce:**

- Write simple function
```js
'use strict';
function foobar() {
 console.log(moment.parseZone("2013-01-01T00:00:00-13:00").utcOffset);
}
```
- Write test calling this function in jasmine/karma
```js
'use strict';
describe('foobar', function() {
    it('should log a function', function() {
        foobar();
    });
});
```
- Run test
- Test returns log 'undefined'

For some reason in karma/jasmine utcOffset function is not set. Is anyone can explain me why?
In web browser everything works fine.

**Comment by icambron** [comment]
My guess is that you're loading an old version of Moment that doesn't have that function. Can you log `moment.version` and confirm it's > [2.9.0](http://momentjs.com/docs/#/manipulating/utc-offset/)?

**Comment by jankoprowski** [comment]
You are right. For some reason in tests we are using moment in version 2.8.1. Issue resolved! Thanks a lot! I must to investigate it.
