### ISSUE TITLE
isDST() not working for years after 2038

### ISSUE THREAD

**Issue by HiMyNameIsIlNano** [moment/moment#3512]
**Description of the Issue and Steps to Reproduce:**
When we try to perform the following tests: 

```
var date_no_dst = moment("2039-01-01").tz("Europe/Berlin");
undefined
date_no_dst.isDST();
false
var date_dst = moment("2039-06-01").tz("Europe/Berlin");
undefined
date_dst.isDST();
false
var date_dst_2036 = moment("2036-06-01").tz("Europe/Berlin");
undefined
var date_no_dst_2036 = moment("2036-01-01").tz("Europe/Berlin");
undefined
date_dst_2036.isDST();
true
date_no_dst_2036.isDST();
false
```
we get inconsistent results. In our application we are relying on the isDST function to localize timeslices and provide the correct values to our users. When one of our users is accessing data with a timeslice grater than 2038, our localization fails.

Other tests:
expected value(s): 01.10.2186 06:00 - 01.10.2187 06:00 
actual result(s): 01.10.2186 04:00 - 01.10.2187 04:00 (the method _isDST()_ returns false even if October is still DST in Germany)

**Environment:**
Test System
Chrome Version 53.0.2785.143 m (64-bit), Windows 7 64-bit

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on:
UTC+01:00 Brussels, Copenhagen, Madrid, Paris
* The time and date at which the code was run:
19/10/2016 @12:55
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
Wed Oct 19 2016 12:55:58 GMT+0200 (Central Europe Daylight Time)
undefined

console.log((new Date()).toLocaleString())
19.10.2016, 12:56:22
undefined

console.log( (new Date()).getTimezoneOffset())
-120
undefined

console.log( navigator.userAgent)
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
undefined

console.log(moment.version)
2.9.0
undefined
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by icambron** [comment]
This needs to go in the [moment-timezone](https://github.com/moment/moment-timezone) repo.

**Comment by HiMyNameIsIlNano** [comment]
moved to [moment-timezone](https://github.com/moment/moment-timezone/issues).

Thanks,
Daniele.

**Comment by jyywhw** [comment]
why not make moment-timezone in moment?
