### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by JamesJGoodwin** [moment/moment#3516]
**Description of the Issue and Steps to Reproduce:**

I've just downloaded moment-with-locales.js from the site, and already got this error. Also, i can't initialize the script:

`Uncaught ReferenceError: moment is not defined(…)`

**Environment:**

Chrome 54 on Ubuntu 16.04.1

**Other information that may be helpful:**

jQuery 3.1.1

**Comment by icambron** [comment]
Works for me, albeit on OSX. My guess is that Chrome decided to interpret the file as ASCII instead of as UTF-8. Are you loading it from a server and if so do the headers specify UTF-8?  You can also try this:

```js
<script src="moment-with-locales.js" charset="UTF-8"></script>
```

**Comment by icambron** [comment]
Closing for age.
