### ISSUE TITLE
Calling moment([Date]) returns different results than moment([Date], ["MM/DD/YYYY"], false)

### ISSUE THREAD

**Issue by opusrocks** [moment/moment#3529]
If you pass a Date to the moment constructor, but also pass a format string, the resulting moment instance does not represent the correct date. 

Using v 2.15.2:
var d= new Date("2/1/2016");
var m = moment(d);
console.log(m.format());
// 2016-02-01T00:00:00-08:00
var m = moment(d, ["MM/DD/YYYY"], false);
console.log(m.format());
// 2016-01-20T00:00:00-08:00

I traced the issue to the prepareConfig function:

 function prepareConfig (config) {
       ...
        } else if (isArray(format)) {
            configFromStringAndArray(config);
        } else if (isDate(input)) {
            config._d = input;
...
}

It seems to me that the isDate() check should precede the isArray(format) check.

**Comment by johncrisostomo** [comment]
You were right, I already submitted a pull request.

**Comment by maggiepint** [comment]
closed #3530
