### ISSUE TITLE
Multiple locales always end up in last imported one

### ISSUE THREAD

**Issue by peterpeterparker** [moment/moment#3535]
Hey,

I'm using the last version of moment, 2.15.2, with Ionic 2 RC.1

When I import many locales, like following:

    import moment from 'moment';
    import 'moment/src/locale/fr';
    import 'moment/src/locale/de';
    import 'moment/src/locale/it';

Settings the locales to moment will actually have no effect, I will always end up using the last imported locales. For example if I set french like following:

    moment().locale('fr');

=> I will still have the locales set in italian. (like for pattern 'MMMM YYYY' my app will display 'OTTOBRE 2016' instead of 'OCTOBRE 2016')

I my example, if I remove the italian import, I will end up in german, etc.

Do I do something wrong or is that a bug?

Thx in advance for your feedback.

**Comment by Alx101** [comment]
I noticed this as well. The problem can be solved by setting the global moment locale instead of the local one.
Using moment().locale('en') sets the local moment instance to english,
but on the other hand setting the locale using the global way: moment.locale('en') set my whole app to using english, despite the import setting it. 

Info on it can be found on the moment website: [http://momentjs.com/docs/#/i18n/](http://momentjs.com/docs/#/i18n/)

**Comment by peterpeterparker** [comment]
the solution of @Alx101 totally works for me and resolved my issue.

So instead of 

    moment().locale('fr');

I do

   moment.locale('fr');

Furthermore, it's important to process these configuration before using moment (sounds silly but you never know. In my case I added this initialization in app.component.ts of my Ionic2 project).

thx @Alx101 for the solution

**Comment by zefrench** [comment]
Finally I found someone using moment with Ionic2 rc1 !
Could you tell me how exactly you add moment in your app ?
 
I would appreciate your help cos I'm struggle with this.

**Comment by peterpeterparker** [comment]
@zefrench:

Install momentjs

    sudo npm install moment --save

Install typescript definition for momentjs

    sudo npm install --save-dev @types/moment

To import moment in one of your typescript class do like following

    import moment from 'moment';

Example of use

    moment(new Date()).format('LLL');
    moment(new Date()).add(5, 'd').toDate();

**Comment by zefrench** [comment]
@peterpeterparker 
Super. I'm going to try and I'll tell you. 
Have a good morning.

**Comment by zefrench** [comment]
@peterpeterparker 
When I installed the @types/moment I got this message : 
npm WARN deprecated @types/moment@2.13.0: This is a stub types definition for Moment (https://github.com/moment/moment). Moment provides its own type definitions, so you don't need @types/moment installed!
ionic-hello-world@ /Users/ophelia/Downloads/abondanceRC0
└── @types/moment@2.13.0 

So maybe  I have to uninstall it ??

**Comment by peterpeterparker** [comment]
@zefrench it's a warning to tell you that you don't need to install the type definitions coz it's already included in momentjs modules. so yep maybe it works without the types definition. try to remove them, if it works fine, if it didn't ignore the warning

**Comment by zefrench** [comment]
I think I have a problem...
When I try this : 
var momentdate = moment(new Date()).format('LLL');
    console.log(momentdate);

I get nothing in the console.
But if I try : 
var momentdate = moment(new Date());
    console.log(momentdate);
I get something as proof moment is installed correctly : 
Moment {_isAMomentObject: true, _i: Sun Nov 13 2016 04:47:03 GMT-0600 (CST), _isUTC: false, _pf: Object, _locale: Locale, …}

**Comment by peterpeterparker** [comment]
First, you should maybe open an issue on the https://forum.ionicframework.com because your questions are not related to that issue

Then I don't know the same piece of code works fine for me. Maybe once you have opened the issue on the forum, if possible, show a little bit more of your codes.

You could write down here the link to your post on the forum, I gonna follow it

**Comment by zefrench** [comment]
It seems I finally get it work !

Thanks for your nice Help !

Have a good day !

**Comment by zefrench** [comment]
@peterpeterparker Are you able to use Moment pipe directly in your ionic view ??
It seems the pipe are not installed...

**Comment by peterpeterparker** [comment]
@zefrench  you have to create your own pipe

**Comment by zefrench** [comment]
Really to complicate for me...
I thought the pipe like amTImeAgo will work out of the box.

**Comment by peterpeterparker** [comment]
Again, it's not related to that issue, use the Ionic Forum!

For example there I posted an example of what you are looking for

https://forum.ionicframework.com/t/solved-currency-pipe-in-ionic2/63571/15?u=reedrichards

**Comment by Alx101** [comment]
@zefrench If you want pipes you need to use a different library that has them. I'm using this one https://github.com/urish/angular2-moment

**Comment by zefrench** [comment]
Thanks Alex ! (My name is Alex too..)
