### ISSUE TITLE
moment won't parse some month in french

### ISSUE THREAD

**Issue by l1br3** [moment/moment#3536]
**Description of the Issue and Steps to Reproduce:**
moment won't parse some month in french

*Please include the values of all variables used.*
Paste the code in runkit

```javascript
var moment = require("moment")
moment.locale('fr')


// Working parsing
var janvier = moment('12 janvier')
var mars = moment('12 mars')
var septembre = moment('12 septembre')
var octobre = moment('12 octobre')
var novembre = moment('12 novembre')

console.log(janvier._d)
console.log(mars._d)
console.log(septembre._d)
console.log(octobre._d)
console.log(novembre._d)


// Not working parsing
var avril = moment('12 avril')
var mai = moment('12 mai')
var juin = moment('12 juin')
var juillet = moment('12 juillet')


var décembre = moment('12 décembre');
var decembre = moment('12 decembre');

var août = moment('12 août');
var aout = moment('12 aout');

var février = moment('12 février');
var fevrier = moment('12 fevrier');

console.log(avril._d)
console.log(mai._d)
console.log(juin._d)
console.log(juillet._d)

console.log(décembre._d)
console.log(decembre._d)
console.log(août._d)
console.log(aout._d)
console.log(février._d)
console.log(fevrier._d)

```

**Environment:**
In chrome/chromium/canari on windows 7 and Debian8.
In runkit also => https://runkit.com/npm/moment

**Comment by mj1856** [comment]
1. You should not attempt to parse date/time strings in non-ISO formats without a format specifier.
2. Never evaluate `_d`, or any other properties beginning with underscore.  Those are internal.  Use the public API functions like `.format()`, and others.
3. Accents *are* required in order for month names to be properly recognized.

```
moment('12 décembre', 'D MMMM').isValid() // true
moment('12 décembre', 'D MMMM').format() // "2016-12-12T00:00:00-08:00"
```

**Comment by l1br3** [comment]
Thanks for your answer, my main issue is that I need to guess the format and this is why I did not give a format.
I don't use _d in the app, it was only for debug in runkit.

**Comment by Clovis-Portron** [comment]
Hi @l1br3, did you fix your issue ? 
It seems I have the same (for février for example), and I dont achieve to fix it :/
