### ISSUE TITLE
Can't find a difference between two dates

### ISSUE THREAD

**Issue by JamesJGoodwin** [moment/moment#3537]
Hi. I'm trying to find a difference between two dates. First off all, i'm parsing a unix timestamp date, then converting it to normal date and try to compare today's date and parsed date with `.diff()` function, but console says that diff() is not a function. I almost break my mind with this function. Why it doesn't working? 

```
$(function unixToDays() {
	var today = moment().format("YYYY, MM, DD");
	$('.card.offer').each(function(i) {
		var unixDate = $(this).find('span#days-count').text();
		var time = moment.unix(unixDate).format("YYYY, MM, DD");
		var difference = time.diff(today, 'days');
		console.log(difference);
		//$(this).find('#days-count').text(dateString);
	});
});
```

**Comment by mj1856** [comment]
Your `time` variable is a `string`, and you're treating it like it's a `moment` object.  You probably don't want to call the `format` function there.

Really, you don't want to call the format function at all, even on your `today` variable.
