### ISSUE TITLE
Moment timez changes once output to server in another location.

### ISSUE THREAD

**Issue by Markj89** [moment/moment#3539]
I've been working on a travel form for a few months now and I've had this issue regarding times being sent correctly. 
I'm using a Angular DateTimePicker which sends all times through JSON and into our CRM, (Which is in different states). The dates come back correct, however, the time values are about 4 hours off.

Now originally, I used add() but if I want users from other parts of the country to be able to add their time without the server messing with the value, how can I configure the value to post the date without changing it due to whatever timezone it's in.

I'm currently using require + Angular + moment +moment-timezones

```
angular.forEach(stopData, function(value, index) {
                var departDate = moment.parseZone(stopData[index]['depart_date'], "MM/DD/YYYY hh:mmaZ").utcOffset(tzone).format();
                var arriveDate = moment.parseZone(stopData[index]['arrive_date'], "MM/DD/YYYY hh:mmaZ").utcOffset(tzone).format();

                stopData[index]['depart_date'] = departDate;
                stopData[index]['arrive_date'] = arriveDate;
            });
```

**Comment by mj1856** [comment]
Sorry, I'm not sure what you're asking.  You say you are using moment-timezone, but you also show adjustment using the `utcOffset` function.  What is in your input data?  What is in your `tzone` variable?  What did you expect and what did you actually get?

Perhaps you could create a JSFiddle or other minimal example to demonstrate?

**Comment by ayelet-indegy** [comment]
@Markj89 
Hi i'm experiencing the same problem, my server is on time zone +00:00
and the client is in a different timezone (any time zone for that matter).
and when I convert the string (with time zone +00:00 in the end) the moment service will add the time zone offset of the client

**Comment by maggiepint** [comment]
@ayelet-indegy you're probably using the `moment()` factory function when you need a different one: https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/

**Comment by Markj89** [comment]
`var tzone = theDate.getTimezoneOffset();
`

I can make a jsfiddle, but I'm not sure how that will help since the data is passed to the server. 
That is when the time is altered.

**Comment by Markj89** [comment]
@maggiepint I've read your article before and tried this method, but I keep getting the same result. 
I uploaded two images regarding my input field and how it output on my company's CRM. The issue is because we different servers across the country and so the data is passed back and forth to several of them. 

I'm thinking my best option now is to find some work around in PHP before it submits to cURL.

![screen shot 2016-11-03 at 2 10 32 pm](https://cloud.githubusercontent.com/assets/3435026/19981310/71e9b784-a1cf-11e6-80ea-16fb10a21d5a.png)
![screen shot 2016-11-03 at 2 10 45 pm](https://cloud.githubusercontent.com/assets/3435026/19981309/71e8fc9a-a1cf-11e6-9d67-a4cb2778a3ad.png)

**Comment by maggiepint** [comment]
What's the exact format of the data you are passing into moment? If you are passing the data in in this format, without specifying a format string, then it's probably being parsed wrong.

**Comment by Markj89** [comment]
@maggiepint I'm using [Kendo Datetimepicker](http://demos.telerik.com/kendo-ui/datetimepicker/index) 

On the front-end, I format it like so

` var dateValue = new Date();
        var dateToString = moment.utc(dateValue, "MM/DD/YYYY hh:mma").add(1, 'days').format();
        var regularDateToString = moment.utc(dateValue, "MM/DD/YYYY").add(1, 'days').format();

        $scope.dateTimePickerOptions = {
          format: "MM/dd/yyyy hh:mmtt",
          timeFormat: "hh:mmtt",
          parseFormats: [dateToString],
          min: dateToString,
          interval: 15
        };`

And since these are dynamic fields I use angular.foreach to parse it 
`angular.forEach(stopData, function(value, index) {
                var departDate = moment.parseZone(stopData[index]['depart_date'], "MM/DD/YYYY hh:mma").format();
                var arriveDate = moment.parseZone(stopData[index]['arrive_date'], "MM/DD/YYYY hh:mma").format();

                stopData[index]['depart_date'] = departDate;
                stopData[index]['arrive_date'] = arriveDate;
            });`

Once I use JSON.stringify and pass it over to PHP, I get this in my console
`2016-11-27T18:15:00Z`

**Comment by Markj89** [comment]
I may have solved the issue, I added "LLL" and the UTC "Z" to the parsed value.
