### ISSUE TITLE
Fails to parse date with short time

### ISSUE THREAD

**Issue by dimalu85** [moment/moment#3541]
I've got error on parsing moment("2016-10-28 5:33:38") in IE10 with 2.8.3 version. So I've tried new version in jsfiddle and result is incorrect.

moment("2016-10-28 5:33:38") - Fri Oct 28 2016 00:00:00 GMT+0300 (Russia Standard Time)
moment("2016-10-28 05:33:38") - Fri Oct 28 2016 05:33:38 GMT+0300 (Russia Standard Time)

https://jsfiddle.net/dimalu85/etzwaet9/
Windows 10, IE10, Chrome 53.0.2785.143

log output:

Fri Oct 28 2016 13:17:14 GMT+0300 (Russia Standard Time)
VM345:53 28.10.2016, 13:17:14
(index):54 -180
(index):55 Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
(index):56 2.15.2

2016-10-28 5:33:38 - Fri Oct 28 2016 00:00:00 GMT+0300 (Беларусь (зима))
2016-10-28 05:33:38 - Fri Oct 28 2016 05:33:38 GMT+0300 (Беларусь (зима))
Fri Oct 28 2016 13:18:32 GMT+0300 (Беларусь (зима))
‎28‎.‎10‎.‎2016‎ ‎13‎:‎18‎:‎32
-180
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; ASU2JS; rv:11.0) like Gecko
2.15.2

**Comment by butterflyhug** [comment]
Right.  ISO 8601 formats require the leading zero, so this is falling through to Chrome's Date parser.  I'm afraid we can't take responsibility for Chrome's code.

**Comment by dimalu85** [comment]
But you have an example on docs page http://momentjs.com/docs/#/parsing/ under topic "Hour, minute, second, millisecond, and offset tokens":
> moment("2010-10-20 4:30",       "YYYY-MM-DD HH:mm");   // parsed as 4:30 local time
> moment("2010-10-20 4:30 +0000", "YYYY-MM-DD HH:mm Z"); // parsed as 4:30 UTC

But there we have format parameter. So I hope to parse short time without specifying format.

Also this issue happened both for IE and Chrome.

**Comment by maggiepint** [comment]
Right, you can't parse without a format unless you have an ISO8601 format string. The behavior is not supported.
