### ISSUE TITLE
Diff error when creating date with format

### ISSUE THREAD

**Issue by tikoflano** [moment/moment#3542]
When creating a date using a non ISO format, the diff function returns weird results (it seems like it is ignoring the minutes of the date).

- 26/10/2016 14:19:46 - 26/10/2016 14:19:37 = 9 seconds
- 26/10/2016 14:08:50 - 26/10/2016 14:08:39 = 11 seconds
- 26/10/2016 14:07:00 - 26/10/2016 14:06:49 = -49 seconds
- 26/10/2016 13:48:07 - 26/10/2016 13:47:43 = -36 seconds
- 26/10/2016 13:58:07 - 26/10/2016 13:47:43 = -36 seconds

Here is a [jsFiddle ](https://jsfiddle.net/tikoflano/8m7dgny3/2/)where you can check the issue:

```
var dates = [
    {start: '26/10/2016 14:19:37', end: '26/10/2016 14:19:46'},
    {start: '26/10/2016 14:08:39', end: '26/10/2016 14:08:50'},
    {start: '26/10/2016 14:06:49', end: '26/10/2016 14:07:00'},
    {start: '26/10/2016 13:47:43', end: '26/10/2016 13:48:07'},
    {start: '26/10/2016 13:47:43', end: '26/10/2016 13:58:07'}
];

for(let i = 0, len = dates.length; i < len; i++){
	let start = moment(dates[i].start, 'DD/MM/YYYY H:i:s');
  let end = moment(dates[i].end, 'DD/MM/YYYY H:i:s');
  let diff = end.diff(start, 'seconds');
  
  document.body.innerHTML += '<div>'+end._i+' - '+start._i+' = '+diff+' seconds </div><br>';
}

document.body.innerHTML += '<hr>';

dates = [
    {start: '2016-10-25 14:19:37', end: '2016-10-25 14:19:46'},
    {start: '2016-10-25 14:08:39', end: '2016-10-25 14:08:50'},
    {start: '2016-10-25 14:06:49', end: '2016-10-25 14:07:00'},
    {start: '2016-10-25 13:47:43', end: '2016-10-25 13:48:07'},
    {start: '2016-10-25 13:47:43', end: '2016-10-25 13:58:07'}
];

for(let i = 0, len = dates.length; i < len; i++){
	let start = moment(dates[i].start);
  let end = moment(dates[i].end);
  let diff = end.diff(start, 'seconds');
  
  document.body.innerHTML += '<div>'+end._i+' - '+start._i+' = '+diff+' seconds </div><br>';
}
```
I'm using Chrome 54 on Widnows 10 

Next is the output of:

```
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

- Fri Oct 28 2016 11:02:55 GMT-0300 (Hora verano Sudamérica Pacífico)
- 28/10/2016 11:02:55
- 180
- Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
- 2.15.2

**Comment by maggiepint** [comment]
You need a different format string. `i` is not a moment token. The format you are using would properly be coded as `DD/MM/YYYY HH:mm:ss`.

Also of note - any variable prefixed with `_` is private and should not be used in your code. `_i` is in fact just the initial string passed to the parser. If you had used `.format()` instead, you would have seen that the minutes were in fact not parsing.
