### ISSUE TITLE
Intermixing time zones

### ISSUE THREAD

**Issue by rohdef** [moment/moment#3544]
**Description of the Issue and Steps to Reproduce:**
This should've been a fairly simple operation, but with intermixing time zones everything got blown up. The issue arises when having multiple time zones, those could come from localized calendar components or external services.

When I am only interested in the date (according to the timestamp), I want to neutralize the time (set it to 00:00) in a way that corresponds to the server where I store the data, let's say GMT, and the server stores nothing but the date (like many date database types does), just to intercept the argument with having time zones should solve it, because if there is no time zone only the date is left. So my approach was to do something along the lines of:

    var fixTimeZoneOffset = function(date) {
        var correctedDate = moment(date); // Overcome the nasty mutability... btw. what the f***? A mutable date component, really?
        correctedDate.hours(0).minutes(0);
        
        var timezoneOffset = moment.parseZone(correctedDate).utcOffset();
        correctedDate.add(timezoneOffset, "minutes");

        return correctedDate;
    };

If the date object is in the same time zone as the browser, this works fine: ```fixTimeZoneOffset(moment("2016-01-13T13:37:00"))```, sweet.  But what happens when I get a date that does not correspond? Let's say the browser is set to GMT+02 (either through timezone or just being the settings the browser is run with), and we pass the following: ```fixTimeZoneOffset(moment("2016-01-13T13:37:00-03:00"))```, then I would expect the hours(0).minutes(0) part to act relative to GMT-03, not GMT+02, however the resulting time after that step will be: "2016-01-12T19:00:00-03:00" or "2016-01-12T22:00:00Z". When correcting for the offset now the result will end up in "2016-01-12T22:00:00Z" in stead of the expected "2016-01-12T00:00:00Z".

For the love of sanity, could you please change hours, minutes etc. to operate of the time zone of the actual object? It is highly unexpected to have something defined with moment("[...]+XX:XX") operate in timezone "+YY:YY".

**Environment:**
Browsers, combined with external data. Tested with Firefox on Ubuntu, Chrome on Ubuntu, Edge Windows 10 and Internet Explorer Windows 10, behavior is identical
```

**Comment by maggiepint** [comment]
There is a lot to unpack here, but I think I'll just give you some resources.

Docs explaining the difference between timezone and offset:
http://momentjs.com/guides/#/lib-concepts/timezone-offset/

Docs explaining how to use parse zone, which would fix your problem: http://momentjs.com/guides/#/parsing/

Blog post explaining moment's factory functions, which will also show you how to parse while ignoring the time: https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/

Why moment isn't immutable, and our plan for getting it there: https://maggiepint.com/2016/07/16/immutability-its-happening/

**Comment by maggiepint** [comment]
Also, in the future, if you are swearing, even with *, on github issues, they will get closed without a response.

**Comment by rohdef** [comment]
Removed the swearing, will look at the links asap, thanks for those. Still doesn't change that the way to work around this became extremely complicated, I have been searching for hours to solve these issues.

**Comment by mj1856** [comment]
I think the links Maggie gave will answer your questions, but also in general recognize that adding or subtracting time to account for time zone is not going to work well.  If you need to adjust the offset from UTC, or work in a specific time zone, we have functions for that already.
