### ISSUE TITLE
Is this a bug? dateTime.month()?

### ISSUE THREAD

**Issue by spksoft** [moment/moment#3547]
When I try 'dateTime.month()' that should give me 10, it gives me 9 instead. So I don't know if I miss something or don't understand something clearly. Thank you in advance.

Code: 
![image](https://cloud.githubusercontent.com/assets/1377991/19832191/226428a6-9e47-11e6-8aff-fe6e79639d04.png)
Result: 
![image](https://cloud.githubusercontent.com/assets/1377991/19832192/30fe0b20-9e47-11e6-984b-c19a02602ce9.png)

**Comment by maggiepint** [comment]
This is the way javascript works. It is madness, but the months index from 0. So 9 is October. Moment mirrors the programming language.

**Comment by tandrewnichols** [comment]
Just because the people that wrote javascript got it wrong doesn't mean moment should. People use moment to get away from the annoying and inconsistent nature of the Date prototype. There's no conceivable reason the month should be 0-indexed. Personally, I consider this a bug.
