### ISSUE TITLE
Builds of Webpack ::: as a feature request

### ISSUE THREAD

**Issue by Peripona** [moment/moment#3551]
Please if possible create webpack build option

**Comment by maggiepint** [comment]
What do you mean? I guess I'm not sure what a specific webpack build would involve. People use moment with webpack all the time, no special effort on our part.

**Comment by Peripona** [comment]
I meant the source project of moment, if we can integrate webpack as a build tool instead of grunt. !?

**Comment by mj1856** [comment]
@Peripona - You want us to restructure a working build system to use a different build system?  Why would it matter?  Is there something you can't do today that you'd like to be able to do?

**Comment by icambron** [comment]
No, we're not going to do that. One  build system is hard enough to support as-is.
