### ISSUE TITLE
Add 1 week to 52 resets back to week 1

### ISSUE THREAD

**Issue by iamdriz** [moment/moment#3552]
When adding a week to the last week  of the year. e.g. `moment('2013-52', 'YYYY-WW').add(1, 'week').format('YYYY-WW');` it should be returning  the next year at week 1: `2014-01` but instead returns the same year at week 1 `2013-01`.

Subtracts seem to work fine. e.g.
`moment('2013-01', 'YYYY-WW').subtract(1, 'week').format('YYYY-WW');` returns `2012-52`

Tested this in Chrome on OS X with 2.14.1 version of moment.

**Comment by butterflyhug** [comment]
`YYYY` is the token for calendar year.  You're formatting one of the last days in December, which still has the previous calendar year even though its week is numbered in the following year.

`gggg` is the token for week year, so your format should be `"gggg-WW"`.
