### ISSUE TITLE
Day validation with 'DD' format

### ISSUE THREAD

**Issue by jonasnas** [moment/moment#3554]
**moment('31', 'DD', true).isValid() returns false if current month has only 30 days**

If I execute `moment('31', 'DD', true).isValid()` it returns `false` if current month has only 30 days. Is it expected behaviour? 

**Environment:**

*All*

**Comment by maggiepint** [comment]
This sort of validation really only works when you specify all of month, day, and year. Some months have 31 days, some have 30, some have 28, and some even 29. Without knowing both year and month, we can't really give you meaningful validation. If you want to check if a number is less than or equal to 31, why not just check that directly? It will save memory and perform better.

**Comment by icambron** [comment]
@jonasnas yes, this is the intended behavior. Remember that Moment parses your string into a specific instance in time, which means it has to provide defaults for things you didn't specify like month and year. It doesn't have the abstract concept of the nth day of, like, a month in general. And in this case, like @maggiepint says, it's hard to imagine what the semantics of `isValid()` should be even if Moment contain that concept.
