### ISSUE TITLE
Moment date object not binding in input type time in angualrjs

### ISSUE THREAD

**Issue by go2shibu** [moment/moment#3564]
**We are using moment 2.14.2 version in the angularjs. Here, I'm not getting an updated value in the ng-model when I change the input type time. Here is the scenario to reproduce the issue.**

* Convert time from string to moment date object
```js
angular.module('timeExample', [])
   .controller('DateController', ['$scope', function($scope) {
     $scope.startTime = moment('10:20', "HH:mm").toDate();
     //working snippet
     //$scope.startTime = new Date(1970, 0, 1, 10, 20, 0);
   }]);
<div ng-controller="DateController">
<input type="time" placeholder="HH:mm" min="00:00" max="23:59" ng-model="startTime "/>
<tt>value = {{startTime | date: "HH:mm:ss"}}</tt><br/>
</div>
```
*This model value is undefined and doesn't get update when I change the time, but if I use javascript date object It is updating the model.*

Is anyone faced this kind of issue? help me to solve or do I want to create new component/directive to watch the changes and update the model value? any idea why model value doesn't get update?

**Comment by mj1856** [comment]
I'd suggest trying the [angular-moment](https://github.com/urish/angular-moment) project.
