### ISSUE TITLE
Only want to compare TIME values MomentJS

### ISSUE THREAD

**Issue by rfossella** [moment/moment#3568]
After looking through other MomentJS questions I'm still stumped as to how one would use moment to simply compare **two different times** 

**I need (want) the day/date to be ignored.** 

Use case:
    I'm reading a schedule w/ start & end times from a config file.  This is done using Node.js
> Start time = 6:30 PM  
> End time = 3:30 AM

    var currentTime= moment();    // e.g. 11:00 pm
    var startTime = moment('06:30 pm', "HH:mm a");
    var endTime = moment('03:30 am', "HH:mm a");
    
    amIBetween = currentTime.isBetween(startTime , endTime);
    console.log(amIBetween);   //  returns false.  if date ignored I expect TRUE

My scenario is technically **spanning two days** and I understand why it's false.

I need (expect) moment to return TRUE - i.e. that currentTime isBeteen startTime and endTime and falls in that range. 

I thought I had it solved by checking if endTime hour is > 12 then add a day to make moment understand it's the following day.  e.g.

```
if (startTime.hour() >=12 && endTime.hour() <=12 )
	{
		endTime.add(1, "days");       // handle spanning days
	}

	var isBetween = currentTime.isBetween(startTime, endTime);   // TRUE

```

But if currentTime is also after midnight then it breaks - e.g.

01:30am will not be considered between 06:30pm and 03:30am  - also because of different days

Any other suggestions for accomplishing this and simply ignoring the day/date?

I'm finding it hard to believe that it's this complex, but maybe it is :\

--

Here's further clarification that issue arises with spanning days, even when trying to be more explicit:

    var currentTime= moment('11:00p', "HH:mm a");
    var startTime = moment('06:00p', "HH:mm a");
    var endTime = moment('03:30a', "HH:mm a");

    currentTime.toString(); //"Fri Oct 28 2016 23:00:00 GMT-0400"
    startTime.toString();   // "Fri Oct 28 2016 18:00:00 GMT-0400"
    endTime.toString();    // "Fri Oct 28 2016 03:30:00 GMT-0400"

    currentTime.isBetween(startTime, endTime);  // false
    currentTime.isAfter(endTime) && currentTime.isBefore(startTime); //false
    currentTime.isAfter(startTime) && currentTime.isBefore(endTime); //false

Seems kind of obvious that they'd be false since the *day/date* is considered by moment.  This is what I'm trying to get around.

The following would work:

    endTime.add(1, "days");
    currentTime.isBetween(startTime, endTime);  // TRUE

This would mean however, that I'd need to check if the START TIME was before 12AM && the ENDTIME as after 12AM then add 1 day to ENDTIME.

**Comment by icambron** [comment]
Closing this after discussion in #1199.

**Comment by AhrenFullStop** [comment]
I made my own method to simply align dates so that moment is effectively only caring about the time, and I use it when needed:

`  alignDates(baseline,toBeModified){
    //Align date, keep time
    //This method should keep only min and hours, and align dates to baseline
    let alignedDate = baseline.clone().set('hours',toBeModified.hours()).set('minutes',toBeModified.minutes());
    return alignedDate;
  }`
