### ISSUE TITLE
no en-us locale?

### ISSUE THREAD

**Issue by hellatan** [moment/moment#3569]
I installed moment@2.15.2 and was looking through the locales available. I assumed there was an `en-us` locale, but when I tried to load it, it failed. Upon further inspection, I only saw these `en` locales:

- en-au
- en-ca
- en-gb
- en-ie
- en-nz

Am I missing something? I feel like `en-us` would be its own locale as well based on what I have dealt with in the past. Am I missing something here? Can someone point me in the right direction?

**Comment by maggiepint** [comment]
The default en is en-us. It's what we speak on the Moment team :-)

**Comment by hellatan** [comment]
thanks @maggiepint. Is that somewhere in the docs? I searched for awhile and I couldn't find any mention of the default locale.

**Comment by maggiepint** [comment]
I just modified the note in the doc to specify English (United States). Good point.
