### ISSUE TITLE
when subtracting a date from another, why does it gives 1000  more seconds than it should ?

### ISSUE THREAD

**Issue by jpca999** [moment/moment#3572]
var nowMoment = moment();

  var c = nowMoment;
  var d = moment().subtract(1,'d'); 

console.log( ' C =' , c); 
console.log( ' d =' , d); 

console.log( ' --------- RAW diff cd -------',  c-d);   //  8640,0000

**Comment by butterflyhug** [comment]
Coercing a moment to a number gives you [a timestamp in milliseconds](http://momentjs.com/docs/#/displaying/unix-timestamp-milliseconds/), not seconds.
