### ISSUE TITLE
how to subtract a date from another when it has  some format ?

### ISSUE THREAD

**Issue by jpca999** [moment/moment#3574]
var nowMoment = moment();
  var c = nowMoment.format('YYYY-M-D');
  var d = moment().subtract(14, 'day').format('YYYY-M-D');
  console.log( ' C =' , c); 
  console.log( ' d =' , d); 
  console.log( ' --------- diff cd -------',  c.diff(d, 'days')); 

How to subtract  c-d to get back 1 day ?

**Comment by maggiepint** [comment]
`c` and `d` are strings.  If you leave them as moments it is easy.

```js
var d = moment().subtract(14, 'day');
console.log( ' C =' , c);
console.log( ' d =' , d);
console.log( ' --------- diff cd -------', nowMoment.diff(d, 'days'));
```
