### ISSUE TITLE
how to deformat the formatted date to original raw object ?

### ISSUE THREAD

**Issue by jpca999** [moment/moment#3575]
var nowMoment = moment();
  var c = nowMoment.format('YYYY-M-D');
this gives use 2-16-11-6 

How do i get back to :  

q {_isAMomentObject: true, _isUTC: false, _pf: Object, _locale: B, _d: Sun Nov 06 2016 15:49:21 GMT-0400 (EDT)…}

**Comment by maggiepint** [comment]
Is there a reason to get back? The variable ``nowMoment`` is still a moment.

**Comment by icambron** [comment]
`c` should be "2016-11-6" (not sure where that extra hyphen came from in your post). Anyway, use `moment(c, 'YYYY-M-D')` to parse it into a Moment object. Or, as Maggie says, don't turn it into a string and back and instead just keep the old object.
