### ISSUE TITLE
Additional formats

### ISSUE THREAD

**Issue by Spenhouet** [moment/moment#3578]
We need two formats that moment doesn't support yet.

1. **QA** (abbreviated) _e.g. en: Q1, Q2, Q3 and Q4, fr: T1, T2, T3 and T4,..._
2. **MMDD** _e.g. en: 04/19 (MM/DD), de: 19.04 (DD.MM),...._

Both formats for every language can be found in the CLDR project here: https://github.com/unicode-cldr/cldr-dates-full/tree/master/main

For example:

1. **QA** => [en/ca-gregorian.json](https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/en/ca-gregorian.json) - main.en.dates.calendars.gregorian.quarters.format.abbreviated
2. **MMDD** => [en/ca-gregorian.json](https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/en/ca-gregorian.json) - main.en.dates.calendars.gregorian.dateTimeFormats."Md"

I'm not a licence expert and don't know if the CLDR data could just be copied (http://unicode.org/copyright.html#License)?

If the Licence is no problem, we even would be willing to do the work of copying both formats for every of the 104 language files you support and create a pull request.

We really need both formats and don't want to program a workaround.

**Comment by mj1856** [comment]
Thanks, but we really don't want to expand the locale data size right now.  We've had requests for things like `MMDD` and other format combinations in the past, and rejected for similar reasons.

These can both be accomplished already, just not in a locale-generic way.

Eventually (long term goal), I'd like to integrate more closely with [Globalize](https://github.com/globalizejs/globalize) for this sort of thing anyway.
