### ISSUE TITLE
moment().startOf() fails during extra daylight savings hour

### ISSUE THREAD

**Issue by clwainwright** [moment/moment#3580]
**Description of the Issue and Steps to Reproduce:**

Calling `moment().startOf('hour')` during the hour that's repeated when clocks are rolled back from daylight savings time yields the next hour, not the previous one.

For example, `moment([2016,10,6]).add(1, 'hour').toDate()` correctly yields `Sun Nov 06 2016 01:00:00 GMT-0700 (PDT)` (where my local timezone is US/Pacific), whereas `moment([2016,10,6]).add(1, 'hour').startOf('hour').toDate()` yields `Sun Nov 06 2016 01:00:00 GMT-0800 (PST)`. This leads to some very odd behavior, like `moment([2016,10,6]).add(1, 'hour').startOf('hour') <= moment([2016,10,6]).add(1, 'hour')` yielding `false`. The same problem occurs for `startOf('minute')` and `startOf('second')`.

Strangely, this does not seem to be a problem when setting the timezone explicitly using `moment.tz([2016,10,6], 'US/Pacific')`.

**Environment:**

This is running moment version 2.15.2 directly off of the momentjs homepage in my browser's console. I'm running Safari 10.0.1 on macOS 10.12.1. I get the same problem on Firefox 49.0.2, but not on Chrome 54.0.2840.71.

_If you are reporting an issue, please run the following code in the environment you are using and include the output:_
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

```
[Log] Mon Nov 07 2016 13:25:46 GMT-0800 (PST)
[Log] 11/7/2016, 1:25:46 PM
[Log] 480
[Log] Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14
[Log] 2.15.2
```

**Comment by mj1856** [comment]
This seems related to #1990, #2749 and #3132.

I'm not sure if it's an exact duplicate though, so leaving this open for now.  Thanks for reporting.

**Comment by marwahaha** [comment]
I'm trying to reproduce (on the momentjs.com website, which is now running 2.18.1) and the bug seems to be fixed.

![image](https://cloud.githubusercontent.com/assets/2541209/24595789/a0a88fd8-1807-11e7-9f7e-c2ae972b1fa0.png)


Please re-open if you see this bug again.

**Comment by mj1856** [comment]
There's still something up here.

![image](https://cloud.githubusercontent.com/assets/1396388/24965109/f6aba5d0-1f57-11e7-95c2-32e99a8636f0.png)

The last line should have stayed in GMT-0500 (Eastern Standard Time).

I also get the same results using `.format()` instead of `.toDate()`.  Something in the `startOf` function is jumping back to the first instance of the repeated hour, even if we're within the second instance.

**Comment by mj1856** [comment]
(Chrome 57 latest on Win10, on Moment 2.18.1)

**Comment by tomasztomys** [comment]
The same problem here - moment 2.19.2, Chrome 62 on Win10
