### ISSUE TITLE
method format() have a bug

### ISSUE THREAD

**Issue by macurial** [moment/moment#3584]
when i use moment().format() in nodejs,
the result of moment("2016-11-9").format("YYYY-MM-DD") is "2016-11-01".is there anything wrong?

**Comment by TracyGJG** [comment]
I think DD will expect a leading zero on days on the month less than 10.

**Comment by TracyGJG** [comment]
I think DD will expect a leading zero on days on the month less than 10. Try a single D in your format string.

**Comment by TracyGJG** [comment]
I suspect the string you tried to instantiate with produced an invalid object. To confirm you should check the value of the isValid method rather than the value of the object itself.

**Comment by macurial** [comment]
@ TracyGJG   
I have loged this  moment('2016-11-9 17:53').isValid() to check if this string is valid ,it turn out  a TRUE， but the result of moment('2016-11-9 17:53').format('YYYY-MM-DD') still to be a "2016-11-01", and in the document of moment , D means  no zero on days less than 10 ,DD means a leading zero on days less than 10 ,so,the format() function still has a bug

**Comment by mj1856** [comment]
The `DD` format here is in the *output*. There was no format passed to the input, and the input provided is not in one of the [default formats](http://momentjs.com/docs/#/parsing/string/).

If your input is going to be as you showed, you need to specify the format of the input.

```js
moment('2016-11-9', 'YYYY-M-D').format('YYYY-MM-DD')  // "2016-11-09"
``
Note that I'm using the single-digit tokens for the input format, and the two-digit tokens in the output format.  Adjust as needed.

No, there is no bug here.  This is working as designed.  The `format` function is not to specify the format of the input, but rather to *format* the moment object to a string using the requested format.
