### ISSUE TITLE
German locale support for AM/PM

### ISSUE THREAD

**Issue by raijitendra** [moment/moment#3585]
Recently I  have started using moment.js to address DST issues, but came to know that there is no support for  AM/PM in German locale. Please let me know whether this is known issue if not please let me know how to handle it as there is no translation for AM/PM in the locale file.

**Comment by maggiepint** [comment]
Just asked the German speaker who sits next to me at work to confirm. There is no AM/PM in German. They use the 24 hour method exclusively.

I would suggest looking at the localized formats to get around issues like this:
http://momentjs.com/docs/#/displaying/format/

**Comment by mj1856** [comment]
@raijitendra:

From: http://www.dummies.com/languages/german/basic-german-telling-time/

> German speakers have two systems for telling time: one using the numbers 1–12 on a standard clock and one using a 24-hour format. They use the 12-hour system in casual conversation and the 24-hour system when they want to avoid any chance of misunderstanding. Unlike in the United States, Germans don’t use the a.m./p.m. system.

> ...

> Many German speakers use the 12-hour clock format when talking casually. This system is one you’re already familiar with: You use the numbers 1 through 12 on a standard clock. However, German doesn’t have the expressions a.m. and p.m., so German speakers revert to the 24-hour format to avoid potential misunderstandings, for example, when discussing schedules and the like.

Moment will still return `"am"`/`"pm"` when you use the `a` formatting token, or `"AM"`/`"PM"` for `A`, but it will not use them with any of the locale-specific formats like `LLL`

**Comment by raijitendra** [comment]
@maggiepint  we are using AngularJs library where AM/PM are localized and hence we facing issue of inconsistent behavior.
