### ISSUE TITLE
.isValid() incorrect for leap year dates in the new millenium 

### ISSUE THREAD

**Issue by lesansley** [moment/moment#3586]
**Description of the Issue and Steps to Reproduce:**

*Called `.isValid()` on the date 29/02/2016 and was returned `true`*
```js
moment('29/02/2016', 'DD/MM/YYYY').isValid(); // true
moment('29/02/2014', 'DD/MM/YYYY').isValid(); // false
moment([2016]).isLeapYear(); // true
moment([2014]).isLeapYear(); // false
```

**Environment:**

*Chrome 55.0.2883.35 beta (64-bit) on OSX El Capitan*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
Wed Nov 09 2016 14:34:09 GMT+0000 (GMT)
VM3376:2 11/9/2016, 2:34:09 PM
VM3376:3 0
VM3376:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.35 Safari/537.36
VM3376:5 2.15.2
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by maggiepint** [comment]
2016 is a leap year.

![image](https://cloud.githubusercontent.com/assets/6054610/20147619/b1af4432-a65d-11e6-866b-dbea82bb012f.png)
