### ISSUE TITLE
"Moment Timezone has no data for America/Mexico_City. See http://momentjs.com/timezone/docs/#/data-loading/."

### ISSUE THREAD

**Issue by patchie** [moment/moment#3587]
**Description of the Issue and Steps to Reproduce:**
I am using "dashing" to create a dashboard with a widget with 3 clocks with 3 different timezones.
But it only shows me the current timezone on all 3 clocks.

Whats also strange is that if i open moment-timezone.js and put in js alerts to debug, i find that normalizename changes the slash to a underscore. Why?
```js
function getZone (name, caller) {
                alert('test1:' + name); // --> test1:America/Mexico_City
		name = normalizeName(name);
                alert('test2:' + name); // --> test2:america_mexico_city
```
I am not sure why it removes the slash? is that the way it is supposed to work?
In the file moment-timezone-data.js, the string is like in test1.

**Software:**
moment.js - version 2.15.2
moment-timezone.js - version 0.5.9
moment-timezone-data.js - http://momentjs.com/downloads/moment-timezone.js

**Environment:**
Server: Ubuntu 14.04.4 LTS
Client: Windows 7 - Firefox 49.0.2

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
```CET (Europe - Norway)```
* The time and date at which the code was run
```09.11.2016 - 15:33```
* Other libraries in use (TypeScript, Immutable.js, etc)
```Dashing --> https://github.com/Shopify/dashing```

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString()) --> Wed Nov 09 2016 15:35:06 GMT+0100 (W. Europe Standard Time)
console.log((new Date()).toLocaleString()) --> 9.11.2016, 15.35.06
console.log( (new Date()).getTimezoneOffset()) --> -60
console.log( navigator.userAgent) --> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0
console.log(moment.version) --> 2.15.2
```

**HTML:**
```html
Nor
<p data-bind="no_today_date"></p>
<h2 data-bind="no_today_time"></h2>

SG
<p data-bind="sg_today_date"></p>
<h2 data-bind="sg_today_time"></h2>

US
<p data-bind="us_today_date"></p>
<h2 data-bind="us_today_time"></h2>
```

**Coffeescript:**
```coffeescript
class Dashing.Clock extends Dashing.Widget

  ready: ->
    setInterval(@startTime, 500)

  startTime: =>

    us_today = moment(new Date()).tz('America/Mexico_City')
    @set('us_today_time', us_today.format('HH:mm'))
    @set('us_today_date', us_today.format("MMM Do"))

    no_today = moment(new Date()).tz('Europe/Stockholm')
    @set('no_today_time', no_today.format('HH:mm'))
    @set('no_today_date', no_today.format("MMM Do"))

    sg_today = moment(new Date()).tz('Asia/Singapore')
    @set('sg_today_time', sg_today.format('HH:mm'))
    @set('sg_today_date', sg_today.format("MMM Do"))
```

**Error message when loading the page:**

```
"Moment Timezone has no data for America/Mexico_City. See http://momentjs.com/timezone/docs/#/data-loading/."
"Moment Timezone has no data for Europe/Stockholm. See http://momentjs.com/timezone/docs/#/data-loading/."
"Moment Timezone has no data for Asia/Singapore. See http://momentjs.com/timezone/docs/#/data-loading/."
....etc over and over
```

Thanks in advance!

**Comment by mj1856** [comment]
A few things:

1. Moment-timezone has [its own issue tracker](https://github.com/moment/moment-timezone/issues).  In the future, please raise questions about moment-timezone there.

2. It sounds like you just haven't loaded the moment-timezone data.  You either need to call `moment.tz.add` for each time zone you want, or you need to use one of the "with data" distributions (either "all years", or "2010-2020").

3. Yes, the `getZone` and `normalizeName` functions are working as intended.

**Comment by patchie** [comment]
Thanks a lot. 
Thanks for all advice! 
It worked.

**Comment by jerbob92** [comment]
For anyone reading this: make sure you don't have any whitespaces before or after your Timezone name. The normalizeName function does not trim/remove whitespaces.
