### ISSUE TITLE
Incorrect date time returned from moment(unixtime).format('YYYY-MM-DD HH:MM:SS')

### ISSUE THREAD

**Issue by davidchappelle** [moment/moment#3588]
**Description of the Issue and Steps to Reproduce:**
moment(1473708712743).format('YYYY-MM-DD HH:MM:SS')
Returns: 2016-09-12 15:09:74

Clearly we can't have 74 as the seconds value.

**Environment:**
node: v4.4.7
moment: 2.14.1

**Other information that may be helpful:**

```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log(moment.version)
```

```
Wed Nov 09 2016 15:25:16 GMT-0500 (EST)
11/9/2016, 3:25:16 PM
300
2.14.1
```

**Comment by maggiepint** [comment]
YOur format string is wrong. `M` is months, not minutes. `S` is milliseconds, `s` is seconds.
