### ISSUE TITLE
typing errors after upgrading from 2.15.2 to 2.16.0

### ISSUE THREAD

**Issue by donaldpipowitch** [moment/moment#3589]
**Description of the Issue and Steps to Reproduce:**

Try to import `2.16.0` and compile moment from inside an TypeScript project.

**Environment:**

Mac, TypeScript 2.0.6

tsconfig:

```json
{
  "compilerOptions": {
    "target": "es6",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "strictNullChecks": true
  },
  "exclude": [
    "node_modules",
    "examples"
  ]
}
```

**Other information that may be helpful:**

`2.15.2` compiles without errors. `2.16.0` throws with the following error:

```
ERROR in [default] ./node_modules/moment/moment.d.ts:63:4
Property 'sameDay' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.

ERROR in [default] ./node_modules/moment/moment.d.ts:64:4
Property 'nextDay' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.

ERROR in [default] ./node_modules/moment/moment.d.ts:65:4
Property 'lastDay' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.

ERROR in [default] ./node_modules/moment/moment.d.ts:66:4
Property 'nextWeek' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.

ERROR in [default] ./node_modules/moment/moment.d.ts:67:4
Property 'lastWeek' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.

ERROR in [default] ./node_modules/moment/moment.d.ts:68:4
Property 'sameElse' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.
```

**Comment by kristho91** [comment]
I got the same error.
Windows 10, Typescript 2.0.8.

tsconfig:
`"compilerOptions": {
		"target": "es5",
		"module": "system",
		"moduleResolution": "node",
		"lib": [ "dom", "es6" ],
		"sourceMap": true,
		"strictNullChecks": true,
		"noImplicitAny": false,
		"noImplicitReturns": true,
		"noUnusedLocals": false,
		"noUnusedParameters": false,
		"noEmitOnError": true,
		"typeRoots": [ "node_modules/@types" ],
		"types": [
			"jquery",
			"jqueryui",
			"angular",
			"angular-material",
			"angular-mocks",
			"angular-ui-bootstrap",
			"angular-ui-router",
			"bootstrap",
			"chartist",
			"highlight.js",
			"interact.js",
			"moment",
			"ng-file-upload",
			"uglify-js",
			"mocha",
			"chai",
			"sinon"
		],
		"outFile": "./Scripts/dist/app.js"
	},
	"exclude": [
		"Scripts/dist",
		"Scripts/test",
		"node_modules"
	],`

**Comment by itaysabato** [comment]
+1

**Comment by Delagen** [comment]
I think interface must be updated to
```
interface CalendarSpec {
    sameDay?: CalendarSpecVal;
    nextDay?: CalendarSpecVal;
    lastDay?: CalendarSpecVal;
    nextWeek?: CalendarSpecVal;
    lastWeek?: CalendarSpecVal;
    sameElse?: CalendarSpecVal;

    // any additonal properties might be used with moment.calendarFormat
    [x: string]: CalendarSpecVal|***undefined***;
  }
```

**Comment by ichernev** [comment]
Can somebody prepare pr with this and typings test update?

**Comment by Delagen** [comment]
@ichernev already prepared #3591

**Comment by adambuczynski** [comment]
I am also getting errors in the form of `Module 'moment' has no exported member 'UnitOfTime'`
Someone suggested that these typings had changed?

I would expect that if breaking changes are made to the typings, moment will bump the major version and not just minor version?

**Comment by maggiepint** [comment]
closing dupe to 2.17.1 point release
