### ISSUE TITLE
Error formatting 'startOf' week (Spanish) (24H)

### ISSUE THREAD

**Issue by aabilio** [moment/moment#3593]
On Spanish locale, format the 'startOf' week returns an incorrect hour (24H)

Example:

**English. Correct:** 
```js
moment.locale('en');
moment().add('1 week').startOf('week').tz('Europe/Madrid').format("dddd D MMM kk:mm");
```
```> "Sunday 6 Nov 24:00"```

**Spanish. Error:** 
```js
moment.locale('es');
moment().add('1 week').startOf('week').tz('Europe/Madrid').format("dddd D MMM kk:mm");
```
```> "lunes 7 nov. 24:00"```

I thin it should be ```Domingo 6 nov. 24:00```or better ```lunes 7 nov. 00:00```

**Environment:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on: Europe/Madrid
* The time and date at which the code was run: Nov. 10 2016 17:56

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
```
> Thu Nov 10 2016 17:57:09 GMT+0100 (CET)
> 2016-11-10 17:57:09.870 VM19278:2 10/11/2016 17:57:09
> 2016-11-10 17:57:09.870 VM19278:3 -60
> 2016-11-10 17:57:09.870 VM19278:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
```

**Comment by icambron** [comment]
`kk` is what's giving you 24:00. It doesn't mean the 24th hour of that day. It just replaces 00 with 24 without modifying the day. Use `HH` if you want "00". It'll still say "lunes" for the day.

As an aside, you should set the TZ before setting the beginning of the week if you expect it to be the beginning of the week in the target zone. Compare:

```js
> moment().add('1 week').tz('Europe/Madrid').startOf('week').format("dddd D MMM kk:mm");
'Sunday 13 Nov 24:00'
> moment().add('1 week').startOf('week').tz('Europe/Madrid').format("dddd D MMM kk:mm");
'Sunday 13 Nov 09:00' //because I'm 9 hours behind Spain
```

**Comment by aabilio** [comment]
@icambron thanks for your answer. I reported that as an error because it was weird to me to get the Monday at 24:00 as the start of a week, but now I know how it works, thanks.

About your advice with the timezone, I really want to get the client time when in Spain is the start of a week. But thanks.

**Comment by icambron** [comment]
> About your advice with the timezone, I really want to get the client time when in Spain is the start of a week.

You're doing the opposite of that: you're getting the start of the week in the local TZ and then formatting that time as it would be in Spain.

**Comment by aabilio** [comment]
Oh! I see, you're right. I was confusing because with the using of `tz` after the `startOf` I was getting a different Spanish `startOf('week')`, and not the same start of week of Spain as we get when we use `tz` before `startOf('week')` (thing that is logic because start of week is the same everywhere, at least using [ISO 8601](https://en.wikipedia.org/wiki/ISO_week_date)).

But with all of this I realize that what I really want it is something like this (If I want the hour in Argentine when in Spain is `Monday XX 00:00`):

```js
moment().tz('Europe/Madrid').startOf('week').tz('America/Argentina/Buenos_Aires').format('dddd D MMM HH:mm')
```

Get the start of week of Spain by first setting the timezone to _'Europe/Madrid'_ and then set timezone again to local time to format that date. Problem here is that I don't know how to know in which timezone the client really is for the second `tz`. I will investigate. Thanks.
