### ISSUE TITLE
Moment not parsing dates using the current system timezone

### ISSUE THREAD

**Issue by mrapczynski** [moment/moment#3594]
I'm experiencing an extremely strange issue using Moment to parse a simple MMMM YYYY date.

It generates an object with the correct month, day, and year -- but the timezone is the wrong one. Therefore if this date is passed to other external systems where the timezone is sync'ed correctly, such as when using NTP, then the date is read an hour behind.

For example: if I parse `November 2016` using the pattern `MMMM YYYY`, then I get a Moment object for `November 1, 2016 12:00 AM PDT`. When passed to another application, there is a risk of it being stored as `October 31, 2016 11:00 PM PDT`

In the sample program below, I have reproduced this with both `moment` and `moment-timzeone`, and no matter what I do, I cannot even force the UTC offset to match the system.

**Environment:**

OSX 10.11.6
Node 6.9.1
Current Date and Time on System: Thu Nov 10 13:06:26 PST 2016

**Sample Program:**
```js
'use strict';
let Moment = require('moment');
let MomentTz = require('moment-timezone');

function printDateWithOffset(label, date) {
    console.log(`${label}: ${date} -> UTC Offset = ${date.getTimezoneOffset()}`);
}

let jsDate = new Date();
let momentParsed = Moment('November 2016', 'MMMM YYYY');
let momentParsedWithOffset = Moment('November 2016', 'MMMM YYYY').utcOffset(480);
let momentTzParsed = MomentTz.tz('November 2016', 'MMMM YYYY', 'America/Los_Angeles');

printDateWithOffset('Std. JS Date', jsDate);
printDateWithOffset('Moment (parsed)', momentParsed.toDate());
printDateWithOffset('Moment (parsed w/ offset)', momentParsedWithOffset.toDate());
printDateWithOffset('Moment TZ (parsed)', momentTzParsed.toDate());
```

**Sample Output:**
```
Std. JS Date: Thu Nov 10 2016 13:11:06 GMT-0800 (PST) -> UTC Offset = 480
Moment (parsed): Tue Nov 01 2016 00:00:00 GMT-0700 (PDT) -> UTC Offset = 420
Moment (parsed w/ offset): Tue Nov 01 2016 00:00:00 GMT-0700 (PDT) -> UTC Offset = 420
Moment TZ (parsed): Tue Nov 01 2016 00:00:00 GMT-0700 (PDT) -> UTC Offset = 420
```

**Comment by mrapczynski** [comment]
Nevermind... I see what is happening here. Moment is _so sophisticated_ that is actually applies the prior offset from before the time change on November 6th. Fecha does the same exact thing. Good job on being so thorough.

**Comment by maggiepint** [comment]
I'm not sure if you're interpreted that correctly, but I could be misunderstanding this. When you get a javascript date by calling `.toDate()` you will always get the local time of the system, and not the timezone you parsed in, because date doesn't understand timezones.

I would read this: https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/
