### ISSUE TITLE
Linting is not checking commits effectively

### ISSUE THREAD

**Issue by tomhicks-bsf** [moment/moment#3596]
Commit 38e3e52dc92958d3e7dae399693c3153c3e947c8 introduced a subtle bug which would be easily caught if this project were to include some basic linting checks.

Things such as referencing undeclared variables are simple to catch with linting, and a project as important (due to its widespread use) as this one must have basic checks such as this.

I'm prepared to help with this if it's more of a job than "oh, whoops, we forgot to lint the utils folder" or whatever.

**Comment by maggiepint** [comment]
The code base has both JSCS and JSHint in it, and quite a lot of linting is done already. If you wish to turn that rule on, by all means do so, fix the errors, and make a pull request.
