### ISSUE TITLE
Undefined var is being convert to actual datetime

### ISSUE THREAD

**Issue by alexcarrasco93** [moment/moment#3598]
I am passing a scoped data to moment($scope.dateStart) and moment($scope.dateFinal) by inputs. I want to set it undefined if the scoped data is undefined but I'm getting the actual datetime. I want it this way because you may just want to introduce  dateStart so will work like a filter until infinite future. Is there anything to keep it undefined if $scope.dateFinal is undefined? I don't want to make moment() function when moment(undefined)

**Environment:**

*Ionic, Angular*

**Comment by icambron** [comment]
`moment(undefined)` will always be the same as `moment()`. I'm not an Angular person so I can't help you with the Angular specific part of it, but why not just check if `dateFinal` is undefined before creating your Moment instance?

**Comment by alexcarrasco93** [comment]
Ow thank you. That's a good idea. I didn't think about it because I am a beginner programmer.  I want to learn how to think so that was helpful. 

Thank you!

**Comment by jarryd999** [comment]
@icambron Why is this the case?  It seems to me that the intuitive result of `moment(undefined)` is a moment object representing an `Invalid Date`.  Could you elaborate on the decision?

**Comment by icambron** [comment]
@jarryd999 See https://github.com/moment/moment/issues/2729#issuecomment-159908460 and a fuller discussion here: https://github.com/moment/moment/issues/3180#issuecomment-219200760
