### ISSUE TITLE
Deprecation warning : defineLocale from french locale file

### ISSUE THREAD

**Issue by vincent-guesnard** [moment/moment#3600]
Hello,

I got a warning (console) while using french locale fr.js file (since version 1.15.x and with 1.16.0) : 

moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.

Am i supposed to do something to avoid this ? If i can help on the french file, it would be pleasure.

In all case : thanks you for this amazing lib which works flawlessly with fullcalendar.

Best regards,

Vincent

**Comment by maggiepint** [comment]
If you are using the default locale file and not overriding any part of it in your code, then my guess is you are loading the file twice. If you override any part of the locale file in your code, then you need to change that code to use `.updateLocale` instead of `.locale`.

**Comment by vincent-guesnard** [comment]
Thanks you for your answer, here is what i load : 

- min/moment.min.js
- then locale/fr.js (warning is fire at this moment)

Since i'm using files "as it", without any change, i was thinking about a depreciation within the locale/fr.js

**Comment by edouard-lopez** [comment]
If you use fullcalendar it might be the cause (cf. #3076).

**Comment by vincent-guesnard** [comment]
Yes, i've reported it here : https://github.com/fullcalendar/fullcalendar/issues/3471
