### ISSUE TITLE
time starting from 5s,4s,3s,2s,1s and 2s,3s,4s.........

### ISSUE THREAD

**Issue by ajayreddy56** [moment/moment#3601]
i facing an issue with` moment.lang('en', { relativeTime : { future: "in %s", past: "%s", s: "%ds", m: "1m", mm: "%dm", h: "1h", hh: "%dh", d: "1d", dd: "%dd", M: "30d", MM: function (number) { return number * 30 + 'd'; }, y: "365d", yy: function (number) { return number * 365 + 'd'; } } }); 
`

when i post , time starting from 5s,4s,3s,2s,1s, then it's displaying 2s,3s,4s,5s,6s.........
it should start from 1s,2s,3s.....go on

**Comment by icambron** [comment]
Can you provide a working example of your issue?

**Comment by ajayreddy56** [comment]
<span am-time-ago="post.createdTS"></span>

**Comment by icambron** [comment]
A working example means something I can click on and observer, like a JSFiddle
