### ISSUE TITLE
Moment format ("2016-11-15T23:59:59Z").format('DD/MM/YYYY') adds 1 day

### ISSUE THREAD

**Issue by eliavmaman** [moment/moment#3606]
Moment format ("2016-11-15T23:59:59Z").format('DD/MM/YYYY') returns wrong date.
it's returns the Date with advanced day e.g '16/11/2016'.
am i doing something wrong?

**Comment by maggiepint** [comment]
You probably want `moment.utc()` instead of `moment()` when creating your moment object if you don't want the day to change. See this blog post: https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/
