### ISSUE TITLE
When using calendar() with inline day options, nextDay and lastDay are incorect

### ISSUE THREAD

**Issue by optikalefx** [moment/moment#3607]
**Description of the Issue and Steps to Reproduce:**
When using calendar() with inline options, the nextDay key and the lastDay key are flipped. I have to set to nextDay to [Yesterday] and lastDay to [Tomorrow] for it to be correct. Using the options globally does not have this problem.

**Environment:**
OSX Chrome evergreen

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*
I'm using ember-moment, but this feature is just off the moment lib

Input that should show yesterday `2016-11-14 00:00:00` says Tomorrow  
Input that should show tomorrow `2016-11-16 00:00:00` says Yesterday

```
row.calendarDay = moment().calendar(new Date(row.pickupDate), {
	sameDay: '[Today]',
	nextDay: '[Tomorrow]',  // USED FOR YESTERDAY'S DATE
	nextWeek: 'dddd',
	lastDay: '[Yesterday]',  // USED FOR TOMORROW'S DATE
	lastWeek: '[Last] dddd',
	sameElse: 'DD/MM/YYYY'
});
```

```js
Tue Nov 15 2016 10:24:34 GMT-0500 (EST)
controller.js:32 11/15/2016, 10:24:34 AM
controller.js:33 300
controller.js:34 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36
controller.js:35 2.14.1
```

**Comment by icambron** [comment]
You have the signature backwards:

```js
moment().calendar();
moment().calendar(referenceTime);
```

Reference time means "pretend that we want the results relative to some other time instead of now". The actual calendar is applied to `this`. So you want:

```js
moment(new Date(row.pickupDate)).calendar(moment());
```

Since *right now* is the default "anchor" for `calendar` anyway, this simplifies to just that first signature:

```js
moment(new Date(row.pickupDate)).calendar();
```

With things flipped around, the dates should be right.

**Comment by optikalefx** [comment]
perfect, thank you!
