### ISSUE TITLE
moment("11", "YYYY-MM-DD").isValid() ?

### ISSUE THREAD

**Issue by niyazpk** [moment/moment#3610]
Opened the console in the momentjs documentation site and typed:

    moment("11", "YYYY-MM-DD").isValid()
    >> true

I would hope that anything that does not conform to the format given is invalid. Isn't this a bug?

Environment:

    Fri Nov 18 2016 19:28:01 GMT-0800 (PST)
    11/18/2016, 7:28:01 PM
    480
    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
    2.16.0

**Comment by icambron** [comment]
You want strict parsing:

```js
moment("11", "YYYY-MM-DD", true).isValid(); //=> false
```
