### ISSUE TITLE
Creating 10/31/1987 actually creates 10/01/1987

### ISSUE THREAD

**Issue by radicalray** [moment/moment#3613]
```
> moment().date(31).month(9).year(1987).unix() * 1000;
560099594000
> moment().date(30).month(9).year(1987).unix() * 1000;
562608799000
```

**Environment:**
Node v6.0.0
moment@2.15.1

OSX 10.11.6

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

Output:
```
> console.log( (new Date()).toString())
Sat Nov 19 2016 11:20:05 GMT-0500 (EST)
undefined
> console.log((new Date()).toLocaleString())
11/19/2016, 11:20:05 AM
undefined
> console.log( (new Date()).getTimezoneOffset())
300
undefined
> console.log( navigator.userAgent)
ReferenceError: navigator is not defined
    at repl:1:14
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:219:10)
    at REPLServer.Interface._line (readline.js:561:8)
    at REPLServer.Interface._ttyWrite (readline.js:838:14)
> console.log(moment.version)
2.15.1
undefined
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by marwahaha** [comment]
I think it's because `date(...)` doesnt know how to respond if the month isn't set.

For comparison, try:
```
> moment().year(1987).month(10).date(31).unix() * 1000
565389524000
> moment().year(1987).month(10).date(30).unix() * 1000
565303126000
```

By the way, your example uses September (`month==9`)

**Comment by radicalray** [comment]
Month is zero-based so .month(9) is actually October. You can check by doing a toString on the object you created. The edge case I came up with isn't duplicate-able easily for just any other end of month. 

What do you mean by "the month is not set"?

**Comment by mattjdev** [comment]
What I think @marwahaha was trying to get at is that the order in which you set the month and date values matter.

Because November (current month) only has 30 days, `moment().date(31)` returns December 1, and then you set the `month` on December 1, which will return October. So the safest thing to do (as shown in @marwahaha's) example) is to call the functions from year, then month, then day, then hour, etc.

**Comment by maggiepint** [comment]
@mattjdev is quite correct so I'm going to close this.

It is worth noting that if you use `moment().set()` the unit order is actually always descending programmatically, so it will automatically avoid this sort of issue.

**Comment by radicalray** [comment]
Super! Thank you all for the clarification. 👍
