### ISSUE TITLE
typings for jsnext

### ISSUE THREAD

**Issue by stephenlautier** [moment/moment#3616]
Currently moment with typescript is only usable with the non es6 version of moment, which preferably we can use the es6 version instead. Another great benefit is also to be able to get it working with rollup.

I was experimenting to try and get them working together within the same package (Typings for es6 and non es6) however I didn't manage. Would you accept a PR if i make the typings for es6 and change the default to be the es6 version instead? 

Usage would be as

```ts
import moment, { Moment } from "moment";
const date: Moment = moment();

// instead of 
import * as moment from "moment";
const date: moment.Moment = moment();
```
Its also much cleaner and the way imports should be used. What do you think?

**Comment by marwahaha** [comment]
I think we'd like this @stephenlautier  - but this breaks our TS 1.x users. I think in the next major version, we can provide something like this.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
