### ISSUE TITLE
isValid() is not correct for moment object created with array

### ISSUE THREAD

**Issue by zamronypj** [moment/moment#3621]
**Description of the Issue and Steps to Reproduce:**

isValid() for moment defined using array always returns true for invalid date. For example
for date 30 February 2010.

```js
console.log(moment([2010,2,30]).isValid()); //true
```

*Please include the values of all variables used.*

**Environment:**

*Ubuntu 14.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
Thu Nov 24 2016 09:28:29 GMT+0800 (WITA)
24/11/2016 09.28.29
-480
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
2.12.0

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by icambron** [comment]
Months in JS are 0-indexed, so that's March 30, which is valid. Feb works fine:

```js
> moment([2010,1,30]).isValid()
false
```
