### ISSUE TITLE
validating positively for a missing timezone

### ISSUE THREAD

**Issue by sebs** [moment/moment#3622]
Came by this in a discussion, we opened a bug report. Probably a isse. 

**Description of the Issue and Steps to Reproduce:**

1. Validating a ISO 8601 formatted date without timezone declaration in non-strict mode always results as true even when the timezone is missing. Validating in strict mode is not an alternative because then the entire date must be mapped, which can't be done in case the exact formatting of the remainder of the date isn't known at programming time.

```js
import { module, test } from '../qunit';
import moment from '../../moment';

module('bugreport');

test('validating positively for a missing timezone', function (assert) {
    var validated = moment("2097-07-16T19:20:30.45", 'Z').isValid();
    assert.notOk(validated, 'We expect a date without a expressively mentioned timezone as invalid');
});

```

*Please include the values of all variables used.*

**Environment:**

* unit test suite

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())

Thu Nov 24 2016 11:03:09 GMT+0100 (CET)
2016-11-24 11:03:09
-60
```

node.js / moment - latest development master 

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by maggiepint** [comment]
What I think you are saying here is that you believe that an ISO8601 date must always include an offset. That is not the case. Per the standard, you can omit the offset, in which case the timestamp is interpreted as local time.

It is worth noting that an offset is not a time zone - I live in the America/Los_Angeles time zone, which sometimes has an offset of -8:00 and sometimes -7:00.

If you wanted to specifically validate the existence of an offset, then the following code would do the trick:

```
moment("2097-07-16T19:20:30.45", 'YYYY-MM-DDTHH:mm:ss.SSZ', true).isValid();
false
```

**Comment by sebs** [comment]
Thanks for answering. We had a lengthy discussion and I will pass on the info
