### ISSUE TITLE
locale bundling problem

### ISSUE THREAD

**Issue by timbell** [moment/moment#3623]
I implement locales as es6 modules in my application. Each locale module imports locale information from any 3rd party libraries used along with message translations etc. Activating a locale is done by importing the locale module (using systemjs) at runtime.

An example locale module (fr.ts):
```
import {IntlLocaleData} from '../services/intl-service'; // my locale data interface
import ng2IntlData from 'ng2-intl/locale-data/fr'; // locale data for ng2-intl library
import 'moment/locale/fr'; // moment's locale data (fr)
import messages from '../../../src/i18n/fr.json'; // my application messages (fr)

export default <IntlLocaleData>{
    // data for ng2-intl
    ng2Intl: {
        locale: "fr-FR",
        data: ng2IntlData
    },
    // moment locale name (data is auto defined by importing the moment locale)
    moment: {
        locale: "fr"
    },
    // my messages
    messages: messages
};
```
The problem I have is with the moment locale automatically calling moment.defineLocale when loaded. When I bundle my locale (using rollup) I make moment an external (I don't want to bundle an instance of moment with each locale) but then the call to defineLocale is problematic. I have worked around this by using rollup's ability to inject code into the generated bundle and creating a fake moment but it's pretty messy.

A big ask I know, but I wonder whether you would consider shipping an alternative version of the locale data which doesn't import moment and just returns the data? Something like this (eg locale-data/fr.js):
```
export default locale(moment) {
    return { // same object as is passed to defineLocale
        months : 'janvier_février_mars_avril_mai_juin_juillet_août_septembre_octobre_novembre_décembre'.split('_'),
        monthsShort : 'janv._févr._mars_avr._mai_juin_juil._août_sept._oct._nov._déc.'.split('_'),
        // etc...
    };
};
```

Files like these could be shipped next in a separate folder (eg locale-data) next to the current locale folder. To use you would do something like this:
```
import moment from 'moment';
import localeData from 'moment/locale-data/fr';

moment.defineLocale('fr', localeData(moment));
```
moment is passed in as a parameter to the locale function to allow access to moment. (The zh-cn locale uses moment in calendar.nextWeek/lastWeek.)

As I say, it's not a blocker for me, but I think there's merit to the approach?

**Comment by maggiepint** [comment]
I understand what you are saying, and I think we would take a pull for this. I don't think it will be a development priority for our core team unless there were quite a bit more interest.

**Comment by benkeen** [comment]
Funny - over 2 years on, but I just ran into precisely this same scenario with my own codebase. We're using webpack and I'm finding I'm having to explore similar workarounds.

Having the locale data exported just as data would solve it for me too.

**Comment by benkeen** [comment]
Would there still be any interest in a pull request for this? I'd be happy to put something in.  

The source code for the locales appears to be in this folder, e.g. Afrikaans:
https://github.com/moment/moment/blob/develop/src/locale/af.js

What we could do was create a new folder to house the standalone locale data, e.g.
`moment/locale-data/`

That would contain `af.js`, `fe.js` files etc in es6 format, with a default export like so: 

```
export default { 
    months : 'Januarie_Februarie_Maart_April_Mei_Junie_Julie_Augustus_September_Oktober_November_Desember'.split('_'),
    monthsShort : 'Jan_Feb_Mrt_Apr_Mei_Jun_Jul_Aug_Sep_Okt_Nov_Des'.split('_'),
    weekdays : 'Sondag_Maandag_Dinsdag_Woensdag_Donderdag_Vrydag_Saterdag'.split('_'),
   ...
}
```

Then the original source file (https://github.com/moment/moment/blob/develop/src/locale/af.js) would be changed to simply import the data from that source.

```
import moment from '../moment';
import af from '../locale-es6';

export default moment.defineLocale('af', af);
```

That'll allow people to import the locale data in plain es6 format and shouldn't affect any of the existing build code for moment.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
