### ISSUE TITLE
Precision for humanize(), toNow(), fromNow() and to() for months is wrong

### ISSUE THREAD

**Issue by tgelu** [moment/moment#3625]
``moment.duration(11, 'months').humanize(); // returns 'a year' instead of 11 months``

I am aware of the issue here https://github.com/moment/moment/issues/2542 but the whole discussion there is around minutes and seconds.

I believe that when talking about larger durations of time (like 11 months) it is expected that rounding is less precise, but there still is no reason to skip the 11 months step, and it is contrary to the docs. There (http://momentjs.com/docs/#/displaying/tonow/) it is stated that for ``45 to 345 days`` toNow() should return ``in 2 months ... in 11 months``. But the tests never expect that (https://github.com/moment/moment/blob/develop/src/test/moment/duration.js#L388), actually the contrary is expected: that 344 days duration returns 'a year'.
`` assert.equal(moment.duration({days: 344}).humanize(),    'a year',        '344 days = a year');``

So either the docs should reflect the reality at least, or momentjs should be able to return ``11 months`` for durations.

**Comment by maggiepint** [comment]
Using blame, I can see that this this has behaved this way for at least two years. Given that that is the case, I'm not inclined to change it. Rounding can always be customized. That said, would be happy to take a docs pull request.

**Comment by mj1856** [comment]
Fixed with moment/momentjs.com#378

**Comment by tgelu** [comment]
@maggiepint - makes sense :)
On another note: can you please help me understand how to customise the rounding? as you pointed out

**Comment by trevor-gullstad** [comment]
use humanize 
https://github.com/moment/moment/blob/e96809208c9d1b1bbe22d605e76985770024de42/src/lib/duration/humanize.js#L82
with custom thresholds
https://github.com/moment/moment/blob/develop/src/lib/duration/humanize.js#L4-L12
