### ISSUE TITLE
updateLocale does not keep the correct predefined locale but overwrites with default (en)

### ISSUE THREAD

**Issue by seriousManual** [moment/moment#3626]
**Description of the Issue and Steps to Reproduce:**

I wanted to update the 'monthShort' of the german Locale with the follwoging code:
```js
var moment = require('moment');

moment.updateLocale('de', {monthsShort: ["JAN", "FEB", "MÄR", "APR", "MAI", "JUN", "JUL", "AUG", "SEP", "OKT", "NOV", "DEZ"]});

var date = moment('2011-02-02');

date.locale('de');

console.log(date.format('YYYY MMM MMMM'));
````

Expected would be an output of '2011 FEB Februar', instead the output is '2011 FEB February'.
When updateing the 'monthsShort' key in the locale definition the resulting locale is not based on the german definition anymore but on the english Definition, hence 'Febraury' instead of 'Februar'.

**Environment:**

Node 6.3.1 on LInux

**Other information that may be helpful:**

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
//console.log( navigator.userAgent)
console.log(moment.version)
```
Mon Nov 28 2016 11:23:45 GMT+0100 (STD)
2016-11-28 11:23:45
-60
//omitted the 'navigator' potion
2.17.0

**Comment by seriousManual** [comment]
**Update:**

When the locale that is to be changed has been explicitly used prior to the 'changeUpdate' function call, the update works correctly:
```js
var moment = require('moment');

var date1 = moment('2011-02-02');
date1.locale('de');
console.log(date1.format('YYYY MMM MMMM'));

moment.updateLocale('de', {monthsShort: ["JAN", "FEB", "MÄR", "APR", "MAI", "JUN", "JUL", "AUG", "SEP", "OKT", "NOV", "DEZ"]});

var date = moment('2011-02-02');
date.locale('de');
console.log(date.format('YYYY MMM MMMM'));
```

**Comment by seriousManual** [comment]
**Update:**

I looked into this a bit more and came up with a possible solution:
![image](https://cloud.githubusercontent.com/assets/1330022/20666493/b43cdcbc-b564-11e6-8079-0bbd6525a2a5.png)

Let me know what you think and if I should do a PR.

**Comment by icambron** [comment]
Looks like a bug to me. I can't really comment on your specific proposed fix without spending some more time, but in general we'd take a PR for this.

**Comment by cmyers** [comment]
Been looking at bugs to work on and I see this one is still apparent can still be reproduced. I've refactored the above suggested solution and submitted a PR.
