### ISSUE TITLE
Locale short month: dots should not be required for parsing (error in monthsShort function call)

### ISSUE THREAD

**Issue by lstarky** [moment/moment#3629]
**Description of the Issue and Steps to Reproduce:**
In the Spanish locale, the `if (/-MMM-/.test(format)) {` test for `D-MMM-YYYY` format is **not** working for parsing, and therefore dates like `8-Dic-2016` result in `Invalid date`.  The format should be accepted.  `8-Dic.-2016` is parsed correctly, but is not the proper way of expressing a date in this format and the dot should not be required.

I've lived in Nicaragua for 16 years and the format `8-Dic-2016` is clearly the most common way of writing a shorthand date.  It's also highly preferred to use this type of format because in a mixed national/expat community using numbers-only dates is too confusing.

It appears that the problem is related to the fact that in line 19 of **es.js**, the test `if (/-MMM-/.test(format)) {` always comes up with an empty value for `format` when parsing.  Therefore, the use of `monthsShortDot` is always used and `monthsShort` is never used.  This is what is breaking the algorithm.  If format was passed correctly, it would select `monthsShort` and work properly.

**Environment:**
Chrome 54 on Windows 10

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

Console Log Output:
Tue Nov 29 2016 10:35:21 GMT-0600 (Central America Standard Time)
11/29/2016, 10:35:21 AM
360
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
2.15.1

```

**Comment by rhyek** [comment]
Just came across this issue as well.

```js
let str = moment(new Date(2016, 7, 2)).format('DD-MMM-YYYY'); // "02-ago-2016"
moment(str, 'DD-MMM-YYYY').month(); // 0 instead of 7
moment.monthsShort(); // ["ene.", "feb.", "mar.", "abr.", "may.", "jun.", "jul.", "ago.", "sep.", "oct.", "nov.", "dic."]
moment('02-ago.-2016', 'DD-MMM-YYYY').month(); // 7
moment.monthsShort('DD-MMM-YYYY'); // ["ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"]
```

**Comment by alexluecke** [comment]
This is still broken:

    let test = moment();
    test.locale('es');
    test.localeData().monthsShort(); // Uncaught TypeError: Cannot read property 'month' of undefined

**Comment by timfish** [comment]
This needs fixing. Anybody understand what's going wrong?

https://runkit.com/581ddb1783dafc001466d8e6/58bac4ef6fc4fc0014cc5b30/branches/master

**Comment by timfish** [comment]
`localeData().monthsShort()` also appears to be broken for:
- `es-do`
- `nl`
- `nl-be` 
- `fy`

Both `m` and `format` are undefined:

```
    monthsShort : function (m, format) {
        if (/-MMM-/.test(format)) {
            return monthsShort[m.month()];
        } else {
            return monthsShortDot[m.month()];
        }
    },
```

**Comment by marwahaha** [comment]
I agree this is a bit unusual. Perhaps we can make the dots optional for parsing? @julionc what is your recommendation?

**Comment by kkopanidis** [comment]
So, i was thinking of solving this issue as my first PR if that's ok. I took a look at the code, and i was thinking of changing the locale structure, by adding months regex like the nl locale does. Both the nl and es have the same needs concerning month format, and does not involve changing any other part of the locale or any parsing method.

**Comment by butterflyhug** [comment]
@kkopanidis Sounds great -- please do!  :grinning:
