### ISSUE TITLE
Grunt transpile with locales fails - missing parent locale

### ISSUE THREAD

**Issue by taneltm** [moment/moment#3631]
**Description of the Issue and Steps to Reproduce:**
1. ```git clone https://github.com/moment/moment.git```
2. ```git checkout tags/2.17.0```
3. ```npm install```
4. ```grunt transpile:en-gb,fi```

Expected:
* It to build moment-with-locales.custom.js with English and Finnish locales

Actual:
```
>> error transpiling-custom Error: You probably specified locales requiring parent locale, but didn't specify parent
>>     at /home/tanel/workspace/moment/tasks/transpile.js:284:23
>>     at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Environment:**
NodeJS 4.6.2 (also tried 6.9.1) on Debian 8.6

**Other information that may be helpful:**
* I actually needed a feature from moment v2.13.0 and that version transpiled just fine
* It seems to fail in the ```tasks/transpile.js``` at this check:
  ```if (moment.locales().length !== localeFiles.length)```
  I logged the arrays from moment.locales() and localeFiles before the IF statement, the result was:
  ```moment.locales(): [ 'en', 'en-gb', 'fi' ]```
  ```localeFiles: [ 'locale/en-gb.js', 'locale/fi.js' ]```
  So it seems like it's expecting a file ```locale/en.js``` to be listed under localeFiles, but that kind of file doesn't exist in the ```locale/``` directory.

**Comment by ichernev** [comment]
@taneltm thank you for the detailed error report. You're completely right -- the logic should avoid making an issue about `en`, I guess in certain cases it appears in the list (when I tested it didn't). We'll fix this in the next release. You can just use the generated files, the exception is just thrown FYI.
