### ISSUE TITLE
TS2503: Cannot find namespace 'moment'

### ISSUE THREAD

**Issue by valotas** [moment/moment#3636]
**Description of the Issue and Steps to Reproduce:**
I'm just trying to use moment within a `d.ts` file:

```
interface SomethingWithMoment {
    moment(): moment.Moment;
}
``` 

While compiling I get a `TS2503: Cannot find namespace 'moment'`.

I am not sure if it is a moment problem or a typescript one.

**Environment:**
moment 2.17.0
typescript 2.0.10

**Other information that may be helpful:**
Example project: https://github.com/valotas/ts-moment

**Comment by maggiepint** [comment]
See @blakeembrey in #3657
