### ISSUE TITLE
Moment does not get correct time when local time is wrong

### ISSUE THREAD

**Issue by vutaviva** [moment/moment#3639]
When the computer have wrong time (not synchronized with standard internet time), momentjs is also return this wrong time. I used moment() and moment.utc() function, but all of them is same result. How can I get global time independently with local time?

**Comment by icambron** [comment]
You'll have to get the current timestamp from some external service and pass it to Moment. Moment.js is just a convenient, value-added API around the native Date functionality the JS environment provides, so it only knows what your computer knows.

**Comment by vutaviva** [comment]
Yes, I see.
