### ISSUE TITLE
Missing Static Definition

### ISSUE THREAD

**Issue by patrickhousley** [moment/moment#3642]
The definition file is missing the definition of the moment function. Take a look at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/moment/moment.d.ts#L580. The below code complains that `moment` is not of Function type.

```
import Moment from 'moment/moment.d';
declare const moment: Moment.Moment;
let minDate = moment().add(9, 'days').toDate();
```

**Comment by butterflyhug** [comment]
The moment team supplies our own typings in this repo and I don't think we're involved with the DefinitelyTyped typings.  [Our own typings](https://github.com/moment/moment/blob/2.17.1/moment.d.ts) do include a definition of the `moment` function at the top of the file.

**Comment by patrickhousley** [comment]
Thank you @butterflyhug for your reply. I included the link to DefinitelyTyped for representational purposes. This is still an issue because the `Function` declaration in the definition file is not exported. This may be that I am missing something simple. However, I still cannot declare `moment` in my TypeScript file unless I give it a type of `any`. I would much prefer to give it a proper type. The below code does work for me but I would think it is not the right way to solve this issue.

```
import Moment from 'moment/moment.d';
declare const moment: (inp?: Moment.MomentInput, format?: Moment.MomentFormatSpecification, strict?: boolean) => Moment.Moment;
```

**Comment by DaSchTour** [comment]
@patrickhousley why do you import the typings and not the module itself, which also will import the typings and why do you try to declare moment although you already have typings?

**Comment by butterflyhug** [comment]
Well, if you have a specific proposed change to our typings to make them more usable then I think we'd be happy to look at a PR.  I still don't quite understand why our current typings don't already do what you want, but then I don't personally use Typescript much.
