### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'm.month()')

### ISSUE THREAD

**Issue by 42he** [moment/moment#3646]
**Description of the Issue and Steps to Reproduce:**

Moment.js used with full calendar in an rails app. 

TypeError: undefined is not an object (evaluating 'm.month()') occurs in function localeMonthsShort since Version Update from 2.11.1 to current. 

Happens with 

//= require moment
//= require moment/de-at.js
//= require moment/de.js
//= require moment/es.js
//= require moment/en-gb.js

from momentsjs-rails gem and also from moment-with-lang directly from here. 

*Please include the values of all variables used.*

**Environment:**

OSX Sierra, Safari and Chrome. 

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Using jquery-rails 4.2.1
Using jquery-ui-rails 6.0.1
Using jquery-timepicker-rails 1.11.4

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
"Tue Dec 06 2016 15:32:10 GMT+0100 (CET)"
console.log((new Date()).toLocaleString())
"6.12.2016, 15:31:59"
console.log( (new Date()).getTimezoneOffset())
-60
console.log( navigator.userAgent)
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
console.log(moment.version)
2.17.1
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by icambron** [comment]
Can you post a JSFiddle demonstrating the problem?

**Comment by marwahaha** [comment]
If you haven't used JSFiddle before, you can go to https://jsfiddle.net/ and add some Javascript that reproduces the error.

**Comment by icambron** [comment]
I'm actually just going to close this one
