### ISSUE TITLE
No way of getting original time

### ISSUE THREAD

**Issue by yrtimiD** [moment/moment#3647]
Moment provides two switches ".local()" and ".utc()" which changes the way how current moment object shows time.

Problem: if original input date was presented with a timezone different from UTC and local, I have no way to retrieve original time (format it).

```js
var date = moment("2016-12-06T15:00:00-02:00");
console.log(date.format("LTS")); //returns 19:00:00 if my timezone is +2, i.e. returns local time
```
sample code is at [https://jsfiddle.net/rz421ccj/4/](https://jsfiddle.net/rz421ccj/4/)

So, actually since moment object is created it is in "local" mode and can't be switched back to "original".

**Comment by maggiepint** [comment]
There is no original, but may I suggest that you look at ``.parseZone()``? That will probably do what you want.

**Comment by yrtimiD** [comment]
Yeah, that's exactly what I need. Sorry for invalid report. 
Maybe it's worth to mention `.parseZone()` in the Parse area of documentation?
