### ISSUE TITLE
Can not select anything on the home page (for copying) 

### ISSUE THREAD

**Issue by Starojitski** [moment/moment#3649]
**Description of the Issue and Steps to Reproduce:**
it's very difficult to select code examples on home page ( http://momentjs.com/ ). Before you even finish selecting something the selection is gone.

That's because the page is constantly refreshing itself to show actual current seconds in one of the examples. A gimmick that serves no real purpose and is counter productive. 

**Environment:**
Chrome 54 on OSX

**Comment by icambron** [comment]
See [this issue in the website's repository](https://github.com/moment/momentjs.com/issues/158)
