### ISSUE TITLE
Norwegian months double dots

### ISSUE THREAD

**Issue by kdichev** [moment/moment#3652]
I have something in the line of this:

`moment(this.state.returnTime).format('DD. MMM. HH:mm')}`

in norwegian the date is then compiled as such:

**09. des.. 17:00**

So I guess there is a hardcoded "des." in moment files for norwegian.

Can you guys advice me on how to remove this issue???

**Comment by icambron** [comment]
This is expected. For example, here is French:

```js
moment().locale('fr').format('DD. MMM. HH:mm')
"11. déc.. 20:30"
```

It's an odd format to internationalize: in most locales, "DD. MMM." wouldn't make much sense. Is this meant to be *only* used in `nb`? In which case, why not use `MMM` without adding the dot? And if not, is that really the format you want? We don't unfortunately have a month/day/time format that doesn't also include the year, but you might consider `LLL` anyway.

I will concede that some similar locales like `nn` put the dots in their `ll`-type formats but not in the actual short month names themselves, so perhaps some locales are a little inconsistent in that respect.

**Comment by kdichev** [comment]
The thing is that the solution is multi-language and multi country so the particular case is that in DK, SE there is no dot in the format in moment so our outputs are like:

after format of 'DD. MMM. HH:mm'

DK: 11. dec. 20:30
SE: 11. dec. 20:30
NO: 11. des.. 20:30

**Comment by maggiepint** [comment]
You can certainly customize the locale to omit the dots. See http://momentjs.com/docs/#/customization/month-names/

Unfortunately there's not much else to be done. In the locale space, there are a lot of matters of opinion.

**Comment by hozefaj** [comment]
What is the value for locale you are using for `no`. I have code 

```
expiryDate() {
    moment.locale(this.props.locale);
    const expiryDate = moment(new Date(this.props.details.offer_end_time));

    return (
      <p className="expiry">
        {this.props.staticContent.expiresOn}&nbsp;{expiryDate.format('LL')}
      </p>
    );
  }
```

But for `no` locale, I am seeing `June 5, 2017` being returned.
