### ISSUE TITLE
Implement type checking to allow calendar to specify config first

### ISSUE THREAD

**Issue by maggiepint** [moment/moment#3658]
Currently the API of ``moment().calendar()`` is specified as ``moment().calendar(moment-like, formats)``.

As pointed out in urish/angular2-moment#64, changing the formats is actually a much more common operation than changing the reference time.

It should be possible to use type checking to implement ``moment().calendar(formats)`` as an overload of this.

To accomplish this, ensure that exactly one parameter is specified, and that that one parameter has a type of object, and is NOT a ``moment``. If that is done, it should be reasonable to assume it is a format specifier.

**Comment by josephjaniga** [comment]
Found this issue report today and wrote up a fix, in the process of adding a few tests to the suite to cover my change.  Will put up my first ever PR shortly.

**Comment by josephjaniga** [comment]
Hm looks like I might be late to the party if I am reading this right.

**Comment by maggiepint** [comment]
Closed in favor of #3666
