### ISSUE TITLE
moment-tests.js error when publish project MVC

### ISSUE THREAD

**Issue by AdwardNguyen** [moment/moment#3660]
Error		Copying file Content\moment-develop\typing-tests\moment-tests.js to obj\Release\AspnetCompileMerge\Source\Content\moment-develop\typing-tests\moment-tests.js failed. Could not find file 'Content\moment-develop\typing-tests\moment-tests.js'.	

**Environment:**
Chrome OS windows 10 Pro
Visual Studio 2015, SQL Server 2014
Moment Js ver 2.16.0

**Comment by maggiepint** [comment]
We frankly have no way to debug this. This has something to do with your setup of your ASP.NET app, but almost certainly nothing to do with Moment. The only guidance I can give you is that you should only be copying a prebuilt file (moment.min.js), or your own build of the source, but certainly not any tests.

**Comment by CelzioBR** [comment]
Hi, i updated the momento to "moment": "^2.18.1", in bower and update the files.
