### ISSUE TITLE
Invalid relative path to locale files when using jsnext:main

### ISSUE THREAD

**Issue by tauren** [moment/moment#3661]
The relative path to locale files is invalid when imported with `jsnext:main`. The following line at https://github.com/moment/moment/blob/develop/src/lib/locale/locales.js#L55 attempts to load a locale file from `/src/lib/locale/...`, which doesn't exist. It should reference the `/locale` folder (at the project root). 

```js
// /src/lib/locale/locales.js line 55
require('./locale/' + name);
```

I'm creating this issue for better visibility even though the problem has been brought up before by @farwayer as a comment buried in another issue:
https://github.com/moment/moment/issues/3104#issuecomment-259411592

I'm not sure how to best solve this so that the `jsnext:main` module works without breaking `/moment.js`, `/min/moment.min.js`, and the other bundled modules. I'm willing to work on a PR if one of the maintainers would give some advice on a solution that would be acceptable.

**Comment by randing89** [comment]
Still having the same problem

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
