### ISSUE TITLE
Wrong year when we get the fomat with week and the year of a date at the end of year and this date is week 1.

### ISSUE THREAD

**Issue by jare-talend** [moment/moment#3665]
**Description of the Issue and Steps to Reproduce:**
Wrong year when we get the fomat with week and the year of a date at the end of year and this date is week 1.

When the week and the year is called, Moment should be increment the year when the week is transformed to 53 to 1.

*Please include the values of all variables used.*
new Date(-259200000) // returns Mon Dec 29 1969 01:00:00 GMT+0100 (CET)
moment(-259200000).format('W YYYY'); //return 1 1969

It should return 1 1970

**Environment:**
all environnement

Fri Dec 16 2016 10:12:01 GMT+0100 (CET)
VM376:3 16/12/2016 à 10:12:01
VM376:4 -60
VM376:5 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36
VM376:6 2.17.1

**Comment by butterflyhug** [comment]
`YYYY` is specifically the calendar year.  You'll want to use `GGGG` to get the ISO week year instead.
