### ISSUE TITLE
Moment creates invalid dates when using locale formatted string

### ISSUE THREAD

**Issue by roxanabalag** [moment/moment#3669]
[JSFiddle](https://jsfiddle.net/1s6ump7j/)

Formatting a moment based on its locale and creating a moment object from the formatted one results in an invalid moment.
I would have expected locale formats to be taken into account when creating the moment. Is my assumption wrong?

Similar, perhaps related, to #3487?

```
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
Outputs

> Mon Dec 19 2016 22:26:20 GMT+0000 (GMT Standard Time)
> 19/12/2016, 22:26:20
> 0
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
> 2.17.1

**Comment by icambron** [comment]
Moment does't know how to parse arbitrarily formatted strings. This should work though:

```js
 var m = moment(formatted, "L");
```

**Comment by roxanabalag** [comment]
Why is using a format from a locale (which is set and expected to be used globally) considered arbitrary formatting?

**Comment by icambron** [comment]
First because it's not going to speculatively parse "L", "LL", "LLL", "LLLL", "l", "ll", "lll", "llll", "LT", and "LTS" just in case that's what you happened to pass. Second, it would be pretty weird for the formats of accepted to be contingent on some global state; that's a recipe for confusion.

**Comment by roxanabalag** [comment]
Thank you for the information. Keep up the good work!
