### ISSUE TITLE
Wrong week number.

### ISSUE THREAD

**Issue by luisaceituno** [moment/moment#3670]
**Description of the Issue and Steps to Reproduce:**
```js
console.log(moment('2017-01-01').startOf('week').format('W/YYYY'));
```

The expected output is either `1/2017` or `52/2016`.
The actual output is `52/2017`, which is a combination of both.

Maybe the start of week is different when setting it and when calculating the week number?

I'm running moment.js with TypeScript in an Angular 2 application, but I've reproduced this issue without TypeScript too. Using Windows 10 x64 and Chrome. 

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
Tue Dec 20 2016 18:38:30 GMT+0100 (Mitteleuropäische Zeit)
console.log((new Date()).toLocaleString())
12/20/2016, 6:38:30 PM
console.log( (new Date()).getTimezoneOffset())
-60
console.log( navigator.userAgent)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
console.log(moment.version)
2.17.1
```

**Comment by luisaceituno** [comment]
My bad, the uppercase W is for ISO week, while startOf('week') isn't setting the ISO week. startOf('isoWeek') should have been used.

**Comment by butterflyhug** [comment]
Also, `GGGG` is the token for ISO week year -- `YYYY` is always the calendar year, which may not match the ISO week number from `W`.
