### ISSUE TITLE
duration#locale exists but not documented

### ISSUE THREAD

**Issue by jmm** [moment/moment#3673]
With moment@2.17.1, `duration#locale` exists ([demo](https://runkit.com/585075bc6eea770014d02340/585ae9ef6966c40014536d45)), but it doesn't seem to be documented. It would be useful, and I've seen it in the wild. If it's intended to be part of the public API, can you please document it? If not, can you please say why? I need locale aware humanization of a duration (e.g. I have a value in seconds) and would like to do:

```js
moment.duration(duration, "seconds").locale(locale).humanize(true)
```

But since it's not documented as public API I'm currently faking it by generating 2 fictitious dates and using `moment#from`.

**Comment by jmm** [comment]
I realized that to support the usage in the example (chaining `locale(locale).humanize()` would also require documenting that `moment#locale|duration#locale` return the instance they were called on.

**Comment by icambron** [comment]
I don't think there's a reason it's not document. We'd take a PR to the [docs repository](https://github.com/moment/momentjs.com) documenting it.

**Comment by jmm** [comment]
Great, thanks @icambron! If someone else is up for it before me (no telling when that'll be), that'd be super (please make sure to document return value of `locale()` methods in the process). There's only an individual CLA, no corporate one?

**Comment by icambron** [comment]
I'll defer to @maggiepint on the CLA question

**Comment by marwahaha** [comment]
@jmm We'd love some documentation!

**Comment by reznord** [comment]
@marwahaha I would be happy to help with this. This would be my first contribution to moment library.

**Comment by marwahaha** [comment]
Great @reznord --- the repo for the website is here: https://github.com/moment/momentjs.com

Run it locally, make changes, and submit a PR . Feel free to reach out if you're having trouble.

**Comment by marwahaha** [comment]
This is still up-for-grabs!

**Comment by erikasf** [comment]
Hi, I would like to try my hand at it. I'll do the above and submit a PR this week.

**Comment by malashkevich** [comment]
Hey guys.
There is existing PR (https://github.com/moment/momentjs.com/pull/429)
I think it's time to close this issue and merge mentioned PR.

**Comment by marwahaha** [comment]
http://momentjs.com/docs/#/durations/locale/
