### ISSUE TITLE
import locale file too large

### ISSUE THREAD

**Issue by yeluoqiuzhi** [moment/moment#3674]
I use webpack bundle my project, vendor file size increase to 300KB, just by adding one line:

```
import 'moment/locale/zh-cn'
```

but there is no other dependencies in zh-cn.js.
Not only zh-cn, but also other locale file lead to this problem, why?

**Comment by nealoke** [comment]
Having the same issue when importing moment. My file sizes goes from 1.94 MB to **2.44 MB** ?! Removing the import, the file sizes goes back to normal (1.94)....

`import moment from 'moment';`

**Comment by yeluoqiuzhi** [comment]
```
import moment from 'moment';
```
looks good here

**Comment by nealoke** [comment]
@yeluoqiuzhi what version are you using? Can it be because of the devtools webpack provides?

**Comment by yeluoqiuzhi** [comment]
I am using webpack2, I have a look at my bundle result.

I only import 'moment/locale/zh-cn', but all locale file is bundled into result file.

**Comment by yeluoqiuzhi** [comment]
There is  dynamic require in source code of moment. It will lead to create a context in webpack.
Webpack will bundle all file under that context, so...

```js
require('./locale/' + name);
```

I have solved this by applying a webpack plugin(Is it a hack?).

```js
plugins: [
            new webpack.ContextReplacementPlugin(/^\.\/locale$/, context => {
                // check if the context was created inside the moment package
                if (!/\/moment/.test(context.context)) { return }
                // context needs to be modified in place
                Object.assign(context, {
                    // include only japanese, korean and chinese variants
                    // all tests are prefixed with './' so this must be part of the regExp
                    // the default regExp includes everything; /^$/ could be used to include nothing
                    regExp: /^\.(zh-cn)/
                })
            })
        ]
```

Now, it will bundle only zh-cn.js. looks goods.

**Comment by maggiepint** [comment]
It looks like you worked around so closing. For what it's worth, issues like this are usually better addressed to the WebPack team. We don't use it, so we don't know what doesn't work.
