### ISSUE TITLE
Not a year but shows "a year ago"

### ISSUE THREAD

**Issue by cxgreat2014** [moment/moment#3679]
```
>_ moment('2016-02-24').fromNow()
"10 months ago"
>_ moment('2016-01-24').fromNow()
"a year ago"
```
???
now is 1016/12/24, '2016-01-24' from now is 11 month, why show a year ago?

**Comment by maggiepint** [comment]
This is working as designed per the documentation for From Now. It is not meant to be exact. If you wish to customize, the documentation for that is here: http://momentjs.com/docs/#/customization/relative-time-rounding/
