### ISSUE TITLE
Compressing unix Timestamp

### ISSUE THREAD

**Issue by aakashrathore** [moment/moment#3682]
Hey,
 I was wondering if there is a way to compress UNIX timestamps to "Human Readable characters." For eg: compressing 14,000,000,000 to 14B. 
So I am basically designing a timeline which displays dates from the start of the universe to the time you're reading this. Since date datatype cannot display dates at the start of the universe I am using Unix timestamps to display astronomical dates. here is a screenshot.
<img width="1436" alt="screen shot 2016-12-26 at 6 20 07 pm" src="https://cloud.githubusercontent.com/assets/11655317/21488079/fb0297ba-cb97-11e6-98d5-e996cfd4f7aa.png">
In the screenshot, as you can see, the numbers are huge and I would like to compress them. like 14,000,000 would be 14M and 13,800,000,000 would be 13.8B.
All I need to know if there is a way to customize the timestamp or an event handler in the library that'd let me handle the times before displaying. By "handle", I mean that the event handler would provide me the timestamp and I could parse it as needed and then return the String which would take place of the original timestamp without disrupting the sequence of numbers.
**Environment:**
browser: chrome(for dev), and OS: Linux based server.

**Comment by icambron** [comment]
I'm not sure what you mean by event handler; Moment just has functions to return things and you can of course parse them as you see fit.

```js
var timestamp = someMomentObject.valueOf();
yourPrettifyFunction(timestamp);
```

Perhaps there's some context I'm missing?

**Comment by aakashrathore** [comment]
What exactly are you doing here? Sorry but I couldn't understand what you meant there.

**Comment by icambron** [comment]
I probably just don't understand your question. What are you hoping Moment can do for you?

**Comment by aakashrathore** [comment]
Sorry if i wasn't clear. You can close the issue since i figured it out.
