### ISSUE TITLE
Contribution Opportunity!

### ISSUE THREAD

**Issue by tarang9211** [moment/moment#3684]
Hey guys! 
I was looking through the issue but could not find any **beginner** or **first-time-contributor** labels to get started with contributing here. Could someone point me to some of those issues? I know there is a **Up-for-grabs** label, but wasn't sure if that is good for someone new to the repo.

**Comment by maggiepint** [comment]
Up-for-grabs means that we welcome community contributions. At a glance, most of the ones labeled bug right now are fairly reachable.
