### ISSUE TITLE
`isUtc()` does not seem to be working

### ISSUE THREAD

**Issue by kamranahmedse** [moment/moment#3687]
Please find the steps to reproduce below

```javascript
var utcDate = '2016-12-28T06:40:28Z';
moment(utcDate).isUtc();   // returns false
```

Even it is not recognizing `moment` generated UTC dates as UTC, see

```javascript
var utcDate = moment.utc().format();
moment(utcDate).isUtc();    // returns false
```

What am I missing here?

**Comment by maggiepint** [comment]
This function isn't looking for an offset of `z`. It is looking to see if the moment object itself is in UTC mode, and thus computations are being performed in UTC. See:

http://momentjs.com/guides/#/parsing/local-utc-zone/

https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/
