### ISSUE TITLE
Moment included twice in webpack bundle

### ISSUE THREAD

**Issue by astrebel** [moment/moment#3690]
**Description of the Issue and Steps to Reproduce:**
I'm using moment and want only import one locale. I'm doing this with the webpack IgnorePlugin.

`new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)`

In my typescript file I import moment and the locales like this.
```
import * as moment from 'moment';
import 'moment/locale/de';
```
This works fine except that webpack includes moment twice due to my import of moment and a second import in the locale file. So there are two require that look like this:

`require('moment')` - my import
`require('../moment')` - the import in the locale file

Webpack doesn't seem to see that it's the same module and includes it twice which is a problem since the "de" locale will only be added to the module imported in the locale file. So the moment module used everywhere else doesn't have the new locale.

I even tried to use the `new webpack.optimize.DedupePlugin()` which removes the duplicate but still creates two instances of the same module. Which again creates the same problem.

**Environment:**
webpack 1.4.15
moment 2.17.1
typescript 2.1.4

**Comment by Bnaya** [comment]
Something you can try:
on webpack alias set '../moment' to to point to 'moment'

**Comment by maggiepint** [comment]
I'm going to close this one because we really don't have a ton of expertise in webpack around here. I think the best case at this point is for you to go to them.
