### ISSUE TITLE
8 tests failed. create:parsing week and weekday information (2397.1) create:parsing week and weekday information (2397.2) create:parsing week and weekday information (2397.3) create:parsing week and weekday information (2397.4) create:parsing week and weekday information (2397.5) create:parsing week and weekday information (2397.6) create:parsing week and weekday information (2397.7) create:parsing week and weekday information (2397.8) 

### ISSUE THREAD

**Issue by joaxazevedo** [moment/moment#3691]
### Client info
```
Date String   : Thu Dec 29 2016 10:59:17 GMT-0300 (Hora oficial do Brasil)
Locale String : 29/12/2016 10:59:17
Offset        : 180
User Agent    : Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.28 Safari/537.36
Moment Version: 2.17.1
```

====

### create:parsing week and weekday information (2397.1) 

compare: week-year two digits

```javascript
// Expected 2012 12 30
// Actual   Invalid date
"Invalid date" === "2012 12 30"
```

====

### create:parsing week and weekday information (2397.2) 

round trip: week-year two digits

```javascript
// Expected 12
// Actual   Invalid date
"Invalid date" === "12"
```

====

### create:parsing week and weekday information (2397.3) 

compare: week-year four digits

```javascript
// Expected 2012 12 30
// Actual   Invalid date
"Invalid date" === "2012 12 30"
```

====

### create:parsing week and weekday information (2397.4) 

round trip: week-year four digits

```javascript
// Expected 2012
// Actual   Invalid date
"Invalid date" === "2012"
```

====

### create:parsing week and weekday information (2397.5) 

compare: week-year two digits previous year

```javascript
// Expected 1999 12 26
// Actual   Invalid date
"Invalid date" === "1999 12 26"
```

====

### create:parsing week and weekday information (2397.6) 

round trip: week-year two digits previous year

```javascript
// Expected 99
// Actual   Invalid date
"Invalid date" === "99"
```

====

### create:parsing week and weekday information (2397.7) 

compare: week-year four digits previous year

```javascript
// Expected 1999 12 26
// Actual   Invalid date
"Invalid date" === "1999 12 26"
```

====

### create:parsing week and weekday information (2397.8) 

round trip: week-year four digits previous year

```javascript
// Expected 1999
// Actual   Invalid date
"Invalid date" === "1999"
```

**Comment by marwahaha** [comment]
@nwhittaker does your commit fix the above unit tests?

**Comment by nwhittaker** [comment]
@marwahaha no, I would not expect it to.

**Comment by marwahaha** [comment]
I'm going to close this. Hopefully this has been resolved in recent releases. If not, feel free to re-open or file a new ticket.
