### ISSUE TITLE
use "isFunction" insteadof "instanceof Function" 

### ISSUE THREAD

**Issue by zhaoyihong** [moment/moment#3693]
why not use "isFunction" insteadof "instanceof Function"  in https://github.com/moment/moment/blob/develop/moment.js#L647 ? 
I meet some problem when instanceof Function return false.
isFuntion:https://github.com/moment/moment/blob/develop/moment.js#L340

thank you!

**Comment by icambron** [comment]
AFAIK, no reason -- it should use `isFunction()`

**Comment by mj1856** [comment]
Close in favor of PR #3712.  Thanks.
