### ISSUE TITLE
Setting year and week at the same time may lead to incorrect year

### ISSUE THREAD

**Issue by fkaempfer** [moment/moment#3694]
**Description of the Issue and Steps to Reproduce:**
This is something I noticed, which only happens on the last day of the year 2016 (I pass new Date().getTime()) to the constructor to reproduce:

moment(1483173987487).set({year:2017,week:3}).toDate()
> Sun Jan 14 2018 09:46:27 GMT+0100 (CET)

Is this the expected result? I think it should be the 3rd week of 2017 not 2018.

The same thing happens when you do moment(..).year(2017).week(3) 

**Environment:**
Chrome Fedora24 55.0.2883.87 (64-bit)

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
GMT+1
* The time and date at which the code was run
31/12/2016 9:50

console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

Sat Dec 31 2016 09:51:32 GMT+0100 (CET)
VM3134:2 31.12.2016, 09:51:32
VM3134:3 -60
VM3134:4 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
VM3134:5 2.17.1

```

**Comment by icambron** [comment]
You can't mix weeks and calendar years like that, because `moment(1483173987487).set({year: 2017})` is actually in the 2018 week year. Just use `weekYear`:

```js
moment(1483173987487).set({weekYear: 2017, week: 3}).format(); // => "2017-01-21T03:46:27-05:00"
```

**Comment by fkaempfer** [comment]
Thanks for the explanation!
