### ISSUE TITLE
Is it possible to modify moment constructor?

### ISSUE THREAD

**Issue by timpler** [moment/moment#3698]
I'd like to modify moment constructor so it'll use [https://sugarjs.com/dates/](url) to be able to perform advanced parsing of human-readable dates.

It would make possible to do something like:
`moment('next friday').isBefore('next saturday'); // true`

Parsing of input string is done like:
```
import SugarDate from 'sugar/date';
SugarDate.create('next friday'); // native date object
```

Some 'filter hook' that would be able to perform some operations on input would do the job too. eg:

```
moment.on('beforeCreate', (input) => {
  if (typeof input === 'string') return SugarDate.create(input);
  return input;
});
```

**Comment by butterflyhug** [comment]
If I were you, I'd personally write this as a simple global function that returns a moment:

```js
function parseMoment(input) {
  if (typeof input === 'string') {
    return moment(SugarDate.create(input));
  }
  return moment.apply(null, arguments);
}
```

And then your example becomes:  
`parseMoment('next friday').isBefore(parseMoment('next saturday'))`;

It is technically possible to swap out the `moment` function and copy all the Moment APIs onto your customized constructor, but I really wouldn't recommend it.  It's a bit harder to write that correctly.  That sort of change might break plugins and other third-party code that assume moment will behave as documented. Also, we don't guarantee that implicitly created moments will be constructed using the public API, so changing the constructor might not change the parsing behavior of `isBefore` (and even if that works now, it might break without warning in future versions).

We don't currently have any hooks to customize the parser like this.  A more extensible parser might happen someday, but it's not a top priority right now.

Feel free to reply if you have further questions.
