### ISSUE TITLE
Missing 'weeks' option

### ISSUE THREAD

**Issue by battmanz** [moment/moment#3702]
**Description of the Issue and Steps to Reproduce:**

In the moment.d.ts typings file, either the `MomentInputObject` or the  `DurationInputObject` interface (I don't know which one it should be) is missing the weeks options. I.e.

    interface MomentInputObject { // or DurationInputObject
      ...
      weeks?: number;
      week?: number;
      w?: number;
    }

I would be happy to submit a pull request if someone could tell me which interface it belongs in.

**Comment by maggiepint** [comment]
I'm not a typescript developer, but I believe you want this on duration. Moment construction objects don't take weeks.
