### ISSUE TITLE
Long date format without meridiem, hour, minute

### ISSUE THREAD

**Issue by pzheng64** [moment/moment#3705]
**Description of the Issue and Steps to Reproduce:**
Is there any way to have long date format without time?

*Please include the values of all variables used.*
I'd like to get output like the follow one's except last part (meridiem, hour, minute)
```js
moment().format('LLLL');
```

For example, 
locale=zh-hk: YYYY年MMMD日dddd
locale=en-au: dddd, D MMMM YYYY

I can use this for Western locales, but it does not look good for Eastern locales.
```js
moment().format('dddd, LL'); 
```

**Environment:**
Any environment

**Comment by maggiepint** [comment]
If the pre-defined locale based formats don't have what you want, then they don't have what you want. You can customize the locales to have additional/different formats using the `.updateLocale` function. Perhaps you could simply update the locales you are using?

**Comment by pzheng64** [comment]
I'd like to have this in next release of momentjs.
