### ISSUE TITLE
Year incorrect when formatting as weeks

### ISSUE THREAD

**Issue by iamdriz** [moment/moment#3711]
If I have: `moment('2016-01-01', 'YYYY-MM-DD').format('YYYY-WW');`

I should be getting `2015-53` but get `2016-53`

Likewise if I do: `moment().startOf('month').format('YYYY-WW');` (time of question, 10 Jan 2017)

I should be getting `2016-52` but get `2017-52`

So the week numbers are correct, but the year is coming back incremented by 1...

Update: I've just realised I asked a similar question here: https://github.com/moment/moment/issues/3552 where changing `YYYY` to `GGGG` solves it.

**Comment by maggiepint** [comment]
Yes, you need to use a week-year token, so `GGGG`
