### ISSUE TITLE
Allow .diff() with limited precision

### ISSUE THREAD

**Issue by 4rlekin** [moment/moment#3713]
**Description of the Issue and Steps to Reproduce:**

Currently, if for instance we want to diff on days level (`a.diff(b, 'days')`) the diff checks for 24h period.
While in and of itself it is of course a valid behavior i found it confusing, since i expected that diffing on "days level" will basically check for the date only, regardless of actual time passed.

This behavior is illustrated by this code:  
```
console.log("no hours set");
var a = moment([2007, 0, 29]);
var b = moment([2007, 0, 28]);
console.log(a.diff(b, 'days')); // 1

console.log("same hours set");
a = moment([2007, 0, 29, 12]);
b = moment([2007, 0, 28, 12]);
console.log(a.diff(b, 'days')); // 1

console.log("more than 24h apart");
a = moment([2007, 0, 29, 12]);
b = moment([2007, 0, 28, 10]);
console.log(a.diff(b, 'days')); // 1

console.log("almost 48h apart");
a = moment([2007, 0, 29, 23]);
b = moment([2007, 0, 28, 1]);
console.log(a.diff(b, 'days')); // 1

console.log("less than 24h apart");
a = moment([2007, 0, 29, 12]);
b = moment([2007, 0, 28, 14]);
console.log(a.diff(b, 'days')); // 0 say whaaaat ?!
````  

So all works as expected, except when there is less than 24h between compared dates it treats it as if there wasn't any days of difference, even if between two dates midnight passed.
So it isn't all that useful, since if you just want to know if something happened yesterday you still need to write some chain of methods such as:  
```
var now = moment();
var orderDate = moment(date);
var daysDiff = now.startOf('day').diff(orderDate, 'hours');
```

**Conclusion**
I'd like to know if that would be considered as legitimate issue and in such case i'd be willing to make PR solving that - provided someone would guide me a little, since i never made any PRs to moment.js (or anything for that matter).

Cheers.

**Comment by mj1856** [comment]
This already exists, in that you can pass a `true` flag as a third parameter, and it will return with decimals.

```js
var a = moment([2007, 0, 29, 12]);
var b = moment([2007, 0, 28, 14]);
console.log(a.diff(b, 'days', true));  // 0.9166666666666666
```

You could round up if you like.
```js
var a = moment([2007, 0, 29, 12]);
var b = moment([2007, 0, 28, 14]);
console.log(Math.ceil(a.diff(b, 'days', true))); // 1
```

As far as adding a built-in way of rounding up automatically, I think that would be inconsistent with the definition of the function.  It's not measuring how many units have changed between two values, but how much actual whole units of difference there are between them.

As an analogy, consider that `2.1 cm - 1.9 cm = 0.2 cm`.  The ones place is a whole number off, but that doesn't make them 1 cm apart.

Thanks.

**Comment by 4rlekin** [comment]
@mj1856 I see, its alright then.
Could i bother you to point me to some issue i could contribute on ? Preferably something that would be reasonable for a first contribution to project (i don't grok the codebase yet)
