### ISSUE TITLE
[Enhancement] combination of format localized

### ISSUE THREAD

**Issue by Jerome2606** [moment/moment#3715]
It would be nice to have the possibility to combine localized format

http://momentjs.com/docs/#localized-formats

for example:
be able to do something like:

moment().format('L LT')

**Comment by icambron** [comment]
I don't think that's a good idea for a few reasons:

 1. First, `moment().format('L LT')` actually does something. In English, it produces `"01/16/2017 9:00 PM"` and it would be weird if it did anything else, e.g. "you put a space between two format tokens but we decided you actually wanted something else"

 2. Each locale would need to provide abstract rules for combining arbitrary formats. This sounds hard to do on an individual locale level, not to mention for the entire set of them.

 3. Avoiding this kind of thing is why we ended up with some many formats in the first place. That wasn't necessarily the wisest approach but at this point we'll stick with it.
