### ISSUE TITLE
TypeScript definition file misses weekDays*(localeSorted: boolean) function overloads

### ISSUE THREAD

**Issue by cervengoc** [moment/moment#3719]
The current version's `moment.d.ts` file misses the above mentioned function overloads.

**Comment by marwahaha** [comment]
Happy to take a PR!

**Comment by 77ganesh** [comment]
Is this the same?

https://github.com/moment/moment/blob/7ff10bd598a68905c9f2f45683b1aab1be3f8736/moment.d.ts#L662-L665

**Comment by ovangle** [comment]
Yeah, the functions are already there, it's just inconsistent capitalization between `weekday` and `weekYear`.

**Comment by 77ganesh** [comment]
Do you plan to make it consistent? But that will mean breaking changes right?

**Comment by ovangle** [comment]
I don't think so, it's unlikely to be a potential source of bugs. 

It's also difficult to know what axis to standardise it on -- weekday is a common english word, whereas weekyear isn't. No matter what you do you're going to displease somebody, so I think preserving the status quo is the most sensible course of action.

**Comment by 77ganesh** [comment]
haha true!
