### ISSUE TITLE
unexpected isValid() == true for date

### ISSUE THREAD

**Issue by aikomastboom** [moment/moment#3720]
**Description of the Issue and Steps to Reproduce:**

```js
var moment = require('moment');
var date = moment().set({'year':'year','month':'month','date':'day'});
date.isValid() // true
```

*Please include the values of all variables used.*

**Environment:**
moment@2.17.1",
$ node -v
v6.5.0

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
> var moment = require('moment');
> console.log( (new Date()).toString())
Wed Jan 18 2017 16:01:31 GMT+0100 (CET)
> console.log((new Date()).toLocaleString())
1/18/2017, 4:01:31 PM
> console.log( (new Date()).getTimezoneOffset())
-60
> console.log( navigator.userAgent)
ReferenceError: navigator is not defined
> console.log(moment.version)
2.17.1
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

```
$ node -e "console.log(require('moment')().set({'year':'year','month':'month','date':'day'}).isValid());"
true
```

**Comment by mj1856** [comment]
Thanks.  This has been reported already.  See #3483.  A fix is pending with #3704 in the next release.

Also, if you are actually passing input in that way, you shouldn't start with `moment()` - that initializes everything with the current time.  Instead, just pass the object in to begin with.

```js
moment({'year': 2017, 'month': 0, 'date': 30}).isValid() // true
moment({'year': 'foo', 'month': 'bar', 'date': 'baz'}).isValid() // false
```
