### ISSUE TITLE
Issue with .add(x, 'days')

### ISSUE THREAD

**Issue by sylvainbx** [moment/moment#3721]
I have a strange behavior when adding days to a moment.

Please see the code in [this Plunker](https://plnkr.co/edit/e1idiUSbDlj94gmJPHSZ), it simply adds one more day per cycle to a moment.
You can see in the console that everything goes fine until `Tue Jan 17 2017 01:00:00 GMT+0100 (CET)`, but just after, adding one more day, the moment return to the date of `Sun Dec 04 2016 01:00:00 GMT+0100 (CET)`.

**Environment:**

Node.js 6.9.1, also seen with Chromium 55 on Ubuntu 16.04 when running the attached plunker.

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on: **Europe/Paris**
* The time and date at which the code was run: **2017-01-19 17:39:19 (UTC+0100)**

Here's the environment info:
```js
console.log( (new Date()).toString())
// Wed Jan 18 2017 17:40:54 GMT+0100 (CET)
console.log((new Date()).toLocaleString())
// 2017-01-18 17:40:54
console.log( (new Date()).getTimezoneOffset())
// -60
console.log( navigator.userAgent)
// ReferenceError: navigator is not defined
console.log(moment.version)
// 2.16.0
```

**Comment by mj1856** [comment]
Sorry, I'm unable to reproduce.  The script just emits the days from Dec 4 through Jan 17.  It doesn't produce any further output.
