### ISSUE TITLE
Several locales are broken in locales.min.js

### ISSUE THREAD

**Issue by SDKiller** [moment/moment#3725]
See lines 94-95:

https://github.com/moment/moment/blob/develop/min/locales.min.js#L94-L95

Line 94 referres to `ru` locale, but it is not finished, on line 95 it continues with words from probably `sk` locale.

**Comment by SDKiller** [comment]
Anyway, I suppose it's worth investigating what actually caused trouble with minification (e.g. comments, some special characters, etc.) - as this may happen in some other place.

**Comment by marwahaha** [comment]
Is anything broken?
