### ISSUE TITLE
First Monday on January 1 2017 is wrong

### ISSUE THREAD

**Issue by mpalese** [moment/moment#3728]
**Description of the Issue and Steps to Reproduce:**
The first Monday if the date is the first day of the month and is Sunday get the next day and not the previous Monday
```js
var firstOfMonth = moment('2017-01-01');//the same with 2016-05-01
var firstMonday = firstOfMonth.clone().day(1);//get 2017/01/02
console.log(firstMonday.toDate());
```

**Environment:**
Chrome 55, IE 11 on Windows 8.1 64bit

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
Timezone machine (UTC+01:00) Amsterdam, Berlino, Berna, Roma, Stoccolma, Vienna
Timezone moment (UTC+01:00) Europe/Rome

**Comment by mj1856** [comment]
I see nothing wrong here.  You are within the week from `2017-01-01` through `2017-01-07`.  The Monday within that week is `2017-01-02`.
