### ISSUE TITLE
defineLocale superseeds new properties

### ISSUE THREAD

**Issue by sentient06** [moment/moment#3729]
When attempting to create a new locale like this:

        moment.defineLocale('en-uk-m', {
            parentLocale: 'en',
            week : {
                dow: 6 // Saturday is the first day of the week.
            },
            monthsShort: "jfmamjjasond".split("")
        });
        let date = moment('2011-02-02');
        date.locale('en-uk-m');
        console.log(date.format('YYYY MMM MMMM'));

Saturday is correctly defined as the first day of the week and the output of that console log is "2011 f February" as expected.

However, when doing this (please note: the new parentLocale is `en-gb`):

        moment.defineLocale('en-uk-m', {
            parentLocale: 'en-gb',
            week : {
                dow: 6 // Saturday is the first day of the week.
            },
            monthsShort: "jfmamjjasond".split("")
        });
        let date = moment('2011-02-02');
        date.locale('en-uk-m');
        console.log(date.format('YYYY MMM MMMM'));

The first day of the week is Sunday and the console output is "2011 Feb February".

**Environment:**

Chrome 55 and Firefox 50 on OSX.

Machine running on GMT time zone. Using MomentJS with "React Datepicker".

I believe this issue is connected to issue #3626. That one is about `updateLocale`, but this one is about `defineLocale`. Perhaps it can be considered the same bug? I don't know.

Cheers!

**Comment by icambron** [comment]
This worked fine, for me, actually. I modified it slightly to confirm the inheritance was working:

```js
    moment.defineLocale('en-uk-m', {
        parentLocale: 'en-gb',
        week : {
            dow: 6 // Saturday is the first day of the week.
        },
        monthsShort: "jfmamjjasond".split("")
    });
    date = moment('2011-02-03');
    date.locale('en-uk-m');
    console.log(date.format('L YYYY MMM MMMM'));
```

Then I pasted it into the console [here](http://momentjs.com/docs/) and got:

```
03/02/2011 2011 f February
```

Are you running the latest version of Moment?

**Comment by icambron** [comment]
Closing just to clean up some tickets. Mention me in a response and I reopen and reply.

**Comment by sentient06** [comment]
Hello, I had to re-visit this issue due to an update in the system I've been working on. I tried your code and got `02/03/2011 2011 Feb February`. Any clues why won't that work?
