### ISSUE TITLE
.diff with undefined values

### ISSUE THREAD

**Issue by thec0keman** [moment/moment#3730]
When using `diff` and `undefined` moment returns 0.  My assumption was it would function like `null` and return `NaN`.  Is this the expected behavior?

```
moment().diff(null)                // => NaN
moment().diff(undefined)           // => 0
```

This is in Chrome 55 on OSX inside of an Ember.js app (2.10).

Environment info:
```
Tue Jan 24 2017 12:39:41 GMT-0800 (PST)
1/24/2017, 12:39:41 PM
480
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
2.17.1
```

Thanks!

**Comment by maggiepint** [comment]
That API expects a moment-like object. When it doesn't receive one, it falls back to the current time. Because passing undefined in JavaScript is the moral equivalent of passing nothing, it's falling back to now, and of course the difference between now and now is zero.

**Comment by thec0keman** [comment]
@maggiepint thanks for the helpful explanation!  It makes sense that `moment(null)` is very distinct from `moment(undefined)` and `moment()`.
