### ISSUE TITLE
duration humanize unexpected result "PT3H30M" to "4 hours"

### ISSUE THREAD

**Issue by JiLiZART** [moment/moment#3732]
this code
```js
moment.duration('PT3H30M').humanize();
```
outputs `4 hours` but I expect `3 hours 30 minutes`.

It is a valid behavior?

some browser data

```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

```
Fri Jan 27 2017 18:08:59 GMT+0200 (EET)
27/01/2017, 18:08:59
-120
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
2.17.1
```

**Comment by mj1856** [comment]
Unfortunately, yes.  We don't have a version of `humanize` that breaks out the duration into multiple parts like that.  If it exceeds the [relative time thresholds](http://momentjs.com/docs/#/customization/relative-time-threshold/), it is always represented as an approximation, in the largest units.

You can of course get the values yourself:
```js
var d = moment.duration('PT3H30M');
d.hours()   // 3
d.minutes() // 30
```

But we don't have anything built-int that will give you a string like `3 hours 30 minutes`.
