### ISSUE TITLE
Consistency in locale names

### ISSUE THREAD

**Issue by slucas-nwx** [moment/moment#3733]
This is a suggestion. 

Right now locales are defined as "en", "en-ie", "en-au" ... etc..

I think it would add benefit to have consistent naming conventions on locales so that it is always structured as
"en-us", "en-ie", "fr-fr","fr-ca" and so on. Always specifying the language-country.

Thanks

**Comment by mj1856** [comment]
We already support this by fallback.

```js
moment.locale('en')     // "en"
moment.locale('en-us')  // "en"
moment.locale('en-ie')  // "en-ie"
moment.locale('en-gb')  // "en-gb"
moment.locale('en-foo') // "en"

moment.locale('fr')     // "fr"
moment.locale('fr-fr')  // "fr"
moment.locale('fr-ca')  // "fr-ca"
moment.locale('fr-foo') // "fr"
```

If you're saying you'd like us to create a separate file for each and every language/country combination - sorry, no.  That doesn't help us.

**Comment by slucas-nwx** [comment]
Fallback is fine, that wasn't clear in the documentation I found. Thanks for the clarification.
