### ISSUE TITLE
Difference in isoWeek

### ISSUE THREAD

**Issue by yamsellem** [moment/moment#3734]
Hi,

Because `moment('2017/01/01').isoWeek()` returns 52 and `moment('2017/01/02').isoWeek()` returns 1, I was expected that `moment('2017/01/01').diff(moment('2017/01/02'), 'isoWeek')`will return 1 as well.

But it returns value in milliseconds.

May the difference of isoWeek can be added to the `diff` method?
This could be very handy.

Iso dates have this great advantage to start on Mondays ;-)

**Environment:** Chrome 49 on OSX

**Comment by mj1856** [comment]
That wouldn't make sense.  `isoweek` vs `week` is important when you are aligning to some representation of a week numbering system.  We use that with functions like `.startOf(`isoWeek`)` and `.isoWeek()`.

The `diff` function does not align to any particular week numbering system.  It is just measuring the difference between the values provided.  A week is 7 days.

```js
moment('2017-01-08').diff('2017-01-01', 'days')  // 7
moment('2017-01-09').diff('2017-01-02', 'days')  // 7
moment('2017-01-10').diff('2017-01-03', 'days')  // 7
```

Therefore:
```js
moment('2017-01-08').diff('2017-01-01', 'weeks')  // 1
moment('2017-01-09').diff('2017-01-02', 'weeks')  // 1
moment('2017-01-10').diff('2017-01-03', 'weeks')  // 1
```
