### ISSUE TITLE
moment().to(), outputs number for seconds?

### ISSUE THREAD

**Issue by ErraticFox** [moment/moment#3736]
Hello, I was wondering it was possible to use `moment().to()` to return the seconds number?

**Comment by mj1856** [comment]
What specifically are you looking for?  Give examples please.

**Comment by ErraticFox** [comment]
If I do `moment('01/31/17 15:00:00').to('01/31/17 15:05:00', true)` it would output `5 minutes`. Is it possible to get the seconds `to` that time aswell?

**Comment by icambron** [comment]
No that's really meant for imprecise, almost casual displays of time, like what you see right here in the tickets ("commented 7 days ago"). If you specifically want seconds, just do:

```js
> moment('01/31/17 15:05:00').diff('01/31/17 15:00:00', 's')
300
```
