### ISSUE TITLE
Regex for YYYY using strict mode allows 1-4 chars and pads with leading zeros causing invalid date comparisons

### ISSUE THREAD

**Issue by rickschott** [moment/moment#3740]
Regex for date formats using YYYY using strict mode allows 1-4 chars and pads with leading zeros causing invalid date comparisons.
```javascript
var notValid = moment('27-01-17','DD-MM-YYYY',true);
notValid.isValid();
true
```

Code that causes this:
Line 47
```javascript
 parseTokenFourDigits = /\d{1,4}/, // 0 - 9999
```

```javascript
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
Tue Jan 31 2017 09:20:27 GMT-0500 (Eastern Standard Time)
1/31/2017, 9:20:27 AM
300
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
2.4.0
```

Fix:
```javascript
parseTokenFourDigits = /\d{4}/,
```

**Comment by icambron** [comment]
You must be running an older version? Try pasting this into the console [here](http://momentjs.com/docs/):

```js
moment('27-01-17','DD-MM-YYYY',true).isValid()
false
```

The relevant code is [here](https://github.com/moment/moment/blob/497f918515ae6ab900f008f19523b1e4ae5e2450/src/lib/units/year.js#L38): the second arg is the strict version and is defined [here](https://github.com/moment/moment/blob/497f918515ae6ab900f008f19523b1e4ae5e2450/src/lib/parse/regex.js#L4).
