### ISSUE TITLE
The "mometn.format" makes the incorrect date.

### ISSUE THREAD

**Issue by Claud** [moment/moment#3744]
**Description of the Issue and Steps to Reproduce:**

```js
"use strict";

const moment = require('moment-timezone');
moment.tz.setDefault('UTC');
moment.defaultFormat = 'YYYY-MM-DD HH:mm:ss.SSS';
console.log(moment.tz('Etc/GMT+0').format());
```
Result: `2017-02-01T10:38:18Z`

i see this trouble also with Etc/GMT, Etc/GMT-0, but Etc/GMT-1... is working.

**Environment:**

Nodejs 6.9.1x64, windows 10 x 64 (tz: Europe/Moscow), moment.js 2.17.1, moment-timezone 0.5.11

**Other information that may be helpful:**

```js
console.log( (new Date()).toString()); // Wed Feb 01 2017 13:50:10 GMT+0300 (RTZ 2 (зима))
console.log((new Date()).toLocaleString()); // 2017-02-01 13:50:10
console.log( (new Date()).getTimezoneOffset()); // -180
```

**Comment by icambron** [comment]
Can you reopen this in the `moment-timezone` repository? https://github.com/moment/moment-timezone
