### ISSUE TITLE
Incorrecr compare date

### ISSUE THREAD

**Issue by onekosha** [moment/moment#3745]
**Description of the Issue and Steps to Reproduce:**
moment("01.04.2017", "YYYY-MM-DD").isAfter(moment("01.05.2017", "YYYY-MM-DD"))
result: false
explain: 1 april 2017 year isAfter 1 may 2017 year
but
moment("10.04.2017", "YYYY-MM-DD").isAfter(moment("01.05.2017", "YYYY-MM-DD"))
result: true
explain: 10 april 2017 year isAfter 1 may 2017 year

**Environment:**

*Chrome 56 on Windows 10*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on Ukraine
* The time and date at which the code was run february 2017
* Other libraries in use (TypeScript, Immutable.js, etc) no

**Comment by marwahaha** [comment]
I think you are calling `moment` incorrectly.
The correct second call should be:
```
moment("10.04.2017", "DD.MM.YYYY").isAfter(moment("01.05.2017", "DD.MM.YYYY"))
```
Which is in fact `false`.

**Comment by icambron** [comment]
@marwahaha is right: `moment("01.04.2017", "YYYY-MM-DD")` is not correct
