### ISSUE TITLE
sBetween() is not returning true when the date is on the boundary of the inclusivity parameter

### ISSUE THREAD

**Issue by jlubean** [moment/moment#3751]
**Description of the Issue and Steps to Reproduce:**

isBetween() is not returning true when the date is on the boundary of the inclusivity parameter.  For example, the example below shows that the date 02/07/2017 (at midnight) should be between 02/07/2017 (at midnight) and 02/08/2017 (at midnight) when the inclusion parameter is '[)', but isBetween() returns false.  But, if you add 1 millisecond to the date, isBetween() returns true. 

```js
    var date = moment('02/07/2017', 'MM/DD/YYYY').startOf('day');
    var today = moment('02/06/2017', 'MM/DD/YYYY').startOf('day');
    var tomorrow = moment('02/06/2017', 'MM/DD/YYYY').startOf('day').add(1, 'd');
    var dayAfterTomorrow = moment('02/06/2017', 'MM/DD/YYYY').startOf('day').add(2, 'd');
    
    if(date.isBetween(tomorrow, dayAfterTomorrow, '[)')) {
        console.log(date.format('MM/DD/YYYY HH:mm:ss:SSS') + ' IS between ' +  tomorrow.format('MM/DD/YYYY HH:mm:ss:SSS') + ' and ' + dayAfterTomorrow.format('MM/DD/YYYY HH:mm:ss'));
    } else {
        console.log(date.format('MM/DD/YYYY HH:mm:ss:SSS') + ' IS NOT between ' +  tomorrow.format('MM/DD/YYYY HH:mm:ss:SSS') + ' and ' + dayAfterTomorrow.format('MM/DD/YYYY HH:mm:ss:SSS'));
    }

    date = moment('02/07/2017', 'MM/DD/YYYY').startOf('day').add(1, 'ms');

    if(date.isBetween(tomorrow, dayAfterTomorrow, '[)')) {
        console.log(date.format('MM/DD/YYYY HH:mm:ss:SSS') + ' IS between ' +  tomorrow.format('MM/DD/YYYY HH:mm:ss:SSS') + ' and ' + dayAfterTomorrow.format('MM/DD/YYYY HH:mm:ss:SSS'));
    } else {
        console.log(date.format('MM/DD/YYYY HH:mm:ss:SSS') + ' IS NOT between ' +  tomorrow.format('MM/DD/YYYY HH:mm:ss:SSS') + ' and ' + dayAfterTomorrow.format('MM/DD/YYYY HH:mm:ss:SSS'));
    }

    // Output:
    //     02/07/2017 00:00:00:000 IS NOT between 02/07/2017 00:00:00:000 and 02/08/2017 00:00:00:000
    //     02/07/2017 00:00:00:001 IS between 02/07/2017 00:00:00:000 and 02/08/2017 00:00:00:000
```
*Please include the values of all variables used.*

**Environment:**

    Chrome 55.0.2883.95 (64-bit) on OSX

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
```
Mon Feb 06 2017 08:56:34 GMT-0700 (MST)
2/6/2017, 8:56:34 AM
420
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
2.17.1
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by icambron** [comment]
The arguments to `isBetween` are like this:

```js
date.isBetween(tomorrow, dayAfterTomorrow, null, '[)')
```

http://momentjs.com/docs/#/query/is-between/

Note that `null` as the third argument; that's the units argument. In your code, Moment ignored the '[)' as a unit and defaulted the inclusivity to '()', so that's why adding an ms "worked".
