### ISSUE TITLE
moment.tz.setDefault() is global and shared by all modules.

### ISSUE THREAD

**Issue by jontelm** [moment/moment#3754]
Default timezone is shared between all modules:

server.js
```
var moment = require('moment-timezone');
console.log('sets timezone to Europe/Stockholm and locale to sv');
moment.tz.setDefault('Europe/Stockholm');
moment.locale('sv');

var moduleA = require('./moduleA');
var moduleB = require('./moduleB');
```
moduleA.js
```
var moment = require('moment-timezone');

setInterval(function () {
  console.log('Moment in moduleA', moment().format('MMMM Do YYYY, h:mm:ss a'));
}, 100)
```

moduleB.js
```
var moment = require('moment-timezone');

setInterval(function () {
  console.log('Moment in moduleB', moment().format('MMMM Do YYYY, h:mm:ss a'));
}, 100)

setInterval(function () {
  console.log('Changing timezone in moduleB  America/New_York locale en');
  moment.tz.setDefault("America/New_York");
  moment.locale('en');
}, 3000);
```

Output after 3 seconds:

````
Moment in moduleA februari 8e 2017, 9:09:19 am
Moment in moduleB februari 8e 2017, 9:09:19 am
Moment in moduleA februari 8e 2017, 9:09:19 am
Moment in moduleB februari 8e 2017, 9:09:19 am
Changing timezone in moduleB  America/New_York locale en
Moment in moduleA February 8th 2017, 3:09:19 am
Moment in moduleB February 8th 2017, 3:09:19 am
Moment in moduleA February 8th 2017, 3:09:19 am
````

**Comment by icambron** [comment]
What environment is this?

**Comment by jontelm** [comment]
Node 4.7.3, ubuntu 14.04

**Comment by jontelm** [comment]
I think we should add a warning about this in the docs and not recommend developers to use this function in systems like node.
http://momentjs.com/timezone/docs/#/using-timezones/default-timezone/

**Comment by alburthoffman** [comment]
moment.tz.setDefault() is obviously a global config method for module moment.tz

Not sure if it's correct that require in node only import module moment.timezone only once instead of several times. If it's true, then the example output is expected.

**Comment by jontelm** [comment]
@alburthoffman Yes it's the expected output but I think a lot of people can get problems with this in node environments when a module far down in the dependency list can do something with setDefault and it will have a impact on all modules that have require('moment-timezone'). I spent a lot of time before I got this right.

If you guys agree can we add a info-text like this: https://github.com/mashpie/i18n-node#example-usage-in-global-scope but we can also just close this issue when it's not a bug.

**Comment by adamreisnz** [comment]
It would be great if we could have something like this:

```js
//Module A
const moment = require('moment-timezone').instance();
moment.tz.setDefault('foo');

//Module B
const moment = require('moment-timezone').instance();
moment.tz.setDefault('bar');
```

And for neither moment to be affected by each other's timezone.

This would also be great for applications using Express, where you can then create a moment instance for the duration of the request, configure it with a global timezone, and rest assured that all the rest of your middleware will use the correct timezone.

Right now, we have to set the correct timezone literally in 100's of places in our code, because we can't use `moment.tz.setDefault()`.

Thoughts?

**Comment by isair** [comment]
You could do

```
import moment from 'moment-timezone';
export default moment().tz('foo');
```

```
import momentFoo from '../somewhere/moment-foo';
```

**Comment by jackielii** [comment]
@isair it doesn't quite work:

```Uncaught TypeError: Object(...) is not a function```

**Comment by marwahaha** [comment]
Sure, we'll take a documentation PR at https://github.com/moment/momentjs.com

@adamreisnz - please file a ticket for your feature request in https://github.com/moment/moment-timezone

**Comment by adamreisnz** [comment]
How exactly does #684 fixes this issue? It's just a readme update to clarify the current behaviour as far as I can see.

**Comment by appsparkler** [comment]
# How about this?

```javascript
const estMoment = (d) => moment.tz(d, 'America/New_York')

console.log(estMoment().format())
console.log(moment().format())
```

This way you can have a moment for various timezones.
