### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature. Type 'typeof 'moment'' has no compatible call signatures.

### ISSUE THREAD

**Issue by lansefengxinzi** [moment/moment#3755]
i use normal ,but i dont know why error,
![1f15b1fb-e1e4-4215-8ca5-9ef2def6e017](https://cloud.githubusercontent.com/assets/12048313/22729751/10f7b0b0-ee1f-11e6-92b3-be77b0b32a7e.png)

**Comment by lansefengxinzi** [comment]
i use typescript

**Comment by maggiepint** [comment]
You don't have the typings for moment installed correctly. Without knowing your setup, I can't help you much more than that.

**Comment by Giovanni-Mattucci** [comment]
I have this same issue. 
I was using Definitely Types definitions, but supposedly moment has its own typings as part of the package, so I removed them and now I'm getting this.
