### ISSUE TITLE
Duration not returning accurate number of days

### ISSUE THREAD

**Issue by hipwebdesign** [moment/moment#3759]
I find that if I take the Difference between two dates and turn it into a Duration, it returns the correct number of years, months, hours, minutes, and seconds -- but not days. For example:

```
var now = moment();
var future = moment("2017-4-17 23:18:30"); // a future
var diff = future.diff(now);
var duration = moment.duration(diff);

var dateA = moment(now).add(duration._data);
var dateB = moment(now).add(duration);
```
In this example, {dateA} returns ~2 fewer days than {dateB}.

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:51.0) Gecko/20100101 Firefox/51.0
> 2.17.1

**Comment by GaleOnGitHub** [comment]
The dateB  works because the add method is using the '_milliseconds' property of the duration. 
I suspect dateA isn't working because duration doesn't accurately convert units that depend on context (https://momentjs.com/docs/#/durations/).

**Comment by icambron** [comment]
Please don't use private properties like `_data` in Moment objects. We have APIs for a reason. In this case, adding the duration is working as expected when you add the duration directly (you get back the original date), so what's the problem?

**Comment by hipwebdesign** [comment]
@icambron The problem, I think, is that Duration is returning `days()` based on the `_data` property, which is not equal to the original date. This means that when I use the `days()` getter on a Duration, I get in incorrect number of days.

**Comment by icambron** [comment]
@hipwebdesign Are you sure you don't want `asDays()`? (I'm still a little unclear on what you're trying to do.)

**Comment by hipwebdesign** [comment]
@icambron Consider these two dates:
```
var start = moment("2017-02-14 13:23:20");
var end = moment("2017-04-17 23:18:30");
var diff = end.diff(start);
```
`diff` is the milliseconds between the two dates.

Now I want to turn `diff` into a Duration so that I may see how many years, months, weeks, days, hours, and seconds make up `diff`:

`var duration = moment.duration(diff);`

The `_data` property of `duration` returns:

```
years: 0
months: 2
days: 1
hours: 8
minutes: 55
seconds: 10
milliseconds: 0
```
If I add 2 months, 1 day, 8 hours, 55 minutes, and 10 seconds to the `start` date, I get `2017-04-15 22:18:30`. This is not equivalent to the intended `end` date. It's a few days behind.

So, when I use the `duration.days()` getter, it returns `1`, when it should return `3` — and now that I'm looking at it, it's 1 hour behind as well. `duration.hours()` returns `8`, when it should be `9`.

**Comment by icambron** [comment]
Ah, ok, I see. @GaleOnGitHub's answer is right, but I'll expand it:

A month isn't a fixed length of time; it varies month to month. Moment adds and subtracts months as spans on the calendar, (e.g. Jan 23 + 2 months = March 23) regardless of how long they are. On the other hand, a duration is just a wrapper for a number of milliseconds. When you create a duration, Moment doesn't know that it really came from some *particular* block of the calendar; the `months` and `days` it roles up into a really just abstract blocks of time, like a 1 month = 30 days and so on. So the trick here is that by taking the diff and then converting it to months, you lost information; you went from a very particular month to an abstract one. Then when you added them back together, you treated that abstract month as a real one and got an unexpected answer.

That's consistent with the API's design. Except by resorting to private fields, you can only add the whole duration, by which we mean you can add those milliseconds, which is all the information really contained in the duration. Those getters like `months()` and `days()` are for your convenience in, say, rendering the duration; they don't contain separate information that pertains specifically to any section of the calendar.

The hours being off is similar and actually nicely illustrative: when Moment adds a day, it makes up for DSTs it finds along the way. 1 day after 8:00 is 8:00 the next day even if that particular day jumps ahead or behind such that it's really 23 or 25 hours long. But here again when you just give a duration a count of milliseconds, it doesn't know that some of the days that count is a diff between shift their calendar, so when it boils into days it just uses simple conversions like 1 day = 24 hours. So when you add them back up, you end up off by an hour.
