### ISSUE TITLE
Add "no conflict" mode to library 

### ISSUE THREAD

**Issue by andruxin** [moment/moment#376]
Similar to jQuery, it would be useful to have a way to keep the moment.js library from conflicting with another unexpected instance of moment.js that be on the page. jQuery has a $.noConflict(bool).

**Comment by Skyrpex** [comment]
Still, a noConflict function would be really appreciated here. Not everyone can control which libraries are already loaded in a website.

In our company, we inject custom scripts into our customer's websites. We don't know if moment is already being used, and we don't want to leave any footprint. Actually, we "manually" use a noConflict feature...

**Comment by stopsopa** [comment]
I think when You build so universal library like moment.js it should have noConflict functionality. 
There is no excuse for that, also because noConflict is nothing difficult, its 3 or 4 lines of code.
This excusing of "timrwood" is really pathetic, he spend more of time to explaining why this is bad idea then if he would try to implementing this.

**Comment by wonderb0lt** [comment]
I've got a similar setup as @Skyrpex and would like to see this functionality in the library. Can this issue at least be re-opened?

**Comment by khirakawa** [comment]
@skyrpex @wonderb0lt Would it be possible for you to share your manual `noConflict` logic? I think it would help folks who need this functionality

**Comment by skyrpex** [comment]
Well... actually, we concatenate our scripts into one single file. This file is wrapped by an anonymous function that takes care of moment.

It looks like this:

```javascript
(function(global) {

    // Save original moment
    var noConflict = global.moment;

    // All of our scripts here... for example
    // jquery.min.js
    // moment.min.js

    // Restore original moment
    global.moment = noConflict;
    
})(this);

```

**Comment by khirakawa** [comment]
@skyrpex thanks for the quick reply :+1:
