### ISSUE TITLE
Feature request: allow parsing 12 noon / 12 midnight and formatting 12 noon / 12 midnight

### ISSUE THREAD

**Issue by bushmango** [moment/moment#3760]
It would be really helpful to be able to have strings for midnight and noon, as people are easily confused by 12 am / pm

For reference, this time picker pedantic mode:

http://www.material-ui.com/#/components/time-picker

**Description of the Issue and Steps to Reproduce:**

 let date = moment('12 noon', 'H:mm aa') // date set to 12 noon

 let formatted = moment(date).format('H:mm aa') // 12 noon

--

 let date = moment('12 midnight', 'H:mm aa') // date set to 12 midnight

 let formatted = moment(date).format('H:mm aa') // 12 midnight

**Environment:**

any

**Comment by icambron** [comment]
I'm not against this in principle, but a few challenges:

 1.  we'd need "midnight" and "noon" in every locale supported by Moment. That's a tall order. Perhaps they can be swiped from CLDR?

 2. It's not clear to me how it would actually work as a parsing string. What's the expected input for 3 pm? Does `aa` also match AM/PM?

**Comment by marwahaha** [comment]
related to https://github.com/moment/moment/issues/3873

Should we act on this?

**Comment by icambron** [comment]
@marwahaha After thinking a bit, I think I'm -1. Almost anything that creeps our internationalization requirements is going to need a high level of support for them. Given the outcome of #3873 and the lack of support here, I think we should `wontfix` this.

**Comment by maggiepint** [comment]
I'm going to agree with @icambron  and shut this one down. I believe CLDR does have translations for noon, but not midnight. Anything that causes us to add yet more non-CLDR locale data is just a no-go.
