### ISSUE TITLE
(Feature request) Option to display "1 minute ago" instead of "a minute ago" 

### ISSUE THREAD

**Issue by darkred** [moment/moment#3764]
My feature request is, when using e,g, [`moment().fromNow();`](https://momentjs.com/docs/#/displaying/fromnow/),
instead of 
"a minute ago. an hour ago, a day ago, a month ago, a year ago"
to show:
"1 minute ago, 1 hour ago, 1 day ago, 1 month ago, 1 year ago".

I'm using moment.js [in this userscript](https://greasyfork.org/en/scripts/13846-thepiratebay-helper) (using GreaseMonkey in Firefox)
in order (among other things) to convert the torrent timestamps in HTML tables to relative format.
So, I'd like to avoid having e.g. this:
![](https://cloud.githubusercontent.com/assets/723651/22947768/f1e5db80-f304-11e6-9f8d-60e03ec6ea09.jpg)

I'd prefer having '1 minute' and '1 hour ago'.

**Comment by icambron** [comment]
Just customize the strings in the locale:

```js
moment.updateLocale('en', {
   relativeTime: {
        future: "in %s",
        past:   "%s ago",
        s:  "seconds",
        m:  "1 minute",
        mm: "%d minutes",
        h:  "1 hour",
        hh: "%d hours",
        d:  "1 day",
        dd: "%d days",
        M:  "1 month",
        MM: "%d months",
        y:  "1 year",
        yy: "%d years"
  }
});
moment().subtract(1, 'minute').fromNow(); //=> "1 minute ago"
moment().subtract(1, 'hour').fromNow(); //=> "1 hour ago"
moment().subtract(1, 'day').fromNow(); //=> "1 day ago"
moment().subtract(1, 'month').fromNow(); //=> "1 month ago"
```

**Comment by darkred** [comment]
Thanks a lot for the detailed answer!
