### ISSUE TITLE
Error in function toISOString() when 0 year

### ISSUE THREAD

**Issue by vagsa2** [moment/moment#3765]
**Description of the Issue and Steps to Reproduce:**

In the [Standard ECMA-262](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15.1) we can find condition for extended year format `before 0 or after 9999`. But in `moment.js` [realization](https://github.com/moment/moment/blob/b8a297c1f99b3918f44dd9e3d7bd59379a876ba6/moment.js#L3126)  condition is `0 < m.year() && m.year() <= 9999`.

I think, the right condition is `0 <= m.year() && m.year() <= 9999`

```js
var date = moment('0000-01-01T21:00:00.000Z')
date.toISOString() // returns "+000000-01-01T21:00:00.000Z"
date.toDate().toISOString() // returns "0000-01-01T21:00:00.000Z"
```

**Comment by icambron** [comment]
Agreed

**Comment by icambron** [comment]
Closing in favor of #3780
