### ISSUE TITLE
mogodb in not  convert  user define date  to ISO 

### ISSUE THREAD

**Issue by anupkmourya** [moment/moment#3767]
i am  give date and time in  var date = new Date();
than  store mongodb in date does not convert date iso 
this problem only server site host
local server in work fine  

code

 date = formData.date,                      //ex 2017-02-16
        time = formData['time-value']; //ex : 11:12 am
        var date = new Date(date + ' ' + time);   

local mongo database in store  fine 
date :  ISODate("2017-02-13T05:55:39.789Z")

but i am host server mongo database in store not correct output
date : ISODate("2017-02-13T11:12:00.000Z")

does not convert 

meteor with mongo 

please reply

**Comment by icambron** [comment]
As far as I can tell, this has nothing to do with Moment.
