### ISSUE TITLE
Moment.js v2.17.1 not compatible with ContentSecurityPolicy

### ISSUE THREAD

**Issue by akshaydhiman09** [moment/moment#3768]
I was using the fullcalendar plugin with momentjs in Salesforce lightning and everything was working fine. But recently Salesforce has implemented a service called LokerService which is restricting the use of 'unsafe-eval' and has implemented the Content Security Policy. Due to this momentjs is not working as it is not compatible with the ContentSecurityPolicy. However i was able to find that v1.7.1 is free from ContentSecurityPolicy but we cannot use Moment Timezone with that.

What is happening that when i try to get back the value from momentjs it is returning the String like
"**function () {				return zeroFill(func.apply(this, arguments), padded[1], padded[2]);			}/function () {				return zeroFill(func.apply(this, arguments), padded[1], padded[2]);			}/function () {				return zeroFill(func.apply(this, arguments), padded[1], padded[2]);			}**".

So please help me out in this.
Thank you.

**Comment by icambron** [comment]
What are you asking us to change? I don't think Moment uses unsafe eval as of 2.16.0
