### ISSUE TITLE
Can't parse 2016W53 into a date

### ISSUE THREAD

**Issue by marcelpanse** [moment/moment#3769]
Parsing 2015W53 works fine.
Parsing 2016W53 gives a null object.

Fiddle: http://jsfiddle.net/wajzudo8/1/

**Comment by GaleOnGitHub** [comment]
Seems 2015 had 13 weeks but 2016 didn't so its flagged as an invalid date. Setting 2015 to week 54 has the same effect. 
**2015**
W53 => Dec 28th
W54' => 'invalid' (null)
**2016**
W52 => Dec 26th
W53 => 'invalid' (null)
It still returns an object though, as you can still run methods on the result. 
ex: `moment('2016-W53').isValid() //false`

**Comment by icambron** [comment]
Well said @GaleOnGithub
