### ISSUE TITLE
Typescript - Can't use Duration as value

### ISSUE THREAD

**Issue by aequasi** [moment/moment#3771]
I feel like i'm missing something very simple here, but, im trying to use `Duration` as a value, like so:

```
param.Type = Duration;
if (param.Type === Duration) {
  // Do something with param
}
```

Is there a way to use Duration this way?

**Comment by richseviora** [comment]
If you're looking to see if a value is a duration, please use:

    moment.isDuration(param) 

There is no `Type` property available on `Moment` types.

**Comment by aequasi** [comment]
Thats not what i was looking to do. I was looking to use the Type, as a value, like you can with any concrete class

**Comment by richseviora** [comment]
Can you expand on the context? I feel there might be a better way to accomplish this without using concrete classes as objects.

TypeScript types don't exist in code once compiled to JS outside of the concrete classes that been created via prototypes, and the moment module does not expose the prototypes directly. So you can't interact with `moment.Duration` directly because it only exports the `Duration` interface.

You can, however, do:

```
let test = moment();
let testProto = Object.getPrototypeOf(test);
let duration = moment.duration();
let durationProto = Object.getPrototypeOf(duration);
let result : boolean = durationProto === testProto; // Returns False
let newDuration = moment.duration();
let newDurationProto = Object.getPrototypeOf(newDuration);
let durationResult : boolean = newDurationProto == durationProto; // Returns True
```

**Comment by marwahaha** [comment]
If you want to denote `param` having an attribute `Duration`, you could always use a string:
```
param = {}
types = {DURATION: "Duration"};
param.type = types.DURATION;
```

**Comment by hoorayimhelping** [comment]
@aequasi how are you importing moment?

**Comment by marwahaha** [comment]
Closing due to age. If you still have questions please re-open.

**Comment by albanx** [comment]
I am having the following issue:
Component X using Moment for generating a Duration object.
Component Y using Moment.IsDuration for checking the Duration Object sent by Component X.

Those components are bundled separately, having each one its own Moment library inside the bundle.

Component Y returns false when checking the .isDuration(componentXduration);

How can I solved this issue?
