### ISSUE TITLE
diff() doesn't take days rounding into account

### ISSUE THREAD

**Issue by random82** [moment/moment#3774]
Hi,

I found this weird behavior. I try to truncate time and use dates only to calculate difference. It looks like ```startOf('day')``` is not properly taken into account when calculating date difference. 

EDIT: I would like to calculate date difference in UTC, it looks like it translates to local time.
I'm sitting in +10 timezone which makes below calculations valid in local time.

Expected behavior would be to completely ignore time when rounding is being requested.

Example and repro steps:

```javascript
console.log('======== BEGIN ===========')

var date1 = "2016-11-10T16:12:17.933Z"
var date2 = "2016-11-13T11:17:13.933Z"

var m1 = moment(date1);
var m2 = moment(date2);

var diff = m2.diff(m1);
var diffDays = moment.duration(diff).asDays();

console.log(diff)
console.log(diffDays)

console.log("That's fine -> we take hours into account, diff is less than 3 days")

m1 = moment(date1).startOf('day');
m2 = moment(date2).startOf('day');

diff = m2.diff(m1); 
diffDays = moment.duration(diff).asDays();

console.log(diff)
console.log(diffDays)
console.log("That should be rounded to 3 days difference without hours into account, but ok...")

// Let's change hours - since we round to days it should be irrelevant
date1 = "2016-11-10T10:12:17.933Z"
date2 = "2016-11-13T11:17:13.933Z"

m1 = moment(date1).startOf('day');
m2 = moment(date2).startOf('day');

diff = m2.diff(m1); 
diffDays = moment.duration(diff).days();

console.log(diff)
console.log(diffDays)
console.log("Wait, what? That should be same as above as we calculate date difference only, right?")

console.log('========= END ===========')
```

**Comment by icambron** [comment]
Following along in my own JS console, I got a little confused. The last two `console.log(diffDays)` printed `3` for me. Is that not what you got? Is it not what you expect?

**Comment by random82** [comment]
@icambron I think I found the issue. Time calculation are done in local time. I was expecting UTC differences. Is there a way I can choose UTC calculations?

**Comment by icambron** [comment]
Depends a bit on what you mean by "calculation". The number of MS between two timestamps is the same regardless of zone, so it won't change `diff`. But you can certainly make it compute `startOf` as the the start of the UTC day:

```js
moment(date1).utc().startOf('day');
````

**Comment by icambron** [comment]
Closing this due to age. Happy to reopen if you have more questions comments.
