### ISSUE TITLE
v3 changes

### ISSUE THREAD

**Issue by ichernev** [moment/moment#3775]
To be:
- [ ] immutability
- [ ] strict parsing by default
- [ ] improve silent failures (moments and durations) - #3704 and #3611
- [ ] remove all deprecations (except maybe Date parse failover?)
- [ ] typescript 2.0
- [ ] remove ordinalParse(Lenient) in favor of dayOfMonthOrdinalParse(Lenient)

To discuss:
- [ ] pluggable everything (format tokens/functions, parse regex/token/functions/preprocs) -- so different calendar systems can be implemented as a plugin
- [ ] locales in a different repo
- [ ] docs in same repo + docs versioning
- [ ] new zone interface

**Comment by ichernev** [comment]
The process is going to be the following -- if you want to propose a change for v3 (highly aligned with the list above), make sure to based it off the immutability branch. We might change it a bit, but most things will stay so rebasing shouldn't be an issue.

**Comment by maggiepint** [comment]
this is a small one, but I would like to remove the `moment()` constructor and have it be `moment.local()`. I think this will reduce a lot of ambiguity for users. Yes, a lot of people will have to change a lot of code, but it's a straightforward find and replace change.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
