### ISSUE TITLE
Kabyle locale

### ISSUE THREAD

**Issue by belkacem77** [moment/moment#3783]
Hi,
I'd like to add the kabyle locale in moment. some addons for kab apps are using it.

Please, i like guidance. Is tehre any translation tool for that?

Thanks for support.

**Comment by marwahaha** [comment]
Hi,

@narainsagar had a great note about how to do this:

> FYI. For your PR to be published. You have to follow this rules:
> 
> * Create locale source file under src/locale/
> * write unit tests for your locale under src/test/locale/ (make sure you keep the names same on both sides)
> * run the unit tests and make sure all unit tests passes..
> * just push your code (only those files under src/locale/)
> 
> For more read this contributing guidelines from here: https://github.com/moment/moment/blob/develop/CONTRIBUTING.md

You can see his changes here: https://github.com/moment/moment/pull/3659/files

**Comment by icambron** [comment]
@marwahaha's advice is good for the technical side of it, but here's some more general guidance on approaching it:

 1. I don't know of any translation tools that would be helpful. I believe all the locales we have were written manually.
 2. It's often good to start with CLDR data, but Moment needs strings that, last I checked, CLDR didn't have. (If we could get everything from CLDR, we'd just use that data. It would be great!)
 3. It's pretty important that you speak (or have access to someone who speaks) Kabyle. Most of the locale files are written by native speakers of the relevant languages.

I'm going to close this, but feel free to ask follow-up questions tagging me specifically.
