### ISSUE TITLE
Adding 28 days or more causes overflow when date is close to February

### ISSUE THREAD

**Issue by mdumrauf** [moment/moment#3789]
**Description of the Issue and Steps to Reproduce:**

Adding *28 days or more* to a date in a non-leap year (or >= 29 in a leap year) is causing the library to calculate remaining time wrong:

E.g.:
```js
moment('2017-01-31').add(26, 'days').from(moment('2017-01-31')) // "in 26 days"
moment('2017-01-31').add(27, 'days').from(moment('2017-01-31')) // "in 27 days"
moment('2017-01-31').add(28, 'days').from(moment('2017-01-31')) // "in 30 days"
moment('2017-01-31').add(29, 'days').from(moment('2017-01-31')) // "in 31 days"
moment('2017-01-31').add(30, 'days').from(moment('2017-01-31')) // "in 32 days"
moment('2017-01-30').add(29, 'days').from(moment('2017-01-30')); // "in 30 days"
```

*Please include the values of all variables used.*

* Date from: '2017-01-31'

**Environment:**

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

* node.js v6.2.2 on Linux Mint Cinnamon 17.3

```js
> moment('2017-01-31').add(28, 'days').from(moment('2017-01-31'))
'in a month'
> moment.version
"2.13.0"
```

* Chrome 55.0.2883.87 (64-bit) on Linux Mint Cinnamon 17.3

```js
> moment('2017-01-31').add(28, 'days').from(moment('2017-01-31'))
'in 30 days'
> moment.version
"2.17.1"
```

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on: GMT-0300 (ART)
* The time and date at which the code was run: Feb 26 2017 13:23:49 GMT-0300 (ART)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
```
Sun Feb 26 2017 13:24:25 GMT-0300 (ART)
2/26/2017, 1:24:25 PM
180
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
2.17.1
```

**Comment by marwahaha** [comment]
Perhaps I'm missing something. I've tested this on 2.17.1 and I get `"in a month"` for each case you posted!

```
Fri Mar 03 2017 01:27:44 GMT-0500 (EST)
3/3/2017, 1:27:44 AM
300
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
2.17.1
```

Also tested on 2.17.1 using node.js v6.5.0 on Mac OS 10.11.6

**Comment by mdumrauf** [comment]
Dumb questions first: is it possible that this only happens on February?

**Comment by icambron** [comment]
No, I tried changing my clock:

```js
> moment().format()
'2017-02-09T01:14:31-05:00'
> moment('2017-01-30').add(29, 'days').from(moment('2017-01-30'));
'in a month'
```

Is it possible you've overidden your [relative time thresholds](http://momentjs.com/docs/#/customization/relative-time-threshold/)?

**Comment by mdumrauf** [comment]
No, I didn't. It is weird, because since March I can't reproduce it anymore. It keeps telling me "in a month" instead of "in 30 days". Is there a way to force to display `in xx days` instead of 'in a month`?

**Comment by icambron** [comment]
Yes, that's why I linked you to the way to do that and asked if that's what you had done.

```js
> moment.relativeTimeThreshold('d', 31)
true
>  moment('2017-01-30').add(29, 'days').from(moment('2017-01-30'))
'in 30 days'
```

That isn't right, but it comes from Moment realizing that you added a full month and creating a duration of <one month> and then forgetting which specific month it is. Then when asked to translate back to days, it just thinks a month is 30 days long. I bet that mismatch comes from the internals being built before the thresholds were made configurable.

That's definitely a bug, but I'm guessing it's a low priority to fix. More importantly, if you're not setting `relativeTimeThreshold()` it's not the problem you're seeing. You'll have to provide us with something reproducible so we can help.

**Comment by icambron** [comment]
Closing for age. If you have more info, feel free to @ me and I'll reopen.
