### ISSUE TITLE
utcOffset - invalid parsing when no leading sign

### ISSUE THREAD

**Issue by dafco** [moment/moment#3794]
The docs for utcOffset says:

> Note that the string is required to start with the + or - character. Passing a string that does not start with + or - will be interpreted as if it were "+00:00".

However, I've come across a counterexample:

> moment().utcOffset('0300').format()
> "2017-02-27T09:53:40+01:00"
> moment().utcOffset('+03:00').format()
> "2017-02-27T11:53:46+03:00"
> 

These:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
Return:

> Mon Feb 27 2017 09:50:21 GMT+0100 (Central European Standard Time)
> 2/27/2017, 9:50:21 AM
> -60
> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
> 2.17.1

**Comment by marwahaha** [comment]
Weird.

I think the documentation is wrong here: any string that is passed that does not contain `/[+-]00:?00/` will not set the offset. (If we accepted `0300` and the like, we might catch on years 😬  )

**Comment by icambron** [comment]
I agree we should change the docs. I think we can just remove the second sentence. Looking at the code, it seems pretty clear it's meant to ignore the "0300" case. Along the same lines, `utcOffset` also accepts 'Z' but that's not in the docs.

**Comment by icambron** [comment]
Closing in favor of https://github.com/moment/momentjs.com/pull/410
