### ISSUE TITLE
Kazakh locale (kk) is not loading

### ISSUE THREAD

**Issue by XAMeLi** [moment/moment#3797]
`moment.locale('kk')` is returning `"en"` and relative texts are in English - e.g. displays "a day ago" instead of "1 күн бұрын".

Steps taken:

1. Made sure `locale/kk.js` is loaded (via browser's "Network" tool). Also, a break-point in the file is reachable and stops when page is reloaded.
2. In browser's console, `IntlRelativeFormat.__localeData__` looks like this: `Object {en: Object, kk: Object, kk-cyrl: Object, kk-cyrl-kz: Object}`
3. `IntlRelativeFormat.__localeData__.kk` looks exactly as in the file.
4. all other ~40 locales of the application work as expected.
5. Executing `moment.locale('kk', IntlRelativeFormat.__localeData__.kk)` returns `"kk"` as expected, but application still shows English strings.

**Comment by tell-y** [comment]
`moment.locale('ja')` also does not work, returning value in English.

**Comment by marwahaha** [comment]
I'm not sure how to reproduce.

For example, in the browser console of http://momentjs.com/
```
x = moment()
x.locale("kk")
x.calendar()
```
produces `"Бүгін сағат 00:15"`

**Comment by icambron** [comment]
@XAMeLi Is Node a browser? If a browser, how are you loading Moment?

**Comment by marwahaha** [comment]
@XAMeLi Let us know how we can help with this.

**Comment by maggiepint** [comment]
Closing, inactive. Feel free to reopen if you still need help.
