### ISSUE TITLE
How to calculate user's current time zone in a format like America/Chicago etc depending on where user is located?

### ISSUE THREAD

**Issue by singhrasster** [moment/moment#3802]
My app uses Angular 2 for front end and Node as backend. I need to calculate the current timezone on Angular 2 front end based on user's location (browser/OS etc) and send it as part of HTTP call as part of query string. The calculated timezone should be of the string format: "America/Chicago" but ofcourse depending on user's location. I heard I could use Moment for this. If yes, how can I use moment to calculate timezone for the user's current location in the string format mentioned above?

**Comment by marwahaha** [comment]
I would recommend using Moment Timezone.
http://momentjs.com/timezone/

```
moment.tz.guess()
// "America/New_York"
```

**Comment by icambron** [comment]
@marwahaha is correct
