### ISSUE TITLE
German short months do not follow CLDR

### ISSUE THREAD

**Issue by fheidrich** [moment/moment#3803]
Looking at https://github.com/moment/moment/blob/develop/locale/de.js it has
`monthsShort : 'Jan.Febr._Mrz._Apr._Mai_Jun._Jul._Aug._Sept._Okt._Nov._Dez.'.split(''),`

Not exactly the same as spec'ed in CLDR
CLDR:
`<monthWidth type="abbreviated">`
`<month type="1">Jan.</month>`
`<month type="2">Feb.</month>`
`<month type="3">März</month>`
`<month type="4">Apr.</month>`
`<month type="5">Mai</month>`
`<month type="6">Juni</month>`
`<month type="7">Juli</month>`
`<month type="8">Aug.</month>`
`<month type="9">Sep.</month>`
`<month type="10">Okt.</month>`
`<month type="11">Nov.</month>`
`<month type="12">Dez.</month>`
`</monthWidth>`
Isn't moment suppose to follow the CLDR?

**Comment by icambron** [comment]
> Isn't moment suppose to follow the CLDR?

Citation needed. We often use CLDR as a source of info. We'd also like to eventually switch over to CLDR completely when/if they support all the strings we need. Finally, we've imagined several times automatically generating the portion of the locales that we can from CLDR. But until we do that, I don't think it's true that we're committed specifically to following CLDR.

That of course doesn't mean we're right about German months! A couple of other sources I quickly checked also leave out the periods for some of the months. What do you think, @lluchs?

**Comment by fheidrich** [comment]
The following came from our I18N engineers:
1) Visit http://unicode.org/Public/cldr/30.0.3/ 
2) Download cldr-common-30.0.3.zip
3) See common/main/de.xml

Please advise, thanks

**Comment by icambron** [comment]
I didn't mean citation that CLDR says that; I meant a citation that Moment is committed to following it. That said, I looked at a few other sources and they seemed to agree that the short months shouldn't have dots. So we'd accept a PR.

**Comment by Seldaek** [comment]
See #3829 for the PR doing the change to all German locales. I checked the CLDR for de-ch and de-at as well btw.

**Comment by lluchs** [comment]
Changing the abbreviations is fine by me - there aren't really any standard abbreviations. Moment's current list is as good as the one in CLDR.

**Comment by marwahaha** [comment]
Is this ticket related? https://github.com/moment/moment/issues/2649 What's your opinion on this, @lluchs  @Seldaek @fheidrich

**Comment by Seldaek** [comment]
Yes I would say it can be closed too although I did not remove the `.` as they strike me as being more common than not, and CLDR as well as other abbreviation sources have the dots in.

**Comment by fheidrich** [comment]
Thanks!

**Comment by maggiepint** [comment]
closing #3829
