### ISSUE TITLE
moment.d.ts: export as namespace moment;

### ISSUE THREAD

**Issue by oldrich-s** [moment/moment#3808]
It would be nice if you included `export as namespace moment;` into `moment.d.ts` to allow for consuming the moment declarations without ES6 modules.

**Comment by marwahaha** [comment]
Up-for-grabs. This needs to be TS 1.x compatible!

**Comment by nomaed** [comment]
So... is this thing going to be merged in?

**Comment by ovangle** [comment]
It can't be merged into 2.x, because 2.x needs to retain backwards compat for typescript 1... If you want to resubmit the changes against 3.x then we can have a discussion about setting a minimum supported typescript version a little higher.

**Comment by nomaed** [comment]
This should be compatible with TS 1.5+, shouldn't it?

**Comment by ovangle** [comment]
We don't actually have _any_ official minimum supported version of typescript unfortunately-- every dependency in our package.json is just `latest`. I just joined here -- don't blame me.

But there's only at most one version of 2.x to go, I'm assuming that the minimum version moment 2.x supports is 1.0. 

3.x will support `>=2.4.0` and there will be more frequent major releases going forward, so I'll make sure to put this in there when I do my typescript changes for that.

**Comment by ovangle** [comment]
Whoops, didn't mean to close this, I thought it was a PR.

**Comment by DavidJohnWilliams** [comment]
Hi guys, can anyone answer why this hasn't been merged yet? TypeScript supported modules from 1.5+ (besides is anyone is even still using older versions?). For those working on older projects that cannot target ES6 or use module loaders this would be most useful. Currently we have to manually add the line which means not being able to use package managers...

**Comment by ksorv** [comment]
2 years and this is still open! @marwahaha Anything? 
Want to review that pr above?

**Comment by marwahaha** [comment]
Sorry this is causing you pain.
This is a breaking change, as listed above.
When the maintainers have time to make such a change, we hope to include a fix for this.

**Comment by ksorv** [comment]
Hey Kunal,

This is not causing me anything.
I was just looking around, thought to help you guys as you guys seem pretty
busy.

Nothing else.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
