### ISSUE TITLE
fromNow reports wrong duration

### ISSUE THREAD

**Issue by pronebird** [moment/moment#3810]
Running this in electron/chromium:

```js
moment().startOf('day').add(27, 'days').fromNow(true) // a month
moment().startOf('day').add(26, 'days').fromNow(true) // 25 days
```

Really do not understand how's adding 27 days to "March, 6" makes it "a month". Less than a month, precisely 27 days from now on.

Something is fishy in there.

**Comment by maggiepint** [comment]
This is configurable: http://momentjs.com/docs/#/customization/relative-time-threshold/

**Comment by pronebird** [comment]
Thanks @maggiepint

**Comment by laura-chacon** [comment]
> Running this in electron/chromium:
> 
> ```js
> moment().startOf('day').add(27, 'days').fromNow(true) // a month
> moment().startOf('day').add(26, 'days').fromNow(true) // 25 days
> ```
> 
> Really do not understand how's adding 27 days to "March, 6" makes it "a month". Less than a month, precisely 27 days from now on.
> 
> Something is fishy in there.

Did you manage to do it? Because I am not being able to do it using `relativeTimeThreshold`. In mi case I want _a month ago_ if I have more 45 days instead of _two months ago_
