### ISSUE TITLE
endOf('day') on a Sunday date changes the timezone?

### ISSUE THREAD

**Issue by swapkids** [moment/moment#3820]
**Description of the Issue and Steps to Reproduce:**
`endOf('day')` on a Sunday date changes the timezone?

```
var date = new Date("Sat Mar 25 2017 00:00:00 GMT+0100 (CET)");
moment(date).endOf('day').toDate()  -> Sat Mar 25 2017 23:59:59 GMT+0100 (CET)

var date = new Date("Sun Mar 26 2017 00:00:00 GMT+0100 (CET)");
moment(date).endOf('day').toDate()  -> Sun Mar 26 2017 23:59:59 GMT+0200 (CET)

```
GMT+0200 ??

**Comment by icambron** [comment]
Yes, that's Daylight Saving Time. I guess your locale has it the morning of the 26th? (There is a reason we ask for you location in the issue template)
