### ISSUE TITLE
moment.toDate documentation outdated

### ISSUE THREAD

**Issue by prndP** [moment/moment#3822]
**Description of the Issue and Steps to Reproduce:**

Moment documentation currently indicates toDate returns a reference to the wrapped date object, and any changes to underlying date obj will be passed through
https://momentjs.com/docs/#/displaying/as-javascript-date/

However, in code, toDate now returns a copy of date as per
https://github.com/moment/moment/commit/b4b4efec9622bfb69eae49fd350fe6f19c31f897

Can you clarify which one should be the expected behavior?

Thanks

**Comment by maggiepint** [comment]
Copy is expected. We changed that a couple months ago.

**Comment by prndP** [comment]
Thank you for the quick response. I'll submit a PR in docs for this

**Comment by icambron** [comment]
I merged the docs PR so I'm going to close this. It will go out next build of the site.
