### ISSUE TITLE
Problem with FireFox

### ISSUE THREAD

**Issue by raminahmadi1986** [moment/moment#3825]
Hi ,
I Have a problem with firefox , the time that is display in firefox is wrong , but it's correct in other browsers .
code :
var c = moment.tz( 1488791859000 ,"Asia/Tehran").format("HH:mm");

I want to display date time in given locale format ("asia/tehran")

**Comment by icambron** [comment]
@raminahmadi1986 you'll need to open this ticket in the Moment Timezone repository [here](https://github.com/moment/moment-timezone). Also, when you do so, make sure you specify what version of Firefox this is, what specifically you expect that code to return, and what that code actually returns.
