### ISSUE TITLE
'M' format accepts '01' as valid month in strict mode

### ISSUE THREAD

**Issue by jasomimo** [moment/moment#3830]
**Issue:**

Parsing date string in a **strict mode** accepts two digit months and days, when just 'M' or 'D' format is specified. Other way around, when 'MM' format is specified and one digit month is provided parsing fails, as expected.

Why does 'M'/'D' formats accept '01' as valid moth/day respectively? 

**Environment:**
Tested in Chrome 56, moment.js 2.17.1

```js
moment('1/09/2017', 'MM/D/YYYY', true).isValid()  // false
moment('01/09/2017', 'M/D/YYYY', true).isValid()  // true
```

**Comment by icambron** [comment]
It's just [not quite that strict](https://github.com/moment/moment/blob/1d70961e1045b9cbf7ef83f0e403091bf14b7ff1/src/lib/units/month.js#L45). I agree it could be stricter, though it's not obvious to me offhand why it needs to be. What is your use case where you need it to be stricter?

**Comment by jasomimo** [comment]
Needed to implement TryParse logic, where for one base format e.g. 'MM/DD/YYYY', there is some kind of tolerance. So dates '01/09/2017', '01/9/2017' and '1/9/2017' should be accepted. It is done by transforming the base format to other allowed formats and then parsing by momentjs in strict mode. 

If 'M' and 'D' accepts '01' and '1' as valid, it would simplify custom TryParse logic, because 'M/D/YYYY' would cover multiple allowed formats. 

But I am not sure if this benevolent parsing for 'M' and 'D' formats is by design or it is a potential bug and will be fixed in future.

**Comment by icambron** [comment]
> But I am not sure if this benevolent parsing for M and D formats is by design or it is a potential bug and will be fixed in future.

We certainly did it on purpose, although I don't quite remember our reasoning. In general I'd rather leave it as is than change it.

**Comment by jasomimo** [comment]
Thanks for clarification, so it is not a bug and it can be counted on also in later releases.

**Comment by marwahaha** [comment]
I'd prefer to keep this open, figure out why, and add it to the docs before we close this one.

**Comment by vchabal** [comment]
Token `MM` has RegEx `/\d\d?/` and Strict RegEx `/\d\d/`
Token `M` has RegEx `/\d\d?/` and no Strict RegEx. So due this also 01 is matched. Check months definition in lib/units/month.js:45.

**Comment by marwahaha** [comment]
Thanks @vchabal - perhaps we can add it as a test in moment and/or on https://github.com/moment/momentjs.com/ so we don't forget about this behaviour.

**Comment by vchabal** [comment]
Strict month testing already present in [src/test/moment/create.js](https://github.com/moment/moment/blob/a1b527f761bab3e28c7e8926a76e76e6b3458348/src/test/moment/create.js#L966-L969).

In [documentation](https://github.com/moment/momentjs.com/blob/master/docs/moment/01-parsing/03-string-format.md) is mentioned something similar:

> Note that the number of `S` characters provided is only relevant when parsing in strict mode. In standard mode, `S`, `SS`, `SSS`, `SSSS` are all equivalent, and interpreted as fractions of a second. For example, `.12` is always 120 milliseconds, passing `SS` will not cause it to be interpreted as 12 milliseconds.

**Comment by marwahaha** [comment]
Thanks!
