### ISSUE TITLE
Issue with moment datetime in mozilla

### ISSUE THREAD

**Issue by Jaaichandran** [moment/moment#3836]
I have an issue with moment dates, it happens in Mozilla. I am using chrome and the issue is not getting in Chrome.

 var time="2017-03-01T13:31:00";
     var hours = moment(new Date(time), "dddd, MMMM Do YYYY, HH:mm:ss a").get('hour');
        var minutes = moment(new Date(time), "dddd, MMMM Do YYYY, HH:mm:ss a").get('minute');
alert(hours+":"+minutes)

The alert returns 13:31 in Mozilla and 01:31 in Chrome, I want the Chrome version of the time and when using in Mozilla it will increment the day by 1. So that I get a future date(tomorrow).

I am including the JsFiddle.
https://jsfiddle.net/jayachandranr/p7h0wunt/

**Comment by maggiepint** [comment]
You aren't using moments date parser, you're using the one from the JavaScript date object - that's why it's broken. The date you have is in ISO8601 format, so your code should simply be:

```
moment('2017-03-01T13:31:00').get('hour')
```
