### ISSUE TITLE
Some date/time string are not formatted according to CLDR

### ISSUE THREAD

**Issue by jha-nishant** [moment/moment#3838]
**Some date/time string are not formatted according to CLDR http://unicode.org/Public/cldr/30.0.3/** 

According to German CLDR definition (common/main/de.xml) , the date formatting "20. Febr. 2017" is incorrect, the abbreviated text for February in CLDR is "Feb", and applying follow the format 
"<dateFormatItem id="GyMMMd">d. MMM U</dateFormatItem>" , it should be "20. Feb. 2017".

**Comment by marwahaha** [comment]
I think this is fixed by #3829 . What do you think @jha-nishant ?

**Comment by maggiepint** [comment]
closing in favor of #3829
