### ISSUE TITLE
'Y' format returns <4 digits for years in range [-999,999]

### ISSUE THREAD

**Issue by balagge** [moment/moment#3842]
**Description of the Issue and Steps to Reproduce:**

If the year component of a date is in the range -999 to +999, the 'Y' formatting option drops leading zeroes. 

This MAY be deliberate, but the documentation of the 'Y' token on momen#format says:

"This complies with the ISO 8601 standard for dates past the year 9999"

It does work correctly for years >= 10000 (includes mandatory '+') I guess the standard should be adhered to for year values between -999 and +999. ISO 8601 prescribes a **minimum of** four digits in the year part.

https://en.wikipedia.org/wiki/ISO_8601#Years

Example: expected results of the 'Y' token for different year values (value -> formatted value)

-10000 -> -10000
-1234 -> -1234
-999 -> **-0999**
-2 -> **-0002**
0 -> **0000**
123 -> **0123**
999 -> **0999**
1234 -> 1234
9999 -> 9999
10000 -> +10000

Those marked bold are not working like this at the moment (no leading zeroes added) to make the year part contain at least four characters.

If, for some reason, this behavior is not desired, then it would be great to add another year token which is fully ISO 8601 compliant.

**Comment by marwahaha** [comment]
I'm not quite sure if this is what we want. (I'm a new maintainer for Moment.)

But, if we want to change the `Y` token, I have a PR ready.

**Comment by ichernev** [comment]
So then what is the difference between Y and YYYY? Y parses shorter things?

**Comment by marwahaha** [comment]
It seems like `Y` should handle full ISO 8601 compliance.

**Comment by balagge** [comment]
Clarification: This is about **formatting**, not parsing.

I think it would be great to have a formatting token (either `'Y'` or, if not desired, because that one is intended for something else, then maybe a new one) for ISO 8601 years.

I believe (1) the standard requires **4 or more digits for any year value**

I believe (2) the standard requires a **sign (even positive) before any year value which has 5 or more digits**.

- The `'Y'` token conforms to (2) but not (1).

- The `'YYYY'` token conforms to (1) but not (2).

The request is: either change `'Y'` to conform to (1) (which is what I was originally suggesting), or a new token could be introduced instead.

**Comment by balagge** [comment]
I looked up the current ISO 8601:2004 version, because I was not sure about the accuracy of Wikipedia.

Here are the relevant parts, which means that I was not entirely correct: The ISO has a basic range of 0000 to  9999 (inclusive) as the year part, which is always 4 characters long. Anything outside of that range would, in theory, require an "expanded representation", which must have a **predefined number of characters** in the year part. (in the guide this is assumed to be 6). This requires "mutual agreement" of the parties communicating.

>  **3.6. Leading zeros**
>
> If a time element in a defined representation has a defined length, then leading zeros shall be used as required.
>
> **3.7 Mutual agreement**
>
> Some of the representations identified in this International Standard are only allowed by mutual agreement of the partners in information interchange. Such agreement should ensure that fields in which the representation may occur are not allowed to hold other representations that cannot be unambiguously distinguished from the agreed representation.
> 
> **4 Date and time representations**
>
> [...]
>
> **4.1.2 Calendar date**
>
> **4.1.2.1 General**
>
> In expressions of calendar dates
>
> - calendar year is, unless specified otherwise, represented by four digits. Calendar years are numbered in ascending order according to the Gregorian calendar by values in the range [0000] to [9999]. Values in the range [0000] through [1582] shall only be used by mutual agreement of the partners in information interchange.
>
> [...]
> 
> **4.1.2.2. Complete representations**
> 
> When the application identifies the need for a complete representation of a calendar date, it shall be one of the numeric expressions as follows, where [YYYY] represents a calendar year, [MM] the ordinal number of a calendar month within the calendar year, and [DD] the ordinal number of a calendar day within the calendar month.
> 
> Basic format: YYYYMMDD Example: 19850412
> Extended format: YYYY-MM-DD Example: 1985-04-12
[...]
>
> 
> **4.1.2.4 Expanded representations**
> 
> If, by agreement, expanded representations are used, the formats shall be as specified below. The
> interchange parties shall agree the additional number of digits in the time element year. In the examples below it has been agreed to expand the time element year with two digits.
> 
> a) A specific day
> Basic format: ±Y̲YYYYMMDD Example: +0019850412
> Extended format: ±Y̲YYYY-MM-DD Example: +001985-04-12

Note: in the representations above, ± means a mandatory sign (either + or -), Y̲ means zero or more extra digits in the year part.
