### ISSUE TITLE
Obsolete Timezones returned from moment.tz.guess()

### ISSUE THREAD

**Issue by AppliedEllipsis** [moment/moment#3852]
moment.tz.guess() detects obsolete timezones.
You can test by using Buenos Aires timezone.
It will detect America/Buenos_Aires, when that is obsolete and needs to be America/Argentina/Buenos_Aires
Another example is 
Asia/Calcutta being obsolete and should be Asia/Kolkata
You can test with the vanilla CDN

```

<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.11/moment-timezone-with-data-2010-2020.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function(e) {

  var tz = moment.tz.guess();
  alert(tz);
});
</script>




```
The impact is languages like PHP don't recognize the obsolete timezones in DateTimeZone::listIdentifiers().

References
http://www.timezoneconverter.com/cgi-bin/zoneinfo.tzc?s=default&tz=America/Buenos_Aires
http://www.timezoneconverter.com/cgi-bin/zoneinfo.tzc?s=default&tz=Asia/Calcutta

**Comment by maggiepint** [comment]
This is actually a result of the following function from the Intl API when run in chrome (I personally am on Windows but I'm not sure if it matters):
```js
Intl.DateTimeFormat().resolvedOptions().timeZone
```

I'll tend to agree that the 402 spec should be changed to use canonical time zone names, but I'm disinclined to make a workaround in moment-timezone given that these zone identifiers should work fine. I'll raise an issue on 402.

**Comment by mj1856** [comment]
> The impact is languages like PHP don't recognize the obsolete timezones in DateTimeZone::listIdentifiers().

While PHP may not list these via that particular method, it certainly supports them.  I can understand that you may need to canonicalize it first if you expect to use it to pick a default user time zone from a list.

PHP does have CLDR support.  You should be able to use [`IntlTimeZone::getCanonicalID`](http://php.net/manual/en/intltimezone.getcanonicalid.php) to get the behavior you're looking for.

**Comment by snerror** [comment]
> The impact is languages like PHP don't recognize the obsolete timezones in DateTimeZone::listIdentifiers().

PHP `DateTimeZone::listIdentifiers()` can actually recognize obsolete timezones if you use [ALL_WITH_BC](http://php.net/manual/en/class.datetimezone.php#datetimezone.constants.all-with-bc) constant when calling the function.

**Comment by srp321** [comment]
I still am having this issue and just because of this obsolete data, my application is behaving erratically in few time-zones.
A detailed issue what i have been facing has been asked my me on SO, below's the link to that:

[https://stackoverflow.com/questions/50835668/issue-with-moment-js-method-moment-tz-guess-in-chrome-browser/](url)

Although i do think this bug needs to be discussed again in details, but for the time being, any help or workaround would be very appreciated

**Comment by srp321** [comment]
> @srp321 do you get any permanent fix for it?
> What I have is the list of google Calender Timezone, where there is no timezone like ##Asia/Calcutta instead they have ##Asia/Kolkata. When I am trying to get the current timezone through moment.tz.guess() it gives me ##Asia/Calcutta in chrome which is not present in the google calender timezone list, so no default selection shows by me Timezone Selector Input Field

Nope, till few months back, I hadn't got any permanent fix for it.
Not sure about the current situation although.

**Comment by AppliedEllipsis** [comment]
I believe I did the same hack mentioned in earlier comments. I think I created a hash table for that project to map the problematic results as we found them.

**Comment by ayuhito** [comment]
For those in the future who may run into this, it is worth tracking [tc39/proposal-canonical-tz](https://github.com/tc39/proposal-canonical-tz) that aims to resolve these issues.

It's a very deep rabbit hole (I needed it to create [timezone to country name mappings](https://github.com/medama-io/go-timezone-country/tree/main)), but it is a great source to find existing workarounds for any issues you may encounter.
