### ISSUE TITLE
Strange char in moment.js

### ISSUE THREAD

**Issue by NielsHolt** [moment/moment#3855]
Hi

When I download moment 2.18.0 on my Windows 10 PC there are a strange  char in moment.js at line 361 at col 48. It seems to be at "A0" instead of "20"

It doesn't seems to be a problem on Unix

**Comment by ucsdmath** [comment]
JSC_PARSE_ERROR: Parse error. Character '¬' (U+00AC) is not a valid identifier start char at line 361 character 47
        (this._dayOfMonthOrdinalParse.source ||¬†this._ordinalParse.source) +

**Comment by butterflyhug** [comment]
See #3853.

**Comment by icambron** [comment]
The fix is in 2.18.1
