### ISSUE TITLE
Short months are not valid

### ISSUE THREAD

**Issue by mkudelya** [moment/moment#3856]
Hi

I found a bug when months with trailing period aren't valid. I have tested this on version 2.17.1. Can you please tell me if you are planning on fixing this error? If so, in which version? Here is [code example](https://jsfiddle.net/99sejg9j/5/). Probably this issue is duplicate of this one #2186.

**Comment by icambron** [comment]
It's fixed in 2.18.1. Here's the fiddle: https://jsfiddle.net/99sejg9j/6/
