### ISSUE TITLE
Regression on electron

### ISSUE THREAD

**Issue by bresotec-bear** [moment/moment#3857]
**Description of the Issue and Steps to Reproduce:**
Version 2.17.1 works fine in [Electron](https://electron.atom.io/), but version 2.18.0 shows error:

    Uncaught SyntaxError: Unexpected token this at moment.js:361

After downgrade `moment.js` to 2.17.1, the error disappeared.

**Environment:**
`Electron 1.6.2`

**Comment by icambron** [comment]
See https://github.com/moment/moment/pull/3853. We released 2.18.1 that fixes this.
