### ISSUE TITLE
toDate() doesn't create copy of date

### ISSUE THREAD

**Issue by Sybe** [moment/moment#3858]
**Description of the Issue and Steps to Reproduce:**
Calling a toDate() on a moment will not create a copy of the date wrapped by the moment, but a pointer to the actual date that is still used by the moment.
Example:
```js
var m = new moment();
var begin_date = m.startOf('month').toDate();
var end_date = m.endOf('month').toDate();
console.log(begin_date);
console.log(end_date);
```
returns
```
Fri Mar 31 2017 23:59:59 GMT+0200 (CEST)
Fri Mar 31 2017 23:59:59 GMT+0200 (CEST)
```
Here I expected the begin_date to be March 1st.

**Environment:**
Using on server. Meteor 1.4.3.1, node 4.7.3, momentjs 2.13.0

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
the navigator.userAgent crashed the application, logs of other calls:
```
Wed Mar 22 2017 10:26:51 GMT+0100 (CET)
3/22/2017, 10:26:51 AM
-60
2.13.0
```

**Comment by maggiepint** [comment]
This behavior was changed in either 2.16 or 2.17 - can't remember which. Upgrade your version of the library.
