### ISSUE TITLE
moment().isSame(undefined, 'day') returns true

### ISSUE THREAD

**Issue by grebenyuksv** [moment/moment#3859]
Dear moment team, `moment().isSame(undefined, 'day')` is returning `true` to me. 

Here's a [jsfiddle](https://jsfiddle.net/u7xvzwzo/).

Am I missing something?

**Comment by maggiepint** [comment]
This is working as designed. It is common in most JS APIs that the behavior of calling a function with undefined as a parameter is the same as calling with no parameters at all. `.isSame` expects a moment-like object as the first parameter - that is to say a moment, string, or JS Date - and it converts that parameter into a `moment` object. 

By convention in this library, anything that expects a moment-like will treat no parameter being passed, or undefined, as the same as calling `moment()`. 

At this point, we aren't interested in changing this behavior. It would involve checking the length of arguments all over the code base, and I'm not sure if it has much benefit. If you feel strongly that this should be different, I'm open to argument, but for now I"m closing this issue.
