### ISSUE TITLE
1 test failed. locale:x-pseudo:calendar day (2493.6) 

### ISSUE THREAD

**Issue by ghandmann** [moment/moment#3866]
Hi There,
just occasionally ran the testframework and got an error. Yesterday at 02:00AM Germany switched to DST. Therefore there was no 02:00am but instantly 03:00am.

Not sure, if this is a bogus test-case which simply fails 2 times a year (if DST is applicable) or should be handled transparently by the library.

### Client info
```
Date String   : Mon Mar 27 2017 09:47:42 GMT+0200 (CEST)
Locale String : 27.3.2017, 09:47:42
Offset        : -120
User Agent    : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.1144
Moment Version: 2.18.1
```

====

### locale:x-pseudo:calendar day (2493.6) 

yesterday at the same time

```javascript
// Expected Ý~ést~érdá~ý át 02:00
// Actual   Ý~ést~érdá~ý át 03:00
"Ý~ést~érdá~ý át 03:00" === "Ý~ést~érdá~ý át 02:00"
```

**Comment by icambron** [comment]
Thanks for the report.

> Not sure, if this is a bogus test-case which simply fails 2 times a year (if DST is applicable) 

I'm pretty sure that's what this is. With a couple of exceptions, the library itself works well with DSTs, but the tests make lots of assumptions in their asserts that aren't valid across DSTs, leading to test failures like this; i.e. Moment did what it was supposed to but the test didn't expect it to, so it failed. So I'm going to close this as probably-not-a-real-problem.
