### ISSUE TITLE
utcOffset parses a phantom zone from an ISO8601 string without an offset

### ISSUE THREAD

**Issue by kring** [moment/moment#3878]
`moment('2015-01-01T00:00:00').utcOffset('2015-01-01T00:00:00').format()`

returns:

`2014-12-31T12:00:00-01:00`

See the jsfiddle:
https://jsfiddle.net/aa25w17t/

-01:00 is not my time zone (it's +11:00), it appears to be parsing that from the date.  For example, if I change `2015-01-01` to `2015-01-02`, the offset changes to `-02:00`

Also, `moment.parseZone('2015-01-01T00:00:00').format()`, which the docs say should be equivalent, returns the expected result (`2015-01-01T00:00:00Z`).

**Environment:**

```js
console.log( (new Date()).toString()) -> "Fri Mar 31 2017 15:46:47 GMT+1100 (AUS Eastern Daylight Time)"
console.log((new Date()).toLocaleString()) -> "3/31/2017, 3:46:47 PM"
console.log( (new Date()).getTimezoneOffset()) -> "-660"
console.log( navigator.userAgent) -> "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
console.log(moment.version) -> "2.18.1"
```

**Comment by icambron** [comment]
Looks like a bug to me. `utcOffset()` isn't handling the absence of zone information right. I suspect you're right about it just finding something offset-looking anywhere in the string. I personally think it's a little silly to allow `utcOffset()` to take in whole ISO strings like that, but that's what the API is, so we should make it work.

**Comment by marwahaha** [comment]
parseZone isn't doing this correctly either.
* UTCOffset will try finding a short-offset ([+-]\d\d with optional :\d\d) (which sadly catches on some days, like '-01' and so on.
* parseZone will try finding a long-offset ([+-]\d\d:?\d\d), othewise defaults to Z.

So, if you change the parsing string, parseZone will always go to Z, but UTCoffset catches on random days.

I'm not sure what the best way forward is @icambron

**Comment by andyhelp** [comment]
Similar issue when initialising.
If it is the same, I wonder if offset parsing can be done on remaining string not already "consumed/parsed" by date and time.
```
Welcome to Node.js v12.17.0.
Type ".help" for more information.
> const moment = require('moment')
undefined
> moment('2020-03-28 20:00')
Moment<2020-03-28T20:00:00+00:00>   <--- Expected +01:00 (my default tz)
> moment('2020-03-29 20:00')
Moment<2020-03-29T20:00:00+01:00>   <--- Correct
> moment.version
'2.27.0'
```

**Comment by marwahaha** [comment]
I've updated the documentation, but i don't think we should change the functionality. The string can be a shortOffset, so ISO8601 dates without offsets will parse incorrectly.
