### ISSUE TITLE
isSame 'day' not working well

### ISSUE THREAD

**Issue by SuperMariosYoshi** [moment/moment#3882]
Hello, today i noticed one issue with isSame function,  so when i try example from official documentation
moment('2010-01-01').isSame('2010-02-01', 'day');   // false, different month **this works well**

moment('2009-01-01').isSame('2010-01-01', 'day');  // false 
when i try same example but with same day and month i still get false, this will only work if year is same, i'm wondering is that expected behavior or i should get here true, since month and day are actually same, and only different param is year?

**Comment by marwahaha** [comment]
http://momentjs.com/docs/#/query/is-same/

```
When including a second parameter, it will match all units equal or larger. Passing in month will check month and year. Passing in day will check day, month, and year.
```

isSame checks if two moments are the "same". The unit argument (i.e. "day") would check if two moments have the same day AND all units larger. For example, a moment at 9am and at 4pm would be the same day.

Thanks for filing the ticket.

**Comment by nealoke** [comment]
@marwahaha So how do you figure out if `moment('2000-10-10')` is the same as `moment('1993-10-10)`? So only comparing day and month (not year)?
