### ISSUE TITLE
Any way to guess/detect 12h vs. 24h time format?

### ISSUE THREAD

**Issue by hundsim** [moment/moment#3885]
With Moment Timezone's  [moment.tz.guess();](https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/) we get timezone detection.

Is there any way to use Moment in the same manner to detect time format convention, i.e. 12h or 24h?

**Comment by icambron** [comment]
There is nothing built into Moment, but if you stick to [modernish browsers](https://caniuse.com/#search=intl), it's pretty easy:

```js
new Intl.DateTimeFormat('en-gb', {hour: 'numeric'}).resolvedOptions().hour12; //=> false
new Intl.DateTimeFormat('en-us', {hour: 'numeric'}).resolvedOptions().hour12; //=> true
```
