### ISSUE TITLE
PHP’s DateTime parsing

### ISSUE THREAD

**Issue by gscscnd** [moment/moment#3887]
In PHP, there’s a [DateTime](https://secure.php.net/manual/en/class.datetime.php) class. When I run the following code:

```php
echo json_encode(new DateTime());
```

I get a JSON string: `{"date":"2017-04-04 18:38:42.000000","timezone_type":3,"timezone":"Europe\/Berlin"}`. Such string may be used for example in an API response, to be read by a JavaScript client application (as a JSON object) that’d like to display this date — but it has to parse it first. It’s possible to do the following:

```typescript
const date = moment(theDateFromResponse.date);
```

And then somehow set correct timezone. But what do you think about parsing the whole mentioned JSON object by moment? For example:

```typescript
let date = moment({
  // assume the following comes from API response
  date: '2017-04-04 18:38:42.000000',
  timezone_type: 3,
  timezone: 'Europe/Berlin'
});

// print “2017-04-04T18:38”
console.log(date.format('Y-MM-DDTHH:mm'));
```

**Comment by marwahaha** [comment]
This doesn't feel like a crazy idea. But I'm not too sure what all the fields are. What's `timezone_type`?

For now, you can do `moment.tz('2017-04-04 18:38:42.000000', 'Europe/Berlin')`

**Comment by gscscnd** [comment]
From [https://stackoverflow.com/a/17711005/7178441](https://stackoverflow.com/a/17711005/7178441):

> * Type 1; A UTC offset, such as in new DateTime("17 July 2013 -0300");
> * Type 2; A timezone abbreviation, such as in new DateTime("17 July 2013 GMT");
> * Type 3: A timezone identifier, such as in new DateTime( "17 July 2013", new DateTimeZone("Europe/London"));

On the other hand, there’s [bug 49382](https://bugs.php.net/bug.php?id=49382) that suggests, that it shouldn’t be possible to use `json_encode` on a `DateTime` object.

**Comment by maggiepint** [comment]
This feature can't go in core moment because it relies on Moment-timezone being present to handle the IANA identifier if it is presented. Really all that is happening here is that some business logic needs to be implemented to choose between moment factory functions based on the timezone_type. The code is simply:

``js
if(phpDate.timezone_type === 1)
    moment.parseZone(phpDate.date + phpDate.timezone) //concatenate the string to ISO8601 w/offset
else if (phpDate.timezone_type === 3)
    moment.tz(phpDate.date, phpDate.timeZone)
```
Note that we can't support parsing of the three-letter timezone abbreviation because it is inherently ambiguous. CST is both Central Standard Time and China Standard time. If those three letter abbreviations are guaranteed to be US though, one could manually map them to offsets.

This probably could make a great plugin, as long as it was understood that `moment-timezone` had to be loaded for it to work. If you were to make it, feel free to list it in the docs: http://momentjs.com/docs/#/plugins/

**Comment by gscscnd** [comment]
OK, thank you for feedback.
