### ISSUE TITLE
You guys are awesome.

### ISSUE THREAD

**Issue by rudimk** [moment/moment#3891]
This isn't an issue or a bug report. 

I stumbled upon [Tim's post](https://medium.com/@timrwood/moment-endof-term-522d8965689) from way back last year, where he talks about the relationship between open source and feeling burnt out. I realized that hey, here's a library that I used and loved - _really_ used, and I have no idea who really built it, who maintains it. You have no idea how many times moment and moment-timezone have both saved my bacon, when it boiled down to handling date/time algebra, or easy tz conversions.

Tim, Iskren, Matt, Maggie, Isaac, Andre, JD, Lucas - a huge thank you for bringing moment to where it is today - it's not just the best Javascript library to get datetimes done, it's become the blueprint of sorts, when it comes to datetime libraries. Thank you for your work, which can get pretty intense and thankless at times. :)

**Comment by maggiepint** [comment]
We love this, and I'm not sure if anybody has the heart to close it :-)

**Comment by icambron** [comment]
Thanks @rudimk!

I am going to close this though

**Comment by maggiepint** [comment]
@icambron :-(
