### ISSUE TITLE
isValid behaves unexpectedly

### ISSUE THREAD

**Issue by OliverFischer** [moment/moment#3900]
**Description of the Issue and Steps to Reproduce:**
When trying to use isValid() moment.js behaves some kind of strange.
*Please include the values of all variables used.*
Tests:
Captured from the node.js repl:
> moment('10.12.2012','DD.MM.YYYY').isValid()
true
> moment('10.12.2012','DD.MM.YYY').isValid()
true
> moment('10.12.2012','DD.MM.YY').isValid()
true
> moment('10.12.2012','DD.MM').isValid()
true
> moment('10.12.2012','DD.MM.YYYY').isValid()
true
> moment('10.12.201A2','DD.MM.YYYY').isValid()
true
> moment('10.12.AAAA','DD.MM.YYYY').isValid()
true
> moment('10.12.not a year','DD.MM.YYYY').isValid()
true

**Environment:**
node v7.6.0 on mac os x sierra
```
Sat Apr 08 2017 00:06:05 GMT+0200 (CEST)
4/8/2017, 12:06:05 AM
-120
2.18.1
```

**Comment by OliverFischer** [comment]
Especially the last command ```moment('10.12.not a year','DD.MM.YYYY').isValid()```seems to be a wrong, or not?

**Comment by maggiepint** [comment]
You need to use 'strict mode' - the parser is by default forgiving. This is something we have wanted to change as the default, but haven't yet for a variety of reasons. See the parsing guide for more information: http://momentjs.com/guides/#/parsing/strict-mode/
