### ISSUE TITLE
1 hour difference when using epoch time

### ISSUE THREAD

**Issue by Doddzy** [moment/moment#3909]
I have a very unexpected behaviour today around epoch time where it actually loses an hour, if I do the following:
```js
moment(0).add(1, 'day').subtract(1, 'day').format()
```
It will return "1970-01-01T10:00:00+11:00"

However if I do:
```js
moment(0).format()
```
It will return "1970-01-01T10:00:00+10:00".

This isn't simply an issue of the timezone information changing, it is actually losing an hour in the process. (The top example still thinks it's 10 am even with +11 timezone)

**Environment:**
Both Chrome 57 and Node 7.4.0 on OSX

toString: Thu Apr 13 2017 11:01:48 GMT+1000 (AEST)
localeString: 13/04/2017, 11:01:48
timezoneOffset: -600
momentVersion: 2.18.1

**Comment by mj1856** [comment]
Thanks.  I'm looking into it.

**Comment by mj1856** [comment]
I can reproduce this, but it's not our bug.  It appears to be a bug with a component shared between Chrome and Node.  Probably ICU.

It's putting a "fall-back" style transition right at the local equivalent of `1970-01-01T00:00:00Z`, but only if the local time zone has some DST transitions, and only for those with higher positive standard offsets.  I was able to reproduce it with `Australia/Adelaide`, `Australia/Sydney`, and all others east of those that have DST.

I can also reproduce this without moment at all:

```bash
TZ=Australia/Sydney node
```
```js
> new Date(0).toString() // 'Thu Jan 01 1970 10:00:00 GMT+1000 (AEST)'
> new Date(-1).toString() // 'Thu Jan 01 1970 10:59:59 GMT+1100 (AEDT)'
```
There should be no transition here.  It's not in the TZDB data anyway.

I'll keep this open to track for now - but recognize it's not a Moment bug, so there's not much we can do about it.

**Comment by icambron** [comment]
@mj1856 Can I close this?

I'd also like to point out the browser vendors are just mean to Australia. See #2315 and #1145 for nasty Safari DST bugs there.

**Comment by maggiepint** [comment]
Let's close this here. I'll pass to TC39 for one of the V8 implementers to hunt down.

**Comment by littledan** [comment]
If this is an issue, I think it's in glibc. I am seeing the same results in ChakraCore, JSC, V8 and SpiderMonkey, and I think they all call out to glibc for these times on Linux.
