### ISSUE TITLE
[Question] How to get expected humanize duration 

### ISSUE THREAD

**Issue by muhammad-ammar** [moment/moment#3912]
momentjs version is 2.17.1

`moment.duration('00:00:45').humanize()` gives `a minute`
`moment.duration('00:123:00').humanize()` gives `2 hours`

Anyway to get `45 seconds` and `123 minutes` for the above respectively?

**Comment by mj1856** [comment]
You can set the [relative time thresholds](http://momentjs.com/docs/#/customization/relative-time-threshold/), such as follows:

```js
moment.relativeTimeThreshold('m', Number.MAX_VALUE);  // Never display hours
moment.relativeTimeThreshold('s', 60); // Display minutes when 60 seconds has been reached
moment.relativeTimeThreshold('ss', 0); // Never display "a few seconds"

moment.duration('00:00:45').humanize()  // "45 seconds"
moment.duration('00:123:00').humanize()  // "123 minutes"
```

However, you might want to think about whether `humanize` is the right function for you.  If you know you always want the results in a particular unit, then use something like `.as('seconds')` or `.as('minutes')` instead.

**Comment by muhammad-ammar** [comment]
Thanks @mj1856
