### ISSUE TITLE
Moment fromNow not working on ios

### ISSUE THREAD

**Issue by theomathieubhvr** [moment/moment#3913]
**Description of the Issue and Steps to Reproduce:**

moment(date).fromNow(); returns invalid date.

Same with 
moment().subtract(1, 'days').fromNow();
moment().fromNow();

**Environment:**

IOS Cordova (WKWebView IOS 10)

**Other information that may be helpful:**

```js
console.log( (new Date()).toString()) => Mon Apr 17 2017 11:28:41 GMT-0400 (EDT)
console.log((new Date()).toLocaleString()) => 2017-04-17 11:28:41
console.log( (new Date()).getTimezoneOffset()) => 240
console.log( navigator.userAgent) => Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like
            Gecko) Mobile/14D27 (4301327536)
console.log(moment.version) => 2.18.1
```

Thanks !

**Comment by mj1856** [comment]
What is the `date` variable in your input?  A string?  A `Date` object? Something else?  It's reasonable to get "Invalid Date" if your input value is not a valid date.

However, it's not possible for the other two to return `Invalid Date` because there is nothing being input.  Are you sure you get the same "Invalid Date" response for those?  Can you show us?

**Comment by theomathieubhvr** [comment]
`date` is a string based date.

When I do moment(date).format() it shows the good result.

I am sure that the 2 others return `Invalid Date`. What do you want me to show you ? Screens ?
console.log(moment().subtract(1, 'days').fromNow()) returns `Invalid Date`.

Thanks 👍

**Comment by theomathieubhvr** [comment]
Let me know if you need any console.log results or anything else.

**Comment by mj1856** [comment]
An example of the string that you pass would be useful.

And yes, a screenshot or something to show it failing would be useful.  We have a LOT of users, and nobody else has complained that basic functionality isn't working on iOS.  How are you loading in moment? Is it a simple web page with a script tag, or are you using something more advanced?

**Comment by mj1856** [comment]
This jsFiddle: https://jsfiddle.net/c15p8rkw/

Works just fine on an iPhone 6S on [BrowserStack](https://www.browserstack.com/).

![image](https://cloud.githubusercontent.com/assets/1396388/25154609/30534192-2446-11e7-9604-5fa95e772d48.png)

**Comment by theomathieubhvr** [comment]
Yes I am aware of being the only one with this issue. Thanks for your help !! It might be coming from Cordova IOS. I'm using Webpack 2 (with ionic2).

This is how I import your momentjs : `import * as moment from 'moment';`.

![capture d ecran 2017-04-18 a 17 57 34](https://cloud.githubusercontent.com/assets/24896997/25154903/90fda428-2460-11e7-8fe5-8f648eee7923.png)

![capture d ecran 2017-04-18 a 17 55 46](https://cloud.githubusercontent.com/assets/24896997/25154905/943cd7d0-2460-11e7-9eec-779fc2742877.png)

**Comment by butterflyhug** [comment]
That's very interesting.

Could you try logging the result of `moment.now()`, `Date.now()`, and `+(new Date())`?

**Comment by theomathieubhvr** [comment]
Thanks again for your help.

You question made me understand that it was coming from syncing clock with server.

I did what is explained here https://github.com/moment/moment/issues/2337#issuecomment-94596647 but it failed for some reasons (caused by my use of Date constructor).

I still don't understand why it did not work only on ios, but mystery solved.

Thanks everybody, I hope this will help some other people with the same issue as me.

**Comment by mj1856** [comment]
So if you're using a newer release of Moment and need to change the time source, then you should override the `moment.now` function as described in the docs [here](https://momentjs.com/docs/#/customization/now/).

It's often used during testing, but sure - you can use it to sync with a server's clock.  Just keep in mind you'll need to incorporate the `Date` object or another timer such that time still advances.  Also, accuracy will be impacted by transmission latency from the server.

Glad you found the source of the problem.

**Comment by hmartin** [comment]
@theomathieubhvr i've the same problem... You said mystery solved, but the problem is still here. I understand that is not a moment.js problem, but may be it can be usefull to have a solution here to "help some other people with the same issue as me"!
Thanks in advance
