### ISSUE TITLE
4-digit year not recognized as valid ISO date

### ISSUE THREAD

**Issue by j0hj0h** [moment/moment#3916]
When parsing a date with just a year, there appears a warning in the console, that it is not a valid ISO or RFC format. But just a year should be valid: https://www.w3.org/TR/NOTE-datetime

https://jsfiddle.net/yke0c876/3/

```js
> moment('2000');
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions ...
```

Environment: Chrome 57 on OSX

**Comment by mj1856** [comment]
In general, we support the formats listed [here](http://momentjs.com/docs/#/parsing/string/), unless you provide a format string.

However, there's something to be said about being consistent with handling of incomplete representations.  Rewritten as #3918.  Thanks.
