### ISSUE TITLE
Minimising bundle size

### ISSUE THREAD

**Issue by stevermeister** [moment/moment#3917]
I'm trying to minimise the bundle size of my application with moment in (that is installed via npm and included like `import * as moment from 'moment'; import 'moment/locale/nl';`). 

I'm using [source-map-explorer](https://www.npmjs.com/package/source-map-explorer) to see the details:

![screen shot 2017-04-18 at 16 28 38](https://cloud.githubusercontent.com/assets/1526680/25135979/190b706e-2454-11e7-81d1-fc28e1e812ce.png)

Looks like it includes all the locales by default. Could I load only needed ones?

**Comment by alburthoffman** [comment]
yes. you can just remove all those unused locale files and re-bundle them into one.
As long as you only use locale n1, then that's fine.

**Comment by stevermeister** [comment]
But could you give me a hint how to do it?
this lines include everything:

    import * as moment from 'moment'; 
    import 'moment/locale/nl';

**Comment by maxailloud** [comment]
I'm looking to do the same.
We don't often use all the locale files in an app so having all fo them is kind of too much.

**Comment by TracyDa** [comment]
Yeah, me too, I just want use `moment(startTime),` but it seems still need 120kb.

And I tried `new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, ),` it doesn't work.

**Comment by screendriver** [comment]
Maybe [this one](https://webpack.js.org/plugins/context-replacement-plugin/) can help you? For me it worked fine.

You could also look here #2373 or here #4025

**Comment by WangYang-Rex** [comment]
I'm looking to do the same, How to figuare it out

**Comment by manico** [comment]
I'm using moment inside vue and I'm importing moment in several components:

`import moment from 'moment';`

When running webpack distribution, `CommonsChunkPlugin` does not pick up moment and does not extract it but it places it into all chunks. Is there a solution for this?

**Comment by marwahaha** [comment]
We're open to creative ways to reduce bundling size in Moment. There are various solutions in issues like these for Webpack and other bundlers. We would love PRs on our [docs repo](https://github.com/moment/momentjs.com) with tips and suggestions.

It's unclear how best to package moment with its locales. Should we publish a package for each locale, (with the existing package publishing all locales?) Are there other ways to solve this problem?

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.
For creative solutions, please submit to https://github.com/moment/momentjs.com/
