### ISSUE TITLE
Parsing `+0000` timezones in RFC 2822 strings incorrectly

### ISSUE THREAD

**Issue by jgr3go** [moment/moment#3920]
When parsing a date with a `+0000` timezone modifier at the end (RFC format), it parses it incorrectly. 

    $> moment.version
    '2.18.1'
    $> moment('Mon, 02 Jan 2017 06:00:00 -0800').format()
    '2017-01-02T01:00:00-05:00'
    $> moment(new Date('Mon, 02 Jan 2017 06:00:00 -0800')).format()
    '2017-01-02T09:00:00-05:00'

I am currently in EST, so the second output is what the actual time should be. 

**Environment:**
Chrome 57 and NodeJS 7.x on Windows 10

```js
console.log( (new Date()).toString()) // Wed Apr 19 2017 19:58:19 GMT-0400 (Eastern Daylight Time)
console.log((new Date()).toLocaleString()) // 4/19/2017, 7:58:19 PM
console.log( (new Date()).getTimezoneOffset())  // 240
console.log( navigator.userAgent) // ReferenceError: navigator is not defined
console.log(moment.version) // 2.18.1
```

**Comment by jgr3go** [comment]
I should note, this format (while not ISO standard) *should* be accepted, at least according to the docs under "The RFC 2822 date time format".   `momentjs` version 2.17.x gives an unrecognized format warning, however.

**Comment by icambron** [comment]
Yeah, this case should be handled. I haven't debugged it, but I think it's falling through to this: https://github.com/moment/moment/blob/7589bb8967aca2bda0192595e6e53a12c750aa69/src/lib/create/from-string.js#L154

**Comment by ichernev** [comment]
Hm, on a related note - we should have dedicated rfc2822 format method. Date.toString is not portable.

**Comment by TracyGJG** [comment]
@ichernev, do you mean that we could do this something like moment().toRFC2822String() for output or an input format, or both? Could we raise this as a separate issue?

**Comment by TracyGJG** [comment]
@ichernev, I have added a toRFC2822String() method to the PR.

**Comment by icambron** [comment]
Closing in favor of #3938
