### ISSUE TITLE
Parsing Date with lowercase year format d MMM yyyy

### ISSUE THREAD

**Issue by brendonco** [moment/moment#3921]
Is this an issue if the date format contain lowercase?

e.g. data in UTC, convert to GMT +8:00

```
value: 1979-03-29T16:00:00Z
```

```
moment(value).format("d MMM yyyy")
```

output:
29 Mar yyyy

Expected:

30 Mar 1979

**Comment by jgr3go** [comment]
Expected is `29 Mar yyyy`.  lowercase `y` is not a valid token. https://momentjs.com/docs/#/displaying/

**Comment by icambron** [comment]
@jgr3go is correct. Use "YYYY"

**Comment by brendonco** [comment]
Thanks @jgr3go  @icambron
