### ISSUE TITLE
formating the datetime with moment.format is returning an hour short  every time. 

### ISSUE THREAD

**Issue by rizwanh12** [moment/moment#3922]
formating the datetime with moment.format is returning an hour short  every time.  

var sd = moment(event.start).format('DD-MM-YYYY HH:mm');

Thu May 04 2017 07:00:00 GMT+0100 (GMT Daylight Time) returns "04-05-2017 06:00" 

//! moment.js
//! version : 2.13.0
any suggestion? 

thanks

**Comment by jgr3go** [comment]
What's the timezone of the environment your code is running in?  It will default to displaying it in that.

**Comment by icambron** [comment]
Yeah, please answer @jgr3go's question. `moment(...)` converts the time to local time.

**Comment by mj1856** [comment]
Given the lack of detail given, I'll just refer you to @maggiepint's excellent blog post on this subject and close the issue.

https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/

Also, 2.13.0 is a year old now.  Please update.  Thanks.
