### ISSUE TITLE
Moment._pf.meridiem undefined

### ISSUE THREAD

**Issue by iturn** [moment/moment#3923]
**Description of the Issue and Steps to Reproduce:**

parsing a ISO date and time string like '2014-04-20T07:30:00'
in code;  let starttime:moment.Moment = moment('2014-04-20T07:30:00');
returns a valid moment but the JSON is invalid because the starttime._pf.meridiem is undefined. This gives issues later in the application.
Setting the locale doest seem to change anything about meridiem. What is going on here?

**Environment:**
Chrome 57 on OSX

* Other libraries in use
"dependencies": {
    "@angular-mdl/core": "~4.0.*",
    "@angular/common": "~4.0.*",
    "@angular/compiler": "~4.0.*",
    "@angular/core": "~4.0.*",
    "@angular/forms": "~4.0.*",
    "@angular/http": "~4.0.*",
    "@angular/platform-browser": "~4.0.*",
    "@angular/platform-browser-dynamic": "~4.0.*",
    "@angular/router": "~4.0.*",
    "@types/lodash": "^4.14.41",
    "angular2-moment": "^1.0.1",
    "angularfire2": "^2.0.0-beta.8",
    "chart.js": "^2.4.0",
    "core-js": "^2.4.1",
    "firebase": "^3.7.5",
    "lodash": "^4.17.2",
    "material-design-icons": "^3.0.1",
    "material-design-lite": "^1.2.1",
    "moment": "^2.18.1",
    "promise-polyfill": "^6.0.2",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "ts-md5": "^1.2.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "~1.0.0",
    "@angular/compiler-cli": "~4.0.*",
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "codelyzer": "2.1.1",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "~4.5.0",
    "typescript": "~2.2.2",
    "webdriver-manager": "10.2.5"
  }
If you are reporting an issue, please run the following code in the environment you are using and include the output:
![1](https://cloud.githubusercontent.com/assets/12299090/25290439/5800fdda-26ce-11e7-8e1f-b2e30751091a.png)

**Comment by icambron** [comment]
I think it's a little strange that it's `undefined` and not `null` to be consistent with, for example, `invalidMonth`. That said, I don't actually understand why this is breaking your application. It sounds like you're serializing all this as JSON?

**Comment by iturn** [comment]
Yes you are right. After serializing into json there is no issue furtheron in the application. 

Just wanted to notify that this property isn't get set properly while parsing to a Momeny from and ISO string.

Br,

Stijn Post

**Comment by maggiepint** [comment]
This is an internal variable and it should never be serialized as Json, because it shouldn't be leaking out of any programs. If you need to pass the moment's value as json, use ``moment().toJSON()``.
