### ISSUE TITLE
Unreachable code warnings

### ISSUE THREAD

**Issue by PhilPJL** [moment/moment#3927]
**Description of the Issue and Steps to Reproduce:**

Using moment-with-locales.js, Visual Studio gives lots (18) of 'unreachable code detected' warnings.

Visual Studio 2017 + R# 

![image](https://cloud.githubusercontent.com/assets/271656/25376463/313cf9c6-299c-11e7-990a-43027ed8b29c.png)

**Comment by onionhammer** [comment]
Yeah this is annoying

**Comment by icambron** [comment]
If you can remove those breaks and make sure our linter passes, we'd accept a PR.

**Comment by PhilPJL** [comment]
I created a pull request for this but there are issues.  It's telling me I don't have an account and haven't signed the cla, which I have done. So...?

**Comment by maggiepint** [comment]
Close in favor of #3951

**Comment by marwahaha** [comment]
Since the PR has not merged, I will re-open.

**Comment by marwahaha** [comment]
I will close since we don't use resharper (I assume that's what's meant by R# ?) 

If it was something else, please re-open and we can have another look.
