### ISSUE TITLE
Moment.js should support HTML5 inputs like datetime-local

### ISSUE THREAD

**Issue by tkrotoff** [moment/moment#3928]
Moment.js should support out of the box [HTML5 inputs](https://www.w3.org/TR/html/sec-forms.html#sec-states-of-the-type-attribute) [datetime-local, date, time, week, month](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local).
Instead of writing:
```JSX
<input type="datetime-local" value={start.format('YYYY-MM-DDTHH:mm')} />
<input type="date" value={start.format('YYYY-MM-DD')} />
<input type="time" value={start.format('HH:mm:ss')} />
```
something like:
```JSX
<input type="datetime-local" value={start.toHtmlInput_datetime_local()} />
<input type="date" value={start.toHtmlInput_date()} />
<input type="time" value={start.toHtmlInput_time()} />
<input type="week" value={start.toHtmlInput_week()} />
<input type="month" value={start.toHtmlInput_month()} />
```

=> more explicit, less error-prone (ss vs SS, local vs UTC, yyyy vs YYYY...)

`datetime-local` expects "yyyy-MM-ddThh:mm" followed by optional ":ss" or ":ss.SSS" format
`date` expects "yyyy-MM-dd"
`time` expects "HH:mm", "HH:mm:ss" or "HH:mm:ss.SSS"
`week` expects "yyyy-Www"
`month` expects "yyyy-MM"
(taken from error messages given by Chrome 57. Yes Chrome speaks yyyy and dd instead of YYYY and DD, see #1603)

**Comment by icambron** [comment]
I think the way we've been thinking about these is to create constants of the form `moment.DATETIME_LOCAL = "YYYY-MM-DD"` and letting you just `moment().format(moment.DATETIME_LOCAL)`. That seems like a good way to help with this without adding a whole bunch of new functions.

**Comment by maggiepint** [comment]
I think we can up-for-grabs this one. Those kinds of constants are simple enough.

**Comment by tkrotoff** [comment]
I like the constants approach better than my original proposition.
Would love to see these constants added to Moment.

**Comment by nitte93** [comment]
Hi, I want to contribute in fixing this issue. This is going to be my first PR. I have forked and setup the project locally. It would be helpful if you guys provide some specific pointers for me to get started.

**Comment by cmdrwebdev** [comment]
Is this still open?

**Comment by icambron** [comment]
@cmdrwebdev yup!
