### ISSUE TITLE
Can you add support for English (India)?  Would like to use moment.js in my companies web applicaiton.  One of our major customers is located in India.  Currently you have support for Hindu (India) but English (India) is widely used and I believe the preference.  Thanks Jim

### ISSUE THREAD

**Issue by James1128** [moment/moment#3936]
**Description of the Issue and Steps to Reproduce:**

*Please include the values of all variables used.*

**Environment:**

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by marwahaha** [comment]
Hi @James1128 , I'm not sure of all the differences between US English and English in other countries, especially when it comes to dates. Do you know?

**Comment by James1128** [comment]
Hi Kunal,

Thanks for the response. A few of my colleagues are from India who are also software engineers. If I can get you the information you need would you be able to add locale support to moment.js for English (India)?

Thanks,
Jim

**Comment by marwahaha** [comment]
If you can follow these steps, we will take a PR for English (India).
https://github.com/moment/moment/pull/3796#issuecomment-282992200

**Comment by marwahaha** [comment]
If there is a need for this language that `moment.locale("en")` wouldn't satisfy, please re-open.
