### ISSUE TITLE
weekYear(Number) jumps to the previous day of the week (and wraps around)

### ISSUE THREAD

**Issue by xehpuk** [moment/moment#3944]
**Description of the Issue and Steps to Reproduce:**

For the German locale, `weekYear(Number)` does not preserve the day of the week, even if `Number === weekYear()`. It always jumps to the previous day and wraps around on Sunday. 

```js
import moment from 'moment'

moment.locale('de')

const date = moment('2016-01-01')

date.weekYear(2015) // 2015-12-31 Th
date.weekYear(2015) // 2015-12-30 We
date.weekYear(2015) // 2015-12-29 Tu
date.weekYear(2015) // 2015-12-28 Mo
date.weekYear(2015) // 2016-01-03 Su
date.weekYear(2015) // 2016-01-02 Sa
date.weekYear(2015) // 2016-01-01 Fr

// Workaround:
const day = date.day() // 5
date.weekYear(2015).day(day) // 2016-01-01 Fr
```
https://jsfiddle.net/mtvsr738/

**Environment:**

Chrome 57, Firefox 52 and Edge 38 on Windows 10

**Other information that may be helpful:**

```
Tue May 02 2017 21:08:56 GMT+0200 (Mitteleuropäische Sommerzeit)
2.5.2017, 21:08:56
-120
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
2.18.1
```

**Comment by icambron** [comment]
Looks like a bug to me. Would accept a patch.

**Comment by MTelling** [comment]
Seems to be not only 'de'. I can repro on 'da', 'ca' and 'fr' as well. Only seems to work in 'en'.

**Comment by MTelling** [comment]
Seems to be an issue in other locales as well. I can repro in 'ca' and 'da' as well locally.

**Comment by xehpuk** [comment]
[dayOfYearFromWeeks(year, week, weekday, dow, doy)](../blob/497f918515ae6ab900f008f19523b1e4ae5e2450/src/lib/units/week-calendar-utils.js#L19) seems to calculate a wrong `dayOfYear`.

`moment([2015, 11, 27]).locale('de').weekYear(2015)` leads to the call `dayOfYearFromWeeks(2015, 52, 6, 1, 4)` which then calculates `dayOfYear = 360`, while it should be `361`.

**Comment by Nosfistis** [comment]
I am having the same issue, it behaves as if `doy` is ignored. @nikofil are you preparing a PR?
