### ISSUE TITLE
IE11 moment js date formatting for mm/dd/yyyy gives a correct date for invalid input 55/55/2

### ISSUE THREAD

**Issue by kunchamwarp** [moment/moment#3949]
**Description of the Issue and Steps to Reproduce:**
moment('55/55/1', 'MM/DD/YYYY').format('MM/DD/YYYY') returns a valid date instead of NAN
*Please include the values of all variables used.*

**Environment:**

*Examples: Internet Explorer 11 on Windows 7, 

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by neroux** [comment]
What do you mean by valid date? What is the return value? It is not supposed to return `NaN`.

http://momentjs.com/docs/#/parsing/is-valid/

**Comment by maggiepint** [comment]
This shouldn't return NaN. What I get in IE is:

moment('55/55/1', 'MM/DD/YYYY').format('MM/DD/YYYY')
// "Invalid date"

In short, working exactly as designed.

**Comment by kunchamwarp** [comment]
Attached is the screenshot for the same. 
![ie11-date](https://cloud.githubusercontent.com/assets/11211219/26350439/c8f9fc42-3fd0-11e7-8ad5-72d73d4a3d3a.PNG)


See that the date returned is 10/15/0004 which is valid date. while if same thing is given in chrome or firefox it is NAN.

**Comment by kunchamwarp** [comment]
Duplicate of #3972

**Comment by neroux** [comment]
> Duplicate of #3972

Can hardly be a duplicate of an issue that was filed later ;)

I will later try to reproduce it also on IE11 and Firefox, but Chrome at least does not return `NaN` but simply an invalid date, as it supposed to.

**Comment by neroux** [comment]
http://jsbin.com/hiwefikidu/edit?html,js,console

**Comment by kunchamwarp** [comment]
The version of moment it use is 2.14.1 and we are using is 2.0.0

**Comment by neroux** [comment]
> The version of moment it use is 2.14.1 and we are using is 2.0.0

Well, that might easily explain it. I'd suggest to upgrade then.

**Comment by kunchamwarp** [comment]
@neroux thankyou will try to update the version and update thread.

**Comment by neroux** [comment]
Just tried it under Firefox, IE, and Edge and it works everywhere as supposed to.
