### ISSUE TITLE
Allow format to receive options compatible with Intl.DateTimeFormat

### ISSUE THREAD

**Issue by yanickrochon** [moment/moment#3950]
**Description of the Issue and Steps to Reproduce:**

On some hardware and browsers, [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) is not supported, and some component make use of this API and it would be useful if this module would work seamlessly, defaulting to the native implementation if one is present.

**Environment:**

Any browser, more specifically those not supporting `Intl.DateTimeFormat`.

**Usage**

```
const locale = "fr";
const options = { month: "short", weekday: "short", day: "2-digit" };
const df = moment.DateTimeFormat(locale, options);

df.format(new Date());
// "lun. 08 mai"
```

Something like this, using [Meterial UI](http://www.material-ui.com/#/components/date-picker)

```
<DatePicker
      hintText="fr locale"
      DateTimeFormat={ moment.DateTimeFormat }
      okLabel="OK"
      cancelLabel="Annuler"
      locale="fr"
    />
```

**Comment by newyankeecodeshop** [comment]
You might be better off just using the `Intl` polyfill from [https://github.com/andyearnshaw/Intl.js](https://github.com/andyearnshaw/Intl.js). It's recommended by the folks at https://formatjs.io too.

**Comment by yanickrochon** [comment]
Ah! Thanks! The entire script with all locales is just 600k. It's a fair price for something that is only optional. Thanks!
