### ISSUE TITLE
Weeksdaysmin does not take into account locale capitalization.

### ISSUE THREAD

**Issue by stephan-v** [moment/moment#3956]
**Description of the Issue and Steps to Reproduce:**

When executing:

```JS
moment.weekdaysMin(true)
```

The locale weekdays that are returned do not take into account locale settings when it comes to capitalization. For example in dutch the days that are returned are as following:

```JS
['Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za', 'Zo']
```

In Dutch however days are written without a capital letter. In german however they are written with a capital so I can not simply do something like `toUpperCase`.

I am uncertain if this is a bug or if I am suppose to use something else for this. If you need any more information please let me know.

**Comment by maggiepint** [comment]
I'm not sure what you're asking. In our locale files, both the Dutch and German locale files have capitalized weekdays. I think it's just a quirk of the languages that the strings happen to be the same - the locale files are different. If they are wrong for dutch, then please provide a normative reference like CLDR to show that the locale file is wrong and make a pull request.

If you just want to modify that property for personal purposes, you could use Update Locale:

```js
moment.updateLocale('nl', { weekdaysMin: 'zo_ma_di_wo_do_vr_za'.split('_'),});
moment.weekdaysMin(true);

// ["ma", "di", "wo", "do", "vr", "za", "zo"]
```

**Comment by stephan-v** [comment]
I will make a pull request to change the locale weekdaysMin to lowercase since that is how they should officially be written.
