### ISSUE TITLE
isSame comparison not timezone sensitive

### ISSUE THREAD

**Issue by absolutehype** [moment/moment#3957]
**Description of the Issue and Steps to Reproduce:**

I have two dates created with different timezone offsets, however both share the same date/time in their respective timezones. When I do an ```isSame``` comparison on ```day``` moment returns ```false```.

```js
let london = moment('2017-05-08T01:00:00+0100').tz('Europe/London'),
    singapore = moment('2017-05-08T01:00:00+0800').tz('Asia/Singapore');

london.isSame(singapore, 'day') // false
```

Both occurred on Monday, 8th May 2017.

Existing tests for ```isSame``` only diff up to a year so are missing this (https://github.com/moment/moment/blob/68a68b8730fbb69515ddbfb1d62bcfe34a484ae1/src/test/moment/is_same.js#L143)

Using ```valueOf``` in the comparison functions will lose the timezone awareness of the moments objects converting them back to UTC. (https://github.com/moment/moment/blob/497f918515ae6ab900f008f19523b1e4ae5e2450/src/lib/moment/compare.js#L38)

**Environment:**

Chrome 58 on Mac OS Sierra

**Comment by absolutehype** [comment]
I'm noticing similar behaviour with other comparators.

```js
let london = moment('2017-05-08T00:59:00+0100').tz('Europe/London'),
    singapore = moment('2017-05-08T01:00:00+0800').tz('Asia/Singapore');

london.isBefore(singapore)
```

I'm not sure how best to handle this, there are situations where you may not want a timezone sensitive comparison.

**Comment by maggiepint** [comment]
Yeah, basically this is how it works. At the end of the day, a moment object is always a reference to a point on the global timeline - and there would be no good way to change this. Moment is a wrapper for the JS date object, and this is how the JS date object IS. 

A possible work-around might be to parse the date time using `moment.utc('2017-05-08T00:59:00+0100', 'YYYY-MM-DDTHH:mm:ss')`. This ignores the offset and parses the local time as a UTC time. From here, the comparisons should be in local time by virtue of having ignored the offset. Not a great solution, but it will do the job.

I suppose one could make a pull request to like format the local time date parts and use those for comparison, but it would get pretty intense. The js-joda library does something like this.

Ultimately what we need is a date time only type that doesn't reference a point on the global timeline. A few of us have this underway at a language level (maggiepint/proposal-temporal), but until that proposal gets in ECMAScript (probably 1-2 years away), we're stuck with what we have.
