### ISSUE TITLE
"Ordinal" for year?

### ISSUE THREAD

**Issue by chochihim** [moment/moment#3958]
In Chinese, we use 日, 月 and 年 as ordinal for day, month and year respectively (actually they are more of units than ordinals in Chinese). For example, the date of this issue reported in Chinese format is 2017年5月12日

 I can format desired month and day by using ordinal formatting:
```
moment().format('Mo') === "5月";
moment().format('Do') === "12日";
```
How can I achieve the same for year?

I know I can get the full date format by using longDateFormat (like 'll') but sometimes I only want the year part.

Now I use updateLocale to override one of the longDateFormat to "YYYY年" for such formatting purpose. Can we have a better way to handle this?

Ways I can think of:
1. adding "Yo" for such formatting purpose
2. adding customised format like longDateFormat.

**Comment by marwahaha** [comment]
Thanks, this is a nice idea.

See https://momentjs.com/docs/#/-project-status/, Moment.js will not add any new tokens.
