### ISSUE TITLE
It is not possible to parse correctly formatted Spanish date in DD-MMM-YYYY format

### ISSUE THREAD

**Issue by xMort** [moment/moment#3959]
**Description of the Issue and Steps to Reproduce:**
It is not possible to parse correctly formatted Spanish date in DD-MMM-YYYY.
The issue was supposed to be fixed in [#1234](https://github.com/moment/moment/issues/1234) but it seems to work only for formatting values, not for parsing them. The problem is caused by the incorrect expectation of the dot character after the shortened month for MMM pattern.

When parsing is involved the condition on line 21 in [es.js](https://github.com/moment/moment/blob/develop/locale/es.js) that checks for "-MMM-" occurrence is not triggered because "format" parameter is not forwarded in this case.

You can see the issue in this test case:
[https://jsfiddle.net/0yxe7oev/](https://jsfiddle.net/0yxe7oev/)

**Environment:**
Chrome 58, Windows 10
Latest moment.js

**Other information that may be helpful:**
Fri May 12 2017 15:40:05 GMT+0200 (Central Europe Daylight Time)
VM27369:2 5/12/2017, 3:40:05 PM
VM27369:3 -120
VM27369:4 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

**Comment by icambron** [comment]
That makes sense.

>  checks for "-MMM-" occurrence is not triggered because "format" parameter is not forwarded in this case.

Perhaps that's the problem in itself. I don't remember the details of how this works, but maybe we just need to fix that?

**Comment by marwahaha** [comment]
I believe this is fixed, as of 2.19.0, and definitely in 2.20.1 . There's even a test case for it.

https://github.com/moment/moment/blob/develop/src/test/locale/es.js#L214-L217
