### ISSUE TITLE
Bug in moment parse date

### ISSUE THREAD

**Issue by marlonmleite** [moment/moment#3966]
When reviewing a date and a format, the parse date not validate the input format.

```js
//Wrong isValid
moment('16/031/19921122222', 'DD/MM/YYYY').isValid() //true

//Correct isValid
moment('16/031/19921122222', 'DD/MM/YYYY').isValid() //false
```

The parse is right?

What function validate for an entry date for the format?

**Comment by icambron** [comment]
The parser without the strict flag is pretty liberal. Just do this:

moment('16/031/19921122222', 'DD/MM/YYYY', true).isValid() //=> false
