### ISSUE TITLE
Invalid Date in IE 11

### ISSUE THREAD

**Issue by thegrumpysnail** [moment/moment#3968]
**Description of the Issue and Steps to Reproduce:**
Basically, calling `Moment()` in Internet Explorer 11 gives an 'Invalid Date'. If I pass `new Date()` to `Moment(new Date())`, it behaves as expected. My guess is that the constructor passes in `NaN` to `new Date(NaN)`, like so, and this is giving this unexpected behavior.

*Please include the values of all variables used.*
```JS
var now = Moment();
console.log(now);
// Should dump out 'Invalid Date'

var now = Moment(new Date());
console.log(now);
// Should dump out whatever the local time is
```

**Environment:**
Internet Explorer 11 on Windows 10.

It is worth mentioning that I am using moment.js from a CDN through require.js and do not have any localization libraries loaded.

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log((new Date()).toLocaleString()) // Actually returns 'Invalid Date'
console.log((new Date()).getTimezoneOffset()) // 240
console.log(moment.version) // 2.18.1
```

**Comment by mj1856** [comment]
That's not how to construct a moment object.  You should be doing something like:

```js
var now = moment();  // lower-case
 
var now = moment(new Date());  // this works too, but is redundant.
```

**Comment by thegrumpysnail** [comment]
My apologies, I should have mentioned that I am using requirejs, and I happened to call it `Moment` instead of `moment`. Regardless, that still doesn't change the fact that the behavior of `moment()` is giving me different behavior than `moment(new Date())`. I resorted to using the "redundant" version of it since that's the one that works.

**Comment by mj1856** [comment]
If you can reproduce it in a jsfiddle or similar, please do.  Everything is working fine for me.

Reading your original question again, you said you expected `moment()` to return an invalid date, but it should not.  It should return the current local time, identical to `moment(new Date())`.

**Comment by thegrumpysnail** [comment]
Yeah, sorry, what I meant was, under normal circumstances, I expect it to give me valid output (which it does in Chrome, Edge and Firefox), but it did not do it in Internet Explorer 11. However, I was working on putting together a small snippet to reproduce the error, and I could not reproduce it, so I think we're in the clear here. I am guessing it was a problem with some other library (possibly a weird interaction with some really old HaXe output that I am in the process of replacing). Anyway, thanks for getting back to me! If I can reproduce it with JUST moment.js, I'll open a new thread with better details, and reference this one.

**Comment by smileheart2** [comment]
Yesterday I met new Date("2018-03-29 17:25:2") under IE11 for Invalid Date. Firefox and Google Chrome are normal. I don't know if it is the same as your problem. The solution is to replace "-" with "-". Changed to "/" to become new Date("2018/03/29 17:25:2"). I have poor English and I don't know if you can read it. Sorry.

**Comment by jraack** [comment]
@smileheart2 Fixed it for me as well, IE11.

**Comment by tinyweasel** [comment]
> replace "-" with "-". What's the difference?

**Comment by fengye1988qiu** [comment]
> > replace "-" with "-".
> 
> What's the difference?

I think he want to say, replace '-' with '/'

**Comment by tinyweasel** [comment]
Oh yeah. Maybe they'll edit that.

**Comment by anisbi** [comment]
For me (and I'm guessing also for OP) the issue was with the native Date API, as it wasn't able to parse the date from my String which had _DD-MMM-YYYY_ format.
consider:
`var dateStr = "23-Apr-1990";
var date = new Date(dateStr); //Invalid in IE but works in Chrome`
And basically this was the root of the issue.
Workaround for me was to replace "-" with " ", st:
`var dateStr = "23-Apr-1990".replace(/-/g,' ');
var date = new Date(dateStr); //Works properly in all browsers I checked`
