### ISSUE TITLE
Add new function to get Semi-annual or Half-year number

### ISSUE THREAD

**Issue by mxgit1090** [moment/moment#3970]
**Description of the Issue and Steps to Reproduce:**
For some business using there is the demand for the semi-annual time period, we can add a new 
function like following:
```js
moment().semiAnnual(); // 1
moment().halfYear(); // 1
```

**Environment:**
Chrome 58, Node.JS >=7.9.0 on macOS Sierra 10.12.4 / Windows 10

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
UTC+08:00 (Asia/Taipei)
* The time and date at which the code was run
moment("2017-05-23T12:32:22.679")

**Comment by marwahaha** [comment]
What about quarter?

```
moment().quarter() // 2
```

**Comment by mxgit1090** [comment]
@marwahaha 

Oh! I just add 2 quarters and divide it by 2, it is semi-annual!

Thank you.

**Comment by marwahaha** [comment]
Great, sounds like this works for you.

**Comment by chemseddine201** [comment]
> @marwahaha
> 
> Oh! I just add 2 quarters and divide it by 2, it is semi-annual!
> 
> Thank you.

please show an example for this case?
