### ISSUE TITLE
Time format for de-ch is weird

### ISSUE THREAD

**Issue by AyrA** [moment/moment#3973]
The Time format for de-ch was taken from a document that describes how the government writes official documents. This document does not necessarily describes how date and time is formatted outside of this.

People in Switzerland primarily use `HH:mm` format and not `HH.mm` format. This is also what computers (linux+windows) use by default when set to that locale. In Windows the dot is not even one of the supported choices in the language settings for Switzerland.

I recommend changing the time formats to `HH:mm` and `HH:mm:ss`.

Various documents from the government I have (for example tax forms) use a colon instead of a point in their time format. Documents generated by the governments online system also use this way of writing time instead.

People using computers expect `HH:mm` and not `HH.mm`.

**Comment by neroux** [comment]
There are several issues with that locale (and its sub-locales AT and CH) at the moment (pun unintentional :) ), some of them are semi-fixed in #3803

**Comment by mj1856** [comment]
@sschueller - your opinion please?

**Comment by sschueller** [comment]
We operate many websites for Swiss municipalities and tend to go with what is available in official documents. However I am only an engineer so I will ask internally and post another comment in the next few days. Thanks

**Comment by sschueller** [comment]
I have discussed this internally and we have no objection to the change.

**Comment by wittwerch** [comment]
As a swiss I would consider that also a bug. It's common to use ```HH:mm``` for times, never saw the notation with a dot somewhere.

**Comment by AyrA** [comment]
@wittwerch Even the government is not sure how to do it. The DMV is a good example:

- [DMV LU](https://strassenverkehrsamt.lu.ch/wir_ueber_uns/kontakt_oeffnungszeiten) uses `.`
- [DMV ZH](https://stva.zh.ch/internet/sicherheitsdirektion/stva/de/ueber_uns/organisation/StVA_Gt.html) uses `:`

**Comment by fbonzon** [comment]
This was fixed in #4200. This issue can be closed.
