### ISSUE TITLE
moment().diff() sometimes returning -0

### ISSUE THREAD

**Issue by sasikumar25** [moment/moment#3974]
When using moment().diff(moment(new Date()),'days') sometimes it's returning "-0"

**Comment by neroux** [comment]
Is that particular about `moment(new Date())` (which should be identical to `moment()`) and/or `'days'`?

Also, post the other information that was asked for when you opened the issue.

**Comment by sasikumar25** [comment]
No, It's not related to new Date() even if you pass a ISO string to moment i'm getting the same.

Please find the below information

console.log( (new Date()).toString()) - > Tue May 23 2017 19:06:16 GMT+0530 (India Standard Time)
console.log((new Date()).toLocaleString()) -> 5/23/2017, 7:06:16 PM
console.log( (new Date()).getTimezoneOffset()) -> -330
console.log( navigator.userAgent) -> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36
console.log(moment.version) -> 2.10.6

**Comment by neroux** [comment]
First, I'd recommend to upgrade to the latest version.

Second, I'd try to find out which the exact timestamps are making `diff()` return a negative zero. When you run your code log them with `valueOf()` and when you have two that reproduce the value post them here.

Third, in case of negative zero you could use `Math.abs()` as workaround.

**Comment by neroux** [comment]
#2503 might be related.

**Comment by maggiepint** [comment]
I am pretty sure I fixed this a year ago. What version are you using?

**Comment by maggiepint** [comment]
I just noticed - 2.10.6 - sorry. I would upgrade and I believe this will be fixed.
