### ISSUE TITLE
calendar sameElse garbled output

### ISSUE THREAD

**Issue by scrambled2k3** [moment/moment#3975]
**Description of the Issue and Steps to Reproduce:**
I would like to use .calendar with .fromNow being returned in the 'sameElse'.  I keep getting some garbled results.

```
moment("2017-05-16T18:00:00")
    .endOf('day')
    .calendar(null, {
        sameDay: '[Today]',
        nextDay: '[Tomorrow]',
        nextWeek: 'dddd',
        lastDay: '[Yesterday]',
        lastWeek: '[Last] dddd',
        sameElse: function(now) {return this.fromNow();}
     })
```

Everything works fine except for the 'sameElse' section.  The output is gibberish.  If I console.log(this) from within sameElse, I do get a valid moment date object that correctly represents the date being passed to it.

Example: the above 'sameElse' will output '6 2pmy59 pmgo'.
For reference: todays date is 2017-05-23

**Environment:**
Chrome 57 and Microsoft Edge on Windows 10

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```
console.log( (new Date()).toString()) = Tue May 23 2017 08:50:22 GMT-0400 (Eastern Daylight Time)
console.log((new Date()).toLocaleString()) = 5/23/2017, 8:50:22 AM
console.log( (new Date()).getTimezoneOffset()) = 240
console.log( navigator.userAgent) = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
console.log(moment.version) = 2.18.1
```

**Comment by neroux** [comment]
The problem is you are returning an already formatt**ed** string, when the callback actually needs to return a formatt**ing** string. If you escape the return value of `fromNow()` it should work.

    sameElse: function(now) {return '['+this.fromNow()+']';}

**Comment by scrambled2k3** [comment]
Ahhhh, makes sense.  Thanks for your help, that worked like a charm!
