### ISSUE TITLE
Chinese datetime string broken in 2.18.1 after working in 2.10.6

### ISSUE THREAD

**Issue by gareim** [moment/moment#3987]
**Description of the Issue and Steps to Reproduce:**
"2015年8月3日星期一晚上6点06分" is the string in question

%H should return 18, but returns 6.
Returns 18 on 2.10.6
Return 6 on 2.18.1

*Please include the values of all variables used.*
```format = ["YYYY", "LT", "LTS", "L", "l", "LL", "ll", "LLL", "lll", "LLLL", "llll", "D MMM YYYY", "H:mm", "ddd, YYYY MMM D [] HH:mm:ss Z", "ddd, YYYY MMM D [] HH:ss Z", "ddd MMM D, YYYY h:mma", "ddd MMM D, YYYY ha", "MMM D, YYYY h:mma", "MMM D, YYYY ha", "MMM D [于] HH:mm", "MMM D [于] HH", "dddd, MMMM D", "ddd YYYY MMM D", "ddd, MMM D", "YYYY MMMM D HH:mm", "YYYY MMMM D HH", "YYYY MMMM D", "YYYY MMM D", "MMM D HH:mm", "MMM D HH", "MMM D", "YYYY-M-D", "HH:mm", "HH", "H", "dddd", "ddd"]```

`a = moment.apply(null, ["2015年8月3日星期一晚上6点06分", format, "zh-cn"])`

**Environment:**
Chrome 58 on MacOS Sierra

This behavior is seen in app, and in a barebones html file that just pulls in the momentjs library.

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```
Tue May 30 2017 12:48:49 GMT-0500 (CDT)
5/30/2017, 12:49:15 PM
300
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
2.18.1
```

**Comment by marwahaha** [comment]
@gareim - I think this parses fine. You need to specify the character for post or ante meridiem, `A`.
([More info here.](http://momentjs.com/docs/#/parsing/string-format/))

Try this:
```
x = moment("2015年8月3日星期一晚上6点06分", "YYYY-MM-DD-AHH:mm", "zh-cn")
x.format() // "2015-08-03T18:06:00-07:00"
x.format("%H") // %18
```

Let me know if this works, and we can close the issue.

**Comment by marwahaha** [comment]
Closing due to age. Let us know if you have more questions.
