### ISSUE TITLE
Uncaught TypeError: key.toLowerCase is not a function

### ISSUE THREAD

**Issue by Kyslik** [moment/moment#3990]
**Description of the Issue and Steps to Reproduce:**

Error caused by:

```
function normalizeLocale(key) {
    return key ? key.toLowerCase().replace('_', '-') : key;
}
```

trying to do following:
```
moment.updateLocale('en', {
    week : {
        dow : 1
    }
```

No issues using `moment.locale` or `moment.lang`.

**Environment:**
OS X, Chrome latest

```js
Wed May 31 2017 17:07:51 GMT+0200 (CEST)
VM410:2 5/31/2017, 5:07:51 PM
VM410:3 -120
VM410:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
VM410:5 2.18.1
```

<strike>*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*</strike> (not sure)

**Comment by icambron** [comment]
Seems to work OK for me: https://jsfiddle.net/4j9p6uvu/. Can you make a fiddle that reproduces this?

**Comment by icambron** [comment]
Closing for age.

**Comment by tremby** [comment]
I just came across this. I was trying to do `moment(year, month, day, hour, min, sec, ms)` when I should have been doing `moment([year, month, day, hour, min, sec, ms])`.

**Comment by mariohmol** [comment]
I havi this following this 

https://material.angular.io/components/datepicker/overview#watching-the-views-for-changes-on-selected-years-and-months

or this

https://stackblitz.com/angular/rekdadngmrl?file=app%2Fdatepicker-views-selection-example.ts

the `key ` is coming as an object

**Comment by flycal6** [comment]
I had this issue in version 11 and solved it by adding MAT_DATE_LOCALE to the providers array:
```
{ provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: { useUtc: true } },
{ provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE, MAT_MOMENT_DATE_ADAPTER_OPTIONS]},
{ provide: MAT_DATE_LOCALE, useValue: 'en-US' }`
