### ISSUE TITLE
moment.subtract giving false results

### ISSUE THREAD

**Issue by AnixPasBesoin** [moment/moment#3993]
I witnessed this weird behavior:

This code: `moment(new Date()).subtract(1, 'months')` is actually subtracting 'days' instead of 'months'.
While this one: `moment(new Date()).subtract(1, 'days')` is doing the opposite, it is subtracting months.

Please try to reproduce it and fix it ASAP. It's a critical  bug.

**Comment by maggiepint** [comment]
Looks completely fine to me:
```
moment(new Date()).subtract(1, 'months').format()
"2017-05-05T18:25:52-07:00"
```

```
moment(new Date()).subtract(1, 'days').format()
"2017-06-04T18:26:07-07:00"
```
