### ISSUE TITLE
Get a weekend

### ISSUE THREAD

**Issue by LusenkoSasha** [moment/moment#3995]
Hello. I need to get a weekend from the current date to the month. It is to get the dates of the weekend in the array. This can be done?

**Comment by maggiepint** [comment]
We don't really support the concept of 'weekend' as it varies between cultures. Beyond that, I'm not really sure what you are asking. You are wondering how to get all of the saturdays and sundays in a month?

**Comment by LusenkoSasha** [comment]
Yes, I need to receive the dates of all Saturdays and Sundays within a month from the start date.

**Comment by LusenkoSasha** [comment]
@maggiepint Yes, I need to receive the dates of all Saturdays and Sundays within a month from the start date.

**Comment by icambron** [comment]
@LusenkoSasha yes, you just need to do a little programming. You can start with a moment, set it to the beginning of the month, find that saturday, then in a loop add a week until you're not in the month anymore, adding to the array as you go.
