### ISSUE TITLE
Possibility to handle tertiles (4-month-periods)

### ISSUE THREAD

**Issue by marwej** [moment/moment#3999]
I have the need to handle tertiles (a third of a year) and it would be very handy to be able to e.g. add and subtract such a period like `moment().add(1, 'tertiles')` without special handling of that case.

But I suppose that such a feature would implicate other changes as well...

**Comment by icambron** [comment]
We'll pass on implementing in Moment. Here's our rationale in rejecting semesters: #1998. I think this is at least as niche. If I were you, I'd add a `tertile` function that returned a three-month duration. Then you could add and subtract it as you please. If you really want to make it smooth, you could monkey patch `add` and similar with a shim that does the tertile -> three month conversion. I don't recommend it though.
