### ISSUE TITLE
Formatting the return object of parseZone doesn't handle z correctly

### ISSUE THREAD

**Issue by hengfengli** [moment/moment#4005]
I used `parseZone` to parse a DateTime string into moment object. However, the timezone is incorrect in the formatting result. 

```javascript
console.log(moment.parseZone('2017-06-06T19:35:42-0700').format('l LT z'))
=> 6/6/2017 7:35 PM UTC
console.log(moment.parseZone('2017-06-06T19:35:42-0700').format('l LT Z'))
=> 6/6/2017 7:35 PM -07:00
console.log(moment.parseZone('2017-06-06T19:35:42-0700').tz('America/Los_Angeles').format('l LT z'))
=> 6/6/2017 7:35 PM PDT
console.log(moment.parseZone('2017-06-06T19:35:42-0700').tz('America/Los_Angeles').format('l LT Z'))
=> 6/6/2017 7:35 PM -07:00
```

The timezone of the first statement should be also `PDT` instead of `UTC`. Please check the following jsfiddle link: 

[https://jsfiddle.net/hengfengli/rgr27mh7/5/](https://jsfiddle.net/hengfengli/rgr27mh7/5/)

**Comment by icambron** [comment]
There's no way that can say "PDT". How does it know that the UTC-7 offset you provided is actually PDT? Maybe it's in the equivalent in Mexico or Canada, or even Arizona in all-year-round Mountain Standard Time. The string -0700 doesn't say. `parseZone` is a bad name; it really means `parseOffset`

I *am* sympathetic to the view that it needs to say something better than "UTC". @mj1856 would you say here? "UTC-7" is what comes to mind for me.

**Comment by mj1856** [comment]
Correct, it can't say `UTC`.  The best it could say is `UTC-7`.  For partial hour offsets it would be like `UTC+5:30`.

Do note that the docs make it clear that `z` should be considered deprecated for plain moment objects.  It's only useful in conjunction with moment-timezone.

**Comment by marwahaha** [comment]
In https://momentjs.com/docs/#/displaying/format/

> Note: as of 1.6.0, the z/zz format tokens have been deprecated from plain moment objects. Read more about it here. However, they *do* work if you are using a specific time zone with the moment-timezone addon. 

They are deprecated, unless you use them in your 2nd style (e.g. parseZone -> tz -> format ). 
So I will not update these deprecated identifiers.

See also https://momentjs.com/docs/#/-project-status/
