### ISSUE TITLE
Turkish calendar() works differently than others

### ISSUE THREAD

**Issue by 3LOK** [moment/moment#4006]
**Description of the Issue and Steps to Reproduce:**
The following fails:
```javascript
const a = moment.utc(1497172800000).add(3, 'days');
expect(a.calendar(1497172800000)).to.equal('Çarşamba saat 09:20'); 
```
So the problem is in the ```calendar()``` function in Turkish:
What should it show: 

> Çarşamba saat 09:20

What does it show: 

> haftaya Çarşamba saat 09:20 (which means "Wednesday next week at 09:20")

What does it show in other locales (eg. English): 

> Wednesday at 09:20

The reason is that in [TR locale the calendar object](https://github.com/moment/moment/blob/develop/locale/tr.js#L52) includes "Next" (haftaya) unlike other locales which do not contain it (eg. [English locale](https://github.com/moment/moment/blob/develop/locale/en-gb.js#L30)). 

**Environment:**
Happens on all environments (including node, chrome, firefox, etc...), since it's just a mistake in Turkish calendar() object definition.

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
Sun Jun 11 2017 12:29:40 GMT+0300 (IDT)
console.log((new Date()).toLocaleString())
6/11/2017, 12:29:40 PM
console.log( (new Date()).getTimezoneOffset())
-180
console.log(moment.version)
2.18.1
```

**Comment by icambron** [comment]
@erhangundogan, @BYK what do you guys think?

**Comment by BYK** [comment]
@icambron looks legit. If you're in the same week, you just mention the weekday. You only mention the "next" part if it is the following week. Alternative to `haftaya` is `onumuzdeki` which is more informal.

**Comment by erhangundogan** [comment]
@icambron seems legit 👍  as @BYK mentioned `önümüzdeki çarşamba` would be a simple replacement..

**Comment by icambron** [comment]
Cool, would accept a PR

**Comment by marwahaha** [comment]
This was fixed awhile back.
