### ISSUE TITLE
ios format() bug

### ISSUE THREAD

**Issue by Symous** [moment/moment#4011]
Hi,I use this lib in an angular/cordova app, and I found a bug that if I have 2 time string:
var time1 =  '2017-6-13 8:01:01';
var time2 =  '2017-06-13 08:01:01';

if I use moment(time1).format('HH:mm') it will return invalid date in iOS. and moment(time2).format('HH:mm') works well.

Both time1 and time2 format as expected with Android & Web. :-)

**Comment by icambron** [comment]
Correct. You're aren't providing a parsing string, so Moment is just handing it off to the native date constructor, which varies by platform. We actually deprecated that fallback because of issues like that:

```js
moment('2017-6-13 8:01:01')
global.js:293 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
[snip]
```

Use ISO 8601 or provide a second arg specifying the format.
