### ISSUE TITLE
Missing locale 'en-IN'?

### ISSUE THREAD

**Issue by debo-personal** [moment/moment#4012]
I installed moment@2.18.1 and was looking through the locales available. I assumed there was an en-in locale. Upon further inspection, I only saw these en locales:

en-au
en-ca
en-gb
en-ie
en-nz

Am I missing something? Just for an example for 'en-IN', 'l' date-format should give 'dd/MM/yyyy' but it's giving 'MM/dd/yyyy', may be the default one. If there was a file for 'en-in', it would have been there in longDateFormat. Please suggest.

I'am using it like this - 
var formattedDate = moment(dateInput).locale(locale).tz(timezone).format(momentFormat);
e.g. var formattedDate = moment( 1497260107000 ).locale( "en-IN" ).tz( "Asia/Calcutta" ).format( "l LT" );

Above expression gives me result in mm/dd/yyyy h:mm AM/PM format where I was expecting in dd/mm/yyyy h:mm AM/PM where it's giving correct result for 'en-gb' or 'en-au' because corresponding locale files are available.

**Comment by icambron** [comment]
Nope, there's no en-in right now, so en-in will fall back to en, which is actually en-us. If you want en-in, you'll need to implement it.

**Comment by shadowhand** [comment]
Strange that this would be closed. `en-IN` is really just an alias to `en-GB`. Should be fairly trivial to implement, no?

**Comment by icambron** [comment]
We don't generally leave "I want this language" tickets open, since we're willing to take just about any language definition as pull request whether an issue exists or not. The only thing missing here is someone implementing it and posting it as a PR.
