### ISSUE TITLE
Using moment-with locales, has no locales

### ISSUE THREAD

**Issue by resistorsoftware** [moment/moment#4013]
**Description of the Issue and Steps to Reproduce:**

command to use another locale like moment.locale('it') always returns "en". moment.locales() command returns {'en"]. File being used is moment-with-locales.js

*Please include the values of all variables used.*

**Environment:**
moment.version "2.13.0"
Chrome 58 on OSX

In the Chrome Dev console... I get this... 

moment.locales()
["en"]
moment.locales()
["en"]
moment.locale('it')
"en"
moment.locales()
["en"]

So how does one utilize moment with locales to use the locales?

**Comment by icambron** [comment]
Looks fine to me, even pulling that specific version: https://jsfiddle.net/0u6ft652/1. Can you create fiddle demonstrating the issue?

**Comment by resistorsoftware** [comment]
Sorry for the noise. I discovered that in the load chain, a poorly written plugin had copy and pasted an old version of moment, 2.13 with no locales into the browser, presumably AFTER the script load from me, hence it overwrote the moment function with a non-localized old version. Trying to wrap my head around how to code around that now
