### ISSUE TITLE
moment().isSame not working

### ISSUE THREAD

**Issue by Symous** [moment/moment#4016]
When I try to check whether the current date is same as a given one , I use:
```js
var givenDate = '2017-06-15';
var result = moment().isSame(givenDate);
```
it always return false , so I must write like this:
```js
var result = moment(moment().format('YYYY-MM-DD')).isSame(givenDate);
```
so it seems like that moment() directly is not supported with isSame method.
 
But isBetween method works well with this format.
```js
var result = moment().isBetween(givenDate,'2017-06-18',null,'[]');
```

**Comment by Symous** [comment]
Sorry,Just have found that I need to add 'day' param to make it work.
```js
var result = moment().isSame(givenDate,'day');      //return true;
```

**Comment by mayurithakur** [comment]
refer to the note in moment.js docs https://momentjs.com/docs/#/query/is-same/
It says: 
NOTE: moment().isSame() has undefined behavior and should not be used! If the code runs fast the initial created moment would be the same as the one created in isSame to perform the check, so the result would be true. But if the code runs slower it's possible that the moment created in isSame is measurably after the one created in moment(), so the call would return false.
Above note is applicable to moment().isBefore() as well.

**Comment by Ahsanzafar-786** [comment]
i use isAfter and isSame but they not work properly. They give false result all the time
 var systemTime = moment().add(1, 'hour').format('YYYY-MM-DD');
  var startTime = moment(this.purchase.startTime).add(1, 'hour').format('YYYY-MM-DD')
                    var years = moment(systemTime).isSame(startTime, 'year');
                    if (years == false) {

**Comment by fabioselau077** [comment]
> i use isAfter and isSame but they not work properly. They give false result all the time var systemTime = moment().add(1, 'hour').format('YYYY-MM-DD'); var startTime = moment(this.purchase.startTime).add(1, 'hour').format('YYYY-MM-DD') var years = moment(systemTime).isSame(startTime, 'year'); if (years == false) {

same here...
