### ISSUE TITLE
Month documentation out of date

### ISSUE THREAD

**Issue by ir-fuel** [moment/moment#4020]
http://momentjs.com/docs/#/get-set/month/

> Before version 2.1.0, if a moment changed months and the new month did not have enough days to keep the current day of month, it would overflow to the next month.

> As of version 2.1.0, this was changed to be clamped to the end of the target month.

vs

http://momentjs.com/docs/#/get-set/date/

> Note: if you chain multiple actions to construct a date, you should start from a year, then a month, then a day etc. Otherwise you may get unexpected results, like when day=31 and current month has only 30 days (the same applies to native JavaScript Date manipulation), the returned date will be 1st of the following month.

**Comment by marwahaha** [comment]
@ir-fuel - do you have a proposed change ?
