### ISSUE TITLE
Method parseTwoDigitYear missing from typescript definitions

### ISSUE THREAD

**Issue by chrisleck** [moment/moment#4023]
**Description of the Issue and Steps to Reproduce:**
parseTwoDigitYear is not present in the published `moment.d.ts` definition.

*Please include the values of all variables used.*
N/A

**Environment:**
moment version 2.17.1

**Comment by marwahaha** [comment]
You're welcome to add it, or you can wait for my (slightly larger) TS changeset later this week :)

**Comment by ashley-s** [comment]
Hello,

Has it been added? I am currently using the version 2.18.1. Will a new version be released soon?

Thanks,
Ashley

**Comment by admmasters** [comment]
This hasn't been added - is it worth me opening a PR for this?

**Comment by marwahaha** [comment]
Go for it.

**Comment by Elrhino** [comment]
@marwahaha I'm looking forward to this. Will it be added to the next release?

**Comment by eddiemonge** [comment]
With this change, how do you overwrite the function (as recommended everywhere to add a new cutoff year ?!?!?) without TypeScript complaining about doing that?
