### ISSUE TITLE
Modifying leap year to non-leap year changes Feb-29 to Mar-1

### ISSUE THREAD

**Issue by haxxxton** [moment/moment#4024]
**Description of the Issue and Steps to Reproduce:**
Unlike `.month()` since 2.1.0 which maintains the month, and selects the last day, using `.year()` to change from a leap year's Feb-29th to a non-leap year, results in a Mar-1st instead of the expected Feb-28th.

```js
// changing to a non-leap year
// UNEXPECTED RESULT
moment('2012-02-29').year(2017).format('LLLL') // => "Wednesday, March 1, 2017 12:00 AM"
// expected "Tuesday, February 28, 2017 12:00 AM"

// changing to the following February using `.month`
// EXPECTED RESULT
moment('2012-02-29').month(13).format('LLLL') // => "Thursday, February 28, 2013 12:00 AM"

// changing month on from a month with more days than the shifted to month
// EXPECTED RESULT
moment('2012-07-31').month(5).format('LLLL') // => "Saturday, June 30, 2012 12:00 AM"
```

**Environment:**

Chrome  58.0.3029
OSX 10.12.5

```
// console output
Tue Jun 20 2017 17:02:07 GMT+1000 (AEST)
2017-6-20 17:02:07
-600
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
2.18.1
```

**Comment by icambron** [comment]
Would accept a PR

**Comment by martinzc** [comment]
Hi, I am very new to open source contribution. May I get assigned to this issue?

**Comment by icambron** [comment]
@martinzc There are no assignments; everyone is free to contribute any time they wish. So by all means, give it a try. When you create a pull request, please link to this issue so that other people coming to this issue will find it.

**Comment by 91aman** [comment]
Hi, @icambron I looked into moment source code for this issue, And I have found the function which is causing this ambiguity. Internally we use, Javascript Date instance's setMonth/setYear functions. The default behaviour of these function is different from that of the moment function.

```
moment('2012-02-29').month(13).format('LLLL')
"Thursday, February 28, 2013 12:00 AM"
```
```
new Date(new Date('2012-02-29').setMonth(13))
Fri Mar 01 2013 05:30:00 GMT+0530 (IST)
```

Before solving this issue, I just wanted to know the reason for keeping a different behaviour than the native for the same functionality.

**Comment by haxxxton** [comment]
@91aman, IMO the moment implementation makes more sense to me. I would much prefer to have changing months not potentially creep into a month i hadnt expected. For example with a regular `.month` implementation:

```js
moment('2012-07-31').month(5).format('LLLL')
// "Saturday, June 30, 2012 12:00 AM"
```

```js
new Date(new Date('2012-07-31').setMonth(5));
// Sun Jul 01 2012 10:00:00 GMT+1000 (AEST)
```

I think this definitely makes the most sense. Since 31st June is not valid, personally i would prefer it to auto-select 30th June, than 1st July. Which i think has reached consensus previously, which is the reason why ([docs](http://momentjs.com/docs/#/get-set/month/)) 

> Before version 2.1.0, if a moment changed months and the new month did not have enough days to keep the current day of month, it would overflow to the next month.
>
>As of version 2.1.0, this was changed to be clamped to the end of the target month.

**Comment by icambron** [comment]
Agreeing with @haxxxton. The current behavior of `month` is correct; we just need `year` to use the same logic

**Comment by andy-shi88** [comment]
is this still up for grab?

**Comment by lightbringer1991** [comment]
@icambron I have submitted a PR to fix this
Could you please CR and merge if possible, thank you

**Comment by gatitoneku** [comment]
@icambron tried to give a shot at this (#4176)
would be glad if you take a look

**Comment by abdatta** [comment]
Hi, I'm new to open source contributions. I'm eager to contribute to momentjs as I've used it many times in my node applications. So, should start with a PR for this? I see some people have already submitted one. If not, it would be nice if someone can suggest me some issues that I can look forward to submitting a PR for.
