### ISSUE TITLE
moment.duration().format is not a function

### ISSUE THREAD

**Issue by Zorig** [moment/moment#4026]
**Description of the Issue and Steps to Reproduce:**
moment.duration(123, "seconds").format() it gives me an error `moment.duration().format is not a function`
*Please include the values of all variables used.*
`123`, `192.343`
**Environment:**

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*
Chrome 59 on OSX NodeJS 6.10
*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by icambron** [comment]
That function does not exist, so calling it results in an error.

Many people want that function to exist, and for the most comprehensive overview of that, see #1048.
