### ISSUE TITLE
Feature: Interest in supporting a Rails like distance_of_time_in_words?

### ISSUE THREAD

**Issue by AJamesPhillips** [moment/moment#4028]
Adapted from: https://gist.github.com/sulf/1157909/62a16f4c8204022b8f6d40716b81eef39ded6850
Would be good to translate the [full featured rails version](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/date_helper.rb) as I'm sure this version also has mistakes in it that I have not corrected.

    export function time_ago_in_words (from_date: Date, include_seconds: boolean = false) {
        return distance_of_time_in_words(from_date, new Date(), {include_seconds, include_tense: true});
    }

    interface Options {
        include_seconds: boolean;
        include_tense: boolean;
    }

    const default_options = {
        include_seconds: true,
        include_tense: true,
    };

    export function distance_of_time_in_words (from_date: Date, to_date: Date, options: Partial<Options> = {}) {

        const full_options: Options = Object.assign({}, default_options, options);

        const from_time = from_date.getTime();
        const to_time = to_date.getTime();

        const diff = to_time - from_time;
        const distance_in_minutes = Math.round(Math.abs(diff) / 60000);
        const distance_in_seconds = Math.round(Math.abs(diff) / 1000);
        const tense = full_options.include_tense ? (diff > 0 ? " from now" : " ago") : "";
        if (0 <= distance_in_minutes && distance_in_minutes <= 1) {

            if (!full_options.include_seconds) {
                if (distance_in_minutes === 0) {
                    return "less than 1 minute" + tense;
                } else {
                    return "" + distance_in_minutes + " minute" + tense;
                }
            }

            if (distance_in_seconds < 5) {
                return "less than 5 seconds" + tense;
            } else if (distance_in_seconds < 10) {
                return "less than 10 seconds" + tense;
            } else if (distance_in_seconds < 20) {
                return "less than 20 seconds" + tense;
            } else if (distance_in_seconds < 40) {
                return "less than half a minute" + tense;
            } else if (distance_in_seconds <  60) {
                return "less than 1 minute" + tense;
            } else {
                return "1 minute" + tense;
            }

        } else if (distance_in_minutes < 45) {
            return "" + distance_in_minutes + " minutes" + tense;
        } else if (distance_in_minutes < 90) {
            return "about 1 hour" + tense;
        } else if (distance_in_minutes < 1440) {
            return "about " + (Math.round(distance_in_minutes / 60.0)) + " hours" + tense;
        } else if (distance_in_minutes < 2530) {
            return "1 day" + tense;
        } else if (distance_in_minutes < 43200) {
            return "" + (Math.round(distance_in_minutes / 1440.0)) + " days" + tense;
        } else if (distance_in_minutes < 86400) {
            return "about 1 month" + tense;
        } else if (distance_in_minutes < 525600) {
            return "" + (Math.round(distance_in_minutes / 43200.0)) + " months" + tense;
        } else {
            const distance_in_years = distance_in_minutes / 525600;
            const minute_offset_for_leap_year = (distance_in_years / 4) * 1440;
            const remainder = (distance_in_minutes - minute_offset_for_leap_year) % 525600;
            if (remainder < 131400) {
                return "about " + (Math.round(distance_in_years)) + " years" + tense;
            } else if (remainder < 394200) {
                return "over " + (Math.round(distance_in_years)) + " years" + tense;
            } else {
                return "almost " + (Math.round(distance_in_years + 1)) + " years" + tense;
            }
        }
    }

**Comment by icambron** [comment]
No thanks. That's a much more complicated version of Moment's `fromNow()`:

```js
moment().subtract(3, 'hours').fromNow(); //=> "3 hours ago"
moment().add(440, 'minutes').fromNow(); //=> "in 7 hours"
```

which is as complicated as we'd like to make it. Part of that it would have to work across all locales. Part of it is that it's the sort of scope creep we'd like to avoid. All that said, it would make an excellent plugin.
