### ISSUE TITLE
isSameOrAfter not giving correct result

### ISSUE THREAD

**Issue by larryu** [moment/moment#4030]
Chrome 56 on Cento OS.

When using format "DD/MMM/YYYY" to use isSameOrAfter, it gives wrong result.
Should I must format the date to "YYYY-MM-DD'' to use isSameOrAfter?
I had thought no matter what format you passes to moment, isSameOrAfter will give the same result, but it seems not.

**Comment by icambron** [comment]
Please post a reproducible example, with what you expect vs what is returned, preferably as a jsFiddle

**Comment by larryu** [comment]
@icambron Sorry mate, I couldn't reproduce it any more even though I rolled back all my source to that version. Maybe it's my misuse.
