### ISSUE TITLE
Issue with es6 module while bundling (Tree shaking)

### ISSUE THREAD

**Issue by msreddy09** [moment/moment#4031]
**Description of the Issue and Steps to Reproduce:**
I am using momentjs for react-i18next libraryand trying to load es6 module through webpack. I want to achieve tree  shaking through the webpack. For that I gven config is in webpack
```
  plugins: [ 
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('production')
      }
    })
  ],
  resolve: {
	mainFields: ['jsnext:main', 'browser', 'main'],
  } 
```
**Issue**
`./locale` path is not resolved, since it is loading through `require`

**Log:**
```
WARNING in ./~/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in 'C:\view\gitdev\React\react-i18next\node_modules\moment\src\lib\locale'
 @ ./~/moment/src/lib/locale/locales.js 55:12-39
 @ ./~/moment/src/lib/locale/locale.js
 @ ./~/moment/src/moment.js
 @ ./app/i18n.js
 @ ./app/main.js
 @ multi ./app/main.js
```

**Comment by ovangle** [comment]
I've dealt with this issue myself recently. The locale is not resolved because it provides a path relative to the current module at `node_modules/moment/src/lib/locale/locales.js` -- the moment build process bundles the `moment` library as a single file `node_modules/moment/moment.js`, it loads the locales from the correct directory, so it thinks the relative directory is correct.

I'll submit a PR about it tonight.

**Comment by ovangle** [comment]
ps. Webpack only sees the `require` and doesn't see the exception handling around it because it has no access to the runtime environment and thus doesn't know whether the exception is handled or not. 

In a runtime environment the require would have just failed silently.

**Comment by msreddy09** [comment]
:+1: 

Did you create PR?

**Comment by tquetano-r7** [comment]
So ... ironically, I only came across this issue when updating to `2.19.0`, which supposedly has the fix for this. Has anyone else experienced this?

**Comment by stevebauman** [comment]
@tquetano-r7 Experiencing this now as well with `v2.19.0`

**Comment by stevebauman** [comment]
Can confirm that `v2.18.1` does not have this issue. Rolled back for the time being.
