### ISSUE TITLE
RFC 2822 parser discards offset

### ISSUE THREAD

**Issue by jwoyame** [moment/moment#4035]
These outputs should be identical:
`console.log(moment('Thu, 22 Jun 2017 18:17:45 EDT').format('MM/DD/YYYY h:mm a'));`
`console.log(moment('Thu, 22 Jun 2017 18:17:45 -0400').format('MM/DD/YYYY h:mm a'));`

Actual outputs:
06/22/2017 6:17 pm
06/22/2017 2:17 pm

An examination of the RFC 2822 parsing code shows that the +-9999 time offset is always replaced with the GMT offset:

`  default: // UT or +/-9999`
`    timezone = timezones[' GMT'];`

Pull request forthcoming.

**Comment by TracyGJG** [comment]
Please confirm this is different to PR #3938

**Comment by icambron** [comment]
Closing in favor of #3938
