### ISSUE TITLE
RFC 2822 parsing accuracy is not tested

### ISSUE THREAD

**Issue by jwoyame** [moment/moment#4037]
Thanks for the great project.

I see there are test cases for RFC 2822 validity (`parsing RFC 2822`, `non RFC 2822 strings`) which cover the possible situations well, but they do not check whether the valid date is accurate or not.

See #4035, where the parser was overwriting the numeric time offset component.

**Comment by icambron** [comment]
I'm sure we'd accept some PRs for better test coverage

**Comment by icambron** [comment]
I believe #3938 addresses this, though of course if you think more testing is needed, we're happy to take additional test code.
