### ISSUE TITLE
Setting locale with an array returns unexpected value

### ISSUE THREAD

**Issue by mrkesh** [moment/moment#4039]
**Description of the Issue and Steps to Reproduce:**

Setting array of locales doesn't always return the value expected. I use as inputs locale format of _ab_CD_.

Examples
`moment.locale('es_ES'); // es`
`moment.locale(['es', 'en-gb'] // es`

Based on the examples above, it seems `es_ES` is understood by moment. However, I am not getting the same result as in the second example when I try:
`moment.locale(['es_ES', 'en_GB'] // en-gb`

The documentation mentions "Finally, Moment will search intelligently through an array of locales and their substrings." but it is unclear how the search is being done. I'd expect the array to work sort of like a priority-based list with the `es_ES` being evaluated before getting to `en_GB`.

Bug or am I misunderstanding how `moment.locale([locales]` work?

**Environment:**
Chrome 59 on OSX

Thanks

**Comment by icambron** [comment]
See #3946 for a discussion of this
