### ISSUE TITLE
Why does fromNow why skip from 25 days to a month?

### ISSUE THREAD

**Issue by jcalfee** [moment/moment#4040]
> moment('2017-07-21T11:03:57').fromNow()
'in 25 days'
> moment('2017-07-22T11:03:57').fromNow()
'in a month'
> 

and from 10 months to a year?

moment@2.18.1

**Comment by icambron** [comment]
It's useful rounding, similar to how it doesn't say "9 months, 26 days, 4 hours". You can [customize](http://momentjs.com/docs/#/customization/relative-time-threshold/) the thresholds if you want.

**Comment by laura-chacon** [comment]
> It's useful rounding, similar to how it doesn't say "9 months, 26 days, 4 hours". You can [customize](http://momentjs.com/docs/#/customization/relative-time-threshold/) the thresholds if you want.

Do you now how customize the maximum? Because the function `relativeTimeThreshold` lets you change the least number. In my case I want `fromNow` to return _a month ago_ when day difference is less than 61 days.
