### ISSUE TITLE
Add moment.utc.ISO_8601 for formatting, validation

### ISSUE THREAD

**Issue by alanhett** [moment/moment#4051]
I sometimes import moment this way when I know I'm going to use utc across the board:

`var moment = require('moment').utc;`

The only problem is, I can't access moment.ISO_8601, so I have to do a separate import like so:

`var ISO_8601 = require('moment').ISO_8601;`

It would be nice to be able to access that function like this:

`moment.utc.ISO_8601;`

Thank you for this incredible library.

**Comment by icambron** [comment]
We'll pass on this. Requiring `.utc` is a neat trick, but not something we're going to officially support. It's also not clear why we'd support the ISO constant but not, say, `.duration` that way. Simpler to put things in one place. If I were you, I'd do something like this:

```js
var moment = require('moment');
var mom = moment.utc;
```

Then you can use `mom` most of the time and fallback to `moment` on the rare occasions that you need something that hangs off of it.
