### ISSUE TITLE
Issue for Units like FORTNIGHT, HALFYEAR

### ISSUE THREAD

**Issue by jmanligu** [moment/moment#4053]
**Description of the Issue and Steps to Reproduce:**
I'm trying to calculate the difference between dates and needs the output for fortnight and halfyear.

Math.ceil(moment("2022-07-30").diff(moment(), "HALFYEARs") / 1);

However, it seems moment haven't support these type of units yet.

**Comment by mj1856** [comment]
You're joking, right?

**Comment by mj1856** [comment]
For fortnights, just diff by weeks and divide by 2.
For halfyears, just diff by quarters and divide by 2.

**Comment by jmanligu** [comment]
Well, I just thought units like this were already supported. 
It seems we'll just amend the code then checks if users uses units not supported by moment.js

Thanks sir. 👍
