### ISSUE TITLE
moment('02-29', 'MM-DD') is invalid

### ISSUE THREAD

**Issue by mleduque** [moment/moment#4054]
moment('02-29', 'MM-DD').isValid() returns false.

see for example the console in https://jsfiddle.net/2kkjLn8f/1/

Tested on Linux/chromium 59, Linux/firefox 54
*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

I suspect that's because it's using the current year (2017), but 02-29 is a valid date some years.

**Comment by icambron** [comment]
Moment is a fancy wrapper for epoch timestamps, so each instance represents a specific millisecond. Thus, your string means exactly 2017-02-29T00:00:00.000 in your local time zone, not, like, abstract idea of Feb 29. So it's not valid. If you provided a leap year to the parser, it would be fine.
