### ISSUE TITLE
How can i get hours in two digits?

### ISSUE THREAD

**Issue by mallikarjuna909** [moment/moment#4056]
Hi,

I'm using 'moment().format("L LTS");'. 
So i'm getting as expected: "07/06/2017 5:35:51 PM" 

But i'd like hours in two digits like: "07/06/2017 05:35:51 PM".

Thanks.

**Comment by jeffrey008** [comment]
By default LTS has no zero padding.
You can do 
`moment().format("L HH:mm:ss A"); `

**Comment by mallikarjuna909** [comment]
Hi @jeffrey008 
Thanks for your kind reply but unfortunately this code won't help to me, because i'm displaying time based on locale. So i cant hardcode like `HH:mm:ss` . 
Also When we are displaying time 24 hours format why we need show meridian? 

`moment().format("L HH:mm:ss A");` gives "07/07/2017 13:23:25 PM". 

Thanks.

**Comment by icambron** [comment]
Yeah, the default `en-us` has no padding for LTS. Sampling a few locales, it looks like those who use `h` and `a` tend to use just `h` and those that just use `H` tend to use `HH`. I'm not sure how to help you here; the authors of these `h` locales have determined that the the format shouldn't pad. For the only language I know well, en-us, this is unambiguously the right decision.

So your request is an odd one: you want locale-specific formatting except for in the one way where you don't want it to be locale-specific but instead be your way.  You can of course override all of the relevant locales to use padding. There might be a way of doing it automatically where you replace instances of `hh` in the current locale's LTS setting, though I haven't thought about how exactly to do that. But I'd suggest that if you want a standard format times, you should use a standard format and that if you want locale-specific formats, that you accept locale specific formats that may or may not pad. I mean, you either want settings that are appropriate for the locale or you don't, right?

**Comment by mallikarjuna909** [comment]
Hi @icambron 

Firstly, thanks for your kind reply. I agree with you what you said and even i know that is locale's standard. But i was expected some method or constant that we can easily change right away.

But However i stick to locale standard until unless my clients okay with it. otherwise i'll go with changing instances of `hh` in Locale's LTS settings.
like
```
_longDateFormat : {
LT : "hh:mm A",
.....
} 
```  

Thanks.
