### ISSUE TITLE
moment().format() always output in local time, utcOffset() odd behaviour 

### ISSUE THREAD

**Issue by jeffrey008** [moment/moment#4057]
**Description of the Issue and Steps to Reproduce:**
```js
// NOT what I expect
moment("2017-07-03T00:00:00+08:00").format() 
// => "2017-07-02T10:00:00-06:00"

// What I expect, but a bit clumsy
moment("2017-07-03T00:00:00+08:00").utcOffset("2017-07-03T00:00:00+08:00").format()
// => "2017-07-03T00:00:00+08:00"
```

Also moment somehow use local time as utcOffset which cause the following behaviour:
```js
// Wrong, gives  -360
moment("2017-07-03T00:00:00+08:00").utcOffset() 
```

Can we make moment to use its internal `_tzm` by giving an option into `format()` ?
So that 
```js
moment("2017-07-03T00:00:00+08:00").format('', {useTZM: true})
 // => "2017-07-03T00:00:00+08:00"
```

**Environment:**
Chrome 58 on OSX
moment.version "2.14.2"

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on 2017-07-07T01:57:48-06:00

**Comment by maggiepint** [comment]
You need `.parseZone`.

See this blog post:
https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/
