### ISSUE TITLE
grunt transpile-raw task fails: bundle.generate now returns a Promise instead of a { code, map }

### ISSUE THREAD

**Issue by NTag** [moment/moment#4060]
**Description of the Issue and Steps to Reproduce:**

I just cloned the repository, checkout `develop`, `npm install`, `npm install -g grunt` and executed `grunt`.

I got the following output:
```
Running "jshint:all" (jshint) task
>> 399 files lint free.

Running "jscs:all" (jscs) task
>> 399 files without code style errors.

Running "transpile" task

Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "transpile-raw" task
>> error transpiling Error: bundle.generate(...) now returns a Promise instead of a { code, map } object
>>     at Promise.get (/Users/ntag/Projets/moment/node_modules/rollup/src/rollup.js:81:9)
>>     at /Users/ntag/Projets/moment/tasks/transpile.js:75:26
>>     at process._tickCallback (internal/process/next_tick.js:103:7)
Warning: bundle.generate(...) now returns a Promise instead of a { code, map } object Use --force to continue.

Aborted due to warnings.
```

**Environment:**

I use macOS, tried with node v0.12.18 (npm v2.15.11), node v6.9.15 (npm v3.10.10), and also with node v7.10.0 (npm v4.2.0), all failed.

`grunt --version` gives `grunt-cli v1.2.0 grunt v0.4.5`.

But I see that travis has the same issue, so you might already know about!

**Comment by halfnibble** [comment]
I'm getting this message using Rollup.js. Any idea what the relation may be?
