### ISSUE TITLE
weird result of isValid()

### ISSUE THREAD

**Issue by chouex** [moment/moment#4064]
**Description of the Issue and Steps to Reproduce:**
i want to detinmine if the date format is 'D/M/YYYY' using moment("1991-10-10T00:00:00", 'D/M/YYYY').isValid() 
but i got wrong result for different year

**Environment:**
Chrome,IE

```js
moment("1991-10-10T00:00:00", 'D/M/YYYY').isValid() 
false
moment("2001-10-10T00:00:00", 'D/M/YYYY').isValid() 
true
moment("2000-10-10T00:00:00", 'D/M/YYYY').isValid() 
false
```

**Comment by icambron** [comment]
By default, Moment is very aggressive about finding a way to parse your string. You can see how it tries to handle each string with `moment("1991-10-10T00:00:00", 'D/M/YYYY').parsingFlags() `. What you probably want to do is to parse in strict mode:

```js
moment("2001-10-10T00:00:00", 'D/M/YYYY', true).isValid() //=> false
```
