### ISSUE TITLE
moment.parseZone() Incorrect .isDST() behavior

### ISSUE THREAD

**Issue by al3x-huang** [moment/moment#4069]
**Description of the Issue and Steps to Reproduce:**
moment.parseZone("2017-01-15T16:31:06.000-08:00").isDST() false when it should be yes.
*Please include the values of all variables used.*

**Environment:**
NodeJS 4.4.4 on OSX
*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

**Comment by icambron** [comment]
No, it shouldn't. `parseZone` moves the Moment instance into a fixed-offset zone according to the offset supplied in the string (in this case UTC-8). A fixed-offset zone is never in a a DST. Moment doesn't know you mean, say, US Pacific Time; it just has the string -8. Lots of different zones with different DST rules could be in a given offset and Moment doesn't try to guess what DST rules you expect to be applied.

Also, Jan 15 is not in a DST anywhere, so there's that.

**Comment by jyywhw** [comment]
Could moment support use city name/special name as parameter?  
like
moment.parseZone("Europe/Tallinn").isDST() // time is the PC time.
or 
moment("2017-06-15T16:31:06").parseZone("Europe/Tallinn").isDST()

**Comment by icambron** [comment]
@jyywhw no, IANA zones are supported in moment-timezone but not Moment itself

**Comment by jyywhw** [comment]
I use moment-timezone at last.
