### ISSUE TITLE
Date format issue in Korean language

### ISSUE THREAD

**Issue by YenalTuran** [moment/moment#4070]
Korean date format must be e.g. 2017. 07. 17. 
But in Moment.js it is implemented as 2017. 07. 17
Basically one dot is missing in the end of the day of the date.

**Comment by stephan-v** [comment]
https://github.com/moment/moment/blob/develop/CONTRIBUTING.md

You can create a pull request with updated unit tests, also this:

> If you have any changes to existing locale files, @mention the original author in the pull request (check the top of the language file), and ask if he/she approves of your changes. Because I don't know any languages I can't judge your locale changes, only the original author can :)
> 
> In order for your pull request to get merged it must have approval of original author, or at least one other native speaker has to approve of the change (happens rarely).

**Comment by icambron** [comment]
cc  @kyungw00k

**Comment by marwahaha** [comment]
@kyungw00k or @jeeeyul -- do you have thoughts here?

**Comment by kyungw00k** [comment]
> In written documents, the date form above (but not the time) is often abbreviated by replacing each unit suffix with a single period; for example, 1975년 7월 14일 would be abbreviated as “1975. 7. 14.” (note the trailing period and intervening spaces).
> (from https://en.wikipedia.org/wiki/Date_and_time_notation_in_South_Korea)

@YenalTuran You got the point. Will you make the PR with the trailing period?
@jeeeyul How about that?
@marwahaha @icambron I think it is good to go. 👍

**Comment by YenalTuran** [comment]
Thanks guys for following up this.

**Comment by GCKPaulYang** [comment]
Hi 

I am Paul Yang and working for GCK.
I am happy to work with you.
First of all, there is never a need for dot to use at the end of date in a sentence.
The issue is when a date is used by itself, but even in this case, the dot is not necessary.
So dot is recommended to be removed at the end.

And "-" rather than "." is commonly used.
For example 2018-08-18 is common.
Please refer to it.

Paul

**Comment by OlegZee** [comment]
Here's a picture from .NET application:
![image](https://user-images.githubusercontent.com/513301/134461676-9b8c328e-0c76-4bb8-9fa7-7e93cf11e10f.png)

It supports @GCKPaulYang 's statement.
