### ISSUE TITLE
moment().isBefore() Crashes in Internet Explorer 8

### ISSUE THREAD

**Issue by kumaran-nc** [moment/moment#4072]
**Description of the Issue and Steps to Reproduce:**
A fatal error, "Object doesn't support this property or method", is received when calling `isBefore` with a granularity argument.
i.e.
```
moment().isBefore(moment(), 'year');
```

**Environment:**
I've only been able to recreate this issue on Internet Explorer 8 running on Windows XP.

**Other information that may be helpful:**
It appears that the offending code is in this `isDurationValid` function at line 2658. The use of Array's `indexOf` method is the problem, as that doesn't exist in IE8. I've modified my MomentJS library and replaced it with the custom indexOf function that's defined earlier in the file and that solves the issue.

**Comment by stephan-v** [comment]
> Currently the following browsers are used for the ci system: Chrome on Windows XP, IE 8, 9, and 10 on Windows 7, IE 11 on Windows 10, latest Firefox on Linux, and latest Safari on OSX 10.8 and 10.11.

This is known so it is not much of an issue and it is debatable whether to build in more support for IE on windows XP.

**Comment by maggiepint** [comment]
While I"m not delighted with spending tons of time on this, there is a simple fix. Use the IndexOf function inside the utils folder that defaults back to iterative code if the Indexof function doesn't exist. Will mark up for grabs.

**Comment by maggiepint** [comment]
actually closed #4079
