### ISSUE TITLE
Moment typescript library uses `void` type as parameter input

### ISSUE THREAD

**Issue by chrisleck** [moment/moment#4073]
**Description of the Issue and Steps to Reproduce:**
The moment constructor parameter (`MomentInput` @ https://github.com/moment/moment/blob/develop/moment.d.ts#L396) is typed to include `void` as a possible input type but does not include `undefined` or `null`.  With `strictNullChecks` enabled, these are not interchangeable.

**Comment by chrisleck** [comment]
An example error from tslint when passing a parameter of type `Date | null` into `moment`:

```Error at test.ts:439:25: Argument of type 'Date | null' is not assignable to parameter of type 'string | number | void | Date | (string | number)[] | Moment | MomentInputObject | undefined'.```

**Comment by chrisleck** [comment]
Note that this happens with Typescript >= 2.0.0

**Comment by ovangle** [comment]
That looks like it's a correct type error to me. `moment(null)` is an invalid moment.

**Comment by chrisleck** [comment]
`moment(null)` is an invalid moment, but allowed by the API.

In any case, the typing of `void` already allows for `null` with `strictNullChecks` disabled.  The problem is that when `strictNullChecks` is enabled, this no longer holds and the type no longer reflects the API.

**Comment by ovangle** [comment]
Well yeah, that's why you turned `strictNullChecks` on -- so that you get stricter type checks out of it. If a result is guaranteed to be invalid for all inputs of a type, then the type is _not_ allowed by the API.

There are actually some places where I'd tighten it up even further and disallow `undefined` from being passed into `MomentInputArg` methods.

**Comment by marwahaha** [comment]
@ovangle @chrisleck What's the best way to fix this?

**Comment by chrisleck** [comment]
IMO, the typing is currently incorrect - `void` is not a valid parameter type in any type library I've seen.  Passing `null` into the moment constructor is allowed and returns a well-formed invalid moment.  I strongly believe the typing should be changed to remove void and replace it with `undefined | null`.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

There will not be a Moment v3.

Perhaps it was fixed with https://github.com/moment/moment/pull/5151
