### ISSUE TITLE
Implement options for Vue JS

### ISSUE THREAD

**Issue by nicolasvahidzein** [moment/moment#4075]
Hello,

can you please tell me where i can find the method to set options for vue js please?

when i try this anywhere in vuejs it crashes:

// core with all locales
define(['moment/min/moment-with-locales'], function (moment) {
    moment.locale('de');
    console.log(moment().format('LLLL')); // 'Freitag, 24. Juni 2016 01:42'
});

**Comment by yzxchoice** [comment]
npm install moment

import * as moment from 'moment';

let now = moment().format('LLLL');

**Comment by nicolasvahidzein** [comment]
i was talking about the locale part and loading multiple locales and adding more. 

Thank you.

**Comment by nicolasvahidzein** [comment]
i figured it out, thank you so much. I just had to import in i18next moment once again and then simply just write:

var languagesetdynamicallyvar = GETFROMSSYTEM

moment.locale(languagesetdynamicallyvar)
