### ISSUE TITLE
Invalid output format for YYYY-MM-DDThh:mm, changes T for A: 2017-07-18A08:00

### ISSUE THREAD

**Issue by ppazos** [moment/moment#4081]
**Description of the Issue and Steps to Reproduce:**

Got a moment object with any date, and apply the format with time separator T.

console.log(start.format("YYYY-MM-DDThh:mm"));

The result is the T is transformed to A 2017-07-18A08:00

My goal is to use the value from format to set a datetime-local input field.

*Please include the values of all variables used.*

**Environment:**

MacOs 10.11.6 / Chrome 59
Moment 2.18.1

**Other information that may be helpful:**
* Using it as a dependency for fullcalendar https://fullcalendar.io/

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

```
Sat Jul 22 2017 02:07:50 GMT-0300 (UYT)
7/22/2017, 2:07:50 AM
180
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
2.18.1
```

**Comment by ashsearle** [comment]
Which locale, and are you using any moment plugins or customisation?

In the meantime, you should be able to escape the `T` using: `.format("YYYY-MM-DD[T]hh:mm")`

**Comment by ppazos** [comment]
@ashsearle no plugins, no customization, I didn't specified any locales, but my machine is en-US.

the escape workaround worked OK.

**Comment by icambron** [comment]
This works fine for me:

```js
moment().format("YYYY-MM-DDThh:mm"); //=> "2017-07-31T09:37"
```

Can you create a JSFiddle reproducing the issue?

**Comment by Guilouf** [comment]
Here is a fiddle reproducing the issue, but only managed to do it with fullcallendar instanciated moment.js instance: http://jsfiddle.net/jso51pm6/284/

**Comment by ashsearle** [comment]
@Guilouf Thanks... having investigated a little, it looks like the problem is with [fullcalendar's custom implementation of the format method](https://github.com/fullcalendar/fullcalendar/blob/9c97382a2b22aed5a217fedc261edbe60fe4ab6a/src/date-formatting.ts#L12) - it's not a problem in moment itself.

**Comment by icambron** [comment]
That certainly clears things up. I'm not sure I even think FullCalendar is doing anything wrong here; you should definitely wrap literals in `[ ]`.
