### ISSUE TITLE
Wrong "Time from now" for RFC 2822 date

### ISSUE THREAD

**Issue by cravler** [moment/moment#4082]
Moment.js version 1.18, proper RFC 2822 date time format show wrong value for `moment().fromNow()`

**Steps to Reproduce:**

```js
var DATE_RFC2822 = "ddd, DD MMM YYYY HH:mm:ss ZZ";
var now = moment().format(DATE_RFC2822);
console.log(now); // Mon, 24 Jul 2017 10:00:47 +0300
console.log(moment(now).fromNow()); // in 3 hours
console.log(moment(new Date(now)).fromNow()); // a few seconds ago
```
both must be `a few seconds ago`

**Comment by maggiepint** [comment]
I believe this is the fact that we don't have numeric parsing in RFC2822 right now. There is a pull request for this that needs unit tests and validation, #4082. Closing this in favor of that.
