### ISSUE TITLE
duration's toISOString() produces incorrect results after "add" operation

### ISSUE THREAD

**Issue by jpuffer** [moment/moment#4089]
After adding or subtracting from a duration, the toIsoString method produces incorrect results.

To reproduce:
`moment.duration("P2DT71H30M").toISOString()` -> "P2DT71H30M"
`moment.duration("P2DT71H30M").add(-3, "days").toISOString()` -> "P1DT71H30M"
This returned value is one day less than the original duration, even though we asked to subtract three days.

I reproduced by entering these values into the console on the version of moment running on https://momentjs.com.

**Environment:**
Chrome 59 on OSX

**Comment by jpuffer** [comment]
also see https://github.com/moment/moment/issues/4089

**Comment by icambron** [comment]
Yeah, I suspect that's a bug.

**Comment by jpuffer** [comment]
Any idea whether the bug is in the creation of the Duration or in the stringification of it?

**Comment by icambron** [comment]
I don't have time to look now, but you should be able to use the accessors to check its day, hour, etc; if they produce correct results, then it must have created it right and failed to string it. Otherwise the opposite of that

**Comment by jpuffer** [comment]
Looking deeper, I believe the bug is in the `toISOString` method.  The duration object up to that point seems to have strange albeit correct data (it allows negative values).

It looks like the first operation (subtracting three days) produces a moment like this:
```
_data:{
  days: 1,
  hours: 23,
  milliseconds: 0,
  minutes: 30,
  months: 0,
  seconds: 0,
  years: 0,
},
_days: -1,
_isValid: true,
_milliseconds: 257400000,
_months: 0
```
The underscore prefixed v`_days` value goes negative, while the values inside _data seem to correctly "borrow" from hours to avoid a negative value for days.

Then `toISOString` runs, it uses the underscored values, not those inside _data.  It performs `Math.abs` (I'm not sure why) which turns `_days:-1` into a value of `1` for its internal days value. (This is where the value of the duration becomes incorrect)

I would assume the underscored values on the root of the object are meant to represent the "original" duration and those inside `_data` represent the "interpreted" duration?  If that's the case, it would seem the approach would be either to:
1) Use the interpreted values inside `_data` to perform the toISOString output.
or
2) Instead of `Math.abs` here https://github.com/moment/moment/blob/develop/src/lib/duration/iso-string.js#L17 it should replicate the same "borrowing" logic that keeps the `_data` values positive.  This approach seems it may be difficult given the inexact relationship between Days and Hours and the comment about how days are supposed to be non-bubbling. (https://github.com/moment/moment/blob/develop/src/lib/duration/iso-string.js#L7)

**Comment by jpuffer** [comment]
I've also notices that this issue can also be reproduced with "proper" durations (durations with hours that are not greater than 23).  The following will also reproduce the bug:
`moment.duration("P5DT23H").toISOString()` -> "P5DT23H"
`moment.duration("P5DT23H").add(-6, "days").toISOString()` -> "-P1DT23H"

The latter statement should have produced "-PT30M".

The ISO formatter's inability to "borrow" from hours and interpretation of days as their 
Absolute Value seems to be causing the output to be inaccurate.

**Comment by icambron** [comment]
Yeah, borrowing is lossy, but required if we wanted to avoid scattering negatives about. Here's my experimental library that does this, though I call it "normalizing": https://github.com/icambron/luxon/blob/master/src/duration.js#L204

**Comment by jpuffer** [comment]
Reading the issues you referenced, it seems the community would agree the expected behavior of `toISOString` would be to output mixed negatives.
So in the case of `moment.duration("P5DT23H").add(-6, "days").toISOString()`, the expected output would actually be "P-1DT23H"?

It seems like normalization is a separate issue from this bug and maybe someday Moment could add a method to 'normalize', turning durations into sane ones, like the library you linked.  (both un-mixing negatives and borrowing from overloaded values like "30 hours".)

It seems this existing PR fixes the correctness problem in the bugs described by this ticket: https://github.com/moment/moment/pull/4062/files

**Comment by icambron** [comment]
OK, I hadn't really caught up on those other tickets, but skimming it now I agree it looks like we're moving forward with mixed negatives in ISO output. I'm going to close this in preference for #3960
