### ISSUE TITLE
fromNow() return values are different

### ISSUE THREAD

**Issue by linzhaoken** [moment/moment#4092]
**Description of the Issue and Steps to Reproduce:**
When I use fromNow() function to calculate day and time difference I have got different results on the same date. I just wonder if this is an bug or this is an expected results.

*Please include the values of all variables used.*
function used ```moment(fromDate).fromNow()```

Case 1: will return 2 days
Date Now: 2017-07-28 01:00:00
fromDate: 2017-07-31 00:00:00
difference is 58 hours so < 2 and half day

Case 2: will return 3 days
Date Now: 2017-07-28 01:00:00
fromDate: 2017-07-31 02:00:00
difference is 60 hours so >= 2 and half day

**Environment:**
Chrome 59 on OSX, Firefox 53.2.1, Node JS v6.9.5

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)
Time Zone: Irish Standard Time

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString()) // Mon Jul 31 2017 11:45:11 GMT+0100 (IST)
console.log((new Date()).toLocaleString()) // 7/31/2017, 11:45:11 AM
console.log( (new Date()).getTimezoneOffset()) // -60
console.log( navigator.userAgent) // Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0
console.log(moment.version) // 2.18.1
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by icambron** [comment]
Right, it's just rounding. You can customize the rounding; see [here](http://momentjs.com/docs/#/customization/relative-time-rounding/)
