### ISSUE TITLE
isoWeek misbehaving ?

### ISSUE THREAD

**Issue by turshija** [moment/moment#4094]
**Description of the Issue and Steps to Reproduce:**

I'm trying to get isoWeek in a specific year, but I'm receiving weird results. If I create moment object only with year (2017), I receive date with year 2016. If I create object with [2017, 0] (January 2017), I get same result with year 2016, but if I create an object with [2017, 1] (February 2017), I receive result with year 2017.

I tested it in console on momentjs.com website.

#### Test data:

moment().isoWeek(31).format('YYYY-MM-DD')
> "2017-08-01"

moment([2017]).isoWeek(31).format('YYYY-MM-DD')
> "2016-08-07"

moment([2017, 0]).isoWeek(31).format('YYYY-MM-DD')
> "2016-08-07"

moment([2017, 1]).isoWeek(31).format('YYYY-MM-DD')
> "2017-08-02"

**Environment:**

* Chrome 59.0.3071.115 on OSX

```
Tue Aug 01 2017 17:10:02 GMT+0200 (CEST)
8/1/2017, 5:10:02 PM
-120
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
2.18.1
```

**Comment by icambron** [comment]
`isoWeek(w)` maintains the current ISO weekday, so Tuesday week 1 -> Tuesday week 31, etc. This is analogous to maintaining the day when setting the month; `moment(2017, 0, 5).month(6)` results in July 5, not July 1. I think you probably want this:

```js
moment(...).isoWeek(31).startOf('isoWeek');
```

**Comment by nicholasbraun** [comment]
@icambron This behaves strange too. For example 
> for (i = 2018; i<=2040; i++) {
	console.log(i + ' ' + moment('' + i, 'YYYY').isoWeek(2).startOf('isoWeek').format('YYYY-MM-DD'))
}

gives the output:
> 2018 2018-01-08
2019 2019-01-07
**2020 2020-01-06
2021 2020-01-06**
2022 2021-01-11
2023 2022-01-10
2024 2024-01-08
2025 2025-01-06
**2026 2026-01-05
2027 2026-01-05**
2028 2027-01-11
2029 2029-01-08
2030 2030-01-07
2031 2031-01-06
**2032 2032-01-05
2033 2032-01-05**
2034 2033-01-10
2035 2035-01-08
2036 2036-01-07
**2037 2037-01-05
2038 2037-01-05**
2039 2038-01-11
2040 2039-01-10

Every few years it gives the output of the year before.

**Comment by icambron** [comment]
@nicholasbraun No, that's probably right. ISO week years and Gregorian years don't always line up. Eg, that's saying Jan 1, 2021 is at the 2020 ISO week year, so taking the second week of the week year puts you all the way back at the start of the 2020 week year. See more [here](https://en.wikipedia.org/wiki/ISO_week_date#Relation_with_the_Gregorian_calendar).

Try it with 'GGGG' instead of 'YYYY'; I bet it will go how you expect.
