### ISSUE TITLE
Calendar function returns incorrect week with local "zh"

### ISSUE THREAD

**Issue by tokinonagare** [moment/moment#4097]
https://github.com/moment/moment/issues/4047 in this issue tell about incorrect week.

In zh local e.g：If today is  Thursday (2017-08-03T16:25:11.750), the display is “上星期二”, in fact is this week Tuesday(2017-08-03), but for Chinese, they would thought  it was 2017-07-25.

by the way, I google it:
![image](https://user-images.githubusercontent.com/6461520/28912942-e0ac7ed4-7868-11e7-9df9-ca17243e3c5f.png)

Thanks for you help 😊

**Comment by leandrogehlen** [comment]
This problem is happening with any locale when update locale.

Scenario: 

```js
moment.locale('pt-br', {
  sameDay: '[Hoje],
  nextDay: '[Amanhã]',
  nextWeek: 'dddd ',
  lastDay: '[Ontem]',
  lastWeek: function () {
     return (this.day() === 0 || this.day() === 6) ?
         '[Último] dddd' : // Saturday + Sunday
         '[Última] dddd'; // Monday - Friday
     }
});

moment('2017-08-18').calendar(); //result: Última Friday
//expected: Última Sexta-Feira


});
```

**Comment by luckylooke** [comment]
It happens with "en" locale as well, even you do not update locale:
Just open momentjs.com and run this in console
```
moment.locale()
// "en"
a = moment().add(2, 'days')
a.format()
//"2018-02-08T11:40:37+01:00"
moment().format()
//"2018-02-06T11:41:06+01:00"
moment().calendar(a)
//"Last Tuesday at 11:41 AM"
```
Definitely not "last" Tuesday.

tested with latest chrome browser on latest mac OS

**Comment by marwahaha** [comment]
seems similar to https://github.com/moment/moment/issues/4006

@ben-lin @suupic thoughts?

**Comment by shiny** [comment]
it is a ridiculous bug exists for **years**!

**Comment by awmleer** [comment]
For Chinese people this is actually very confusing. And most of us will regard this behavior as a bug.
