### ISSUE TITLE
Setters changing timezone

### ISSUE THREAD

**Issue by henit** [moment/moment#4098]
Code:

    import moment from 'moment-timezone';
    moment.tz.setDefault('Europe/Oslo');
    console.log(moment.parseZone('2017-08-03T15:30:00Z').format());
    console.log(moment.parseZone('2017-08-03T15:30:00Z').hour(16).format());
    console.log(moment.parseZone('2017-08-03T15:30:00Z').set('hour', 17).format());

Output:

2017-08-03T15:30:00Z
2017-08-03T16:30:00+02:00
2017-08-03T17:30:00+02:00

So, all three start as `15:30:00Z`, but when I try to change hour, it goes to timezone `+02:00` (probably from the default set above).

Should not the moment keep its timezone when setting hour like this? And it appears to change timezone before setting hour, as `15:30 Z` changed to hour **16** (in the original timezone) would be `18:30 +02:00`.

It seems strange to me that setting hour, minute or similar parts of a timestamp would change it to a different timezone...

**Comment by icambron** [comment]
This works OK without the `moment.tz.setDefault()` call. I suspect there's a bug in the interaction between moment and moment-timezone, but I'm not sure which side of the fence the bug is on.

**Comment by henit** [comment]
Yes, without the `setDefault`, it works as expected even when the input timestamp is of a different time zone than what I presume is the default when not set explicit (Z).

    import moment from 'moment-timezone';
    
    console.log(moment.parseZone('2017-08-03T15:30:00+03:00').format());
    console.log(moment.parseZone('2017-08-03T15:30:00+03:00').hour(16).format());
    console.log(moment.parseZone('2017-08-03T15:30:00+03:00').set('hour', 17).format());

2017-08-03T15:30:00+03:00
2017-08-03T16:30:00+03:00
2017-08-03T17:30:00+03:00

**Comment by henit** [comment]
I also notice that this only happens when using `moment.parseZone`, not with `moment.tz`. Example trying to force two timestamps to be in London time at `16:00`:

    import moment from 'moment-timezone';
    
    moment.tz.setDefault('Europe/Oslo');
    
    console.log(moment.tz('2017-08-03T15:30:00Z', 'Europe/London').format());
    console.log(moment.tz('2017-08-03T15:30:00Z', 'Europe/London').hour(16).minute(0).format());
    
    console.log(moment.parseZone('2017-08-03T16:30:00+01:00').format());
    console.log(moment.parseZone('2017-08-03T16:30:00+01:00').hour(16).minute(0).format());

2017-08-03T16:30:00+01:00
2017-08-03T16:00:00+01:00

2017-08-03T16:30:00+01:00
2017-08-03T16:00:00+02:00

**Comment by ellenaua** [comment]
Moment-timezone has a hook `updateOffset()` here https://github.com/moment/moment-timezone/blob/develop/moment-timezone.js#L528-L550
That hook is called after any manipulation with a date (adding or subtracting days, hours, etc) and updates `_offset`, because there may be Daylight Saving time shift. 
What that hook does:
- gets timezone saved in `._z` property of moment object OR `moment.defaultZone`
- finds offset which is at that time at that timezone, and updates `._offset` of moment object

What we need: when date is parsed using `parseZone()`, `._z` property should be set to null (so that updateOffset() never happens) or to correct timezone of that date.
Currently, it's set to undefined and because of that  `updateOffset()` uses `moment.defaultZone`.

**Comment by icambron** [comment]
good analysis @ellenaua. want to writ ea pull request?

**Comment by ellenaua** [comment]
yes, will send a PR later

**Comment by nisha-kaushik** [comment]
Is this issue still exists?

Code:
moment.tz.setDefault('Europe/Oslo');
console.log(moment.parseZone('2017-08-03T16:30:00+01:00').format());
console.log(moment.parseZone('2017-08-03T16:30:00+01:00').hour(16).minute(0).format());

And the output is : 
2017-08-03T16:30:00+01:00
2017-08-03T16:00:00+01:00

Please guide me on this, I want to work on this as my first contribution.

**Comment by papaiatis** [comment]
I'm having a similar issue with latest moment library.
I'm in GMT+2 now, and when I add 1 month to the current date, I get back a Date with a different time zone:
```
moment(new Date()).toString(); 
--> "Wed Oct 02 2019 19:03:27 GMT+0200"
moment(new Date()).add(1, 'M').toString(); 
--> "Sat Nov 02 2019 19:03:21 GMT+0100"
```
Tried many ways to fix it but can't figure out how. Any thoughts?

**Comment by Alanscut** [comment]
@papaiatis maybe this is due to `Daylight saving time`, European Summer Time  ends at 01:00 UTC (02:00 WEST, 03:00 CEST, 04:00 EEST) on the last Sunday in October each year, so when Oct 02 -> Nov 02, the timezone will change, namely GMT+1 - > GMT+2

**Comment by marwahaha** [comment]
I cannot reproduce this anymore. I suspect it has been fixed/
Thank you for reporting this and discussing it.
Please re-open if you still have concerns.
