### ISSUE TITLE
Is it a bug or feature that moment("100-100-100", "YYYY-MM-DD").isValid() return true?

### ISSUE THREAD

**Issue by sunlin7** [moment/moment#4102]
**Description of the Issue and Steps to Reproduce:**
`moment("100-100-100", "YYYY-MM-DD").isValid()` return true, 
is it a bug or feature?

Thanks
Lin

**Comment by ashsearle** [comment]
It's a feature:

From [the docs](https://momentjs.com/docs/)
> Moment's parser is very forgiving, and this can lead to undesired/unexpected behavior

To get the behaviour you want, pass `true` as a third parameter to parse in 'strict mode':
moment("100-100-100", "YYYY-MM-DD", true).isValid(); // returns false

**Comment by sunlin7** [comment]
@ashsearle 

Great! Understand. Thank you so much.
