### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by mvaipa** [moment/moment#4103]
How do I translate into Portuguese?

**Comment by chuckrincon** [comment]
See the [documentation reference](http://momentjs.com/docs/#/i18n/).
You can set the locale as: `Portuguese` or `Portuguese (Brazil)`
With the following statements as example (importing the `moment-with-locales.js` resource):
```javascript
var march = moment('2017-03')
console.log(march.format('MMMM')) // 'March'

// returns the new locale, in this case 'pt' (Portuguese) or 'pt-br' (Portuguese (Brazil))
moment.locale('pt')

// 'March' still, since the instance was before the locale was set
console.log(march.format('MMMM'))

var ptMarch = moment('2017-03')
console.log(ptMarch.format('MMMM')) // 'Março'

// You can, however, change just the locale of a specific moment
march.locale('es')
console.log(march.format('MMMM')) // 'Marzo'
```
You can find all the local files [here](https://github.com/moment/moment/tree/develop/src/locale)

**Comment by maggiepint** [comment]
I think this covers it. thank you @chuckrincon
