### ISSUE TITLE
moment.unix giving me back incorrect date

### ISSUE THREAD

**Issue by soma83** [moment/moment#4107]
I need to obtain a moment object from a timestamp in seconds. I tried:

`
let value = 1459382400;
let obj = moment.unix(value);
`

and 

`
let obj = moment.unix(value).utc();
`

both of them gives me a wrong date. The 1459382400 corresponds to Thu, 31 Mar 2016 00:00:00 GMT, but instead I'm getting Wed Mar 30 2016 20:00:00 GMT-0400 (CDT), however if I do this:

`
moment.utc(valor, 'X').format('YYYY-MM-DD')
`

it gives me the right date, but in string format... I need it as a moment object. How can I tell moment to ignore the timezone in order to get the right moment???

**Comment by ashsearle** [comment]
You are confusing debug / string output with the internal representation of time.

The moment is correct: 'Wed Mar 30 2016 20:00:00 GMT-0400 (CDT)' is the same point in time as 'Thu, 31 Mar 2016 00:00:00 GMT'.

**Comment by soma83** [comment]
@ashsearle, I thank you for your response. The thing is I only need a moment object with the correct date representation. Firefox returns the correct moment, Chrome doesn't. You are telling me they are correct because they are the same point in time, now my question is: how can moment ignore the timezone?

**Comment by ashsearle** [comment]
Both these return the same thing in Firefox and Chrome:

```js
moment.unix(1459382400).utc().toString(); // "Thu Mar 31 2016 00:00:00 GMT+0000"
moment.unix(1459382400).local().toString(); // "Thu Mar 31 2016 01:00:00 GMT+0100" (my timezone)
```

**Comment by soma83** [comment]
Mr. @ashsearle, I just tried your code, and in Firefox it gives me the correct date for .utc() but not for .local(). I'm assuming Chrome ignores .utc() because it gives me back the same date twice time as in Firefox for .local().

**Comment by soma83** [comment]
I'm planning to ask the time and if is present to add 1 day to the moment.

**Comment by soma83** [comment]
Mr. @ashsearle you are rigth, both of them represents the same point in the time. Now it is working properly, my mistake.
