### ISSUE TITLE
I confuse about format time to show

### ISSUE THREAD

**Issue by zeing** [moment/moment#4109]
I have **only time** 
e.q.( 2.00 ) it mean 9.00(2.00+7 is my local in Thailand ) in 24hrs   
i try to convert format for output is  **9.00** but i can't 

What's wrong? 
this is my problem [https://jsfiddle.net/zeing/8ddpeyyo/5/](https://jsfiddle.net/zeing/8ddpeyyo/5/)

 thank you , sorry for my english

**Comment by zeing** [comment]
i fix by
```
                var time = moment(eachDays[eachDay].start,"HH:mm");
                        var now =moment().utc().set({hour:time.get('hour'),minute:time.get('minute'),second:0,millisecond:0});
                        console.log(now.local().format("HH:mm"))
```
it's right

**Comment by elsimir** [comment]
just so you know,

I believe the correct way of approaching this is
moment.utc('2:00', 'HH:mm').local().format('HH:mm');

**Comment by zeing** [comment]
oh thank you , it's shorter
