### ISSUE TITLE
Parsing should fail when day-of-week is inconsistent with date

### ISSUE THREAD

**Issue by dtreiter** [moment/moment#4112]
The [documentation](https://github.com/moment/momentjs.com/blob/1c94b872d4642ebbd08bf4dbc64998fdad8e2bef/docs/moment/01-parsing/02-string.md#L107) on momentjs.com claims:
"The parser also confirms that the day-of-week (when included) is consistent with the date."

Perhaps I'm misinterpreting this, but it does not seem to be the case.

**Example**
Parsing the date `Wed 08-10-2017` (which is actually a Thursday). See [JSFiddle](https://jsfiddle.net/17wd8tnm/1/).

**Expected behavior**
Moment should fail to parse the date.

**Observed behavior**
Moment parses the date, ingoring the provided day of the week. Subsequently calling `.toDate()` will use the true day of the week.

**Comment by icambron** [comment]
Yeah, this must have broken and sadly not had a test for it. I guess it's possible that we changed the behavior on purpose but didn't change the docs, but that seems less likely. IMO, the docs reflect the desired behavior and we should `isValid() //=> false`

**Comment by mikeparas** [comment]
Hello! I have submitted a PR that addresses this. If there are any issues, please let me know!
