### ISSUE TITLE
Moment's methods unnecessarily clone() when passing null like the docs (and also conflict with moment.d.ts typings).

### ISSUE THREAD

**Issue by esprehn** [moment/moment#4114]
**Description of the Issue and Steps to Reproduce:**

ex. the examples have passing null for optional arguments (things with ? in the moment.d.ts) all over the place.
https://momentjs.com/docs/#/query/is-between/

```js
moment('2016-10-30').isBetween('2016-10-30', '2016-12-30', null, '()'); //false
```

but an optional argument doesn't accept null when strictNullChecks is enabled.

This means we get lots of errors like:

`error TS2345: Argument of type 'null' is not assignable to parameter of type '"day" | "hour" | "minute" | "month" | "second" | "year" | "s" | "m" | "h" | "d" | "M" | "y" | "ye...'.`

This lead me to look at the code to see if the types or the docs were right...

isBetween calls isAfter: `this.isAfter(from, units)`

isAfter calls `units = normalizeUnits(!isUndefined(units) ? units : 'millisecond');`

isUndefined is `input === void 0`
normalizeUnits is `typeof units === 'string' ? aliases[units] || aliases[units.toLowerCase()] : undefined;`

The examples pass null instead of undefined, so we get `units = normalizeUnits(!(null === void 0) ? null : 'millisecond');` and null is not === to void 0, so we get `normalizeUnits(null)`

`typeof null === 'string' ? aliases[units] || aliases[units.toLowerCase()] : undefined;`

typeof null is 'object', so we return undefined, which inside isAfter means we fail the next check:

```js
if (units === 'millisecond') {
  return this.valueOf() > localInput.valueOf();
}
```

and instead do:

```js
return localInput.valueOf() < this.clone().startOf(units).valueOf();
```

and startOf calls normalizeUnits again: `units = normalizeUnits(units)` which returns undefined, we fall all the way through the switch statements and if blocks and return `this`.

So in the end we don't modify the clone at all, so it all collapses down to:

```js
return localInput.valueOf() < this.valueOf();
```

which is the **same** as the milliseconds fast path, except we wasted time cloning. So it seems like passing undefined is **better** than passing null like in the examples.

I think moment wants to fix the typings to allow both null and undefined, and I think the code wants to fix the checks to make passing null have the same fast paths as passing undefined. Today they have the same behavior, but passing null like the docs is slower.

**Environment:**

TypeScript Version 2.4.1

**Comment by ovangle** [comment]
I agree -- `null` should not be used indicate that the argument is optional.

There also shouldn't be _any_ function signatures where it's necessary to explicitly pass `null` or `undefined` in order to indicate an optional argument is not provided.
