### ISSUE TITLE
Getting wrong value from parsing time and date

### ISSUE THREAD

**Issue by Qoutroy** [moment/moment#4115]
**Description of the Issue and Steps to Reproduce:**

```js
var obj = {
  "startDate": "17/12/1",
  "startTime": "12:40"
}
obj.startDateTime = moment(obj.startDate+"-"+obj.startTime, "YY-MM-DD-HH-mm").toISOString();
console.log(obj.startDateTime);// "2018-01-08T23:00:00.000Z"
```
The output is totally wrong!
I managed to get it to work by changing "-" to " " and in the format string "-" to " ":
```js
obj.startDateTime = moment(obj.startDate+" "+obj.startTime, "YY-MM-DD HH-mm").toISOString();
```

**Environment:**
Chrome 59.0.3071.115 (Official Build) (64-bit) on Ubuntu 16.0.4

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString()) // "2018-01-08T23:00:00.000Z"
console.log((new Date()).toLocaleString()) // 8/10/2017, 2:49:34 PM
console.log( (new Date()).getTimezoneOffset()) // -120
console.log( navigator.userAgent) // Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
console.log(moment.version) // 2.9.0
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by icambron** [comment]
Your string is "17/12/1-12:40" but your format is "YY-MM-DD-HH-mm", which looks nothing like that. Without having debugged it, my guess on what's happening is that when when you put in a space, you somehow managed to convince Moment's very forgiving parsing to do what you were hoping. But in general, you shouldn't depend on Moment being able to figure out what format you *really* meant.

My advice is to use strict parsing (i.e. add a `true` third argument) and provide a format string that matches the format of your input.

**Comment by Qoutroy** [comment]
What do you mean with "nothing like that", the documentation says i should be able to use any(like - and /) character instead of "-".
