### ISSUE TITLE
Split moment.d.ts

### ISSUE THREAD

**Issue by ovangle** [moment/moment#4118]
moment.d.ts is the typescript file that declares typings for the public API of moment. 

#### Locality
Since moment.d.ts attempts to encapsulate the entire public API of moment in one hit, there is no clear direction to a developer working on a file in one of the `src/` directories that it needs to reflect changes in the code

### API surface documentation
The declarations file is great documentation for external javascript and typescript developers consuming the moment libraries. However, there is almost no documentation within the moment code. Function docstrings are few and far between and when provided are minimalist at best.

### Mixins
Moment defines only a few core types (`Moment`, `Locale`, `Duration` etc.) and heavily relies on  an informal mixin-like API to provide functionality to the core types. This can be leveraged to improve the tree shaking functionality of moment. However, due to a lack of documentation/types, there are numerous small differences between the way mixins are applied -- even between mixins applied to the same core type.

By standardising the mixin interface, it will open up the potential of future work supporting tree shakers, minimising the bundle size of moment.

### Dated typings
Due to backwards compatability concerns, a lot of typescript features which would be very useful in the public moment API (most notably `keyof` and `Partial`, added in 2.1). 

## Solution
Converting the entire project to typescript is a large project and requires providing typings for a lot of internal functionality which does not need it. In addition, it would greatly increase the difficulty of merging fixes back into moment 2.x.

### Split moment.d.ts

- `src/lib/core/core.d.ts`
typings for moment mixins, core, and defines the core moment interface.
- `src/lib/core/units.d.ts`
defines the basic units of moment
- `src/lib/create/create.d.ts`   
typings for moment factory functions
` `src/lib/duration/duration.d.ts`
durations
- `src/lib/locale/locale.d.ts`
locales, locale mixins, 
- `src/lib/locale/units.d.ts`
locale mixins for the unit types
- `src/lib/format/serialization.d.ts`
parsing and formatting functionality
- `src/lib/format/units.d.ts`
parsing and formatting tokens for the different units
- `src/lib/moment/moment.d.ts`
The calendar, compare, diff, start-end
- `src/lib/timezone/timezone.d.ts`
timezones, timezone mixins.
- `src/lib/moment.d.ts`
Re-exports functions from lib/* and 

## Breaking changes
The namespace is _not_ the default factory function. The following code will be invalid after this change

```typescript
// Incorrect: 2.x
const moment = require('moment');
let m = moment();

// Correct
const {moment} = require('moment');
let m = moment();
```

Typings (except for the namespace change) will be backwards compatible, but will require a minimum typescript version of 2.3. ~I'll create a PR in the next couple of days containing _only_ the typescript changes, no javascript changes.~ The typescript changes are available for review in PR #4121. it contains no javascript changes so that new types can be discussed and improved before implementation.

All javascript changes (except for the namespace change) will be internal refactorings and will not affect the public API.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
