### ISSUE TITLE
duration.add: 24 hours isn't the same as 1 day when adding to negative values

### ISSUE THREAD

**Issue by tstirrat15** [moment/moment#4120]
## Description of the Issue and Steps to Reproduce:
Inconsistent behavior of `duration.add`. To wit:
```javascript
// This works fine
expect(duration(-2, 'hours').add(24, 'hours').toJSON()).to.equal(duration(22, 'hours').toJSON());
// This errors
expect(duration(-2, 'hours').add(1, 'days').toJSON()).to.equal(duration(22, 'hours').toJSON());
// With output:
//      AssertionError: expected 'P1DT2H' to equal 'PT22H'
//      + expected - actual
//
//      -P1DT2H
//      +PT22H
```

## Environment:
Node 8.1.3 on Ubuntu 17.0.4

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
// Tue Aug 15 2017 14:57:21 GMT-0500 (CDT)
console.log((new Date()).toLocaleString())
// 2017-8-15 14:57:21
console.log( (new Date()).getTimezoneOffset())
// 300
console.log( navigator.userAgent)
// NA for node
console.log(moment.version)
// 2.18.1
```

**Comment by ashsearle** [comment]
Current behaviour is correct.

1 day is not always equal to 24 hours: it depends when you apply it (e.g. across daylight-savings-time.)

**Comment by tstirrat15** [comment]
Hmm. In the case described above, a day was appearing to be 26 hours. In
what case would that make sense? (i.e. the duration was showing up as 1d2h
instead of 22h).

**Comment by ashsearle** [comment]
I don't see '26 hours' mentioned anywhere.  I see 'P1DT2H' - this is not the same as 26 hours!

However... I have to take back my earlier statement: this behaviour is not correct.

The duration should have been formatted as P1DT-2H, and this is a known issue #3960 with a fix waiting to be merged.

**Comment by tstirrat15** [comment]
Ah, makes sense. Thank you for linking those things for me. I will close this issue as a duplicate of #3960.
