### ISSUE TITLE
Turkish locale should work differently

### ISSUE THREAD

**Issue by michaelgeorgeattard** [moment/moment#4122]
Hi,

Apologies if I avoided using the issue template.

The below, using Turkish locale:

`moment().format("Do MMMM")`

Returns:

`"16'ncı Ağustos"`

This could be considered working as expected, however seems that in Turkey it is not custom to use dates in the above format, but instead should be:

`"16 Ağustos"`

Would it be possible to emit the above without having to switching formatting string to `"D MMM"` for Turkish locale only?

**Comment by ovangle** [comment]
Yes, you can define a custom locale, say `tr-turkey` (sorry, I don't know the standard abbreviation for the turkish locale) which overrides the 'ordinal' and 'dayOfMonthOrdinalParse' keys. 

If you can evidence that turkish dates always use a cardinal day of month, then we'll happily accept a PR with the relevant changes.

**Comment by alan-agius4** [comment]
Not sure if this helps but even Google translates it as such;
![image](https://user-images.githubusercontent.com/17563226/29410697-f4c20c6a-8351-11e7-99cc-ce26d556fbcd.png)

**Comment by alan-agius4** [comment]
http://www.turkishclass.com/turkish_lesson_47

Date:  -14 Temmuz 2004.

**Comment by alan-agius4** [comment]
Should we do a PR for this?

**Comment by marwahaha** [comment]
@BYK or @erhangundogan - do you have thoughts on this issue?

**Comment by BYK** [comment]
>If you can evidence that turkish dates always use a cardinal day of month, then we'll happily accept a PR with the relevant changes.

This is the case. We never use ordinals for dates in Turkish. It is always "15 Agustos" or similar. Ordinals are only used for cases like "the second Friday of the month` etc. I think a PR is due.
