### ISSUE TITLE
week() is not correct for end of year

### ISSUE THREAD

**Issue by DavidOnGitHub** [moment/moment#4125]
const date = moment('2015-12-27')
console.log(date.week()) // 1
console.log(date.year()) // 2015

I suppose date.week() should be 53? if date.week() is 1 then date.year() can't be 2015 coz it would be the same week as '2015-01-01'.

console.log( (new Date()).toString()) // Thu Aug 17 2017 15:37:12 GMT+1000 (AEST)
console.log((new Date()).toLocaleString()) // 17/08/2017, 15:37:12
console.log( (new Date()).getTimezoneOffset()) // -600
console.log( navigator.userAgent) // Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
console.log(moment.version) // 2.18.1

**Comment by ovangle** [comment]
Are you looking for `moment.weekYear()` perhaps?

const date = moment('2015-12-27')
console.log(date.week()) // 1
console.log(date.weekYear()) // 2016

**Comment by ashsearle** [comment]
@ovangle What do you mean "there aren't 53 weeks in a year"?

Both `week()` and `isoWeek()` can return 53.  e.g. in "en" locale:
```js
moment('2016-12-27').week(); // 53
moment('2020-12-31').isoWeek(); // 53
```

(I 100% agree in using `week()` with `weekYear()`, or `isoWeek()` with `isoWeekYear()`)

**Comment by ovangle** [comment]
Yeah, sorry my bad. Sometimes people speak before they think... 

In future I'll keep my head out of these actual date manipulation issues and focus on what I actually know something about lol.

**Comment by DavidOnGitHub** [comment]
I didn't realise there is weekYear()... Thank you @ovangle 👍
