### ISSUE TITLE
Moment returns 'Invalid Date' in latest version

### ISSUE THREAD

**Issue by durgeshahire4** [moment/moment#4128]
**Description of the Issue and Steps to Reproduce:**

below date returns 'Invalid Date'
moment("2017-08-17T9:19Z").format("MM/DD/YY [at] hh:mm A")

version: 2.18.1

**Comment by icambron** [comment]
You need `09` instead of `9`

**Comment by durgeshahire4** [comment]
Previously i was using '2.2.0' version of moment that time it was working perfectly. but now i have upgrade the version to '2.6.0' and its failing, returning 'Invalid Date' and same for latest version ' 2.18.1'.

@icambron  Need your input.

**Comment by icambron** [comment]
Right, because it was an invalid ISO 8601 date and we fixed the bug that pretended it wasn't.

**Comment by durgeshahire4** [comment]
@icambron is there any release note in which this is mention, if so can you please share the link.

**Comment by icambron** [comment]
I don't see one. Your string was never supported, so it's not something we would have tracked behavior changes on carefully.
