### ISSUE TITLE
Incorrect parse with TZ when date affected by daylight saving

### ISSUE THREAD

**Issue by hrimhari** [moment/moment#4130]
Since 2.16.0, when parsing a date/time string with TZ and daylight saving is supposed to affect it, moment is set 1 hour in the future.

Example strings:
(no tz, correct): '2017-07-27 16:57:11.0' -> Thu Jul 27 2017 16:57:11 GMT-0400
(with tz, wrong): '2017-07-27 16:57:11.0 EST' -> Thu Jul 27 2017 17:57:11 GMT-0400

See those two JsFiddles:

Moment 2.15.2 (works fine): https://jsfiddle.net/j05qbwun/1/
Moment 2.18.1 (broken): https://jsfiddle.net/c4u0dzyx/1/

**Environment:**

Chrome 60.0.3112.90 (Official Build) (64-bit) on OSX

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
EST(EDT)
* The time and date at which the code was run
2017-08-18 15:10
* Other libraries in use (TypeScript, Immutable.js, etc)
jQuery, JsFiddle

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
N/A (JsFiddle).

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by ashsearle** [comment]
Where did the string `2017-07-27 16:57:11.0 EST` come from?

If you're expecting that to be interpreted in EDT then the timezone should have been specified in EDT.  i.e. `2017-07-27 16:57:11.0 EDT`.

Please check the output of the `console.log` statements suggested when reporting an issue:

```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

**Comment by icambron** [comment]
Yeah, what's happening here is that Moment is passing your string to the native date constructor because it doesn't know how to parse it (see the deprecation warning you get in the console). The native date constructor, not unreasonably, interprets your two strings differently:

```js
new Date('2017-07-27 16:57:11.0').toString() // => Thu Jul 27 2017 16:57:11 GMT-0400 (EDT)
new Date('2017-07-27 16:57:11.0 EST').toString(); //=> Thu Jul 27 2017 17:57:11 GMT-0400 (EDT)
```

Which makes perfect sense, because (as @ashsearle said) 16:57 EST really is an hour later than the 16:57 local time, which is in EDT. Hence the question of above about where your string came from: no one is in EST in July.
