### ISSUE TITLE
Unpredictable behaviour when the input format does not exactly match the input date string due to non-alphanumeric characters

### ISSUE THREAD

**Issue by nikhilw** [moment/moment#4132]
**Description of the Issue and Steps to Reproduce:**
The documentation says that:

> The parser ignores non-alphanumeric characters, so both of the following will return the same thing.
> moment("12-25-1995", "MM-DD-YYYY");
> moment("12/25/1995", "MM-DD-YYYY");

 Yet:
```bash
> const moment = require("moment");
undefined
> moment("Jul 17, 2017", "MMM D, YYYY").format("YYYY-MM-DD");
'2017-07-17'
> moment("Jul 17, 2017", "MMM ,D, YYYY").format("YYYY-MM-DD"); // additional comma before D
'2017-07-20'
> moment("Jul ,17, 2017", "MMM ,D, YYYY").format("YYYY-MM-DD"); // no issue if date is also of the same format
'2017-07-17'
```

**Environment:**
node v6.9.1, on Linux Mint 18.2.

Output of the code provided:

```bash
> const moment = require("moment");
undefined
> console.log( (new Date()).toString())
Sat Aug 19 2017 12:20:40 GMT+0530 (IST)
undefined
> console.log((new Date()).toLocaleString())
8/19/2017, 12:20:40 PM
undefined
> console.log( (new Date()).getTimezoneOffset())
-330
undefined
> console.log( navigator.userAgent)
ReferenceError: navigator is not defined
    at repl:1:14
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
> console.log(moment.version)
2.18.1
undefined
> 
```

**Comment by ashsearle** [comment]
If you want predictable behaviour, please use _strict mode_ by passing `true` as 3rd parameter to `moment(...)`:

```js
moment("Jul 17, 2017", "MMM ,D, YYYY", true).format("YYYY-MM-DD"); // 'Invalid Date'
```

**Comment by icambron** [comment]
@ashsearle is right

**Comment by nikhilw** [comment]
While returning error instead of attempting to parse when one requests strict parsing can 'avoid' such issues; I doubt what we are observing here is an expected behaviour.

If we are saying that the behaviour is expected, may I suggest that we mention it as such in the documentation? It would be best to clarify under the line that says "ignores non-alphanumeric characters" that it is not advisable to do so and users should prefer strict adherence to format or use strict parsing.

**Comment by icambron** [comment]
Many people rely on the forgiving parsing so yes, it is intended. In fact, it was the original behavior of the library. We don't much like it and we'd love to just change it and end the constant stream of issues, but that's not quite how maintaining a widely used library works.

Here are the docs for forgiving parsing and strict parsing:
 http://momentjs.com/guides/#/parsing/forgiving-mode/
 http://momentjs.com/guides/#/parsing/strict-mode/

We link to that from the main docs page like this:

> Strict parsing is frequently the best parsing option. For more information about choosing strict vs forgiving parsing, see the [parsing guide].
