### ISSUE TITLE
Italian long date format shouldn't use comma between name of the day and number

### ISSUE THREAD

**Issue by svavassori** [moment/moment#4133]
First of all thanks for the great lib you created, it's very easy to use and full of options to configure!

I have searched in issues and PR but I didn't find anything related to this, that's the reason for which I'm opening this issue.

Currently (as of 1f613c2 or version 2.18.1) the long date format for Italian locale is this:
```
longDateFormat : {
        ...
        LLLL : 'dddd, D MMMM YYYY HH:mm'
},
```
however there shouldn't be a comma between the name of the day and the number, so I propose to change it to:
```
longDateFormat : {
        ...
        LLLL : 'dddd D MMMM YYYY HH:mm'
},
```

This is in order to keep the polymorphic behavior between the different locales.

Moreover I'd ask of there is a way to have a polymorphic way to format only the date without the time, like 'dddd D MMMM YYYYY'. I didn't find any, so I had to use the 'LLLL' format and strip off the time part to keep it working across the different locales.

**Comment by icambron** [comment]
What do you think, @nostalgiaz?
