### ISSUE TITLE
Add months provides incorrect result

### ISSUE THREAD

**Issue by lightbringer1991** [moment/moment#4135]
**Description of the Issue and Steps to Reproduce:**
```javascript
var date = moment('2017-09-01');
date.add(1, 'months');
console.log(date.toISOString());    // this produces 2017-09-30T14:00:00.000Z
```
tested on version `2.18.1`

I have tried passing different timezone, but the issue persists

*Please include the values of all variables used.*

**Environment:**
Chrome Version 60.0.3112.90 (Official Build) (64-bit) on OSX

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())    // Sat Aug 19 2017 13:06:07 GMT+1000 (AEST)
console.log((new Date()).toLocaleString())     // 19/08/2017, 13:06:07
console.log( (new Date()).getTimezoneOffset())     // -600
console.log( navigator.userAgent)     // Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
console.log(moment.version)     // 2.18.1
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by ashsearle** [comment]
This looks like expected behaviour as you're 10 hours ahead of the UTC timezone used by `toISOString`.  [The docs say](https://momentjs.com/docs/#/displaying/as-iso-string/):

> Note that .toISOString() always returns a timestamp in UTC, even if the moment in question is in local mode.

**Comment by icambron** [comment]
@ashsearle is correct. 2017-09-30T14:00:00.000Z is 2017-10-01T00:00:00 in your local time.
