### ISSUE TITLE
Android Bug only with Chrome

### ISSUE THREAD

**Issue by wayofthefuture** [moment/moment#4139]
I'm not a pro with this stuff, but this line of code yields different results. I am using MomentJS 2.18.1.

Chrome, Safari, Internet Explorer, pretty much all browsers (desktop and ios mobile):
> moment(Date.now()).format('HH:mm')
> returns 14:27

Chrome on Android Mobile:
> moment(Date.now()).format('HH:mm')
> returns 20:27

Opera Mini on Android Mobile:
> moment(Date.now()).format('HH:mm')
> returns 14:27

Something about mobile chrome is losing the offset. However, Opera Mini on the same phone respects the offset. I have no idea what is causing this.

**Comment by icambron** [comment]
Can you check what `new Date().getTimezoneOffset()` returns on that platform?

**Comment by wayofthefuture** [comment]
A restart of the phone fixed the problem. My apologies for your time.
