### ISSUE TITLE
noise in duration ISO string 

### ISSUE THREAD

**Issue by pabigot** [moment/moment#4145]
**Description of the Issue and Steps to Reproduce:**

ISO8601 representation of durations includes floating point noise in some cases even though the duration value is clearly integral milliseconds.

    'use strict';
    const moment = require('moment');
    let dur = moment.duration(123);
    console.log(+dur);
    console.log(dur.toISOString());
    dur = moment.duration(123456789);
    console.log(+dur);
    console.log(dur.toISOString());
    
    console.log((new Date()).toString())
    console.log((new Date()).toLocaleString())
    console.log((new Date()).getTimezoneOffset())
    console.log(moment.version);

produces:

    123
    PT0.123S
    123456789
    PT34H17M36.78900000000431S
    Tue Aug 29 2017 06:53:18 GMT-0500 (CDT)
    2017-8-29 06:53:18
    300
    2.18.1

Note the second duration has trailing `00000000431` noise in the seconds block.

**Environment:**

Node.js 4.5.0, 6.9.5, and 8.4.0 on Ubuntu

**Comment by maggiepint** [comment]
Closing in favor of #4146
