### ISSUE TITLE
days diff wrong

### ISSUE THREAD

**Issue by mariusa** [moment/moment#4147]
**Description of the Issue and Steps to Reproduce:**
Today, 2017-08-30 10AM, this gives
moment('2017-08-30').diff(moment(), 'days')
0
which is correct.

But this gives
moment('2017-08-31').diff(moment(), 'days')
0
which is wrong, should have been 1.

**Environment:**
Chrome

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
tried different timezones, same issue

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

VM222:1 Wed Aug 30 2017 10:57:57 GMT+0300 (EEST)
VM222:2 8/30/2017, 10:57:57 AM
VM222:3 -180
VM222:4 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36
VM222:5 2.18.1
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by yashcr07** [comment]
This is happening because `moment('2017-08-31')` equals `2017-31-08 00:00`.
so when you make a diff it is 14 hrs which is less than 24 hrs which gives you 0.
you can do `moment('2017-08-31').endOf('day').diff(moment(), 'days')` which will give you the desired result.

**Comment by mariusa** [comment]
Thanks yash! That makes sense.
