### ISSUE TITLE
calendar bug report

### ISSUE THREAD

**Issue by willin** [moment/moment#4149]
**Description of the Issue and Steps to Reproduce:**

*Please include the values of all variables used.*

**Environment:**

*Examples: Chrome 60 on OSX,  Node.JS 8.4.0 on OSX

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on Asia/Shanghai
* The time and date at which the code was run 2017-09-07

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
// today 2017-08-31
console.log(moment('2017-09-07').calendar())
// 09/07/2017
// it's Saturday next week indeed
console.log(moment('2017-09-02').calendar())
// 下星期六00:00 
// which means Saturday next week, but it's Saturday this week indeed
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

source code:

```js
calendar : {
  sameDay : '[Today at] LT',  // today, right
  nextDay : '[Tomorrow at] LT', // tomorrow, right
  nextWeek : 'dddd [at] LT', // this week, wrong
  lastDay : '[Yesterday at] LT', // yesterday, right
  lastWeek : '[Last] dddd [at] LT', // this week, wrong
  sameElse : 'L' // have no idea about this
}
```

today is 2017-08-31, in chinese:

- 2017-08-28 ~ 2017-09-03 from Monday to Sunday are all in this week.
- 2017-08-21 ~ 2017-08-27 are last XXXday
- 2017-09-04 ~ 2017-09-10 are next XXXday

**Comment by icambron** [comment]
This seems similar to #4097
