### ISSUE TITLE
ERROR TypeError: a.toLowerCase is not a function at Xa (VM581 moment.min.js:6) 

### ISSUE THREAD

**Issue by tomokohn** [moment/moment#4158]
this error comes up when using fullcalendar that uses moment js.

ERROR TypeError: a.toLowerCase is not a function at Xa (VM581 moment.min.js:6) 
 at Ya (VM581 moment.min.js:6)
    at Function.bb [as localeData] (VM581 moment.min.js:6)
    at getMomentLocaleData

*Please include the values of all variables used.*

**Environment:**

Chrome 60 on windows 10 X64.

**Other information that may be helpful:**
using fullcalendar.js

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString()):
Wed Sep 06 2017 10:04:13 GMT+0300 (Eastern Europe Daylight Time)
console.log((new Date()).toLocaleString()):
9/6/2017, 10:08:43 AM
console.log( (new Date()).getTimezoneOffset()):
-180
console.log( navigator.userAgent):
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
console.log(moment.version):
2.18.1
```

thanks

**Comment by zxiaohong** [comment]
@tomokohn  I come with the same problem.But I can't find where the error came from.can you tell me your scene?
