### ISSUE TITLE
Spanish Language in US locale, date formatting incorrect

### ISSUE THREAD

**Issue by absessive** [moment/moment#4162]
**Description of the Issue and Steps to Reproduce:**
I have a long date `Nov 01, 2015` with the date format `MMM D, YYYY`. This works for the `en `locale (which is English US). However when switching to `es`, how do I get this to still work? The localized date is now `nov 01, 2015` with the same date format `MMM D, YYYY`

```js
moment.locale('en')
-> "en"
moment('Nov 01, 2015', 'MMM D, YYYY', true).isValid()
-> true
moment('nov 01, 2015', 'MMM D, YYYY', true).isValid()
-> false

```
The Spanish date returns as an `Invalid Date`

**Comment by icambron** [comment]
I don't understand the question. Your code doesn't switch to `es`; it provides a Spanish-formatted date to a parser that expects English because you specifically configured Moment to be English. What are you trying to do?

**Comment by marwahaha** [comment]
Huh. Those two are valid in `en` and in `es`, but not in `es-us`.

**Comment by marwahaha** [comment]
My guess is it's the same as 
https://github.com/moment/moment/issues/3629

which was nicely solved 
https://github.com/moment/moment/pull/3894

Both `es` and `es-do` implement a regex that allows for parsing without a trailing dot. 

@bustta do you have thoughts?

**Comment by marwahaha** [comment]
I've added https://github.com/moment/moment/pull/4377 and added a test.

@absessive - does this fix your issue?
