### ISSUE TITLE
Vulnerable Regular Expression

### ISSUE THREAD

**Issue by cristianstaicu** [moment/moment#4163]
The following regular expression used to parse dates specified as strings is vulnerable to ReDoS:
```js
/[0-9]*['a-z\u00A0-\u05FF\u0700-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+|[\u0600-\u06FF\/]+(\s*?[\u0600-\u06FF]+){1,2}/i
```
The slowdown is moderately low: for 50.000 characters around 2 seconds matching time. However, I would still suggest one of the following: 
- remove the regex,
- anchor the regex,
- limit the number of characters that can be matched by the repetition,
- limit the input size.

If needed, I can provide an actual example showing the slowdown.

**Comment by mj1856** [comment]
For clarification, this is in the `matchWord` regex, in `/src/lib/parse/regex.js` [here](https://github.com/moment/moment/blob/29afed6631e596fe9b3ff6c61ddc55eee18810e6/src/lib/parse/regex.js#L23).

[Here is a railroad diagram of the regular expression](http://bit.ly/2yAKjq7).  From this we can see that the grouping with repetition is related to parsing Arabic characters.   It would be helpful if someone who understands both regular expressions and Arabic language could take a crack at this.

[An overview of ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) is also helpful.

**Comment by hamiltondanielb** [comment]
Ill take this is no one has already started

**Comment by icambron** [comment]
@hamiltondanielb all yours :)

**Comment by Drag0s** [comment]
>@cristianstaicu 
>If needed, I can provide an actual example showing the slowdown.

I'd like to see the some example if it's possible :)

**Comment by cristianstaicu** [comment]
@Drag0s sent it on your private email.

**Comment by mattgrande** [comment]
FYI, this was added to NSP (see [here](https://nodesecurity.io/advisories/532)), so this is probably going to start breaking people's builds soon.

@hamiltondanielb - Did you get anywhere looking into this?

**Comment by jonsharratt** [comment]
Just had our build break 👯

**Comment by dskrvk** [comment]
It's sad that the issue had to become public before it was fixed. Issue opened on Sep 8, NSP advisory published today. @cristianstaicu perhaps you should've reminded the maintainers about the disclosure deadline to give this some momentum.

**Comment by rupesh1** [comment]
@mattgrande there is a meta-ness to this: turns out the version of nsp we were pinned to (2.8.1) depends on moment (via joi) so it was reporting a vulnerability on its own dependency:

<img width="601" alt="1__bash" src="https://user-images.githubusercontent.com/3313870/33283649-60456bd8-d3a4-11e7-8863-02730c10a830.png">


Upgrading to nsp 3.1.0, resolved this because the dependency is no longer there - so beware of that if you don't directly depend on moment.

**Comment by bit7** [comment]
Is there a fix for this yet?

**Comment by JoanYin** [comment]
Please advise any fix available?

**Comment by fluxsauce** [comment]
No fix has been published yet.

Please, if you're interested in getting updates from the maintainers, subscribe to notifications for updates to this issue by clicking the "Subscribe" in the right-hand column.

**Comment by westy92** [comment]
To add an `nsp` exception for this, add a `.nsp` file:
```
{
  "exceptions": [
     "https://nodesecurity.io/advisories/532"
  ]
}
```

**Comment by Dexterslab** [comment]
Hi @westy92. I have the following code. 
var tasksMethods = require('gulpfile-ninecms');
gulp.task('nsp', tasksMethods.nsp);
Its not picking up the .nsprc file exception. It keeps giving me the vulnerability error for moment.  
I added the file on root of the project. Is there anything I am missing to do?

**Comment by westy92** [comment]
@Dexterslab we're using [`gulp-nsp`](https://github.com/nodesecurity/gulp-nsp), which works fine when the `.nsprc` is in the project directory (same level as `package.json`).  Maybe try using `gulp-nsp` directly?

**Comment by nicosommi** [comment]
@cristianstaicu @mattgrande is this happening in Luxon as well?

**Comment by davidnormo** [comment]
We'd appreciate it the fix for this can be expedited, now that it has been logged in nsp it is failing our builds.

**Comment by jamacon36** [comment]
Bump for fix

**Comment by flovilmart** [comment]
Can I suggest the maintainers to lock this convo? 
For everyone waiting for a fix, just hit the subscribe button, and you’ll be notified.

If anyone want to undertake the fix, feel free to open a PR.

**Comment by UziTech** [comment]
There is a PR for this already https://github.com/moment/moment/pull/4326

**Comment by westy92** [comment]
Does someone need to notify `nsp` this has been patched? https://nodesecurity.io/advisories/532

**Comment by marwahaha** [comment]
This has been fixed in version 2.19.3 . Please update accordingly.

I'm not sure how to notify NSP -- @cristianstaicu could you or others help here?

**Comment by kirkstrobeck** [comment]
cc @evilpacket @lukekarrys @nlf @wraithgar

**Comment by mdholloway** [comment]
I emailed report@nodesecurity.io:

> Hello,
> 
> The currently outstanding moment.js vulnerability (https://nodesecurity.io/advisories/532) was [recently patched](https://github.com/moment/moment/issues/4163) and the fix [released](https://www.npmjs.com/package/moment) in v.2.19.3.
> 
> What's the process for reporting status updates on advisories?  This email address is the best avenue I could find.  
> 
> Thanks!

**Comment by mdholloway** [comment]
Just got a reply that the NSP DB should be updated with 2.19.3 as the fixed version.

Verified on my end that 2.19.3 no longer alerts.
