### ISSUE TITLE
Wrong day difference in leap-years

### ISSUE THREAD

**Issue by michaelfeinbier** [moment/moment#4165]
Hey team/community,

**Description of the Issue and Steps to Reproduce:**
the year 2016 was a leap year so it contained 366 days instead of 365. So an according call to something like this:
```js
let start = moment('2016-01-01')
    end   = moment('2016-12-31');

let diff = end.diff(start, 'days');
```
should return 366 as result. But actually it returns 365 [Here is a codepen snippet to reproduce the behaviour](https://codepen.io/denkweite/pen/Vzojzy).
I think it's a bug, but maybe I just did something wrong?

**update**
You can reproduce this bug with this test
```js
test('leap year difference', function(assert) {
    assert.equal(moment([2016, 11, 31]).diff(moment([2016, 0, 1]), 'days'), 366, 'leap year contains 366 days');
    assert.equal(moment([2016, 1, 29]).diff(moment([2016, 1, 1]), 'days'), 29, 'february in leap year contains 29 days');
});
```

*Please include the values of all variables used.*

**Environment:**
I use moment in an browser-only-environment (build with webpack)

Some other useful information:
```js
"Sat Sep 09 2017 10:16:47 GMT+0200 (CEST)"
"9.9.2017, 10:16:47"
-120
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
"2.18.1"
```

**Comment by icambron** [comment]
That isn't right. Remember that `moment('2016-12-31')` is the *beginning* of Dec 31, not the end. So there are in fact 365 days there. You can also see this by switching to 2015 and seeing that there are 364 days, i.e. it has nothing to do with leap years.

```js
let start = moment('2015-01-01')
    end   = moment('2015-12-31');

let diff = end.diff(start, 'days');
```
