### ISSUE TITLE
Format with year starting with 000 is 2000 based.

### ISSUE THREAD

**Issue by jrm2k6** [moment/moment#4167]
**Description of the Issue and Steps to Reproduce:**

When I run: ```moment('11/11/0005').format('dddd, MMMM Do, YYYY')```
I am expecting to see: "Day, Month 0005" but instead I get "Friday, November 11th, 2005".
It works fine with ```moment('11/11/0115').format('dddd, MMMM Do, YYYY')``` for example.
Anything I am doing wrong?

```
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
Sat Sep 09 2017 15:50:11 GMT-0700 (PDT)
9/9/2017, 3:50:11 PM
420
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
2.18.1
```

**Comment by ashsearle** [comment]
That date format doesn't match an ISO 8601 or RFC 2822 format, so is actually being parsed by the browser via`new Date(string)`.

It's hard to tell what format you're expecting there: do you want day first, or month first?  Are you zero-padding date and/or month?

Based on your timezone, I guess you're wanting US format, so you can pass the date format explicitly to the moment constructor as `MM/dd/yyyy`:
```js
moment('11/11/0005', 'MM/dd/yyyy').format('dddd, MMMM Do, YYYY')
```

**Comment by jrm2k6** [comment]
@ashsearle Thanks for the answer. Yes, I let moment decides how to interpret the date I was passing as a string. I will make sure to be more explicit! 
Thanks
