### ISSUE TITLE
No way to import Moment that makes both SystemJS and Rollup happy

### ISSUE THREAD

**Issue by benelliott** [moment/moment#4170]
**Description of the Issue and Steps to Reproduce:**

A very common way to build Angular (2+) applications is to use Rollup or Webpack for production builds and SystemJS for unit testing. However each of these build tools prefers a different way to import Moment.

For SystemJS, one must use

```
import * as moment from 'moment';
```

but this gives the error `Cannot call a namespace` under Rollup. Rollup will instead work with 

```
import moment from 'moment';
```

but this results in `undefined` imports when using SystemJS.

This issue has been brought up before in https://github.com/moment/moment/issues/3748 and [on StackOverflow](https://stackoverflow.com/questions/39519823/using-rollup-for-angular-2s-aot-compiler-and-importing-moment-js) but nobody has found a solution, only workarounds (like using a script to rewrite these imports between builds).

**Environment:**

Build time issue, Windows 10, NodeJS 7.10.0

**Other information that may be helpful:**
Using TypeScript 2.5.2 with Angular 4.3.6, SystemJS 0.20.18, Rollup 0.49.3.

**Comment by icambron** [comment]
> A very common way to build Angular (2+) applications is to use Rollup or Webpack for production builds and SystemJS for unit testing.

OK, how should Moment be different such that this problem goes away? Like, how do other libraries make this work?

**Comment by tqc** [comment]
Would adding a named export work? `import {moment} from ‘moment’;` should be less ambiguous than the various ways default exports are handled. 

In my experience named and default exports coexist quite well, though proper cross platform regression testing might be tricky.

**Comment by sjmueller** [comment]
Well that's discouraging @tqc.

A little more info, I just cleared my `node_modules` and `package-lock`, and did a fresh `npm i` with `"moment": "tqc/moment#no-dynamic-import"` in package.json. This is the error I get:

```
Failed to load bundle...
(TransformError: ../node_modules/moment/moment.js: require() must have a single string literal argument (null))
```

**Comment by tqc** [comment]
Turns out that didn't quite work - at least in the test system, the default export is transpiling to something very different when there is also a named export. 

Putting the named file in a separate file at least doesn't break all the tests, but of course that won't help with any preexisting default imports.

**Comment by kmmbvnr** [comment]
Is it happens b/c moment.js lacks the case in module declaration section?

Compare  with what the webpack does:

```javascript
if(typeof exports === 'object' && typeof module === 'object')
  module.exports = factory();
else if(typeof define === 'function' && define.amd)
  define([], factory);
else if(typeof exports === 'object')
  exports["mdc"] = factory();
else
  root["mdc"] = factory();
})(this, function() {
```

And what `moment.js` has:

```javascript
;(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
    typeof define === 'function' && define.amd ? define(factory) :
    global.moment = factory()
```

We essentially miss the case with `exports["moment"] = factory();`

Here is [the reference ](https://github.com/jwagner/smartcrop.js/blob/master/smartcrop.js#L543)to another vanilla js package, that has `exports` declaration.

**Comment by ichernev** [comment]
@benelliott can you please check if @kmmbvnr suggestion works for this setup?

**Comment by gkjohnson** [comment]
Is this not technically a problem with rollup or systemjs? Both of those statements are valid in the browser but yield different imported objects.

**Comment by marwahaha** [comment]
Is this still an issue with Rollup or SystemJS?

**Comment by oscarvaldes** [comment]
Using latest version of rollup this seems to have been resolved.

**Comment by oscarvaldes** [comment]
#https://github.com/ng-packagr/ng-packagr/issues/217 helping others who may run into this from older ngpackagr versions :)
