### ISSUE TITLE
Wrong locales when using in different files

### ISSUE THREAD

**Issue by bloodcarter** [moment/moment#4171]
I cannot explain this weird behaviour. Consider following files:
```
//file1.js
var Moment = require('moment');
Moment.locale('ru-RU');
const MomentRange = require('moment-range');
const moment = MomentRange.extendMoment(Moment);

//file2.js
var Moment = require('moment-timezone');
Moment.locale('en-US');
const MomentRange = require('moment-range');
const moment = MomentRange.extendMoment(Moment);

//somewhere later in the same file
let m = moment();
m.locale(); // 'ru'  - unexpected behaviour!!!!!!

```
If all moment instances are local, the subsequent locale calls shouldn't change locales of the existing library instances, right? And if not, then how do I maintain several different locales across multiple files?

Momentjs version is 2.18.1

**Comment by icambron** [comment]
I think this probably has something to do with `moment-range` and how it plugged into Moment. I assume removing that fixes it?

**Comment by marwahaha** [comment]
Closing-  @bloodcarter please re-open if this is still a problem.
