### ISSUE TITLE
.fromNow() in days

### ISSUE THREAD

**Issue by Ceceu** [moment/moment#4172]
Hello,

Is there possible to use .fromNow() function with a specific date and get only a numeric answer in days?
Something like:

`date = '2017-09-10' // yyyy-MM-dd
days = moment(data).fromNow() // days should be equals the amount of the days until now`

Thanks.

**Comment by icambron** [comment]
`fromNow` doesn't do that, no.

But it sounds like maybe you just want `diff()`?

```js
moment().diff( '2017-09-10', 'days'); //=> 4
```

**Comment by bminer** [comment]
I've used something like this in the past:

```javascript
moment({hours: 0}).diff('2018-11-07', 'days'); // => 1
moment({hours: 0}).diff('2018-11-08', 'days'); // => 0
moment({hours: 0}).diff('2018-11-09', 'days'); // => -1
```

If you don't set `{hours: 0}`, you might get strange results.
