### ISSUE TITLE
DST bugs.

### ISSUE THREAD

**Issue by hifall** [moment/moment#4178]
This is nothing too specific, just a question on DST issues in a more generic sense: it seems to me that moment/moment-timezone have some long-lasting issues related to DST, like #4152, #3132, [#327](https://github.com/moment/moment-timezone/issues/327), #2749, etc.

I wonder if fixing these is of high priority on your list?

Great great projects, BTW.

**Comment by icambron** [comment]
Yeah, we'd love to get fixes for those. But no, it's not anyone on the team's priority. So it would have to come as a PR.

**Comment by gsidler** [comment]
A PR to fix DST issues has been submitted here: https://github.com/moment/moment/pull/4164 It would be great if someone could have a look and merge. We use this fix in a widely used calendar application and it works well for us.
