### ISSUE TITLE
Strict parsing of date string including zz is failng

### ISSUE THREAD

**Issue by gajus** [moment/moment#4179]
```js
console.log(moment('Sunday 17 September 201709.00 BST', 'dddd D MMMM YYYYHH.mm zz', true).format());

```

Expect this to produce ISO date. Instead getting "Invalid date". Tried `moment` and `moment-timezone`.

**Comment by gajus** [comment]
Looks like anything using strict parsing that includes timezone data is failing, e.g.

```js
console.log(moment.tz('Sunday 17 September 201708.00', 'ddd D MMMM YYYYHH.mm', true, 'Europe/London').isValid());

```

**Comment by icambron** [comment]
`zz` isn't supported as a parsing token and doesn't appear in the documentation for it. It's supported as a *formatting* token, though it's deprecated in Moment proper and really ought to have been removed in 2.0. (Formatting ought to still work with `moment-timezone`).

The reason for not supporting it as a parsing token is that they're sometimes ambiguous. For example, BST is also Bangladesh Standard Time or even Bougainville Standard Time. There's just no way to for Moment to know, it's not really reasonable for it to guess.

**Comment by gajus** [comment]
I see. Thank you for the explanation.
