### ISSUE TITLE
endOf/startOf doesn't work with predefined Date Objects

### ISSUE THREAD

**Issue by bastiankemmer** [moment/moment#4180]
**Description of the Issue and Steps to Reproduce:**
I am trying to create a moment object from a Javascript Date Object and then set it to the end of the day.
While
`moment().endOf("day")`
does work, 
`moment(new Date()).endOf("day")`
doesn't work.

**Environment:**
Chrome Version 60.0.3112.113 (Offizieller Build) (64-Bit) on a Mac OSX

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
Tue Sep 19 2017 08:00:08 GMT+0200 (CEST)
19.9.2017, 08:00:08
-120
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
2.18.1```

**Comment by bastiankemmer** [comment]
It does work on server side with node.js. It could be a problem with my set up on Chrome and not with moment js.

**Comment by guyellis** [comment]
@bastiankemmer did you get to the bottom of this? I'm hitting this problem in a test running on Node 8.7 but so far it's been impossible to isolate and reproduce.

**Comment by bastiankemmer** [comment]
I could not reproduce the problem and I stopped trying to do so. For me it seemed like a Bug, but I was confused, because a colleague said on his PC it does work fine. Maybe I can try to reproduce this problem again.
Perhaps i can check this afternoon.
