### ISSUE TITLE
Wrong month when using moment().set()

### ISSUE THREAD

**Issue by stefdelec** [moment/moment#4181]
In MomentJs doc it is written : 

> M MM 1..12 Month number

However, if I do :
```
    const b = moment()
      .set({
        'year': 2018,
        M: 9
      });
    console.log(b.format('MM'));
    // output 10
--------------------------------------------------------
    const b = moment()
      .set({
        'year': 2018,
        M: moment().format('MM')
      });
    console.log(b.format('MM'));
    // expect 9 output 10
```

Wed Sep 20 2017 12:00:13 GMT+0200 (Paris, Madrid (heure d’été))
VM134:2 20/09/2017 à 12:00:13
VM134:3 -120
VM134:4 Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by ashsearle** [comment]
There are separate sections of the documentation for constructing a moment using [`moment(String, String)`](https://momentjs.com/docs/#/parsing/string-format/) vs [`moment(Object}`](https://momentjs.com/docs/#/parsing/object/).  You're constructing a moment using an `Object`, so this documentation applies:

> Note that like moment(Array) and new Date(year, month, date), months are 0 indexed.

Do you think the documentation needs to change to draw more attention to the fact months are 0-based in some cases and 1-based in others?

**Comment by stefdelec** [comment]
I don't know. It is somehow counter-intertuive.

Are years in a array? Then 0 would be the year 0 in the array? What about
-1? Do you see my point?

Perhaps I am misunderstanding something. In that case yes, a section about
set() in moment's doc is worth it.

**Comment by icambron** [comment]
Wait, no, they are always 0-indexed when specifying months to Moment. The problem is that you're passing the *formatted* month into the month position:

```js
M: moment().format('MM')
```

You want to use `moment().month()` there, which will give you the 0-indexed month. `format()` returns a string for displaying to a user, which is obviously going to be 1-indexed

**Comment by icambron** [comment]
Also, hey @ashsearle, email me at the email address on my GH profile. Thanks!
