### ISSUE TITLE
Not correct parsing for Portoguese locale '20 de agosto de 2017' becomes '2017-09-20'

### ISSUE THREAD

**Issue by bitliner** [moment/moment#4185]
**Description of the Issue and Steps to Reproduce:**

`require('moment')("20 de agosto de 2017" ,'DD de MMMM de YYYY')`
returns 
`moment("2017-09-20T00:00:00.000")`

Instead, I expect `moment("2017-08-20T00:00:00.000")`

**Environment:**

moment: v2.18
nodejs: v8.2.1

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on -> CEST 2017
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString()) // Mon Sep 25 2017 01:34:40 GMT+0200 (CEST)
console.log((new Date()).toLocaleString()) // 
console.log( (new Date()).getTimezoneOffset()) // 2017-9-25 01:34:57
console.log( navigator.userAgent) // undefined
console.log(moment.version) // 2.18.1
```

**Comment by xehpuk** [comment]
> To escape characters in format strings, you can wrap the characters in square brackets.

Try this: `('20 de agosto de 2017' , 'DD [de] MMMM [de] YYYY')`

**Comment by icambron** [comment]
Yeah, you need to escape the literals.
