### ISSUE TITLE
Include .js.map file for production debugging

### ISSUE THREAD

**Issue by CJDennis** [moment/moment#4186]
Please include a .js.map file for each minified .js file. This allows the minified code to be debugged by mapping it back to the original source file.

**Comment by ArwaLokhandwala** [comment]
@marwahaha I am first time contributor, I would like to contribute to this issue. Can you help?

**Comment by marwahaha** [comment]
I'm not sure how to do this, but I would read about Source Map files.
https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/
https://raygun.com/blog/getting-started-with-javascript-source-maps/

**Comment by ArwaLokhandwala** [comment]
Ok cool, even I’ll look into it👍🏻And raise a PR!!

**Comment by akanshgulati** [comment]
@marwahaha Please review the PR.

**Comment by marwahaha** [comment]
fixed in https://github.com/moment/moment/commit/4dfe59b576e5a67597fa7a95934fa9f123f62e1b
