### ISSUE TITLE
Swiss times formatted wrongly

### ISSUE THREAD

**Issue by hardcodet** [moment/moment#4189]
FYI: Just noticed when checking out the project that our time (German, Swiss) is misformatted. For 2pm, it shows `14.00` (single dot as separator) instead of `14:00` .

**Comment by mattgrande** [comment]
Looks like CLDR agrees with what @hardcodet is saying: http://demo.icu-project.org/icu-bin/locexp?d_=en&_=gsw_CH

**Comment by joelmheim** [comment]
Am I right in thinking this would be as simple as going into src/locale/de-ch.js and fixing all the relevant cases plus the tests? If this is the case, I'm happy to provide a quick PR for this. 

Let me know if there is something else I need to think about. Been a while since I've contributed.

**Comment by mattgrande** [comment]
I think that's it, yes. Been awhile for me as well though :)

Also, check the Contribution guide: https://github.com/moment/moment/blob/develop/CONTRIBUTING.md#read-before-submitting-pull-requests

**Comment by joelmheim** [comment]
Of course.
