### ISSUE TITLE
Invalid Date with week ISO format

### ISSUE THREAD

**Issue by nkint** [moment/moment#4190]
**Description of the Issue and Steps to Reproduce:**
Transform a date to YYYY-WW and back is not coherent: same sting produce a `Invalid Date`

```
console.log( moment('2016-01-01').format('YYYY-WW') ) // "2016-53"
console.log( moment('2016-53', 'YYYY-WW').toDate() ) // "Invalid date"
```

*Please include the values of all variables used.*
no addition variables

**Environment:**
Version 61.0.3163.91 (Official Build) (64-bit) on OSX
Running from Italy (Europe)

**Comment by ashsearle** [comment]
You're mixing ISO (`WW`) and non-ISO (`YYYY`) formats, and have produced an invalid year-week combination (2016 doesn't have 53 ISO weeks.).

If you use the ISO Year format (`GGGG`) things work as you want:

```js
console.log( moment('2016-01-01').format('GGGG-WW') ) // "2015-53"
console.log( moment('2015-53', 'GGGG-WW').toDate() ) // Mon Dec 28 2015 ... (1st day of ISO week)
```

**Comment by nkint** [comment]
thanks!

**Comment by millun** [comment]
expect(moment('2015536', ["YYYYWWE", moment.ISO_8601]).format('YYYYWWE')).toEqual('2015536');

fails because it gets '201**6**536' (an invalid ISO8601 date).
i haven't been able to find a workaround for this.
