### ISSUE TITLE
`moment.duration(65, 'days').days();` gives 4

### ISSUE THREAD

**Issue by nocksock** [moment/moment#4191]
I'm not sure what's going on, but I've set up a very simple example. Basically the one in the title:

Here's a failing test: https://jsfiddle.net/yp1Lebnh/1/

**Comment by kkopec** [comment]
It works properly according to the documentation:
>As with the other getters for durations, `moment.duration().days()` gets the days (0 - 30).
`moment.duration().asDays()` gets the length of the duration in days.

**Comment by nocksock** [comment]
Wow. Okay, I didn't expect it to be **THAT** smart. :D
