### ISSUE TITLE
Difference of moments: Docs could be improved

### ISSUE THREAD

**Issue by jtheisen** [moment/moment#4192]
I just tried to figure out how to get the difference between two moments. Naturally, I assumed that there is some function so that `x.diff_fun(y)` is a `duration`.

Maybe I'm spoiled, but in .NET `x - y` is a `TimeSpan` when `x` and `y` are `DateTime`s.

I think there ought to be such a function in `moment` as well, or at least the docs should talk about an idiom at the discussion of `duration` or that of the `diff` and `subtract` functions, such as

```
moment.duration(x.diff(y))
```

I needed SO to figure that this is the current idiom.

**Comment by marwahaha** [comment]
Hi,

Do you have a recommended set of phrases or sentences that would have cleared this up for you in the docs?

**Comment by icambron** [comment]
Would accept a doc PR

**Comment by andyfry01** [comment]
Hello, 

Looking at the docs for [durations](https://github.com/moment/momentjs.com/tree/master/docs/moment/08-durations), [display](https://github.com/moment/momentjs.com/tree/master/docs/moment/04-displaying), and [diff](https://github.com/moment/momentjs.com/blob/master/docs/moment/04-displaying/07-difference.md), it doesn't seem like a PR has been either made or merged for this yet. I'd be glad to make a small contribution if you're still interested in a PR. 

I assume opening an issue in the [docs repo](https://github.com/moment/momentjs.com) and making a PR there would be the best way to go, right?

Thanks!

**Comment by icambron** [comment]
@andyfry01 yup!
