### ISSUE TITLE
CS locale 'l' longDateFormat is wrong

### ISSUE THREAD

**Issue by lukesahula** [moment/moment#4198]
There should be no white spaces between the numbers in the 'l' longDateFormat.
D.M.YYYY instead of D. M. YYYY,

**Comment by marwahaha** [comment]
@lukesahula is this true for other formats too?
```
moment().format('L')
"19/12/2017"
moment().format('LL')
"19. prosinec 2017"
moment().format('LLL')
"19. prosinec 2017 3:20"
moment().format('LLLL')
"úterý 19. prosinec 2017 3:20"
moment().format('l')
"19. 12. 2017"
moment().format('ll')
"19. pro 2017"
moment().format('lll')
"19. pro 2017 3:20"
moment().format('llll')
"út 19. pro 2017 3:20"
```

@petrbela any thoughts ?

**Comment by petrbela** [comment]
@lukesahula See https://github.com/moment/moment/pull/2016#issuecomment-187670054

According to the norm [ČSN 01 6910](http://prirucka.ujc.cas.cz/?id=810), it can be either 23. 2. 2016 (with spaces) or 23.02.2016 (with padded 0 without spaces). `format('l')` produces the former, and `format('L')` the latter.

**Comment by marwahaha** [comment]
Since both options are available, I will close this.
