### ISSUE TITLE
Moment JS time format issue on initialization

### ISSUE THREAD

**Issue by karthickshanmugam0689** [moment/moment#4201]
Hi Moment JS Team,

We are very happy with the working of moment js. Only thing is we have  an issue on date parsing on initialization.

When we have the command as follows, we get an issue on parsing

console.log(moment('2005/05/01',"DD.MM.YYYY").format("DD.MM.YYYY"));

Here the output obtained is:

20.05.2005

I know that the date given here and the format is wrong. So either the return value can say that the date is invalid as the format doesn't match or it could have parsed and given the output in a perfect way such that the output is 01.05.2005. But it produced a wrong result which is 20.05.2005 which is no where related to the date input given.

Environment : Browser Version : Chrome v56. OS : Windows 10

Timezone setting of the machine : Central European Summer Time (CEST).
Date and time : 04th October 2017 10:35 AM CEST

**Comment by karthickshanmugam0689** [comment]
Hi Team,

Will this issue be resolved any sooner. We are waiting for the fix very eagerly.

Thanks and Regards,
Karthick Shanmugam

**Comment by ashsearle** [comment]
Does [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/) do what you want?
```js
console.log(moment('2005/05/01',"DD.MM.YYYY", true).format("DD.MM.YYYY"));
// Invalid date
```

**Comment by apedicdev** [comment]
same on Magento 2
`Moment {_isAMomentObject: true, _i: "2017-08-01 00:00:00", _f: "DD/MM/YYYY", _isUTC: false, _pf: {…}, …}
_a
:
(7) [2008, 16, 20, 0, 0, 0, 0]
_d
:
Invalid Date {}
_f
:
"DD/MM/YYYY"
_i
:
"2017-08-01 00:00:00"`

**Comment by karthickshanmugam0689** [comment]
@ashsearle  I tried to using strict mode but i got the below result on format output

20.05.0005

Still doesnt work. :(

**Comment by karthickshanmugam0689** [comment]
@ashsearle Oops sorry it works with strict mode... If I give strict, then it says invalid date..... Thanks for the response

**Comment by icambron** [comment]
Closing: using strict mode is the answer here.
