### ISSUE TITLE
Set Local but timezone doesn't change

### ISSUE THREAD

**Issue by opjlmi** [moment/moment#4202]
Hi
I use `moment.locale('zh-tw')` to set default with +8 timezone.
But If I use `moment().format('ZZ')`, it still show `+0000`.
But `.valueOf()` is correct.....

**Comment by EthanChouTW** [comment]
hey hi did you figure out what't going on?  facing the same issue here

**Comment by opjlmi** [comment]
@EthanChouTW Yes, that because you need to install [Moment-Timezone](http://momentjs.com/timezone/docs/) package.
And use `moment.tz.setDefault("Asia/Taipei")` to set the default timezone.
