### ISSUE TITLE
Can standard locales work when using ES6 directly?

### ISSUE THREAD

**Issue by tqc** [moment/moment#4205]
Related to #4042, #4170, #4187, #4126

The files in moment/locale all start with `require(‘../moment’)`, which resolves to the ES5 transpiled version. Unfortunately, that has a different locale store to the ES6 version.

You can use `import “moment/src/locale/...”`, but that isn’t ideal when the version of moment used can depend on the bundler and package.json rather than user code. 

Replacing ‘..moment’ with ‘moment’ in the locale header should work in most cases, but might break systems that translate require into loading a url.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

I am still interested in fixes that don't break existing users of Moment.js .
