### ISSUE TITLE
Reset language after loading all language strings.

### ISSUE THREAD

**Issue by manastungare** [moment/moment#421]
Currently, if I include the lang-all.min.js file, it sets the current language to the last one in that file. There is no way to simply load all available language strings, yet retain the default language. At the very least, the last line of that file should set:

moment.lang(window.navigator.language);

to use the best guess instead of whatever happens to be last in that list.

**Comment by alexg313** [comment]
I've run into this issue after pulling momentJS from a CDN. 

See http://stackoverflow.com/questions/30336964/momentjs-default-locale-is-zh-tw-and-cant-seem-to-overwrite-it
