### ISSUE TITLE
No way to specify Year character in Japanese locale without affecting all locale results (hard-coding in format string) or checking for locale.

### ISSUE THREAD

**Issue by Panoplos** [moment/moment#4211]
**Description of the Issue and Steps to Reproduce:**
```es6
moment.locale('ja')
moment().format('LL')
```
Will output '2017年10月6日', as expected, but how do I specify just the Year and Month (i.e. '2017年10月') without having to hard-code a check for Japanese?

I see that calling `moment().format('MMM')` outputs '10月' (with the month character appended), but `YYYYY` does not result in '2017年', so `YYYYYMMM` outputs ' 0201710月'.

**Environment:**
All

Output:

Mon Oct 09 2017 17:01:04 GMT+0900 (Japan Standard Time)
VM10714:2 10/9/2017, 5:01:04 PM
VM10714:3 -540
VM10714:4 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3230.0 Safari/537.36
VM10714:5 2.18.1

**Comment by Panoplos** [comment]
No update on this?

**Comment by icambron** [comment]
Moment doesn't provide a year/month formatting option that knows how to do that. It's a valid feature request but we're unlikely to add another format to all of the locales.

**Comment by Panoplos** [comment]
Considering that all forms of Chinese also require this (yeah, the language utilised by most of the people in this world), it seems odd that it would not be supported.
