### ISSUE TITLE
How to not import locales

### ISSUE THREAD

**Issue by sneakyfildy** [moment/moment#4217]
Subj.
How do I escape adding locales in my bundle?

**Comment by sneakyfildy** [comment]
https://github.com/moment/moment/issues/4025

alright.
what a mess I must say...

**Comment by nkoterba** [comment]
@sneakyfildy Are you using webpack?

If so, you can follow: https://github.com/webpack/webpack/issues/3128#issuecomment-311418452

to only include the locales you need. This was working as of moment `2.18.x` but seems to break on `2.19.x`.  I'm looking into why.

**Comment by KingsDevelopment** [comment]
Breaks using 2.19 for me too, using webpack (through angular-cli)

**Comment by jeffijoe** [comment]
Yeah, latest version broke things for me, too, using IgnorePlugin.

**Comment by sneakyfildy** [comment]
@jeffijoe can you please share an ignorePlugin setup? I'm having hard times ignoring plugins by path. It's only working for me to ignore by name.

**Comment by jeffijoe** [comment]
@sneakyfildy Sure! IgnorePlugin uses regexps though, so that's probably why.

```
new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
```

I did try disabling it, but I still got an error.

**Comment by KhaledSMQ** [comment]
👍 same as well here i am having same problem after new update.
```
WARNING in ./node_modules/moment/src/lib/locale/locales.js
```

**Comment by keatkeat87** [comment]
any update ?

**Comment by chamini2** [comment]
> a moment/core that only has `en`

What about not having any language set and instead having moment/core throw if no language is imported? That way other languages developers don't **have** to have an `en` locale added to their payload.

**Comment by azavisha** [comment]
This is just a simple workaround, not a solution.

I don't use any locales, so I just added this to my `package.json`. This removes all locale files during the packge installation, which obviously prevents webpack from importing them.

```
"scripts": {
  "postinstall": "rm -r node_modules/moment/locale"
}
```

If you need to keep one of the locales (`en-ca` for example), instead of `rm` command, you can use something like this:

```
find node_modules/moment/locale -type f -not -name 'en-ca.js' -delete
```

Please don't use these commands if you don't know what they are doing...

**Comment by AlexShuraits** [comment]
@azavisha solution worked, but with warning:
WARNING in ENOENT: no such file or directory, scandir '/node_modules/moment/locale'
Fixed with 
"postinstall": "rm -rf node_modules/moment/locale/*"

**Comment by Liero** [comment]
@marwahaha:
> Perhaps a more sustainable solution is to publish a new package for each locale, and a moment/core that only has `en`. We can leave the existing package the same.

No, I don't think so. There is a lot of community libraries that depends on moment, so using any of them would include all locales again.

I don't understand, why it is a problem to simply ignore locales when importing

`import * from `moment`

and have them explicitly imported

import 'moment/locale/de'

**Comment by marwahaha** [comment]
Information on importing (and not importing) locales is available here:
https://momentjs.com/docs/#/i18n/loading-into-nodejs/
https://momentjs.com/docs/#/use-it/webpack/

For future directions (might require a breaking change to drop certain groups of existing users),
https://github.com/moment/moment/issues/5288
https://github.com/moment/moment/pull/3688

Sorry this has been such a painful issue for many people.
Please re-open if you still have concerns.
