### ISSUE TITLE
Get last week of year returns a date of previous year.

### ISSUE THREAD

**Issue by ronaldgj** [moment/moment#4219]
Hi Guys,

I ran into a problem with momentjs when trying get the last day of the last week in January 2017.
I use the locale 'nl'. It's Dutch.

I made the following code:
```
moment({ year: 2017, month: 0 }).week( 5 )
```

This should return 'Tue Jan 31 2017'. But it returns a date of  'Sun Feb 07 2016'.

Any ideas?

**Comment by ashsearle** [comment]
You're creating a moment for Jan 1st 2017, which is the last day of Week 52 of 2016 (in 'nl' locale), so Week 5 of the same 'weekYear' puts you back near the beginning of 2016.

If you just want the last day in January, why are you playing with `week()` at all?  Why not just create your moment as `moment({ year: 2017, month: 0, date: 31 })`?

**Comment by icambron** [comment]
^^
