### ISSUE TITLE
Setting a language with the full locale (e.g. en-us) should set the language correctly (en).

### ISSUE THREAD

**Issue by manastungare** [moment/moment#422]
Actual:
1. Load moment.js.
2. Load lang-all.js.
3. At this point, moment.lang() returns 'zh-tw'. (filed separately as #421).
4. Set moment.lang(window.navigator.language); My window.navigator.language is 'en-US'.
5. Now, moment.lang() still returns 'zh-tw'.

Expected:
5. moment.lang() should return 'en', since although it doesn't have strings for 'en-us', it does have strings for 'en'.

**Comment by bbottema** [comment]
Did this break in newer releases? It's not working for me anymore (I don't see 'en' either anymore, so the alias may have become invalid).

On a side note cross browser support for `window.navigator.language` has become a lot better.
