### ISSUE TITLE
Mess with locales

### ISSUE THREAD

**Issue by sneakyfildy** [moment/moment#4220]
Sorry for interrupting these concurrent locales battles.
Why locales are loaded/bundled automatically? I see no single reason to do that.
And this dynamic "require" usage. For what sake?

Can we have one nice simple solution to not have locales auto-bundled/auto-loaded?
There must be a separate locale loader which will resolve all troubles.

I've spent half of my working day trying to understand, can we use this library on production and now I see how people are suggesting each other to remove files from node_modules (!!!) to not have excess 100KB in their compiled applications. This is ridiculous.
Talking about browser applications of course.

**Comment by sneakyfildy** [comment]
Blah. Nevermind. This will break backward compatibility. Pretty unreliable picture.

**Comment by silentroach** [comment]
If you use webpack, you can use IgnorePlugin to skip unused locales

    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)

And include 'moment' (en locale included) and 'moment/locale/xx' for your locales.

**Comment by sneakyfildy** [comment]
Thanks, but I can accept using any "Ignore" approach only for "until we finally fix it properly" way.
