### ISSUE TITLE
Uncaught TypeError: __webpack_require__.i(...) is not a function

### ISSUE THREAD

**Issue by nottinhill** [moment/moment#4223]
**Description of the Issue and Steps to Reproduce:**

```
Uncaught TypeError: __webpack_require__.i(...) is not a function
    at Object.../../../../moment/src/lib/units/year.js (vendor.bundle.js:47527)
    at __webpack_require__ (inline.bundle.js:55)
    at Object.../../../../moment/src/lib/moment/get-set.js (vendor.bundle.js:44718)
    at __webpack_require__ (inline.bundle.js:55)
    at Object.../../../../moment/src/lib/units/month.js (vendor.bundle.js:46328)
    at __webpack_require__ (inline.bundle.js:55)
    at Object.../../../../moment/src/lib/locale/base-config.js (vendor.bundle.js:43484)
    at __webpack_require__ (inline.bundle.js:55)
    at Object.<anonymous> (vendor.bundle.js:43805)
    at Object.../../../../moment/src/lib/locale/locales.js (vendor.bundle.js:44010)
```

*Please include the values of all variables used.*

**Environment:**

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

Latest Chrome on Mac
Angular 4 on Kubernetes Linux Cluster

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
UTC+2
* The time and date at which the code was run
Just now.
* Other libraries in use (TypeScript, Immutable.js, etc)
Typescript, Angular4, Angular-CLI

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
Logger of Browser
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by joshjohn1984** [comment]
I spent the whole before realizing this was the issue!

**Comment by nottinhill** [comment]
You resolved it?

**Comment by lpsantana** [comment]
@nottinhill do you solved the problem?

**Comment by joshjohn1984** [comment]
@nottinhill .. I just reverted back to my previous moment version

**Comment by lpsantana** [comment]
@joshjohn1984 what version did you change? the angular2-moment one or moment one?

**Comment by matthew-sutterlin** [comment]
Our team had the same issue after autoinstalling 1.19, fixed everything by uninstalling and specifically npm install moment@2.18

error was:
year.js:84 Uncaught TypeError: __webpack_require__.i(...) is not a function
    at Object.<anonymous> (year.js:84)
    at __webpack_require__ (bootstrap 2097b80…:686)
    at fn (bootstrap 2097b80…:105)
    at Object.exports.__esModule (get-set.js:6)
    at __webpack_require__ (bootstrap 2097b80…:686)
    at fn (bootstrap 2097b80…:105)
    at Object.<anonymous> (month.js:1)
    at __webpack_require__ (bootstrap 2097b80…:686)
    at fn (bootstrap 2097b80…:105)
    at Object.<anonymous> (base-config.js:6)
(anonymous)    @    year.js:84

**Comment by morrisonbrett** [comment]
I ended up getting past this by changing:

`import * as moment from 'moment';`

to:

`import * as moment from 'moment/moment';`

**Comment by nottinhill** [comment]
@morrisonbrett Would you need to do code changes then?

**Comment by morrisonbrett** [comment]
Yes, I had to update the import statement in all usages of moment. You can also alias the package per: https://github.com/moment/moment/issues/4216#issuecomment-335637520

**Comment by YashaswiNayak99** [comment]
I have been facing this issue since yesterday, my moment version is 2.18.1, no changes in moment version since beginning. I have no import moment statements, any suggestions?

**Comment by 4apkis** [comment]
This happens because of corrupted 2.19 moment version.
In my project we use angular2-moment, which is linked to moment. See the version - it is not strictly defined.
```
  "dependencies": {
    "moment": "^2.16.0"
  },
```
Once moment got updated, our project got failed. 
We had to explicitly add 
`"moment":"2.18.1"`
to our package.json and the issue had gone.

**Comment by Jerome-Joestar** [comment]
@YashaswiNayak99 I am also having this issue on version 2.18.1, have you found any solutions to this issue?

**Comment by 4apkis** [comment]
@Jerome-Joestar is this version defined in your package.json?
When you build the project and see the issue, you can see the actual sources in the browser. Does that file still say "2.18.1"?

**Comment by Jerome-Joestar** [comment]
@4apkis Just checked and you are correct it bumped the version up to 2.19.0, setting it strictly to 2.18.1. Thanks!

**Comment by mj1856** [comment]
Dup #4216
