### ISSUE TITLE
karma unit tests failing after updating from 2.18.1 to 2.19.0: Object is not a constructor

### ISSUE THREAD

**Issue by baywet** [moment/moment#4224]
Our unit tests suddenly started breaking when 2.19 was released this afternoon on lines like these ones:
```ts
import * as moment from 'moment';
// ...
const oriDate = moment(InstanceDate); // where instanceDate is a ISO string representation of a date.
```
These are the kind of errors we're getting.
```
× View Model initialization
2017-10-10T20:26:56.6318731Z       PhantomJS 2.1.1 (Windows 8 0.0.0)
2017-10-10T20:26:56.6318731Z     Object is not a constructor (evaluating 'moment(InstanceDate)')
2017-10-10T20:26:56.6318731Z     MeetingInstance@src/app/components/MeetingInstanceDisplay/test/MeetingInstanceDisplay.test.ts:74180:33
2017-10-10T20:26:56.6318731Z     src/app/components/MeetingInstanceDisplay/test/MeetingInstanceDisplay.test.ts:109614:69
```

*Please include the values of all variables used.*

**Environment:**
PhantomJS 2.1.1 (Windows 8 0.0.0) with

**Other information that may be helpful:**
TimeZone of the machine running the unit test Eastern Standard Time
2017-10-10T20:26:56.6318731Z       
Karma@latest, Sinon@latest, TypeScript@latest, Webpack@2.X and chai@latest

CC @ichernev

**Comment by mi9rom** [comment]
Angular 4.4.4, TS 2.5.2, "webpack": "3.6.0", Anular-cli :
after switching "moment": "2.18.1" -> "2.19.0"

**import {moment} from 'moment':**
....... /node_modules/moment/moment"' has no exported member 'moment'.

**import * as moment from 'moment':**
104:25-42 "export 'localeData' (imported as 'moment') was not found in 'moment'
TypeError:
WEBPACK_IMPORTED_MODULE_7_moment__ is not a function.

**Comment by tqc** [comment]
See #4216. 

At the moment webpack is getting pointed at a not quite backward compatible ES6 version. For now, just set the dependency in package.json to 2.18.1 rather than ^2.18.1

**Comment by baywet** [comment]
We already locked down to 2.18.1 for now in order to fix our builds/CI. I was reporting the issue for the long term implications. #4216 seemed different as it's mentioning a submodule, hence why I opened a new one.

**Comment by tqc** [comment]
@baywet The title issue is a different one, but it's a long thread with some other stuff mixed in. 

The es6 version needs to be imported as 

     import moment from ‘moment’

or

    require(‘moment’).default

The submodule stuff just comes up because you don’t get to rewrite the require statements in intermediate modules.

**Comment by vanslly** [comment]
For `import moment from ‘moment’` I get
> Module '"[...]/node_modules/moment/moment"' has no default export.

I am using TypeScript with commonjs module resolution.

**Comment by tqc** [comment]
@vanslly You might be running into #4170 there - moment/moment isn't an es6 module, and sets module.exports rather than module.exports.default.

**Comment by DanielKucal** [comment]
Same here with v2.19
```
TypeError: Object is not a function (evaluating 'moment(event.datePublish)') in config/spec-bundle.js
```
```
ARNING in ./~/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/Users/danielkucal/Applications/Angular2/zoomsphere2-web/node_modules/moment/src/lib/locale'
 @ ./~/moment/src/lib/locale/locales.js 65:16-60
 @ ./~/moment/src/lib/locale/locale.js
 @ ./~/moment/src/moment.js
 @ ./src/app/pages/restricted/module/publisher/calendar/events/calendar-events.component.spec.ts
 @ ./src \.spec\.ts
 @ ./config/spec-bundle.js

WARNING in ./~/ngx-bootstrap/datepicker2/time/bs-date-time-picker.component.js
76:12-29 "export 'localeData' (imported as 'moment') was not found in 'moment'

WARNING in ./~/ngx-bootstrap/datepicker2/common/bs-date-picker-base.class.js
376:25-42 "export 'localeData' (imported as 'moment') was not found in 'moment'

WARNING in ./~/ngx-bootstrap/datepicker2/common/bs-date-picker-base.class.js
385:22-37 "export 'weekdays' (imported as 'moment') was not found in 'moment'

WARNING in ./~/ngx-bootstrap/datepicker2/common/bs-date-picker-base.class.js
386:27-45 "export 'weekdaysMin' (imported as 'moment') was not found in 'moment'

WARNING in ./~/ngx-bootstrap/datepicker2/common/bs-date-picker-base.class.js
387:24-42 "export 'monthsShort' (imported as 'moment') was not found in 'moment'
```

**Comment by kimamula** [comment]
I also ran into the same problem, which has been solved by adding `"allowSyntheticDefaultImports": true` in tsconfig.json and using `import moment from 'moment';`.

**Comment by baywet** [comment]
version 2.19.1 that came out yesterday fixes the issue with no code/configuration change. Thanks for the help. Closing.
