### ISSUE TITLE
WARNING in ./node_modules/.2.19.0@moment/src/lib/locale/locales.js Module not found: Error: Can't resolve './locale'

### ISSUE THREAD

**Issue by fengxinming** [moment/moment#4228]
WARNING in ./node_modules/.2.19.0@moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in 'D:\demows\h5-travel-plus\node_modules\.2.19.0@moment\src\lib\locale'

plugins: [
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
]

**Comment by saurabhnemade** [comment]
@	fengxinming

Duplicate of #4218 .
`npm install moment@2.18.1` will fix it for now.

**Comment by mengcan555** [comment]
package.json里锁定版本吧 "moment": "2.18.1",

**Comment by ekiliqua** [comment]
Yes, i have the same problem and i fix it uninstalling last version and installing 2.18.1.

**Comment by joseneto-fixeads** [comment]
I back to 2.18.1 and fixed

**Comment by mfazul** [comment]
I also faced same issue and reverted to 2.18.1, why this is not fixed in latest version?

**Comment by johannesjo** [comment]
I would assume that this related to #4042 [bugfix] "Make auto locale loading for node not mess webpack"

**Comment by mj1856** [comment]
Dup #4216

**Comment by guohuihuiguo** [comment]
我降到了2.18.1 依然报这个错误，大家是如何解决的呢
