### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_0_moment__ is not a function

### ISSUE THREAD

**Issue by huyjack178** [moment/moment#4229]
I got this issue this morning after run npm install again. Yesterday everything is ok. Have anyone had solution for this issue yet?

**Comment by epfisztner** [comment]
We had similar issue with webpack uglify plugin. The solution was to downgrade to 2.18.1

**Comment by AlfredMou** [comment]
I think they should use the 3.0.0 version number instead of 2.19.0。we have the same problem In our NPM package because of moment@2.19.0

**Comment by AAudusseau** [comment]
Same issue with version 2.19.0. As @epfisztner said downgrade to 2.18.1 fix the problem.

**Comment by valscion** [comment]
Duplicate of #4216

**Comment by Valentin1918** [comment]
The same, please resolve it ASAP:
Uncaught TypeError: __webpack_require__.i(...) is not a function
Can't resolve './locale' in '.../node_modules/moment/src/lib/locale'

**Comment by valscion** [comment]
Maintainers are aware of this issue, please refrain from posting new comments. Instead, you can subscribe to #4216 if you want to track this issue.

![screen shot 2017-10-11 at 12 01 31](https://user-images.githubusercontent.com/482561/31431309-f4b6e92a-ae7b-11e7-82ee-ddf639fbda8f.png)

**Comment by kelvindart** [comment]
A in-code fix, is to change
```
import * as moment from 'moment';
```

To:
```
import * as moment from 'moment/moment';
```

**Comment by mj1856** [comment]
Dup #4216

**Comment by HuffyPiet** [comment]
I landed here whilst facing a similar problem, but I quickly had a gotcha moment, when I realized it was just a resolution problem, I was able to fix the bug quicker than I had thought i could ... new updates means , maybe project structure might have changed slightly, :) lol

**Comment by Loskilo** [comment]
TypeError: _util_Yelp__WEBPACK_IMPORTED_MODULE_4__.default.search is not a function <= this my error can someoen please help me

**Comment by galaxy-dot** [comment]
Having the same issue in 2023 when downloaded moment 2.29.4 to fix a vulnerability. Any suggestions to fix it? Much appreciated!

Was using moment 2.29.1, no issue. 

Code snippet:

```
// a helper.js file

import moment from 'moment';
export const currentTZ = () => moment().tz("<some time zone string>")
  .format('<something>') === '<+some number>' ? '<a string>' : '<another string>';
```
