### ISSUE TITLE
Missing Dependencies error thrown

### ISSUE THREAD

**Issue by KyleWMiller** [moment/moment#4237]
**Description of the Issue and Steps to Reproduce:**
`yarn add moment`

*Please include the values of all variables used.*
I am adding them to a file that is already being used for a tessel 2 project. 

**Environment:**
Mac
fish terminal
nodeJSv8.4 installed
Tessel 2

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

this is the list of "missing dependencies" that I was asked to report to the package maintainer: `colony-compiler`, `colors`, `colorsafeconsole`, `effess`, `hardware-resolve`, `humanize`, `my-local-ip`, `nomnom`, `semver`, `structured-clone`, `temp`, and `usb`. 

Thanks for working to make this project grrrrrrrrreat!

**Comment by ashsearle** [comment]
Hi @KyleWMiller 

You say you were trying to add moment to an existing project.  Before trying `yarn add moment`, are you sure you'd already (successfully) downloaded the other libraries for the project (e.g. by simply running `yarn` alone?)

I don't think it's possible for this to be a moment issue as moment doesn't have any dependencies (see Dependencies listed as 'None' at [npm registry](https://www.npmjs.com/package/moment), and there's no `"dependencies"` key in [moment's package.json](https://github.com/moment/moment/blob/develop/package.json)

**Comment by icambron** [comment]
Closing this for age. I can reopen if you respond to @ashsearle's comments.
