### ISSUE TITLE
Daylight saving time issue

### ISSUE THREAD

**Issue by darakeon** [moment/moment#4249]
The function endOf of 2017-10-15 returns a value greater than startOf of 2017-10-16

* GMT-3h, Brazil
* Chrome, Firefox and Edge - Windows 10
* Chrome - Arch Linux
* version 2.18.1

The code we've done as fix:

```
    let endOf = dates.clone().endOf('day')

    const startOfDayAfter =
      dates.clone().add(1, 'days').startOf('day')

    if (startOfDayAfter.isBefore(endOf)) {
      endOf = startOfDayAfter.add(-1, 'milliseconds')
    }
```

**Comment by derekstavis** [comment]
This issue was originally found on airbnb/react-dates/issues/776

**Comment by icambron** [comment]
Yeah, this is an old bug and it's particularly acute in Brazil because of the midnight DST. See e.g. #1990, #4164, #2749, and most importantly #3132

**Comment by darakeon** [comment]
@icambron, after opening the issue I looked into the code and fixed it: https://github.com/moment/moment/pull/4254
