### ISSUE TITLE
Memoizing moment

### ISSUE THREAD

**Issue by mmahalwy** [moment/moment#4250]
Question about memoizing moment. We found that it is expensive to have moments calculate dates in a React component - especially when the data passed into moment has not changed. Wondering, how crazy would it be if we memoize all the functions on moment. For example, `moment.isDate` could be memoized by `lodash/memoize`. 

Looking for thoughts / concerns.

**Comment by icambron** [comment]
Static stuff like `isDate` would be fine, but most operations are in Moment instances. How would you memoize that? But that if you did memoize at the per-object level, you'd still have the problem that Moment objects are mutable and everything would break.

**Comment by mmahalwy** [comment]
@icambron I will put up a repo soon. Yes, memoizing static methods is easy. And currently, memoizing parsing is valuable, but beyond that it gets complicated. Stay tuned!

**Comment by icambron** [comment]
@mmahalwy I'm cleaning out tickets and I'm going to close this. But let me know what you come up with!
