### ISSUE TITLE
function add

### ISSUE THREAD

**Issue by blueshw** [moment/moment#4253]
- version: 2.18.1

I have a problem using function add
```
var d = moment().add(1, 'day');
```
this is ok. but, 
```
var CURRENT_DATE = moment();
var TOMORROW = CURRENT_DATE.add(1, 'day')
var DATE_FORMAT = 'YYYYMMDD'
console.log(CURRENT_DATE.format(DATE_FORMAT));
console.log(TOMORROW.format(DATE_FORMAT));
```
The result is the Same.
I expect values like
```
// expected
CURRENT_DATE === '20171018'
TOMORROW === '20171019'

// received
CURRENT_DATE === '20171019'
TOMORROW === '20171019'

```
maybe object moment need another function doesn't add the value of current object.

**Comment by amoghesturi** [comment]
From the documentation, 

"It should be noted that moments are mutable. Calling any of the manipulation methods will change the original moment."

**Comment by maggiepint** [comment]
See comment above. Just use copy.

var d = moment().copy().add(1, 'day');
