### ISSUE TITLE
Add support for X / unix timestamp parsing in constructor [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [moment/moment#4257]
Being able to do the following would be so useful:
```
const moment = Moment(value, ['X', Moment.ISO_8601]); //automatically detect if timestamp or iso string
```
Right now I'm falling back to detect in an if branch `value.match(/^\d+$/)` and use different parsers.

**Comment by icambron** [comment]
I don't think I understand the issue: doesn't that work?

**Comment by damianobarbati** [comment]
Oh I tried when I posted this issue and it was not working: my bad :|
