### ISSUE TITLE
moment 2.19.x parse broken

### ISSUE THREAD

**Issue by devongovett** [moment/moment#4259]
**Description of the Issue and Steps to Reproduce:**

Using moment 2.19.x, parsing seems to be broken. The only thing different between the below runs is a one hour difference. Somehow one is invalid and the other isn't. Both work fine in 2.18.1.

```
> require('moment').utc('Fri Mar 04 15:00:00 +0800 2016', 'ddd MMM DD HH:mm:ss Z YYYY')
moment.invalid(/* Fri Mar 04 15:00:00 +0800 2016 */)

> require('moment').utc('Fri Mar 04 16:00:00 +0800 2016', 'ddd MMM DD HH:mm:ss Z YYYY')
moment.utc("2016-03-04T08:00:00.000+00:00")
```

**Environment:**

Node v6.11.1.

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString()) // => Fri Oct 20 2017 10:59:29 GMT-0700 (PDT)
console.log((new Date()).toLocaleString()) // => 10/20/2017, 10:59:29 AM
console.log( (new Date()).getTimezoneOffset()) // => 420
console.log( navigator.userAgent) // => undefined
console.log(moment.version) => // 2.19.0
```

**Comment by alex88** [comment]
Same here, I've tried this jsfiddle http://jsfiddle.net/hhe7jkur/ and it works fine, same version included via npm in browser:

```
moment.version
"2.19.1"
moment('4-Oct-17', ['D-MMM-YY']).isValid()
false
```

* Environment:*

Chrome 61.0.3163.100

If you are reporting an issue, please run the following code in the environment you are using and include the output:

```
console.log( (new Date()).toString()) // => Fri Oct 20 2017 15:42:57 GMT-0700 (PDT)
console.log((new Date()).toLocaleString()) // => 10/20/2017, 3:43:16 PM
console.log( (new Date()).getTimezoneOffset()) // => 420
console.log( navigator.userAgent) // => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
console.log(moment.version) // => 2.19.1

```

**Comment by icambron** [comment]
Closing in favor of #4298
