### ISSUE TITLE
Using pretext in russian locale

### ISSUE THREAD

**Issue by DodgeCamaro** [moment/moment#4260]
I use script for generate date in russian. 

`return console.log(moment().format("[в] dddd Do MMMM [в] LT").toString());
`
Output - в пятницу 20-го октября в 11:04

But one day of the week (Tuesday) have problem with generation date.

Wrong output - В/в вторник 17-го октября в 15:30.

**Correct output** - **Во/во** вторник 17-го октября в 15:30. 
Pretext always using only for Tuesday.

**Description of the Issue and Steps to Reproduce:**

time.sh script
```
#!/usr/bin/env node
var moment = require("moment");
moment.locale("ru");

return console.log(moment().format("[в] dddd Do MMMM [в] LT").toString());
```
package.json

```
{
  "name": "time",
  "version": "1.0.0",
  "description": "",
  "main": "moment.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "moment": "^2.19.1"
  }
}
```

**Environment:**

*NodeJS 8.6 on Ubuntu 16.04*

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
Sat Oct 21 2017 14:10:42 GMT+0300 (EEST)
console.log((new Date()).toLocaleString())
2017-10-21 14:11:15
console.log( (new Date()).getTimezoneOffset())
-180
console.log( navigator.userAgent)
n/a
console.log(moment.version)
2.19.1
```

**Comment by marwahaha** [comment]
Hi @DodgeCamaro - notice that your format provides the `в` -- Moment.js does not provide that first character.

Today is a Tuesday in USA - and your format string will provide:
```
console.log(moment().format("[в] dddd Do MMMM [в] LT").toString())
> в Tuesday 19th December в 10:22 PM
```

Perhaps you need Tuesdays prepended with  `во`, but I don't see where the Moment bug is.

**Comment by marwahaha** [comment]
Closing due to age. Please re-open if you still have questions.
