### ISSUE TITLE
Weird "Invalid Date" return

### ISSUE THREAD

**Issue by obetomuniz** [moment/moment#4261]
I detected this issue trying to parse the following code:

```javascript
moment('Tuesday, April 10 at 7:00 PM', 'dddd[,] MMMM DD [at] H:mm A').format('YYYY-MM-DD')
// "Invalid date"

moment('Monday, October 23 at 7:00 PM', 'dddd[,] MMMM DD [at] H:mm A').format('YYYY-MM-DD')
// "2017-10-23"
```

Chrome 61 on OSX

```js
Sat Oct 21 2017 20:30:05 GMT-0200 (-02)
10/21/2017, 7:30:05 PM
120
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
2.19.1
```

**Comment by ashsearle** [comment]
The dates your parsing don't specify a year, so moment is guessing you mean this year (2017)

April 10th 2017 was a Monday. So 'Tuesday, April 10' is invalid.

**Comment by icambron** [comment]
^^

**Comment by obetomuniz** [comment]
For me, it is an issue @ashsearle, even if it's just a documentation gap. Anyway, @icambron already closed the PR without any reasonable justification (and workaround). Let move forward. Thanks.

**Comment by icambron** [comment]
I agree there's a missing entry somewhere here: http://momentjs.com/docs/#/parsing/is-valid/
