### ISSUE TITLE
Duration compare/equality method?

### ISSUE THREAD

**Issue by Techn1x** [moment/moment#4262]
Would this be hard to add? I am thinking something like the `isSame()` method that standard moments have, but for durations.

Currently I'm just comparing durations in my code by doing
`moment.duration().toISOString() === moment.duration().toISOString()`

Additionally, if they could be compared like `moment.duration() === moment.duration()` that would be great

**Comment by icambron** [comment]
I think `isEqual` is a reasonable feature request. There are some caveats, though: I think for example, that `moment.duration({ hours: 24 })` and `moment.duration({ days: 1 })` should *not* be equal, and if the caller wants that they should compare `valueOf()` values. In other words, I think it should compare the durations partwise, just like your `toISOString` thing does.

**Comment by Techn1x** [comment]
I don't know if this is possible, but perhaps we could use the `==` operator for non-strict comparisons (eg `moment.duration({ hours: 24 }) == moment.duration({ days: 1 })` would be `true`) and `===` for the same condition would be `false`. However this might not logically work when you go to compare something like `moment.duration({ days: 30 }) == moment.duration({ months: 1 })` because the number of days in a month varies...

-----

Just to further complicate things, it would also be great if other comparison's could be supported (say, `moment.duration() > moment.duration()`) - My assumption would be that it would take a stepwise approach and compare each unit of time, starting at the largest.

For example, `moment.duration({ hours: 24 }) > moment.duration({ days: 1 })` would evaluate to `false` because `{ days : 1 }` is larger than `{ hours: 24 }` (which is essentially days: 0, hours: 24 )

But perhaps this might be too confusing and result in unexpected behavior for people who don't read documentation before using it..

**Comment by Techn1x** [comment]
Perhaps the only sane, sensible approach with expected results is to just compare the raw millisecond value for both equality and gt lt comparisons?

`moment.duration({ days: 1}).asMilliseconds() === moment.duration({ hours: 24 }).asMilliseconds()` true
`moment.duration({ days: 1}).asMilliseconds() > moment.duration({ hours: 23 }).asMilliseconds()` true
`moment.duration({ days: 1}).asMilliseconds() > moment.duration({ hours: 24 }).asMilliseconds()` false
`moment.duration({ days: 1}).asMilliseconds() > moment.duration({ hours: 25 }).asMilliseconds()` false
`moment.duration({ months: 1}).asMilliseconds() > moment.duration({ days: 30 }).asMilliseconds()` false (according to the duration docs, length of a duration in months is defined as 30 days, so this would be equal)

Thoughts?

**Comment by marwahaha** [comment]
I'm hesitant to add this to the codebase, since (as you mentioned) one can compare the millisecond values. I can budge if you have a strong argument for it. 

We do have `isSame`/`isBefore`/`isAfter`/`isSameOrBefore`/`isSameOrAfter` for moments, but I don't exactly love those either.

**Comment by icambron** [comment]
RIght, if all we're doing is comparing milliseconds, then you can just do

```js
+someDuration === +someOtherDuration
```

I think the only real case for `isEqual` is checking that both durations have the same units with the same values.

**Comment by marwahaha** [comment]
Even so - I'm not sure that comparing durations with the same units is useful, since duration, i.e. "difference between two timestamps", feels the same in any unit.

**Comment by icambron** [comment]
Well, whether it's genuinely useful or not is a fair question, and I'm OK on closing. But I firmly disagree with this:

> feels the same in any unit

Moment's imprecise higher order units make this untrue (and should!). An illustration:

```js
var dur1 = moment.duration({months: 1});
var dur2 = moment.duration({milliseconds: dur1.asMilliseconds()});
+dur1 === +dur2  //=> true
var now = moment();
now.toString();   //=> "Fri Dec 29 2017 16:38:49 GMT-0500"
now.add(dur1).toString(); //=> "Mon Jan 29 2018 16:38:49 GMT-0500"
now.add(dur2).toString();  //=> "Wed Feb 28 2018 16:38:49 GMT-0500"
```

In other words, those durations have totally different behaviors, despite corresponding to the same number of milliseconds. If you want to ask "are these objects the same?", you need to include everything that affects their behavior (i.e. equivalent objects can be used interchangeably). Since that's unit-dependent, the check would have to be too.

**Comment by Techn1x** [comment]
When I opened this issue I didn't have a _real_ use case for needing an isEqual type of method - I just noticed it seemed to be something that moment objects had, but duration objects were missing. And I can see why now, it's clearly not as simple as I first thought :)

I would be fine with this being closed

**Comment by marwahaha** [comment]
Ok. 

Noted @icambron - ms/sec/min/hr/day seem distinct from month/year

**Comment by icambron** [comment]
@marwahaha agreed. Here's how I explained it in Luxon: https://moment.github.io/luxon/docs/manual/math.html#calendar-math-vs-time-math
