### ISSUE TITLE
Moment.js timestamp and utc timestamp is not matched

### ISSUE THREAD

**Issue by rajanmidd** [moment/moment#4263]
I am using the unix() function of moment.js in node.js and it returns the timestamp and when i matched this timestamp with epoch timestamp (https://www.epochconverter.com/) then there is a difference of 18-20 sec.

moment().unix()

so anyone can help on this.

**Comment by samliew** [comment]
I had to revert to release 2.18.1 to fix this issue.

**Comment by icambron** [comment]
Can you show me what you mean? It seems to match to me:

```js
var m = moment();
m.format(); //=> '2017-11-13T13:50:02-05:00'

// pasting in from that website:

// Monday, November 13, 2017 6:50:02 PM
```

Since that last time is GMT, those are the same down to the second.

**Comment by marwahaha** [comment]
Epochconverter and Moment.js display the same time, as you can see by running `moment().unix()` in the browser console on https://www.epochconverter.com/. Please re-open if you have other issues.

**Comment by juanarbol** [comment]
I solved without using `.unix` method, just `moment(timestamp)`
