### ISSUE TITLE
Parsing dates with pattern DMYYYY does not work

### ISSUE THREAD

**Issue by wuarmin** [moment/moment#4265]
Hello,
I have a problem with following code:
```javascript
moment('551960', 'DMYYYY', true); // invalid-date
//Object { _isAMomentObject: true, _i: "551960", _f: "DMYYYY", _strict: true, _isUTC: false, _pf: Object, _locale: Object, _d: Invalid Date, _isValid: false }
moment('05051960', 'DMYYYY', true); // valid-date
//Object { _isAMomentObject: true, _i: "05051960", _f: "DMYYYY", _strict: true, _isUTC: false, _pf: Object, _locale: Object, _d: Date 1960-05-04T22:00:00.000Z, _isValid: true }
```
What's the reason that string '551960' cannot be parsed?

**This is my output:**
Tue Oct 24 2017 08:55:36 GMT+0200 (CEST) 
24.10.2017, 08:55:36 
-120 
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0 

Thank you :smile:

**Comment by ashsearle** [comment]
Given an input like '1111960', would you expect that to be parsed as 1st Nov 1960, or 11th January 1960?

Why?

**Comment by wuarmin** [comment]
Oh, yes that's right. For '1111960' I would expect an invalid date, because there is a ambiguity. My format says there are four digits at the end which reflect the year. So there are three remaining digits, which are ambiguous. '551960' on the other hand is unambiguous. I just wanted to know if this is expected.

**Comment by ashsearle** [comment]
I can't say it's expected behaviour, but I wouldn't want to 'fix' it to support this format either: there are so many ambiguous combinations it would be an incredibly unreliable format to parse.

**Comment by wuarmin** [comment]
That's right. Thank you for the clarification. I think the issue can be closed.

**Comment by manusinghal19** [comment]
@ashsearle I am also facing the same issue. When format information is missing, Only then question of ambiguous combinations come into picture. So, as long as format is provided, momentjs should parse correctly.

**Comment by manusinghal19** [comment]
Also I think , going by discussion above, fixing this might not be as easy as said. It seems momentjs  first try to parse  input string as date, and then apply formatting on top of that.

**Comment by ashsearle** [comment]
@manusinghal19 Please re-read https://github.com/moment/moment/issues/4265#issuecomment-338938105 and tell me which result you'd expect from parsing `"1111960"`

**Comment by manusinghal19** [comment]
@ashsearle 
`moment('1111960'); // invalid-date
moment('1111960', 'DMMYYYY', true); // valid-date  interpreted as 1st Nov 1960
moment('1111960', 'DDMYYYY', true); // valid-date  interpreted as 11th Jan 1960`

**Comment by wuarmin** [comment]
I agree with @manusinghal19. I think this is a common scenario.

**Comment by ashsearle** [comment]
@manusinghal19 This issue is specifically about `DMYYYY` format, not `DMMYYYY` or `DDMYYYY`.

With `DMYYYY` you have to choose: should `moment('1111960', 'DMYYYY', true)` be interpreted as 1st Nov 1960 or 11th Jan 1960?  Why?

I've never seen anyone use DMYYYY format for formatting dates for display or data-interchange format - probably because it's error-prone, ambiguous and broken.

e.g. if you make the arbitrary choice that `1111960` represents 1st November 1960 instead of 11th January 1960, that means you have no way to pass 11th January (of any year) to another system.  

It's a rubbish date format.  Don't use it!

**Comment by icambron** [comment]
Yeah, @ashsearle is completely right. If your format is ambiguous, the parser has to guess and I don't see how it could reliably guess right. 

re: `DMMYYYY`: there *is* a valid complaint about Moment's greediness as a parser: in principle you do get one degree of "freedom", i.e. with `DMMYYYY` it ought to be able to decide how many digits to allocate to `D`. But Moment's parser will eat up as many digits with D and never backtrack when it can't fulfill `YYYY`. There's a ticket somewhere about that, but a) that does *not* apply `DMYYYY`, which doesn't even work in principle and b) we're not going to fix `DMMYYYY` until we get rid of non-strict parsing and rewrite the whole parser.
