### ISSUE TITLE
Support for 0-11, 00-11 hours display format

### ISSUE THREAD

**Issue by Scit** [moment/moment#4268]
Do you plane to support 0-11/00-11 hours display format? Like "K/KK" format pattern in SimpleDateFormat?

Thank you!

**Comment by ashsearle** [comment]
I've never seen this format in use: does your country / application need this?

**Comment by Scit** [comment]
@ashsearle, Yes. We use it our project.
moment uses:
"k" for [1 .. 24] hours 
"H" for [0 .. 23] hours
"h" for [1 .. 12] hours
But [0..11] is missing :-) So, we can't provide this format for our users.

**Comment by ashsearle** [comment]
If I understand you correctly: you're saying you don't have any use for this format yourself, you simply want to offer it as a format for your users in case they need it.

Have any users asked you to support this specific format?

**Comment by Scit** [comment]
Ok, This feature is not so important at the moment. Thank you.

**Comment by pyemelyanovj2** [comment]
Is there any updates on adding support to this feature?
"K"/"KK" pattern is also part of Java Date Time format
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
` K       hour-of-am-pm (0-11)  `

**Comment by ashsearle** [comment]
@pyemelyanovj2 Based on the moment [project status](https://momentjs.com/docs/#/-project-status/) I'd say not.

> We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done.
>
> In practice, this means:
> We will not be adding new features or capabilities.

I'm just as curious as I was three years ago: do you have a use case for this format?

**Comment by pyemelyanovj2** [comment]
> @pyemelyanovj2 Based on the moment [project status](https://momentjs.com/docs/#/-project-status/) I'd say not.
> 
> > We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done.
> > In practice, this means:
> > We will not be adding new features or capabilities.
> 
> I'm just as curious as I was three years ago: do you have a use case for this format?

yep, we have some of our backends running with java, and it's sending us time in this format, using "K" pattern 
i've made workaround for this case, just was wondering if there's a plan to add this
what if i'll contribute with update for that ?

**Comment by ashsearle** [comment]
@marwahaha Given the project status, what's the likelihood of merging any PR if @pyemelyanovj2 made one?

**Comment by marwahaha** [comment]
I'm personally nervous about it unless the code footprint is quite small.

**Comment by pyemelyanovj2** [comment]
I mean i haven't made ay fix for that yet, i've just added workaround for it in my code
but i would like to contribute if it's possible
