### ISSUE TITLE
Moment object created before updateLocale() doesn't use changed locale

### ISSUE THREAD

**Issue by louisptremblay** [moment/moment#4269]
**Description of the Issue and Steps to Reproduce:**
EASY to reproduce
https://codepen.io/anon/pen/jGgNoq

If you create the moment object before a call to updateLocale()
The locale change is never taken into account for that object.

```javascript
// January 1
var a = moment('2018-01-01');
// Print 'January' (OK)
document.write(a.format('MMMM'));
// Change 'January' string to 'Test'
moment.updateLocale('en', { months: ['Test'] });
// Should print 'Test', but prints 'January'
document.write(a.format('MMMM'));
// Create a new moment object from original
a = moment(a.format());
// Now correct, prints 'Test'
document.write(a.format('MMMM'));
```

**Environment:**
All environments, moment 2.19.1

**Comment by ashsearle** [comment]
That's working [as documented](https://momentjs.com/docs/#/i18n/):

> This function does not affect moments that already exist.

**Comment by louisptremblay** [comment]
You are right, I missed that
Thanks,
