### ISSUE TITLE
Arabic months names are duplicates 

### ISSUE THREAD

**Issue by Ahmed** [moment/moment#4270]
Hi team:
My team at Google use your library to translate months into a localized version. I noticed during QA that the Arabic months are duplicates for two different regions. 

https://github.com/moment/moment/blob/develop/locale/ar.js#L60-L73

For instance, "كانون الثاني يناير" means "January January". One is for standard Arabic, the other for Levant Arabic. I speak Arabic natively, and this indeed does not look right

Could I create a PR to fix it?

**Comment by trivett** [comment]
👍  on this. Just think of all of the non Arabic speakers who might be showing double months without knowing it!

I agree that `ar` on it's own should have a reasonable default, just as `en` defaults to American English.

**Comment by icambron** [comment]
Sure, will take a PR.

**Comment by trivett** [comment]
Any action on this? Getting this released would be really helpful. Thanks!

**Comment by trivett** [comment]
@marwahaha Hello Kunal. Sorry to prod but it looks like Ahmed's fix got merged into master but somehow overwritten on both v 2.2.0 and on the develop branch. Would it be possible to bring that back in? I would PR it myself but obviously don't know one word from another in Arabic so perhaps a native speaker would be better for that.

**Comment by icambron** [comment]
Reopening while we double check what happened

**Comment by marwahaha** [comment]
Ok, so this happened because the `locale/*` files were edited, not the `src/locale/*` files.

In the future, I'll be more careful when merging PRs -- but it also might help to set up automation to inform contributors!

**Comment by AhmedNourJamalElDin** [comment]
So according to PR, I can't now use the other month names i.e. "كانون الثاني", "شباط".. any idea how to add them?

**Comment by OmarIthawi** [comment]
@AhmedNourJamalElDin the proper fix for using `شباط` (which I really like), is to add another locale e.g. `ar_IQ` or `ar_SY` for country specific locale.

This is a common practice especially for things that vary within the same language:

 - Currency
 - Date format
 - Month names
 - Decimal separators: comma or period
 - Thousands operators: usually comma
 - etc
