### ISSUE TITLE
function is treated as string in Java Rhino

### ISSUE THREAD

**Issue by prasanna-rays** [moment/moment#4272]
**Description of the Issue and Steps to Reproduce:**
I am using momento in a java script which I am running u sing Java Rhino. When using format functionality of momento, it's not giving expected output. I had narrowed down the issue to the following code:
`function addFormatToken (token, padded, ordinal, callback) {
        var func = callback;
        if (typeof callback === 'string') {
            func = function () {
                return this[callback]();
            };
        }
        if (token) {
            formatTokenFunctions[token] = func;
        }
        if (padded) {
            formatTokenFunctions[padded[0]] = function() {
            return zeroFill(func.apply(this, arguments), padded[1], padded[2]);
            };
        };
        if (ordinal) {
            formatTokenFunctions[ordinal] = function () {
                return this.localeData().ordinal(func.apply(this, arguments), token);
            };
        }
    }`

The function _function() { return zeroFill(func.apply(this, arguments), padded[1], padded[2]); };_  is treated as string and so I am getting this as output.

I am using moment version 2.14.1 and Mozilla Rhino version 1.7.6

**Comment by prasanna-rays** [comment]
Can someone please respond to the issue I reported?

**Comment by icambron** [comment]
I don't see an issue reported. An issue looks like "I expect this code to return [something] but it instead returns [some other thing]". I don't know what to do with "here is some Moment code that I believe is responsible for some unstated unexpected output". Please create a new issue with a succinct description of the problem.
