### ISSUE TITLE
moment diff issues involving last week of year.

### ISSUE THREAD

**Issue by dmcmillin** [moment/moment#4273]
**Description of the Issue and Steps to Reproduce:**
 const nMonths = moment(overflow.end. value.split('-')).diff(moment(overflow.start.value.split('-')), 'months', true); start.value =any day within the last week of decemember end.value = any day after the start of the next year. 

*Please include the values of all variables used.*

**Environment:**
jsfiddler.net

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
Fri Oct 27 2017 04:11:11 GMT-0700 (Pacific Daylight Time)
10/27/2017, 4:11:11 AM
420
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
2.19.1

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by icambron** [comment]
When filing an issue it's important to state clearly what the issue is, to demonstrate the issue, and to describe the difference in the behavior you see from the behavior you expect. Please open a new issue that does that.
