### ISSUE TITLE
Chokes on a valid date parse: moment('Sun 07 Jan', 'ddd DD MMM', 'en', true)

### ISSUE THREAD

**Issue by gajus** [moment/moment#4276]
```js
moment('Sun 07 Jan', 'ddd DD MMM', 'en', true).isValid(); => false

```

Expect `true`.

**Comment by davidNHK** [comment]
+1 
`moment.utc('17:01 Tue 20 Sep 2016', 'HH:mm dddd DD MMMM YYYY').isValid(); => false`

**Comment by gajus** [comment]
Your issue is not related. You have your tokens wrong to begin with.

**Comment by icambron** [comment]
Jan 7, 2017 was a Saturday, not a Sunday
