### ISSUE TITLE
Locale aware format key that displays dates in official format

### ISSUE THREAD

**Issue by xeii** [moment/moment#4282]
**Description of the Issue and Steps to Reproduce:**

For example, when comparing Finnish and Swedish official date formats:

`1.1.2018` in Finnish
`2018-01-01` in Swedish

The locale aware formatting key `l` (lowercase L) drops out leading zeroes which produces the correct format for Finnish dates, but incorrect one for Swedish dates. With `L` the problem swings other way around.

moment.js version 2.18.1

**Is there any plans to add formatting key that would produce official date format based on the current culture?**

**Comment by marwahaha** [comment]
What constitutes `official` here? Is there a single accepted way for every language to display dates?

I would be comfortable with a "preferred" date format for each language.

**Comment by xeii** [comment]
"Preferred" would be fine for me. I have to work with finnish, swedish and english locales, at least for those there are "official" date formats. If there is a support for this kind of translation key, each format can then be drive by the community. I think they will know best.

**Comment by ichernev** [comment]
@xeii you need to provide some "official" place which states what is official in each language. CLDR is also a good starting point.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
