### ISSUE TITLE
Moment incorrectly validates times

### ISSUE THREAD

**Issue by alex-zh** [moment/moment#4284]
var time = moment("13:22rrr", 'HH:mm','en', true) 
 time.isValid() //true
 var time1 = moment('03:a5jojojo', 'HH:mm',true)
 time1.isValid() //true
Moment considers these times as valid ones.

**Comment by icambron** [comment]
Are you running an old version of Moment? Both of those returns `false` for me

**Comment by alex-zh** [comment]
Yes, it seems I used old version, current one 2.19 seems works correctly. 

But here it returns true: http://jsfiddle.net/sjdfhftv/

**Comment by icambron** [comment]
👍
