### ISSUE TITLE
Using .fromNow() on moment skips time intervals

### ISSUE THREAD

**Issue by bdbrown4** [moment/moment#4286]
On a moment, using the .fromNow() function, it jumps from '45 minutes ago' to 'an hour ago', skipping 46-59 minutes ago.

**Comment by jlindenger** [comment]
I believe that this is the expected behavior according to [the docs](http://momentjs.com/docs/#/displaying/fromnow/). It groups the description into a number of buckets, with 45 - 89 minutes being summarized as "an hour ago."

**Comment by bdbrown4** [comment]
Thanks for the clarification, seems odd to do that in the shorter time ranges, but oh well. Thanks!

**Comment by bdbrown4** [comment]
This is resolved.
