### ISSUE TITLE
No space after number in relativeTime for zh-cn and zh-tw

### ISSUE THREAD

**Issue by MananS77** [moment/moment#4288]
**While using the relativeTime method, there is no spacing after the number for locales zh-cn and zh-tw**

*zh-cn : https://github.com/moment/moment/blob/develop/src/locale/zh-cn.js#L81

zh-tw : https://github.com/moment/moment/blob/develop/src/locale/zh-tw.js#L79*

*Examples: Chrome 50+on Windows 10, Internet Explorer 10+ on Windows 10*

![image](https://user-images.githubusercontent.com/21033516/32366051-774995da-c0a2-11e7-9888-96ae6a3e766b.png)

**Comment by marwahaha** [comment]
@ben-lin @hehachris @suupic @zenozeng ?

**Comment by ben-lin** [comment]
The code looks fine. It takes the entire argument including the unit, meaning `10天` is what you passed to the lib. @MananS77 do you have the actual code how you used it?

**Comment by marwahaha** [comment]
Closing due to age. Please re-open if this is still an issue.
