### ISSUE TITLE
moment({minutes: 90}).format('H:mm') is Invalid date

### ISSUE THREAD

**Issue by fluxlicious** [moment/moment#4291]
**Description of the Issue and Steps to Reproduce:**
Parse an integer value (e.g. 90) in minutes to H:mm (e.g. 1:30) like so:
```
moment({minutes: 90}).format('H:mm')
```

Apparently this worked in version 2.2.1 (see https://jsfiddle.net/L5cpovk9/) but doesn't seem to work anymore in the latest version (https://jsfiddle.net/bo6xqct1/). I'm always getting Invalid date unless my minutes value is below 60. I get why this is "invalid" cause there can't be more than 59 minutes in an hour, but i assumed "minutes" is for letting moment do the conversion (90 -> hour:1 minute:30) and "minute" is for the actual minute value (0-59). I'm not sure if this is a bug or by design, but de docs could be clearer in the difference between minute and minutes.
Also looking at the minute(s) setter it does mention if you exceed the 0-59 range, it will bubble up to the hour: https://momentjs.com/docs/#/get-set/minute/

**Comment by icambron** [comment]
Yeah, that's not expected to work and only worked before by happenstance. The part that isn't true is this:

 >  i assumed "minutes" is for letting moment do the conversion (90 -> hour:1 minute:30) 

You're constructing a datetime, not a duration; "minutes" is just an alias for "minute". The code is basically abusing the fact that at today at 1:30 in the morning will format to "1:30" as a way of making up for Moment not having a duration formatter. The same hack done right is:

```js
moment.utc().startOf('day').add({ minutes: 90 }).format('H:mm');
```

Here, the 90 minutes really is creating a duration and so it will do what you want.
