### ISSUE TITLE
moment with locales

### ISSUE THREAD

**Issue by hsl1** [moment/moment#4292]
**Description of the Issue and Steps to Reproduce:**
change to PT_PT locale
*Please include the values of all variables used.*

        $(function () {
            $('#timepicker').datetimepicker({
                format: 'LT',
                
        
            })
        });
       
       

**Environment:**

: Chrome 62

**Other information that may be helpful:**

i want to see 24 hour clock and calendar with my local

If you are reporting an issue, please run the following code in the environment you are using and include the output:

the specified value does not conform to the required format HH:mm
```
this appear because it dont user 24 hour clock and also not in my language

Using moment with locales

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by ashsearle** [comment]
Are you using jQuery UI datepicker?  Are you sure this issue is related to moment, and isn't a question about [how to localise jQuery UI datepicker](https://stackoverflow.com/questions/494958/how-do-i-localize-the-jquery-ui-datepicker)?

**Comment by icambron** [comment]
^^
