### ISSUE TITLE
Feature Request: Pass relativeTimeThresholds to humanize() as argument

### ISSUE THREAD

**Issue by TedDriggs** [moment/moment#4295]
_Note:_ PR #4296 has been submitted for this.

**Description of the Issue and Steps to Reproduce:**

1. Have an application which wants to use different `relativeTimeThreshold` values in different parts of its application
1. Call `relativeTimeThreshold` in one part of the application

**Desired:** There is a way to confine those relative time thresholds to that part of the application
**Observed:** The changes are global

# Proposal
Change the signature of `humanize` as follows:

```typescript
export function humanize(withSuffixOrOptions?: boolean | Options): string;

export interface Options {
    withSuffix?: boolean;
    thresholds?: Thresholds;
}

// Define a type with the current set of keys accepted by relativeTimeThreshold
export type Thresholds = typeof thresholds;
```

Within `humanize`, if `withSuffixOrOptions` is an object and it contains a `thresholds` property, that will be used instead of the `var thresholds` defined earlier in the file.

**Comment by rokoroku** [comment]
This feature is good, but I think it's not enough to format duration.

Could we have time unit to includes as options, rather than the thresholds?

e.g. 
```js
moment.duration({ s: 100 }).humanize({ s: true }) // '100 seconds'
moment.duration({ s: 100 }).humanize({ m: true }) // '1 minutes'
moment.duration({ s: 100 }).humanize({ m: true, s: true }) // '1 minutes 40 seconds'
moment.duration({ s: 100 }).humanize({ ms: true }) // '10000 milliseconds'
```

**Comment by TedDriggs** [comment]
This issue describes a scoped means of invoking existing formatting behavior. I’d suggest filing a separate issue for a new formatting behavior that spans multiple units of time.
