### ISSUE TITLE
Month method returns previous month

### ISSUE THREAD

**Issue by ondrejsevcik** [moment/moment#4299]
When I try to use month method on a date in an ISO format, I got a month number from the previous month. It behaves same in all browsers I've tried on my Mac (Chrome 62, Firefox  56, Safari 11).

```js
moment('2016-10-20').month()  // returns 9
moment('2016-10-20').toISOString() // returns "2016-10-19T22:00:00.000Z"
```

My timezone info:
```
Fri Nov 10 2017 20:44:50 GMT+0100 (CET)
10/11/2017, 20:44:50
timeoffset: -60
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
moment version: 2.19.1
```

Thanks for help.

**Comment by mj1856** [comment]
Yes, this is behaving as documented.
http://momentjs.com/docs/#/get-set/month/

The original design of Moment copies several behaviors from the `Date` API, including that months are indexed 0-11.

**Comment by oojacoboo** [comment]
> including that months are indexed 0-11

WTFJS
