### ISSUE TITLE
Year format parsing with strict flag

### ISSUE THREAD

**Issue by Kirill89** [moment/moment#4301]
```javascript
moment('07.17', 'MM.YYYY', true).format(); // => "Invalid date"
```
But according to documentation YYYY is "4 or 2 digit year". Why is it "Invalid date"?

*Environment:*

Google Chrome Version 61.0.3163.100 (Official Build) (64-bit) on Linux Mint 17.3.

```
Sun Nov 12 2017 10:14:31 GMT+0200 (IST)
11/12/2017, 10:14:31 AM
-120
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
2.19.2
```

**Comment by icambron** [comment]
The docs are just totally wrong about this. In strict mode it always matches 4 digits. In general, the documentation does a poor job of describing differences between strict and non-strict parsing.

The real solution is probably to add a `YYY` that always matches 2-4. Then we could describe `YYYY` as just 4 and let the non-strict one just be looser.

**Comment by voltaaage** [comment]
I would be interested in tackling this.

**Comment by voltaaage** [comment]
@icambron If I understand correctly, the fix would be to:
- Update the docs to call out that, in strict mode, YYYY would not match 2 digits
- Add the YYY matcher as you mentioned. 

## Documentation Updates
	- Update the YYYY description in the docs to state: `4 or 2 digit year (4 digits in strict mode)`
	- Alternatively, we can add a bolded statement at the bottom of the `Year, month, and day tokens` to state: `In strict mode, YYYY will only match 4 digit years`. This will also give us room to call out any other matchers which may be similarly affected. 

## YYY Matcher
- The intention behind this matcher is that it is matches both YY and YYYY. 
- Not to be used with strict mode.

### Questions
1. What should happen when you use this matcher with strict mode? Return invalid date?
2. What other considerations need to be made when creating a new matcher? My investigation shows that this will likely involve updating locale support along with standard tests and documentation updates. 
3. How will these changes play along with the upcoming updates to change everything to strict mode by default?

**Comment by icambron** [comment]
Not quite. Here's what I had in mind

 * Change the docs to simply say that YYYY matches 4 digits. Leave it matching 2 or 4 digits in non-strict mode. Non-strict mode matches all sorts of stuff that isn't documented, so this is OK.
 * YYY matches 2 or 4 digits and does the appropriate thing in both strict and non-strict mode. It's just explicit about it.

So on your questions:

 1. It works fine
 2. What additional locale support is required? As far as I know, nothing is required here.
 3. Neatly, I believe: we are preserving the existing behavior of YYYY in strict mode and adding a new option to help the people depending on non-strict mode behavior.

**Comment by OjasM** [comment]
I have made the changes as suggested by @icambron in #4883 . For the new 'YYY' parsing token, I have also created a corresponding format token which formats to 4-digit year strings. I will also update the docs accordingly.

**Comment by KevinAndersonXactly** [comment]
@OjasM is this issue still in need of address?

**Comment by filipecorrea** [comment]
This pull request updates the docs: https://github.com/moment/momentjs.com/pull/621

**Comment by shaedrich** [comment]
There's a similar pr: #610

**Comment by marwahaha** [comment]
Docs are updated.
YYY was rejected in https://github.com/moment/moment/pull/4883
