### ISSUE TITLE
yarn check error! moment v 2.19.2 

### ISSUE THREAD

**Issue by alexeikaratai** [moment/moment#4302]
**Description of the Issue and Steps to Reproduce:**
1. yarn check
   error "react-moment-proptypes#moment" not installed
2. after install  - yarn add react-moment-proptypes 
3. yarn check - not fix this error! 

**Environment:**
node 8.9.0
yarn 1.3.2
npm 5.5.1

**Comment by ichernev** [comment]
I'm sorry, can you describe what you're trying to do. 2.19.2 is a bugfix release, so very unlikely that we broke something package-management related.

**Comment by alexeikaratai** [comment]
@ichernev after upgrade to moment2.19.2! all works fine! but when run 'yarn check' we can see "error "react-moment-proptypes#moment" not installed". But react-moment-proptypes are installed. Thats my problems!

**Comment by mj1856** [comment]
@alexeikaratai - we are just Moment here.  You should check over here: https://github.com/CalebMorris/react-moment-proptypes
