### ISSUE TITLE
Getting last Tuesday... without if conditions

### ISSUE THREAD

**Issue by raptor235** [moment/moment#4304]
I'm trying to get last X day of either current week or previous week... just like php strotime("last tuesday"

Should return the date for the Tuesday last week if you're on the Monday of this week or if it's now Wed you should get Tuesday of this week... 

I'm not sure how to do this without if statements of figuring out if you've passed a specific day of the week already.

**Comment by icambron** [comment]
See the bigger discussion in #2522
