### ISSUE TITLE
Parsed date is considered invalid

### ISSUE THREAD

**Issue by larsnystrom** [moment/moment#4307]
**Description of the Issue and Steps to Reproduce:**
Parsing the date "Thu Nov 2 23:42:48 2017+0000" with format "ddd MMM D HH:mm:ss YYYYZZ" and strict set to true will return an invalid date.

Possible causes:
1. Bug in moments date parsing.
2. (More likely) I'm using the wrong format string, but I swear I've double and triple checked it with the docs.

```
const date = moment("Thu Nov 2 23:42:48 2017+0000", "ddd MMM D HH:mm:ss YYYYZZ", true).locale('en');
console.log(date.isValid()); // Outputs false
```

*Please include the values of all variables used.*
See code.

**Environment:**
Chrome 62 on macOS, Firefox 57 on Ubuntu.
moment version 2.19.2

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
macOS: GMT+0100
Ubuntu: GMT+0100
* The time and date at which the code was run
Thursday Nov 16 around 9:30 am.
* Other libraries in use (TypeScript, Immutable.js, etc)
React, webpack, babel, et al.

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
VM63:1 Thu Nov 16 2017 09:38:34 GMT+0100 (CET)
VM63:2 2017-11-16 09:38:34
VM63:3 -60
VM63:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
VM63:5 Uncaught ReferenceError: moment is not defined
    at <anonymous>:5:13
```
(Moment is used as a module, so it is not available in the global scope, version is 2.19.2)

**Comment by icambron** [comment]
See #4227
