### ISSUE TITLE
add() method returns strange result

### ISSUE THREAD

**Issue by crafter999** [moment/moment#4308]
Tried the following code on the latest Chrome/Firefox browser but there's no actual time update, the date is still the same. I'm using this moment lib: https://cdn.jsdelivr.net/npm/moment@2.19.2/moment.min.js. **Works fine** on my Node.js 9.x.x using the default version of moment. grabbed from the npm package manager.

```
var timer = new moment("2017-11-15 00:00:00")
timer.add(10, "seconds")
// returns: 2017-11-15 00:00:00
```

P.S.
Browser run: moment.min.js  2.19.2
Node.js run: default 2.19.2

**Comment by icambron** [comment]
I just pasted this into the developer console on momentjs.com:

```js
moment("2017-11-15 00:00:00").add(10, 'seconds').format()
"2017-11-15T00:00:10-05:00"
```

So that looks good. I think maybe you're reading the `_i` property off the Moment object? If so, ignore that; that's an implementation detail.

**Comment by marwahaha** [comment]
@crafter999 - to format Moment objects, you can use the API available here: https://momentjs.com/docs/#/displaying/format/ .

Please reopen if you have further issues.
