### ISSUE TITLE
Uncaught TypeError: Moment(...).tz is not a function at <anonymous>:1:10

### ISSUE THREAD

**Issue by grrttmrtn** [moment/moment#4313]
Attempting to test some timezone conversions in chrome console and I've imported moment.js, moment-with-locales.js, and moment-timezone-with-data.js with the same problem. I can run moment.version and come back with 2.19.2

When I try running moment().tz('America/Chicago').format('M') I get the uncaught error.

moment.version
"2.19.2"
moment().tz('America/Chicago').format('hh:mm:ss z')
VM5252:1 Uncaught TypeError: moment(...).tz is not a function
    at <anonymous>:1:10

Not 100%, but fairly sure this happened after the newest Chrome update - Version 62.0.3202.94 (Official Build) (64-bit) - Windows 7

Mon Nov 20 2017 16:11:52 GMT-0600 (Central Standard Time)
VM5257:2 11/20/2017, 4:11:52 PM
VM5257:3 360
VM5257:4 Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by laf1greg** [comment]
Same problem here.  After updating my packages to : 
"moment": "^2.19.4",
    "moment-timezone": "^0.5.14",
    "react": "^16.2.0",
    "react-bootstrap": "^0.31.5",
    "react-cookie": "^1.0.4",
    "react-dom": "^16.2.0",
    "react-flip-move": "^2.10.0",
    "react-moment": "^0.6.8",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "redux": "^3.7.2",
    "redux-form": "^7.2.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"

**Comment by laf1greg** [comment]
Sorry works now : had to do " import moment from 'moment-timezone'; " instead of " import moment from 'moment';"

**Comment by marwahaha** [comment]
@grrttmrtn - did @laf1greg 's solution work for you ?

**Comment by rhymes** [comment]
This worked for me:

```js
import 'moment-timezone/builds/moment-timezone-with-data-2012-2022';
import moment from 'moment-timezone';
```

Using moment 2.20.1 and moment-timezone 0.15.4

**Comment by marwahaha** [comment]
Closing due to age. If there are still problems please re-open.

**Comment by kheengz** [comment]
If you're using Node.js, you may accidentally be using

`const moment = require('moment'); //moment`

instead of

`const moment = require('moment-timezone'); //moment-timezone`

Also, make sure you have installed moment-timezone with

`npm install moment-timezone --save`
