### ISSUE TITLE
    moment.locale('de');  not working with minified moment-with-locales.min.js

### ISSUE THREAD

**Issue by pmbert** [moment/moment#4315]
with moment-with-locales.js it's working.
Version 2.19.2

**Comment by cmyers** [comment]
Did a quick test with [jsfiddle](https://jsfiddle.net/t5atvvsb) using moment-with-locales.min.js 2.19.2 and it appears to be working as expected. What seems to be the issue you're having?

**Comment by pmbert** [comment]
You are right. There's no difference, both are working. I was only irritated, because switching to locales is only working always after the second call after restart. But this maybe not an issue of moment but of chart.js? Anyway, I don't know how I can change this.
