### ISSUE TITLE
moment.max moments[i].isValid is not a function

### ISSUE THREAD

**Issue by Diluka** [moment/moment#4316]
**Description of the Issue and Steps to Reproduce:**

`moment.max(moment(),new Date())`

**happens when last parameter is not moment**

```
global.js:2673 Uncaught TypeError: moments[i].isValid is not a function
    at pickBy (global.js:2673)
    at Function.max (global.js:2690)
    at <anonymous>:1:8
```

**Environment:**
any

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
```
Wed Nov 22 2017 15:26:08 GMT+0800 (CST)
VM97:2 2017/11/22 下午3:26:08
VM97:3 -480
VM97:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
VM97:5 2.19.2
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by ashsearle** [comment]
What behaviour are you expecting?

The [method signature for max](https://momentjs.com/docs/#/get-set/max/) says it takes 1 or more Moment instances - so a `Date` instance isn't valid here.

**Comment by Diluka** [comment]
So the built-in typing is wrong?
https://github.com/moment/moment/blob/03073778ec18ee38e179208cd1af899e8d1848dc/moment.d.ts#L688
https://github.com/moment/moment/blob/03073778ec18ee38e179208cd1af899e8d1848dc/moment.d.ts#L400
