### ISSUE TITLE
end of year + toISOString is wrong

### ISSUE THREAD

**Issue by pencilcheck** [moment/moment#4318]
**Description of the Issue and Steps to Reproduce:**

```
const start = moment('2011-10-05T22:26:12-04:00').endOf('year').toISOString();
console.log(start);
```

Example codepen:
https://codepen.io/anon/pen/xPjdzw?editors=1111

Expected value:
`2012-01-01T03:59:59.999Z`

*Please include the values of all variables used.*

**Environment:**

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*
Codepen

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

```
Wed Nov 22 2017 11:48:01 GMT-0800 (PST)
11/22/2017, 11:48:01 AM
480
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/605.1.13 (KHTML, like Gecko) Version/11.1 Safari/605.1.13
2.19.2
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by brion-fuller** [comment]
Hello,

If you would like to work in other timezone's besides local time or UTC please refer to moment-timezone.
Expected result in your current case would be "2012-01-01T07:59:59.999Z" as this is the difference in offset from your localtime and utc.

**Comment by marwahaha** [comment]
`moment()` really functions like a `moment.local()`: It parses the datetime and represents it in your local timezone. So, `.endOf('year')` will set it to the last instant before the new year in your timezone.

If you're looking for the date in UTC, try using `moment.utc()`. 

If you need more granularity, as @brion-fuller mentioned, you can use moment-timezone.

Please reopen if you have further questions!
