### ISSUE TITLE
Greetings API with I18n language support [New Feature Recomendation]

### ISSUE THREAD

**Issue by kt-12** [moment/moment#4319]
It has been while I am searching for a way to greet my client (Good Morning, Good Evening etc ) based on their system timing and the language of the site they are viewing.

So,

- I can pass in the language code and the function will return me the greeting text based on the system time.
- I can pass in the language code and time ant the function will return a greeting text.

**Comment by marwahaha** [comment]
I think this is a great idea for a plugin, but I'd prefer not to have this in the core Moment.js codebase. What do you think?

You may want to look at the other plugins here: https://momentjs.com/docs/#/plugins/

If you develop a plugin, we can probably include it on the page I linked.
