### ISSUE TITLE
isSame function return different result when it's type of first parameter is number or string

### ISSUE THREAD

**Issue by JChehe** [moment/moment#4322]
**Description of the Issue and Steps to Reproduce:**
```
moment('2017-11-26').isSame('2017', 'year') // true
moment('2017-11-26').isSame(2017, 'year') // false
```

**Environment:**
Chrome 62.0.3202.94 on OSX

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString()) // Sun Nov 26 2017 14:12:45 GMT+0800 (HKT)
console.log((new Date()).toLocaleString()) // 2017/11/26 下午2:12:45
console.log( (new Date()).getTimezoneOffset()) // -480
console.log( navigator.userAgent) // Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
console.log(moment.version) // 2.19.2
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by ashsearle** [comment]
That's expected behaviour.

The 1st parameter to `isSame` is converted to a moment.  `moment(2017)` is different to `moment('2017')`.

(Under the covers you can compare the result of `new Date('2017')` vs `new Date('2017')` and see that the first results in Jan 1st 2017, while the second results in a date in 1970)

**Comment by marwahaha** [comment]
Perhaps the docs can be more clear that the first parameter of `isSame` (or others like it) will be parsed as a Moment object, if not already. We would happily take a PR on this (@JChehe or others)
