### ISSUE TITLE
Localized date without the year

### ISSUE THREAD

**Issue by mschipperheyn** [moment/moment#4325]
Sometimes you want to be able to show a localized date without the year.
E.g.
en - Nov 19 
du - 19 nov

A common scenario is in newsfeeds, where you will generally show the year only when it isn't the current one, e.g.:
- Just now
- 2 days ago
- Nov 17, 12:18PM
- Nov 2, 2016 12:28AM

This is currently not supported as a default format. A discussions about it can be seen here: https://stackoverflow.com/questions/27360102/locale-and-specific-date-format-with-moment-js 

IMHO the `moment().format('l');` would be the ideal candidate for this, since the current representation `11/27/2017` is out of sync with the 'l' style representations that all include the name of the month in some way.

**Comment by nightwolf13** [comment]
+1
Also need localized date without a year.. (It could be applicable in any scenario when we need to show some dates in the current year )..

**Comment by DannyvdSluijs** [comment]
Could use the twitter style (d mmm) format.

**Comment by TimotheeJeannin** [comment]
Would be nice to have this !

**Comment by beshanoe** [comment]
I don't think there is a trivial solution for that, it either require editing of every locale file to add new so-called "long date format" or you can use regexp to get rid of year in place like I did:
```ts
const noYearLocaleFormat = moment
  .localeData()
  .longDateFormat('L')
  .replace(/[,\/-/.]*\s*Y+\s*/, '')
```
But there's no garanty that it will work on every locale, though it you have finite amout of locales supported(like I do), you can at least test it.

**Comment by ichernev** [comment]
@mschipperheyn unfortunately the current moment interface does not allow for granual specification of what units to include, exclude in a locale friendly way.

A proper/good way to handle this is something similar to the Intl API: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

We're open to suggestions/PRs on that front, but we're **NOT** making minor tweaks to existing locale setup just because someone has a pecurliar use case. Nothing personal, its just that the current system requires exponential amount of data to function for every possible use case, and this is just not the way to go forward.

**Comment by SirHodlington** [comment]
I also need this

**Comment by kid1412621** [comment]
if native support for formatting to hide current year only would be better.

**Comment by AldonIsenberg11** [comment]
Yeah just ran into this also

**Comment by alexander-elgin** [comment]
You can use [toLocaleDateString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString) method of JS Date. E.g.

```
const getFormattedDateTime = dateTime => dateTime.toLocaleDateString('ru-RU', {
  month: 'short',
  day: 'numeric',
  hour: 'numeric',
  minute: 'numeric',
})
```

**Comment by iec989** [comment]
> ```js
> .split(',')[0]
> ```

That would only work with English - In Spanish it looks like: 3 de Octubre de 2020; I guess I will do my own with i18n

**Comment by AldonIsenberg11** [comment]
> > Yeah just ran into this also, my solution for javascript:
> > ```js
> > moment().format('ll').split(',')[0]
> > ```
> > 
> > 
> > output:
> > `Apr 7`
> 
> That would only work with English @AldonIsenberg11 - In Spanish it looks like: 3 de Octubre de 2020; I guess I will do my own with i18n

Post the spanish solution you come up with here. 

This is an open source project so posting "your solution doesn't work for..." doesn't help anyone. Following up with a solution however will help several people.

**Comment by Programero** [comment]
moment.localeData().longDateFormat('ll')
.replace(/Y/g, '') // to replace all YYYY
.replace(/\[.*?\]/g, '') // to replace all [h] [de]...
.replace(/\s+/g, ' ') // to convert multiple spaces to one space
.replace(/[^\w\s]|\s+$/g, ''); // to remove non-word characters like ',' , '|' , '-' ....

**Comment by gauravbharat** [comment]
Following worked for me (ES2022 in Angular 17) - 

`
// set locale
moment.locale(locale); // where locale is any valid supported string e.g. 'en', 'es', 'pt', 'fr', etc.

//check that not past year
const now = moment(new Date().toJSON());
const blogDate = moment(v.date); // where v.date is your UTC date input e.g. '2024-02-01T13:36:47.615Z'
const pastYear = now.year() > blogDate.year();
const differenceDays = now.diff(blogDate, 'days');

const date =
            differenceDays > 7
              ? blogDate.format(pastYear ? 'll' : 'MMM DD')
              : blogDate.startOf('day').fromNow();
console.log('date', date);
`

See it live here - https://gaurav.web-developer.in/en/blog
