### ISSUE TITLE
cannot create date object from date strings without leading 0 in day in Safari and IE

### ISSUE THREAD

**Issue by botondev** [moment/moment#4329]
**Description of the Issue and Steps to Reproduce:**
In IE and Safari try to run this code
new moment("2018-12-7")

*Please include the values of all variables used.*
"2018-12-7"

**Environment:**
Latest IE and Safari

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
UK London UTC-0
* The time and date at which the code was run
28/22/2017
* Other libraries in use (TypeScript, Immutable.js, etc)
jQuery

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
-> Tue Nov 28 2017 15:12:55 GMT+0000 (GMT Standard Time)
console.log((new Date()).toLocaleString())
->‎28‎/‎11‎/‎2017‎ ‎15‎:‎12‎:‎55
console.log( (new Date()).getTimezoneOffset())
-> 0
console.log( navigator.userAgent)
-> Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko
console.log(moment.version)
-> 2.19.1
```

Note: Unfortunately I do not have access to a Safari at this moment other then a phone and tablet

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by ashsearle** [comment]
The date's not in ISO or RFC2822 format, and you haven't provided a format string to use to parse the date.

The constructor falls back to parse the date via `new Date(string)` - and the supported formats will vary from browser to browser.

This is documented behaviour.

**Comment by marwahaha** [comment]
I agree with ashsearle. 

In Safari:
```
> moment("2018-12-7").isValid()
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
...
< false
> moment("2018-12-7", "YYYY-MM-D").isValid()
< true
```

The docs have a ton more info about how to parse dates in Moment.js 
http://momentjs.com/docs/
