### ISSUE TITLE
How to edit style of text in moment-timezone ?

### ISSUE THREAD

**Issue by kilaniba** [moment/moment#4340]
I created a time of zone by `moment.tz(id_zone).hour(v).format('hh:mm:ss a')` .I want to handle this time , for example , the hour displayed on a big size and minute on small size . Please is it possible with moment and moment-timezone ?

**Comment by ashsearle** [comment]
Hello, I think you'll find you get a faster response to this type of question at [stackoverflow](https://stackoverflow.com/).

github issues are normally used for people to report and discuss bugs and feature requests, not as a general advice forum.
