### ISSUE TITLE
Converting a string literal date to utc and formatting result in previous day

### ISSUE THREAD

**Issue by jangedoo** [moment/moment#4342]
**Description of the Issue and Steps to Reproduce:**
When a date from is passed to moment constructor and is converted to utc time and then formatted with "YYYY-MM-DD", it returns a string representation of previous date.
I'm not sure if this is intended or a bug but I can't seem to understand the behaviour behind this. 

*Please include the values of all variables used.*
Here is the full code. I expect it to return "2017-12-12" but it returns "2017-12-11"
console.log(moment("2017-12-12").utc().format("YYYY-MM-DD"))

**Environment:**
NodeJS v8.5.0 on Windows 10
Chrome 62.0 on Windows 10

**Other information that may be helpful:**
Timezone: Berlin time (UTC+1)
Date of execution: 2017-12-5 (y-m-d)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
- Tue Dec 05 2017 18:28:02 GMT+0100 (W. Europe Standard Time)
- 12/5/2017, 6:28:02 PM
- -60
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
- 2.2.1

**Comment by neroux** [comment]
By omitting the time it defaults to midnight, which - based on your timezone - is 11pm GMT, which is the previous day.

Dont convert it to UTC to avoid that.

**Comment by jangedoo** [comment]
Got it. Thanks.
