### ISSUE TITLE
Feature request: Formatting duration in multiple time units

### ISSUE THREAD

**Issue by rokoroku** [moment/moment#4344]
**Description of the Issue and Steps to Reproduce:**
It's a subsequent feature request for #4295 

1. #4295 will add support to format duration in `momentjs`' existing relative formatting behavior. 
2. Formatting duration via `.humanize()` could be also achieved with multiple time units. e.g.
 
```js
moment.duration({ s: 100 }).humanize({ s: true }) // '100 seconds'
moment.duration({ s: 100 }).humanize({ m: true }) // '1 minute'
moment.duration({ s: 100 }).humanize({ m: true, s: true }) // '1 minute 40 seconds'
moment.duration({ s: 100 }).humanize({ ms: true }) // '10000 milliseconds'
```

**Comment by marwahaha** [comment]
This is pretty cool!

**Comment by ichernev** [comment]
@rokoroku how would you handle unit "holes", like `{years: true, seconds: true}`. Provide more info on edge cases and we can discuss the proposal.

**Comment by rokoroku** [comment]
https://github.com/moment/moment/blob/2e2a5b35439665d4b0200143d808a7c26d6cd30f/src/locale/en-au.js#L29-L44

Since moment already has locale strings for each time units, we can compose the duration with existing unit strings by mathematical modulo and floor function.

**Comment by Alanscut** [comment]
@ichernev I'm very interested in this proposal! I also read the source code, but as you said, there are "vulnerabilities" in the processing unit. I checked issue #2928, The same is true here. Can we use the idea of `asmonths` for reference to calculate and obtain the value of milliseconds, and then use mathematical modulus(remainder)  and floor operation?  Do we need to consider the threshold?Personally, they should be mutually exclusive. Could you please provide direction on this  :)?

**Comment by Pearce-Ropion** [comment]
I was actually looking for something like this recently. I ended up just writing my own helper function to do this. Maybe this code would help someone implement this in the future. @ichernev Could you explain what you mean by unit "holes"?

```javascript
import _ from "lodash";
import moment from "moment";

/**
 * @function formatDuration
 * @description Formats a number representing a duration to a humanized version
 * of said duration.
 *
 * @example duration = 90
 *  durationUnit = "minutes"
 *  result = 1 Hour 30 Minutes
 *
 * @param {Number} duration
 * @param {Object} options
 * @property {String} [durationUnit = "minutes"]
 * @property {Boolean} withWeeks - return the number of weeks in the duration.
 *       @example: 1 Month 3 Weeks 2 Days vs 1 Month 23 Days
 * @property {Boolean} useAnd - formats the last unit to be preceded by the word "and"
 * @property {Boolean} [capitalize = true] - capitalize the duration unit string
 *
 * @returns {String} Formatted duration
 */
export const formatDuration = memoize(
    (
        duration,
        { durationUnit = "minutes", withWeeks, useAnd, capitalize = true } = {}
    ) => {
        const units = [
            "year",
            "month",
            "week",
            "day",
            "hour",
            "minute",
            "second",
            "millisecond",
        ];

        const d = moment.duration(duration, durationUnit);

        const segments = units
            .map(unit => {
                let value = d.get(unit);

                if (withWeeks && unit === "day") {
                    value = value % 7;
                }

                if (value > 0) {
                    if ((unit === "week" && withWeeks) || unit !== "week") {
                        let unitString = capitalize ? _.capitalize(unit) : unit;
                        if (value > 1) {
                            unitString = `${unitString}s`;
                        }
                        return `${value} ${unitString}`;
                    }
                }
            })
            .filter(Boolean);

        if (useAnd) {
            const head = _.initial(segments);
            const tail = _.last(segments);
            return `${head.join(" ")} and ${tail}`;
        }

        return segments.join(" ");
    }
);
```

**Comment by marwahaha** [comment]
Unfortunately we will not take any new features.

See https://momentjs.com/docs/#/-project-status/
