### ISSUE TITLE
method add

### ISSUE THREAD

**Issue by lixinchuang** [moment/moment#4348]
moment('2017-12-10').add(9,'days')

the result  is wrong

**Comment by marwahaha** [comment]
Could you provide more information?

**Comment by lixinchuang** [comment]
![themoment](https://user-images.githubusercontent.com/13194227/33981011-29555d1e-e0e6-11e7-8993-f4e5c9ecb958.png)

**Comment by marwahaha** [comment]
I recommend reading more of the documentation.
https://momentjs.com/docs/#/displaying/format/

Try comparing 
```
moment('2017-12-10').format()
```
with
```
moment('2017-12-10').add(9,'days').format()
```

**Comment by lixinchuang** [comment]
Thanks, But this way is so trouble， do you think so?

**Comment by marwahaha** [comment]
It all depends on what you are trying to do.

There are some guides available here: https://momentjs.com/guides/
