### ISSUE TITLE
[locale] en-au: wrong first day of week

### ISSUE THREAD

**Issue by tmoschou** [moment/moment#4349]
Sunday is considered the first day of the week in Australia and as specified in the latest Unicode CLDR (Common Locale Data Repository) 32.0. Currently moment has this as Monday.

See 

* http://unicode.org/repos/cldr/trunk/common/supplemental/supplementalData.xml 
  ```
  <firstDay day="mon" territories=" 001 AD AI AL AM AN AT AX AZ BA BE BG BM BN BY CH CL CM CR CY CZ DE DK EC EE ES FI FJ FO FR GB GE GF GP GR HR HU IS IT KG KZ LB LI LK LT LU LV MC MD ME MK MN MQ MY NL NO NZ PL PT RE RO RS RU SE SI SK SM TJ TM TR UA UY UZ VA VN XK"/>
  <firstDay day="fri" territories="BD MV"/>
  <firstDay day="sat" territories="AE AF BH DJ DZ EG IQ IR JO KW LY MA OM QA SD SY"/>
  <firstDay day="sun" territories=" AG AR AS AU BR BS BT BW BZ CA CN CO DM DO ET GT GU HK HN ID IE IL IN JM JP KE KH KR LA MH MM MO MT MX MZ NI NP PA PE PH PK PR PY SA SG SV TH TN TT TW UM US VE VI WS YE ZA ZW"/>
  <firstDay day="sun" territories="GB" alt="variant" references="Shorter Oxford Dictionary (5th edition, 2002)"/>
  ```
* https://github.com/unicode-cldr/cldr-core/blob/32.0.0/supplemental/weekData.json#L73

I have not checked whether other locales first day of week is inconsistent with CLDR.

**Steps to Reproduce:**
```
import * as moment from 'moment';
import 'moment/locale/en-au';
moment.locale('en-au');
console.log(moment.localeData().firstDayOfWeek());
```

Expected Behaviour: Outputs `0`
Actual Behaviour: Outputs `1`

**Comment by AlexanderEllis** [comment]
I'd be more than happy to open a PR to fix this issue!

As a non-Australian though, I'm far from an expert on Australian week days.  After a quick search, I saw that Australia follows ISO 8601, specifically AS ISO 8601-2007, and ISO 8601 defines Monday as the first day of the week.  Is Sunday widely considered the first day, but officially Monday is the first day?  This might open a bigger question as to how moment should handle this, but I'd be interested in hearing what you think.

**Comment by marwahaha** [comment]
thoughts @jarcoal ?

**Comment by tmoschou** [comment]
Hmm. I just read the preface to AS ISO 8601-2007 (full version I can't get hold of freely) which states

> The objective of this Standard is to provide **database designers and users with applicable
interchange formats** for representation of dates in the Gregorian calendar, times in the 24 hour
timekeeping system, time intervals and recurring time intervals or of the formats of these
representations used for information interchange. 

As an Australian software engineer, I can attest that ISO 8601 is used in the IT profession but I would not think as a standard for Australian Locale - The closest guidance I could find on this was CLDR. For instance dates are almost never shown in ISO 8601 format to users but as dd/mm/yyyy (or longer form variants) but rarely yyyy-mm-dd and especially not in print (e.g. government forms).

Calendars (hard print) in Australia for instance generally have 'Sunday' first column. Soft copy do too (by default - of course always changeable be user preferences) but they are generally based off CLDR or moment and a504a81f6b0aaacf4460da9b9a30d60b95ad2190 didn't enlightenment to how moment came to its decision, whether it was based off AS ISO 8601-2007 or a copy-paste (E.g. en-gb may have been the basis, which Australia follows very similar except perhaps on first day of week).

**Comment by jarcoal** [comment]
@marwahaha I don't have any expertise on this, so I'll defer to the OP.

I believe I originally proposed/added `en-au` because I had some Australian users who mentioned that the `en-gb` locale wasn't sufficient as they didn't use a 24h time formatting in Australia.

**Comment by marwahaha** [comment]
@tmoschou - CLDR is typically a good reason to us. If @jarcoal is ok with it, can we list you as another author on the `en-au` file? that way, we can reach out if there are other questions.
https://github.com/moment/moment/blob/develop/src/locale/en-au.js

If that sounds good, feel free to make a PR changing this to Sunday and adding yourself as an author.

**Comment by mechamoth** [comment]
Chiming in with anecdata: I'm Australian working in Australia. A straw poll of the office says 8/8 people say Monday is the first day of the week. 2 of us thought that "officially" it was Sunday, but when pressed on what "officially" meant, both agreed that it doesn't really mean anything and that for all intents and purposes they use Monday.

**Comment by akirayamamoto** [comment]
Even government websites vary a lot: https://www.google.com.au/search?rlz=1C1CHBF_en-GBAU776AU776&biw=1645&bih=954&tbm=isch&sa=1&ei=sL0EW9akG4iR8wXAzK2ACw&q=calendar+2018+site%3Agov.au&oq=calendar+2018+site%3Agov.au&gs_l=img.3...29076.33730.0.33968.13.12.0.0.0.0.358.1627.0j3j3j1.7.0....0...1c.1.64.img..6.1.201...0j0i8i30k1j0i24k1.0.u1T7n3dA2VU#imgrc=FLVJXZlPOH792M:

**Comment by ichernev** [comment]
This is a recurring issue in moment. In general we side with CLDR, in practice I'd advice all interested parties to patch the locales they way they see fit (esp if you're developing a one-locale-targeting application).

**Comment by marwahaha** [comment]
We will move forward with this change to align with CLDR.

**Comment by kladnik** [comment]
@marwahaha Moment also returns the incorrect first day of the week for few others as well.
`en_DE` -> Sunday (should be Monday)
`en_SI` -> Sunday (should be Monday)
Android and iOS both return Monday for selected locales and this looks like it's a bug.

**Comment by marwahaha** [comment]
@kladnik Sure, and please tag the respective locale authors (at the top of the locale file in `src/locale/`).

**Comment by C6H7NO2** [comment]
This was an entirely wrong move. Monday, and only Monday is officially the first day of week in Australia. Yes, there are plenty of customary usage with Sunday, just like many still use feet for human height, but this is WRONG. All official planning, including week numbering, rely on Monday being the first day.

**Comment by sam-s4s** [comment]
@C6H7NO2 is correct. Monday is Australia's official start of week day.

It should have never been changed to Sunday, on either Unicode CLDR or moment.

Australia adheres to ISO 8601-2007 (and in turn, ISO 8601) - which clearly states Monday is the first day of the week.

This can be verified in many places, but here is the wikipedia for easy reading:
https://en.wikipedia.org/wiki/ISO_8601
Note the inclusion of Australia under the "Adoption as national standards" section.

And the definition "[D] is the weekday number, from 1 through 7, beginning with Monday and ending with Sunday."

For a brief period, in the official Unicode Common Locale Data Repository (CLDR), Australia's start day was incorrectly changed to Sunday due to a misunderstanding (basically some people put in requests to change it to Sunday, with no actual research or facts to back it up, and it was for some reason changed, accepted without scrutiny). But after the following case, it was changed back to Monday, which is correct.

https://unicode-org.atlassian.net/browse/CLDR-14795

Sadly, during the time that someone mistakenly change the Unicode entry to Sunday, moment used that repository for it's versions after 2.25.3 - which is the version we're stuck on because of this problem.
And now because it is deprecated, it looks like there will never be a "correct" version of moment released ever again :(
(we're moving to Luxon though, so, oh well...)
