### ISSUE TITLE
Wrong codes for weekdaysMin and/or weekdaysShort

### ISSUE THREAD

**Issue by sja-odoo** [moment/moment#4353]
Why these all three are same ?
weekdays, weekdaysShort and weekdaysMin ??

https://github.com/moment/moment/blob/fea48bb69eda8c0459915d6aa66a910a4d43a55b/locale
/km.js#L16

https://github.com/moment/moment/blob/fea48bb69eda8c0459915d6aa66a910a4d43a55b/locale/km.js#L17

https://github.com/moment/moment/blob/fea48bb69eda8c0459915d6aa66a910a4d43a55b/locale/km.js#L18

**Comment by ashsearle** [comment]
That's how the locale has been defined since it was added in [PR 1544](https://github.com/moment/moment/pull/1544)

Please share your suggestions (or raise a PR) for alternative `weekdaysShort` and `weekdaysMin` values.

**Comment by sja-odoo** [comment]
I found references from here,
https://github.com/nuxeo/nuxeo.github.io/blob/master/api-playground/packages/intl/src/data/dates/symbols/km.json

https://github.com/jnorthrup/gwt/blob/master/gwt-user/src/main/java/com/google/gwt/i18n/client/constants/DateTimeConstantsImpl_km.properties#L19

**Comment by kruyvanna** [comment]
@sja-odoo 
It's hard to decide. In Khmer, we rarely see short versions of weekdays.

The ref
https://github.com/jnorthrup/gwt/blob/92873b0875b53d77820b62b29d0687590a078d85/gwt-user/src/main/java/com/google/gwt/i18n/client/constants/DateTimeConstantsImpl_km.properties#L19

is acceptable though.

It would be nice if you can raise your use-case and see which one works best.

**Comment by sja-odoo** [comment]
@kruyvanna 
I'm not familiar Kmer language, So you can decide what suits best for it...

**Comment by kruyvanna** [comment]
ok. will survey some friends for input

**Comment by sja-odoo** [comment]
Hello @kruyvanna any updates on this?

**Comment by kruyvanna** [comment]
@sja-odoo I've been busy lately. I'll be able to update in a few days.

**Comment by kruyvanna** [comment]
@sja-odoo decided and made a pull request. Plus added translation to AM/PM

**Comment by sja-odoo** [comment]
@kruyvanna Thanks :+1:

**Comment by kruyvanna** [comment]
@sja-odoo You're welcome

**Comment by marwahaha** [comment]
addressed by https://github.com/moment/moment/pull/4392
