### ISSUE TITLE
Not right when call calendar occasionally

### ISSUE THREAD

**Issue by huiop368** [moment/moment#4354]
moment(1513069478736).calendar()    //  Last Tuesday at 5:04 PM
But 
new Date(1513069478736)   // Tue Dec 12 2017 17:04:38 GMT+0800 (CST)

Should not be  ** Last Tuesday **, should be ** Tuesday **

moment version is 2.19.3 

and I am in China

**Comment by marwahaha** [comment]
Is this related to #4097 or #4149 ?

**Comment by huiop368** [comment]
oh, yes,  thanks much

**Comment by marwahaha** [comment]
cool. closing as duplicate of #4097
