### ISSUE TITLE
Moment is trying to make sense of string that doesn't match format

### ISSUE THREAD

**Issue by muhammadfaizan** [moment/moment#4355]
**Description of the Issue and Steps to Reproduce:**
I have provided invalid date string that doesn't match format, yet moment parses it to a date that is not desired.

**moment-timezone**
_Version 0.5.13_

```
const moment = require('moment-timezone');

let format1 = 'YYYY-MM-DD'
let format2 = 'DD-MM-YYYY'
let date1 = '01-01-2017'
let date2 = '2017-01-01'
moment(date1, format1) // moment("2001-01-20T00:00:00.000")
moment(date1, format2) // moment("2017-01-01T00:00:00.000")
moment(date2, format1) // moment("2017-01-01T00:00:00.000")
moment(date2, format2) // moment("2001-01-20T00:00:00.000")
```

**Environment:**
_Node.js: v8.9_

Linux & Windows Environment ( easily replicable in all environments)

**Other information that may be helpful:**
* Tried on UTC timezone also 
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

**Comment by ashsearle** [comment]
Use [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/) to avoid this problem:

```js
moment(date1, format1, true) // Invalid date
moment(date1, format2, true) // moment("2017-01-01T00:00:00.000")
moment(date2, format1, true) // moment("2017-01-01T00:00:00.000")
moment(date2, format2, true) // Invalid date
```

**Comment by marwahaha** [comment]
Closing, since there is a solution (Thanks @ashsearle !)
