### ISSUE TITLE
'YY' formatted dates wrap around to 1900's

### ISSUE THREAD

**Issue by BBlayne** [moment/moment#4356]
**Description of the Issue and Steps to Reproduce:**
When accepting a date formatted as MM-YY or MM/YY, is After/isBefore will return incorrect values for years ending in 69 and above. 01/68 is 2068, but 01/69 is 1969.

1. Create a script that accepts as user input a valid date in MM-YY or MM/YY.
2. Compare the inputted value with the current date/time using IsBefore/IsAfter/FromNow()
3. Return the results to the console.

*Please include the values of all variables used.*
Current date.
values 01/68 to 01/99

**Environment:**
Chrome: Version 63.0.3239.84 (Official Build) (64-bit)
OS: Windows 10 64bit
Using validatejs library.

```js
        txtCreditCardExpiry: {
			presence: {
				message: "^Cannot be blank"
			},
			datetime: function(value, attributes, attributeName, options, constraints) {
				if (value) {
					if (moment(value, "MM-YY", true).isValid() || moment(value, "MM/YY", true).isValid())
					{	
						console.log(moment(value, "MM-YY").utc().toString() + ": is " + moment(value, "MM-YY").utc().fromNow());
						if (moment(moment(), "MM-YY").utc().isAfter(moment(value, "MM-YY").utc()))
						{
							console.log(moment().utc().toString() + ", is after " + moment(value, "MM-YY").utc().toString());
							return {
								expiryOnly: true,
								message: "^Is expired"
							}
						}
						else {
							console.log(moment().utc().toString() + ", is before " + moment(value, "MM-YY").utc().toString());
							return null;
						}										
					}						
					else 
					{
						return {
							dateOnly: true,
							expiryOnly: true,
							message: "^Not a valid date"
						}
					}
				}
			}
        }
```

**Comment by ashsearle** [comment]
I believe this is behaving as documented in a section on [Parsing two digit years](https://momentjs.com/docs/#/parsing/string-format/) - quoting:

> By default, two digit years above 68 are assumed to be in the 1900's and years 68 or below are assumed to be in the 2000's

That section also shows how to change the behaviour, and (I guess) do what you want - to treat ALL 2-digit years as though they're in the 2,000's:

```js
moment.parseTwoDigitYear = function(yearString) {
    return parseInt(yearString) + 2000;
}
```

**Comment by BBlayne** [comment]
Thanks!
