### ISSUE TITLE
[locale] bo: Add bo-IN locale and align bo with CLDR

### ISSUE THREAD

**Issue by JLHwung** [moment/moment#4369]
According to Unicode CLDR ([here](http://www.unicode.org/repos/cldr/tags/release-32-0-1/common/main/bo.xml)), the `bo` will have dateFormat as
```xml
<availableFormats>
<dateFormatItem id="GyMMM">G y LLLL</dateFormatItem>
<dateFormatItem id="MMMd">MMMཚེས་d</dateFormatItem>
<dateFormatItem id="MMMEd">MMMཚེས་d, E</dateFormatItem>
<dateFormatItem id="MMMMd">MMMMའི་ཚེས་d</dateFormatItem>
<dateFormatItem id="yMMM">y LLL</dateFormatItem>
<dateFormatItem id="yMMMd">y ལོའི་MMMཚེས་d</dateFormatItem>
<dateFormatItem id="yMMMMd">སྤྱི་ལོ་y MMMMའི་ཚེས་d</dateFormatItem>
</availableFormats>
```
which is `bo-CN` actually from the YMD dateFormat order. The current `longDateFormat` of `bo`,

```js
longDateFormat : {
        LT : 'A h:mm',
        LTS : 'A h:mm:ss',
        L : 'DD/MM/YYYY',
        LL : 'D MMMM YYYY',
        LLL : 'D MMMM YYYY, A h:mm',
        LLLL : 'dddd, D MMMM YYYY, A h:mm'
    }
```
corresponds to `bo-IN` after I review the DMY date format on [CLDR hi](http://www.unicode.org/repos/cldr/tags/release-32-0-1/common/main/hi.xml).

I suggest we rename `bo` locale to `bo-IN` and align `bo` date accordingly.

This will break locale name compatibility and we should document that the user of `bo` locale should choose between `bo` and `bo-IN`.
 
cc @vajradog

**Comment by marwahaha** [comment]
closing as part of https://github.com/moment/moment/issues/4949
