### ISSUE TITLE
Wrong result related by 'weeks' in 2017-12-31.

### ISSUE THREAD

**Issue by kimtis** [moment/moment#4374]
```
var t = moment('2017-12-31', 'YYYY-MM-DD');

t.format('YYYYw');  // '20171'
t.format('YYYYww'); // '201701'
t.format('YYYYwo'); // '20171st'
```

I think it is wrong..

**Comment by kimtis** [comment]
I thought wrong :(  The problem is that you have to think of 'YYYY' and 'ww' differently.
I will close this issue.

**Comment by yesmeck** [comment]
For anyone who encounters this issue else, you can use `t.format('ggggw')`;
