### ISSUE TITLE
3 tests failed. create:string with format - years (2732.4) format:Y token (2896.6) week day:weekday first day of week Sunday (dow 0) (3194.5) 

### ISSUE THREAD

**Issue by goofballLogic** [moment/moment#4381]
### Client info
```
Date String   : Fri Dec 29 2017 14:45:52 GMT+0000 (GMT)
Locale String : 29/12/2017, 14:45:52
Offset        : 0
User Agent    : Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 Firefox/42.0
Moment Version: 2.20.1
```

====

### create:string with format - years (2732.4) 

70 > 1970

```javascript
// Expected 1970
// Actual   1969
"1969" === "1970"
```

====

### format:Y token (2896.6) 

format 9999 with Y

```javascript
// Expected 9999
// Actual   9998
"9998" === "9999"
```

====

### week day:weekday first day of week Sunday (dow 0) (3194.5) 

Jan  1 1970 is Thursday  -- 4th day

```javascript
// Expected 4
// Actual   3
3 === 4
```

**Comment by goofballLogic** [comment]
Older version of Firefox mandated by our public libraries.

**Comment by marwahaha** [comment]
@goofballLogic does this still happen?

**Comment by goofballLogic** [comment]
Won't be back in the library for another two weeks. I imagine it does although there were rumours of them upgrading their version of Firefox soon.
