### ISSUE TITLE
Issue while running tests using grunt

### ISSUE THREAD

**Issue by nishantgupta204** [moment/moment#4385]
After fixing a bug I ran the grunt command to build the project. Below is the issue I am getting while running the command.

>> build/umd/min/moment-with-locales.js

Running "concat:tests" (concat) task
Running "qtest" task
Deprecation warning: testing deprecation
Arguments:
Error
    at C:\moment\build\umd\test\moment\deprecate.js:154:94
    at Object.<anonymous> (C:\moment\build\umd\test\moment\deprecate.js:173:5)
    at Test.run (C:\moment\node_modules\qunitjs\qunit\qunit.js:136:18)
    at C:\moment\node_modules\qunitjs\qunit\qunit.js:279:10
    at process (C:\moment\node_modules\qunitjs\qunit\qunit.js:1277:24)
    at Timeout._onTimeout (C:\moment\node_modules\qunitjs\qunit\qunit.js:383:5)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
woot Error: Process blocked for too long
    at Timeout.<anonymous> (C:\moment\node_modules\qunit\lib\testrunner.js:83:30)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) { files: 0,
  assertions: 0,
  failed: 0,
  passed: 0,
  runtime: 0,
  tests: 114,
  coverage:
   { files: 0,
     statements: { covered: 0, total: 0 },
     branches: { covered: 0, total: 0 },
     functions: { covered: 0, total: 0 },
     lines: { covered: 0, total: 0 } } }

Please let me know what the issue is.

**Comment by nishantgupta204** [comment]
Job details -

https://travis-ci.org/moment/moment/jobs/324004373

**Comment by nishantgupta204** [comment]
@marwahaha I did incorporate the changes that you suggested and ran the grunt command. It is throwing me the same issue.

**Comment by nishantgupta204** [comment]
The error is coming the long before timeout is occurring. Is it because it is not able to recognize the test cases?

**Comment by marwahaha** [comment]
If you open a PR with the broken code, others can help debug.

**Comment by nishantgupta204** [comment]
PR link
https://github.com/moment/moment/pull/4388/files

**Comment by nishantgupta204** [comment]
@marwahaha I ran the grunt command on the updated code without my changes, still the same issue is coming. Am I missing something in installation?

**Comment by nishantgupta204** [comment]
@marwahaha I ran the "grunt test" command on the updated code and without my changes. It showed the same error but the test cases ran after the error. But with my code the it just hangs up with the error.

**Comment by marwahaha** [comment]
@nishantgupta204 There may be an infinite loop in your code. Unfortunately, I don't have time to debug - perhaps others can help. 

What bug were you trying to fix ?

**Comment by marwahaha** [comment]
Unfortunately, I don't have the time to help you fix this, but maybe someone else in the community can help out.
