### ISSUE TITLE
Uppercase function 'undefind' for locale.

### ISSUE THREAD

**Issue by BMK91** [moment/moment#4386]
Hello,
I'm reviewing tutorial
https://momentjs.com/docs/#/i18n/locale-data/

**I got an issue for the following:**
localeData = moment.localeData();
localeData.longDateFormat();
**Uncaught TypeError:** Cannot read property 'toUpperCase' of undefined

**Also recently found.**
localeData.relativeTime();
**Uncaught TypeError:** Cannot read property 'replace' of undefined

localeData.week();
**Uncaught TypeError:** Cannot read property 'year' of undefined

Please resolve this issue.
Thank you.

**Comment by AlexanderEllis** [comment]
I saw this was marked as a bug, but I did a little digging and think it might not actually be one.  Below [this link](https://momentjs.com/docs/#/i18n/locale-data/), the docs say that "The returned object has the following methods:"
```
localeData.longDateFormat(dateFormat);  // returns the full format of abbreviated date-time formats LT, L, LL and so on
localeData.relativeTime(number, withoutSuffix, key, isFuture);  // returns relative time string, key is on of 's', 'm', 'mm', 'h', 'hh', 'd', 'dd', 'M', 'MM', 'y', 'yy'. Single letter when number is 1.
localeData.week(aMoment);  // returns week-of-year of aMoment
```

Calling these functions without the proper arguments (like `localeData.longDateFormat();`) does indeed throw these typeErrors, as the `dateFormat` would not be provided.  Maybe not the most elegant result, but is this what we would expect?

That being said, I also missed this in the docs at first glance and spent some time digging through the code, as the method signatures seem to imply you can call these without arguments.  I only noticed it after returning to the docs and scrolling down to see if what I found matched anything there.  

Looks like the method signatures in the docs could use some updating.  If that sounds about right, I can go ahead and update these ones as needed.  

The only thing I'm not sure about is some of the methods that seem to behave differently with or without arguments.  For instance, `moment.localeData().months()` returns all months, but it seems that `moment.localeData().months(moment())` is different, in that it just returns the current month.

**Comment by marwahaha** [comment]
Yea, this looks like a documentation issue. Thanks @AlexanderEllis
