### ISSUE TITLE
Time Format for Korean language should be 24H

### ISSUE THREAD

**Issue by xdumaine** [moment/moment#4387]
**Description of the Issue and Steps to Reproduce:**

Our Localization team has reported that Korean time is more formally used in writing as 24 hour format (hh:mm) but moment uses the more informal 12 hour time (A h:mm). 

`moment().locale('ko').format('LT')`

**Comment by xdumaine** [comment]
If this is accepted, I'll gladly open the PR for it.

**Comment by xdumaine** [comment]
@kyungw00k or @jeeeyul I saw you tagged on other Korean related PRs, could you please comment?

**Comment by bartclaeys** [comment]
Any update on this?

**Comment by bartclaeys** [comment]
Here facts about Korean date/time formatting:
https://www.ibm.com/support/knowledgecenter/en/SSS28S_8.1.0/XFDL/i_xfdl_r_formats_ko_KR.html

**Comment by kyungw00k** [comment]
I think this issue is based on the opinion which format is widely used in general.

> Korean time is more formally used in writing as 24 hour format (hh:mm) but moment uses the more informal 12 hour time (A h:mm).

According to KSXISO8601(formerly KSX1511), `YYYY-MM-DD HH:MM:SS` is widely used in `computing` and on the `Korean internet`.

But, in terms of `LT` which is part of `longDateFormat` section, I think `오후 6:52` is more likely use then `18:52`.

@jeeeyul @bigtone1284 @JunhoKim01 I need your opinion about this.

**Comment by marwahaha** [comment]
@jeeeyul @bigtone1284 @JunhoKim01 @xdumaine - thoughts?

**Comment by JunhoKim01** [comment]
I agree with @kyungw00k`s  idea.

**Comment by xdumaine** [comment]
I'm not sure what the question is. I don't have any knowledge of Korean language, I'm just passing on what my localization team asked for. If you disagree please just close the issue.

**Comment by outsideris** [comment]
I don't believe Korean use 24 hour format formally although I'm Korean.
Agreed with @kyungw00k

**Comment by marwahaha** [comment]
Ok, I will leave as is.
