### ISSUE TITLE
isValid() inconsistent between browsers

### ISSUE THREAD

**Issue by im1dermike** [moment/moment#4389]
I found that `isValid()` is inconsistent between browsers when the string is formatted in a certain way.

Here is what I see in Firefox (57.0.3):

![Firefox](https://image.ibb.co/khYChG/Capture.png)

Here is what I see in Chrome (63.0.3239.108):

![Chrome](https://image.ibb.co/d25Q2G/Capture2.png)

Other formats I've tried work, but `MM-DD-YYYY` is exhibiting this behavior.

I'm using moment 2.19.4.

**Comment by ashsearle** [comment]
It's not `isValid` that is inconsistent, it's `moment(str)` (specifically the fall back behaviour using `new Date(str)` when the string isn't in ISO 8601 or RFC 2822 format.)

See the [warning about inconsistent browser support](https://momentjs.com/docs/#/parsing/string/) in the docs.

**Comment by im1dermike** [comment]
Thanks for your response.  I'll force a specific format that is supported across browser.
