### ISSUE TITLE
moment().toISOString(true) is not keep the local time

### ISSUE THREAD

**Issue by lira92** [moment/moment#4390]
When I execute moment().toISOString() the result is "2018-01-04T12:54:33.621Z" and when I execute moment().toISOString(true) the result is "2018-01-04T12:54:35.916-02:00", Shouldn't be "2018-01-04T10:54:35.916-02:00" ?

**Environment:**
Chrome 63.0.3239.108 on Windows 10 64 bit

The time and date at which the code was run
2018-01-04 10:54:35 (America/São Paulo)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
Thu Jan 04 2018 11:02:16 GMT-0200 (Horário brasileiro de verão)
04/01/2018 11:02:16
120
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2.20.1
```

**Comment by ashsearle** [comment]
My mistake... should be fixed by PR #4391
