### ISSUE TITLE
Wrong formatting for week

### ISSUE THREAD

**Issue by vgalkin** [moment/moment#4394]
**Description of the Issue and Steps to Reproduce:**

`format` returns wrong data when using Week format

correct:

```js
moment('20180101010000', 'YYYYMMWWDDHHmm').format('YYYY-MM-DD:HH') // "2018-01-01:00"
```

wrong:
```js
moment('2018011010000', 'YYYYMMWDDHHmm').format('YYYY-MM-DD:HH') // "2018-01-10:00"
```
**Environment:**
Chrome 49 on OSX

```js
Tue Jan 09 2018 11:48:18 GMT+0200 (EET)
1/9/2018, 11:48:18 AM
-120
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
2.20.1
```

**Comment by Baelyk** [comment]
As far as I can tell, this is just an error with not using [strict mode](http://momentjs.com/guides/#/parsing/strict-mode/).
This is what you intend to happen:
```
YYYY MM W DD HH mm --> YYYY-MM-DD:HH
2018 01 1 01 00 00 --> 2018-01-01:00
```
But, `W` can also mean `WW` in non strict mode, so this is what actually happens:
```
YYYY MM WW DD HH mm --> YYYY-MM-DD:HH
2018 01 10 10 00 0  --> 2018-01-01:00
```
The week takes the leading zero from `DD`, then `DD` takes the zero from `HH`, and so on, shifting the problem down the line until `mm`, which in non-strict mode is valid even if it only has 1 digit (uses the regex `match1to2` like `W` and `WW` in non-strict mode).

Using strict mode:
```js
moment('2018011010000', 'YYYYMMWDDHHmm', true).format('YYYY-MM-DD:HH') // "Invalid date"
```

**Comment by marwahaha** [comment]
Thanks Baelyk!

@vgalkin - Please re-open if you have other questions.
