### ISSUE TITLE
Date is not correct using week no and year

### ISSUE THREAD

**Issue by sunithajanapareddy** [moment/moment#4398]
moment().day("Sunday").year(2017).week(47).format('YYYY-MM-DD');

in the above iam asking sunday of the week but output 25/11/2017 which is saturday

but it is working correct for current year

**Comment by ashsearle** [comment]
Explanation:
```js
moment().format('dddd YYYY-MM-DD'); // Friday 2018-01-12
moment().day("Sunday").format('dddd YYYY-MM-DD'); // Sunday 2018-01-07
moment().day("Sunday").year(2017).format('dddd YYYY-MM-DD'); // Saturday 2017-01-07
```

See what happened?
moment preserves the date when changing year, not the day-of-week.

You now have a moment set to Saturday, and so:
```js
moment().day("Sunday").year(2017).week(47).format('dddd YYYY-MM-DD'); // Saturday 2017-11-25
```

Reordering your method chain gets you a different answer - which might be what you want:
```js
moment().year(2017).week(47).day("Sunday").format('dddd YYYY-MM-DD'); // Sunday 2017-11-19
```

**Comment by marwahaha** [comment]
Let us know if you have other issues!
