### ISSUE TITLE
Moment Parses Dates incorrectly

### ISSUE THREAD

**Issue by clethrill** [moment/moment#4400]
I have a date in the format "4:40PM / Sat 20 Jan". This date does not have a year associated, I know that it is either last year, this year or next year. So I append '2017', '2018 and '2019' to the date and use `var date = moment("4:40PM / Sat 20 Jan", "h:mm a / ddd DD MMM YYYY");` and then use `date.isValid()` to determine whether the 20th of January fell on a Saturday in 2017, 2018 or 2019 (it at most happens every 6 years so it can't be more than one of these). This produces differing results in different environments, other dates like Mon 6 Feb seem to have an issue too.

The code is primarily running in a lambda function on AWS and sometimes thinks none of the years are valid and sometimes thinks the wrong year is valid. Unfortunately sometimes it works and sometimes it doesn't, even in the same environment! This makes it very difficult to reproduce or replicate. I have used google calendar on my phone to cross reference every date that is has been getting incorrect so I know that the dates I am selecting should be falling in certain years.

example code:

```
const moment = require("moment-timezone");

let thisYear = 2017;
let datetime = "4:40PM / Sat 20 Jan";
let years = [thisYear-1, thisYear, thisYear+1]; // make array of years to test date against

let date = null;
for (let year of years) {
	let dateWithYear = datetime + " " + year;
	let testDate = moment(dateWithYear, "h:mm a / ddd DD MMM YYYY");
	if (testDate.isValid()) {
		date = testDate;
		console.log("Year for date " + date.format() + " is " + year);
		break;
	}
	else {
		console.log("Not from " + year);
	}
}
```

expected results would be:

```
"Not from 2017"
"Year for date ... is 2018"
```

results getting sometimes are either:

```
"Year for date ... is 2017"
```

or

```
"Not from 2017"
"Not from 2018"
"Not from 2019"
```

moment version: 2.20.1
moment-timezone version: 0.5.14

**Comment by ashsearle** [comment]
Try tweaking the format and using strict mode:

```diff
10c10
< let testDate = moment(dateWithYear, "h:mm a / ddd DD MMM YYYY");
---
> let testDate = moment(dateWithYear, "h:mmA / ddd DD MMM YYYY", true);
```

**Comment by clethrill** [comment]
the " a", "A" change was an error on my part moving the code into github and stripping away the unrelated stuff. I'll try with strict mode though

**Comment by marwahaha** [comment]
I'm going to close this. Please re-open if there are other issues.
