### ISSUE TITLE
Get Days by week number in a year

### ISSUE THREAD

**Issue by aftab1001** [moment/moment#4402]
I want to get Days week for example for year 2016 and WeekNumber 33  i want to get the Dates Ranges that lies in this week.How can i do this.

**Comment by YounGoat** [comment]
@aftab1001 
You can get the week rang via [dafo.getWeekRange()](https://www.npmjs.com/package/dafo#others). E.g. 
```javascript
const dafo = require('dafo');
const range = dafo.getWeekRange({ year: 2016, week: 33, mode: 0 });
range.first.toString();
range.last.toString();
```
ATTENTION: Options property *mode* is necessary! See [Week Mode](https://www.npmjs.com/package/dafo#week-mode) for details.

**Comment by YounGoat** [comment]
@marwahaha What does label **Up-For-Grabs** mean? A PR encouraged about this feature?

**Comment by ichernev** [comment]
@YounGoat you can create a moment in that week, and then use `startOf`/`endOf` to get the first/last part of it.

```javascript
m = moment("2018-W13")
m.startOf('week')
m.endOf('week')
```
