### ISSUE TITLE
Format method, take into account whitespaces in escaped characters

### ISSUE THREAD

**Issue by lequem** [moment/moment#4404]
Hello, 

I use the moment library to display time using the format method.
I needed to let a space between the date and the hour but the white spaces that I've set in the escaped characters are not taken into account. Specials characters like \t  are not taken into account either.

Here the syntaxt of my format:
moment().format('DD/MM/YY [********GMT] HH:mm:ss') and the result is : 
"2018-01-08 GMT 08:02:17" and I would like "2018-01-08 ********GMT 08:02:17"

!!!!!! replace * by whitespaces. I've set * because the result github post trim the whitespaces.

current version of moment.js: 2.20.1

Thx

**Comment by ashsearle** [comment]
This sounds like an HTML / CSS problem, not a moment problem.

Read up on how HTML 'collapses' sequences of white-space, and the [CSS white-space property](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) you can use to control that.

**Comment by lequem** [comment]
You're right.
Thank you for your help
