### ISSUE TITLE
Invalid date formatting for new year holidays

### ISSUE THREAD

**Issue by Imperat** [moment/moment#4406]
Hi, everyone!
I found strange issue for 31 December. I have the Date object like this:
`Sun Dec 31 2017 00:00:00 GMT+0400 (+04)`

I use "format" function to get year and week number:
`moment(date, 'w-YY') // Is equal to '1-17'.`

I think it's wrong representation of this case. Probably is most useful to show "53-17" or "1-18"?

Found in Chrome Version 59.0.3071.86 (Official Build) (64-bit) on Ubuntu 16.04

**Comment by ashsearle** [comment]
You're using the locale-aware `'w'` to get the week number, so you should probably also use the locale-aware `'gg'` to get your year number (instead of `'YY'`).

i.e. try `moment(date).format('w-gg')`

**Comment by Imperat** [comment]
It's working. Thank you for you support!

**Comment by marwahaha** [comment]
Thanks @ashsearle !
