### ISSUE TITLE
Changing the year on a moment messes the utc offset

### ISSUE THREAD

**Issue by SudoPlz** [moment/moment#4409]
I'm doing this:

        moment.tz.setDefault('America/New_York');
	const dateMoment = moment('2018-01-23T17:00:00-0700', 'YYYY-MM-DDTHH:mm:ssZZ');
	const timeMoment = moment('2020-01-23T17:00:00-0700', 'YYYY-MM-DDTHH:mm:ssZZ');
	const momContainingDate = timeMoment.clone().year(dateMoment.year());

	if (timeMoment.utcOffset() !== momContainingDate.utcOffset()) {
	   console.log('UTC offset changed'); // <-- we always end up here
	}

All `.clone`, `.year`, `.month`, `.date` and `.add` or `.subtract` mess the utc offset when we've set a default timezone:

(`moment.tz.setDefault("America/New_York");`)

**Comment by ashsearle** [comment]
Your example code shows you using `===`.  Is that right?

As written, the `console.log('UTC offset changed')` is extremely misleading as the UTC offset has _not_ changed.

**Comment by SudoPlz** [comment]
What do you mean? The final offset was actually different from the initial one. 
I don't have the exact time that was being output but it was something like `2020-01-23T08:00:00+0200`

**Comment by ashsearle** [comment]
@SudoPlz I meant that you have a mistake in your example code.  What you've written is the same as writing: 

```js
if (a === b) {
  console.log("a does not equal b");
}
```

Also: you're missing quotes around the timestamps you're using.

Please fix your example code and use dates/times that actually demonstrate the problem you're attempting to report.

**Comment by SudoPlz** [comment]
Whoops, yes you're right, I corrected the example. The problem is still there though.

**Comment by ashsearle** [comment]
@SudoPlz I still don't see the issue with the code you've provided.

Does your real code use `moment.parseZone(...)` to preserve the timezone information?  I suspect this might be a known issue in moment-timezone: moment/moment-timezone#208

**Comment by SudoPlz** [comment]
I do use `parseZone` in many places within my code and I am using `moment-timezone` all within a react-native project.. Wow good catch that might be the issue.
