### ISSUE TITLE
Can't get local .month()

### ISSUE THREAD

**Issue by iffy** [moment/moment#4411]
**Description of the Issue and Steps to Reproduce:**

I expect `.month()` to return the local zone month (or for there to be a way to get the local month number).  Instead, it always returns the UTC month.  In the following example, I would expect `a.month()` or `a.local().month()` to return `0` instead of `11`.

~~~
> let a = moment('2018-01-01T00:00:00+01:00')
> a.month()
11
> a.local().month()
11
> a.utc().month()
11
> moment.version
"2.20.1"
~~~

**Environment:**

- Electron/NodeJS on Ubuntu 17.10
- and Chrome 63.0.3239.132 (Official Build) (64-bit) on macOS 10.12.6

**Other information that may be helpful:**

- macOS timezone: -07:00
- Ubuntu timezone: +01:00
- Using TypeScript, but I can reproduce w/o it on https://momentjs.com/guides/ in the console.

```
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

VM214:1 Wed Jan 24 2018 13:48:55 GMT-0700 (MST)
VM214:2 1/24/2018, 1:48:55 PM
VM214:3 420
VM214:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
VM214:5 2.20.1
```

**Comment by ashsearle** [comment]
I think you might be confused about what 'local zone' means.

From the information you've provided, your local zone is GMT-0700 (MST)
`'2018-01-01T00:00:00+01:00'` is the same point in time as `'2017-12-31T16:00:00-07:00'`, so moment is correctly returning a month of 11 (December)

If you're aim is to preserve the `+01:00` zone from the input string,  try using `parseZone` to get a moment instance fixed to that zone:
```js
> let a = moment.parseZone('2018-01-01T00:00:00+01:00')
> a.month()
0
> a.format()
'2018-01-01T00:00:00+01:00'
```

**Comment by iffy** [comment]
That's definitely my confusion.  Thank you!
