### ISSUE TITLE
Duration from format

### ISSUE THREAD

**Issue by jvitoroc** [moment/moment#4412]
Is there something like this in momentjs?
moment.duration("00:20:32,836", "HH:mm:ss,SSS").seconds();
It would work like: https://momentjs.com/docs/#/parsing/string-format/
I want to parse [.srt files](http://www.3playmedia.com/2017/03/08/create-srt-file/)

**Comment by marwahaha** [comment]
Short version: If you need something flexible, use a plugin, like the one here:
http://momentjs.com/docs/#/plugins/duration-format/

Long discussion here:
https://github.com/moment/moment/issues/1048
