### ISSUE TITLE
momentWithLocales2.default.duration(...).format is not a function

### ISSUE THREAD

**Issue by VanessaChu** [moment/moment#4421]
I'm using React Native and I'm trying to change the language of my moment.js by changing import moment from 'moment' to import moment from 'moment/min/moment-with-locales'. 

import moment from 'moment/min/moment-with-locales'
import 'moment-duration-format' // used by moment

However, I get an error "momentWithLocales2.default.duration(...).format is not a function" at this line: 

const total = moment.duration(this.props.stoveUsage.total, 'seconds').format('H:mm', { trim: false })

before there was no error with just import moment from 'moment'

**Comment by marwahaha** [comment]
@jsmreese  ?

**Comment by marwahaha** [comment]
i'm going to close this. I recommend you bring it up here: https://github.com/jsmreese/moment-duration-format

Good luck!
