### ISSUE TITLE
How to change locale in momentJS in React Native?

### ISSUE THREAD

**Issue by VanessaChu** [moment/moment#4422]
This is what I have but it does not work.
```
import moment from 'moment' 
import 'moment/min/moment-with-locales' 
import 'moment-duration-format' // used by moment  
```

```
componentDidMount () {  
 console.log(moment.locale())   
 console.log(moment.locale('zh-cn'))    
 console.log(moment.locale())  
} 
```

console log outputs: en, en, en
expected console log output: en, zh-cn, zh-cn

When I tried changing import moment from 'moment' to import moment from 'moment/min/moment-with-locales' but it throws an error on this line:

`const total = moment.duration(this.props.stoveUsage.total, 'seconds').format('H:mm', { trim: false })  `

error: momentWithLocales2.default.duration(...).format is not a function

**Comment by rudyryk** [comment]
Confirming that, `moment.locale('es')` has  no effect for me in React Native.

**Comment by rudyryk** [comment]
`import 'moment/min/moment-with-locales'`

Does the trick!

`moment.locale('es'); moment().format("ll");`

results `1 févr. 2018` as expected.

**Comment by Leeds-eBooks** [comment]
If you don't want to use `moment-with-locales`, which loads all locale data, rolling back to moment v2.18 fixed this for me. There is definitely a bug with moment v2.20 and setting the locale in react native.

**Comment by msevestre** [comment]
@Leeds-eBooks Could you explain how you import moment? I rolled back to 2.18 and yet I need to import moment from moment-with-locales in to get local to work properly in react-native

Thanks

**Comment by Leeds-eBooks** [comment]
@msevestre Yeah of course, although I think my solution may be out of date now, I made it work in my code and moved on, I think a later version of moment might have fixed it. Nevertheless, my fix is:

- install `https://github.com/tqc/moment.git#no-dynamic-import` instead of `moment` directly from npm
- then:

```js
import moment from 'moment'

import 'moment/src/locale/en-gb'
import 'moment/src/locale/es'
import 'moment/src/locale/fr'
import 'moment/src/locale/pl'
import 'moment/src/locale/pt'
// ...etc

// bonus trick!
import DeviceInfo from 'react-native-device-info'
const deviceLocale = DeviceInfo.getDeviceLocale()
moment.locale([deviceLocale, 'en'])
```

This is what I'm doing, and it's working for me, but as I say it may no longer be necessary.

**Comment by msevestre** [comment]
@Leeds-eBooks Awesome. Thanks for your quick feedback. Really helped

**Comment by wstan77** [comment]
This worked to me,

[](https://momentjs.com/docs/#/i18n/instance-locale/
)
You must instance on App.js all words to language than you want, this will work in all your application.

**Comment by wstan77** [comment]
This worked to me,

[https://momentjs.com/docs/#/i18n/instance-locale/](url)
You must instance on App.js all words to language than you want, this will work in all your application.

**Comment by marwahaha** [comment]
@VanessaChu - do you still have a problem?

**Comment by jeffhtli** [comment]
[This solution](https://github.com/moment/moment/issues/1875#issuecomment-263220119) works for me

**Comment by MayeuldP** [comment]
Hey peoples, `import 'moment/locale/fr'; 
` works for me, but if I want to do a dynamical one, like not have to import all the exisiting languages, do you know any tricks to do something like `import 'moment/locale/[variable]'` where variable is the needed language ? 
So that it works with every country... :/

**Comment by ichernev** [comment]
I hope most discussion participants got their problems sorted out :) Thank you @Leeds-eBooks

For 3.x we might have more versions of moment with/without the dynamic import/es6 so this is less of an issue.

**Comment by stenrdj** [comment]
Hello @MayeuldP ,
i don't know if you arrive to fix using variable languages of moments in Reactjs / ReactNative , but i want to share the solution it may help somebody .
you don't have to import culture by culture instead just add :```  import 'moment/min/locales' ```  only and later you can set your moment.local('') with your favorite culture.

**Comment by KashifAhmed** [comment]
I'm using v2.18 and this method works.
```
import moment from 'moment';
import momentFR from 'moment/src/locale/fr' 
moment.locale('fr',momentFR );

``

**Comment by fructurj** [comment]
Hi, @KashifAhmed In v.2.22.2 you should use moment.updateLocale('fr',momentFR)

> Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.

**Comment by RicardoBer** [comment]
Check this:

```
import moment from "moment";
import 'moment/min/locales'
```
This include all languajes configurations from moment, it's js, so no problem with size.

I had problem before when some one install the app with an mobile with different languaje.

From this you can set any locale defined by moment without any problem, 

`moment.locale('es');`

**Comment by tapz** [comment]
> import 'moment/min/locales'
> import 'moment/min/moment-with-locales'

Both of these do not work in React Native. The only way that works, is to import every single locale as you can't know what locale the user has selected in the device. As it seems such a simple task is impossible with moment, I'm considering implementing the formatting in native side. It's probably just one line of code.

**Comment by lautaro-osacar** [comment]
To set locale without extra libraries:

```
import moment from "moment";
import "moment/min/locales";
import { NativeModules, Platform } from "react-native";

constructor() {
 super();
 const deviceLocale =
      Platform.OS === "ios"
        ? NativeModules.SettingsManager.settings.AppleLocale
        : NativeModules.I18nManager.localeIdentifier;
 moment.locale(deviceLocale);
}
```

**Comment by euharrison** [comment]
In my case, import the locale wasn't enough, so I used the imported dictionary and remove the first character that is an underscore `_`

```js
import moment from 'moment';
import momentPTBR from 'moment/src/locale/pt-br';

function prepareLocale(locale) {
  for (const key in locale) {
    if (locale.hasOwnProperty(key)) {
      // remove first character underscore fom key, i.e. '_calendar' => 'calendar'
      locale[key.substring(1)] = locale[key];
    }
  }
  return locale;
}

moment.defineLocale('pt-br', prepareLocale(momentPTBR));
```

**Comment by Asday** [comment]
`import 'moment/src/locale/en-gb'` didn't work for me, but `import 'moment/locale/en-gb'` did.

```JSON
  "dependencies": {
    "expo": "32.0.0",
    "moment": "2.24.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
  },
```

In the upper-most file in the tree, here's how my code looks:

```es6
import moment from 'moment'

import 'moment/locale/en-gb'

const momentLocale = moment.locale('en-gb')
if (momentLocale !== 'en-gb') {
  throw new Error(`Moment fell back to locale ${momentLocale}`)
}

export default () => null
```

**Comment by karthikeyan110798** [comment]
> I'm using v2.18 and this method works.
> 
> ```
> import moment from 'moment';
> import momentFR from 'moment/src/locale/fr' 
> moment.locale('fr',momentFR );
> ``
could you please give some examples.
thanks a lot!

**Comment by thinklinux** [comment]
I changed my version from 2.24 to 2.18 and it works now. There is a bug somewhere after 2.20.

**Comment by juliovieceli** [comment]
its work for me 
```
import moment from 'moment'
import 'moment/locale/pt-br'
moment.locale('pt-br')
```

**Comment by Asday** [comment]
> its work for me
> 
> ```
> import moment from 'moment'
> import 'moment/locale/pt-br'
> moment.locale('pt-br')
> ```

Make sure you're checking that what you get back from `.locale()` is what you set.  It falls back silently.

**Comment by AlfreddGco** [comment]
The current solution for January 4, 2020, on version 2.29.1 installing with `npm install moment` is:
`
import moment from 'moment';
moment.updateLocale('es-MX');
moment.locale(); // 'es-MX'
`

**Comment by wmonecke** [comment]
I don't understand how this is working for you guys.
For me, it is ONLY working on the initial view. If you go to another view moment default back to English. 

In other words `moment.locale()` is setting the locale to the local instance of `moment` and NOT GLOBAL.

**Comment by Asday** [comment]
Set it in your app root, not in a view.  Mine is _above_ the call to `ReactDOM.render()`.

**Comment by wmonecke** [comment]
@Asday 

This is my `index.js` 
````
import moment from 'moment'
import strings from './src/i18n/strings'
import 'moment/locale/fr';
import 'moment/locale/de';
import 'moment/locale/it';
import 'moment/locale/pt';
import 'moment/locale/es';
const deviceLanguage = strings.getInterfaceLanguage().split('-')[0].split('_')[0];
moment.updateLocale([deviceLanguage, 'en'])

import 'react-native-gesture-handler';
import App from './src/App';
import { AppRegistry } from 'react-native';
import { name as appName } from './app.json';

AppRegistry.registerComponent(appName, () => App);
````

Works on the first view and when I navigate away it stops working.

**Comment by Asday** [comment]
Opened the project I've done this on to check, and I don't have an index.  I let react-native take care of whatever it wants to in there, and set my locale in `App.jsx`.

What's the advantage of hand-rolling your own index?  Is the react-native provided one doing something yours isn't?

**Comment by AmirDiafi** [comment]
**this is what you look for:**

```
import * as RNLocalize from 'react-native-localize'
const local = RNLocalize.getLocales()
const lanTag = local[0].languageTag.toLowerCase()
console.log(lanTag)
import moment from 'moment'
import 'moment/min/locales'
moment.locale(lanTag) //set moment local
```

**Comment by arbisyarifudin** [comment]
I use v2.29.4

```
import moment from 'moment'
import 'moment/dist/locale/id'
moment.locale('id')
```

and IT'S WORK!!

**Comment by samy-tcheik** [comment]
I use version v2.29.4
and this solution worked for me
```
import moment from 'moment'
import 'moment/min/locales*
moment.locale("ar")
```

**Comment by iswiboni** [comment]
take look this guide  : https://momentjs.com/guides/#/warnings/define-locale/

bellow is working for me :

```JS
import moment from 'moment'
moment.defineLocale('id',{
  months : [
    'Januari',
    'Februari',
    'Maret',
    'April',
    'Mei',
    'Juni',
    'Juli',
    'Agustus',
    'September',
    'Oktober',
    'November',
    'Desember',
  ],
  //etc opts
})
```
