### ISSUE TITLE
Get single letter abbreviation of week day.

### ISSUE THREAD

**Issue by 0xbsec** [moment/moment#4426]
**Description of the Issue and Steps to Reproduce:**

I need to get single letter abbreviation of week day e.g. `R` for Thursday, `F` for Friday, `S` for Saturday, `U` for Sunday.

Using `moment().format('d')` give the number of the day of the week. 

Is this supported by moment or can I added explicitly? 

**Environment:**

Chrome 63 on OSX.

Moment version: 2.20.1.

**Comment by ashsearle** [comment]
The shortest form you can get is 2-letters (in English): `moment().format('dd') `

I've never seen Thursday abbreviated as 'R'.  Have you made that up?

**Comment by 0xbsec** [comment]
@ashsearle Thanks for checking.

Sadly I can't find any international standard for this. Though I've found multiple instance of this usage:

1- http://eventguide.com/topics/one_digit_day_abbreviations.html
2- https://forum.wordreference.com/threads/abbreviation-for-the-days-monday-tuesday.327232/#post-11942753

I believe that it's fair for moment not to support a format without a standard. But is there a way to add this abbreviation without modifying moment directly?

**Comment by ashsearle** [comment]
If you're not going to use the existing minimal weekday abbreviations used by `dd`, you can [use `updateLocale` to override](https://momentjs.com/docs/#/customization/weekday-min/)

```js
moment.updateLocale('en', { weekdaysMin: 'U_M_T_W_R_F_S'.split('_') });
moment().format('dd');
```

However... I would strongly advise doing this.  I can't think of any scenario where a 1-character abbreviated weekday makes sense: it makes no sense on a calendar, as dates are 2-digits, and it makes no sense in isolation where 'T' and 'S' will be confusing abbreviations unless the full set of other characters is known.  And, frankly, U and R are ridiculous stand-ins for Sunday and Thursday in any circumstance (both of which contain a 'U'...)

**Comment by 0xbsec** [comment]
@ashsearle I completely agree with you. Thanks!

**Comment by jalfonso** [comment]
Just wanted to add that this is a common abbreviation in North American higher education;  there are widely used, decades-old campus systems which use a single letter abbreviation for each day of the week.

Examples:  https://www.google.com/search?q=thursday+abbreviation+r+site%3Aedu

**Comment by G89Angel** [comment]
For example in Spain it makes a lot of sense to use (L_M_X_J_V_S_D). Maybe it could be a good addition for certain languages.

In the mean time I'll use @ashsearle recommendation.
