### ISSUE TITLE
Wrong output when formatting date

### ISSUE THREAD

**Issue by juliandavidmr** [moment/moment#4427]
**Description of the Issue and Steps to Reproduce:**

I have a date in ISO_8601 format _(that's what it looks like)_, when I try to give it the following `DD-MM-YYYY h:mm:ss a` format then it changes the time. Note that the time is `20` but after formatting this changes to `3` when it should be `8`

Original:     `2018-01-31T20:57:00Z`
Converted: `31-01-2018 3:57:00 pm`
Expected: `31-01-2018 8:57:00 pm`

*Please include the values of all variables used.*
```ts
let limitDate = "2018-01-31T20:57:00Z";
moment(limitDate, moment.ISO_8601).format('DD-MM-YYYY h:mm:ss a') // 31-01-2018 3:57:00 pm
```

**Environment:**

*Firefox 58*
*MS Windows 8*
*Running in an environment with NodeJS and Ionic v3*

**Other information that may be helpful:**
* The time zone: _Bogotá, Lima, Quito, Rio Branco_
* Other libraries in use: TypeScript, Ionic Framework v3, Node 8

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

/*
Output:
Wed Jan 31 2018 16:14:40 GMT-0500
31/1/2018 16:14:40
300
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
2.20.1
*/
```

**Comment by ashsearle** [comment]
Your timezone in Lima is `-05:00`

`2018-01-31T20:57:00Z` is the same point in time as `2018-01-31T15:57:00-05:00` - which is 3pm in your timezone.

Have a look at the [utc()](https://momentjs.com/docs/#/parsing/utc/) method if you want to parse-and-format in UTC instead of your local timezone.
