### ISSUE TITLE
pre-treat moment.min.js with dllplugin got warning

### ISSUE THREAD

**Issue by yhshen93** [moment/moment#4428]
**Description of the Issue and Steps to Reproduce:**

I am using webpack.dllplugin to pre-treat some stable dependencies, include moment.

Some codes in my webpack.dll.config.js is shown here

```javascript
module.exports = {
  entry: {
    vendor: ['moment/min/moment.min.js']
  }
}
```
And then I got warning: 

> WARNING in ./~/moment/min/moment.min.js
Module not found: Error: Can't resolve './locale' in 'E:\workspace\nms8\webpack\node_modules\moment\min'
 @ ./~/moment/min/moment.min.js 1:8507-8529
 @ dll vendor

**Environment:**

OS: Windows 10 pro
Node: v6.10.2
npm: v3.10.10
webpack: v2.2.1
moment: v2.19.3

**Comment by marwahaha** [comment]
Closing due to age. Let us know if you still have questions.

**Comment by mattjohnsonpint** [comment]
Please see https://github.com/moment/moment/issues/6092#issuecomment-5331841987
