### ISSUE TITLE
startOf('week') for moment.locale('en-ca') is not the same as for moment.locale('en-ca')

### ISSUE THREAD

**Issue by VanessaChu** [moment/moment#4431]
` dt: moment()
`
```
    console.log(moment(dt).locale('en-ca').startOf('week')).format('MMM D')  //returns Jan 28
    console.log(moment(dt).locale('zh-cn').startOf('week')).format('MMM D')  //returns Jan 22
```

First console.log returns Jan 28 for locale('en-ca') which is a Sunday
Second console.log returns Jan 22 for locale('zh-cn') which is a Monday

Time is not in sync.

**Comment by ashsearle** [comment]
The locales have different definitions for the start of a `'week'`:

```js
moment().locale('zh-cn').localeData().firstDayOfWeek(); // 1 - Monday
moment().locale('en-ca').localeData().firstDayOfWeek(); // 0 - Sunday
```

If you want to ignore the locale's definition of a week, you could use `startOf('isoWeek')` which always uses Monday as the start of the week.
