### ISSUE TITLE
YYYY in strict vs forgiving mode.

### ISSUE THREAD

**Issue by newtang** [moment/moment#4434]
**Description of the Issue and Steps to Reproduce:**
The documentation states that "YYYY from version 2.10.5 supports 2 digit years, and converts them to a year near 2000 (same as YY)" . However, this appears to be untrue in strict mode. [I demonstrated this in JSFiddle](https://jsfiddle.net/wj6dsxvv/)

I wasn't sure if this was a bug or unclear documentation. 

**Environment:**
Moment 2.20.1 
Chrome: 64.0.3282.140
Node 7.7.2

**Comment by prendradjaja** [comment]
This is both a bug and unclear documentation. See also #4301. YYYY should only parse 4-digit years.

@marwahaha
