### ISSUE TITLE
Moment doesn't use "best fit" format to accurately convey errors.

### ISSUE THREAD

**Issue by newtang** [moment/moment#4435]
**Description of the Issue and Steps to Reproduce:**
I would like to convey to my users that their day choice is invalid in a date such as `2/30/2019 7:00pm`.  Typically, `parsingFlags()` allows me to see there's an overflow error, and I can accurately report back to the user. However, if I use multiple formats, moment appears to report the `parsingFlags()` for the final format, not necessarily the one that best "fit" the string argument. In my example, `M/DD/YYYY h:mma`  "fits" much better than `MM-D-YYYY h:mm`, but if it's the last format in my array I'll see the `parsingFlags()` for that one. I [demonstrated this in jsfiddle.](https://jsfiddle.net/L5yyp80j/)

**Environment:**
Moment 2.20.1

**Comment by newtang** [comment]
It appears there might be something special with my choice of `2/30/2019`. If I use `02/30/2019` instead, I get the proper overflow reporting.

**Comment by marwahaha** [comment]
If you get to the bottom of it, feel free to make a PR!

**Comment by ichernev** [comment]
@newtang there is the concept of best-fit in the code for handling multiple formats, so it shouldn't be too hard to add.

**Comment by chrisbucholz** [comment]
If this is still up for grabs, I think I see how to fix it.
