### ISSUE TITLE
Types of property 'relativeTime' are incompatible.

### ISSUE THREAD

**Issue by shivijais** [moment/moment#4438]
After this change https://github.com/moment/moment/issues/3137, I can merge  a single relativeTime handler, like

```
moment.updateLocale('en', {
  relativeTime : {
    dd: (number) => {
       if (number < 7) {
            return number + ' days'; // Moment uses "d" when it's just 1 day.
          }
          else {
            var weeks = Math.round(number / 7);
            return weeks + ' ' + (weeks > 1 ? 'weeks' : 'week');
          }
        }
    }
  }
});
```

But it throws Typescript error 
`Types of property 'relativeTime' are incompatible.
      Type '{ dd: (number: any) => string; }' is not assignable to type 'RelativeTimeSpec'.
        Property 'future' is missing in type '{ dd: (number: any) => string; }'.`

The properties of RelativeTimeSpec interface should be marked optional in moment.d.ts.

**Comment by ichernev** [comment]
Close in favor of #4445
