### ISSUE TITLE
Feature Request: More ways to format timezone display

### ISSUE THREAD

**Issue by tsujp** [moment/moment#4440]
I would like to be able to display the timezone as +8 or +8.5 instead of either +0800 or +08:30. Can you add support for this?

**Comment by ashsearle** [comment]
Is this based on any standard?  Would you also expect to see `+5.75` (for Nepal)?  Do you think that's usable?

**Comment by tsujp** [comment]
Not that I know of.

I just want to get rid of leading 0s. I'd be happy with +5:45 for Nepal if that's the case.

**Comment by marwahaha** [comment]
This seems reasonable! I think we would take a PR for this.

**Comment by rishu2482** [comment]
thanks. Will submit a PR as soon as possible.

**Comment by rishu2482** [comment]
Hi @marwahaha , 
I have raised a pull request. Please review it and let me know if any updates required.

**Comment by rishu2482** [comment]
Hi @marwahaha ,
Please review the PR and let me know if any update required.

**Comment by ichernev** [comment]
@marwahaha I can argue how "useful" it is to display time(zone) in a non-standard format.

Also "polluting" the already crazy situation of timezone tokens with something, we can't even point to (again -- is there a standard about this?) is not a great idea.

@rishu2482 I understand that you want to help with moment's development, and your patch is not bad, but problems in programming are not always sorted with code :) You can be more active in the issues section.

The **correct** solution for this sort of problem is pluggable token system. We've discussed this in the past, there just needs to be an easy way for plugins to add new tokens, along with formatters and parsers. This is a bigger undertaking, and probably something we can consider for 3.x or later.
