### ISSUE TITLE
Wrong date format for locales

### ISSUE THREAD

**Issue by craigvn** [moment/moment#4441]
I am trying to parse some dates and noticed some locales differ from the standards. For example, given this simple code

```js
var localeData = moment.localeData('af-ZA');
console.log(localeData._config.longDateFormat.L);
```

It will display DD/MM/YYYY. Although this is 'commonly used', it is not technically the correct format for South Africa, it should be YYYY-MM-DD. Is it possible to change the locale info to include both formats?

**Comment by ashsearle** [comment]
You say you're parsing dates: do you need to parse locale-specific date formats, or can you achieve what you need by passing [multiple format strings](https://momentjs.com/docs/#/parsing/string-formats/) to the moment constructor?

**Comment by craigvn** [comment]
They are locale-specific dates, so they user stores their locale and based on that we assume the date format.

**Comment by marwahaha** [comment]
Thanks for writing.

We have a default format per locale. If you think a particular locale has an incorrect format, please submit a patch and tag the locale author. Then, we can have a discussion about the specific change.
