### ISSUE TITLE
Diff when a date time is set as 12:00 AM is not working correctly

### ISSUE THREAD

**Issue by VitoAlbano** [moment/moment#4443]
**Description of the Issue and Steps to Reproduce:**
Hi,

I am trying to compare two dates the same day but with a different time for example : 
'08/02/2018 12:00 AM' and '08/02/2018 11:50 AM' but it looks that i get wrong results into comparison.
For example : 
var dateA = moment('8-2-2018 12:00 AM','D-M-YYYY hh:mm A')
var dateB = moment('8-2-2018 11:00 AM','D-M-YYYY hh:mm A')

then : 
dateA.isBefore(dateB) => true.

is it an issue? 
Or there is something i'm doing wrong?

Thanks !

*Please include the values of all variables used.*

**Environment:**

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
Thu Feb 08 2018 12:11:31 GMT+0000 (GMT)
08/02/2018, 12:11:31
 0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
 2.18.1
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by ashsearle** [comment]
What do you think is wrong?  12:00 AM _is_ before 11:00 AM

**Comment by VitoAlbano** [comment]
Ok so probably my mistake was thinking that 12:00 refers to the same day and not the next one :) thanks
