### ISSUE TITLE
BUG: fromNow() doesn't take care the timezone 

### ISSUE THREAD

**Issue by C0deZLee** [moment/moment#4449]
**How to reproduce**
I have a variable _created_ returned from server in UTC format,
example: 2018-02-15T00:30:31Z
I want to display the time interval from _created_  to user's local time
this is my code:

```
1:   moment(_created_).local().fromNow()

2:   moment(moment(_created_).local().toISOString()).fromNow()

3:   var usertimezone = moment.tz.guess()
     var value = moment.utc(_created_)
     var formatDate = moment.tz(value, usertimezone)
     return formatDate.fromNow()
```
All don't work.
I googled 3 hours, tons of people are bothered by this problem since **2013**, and there is no solution, and this bug is not fixed.

Which is kind of disappointing for such a famous package.

**Environment:**
Chrome 53 on OSX

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

Sat Feb 17 2018 03:45:28 GMT-0500 (EST)
2 2/17/2018, 3:45:28 AM
300
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
2.20.1
```

**Comment by ashsearle** [comment]
@C0deZLee Could you provide some example expected and actual output, and perhaps an issue number that you say has existed since 2013?

(Please be aware that the maintainers on this project have probably changes since 2013, and may not even be aware of the issue you're talking about.)

**Comment by C0deZLee** [comment]
@ashsearle Yes I tried moment(_created_).fromNow(), and the value it returns has 5 hours diff with my current timezone, which means it uses UTC timezone instead of my current timezone

**Comment by ashsearle** [comment]
Can you give some example output?  Do you mean you're seeing something like "8 hours ago", when you should be seeing "3 hours ago"?

**Comment by C0deZLee** [comment]
@ashsearle Yes, that's what meant. It always has 5 hours shift

**Comment by ashsearle** [comment]
@C0deZLee I don't see this issue at all.

Are you using any moment plugins?
Are you changing the default timezone / locale for moment?
What are you doing (if anything) between `var created = moment(isoFormattedString)` and `created.fromNow()`?

**Comment by C0deZLee** [comment]
@ashsearle So the _created_ is an ISO-formatted string ending with Z returned from server,
and I tried `moment(_created_).fromNow()`at the very beginning but it didn't return the right result.
 (I assume using `moment(_created_).fromNow()` won't create any difference with ` var created = moment(isoFormattedString);created.fromNow()`?)

**Comment by ashsearle** [comment]
@C0deZLee If you can provide more information about your locale, timezone any moment plugins or the issue you said had been around since 2013, then I'll take another look at this.

Until then, this will remain a mystery.

**Comment by ashsearle** [comment]
@C0deZLee I thought of a couple more things to try.

Can you try these:
```js
console.log(moment.locale());
console.log(moment().subtract(2, 'hours').fromNow());
console.log(moment(moment().subtract(2, 'hours')).fromNow());
console.log(moment(moment().subtract(2, 'hours').toISOString()).fromNow());
```

**Comment by marwahaha** [comment]
Sorry, it's not clear what you are trying to do.

If you have a timestamp returned from a server in UTC, `fromNow` will give you the time difference from that timestamp to now. 

If you assume the server-returned timestamp is in the user's local time, you can strip the `Z` from the string.

Please re-open if you have still have issues.

**Comment by nicotroia** [comment]
I'm having a similar issue parsing a UTC date from the server using `fromNow`.
```
console.log('1', moment(date).format())
console.log('2', moment.tz(date, 'America/Los_Angeles').format())
console.log('3', moment.tz(date, 'America/New_York').format())
console.log('4', moment(date).fromNow())
console.log('5', moment.tz(date, 'America/Los_Angeles').fromNow())
console.log('6', moment.tz(date, 'America/New_York').fromNow())
```
Logs 1, 2, 3 display the time changing as expected (3 hr diff between NYC and LA)
Logs 4, 5, 6 (which use fromNow) all display the same value "in 4h", but I'm expecting "just now"

**Comment by ashsearle** [comment]
@nicotroia It would be really helpful to have examples of `date` - if you're passing a string, what format is it in?

**Comment by nicotroia** [comment]
@ashsearle sorry for the late reply. An example I "date" get from the server is `2018-10-23T11:02:22.000Z` which I believe is created with `moment().format('YYYY-MM-DD HH:mm:ss')`

**Comment by DeepSelvaraj** [comment]
Is this solved.. i am stuck form 2 days.. a solution would be a great help.


Thank you

**Comment by miaohf** [comment]
> Is this solved.. i am stuck form 2 days.. a solution would be a great help.
> 
> Thank you

me too, any help?

**Comment by kyec1118** [comment]
Hi :) 
I was having the same issue and solved it by using:
moment(moment(date).local()).fromNow()

**Comment by Kritika2808** [comment]
fromNow() is still not considering timezone

**Comment by hamza-HL** [comment]
moment.tz(date , "CurrentTimeZone").tz('RequiredTimeZon').fromNow()

**Comment by SyedAzeemJaved** [comment]
When creating a new momentJS object, try this:

moment.utc(date).fromNow()

This sets the _isUTC property on the moment object to true, and then .fromNow() will take into account the timezone offset.
