### ISSUE TITLE
YYYYMMDDHHmmss as Integer (or "preparing" input before moment parses it)

### ISSUE THREAD

**Issue by Matthijn** [moment/moment#4454]
Currently I am working on a project where in our current code base we work with timestamps in ms, and we are receiving data from an external service that uses the `YYYYMMDDHHmmss` format but sends it as integers. Moment parses correctly when the value is a string, but when it is an integer it thinks (correctly) it is a timestamp.

However, since our timestamps will never exceed 13 characters which allows us up to a date in the year 2286 I would like to allow parsing of 14 character numbers as the format above.

I can understand this is not something that you would want in most project. So I was thinking is there a way where I can "prepare" the value before moment parses it? With a hook or something. 

So if I do this `moment(20180404100000)` a hook is called where I can do a simple check like:

```
moment.beforeParse = function (value) {
    // The return value in this function is passed along to as in moment(value)
    if (typeof value === "number") {
        as_string = value + ""
        if (as_string.length === 14) { return as_string } 
    }
    return value
}
```

So it will parse numbers with a length of 14 as the `YYYYMMDDHHmmss` format and other numbers as timestamps.

**Comment by ashsearle** [comment]
moment doesn't have any hooks to preparse _numbers_ from the moment constructor.

Is there some reason you can't process the data from the external service either on receipt, or before just-in-time as you call the moment? constructor  

It seems like these would work fine (assuming your server's returning timestamps in UTC):
```js
var example = 20180228083000;
moment(String(example)); // parsed by JS runtime, emitting deprecation warning
moment(String(example).slice(0,8) + 'T' + String(example).slice(8)); // parsed as an ISO string
```

**Comment by Matthijn** [comment]
Yeah, doing that now, if it comes from their end first just converting it to a string. Thanks.
