### ISSUE TITLE
TypeScript error TS2430: Interface 'Moment' incorrectly extends interface 'Object'.

### ISSUE THREAD

**Issue by carmanchris31** [moment/moment#4459]
Full error message using TypeScript 2.7.1:
```
ERROR in [at-loader] ./node_modules/moment/moment.d.ts:413:13 
    TS2430: Interface 'Moment' incorrectly extends interface 'Object'.
  Types of property 'valueOf' are incompatible.
    Type '() => number' is not assignable to type '() => Object'.
      Type 'number' is not assignable to type 'Object'.
```

This affects versions 2.18.0 and up, based on the following commit:
https://github.com/moment/moment/commit/19b313d1c8cf5e2aa4577c9cc548efcffebc787b#diff-3dd6cebe542b0e207494192c4bbf4a22

**Comment by marwahaha** [comment]
`valueOf` is used specially in moment to return the number of ms since the Unix Epoch:
https://momentjs.com/docs/#/displaying/unix-timestamp-milliseconds/

Do you have a recommended fix? For now, the typings need to be 1.x compatible

**Comment by ichernev** [comment]
TS 1.x vs 2.x. Expect a fix with 3.x

**Comment by kevinsar** [comment]
@ichernev I recently upgraded my typescript version to 3.x and I was still getting this issue. Anyone confirm that this was a fix for this issue?

**Comment by bradymholt** [comment]
In the meantime, I've added this setting to `tsconfig.json` to prevent this suppress this error:

```
{
  "compilerOptions": {
    "skipLibCheck": true,
    ...
```

**Comment by aboutcroon** [comment]
> 

Thanks, this exactly helps !
