### ISSUE TITLE
Subtracting days using .day(x) subtracts an inconsistent amount

### ISSUE THREAD

**Issue by pmarshall111** [moment/moment#4460]
Try the below code in JSBin (using latest CDN). Same problem also happened in my project using node (2.20.1).

First bit of code should subtract 6 days, but subtracts 12.
Second bit should subtract 5 days, but subtracts 11.

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
<script>
var date = moment("2017-11-18", "YYYY-MM-DD");
console.log(date.toString());

var dayOfWeek = date.day();
console.log(dayOfWeek);

date.day(-dayOfWeek);
console.log(date.toString());
  
  
  
var date2 = moment("2017-11-18", "YYYY-MM-DD");
console.log(date2.toString())
date2.day(-5);
console.log(date2.toString())
</script>
```

Edit: Using moment().subtract(x) method works correctly and is perfect substitute. However, the docs do say that the above method should be possible https://momentjs.com/docs/#/get-set/day/

**Comment by ashsearle** [comment]
It sounds like you think that `moment().day(-1)` should return 'yesterday'.

That's not how it works.

I think you need to forget your assumptions about how `day()` works, and re-read the documentation.

`day()` is not a substitute for `add` or `subtract`.  It has a completely different purpose: to set the _day of the week_.

`moment().day(-6)` will go back to the beginning (Sunday) of the week, then go back a further 6 days.

In your example: "2017-11-18" is a Saturday.  So: `moment("2017-11-18").day(0)` will be Sunday 12th, and `moment("2017-11-18").day(-6)` is 6 days before that: Monday 6th.

This is working exactly as intended.

**Comment by pmarshall111** [comment]
I see now, thankyou for clearing it up.

Imo the examples should start from a non Sunday/0 day. From the examples given in the documentation it looks just like an add/subtract substitute.

`moment().day(-7); // last Sunday (0 - 7)`
-7 => go back 7 days

`moment().day(7); // next Sunday (0 + 7)`
7 => go forward 7 days

`moment().day(10); // next Wednesday (3 + 7)`
10 => go forward 10 days

`moment().day(24); // 3 Wednesdays from now (3 + 7 + 7 + 7)`
24 => go forward 24 days
