### ISSUE TITLE
isValid() not working properly with format as second parameter

### ISSUE THREAD

**Issue by brunosiqueira** [moment/moment#4462]
**Description of the Issue and Steps to Reproduce:**
isValid() has a weird behavior. Using the browser (momentjs site open), if I type:

`moment('2018-dkjsnaksaj x-null').isValid() >> false`

But if I set the format of the string as a second parameter, then I get:

`moment('2018-dkjsnaksaj x-null', 'YYYY-M-DD').isValid() >> true `

*Please include the values of all variables used.*

**Environment:**

Chrome  64.0.3282.186
MacOS High Sierra
*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
Thu Mar 01 2018 15:15:41 GMT-0300 (-03)
VM258:2 01/03/2018 15:15:41
VM258:3 180
VM258:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
VM258:5 2.20.1
undefined

**Comment by prendradjaja** [comment]
The parser is very forgiving unless strict mode is enabled. See docs [here](https://momentjs.com/guides/#/parsing/strict-mode/) and [here](https://momentjs.com/docs/) for more details.

You probably just want to enable strict mode by passing `true` as the last argument.

`moment('2018-dkjsnaksaj x-null', 'YYYY-M-DD', true).isValid() >> false`

@marwahaha

**Comment by marwahaha** [comment]
Yeah, strict mode will help here. There's more info [in this comment](https://github.com/moment/moment/issues/3004#issuecomment-192562297).
