### ISSUE TITLE
Guid parsing as valid in strict mode

### ISSUE THREAD

**Issue by togakangaroo** [moment/moment#4467]
moment("0d7879cc-8e5f-4cc8-9910-e54e48e9f9bb", 'YYYY-MM-DD').isValid()

gives you `true`. You can verify this [currently on the momentjs page](http://momentjs.com/docs/#/parsing/is-valid/)

```
Fri Mar 02 2018 14:28:28 GMT-0600 (CST)
3/2/2018, 2:28:28 PM
360
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
2.20.1
```

**Comment by NoMan2000** [comment]
Reproduced:  https://codepen.io/NoMan2000/pen/VQNLEv

**Comment by medinarkhov** [comment]
any integer in string makes moment date valid, i.e  moment("invalid1", 'YYYY-MM-DD')

**Comment by prendradjaja** [comment]
Issue title ("Guid parsing as valid in strict mode") is misleading -- your example is not parsing in strict mode. Use `true` as the last argument to use strict mode, i.e.

`moment("0d7879cc-8e5f-4cc8-9910-e54e48e9f9bb", 'YYYY-MM-DD', true).isValid()`

This gives `false`, as expected. (at least for me)

See also #3004, #3189.

**Comment by marwahaha** [comment]
Thanks @prendradjaja - let me know if there are other questions.
