### ISSUE TITLE
m.millisecond() returns zero

### ISSUE THREAD

**Issue by jlbooker** [moment/moment#4468]
**Description of the Issue and Steps to Reproduce:**
moment.millisecond() function is returning 0. It should return the number of milliseconds since epoch for the Moment instance its called on ([per docs](https://momentjs.com/docs/#/get-set/millisecond/)). Oddly, the `.unix()` function still works correctly. 

[Example JS Fiddle to reproduce](https://jsfiddle.net/0nhyc3np/5/)

```
function foo(){
    m = moment("02/27/2018", "MM/DD/YYYY");
    console.log(m.millisecond());
    console.log(m.unix());
}

foo();
}
```

Output is:
```
0
1519707600
```

This seems pretty basic, so I hope I'm just doing something wrong.

**Environment:**
Version 64.0.3282.186 (Official Build) (64-bit) on Fedora 27

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on: Eastern Standard (New York, US)
* The time and date at which the code was run: 2018-03-02 ~4:15pm
* Other libraries in use: Originally encountered in React, but ruled this out via JSFiddle.

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

Fri Mar 02 2018 16:18:50 GMT-0500 (EST)
3/2/2018, 4:18:50 PM
300
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
2.20.1
```

**Comment by marwahaha** [comment]
Perhaps there's a misunderstanding here. I think you're looking for `valueOf()`:
https://momentjs.com/docs/#/displaying/unix-timestamp-milliseconds/
> `moment#valueOf` simply outputs the number of milliseconds since the Unix Epoch, just like `Date#valueOf`.

Your moment object has only year, months, days, so things of higher resolution (incluidng sec & ms) are set to zero.
I ran this:
```
function foo2(){
    m = moment("02/27/2018", "MM/DD/YYYY");
    console.log(m.valueOf());
    console.log(m.unix());
}

foo2();
}
```

and received
```
1519718400000
1519718400
```

Please reopen if you have other issues.

**Comment by jlbooker** [comment]
@marwahaha Yep, that was it. Thanks!

The .milliseconds() function is in the "get + set" section of the docs, so I thought I was _getting_ the value of the moment object in milliseconds. I suppose it was getting just the milliseconds _part_ of the timestamp, which is correctly set to 0 when I only gave year/month/day.
