### ISSUE TITLE
Misbehavior in Safari

### ISSUE THREAD

**Issue by sassanh** [moment/moment#4469]
If your timezone is +3:30 (Iran) These expressions:
```
moment(new Date(2018,2,21,0,0,0)).startOf('day').format('YY/MM/DD HH:mm:ss ZZ')
moment(new Date(2018,2,22,0,0,0)).startOf('day').format('YY/MM/DD HH:mm:ss ZZ')
```
both return `"18/03/21 00:00:00 +0330"` in Safari.

Environment:
Safari 11.03, MacOS High Sierra (10.13.3)

There's no problem in Chrome.

```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
Result:
```
"Sat Mar 03 2018 20:12:57 GMT+0330 (+0330)"
"3/3/2018, 8:12:57 PM"
-210
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
"2.14.1"
```

If you run this JSBin in Safari with the above mentioned timezone you should see the results mentioned above in console.

**Comment by sassanh** [comment]
For reference: This was first reported in `moment-jalali` here: https://github.com/jalaali/moment-jalaali/issues/128.

**Comment by ashsearle** [comment]
This sounds like a bug in `Date`, not in `moment`.

Can you check the value of `new Date(2018,2,22,0,0,0).valueOf()` in Chrome and Safari?

**Comment by sassanh** [comment]
Sure, this is in Chrome:
```
> new Date(2018,2,22,0,0,0).valueOf()
< 1521664200000
> new Date(2018,2,22,0,0,0)
< Thu Mar 22 2018 01:00:00 GMT+0430 (+0430)
```
This is in Safari:
```
> new Date(2018,2,22,0,0,0).valueOf()
< 1521660600000
> new Date(2018,2,22,0,0,0)
< Wed Mar 21 2018 23:00:00 GMT+0330 (+0330)
```

**Comment by artitmedia** [comment]
Hello.
I am struggling with the same problem and can't seem to find a fix yet. Maybe someone will figure it out eventually...

Here is what I am using:

Firefox:
```
var time_zone_br = Intl.DateTimeFormat().resolvedOptions().timeZone;
console.log(time_zone_br);
var date_tz =  moment("2018-03-20 16:20").tz(time_zone_br).format("YYYY-MM-D HH:mm");
console.log(date_tz);
> America/Montreal
> 2018-03-20 12:20
```

Chrome:
```
var time_zone_br = Intl.DateTimeFormat().resolvedOptions().timeZone;
console.log(time_zone_br);
var date_tz =  moment("2018-03-20 16:20").tz(time_zone_br).format("YYYY-MM-D HH:mm");
console.log(date_tz);
> America/Montreal
> 2018-03-20 12:20
```

Safari:
```
var time_zone_br = Intl.DateTimeFormat().resolvedOptions().timeZone;
console.log(time_zone_br);
var date_tz =  moment("2018-03-20 16:20").tz(time_zone_br).format("YYYY-MM-D HH:mm");
console.log(date_tz);
> [Log] America/Montreal
> [Log] 2018-03-20 16:20
```

**Comment by jbpenrath** [comment]
Hi,
To complete this discussion, I encount also an issue with Safari (11.1)

Some string formats are considered as valid on Chrome & Firefox but not on Safari to generate a moment date.

*e.g*:
`moment('2018-3')` will give
**Chrome/Firefox** -> `Thu Mar 01 2018 00:00:00 GMT+0100 (CET)`
**Safari** -> `Invalid Date` but `moment('2018-03')`will be valid on Safari

**Comment by ichernev** [comment]
@sassanh I think it's pretty clear that there is some DST going on there. Browsers (and Safari in particular) are notoriously buggy in that regard. In moment 3.x DST will be handled internally, so all of that will go away. 2.x however -- there is no solution, other than to write tons of checks around each moment creation.

You can also try to pass the variables directly to moment, because using `moment(new Date(...))` means you pick the bugs of `Date` on the way.

**Comment by sassanh** [comment]
Thanks for clarification, I guess this is resolved till 21 March 2019 when this issue can show it again.

**Comment by ozgrozer** [comment]
I have same problem too. Chrome and Safari shows different times. Do you guys have any solution?

**Comment by timendez** [comment]
This is an ongoing problem with dates and Safari both on desktop and on mobile. Unfortunately all browsers on iOS use Safari as an underlying platform, so they're all broken because Safari is.
