### ISSUE TITLE
[Suggestion] Make Strict Mode as default option

### ISSUE THREAD

**Issue by medinarkhov** [moment/moment#4471]
Would you like to make Strict mode a default parsing option?
`moment("2018-03-03", 'YYYY-MM-DD')` for Strict Mode
`moment("2018-03-03", 'YYYY-MM-DD', false)` for Forgiving Mode

According to the documentation, Strict mode is the recommended mode for parsing dates. Nevertheless, I noticed that so many issues have been raised because of NOT using Strict mode.  It it likely that similar issues will be raised again and again. 

Just a suggestion, happy to help with implementation. Feel free to decline if you don't like the idea.

**Comment by marwahaha** [comment]
Thanks for the suggestion. It's in our list here:
