### ISSUE TITLE
How to get the before date from the current date in ISO format?

### ISSUE THREAD

**Issue by bhanuprasad04** [moment/moment#4477]
I have followed below approach to get one day before day for the current date
          var moment = require('moment');
          var beforedate = moment().subtract(1,'days');
          log.info("start date "+beforedate.startOf('day').toDate());
          log.info("End date "+beforedate.endOf('day').toDate()); 
But it is giving the result like below 
Sun Mar 05 2018 00:00:00 GMT+0530
Sun Mar 05 2018 23:59:59 GMT+0530
But I want above format in ISO, can you please help me on this .

**Comment by lad475** [comment]
Hi!  If you see [here in the documentation](https://momentjs.com/docs/#/displaying/as-iso-string/), if you'd like your date to be formatted as ISO when printing it out, you should simply use the toISOString() method.

If you want your current code to be logged out as ISO
`var moment = require('moment');
var beforedate = moment().subtract(1,'days');
console.log("Start date "+beforedate.startOf('day').toISOString());
console.log("End date "+beforedate.endOf('day').toISOString());:`

**Comment by marwahaha** [comment]
Thanks @lad475 !

You can also try [`moment.utc`](https://momentjs.com/docs/#/parsing/utc/):
```
moment.utc().startOf('day').toISOString()
> "2018-04-04T00:00:00.000Z"
moment.utc().subtract('1', 'day').startOf('day').toISOString()
> "2018-04-03T00:00:00.000Z"
```

Please re-open if you still have issues.
