### ISSUE TITLE
'G_YYYYMMDD' Parsing Error

### ISSUE THREAD

**Issue by ybbarng** [moment/moment#4480]
**Description of the Issue and Steps to Reproduce:**
http://jsfiddle.net/dp7rzmw5/8354/
```
moment('G_20180307', 'G_YYYYMMDD').isValid() === false
moment('A_20180307', 'A_YYYYMMDD').isValid() === true
```
*Please include the values of all variables used.*

**Environment:**

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
Wed Mar 07 2018 00:41:20 GMT+0900 (대한민국 표준시)
2018. 3. 7. 오전 12:41:20
-540
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
2.21.0

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by marwahaha** [comment]
You can escape the `G` - that character is used for other parsing.

```
> moment('G_20180307', '[G]_YYYYMMDD').isValid()
true
```

**Comment by ybbarng** [comment]
There are two points I want to ask.
1. What is the single G means? I can find only double G (GG) or four Gs (GGGG) have meanings, not a single G. It looks like that it means a single year digit (one digit), but it is not documented.

2. A single 'A" character has also meaning (am/pm), but it says that normal 'A' character is also valid. The followings are all true.
moment('A_20180307', 'A_YYYYMMDD').isValid(): true
moment('am_20180307', 'A_YYYYMMDD').isValid(): true
moment('pm_20180307', 'A_YYYYMMDD').isValid(): true
But 'G" is not. What is the different G and A?
