### ISSUE TITLE
The moment dependency defined in package-lock.json has a known moderate severity security vulnerability

### ISSUE THREAD

**Issue by apmeena** [moment/moment#4482]
![image](https://user-images.githubusercontent.com/6169344/37078320-cb0cde16-2204-11e8-9b1c-13b2d5ea833e.png)

The moment dependency defined in package-lock.json has a known moderate severity security vulnerability in version range < 2.19.3 and should be updated.

**Comment by Fedeorlandau** [comment]
Same here

**Comment by marwahaha** [comment]
Can you show a bigger screenshot? We are on version 2.21.0 now. There was a vulnerability in the past, but it has since been fixed.

Also, I don't see a package-lock.json anywhere inthe code.

**Comment by visualcookie** [comment]
Here a `package-lock.json`: https://github.com/visualcookie/auth-api/blob/master/package-lock.json

And a detailed screenshot: 
![image](https://user-images.githubusercontent.com/1857554/37223960-6b9052f4-23d2-11e8-9c7c-87bef95e4bdf.png)

**Comment by marwahaha** [comment]
Cool. This is for consumer's `package-lock.json`.

GitHub is trying to be helpful here. I would heed its advice and update your version of `moment`.

I think `npm update moment` will do the trick.

Let me know if folks have issues.
