### ISSUE TITLE
why date is changed to GMT while actually +03 and that on JSON?

### ISSUE THREAD

**Issue by msman** [moment/moment#4483]
Hi,

At nodejs, I conole.log a date and get :
`moment.parseZone("2018-03-07T00:00:00.000+03:00")`
but on Postman, on JSON, it is appeared to be 
`2018-03-06T21:00:00.000Z`

Notice the difference on date, 1 day is decreased and time is decreased 3 hours as well.
what can solve this? It should appear as it is on JSON, right?

And at the front end, reactjs, the date is read as 07-03-2018 without including .tz(...) for it.

I am afraid if I use the .tz(...) at front end, I will increase the hours and will lead to bugs. Or shall I leave date without .tz(...) at front end. I am confused of that different value on node and JSON.

Thank you for you help

**Comment by ashsearle** [comment]
The [docs for toJSON](https://momentjs.com/docs/#/displaying/as-json/) say the date will be formatted in UTC, which is the format ending in `Z` - and is equivalent to `+00:00`.

i.e. these are representations of the same point in time:
```
2018-03-07T01:00:00.000+04:00
2018-03-07T00:00:00.000+03:00
2018-03-06T23:00:00.000+02:00
2018-03-06T22:00:00.000+01:00
2018-03-06T21:00:00.000+00:00
2018-03-06T21:00:00.000Z
```

I hope that makes sense.
