### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by ScreamZ** [moment/moment#4484]
https://github.com/moment/moment/blob/d0a45f0390c108cc18d71a3d3f38d040392483c5/moment.js#L1830

Use https://www.npmjs.com/package/include-all from sails.

**Comment by ichernev** [comment]
@ScreamZ heh, this is a very well discussed topic here, mostly related to webpack.

We're not really changing that for 2.x. For 3.x we might just provide separate targets, but that code is not moving away anytime soon.
