### ISSUE TITLE
TypeScript docs has invalid ESM usage

### ISSUE THREAD

**Issue by jdalton** [moment/moment#4488]
The doc example [here](https://momentjs.com/docs/#/use-it/typescript/):

```
import * as moment from 'moment';

let now = moment().format('LLLL');
```
Is performing a namespace object import but expecting the `moment` default export function. This is causing bundlers like parcel grief as they try to support this invalid ESM syntax.

Related to:
https://github.com/parcel-bundler/parcel/pull/530

**Update:**

With [TypeScript 2.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html) you can now flag to throw on this incorrect use and also support
`import d from "cjs"` with `--esModuleInterop`.

**Comment by marwahaha** [comment]
Moment is still TS 1.x-compatible. We're open to suggestions, provided you don't break existing functionality.

I dont know much about Parcel, but maybe others around here do.
