### ISSUE TITLE
Cannot read property 'humanize' of undefined

### ISSUE THREAD

**Issue by munkhorgil** [moment/moment#4493]
When I set locale as mn it produces error if I use updateLocale, On the contrary If I use locale instead of updateLocale there is no error, but gives depreciation warning. 
**Code as follows**
```
moment.updateLocale('mn', {
    relativeTime: {
        future: '%s дараа',
        past: '%s өмнө',
        s: 'саяхан',
        m: 'минутын',
        ...
    }
});

moment.locale('mn');
```
**Environment:**
- Chrome
- OSX
- Node JS
- React JS
- Moment 2.17

**Error:**
**Cannot read property 'humanize' of undefined**

**Comment by ashsearle** [comment]
Can you check if this problem still exists in 2.21.0, and if it does can you show a bit more code for us to reproduce.

(I tried the code you provided - with `...` deleted - and it works fine.)

**Comment by munkhorgil** [comment]
@ashsearle I've just upgraded to 2.21.0 error still showing here is my code
```
import React from 'react';
import ReactDOM from 'react-dom';
import { KnowledgeBase } from './containers';
import './sass/style.scss';
import TranslationWrapper from '../TranslationWrapper';
import moment from 'moment';

window.addEventListener('message', (event) => {
  // set locale moment
  moment.updateLocale('en', {
    relativeTime: {
      future: 'in %s',
      past: '%s ',
      s: 's',
      m: 'm',
      mm: '%d m',
      h: 'h',
      hh: '%d h',
      d: 'd',
      dd: '%d d',
      M: 'a mth',
      MM: '%d mths',
      y: 'y',
      yy: '%d y',
    },
  });

  moment.updateLocale('mn', {
    relativeTime: {
      future: '%s дараа',
      past: '%s өмнө',
      s: 'саяхан',
      m: 'минутын',
      mm: '%d минутын',
      h: '1 цагийн',
      hh: '%d цагийн',
      d: '1 өдрийн',
      dd: '%d өдрийн',
      M: '1 сарын',
      MM: '%d сарын',
      y: '1 жилийн',
      yy: '%d жилийн',
    },
  });

  moment.locale('mn');

  // render root react component
  ReactDOM.render(
      <TranslationWrapper>
        <KnowledgeBase />
      </TranslationWrapper>,
    document.getElementById('root'),
  );
});

```

**Comment by munkhorgil** [comment]
@ashsearle There is no locale for **mn** so that I put **moment.defineLocale('mn', ...)** instead of updateLocale now it works fine.

**Comment by munkhorgil** [comment]
Unfortunately deprecation warning shows up @ashsearle

**Comment by ashsearle** [comment]
Which line of code triggers the deprecation warning?  Which warning is it?

**Comment by munkhorgil** [comment]
Warning as follows: **deprecation warning use moment.update locale**
`moment.locale('mn') `

**Comment by ashsearle** [comment]
I'm not convinced you've given the right warning or line of code.

I suspect you're actually seeing:
> Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.

You're trying to configure two locales.  One already exists (`'en'`) and one doesn't (`'mn'`)

You should use `updateLocale` to modify the `'en'` locale, and `defineLocale` for the `'mn'` locale.

If you do that, does it get rid of the deprecation warning?

**Comment by marwahaha** [comment]
@munkhorgil - try upgrading to 2.22.0 - [we now support locale `mn`](https://github.com/moment/moment/blob/develop/CHANGELOG.md).

Please re-open if you still have problems.

**Comment by bhaskardabhi** [comment]
Using 2.27.0 still issue is there
