### ISSUE TITLE
Default formats of format() function are missing milliseconds

### ISSUE THREAD

**Issue by sylv3r** [moment/moment#4497]
I don't know if this is by design, and if yes why, but the default formats (local and utc) of the `format()` function are missing milliseconds.

https://github.com/moment/moment/blob/b8bc8353c92172ee2e3669a62c854467f47daae4/src/lib/moment/format.js#L56-L62
https://github.com/moment/moment/blob/b8bc8353c92172ee2e3669a62c854467f47daae4/src/lib/moment/format.js#L5-L6

**Example** :

```js
// milliseconds are still there
moment(1520984439342, 'x').utc() // moment.utc("2018-03-13T23:40:39.342+00:00")

// milliseconds are missing
moment(1520984439342, 'x').utc().format() // 2018-03-13T23:40:39Z
```

I expect the `format()` function to not filter any information by default if no custom format string is provided : 

```js
// milliseconds should be included :
moment(1520984439342, 'x').utc().format() // 2018-03-13T23:40:39.342Z
```

**Comment by marwahaha** [comment]
To be clear, the constructor is not losing any information.
```
moment(1520984439342, 'x').utc().format('YYYY-MM-DDTHH:mm:ss.SSSZ')
> "2018-03-13T23:40:39.342+00:00"
```
The default format is [clearly documented](https://momentjs.com/docs/#default-format). If you don't like it, you can use a different format.
