### ISSUE TITLE
duration.abs() returns negative number of days

### ISSUE THREAD

**Issue by XeniaSiskaki** [moment/moment#4499]
**Description of the Issue and Steps to Reproduce:**
I am trying to get the duration between two dates but the number of days is negative albeit the `abs` call:

```js
var date1 = moment("2018-03-13 09:57:57");
var date2 = moment("2018-03-14 10:03:16");
var duration = moment.duration(date1.diff(date2)).abs();
duration.days(); // -1
// duration._data = {days: -1, hours: 0, milliseconds: 0, minutes: 5, months: 0, seconds: 19, years: 0}
```

**Environment:**
Chrome 60 on OpenSuse13.1

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on => GMT+0100 (CET)
* The time and date at which the code was run => "Wed Mar 14 2018 10:15:40 GMT+0100 (CET)"
* Other libraries in use (TypeScript, Immutable.js, etc) => I don't think it matters since the issue is reproducible in https://momentjs.com/

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
// "Wed Mar 14 2018 10:17:17 GMT+0100 (CET)"
console.log((new Date()).toLocaleString())
// 3/14/2018, 10:17:31 AM
console.log( (new Date()).getTimezoneOffset())
// -60
console.log( navigator.userAgent)
// Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
console.log(moment.version)
// 2.21.0
```

**Comment by ashsearle** [comment]
The [documentation for diff](https://momentjs.com/docs/#/displaying/difference/) has this to say (several paragraphs down):
> If the moment is earlier than the moment you are passing to moment.fn.diff, the return value will be negative.

That sounds like your case - date1 is earlier than date2.  I think this is working as expected.

**Comment by ashsearle** [comment]
I suggest you avoid duration.abs() and instead use:

```js
moment.duration(Math.abs(date1.diff(date2)));
```

`abs()` isn't documented, and IMHO it's hard to figure out what it should do: it currently runs the durations time fields through `Math.abs` independently of the date fields, which can cause the whole meaning of the duration to change.

e.g. `moment.duration('P1DT-12H').abs().toString()` becomes `'P1DT12H'`, and `'P1Y-3D'` becomes `'P1Y3D'` - the results are significantly different durations by any measure.

If you take a step back and think about defining `abs()` as flipping the sign on all fields such that the overall duration is moving forward in time, then you need to know a reference date: e.g. `P1M-29D` might be positive in time most of the year, but not some days.  Similarly something like `'P1DT-23H-30M'` could normally be summed up as 30 minute duration forwards in time... _except around changes for DST_.

(Your issue highlights a bug where the 'days' field of a duration's internal data structure doesn't get passed through `Math.abs`.  However, making a one-line change to fix that doesn't help with any of the issues above.)

**Comment by XeniaSiskaki** [comment]
Thanks for your input! I'll go with your solution.

But I guess `abs` should be documented so that we avoid such errors.
