### ISSUE TITLE
No Documentation for .set({day

### ISSUE THREAD

**Issue by JamesWilkinson-ICFOlson** [moment/moment#4500]
I've observed that I can set a day of the week with

```
openTime = moment.tz(moment(), todayWorkingHours.timeZoneName).set({
                'day': -1,
                'hour': todayWorkingHours.start_time.split(":")[0],
                'm':todayWorkingHours.start_time.split(":")[1],
                's': 0}).format();
            closeTime = moment.tz(moment(), todayWorkingHours.timeZoneName).set({
                'day': todayWorkingHours.end_day,
                'hour': todayWorkingHours.end_time.split(":")[0],
                'm': todayWorkingHours.end_time.split(":")[1],
                's': 0
            }).subtract(todayWorkingHours.lead_time, 'm').format();
```

But in our code reviews one dev noticed that set for day is not documented.

**Comment by marwahaha** [comment]
Hi @JamesWilkinson-ICFOlson 

We have some (admittedly terse) documentation here: http://momentjs.com/docs/#/get-set/set/

If you have suggestions for better docs, please let us know! Otherwise, feel free to close the issue.

**Comment by JamesWilkinson-ICFOlson** [comment]
It's there a repo for the docs I can submit PR to update?



On Mon, Apr 2, 2018 at 9:54 AM +0200, "Kunal Marwaha" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @JamesWilkinson-ICFOlson<https://github.com/JamesWilkinson-ICFOlson>

We have some (admittedly terse) documentation here: http://momentjs.com/docs/#/get-set/set/

If you have suggestions for better docs, please let us know! Otherwise, feel free to close the issue.

-

**Comment by marwahaha** [comment]
https://github.com/moment/momentjs.com
