### ISSUE TITLE
Wrong Belarusian translation: no cases.

### ISSUE THREAD

**Issue by SobakaSlava** [moment/moment#4502]
There are some grammatical mistakes in Belarusian translation: cases are not taken into consideration. Russian language is similar to Belarusian, but Russian localisation has no mistakes. 
E.g. instead of "У мінулую пятніца ў 15:00" should be "У мінулую пятніцУ ў 15:00"

**Comment by marwahaha** [comment]
Hi @SobakaSlava - thanks for writing. 

We have our Belarusian translation here:
https://github.com/moment/moment/blob/develop/src/locale/be.js

If you can, please make a Pull Request with what should be changed.

Otherwise, perhaps @demidov91 or others can help out.
