### ISSUE TITLE
How to use submodul importing in moment?

### ISSUE THREAD

**Issue by safeimuslim** [moment/moment#4504]
Hi, 
How to use submodul importing in moment? 
When i import like `import moment from 'moment'`, the produce file so big.

![screen shot 2018-03-18 at 22 31 12](https://user-images.githubusercontent.com/12455939/37567622-1f60da94-2afc-11e8-8537-cc018468989e.png)

**Comment by raysuelzer** [comment]
From looking at the webpack config, it seems that it is importing all the locales, this isn't necessary in many cases.  Is there a way to not import all locales?

**Comment by kirankalyan5** [comment]
+1

**Comment by ichernev** [comment]
https://github.com/moment/moment/issues/2416
