### ISSUE TITLE
Compare methods should treat date strings in the same timezone

### ISSUE THREAD

**Issue by xehpuk** [moment/moment#4507]
**Description of the Issue and Steps to Reproduce:**

I'd expect the compare methods to parse the first argument in the same timezone as the moment object it was called on:

```js
moment('2018-01-01').isSameOrAfter('2018-01-02', 'day') === false // ok
moment.utc('2018-01-01').isSameOrAfter('2018-01-02', 'day') === true // issue
moment.utc('2018-01-01').isSameOrAfter(moment.utc('2018-01-02'), 'day') === false // workaround
```

**Environment:**

* Chrome 65 on Windows 10

**Other information that may be helpful:**
```
Wed Mar 21 2018 15:32:47 GMT+0100 (Mitteleuropäische Zeit)
21.3.2018, 15:32:47
-60
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
2.20.1
```

**Comment by marwahaha** [comment]
I don't love this, but if the first argument in `isSameOrAfter` is not a `moment`, it gets treated like the input to the `moment()` constructor.

Do you think the `.utc.isSameOrAfter()` should work differently?

**Comment by xehpuk** [comment]
I'd find it more logical as comparisons between local and UTC moments should be the exception. (At least I think so.)

**Comment by GomuGilad6** [comment]
@marwahaha I will be happy to give it a try!

**Comment by nisha-kaushik** [comment]
Is this available to pick up. I would like to pick this is up as my initial contribution.

**Comment by ichernev** [comment]
@xehpuk so if I understand correctly your proposal is to handle moment.utc(...).isXXX(str) to mean that the str is utc as well?

What if the moment on the left has utcOffset set manually, would you want that too to propagate to the string? I'm not so sure.

I think you need to specify a moment object and remove all ambiguity as of what it means.

I think we should keep the logic as is -- it is at least easier to understand.
