### ISSUE TITLE
Problem with parsing specific date string in catalan language

### ISSUE THREAD

**Issue by bkahraman** [moment/moment#4508]
**Description of the Issue and Steps to Reproduce:**
When creating a date from the string `'4 de maig'` using format `'M DDDD'` and locale `'ca'` I am getting a wrong date. The problem is reproducable through interactive node.js shell:
```
> moment = require('moment')
....
> moment.locale('ca')
'ca'
> moment('2018-05-04').format('D MMMM')
'4 de maig'
> moment('4 de maig', 'D MMMM')
moment("2018-03-04T00:00:00.000")
> moment('4 de maig', 'D MMMM', true)
moment.invalid(/* 4 de maig */)
```

**Environment:**
*Node.JS v8.9.4 on macOS Sierra 10.13.3*
```
> console.log( (new Date()).toString())
Wed Mar 21 2018 22:34:11 GMT+0100 (CET)
> console.log((new Date()).toLocaleString())
2018-3-21 22:34:11
console.log( (new Date()).getTimezoneOffset())
-60
> console.log(moment.version)
2.20.1
```

Any ideas what's going wrong here? Thanks for any suggestion in advance.

**Comment by marwahaha** [comment]
@juanghurtado - thoughts ?

**Comment by juanghurtado** [comment]
Right now i'm rather busy and cannot take a look at this. However it seems that @dmckenna24 is right. If someone can pick this up and take a look, it would be great.

**Comment by urinieto** [comment]
As a native Catalan and Spanish speaker, `4 de maig` is the right Catalan translation of `May 4th`. However, the Spanish translation seems wrong: should be `4 de mayo`, not `4 mayo.`

The strictly correct thing to do here would be to update the Spanish localization strings by adding the `de` preposition in front of every month. In Catalan, the preposition should be `de` if the month starts with a consonant (e.g., `4 de maig`) or `d'` otherwise (e.g., `4 d'abril`).

**Comment by juanghurtado** [comment]
If `moment('2018-05-04').format('D MMMM')` returns '4 mayo' and '4 May' as @dmckenna24 said, the correct translation to catalan would be '4 maig', just to be consistent with all the other translations.

**Comment by urinieto** [comment]
Yup, that would be the correct translation from an incorrect way of saying a date in Spanish.

**Comment by juanghurtado** [comment]
And also from an incorrect way of saying a date in english, don't forget that.

Once we have 'May 4th' as the result of that command un english, the translation to catalan should be changed to '4 de maig'. Until then, I guess the right behavior is that it should be '4 maig'.

**Comment by ichernev** [comment]
The format() call produces a stupid verbatim concatenation of strings, with some minor availability for tweaking (nominative/accusative month names are supported somewhat).

The best way to do this is for the function to collect the tokens and then figure out a correct way to spell it out in each locale. This is, unfortunately, out of the scope of what moment is doing right now.
