### ISSUE TITLE
setRelativeTime should pass current date to formatter

### ISSUE THREAD

**Issue by TylerYang** [moment/moment#4510]
**Should provide a way for relativeTime formatter(function) to access to current time:**
Consider the requirements below, 
```
const baseTime = moment('2018-03-23 16:00:00')
moment('2018-03-22 18:00:00').from(baseTime)  // output: `a day ago`
```
we might need to customize the text to: `18:00 Yesterday`

There is no solution to do it right now because the relativeTime formatter cannot access to `baseTime`.
From [this line](https://github.com/moment/moment/blob/develop/src/lib/locale/relative.js#L23) we know that `this` is not pointing to current moment instance.

Any suggestions would be appreciated.

**Comment by marwahaha** [comment]
Interesting idea.
Unfortunately, we do not plan to implement new features.
See https://momentjs.com/docs/#/-project-status/
