### ISSUE TITLE
Parsed time after DST switch displayed with +1 hour than its current time. 

### ISSUE THREAD

**Issue by Webrow** [moment/moment#4512]
**Description of the Issue and Steps to Reproduce:**
Parse and display the following timestring: "2018-03-25T19:00:00+01:00"
Note, this time is after the DST switch. 
When I display this time with  a.format("HH:mm") I would expect. 19:00. 
But it shows, 20:00. 
Is there a way to print times in their current equivalent? (I suppose this issue is gone after next saturday) but will appear again over 6 months. 

*Please include the values of all variables used.*
var a = moment("2018-03-25T19:00:00+01:00")

**Environment:**
58.0.2 (64-bit) Mozilla Firefox on Ubuntu
Ubuntu 16.04

**Other information that may be helpful:**
Location is amsterdam. 
CET (Central European Time)
UTC/GMT +1 hour

If you are reporting an issue, please run the following code in the environment you are using and include the output:
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
Fri Mar 23 2018 16:11:32 GMT+0100 (CET)
23/03/2018, 16:11:32
-60 
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0code:4:1
2.21.0
(bower installed)  "moment": "^2.17.0",

**Comment by ashsearle** [comment]
I think you might be looking for `parseZone`:

```js
moment.parseZone("2018-03-25T19:00:00+01:00").format('HH:mm'); // 19:00
moment.parseZone("2018-03-25T19:00:00+02:00").format('HH:mm'); // 19:00
moment.parseZone("2018-03-25T19:00:00+03:00").format('HH:mm'); // 19:00
```

**Comment by marwahaha** [comment]
@Webrow does this answer your question? 
See https://momentjs.com/docs/#/parsing/parse-zone/ for more info

**Comment by Webrow** [comment]
Sorryz forgot to close it. Yeah it was parsezone!

Op wo 4 apr. 2018 09:03 schreef Kunal Marwaha <notifications@github.com>:
