### ISSUE TITLE
Add "module" support

### ISSUE THREAD

**Issue by amilajack** [moment/moment#4513]
Bundlers are now leveraging the `module` property to support es6 improts/exports. Would a PR for adding this property be welcome?

**Comment by amilajack** [comment]
Implications for the codebase are that it will need to allow users to import an esnext build which uses es6 modules. Having users import `moment` via es6 modules rather than commonjs that will allow apps such as `webpack`, `rollup`, `parcel`, etc to [treeshake](https://webpack.js.org/guides/tree-shaking/) modules, producing smaller and more optimized builds for the user

**Comment by ichernev** [comment]
@amilajack you mean the es6 import/export? So there needs to be a separate codebase (they can not coexist as with UMD in the past).

Also treeshaking moment is non-sense -- its one object with everything attached to it. Anyway, I though there was an ES5 compatible way to export ES6 modules, I guess I was dreaming a bit too much.
