### ISSUE TITLE
[Bug] Timezone offset is set to zero after changing system timezone

### ISSUE THREAD

**Issue by sellakkumaran** [moment/moment#4516]
**Environment:**

-  All browsers in **macOS High Sierra** 

Description of the Issue and Steps to Reproduce:

- current timezone offset (-330)

- change the system timezone to (-480)

- moment time zone offset is shown as (0)

PS: Issue not occuring in new tab

**Comment by ashsearle** [comment]
moment gets its timezone offset information from `Date`.

You've identified a problem with the macOS timezone propagating to `Date`, which isn't something moment can detect or do anything about.

The timezone propagation isn't consistent in browsers at all.
e.g. if you create a Date instance (`d = new Date()`) and check `d.getTimezoneOffset()` before/after changing time zone you'll see that the timezone offset doesn't change in Firefox and Safari, but gets set to 0 in Chrome.

If you look at Firefox in particular and check `new Date().getTimezoneOffset()` you can see it either retains its original value, gets reset to 0, or takes on the new timezone value depending on whether you're looking at windows/tabs which which were already open, the 1st tab in a new window or a new tab in a new window.  Even better, I've seen it retain original value, reset to 0 or new timezone value in a new _private_ window's 1st, 2nd and 3rd tabs respectively.

These are macOS/browser environment propagation bugs which moment won't be able to detect.

**Comment by ichernev** [comment]
@ashsearle thank you! I completely agree, I don't think this is something moment could handle, even if we wanted to.

@sellakkumaran you can try to address this issue with browser vendors themselves. You can also try to work around it using an iframe (it could get a new "context" with the correct time in it), or something similar. But any crazy hack like this has no place in moment.
