### ISSUE TITLE
webpack warning with moment for missing 'locale' folder

### ISSUE THREAD

**Issue by dpundir** [moment/moment#4519]
I am using moment version@2.10.6 and seeing warning message in webpack run.

`WARNING in ./node_modules/moment/min/moment-with-locales.js
Module not found: Error: Can't resolve './locale' in 'E:\code\web-base\node_modules\moment\min'
 @ ./node_modules/moment/min/moment-with-locales.js 263:16-43
 @ ./node_modules/moment/min/moment-with-locales.js-exposed
`
I am using webpack alias:
`'moment': 'node_modules/moment/min/moment-with-locales',`

After changing the 'locale' path to include '../' the warning disappear:
`
    function loadLocale(name) {
        var oldLocale = null;
        // TODO: Find a better way to register and load all the locales in Node
        if (!locales[name] && typeof module !== 'undefined' &&
                module && module.exports) {
            try {
                oldLocale = globalLocale._abbr;
                require('./../locale/' + name);
                // because defineLocale currently also sets the global locale, we
                // want to undo that for lazy loaded locales
                locale_locales__getSetGlobalLocale(oldLocale);
            } catch (e) { }
        }
        return locales[name];
    }
`

Environment: windows 10 and might be linux as well

**Comment by stephenway** [comment]
Can confirm this is happening on 2.22.1 also.

**Comment by pgee70** [comment]
i have this issue with version 2.24.0
npm run build gives: (via react boilerplate)
...
```
WARNING in ./node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/opt/local/www/apache2/html/cdr/node_modules/moment/src/lib/locale'
 @ ./node_modules/moment/src/lib/locale/locales.js
 @ ./node_modules/moment/src/lib/locale/locale.js
 @ ./node_modules/moment/src/moment.js
 @ ./node_modules/@date-io/moment/build/index.js
 @ ./app/containers/presentation/ThemeProvider/index.js
 @ ./app/app.js
 @ multi ./node_modules/react-app-polyfill/ie11.js ./app/app.js
```
...

i have found the warning is resolved if i change the file:
`node_modules/moment/src/lib/locale/locales.js`

```
function loadLocale(name) {
    var oldLocale = null;
    // TODO: Find a better way to register and load all the locales in Node
    if (!locales[name] && (typeof module !== 'undefined') &&
            module && module.exports) {
        try {
            oldLocale = globalLocale._abbr;
            var aliasedRequire = require;
            aliasedRequire('./locale/' + name);
            getSetGlobalLocale(oldLocale);
        } catch (e) {}
    }
    return locales[name];
}
```
to:
```
function loadLocale(name) {
    var oldLocale = null;
    // TODO: Find a better way to register and load all the locales in Node
    if (!locales[name] && (typeof module !== 'undefined') &&
            module && module.exports) {
        try {
            oldLocale = globalLocale._abbr;
            var aliasedRequire = require;
            aliasedRequire('/' + name);
            getSetGlobalLocale(oldLocale);
        } catch (e) {}
    }
    return locales[name];
}
```

**Comment by marwahaha** [comment]
I don't think Moment.js can do anything about this.

See also https://momentjs.com/docs/#/-project-status/

Fortunately it seems like it's only a warning.

**Comment by tabrez96** [comment]
Any workaround for this with webpack plugins?

**Comment by Aston13** [comment]
This issues has resurfaced (currently on v2.29.4)

**Comment by baphony** [comment]
Same for me with version 2.29.1

**Comment by mattjohnsonpint** [comment]
Please see https://github.com/moment/moment/issues/6092#issuecomment-5331841987
