### ISSUE TITLE
Still see this bug #3717 ([bugfix] Fixes #3717, ensure day-of-year is non-zero #3787)

### ISSUE THREAD

**Issue by Stanols** [moment/moment#4531]
Hi there,

Quite simple to reproduce, parsing a number with 7 characters using moment.ISO_8601 is returning true.

Examples:

moment(1111201, moment.ISO_8601, true).isValid() // true
I run directly on the moment.js website

Version
Chrome Version 55.0.2883.95 (64-bit) on OSX

**Comment by marwahaha** [comment]
This is intended behavior. In this case, it is parsed as year=1111, day-of-year=201. 

[See this comment](https://github.com/moment/moment/issues/3717#issuecomment-276395363) for more details.
