### ISSUE TITLE
set does not update an invalid moment object

### ISSUE THREAD

**Issue by linqcan** [moment/moment#4532]
**Description of the Issue and Steps to Reproduce:**
The issues stems from working with leap years and dates in "MMM DD" format.
If I parse a leap year date (today, 2018) like "Feb 29" the moment object is invalidated.
When I then try and change the year to a leap year, like 2020, the moment object is not updated.

```
> a = moment("Feb 29", "MMM DD")
> a.set('year', 2020)
> a.year()
< NaN
> a.toDate()
< Invalid Date
```
I am expecting `a.year()` to return "2020" and `a.toDate()` to return a date equal to "2020-02-29".

The [documentation ](https://momentjs.com/docs/#/get-set/set/) does not mention that `set()` only works for valid objects.

Note that the above example only works if the current year is a non-leap year as moment assumes the current year if omitted in the parsed string.

Either code or docs need updating, imho.

**Environment:**
Google Chrome Version 65.0.3325.181 (Official Build) (64-bit) Windows 10

**Other information that may be helpful:**
If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
Wed Apr 04 2018 14:24:03 GMT+0200 (W. Europe Daylight Time)
console.log((new Date()).toLocaleString())
4/4/2018, 2:24:03 PM
console.log( (new Date()).getTimezoneOffset())
-120
console.log( navigator.userAgent)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
console.log(moment.version)
2.18.1
```

**Comment by marwahaha** [comment]
I feel like this should be updated in the docs. It's not clear invalid moment objects should change at all.

**Comment by sobralex000** [comment]
Can I claim this issue as my first pr?

**Comment by extra-mayo** [comment]
@marwahaha I believe that certain exceptions should be made when it comes to changing invalid moment objects, especially when it concerns method calls such as ```set()```. In this context, Feb 29th is valid every once in a blue moon.

Looking at the source code, it seems that function checks for the validity of the _original_ moment object before trying to make any changes.
```javascript
function set$1 (mom, unit, value) {
        if (mom.isValid() && !isNaN(value)) {
                  ...
        }
}
```
It'd make more sense to see if the new date is valid first rather than basing decisions on the original invalid date.

**Comment by marwahaha** [comment]
@extra-mayo fair point, but I think the intent of `Invalid date`s is that they are forever `Invalid`; any changes to an invalid date will not cause a date to regain validity.

**Comment by marwahaha** [comment]
@sobralex000 - go for it, the docs repo is https://github.com/moment/momentjs.com

**Comment by fstanis** [comment]
Just came across this issue as well.

The documentation does mention it in the [Validation](http://momentjs.com/docs/#/parsing/is-valid/) part:

> # Invalid Moments
> 
> If a moment is invalid, it behaves like a NaN in floating point operations.
> 
> All of the following produce invalid moments:
> 
> *    [...]
> *    `invalid.set(unit, value)`
> *    [...]

That said, I'd like it very much if we could change the behaviour of `set` here, since my current use-case seems impossible as it is now. Namely, I get dates in the `DD MMM` format and then later figure out the year:

```js
// inputDate == '29 Feb'
let date = moment(inputDate, 'DD MMM');
// later in the code
let formatted = date.set('year', 2016).format('YYYY-MM-DD');
// outputs 'Invalid date'
console.log(formatted);
```

The way it is now, I need to change the user input to include the year, which doesn't seem very nice.

**Comment by ashsearle** [comment]
@fstanis The current behaviour seems easy to explain (once invalid a moment stays invalid.)  I think it would be difficult to explain behaviour that tried to somehow keep track of the valid bits of an invalid moment, eventually leading to a full-blown resurrection from invalid to valid...

Comparing to prior art: the only way to restore a native instance of `Date` is to call [`setFullYear`](https://tc39.github.io/ecma262/#sec-date.prototype.setfullyear) or [`setUTCFullYear`](https://tc39.github.io/ecma262/#sec-date.prototype.setutcfullyear) - but that doesn't behave as you'd want:

```js
var d = new Date(undefined, 1, 29); // Invalid date
d.setUTCFullYear(2016);
d.toString(); // Jan 1st 2016, NOT Feb 29th...
```

In terms of UI gathering dates, none of the native HTML5 input types allow you to ask for a date without also asking for a year (i.e. the input types `month`, `week` and `date` all require you to pick a year before their `value` is set.)

What's your use-case for asking for a date where you think it's a burden to ask for a year at the same time?

**Comment by fstanis** [comment]
So, it's actually a Node.js app that's processing data previously stored in the "DD MMM" format from a set of documents. I infer the date through other means, in a second pass, using a different storage where the metadata is stored that contains the year. Essentially, it's a big mess and I'm using moment to correct the date format and have it include the year (among other things).

A niche use-case, I agree - but what bothers me is that I didn't know this would happen until "Invalid date" started popping up in my output data.

I like the NaN analogy and I can see how the current "once invalid, always invalid" is a clear-cut approach, but perhaps "DD MMM" should just be an invalid format for the `moment()` function, as it includes no year?

**Comment by fstanis** [comment]
@ashsearle I see, good point.

@linqcan Mind sharing what path you took? Right now, the change requires me to change both the input and the format, which I'm reluctant to do if there's a better way.

---

Overall, I see two separate issues here:

-    `moment('29 Feb', 'DD MMM')` is flaky in a sense - the success of that function depends on the current year, so code that relies on it will literally start working in 2020 and then stop again in 2021.
-    It's impossible to "fix" an invalid moment once it becomes invalid.

Seeing all the comments above, I think the latter is a good design decision and shouldn't be addressed, but the former is something that makes me uncomfortable, as it may introduce issues in codebases that rely on it years after being used successfully (e.g. I would never have found this out if I were using that feature in 2016).

A few proposals I have for the `moment('29 Feb', 'DD MMM')` issue:

-   Make a version of `set` (or optional parameter to it) that *can* fix an invalid moment.
-   As a smaller-scope version of the above, add optional parameter to `year()` alone that lets it fix an invalid moment, i.e. treat 29th of February as a special case of "maybe valid" that can be fixed, to avoid the complexity of tracking (in)valid bits, as @ashsearle pointed out.
-   Have `moment('29 Feb', 'DD MMM')` return a valid moment that's equal to the 28th of February unless the year is changed to a leap year. This is similar behavior as when changing the year of 29th of February to a non-leap year, e.g. `moment('29 Feb 2016', 'DD MMM YYYY').year(2017).format('YYYY-MM-DD')` outputs "2017-02-28". In other words, treat 29th of February either as 28th or 29th depending on whether the year is leap.
-   Do nothing, but have the `moment` function display a warning in this situation (taking only day and month, but not year into account when formatting).
-   Do nothing, but make this clearer in the documentation.
-   Do nothing, it's an unfortunate edge case.

Thoughts?

**Comment by ashsearle** [comment]
@fstanis Moment already has a bunch of stuff to analyse why a newly created moment is invalid.

Take read through the [validation docs](https://momentjs.com/docs/#/parsing/is-valid/) and check the result of `parsingFlags()` on an invalid moment - particularly the `overflow` flag (which can also be accessed using `invalidAt()` - although it's admittedly a little cryptic.)

Personally: I dislike the idea (and current behaviour) of Feb 29th being magically converted to Feb 28th when you change years as it doesn't change back again:

```js
moment("29 Feb 2016", "DD MMM YYYY")
  .year(2017)
  .year(2016)
  .format("YYYY-MM-DD");
// result is 2016-02-28
```

**Comment by linqcan** [comment]
@fstanis The path was that we decided against supporting February 29. Not a generic solution but will work for our purposes.

**Comment by ichernev** [comment]
@fstanis when you have a well defined, still niche use case its best to build something from scratch :)

A hack I will suggest is to prepend a leap year at the begining/end so that 29th Feb will always be valid, and then later set the year.

May I ask why do you need a moment object to keep something that is not quite a moment (date + month). If you always get the year later, just keep the 2 vars separately until you get the year, and THEN use moment to create a moment-in-time and check for validity. If you default to the current year, but still would like to handle 29th Feb, you can still make a custom check for that particular thing.

**Comment by fstanis** [comment]
@ichernev fully agree my use case is niche - I did end up doing exactly what you suggested and now I have a "proper" moment constructed, which does make a lot more sense. :)

Still, I think the issue I mentioned previously is worth fixing:

> `moment('29 Feb', 'DD MMM')` is flaky in a sense - the success of that function depends on the current year, so code that relies on it will literally start working in 2020 and then stop again in 2021.

Would be great if this was at least a warning.
