### ISSUE TITLE
Parsing primitive type undefined as true date

### ISSUE THREAD

**Issue by elipeters** [moment/moment#4535]
I'm getting the current date for undefined primitive type...
```javascript
var date = undefined;
console.log(Moment(date).isValid()); // true

date = null;
console.log(Moment(date).isValid()); // false

date = "";
console.log(Moment(date).isValid()); // false
```
Which is the same as `Moment().isValid()` - pointless but ok...

A use case is DyanmoDb not able to accept null entries...

Checking the existence of  date is required to get a good result...

```javascript
if ( object.date != undefined && Moment(object.date).isValid() ){
    // do something
}
````

**Comment by marwahaha** [comment]
In JavaScript, `moment(undefined)` is the same as `moment()`, which parses to right now: http://momentjs.com/docs/#/parsing/now/

There's not a ton we can do about this, at least in this version of moment.
