### ISSUE TITLE
toObject() and toArray() yielding incorrect Month as Integer

### ISSUE THREAD

**Issue by holmesrm23** [moment/moment#4541]
Console outputs:
Mon Apr 09 2018 16:10:02 GMT-0400 (Eastern Daylight Time)
4/9/2018, 4:10:02 PM
240
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
2.18.1

Using either method toArray() or toObject() and getting back the wrong month.

**Comment by marwahaha** [comment]
Note that months are zero-indexed, so January is month 0.

https://momentjs.com/docs/#/get-set/month/

Please re-open if you have other questions.
