### ISSUE TITLE
moment('2017-01-01', 'YYYY-MM-DD').format('YYYYWW') => '201752'. Should be last week of 2016 instead right?

### ISSUE THREAD

**Issue by ebdrup** [moment/moment#4543]
**Description of the Issue and Steps to Reproduce:**
`moment('2017-01-01', 'YYYY-MM-DD').format('YYYYWW') => '201752'`. Should be last week of 2016 instead right?

**Environment:**
Node.js v8.11.1 on OSX High Sierra v10.13.4

**Other information that may be helpful:**
TimeZone: Copenhagen

```js
console.log( (new Date()).toString())
Tue Apr 10 2018 09:49:49 GMT+0200 (CEST)

console.log((new Date()).toLocaleString())
2018-4-10 09:49:49

console.log( (new Date()).getTimezoneOffset())
-120

console.log( navigator.userAgent)
ReferenceError: navigator is not defined

console.log(moment.version)
2.22.0
```

**Comment by marwahaha** [comment]
The `YYYY` refers to the year, which is 2017.
The `WW` refers to the ISO week, which is 52.

You could use `moment('2017-01-01').isoWeekYear()` to get 2016.

Better yet:
```
moment('2017-01-01').format("GGGG-WW")
```

see http://momentjs.com/docs/#/displaying/ and https://en.wikipedia.org/wiki/ISO_week_date for more information.

If you have more questions, please re-open! :)
