### ISSUE TITLE
isSame for time not working

### ISSUE THREAD

**Issue by azrull** [moment/moment#4545]
`<p class="timeSolat"></p>
        <p class="Subuh">6:44:00</p>
        <script src="jquery-3.3.1.min.js"></script>
        <script src="moment.js"></script>
        <script type="text/javascript">
        var Subuh = moment($('.Subuh').text()).format('h:mm:ss').toString();
        var clock = moment().format('h:mm:ss').toString();
        setInterval(
            function(){
             $('.timeSolat').html(clock);
             if (clock === Subuh) {
                 alarm('Yahoo');
             }
            }
        ,1000);
        </script>`

The above code is to carry out alarm. Using isSame function not working.

**Comment by marwahaha** [comment]
Where are you running this? How are you using `moment`? I don't see any `isSame` in the snippet you provided.
