### ISSUE TITLE
Handling goduration string format using moment durations

### ISSUE THREAD

**Issue by mimen** [moment/moment#4550]
**Description of the Issue and Steps to Reproduce:**

Moment doesn't currently support the goduration string format. Lead to us having to implement a converter. For reference, the goduration strings look like: `23h40m0s550ms` etc. 

**Other information that may be helpful:**

Wrote something like this to handle our limited use case:

```
export function goDurationToMoment(goDuration) {
  let hours, minutes, seconds;

  const indexOfHours = goDuration.indexOf('h');
  const indexOfMinutes = goDuration.indexOf('m');
  const indexOfSeconds = goDuration.indexOf('s');

  if (indexOfHours !== -1) {
    hours = goDuration.substring(0, indexOfHours);
  }

  if (indexOfMinutes !== -1) {
    minutes = goDuration.substring(indexOfHours + 1, indexOfMinutes);
  }

  if (indexOfSeconds !== -1) {
    seconds = goDuration.substring(indexOfMinutes + 1, indexOfSeconds);
  }

  return moment.duration({ hours, minutes, seconds });
}

export function momentDurationToGo(momentDuration) {
  const hours = Math.floor(momentDuration.asHours());
  const minutes = momentDuration.minutes();
  const seconds = momentDuration.seconds();
  return `${hours}h${minutes}m${seconds}s`;
}
```

Obviously this doesn't handle the entire feature set of the goduration format, just what we need for our project, but it wouldn't be too hard to get it to a more complete state. It would be neat if moment handled these strings out of the box. I would be happy to work on this myself if you all thought this was a good idea.

**Comment by marwahaha** [comment]
This is an interesting idea.

How does Go interact with JS? Is it common that Go calls out to JS packages like `moment`?

**Comment by ichernev** [comment]
@mimen I'd suggest you make a function to parse/format in go durations, and distribute it as a moment plugin. I don't think we'll include such a feature in core (its just not something most people will use).

```javascript
moment.duration.fn.goDuration = function (str) {
  // do something with str
  // return moment.duration(/* ... */);
}
moment.duration.fn.goFormat = function() {
  // return /* a string repr */
}
```
