### ISSUE TITLE
moment.calendarFormat returns lastDay

### ISSUE THREAD

**Issue by dimik** [moment/moment#4552]
```javascript
moment.calendarFormat(moment(moment().format()), moment())
```

or without now argument

moment.calendarFormat(moment(moment().format()))

returns 'lastDay' but 'sameDay' is expected

**Comment by marwahaha** [comment]
This has to do with how JavaScript executes the arguments:
```
function f(a, b) { return a.valueOf() - b.valueOf(); }
f(moment(moment().format()), moment()) // will be negative, -593
f(moment(), moment()) // 0
``` 

[As stated in the docs](https://momentjs.com/docs/#/customization/calendar-format/), moment.calendarFormat's second argument should be `now`, so I think it's ok to have it be strictly later than the first argument in order for it to be the `sameDay`.

So, I will close this. Let me know what you think, and re-open if you disagree.
