### ISSUE TITLE
Need to declare word 'next' in locale.

### ISSUE THREAD

**Issue by adsingh14** [moment/moment#4568]
**Description of the Issue and Steps to Reproduce:**
Filepath: [**src/locale/pa-in.js**]

*Please include the values of all variables used.*
Need to include object's property(nextWeek) value **[next]**.
**current build:** nextWeek : 'dddd, LT', 
**requested change:** nextWeek : '[next] dddd, LT',

> I found it just because of Travis CI. So, I have to re-commit my changes in a single file.

With Best, 
Aman

**Comment by ashsearle** [comment]
Do you mean there's a Punjabi word missing in the locale file?  So, not 'next', but perhaps 'ਅਗਲਾ' ?

**Comment by adsingh14** [comment]
@ashsearle Actually the object [next] makes real sense while telling time in Punjabi.

**Comment by ashsearle** [comment]
@adsingh14 In the context of [the line you want to change](https://github.com/moment/moment/blob/develop/locale/pa-in.js#L54) - the lines above and below all use punjabi, so it seems strange to suggest putting the English word 'next' in there:

```js
        calendar : {
            sameDay : '[ਅਜ] LT',
            nextDay : '[ਕਲ] LT',
            nextWeek : '[next] dddd, LT', // <-- really?
            lastDay : '[ਕਲ] LT',
            lastWeek : '[ਪਿਛਲੇ] dddd, LT',
            sameElse : 'L'
        },
```

**Comment by ashsearle** [comment]
Hmm... now that I've just cut'n'pasted that.  Are nextDay and lastDay using the same word?  That seems a bit confusing...

**Comment by adsingh14** [comment]
I figured it according to the property 'lastWeek'.

ie: lastWeek has an object [prev/ਪਿਛਲੇ]. So why nextWeek don't have [next] ?

**Comment by adsingh14** [comment]
>Hmm... now that I've just cut'n'pasted that. Are nextDay and lastDay using the same word? That seems a bit confusing...

That's makes sense in Punjabi language. 😅

**Comment by adsingh14** [comment]
@ashsearle 
>nextWeek : '[next] dddd, LT', // <-- really?

I figured it according to the property 'lastWeek'.
ie: lastWeek has an object [prev/ਪਿਛਲੇ]. So why nextWeek don't have [next] ?

>Hmm... now that I've just cut'n'pasted that. Are nextDay and lastDay using the same word? That seems a bit confusing...

That's make sense in Punjabi language. 😅

**Comment by ashsearle** [comment]
Now I'm really confused: I don't see the word 'prev' anywhere in [`src/locale/pa-in.js`](https://github.com/moment/moment/blob/develop/src/locale/pa-in.js)

What are you referring to?

I can't read a single thing in punjabi, but checking [unicode consortium survey tool](http://st.unicode.org/cldr-apps/v#/pa/Fields/59d8178ec2fe04ae) and Google Translate, it looks like 'tomorrow' is  ਕਲ, and 'yesterday' is ਕੱਲ੍ਹ, so shouldn't it be:
```js
nextDay : '[ਕਲ] LT',
lastDay : '[ਕੱਲ੍ਹ] LT',
```

And - assuming we're just failing to communicate - putting the punjabi into nextWeek:
```js
nextWeek : '[ਅਗਲਾ] dddd, LT'
```

?

**Comment by adsingh14** [comment]
@ashsearle ਕੱਲ੍ਹ is same for next & prev day.

next is ਅਗਲਾ
prev is ਪਿਛਲਾ

This is Punjabi grammar.

**Comment by adsingh14** [comment]
@marwahaha i think you've missed that commit from my PR.

**Comment by marwahaha** [comment]
@adsingh14 - does https://github.com/moment/moment/commit/3062ca13cd1cfbcef1c4a0cd5543f5fcd329c1d9 not address the issue?
