### ISSUE TITLE
ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by Mobashir1995** [moment/moment#4572]
I've use the latest version of moment js and include the minified js at the top of my script.

Most of the time the moment timer is working fine, but sometimes it gives a error, which says, 

> "ReferenceError: moment is not defined"

I can't detect what is the problem. Because I've used the same code, but why sometimes it gives the error?

**Comment by lad475** [comment]
Perhaps your script is executing before the moment script is finished loading in?  That would account for why sometimes it works and sometimes it doesn't.

Try to move your script tags around to see if this fixes the problem.

**Comment by Mobashir1995** [comment]
Hi! Thanks for your reply. I've put the moment js code at top of the script, then write the rest of the code. So, I think there is no chance to load my script before of moment JS.

**Comment by eternalharvest** [comment]
@Mobashir1995 

As @lad475 mentiond, i think it is because ur script is executed before moment is loaded.
I think u need to wrap ur code with `window.onload` callback function.

**Comment by robhadfield** [comment]
Just putting the script before another script doesn't guarantee it will be loaded first unfortunately. As @eternalharvest says, wait until the window is loaded before using a call to moment.js

**Comment by PawanKotak** [comment]
@robhadfield I am getting the same issue. For me it is working fine on page load and not on page refresh. As you and @eternalharvest suggest I should call my moment.js after window is loaded. So I tried creating moment object in Chrome Console after everything is loaded but getting same error and verified moment.js in Source Tab of Chrome it is present over their before I am creating my moment object.

**Comment by robhadfield** [comment]
Are you using jQuery?

Try adding this code at the foot of your page:
```
$(window).load(function(){
    // Initiate moment here and console.log it
    console.log( moment() );
});
```

**Comment by PawanKotak** [comment]
@robhadfield  Thanks for response.Not jQuery I am using Angular JS but I tired window.load inside my controller but same issue

**Comment by robhadfield** [comment]
Without seeing the full site code it's tricky but if it's not available on Window load then it's not being loaded.

Is it on a live URL?

**Comment by PawanKotak** [comment]
@robhadfield Thanks. No it is not available on live URL yet
