### ISSUE TITLE
Parsing a date does not write _tzm on the moment object.

### ISSUE THREAD

**Issue by jamespedid** [moment/moment#4573]
**Description of the Issue and Steps to Reproduce:**
When parsing moment from a date object, the _tzm property is not being set. This can be set more accurately by setting the value to -date.getTimezoneOffset()

```
var date = new Date(); // in my location this is <Wed Apr 18 2018 23:17:49 GMT-0400 (EDT)>
var momentObj = moment(date);
console.log(momentObj._tzm) //undefined
```
Note: not depicted here is parsing from new Date().toString(). This also does not set the _tzm value.

Compare this to first casting it into a string and then using the moment:

```
var dateString = "2018-04-18T23:18:50.000-0400" 
var momentObj = moment(dateString);
console.log(momentObj._tzm); //-240
```

Here's a quick representation of this in jsfiddle
https://jsfiddle.net/spmyc7hp/5/

**Environment:**

Chrome, Linux Mint 18.3

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
EST GMT -0400
Ran at 11:33 PM EST (clock on computer advanced for testing)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

Wed Apr 18 2018 23:34:48 GMT-0400 (EDT)
(index):4583 4/18/2018, 11:34:48 PM
(index):4584 240
(index):4585 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
(index):4586 2.22.1

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by jamespedid** [comment]
Note that chrome and firefox (and maybe others) will return a date in a bastardized RFC2822 format that has the month and day switched. Perhaps the regexp can be adjusted to account for this?

**Comment by ashsearle** [comment]
How can you tell if it's appropriate or inappropriate to pull the timezone off a date?

What's the timezone of `new Date(1524212917295)` - how do you know if I wanted that timestamp in UTC or my local timezone?

Isn't `_tzm` an implementation detail?  Are you writing a plugin or something that relies on it?

**Comment by ichernev** [comment]
@jamespedid _tzm is not part of the moment api. Go check the docs: http://momentjs.com/docs/

Also keep in mind that moment doesn't understand timezones, it can only help to some extend with utc offsets.

Date objects in js have a "built-in" time zone which is the local timezone. So there is no way to take an offset from Date object during construction and then present it in a getter.

moment().utcOffset() might do what you want, I'm just not sure exactly what that is.
