### ISSUE TITLE
moment.weekdays() is localized, but order is not ISO

### ISSUE THREAD

**Issue by d-damien** [moment/moment#4579]
It has been localized in #3284, but the order is still not ISO. I guess since the order is localized IRL, we might as well keep `moment.weekdays()` that way, but it would be nice to have `moment.isoWeekdays()`, that would be both ISO and localized − same syntax as `moment().isoWeekday()`.

**Comment by d-damien** [comment]
I imagine we also need `moment.isoMonths()`, as I believe year does not start on January in all countries. Not sure how this goes with `moment.months()`.

**Comment by d-damien** [comment]
I should have provided a use case, you are right. My use case is that I sort data according to their weekday, in a context where (despite english conventions and language), ISO weeks are used. Like :

``` js
let weekdays = moment.weekdays()
weekdays.push(weekdays.shift())
let sortFunction = d => weekdays.indexOf(d)
```

I have to add `line 2` for going from english weeks to ISO weeks, and I feared that in case of multilingual applications, that would require a whole lot of checking for how different languages order weekdays (the kind of thing momentjs helps you to avoid).

**Comment by ashsearle** [comment]
You can remove line 2 if you make line 3 more complicated:
`let sortFunction = d => (weekdays.indexOf(d) || 7)`

**Comment by ashsearle** [comment]
A couple more thoughts: I assume there's a reason you're sorting by weekday _name_ (e.g. you don't have a date.)  If you need to handle abbreviations too, you should look at `moment.localeData().weekdaysParse(nameOfWeekday)` - as that handles the abbreviated versions too - case-insensitively: e.g. Th, Thu, Thursday.

Regarding your suggestion about `isoMonths()` - do you know of any locale with a _stable_ month ordering that doesn't start in January? (I mean: Chinese new year starts in either January or February, Islamic has started anywhere from September to December recently...)

Tax and financial years might be a good case where the months need to be ordered differently, but they don't map to a locale...

I think if you were going to add `isoWeekdays`, then you'd also have to add `isoWeekdaysShort` and `isoWeekdaysMin` for symmetry with `weekdaysShort` and `weekdaysMin`.  Similarly, you couldn't really add `isoMonths` without also adding `isoMonthsShort` for symmetry with `monthsShort`

**Comment by d-damien** [comment]
That would be a lot to add indeed. I think most of the time, people will stick to the locale's weekdays order, and not make a mess with ISO like we do (hopefully they will report it here if they don't).
