### ISSUE TITLE
Better support for +00:00 offset, apart from UTC

### ISSUE THREAD

**Issue by repl-chris** [moment/moment#4582]
It would be nice if moment could disambiguate between UTC timestamps and timestamps with +00:00 offsets.  Technically they're identical obviously, but they have a semantic difference - "this is a UTC world-time adjusted timestamp" vs "this is a local timestamp that just happens to have the same offset as UTC".  
```
moment.parseZone('2017-12-31T07:45:05Z').format();       // Good: '2017-12-31T07:45:05Z'
moment.parseZone('2017-12-31T07:45:05Z').isUtc();        // Good: true
moment.parseZone('2017-12-31T07:45:05+00:00').format();  // Current: '2017-12-31T07:45:05Z', Desired: '2017-12-31T07:45:05+00:00'
moment.parseZone('2017-12-31T07:45:05+00:00').isUtc();   // Current: true, Desired: false
```

I understand the reasoning behind the existing functionality, but it is unfortunate to lose the local vs utc info in this situation.  Could it make sense to provide a parameter to parseZone to optionally treat +00:00 as an offset-based moment? Or even have a way to set the resultant moment to non-UTC afterwards?

**Comment by ashsearle** [comment]
What benefit does this 'better support' give?

I'm struggling to see a benefit to knowing something is in 'local time' without also knowing a location.  Without location you can't do date arithmetic with DST changes, so... what's the point of being able to distinguish between `+00:00` and `Z`?

**Comment by ichernev** [comment]
Some applications slap +00:00 when they mean UTC, go figure. If I were you I'd just use moment-timezone (if that worked), or manually detect +00:00 in the date string and do something accordingly.

moment, without timezone, does not understand zones/offsets. It just has offsets. So utc in moment ligo is exactly equivalent to offset +00:00. Moment is unlikely to change in that regard, but moment-timezone is designed around that, so it could be the solution for you.
