### ISSUE TITLE
Facing issues while using duration and diff methods

### ISSUE THREAD

**Issue by GopiKrishna87** [moment/moment#4584]
Dear Respectives,

I am new to using moment js, I have a requirement where the user gives input in terms of days or months or years, and I have to convert them into years, months and days.
Example:
Case -1 : User inputs 1 month, and I have to calculate and show him as 0 Years 1 month 0 days, but I seeing different result with below code
OR
Case - 2: User input 30days and expects to convert it to 1 month because he is in the month of 30 days but I see 30 days as out put

Sample for Case -1
```
m1 = moment();
m2 = moment(m1);
m2.add(0, 'years').add(1, 'months').add(0, 'days');
duration = moment.duration(m2.diff(m1));
console.log(duration.years() + ', ' + duration.months() + ', '+ duration.days());
```
**Result -** _0, 0, 30_

Sample for Case - 2
```
m1 = moment();
m2 = moment(m1);
m2.add(0, 'years').add(0, 'months').add(30, 'days');
duration = moment.duration(m2.diff(m1));
console.log(duration.years() + ', ' + duration.months() + ', '+ duration.days());
```
**Result -** _0, 0, 30_

This I am trying in my local, even I tried executing this snippet in console of momentJs web page(where I have moment reference).

Also another case:
1. If I give 365 days it is converting to 11 months 30 days, if I give 366 days it converts to 1 year, if I give 731 days it is converting to 2 years, if I give 732 days it is converting to 2 years 1 day, with these results if I give 1 year 365 days and expects 2 years as output it is giving 1 year 11 months 29/30 days.
```
m1 = moment();
m2 = moment(m1);
m2.add(1, 'years').add(0, 'months').add(365, 'days');
duration = moment.duration(m2.diff(m1));
console.log(duration.years() + ', ' + duration.months() + ', '+ duration.days());
```
**Result -** _1, 11, 29_

Help me, whether my understanding is not correct about moment js OR something am I missing.

I am working on firefox 59.0.2, windows 10.

**Environment info**

_Mon Apr 23 2018 15:54:57 GMT+0530 (India Standard Time) debugger eval code:1:1
4/23/2018, 3:54:57 PM debugger eval code:2:1
-330 debugger eval code:3:1
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0 debugger eval code:4:1
2.22.1_

Thanks
Gopi Krishna.

**Comment by GopiKrishna87** [comment]
Thank you for your explanation but what could be the reason for below case

```
var drn = moment.duration({years: 0, months: 0, days: 365});
console.log(drn.years() + ', ' + drn.months() + ', '+ drn.days());

```
**Result-**  _0, 11, 30_

The current year is not a leap year, my expectation is 1 year, why I am not getting that result? am I missing something again?

**Comment by ashsearle** [comment]
Duration's aren't tied to a specific point in time.

Downside is that the conversion from days to months & years may not match what you expect.
Upside is that the conversion is stable.

```js
moment.duration({ days: 365 }).asDays(); // 365
moment.duration({ days: 365 }).asMonths(); // 11.992032690609664
moment.duration({ days: 365 }).asYears(); // 0.9993360575508053
```

**Comment by GopiKrishna87** [comment]
Thank you Ash for your time and suggestion.

**Comment by icambron** [comment]
Luxon durations can do this. I suggest looking there.
