### ISSUE TITLE
Reference error: moment.localeData broken for Spanish (es) locale when trying to serialize

### ISSUE THREAD

**Issue by suprMax** [moment/moment#4585]
There is a small issue with `es` locale.

We use `moment.localeData(LOCALENAME)._config` to package all locale data for FE application (only one locale is loaded at a time) and it currently produces a reference error for `monthsShortDot` variable. Since the function `monthsShort` references a variable from upper scope it's not available after de-serialization.

In all other locales we used so far variables were encapsulated to be part of this `_config`. I understand this is somewhat undocumented use case, but I see no other way to bundle locale data. Could you perhaps fix this (or allow a PR)?

This is the problem specifically: https://github.com/moment/moment/blob/develop/src/locale/es.js#L7

It would be cool to simply move it down to line 16 and define inside the function. That should solve my problem. Relevant PR: https://github.com/moment/moment/pull/4588

**Comment by ashsearle** [comment]
You say you're trying to _bundle_ locales, but only load one at a time.

Did you read through the documentation about how to load locales on demand - e.g. [using RequireJS](https://momentjs.com/docs/#/use-it/require-js/) (which further refers to [this comment](https://github.com/requirejs/requirejs/issues/1554#issuecomment-226269905)).
```js
// async load locale
define(['require', 'moment'], function(require, moment) {
  // Inside some module after the locale is detected. This is the
  // case where the locale is not known before module load time.
  require(['moment/locale/de'], function(localeModule) {
    // here the locale is loaded, but not yet in use
    console.log(moment().format('LLLL'));  // 'Friday, June 24, 2016 1:42 AM'

    moment.locale('de');
    // Use moment now that the locale has been properly set.
    console.log(moment().format('LLLL')); // 'Freitag, 24. Juni 2016 01:42'
  })
});
```

**Comment by ashsearle** [comment]
I'm a little confused about the issue you're having.

You're quite right that `require('moment/locale/de')` returns something that looks like an empty object.  That's the set of exports from the locale file when loaded as a module... i.e. it doesn't export anything.

The locale file does all its work by hooking into the global `moment`, so... requiring a locale works fine, you just need to switch to it afterwards with (e.g.) `moment.locale('de')`

**Comment by suprMax** [comment]
We generate our code bundle with browserify on the server and don't load anything on demand via runtime as with RequireJS.

I'm bundling all language data (mostly JSON, using https://github.com/yahoo/serialize-javascript package) separately from my main script file so it doesn't bloat with unused translations. Since we only use 1 locale at a time, say 'de', there is no point in loading everything else ('fr', 'it', 'es', ...).  This way I have all locale data stored in separate files: `locale-de.js`, `locale-fr.js`, ... that can be loaded depending on the language used.

The code that uses moment library and the locale that moment library uses live in separate files with separate scopes.

**Comment by ashsearle** [comment]
Does the that extended JSON format allows IIFE's?  Can you just wrap up the locale?

```js
var fs = require('fs');
var es = `{
  "moment-locale": (function() {
    ${fs.readFileSync('./node_modules/moment/locale/es.js').toString()}
  })(),
  "other-locale-stuff": {
    ...
  }
}
`;
console.log(es);
```

**Comment by suprMax** [comment]
It would surely serialize the function, but I don't have `moment` globally (it's packaged inside main code bundle all wrapped in IIFE too).

In other words it would include the code but do nothing. Following this approach I could go straight after the source:

**Comment by ashsearle** [comment]
Other locales suffer the same issue too: 'ar-ly', 'ar-sa', 'ar', 'az', 'be', 'bn', 'bo', 'br', 'cs', 'es-do', ...

If I was a maintainer (I'm not), I wouldn't merge the PR for the reason it doesn't fix the general issue and doesn't move the locales or localeData any closer to being able to import/export as pure JSON.

**Comment by suprMax** [comment]
I think it doesn’t have to be JSON, just a self encapsulated object would be enough. I would update all locales if maintainers agree to merge such an undertaking.
