### ISSUE TITLE
Only last imported moment/locale/xx take effect

### ISSUE THREAD

**Issue by wanghz2** [moment/moment#4587]
reproduce this issue on react-native with moment@2.21.0.

import es from 'moment/locale/es';
import fr from 'moment/locale/fr';

moment.locale('es');
console.log(moment.locale());

expect above code return es, but always fr, so moment(time).format(format) is in fr always, no matter how many locale package loaded & which one switched by moment.locale, always the last imported one does take effect.

This even affect moment(time) without .format, so if i want to self convert some languages, only use moment.locale convert one locale, this imported locale will converted all other langs unexpectedly. 

I hope this is fixed, or workaround can be provided as solution for multi-locales supporting App.

**Comment by ashsearle** [comment]
Looks fine:
```js
import moment from 'moment';
import es from 'moment/locale/es';
import fr from 'moment/locale/fr';

moment.locale('es');

console.log(moment.version, moment.locale());
// Outputs: 2.22.1 es
```

**Comment by LitileXueZha** [comment]
`moment/locale/language.js` will set language automatically
