### ISSUE TITLE
[Feature request] Support Era names

### ISSUE THREAD

**Issue by eternalharvest** [moment/moment#4591]
### Description
In Japan, government agency and some company use traditional Japanese Imperial Calendar. But it seems moment.js is currently not supporting era names ~~~other than Christian Era~~~. So I want to write some patch to improve this. But I'm not familiar with this code-base. And I'm not sure whether if this can be done with unicode date format standard.

This feature is implemented as `Era` in Single Unix Specification (SU).
Please refer to the following link.
http://man7.org/linux/man-pages/man3/strftime.3.html

And java has same feature implemented in `java.util.JapaneseImperialCalendar` class though i don't like this implementation.

Regards.

**Other information that may be helpful:**
* http://www.i18nguy.com/l10n/emperor-date.html

### Related Issue
* #3553 How to convert Gregorian year to the Japanese calendar year ?

**Comment by eternalharvest** [comment]
It seems Era names is not supported yet...

In LDML, 'GGGG' means Era name, but moment uses 'GGGG' format as 'ISO 4 digit week year'.
Should I define another symbol for implementing Era name support?

### Related Issue
* #61 Custom, LDML-like pattern language which is not LDML
* #294 Switch to LDML?

**Comment by icambron** [comment]
Yeah, you'd need a new token. Probably anything unused is fine. Remember we can't do this unless we get eras for all the locales, so this is a big feature.

**Comment by eternalharvest** [comment]
@icambron 

Thank u for ur advice!
I'll try this.

**Comment by eternalharvest** [comment]
@mj1856 As u mentioned, Japanese era name is planning to be changing on May 1, 2019.
As the link told me explains, Microsoft has added a registry so that it can respond instantly to updating the era.

On Linux, default definition of Japanese era is stored in `/usr/share/i18n/locales/ja_JP`.
And u can modify the original locale file or define custom locale using `localedef` command.

In my implementation in PR #4591, era name definitions are defined in the locale.
So, I think we can use `Locale#updateLocale()` directly or use `Locale#defineLocale()` to define new custom locale to respond to new updating the era.

Microsoft implementation can respond to new era with a single registry entry.
In contrast, in my implementation we must redefine the whole era entries to respond to new era.
But I think Microsoft implementation is too specialized into Japanese.

**Comment by eternalharvest** [comment]
@icambron, @mj1856 

Although I know u are busy, but I would appreciate reviewing my PR!
And please tell me if I need update my PR.

Thanks u, and beast regards.

**Comment by ichernev** [comment]
Close in favor of #4599

**Comment by robhatfield** [comment]
Why was this issue closed when the pull request has not been merged?  Do you plan to merge in Japan imperial era support or not?
