### ISSUE TITLE
Date.now() in MongoDB only shows first collection accurate, all after that is the same as first

### ISSUE THREAD

**Issue by shone83** [moment/moment#4592]
Date.now() in MongoDB only shows first collection accurate, all after that is the same as first. That problem is until I reset the server with nodemon, only then in next collection date is ok, but the problem is still exist until next restart.

helper:
```
generateDate: function(date, format) {
   return moment(date).format(format);
}
```

model:
```
date: {
    type: Date,
    default: Date.now()
}
```

view:
```
generateDate date 'HH:mm:ss'
```

I only notices this because I entered minutes and seconds and see that is not changing.

**Comment by icambron** [comment]
I don't think we can help with this. We can only help with things like "when I call Moment arguments x, I get a result like y when I expected a result like z". Try StackOverflow?

**Comment by shone83** [comment]
Ok, I will try in some other place.
