### ISSUE TITLE
Modifying existing JS Date with startOf / endOf has no effect

### ISSUE THREAD

**Issue by rkischuk** [moment/moment#4593]
Constructing a new moment from a JS date, and then calling startOf or endOf does not modify the moment

Example:
```js
new Date()
Thu Apr 26 2018 08:50:15 GMT-0400 (EDT)
moment(new Date()).startOf('month')
Moment {_isAMomentObject: true, _i: Thu Apr 26 2018 08:50:19 GMT-0400 (EDT), _isUTC: false, _pf: {…}, _locale: Locale, …}
moment((new Date()).toISOString()).startOf('month')
Moment {_isAMomentObject: true, _i: "2018-04-26T12:58:09.153Z", _f: "YYYY-MM-DDTHH:mm:ss.SSSSZ", _tzm: 0, _isUTC: false, …}
moment.version
"2.22.1"
```
(Expected behavior is that the moment would be modified to and return April 1)

**Environment:**
Running Chrome 65.0.3325.181 (Official Build) (64-bit)on Mac OS X Sierra

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)
This is a Rails & Angular app

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
VM23142:1 Thu Apr 26 2018 09:00:07 GMT-0400 (EDT)
VM23142:2 4/26/2018, 9:00:07 AM
VM23142:3 240
VM23142:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
VM23142:5 2.22.1
undefined
```

**Comment by ashsearle** [comment]
You're looking at implementation details.  `_i` is the _input_ to moment.

The internal field that gets updated by startOf/endOf etc is `_d`, but - to repeat myself - that's implementation detail.

You want to see if moment has changed: use `format`, `toString` or `toISOString`.

e.g. (bearing in mind I'm in a +01:00 timezone):
```js
moment(new Date()).startOf('month').toString()
"Sun Apr 01 2018 00:00:00 GMT+0100"
moment(new Date()).startOf('month').format()
"2018-04-01T00:00:00+01:00"
moment(new Date()).startOf('month').toISOString()
"2018-03-31T23:00:00.000Z"
```

**Comment by icambron** [comment]
What Ash said
