### ISSUE TITLE
Deprecation warning converting Sharepoint Date

### ISSUE THREAD

**Issue by EricCavalher** [moment/moment#4594]
I'm receiving a warning message during formating date with moment.js.

customerData[0].Year = moment(customerData[0].Date, "ddd MMM DD YYYY HH:mm:ss", 'br', true).format('YYYY');

Is there something wrong?

**Comment by icambron** [comment]
Put yourself in our shoes: What's the warning? What's the date value you passed in?

**Comment by EricCavalher** [comment]
My bad... I thought I posted the fiddle.

https://fiddle.jshell.net/a6m1df4j/5/

**Comment by icambron** [comment]
That's coming from calls like this:

```js
moment(customerSortedData[i].Date)
```

where you're not passing in a format string. See more [here](http://momentjs.com/guides/#/warnings/js-date/)
