### ISSUE TITLE
inconsistency of .format() 

### ISSUE THREAD

**Issue by ChetanAgarwal11** [moment/moment#4598]
moment("2010/2/31").format()  //"2010-03-03T00:00:00+05:30"

From the above statement i would expect the output should be "2010-02-31T00:00:00+5:30" but it is outputting "2010-03-03T00:00:00+05:30" 
Is it the effect of leap year functionality,since there is no 31st day in february is it giving me 3 days ahead output?

**Comment by eternalharvest** [comment]
@ChetanAgarwal11 

Why u need to specify the date not exist?
I think it is not a bug of moment, and this behavior is comes from `Date` class of JavaScript.

```javascript
> new Date('2010/2/31')
2010-03-02T15:00:00.000Z
```

If u want to know the date of end of month, u can use following code instead.

```javascript
> moment('2019/2/1').endOf('month')
moment("2019-02-28T23:59:59.999")
```

**Comment by lad475** [comment]
Also keep in mind, similar to what @eternalharvest said, when you format a string going into a date like "2010/2/31" moment falls back to using the native Date constructor.  If you want it to give you an invalid date for that day, pass it in ISO format:

moment('2010-02-31')

**Comment by ichernev** [comment]
Thank you @lad475 and @eternalharvest
