### ISSUE TITLE
[locale] fr: Short month parsing dot notation should be optional

### ISSUE THREAD

**Issue by siboulet** [moment/moment#4600]
I think this issue is similar to https://github.com/moment/moment/issues/3214.

Moment seems to only accept "dot notation" for short month in French parsing. The dot should be made optional.

This doesn't work: 
```
moment('12juil2016', 'DDMMMYYYY', 'fr').toDate();
Tue Jan 12 2016 00:00:00 GMT-0500 (EST)
```

But this works:
```
moment('12juil.2016', 'DDMMMYYYY', 'fr').toDate();
Tue Jul 12 2016 00:00:00 GMT-0400 (EDT)
```
Using latest version 2.22.1.

**Comment by marwahaha** [comment]
@jfroffice ?

**Comment by ichernev** [comment]
@siboulet can you provide some proof about optional dot.

I'm not sure we could even fix that. We could provide a parsing regex, but it will never pass strict parsing.

**Comment by jfroffice** [comment]
@marwahaha  @siboulet 

I did know you can omit de `.` in the parsing.
