### ISSUE TITLE
isValid function does not carry down format arg to monthsShort function

### ISSUE THREAD

**Issue by lizzieleeservicenow** [moment/moment#4606]
**Description of the Issue and Steps to Reproduce:**

For locale (ex: nl, es) that has monthsShort function with monthsShort and monthsShortDot,
when calling moment(value, format, true).isValid(), the format arg does not pass down to monthsShort function correctly, result in validation fails.

Looks like in computeMonthsParse() function, when calling monthsShort function format arg is missing.

*Please include the values of all variables used.*
When format is "DD-MMM-YY", when set() is called, it passes in format arg, so monthsShort returns monthsShort, but when calling moment(value, format, true).isValid(), the format arg does not pass down to monthsShort function correctly, it returns monthsShortDot

**Comment by ichernev** [comment]
@lizzieleeservicenow `moment(value, format, true)` by default uses the english locale. If you want to use the correct locale you can pass a locale as a third argument:

```javascript
moment('01-JAN-05', 'DD-MMM-YY', 'nl')
```

Next time it will really help if you include an actual sample code with your bug description :)
