### ISSUE TITLE
[locale] fo: relativeTime is incorrect

### ISSUE THREAD

**Issue by Sakarisson** [moment/moment#4609]
**Description of bug**
The "one minute" and "one month" values in the Faroese locale are wrong.

In both cases, the word should be in singular indefinite nominative form. 

At the moment, the value for minute is in accusative form (minutt) and month is in dative form (mánaði).

A free Faroese dictionary can be found here: [Sprotin.fo](https://sprotin.fo/dictionaries?_SearchFor=&_SearchInflections=1&_SearchDescriptions=0&_DictionaryPage=1&_DictionaryId=1&_Group=)

In [/locale/fo.js](https://github.com/moment/moment/blob/3062ca13cd1cfbcef1c4a0cd5543f5fcd329c1d9/locale/fo.js#L33), the relativeTime object should be changed as follows:

```js
relativeTime: {
  m : 'ein minuttur',
  M : 'ein mánaður',
}
```

**Steps to reproduce bug:**
Create moment instance with the locale 'fo' and call fromNow() when the time difference is either one minute or one month.

**Comment by ichernev** [comment]
@ragnar123 what do you think?
@Sakarisson can you make a PR in the mean time?

**Comment by Sakarisson** [comment]
@ichernev I can create a PR. I'll tag you in it if it's okay. Probably won't be until next week
