### ISSUE TITLE
[locale] ms: Time format and abbreviations are incorrect that will lead to confusion

### ISSUE THREAD

**Issue by sabnasusan** [moment/moment#4618]
**Description of the Issue and Steps to Reproduce:**

Time format and abbreviation currently showing is incorrect for hh\:mm A for MS_MY Locale:

**- Time format and abbreviation should be as below for "hh\:mm A":**
(Morning) Pagi: 1:00 AM - 11:59 AM
(Afternoon) Tengah hari: 12:00 PM - 1:59 PM
(Evening) Petang: 2:00 PM - 6:59 PM
(Night) Malam: 7:00 PM -11:59 PM
(Midnight) Tengah malam: 12:00 AM - 12:59 AM

**- In the format LT, the 24 hours clock is displayed, which also lead to confusion as in Malay as there it is 12 hour format.**
For example, 8 o'clock in the morning would be 8 AM for Malay and 12 o'clock in the afternoon would be 12 PM. It would cause confusion if we do change it to 24hr format since we do not really use 24hr in Malaysia.

Expected: 
**Correct abbreviations for 12 hour format in hh\:mm A format.
The clock displayed on LT format should be in 12 hour format.**

*Please include the values of all variables used.*

hh\:mm A
LT

**Environment:**
Applicable to all

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.* 

- MacOS, Safari and chrome

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on - IST
* The time and date at which the code was run - IST
* Other libraries in use (TypeScript, Immutable.js, etc) -Not Applicable

If you are reporting an issue, please run the following code in the environment you are using and include the output:

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by ichernev** [comment]
@sabnasusan can you please provide some supporting evidence (why do you think this is correct, and not the way it is now)

@weldan what do you think?

**Comment by marwahaha** [comment]
repeating above comment:

@sabnasusan can you please provide some supporting evidence (why do you think this is correct, and not the way it is now)

@weldan what do you think?

If there are no updates, I will close the issue.
