### ISSUE TITLE
Error in locale language "it"

### ISSUE THREAD

**Issue by tanganellilore** [moment/moment#4621]
**Description of the Issue and Steps to Reproduce:**
Hi all,

in the file moment/locale/it.js there are some error in the months and days.
All information are lowercase, but in Italian all information is Sentence case

for example at line 12 :

`months : 'gennaio_febbraio_marzo_aprile_maggio_giugno_luglio_agosto_settembre_ottobre_novembre_dicembre'.split('_'),
        monthsShort : 'gen_feb_mar_apr_mag_giu_lug_ago_set_ott_nov_dic'.split('_'),
        weekdays : 'domenica_lunedì_martedì_mercoledì_giovedì_venerdì_sabato'.split('_'),
        weekdaysShort : 'dom_lun_mar_mer_gio_ven_sab'.split('_'),
        weekdaysMin : 'do_lu_ma_me_gi_ve_sa'.split('_'),`

become 

`months : 'Gennaio_Febbraio_Marzo_Aprile_Maggio_Giugno_Luglio_Agosto_Settembre_Ottobre_Novembre_Dicembre'.split('_'),
        monthsShort : 'Gen_Feb_Mar_Apr_Mag_Giu_Lug_Ago_Set_Ott_Nov_Dic'.split('_'),
        weekdays : 'Domenica_Lunedì_Martedì_Mercoledì_Miovedì_Venerdì_Sabato'.split('_'),
        weekdaysShort : 'Dom_Lun_Mar_Mer_Gio_Ven_Sab'.split('_'),
        weekdaysMin : 'Do_Lu_Ma_Me_Gi_Ve_Aa'.split('_'),`

I'm use the moment-with-locale.js v 2.22.1

Thanks a lot
Lorenzo

**Comment by ashsearle** [comment]
The locale deliberately uses lowercase, as explained in [a commit from last year](https://github.com/moment/moment/commit/0b1e5c6da6a306c81f0457f858fee4bbbe8feec7) - (the same sort of change was also made for the `es` (Spanish) locale a year earlier.)

As well as the reference in the commit, I notice the unicode consortium's survey tool shows lowercase as the winning [responses for the Italian locale](http://st.unicode.org/cldr-apps/v#/it/Gregorian/)

**Comment by tanganellilore** [comment]
Ok,

I'm Italian but in the normal case (when We talk, write an email etc..) , the days, weeks and months are sentence case.

I close the issue because the correct rule is lowercase (Treccani).

Thanks @ashsearle
