### ISSUE TITLE
moment.isValid() returns true for 1111111111

### ISSUE THREAD

**Issue by ikos23** [moment/moment#4629]
isValid() method seems to have some bug.

**Steps to reproduce are very easy:**
```
var weirdDate = "1111111111";
var momentDate = moment(weirdDate , "MM/DD/YYYY");

// isValid() returns true in this case
console.log(momentDate.isValid());  // TRUE !
```

why ??? only for this value

**Environment:**
Google Chrome Version 64.0.3282.186 (Official Build) (32-bit) on Windows 7

**UPDATE**
The general pattern to reproduce: any string that represents valid values for MM, DD, YYYY but does not match the format (check my comment)

**Comment by ikos23** [comment]
Another input that gives me the same result is **1225121212**.
My assumption is that the bug is somewhere in `configFromStringAndFormat` as it just checks the input string and if parts of that string are valid date fields it treats it as a valid date.

e.g. 1225121212 - 12 (first 2 chars) is a valid month value, as well as 25 (next 2 chars) is a valid value for day of month and so on.

**Comment by eternalharvest** [comment]
@ikos23 

I think this behavior is not a bug.
If u want to check if specified text is valid date text representation, I recomend u to use strict mode.
See below.

```javascript
var weirdDate = "1111111111";

// pass true for 3rd argument so that parse date in strict mode
var momentDate = moment(weirdDate , "MM/DD/YYYY", true);

console.log(momentDate.isValid());  // FALSE
```

FYI) http://momentjs.com/guides/#/parsing/strict-mode/
