### ISSUE TITLE
Five minutes are being added to my time.

### ISSUE THREAD

**Issue by Foxhound013** [moment/moment#4632]
**Description of the Issue and Steps to Reproduce:**
I'm having trouble converting unix time into a human readable time. Perhaps I'm just misunderstanding how it's supposed to work. I have a unix time coming from the client side to my server and I've verified the date with epochconverter.com. When I use the built in moment.unix function it insists on adding five minutes to it when I use moment.unix(date/1000).utc().format('YYYY-MM-DD HH:MM:SS');

For example, If I use 1525147200000 (unix time), the value I would expect is 2018-05-01 04:00:00, but instead I get 2018-05-01 04:05:00.

*Please include the values of all variables used.*
My first variable comes from the client side and is set by node.js
`req.query.startDate = 1525147200000;
var startDate = moment.unix(req.query.startDate/1000).utc().format('YYYY-MM-DD HH:MM:SS')
console.log(startDate);`

I've included a fiddle showing the issue I'm having.
[https://jsfiddle.net/c99x9rvj/](url)

**Environment:**

Windows 7, VS code, Node V8.11.1, npm V5.6.0, moment V2.22.1, Chrome V66.0.3359.181

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on is EST
* Other libraries in use, express and mssql

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
```
Thu May 17 2018 08:47:16 GMT-0400 (Eastern Daylight Time)
2018-5-17 08:47:16
240

Any help is greatly appreciated.

**Comment by eternalharvest** [comment]
@Foxhound013

It seems a error in the format u specified...
U can get correct result by the following code.

```javascript
moment.unix(1525147200).utc().format('YYYY-MM-DD HH:mm:ss')
```

FYI) https://momentjs.com/docs/#/parsing/string-format/

**Comment by Foxhound013** [comment]
@eternalharvest Thank you for that, you're correct. Looks like it was a really silly error in the end, thank you for clearing that up!
