### ISSUE TITLE
locale not work

### ISSUE THREAD

**Issue by VesperHan** [moment/moment#4633]
version: 2.19.3
project: react-native 0.44.0

operation:
-1
import moment from "moment";
-2
moment.locale('zh-cn');
-3
console.log(moment(1316116057189).fromNow());
-4
7 years ago

why the locale not work,  i want help me fix it. Thanks..

**Comment by QuietHeartThinkingFar** [comment]
import moment from 'moment';
import 'moment/locale/zh-cn';
console.log(moment(1316116057189).fromNow());

**Comment by hotdogc1017** [comment]
`import moment from "moment";
import "moment/locale/zh-cn";

moment.locale("zh-cn");
console.log(moment(1316116057189).fromNow());`
This prints out 12 years ago instead of Chinese: 12年以前. I spent a lot of time looking for solutions but to no avail. The moment version I am using is 2.30.1
