### ISSUE TITLE
Doco for utcOffset() is confusing

### ISSUE THREAD

**Issue by peternann** [moment/moment#4635]
To a new user, at least.

I thought a construct like `moment().utcOffset(+10);` set the UTC offset GLOBALLY.
Every single example of utcOffset(<something>) in the doco shows the value of utcOffset() never being used, thus it's very easy to assume it has no useful return value.

But I presume the intention is to use it like, for example, `moment().utcOffset(+10).format('some format')`

Anyway, it confused me. Might confuse others.

I humbly suggest maybe one example, where the 'set' functionality is introduced, showing an example like above.

Cheers.

**Comment by arunikayadav42** [comment]
Can I begin contributing to this project please ?would love to do it :)

**Comment by ichernev** [comment]
@arunikayadav42 have a look at https://github.com/moment/momentjs.com and submit a PR there.

@peternann setting a utcOffset globally doesn't really make a lot of sense. But if you use [moment-timezone](https://github.com/moment/moment-timezone) you could!

**Comment by peternann** [comment]
@ichernev - I understand that: "By default, moment parses and displays in local time."

I guess changing 'localtime' globally for moment **_is_** silly - Who knows what code hiding deep in npm deps could be affected by that...

So what is the normal pattern we should use if we have time data stored as UTC, and we want to display it as different localtime outputs, for different users?

Is it correct to: Start with `mm = moment.utc(myUtcDateData)` and then use `mm.utcOffset(userOffset).format()` for every such display case?
I'm just wondering if that is the typical pattern.

As detailed as the doco is, I find it hard to glean real, typical usage scenarios - The examples are quite terse - Often they show how to call the API, but often it's not clear why you need to, or what the outcome is...

**Comment by marwahaha** [comment]
documented in https://github.com/moment/momentjs.com/pull/532 . If you'd like to add more to the documentation, please make a Pull Request against   https://github.com/moment/momentjs.com !
