### ISSUE TITLE
Moment._isValid = false

### ISSUE THREAD

**Issue by arvin9527** [moment/moment#4643]
<el-date-picker
            size="mini"
            v-model="nowadays"
            type="date"
            @change="loadData(dateConvertFn(nowadays))"
            @blur="nowSelecetDayFn(nowadays)"
            placeholder="选择日期">
          </el-date-picker>

nowSelecetDayFn(nowadays){
        let selected,before;
        **selected = moment(nowadays.split('-'))**
        **//console.log( moment(nowadays.split('-'))._isValid) // false**
        before = moment(moment().format("YYYY-MM-DD").split('-'))
        console.log('selected',selected)
        console.log('before',before)
        this.calendarCont = -(selected.diff( before , 'days' ));
        **//this.calendarCont = NaN**
        console.log('this.calendarCont',this.calendarCont)
      },

**Comment by arvin9527** [comment]
selected Moment {_isAMomentObject: true, _i: Array(3), _isUTC: false, _pf: {…}, _locale: Locale, …}_d: Invalid Date {}_i: (3) ["2018", "05", "31"]_isAMomentObject: true_isUTC: false_isValid: false_locale: Locale {_calendar: {…}, _longDateFormat: {…}, _invalidDate: "Invalid date", ordinal: ƒ, _dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/, …}_pf: {empty: false, unusedTokens: Array(0), unusedInput: Array(0), overflow: 2, charsLeftOver: 0, …}__proto__: Object
app.js:31540 before Moment {_isAMomentObject: true, _i: Array(3), _isUTC: false, _pf: {…}, _locale: Locale, …}_d: Fri Jun 29 2018 00:00:00 GMT+0800 (中国标准时间) {}_i: (3) ["2018", "05", "29"]_isAMomentObject: true_isUTC: false_isValid: true_locale: Locale {_calendar: {…}, _longDateFormat: {…}, _invalidDate: "Invalid date", ordinal: ƒ, _dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/, …}_pf: {empty: false, unusedTokens: Array(0), unusedInput: Array(0), overflow: -1, charsLeftOver: 0, …}__proto__: Object
app.js:31543 this.calendarCont NaN

**Comment by arvin9527** [comment]
<el-button size="mini" @click.stop="nowSelecetDayFn">测试</el-button>

nowSelecetDayFn(){
        var a = moment([2018, 5, 29]);
        var b = moment([2018, 5, 31]);
        var c = a.diff(b, 'days') // 1
        console.log('c',c) //NaN
      }

**Comment by arvin9527** [comment]
**

> problem solved

**



var a = moment('2018-5-29');
        var b = moment('2018-5-31');
        console.log('b',b)
        var c = b.diff(a, 'days') 
        console.log('c',c) //2

**Comment by marwahaha** [comment]
Glad you could solve the problem.
