### ISSUE TITLE
Adding 30 minutes to 10:30am causes date to go back to 10am

### ISSUE THREAD

**Issue by jamesalexmorgan** [moment/moment#4644]
**Description of the Issue and Steps to Reproduce:**

When adding minutes to a moment date, there seems to be an issue when it gets to 10:00..10:30, it duplicates those times.

All you have to do is run this following JS in the console...

const date = moment('1970-01-01 09:00:00');
console.log(date.add(30, 'minutes').format('hh:mma')); // 09:30am
console.log(date.add(30, 'minutes').format('hh:mma')); // 10:00am
console.log(date.add(30, 'minutes').format('hh:mma')); // 10:30am
console.log(date.add(30, 'minutes').format('hh:mma')); // 10:00am ISSUE HERE
console.log(date.add(30, 'minutes').format('hh:mma')); // 10:30am ISSUE HERE
console.log(date.add(30, 'minutes').format('hh:mma')); // 11:00am

**Environment:**
Chrome 66.0.3359.181 on Mac OS 10.12.6

* The time zone setting of the machine the code is running on
Australia, Sydney

* The time and date at which the code was run
8:30am on 30th May 2018

Many thanks awesome moment team! Have always loved this library! 😄

**Comment by marwahaha** [comment]
Hi! Thanks for filing this issue! Unfortunately, I can't reproduce this. Could you provide any other information?

**Comment by jleedev** [comment]
This appears to only happen for timestamps before 0 when the environment is Australia/Sydney and `moment.tz` is not called specifically.

Compare:

```javascript
$ node -e 'moment=require("moment-timezone");moment.tz.setDefault("Australia/Sydney");[-1,0].forEach(t=>console.log(moment(t).toString()))' 
Thu Jan 01 1970 09:59:59 GMT+1000
Thu Jan 01 1970 10:00:00 GMT+1000

$ TZ=Australia/Sydney node -e 'moment=require("moment-timezone");[-1,0].forEach(t=>console.log(moment(t).toString()))' 
Thu Jan 01 1970 10:59:59 GMT+1100
Thu Jan 01 1970 10:00:00 GMT+1000
```

**Comment by ichernev** [comment]
@jamesalexmorgan it looks like a classical DST "feature". I hope @jleedev clarified that!
