### ISSUE TITLE
Using format with small letter d doesn't display the correct day

### ISSUE THREAD

**Issue by DennisNerush** [moment/moment#4645]
**Description of the Issue and Steps to Reproduce:**
Using "_format_" with the small letter 'd' instead of capital 'D' doesn't present the right day of the date. In my opinion it should have the same result
`
moment('2018-06-20').format("MMM d, YYYY")
--> "June 3, 2018"
moment('2018-06-20').format("MMM D, YYYY")
--> "June 20, 2018"
`

**Environment:**
Chrome Version 66.0.3359.181 on OSX 

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)


Thu May 31 2018 14:52:37 GMT+0300 (IDT)
5/31/2018, 2:52:37 PM
 -180
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
2.15.0
```

**Comment by ashsearle** [comment]
Lowercase `d` is used for day-of-week (0..6).

See [format docs](https://momentjs.com/docs/#/displaying/format/)

**Comment by ichernev** [comment]
@ashsearle is correct: `d` is day of week, `D` is day of month.
