### ISSUE TITLE
Incorect time zone for Sofia

### ISSUE THREAD

**Issue by minchopm** [moment/moment#4647]
moment.tz(moment.tz.guess()).utcOffset() is returning 180 for Europe/Sofia -> we are always +2. There are some countries in our area like Belarus that are +3 during the summer and + 2 winter

**Comment by ichernev** [comment]
Hello fellow Sofia dweller!

https://www.timeanddate.com/worldclock/bulgaria/sofia

Sofia can be +2 or +3, currently its +3.
