### ISSUE TITLE
moment.duration().milliseconds() can return negative values

### ISSUE THREAD

**Issue by martin770** [moment/moment#4651]
The documentation states:
```
To get the number of milliseconds in a duration, use moment.duration().milliseconds().
It will return a number between 0 and 999.
```

But `moment.duration(-1).milliseconds()` returns `-1`

I can understand a negative number for moment objects to display moments relative to each other like `moment().from()`, `moment(a).diff(moment(b))` (to say that something happened x minutes in the past), but it seems like a `duration` should always be a positive number.

```
Where a moment is defined as single points in time, durations are defined as a length of time.
Durations do not have a defined beginning and end date. They are contextless.
```

Since they are `contextless`, they should never know they they are negative. You wouldn't say that something 'had a duration of -8 milliseconds' but instead you would say that it 'had a duration of 8 milliseconds'. If you wanted to know if it was a negative value, you would have to compare some context of the start and end times (of which a duration has no knowledge of).

```
const a = moment(0);
const b = moment(8);

const x = moment.duration(-8);
const y = moment.duration(8);

expect(x.asMilliseconds()).toBe(8);
expect(y.asMilliseconds()).toBe(8);

expect(a.diff(b)).toBe(-8);
expect(b.diff(a)).toBe(8);

expect(duration(a.diff(b))).toBe(8);
expect(duration(b.diff(a))).toBe(8);

if (a.diff(b) < 0) {
    console.log('moment a happened ' + a.diff(b) + ' milliseconds BEFORE moment b');
    console.log('moment b happened ' + b.diff(a) + ' milliseconds AFTER moment a');
} else {
    console.log('moment a happened ' + b.diff(a) + ' milliseconds BEFORE moment b');
    console.log('moment b happened ' + a.diff(b) + ' milliseconds AFTER moment a');
}
console.log('the duration from a to b is ' + duration(b.diff(a)) + ' milliseconds (a positive number)');
console.log('the duration from b to a is ' + duration(a.diff(b)) + ' milliseconds (a positive number)');
```

**Comment by ichernev** [comment]
Duration in moment can be negative. This won't change. If you want to make them non-negative use `.abs()`. You can even make a custom constructor that runs `abs()` at the end, and use that throughout your code. The possibilities are endless!

```javascript
moment.duration(-1).abs().milliseconds()
> 1
```
