### ISSUE TITLE
Parsing mistakes

### ISSUE THREAD

**Issue by someden** [moment/moment#4654]
Example: https://codepen.io/someden/pen/jabNGa

```js
const date = moment("2010-01-20", "DD.MM.YYYY")
console.log(date.format()) // "2001-10-20T00:00:00+03:00"
```
2010-01-20 -> 2001-10-20

I think the right behaviour is:
```js
const date = moment("2010-01-20", "DD.MM.YYYY")
console.log(date.format()) // "Invalid date"
```

**Comment by marwahaha** [comment]
If you use strict mode, this works:
```
moment("2010-01-20", "DD.MM.YYYY", true).format()
```

There is more information about strict mode here: https://momentjs.com/guides/#/parsing/strict-mode/
