### ISSUE TITLE
moment.utc Safari BST parse error

### ISSUE THREAD

**Issue by jack828** [moment/moment#4657]
**Description of the Issue and Steps to Reproduce:**

Open Safari 11
Run `moment.utc('Wed Jun 20 2018 00:00:00 GMT+0100 (BST)').toISOString()`
You'll get `null`

**Environment:**

Moment 2.22.2, Safari 11

**Other information that may be helpful:**
Errors on momentjs.org too.

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
>console.log( (new Date()).toString())
< Thu Jun 07 2018 17:12:55 GMT+0100 (BST)
>console.log((new Date()).toLocaleString())
< 07/06/2018, 17:12:55
>console.log( (new Date()).getTimezoneOffset())
< -60
>console.log( navigator.userAgent)
< Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
>console.log(moment.version)
< 2.22.2
```

**Comment by ashsearle** [comment]
If you open developer tools in Safari and ensure console logging it set to All, you'll see the deprecation warning:

> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

i.e. as you've discovered, the date format you're using works in some browsers and not others.

The suggestion is that you should ensure your dates are formatted in accordance with standards, _or_ if you know the format, pass the format string and use strict parsing.

**Comment by ichernev** [comment]
@jack828 specify the format or make sure its either ISO or RFC2822:

```javascript
moment('Wed Jun 20 2018 00:00:00 GMT+0100 (BST)', 'ddd MMM DD YYYY HH:mm:ss [GMT]ZZ')
> moment("2018-06-20T02:00:00.000")
```

Note that this does not parse the `(BST)` so it will fail if run in strict mode. Moment can't skip arbitrary text in its parser.
