### ISSUE TITLE
memory leak with these moment api

### ISSUE THREAD

**Issue by sureshmuvva49** [moment/moment#4658]
**Description of the Issue and Steps to Reproduce:**
## memory leak and holding the memory after a test
*Please include the values of all variables used.*
moment.parseZone('2017-07-31T03:55:13-08:00').format('MM/DD');
moment.parseZone('2017-07-31T03:55:13-08:00').valueOf();
moment.utc('2017-07-31T03:55:13-08:00');
moment.parseZone('2017-07-31T03:55:13-08:00').diff(moment(), 'days');
moment.utc('2017-07-31T03:55:13-08:00').isAfter(moment.utc(), 'day');

**Environment:**
2.18.1

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
Thu Jun 07 2018 14:36:47 GMT-0500 (CDT)
VM553:2 6/7/2018, 2:36:47 PM
VM553:3 300
VM553:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
2.18.1

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by ashsearle** [comment]
Can you give any details about how you spotted the memory leak, and confirm that it's still present in the latest moment release (2.22.2)

**Comment by ichernev** [comment]
@sureshmuvva49 do you have to execute all the code to get a memory leak? Or any line on its own leaks? How did you spot this? We need a way to iterate over possible solutions (at least) so the situation needs to be 100% reproducible.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
