### ISSUE TITLE
Identical branches and possible bugs spot by coverity

### ISSUE THREAD

**Issue by martinpitt** [moment/moment#4659]
We are using moment version 2.22.2. A coverity scan showed two possible bugs:

Defect type: IDENTICAL_BRANCHES
1. node_modules/moment/moment.js:3042: identical_branches: Ternary expression on condition "match[1] === "+"" has identical then and else expressions: "1". Should one of the expressions be modified, or the entire ternary expression replaced?

This is

            sign = (match[1] === '-') ? -1 : (match[1] === '+') ? 1 : 1;

and indeed the latter condition does not make sense. Possibly you mean `: 0` at the end?

Defect type: IDENTICAL_BRANCHES
1. node_modules/moment/locale/sl.js:24: identical_branches: Ternary expression on condition "withoutSuffix || isFuture" has identical then and else expressions: ""sekund"". Should one of the expressions be modified, or the entire ternary expression replaced? 

This is
                    result += withoutSuffix || isFuture ? 'sekund' : 'sekund';

and indeed the check is not having any net effect. This might be a wrong future form, or if there is really no difference, the check could just be removed.

**Comment by ichernev** [comment]
@ashsearle can you please include the `sl.js` fix there as well.
@martinpitt can you submit a patch that adds support for coverity (if its free etc).

Close in favor of #4663

**Comment by martinpitt** [comment]
I'm afraid it's not free, this is Red Hat's paid coverity plan.

Note: Usually the "Fixes #" in the associated PR will auto-close the issue when it lands; this is less confusing and more reliable than manual tracking.
