### ISSUE TITLE
Incorrect duration generated from string

### ISSUE THREAD

**Issue by ian-henderson** [moment/moment#4662]
**Description of the Issue and Steps to Reproduce:**

1. call `moment.duration('60000').asMinutes()` in the momentjs.com console.
2. expect a return value of 1 as a number.
3. a return value of 0 was returned instead.

I came across this on a project for work but found that I could reproduce it on momentjs's site as well. Is this not an intended use case for `moment.duration()`?

**Environment:**

Chrome 67 on OSX 10.13.4

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

In the same order:
```
Sun Jun 10 2018 16:54:14 GMT-0500 (Central Daylight Time)
6/10/2018, 4:54:14 PM
300
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36
2.22.2
```

**Comment by ashsearle** [comment]
> Is this not an intended use case for moment.duration()?

Not quite.  If you pass the number of milliseconds as a _number_ that's fine:

```js
moment.duration(60000).asMinutes(); // 1
moment.duration(+'60000').asMinutes(); // also 1 - using unary '+' to convert String to number
```

What you've done in your original code is pass a `String` to  `moment.duration`, which moment will then try to parse as an ASP.NET style timespan, or an ISO-format duration (see [docs](https://momentjs.com/docs/#/durations/))

**Comment by ian-henderson** [comment]
Oh, I see — thanks for the quick response! I figured that if the string was just a number, it'd be converted to a number instead of being parsed.
