### ISSUE TITLE
install  momentjs error 

### ISSUE THREAD

**Issue by alvin198761** [moment/moment#4669]
i get the error 

npm ERR! Unexpected end of input at 1:7953
npm ERR! li":"latest","benchmark":"latest","grunt-contrib-clean":"latest","gru
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\动岚未来科技02\AppData\Roaming\npm-cache\_logs\2018-06-15T01_43_00_784Z-debug.log

when i want to install momentjs
npm install moment --save

**Comment by liyuhang1997** [comment]
Try this command: `npm cache clean --force`

**Comment by ichernev** [comment]
@alvin198761 I hope @liyuhang1997 comment helped you. Next time try to include more relevant information to your submission.
