### ISSUE TITLE
[Bug] Incorect calculation of function duration - years, months

### ISSUE THREAD

**Issue by giangsoda** [moment/moment#4670]
```js
var start = moment('2018-01-01');
var end = moment('2019-01-01');
var duration = moment.duration(end.diff(start));
console.log(duration.years()); // = 0, but correct result should be 1
console.log(duration.months()); // = 11, but correct result should be 0, because year = 1
```
I use moment.js v2.22.2, hope you fix soon

**Comment by ashsearle** [comment]
Please read the [intro to Duration in the docs](https://momentjs.com/docs/#/durations/), and see if you get better results using `end.diff(start, 'years')` and `end.diff(start, 'months')`

**Comment by giangsoda** [comment]
end.diff(start, 'months') = 12, but i want the result = 0, i want to calculate period time, not the time difference

**Comment by ashsearle** [comment]
I think you've stumbled on the most difficult area to agree on.

You're removing context from two dates, and getting a time difference in milliseconds.  You then want to convert milliseconds to some human-readable interpretation like "3 months 2 days".

The problem is that days, months and years aren't of fixed duration.

Take a period of 60 days.   That could be:
"2 months" - Jan 1st to March 1st 2020.
"1 month 30 days" - April 1st to May 31st 2020 (or July 1st to August 30th 2020)
"2 months 1 day" - Jan 1st to March 2nd 2019

**Comment by giangsoda** [comment]
I agree with you.
But there is a mistake in these two days when using function `moment.duration` (I was asked in the problem description section)
"0 year 11 months": 2018-01-01 -> 2019-01-01, // correct result: 1 year 0 months

**Comment by ashsearle** [comment]
I haven't explained myself very well.

You calculated the difference - in milliseconds - between two dates:
```js
var start = moment('2018-01-01');
var end = moment('2019-01-01');
console.log(end.diff(start)); // result: 31536000000
```

You're then calling `moment.duration(31536000000)`, which you then want to be converted to years and months.

How many milliseconds are there in a year?  Well, it could be 31536000000, but it could also be 31622400000 (leap year.)  On average, it'll be 31557600000, and you've passed it a number less than that - so your duration is shorter than the average year.

I don't think anyone likes the way duration handles conversion from milliseconds to months or years, but it's hard to argue that it'd be 'better' to standardise on 30 day months and 365 day years.

Please reconsider using `end.diff(start, 'months')`, with a little more work:
```js
end.diff(start, 'years'); // 1
end.diff(start, 'months') % 12; // 0
```

**Comment by ichernev** [comment]
@giangsoda you're doing it wrong :)

```javascript
var start = moment('2018-01-01');
var end = moment('2019-01-01');
var duration = moment.duration({from: start, to: end});
duration.years() // 1
duration.months() // 0
```

This is the best way to construct duration from start and end. Otherwise a year is actually 365.25 days. Go ask google. So your duration in milliseconds is just 365 days, which is **clearly** less than a year.

**Comment by alamothe** [comment]
@ichernev Awesome!

**But why is this constructor not mentioned in the docs at all?**

Docs popularize construction based on `diff` which is clearly the wrong way to do this (it's going through milliseconds, which loses all information about units).

**Comment by alamothe** [comment]
...I figured that even:

```
const duration = moment.duration({from: start, to: end});
```

does not account correctly for DST. It will return a duration which only has months and milliseconds. Pretty frustrating.
