### ISSUE TITLE
Incorrect calculation of date when date day/month/year have to much numbers

### ISSUE THREAD

**Issue by agagaga123** [moment/moment#4673]
For invalid date, for example 300/06/2018, we get result: 30/06/2018.
The last numbers are cut.
It should't be calculated like that, it should be defined as invalid date.

Example:
```js
moment('300/06/20108 23:38:59', 'DD/MM/YYYY HH:mm:ss').toDate()
```
Expected result:
> Invalid date

Actual result:
> Wed Jun 30 2010 23:38:59 GMT+0200 (CEST)

Environment:
```
Mon Jun 18 2018 12:41:28 GMT+0200 (CEST)
6/18/2018, 12:41:28 PM
-120
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
2.22.2

**Comment by ashsearle** [comment]
I suggest you use [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/):

```js
moment('300/06/20108 23:38:59', 'DD/MM/YYYY HH:mm:ss', true).toDate(); // Invalid Date
```

**Comment by agagaga123** [comment]
Ok, This is very useful for us. Thanks!
