### ISSUE TITLE
incorrect fromNow()

### ISSUE THREAD

**Issue by flamner** [moment/moment#4675]
today is 2018/06/20 and date is 1990/06/19 so, moment(date, "YYYYMMDD").fromNow() should return 27 years ago, but it return 28 years ago, FIX THIS!

**Comment by liyuhang1997** [comment]
```js
moment("19901222","YYYYMMDD").fromNow();
"27 years ago"
moment("19901221","YYYYMMDD").fromNow();
"28 years ago"
```

**Comment by Aukhan** [comment]
working as expected for me
https://repl.it/@Aukhan/moment-diff-test

which makes sense because I expect it to use the rounded `diff` method

**Comment by ichernev** [comment]
For me it also returns 27. I guess it depens on the timezone, it also depends on the time of day when that happened. Until you provide more info this can not be resolved. If you got a report from a client its possible that they were already a day ahead when that happened and you're looking at local time.

For me I have to push it really hard with utc to get 28, which leads me to the conclusion that this is reported wrong:
```javascript
moment.utc("19901222","YYYYMMDD").diff(moment.utc('2018-06-20T23:59:59-25:00', 'YYYY-MM-DDTHH:mm:ssZZ'), 'years', true)
> -27.50011570859054
// notice 23:59:59 and timezone -25:00, if it is -24 or closer to 0 it still displays 27.49...
```

> FIX THIS!

I could merge a patch, unless it contains `MERGE THIS!`.
