### ISSUE TITLE
Wrong display of moment.format("L") with Chrome

### ISSUE THREAD

**Issue by Xaar37** [moment/moment#4678]
Hi,

I have a strange result with Chrome (Version 67.0.3396.87) that I do not reproduce with Firefox, Edge or IE.

Using moment.format("L") for "1975-08-18T00:00:00+02:00" gives "08/17/1975" with Chrome. It's wrong as it should be "08/18/1975" (like in other browsers).

Here you can find a jsfiddle: https://jsfiddle.net/94Lw61h0/.

Environment: Chrome 67 on Windows 10.
Time zone: UTC+1.
Actual date and time: 2018-06-21 18:22.
No other libraries.

Thank you.

**Comment by ashsearle** [comment]
This sounds like Chrome is working fine.  I'm more concerned about why your other browsers aren't producing the same result.

```js
var mo = moment("1975-08-18T00:00:00+02:00");
console.log(mo.toISOString()); // "1975-08-17T22:00:00.000Z"
console.log(mo.toISOString(true)); // "1975-08-17T23:00:00.000+01:00"
console.log(mo.format("L")); // "08/17/1975"
```

What do you see in Firefox and Edge?

**Comment by Xaar37** [comment]
In Firefox, Edge and others:
1975-08-17T22:00:00.000Z
1975-08-18T00:00:00.000+02:00
08/18/1975

As you can see, format("L") and toISOString(true) do not provide the same result as in Chrome. It's worse for format("L") because it's not the same day...

After some searches, it seems that Chrome v67 changes the way it handles date and time with timezone and the DST (Daylight Saving Time). Chrome is more accurate because in France (GMT+1/+2), the DST exists since 1976-03-28 (not in 1975). Firefox and others browsers seems to handle DST like a constant in time...

It seems not to be a bug from momentjs but it has a huge impact as it makes Chrome behaving different from all others browsers... I'm looking for a way to fix this. No good clue at the moment.

**Comment by ichernev** [comment]
If you want consistent DST behavior across different timezones, you can consider [moment-timezone](https://github.com/moment/moment-timezone).

As far as I understand its an issue with DST handling *in the browser* and not in moment.js. We don't handle browser bugs related to DST (but moment-timezone fixes those). Safari has a ton, I've found a few myself :)

Feel free to reopen if you thing it is an issue with moment.
