### ISSUE TITLE
class base library

### ISSUE THREAD

**Issue by MHA15** [moment/moment#4679]
Hi 
I'm so interested why this component is not converted to class base format yet!!
Is'n there any fork which written in typescript or at least a class base js?
is there any plan to make it class base?

**Comment by ichernev** [comment]
Moment 3.x will likely support the newest typescript. Or it won't support any typescript version and you'd have to import it with `@types/xxx`.

Currently it supports typescript 1.x.

**Comment by MHA15** [comment]
Yeah I know that there is some type definitions for it but I wants to inherit that to customize it for my self but it can not be with just type definitions it must be implemented class way
