### ISSUE TITLE
Feature Request: Customize time or a formatter

### ISSUE THREAD

**Issue by jalite1991** [moment/moment#4680]
Is it possible customize time for a locale like we do with AM/PM . I need to be able to check if do if else check to remove minutes if it doesn't equal 00 or 30. Also change to change 12:00am to Midnight and 12:00pm to noon.

**Comment by ichernev** [comment]
You can inherit a locale and customize it as you wish: http://momentjs.com/docs/#/customization/
You need to tweak date formats: http://momentjs.com/docs/#/customization/long-date-formats/

My suggestion is to just write a function, that attaches to the moment object and call it when you need your thing done:

```javascript
// define it
moment.fn.myFormat = function() {
  // use this.format('...') or any other moment function
  // return this.minutes() != 30 ? this.format('HH') : this.format('HH:mm');
}
// then use it:
moment().myFormat();
```
