### ISSUE TITLE
Non-breaking space should be used between some date and time elements

### ISSUE THREAD

**Issue by dzamlo** [moment/moment#4684]
Without non-breaking space, it's possible that some elements that shouldn't be separated are on different line. For example the the month name and day of the month could be on two different lines. 

The exact rules of where to use non-breaking space are likely to be different for each locale.

To fix that, I think that the locale files could be changed to use the non breaking spaces in `longDateFormat` and `relativeTime` where appropriates.

The problem with that is that the format are also used to parse, and parsing a date that use regular space should still work.

Another question that remains is how to encode the non-breaking spaces in the locale files:
1. - using the Unicode character as is as-is, 
2. - with \u00a0
3. - with the HTML entity &nbsp;

The issue with first solution is that it's hard to know what kind of space is used when reading the source code. With the third solution, you need to be sure that the string is never escaped before in reach the HTML. My preferred solution is the second one.

**Comment by marwahaha** [comment]
If this is required by your use case, I think it can be solved outside of Moment.js . Let us know if you find such a solution, and we can explain it in the docs.

**Comment by marwahaha** [comment]
For now, we will not take this change. Please re-open if you still have issues.
