### ISSUE TITLE
How does from() handle partial dates?

### ISSUE THREAD

**Issue by kcoram** [moment/moment#4686]
**Description of the Issue and Steps to Reproduce:**

My team and I are trying to use moment().from(dateOfBirth) to calculate a person's age. Our unit tests started failing on July 1st. We expected '17.5' to be truncated to give us an age of '17 years', but our tests are now failing saying that '18 years' does not equal '17 year'.

```js
  it('moment().from() should work as expected', () => {
    const firstHalfOfYear = '2018-01-19';
    const secondHalfOfYear = '2018-07-01';
    const testDate = '2001-01-01';

    expect(moment(firstHalfOfYear).from(testDate, true)).toBe('17 years', 'from() fails in first half of the year');
    expect(moment(secondHalfOfYear).from(testDate, true)).toBe('17 years', 'from() fails in second half of the year');
  });
```

Re-reading the docs on https://momentjs.com/docs/ it isn't clear to me what the expected behavior really should be.

**Environment:**

Karama 2.0.2
Jasmine-core 3.1.0
Moment 2.22.2

Browser: Chrome 67.0.3396.99 (Windows)

```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
```
returns:
```
Mon Jul 02 2018 10:10:07 GMT-0400 (Eastern Daylight Time)
VM2630:2 7/2/2018, 10:10:07 AM
VM2630:3 240
VM2630:4 Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
```

**Comment by ashsearle** [comment]
I guess [fromNow](https://momentjs.com/docs/#/displaying/fromnow/) is the most relevant bit of the documentation, and says:

Range | Key | Sample Output
-- | -- | --
320 to 547 days (1.5 years) | y | a year ago
548 days+ | yy | 2 years ago ... 20 years ago

That could probably be clearer, but basically it says that years are rounded, not floored.

i.e. "17 years" describes the range from 16.5 to 17.5 years, not the range from 17 to 18 years.

**Comment by kcoram** [comment]
Thank you, @ashsearle . That clarifies the matter for me.
