### ISSUE TITLE
Moment.defaultFormat does not affect date parsing

### ISSUE THREAD

**Issue by mankey-ru** [moment/moment#4687]
**Description of the Issue and Steps to Reproduce:**
Moment.defaultFormat affects only format() function and does not affect date parsing
```
console.log(moment.version) // 2.22.2
moment.defaultFormat = "DD.MM.YYYY HH:mm";
console.log( moment('20.07.2018 09:19').toDate() ) // Invalid date
console.log( moment('20.07.2018 09:19', moment.defaultFormat).toDate() ) // Fri Jul 20 2018 09:19:00 GMT+0300
```
Is that right?

**Environment:**

Chrome 67 on Windows 10

**Comment by ashsearle** [comment]
Yes, that's correct.

**Comment by jack-chapman** [comment]
I made a PR to add to the docs about this:  https://github.com/moment/momentjs.com/pull/537

**Comment by marwahaha** [comment]
fixed by https://github.com/moment/momentjs.com/pull/537
