### ISSUE TITLE
[Bug] Timezone for Sudan i.e Africa/Khartoum has been changed

### ISSUE THREAD

**Issue by shreyashah115** [moment/moment#4690]
It has been changed from GMT+3 to GMT+2

**Comment by ashsearle** [comment]
The core moment library doesn't contain any timezone information: all timezone info is derived from the browser's underlying Date implementation.

Can you demonstrate the bug?  If you're using it, perhaps it would be more appropriate to raise this in against [moment/moment-timezone](https://github.com/moment/moment-timezone)?
