### ISSUE TITLE
Parsing a time before 1879 will add 12 minutes and 12 seconds on Chrome

### ISSUE THREAD

**Issue by Annoa** [moment/moment#4694]
**Description of the Issue and Steps to Reproduce:**
Parsing a time before 1878-12-31 at 23:47:48+01:00 will add 12 minutes and 12 seconds to any time
moment('1878-12-31T23:47:47+01:00').format('HH:mm');
= 23:59

But for any second after that will return the correct time
moment('1878-12-31T23:47:48+01:00').format('HH:mm');
= 23:48

**Environment:**
I have tried it on Edge and Firefox but only reproducable in Chrome.
Using Chrome Version 67.0.3396.99 (Official version) (64 bit) on Windows 10

**Other information that may be helpful:**
Code was run at Mon Jul 09 2018 15:55:04 GMT+0200 (CEST)

*Result from Output*
Mon Jul 09 2018 15:34:13 GMT+0200 (centraleuropeisk sommartid)
2018-07-09 15:34:13
-120
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
2.11.1

**Comment by ashsearle** [comment]
It looks like Chrome has started to add and use historic timezone information in v67, with historic timezone changes being of the order of minutes and seconds, which leads to this unexpected behaviour.

e.g. see this [Chrome bug report](https://bugs.chromium.org/p/v8/issues/detail?id=7843)

I'm not sure exactly what your location is, but you can see historic timezone information at [timeanddate](https://www.timeanddate.com/time/zone/uk/london?syear=1800) (showing that London changed its timezone by 1 minutes 15 seconds in 1848, and I can see that reflected in Chrome 67 using:

```js
console.log(new Date("1847-01-01T11:00:00+00:00").toString())
// outputs "Fri Jan 01 1847 10:58:45 GMT-0001 (Greenwich Mean Time)"
```

I expect you're based somewhere with a quirky timezone change occurring in 1878.
