### ISSUE TITLE
moment.HTML5_FMT.WEEK should be 'GGGG-[W]WW'

### ISSUE THREAD

**Issue by jacquev6** [moment/moment#4698]
The current value of HTML5_FMT.WEEK is `"YYYY-[W]WW"` but this format is supposed to parse and format *ISO* weeks. It should be `"GGGG-[W]WW"`.

When parsing, `YYYY` is equivalent to `GGGG`, but when formatting, it's not : for a year like 2004 when the first ISO week starts in the previous year, formatting with "YYYY" returns "2003":

    moment("2004-W01", moment.HTML5_FMT.WEEK).format(moment.HTML5_FMT.WEEK) === "2003-W01"
    moment("2004-W01", "GGGG-[W]WW").format("GGGG-[W]WW") === "2004-W01"

**Comment by ashsearle** [comment]
@jacquev6 Well spotted! Thanks for logging the issue :-)

**Comment by Safirion** [comment]
Documentation is not up to date : https://momentjs.com/docs/#/parsing/string-format/

![image](https://user-images.githubusercontent.com/11511729/79696984-4566a100-8280-11ea-9d33-b6bb32d27f00.png)
