### ISSUE TITLE
[WIERD]If I add 48 hours to 2018-10-27 I get 2018-10-28

### ISSUE THREAD

**Issue by moczard** [moment/moment#4699]
**If I add 48 hours to 2018-10-27 I get 2018-10-28**

Code:
import moment from 'moment';

for(let i = 1; i <29; i++){
  console.log(moment([2018, 9, i]).add(48, 'h').format('YYYY-MMMM-DD'));
}

Result:
2018-October-03
2018-October-04
2018-October-05
2018-October-06
2018-October-07
2018-October-08
2018-October-09
2018-October-10
2018-October-11
2018-October-12
2018-October-13
2018-October-14
2018-October-15
2018-October-16
2018-October-17
2018-October-18
2018-October-19
2018-October-20
2018-October-21
2018-October-22
2018-October-23
2018-October-24
2018-October-25
2018-October-26
2018-October-27
**2018-October-28**
**2018-October-28**
2018-October-29

**Info:**

Fri Jul 13 2018 17:15:46 GMT+0200 (Central European Summer Time)
7/13/2018, 5:15:46 PM
-120
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
2.22.2

**Comment by ashsearle** [comment]
You're in the 'Central European Summer Time' zone, and will shift back to 'Central European Time' on the 28th October 2018 when clocks move back from 3AM to 2AM.

In essence, the 28th October will be 25 hours long for you.

**Comment by moczard** [comment]
That makes sense, thanks.
