### ISSUE TITLE
isValid returning true for invalid date string when format is provided

### ISSUE THREAD

**Issue by ralphsmith80** [moment/moment#4702]
**Description of the Issue and Steps to Reproduce:**
The error is present in my environment but this can also be reproduced in any browser dev tool console (that I checked) on the [Moment Doc page](https://momentjs.com/docs/).

I'm pulling off part of a dynamically generated URL to determine if is a valid date matching the format 'YYYY-MM'. I was initially doing this with `moment(<data-test-string>).isValid()` which works but I get the deprecation warning below. I fixed the error by added the format `YYYY-MM` as suggested, but it's returning invalid results. 

**Deprecation warning**
```
moment.js:293 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
```

### Main concern
**Good**
`moment('TWQuQvFqEQk0whGW5TdB', 'YYYY-MM').isValid()`
> true

**Bad**
`moment('TWQuQvFqEQk0whGW5TdB').isValid()`
> false

### Other examples
**Good**
`moment('O8xHgJ17Lml8TK7vGuwD', 'YYYY-MM').isValid()`
> false

**Bad**
`moment('TWQuQvFqEQk0whGW5TdB', 'YYYY-MM').isValid()`
> true

**Good**
`moment('O8xHgJ17Lml8TK7vGuwD', 'YYYY-MM').month()`
> NaN

**Bad**
`moment('TWQuQvFqEQk0whGW5TdB', 'YYYY-MM').month()`
> 4

**Good**
`moment('O8xHgJ17Lml8TK7vGuwD', 'YYYY-MM').toSting()`
> VM132:1 Uncaught TypeError: moment(...).toSting is not a function at <anonymous>:1:46

**Bad**
`moment('TWQuQvFqEQk0whGW5TdB', 'YYYY-MM').toString()`
> "Mon May 01 0000 00:00:00 GMT-0700"

### Environment:
Node v8.10.0
Windows 10
Chrome 67.0.3396.99
Firefox Developer Edition: 62.0b8 (64-bit)
moment 2.22.2

**Other information that may be helpful:**
* time zone MST
* time and date at which the code was run - 10:40am 7/15/2018

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
**output**
```
Sun Jul 15 2018 10:49:55 GMT-0600 (Mountain Daylight Time)
VM165:2 7/15/2018, 10:49:55 AM
VM165:3 360
VM165:4 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
VM165:5 2.22.2
```
*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.* -

**Comment by ralphsmith80** [comment]
As a workaround for now I'm using a regex to ensure the format is was I want before running `moment`.

```
const regex = /([12]\d{3}-(0[1-9]|1[0-2]){1,7}$)/
const month = 'TWQuQvFqEQk0whGW5TdB'
const valid = regex.test(month) && moment(month, 'YYYY-MM').isValid()
```

**Comment by rahulsingh737** [comment]
when you provide format, it goes to a function `configFromStringAndFormat` to create moment string which has the issue with regex patterns and even if it gets string with some integer in between, it takes the integer and tries to create date. But, when you don't provide format for moment, it goes to function `configFromInput` which seems to be working fine and providing warnings.

**Comment by marwahaha** [comment]
The regex might be a better tool in this case.

You can use strict parsing, but then I don't think any of your URLs will pass.

```
moment('TWQuQvFqEQk0whGW5TdB', 'YYYY-MM', true).isValid() // false
```

Glad you have a solution.
