### ISSUE TITLE
Cannot find Moment JS Scripts after install via Nuget Package on Visual Studio 2017

### ISSUE THREAD

**Issue by portal7** [moment/moment#4705]
**Description of the Issue and Steps to Reproduce:**
 
- Create a new Project  "Web Application ASP.NET Core 2" 
- Open Nuget Package Console and run
Install-Package Moment.js  
try to find Moment Script File on ASP.NET Core 2 Project after successfully installation

**Result:**
No package or file found  on  "Content/Scripts"  or wwwroot/Content/Scripts  or any location

**Environment:**
Chrome  (Not matter)  Windows 10 x64, Node  v6.9.5

**Comment by jcardus** [comment]
Same problem here...

**Comment by paul-green** [comment]
I've had a look at this and it works with 'full-cream' .Net projects but simply doesn't work with .net core projects. The moment.nuspec and generated .nupkg are fine. As mentioned by @waseemahmad31 the scripts end up in the user's packages folder and would need to be copied (i.e. not a great solution).

**Comment by ndreisg** [comment]
According to [this issue](https://github.com/NuGet/Home/issues/6548) you have to use the \<contentFiles\> tag in the .nuspec

**Comment by marwahaha** [comment]
I'm not sure what else we can do here.

**Comment by andrerav** [comment]
Seeing the same problem in VS2019 and .NET Core 3.1 with a ASP.NET Core project.
