### ISSUE TITLE
CalendarFormat compares startOfDay instead of now

### ISSUE THREAD

**Issue by emil13** [moment/moment#4707]
**Description of the Issue and Steps to Reproduce:**
In moment/src/lib/moment/calendar.js(21) calendarFormat is called with the variable sod instead of now. According to the documentation of calendar time: 

> Calendar time displays time relative to a given referenceTime (defaults to now),

This causes problems as in my calendarFormat I want to display the amount of minutes since the moment if it's less than an hour ago. But since the parameter now isn't actually now but rather startOfDay my diff between myMoment and now is wrong.

I created a small piece of code to demonstrate:

import moment from 'moment/moment';  
    (() => {  
      moment.calendarFormat = (myMoment, now) => {  
    console.log(myMoment.diff(now, 'hours', true));  
    return 'sameElse';  
  };  
  moment(new Date()).subtract(45, 'minutes').calendar();  
})();

I expected this to output -0.75 but instead I get 13.6329 (hours since midnight minus 45 min)

**Environment:**
Chrome Version 67.0.3396.99 (Official Build) (32-bit) on Windows 7 (64bit)

**Other information that may be helpful:**
I would assume that nobody uses the calendarFormat in this way or this would have been an issue earlier. The functionality I want is: if the moment is less than one hour in the past or less than one hour in the future: display the amount of minutes to the moment. In other cases: date + time.

JS consol log output:
07/18/2018
Wed Jul 18 2018 14:58:18 GMT+0200 (Central European Summer Time)
7/18/2018, 2:58:18 PM
-120
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
2.22.2

**Comment by marwahaha** [comment]
I agree this is confusing. I'd rather update the documentation here/
