### ISSUE TITLE
moment("0004-01-01T07:59:59+08:00").format() result error

### ISSUE THREAD

**Issue by vvpvvp** [moment/moment#4709]
**Environment:**

Chrome 67 on OSX

```js
console.log( (new Date()).toString())
// Thu Jul 19 2018 14:20:08 GMT+0800 (中国标准时间)

console.log((new Date()).toLocaleString())
// 2018/7/19 下午2:20:08

console.log( (new Date()).getTimezoneOffset())
// -480

console.log( navigator.userAgent)
// Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

console.log(moment.version)
// 2.10.6

```
bug: 

``` js
moment("0004-01-01T07:59:59+08:00").format()
// 0004-01-01T08:05:42+08:00
```

other message:

``` js
new Date("0004-01-01T07:59:59+08:00")
// Thu Jan 01 0004 08:05:42 GMT+0805 (中国标准时间)
```

**Comment by ashsearle** [comment]
Chrome 67 added and uses historic timezone information - which leads to some surprising date/time formatting before countries started aligning and standardising around GMT / UTC offsets.

Example: [Chongqing](https://www.timeanddate.com/time/zone/china/chongqing) has an offset of 7 hours 6 minutes 20 seconds until 1928, when it aligned as +7 hours.

moment isn't doing anything wrong, and neither is Chrome.  It's just surprising, and inconsistent as Chrome appears to be the only browser using such historic timezone information.

**Comment by vvpvvp** [comment]
I know it's because chrome use historic timezone info.
But I think moment's result is incorrect.

``` js
moment("0004-01-01T07:59:59+08:00").format()
// 0004-01-01T08:05:42+08:00
```
result should be:
``` js
// 0004-01-01T08:05:42+08:05
or
// 0004-01-01T07:59:59+08:00
```
like chrome's result:
``` js
new Date("0004-01-01T07:59:59+08:00").toISOString()
// 0003-12-31T23:59:59.000Z
```

**Comment by marwahaha** [comment]
I'm going to leave the existing behavior.

on my machine:
```
moment("0004-01-01T07:59:59+08:00").format()
"0003-12-31T16:07:01-07:45"
```

If you don't like it, use
```
moment.utc("0004-01-01T07:59:59+08:00").format()
"0003-12-31T23:59:59Z"
```
