### ISSUE TITLE
Time calculation can be out by 1 hour depending on timezone, OS and browser

### ISSUE THREAD

**Issue by andrewgill-draysontechnologies** [moment/moment#4711]
The following block of code can give different hours depending on your timezone setting and browser used.

```
<!doctype html>
<html>
<head>
    <script src='js/moment.min.js'></script>
</head>
<body>
    <div id='output'></div>
    <script>
        setInterval(() => {
            var datetime = "2018-07-20 12:00:00"
            var m1 = moment(datetime);
            var m2 = moment(moment().diff(m1));
            document.getElementById("output").innerHTML = Date.now() + ":" + m2.format('H') + ' hr ' + m2.format('m') + ' m';
        }, 500);
    </script>
</body>
</html>
```

e.g. When performed on a Mac with timezone set to London/UK BST at 15:47 using the same block of code the output has a 1 hour difference:

Chrome Version 67.0.3396.99 (Official Build) (64-bit):
1532098077351:4 hr 47 m

Safari Version 11.0.3 (13604.5.6):
1532098077351:3 hr 47 m

**Environment:**

If your timezone is BST (Europe/London) and the current date is set to a value inside daylights savings time +1hr e.g. 30-Jul-2018 then different browsers give a different hour calculation. Note that some timezones do not exhibit the issue.

Base time combinations:
Win 10-IE11
Win 10-Edge
Win 10-Firefox
Mac 10.13.3-Safari

Base time +1 hour combinations
Win 10-Chrome
Mac 10.13.3-Chrome
Mac 10.13.3-Firefox

Fri Jul 20 2018 15:54:03 GMT+0100 (British Summer Time)
VM139:2 20/07/2018, 15:54:03
VM139:3 -60
VM139:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Moment 2.22.2

**Comment by ashsearle** [comment]
Can you confirm whether this problem occurs in normal use, or only when you're manually changing your OS timezone?

I'm wondering if this is due to [inconsistent OS timezone propagation](https://github.com/moment/moment/issues/4516#issuecomment-376443186)

Are all the OS/browser combinations you mention affected, or just some subset on macOS?

**Comment by andrewgill-draysontechnologies** [comment]
This is normal use. i.e. start up windows or mac os with timezone set to Europe/London BST. 

I only mention that some other timezones (daylights savings time related) also exhibit the problem while other timezones do not.

The code above will give different hour results if you are set to BST depending on which OS and browser you are using.

Chrome is consistent and is always plus 1 hour on PC or Mac, Firefox varies by OS, with the mac version being +1 hour and IE/Edge and Safari all have 1 hour less than Chrome.

**Comment by ashsearle** [comment]
Interesting...

The data you're using and the way you're using it means `m2` is a date in January 1970.

BST did not revert to GMT in 1969 or 1970 (see [historic data for London time zone](https://www.timeanddate.com/time/zone/uk/london))

Some browsers / OS know this, and use the historically accurate timezone (+0100).  Others do not know the historical information, so use the assumed timezone, which would be GMT at that time of year (+0000)

**Comment by marwahaha** [comment]
I think this is similar to https://github.com/moment/moment/issues/4694 

I think it's based on what your browser thinks the local offset is in 1970. Perhaps `moment.utc()` might help here.

Please re-open if you still have issues.
