### ISSUE TITLE
Month ordinal strict parsing is not working

### ISSUE THREAD

**Issue by heck4** [moment/moment#4714]
**Description of the Issue and Steps to Reproduce:**
I believe that this should be a valid value and format, with no ambiguity:
`moment('22nd,7th,2018', 'Do,Mo,YYYY', true).isValid()`
I would expect that to be true, and matches today's date which is July 22nd, 2018

For comparison this works:
`moment('22nd,7,2018', 'Do,M,YYYY', true).isValid()`

**Environment:**
Chrome Version 67.0.3396.99 (Official Build) (64-bit) on Windows 10 Enterprise 64-bit

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
Central
* The time and date at which the code was run
Around 11:30 PM July 22nd, 2018
* Other libraries in use (TypeScript, Immutable.js, etc)
lodash, global

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
Sun Jul 22 2018 23:40:59 GMT-0500 (Central Daylight Time)
7/22/2018, 11:40:59 PM
300
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
2.20.1

**Comment by ashsearle** [comment]
I think you're trying to use an unsupported / undocumented parsing format: `Mo` isn't mention in the documentation for [parsing format](https://momentjs.com/docs/#/parsing/string-format/).

**Comment by heck4** [comment]
Oh... never mind then. I think I was looking at this sheet for my reference:
https://docs.google.com/spreadsheets/d/1lPzBlmJVAkN6HUw28wBJmY1SdbSInRIBY0JCmBUDUmk/edit?hl=en_US&hl=en_US#gid=0

**Comment by ashsearle** [comment]
Sure, the list of [formatting tokens](https://momentjs.com/docs/#/displaying/format/) is different from parsing tokens.

I don't think it would be that hard to add support for `Mo` (along with others like `Qo`, `DDDo`, `wo` etc.)

I guess the only reason they're not supported is that no-one's asked for them - and it'd add (a little) more bloat.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
