### ISSUE TITLE
error when count different days in years, month and day

### ISSUE THREAD

**Issue by irwanhl** [moment/moment#4715]
var test = _AGE('2004-03-31')

function _AGE(data){

	var now = formatDate()

	console.log("now", now, "birthdate", data)
	var arrNow = now.split('-')
	var yearNow = parseInt(arrNow[0])
	var monthNow = parseInt(arrNow[1])
	var dayNow = parseInt(arrNow[2])

	
	var birth = data.split('-')
	var yearBirth = parseInt(birth[0])
	var monthBirth = parseInt(birth[1])
	var dayBirth = parseInt(birth[2])

	console.log("yearBirth", yearBirth, monthBirth, dayBirth)

	var nowMoment = moment([yearNow, monthNow, dayNow])
	var birthMoment = moment([yearBirth, monthBirth, dayBirth])

	var years = nowMoment.diff(birthMoment, 'year')
	birthMoment.add(years, 'years');

	var months = nowMoment.diff(birthMoment, 'months')
	birthMoment.add(months, 'months')

	var days = nowMoment.diff(birthMoment, 'days')

	console.log(years + ' years ' + months + ' months ' + days + ' days')

	var age = years + "Y " + months + "M " + days + "D";

	console.log(age)

	return age
}

function formatDate() {
    var d = new Date(),
    month = '' + (d.getMonth() + 1),
    day = '' + d.getDate(),
    year = d.getFullYear();
    if (month.length < 2) month = '0' + month;
    if (day.length < 2) day = '0' + day;
    return [year, month, day].join('-');
}

always return NaNY NaNM NaND when fill with 2004-03-31

**Comment by ashsearle** [comment]
`moment` (like `Date`) takes 0-based months, so you need to subtract 1 from month on these lines:

```js
var nowMoment = moment([yearNow, monthNow - 1, dayNow])
var birthMoment = moment([yearBirth, monthBirth - 1, dayBirth])
```

Without doing that, you're actually trying to compare to 2004-04-31, which doesn't exist (as April only has 30 days.)  That's why you're getting `NaN`

**Comment by marwahaha** [comment]
Let us know if you have other troubles.
