### ISSUE TITLE
Parse object with offset

### ISSUE THREAD

**Issue by gilles-crealp** [moment/moment#4722]
It would be great if[ `moment({unit: value, ...});`](http://momentjs.com/docs/#/parsing/object/) (and by the way [`moment(Number[]);`](http://momentjs.com/docs/#/parsing/array/)) would accept an offset. So you can parse date object (or array) who is not in local time (or UTC with [`moment.utc()`](http://momentjs.com/docs/#/parsing/utc/)).

``` javascript
let date = {
  year: 2018,
  month: 6,
  day: 31,
  offset: 2
}

// Current way
console.log(moment.utc(date).subtract(date.offset, 'hour').format())

// New way with offset considered
console.log(moment.utc(date).format())

// Both will output 2018-07-30T22:00:00Z
```

Related with https://github.com/moment/moment/issues/2945.

**Comment by marwahaha** [comment]
This is interesting.

For now, you can use something like
```
var date = {
  year: 2018,
  month: 6,
  date: 31, 
hour: 0, 
minute: 0, 
second: 0}
moment().utcOffset(2).set(date).utcOffset(0).format() // "2018-07-30T22:00:00Z"
```

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
