### ISSUE TITLE
Deprecation warning outputs as error trace

### ISSUE THREAD

**Issue by null4bl3** [moment/moment#4723]
In a deprecation warning i am getting the output of a new Error()).stack trace.
Is it just me or is that perhaps a bit much to return a deprecation warning as a error?

![deepinscreenshot_select-area_20180801110106](https://user-images.githubusercontent.com/10575715/43512004-365bf6aa-957a-11e8-876f-b3db2ad39e32.png)

The issue is present in Nodejs v9.11.1 and v10.2

https://github.com/moment/moment/blob/2e2a5b35439665d4b0200143d808a7c26d6cd30f/moment.js#L320

**Comment by ashsearle** [comment]
The deprecation _uses_ `Error` to get a stack trace, but doesn't return the `Error`.

The message is output using `console.warn`.

The benefit of returning the stack trace is that the user can see which line of _their_ code caused the deprecation warning.

What's the issue you're reporting?  What do you think moment is doing wrong?

**Comment by null4bl3** [comment]
The issue i am reporting is that a basic deprecation warning prints a full Error stack trace to the console. I am all for printing deprecation warnings, especially when the deprecation is breaking in a future Major release, but when there is no error occurring, using an Error to display a deprecation warning is just not right.

**Comment by marwahaha** [comment]
Thanks for opening this request.
For now, we will not take this change.
