### ISSUE TITLE
Humanize Issue

### ISSUE THREAD

**Issue by OriginalArye** [moment/moment#4725]
Hello.
I get an incorrect value when I try to humanize on duration.
When I enter 11 months, the result "a year" instead of "11 Months".

```js
moment.duration(11, 'M').humanize();
```
[http://jsfiddle.net/rLjQx/101462/](http://jsfiddle.net/rLjQx/101462/)
I am using version 2.22.2

**Comment by ashsearle** [comment]
See: <https://momentjs.com/docs/#/displaying/tonow/>

I'm not sure how you're supposed to walk the documentation from `humanize()` to the `toNow`, but... the behaviour follows in the information in the table in the `toNow` section...

```js
moment.duration(319, 'days').humanize(); // 10 months
moment.duration(320, 'days').humanize(); // a year
moment.duration(547, 'days').humanize(); // a year
moment.duration(548, 'days').humanize(); // 2 years
```

**Comment by OriginalArye** [comment]
The problem still exists even if you use ```end.to(start, true)```
I think ```end.to(start, true)``` is using ```moment.duration``` function.

```js
moment.duration(10, "M").humanize()  // 10 months
moment.duration(11, "M").humanize()  // a year.  Should be 11 months
moment.duration(12, "M").humanize()  // a year

moment('2018-11-1').to(moment('2018-1-1'), true) // 10 months
moment('2018-12-1').to(moment('2018-1-1'), true) // a year.  Should be 11 months
moment('2019-1-1').to(moment('2018-1-1'), true) // a year
```

**Comment by ashsearle** [comment]
@OriginalArye It sounds like you expect `humanize` to output exact duration, with words inserted to make it more readable.

I think the purpose of `humanize` is something else: it's to _approximate_ the duration in human-friendly terms.  (If it helps, try adding 'about' or 'roughly' into the output: "about a year", "about 2 years" etc.)

**Comment by OriginalArye** [comment]
I think it should be exact.
When I checked version 2.2.1. It works fine.
Something has changed and I think it's a bug.

See: [http://jsfiddle.net/fz2wrLpk/](http://jsfiddle.net/fz2wrLpk/)


Same problem with days: _(even version 2.2.1)_
```js
moment.duration(25, "days").humanize() // 25 days
moment.duration(26, "days").humanize() // a month. Should be 26 days
```

**Comment by SneakyFish5** [comment]
This might be a bit late but I think you can use [Relative Time Thresholds](https://github.com/moment/momentjs.com/blob/master/docs/moment/07-customization/13-relative-time-threshold.md) to achieve what you are trying to ask.
