### ISSUE TITLE
With your time zone set to Brazil, moment('2020-11-01').endOf('month') returns '2020-12-01'

### ISSUE THREAD

**Issue by itai-katz** [moment/moment#4727]
**Description of the Issue and Steps to Reproduce:**
Switch your computer timezone to be Brazil
run console.log( moment('2020-11-01').endOf('month').format('YYYY-MM-DD'))
you will receive '2020-12-01' instead of '2020-11-30'

**Other information that may be helpful:**
Brazil Daylight saving time ends in November 1st 2020, my guess is this is the root cause.
https://www.timeanddate.com/time/zone/brazil/sao-paulo

* The time zone setting of the machine the code is running on
Brazil GMT-3
* The time and date at which the code was run
2018-08-01 6:50 PM
* Other libraries in use (TypeScript, Immutable.js, etc)
verified with fiddle js and just moment.js latest version

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
with timezone set to GMT-3 Brazil
console.log( moment('2020-11-01').endOf('month').format('YYYY-MM-DD'))
'2020-12-01'

with timezone set to EDT US east coast
console.log( moment('2020-11-01').endOf('month').format('YYYY-MM-DD'))
'2020-11-30'
```

**Comment by ashsearle** [comment]
Probably related to  #3132,, which should be fixed by PR #4338 (been waiting for this to be merged for a while.)

**Comment by moacir-selinger** [comment]
Nice! :) 👍

**Comment by marwahaha** [comment]
In 2.24.0:
```
fmt = d => console.log(d.format() + " " + d.tz())
fmt(moment.tz('2020-11-01', 'America/New_York').endOf('month'))  // 2020-11-30T23:59:59-05:00 America/New_York
fmt(moment.tz('2020-11-01', 'America/Sao_Paulo').endOf('month')) // 2020-11-30T23:59:59-02:00 America/Sao_Paulo
```

Please re-open if you still have issues.
