### ISSUE TITLE
Incorrect daysInMonth() using MM template

### ISSUE THREAD

**Issue by lisunandrey** [moment/moment#4728]
```js
moment("02", "MM").daysInMonth() // 28
```
Expected 29 as max available days count in February, but returns 28

**Comment by ashsearle** [comment]
You didn't provide any other date information, so moment assumes you mean this year.

This is not a leap year.  February has 28 days.

**Comment by lisunandrey** [comment]
I can understand that, but i have sign up form with date of birth input field with format: mm/dd/yyyy
Year will be last parameter. So, user can't write feb-29 if it is not a leap year.
I think function daysInMonth() should be configurable and more flexible.

**Comment by marwahaha** [comment]
I think there are ways to accomplish what you are looking for with Moment.

```
moment("02-2016", "MM-YYYY").daysInMonth() // 29
```

`.daysInMonth` works off the current object, which if the year isn't specified, is (generally) built the current year. So instead, build it with a leap year!


Let us know if you have other troubles.
