### ISSUE TITLE
Validation quirks with dates including 'localhost' substring

### ISSUE THREAD

**Issue by tarsusi** [moment/moment#4730]
This is also same problem(or it's a feature) for javascript Date object.

While validating data as date object or a string, I use moment(data).isValid() function. Then I realized that for above samples input, isValid function returns **true**.

moment('localhost:1').isValid()  --> **true**
moment('localhost.1').isValid()  --> **true**
moment('localhost!1').isValid()  --> **true**
moment('localhost?1').isValid()  --> **true**
moment('localhost=1').isValid()  --> **true**
moment('localhost:1').isValid()  --> **true**
moment('localhost 1').isValid()  --> **true**
moment('localhost1').isValid()  --> **false**

Also, there is a gap between some values after coming 'localhost:' substring

moment('localhost:12').isValid()  --> **true**
moment('localhost:13').isValid()  --> **false**
moment('localhost:14').isValid()  --> **false**
                                *
                                *
                                *
moment('localhost:30').isValid()  --> **false**
moment('localhost:31').isValid()  --> **false**
moment('localhost:32').isValid()  --> **true**

Why moment and javascript Date object accept some string values starting with 'localhost' substring? And why the range from 13 to 31 is an exception for this behaviour?

Issue found on Chrome browser. On Safari and Firefox the issue is not reproduced.

**Comment by ashsearle** [comment]
Do you see a warning in Chrome developer tools?

> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

You haven't told moment a format to parse the string with, so it tries a few common formats (ASP, ISO and RFC2822.)  If the string doesn't match those formats, it outputs the deprecation warning and passes the string directly to `new Date(str)`

As your string doesn't match any date format from the JavaScript spec, browsers fall back to [implementation-specific heuristics](https://tc39.github.io/ecma262/#sec-date.parse)

To avoid this, use strict parsing and a format string.  i.e. `moment(input, format, true)`

**Comment by marwahaha** [comment]
Agreed. Thanks Ash
