### ISSUE TITLE
how pull new locale? UA locale 

### ISSUE THREAD

**Issue by VaskaDagamas** [moment/moment#4733]
I wrote ua locale but lazy setup git for create push request, from UI can't do it, may somebody push this file
[link for locale ](https://drive.google.com/open?id=1KR4Ja2BREsInOQwZFYH1nyTRWWxECVhz)

**Comment by teekirol** [comment]
Duplicat of https://github.com/moment/moment/issues/4734

**Comment by marwahaha** [comment]
closed as duplicate
