### ISSUE TITLE
how push new locale? UA locale 

### ISSUE THREAD

**Issue by VaskaDagamas** [moment/moment#4734]
I wrote ua locale but lazy to setup git for create push request, from UI I can't do it, may somebody push this file
[link for locale ](https://drive.google.com/open?id=1KR4Ja2BREsInOQwZFYH1nyTRWWxECVhz)

**Comment by SneakyFish5** [comment]
I guess I can try and make a pull request for you sure. If there are changes to be made you'll just have to talk to reviewer and stuff and I can make changes.

**Comment by SneakyFish5** [comment]
What language is this for though?

**Comment by VaskaDagamas** [comment]
@SneakyFish5 Ukrainian

**Comment by SneakyFish5** [comment]
Hey seems that Ukrainian has already been done. See: https://github.com/moment/moment/blob/develop/src/locale/uk.js

**Comment by VaskaDagamas** [comment]
@SneakyFish5  okey. I did not guess uk is Ukraine language
https://www.google.com.ua/search?q=uk+language&oq=uk+language&aqs=chrome..69i57j0l5.4399j0j4&sourceid=chrome&ie=UTF-8

https://www.google.com.ua/search?ei=CYqPW9rAKIqJmgW-9ZDYAQ&q=ua+language&oq=ua+language&gs_l=psy-ab.3..0i7i30k1l10.27329.27329.0.28356.1.1.0.0.0.0.110.110.0j1.1.0....0...1c.1.64.psy-ab..0.1.110....0.jzOsvTJbm04
