### ISSUE TITLE
Cannot parse spanish date to moment object without providing format

### ISSUE THREAD

**Issue by mustafasadikot** [moment/moment#4738]
I have an angular 5 project where I convert date to moment object as below:

    moment(date).add(1, 'd').toDate()

For the spanish locale, date string is `'31/7/2018'`. In this case `moment(date)` gives me `Invalid da`. I looked into the moment instance and the locale is correctly set to `es`. I am using below code to load the locale data in moment

    import * as moment from 'moment';
    import 'moment/locale/es'
    
    moment.locale(languageWithRegion);

In `.angular-cli.json`

    "scripts": [
            "../node_modules/jquery/dist/jquery.min.js",
            "../node_modules/bootstrap/dist/js/bootstrap.min.js",
            "../node_modules/moment/min/moment.min.js",
            "../node_modules/moment/locale/es.js",
    ]
The version of moment is `2.22.1`.

Ideally, I should not provide the format while parsing the date string. The date string for current locale should be default identified like you do for ISO formats.

**Comment by marwahaha** [comment]
> For consistent results parsing anything other than ISO 8601 strings, you should use String + Format.

http://momentjs.com/docs/#/parsing/string/

You can use the format `L`
```
moment('31/7/2018', 'L').toDate()
Tue Jul 31 2018 00:00:00 GMT-0700 (Pacific Daylight Time)
```

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
