### ISSUE TITLE
why moment.forma 00:00:00 return 12:00:00

### ISSUE THREAD

**Issue by qiuyaofan** [moment/moment#4747]
console.info(moment('2018-08-23 00:00:00').format('YYYY-MM-DD hh:mm:ss'))

=>2018-08-23 12:00:00
it's a bug?

use in mac chrome 68.0.3440.106

```js
console.log( (moment('2018-08-23 00:00:00').format('YYYY-MM-DD hh:mm:ss')
```

**Comment by ashsearle** [comment]
Because you're using `hh` when you should be using `HH`.

See the [table of format tokens](https://momentjs.com/docs/#/displaying/format/) in the docs.

**Comment by qiuyaofan** [comment]
thank you.my mistake. @ashsearle
