### ISSUE TITLE
Moment Timezone has no data for Asia/Famagusta. See http://momentjs.com/timezone/docs/#/data-loading/.

### ISSUE THREAD

**Issue by vatex** [moment/moment#4749]
Moment Timezone has no data for Asia/Famagusta. See http://momentjs.com/timezone/docs/#/data-loading/.

**Comment by ashsearle** [comment]
@vatex This is the wrong repo to raise this issue.   I see you've also raised this in the right repo: moment/moment-timezone#667

You can close this issue.
