### ISSUE TITLE
moment.toJSON() loses timezone information.

### ISSUE THREAD

**Issue by nickmbailey** [moment/moment#4751]
**Description of the Issue and Steps to Reproduce:**

The toJSON function for moment objects removes any timezone information from the object when formatting it. This means that moment objects can't easily be serialized to JSON while maintaining timezones.

```
var m = require('moment')
var time = m.parseZone("2018-09-10T19:18:00.000-07:00")
console.log(time.format())
// 2018-09-10T19:18:00-07:00
console.log(time.toJSON())
// 2018-09-11T02:18:00.000Z
console.log(JSON.stringify(time))
// "2018-09-11T02:18:00.000Z"
```

**Comment by nickmbailey** [comment]
Currently working around this by overriding the toJSON function for all moment objects to simply call moment.format(). It seems like simply calling format() in the toJSON function might be the right solution. Although I'm not sure what the concerns around backwards compatibility are.

**Comment by ashsearle** [comment]
moment's implementation matches [Date.prototype.toJSON](https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.5.44).  I think that's probably the right thing to do.

You wouldn't really be preserving the 'timezone' using `-07:00` notation; you'd just be preserving an offset.

I guess it depends on your use-case, but you can easily override the default implementation with:

```js
moment.fn.toJSON = function() {
  return this.toISOString(true);
};
```

**Comment by nickmbailey** [comment]
Fair enough on zone vs offset.

We are ok with overriding in this case but the inability to easily preserve offset information when serializing dates (moment or built in) seems like a potential pitfall for users. I certainly spent a few hours figuring it out. Perhaps solveable with documentation.

**Comment by marwahaha** [comment]
@nickmbailey It's already in the documentation.
Please re-open if you still have issues.
https://momentjs.com/docs/#/displaying/as-json/
https://github.com/moment/momentjs.com/commit/11cacb26fef084e42490f06a2686c9f1fbe89a44
