### ISSUE TITLE
2013-03-10T00:00:00.000Z + 1 day != 2013-03-10T23:00:00.000Z

### ISSUE THREAD

**Issue by createthis** [moment/moment#4754]
**Description of the Issue and Steps to Reproduce:**

Maybe I'm missing something, but I think this is a bug:

```js
import moment from 'moment';
let date = new Date('2013-03-10 00:00:00 UTC');
let next = moment(date).add(1, 'days').toDate();
console.log("date=",date,"next=",next);
```

## Output:

```
date= 2013-03-10T00:00:00.000Z next= 2013-03-10T23:00:00.000Z
```

## Expected Output:

```
date= 2013-03-10T00:00:00.000Z next= 2013-03-11T00:00:00.000Z
```

## Hypothesis:

This may be related to daylight savings time. the UTC version behaves as expected:

```js
let next = moment(date).utc().add(1, 'days').toDate();
```

**Environment:**

```
$ node -v
v8.6.0
```

**Comment by ashsearle** [comment]
It's not a bug.

I'm guessing you're in the US(?) - where DST change started at 2AM on March 10th 2013, moving clocks forward by an hour and therefore meaning that March 10th was only 23 hours long.

**Comment by createthis** [comment]
@ashsearle I hear what you are saying. However, I still firmly believe this is a bug.

This is a UTC date, as denoted by the Z on the end. When operating on a UTC date I expect UTC results. I can't think of a reason why I would ever expect `.add(1, 'day')` to only add 23 hours to a UTC date.

This is a fringe case, but the expected results don't match the actual results.

**Comment by ashsearle** [comment]
They're not "UTC dates', they're just dates, representing a point in time.

I believe the output of `console.log` shows Z on the end because you're running your code in node(?) which uses `toJSON()` instead of `toString()`.

**Comment by createthis** [comment]
Ah. Node is lying to me. Ok, thank you and sorry for the noise.
