### ISSUE TITLE
[IE11] [Polyserve] circular dependency issue throwing 'Object expected' in IE

### ISSUE THREAD

**Issue by TremayneChrist** [moment/moment#4756]
I have an issue with moment when using Polymer's CLI to serve the files in IE11. When `src/lib/units/year.js` is compiled it becomes broken, with certain objects being undefined.

Looking through the code it seems `src/lib/units/year.js` (YEAR) imports a function from `src/lib/moment/get-set.js` (GET-SET) and GET-SET imports a function from YEAR. This is fine, however, one of the exports from YEAR is returning a function reference from GET-SET which seems to be the issue.

This is the line in question:

https://github.com/moment/moment/blob/2e2a5b35439665d4b0200143d808a7c26d6cd30f/src/lib/units/year.js#L71

Returning its own function fixes the issue. For example:
```js
export var getSetYear = function () {
    return makeGetSet('FullYear', true).apply(this, arguments);
}
```

**Comment by igomezal** [comment]
You could try to use the version 2.18.1 meanwhile it is fixed
