### ISSUE TITLE
locale [lt] humanize() / fromNow() using plural vs singular words

### ISSUE THREAD

**Issue by mantaspet** [moment/moment#4757]
When using LT locale, numbers 21, 31, 41 etc. (with 1 at the end, except 1 and 11) show an incorrect case when calling humanize() or fromNow() methods.

`moment.duration(21, 'minutes').humanize()` returns '21 minutės'. It should be '21 minutė'.
`moment().add(21, 'minutes').fromNow()` returns 'po 21 minučių'. It should be 'po 21 minutės'.

`moment.duration(21, 'hours').humanize()`: returns '21 valandos'. It should be '21 valanda'.
`moment().add(21, 'hours').fromNow()`: returns 'po 21 valandų'. It should be 'po 21 valandos'.

`moment.duration(21, 'days').humanize()`: returns '21 dienos'. It should be '21 diena'.
`moment().add(21, 'days').fromNow()`: returns 'po 21 dienų'. It should be 'po 21 dienos'.

Other units get rounded and return correct result, years work fine so I can't provide code lines. But considering the output would follow the same pattern, those should look like this:

21 seconds: '21 sekundės' -> '21 sekundė'
31 weeks: '31 savaitės' -> '31 savaitė'
41 months: '41 mėnesiai' -> '41 mėnuo'
51 months: '51 mėnesiai' -> '51 mėnuo'
51 years: '51 metai' is correct. Don't ask, our language is weird.

**Comment by mmozuras** [comment]
@marwahaha sorry for only taking a look at it. @mantaspet is correct, our language is weird. His suggestions are good.

**Comment by marwahaha** [comment]
This is a similar issue to https://github.com/moment/moment/issues/5170

**Comment by marwahaha** [comment]
I don't think we will implement something like this.
https://momentjs.com/docs/#/-project-status/
