### ISSUE TITLE
Why does this comparing fail?

### ISSUE THREAD

**Issue by chobo2** [moment/moment#4758]
```
const utcNow = moment.utc(); // example the time would be 19:08:33 same date.
      const expirationDate = moment.utc("2018-08-30T19:25:14Z").minute(-1);
      const expired = utcNow.isSameOrAfter(expirationDate);

```
but for some reason expired is true.

Is 19:08 not before 19:25?

When I look at moment.utc() I see it in my local timezone(Thu Aug 30 2018 12:05:19 GMT-0700 (Pacific Daylight Time) {}) not utc time. Not sure why.

**Comment by ashsearle** [comment]
Using `minute(-1)` is not the same as `subtract(1, 'minute')`

By using `minus(-1)` you basically set `expirationDate` to 18:59, not 19:24 as you might have expected.

**Comment by marwahaha** [comment]
Ash is right. Let us know if you still have issues.
