### ISSUE TITLE
add(0.625,'days') not work 

### ISSUE THREAD

**Issue by pdap** [moment/moment#4759]
**Description of the Issue and Steps to Reproduce:**

*Please include the values of all variables used.*

**Environment:**

*Examples: Chrome 68 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
Fri Aug 31 2018 10:08:04 GMT+0800 (中国标准时间)
2018/8/31 上午10:08:04
-480
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
2.22.2

moment("2018-8-31 09:00:00").add(0.625,'days')._d 
get 'Sat Sep 01 2018 09:00:00 GMT+0800'
expect 'Sat Sep 01 2018 00:00:00 GMT+0800 (CST)'
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by ashsearle** [comment]
I think it's [documented behaviour](https://momentjs.com/docs/#special-considerations-for-months-and-years):

> As of 2.12.0 when decimal values are passed for days and months, they are rounded to the nearest integer. Weeks, quarters, and years are converted to days or months, and then rounded to the nearest integer

**Comment by marwahaha** [comment]
That is correct. Let us know if you still have issues.
