### ISSUE TITLE
Incorrect date returned when passing array

### ISSUE THREAD

**Issue by cgsmith** [moment/moment#4761]
**Description of the Issue and Steps to Reproduce:**
When passing an array moment returns the incorrect month.

```
// Expected 'Jan 01, 2000'
// Returned 'Feb 01, 2000'
var now = moment([2000,1,1]).format('MMM DD, YYYY');
```
http://jsfiddle.net/rLjQx/130311/

*Please include the values of all variables used.*
They are all included in above example.

**Environment:**
Windows 10, Chrome and on JSFiddle

**Other information that may be helpful:**
* America/Chicago
* Sept 1, 2018 2:27PM CST

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

Sat Sep 01 2018 14:28:23 GMT-0500 (Central Daylight Time)
9/1/2018, 2:28:23 PM
300
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
```

**Comment by ashsearle** [comment]
Working as [documented](https://momentjs.com/docs/#/parsing/array/):

> Note: Because this mirrors the native Date parameters, **months**, hours, minutes, seconds, and milliseconds are all **zero indexed**. Years and days of the month are 1 indexed.
>
> This is often the cause of frustration, especially with months, so take note!
