### ISSUE TITLE
format is not a function, when used on variable defined as var a = moment()

### ISSUE THREAD

**Issue by frenzy81** [moment/moment#4767]
I'm seeing strange behaviors when trying to use the format function on a variable created by using var periodEndDate = moment(), and only get the error message "TypeError: periodEndDate.format is not a function".

moment().format() works, but periodEndDate.format() does not work. See attached screenshot!

Anyone know what might be going on?

*Variables:*
var periodEndDate = moment();
var periodEndDateString = periodEndDate.format();

**Environment:**

Chrome 69.0.3497.81 on Windows Server 2012 R2
Chrome 69.0.3497.81 on Windows 10 1803

**Other information that may be helpful:**
* Tested with:
   - language English (United States), location United States
   - language Norwegian, Bokmål, location Norway
* The time and date at which the code was run: 6 Sept 2018 10:45:00 (TimeZone, Europe/Oslo)

**Test:**
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

**Test Output:**
Thu Sep 06 2018 10:48:47 GMT+0200 (sentraleuropeisk sommertid)
6.9.2018, 10:48:47
-120
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
2.22.2

![momentjs error](https://user-images.githubusercontent.com/23652123/45146946-2529c180-b1c4-11e8-8869-f2c5ad77bf59.jpg)

**Comment by ashsearle** [comment]
How are you importing moment?

Has some of your code overwritten the `format` property?

What's the value of: `moment.fn.format` and `moment().format`?

**Comment by frenzy81** [comment]
I'm creating add-ins for a visualisation tool (OSIsoft PI Vision), and they have an extensibility model where javascript files and libraries are loaded if placed in specific folders.

When I load the web page, moment is loaded with:
<script src="/PIVision/Scripts/app/editor/symbols/ext/libraries/moment.js"></script>

There are also other libraries and js files loaded, quite a lot of them actually. But most importantly modernizr, jquery, hammer, angular, jsTimezoneDetect and kendo are imported as part of the product framework. 


When I enter what you asked for in the debug console I get this:

![image](https://user-images.githubusercontent.com/23652123/45151251-16e0a300-b1ce-11e8-868c-01d2c8c4e222.png)


If you think something interacts with the definition of format I can try creating a simple html file to test only the moment implementation, directly off the IIS server.

**Comment by frenzy81** [comment]
I did test a simple html to test this, and this (of course) worked. Seems I have to go bother OSIsoft on their product instead. Thanks for you help!

```
<!DOCTYPE html>
<html>
<head>
  <title>Moment test</title>
  <script src="moment.js"></script>
</head>
<body>
  <div id="button">
    <button type="button" onclick="var a = moment(); document.getElementById('output').innerHTML = a.format('YYYY.MM.DD')">Try it</button>
  </div>
  <div id="output">
	Placeholder
  </div>
</body>
</html>
```
