### ISSUE TITLE
Feature request: Method for returning time zone offset in milliseconds

### ISSUE THREAD

**Issue by cdmahoney** [moment/moment#4770]
Moment's utcOffset method returns the timezone offset in minutes. However, in some cases the time zone offset may not be an integral number of minutes - for example, in Chrome 68 for timezone Europe/Madrid dates before 1901-01-01 have an offset of -14 minutes 44 seconds - utcOffset returns -15, Javascript's getTimezoneOffset returns 14:.

```js
momentjs("1900-12-31 23:45:15").utcOffset() // -15
momentjs("1900-12-31 23:45:16").utcOffset() // -0

new Date("1900-12-31 23:45:15").getTimezoneOffset() // 14
new Date("1900-12-31 23:45:16").getTimezoneOffset() // 0
```

As Chrome stores the dates internally with the correct offset, doing arithmetic using the rounded offsets can lead to errors (for example, sheetjs generates Excel date/times with a 44 second error using getTimezoneOffset)

Could a "utcOffsetMS" method be added to return the correct offset in milliseconds (seconds would do, but that would be one more returned unit to remember...)

Tested with Chrome 68, tz Madrid/Europe on Windows 7.

**Comment by ashsearle** [comment]
moment's `utcOffset` method rounds off the offset to the nearest 15 minutes (to cater for an old bug in Firefox.)

Chrome's the only browser (so far) to implement sub-minute timezone offsets, and AFAICT doesn't provide  access to read the offset from a `Date.prototype` method.

It might be a bit premature to add a method to support this, given it's only useful in one browser.

However, if you really need this, you could add your own implementation using the `moment.fn` extension point:

```js
moment.fn.utcOffsetMS = function() {
  return this._isUTC
    ? (this._offset || 0) * 1000 * 60
    : moment.utc(this.toArray()) - this;
};
```

**Comment by cdmahoney** [comment]
Agreed that it might be premature to implement at the moment. However, although it will only affect a few users at the moment, those it does affect are likely to have a hard time detecting the problem (I'm lucky to be working in Spain and have some knowledge of the timezone database, otherwise tracking down the problem would have been much more difficult.) A point in favor of adding a method would be that it would act as a heads up, showing users that there might be a problem in some cases. But I'm sure you guys know best, and no doubt have to be vigilant to prevent everything but the kitchen sink being added to the API! 

Thanks for the fix - I had implemented something similar to solve the problem and con confirm it does the trick.

**Comment by marwahaha** [comment]
This is a great exchange. I'm going to close for now. If historical timezone offsets become more popular, we can reconsider this.
