### ISSUE TITLE
Date validation

### ISSUE THREAD

**Issue by SergeyShablenko** [moment/moment#4772]
**Description of the Issue and Steps to Reproduce:**

I`m trying to display different validation messages while user types a date string
moment validates strings perfectly, the question is how to validate format and logicaly incorrect dates separately?

I mean, I want to show "Invalid format" if string has invalid format (supporting strict parsing as in isValid method) and show "Invalid date" if string has valid format but not existing date (e.g. 31.09.2018)

```js
moment("31.09.2018", "DD.MM.YYYY").isValidFormat() // true
moment("31.09", "DD.MM.YYYY").isValidFormat() // true
moment("31.09", "DD.MM.YYYY").isValidFormat(true) // false
moment("31.09.2018", "DD.MM.YYYY").isValidDate() // false
moment("20.09.2018", "DD.MM.YYYY").isValidDate() // true
moment("20.09", "DD.MM.YYYY").isValidDate(true) // false
```

**Comment by ashsearle** [comment]
The docs have a [section on validation](https://momentjs.com/docs/#/parsing/is-valid/) describing the object returned by `parsingFlags()`, which you can use to check how moment parsed the input.

**Comment by SergeyShablenko** [comment]
Is there normal documentation to invalid util?
How to use it on some dates?
