### ISSUE TITLE
162 tests failed.

### ISSUE THREAD

**Issue by Glennmen** [moment/moment#4773]
### Client info
```
Date String   : Tue Sep 11 2018 11:35:52 GMT+0200 (Central European Summer Time)
Locale String : 11/09/2018, 11:35:52
Offset        : -120
User Agent    : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
Moment Version: 2.22.2
```

====

### locale:ka:month parsing correctness (1343.2) 

month 0 fmt MMM upper

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:month parsing correctness (1343.5) 

month 0 fmt MMM upper strict

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:month parsing correctness (1343.8) 

month 0 fmt MMM. upper

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:month parsing correctness (1343.11) 

month 0 fmt MMM. upper strict

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:month parsing correctness (1343.14) 

month 0 fmt MMMM upper

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:month parsing correctness (1343.17) 

month 0 fmt MMMM upper strict

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:month parsing correctness (1343.20) 

month 0 fmt MMMM. upper

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:month parsing correctness (1343.23) 

month 0 fmt MMMM. upper strict

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:month parsing correctness (1343.26) 

month 1 fmt MMM upper

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:month parsing correctness (1343.29) 

month 1 fmt MMM upper strict

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:month parsing correctness (1343.32) 

month 1 fmt MMM. upper

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:month parsing correctness (1343.35) 

month 1 fmt MMM. upper strict

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:month parsing correctness (1343.38) 

month 1 fmt MMMM upper

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:month parsing correctness (1343.41) 

month 1 fmt MMMM upper strict

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:month parsing correctness (1343.44) 

month 1 fmt MMMM. upper

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:month parsing correctness (1343.47) 

month 1 fmt MMMM. upper strict

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:month parsing correctness (1343.50) 

month 2 fmt MMM upper

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:month parsing correctness (1343.53) 

month 2 fmt MMM upper strict

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:month parsing correctness (1343.56) 

month 2 fmt MMM. upper

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:month parsing correctness (1343.59) 

month 2 fmt MMM. upper strict

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:month parsing correctness (1343.62) 

month 2 fmt MMMM upper

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:month parsing correctness (1343.65) 

month 2 fmt MMMM upper strict

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:month parsing correctness (1343.68) 

month 2 fmt MMMM. upper

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:month parsing correctness (1343.71) 

month 2 fmt MMMM. upper strict

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:month parsing correctness (1343.74) 

month 3 fmt MMM upper

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:month parsing correctness (1343.77) 

month 3 fmt MMM upper strict

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:month parsing correctness (1343.80) 

month 3 fmt MMM. upper

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:month parsing correctness (1343.83) 

month 3 fmt MMM. upper strict

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:month parsing correctness (1343.86) 

month 3 fmt MMMM upper

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:month parsing correctness (1343.89) 

month 3 fmt MMMM upper strict

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:month parsing correctness (1343.92) 

month 3 fmt MMMM. upper

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:month parsing correctness (1343.95) 

month 3 fmt MMMM. upper strict

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:month parsing correctness (1343.98) 

month 4 fmt MMM upper

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:month parsing correctness (1343.101) 

month 4 fmt MMM upper strict

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:month parsing correctness (1343.104) 

month 4 fmt MMM. upper

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:month parsing correctness (1343.107) 

month 4 fmt MMM. upper strict

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:month parsing correctness (1343.110) 

month 4 fmt MMMM upper

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:month parsing correctness (1343.113) 

month 4 fmt MMMM upper strict

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:month parsing correctness (1343.116) 

month 4 fmt MMMM. upper

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:month parsing correctness (1343.119) 

month 4 fmt MMMM. upper strict

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:month parsing correctness (1343.122) 

month 5 fmt MMM upper

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:month parsing correctness (1343.125) 

month 5 fmt MMM upper strict

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:month parsing correctness (1343.128) 

month 5 fmt MMM. upper

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:month parsing correctness (1343.131) 

month 5 fmt MMM. upper strict

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:month parsing correctness (1343.134) 

month 5 fmt MMMM upper

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:month parsing correctness (1343.137) 

month 5 fmt MMMM upper strict

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:month parsing correctness (1343.140) 

month 5 fmt MMMM. upper

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:month parsing correctness (1343.143) 

month 5 fmt MMMM. upper strict

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:month parsing correctness (1343.146) 

month 6 fmt MMM upper

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:month parsing correctness (1343.149) 

month 6 fmt MMM upper strict

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:month parsing correctness (1343.152) 

month 6 fmt MMM. upper

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:month parsing correctness (1343.155) 

month 6 fmt MMM. upper strict

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:month parsing correctness (1343.158) 

month 6 fmt MMMM upper

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:month parsing correctness (1343.161) 

month 6 fmt MMMM upper strict

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:month parsing correctness (1343.164) 

month 6 fmt MMMM. upper

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:month parsing correctness (1343.167) 

month 6 fmt MMMM. upper strict

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:month parsing correctness (1343.170) 

month 7 fmt MMM upper

```javascript
// Expected 7
// Actual   NaN
NaN === 7
```

====

### locale:ka:month parsing correctness (1343.173) 

month 7 fmt MMM upper strict

```javascript
// Expected 7
// Actual   NaN
NaN === 7
```

====

### locale:ka:month parsing correctness (1343.176) 

month 7 fmt MMM. upper

```javascript
// Expected 7
// Actual   NaN
NaN === 7
```

====

### locale:ka:month parsing correctness (1343.179) 

month 7 fmt MMM. upper strict

```javascript
// Expected 7
// Actual   NaN
NaN === 7
```

====

### locale:ka:month parsing correctness (1343.182) 

month 7 fmt MMMM upper

```javascript
// Expected 7
// Actual   NaN
NaN === 7
```

====

### locale:ka:month parsing correctness (1343.185) 

month 7 fmt MMMM upper strict

```javascript
// Expected 7
// Actual   NaN
NaN === 7
```

====

### locale:ka:month parsing correctness (1343.188) 

month 7 fmt MMMM. upper

```javascript
// Expected 7
// Actual   NaN
NaN === 7
```

====

### locale:ka:month parsing correctness (1343.191) 

month 7 fmt MMMM. upper strict

```javascript
// Expected 7
// Actual   NaN
NaN === 7
```

====

### locale:ka:month parsing correctness (1343.194) 

month 8 fmt MMM upper

```javascript
// Expected 8
// Actual   NaN
NaN === 8
```

====

### locale:ka:month parsing correctness (1343.197) 

month 8 fmt MMM upper strict

```javascript
// Expected 8
// Actual   NaN
NaN === 8
```

====

### locale:ka:month parsing correctness (1343.200) 

month 8 fmt MMM. upper

```javascript
// Expected 8
// Actual   NaN
NaN === 8
```

====

### locale:ka:month parsing correctness (1343.203) 

month 8 fmt MMM. upper strict

```javascript
// Expected 8
// Actual   NaN
NaN === 8
```

====

### locale:ka:month parsing correctness (1343.206) 

month 8 fmt MMMM upper

```javascript
// Expected 8
// Actual   NaN
NaN === 8
```

====

### locale:ka:month parsing correctness (1343.209) 

month 8 fmt MMMM upper strict

```javascript
// Expected 8
// Actual   NaN
NaN === 8
```

====

### locale:ka:month parsing correctness (1343.212) 

month 8 fmt MMMM. upper

```javascript
// Expected 8
// Actual   NaN
NaN === 8
```

====

### locale:ka:month parsing correctness (1343.215) 

month 8 fmt MMMM. upper strict

```javascript
// Expected 8
// Actual   NaN
NaN === 8
```

====

### locale:ka:month parsing correctness (1343.218) 

month 9 fmt MMM upper

```javascript
// Expected 9
// Actual   NaN
NaN === 9
```

====

### locale:ka:month parsing correctness (1343.221) 

month 9 fmt MMM upper strict

```javascript
// Expected 9
// Actual   NaN
NaN === 9
```

====

### locale:ka:month parsing correctness (1343.224) 

month 9 fmt MMM. upper

```javascript
// Expected 9
// Actual   NaN
NaN === 9
```

====

### locale:ka:month parsing correctness (1343.227) 

month 9 fmt MMM. upper strict

```javascript
// Expected 9
// Actual   NaN
NaN === 9
```

====

### locale:ka:month parsing correctness (1343.230) 

month 9 fmt MMMM upper

```javascript
// Expected 9
// Actual   NaN
NaN === 9
```

====

### locale:ka:month parsing correctness (1343.233) 

month 9 fmt MMMM upper strict

```javascript
// Expected 9
// Actual   NaN
NaN === 9
```

====

### locale:ka:month parsing correctness (1343.236) 

month 9 fmt MMMM. upper

```javascript
// Expected 9
// Actual   NaN
NaN === 9
```

====

### locale:ka:month parsing correctness (1343.239) 

month 9 fmt MMMM. upper strict

```javascript
// Expected 9
// Actual   NaN
NaN === 9
```

====

### locale:ka:month parsing correctness (1343.242) 

month 10 fmt MMM upper

```javascript
// Expected 10
// Actual   NaN
NaN === 10
```

====

### locale:ka:month parsing correctness (1343.245) 

month 10 fmt MMM upper strict

```javascript
// Expected 10
// Actual   NaN
NaN === 10
```

====

### locale:ka:month parsing correctness (1343.248) 

month 10 fmt MMM. upper

```javascript
// Expected 10
// Actual   NaN
NaN === 10
```

====

### locale:ka:month parsing correctness (1343.251) 

month 10 fmt MMM. upper strict

```javascript
// Expected 10
// Actual   NaN
NaN === 10
```

====

### locale:ka:month parsing correctness (1343.254) 

month 10 fmt MMMM upper

```javascript
// Expected 10
// Actual   NaN
NaN === 10
```

====

### locale:ka:month parsing correctness (1343.257) 

month 10 fmt MMMM upper strict

```javascript
// Expected 10
// Actual   NaN
NaN === 10
```

====

### locale:ka:month parsing correctness (1343.260) 

month 10 fmt MMMM. upper

```javascript
// Expected 10
// Actual   NaN
NaN === 10
```

====

### locale:ka:month parsing correctness (1343.263) 

month 10 fmt MMMM. upper strict

```javascript
// Expected 10
// Actual   NaN
NaN === 10
```

====

### locale:ka:month parsing correctness (1343.266) 

month 11 fmt MMM upper

```javascript
// Expected 11
// Actual   NaN
NaN === 11
```

====

### locale:ka:month parsing correctness (1343.269) 

month 11 fmt MMM upper strict

```javascript
// Expected 11
// Actual   NaN
NaN === 11
```

====

### locale:ka:month parsing correctness (1343.272) 

month 11 fmt MMM. upper

```javascript
// Expected 11
// Actual   NaN
NaN === 11
```

====

### locale:ka:month parsing correctness (1343.275) 

month 11 fmt MMM. upper strict

```javascript
// Expected 11
// Actual   NaN
NaN === 11
```

====

### locale:ka:month parsing correctness (1343.278) 

month 11 fmt MMMM upper

```javascript
// Expected 11
// Actual   NaN
NaN === 11
```

====

### locale:ka:month parsing correctness (1343.281) 

month 11 fmt MMMM upper strict

```javascript
// Expected 11
// Actual   NaN
NaN === 11
```

====

### locale:ka:month parsing correctness (1343.284) 

month 11 fmt MMMM. upper

```javascript
// Expected 11
// Actual   NaN
NaN === 11
```

====

### locale:ka:month parsing correctness (1343.287) 

month 11 fmt MMMM. upper strict

```javascript
// Expected 11
// Actual   NaN
NaN === 11
```

====

### locale:ka:weekday parsing correctness (1344.2) 

weekday 3 fmt dd 2015-01-01T18:00:00.000Z upper

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:weekday parsing correctness (1344.5) 

weekday 3 fmt dd 2015-01-01T18:00:00.000Z upper strict

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:weekday parsing correctness (1344.8) 

weekday 3 fmt ddd 2015-01-01T18:00:00.000Z upper

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:weekday parsing correctness (1344.11) 

weekday 3 fmt ddd 2015-01-01T18:00:00.000Z upper strict

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:weekday parsing correctness (1344.14) 

weekday 3 fmt dddd 2015-01-01T18:00:00.000Z upper

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:weekday parsing correctness (1344.17) 

weekday 3 fmt dddd 2015-01-01T18:00:00.000Z upper strict

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:weekday parsing correctness (1344.20) 

weekday 4 fmt dd 2015-01-02T18:00:00.000Z upper

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:weekday parsing correctness (1344.23) 

weekday 4 fmt dd 2015-01-02T18:00:00.000Z upper strict

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:weekday parsing correctness (1344.26) 

weekday 4 fmt ddd 2015-01-02T18:00:00.000Z upper

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:weekday parsing correctness (1344.29) 

weekday 4 fmt ddd 2015-01-02T18:00:00.000Z upper strict

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:weekday parsing correctness (1344.32) 

weekday 4 fmt dddd 2015-01-02T18:00:00.000Z upper

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:weekday parsing correctness (1344.35) 

weekday 4 fmt dddd 2015-01-02T18:00:00.000Z upper strict

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:weekday parsing correctness (1344.38) 

weekday 5 fmt dd 2015-01-03T18:00:00.000Z upper

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:weekday parsing correctness (1344.41) 

weekday 5 fmt dd 2015-01-03T18:00:00.000Z upper strict

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:weekday parsing correctness (1344.44) 

weekday 5 fmt ddd 2015-01-03T18:00:00.000Z upper

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:weekday parsing correctness (1344.47) 

weekday 5 fmt ddd 2015-01-03T18:00:00.000Z upper strict

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:weekday parsing correctness (1344.50) 

weekday 5 fmt dddd 2015-01-03T18:00:00.000Z upper

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:weekday parsing correctness (1344.53) 

weekday 5 fmt dddd 2015-01-03T18:00:00.000Z upper strict

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:weekday parsing correctness (1344.56) 

weekday 6 fmt dd 2015-01-04T18:00:00.000Z upper

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:weekday parsing correctness (1344.59) 

weekday 6 fmt dd 2015-01-04T18:00:00.000Z upper strict

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:weekday parsing correctness (1344.62) 

weekday 6 fmt ddd 2015-01-04T18:00:00.000Z upper

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:weekday parsing correctness (1344.65) 

weekday 6 fmt ddd 2015-01-04T18:00:00.000Z upper strict

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:weekday parsing correctness (1344.68) 

weekday 6 fmt dddd 2015-01-04T18:00:00.000Z upper

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:weekday parsing correctness (1344.71) 

weekday 6 fmt dddd 2015-01-04T18:00:00.000Z upper strict

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:weekday parsing correctness (1344.74) 

weekday 0 fmt dd 2015-01-05T18:00:00.000Z upper

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:weekday parsing correctness (1344.77) 

weekday 0 fmt dd 2015-01-05T18:00:00.000Z upper strict

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:weekday parsing correctness (1344.80) 

weekday 0 fmt ddd 2015-01-05T18:00:00.000Z upper

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:weekday parsing correctness (1344.83) 

weekday 0 fmt ddd 2015-01-05T18:00:00.000Z upper strict

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:weekday parsing correctness (1344.86) 

weekday 0 fmt dddd 2015-01-05T18:00:00.000Z upper

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:weekday parsing correctness (1344.89) 

weekday 0 fmt dddd 2015-01-05T18:00:00.000Z upper strict

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:weekday parsing correctness (1344.92) 

weekday 1 fmt dd 2015-01-06T18:00:00.000Z upper

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:weekday parsing correctness (1344.95) 

weekday 1 fmt dd 2015-01-06T18:00:00.000Z upper strict

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:weekday parsing correctness (1344.98) 

weekday 1 fmt ddd 2015-01-06T18:00:00.000Z upper

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:weekday parsing correctness (1344.101) 

weekday 1 fmt ddd 2015-01-06T18:00:00.000Z upper strict

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:weekday parsing correctness (1344.104) 

weekday 1 fmt dddd 2015-01-06T18:00:00.000Z upper

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:weekday parsing correctness (1344.107) 

weekday 1 fmt dddd 2015-01-06T18:00:00.000Z upper strict

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:weekday parsing correctness (1344.110) 

weekday 2 fmt dd 2015-01-07T18:00:00.000Z upper

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:weekday parsing correctness (1344.113) 

weekday 2 fmt dd 2015-01-07T18:00:00.000Z upper strict

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:weekday parsing correctness (1344.116) 

weekday 2 fmt ddd 2015-01-07T18:00:00.000Z upper

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:weekday parsing correctness (1344.119) 

weekday 2 fmt ddd 2015-01-07T18:00:00.000Z upper strict

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:weekday parsing correctness (1344.122) 

weekday 2 fmt dddd 2015-01-07T18:00:00.000Z upper

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:weekday parsing correctness (1344.125) 

weekday 2 fmt dddd 2015-01-07T18:00:00.000Z upper strict

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:parse (1346.7) 

ᲘᲐᲜᲕᲐᲠᲘ უნდა იყოს თვე 1

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:parse (1346.8) 

ᲘᲐᲜ უნდა იყოს თვე 1

```javascript
// Expected 0
// Actual   NaN
NaN === 0
```

====

### locale:ka:parse (1346.15) 

ᲗᲔᲑᲔᲠᲕᲐᲚᲘ უნდა იყოს თვე 2

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:parse (1346.16) 

ᲗᲔᲑ უნდა იყოს თვე 2

```javascript
// Expected 1
// Actual   NaN
NaN === 1
```

====

### locale:ka:parse (1346.23) 

ᲛᲐᲠᲢᲘ უნდა იყოს თვე 3

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:parse (1346.24) 

ᲛᲐᲠ უნდა იყოს თვე 3

```javascript
// Expected 2
// Actual   NaN
NaN === 2
```

====

### locale:ka:parse (1346.31) 

ᲐᲞᲠᲘᲚᲘ უნდა იყოს თვე 4

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:parse (1346.32) 

ᲐᲞᲠ უნდა იყოს თვე 4

```javascript
// Expected 3
// Actual   NaN
NaN === 3
```

====

### locale:ka:parse (1346.39) 

ᲛᲐᲘᲡᲘ უნდა იყოს თვე 5

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:parse (1346.40) 

ᲛᲐᲘ უნდა იყოს თვე 5

```javascript
// Expected 4
// Actual   NaN
NaN === 4
```

====

### locale:ka:parse (1346.47) 

ᲘᲕᲜᲘᲡᲘ უნდა იყოს თვე 6

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:parse (1346.48) 

ᲘᲕᲜ უნდა იყოს თვე 6

```javascript
// Expected 5
// Actual   NaN
NaN === 5
```

====

### locale:ka:parse (1346.55) 

ᲘᲕᲚᲘᲡᲘ უნდა იყოს თვე 7

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:parse (1346.56) 

ᲘᲕᲚ უნდა იყოს თვე 7

```javascript
// Expected 6
// Actual   NaN
NaN === 6
```

====

### locale:ka:parse (1346.63) 

ᲐᲒᲕᲘᲡᲢᲝ უნდა იყოს თვე 8

```javascript
// Expected 7
// Actual   NaN
NaN === 7
```

====

### locale:ka:parse (1346.64) 

ᲐᲒᲕ უნდა იყოს თვე 8

```javascript
// Expected 7
// Actual   NaN
NaN === 7
```

====

### locale:ka:parse (1346.71) 

ᲡᲔᲥᲢᲔᲛᲑᲔᲠᲘ უნდა იყოს თვე 9

```javascript
// Expected 8
// Actual   NaN
NaN === 8
```

====

### locale:ka:parse (1346.72) 

ᲡᲔᲥ უნდა იყოს თვე 9

```javascript
// Expected 8
// Actual   NaN
NaN === 8
```

====

### locale:ka:parse (1346.79) 

ᲝᲥᲢᲝᲛᲑᲔᲠᲘ უნდა იყოს თვე 10

```javascript
// Expected 9
// Actual   NaN
NaN === 9
```

====

### locale:ka:parse (1346.80) 

ᲝᲥᲢ უნდა იყოს თვე 10

```javascript
// Expected 9
// Actual   NaN
NaN === 9
```

====

### locale:ka:parse (1346.87) 

ᲜᲝᲔᲛᲑᲔᲠᲘ უნდა იყოს თვე 11

```javascript
// Expected 10
// Actual   NaN
NaN === 10
```

====

### locale:ka:parse (1346.88) 

ᲜᲝᲔ უნდა იყოს თვე 11

```javascript
// Expected 10
// Actual   NaN
NaN === 10
```

====

### locale:ka:parse (1346.95) 

ᲓᲔᲙᲔᲛᲑᲔᲠᲘ უნდა იყოს თვე 12

```javascript
// Expected 11
// Actual   NaN
NaN === 11
```

====

### locale:ka:parse (1346.96) 

ᲓᲔᲙ უნდა იყოს თვე 12

```javascript
// Expected 11
// Actual   NaN
NaN === 11
```

**Comment by Glennmen** [comment]
Not sure if this has been reported or not, I couldn't use the `STEP 1` and `STEP 2` buttons because I was getting a `414 Request-URI Too Large` error. But after searching myself I couldn't find a similar issue.

Also maybe a little tip, add a `copy content` button to the `Issue description` on the test page. It would make it a lot easier to copy the issue if you get the above error (select all got me the entire page selected and not only the content of the issue description.

**Comment by ashsearle** [comment]
This is the same issue as #4762
