### ISSUE TITLE
package-lock.json version doesn't match release version (but package.json does)

### ISSUE THREAD

**Issue by rhbecker** [moment/moment#4776]
Is it to be expected that the `version` value in `package-lock.json` for a given release does not match the version of that release?

I'm asking because `v2.22.2` has the correct version in `package.json`, but still lists `v2.22.0` in `package-lock.json`.

https://github.com/moment/moment/blob/2.22.2/package.json#L3
https://github.com/moment/moment/blob/2.22.2/package-lock.json#L3

**Comment by marwahaha** [comment]
Nice catch. I've commented about this on my release process here https://gist.github.com/marwahaha/44deb629e81fbf02c599074ffc8a9c46
