### ISSUE TITLE
datetime is parsed irrespective of the given format

### ISSUE THREAD

**Issue by akakoori** [moment/moment#4777]
**Description of the Issue and Steps to Reproduce:**

this gives a weird result `0004-08-30T15:00:00+08:00`
```javascript
moment.locale('zh-cn');
moment.tz.setDefault('Asia/Shanghai');
moment(`4、公告时间：2018/8/30 15:00:00`, 'YYYY/M/D hh:mm:ss').format()
```
while this gives the expected result `2018-08-30T15:00:00+08:00`
```javascript
moment.locale('zh-cn');
moment.tz.setDefault('Asia/Shanghai');
moment(`4、公告时间：2018/8/30 15:00:00`, '：YYYY/M/D hh:mm:ss').format()
```
Could someone please tell me why the colon is needed here to parse the datetime text? Is this an expected behavior?

**Environment:**

Chrome 68.0.3440.106 on OSX

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
output:
```
Mon Sep 17 2018 00:50:26 GMT+0800 (中国标准时间)
2018/9/17 上午12:50:26
-480
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
2.10.6
```

**Comment by ashsearle** [comment]
You're parsing the date using lenient or [forgiving mode](https://momentjs.com/guides/#/parsing/forgiving-mode/), which doesn't have clearly defined behaviour.  (You'd get more consistent and predictable behaviour using [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/) if you can)

A rough description of 'forgiving mode' would be that the parser works from left-to-right, skipping over any numbers or noise that don't match the format string (which is also being processed from left to right.)

So, in your first example the parser is looking for something matching 'YYYY', and finds `4`, then looks for `/`, causing it to skip over `、公告时间：2018`, and then proceeds to match `M` against `8` and process the rest of the string.

In the second case, the parser starts looking for `:`, so skips straight over `4、公告时间`, and then proceeds to process the rest of the string as you expected.
