### ISSUE TITLE
Library is not loaded on Safari

### ISSUE THREAD

**Issue by piervalli** [moment/moment#4778]
Hi,

I have a problem with Safari, the library is loaded but is not available as moment.
It is work with Chrome, IE, Firefox.
 <script src="node_modules/moment/min/moment.min.js?1536710050050"></script>
ReferenceError: Can't find variable: moment

**Comment by ashsearle** [comment]
Some more details would be useful: e.g. which version of moment, and which OS and browser versions are you talking about?

**Comment by piervalli** [comment]
Hi,

Browser Safari version 10.1 (10603.1.30.0.34)
Mac version OSX Yosemite 10.10.5.
The library is loaded ("/node_modules/moment/min/moment.min.js?1536710050050")
Thanks

**Comment by ashsearle** [comment]
It would be useful to know what version of moment you're talking about, as well as some detail about how you're loading the page in the browser (e.g. via HTTP from a server, or just loading a local file via `file:///` protocol.)

Do you still get the `ReferenceError` if you load moment like this:?
```html
<script src="https://unpkg.com/moment@2.22.2/min/moment.min.js"></script>
```

**Comment by piervalli** [comment]
Hi,

the moment version is 2.22.2.
It is included as <script src="https://unpkg.com/moment@2.22.2/min/moment.min.js"></script>

Example

`
<!DOCTYPE html>
<htm manifest="manifest.appcache">
    <head>
        <link rel="icon" href="favicon.ico">
        <meta charset="utf-8">
        <title>Demo</title>
        <script src="node_modules/lodash/core.min.js?1536710050050"></script>
    <body>
        <div id="loader" class="loader">Loading...</div>
    </body>
</htm>
`
I have downloaded the library as npm  then I haved used as minify version.

**Comment by piervalli** [comment]
Hi,

sorry the mistake. It is my server for test ("http://www.plumeteam.cloud"), so you can check
Thanks.

**Comment by ashsearle** [comment]
I don't see any errors loading that site in Safari, but I'm on a newer OS / Safari version.

Do you have any more information / stack traces in the console?

**Comment by piervalli** [comment]
Hi,

in the main page open the "Inspector web" and in the console write "moment" it returns the error "ReferenceError: Can't find variable: moment".

**Comment by ashsearle** [comment]
That all works fine for me.

If you switch to the Network tab and reload the page, do you see any errors when loading moment.min.js?  Are you accessing the site via www.plumeteam.cloud, or are you accessing via a localhost address?

**Comment by piervalli** [comment]
Sorry,
I tried to clear history navigation, It works. Perhaps there was an error on load the script, but I did not seen error on load.
Thanks for your time.
