### ISSUE TITLE
Swedish locale incorrect, it is set to Sami.

### ISSUE THREAD

**Issue by tanthammar** [moment/moment#4779]
The Swedish standard language code is "SE". 
The Swedish domain is .se
Most programming languages refers to Swedish as 'se'.

In moment-with-locales.min.js Swedish is set to 'sv' and SAMI is set as 'se'.

This is most certainly incorrect.
Sami is a language of the Eskimoes. Don't know if there is even a language code for that.

I swapped in to 'sa' which didn't conflict with anything in the file.
![should be se](https://user-images.githubusercontent.com/21239634/45681442-d4a85180-bb3d-11e8-94dc-63a80f24c8ad.png)
![unknown-locale](https://user-images.githubusercontent.com/21239634/45681444-d4a85180-bb3d-11e8-87f0-a5d01aea4d7e.png)

**Comment by ashsearle** [comment]
I think the locale is fine, it's just the comments that are wrong.

Small human error updating 100 files in commit 4b3fc58ddc777ec7d65fd3a85bd0ae64632e3dfe

**Comment by tanthammar** [comment]
Not sure I understand what you mean. 
In most frameworks Swedish is referred to as SE so if I work with a multilingual application with some function like "get current language", I always have to create a string replace from 'se' to 'sv' to get the correct language in moment.js.

**Comment by ashsearle** [comment]
I made a mistake; I now don't think there's anything wrong with the locale's at all.

Like you, I associate 'se' with sweden.

But, moment tends to use BCP-47 language codes.  So 'sv' is correct for swedish, and would lend itself to having Sweden and Finland variants (sv-SE and sv-FI)

se-NO would be the correct language + region code for Northern Sami, Norway.

I guess the main point to remember is: moment's locales are named based on _language_, not country.

**Comment by marwahaha** [comment]
Hi @tanthammar , thanks for the report. I agree with Ash, the codes from the language itself, not country.

**Comment by Jorsta** [comment]
@tanthammar 'se' stands for the country Sweden, 'sv' stands for the language Swedish.
And sami is not the language of the Eskimoes :-). Your mixing things up
