### ISSUE TITLE
Full locale not properly working

### ISSUE THREAD

**Issue by FacundoPomar** [moment/moment#4780]
Hi, I found an issue with moment i18n with full locales.

Moment: 2.22.1

I'm currently setting moment locale using `window.navigator.languages`, that returns an array like:

`["es-AR", "en-US", "zh-CN"]`

This en theory should set moment to Spanish, but in reality it's setting Chinese as language. My set up is something like:

```
import moment from 'moment';
import 'moment/min/locales.min.js';
...
...
...
const locales = window.navigator.languages;
moment.locale(locales);
console.log(moment.locale()) // zh-cn --> it should be es-ar
```

But, if I change my Chrome configuration to have a plain language on top:

`["es", "es-AR", "en-US", "zh-CN"]`

It works just fine.  `moment.locale() // es`. So seems that there is some kind of error with full locale settings.

I'm not sure if it's in fact an issue on how moment determines full locales or if my current setting is wrong.

Thanks !

**Comment by fzxt** [comment]
https://github.com/moment/moment/pull/3786#issuecomment-353520578
