### ISSUE TITLE
Is there a way to customize moment to only use the langs i need?

### ISSUE THREAD

**Issue by GabMic** [moment/moment#4784]
Is there a way to customize moment to only use the langs i need? 
That way i can shrink the size of my JS considerably.
Thanks.

**Comment by pmochine** [comment]
https://medium.com/@michalozogan/how-to-split-moment-js-locales-to-chunks-with-webpack-de9e25caccea

**Comment by raysuelzer** [comment]
This is not a solution for people not using webpack. I don't see any reason that hundreds of KBs of locales that 99% of developers will never use are included by default.
