### ISSUE TITLE
moment().isSame(undefined, 'day') === true

### ISSUE THREAD

**Issue by samit4me** [moment/moment#4788]
`moment().isSame(undefined, 'day') === true`

If you remove the second parameter it works as intended (e.g. `false`), but if you change `day` to `year` it also returns `true`.

I've tested this using version `2.22.2`.

Found the following:

- `moment().isAfter(undefined, 'day') === false` (correct)
- `moment().isBefore(undefined, 'day') === false` (correct)
- `moment().isSameOrAfter(undefined, 'day') === true` (broken) 
- `moment().isSameOrBefore(undefined, 'day') === true` (broken) 

I understand the docs say the first argument should be of type `Moment|String|Number|Date|Array` but it would be nice if `undefined` was also supported like in the other methods.

**Comment by ashsearle** [comment]
The [documentation for isBefore](https://momentjs.com/docs/#/query/is-before/) has some hints about this:

> If nothing is passed to moment#isBefore, it will default to the current time.
>
> NOTE: moment().isBefore() has undefined behavior and should not be used! If the code runs fast the initial created moment would be the same as the one created in isBefore to perform the check, so the result would be false. But if the code runs slower it's possible that the moment created in isBefore is measurably after the one created in moment(), so the call would return true.

Passing `undefined` is the closest you can get to passing nothing.  The same issue described above applies to `isAfter`, `isSameOrAfter` and `isSameOrBefore`.

The reason you're reliably seeing `true` when adding a unit is that you're very unlikely to bridge a day or year boundary while creating two moment instances.  But, if you omit the unit you're effectively doing: `moment().isSame(undefined, 'millisecond')`, which is unstable.

**Comment by marwahaha** [comment]
Nice find. But Ash is right, this doesn't always work. Perhaps the documentation can be improved on this.
