### ISSUE TITLE
Missing support for locale en-SG

### ISSUE THREAD

**Issue by fsw0723** [moment/moment#4791]
MomentJs does not support locale `en-SG`. It will default to `en` when `en-SG` is used. However the date formatting should not be the same as `en`. 
For example, long date format should be DD/MM/YYYY for `en-SG` instead of MM/DD/YYYY. (Referring to javascript `toLocaleDateString`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)

```
moment.locale('en-SG')   // en
momentDate = moment('Oct 1, 2000');
console.log(momentDate.calendar());    // 10/01/2000

date = momentDate.toDate();
date.toLocaleDateString('en-SG');     //  01/10/2000
```

This can be solved by either adding `en-SG` as a locale for momentJs, or default it to `en-GB`.

**Comment by marwahaha** [comment]
closing as part of https://github.com/moment/moment/issues/4949
