### ISSUE TITLE
Wrong timezone formatted on particular date

### ISSUE THREAD

**Issue by chouex** [moment/moment#4794]
**Description of the Issue and Steps to Reproduce:**
moment('03/05/2007', "DD/MM/YYYY", true).format() 
"2007-05-03T00:00:00+08:00"
moment('03/05/2076', "DD/MM/YYYY", true).format() 
"2076-05-03T00:00:00+08:00"
moment('03/05/1976', "DD/MM/YYYY", true).format() 
"1976-05-03T00:00:00+09:00"

https://codepen.io/chouex/pen/ZqQeJb

what should we do If we want to format date safety.

**Environment:**
browser timezone: GMT+8

**Comment by ashsearle** [comment]
What's your locale?  Is it possible the timezone offset was GMT+09:00 in 1976?

**Comment by ashsearle** [comment]
I shouldn't have used the word locale.   I meant, what region are you in?  Which country?  What's your O/S region settings?

**Comment by chouex** [comment]
My Machine is Windows 10 with following system timezone
China | CN | China Standard Time | (UTC+08:00) | Beijing, Chongqing, Hong Kong, Urumqi

**Comment by ashsearle** [comment]
If you're in Hong Kong your timezone may have been GMT+9 from 18th April to 17th October back in 1976.

Source: https://www.timeanddate.com/time/zone/hong-kong/hong-kong

**Comment by chouex** [comment]
new Date(Date.parse("5/31/1975")).toUTCString() +'\n'+new Date(Date.parse("5/31/2018")).toUTCString()
`Fri, 30 May 1975 15:00:00 GMT
Wed, 30 May 2018 16:00:00 GMT`

since this behavior is related to native JavaScript, Close.
