### ISSUE TITLE
Inconsistent .add(n, 'days') behavior

### ISSUE THREAD

**Issue by smnbbrv** [moment/moment#4798]
**Description of the Issue and Steps to Reproduce:**

I wrote a function to find array of days between given dates:

```
function getDaysBetweenDates(d1, d2) {
    if (!d1 || !d2) {
      return [];
    }

    const md1 = moment(d1);
    const md2 = moment(d2);

    if (md1 > md2) {
      return [];
    }

    return Array.from({ length: md2.diff(md1, 'days') + 1 }).map((e, i) => moment(d1).add(i, 'days')).map(d => d.toISOString());
  }

const days = getDaysBetweenDates('2018-09-03T00:00:00Z', '2018-11-30T00:00:00Z');

console.log(days[0]);
console.log(days[55]);
console.log(days[56]);
```

And this is the result I get:

```
2018-09-03T00:00:00.000Z
2018-10-28T00:00:00.000Z
2018-10-29T01:00:00.000Z
```

As one can see, from 56s day on every date gets 1 hour more which is way not expected.

*Please include the values of all variables used.*

**Environment:**

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

Every browser I have

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

Thu Oct 04 2018 11:23:56 GMT+0200 (Central European Summer Time)
04/10/2018, 11:23:56
-120
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by smnbbrv** [comment]
Actually, if I perform explicit utc conversion then it works as expected.

```
    const md1 = moment(d1).utc().startOf('day');
    const md2 = moment(d2).utc().startOf('day');
```

Very, very weird

**Comment by ashsearle** [comment]
You are currently in "Central European Summer Time", which ends on Sunday October 28th this year.

On 28th October, clocks go back 1 hour and your timezone will change from CEST to CET - this means 28th October 2018 will be 25 hours long for you.

That extra hour will apply for any two dates where the earlier date falls in CEST, and a later one in CET.

**Comment by ashsearle** [comment]
That's exactly the point; you're adding days.  A day can be 23, 24 or 25 hours long.

If you want to add 24 hours every time, use hours.
