### ISSUE TITLE
French locale

### ISSUE THREAD

**Issue by Floby** [moment/moment#48]
I came to the website today and found the site displaying this in French.

`Jeudi, Novembre 10er 2011, 4:55:30 pm`

just wanted to point out that `10er` is not correct it should be only `10`. the suffix -er is only used for 1. Otherwise no suffixes are used in dates.

**Comment by mnoble01** [comment]
@timrwood I just have a quick question about @vjeux's comment above.... 

Is it possible to use the French `17h04` (rather than `00:00am/pm`) time notation with moment? Do the reserved letters (`h` here) pose a problem or is there a way to escape letters which are otherwise used for formatting?

**Comment by timrwood** [comment]
@mnoble01, you can use `[]` to escape like `HH[h]mm`.

**Comment by mnoble01** [comment]
@timrwood, thanks. I guess what I'm really wondering is if there are any plans to make the `00h00` the default for the French locale formats.
