### ISSUE TITLE
moment.format("w YYYY") for last day of year incorrect

### ISSUE THREAD

**Issue by mtobias** [moment/moment#4800]
**Description of the Issue and Steps to Reproduce:**

The "w YYYY" format for 12/31/2017 is "1 2017". Expected to be "1 2018". 

The 7 days of the 52nd week of 2017 ends on the 30th. So the 31st really belongs in the first week of 2018.

*Please include the values of all variables used.*

**Environment:**

Mac OSX. Chrome 69

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

![image](https://user-images.githubusercontent.com/543786/46501415-6e852500-c7f3-11e8-85d0-03b25e25b52f.png)

here is a loop of the days with the corresponding weeks

**Comment by mh81** [comment]
Looking at the docs, it looks like the possible values for "w" are "1 2 ... 52 53".

Given that the week starting on 12/24/2017 is the 52nd week, it seems like the week starting on 12/24/2017 should be the 53rd week.

```
> moment('2017-12-24').format('w YYYY')
'52 2017'
> moment('2017-12-31').format('w YYYY')
'1 2017'
```

Either way, "1 2017" is definitely wrong.

**Comment by mh81** [comment]
@mtobias After looking into this for a bit, I think that the format you want to be using is `w gggg` instead of `w YYYY`.

```
> moment('2017-12-31', 'YYYY-MM-DD').format('w gggg')
'1 2018'
```

https://momentjs.com/docs/#/displaying/format/

**Comment by mtobias** [comment]
Interesting; didn't see that. Thanks!

**Comment by akanshgulati** [comment]
@mtobias  can you close this issue?
