### ISSUE TITLE
moment().format() incorrect on older browsers

### ISSUE THREAD

**Issue by Unsfer** [moment/moment#4803]
**Description of the Issue and Steps to Reproduce:**
When converting to 'DD.MM.YYYY' format some rare dates becomes new, not equal to the initial

```js
var date = "1983-04-01";
var ruDate = moment(date, 'YYYY-MM-DD').format('DD.MM.YYYY');
alert(date + " - " + ruDate);
// Output: "1983-04-01 - 31.03.1983"
```
http://jsfiddle.net/f3jus6cn/

**Environment:**
Reproduced this on Chromium 35 and Firefox 45.9.0
OS: Gentoo 2.2

**Other information that may be helpful:**
* The time zone setting: +0400
* The time and date at which the code was run: doesn't matter

**Comment by ashsearle** [comment]
Please can you run the code below and tell us the output:
```js
var date = "1983-04-01";
var ruDate = moment(date, 'YYYY-MM-DD');
console.log(moment.version, moment.locale(), ruDate.toISOString(), ruDate.toDate().toString());
```

**Comment by Unsfer** [comment]
moment.version: "2.2.1"
moment.locale(): error moment.locale is not a function
toISOString: "1983-03-31T19:00:00.000Z"
toDate: "Thu Mar 31 1983 23:00:00 GMT+0400 (KUYT)"

**Comment by ashsearle** [comment]
moment 2.2.1 - from September 2013?

You should probably upgrade and see if the bug is fixed in a more recent version of moment.

**Comment by Unsfer** [comment]
Tried latest version:
moment.version: "2.22.2"
moment.locale(): "ru"
toISOString: "1983-03-31T19:00:00.000Z"
toDate: "Thu Mar 31 1983 23:00:00 GMT+0400 (KUYT)"

**Comment by marwahaha** [comment]
I think this is working now (2.24.0). 

Please re-open if you still have issues.
