### ISSUE TITLE
Note: There is a bug that prevents moment.locale from being loaded.

### ISSUE THREAD

**Issue by msftsvachon** [moment/moment#4808]
I'm failing to find an open tracking issue for this one from the docs: http://momentjs.com/docs/#/use-it/browserify/. moment.locale(<localeString>) is effectively crashing on release builds as it's failing to load the module.

Work arounds either include adding additional code at the call site to compute the right language code to pass in (e.g. en instead of en-us) or loading the entire 275kb locales module which isn't ideal from a performance/memory footprint standpoint.

Do we have an ETA for the issue getting fixed and a new package version being published with it?

**Comment by marwahaha** [comment]
A working example (or non-example) would be useful here.

**Comment by msftsvachon** [comment]
Thanks for asking Kunal. The repro is calling moment.locale(X) on a release build of Android React Native to observe the crash.

This describes one of the work arounds I was eluding to above. Which is to manually import the locale file before making the call. Which isn't ideal before it involves duplicated work to determine the right string to pass (e.g. some locales are 2 characters such as 'en'  vs 4 such as 'pt-br').

https://stackoverflow.com/questions/49637158/react-native-release-crash-because-of-unkown-module-momentjs-locale

```
import 'moment/locale/pt-br';
moment().locale('pt-br');
```

This issue is also touching on it:
https://github.com/facebook/react-native/issues/1629

**Comment by marwahaha** [comment]
I'm not sure if there's something we can fix on our end. If someone has the expertise, they're welcome to submit a PR.

**Comment by terryx** [comment]
i believe the error happen in `src/lib/locale/locales.js`

```js
function loadLocale(name) {
    var oldLocale = null;
    // TODO: Find a better way to register and load all the locales in Node
    if (!locales[name] && (typeof module !== 'undefined') &&
            module && module.exports) {
        try {
            oldLocale = globalLocale._abbr;
            var aliasedRequire = require;
            aliasedRequire('./locale/' + name);
            getSetGlobalLocale(oldLocale);
        } catch (e) {
           // console.log(e) similar error happens on react native
         }
    }
    return locales[name];
}
```

my solution is to know which locale to `require` before hand or have a switch case to fall back to unsupported locale before require them

**Comment by AlexGrafe** [comment]
Similar for me. Locales are loaded in Expo/RN web build but not in Expo/RN iOS.

**Comment by marwahaha** [comment]
related to https://github.com/moment/moment/issues/3623
related to https://github.com/moment/moment/issues/4217

I'm not sure what we can do here.
For future directions (might require a breaking change to drop certain groups of existing users),
#5288
#3688
#4150
Sorry this has been such a painful issue for many people.
Please re-open if you still have concerns.
