### ISSUE TITLE
Dutch locale regex has duplicate entries and wrong order 

### ISSUE THREAD

**Issue by donroyco** [moment/moment#4811]
**Type**
Bug

**Where?**
Locale[ nl.js](https://github.com/moment/moment/blob/develop/src/locale/nl.js) and [nl-be.js](https://github.com/moment/moment/blob/develop/src/locale/nl-be.js) in develop branch.

**What?**
The month _april_ (April) was two times declared; before and after the month of _mei_ (May) inside monthsRegex regular expression. Next up, inside monthsStrictRegex, the order of months was wrong: april (April) comes after _maart_ (March) and not just before _augustus_ (August).

**How to fix?**
#4810 

**Anything else?**
I don't know what is affected by this bug.

**Comment by marwahaha** [comment]
Thanks for this. I don't think the regex changes, but it's a nice cleanup.
