### ISSUE TITLE
Parsing Timezone Incorrectly

### ISSUE THREAD

**Issue by fishcharlie** [moment/moment#4812]
**Description of the Issue and Steps to Reproduce:**

I have the following JavaScript code using Moment.js.

    const moment = require('moment');

	const time = "Thu Nov 01 2018 00:00:00 GMT-0400";
    const momentTime = moment(time, "ddd MMM DD YYYY HH:mm:ss GMT-ZZ");
	console.log(momentTime.toString()); // Thu Nov 01 2018 00:00:00 GMT-0600

Problem is `momentTime.toString()` (`Thu Nov 01 2018 00:00:00 GMT-0600`) does **not** equal `time` (`Thu Nov 01 2018 00:00:00 GMT-0400`).

I'm expecting `momentTime.toString()` to equal `Wed Oct 31 2018 22:00:00 GMT-0600` (if I did my math correctly).

It looks like it's just parsing that timezone or GMT offset incorrectly for some reason.

According to the [Moment.js parsing documentation](http://momentjs.com/docs/#/parsing/string-format/) I should be able to use `ZZ` to parse it into the correct time zone.

Any idea what I'm doing wrong here?

**Environment:**

macOS 10.14
Node.js v10.9.0

**Other information that may be helpful:**
* [Mountain Time Zone](https://en.wikipedia.org/wiki/Mountain_Time_Zone)
* Sunday October 14th 2018, 7:00 PM
* No other libraries in use

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
> console.log( (new Date()).toString())
Sun Oct 14 2018 19:05:27 GMT-0600 (Mountain Daylight Time)
> console.log((new Date()).toLocaleString())
10/14/2018, 7:05:27 PM
> console.log( (new Date()).getTimezoneOffset())
360
> console.log( navigator.userAgent)
ReferenceError: navigator is not defined
> console.log(moment.version)
2.22.2
```

**Comment by guillemm** [comment]
We looked at your issue with @sarfata.

> `const momentTime = moment(time, "ddd MMM DD YYYY HH:mm:ss GMT-ZZ");`
> Problem is momentTime.toString() (Thu Nov 01 2018 00:00:00 GMT-0600) does not equal time (Thu Nov 01 2018 00:00:00 GMT-0400).

Your time format string should not contain `GMT-`. Leaving `ZZ` **only** will give you the proper behavior.

After changing the timezone of my machine to Denver/Mountain Time with daylight savings, here's what I see on a JS console:
```
moment(time, "ddd MMM DD YYYY HH:mm:ss GMT-ZZ").toString()
"Thu Nov 01 2018 00:00:00 GMT-0600"
moment(time, "ddd MMM DD YYYY HH:mm:ss ZZ").toString()
"Wed Oct 31 2018 22:00:00 GMT-0600"
```

**Comment by fishcharlie** [comment]
@guillemm Awesome. In the documentation it says `Offset from UTC as +-HH:mm, +-HHmm, or Z`. Therefor I thought it would only match against the `-0600` part. I didn't think it'd match the `GMT` as well. Not sure if that can be worded better, but I think it was the documentation that lead me to have this problem.

Thanks for your help!

**Comment by contra** [comment]
Just as a note ^ This does not work in strict mode.

![Screen Shot 2019-05-17 at 5 25 41 PM](https://user-images.githubusercontent.com/425716/57956980-d131b980-78c8-11e9-8ab2-7a5bc0478f76.png)
