### ISSUE TITLE
diff() operation return different milliseconds result with same code 

### ISSUE THREAD

**Issue by tmirun** [moment/moment#4818]
**Description of the Issue and Steps to Reproduce:**

have 2 different result in same code

> you can copy and paste code to console of https://momentjs.com page

```javascript
var endDay = moment().add(1, 'd');
var today = moment();
var diff = endDay.diff(today);
var duration = moment.duration(diff);
console.log(duration)
````
![image](https://user-images.githubusercontent.com/8052536/47148625-79e74e80-d2d1-11e8-83b6-8d9f489a9647.png)

**Environment:**

Chrome 69 on MacOs 10.14

**Comment by ashsearle** [comment]
You are creating one moment for `endDate`, and one for `today`.  It's possible that these are created at different points in time (i.e. a ms apart.)

You'll get more stable behaviour if you use `clone()`, either implicitly or explicitly:

```js
var today = moment();
// Use explicit clone:
var endDay = today.clone().add(1, 'd');

// Or implicit clone:
var endDay = moment(today).add(1, 'd');
```

**Comment by tmirun** [comment]
hey @ashsearle, i was investigating for this situation, we have same conclusion 😉, both moment() is created in different time, ty guy, i will close this issue
