### ISSUE TITLE
moment(undefined) should behave the same as moment(null), not moment()

### ISSUE THREAD

**Issue by TApicella** [moment/moment#4820]
**Description of the Issue and Steps to Reproduce:**
Import moment
Run moment(undefined), moment(null), and moment()

*Please include the values of all variables used.*
N/A

**Environment:**
All

Current behavior for undefined input is to call new date.
https://github.com/moment/moment/blob/develop/src/lib/create/from-anything.js#L67

`function configFromInput(config) {
    var input = config._i;
    if (isUndefined(input)) {
        config._d = new Date(hooks.now());
} `

This is incredibly unintuitive and dangerous behavior as it can make bug detection very difficult.

Proposal:
create isUndefined flag similar to isNullable
remove undefined as a valid input

**Comment by EgorEres** [comment]
+1, Why don't you check function arguments?
![image](https://user-images.githubusercontent.com/32257575/48060637-60556a80-e1de-11e8-9ddd-7a44bc9955e7.png)

**Comment by marwahaha** [comment]
I'll take a documentation request on this, but I don't plan on changing the behavior right now.

This has caused others stress, see https://github.com/moment/moment/issues/1639 .

**Comment by rashkov** [comment]
This is, honestly, infuriating every time I come across this bug in my code. Even javascript's Date API doesn't do this: (new Date(undefined)) == 'Invalid Date'
