### ISSUE TITLE
Validation of meridian chars doesn't work properly at the end of strings?

### ISSUE THREAD

**Issue by davidawad** [moment/moment#4822]
**Description of the Issue and Steps to Reproduce:**
I opened https://momentjs.com and opened the chrome console to try the tool.

*Please include the values of all variables used.*
N/A 

It seems like moment is failing to parse meridian chars on a somewhat straightforward example, see the screenshot below: 
<img width="809" alt="screen shot 2018-10-19 at 5 03 18 pm" src="https://user-images.githubusercontent.com/4019054/47243758-19cfd580-d3c1-11e8-8bfa-611a88adabbd.png">

Is there something obvious I'm missing here? 

Thanks

**Environment:**
Chrome on OSX on latest macbook 13 in.

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
screenshot: 

<img width="1440" alt="screen shot 2018-10-19 at 5 04 55 pm" src="https://user-images.githubusercontent.com/4019054/47243749-12a8c780-d3c1-11e8-86b8-e1703f5f944a.png">

**Comment by ashsearle** [comment]
You have a lot of errors in your format string, but the most relevant would be that you're asking it to parse the meridian twice.

```js
moment().format('AA'); // PMPM
```;

You only need one, and you probably want to fix the year/month/day format characters:

```js
moment('18/06/17:06:12:12 am', 'YY/MM/DD:hh:mm:ss A')
```

**Comment by davidawad** [comment]
thanks
