### ISSUE TITLE
Moment Js loads localization too late when lazy loaded

### ISSUE THREAD

**Issue by pmochine** [moment/moment#4823]
I show you my problem as a gif:

![ohne titel 2](https://user-images.githubusercontent.com/25006691/47255002-1e03fd80-d46a-11e8-8128-fe5ac849e268.gif)

First you see that the date is in English, but should be in German. Going to "another" SPA page and returning back to it you see that the date is correclty set in German. 

The problem is that I'm using lazy loading for the locale files. It's too "slow" loading the files and thus Vue is rendering the page faster than moment is getting the file.

I'm using webpack and with 

import moment from 'moment';

```
if(lang != 'en'){
	import(`moment/locale/${lang}.js`).then(() => 
		moment.locale(lang)
	);
	
}
```

Any idea how I can do this better? I asked [here](https://stackoverflow.com/questions/52899694/moment-js-loads-localization-too-late-when-lazy-loaded) but had no luck.

**Comment by ashsearle** [comment]
Is the real answer vue related: you want vue to rerender after you've loaded the locale?

e.g. (maybe) `vm.$forceUpdate()` (from [stackoverflow](https://stackoverflow.com/a/40586872/98493))

**Comment by pmochine** [comment]
@ashsearle thanks for the tip, didn't know about forceUpdate. I actually found a solution, but it's a bit uglier, but works. 

```
//in assets.blade.php
...
<script src="{{ mix('js/manifest.js') }}"></script>
<script src="{{ mix('js/vendor.js') }}"></script>

{{-- 
	We need moment as a single, because of this bug.
	https://github.com/moment/moment/issues/4823 
	It must be after vendor, because of the bug:  
	ReferenceError: webpackJsonp is not defined
--}}
<script src="{{ mix('js/moment.js') }}"></script> //loading moment
<script src="/js/locale-{{ tongue()->current() }}.js" charset="UTF-8"></script> //dynamically loading my language file for moment

<script src="{{ mix('js/app.js') }}"></script>
```
