### ISSUE TITLE
Wrong information about invalid.toISOString in the documentation

### ISSUE THREAD

**Issue by rholliger** [moment/moment#4830]
**Description of the Issue and Steps to Reproduce:**
Hi all

I just wanted to point out, that in the documentation at https://momentjs.com/docs/#/parsing/is-valid/ there is a small error. It says that `invalid.toISOString()` is returning "Invalid Date" in the localized format but it's now returning `null` due to the change described here:
https://github.com/moment/moment/pull/3710

Is it possible to adjust the documentation, so that people will not get confused?

It's just a small "issue".

**Comment by marwahaha** [comment]
Nice find! Anyone is welcome to fixing this. Bonus if you put which release the behavior changed.

**Comment by marwahaha** [comment]
fixed in https://github.com/moment/momentjs.com/pull/534
