### ISSUE TITLE
Diff in days returning float

### ISSUE THREAD

**Issue by vibar** [moment/moment#4831]
**Description of the Issue and Steps to Reproduce:**

OK (diff == 1)

```
moment([2018, 10, 02]).diff(moment([2018, 10, 01]), 'days')
return 1
```

NOK (diff == 0)

```
moment([2018, 10, 05]).diff(moment([2018, 10, 04]), 'days')
return 0
```
With `true` param:

```
moment([2018, 10, 05]).diff(moment([2018, 10, 04]), 'days', true)
return 0.9583333333333334
```
I'm going to have to round off the return of the diff function (in days)?

Sorry for my english.

**Environment:**

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

Chrome 68 / Node.JS 10.4.0 /  Ubuntu 16.04.2*

Mon Oct 22 2018 13:54:48 GMT-0300 (Brasilia Standard Time)
10/22/2018, 1:54:48 PM
180
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
2.19.2

**Comment by liooh** [comment]
Sorry for my english too lol. 

Can't reproduce this error:

```js
moment([2018, 10, 05]).diff(moment([2018, 10, 04]), 'days')
return 0
```

In my try it returns `1`.

**Comment by BillSheikh1** [comment]
Hello, I too cannot reproduce this error.

`const moments = require("../moment/moment");

moments([2018, 10, 05]).diff(moments([2018, 10, 04]), 'days');
return 1;

moments([2018, 10, 05]).diff(moments([2018, 10, 04]), 'days', true);
return 1;
`

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
