### ISSUE TITLE
first week of 2019 issue

### ISSUE THREAD

**Issue by elsafy** [moment/moment#4833]
**Description of the Issue and Steps to Reproduce:**
There is an issue which only happens for the first week of 2019, because it starts on 31 Dec 2018, please check the code below to reproduce
**Environment:**

*Chrome 69 on OSX*

```js
const week = "2019-W01";
const weekResult = moment(week).format(moment.HTML5_FMT.WEEK);
console.log(weekResult);
// expected result: 2019-W01
// actual result: 2018-W01
```

**Comment by marwahaha** [comment]
@ashsearle does #4700 address this?

**Comment by elsafy** [comment]
@marwahaha yep definitely, thanks a lot for the hint

**Comment by ashsearle** [comment]
@marwahaha Yes.  I don't know why that PR failed to go green, but I'll happily do the close/re-open dance to get a green light once your PR fixing the build is merged in.
