### ISSUE TITLE
Date format conversion failing for DD-MM-YYYY dates

### ISSUE THREAD

**Issue by chinmayapati** [moment/moment#4835]
**moment("1986-12-12", "DD-MM-YYYY").isValid() is returning `true`**

`moment("1986-12-12", "DD-MM-YYYY")` evaluates to _2012-12-19_

Also `moment("1986-12-12", "DD-MM-YYYY").isValid()` returns _true_

It seems even with _"DD-MM-YYYY"_ filter, _"YYYY-MM-DD"_ is being checked since

```js
moment("1986-13-12", "DD-MM-YYYY").isValid()
moment("1986-12-32", "DD-MM-YYYY").isValid()
```
returns _false_

**Comment by marwahaha** [comment]
Try [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/):
```
moment("1986-12-12", "DD-MM-YYYY", true).isValid() 
```
