### ISSUE TITLE
Re-enable failing `ka` tests (after we drop node 10)

### ISSUE THREAD

**Issue by marwahaha** [moment/moment#4839]
This is blocked on a node bug 
https://bugs.chromium.org/p/v8/issues/detail?id=8348#c4

more discussion in #4762

Task: Re-enable https://github.com/moment/moment/pull/4828/commits/c34344f392336e63c56a2d12152b965e97a5a088

cc @srl295

**Comment by srl295** [comment]
^ v8 bug.  @ashsearle @marwahaha can you comment on the priority of this fix in 
https://bugs.chromium.org/p/v8/issues/detail?id=8348#c29 ?

**Comment by marwahaha** [comment]
This breaks Moment.js for all users of the Georgian locale in the latest Node version.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
