### ISSUE TITLE
Can't import moment-with-locales

### ISSUE THREAD

**Issue by bohorquezod** [moment/moment#4842]
**Description of the Issue and Steps to Reproduce:**
I can't import 'moment/min/moment-with-locales.min'

i write in my code 
```import moment from 'moment/min/moment-with-locales.min'```
and it throw ```Module not found: Can't resolve './locale' in '/node_modules/moment/min'```

temporarily fix it by editing ```/moment/min/moment-with-locales.min``` and changing ```'./locale'``` to ```'../locale'```

**Comment by ichernev** [comment]
I believe this is related to webpack trying to require stuff automatically. The problem must be similar to when people are trying NOT to require moment with locales, so if you're using webpack you can just import moment without locales and you'll get them for free.

https://github.com/jmblog/how-to-optimize-momentjs-with-webpack

**Comment by mattjohnsonpint** [comment]
Please see https://github.com/moment/moment/issues/6092#issuecomment-5331841987
