### ISSUE TITLE
using moment(time, 'HH:mm:ss.SSS') is one hour off on DST transition day between 2:00-8:59AM

### ISSUE THREAD

**Issue by zshrc** [moment/moment#4846]
**Description of the Issue and Steps to Reproduce:**
I observed an issue on US Daylight saving date (Nov 4):
**moment('05:00:00.000', `'HH:mm:ss.SSS')->1541332800000 (Sunday, November 4, 2018 4:00:00 AM GMT-08:00)**, which is one hour off.

However if we use moment('2018-11-04T05:00:00.000', 'YYYY-MM-DDTHH:mm:ss.SSS') it calculates correctly as 5AM. 

P.S. the issue went way on Nov 5 after DST transition day. I am still able to reproduce the issue if I adjust my android phone time back to Nov 4.

**Environment:**
react-native application running on Android platform version 24

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on:  America/Los_Angeles (pacific timezone)
* The time and date at which the code was run: Nov 4, 11am PST
* Other libraries in use (TypeScript, Immutable.js, etc): react-native

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString()): Sun Nov 04 2018 16:55:35 GMT-0800 (PST)
console.log((new Date()).toLocaleString()): 11/4/2018, 4:55:35 PM
console.log( (new Date()).getTimezoneOffset()): 480
console.log( navigator.userAgent): undefined
console.log(moment.version): 2.20.1
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Comment by zshrc** [comment]
Hi, does anyone have insights how Moment determine time on DST date and why is it platform dependent?

**Comment by ichernev** [comment]
It is related to DST. Somewhere in the 3.x rewrite we tried to fix this type of issues, but its not something that you can really backport easily.

Basically when you try to set the hour on a Date object, that is on a day with DST, it just sometimes jerks back/forward by one hour for no good reason.
