### ISSUE TITLE
parseZone returns the wrong date on specific format

### ISSUE THREAD

**Issue by ouchxp** [moment/moment#4850]
**Description of the Issue and Steps to Reproduce:**
`moment.parseZone` returns the wrong date on specific format, show as the example below, if I try parse a string with `MM-DD-YYYY HH:mm:ss` format, the result is incorrect.

```
moment.parseZone('2018-11-07 09:57:00', 'YYYY-MM-DD HH:mm:ss').format(); // 2018-11-07T09:57:00Z
moment.parseZone('11-07-2018 09:57:00', 'MM-DD-YYYY HH:mm:ss').format(); // 2018-11-06T00:39:00-20:18
```

**Environment:**
Chrome 70 on OSX, Firefox 64 on OSX, Safari 12.0 on OSX

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
NZDT
* The time and date at which the code was run
`2018-11-07T09:57:00+13:00`
* Other libraries in use (TypeScript, Immutable.js, etc)
moment and moment-timezone only

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
Wed Nov 07 2018 15:26:11 GMT+1300 (New Zealand Daylight Time)
07/11/2018, 15:26:11
-780
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
2.22.2
```

**Comment by ichernev** [comment]
`parseZone()` is supposed to parse the zone from the string provided, ideally if you include it in the string AND add a zone token. You did not include a zone and a zone token and then you wonder why parseZone took -2018 and assumed it was the zone.

Its not Artificial Intelligence its regular expressions.

**Comment by ouchxp** [comment]
The issue does not seems to be caused by regular expression, nor have the difficulty of implementing a Artificial Intelligence algorithm.

In the current implementation [setOffsetToParsedOffset](https://github.com/moment/moment/blob/2e2a5b35439665d4b0200143d808a7c26d6cd30f/src/lib/units/offset.js#L174) is ignoring the format and trying to extract a timezone from provided string blindly. 

I can clearly see cases that the timezone cannot be figuring out, and they were handled by calling `this.utcOffset(0, true);` in the [existing code](https://github.com/moment/moment/blob/2e2a5b35439665d4b0200143d808a7c26d6cd30f/src/lib/units/offset.js#L182)

My opinion is if strict format has been given, the parsing function should respect it. In `setOffsetToParsedOffset` function, when `this._tzm` is undefined and `this._f` clearly states it does not include a timezone, there is no point to call `offsetFromString`.

Anyway, this is a behavior that has not been clearly documented, hence could be categorize as illigal. I am open do disagreement.

**Comment by parthakonda** [comment]
Is this got fixed?
