### ISSUE TITLE
Prepend dash on format

### ISSUE THREAD

**Issue by lcssanches** [moment/moment#4851]
**Description of the Issue and Steps to Reproduce:**
moment prepend a dash on formatted date string.

```
console.log( moment('01-dec-2018').format('YYYY-MM-DD') )
-2018-12-01
```

this does not happens if I create the with format
```
console.log( moment('01-dec-2018', 'DD-MMM-YYYY').format('YYYY-MM-DD') )
2018-12-01
```

**Environment:**

Windows 10
Firefox Developer 64.0b7 (64-bit)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
Wed Nov 07 2018 12:00:21 GMT-0200 (Horário de Verão de Brasília)
console.log((new Date()).toLocaleString())
07/11/2018 12:00:21
console.log( (new Date()).getTimezoneOffset())
120 
console.log( navigator.userAgent) 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
console.log(moment.version)
2.22.2
```

**Comment by marwahaha** [comment]
There is no format in the first example, so we can't guarantee anything about the output (i.e. Moment made its best guess). 

If you don't want this behavior, use a format, [probably with strict mode](https://momentjs.com/guides/#/parsing/strict-mode/)
