### ISSUE TITLE
Request: add 'date' as a duration string for .add() and .subtract()

### ISSUE THREAD

**Issue by pauleustice** [moment/moment#4856]
**Description of the Issue and Steps to Reproduce:**
Thanks for one of the most useful libraries of all time! I'm using a lot of moment at the moment (groan) in a project and have run into something that would make DRYing my code a lot easier: the ability to add or subtract time using 'date' as an alias for 'day'.

Semantically of course, it makes sense to subtract a day. However, when getting, a 'day' refers to the day of the week. An abbreviated example data structure:

```
const years = [
  { year: 2018, data: [ { month: 0, data: [ { date: 0 } ] } ]
]
```

In a codebase where I am referencing nested objects (as above) using 'date', 'month' and 'year' and using those properties with moment, it becomes a pain to write things like this throughout my code:

```
currentMoment.add(1, (bracket === 'date' ? 'day' : bracket))
```

If I were to rename the 'date' property in my objects to 'day', then the equivalent problem occurs when I need to do the following:

```
currentMoment.get(bracket === 'day' ? 'date' : bracket))
```

The best solution, I believe, is to allow the addition and subtraction of 'dates':

```
currentMoment.add(1, 'date')
```

It's a quirk of the English language that the two don't match, and I guess whether it's an acceptable solution depends on whether people feel it makes sense, or could be easily explained within documentation.

**Comment by pauleustice** [comment]
A more elegant alternative that just came to mind: add 'D' as an alias for days when adding or subtracting. This then creates synergy between .get() and .add() when referring to dates, matching the moment().get('D') and negating the need for the somewhat unsemantic solution above.

**Comment by MynockSpit** [comment]
> A more elegant alternative that just came to mind: add 'D' as an alias for days when adding or subtracting. This then creates synergy between .get() and .add() when referring to dates, matching the moment().get('D') and negating the need for the somewhat unsemantic solution above.

`d` (but not `D`) is currently an alias for days. Will that work?

```
now = moment()
now.get('date') // 9
now = now.add(3, 'd')
now.get('date') // 12
```

**Comment by pauleustice** [comment]
@MynockSpit That sounds like the same problem; a difference in the shorthand for a 'day' unit between `.get()` and `.add()`.

The essence of the problem is:

`now.get('d') // Returns day of the week index, not date of the month`
`now.add(1, 'd') // Adds a day`
`now.get('D') // Returns date of the month index`
`now.add(1, 'D') // Doesn't exist, but if it pertained to adding a day it would be great`

There's no synergy between the two shorthands, they refer to different things when getting and adding.

**Comment by MynockSpit** [comment]
Don't get and add have totally different units? `get` refers to the extra number of units until the defined unit boundary and `add` refers to the net number of units, regardless of boundary.

Regardless, you could patch 'D' into working (do this as soon as possible and only once):

```js
(function () {
  // get the prototype of moment objects
  var prototype = Object.getPrototypeOf(moment())

  // store the add function b/c we're going to overwrite it ...
  var add = prototype.add 
  
  // ... here
  prototype.add = function (number, string) {
    // do special logic -- in this case, replace 'D' with 'd'.
    if (string === 'D') string = 'd' 

    // call the original add function
    // pass `this` -- it refers to the date object
    // return the result so we can chain
    return add.call(this, number, string) 
  }
}())
```

**Comment by ichernev** [comment]
`day` is a unit of time equal to 24 hours.
`date` means a point in time (like a moment), but without the time :)

`.get('date')` is somewhat confusing as well, but there are so many things to get that we were out of words! `.get('day')` is for day of week, and `date` is for `day-of-the-month`. It comes from js `Date` object, with its `getDate()` and `setDate()` methods that refer to `day-of-the-month`

If you don't speak English natively, it might make sense to have `.add(1, 'date')`, but that makes zero sense whatsoever in English. Just use `.add(1, 'd')` (which means `day`) and call it a day.
