### ISSUE TITLE
Date format incorrect for en-IE

### ISSUE THREAD

**Issue by martinmcwhorter** [moment/moment#4857]
en-IE uses slashes rather than hyphens to separate day month year.

I have created a PR with the bugfix here

https://github.com/moment/moment/pull/4849

Here is a link to the Unicode CLDR definition for en-IE for reference. 

https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/en-IE/ca-gregorian.json

**Comment by ichernev** [comment]
Close in favor of #4849
