### ISSUE TITLE
Current UTC ISO 8601 date string with milliseconds

### ISSUE THREAD

**Issue by nodesocket** [moment/moment#4864]
Looking to return the current UTC ISO 8601 date string with milliseconds. Currently doing:

```javascript
moment().utc().format()
```

But this returns:

```
2018-11-16T06:18:07Z
```

How can I add current milliseconds to this date string?

**Comment by nodesocket** [comment]
Thanks. Small correction I think it should be:

```
moment().utc().format('YYYY-MM-DD[T]HH:mm:ss.SSS[Z]');
```

Note `[Z]` goes at the end.

**Comment by ashsearle** [comment]
Or use [`toISOString`](https://momentjs.com/docs/#/displaying/as-iso-string/)

**Comment by gujunhk** [comment]
> Thanks. Small correction I think it should be:
> 
> ```
> moment().utc().format('YYYY-MM-DD[T]HH:mm:ss.SSS[Z]');
> ```
> 
> Note `[Z]` goes at the end.

Elegant! Very Elegant!!
