### ISSUE TITLE
convert to ZonedDateTime return times always 0

### ISSUE THREAD

**Issue by juicycool92** [moment/moment#4865]
**Description of the Issue and Steps to Reproduce:**
Hello there! thanks for share nice time parse library. i love it.

recently, i try to print out date include time.

i received ZonedDatetime type variable from Spring.(unfortuatly i dont have authorize change datetype)
and i try to parse for JS with moment.js

this is requested ZonedDatetime object as stringify
`"{\"dateTime\":{\"date\":{\"year\":2018,\"month\":11,\"day\":16},\"time\":{\"hour\":18,\"minute\":30,\"second\":27,\"nano\":0}},\"offset\":{\"totalSeconds\":32400},\"zone\":{\"id\":\"Asia/Seoul\"}}"`

as you can see, there is time value.
but when i did try to parse on JS

`const targetDate = JSON.parse("{\"dateTime\":{\"date\":{\"year\":2018,\"month\":11,\"day\":16},\"time\":{\"hour\":18,\"minute\":30,\"second\":27,\"nano\":0}},\"offset\":{\"totalSeconds\":32400},\"zone\":{\"id\":\"Asia/Seoul\"}}");`

`const myDate = moment(targetDate).format('YYYY-MM-DD a h:mm:ss');`

`console.log(myDate) // "2018-11-16 am 12:00:00"`

time didnt recognized at all.

i tryed chrome and firefox, but its work same, and stuck at googling.

anyone can help me? Thanks.

**Environment:**
Spring4 JSP

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*
Chrome 70
Firefox 64 

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

below code is infomation about this post requested
```
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

Fri Nov 16 2018 19:07:49 GMT+0900 (대한민국 표준시) debugger eval code:1:1
2018. 11. 16. 오후 7:07:49 debugger eval code:2:1
-540 debugger eval code:3:1
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0 debugger eval code:4:1
2.22.2
```

**Comment by x13machine** [comment]
You first need to convert your date format into something moment can understand.
```
var transformedDate = Object.assign(targetDate.dateTime.date,targetDate.dateTime.time); //joins targetDate.dateTime.date & targetDate.dateTime.time
moment(transformedDate).tz(targetDate.zone.id).format('YYYY-MM-DD a h:mm:ss');

```

**Comment by juicycool92** [comment]
> 
> 
> You first need to convert your date format into something moment can understand. This should work for what you want:
> 
> ```
> var transformedDate = Object.assign(targetDate.dateTime.date,targetDate.dateTime.time); //joins targetDate.dateTime.date & targetDate.dateTime.time
> moment(transformedDate).tz(targetDate.zone.id).format('YYYY-MM-DD a h:mm:ss');
> ```

Thankyou very much, its works!
...But unfortunatly, my boss make decision to re-product date in back-end side.
Still, im really appreciate for you help. 
Have a nice day. <3
