### ISSUE TITLE
Some locale not working properly

### ISSUE THREAD

**Issue by dominicarrojado** [moment/moment#4866]
moment.locale('zh-cn');
moment().format('D MMM YYYY')
"20 11月 2018"

Expected is:
"20日 11月 2018年"

**Comment by marwahaha** [comment]
To get the ordinal, use `Do`:
```
moment.locale('zh-cn');
moment().format('Do MMM YYYY')
"19日 1月 2019"
```

https://momentjs.com/docs/#/displaying/format/

Please re-open if you still have issues.
