### ISSUE TITLE
Using moment to calculate overtime: given a range, count seconds that fall within specific hours

### ISSUE THREAD

**Issue by mercmobily** [moment/moment#4868]
Hi,

I have already [submitted this to SO](https://stackoverflow.com/questions/53387198/calculate-how-much-of-a-n-hour-segment-is-outside-business-hours-8am-9pm
), but no real answers there.

I need a function that given two dates A and B which are always N hours apart (3 or 4, but anything ideally would be possible), gives me the total number of hours that fall outside of a window 8AM->5PM (or, 800 -> 1700).

I am developing an overtime calculator for an invoice, and was given this requirement -- as you can imagine, anything that falls outside those times would be charged more.

Does Moment provide such a function? That is, in a date range A -> B, how many milliseconds fall into/outside of a specific time range (800->1700, for example)

Thanks!

**Comment by marwahaha** [comment]
[moment().diff](https://momentjs.com/docs/#/displaying/difference/) or [Durations](http://momentjs.com/docs/#/durations/) might satisfy your needs.

**Comment by mercmobily** [comment]
I couldn't see anything in moment().diff or Durations that might deal properly with intervals, and that might help with my question...

**Comment by ichernev** [comment]
Moment doesn't deal with ranges, there are some plugins: https://github.com/rotaready/moment-range and another one https://github.com/icambron/twix.js/

You can do a bit of fiddling with .isBetween, figure out if how the two ranges overlap, and subtract them yourself. I wouldn't install a plugin for a 1 line computation, but left-pad was popular, so what does my opinion mean anyway :)

```javascript
wStart, wEnd = getWorkRange();
rStart, rEnd = getRegularWorkingRange();

var msOvertime = (wStart.isBefore(rStart) ? rStart.diff(wStart) : 0) + (wEnd.isAfter(rEnd) ? rEnd.diff(wEnd) : 0);
```

**Comment by mercmobily** [comment]
Hi,

The issue is much more complex than you think.
There is a case when for example "overtime" is from 11PM to 3AM, and
somebody works from 10PM through to 5AM. Or, unlikely but possible when
dealing with hiring things rather than people, when "overtime" is 11PM to
3AM and something is hired from 10PM to 11AM *two days later*. Don't get me
started with use cases where "peak  rates" is for example between 10PM and
2AM *and* between 10AM and 1PM...

I haven't found any prior implementation of this anywhere, ever. It must
just be something that doesn't happen often enough to vouch for "generic"
implementations. However, I suspect proper implementation is really
difficult.
