### ISSUE TITLE
toDate with .utc is using local timezone

### ISSUE THREAD

**Issue by basickarl** [moment/moment#4871]
2.10.3

https://momentjs.com/docs/#/parsing/utc/

```
moment.utc(ts).format(); // 2018-10-25T05:00:00+00:00
moment.utc(ts).toDate(); // Thu Oct 25 2018 07:00:00 GMT+0200
```

How do I get the toDate format of the date but lose the local timezone (so that the second line displays 05:00:00 GMT+0000). I thought using ".utc" fixed this?

**Comment by marwahaha** [comment]
`toDate` returns a `Date` object. 
https://momentjs.com/docs/#/displaying/as-javascript-date/

```
typeof moment.utc().format()
"string"
typeof moment.utc().toDate()
"object"
```

If you want the format, you could try different formatting tokens, maybe `llll` 
https://momentjs.com/docs/#/displaying/format/
```
moment.utc().format('llll')
"Fri, Dec 28, 2018 9:18 AM"
```

**Comment by ichernev** [comment]
@basickarl `Date` objects are both UTC and local at the same time. That is why to make this simpler in moment there is separate utc and local modes, so the function .year() can do either, depending on the mode.

For a Date object, you should call `getFullYear()`, or `getUTCFullYear()` depending on what you want. And `.toString()` on Date returns the local representation, you can call `.toISOString()` to get a UTC date string out.

```
moment.utc(ts).toDate(); // Thu Oct 25 2018 07:00:00 GMT+0200
// --> this is actually moment.utc(ts).toDate().toString()
moment.utc(ts).toDate().toISOString(); // check THIS out :)
```
