### ISSUE TITLE
Parsing "Tue 1/1" returns Monday 1/1/2018

### ISSUE THREAD

**Issue by samrispaud** [moment/moment#4879]
The following code:
`moment("Tue 1/1", 'ddd M/D').format()`

Produces this output:
`"2018-01-01T00:00:00-05:00"`

Because the day of the week is specified, shouldn't moment know this is 1/1/2019?

**Comment by marwahaha** [comment]
What locale are you using? I get an Invalid moment when I run this.

Moment's parsing is decent, but it's not an AI.
