### ISSUE TITLE
Date 0000-00-00 == 00-1-11-30

### ISSUE THREAD

**Issue by botaniQQQ** [moment/moment#4882]
```
var m = moment();
console.log(
	m.subtract(m.diff('0000-00-00', "days"), 'days')
        .format('YYYY-MM-DD')
);
// => 00-1-11-30
```

http://jsfiddle.net/b85q4umt/

**Comment by botaniQQQ** [comment]
MySQL: `SELECT TO_DAYS("2017-06-20 09:34:00") ` => **736865**
Moment: `moment('2017-06-20 09:34:00').diff('0000-00-00', "days")` => **736897**

**Comment by botaniQQQ** [comment]
Demo MySQL: https://www.w3schools.com/sql/trymysql.asp?filename=trysql_func_mysql_to_days2
Demo Moment: http://jsfiddle.net/z3ovwft7/

**Comment by ashsearle** [comment]
Your jsfiddle shows moment version is 2.2.1, which is 5 years old.

Please try a more recent version.

**Comment by botaniQQQ** [comment]
@ashsearle, thanks, I update version.
```
console.log(
	moment('2017-06-20 09:34:00').diff('0000-00-00', "days")
);
// => NaN
```

How to get the number of days from zero year?

**Comment by ashsearle** [comment]
Use `0000-01-01`:
```js
console.log(
	moment('2017-06-20 09:34:00').diff('0000-01-01', "days")
);
// -> 736865
```

You're proving a date in ISO format, which does _not_ use 00 for month or day-of-month
