### ISSUE TITLE
Moment isValid() returning true for date checking when providing invalid date value (date with string concatination)

### ISSUE THREAD

**Issue by habibsql** [moment/moment#4888]
Provide any date and concate string befor or after or both:

{{code}}
var valid = moment('aa2018/01/01aa', 'YYYY/MM/DD', true).isValid();
alert(valid); // return true
{{code}}

Expection: it should return false
Actual: it returns true

**Comment by ashsearle** [comment]
Which moment version are you using?

**Comment by habibsql** [comment]
The problem is not found in recent version 2.22.2.)
Hence I close this.
