### ISSUE TITLE
2 tests failed. diff:diff across DST (2887.17) diff:diff across DST (2887.19) 

### ISSUE THREAD

**Issue by robertocifuentes** [moment/moment#4889]
### Client info
```
Date String   : Wed Dec 05 2018 21:11:41 GMT-0600 (hora estándar central)
Locale String : 5/12/2018 21:11:41
Offset        : 360
User Agent    : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
Moment Version: 2.22.2
```

====

### diff:diff across DST (2887.17) 

month diff across DST, lower bound

```javascript
// Expected true
// Actual   false
false === true
```

====

### diff:diff across DST (2887.19) 

year diff across DST, lower bound

```javascript
// Expected true
// Actual   false
false === true
```

**Comment by luc-boussant** [comment]
I would like to try to fix this issue but I can't figure out which tests aren't passing. In what files are they?

**Comment by harkue** [comment]
I didn't any failure in the latest code, and the travis CI didn't triggle any error about it.
Could you provide more infomation about the failures? @robertocifuentes
