### ISSUE TITLE
[Locale] Ar monthsshort is the same as months

### ISSUE THREAD

**Issue by Liam-Ryan** [moment/moment#4890]
If you use the short month format for the ar locale then the full month names are displayed. You can see that monthsShort is set to months in the ar.js file

I'm not an Arabic speaker so it's possible this is intentional, however I checked a few dialect files and they all have short months specified

**Comment by marwahaha** [comment]
@forabi @abdelsaid approval?

**Comment by forabi** [comment]
They are the full month names. I don't see any PR with a fix. Problem is, there are 3 versions of month names used across different Arab countries and I'm not sure which should be used for the default generic Arabic locale. I'm not even sure which is used where.

**Comment by marwahaha** [comment]
Ok, if it varies across countries then we can leave as is. Thanks!

**Comment by forabi** [comment]
To be clear, the currently used full names are the version used in KSA but
the short names are not actually the shor equivalenta, they are exactly the
same full names. We could at least fix the short names to match KSA too for
consistency.

**Comment by tjgriffi** [comment]
Hey if this is still an issue I wouldn't mind tackling it.  We just want the short names to match the KSA short names right? (Not to make it sound simple)

**Comment by TheHandsomeCoder** [comment]
Did a quick look into this out of curiosity. Quick caveat being that I'm not a translator

To see what the Internationalization module would output I ran Node with the `full-icu` package enabled and the following snippet.

```javascript
const january = new Date(9e8);
const englishShort = new Intl.DateTimeFormat("en", { month: "short" });
const englishLong = new Intl.DateTimeFormat("en", { month: "long" });
const spanishShort = new Intl.DateTimeFormat("es", { month: "short" });
const spanishLong = new Intl.DateTimeFormat("es", { month: "long" });
const arabicShort = new Intl.DateTimeFormat("ar", { month: "short" });
const arabicLong = new Intl.DateTimeFormat("ar", { month: "long" });

console.log(englishLong.format(january), englishShort.format(january));
console.log(spanishLong.format(january), spanishShort.format(january));
console.log(arabicLong.format(january), arabicShort.format(january));
console.log(arabicLong.format(january) === arabicShort.format(january));
```

Which results in the following output.

```sh
January Jan
enero ene.
يناير يناير
true
```

It may be that there is no short form for months in `AR`

Similarly looking into the different dialects of `AR` in the moment codebase it seems that in the case of [ar-sa](https://github.com/moment/moment/blob/develop/locale/ar-sa.js#L36-L37) and [ar-dz](https://github.com/moment/moment/blob/develop/locale/ar-dz.js#L12-L13) the `month-short` options are the same as the `months` options.

**Comment by marwahaha** [comment]
Ok, I will close this.
If someone would like this changed, they can open a new issue or submit a PR.
Hope the confusion is cleared up.
