### ISSUE TITLE
Problems with Daylight Saving Time

### ISSUE THREAD

**Issue by ErickMaeda** [moment/moment#4892]
**Description of the Issue and Steps to Reproduce:**

In Brazil we case daylight saving moment. Ok but what happens?
I'm using this library on React Native. Just on Android causes the issue.
When I try to use moment in the summer end's day it back one day.

`moment('02/17/2019', 'MM/DD/YYYY').format('DD/MM/YYYY')` -> Output *16/02/2019*

Ok I know that if we use `.utc()` it fix the problem. But I'd love to have a solution that fix in all the codes that are using `moment()` in my application.

*Please include the values of all variables used.*

With format:
`console.log(moment('02/17/2019', 'MM/DD/YYYY').format('DD/MM/YYYY'))` -> Output **16/02/2019**

Without format:
`console.log(moment('02/17/2019', 'MM/DD/YYYY'))` -> Output **2019-02-17T02:00:00:000Z**

**Environment:**
- *Devices*
  - Android (5.0+) 
  - iOS is correct.

**Comment by ichernev** [comment]
@ErickMaeda how is this related to Daylight Savings Time?

Also the moment is not changing magically from the fact that you are/aren't using `format()` on it. Just call it with `.format()` and take a look at the result.

What version of moment is this with? Can you suggest a bare minimum setup that can reproduce this (assume I don't have any react native/android stuff on my computer).

**Comment by marwahaha** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
