### ISSUE TITLE
Problems with 24h time format

### ISSUE THREAD

**Issue by paul019** [moment/moment#4893]
**Description of the Issue and Steps to Reproduce:**
I've set the locale of momentjs to German and use the `format` function to get a formatted time string:

`moment(time).format('hh:mm [Uhr]'); `

However, I've set `time` to a JS Date object, that represents a time of 23:15 h. I expected to get back the string `23:15 Uhr`, but instead I got `11:15 Uhr`. What's happening here? Am I doing something wrong?

**Environment:**

`react native`

**Comment by Blastius** [comment]
You used `hh:mm` as format, `hh` gives back the 12h format. Try `HH:mm` as `HH` gives the 24h format. See https://momentjs.com/docs/#/displaying/format/

**Comment by paul019** [comment]
Thank you! That worked for me...
