### ISSUE TITLE
moment function is not accepting Asia/Calcutta but tz function is accepting

### ISSUE THREAD

**Issue by JRDuvvuri** [moment/moment#4898]
**Working :**  moment.tz("Asia/Calcutta").format('MMMM Do YYYY, h:mm:ss a');
**Not working :**  moment('December 11th 2018, 6:43:59 am',"Asia/Calcutta").tz("Asia/Calcutta").format('DD-MMM-YYYY hh:mm:ss a');

**why?**
script tags i am using 

1. <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.js"></script>
2. <script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.23/moment-timezone-with-data-2012-2022.min.js"></script>
3. <script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.23/moment-timezone-with-data-2012-2022.js"></script>

Please help.

**Comment by ashsearle** [comment]
The core `moment` function doesn't parse timezone _names_; that's what you use `moment.tz` for.

Compare documentation for parsing in [moment](https://momentjs.com/docs/#/parsing/string-format/) vs. [moment-timezone](https://momentjs.com/timezone/docs/#/using-timezones/parsing-in-zone/).

**Comment by JRDuvvuri** [comment]
Hey thank you, you are correct.
