### ISSUE TITLE
Bug with parsing iso formats

### ISSUE THREAD

**Issue by PhilipGarnero** [moment/moment#4900]
**Description of the Issue and Steps to Reproduce:**
We came across this issue while using the diff method with iso values.
We encountered negative values without understanding why it would happen.  
After some digging we found that when using iso years, the parser messes up the date.

You can look up the code here :

```js
import moment from 'moment'

const astr = '2018/06'
const bstr = '2017/12'

const a = moment(astr, 'GGGG/MM')
const b = moment(bstr, 'GGGG/MM')
const _a = moment(astr, 'YYYY/MM')
const _b = moment(bstr, 'YYYY/MM')

console.log(a, b)
console.log(a.valueOf(), b.valueOf(), a - b)

console.log(_a, _b)
console.log(_a.valueOf(), _b.valueOf(), _a - _b)
```

Output:
```
moment("2018-06-01T00:00:00.000") moment("2018-12-01T00:00:00.000")
1527804000000 1543618800000 -15814800000
moment("2018-06-01T00:00:00.000") moment("2017-12-01T00:00:00.000")
1527804000000 1512082800000 15721200000
```
**Environment:**
Everywhere we tried (chrome, repl.it, firefox)

**Other information that may be helpful:**

Here is the environment we have when running the code:
```js
Wed Dec 12 2018 19:27:56 GMT+0100 (Central European Standard Time)
12/12/2018, 19:27:56
-60
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
2.22.2
```

**Comment by ashsearle** [comment]
I think this is an invalid use of `GGGG`: you're using the ISO format for _Week Year_, but haven't specified a full date, or a week number, so moment doesn't know which week you're referring to.

How would you define the behaviour for this?

**Comment by PhilipGarnero** [comment]
Oh... I get it now. I think we should make that a lot more obvious in the docs. People don't automatically assume they can't use the year without the weeks.
Our behavior comes from the simple misunderstanding that these were ISO year that could work with ISO weeks but it never came across our mind that I should only be used with these weeks.
