### ISSUE TITLE
fromNow() doesn't support weeks

### ISSUE THREAD

**Issue by nanomosfet** [moment/moment#4901]
**Description of the Issue and Steps to Reproduce:**
Why does the `fromNow` function not support weeks?

It jumps from days ago -> months ago. Wouldn't the natural order be go from days to weeks? 

ex 1 week ago, 2 weeks ago, 3 weeks ago, etc. 
```
expect(moment().subtract(1, 'w').fromNow()).toEqual('1 week ago');
```

**Comment by nanomosfet** [comment]
I realized this would be a breaking change when I started implementing it, but it is very doable. Feel free to let me know if this is on the road map and I have a semi working version in my forks,

**Comment by ichernev** [comment]
Close in favor of #4910
