### ISSUE TITLE
Remove PhantomJS

### ISSUE THREAD

**Issue by marwahaha** [moment/moment#4902]
**Is your feature request related to a problem? Please describe.**
PhantomJS is no longer maintained, see  #4843 

**Describe the solution you'd like**
Find an alternative that allows for browser testing.

**Describe alternatives you've considered**
None yet

**Additional context**
see #4843

**Comment by harkue** [comment]
`puppeteer` maybe a good choice.

**Comment by marwahaha** [comment]
I think it is gone.
