### ISSUE TITLE
Can't set multiple relativeTimeThresholds with s and ss

### ISSUE THREAD

**Issue by nanomosfet** [moment/moment#4909]
**Describe the bug**

When you try to set multiple `relativeTimeThresholds` `fromNow` doesn't work as intended for the `'s'` and `'ss'` values.

**To Reproduce**
```js
moment.relativeTimeThreshold('ss', 1);

a = moment();

console.log(a.subtract(2, 's').fromNow()); // 2 seconds ago

moment.relativeTimeThreshold('s', 59);
a = moment();
console.log(a.subtract(2, 's').fromNow()); // a few seconds ago
```

**Expected behavior**
```js
moment.relativeTimeThreshold('ss', 1);

a = moment();

console.log(a.subtract(2, 's').fromNow()); // 2 seconds ago

moment.relativeTimeThreshold('s', 59);
a = moment();
console.log(a.subtract(2, 's').fromNow()); // 4 seconds ago
```
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

**Additional context**

**Comment by nanomosfet** [comment]
I think I found the problem
```
   // in src/lib/duration/humanize.js
    if (threshold === 's') {
        thresholds.ss = limit - 1;
    }
```
If you set 's' after you set 'ss' the problem will happen. 

A work around is setting 'ss' before you set 's'

**Comment by nanomosfet** [comment]
https://github.com/moment/moment/pull/4913

example of failing test.

Maybe we should also check if `threshold.ss` is greater than `limit`?

**Comment by marwahaha** [comment]
This behavior is documented:
https://momentjs.com/docs/#/customization/relative-time-threshold/
