### ISSUE TITLE
85 tests failed. locale:ja:meridiem invariant (1298.97) zones:global failure (3386.1) zones:global failure (3386.2) zones:global failure  (3387.1) zones:global failure  (3387.2) zones:global failure   (3388.1) zones:global failure   (3388.2) zones:global f

### ISSUE THREAD

**Issue by francisyzy** [moment/moment#4914]
### Client info
```
Date String   : Mon Dec 17 2018 14:09:33 GMT+0800 (+08)
Locale String : 12/17/2018, 2:09:33 PM
Offset        : -480
User Agent    : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15
Moment Version: 2.23.0
```

====

### locale:ja:meridiem invariant (1298.97) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure (3386.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure (3386.2) 

afterEach failed on global failure: Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure  (3387.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure  (3387.2) 

afterEach failed on global failure : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure   (3388.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure   (3388.2) 

afterEach failed on global failure  : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure    (3389.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure    (3389.2) 

afterEach failed on global failure   : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure     (3390.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure     (3390.2) 

afterEach failed on global failure    : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure      (3391.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure      (3391.2) 

afterEach failed on global failure     : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure       (3392.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure       (3392.2) 

afterEach failed on global failure      : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure        (3393.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure        (3393.2) 

afterEach failed on global failure       : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure         (3394.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure         (3394.2) 

afterEach failed on global failure        : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure          (3395.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure          (3395.2) 

afterEach failed on global failure         : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure           (3396.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure           (3396.2) 

afterEach failed on global failure          : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure            (3397.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure            (3397.2) 

afterEach failed on global failure           : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure             (3398.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure             (3398.2) 

afterEach failed on global failure            : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure              (3399.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure              (3399.2) 

afterEach failed on global failure             : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure               (3400.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure               (3400.2) 

afterEach failed on global failure              : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                (3401.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                (3401.2) 

afterEach failed on global failure               : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                 (3402.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                 (3402.2) 

afterEach failed on global failure                : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                  (3403.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                  (3403.2) 

afterEach failed on global failure                 : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                   (3404.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                   (3404.2) 

afterEach failed on global failure                  : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                    (3405.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                    (3405.2) 

afterEach failed on global failure                   : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                     (3406.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                     (3406.2) 

afterEach failed on global failure                    : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                      (3407.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                      (3407.2) 

afterEach failed on global failure                     : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                       (3408.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                       (3408.2) 

afterEach failed on global failure                      : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                        (3409.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                        (3409.2) 

afterEach failed on global failure                       : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                         (3410.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                         (3410.2) 

afterEach failed on global failure                        : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                          (3411.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                          (3411.2) 

afterEach failed on global failure                         : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                           (3412.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                           (3412.2) 

afterEach failed on global failure                          : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                            (3413.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                            (3413.2) 

afterEach failed on global failure                           : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                             (3414.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                             (3414.2) 

afterEach failed on global failure                            : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                              (3415.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                              (3415.2) 

afterEach failed on global failure                             : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                               (3416.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                               (3416.2) 

afterEach failed on global failure                              : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                (3417.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                (3417.2) 

afterEach failed on global failure                               : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                 (3418.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                 (3418.2) 

afterEach failed on global failure                                : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                  (3419.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                  (3419.2) 

afterEach failed on global failure                                 : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                   (3420.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                   (3420.2) 

afterEach failed on global failure                                  : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                    (3421.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                    (3421.2) 

afterEach failed on global failure                                   : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                     (3422.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                     (3422.2) 

afterEach failed on global failure                                    : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                      (3423.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                      (3423.2) 

afterEach failed on global failure                                     : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                       (3424.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                       (3424.2) 

afterEach failed on global failure                                      : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                        (3425.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                        (3425.2) 

afterEach failed on global failure                                       : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                         (3426.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                         (3426.2) 

afterEach failed on global failure                                        : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                          (3427.1) 

Script error.

```javascript
// Expected undefined
// Actual   null
null === undefined
```

====

### zones:global failure                                          (3427.2) 

afterEach failed on global failure                                         : Expected deprecation warnings did not happen: moment().zone

```javascript
// Expected undefined
// Actual   null
null === undefined
```

**Comment by marwahaha** [comment]
We can fix this if it comes up again...
