### ISSUE TITLE
Add explanation of different parsing modes to documentation

### ISSUE THREAD

**Issue by JonathanHolvey** [moment/moment#4918]
I found it difficult to work out how to parse an ISO 8601 string, eg `2018-12-13T13:10:20.123+10:00`, and maintain the offset from UTC, so that methods such as `startOf()` work in the specified time zone.

[An answer on StackOverflow](https://stackoverflow.com/a/34282009/3803805) has the details of how different parsing methods affect the timezone of resulting moment object, however I can't find this information in the documentation.

> - `moment(...)` is local mode. Ambiguous input (without offset) is assumed to be local time. Unambiguous input (with offset) is adjusted to local time.
> - `moment.utc(...)` is utc mode. Ambiguous input is assumed to be UTC. Unambiguous input is adjusted to UTC.
> - `moment.parseZone()` keep the input zone passed in. If the input is ambiguous, it is the same as local mode.
> - `moment.tz(...)` with the moment-timezone plugin can parse input in a specific time zone.

It would be good to have a short paragraph at the start of the [Parsing section](https://momentjs.com/docs/#/parsing/) of the docs to help avoid this kind of confusion.

**Comment by marwahaha** [comment]
Sounds good, please open a request at https://github.com/moment/momentjs.com
