### ISSUE TITLE
utcOffset is giving the wrong date

### ISSUE THREAD

**Issue by kambing86** [moment/moment#4919]
**Describe the bug**
utcOffset is giving wrong date

**To Reproduce**
1. Go to 'https://codesandbox.io/s/wwrjm6z4n8'
2. Check the code and result

**Expected behavior**
It should return correct datetime with timezone

**Screenshots**
![screen shot 2018-12-19 at 5 46 13 pm](https://user-images.githubusercontent.com/1342133/50212494-2919d200-03b6-11e9-95ca-a85f15e3d3a2.png)

**Desktop (please complete the following information):**
 - OS: mac osx
 - Browser: chrome
 - Version 71

**Moment-specific environment**

* The time zone setting of the machine the code is running on: 
+0800 Singapore timezone
* The time and date at which the code was run:
Wed Dec 19 2018 17:46:05 GMT+0800
* Other libraries in use (TypeScript, Immutable.js, etc):
Typescript

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

```
Wed Dec 19 2018 17:46:05 GMT+0800 (Singapore Standard Time)
19/12/2018, 17:46:05
-480
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
2.23.0
```

**Comment by kambing86** [comment]
seems like the issue is related to browser
new Date('0001-01-01T00:00:00')
Chrome v71: Mon Jan 01 0001 00:00:00 GMT+0655 (Singapore Standard Time)
Firefox v64: Date 0000-12-31T17:04:35.000Z
Safari v12.0.2: Mon Jan 01 0001 08:00:00 GMT+0800 (+08)

**Comment by kambing86** [comment]
it seems like it's related to this

https://medium.com/@rikdriever/javascript-date-issue-since-chrome-67-50aa555799d0

will close this once it's confirmed

**Comment by marwahaha** [comment]
Yes, this is the reason. 
Thanks for opening this request.
