### ISSUE TITLE
passing customization options to moment.locale makes locale revert to en-US

### ISSUE THREAD

**Issue by lunchboxer** [moment/moment#4923]
**Describe the bug**
According to the documentation I can pass an object with custom formats to moment.locale(), but doing so gives output in default locale (US).

**To Reproduce**
```
const moment = require('moment')
moment.locale('fr', {
  relativeTime: {
    past: '%s butt butt butt'
  }
})
const m = moment(new Date())
m.fromNow()
```
Above outputs "a few seconds butt butt butt" instead of "quelques secondes butt butt butt"

Providing no configuration object gives expected results:
```
const moment = require('moment')
moment.locale('fr')
const m = moment(new Date())
m.fromNow()
```
Above produces "il y a quelques secondes"

**Expected behavior**
I expect it to replace the one item in the locale configuration and set the locale, without reverting to en-US locale

**Moment-specific environment**
running in an express app with node v10.3.0

```
new Date()).toString()  // Sun Dec 30 2018 14:22:23 GMT+0800 (China Standard Time)
new Date()).toLocaleString() // 12/30/2018, 2:22:23 PM
new Date()).getTimezoneOffset() // -480
moment.version // 2.23.0
```

**Comment by OjasM** [comment]
Hi @lunchboxer ,

It seems like you need to use 

```
const moment = require('moment')    

moment.updateLocale('fr', {
 relativeTime: {
    past: '%s butt butt butt'
  }
})
const m = moment(new Date())
console.log(m.fromNow());

```

It works for me and even the docs mention the same -

```
// From 2.12.0 onward    
moment.updateLocale('en', {
    relativeTime : Object
});
```

**Comment by marwahaha** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
