### ISSUE TITLE
Date generated for 2018 off by 1 year (2019) 

### ISSUE THREAD

**Issue by clok** [moment/moment#4924]
**Describe the bug**
When generating a date with moment based off of year and week number, the dates for all weeks in 2018 are generated in 2019 instead.

**To Reproduce**
1. Open node console, load `moment`
2.Generate dates

```
> const moment = require('moment')
undefined
> moment().utc().year(2018).week(27)
moment.utc("2019-06-30T14:15:53.123+00:00")
> moment().utc().year(2017).week(27)
moment.utc("2017-07-08T14:15:59.483+00:00")
> moment().utc().year(2018).week(1)
moment.utc("2018-12-30T14:16:15.010+00:00")
> moment().utc().year(2018).week(2)
moment.utc("2019-01-06T14:16:17.688+00:00")
```

**Expected behavior**

We expect the correct date to be generated by moment. i.e. For a given week in 2018, a 2018 date is generated, not a 2019 date.

**Desktop (please complete the following information):**
 - OS: Mac OSX, ubuntu and Amazon Linux
 - Node: v8.11.3, v8.15.0

**Moment-specific environment**

* Timezones of machines: CDT, EDT and UTC
* 8 AM CDT on 2018/12/30
* Reproduced with no other libraries in use.

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

```
>  const moment = require('moment')
undefined
> console.log((new Date()).toString())
Sun Dec 30 2018 08:27:26 GMT-0600 (CST)
undefined
> console.log((new Date()).toLocaleString())
2018-12-30 08:27:27
undefined
> console.log((new Date()).getTimezoneOffset())
360
undefined
> console.log(navigator.userAgent)
ReferenceError: navigator is not defined
> console.log(moment.version)
2.22.2
```

**Additional context**
We have been running with this version of `moment` on our service for a year without issue.

**Comment by clok** [comment]
I have tried rolling back to 2.20.x and 2.19.x with no success. Bug still occurs. Upgrading to 2.23.0 still shows the error as well.

**Comment by aminebelhassine** [comment]
We had the same problem and it was highly critical for some of our applications in production. We resolved it quickly by the following trick : 

moment().week(52).year(2018) returns moment("2018-12-23T15:43:01.509")
moment().year(2018).week(52) returns moment("2019-12-23T15:43:01.516")

Juste reverse the week / year order and it should be ok.

**Comment by clok** [comment]
Thanks @animebelhassine!

We also found that the bug itself has to do with moment not correctly seeming the year when the year matches the current year. 

A work around that we pushed out yesterday was to force all year calls to `startOf`

Example:
```
moment.utc().year(x).startOf().week(y)
```

This protected us from the issue breaking production. 

I still feel this is a bug within moment though. Date math is hard, that’s why we rely on moment.

**Comment by OjasM** [comment]
Hi @clok 
Are you still getting the error? I am not able to reproduce it.

**Comment by aminebelhassine** [comment]
@clok nice workaround , yes it's really the kind of bugs that are unexpected to happen.
@OjasM actually it gives : 

moment("2018-12-25T13:46:00.389")
moment("2018-12-25T13:46:00.395")

The bug happened only on 30/31 - 18 and 1/19

And I had the same problem writing a sequence of day.week.year, i replaced by week.year.day to fix that.

**Comment by ashsearle** [comment]
@clok This doesn't look like a bug, it looks like a common mistake using `year()` instead of `weekYear()`.

Compare:
```js
moment('2018-12-31').utc().year(2018).week(27).toISOString(); // 2019-07-01T00:00:00.000Z
moment('2018-12-31').utc().weekYear(2018).week(27).toISOString(); // 2018-07-02T00:00:00.000Z
```

(Note: I used 31st instead of 30th December as that shows (and fixes) the problem in locales with weeks running Mon-Sun, as well as those running Sun-Sat like yours.)

**Comment by aminebelhassine** [comment]
@ashsearle how do you explain this : 

**NOW **
console.log(moment().week(52).year(2018).day("Sunday"));
console.log(moment().year(2018).week(52).day("Sunday"));
gives
moment("2018-12-23T20:28:08.912")
moment("2018-12-23T20:28:08.920")

On 31/12/18 ( you can set your computer clock to that date to test )
console.log(moment().week(52).year(2018).day("Sunday"));
console.log(moment().year(2018).week(52).day("Sunday"));
gives
moment("2018-12-23T20:27:36.561")
moment("2019-12-22T20:27:36.569")

Does putting year before week impacts the year calculation ?

**Comment by ashsearle** [comment]
`week()` is locale aware, `day()` isn't, and nor is `year()`.

> Does putting `year` before `week` impacts the year calculation ?

It impacts the intermediate and end results:

Now:
```js
moment()          // Thu Jan 3rd 2019
  .week(52)       // Thu Dec 26th 2019
  .year(2018)     // Wed Dec 26th 2018
  .day('Sunday'); // Sun Dec 23rd 2018

moment()          // Thu Jan 3rd 2019
  .year(2018)     // Wed Jan 3rd 2018
  .week(52)       // Wed Dec 26th 2018
  .day('Sunday'); // Sun Dec 23rd 2018
```

But, starting at 31st Dec 2018:
```js
moment()          // Mon Dec 31st 2018
  .week(52)       // Mon Dec 23rd 2019 (!)
  .year(2018)     // Sun Dec 23rd 2018
  .day('Sunday'); // Sun Dec 23rd 2018

moment()          // Mon Dec 31st 2018
  .year(2018)     // Mon Dec 31st 2018
  .week(52)       // Mon Dec 23rd 2019 (!)
  .day('Sunday'); // Sun Dec 22nd 2019
```

**Comment by k8n** [comment]
I'll add that ```moment("2018-12-31").format('YYYY[W]WW')``` produces `"2018W01"`, incorrect week number (the last day of 2018 is not in week 1).

**Comment by ashsearle** [comment]
@k8n You should use [`GGGG`](https://momentjs.com/docs/#/displaying/format/) with `WW` (or `gggg` with `ww` for non-ISO) as you're after the 'Week Year' in that case.

**Comment by clok** [comment]
Thank you for all the feedback on this. I can see how there is "user error" at fault. I can also see room for improvement on documentation when it comes to what to expect when making calls to `week` and `year` within the current year.

Ultimately, this issue forced us to perform a needed refactor across our stack to ensure that ALL points where we perform date math are using the same, locale aware, methodology.
