### ISSUE TITLE
moment().week() and moment().year() behaving inconsistently during this week

### ISSUE THREAD

**Issue by Kylar13** [moment/moment#4927]
**Describe the bug**
Using moment().week() returns week 1, but moment().year() still returns 2018, creating a lot of issues in our code

**To Reproduce**
1. Go to node console with moment installed
2. Use moment().week() and see that it returns 1st week of the year
3. Use moment().year() and see that it returns 2018 still

**Expected behavior**
Honestly, I'm not sure, I don't think the week number should change before the year has changed. Changing the year beforehand would be unexpected behaviour on itself, so I think the solution should be to allow for week 53 to exist in these cases

**Desktop (please complete the following information):**
 - Server: NodeJS using Typescript
 - Version 10.8.0

**Moment-specific environment**

Default settings, happening since yesterday 30/12/2018

**Comment by marcelpanse** [comment]
I have the same problem.. 
`console.log(moment().format('YYYY_WW')); //prints 2018_01`

I would expect it to print 2019_01, since it is the first week of 2019 (eventhough it started on dec 31).

Is there a way/workaround to get 2019_01 instead?

**Comment by Kylar13** [comment]
What we've done is updated our code so that if it's week 1, month 11 (We've checked and it returns month 11 correctly), hardcode year 2019.
Not ideal but does the job and we need to release a hotfix to production.

**Comment by stephanvane** [comment]
It's possible to get the *week-year* using `gggg`/`GGGG(ISO)` instead of `YYYY`. I think this would fix most problems in this case.

```javascript
moment('2018-12-31').format('GGGG_WW'); // "2019_01"
```
https://momentjs.com/docs/#week-year-week-and-weekday-tokens

**Comment by ashsearle** [comment]
@Kylar13 `year()` is not locale or week-aware.

For locale-dependent week + year, use [`week()`](https://momentjs.com/docs/#/get-set/week/) with [`weekYear()`](https://momentjs.com/docs/#/get-set/week-year/).
For ISO standard, use [`isoWeek()`](https://momentjs.com/docs/#/get-set/iso-week/) with [`isoWeekYear()`](https://momentjs.com/docs/#/get-set/iso-week-year/).

**Comment by sergioflores-j** [comment]
I'm facing the same issue

`moment('2018-12-31').format('WW/YYYY') // prints 01/2018`

Does anyone have a workaround for this?

**Comment by ashsearle** [comment]
@sereysethy Use `GGGG`.

`YYYY` is very simple: it's the year for the date: the `2018` in `2018-12-31`.
`GGGG` is more complex, it's the _ISO week year_, so in this case it's `2019` - which is what you want.

**Comment by ichernev** [comment]
@ashsearle oh my god, is this the only thing wrong with moment? We should celebrate!
