### ISSUE TITLE
Documentation for the parsing of a JQuery selector of an input

### ISSUE THREAD

**Issue by kyro38** [moment/moment#4928]
Hi,

I don't see any documentation for the parsing of a JQuery selector for an input. I was surprised it worked while the parsing of an element (retrieved by `getElementById`) returns an invalid date. 

Did I missed it or should a sub-(sub)section be added in the documention ? 

Thanks.

**Comment by ashsearle** [comment]
I don't think moment has any jQuery-aware code in it.

Can you share example code?

**Comment by kyro38** [comment]
For example I have a hidden input `<input type="hidden"  id="DateLimite" value="08/01/2019" tabindex="2" date-format="DD/MM/YYYY">` 

And `moment($('#DateLimite')).format()` returns a date.

**Comment by kyro38** [comment]
Wait, I'm feeling dumb. 

It returns the current date and not the date in my input. It does't work either with JQuery. 

I'm closing the issue !
