### ISSUE TITLE
Moment fails to convert to "YYYY-MM" and back in "2016-01-01".

### ISSUE THREAD

**Issue by dbsigurd** [moment/moment#4931]
**Describe the bug**
Converting from a Javascript date object to a moment object, extracting a "YYYY-WW" format, converting the extracted value to a moment and from that moment to a JS date object results in a invalid date.

**To Reproduce**
1. Open the developer console
2 .t = new Date("01-01-2016")
3.. m = moment(t);
4. moment(m.format("YYYY-WW"),"YYYY-WW").toDate()

**Expected behavior**
For the date to be valid and near the original date.

**Screenshots**
![image](https://user-images.githubusercontent.com/8729622/50714107-b0ad4500-1034-11e9-9f44-225a9b018a0e.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version 2.23

**Moment-specific environment**

* GMT-0700
* 

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
Fri Jan 04 2019 15:24:45 GMT-0700 (Mountain Standard Time)
VM94005:2 1/4/2019, 3:24:45 PM
VM94005:3 420
VM94005:4 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
VM94005:5 2.23.0

**Additional context**
2016 is a leap year. Your conversion of m.format("YYYY-WW") results in 2016-53. Moment is unable to convert this back to a date.

**Comment by ashsearle** [comment]
You need to use [`GGGG`](https://momentjs.com/docs/#/displaying/format/) instead of `YYYY` as you're trying to parse/format _week years_ not the date's year.

```js
// Bad
moment(moment('2016-01-01').format("YYYY-WW"),"YYYY-WW").toDate()
// Good
moment(moment('2016-01-01').format("GGGG-WW"),"GGGG-WW").toDate()
```

**Comment by ichernev** [comment]
@ashsearle you could write a bot that detects YYYY and GG in the same sentence and automatically answer with that :D
