### ISSUE TITLE
29 of March 2019 returns a very weird result (Android only). 

### ISSUE THREAD

**Issue by dmitryguesty** [moment/moment#4932]
**Describe the bug**
Same as a bug that was closed due to lack of info:
30 of March 2014 returns a very weird result #1568

**To Reproduce**
Steps to reproduce on React Native, Android only, Debug Mode turned Off:

1. 23 March 2018.
moment("2018/03/23").format("DD")
returns: 22

2. 29 March 2019.
moment("2019/03/29").format("DD")
returns: 28

3. 27 March 2020.
moment("2020/03/27").format("DD")
returns: 26

**Expected behaviour**
1. 23 March 2018.
moment("2018/03/23").format("DD")
returns: 23

2. 29 March 2019.
moment("2019/03/29").format("DD")
returns: 29

3. 27 March 2020.
moment("2020/03/27").format("DD")
returns: 27

**Screenshots**

![screen shot 2019-01-06 at 19 13 29](https://user-images.githubusercontent.com/38178646/50739428-d2e7c400-11e8-11e9-8c6a-3d357d0fed46.png)

Company calendar shows incorrect dates.

We found workaround 
const parsedDate = moment(new Date("2020/03/27")).format("DD")
In that way it parsed correctly and returns: 27

**Desktop (please complete the following information):**
 - OS: Android
 - React Native
 - Versions - "moment": "2.22.2","react-native": "0.55.4",
 - Debug mode should be OFF, otherwise JS is running on Chrome and it cannot be reproduced.

**Smartphone (please complete the following information):**
 - Device: Any Android

**Additional context**
It happens on March on different days in each year.

**Comment by dmitryguesty** [comment]
If you upgrade your Android to 8.0.0 it fixes the problem.

**Comment by ericktatsui** [comment]
> If you upgrade your Android to 8.0.0 it fixes the problem.
Awesome solution, it made my day.

**Comment by SaeedZhiany** [comment]
@dmitryguesty 

I have this problem too. the problem occurs on `YYYY/03/22` (22 merch every year) in my case. `moment("2018/03/22").toDate()` returns `2019-03-21T19:30:00.000Z`. therefore I cannot select 22 march on my custom datePicker component. 

Have you any idea How can I solve my problem? (I have to support android minSdk 16, so upgrading to android 8 is not an option. also, I tried the debug mode ON, besides what you said, the behavior is correct on this mode and the incorrect behavior occurs in debug mode OFF and release mode.

Thanks
