### ISSUE TITLE
Date generated Off by 1 year when using utc format

### ISSUE THREAD

**Issue by ricardoMogg** [moment/moment#4937]
I got an off by 1 year date when using this during the last hour of the year:

```

moment.utc().format('YYYY-MM-DDTHH:mm:ss.SSSZ')
// this gave me results like 2019-12-31T23:57:45.663+0000 instead of 2018-12-31T23:57:45.663+0000

```

Version I was using is 2.20.1

**Comment by ichernev** [comment]
You didn't say which timezone you are in, and what time did this happen. I assumed it was related to local time being in 2019 while utc being in 2018, tested it, and it worked flawlessly.

```
> moment.utc().format('YYYY-MM-DDTHH:mm:ss.SSSZ')
'2018-12-31T23:42:01.719+00:00'
> moment().format('YYYY-MM-DDTHH:mm:ss.SSSZ')
'2019-01-01T01:42:07.681+02:00'
```

So if you can provide some more info so that it is actually reproducible it will help a lot!

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
