### ISSUE TITLE
Format does not work correctly for 52 Week Years

### ISSUE THREAD

**Issue by billywhizz** [moment/moment#4938]
**Describe the bug**
We have come across an issue that seems to me would be best fixed inside the moment-timezone or the moment library rather than end users having to implement their own logic to handle it.

Is related to this issue: https://stackoverflow.com/questions/25631682/moment-js-thinks-that-2013-12-31-is-week-1-not-week-53

**To Reproduce**
Here is a gist that shows what happens when we do .format('YYYY-w') when current date is in previous year but the week ends in the following year and the previous year is a 52 week year: https://gist.github.com/billywhizz/1b5affc4b3d915039c03f510b0a04e8b

You can also see how it returns incorrect year with this code:
```
moment('2019-1', 'YYYY-W').format('[Week] W, YYYY')
```
you get the answer "Week 1, 2018" instead of "Week 1, 2019" which i would expect to see.

**Expected behavior**
I think it would be more correct if the library return "2019-01" when operating on 2018-12-31. In this case it currently returns '2018-01' which is not correct. it rolls the week over from 52 to 1 but does not roll the year in same way.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Any OS (Linux/Ubuntu 18 tested)
 - Browser: Any

**Moment-specific environment**

Time Zone: All

Please run the following code in your environment and include the output:
```
Tue Jan 08 2019 22:35:20 GMT+0000 (GMT)
2019-1-8 22:35:20
0
N/A
2.20.1
```

**Comment by sateffen** [comment]
I ran into the same problem, but somehow this is not as trivial as I first thought, so here a little note to think about:

When using `WW YYYY` as a format for 2018-12-31 you'd expect `01 2019` as output, but as soon as you add any other format-elements you won't expect the year to show up as 2019, for example: `WW MM-YYYY` or `WW DD-MM-YYYY`. So, depending on the elements in the format, you'd expect a different output for YYYY for the same input-date, which is somewhat strange...

So, in my opinion, changing the behaviour of YYYY for the edgecase, that there is only a `w, ww, W, WW` with it in the format, would be wrong.  For that kind of date there should be a format option, which is week-aware, like adding a `J, JJ, JJJ, JJJJ` option (J for Jahr in german :-D), or `WY` or so. That would bea nice option in my opinion: A week-aware year-format.

**Comment by ashsearle** [comment]
@billywhizz: You need to use 'week year' format codes: `GGGG` with `W`, or `gggg` with `w`.

**Comment by billywhizz** [comment]
@sateffen yes, i agree it's not necessarily a "bug" and difficult to know how best to handle it but i think it should be handled within moment library rather than everyone writing their own version of the logic.

@ashsearle thanks! that is useful. it resolves the issue i have been having. i.e. this
```
console.log(moment('2019-1', 'YYYY-W').format('[Week] W,'gggg'))
```
correctly prints 'Week 1, 2019' instead of 'Week 1, 2018'

and this now works as expected
```
const moment = require('moment-timezone')

function test(dateString) {
    const now = Date.parse(dateString)
    const tz = 'Europe/London'
    const start = moment(now).tz(tz).startOf('week')
    const week = start.format('gggg-w')
    console.log(`${dateString}: ${week}, start: ${start}`)
}

test('2013-12-31')

test('2016-12-31')
test('2017-01-01')
test('2017-12-04')
test('2017-12-11')
test('2017-12-18')
test('2017-12-25')
test('2017-12-29')
test('2017-12-30')
test('2017-12-31')
test('2018-01-01')


test('2018-12-03')
test('2018-12-10')
test('2018-12-17')
test('2018-12-24')
test('2018-12-30')
test('2018-12-31')
test('2019-01-01')
test('2019-01-06')
test('2019-01-07')

console.log(moment('2019-1', 'YYYY-W').format('[Week] W, gggg'))
```
produces
```
2013-12-31: 2014-1, start: Sun Dec 29 2013 00:00:00 GMT+0000
2016-12-31: 2016-53, start: Sun Dec 25 2016 00:00:00 GMT+0000
2017-01-01: 2017-1, start: Sun Jan 01 2017 00:00:00 GMT+0000
2017-12-04: 2017-49, start: Sun Dec 03 2017 00:00:00 GMT+0000
2017-12-11: 2017-50, start: Sun Dec 10 2017 00:00:00 GMT+0000
2017-12-18: 2017-51, start: Sun Dec 17 2017 00:00:00 GMT+0000
2017-12-25: 2017-52, start: Sun Dec 24 2017 00:00:00 GMT+0000
2017-12-29: 2017-52, start: Sun Dec 24 2017 00:00:00 GMT+0000
2017-12-30: 2017-52, start: Sun Dec 24 2017 00:00:00 GMT+0000
2017-12-31: 2018-1, start: Sun Dec 31 2017 00:00:00 GMT+0000
2018-01-01: 2018-1, start: Sun Dec 31 2017 00:00:00 GMT+0000
2018-12-03: 2018-49, start: Sun Dec 02 2018 00:00:00 GMT+0000
2018-12-10: 2018-50, start: Sun Dec 09 2018 00:00:00 GMT+0000
2018-12-17: 2018-51, start: Sun Dec 16 2018 00:00:00 GMT+0000
2018-12-24: 2018-52, start: Sun Dec 23 2018 00:00:00 GMT+0000
2018-12-30: 2019-1, start: Sun Dec 30 2018 00:00:00 GMT+0000
2018-12-31: 2019-1, start: Sun Dec 30 2018 00:00:00 GMT+0000
2019-01-01: 2019-1, start: Sun Dec 30 2018 00:00:00 GMT+0000
2019-01-06: 2019-2, start: Sun Jan 06 2019 00:00:00 GMT+0000
2019-01-07: 2019-2, start: Sun Jan 06 2019 00:00:00 GMT+0000
Week 1, 2019
```

**Comment by ashsearle** [comment]
@billywhizz Just as an FYI: this line contains a mix of locale and ISO formatting codes:

```js
console.log(moment('2019-1', 'YYYY-W').format('[Week] W, gggg'))
```

You need to make a choice:
* use locale-aware codes: `'[Week] w, gggg'`
* use ISO codes ``'[Week] W, GGGG'``

ISO codes will always be based on Monday-Sunday week, with week 1 containing Jan 4th.
Locale codes will be... variable.  They _might_ match ISO, but often don't.

**Comment by ichernev** [comment]
Thank you @ashsearle 

@billywhizz I know you want moment to be easy and handle all use cases with zero user intervention, but unfortunately time is more complicated than it looks like. The only think that is thinkable, is to have a special warning printed out when you mix week tokens and year tokens (that are not week-year tokens). But for some that might be useful. Also its not wrong per-se, more like babysitting to an extend I don't approve.

If you want to work with the "week calendar", you should use `gggg`, `w` and `GGGG`, `W` accordingly (for local and ISO week-calendars respectively). If you want to work with day-month-year, then you use the YYYY-MM-DD tokens. Mixing yyyy and w tokens is asking for trouble. That's it.
