### ISSUE TITLE
isBetween argument "undefined" treated as a moment

### ISSUE THREAD

**Issue by CH-IanaAndrychowicz** [moment/moment#4940]
**Describe the bug**
When the first argument to isBetween method is a valid date before the moment being compared, and the second argument is an invalid date (like `undefined`), the method returns true.
Example: 
```
moment('2019-01-01').isBetween(moment('2018-01-01'), undefined);
=> true
```

**To Reproduce**
1. Go to 'http://jsfiddle.net/rLjQx/161901/'
2. Click on 'run'

**Expected behavior**
isBetween returns false for all invalid dates

**Screenshots**

**Version**
v2.23.0

**Comment by ichernev** [comment]
Thank you @CH-IanaAndrychowicz for the report.

In general `isBetween` returns false if one of its arguments (or the object being called on) are invalid. However `undefined` has this special meaning in javascript of 'nothing', and when you call moment constructor with 'nothing' you get `now`. This is pervasive in the entire codebase, in some places its makes more sense than others. In this case it makes less sense, I can agree with you on that!

To fix this properly would mean to change all such places (basically all methods accepting a moment-like object), and quite possibly breaking a lot of code that already depends on that. I don't think this is wise for 2.x release, maybe 3.x when that comes out :)

**Comment by CH-IanaAndrychowicz** [comment]
Ah, it makes sense, of course. 
What throw me off is the changelog line `#4417 [bugfix] isBetween should return false for invalid dates`, but of course the result of `moment(undefined)` is a valid date. 
Would be nice to have that caveat mentioned in the docs (unless it already is I just don't know where to look). Thanks for your prompt reply and friendly explanation!

**Comment by marwahaha** [comment]
@CH-IanaAndrychowicz I've added this to the documentation here:
https://github.com/moment/momentjs.com/commit/1f88251ba00e975091d2fc3964f5e6b8c633bdaa

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
