### ISSUE TITLE
Date does not parse, while another date in the same format does

### ISSUE THREAD

**Issue by MelleB** [moment/moment#4941]
**Describe the bug**
For some reason date parsing yields invalid dates. While the format seems to be correct. I suspect this is due to the fact that the date is in the last week of the year, but that's only a hunch. 

**To Reproduce**

    > const moment = require('moment')
    > const fmt = 'ddd MMM DD HH:mm:ss \\C\\E\\T gggg'
    > moment('Fri Dec 28 15:36:16 CET 2018', fmt)
    moment.invalid(/* Fri Dec 28 15:36:16 CET 2018 */)
    > moment('Fri Jan 11 17:27:00 CET 2019', fmt)
    moment("2019-01-11T17:27:00.000")

**Expected behavior**
I expect the first date to be a valid.

**Version (please complete the following information):**
 - NodeJS: v8.14.1
 - Moment: v2.23.0

**Moment-specific environment**

* The time zone setting of the machine the code is running on: CET
* The time and date at which the code was run: see below
* Other libraries in use (TypeScript, Immutable.js, etc): None

Please run the following code in your environment and include the output:
```
> console.log((new Date()).toString())
Thu Jan 10 2019 19:48:00 GMT+0100 (CET)
> console.log((new Date()).toLocaleString())
2019-1-10 19:48:00
> console.log((new Date()).getTimezoneOffset())
-60
> console.log(navigator.userAgent)
ReferenceError: navigator is not defined
> console.log(moment.version)
2.23.0
```

**Additional context**
Examples tested in node REPL

**Comment by ichernev** [comment]
It's good that you're expecting some things to happen, because moment also expects things to happen!

For example when you have a date, including a week day, moment expects the weekday to match the rest of the date. If it doesn't the date is invalid:

```javascript
> moment('Sat Dec 28 15:36:16 CET 2018', fmt) // moment("2019-12-28T15:36:16.000")
> moment('Fri Dec 28 15:36:16 CET 2018', fmt); // moment.invalid(/* Fri Dec 28 15:36:16 CET 2018 */)
> moment('Fri Dec 28 15:36:16 CET 2018', fmt).parsingFlags()
{ empty: false,
  unusedTokens: [],
  unusedInput: [],
  overflow: -1,
  charsLeftOver: 0,
  nullInput: false,
  invalidMonth: null,
  invalidFormat: false,
  userInvalidated: false,
  iso: false,
  parsedDateParts: [ <1 empty item>, 11, 28, 15, 36, 16 ],
  meridiem: undefined,
  rfc2822: false,
  weekdayMismatch: true } // LOOK HERE
```

You can also expect to find the reason for this using `parsingFlags()`.

**Comment by stefandoorn** [comment]
@ichernev Interesting thing here is though that Dec 28 in 2018 was a Friday, so that matches the input if I'm correct and should not become invalid due to mismatching as you've shown here:

```
> moment('Fri Dec 28 15:36:16 CET 2018', fmt); // moment.invalid(/* Fri Dec 28 15:36:16 CET 2018 */)
```

I'm not sure why Sat Dec 28 2018 gets parsed into 2019-12-28 btw, as that's a year forward.

**Comment by ichernev** [comment]
Because you use `gggg` instead of `yyyy`. `G` is for week-year and `Y` is for regular years.
