### ISSUE TITLE
TypeScript usage documentation is wrong: "Cannot find module 'moment'.ts(2307)" 

### ISSUE THREAD

**Issue by andy1547** [moment/moment#4946]
This issue seems to affect basic usage in a TypeScript environment without any extras, just vanilla TypeScript to ES5 + AMD. 

The uploaded sample project has two dependencies: TypeScript 3.2.2 and moment 2.23.0 (my local environment uses NPM 6.5.0).
To setup run "npm install" and to compile run "npm run compile"
[food-store.zip](https://github.com/moment/moment/files/2752188/food-store.zip)

The following line in FoodStore triggers a TypeScript compiler error: `import * as moment from "moment";`

I've also tried enabling `"allowSyntheticDefaultImports": true` and importing with `import moment from 'moment';` but it gives the same error message.

Looking at moment.d.ts, it seems like they follow all the recommended practises in the TypeScript handbook (https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#template).
Should I be using the following syntax to import `import moment= require("moment")` (as suggested in the TypeScript handbook
https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require)?

Is it possible to provide some guidance on basic TypeScript usage in your documentation? Thanks in advance.

**Comment by andy1547** [comment]
Workaround is `{ "moduleResolution": "node", "baseUrl": "src" }`, can this be added to the documentation?

**Comment by stephaneworkspace** [comment]
thanks andy1547 work for me

**Comment by waseemahmad31** [comment]
@marwahaha , @andy1547  I have updated the documentation for this in the below pull request:
[moment/momentjs.com@551](https://github.com/moment/momentjs.com/pull/551). Please review it.

**Comment by andy1547** [comment]
Thanks @marwahaha and @waseemahmad31!
