### ISSUE TITLE
Bug in updateLocale: resetting doesn't work

### ISSUE THREAD

**Issue by kumarharsh** [moment/moment#4962]
**Describe the bug**
Say moment's locale is updated to have a different `week.dow`: `moment.updateLocale(moment.locale(), { week: { dow: 4 } })`. Later, if this locale is reset using `moment.updateLocale(moment.locale(), null)`, then it's observed that the locale is not reset cleanly. I was trying to use this approach in Jest, but it's not working.

**To Reproduce**
1. Go to https://codesandbox.io/s/qqjm33km19
2. See output.

**Expected behavior**
The second date should have been `2018-12-30` because the default locale is 'en' and default week.dow is `0` (Sunday).

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 71

**Moment-specific environment**

* The time zone setting of the machine the code is running on: en-IN
* The time and date at which the code was run: 2019-01-22 19:10
* Other libraries in use (TypeScript, Immutable.js, etc): React

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

```
Tue Jan 22 2019 19:09:50 GMT+0530 (India Standard Time)
1/22/2019, 7:09:50 PM
-330
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
2.24.0
```

**Comment by ashsearle** [comment]
Yep, it's a bug.

moment's resetting the locale OK, but holding onto a global reference.

See the updated [codesandbox](https://codesandbox.io/s/2w8x7648kp) for how to manually avoid this pending a new release with the bug fix.
