### ISSUE TITLE
Conflict with Wordpress 5.0.3

### ISSUE THREAD

**Issue by kkranzo** [moment/moment#4964]
I am using moment.js version 2.15.2 and momentTimezone.js version 0.5.10 on my site. Everything has worked fne and I have been on Wordpress version 4.9.4. I recently upgraded to Wordpress 5.0.3 and now moment.js is throwing a typeError error.

If you have those versions and install Wordpress 5.0.3 you can see the errors.

Do I need to update moment.js and momentTimezone.js in order for them to be compatible with the latest Wordpress version? Is there a reason why those older versions won't work?

**Comment by ashsearle** [comment]
@kkranzo Please update moment and moment-timezone to the latest versions and - if you still see errors - please provide more information: e.g. any error text / stack trace / input strings and formats being used etc.

**Comment by kkranzo** [comment]
@ashsearle - The error is still present when updating moment and moment-timezone to the latest versions. Below are the errors received in console:

TypeError: moment is undefined
TypeError: moment(...).tz is not a function

This error was not present pre WP 5.0+

**Comment by kkranzo** [comment]
@ashsearle - I discovered the issue. WP 5.0+ utilizes moment.js as well, so there was a conflict with enqueuing the moment script and naming it "moment". WP uses the same name so it wasn't loading the moment.js script and therefore momentTimezone was being uses without moment.js loading first.

**Comment by ashsearle** [comment]
@kkranzo Thanks for the update identifying the root cause.

Out of interest, how did you resolve the conflict?

**Comment by kkranzo** [comment]
@ashsearle - I ended up just changing the name of the registered script in my functions.php file from this:

wp_register_script('moment')

To this:

wp_register_script('momentScript')

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
