### ISSUE TITLE
JA long month formatting broken in 2.24.0

### ISSUE THREAD

**Issue by romkhub** [moment/moment#4965]
this fix - https://github.com/moment/moment/pull/4590 - did actually broken JA long month formatting.
the doc referenced in PR (http://cldr.unicode.org/translation/date-time-patterns#TOC-Basic-Date-Formats) states:
```
For some languages, long months are not used; for example, in Japanese the numeric month is used in patterns, in front of the character 月.
```

http://jsfiddle.net/6unkyejc/1/
expected `日曜日 4月 2014`

**Comment by jonnysmith1981** [comment]
Not sure if this is related but Japanese day suffixes no longer work either 
[https://plnkr.co/edit/I00B5MevtTgyKIFwp7tH?p=preview](https://plnkr.co/edit/I00B5MevtTgyKIFwp7tH?p=preview)

**Comment by Kazuki-Taniguchi** [comment]
Hello @romkhub ,
Is there any update on this since then ?
Thank you .
- Kazuki Taniguchi
