### ISSUE TITLE
Wrong initial DST Date for Brazil - 2018 (not 22/Oct but 04/nov)

### ISSUE THREAD

**Issue by hansbrito** [moment/moment#4967]
**Describe the bug**
Initial Date of Brazilian DST is wrong, isn't 22/October/2018 but 04/November/2018.
Please check the nexts DST Date because the rule changed to First Sunday of November.

**To Reproduce**
1. Try to parse a Local DateTime  like 21/10/2018 and 23/10/2018

**Expected behavior**
Only dates after 03/November/2018 are in Daylight Savings Time

**Screenshots**
![image](https://user-images.githubusercontent.com/10194128/51567846-61ae3f00-1e7f-11e9-83a7-aa17e1ba05b3.png)

**Comment by ashsearle** [comment]
The core moment library doesn't contain any DST start/end information - it relies on information from the runtime (e.g. the browser, or node, either of which may rely on the O/S for DST information.)

Did you mean to log this issue against the moment-timezone project instead?  (If so, there's an [issue about the Brazilian government cancelling the DST change](https://github.com/moment/moment-timezone/issues/683) that you might want to look at.)
