### ISSUE TITLE
Make "format" accept a function

### ISSUE THREAD

**Issue by ebuildy** [moment/moment#4973]
**Is your feature request related to a problem? Please describe.**
I want to dynamically format a date:

- if today => display only hour
- if < 7 days => display "2 days ago"
- if same year => "DD/MM"
- Else "MM/YYYY

**Describe the solution you'd like**
```
moment().format(date => {
if (date...) { return "DD/MM";
...
return "MM/YYYY";
})

**Comment by marwahaha** [comment]
You can do this now outside of moment:
```
if (moment().diff(moment('2019-01-01'), 'days') > 7) {
...
}
```

**Comment by Neo-C132** [comment]
bbkhjbkbkbkjbkjbn

**Comment by ashsearle** [comment]
@ebuildy Your 'x days ago' requirement means you can't use `format` on its own.  I'd suggest a custom function instead.

Rushed code:
```js
moment.fn.ebuildy = function() {
  const now = moment();
  if (this.isSame(now, 'day')) {
    return this.format('HH:mm');
  } else if (this.isBefore(now, 'days') && this.diff(now, 'days') > -7) {
    return this.fromNow();
  } else if (this.year() === now.year()) {
    return this.format('DD/MM');
  } else {
    return this.format('MM/YYYY');
  }
};
```

Example usage:
```js
[
  moment(),
  moment().subtract(3, 'days'),
  moment().subtract(10, 'days'),
  moment().subtract(1, 'year'),
].forEach(mo => {
  console.log(mo.ebuildy());
});

/*
Output:
14:08
3 days ago
21/01
01/2018
*/
```

**Comment by emer7** [comment]
Hi is this issue can be worked on or it is going to be closed?

**Comment by marwahaha** [comment]
For now, we will not take this change.
