### ISSUE TITLE
isBetween works incorrectly with undefined

### ISSUE THREAD

**Issue by iamtonny** [moment/moment#4978]
**Describe the bug**
Hi guys, function **isBetween** sometimes works incorrectly with undefined as date_end. The function returns sometimes false sometimes true.

![image](https://user-images.githubusercontent.com/10379871/52111897-1120a980-2616-11e9-960a-f9b3896ed307.png)

**Comment by marwahaha** [comment]
This is documented.
https://momentjs.com/docs/#/query/is-between/

Passing `undefined` results in a new `moment()` created, which is sometimes created in the same millisecond as your `moment()`, but sometimes not.

Please re-open if you still have issues.
