### ISSUE TITLE
the `format` method rounds the date up

### ISSUE THREAD

**Issue by souserge** [moment/moment#4980]
**Describe the bug**
Formatting of the date representing the end of month to YYYY-MM-DD unexpectedly rounds the date up.

**To Reproduce**
```javascript
moment('1983-12-31T23:59:59.999Z').format('YYYY-MM-DD')
// output: '1984-01-01'
```

**Expected behavior**
output: `'1983-12-31'`

**Screenshots**
![image](https://user-images.githubusercontent.com/15277406/52117613-6bb90600-2614-11e9-89c5-6b8c013086ad.png)

**Desktop**
 - OS: macOS Mojave 10.14.2
 - Environment:  Firefox 64.0.2 (64-bit), Google Chrome 71.0.3578.98 (Official Build) (64-bit), node v11.6.0

output of the code run in node:
```
> console.log((new Date()).toString())
Fri Feb 01 2019 11:33:59 GMT+0100 (Central European Standard Time)
> console.log((new Date()).toLocaleString())
2/1/2019, 11:33:59 AM
> console.log((new Date()).getTimezoneOffset())
-60
> console.log(navigator.userAgent)
ReferenceError: navigator is not defined
> console.log(moment.version)
2.24.0
```

**Comment by vigneshrajarr** [comment]
The `moment(string)` and `moment.utc(string)` takes the offset and updates the time to local time or UTC respectively. So,

```
var date = moment('1983-12-31T23:59:59.999Z');

console.log(date.toString());
----Sun Jan 01 1984 05:29:59 GMT+0530
console.log(date._d);
----Sun Jan 01 1984 05:29:59 GMT+0530 (India Standard Time)
console.log(date.format("YYYY-MM-DD:HH-mm-ss Z"));
----1984-01-01:05-29-59 +05:30
```
So, to convert the date without considering the timezone, use `.parseZone()`.
```
moment.parseZone('1983-12-31T23:59:59.999Z').format('YYYY-MM-DD');
----1983-12-31
```
Since no zone is passed in the date `.utc()` can be used too.
```
moment.utc('1983-12-31T23:59:59.999Z').format('YYYY-MM-DD');
----1983-12-31
```

**Comment by marwahaha** [comment]
Try 
```
moment.utc('1983-12-31T23:59:59.999Z').format('YYYY-MM-DD')
```

Please re-open if you still have issues.
