### ISSUE TITLE
Moment object contains incorrect date in _d property value.

### ISSUE THREAD

**Issue by iSerganov** [moment/moment#4982]
Moment object contains wrong date in **_d** property value.

**To Reproduce**
1. Set local timezone in moment globally: `moment.tz.setDefault(Intl.DateTimeFormat().resolvedOptions().timeZone)`
2. Instantiate moment passing any string in ISO8601 format using UTC timezone, e.g. : "2019-01-31T22:00:00Z". (My local timezone is GMT+02:00)
3. Check the result:
![image](https://user-images.githubusercontent.com/41109559/52157752-217a6800-269a-11e9-864d-c24f462ab6e9.png)
4. So format() function on that object returns correct string:
"2019-02-01T00:00:00+02:00"
5. But **._d.toISOString()** returns incorrect date string: "2019-02-01T00:00:00.000Z" which confirms storing incorrect Date object as a value of **_d** property.

**Expected behavior**
._d.toISOString() should return exactly the same date string which was originally passed to moment constructor on step 2: "2019-01-31T22:00:00Z"

 - Browser Chrome
 - Version 2.22.2

**Comment by CKunhardt** [comment]
Also experiencing this, a temporary workaround if you need to display UTC moments in local time is to instantiate a new moment object using the _i property -- moment(myMoment._i) should create a new local moment with the correct date when formatting.

**Comment by ashsearle** [comment]
@iSerganov-andersen Why do you care what value `_d` has?  It's an internal field, not part of the documented API; and it's just _part_ of the value used when formatting or manipulating.  i.e. `momen().toISOString()` is not the same as `moment()._d.toISOString()`

**Comment by iSerganov-andersen** [comment]
@ashsearle, I am not using it directly.
However once I have been debugging the work of the library in order to understand what is there under the hood, I found this behavior. I realize that this is a kind of "technical metadata". However due to the fact that moment object is a kind of wrapper above Date object and I guess _d field is something intended to store the wrapped(original) Date, to the best of my beliefs it is a real trouble.

**Comment by ashsearle** [comment]
@iSerganov-andersen It's no trouble.  Take a look at your screenshot again armed with the knowledge that `_d` and `_offset` are used together.  i.e. `_offset` accounts for the 2 hour difference you thought was a problem.

**Comment by iSerganov-andersen** [comment]
In other words the library's design built on the incorrect Date object assigned to the _d property if I understand you correctly? If I am mistaken, just for my understanding, could you please specify what exactly _d property stands for?

**Comment by ashsearle** [comment]
@iSerganov-andersen The library uses the only native date implementation available: `Date`.

There's no option in a native `Date` for setting the time zone, so moment keeps that separately.

If you use the public API and call `toISOString()` on the moment the date in `_d` will be adjusted by 2 hours (using `_offset`) and give you the correct answer `"2019-01-31T22:00:00Z"`.

This isn't a bug, it's just the way the library works.  You're free to disagree with the design decisions and compromises made to make things work.

**Comment by CKunhardt** [comment]
Not sure if you were having this, but in my case, the _d field was storing the first of the month with the correct timezone offset. So a UTC object storing the date 2018-08-16 (YYYY-MM-DD), for example, was turning into 2018-08-01 when converted to local time, albeit with the correct time. When I inspected the original UTC moment, the _i field was correct, but the _d field was set to the first of the month -- it seems the issue goes beyond just a time offset.

**Comment by iSerganov-andersen** [comment]
@ashsearle, well...
I believe you may close this issue.
Thank you for your clarifications.

**Comment by marwahaha** [comment]
If there's something worth documenting here, we'll take a PR against
https://github.com/moment/momentjs.com
