### ISSUE TITLE
[Feature Request] Add global option to raise errors on invalid dates or fallbacks to `new Date(d)`

### ISSUE THREAD

**Issue by andreynering** [moment/moment#4985]
Something that frustrates me on Moment is that it's hard to debug problems when an `Invalid date` pops somewhere but you don't know where it came from. I think Moment should have a global option to just throw an error on invalid dates.

An error screams in your face you have a problem, and come with a stack trace to know where it came from.

Even if someone doesn't want to enable it on production, it'd useful on debugging situations. In my case, though, I'd have it even on production, so errors would pop on Sentry and console, etc.

Additionally, it'd be nice to have a global option to raise if Moment have to fallback to `new Date(d)` due a missing format argument, instead of just showing a warning.

**Comment by MichaelYogar** [comment]
Hi, I'm looking to make my first open source contribution. Is this feature still needed? If so, I can try to do this.

**Comment by marwahaha** [comment]
@MichaelYogar no, sorry, if one is implemented I will take the existing PR.

**Comment by marwahaha** [comment]
@TimShilov - new development on Moment.js is very slow. You can fork this repository, add the existing PR, and make a package, if you need this feature.
