### ISSUE TITLE
throwing an error for invalid periods (e.g. with a typo)

### ISSUE THREAD

**Issue by oprogramador** [moment/moment#4994]
**Is your feature request related to a problem? Please describe.**
```js
moment().add(1, 'montth');
```
This just returns the current time so it leads to bugs when I do a typo in the period name.

**Describe the solution you'd like**
I would like it to throw an error if the period is invalid. Maybe it should be done in a next major release.

**Describe alternatives you've considered**
At least a warning should be logged.

**Additional context**
It's related to https://github.com/moment/moment/issues/1805

**Comment by marwahaha** [comment]
Thanks for opening this request.
Probably, a solution will be handled like in #1805.
All the best.
