### ISSUE TITLE
Bulgarian Abbreviation of January

### ISSUE THREAD

**Issue by jimmylnb** [moment/moment#4995]
**Describe the bug**
We are using v2.22.1 of moment.js and one of our linguists said the abbreviation of January in Bulgarian language was not correct. 

From this locale file, the full name of January is `януари` and the abbreviation is `янр`. Our linguist suggested it should be `яну` as the first three letters of the full name.
https://github.com/moment/moment/blob/2.22.1/locale/bg.js

I'm not a Bulgarian speaker and one reference I can find is from CLDR data. It is using `яну`.
https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/bg/ca-gregorian.json

Can you please verify if `янр` is the correct usage. Thanks.

**Comment by mitevdev** [comment]
'яну' is the correct one.
