### ISSUE TITLE
diff() has overloaded meaning

### ISSUE THREAD

**Issue by skibrianski** [moment/moment#4996]
diff() tries to "do the right thing" by returning '1 day' for 23/24/25 hour days (timezones using DST) - ref https://github.com/iamkun/dayjs/pull/453/commits/c9ca021594b6bbe2f2e030d9ec4444abad4f08de. The problem is that overloading diff() in this way breaks diffs for GMT dates when moment.js is run in an environment that does observe DST. For instance, compare:

  moment('2019-11-04T00:00:00.000Z').diff(moment('2019-11-01T00:00:00.000Z'));

which returns the correct value of 3 * 86400 * 1000

with:

  moment('2019-11-04T00:00:00.000Z').diff(moment('2019-11-01T00:00:00.000Z'), 'days');

which returns the incorrect values of 2 + 23/24 (if precise) or 2 (non-precise) because we have crossed a DST end boundary. UTC/GMT do not observe daylight savings time, so any result other than 3 in this case is clearly a bug.

https://github.com/iamkun/dayjs/pull/453/commits/c9ca021594b6bbe2f2e030d9ec4444abad4f08de should be reverted, and a different function or flag to indicate "dst-aware-diffs" instead.

**Comment by skibrianski** [comment]
Additionally I noticed there are tests for when DST begins, but no tests for DST ending, and no tests for intervals other than 1/2 day.

**Comment by ashsearle** [comment]
@skibrianski You're using the normal moment constructor, which will create moment instances in your local timezone (the 'Z' UTC timezone.  If you want to have strict UTC based diffs, use `moment.utc`:

```js
moment.utc('2019-11-04T00:00:00.000Z').diff(moment.utc('2019-11-01T00:00:00.000Z'), 'days');
```

On a side note: you're referencing recent changes to dayjs, but this behaviour has been in moment for at least 4 years.

**Comment by skibrianski** [comment]
4 years or not, it's wrong.

And not just for UTC - any timezone that doesn't honor DST will break in this way.

Write some tests and see for yourself.

**Comment by ashsearle** [comment]
I think you're misinterpreting the issue:

> The problem is that overloading diff() in this way breaks diffs for GMT dates when moment.js is run in an environment that does observe DST

What do you think a 'GMT date' is?

(You probably think moment remembers and honours the timezone parsed from strings passed into the `moment(str)` constructor..?)

If you want to do a diff ignoring DST, do this:
```js
moment.utc('2019-11-04T00:00:00.000Z').diff(moment.utc('2019-11-01T00:00:00.000Z'), 'days');
```
```

**Comment by skibrianski** [comment]
Again, it's not just GMT.  Try for instance Copenhagen, Denmark time - which doesn't use daylight savings time, just Central European time - same results.

Are you saying it is expected behavior that asking moment for the difference in days between two **CET** times will yield different results based on whether moment is evaluated in an environment that uses DST for local time or not?

**Comment by ashsearle** [comment]
I'm saying that if you use `diff` between two `moment.utc` instances then it doesn't matter what your environment is.

If you use two non-utc `moment` instances, then yes, it'll depend on your environment any any DST changes between the two.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
