### ISSUE TITLE
Get date format with error

### ISSUE THREAD

**Issue by Hunter-Nomad** [moment/moment#4997]
**Describe the bug**
Get date format with error

**To Reproduce**
Incorrect get date format:
moment(2, 'DD').format('DD') -> get 02, good
moment(28, 'DD').format('DD') -> get 28, good
**moment(29, 'DD').format('DD') -> get Invalid date , error
moment(30, 'DD').format('DD') -> get Invalid date , error
moment(31, 'DD').format('DD') -> get Invalid date , error**

**Comment by ashsearle** [comment]
@Hunter-Nomad The unspecified fields are pulled from the current date / time.

It's now February, in a non-leap year, so Feb 29th, 30th and 31st don't exist.  Hence, you get an invalid date.

**Comment by Hunter-Nomad** [comment]
> @Hunter-Nomad The unspecified fields are pulled from the current date / time.
> 
> It's now February, in a non-leap year, so Feb 29th, 30th and 31st don't exist. Hence, you get an invalid date.

This error in all month.

**Comment by ashsearle** [comment]
In this particular case, the only thing you're doing is zero-padding a positive integer to 2 digits, which is a general JS question, not a moment question.

Old school: `('0' + number).slice(-2)`
New school:  `String(number).padStart(2, '0')`

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.
