### ISSUE TITLE
Zone name for Singapore

### ISSUE THREAD

**Issue by jaynilshah** [moment/moment#4998]
**Describe the bug**
For Singapore the zone abbreviation comes as +08 instead of SGT

**To Reproduce**
timezone = moment.tz("Asia/Singapore").zoneAbbr();
console.log(timezone);

**Expected behavior**
SGT

**Screenshots**
![screenshot from 2019-02-15 19-29-38](https://user-images.githubusercontent.com/36128751/52861566-e7f53280-3158-11e9-9904-ec7636deab24.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
**Moment-specific environment**
moment-timezone-version 0.5.23

**Comment by ashsearle** [comment]
This is an issue with moment-timezone, which has its own repository.

Sounds like [issue 773 in moment-timezone](https://github.com/moment/moment-timezone/issues/723).
