### ISSUE TITLE
[locale] Tetun Dili minute and second should not be the same

### ISSUE THREAD

**Issue by kylekatarnls** [moment/moment#5001]
**Describe the bug**
```js
ss : 'minutu %d',
mm : 'minutu %d',
```
https://github.com/moment/moment/blob/develop/src/locale/tet.js#L35

**To Reproduce**
Translate "3 minutes" and "3 seconds" in Tetun Dili

**Expected behavior**
"minutu 3" / "segundu 3"

**Actual behavior**
"minutu 3" / "minutu 3"

**Comment by rafamsilva** [comment]
Can I make this?

**Comment by kylekatarnls** [comment]
Feel free :)

**Comment by rafamsilva** [comment]
This is completed!
