### ISSUE TITLE
Fractional second parsing

### ISSUE THREAD

**Issue by dannykopping** [moment/moment#5002]
**Describe the bug**
Fractional second parsing is not behaving correctly.

**To Reproduce**
1. `moment('2019-02-17 23:03:29.196123', 'Y-MM-DD H:mm:ss.SSSSSS').valueOf()`
2. Expect to see `1550437409196123`
3. See `1550437409196`

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
> (new Date()).toString()
'Sun Feb 17 2019 23:10:33 GMT+0200 (SAST)'
> (new Date()).toLocaleString()
'2019/02/17, 23:10:33'
> (new Date()).getTimezoneOffset()
-120
> navigator.userAgent
ReferenceError: navigator is not defined
> moment.version
'2.24.0'
```

**Comment by ashsearle** [comment]
`moment`'s `valueOf` returns a [Unix Timestamp in milliseconds](https://momentjs.com/docs/#/displaying/unix-timestamp-milliseconds/) - the same as `Date` does.

You're parsing a timestamp that includes microseconds (the '123' in '.196123') - these are truncated and lost.

If `valueOf()` had returned the value you expect, it'd have represented `+051101-05-29T10:06:36.123Z` - i.e. a date in year 51,101 AD.

**Comment by dannykopping** [comment]
OK, thanks @ashsearle
