### ISSUE TITLE
Can I detect the global moment locale change in moment.js

### ISSUE THREAD

**Issue by modao** [moment/moment#5003]
I'm working on a large project with one framework app loading several sub apps in it. Recently the project needs to be localization. I import moment.js in the framework app and set moment locale globally. But a found some sub apps modify the global locale using moment.locale unexpectedly. 

Does moment.js has some feature likely [globally set moment locale and lock that setting] or [detect the global moment locale setting change]?

Any suggestions on solving this problem?

**Comment by kylekatarnls** [comment]
You can inspect by intercepting the method:
```js
var _locale = moment.locale;

moment.locale = function (id) {
  console.log('locale changed', id);
  console.trace();

  return _locale.apply(moment, arguments);
};
```

You need to track and remove the unexpected calls but certainly not "lock" the locale setting.

**Comment by modao** [comment]
Thanks for your suggestions!
