### ISSUE TITLE
moment subtract via month return same value

### ISSUE THREAD

**Issue by shinxi** [moment/moment#5004]
**Describe the bug**
Not sure whether this is by design? but 03-28, 03-29, 03-30, 03-31 return same value when subtract 1 month.
```js
moment('2018-03-28T05:00:00+08:00').subtract(1, 'month').format(); // "2018-02-28T05:00:00+08:00"
moment('2018-03-29T05:00:00+08:00').subtract(1, 'month').format(); // "2018-02-28T05:00:00+08:00"
moment('2018-03-30T05:00:00+08:00').subtract(1, 'month').format(); // "2018-02-28T05:00:00+08:00"
moment('2018-03-31T05:00:00+08:00').subtract(1, 'month').format(); // "2018-02-28T05:00:00+08:00"
```
Same for 05-31, 05-30 etc.

**Moment-specific environment**

moment 2.24.0

**Comment by kylekatarnls** [comment]
`2018-02-29`, `2018-02-30` and `2018-02-31` does not exist. So what are the different values you would expect?

**Comment by shinxi** [comment]
> `2018-02-29`, `2018-02-30` and `2018-02-31` does not exist. So what are the different values you would expect?

@kylekatarnls We are calculating the date duration using moment diff and subtract, see
```js
const getDuration = (start, end) => {
  const startMnt = moment(start);
  const endMnt = moment(end);
  const interval = {};
  interval.year = endMnt.diff(startMnt, 'years');
  endMnt.subtract(interval.year, 'years');
  interval.month = endMnt.diff(startMnt, 'months');
  endMnt.subtract(interval.month, 'months');
  interval.day = endMnt.diff(startMnt, 'days');
  endMnt.subtract(interval.day, 'days');
  interval.hour = endMnt.diff(startMnt, 'hours');
  endMnt.subtract(interval.hour, 'hours');
  interval.minute = endMnt.diff(startMnt, 'minutes');
  endMnt.subtract(interval.minute, 'minutes');
  interval.second = endMnt.diff(startMnt, 'seconds');
  return interval;
};
```
Overall the function works, but it failed at some end date, e.g., 
getDuration('2019-02-21 00:00:00', '2019-03-29 00:00:00') should be '1 month, 8 days' but returns '1 month, 7 days'.
getDuration('2019-02-21 00:00:00', '2019-03-30 00:00:00') should be '1 month, 9 days' but returns '1 month, 7 days'.
getDuration('2019-02-21 00:00:00', '2019-03-31 00:00:00') should be '1 month, 10 days' but returns '1 month, 7 days'.

Any idea?

**Comment by kylekatarnls** [comment]
You code does not match your expectation:

When you say `getDuration('2019-02-21 00:00:00', '2019-03-29 00:00:00') should be '1 month, 8 days'`
you add 1 month to 2019-02-21 to get 2019-03-21 (in this get 1 month = 28 days = number of days in february), then you add 8 days. You actually proceeded by addition.

While your code actually proceed by substraction. Substracting 1 month from 2019-03-29 give you 2019-02-28 as it cannot gives you 2019-02-29, then you get 7 remaining days. `1 month, 7 days` follows what your code asked.

If you want `1 month, 8 days` you must proceed by addition starting from startDate to endDate. But in this case, you have to think about what you exactly expect for `getDuration('2019-02-29 00:00:00', '2019-03-01 00:00:00')`, `getDuration('2019-02-30 00:00:00', '2019-03-01 00:00:00')`, and such cases but you should get the more intuitive result.

**Comment by shinxi** [comment]
Thanks @kylekatarnls 
> If you want `1 month, 8 days` you must proceed by addition starting from startDate to endDate.

Using addition will still have similar issue, see
```js
var getDuration = (start, end) => {
  var startMnt = moment(start);
  var endMnt = moment(end);
  var interval = {};
  interval.year = endMnt.diff(startMnt, 'years');
  startMnt.add(interval.year, 'years');
  interval.month = endMnt.diff(startMnt, 'months');
  startMnt.add(interval.month, 'months')
  interval.day = endMnt.diff(startMnt, 'days');
  startMnt.add(interval.day, 'days');
  interval.hour = endMnt.diff(startMnt, 'hours');
  startMnt.add(interval.hour, 'hours');
  interval.minute = endMnt.diff(startMnt, 'minutes');
  startMnt.add(interval.minute, 'minutes');
  interval.second = endMnt.diff(startMnt, 'seconds');
  return interval;
}

getDuration('2019-01-27', '2019-03-01'); // output '1 month, 2 day', but should be '1 month, 5 days'
getDuration('2019-01-28', '2019-03-01'); // output '1 month, 1 day', but should be '1 month, 4 days'
getDuration('2019-01-29', '2019-03-01'); // output '1 month, 1 day', but should be '1 month, 3 days'
getDuration('2019-01-30', '2019-03-01'); // output '1 month, 1 day', but should be '1 month, 2 days'
getDuration('2019-01-31', '2019-03-01'); // output '1 month, 1 day', which is correct
```

> But in this case, you have to think about what you exactly expect for `getDuration('2019-02-29 00:00:00', '2019-03-01 00:00:00')`, `getDuration('2019-02-30 00:00:00', '2019-03-01 00:00:00')`, and such cases but you should get the more intuitive result.

Get duration from two dates should be a common scenario, right? See [postgres age API](http://www.postgresqltutorial.com/postgresql-age/), or this [online date calculator](https://www.calculator.net/date-calculator.html), both two have consistent result. 
The postgres age API is kind of like moment.diff, but its response is in duration format, maybe in the future, moment.diff can also support to return a duration type result?

**Comment by kylekatarnls** [comment]
@shinxi >This a third way to think, retrieving complete month(s), then adding trailing days. It's not an obvious norm followed by everyone, see the native interval in PHP for example:

```php
var_dump((new DateTime('2019-01-27 00:00:00'))->diff(new DateTime('2019-03-01 00:00:00')));
// 1 month, 2 days (as in moment)
```

And I'm pretty OK, 1 month to 02-27, then 2 days. It gives me a reversible duration, I can add 1 month then add 2 days to the start date and get the end. If I add 1 month, then 5 days, it will be 2019-03-04.

It completely depends on the circumstances and point of view, and mostly context where you want to use this interval.

If you want a particular algorithm as the one in calculator.net, you have to implement it. It's all about the way you group days of months as a month can be from 28 to 31 days, you have to decide in each case how many days is "1 month", "2 months" in your interval representation.

The calculator.net algorithm would look like this:
```js
var getDuration = (start, end) => {
  var startMnt = moment(start);
  var endMnt = moment(end);
  var interval = {};
  interval.year = endMnt.diff(startMnt, 'years');
  startMnt.add(interval.year, 'years');
  var monthDay = startMnt.get('date') ;
  if (monthDay  > endMnt.get('date')) {
    var daysInMonth = startMnt.clone().endOf('month').get('date');
    interval.day = daysInMonth - monthDay + 1;
    startMnt.add(interval.day, 'days');
  }
  interval.month = endMnt.diff(startMnt, 'months');
  startMnt.add(interval.month, 'months')
  interval.day = (interval.day || 0) + endMnt.diff(startMnt, 'days');
  startMnt.add(interval.day, 'days');
  interval.hour = endMnt.diff(startMnt, 'hours');
  startMnt.add(interval.hour, 'hours');
  interval.minute = endMnt.diff(startMnt, 'minutes');
  startMnt.add(interval.minute, 'minutes');
  interval.second = endMnt.diff(startMnt, 'seconds');

  return interval;
}
```

**Comment by shinxi** [comment]
Thanks @kylekatarnls for your effort, appreciate it. We also implemented a similar algorithm.
```js
var getDuration = (start, end) => {
  var startMnt = moment(start);
  var endMnt = moment(end);
  var interval = {};
  interval.year = endMnt.diff(startMnt, 'years');
  startMnt.add(interval.year, 'years');
  interval.month = endMnt.diff(startMnt, 'months');

  var endMonth = endMnt.get('month')
  var diffDays = 0
  var startMntWithMonths = moment(startMnt).add(interval.month, 'months')
  if (startMntWithMonths.get('month') !== endMonth) {
    var startDay = startMnt.get('date')
    var startMonthDays =  startMnt.daysInMonth()
    diffDays = startMonthDays - startDay;
    startMnt.add(diffDays, 'd')
  }
  startMnt.add(interval.month, 'months')
  interval.day = endMnt.diff(startMnt, 'days') + diffDays;
  startMnt.add(endMnt.diff(startMnt, 'days'), 'days');
  interval.hour = endMnt.diff(startMnt, 'hours');
  startMnt.add(interval.hour, 'hours');
  interval.minute = endMnt.diff(startMnt, 'minutes');
  startMnt.add(interval.minute, 'minutes');
  interval.second = endMnt.diff(startMnt, 'seconds');
  return interval;
}
```
Btw, for your above code, need little refinement to get it work. :)
```js
...
interval.day = (interval.day || 0) + endMnt.diff(startMnt, 'days');
startMnt.add(endMnt.diff(startMnt, 'days'), 'days'); //startMnt.add(interval.day, 'days');
...
```

**Comment by shinxi** [comment]
For moment, "03-28, 03-29, 03-30, 03-31 return same value when subtract 1 month." is the expected behavior. Closing for now.

**Comment by kylekatarnls** [comment]
Indeed, avoid the duplicate call:
```js
  var trailingDays = endMnt.diff(startMnt, 'days');
  interval.day = (interval.day || 0) + trailingDays;
  startMnt.add(trailingDays , 'days');
```
