### ISSUE TITLE
TypeScript missing isoWeeks for add/substract

### ISSUE THREAD

**Issue by Klemensas** [moment/moment#5007]
**Describe the bug**
As a result of https://github.com/moment/moment/issues/4518 we can use `isoWeek` values in add/subtract. But TS typings weren't updated to allow for such usage.

**Expected behavior**
No error.

**Screenshots**

**Moment-specific environment**
TypeScript

**Comment by LoganDupont** [comment]
I have the same problem. @icambron, @marwahaha can someone of you confirm this is an issue?

**Comment by njifares** [comment]
Any updates on this?

**Comment by Klemensas** [comment]
I've made a PR for this the same day I opened the issue. Looks like no one cares enough to review it 🤷‍♂
