### ISSUE TITLE
Parse String + Format bug

### ISSUE THREAD

**Issue by Justin-ZS** [moment/moment#5009]
**Describe the bug**
moment('2014-03-11', 'YYYY-MM-W').format('YYYY-MM-W');
// equals 2014-03-9

**Expected behavior**
should be "2014-03-11"

**Comment by ashsearle** [comment]
I agree the behaviour is unexpected, but so is the usage.

What date are you trying to represent?

**Comment by kylekatarnls** [comment]
Indeed, you cannot have 2014-12-2 because Week 2 cannot be in the month 12. Here, as week is more precise than month, it seems overkill to give both. In which case the result for `YYYY-MM-W` would be different from `YYYY-W`?

**Comment by Justin-ZS** [comment]
@ashsearle @kylekatarnls 
Sure. I also agree that combining the month and week is strange. I can adjust my use case to avoid this issue, but still, the result should be "2014-03-11" since the month info is overridden by week info.

moment('2014-11', 'YYYY-W').format('YYYY-MM-W'); // equals 2014-03-11

**Comment by ashsearle** [comment]
Your simple case hides some of the difficulties of making this work in the general case.

Consider week 9, running from 24th Feb 2014 to 2nd March 2014.  Is `moment('2014-02-9', 'GGGG-MM-W')` valid?  What about `moment('2014-03-9', 'GGGG-MM-W')`?   Which date do they represent?

Side-note: try to be consistent and use ISO formatting codes together: `GGGG-WW`, not `YYYY-WW`:
```js
console.log(moment('2019-01', 'GGGG-WW').format('GGGG-WW')); // 2019-01
console.log(moment('2019-01', 'YYYY-WW').format('YYYY-WW')); // 2018-01!!
```

**Comment by Justin-ZS** [comment]
This problem is much more complicated than I thought.
For the association of a week to the month, I prefer the rule for the first week of the year in [ISO weeks](https://en.wikipedia.org/wiki/ISO_week_date#Weeks_per_month).

I change to use ``year``, ``quarter``, ``month``, ``isoWeek``, ``date`` methods to parse the date.
```js
moment().year(2014).month(3).isoWeek(11).format('GGGG-MM-W'); // 2014-03-11
```

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.
