### ISSUE TITLE
Add new formats with seconds

### ISSUE THREAD

**Issue by yroseau** [moment/moment#5014]
Like *LTS* format compared to *LT*, I proprose to add *LLLS*, *llls*, *LLLLS* and *lllls* formats.

moment().format('LT');   // 10:37 AM
moment().format('LTS');  // 10:37:22 AM
moment().format('L');    // 20/02/2019
moment().format('l');    // 20/2/2019
moment().format('LL');   // 20 February 2019
moment().format('ll');   // 20 Feb 2019
moment().format('LLL');  // 20 February 2019 10:37 AM
moment().format('lll');  // 20 Feb 2019 10:37 AM
moment().format('LLLL'); // Wednesday, 20 February 2019 10:37 AM
moment().format('llll'); // Wed, 20 Feb 2019 10:37 AM
**moment().format('LLLS');  // 20 February 2019 10:37:22 AM
moment().format('llls');  // 20 Feb 2019 10:37:22 AM
moment().format('LLLLS'); // Wednesday, 20 February 2019 10:37:22 AM
moment().format('lllls'); // Wed, 20 Feb 2019 10:37:22 AM**

What do you think about this ? If you are agree with this, I can make a PR..

**Comment by lethak** [comment]
Would be reat

**Comment by SimonaD11** [comment]
I need this format for my project. Is there any progress?

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

We will not add new tokens.
Thanks for your ideas.
