### ISSUE TITLE
parsing with de locale gives wrong isValid result

### ISSUE THREAD

**Issue by hbroer** [moment/moment#5015]
Hi,

i found that parsing of none english values is not correct.

Parsing "Dec 02" will result in "December 02" in english, whats correkt. With "de" locale parsing "Dez 02" will result in "Februar 02" (maybe because it is currently february). Parsing the full month name results in booth languages in the correct result. "Dezember 02" will work in german and "December 02" will work in english.

Version: 2.24.0

## Test 1
```
const value = moment.utc('Dez 02', 'MMMM DD', 'de');
const isValid = value.isValid();
```
value is now _Februar 02_
isValid is _true_

###### EXPECTED
value is **Dezember 02**
isValid is _true_

## Test 2
```
const value = moment.utc('D 02', 'MMMM DD', 'de');
const isValid = value.isValid();
```
value is now _Februar 02_
isValid is _true_

###### EXPECTED
value is **Invalid date**
isValid is **false**

**Comment by hbroer** [comment]
Last momentjs version which works as expected: 2.11.2 (since 2.13.0 got the error above, with 2.12.0 another error)

**Comment by marwahaha** [comment]
To the first test:
the [locale mentioned](https://github.com/moment/moment/blob/develop/src/locale/de.js#L27) uses `Dez.` with a period (`.`) at the end.

To the second test, try strict mode, and I get invalid date:
```
 moment.utc('D 02', 'MMMM DD', 'de', true);
```

Best of luck.
