### ISSUE TITLE
Strange behavior on moment to Date conversions

### ISSUE THREAD

**Issue by Nenrikido** [moment/moment#5016]
**Describe the bug**
As said in the title, it seems that moment.js is translating Moment objects into javascript Date objects with wrong values and this is causing issues when doing operations with moments 'cause it seems (correct me if i'm wrong) that moment.js actually converts its Moment objects into a Date object to do things like comparisons.

**To Reproduce**
What i did to spot this bug is this (i'm using console logs outputs from Google Chrome):
I have 1 Moment object and 1 moment-friendly string which are supposed to be same : 
`x = M {_isAMomentObject: true, _i: "2019-02-23T10:11:11", _f: "YYYY-MM-DDTHH:mm:ss", _isUTC: true, _offset: 0, …}
y = "2019-02-23T10:11:11"`
When i transform the moment into a date (aka `new Date(x)`), it adds 1 hour to it and makes x and y unequal, when i don't want it to. Maybe it's related to my timezone, but even if it is, it's said nowhere that the moment actually take care of the timezones within their conversions and i think it shouldn't be an expected result (i'll delete this issue if it is one though). And as i'm using moment.js in a timezone-less environment, this behavior 'cause me problems even if i resolved it by formatting the moment before converting it into a Date.

**Expected behavior**
The moment should be acting just like the string when converted into a Date

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 72

**Moment-specific environment**

- Timezone: fr_FR
- When was the code executed: This code was executed just before this issue was made
- Other libraries in use: jQuery, Bootstrap, fullcalendar.js, scheduler.js, font-awesome, dataTables

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
    Wed Feb 20 2019 16:39:57 GMT+0100 (heure normale d’Europe centrale)
console.log((new Date()).toLocaleString())
    20/02/2019 à 16:39:57
console.log((new Date()).getTimezoneOffset())
   -60
console.log(navigator.userAgent)
    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
    Chrome/72.0.3626.109 Safari/537.36
console.log(moment.version)
    2.22.2
    undefined
```

**Comment by Nenrikido** [comment]
oopsi, it seems that i've read the documentation wrongly and this is an expected behavior, so sorry, i'm closing this now. But as peoples are having issues with this too, i think it don't have to be deleted. Maybe you should change this behavior.

**Comment by Nenrikido** [comment]
Sorry for this little spam, but after thinking about this for a second, i think it should in fact stays open until we get an answer on if this will be "patched"/updated in a soon to go update or nie.

**Comment by marwahaha** [comment]
Thanks for opening this request.
Unfortunately, I cannot reproduce it.
```
new Date(x)
Date Sat Feb 23 2019 10:11:11 GMT-0800 (Pacific Standard Time)

new Date(y)
Date Sat Feb 23 2019 10:11:11 GMT-0800 (Pacific Standard Time)
```

I don't think we can guarantee that `new Date()` will handle moment objects properly.
Please re-open if you have  other thoughts.
