### ISSUE TITLE
moment.js breaks webpack sourcemaps

### ISSUE THREAD

**Issue by akopchinskiy** [moment/moment#5021]
**Describe the bug**
moment.js breask webpack sourcemaps

**To Reproduce**
1. Create project with webpack with couple of custom modules;
2. Import 'moment' as ES6 module to one of them;
3. Check sourcemaps

**Screenshots**
![image](https://user-images.githubusercontent.com/39277134/53657189-b9498280-3c55-11e9-8ceb-905130f88dba.png)

Please run the following code in your environment and include the output:
```
Fri Mar 01 2019 19:07:06 GMT+0100
VM105:2 01.03.2019, 19:07:06
VM105:3 -60
VM105:4 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) time-tracker-electron-port/0.8.5 Chrome/69.0.3497.106 Electron/4.0.5 Safari/537.36
```

**Additional context**

**Comment by marwahaha** [comment]
Is this still the case? @akopchinskiy 
I don't know if you can use moment as an ES6 module.

**Comment by akopchinskiy** [comment]
> Is this still the case? @akopchinskiy

I think yes. I tested it couple of month ago.

> I don't know if you can use moment as an ES6 module.

Of course you can. Especially with TS.

**Comment by marwahaha** [comment]
I don't think Moment.js can do anything about this.

See https://momentjs.com/docs/#/-project-status/
