### ISSUE TITLE
[feature request] Duration comparison operators - tested and implemented!

### ISSUE THREAD

**Issue by youfoundron** [moment/moment#5022]
**Is your feature request related to a problem? Please describe.**
I'd like to see a way to run comparison operations on moment duration instances.  
Something more explicit than converting to milliseconds and comparing the integers.

**Describe the solution you'd like**
Methods on the duration prototype for doing the above.  
For example:
```javascript
var twoDays = moment.duration({ days: 2 })
var threeDays = moment.duration({ days: 3 })
var fortyEightHours = moment.duration({ hours: 48 })

twoDays.eq(fortyEightHours) // => true
twoDays.gt(threeDays) // => false
twoDays.lt(threeDays) // => true
twoDays.gte(fortyEightHours) // => true
twoDays.lte(fortyEightHours) // => true
```

**Describe alternatives you've considered**
Converting to milliseconds and comparing the integers. Not very explicit.

**Additional Context**
I've submitted a PR with the functionality described above. #5023

**Comment by marwahaha** [comment]
Thanks for opening this request.

For now, we will not take a change like this.

As pointed out in your PR, I think these comparisons can be done natively.

Best of luck with your use case.
