### ISSUE TITLE
Wrong day of month

### ISSUE THREAD

**Issue by Romko775** [moment/moment#5026]
**Describe the bug**

**To Reproduce**
console.log(moment('01-01-2022', 'DD-MM-YYYY').isoWeek());
-> isoWeek is 52, why -> Expected to be always 1

console.log(moment('01-01-2022', 'DD-MM-YYYY').isoWeek(1).isoWeekday(1));
-> logs Mon 04 -> expected to be Mon 03

**Comment by ashsearle** [comment]
ISO week 2021-W52 runs from Monday 27th December 2021 to Sunday 2nd January 2022.

2022-01-01 falls in Week 52 of ISO Weekyear 2021.

```js
moment('01-01-2022', 'DD-MM-YYYY') // Saturday 1st Jan 2022
  .isoWeek(1) // Saturday Jan 9th 2021 (preserves ISO Weekyear and ISO Weekday)
  .isoWeekday(1) // Monday Jan 4th 2021 (preserves ISO Week)
```

**Comment by Romko775** [comment]
Is there a way to get week number '1' of January in ISO standart ? Because there is an issue for building calendar? because start week is 52 & end week is 5 ?

**Comment by kylekatarnls** [comment]
First of all, what you expect is NOT ISO standard:
https://www.epochconverter.com/weeks/2022

The first week of the year according to the ISO-8601 is the first one that contains at least 4 days starting on Monday. Period.

Other numerations are not ISO, they are locale consideration.

So you have to first set the locale to the proper region which will handle the first day of week (Monday/Sunday/Saturday) then that handle the first-week-of-year rule (the minimum day the first week should include).

So now, the question, what is the locale you want to use for that (language and region) and so the rule settings you expect?

**Comment by ashsearle** [comment]
@Romko775 ISO Week 1 always contains January 4th.

You can manually get to the start of week 1 - e.g. for 2022:
`moment('2022-01-04', 'YYYY-MM-DD', true).isoWeekday(1)`

Or, you could just parse ISO week explicitly: `moment('2022-W01', 'GGGG-[W]WW', true)`
