### ISSUE TITLE
add the capitalization to the format

### ISSUE THREAD

**Issue by DontShootMe** [moment/moment#5031]
**Is your feature request related to a problem? Please describe.**
Many times and in many locales people do not always agree among themselves about the case of words.
Just see how many issues are related to that !

**Describe the solution you'd like**
is it possible to add, to the format, the case sensitivity ?

***Example for a Monday of October :***
```javascript

//  - Existing :

/* case according locale file */
//      Locale                en    |  fr
moment().format('dddd'); // Monday  | lundi
moment().format('ddd');  // Mon     | lun.
moment().format('dd');   // Mo      | lu
moment().format('MMMM'); // October | octobre
moment().format('MMM');  // Oct     | oct.


//  - New :
                        //   en     |  fr
/* first letter Ucase */
moment().format('Dddd'); // Monday  | Lundi
moment().format('Ddd');  // Mon     | Lun.
moment().format('Dd');   // Mo      | Lu
moment().format('Mmmm'); // October | Octobre
moment().format('Mmm');  // Oct     | Oct.

/* all letters Ucase */
moment().format('dDDD'); // MONDAY  | LUNDI
moment().format('dDD');  // MON     | LUN.
moment().format('dD');   // MO      | LU
moment().format('mMMM'); // OCTOBER | OCTOBRE
moment().format('mMM');  // OCT     | OCT.

/* all letters Lcase */
moment().format('dddD'); // monday  | lundi
moment().format('ddD');  // mon     | lun.
moment().format('dDd');  // mo      | lu       ==> dd in use : so, inconsistency of dDd  
moment().format('mmmM'); // october | octobre
moment().format('mmM');  // oct     | oct.



```

**Additional context**
I think this can be done without breaking change.

**Comment by kylekatarnls** [comment]
Hello, `lundi`  is a common noun in French, there is no reason to uppercase the `L` until it's a sentence start. If it's the case, it's logical for the user to put this uppercase himself for this particular case.

`Rendez-vous lundi` (it's lowercase, here `Lundi` would be just wrong.)

But `See you Monday` (it's always uppercase in English even in the middle of a sentence.)

So `monday` is always wrong anywhere. Never lowercase `Monday` in English, it's incorrect.

So `Monday` = `lundi`, there is no relevant reason to take a case from a language to an other or apply a case globally to all languages, the case depends on the language, it's a grammar rule among others.

**Comment by DontShootMe** [comment]
@kylekatarnls You are right, and i know these rules !
In this proposition, i do not ask to change or remove any existing behavior !

it just **adds** a possibility to choose case directly from the format string !

>  the case depends on the language

This is exact !
But that can depend on other rules too, a context or so many other elements !
 (internal presentation rules, analysis rules, many other things, etc ... )
>  it's a grammar rule among others

And, as you said, this is only a rule and not an obligation, for all languages !
If you want to strictly respect the rules of grammar, every word cut in French MUST be followed by a point.
So, the french rules file of moment, is not correct, because it must be:
```javascript
weekdaysMin : 'di_lu_ma_me_je_ve_sa'.split('_'),            <== wrong
weekdaysMin : 'di._lu._ma._me._je._ve._sa.'.split('_'),     <== right
```

This improvement offers more possibilities and does not remove anything.
>  If it's the case, it's logical for the user to put this uppercase himself for this particular case

In French, when noun is placed at the beginning of a sentence, we need to uppercase every noun, each time, and here some examples where we have to do it manually !

Calendar presentation :
```javascript
 | Lundi  | Mardi | Mercredi | Jeudi | Vendredi | Samedi | Dimanche |
     1         2        3        4         5         6         7        
     8         9       10       11        12        13        14        
     ...

Lu |  1 |  8 |
Ma |  2 |  9 |
Me |  3 | 10 |
Je |  4 | 11 |
Ve |  5 | 12 |
Sa |  6 | 13 |
Di |  7 | 14 |
```

 Date list :

> Je vous propose les dates suivantes :
>   - Lundi 10 janvier à 15:00
>   - Mardi 11 janvier à 13:00  
>
> Ou bien on décale à l'un des mois suivant :
>   - Juillet 2019
>   - Décembre 2019

Just because my boss prefer !
> Vendredi 08 MARS 2019
> SAM. 3 OCT. 2020
> dimanche 01 décembre 2019

To simplify the parsing of my log file :
> 2019 oct sat 03 13:30 job 320
> 2019 oct sat 03 15:10 action 526
> 2019 oct sat 03 16:20 action 533
> 2019 oct sun 04 13:30 job 450
> 2019 oct sun 04 16:30 action 120
> 2019 oct sun 04 16:50 error uppercase on file
> 2019 oct sun 04 17:00 update

***and so many use case...***
Just remember this improvement do not change or remove any existing behavior, it just adds possibilities !

**Comment by kylekatarnls** [comment]
OK, but let see some troubles, `Dddd` creates a conflict with `D` then `ddd` (this is used in standard Japanese format for example).

IMHO, changing case for presentation is not the responsibility of moment, the role of moment is to 
output dates, if you need a custom case, you have `.toLowerCase()` and `.toUpperCase()` and you can do an upperFirstLetter function using: `str.charAt(0).toUpperCase() + str.substr(1)`

I understand you can need it but I don't think it should be done inside the moment library.

**Comment by DontShootMe** [comment]
> OK, but let see some troubles, Dddd creates a conflict with D then ddd (this is used in standard Japanese format for example).

Ho ... i was not aware of that ! :-(

> IMHO, changing case for presentation is not the responsibility of moment

I was rather of this opinion, and even very rigorous on this point, but in the end I realize that most of the time that I have to modify the result of moment comes from that!
I always have to add upperCase or lowerCase, and when/if I have to add that in my code, you will agree, that it will not be changed after, so i think, it would be better to integrate them directly into the format!

Once again, the goal is to offer something more without taking anything away !

In my first proposition i have tried to use the existing `d` and `M`, but maybe we can add new letters ?
This will have 2 major advantage :
  - this will break nothing for sure !
  - this will introduce something that you can ignore

From my French point of view : `day === jour` so maybe the letter `j` can do the job !
Or the letter `c`, for the english word `case` !
And for the months => `p` as period or `n` as next `M`
``` javascript
   let dayLoweredCase = 'jjjj jjj jj j' || 'cccc ccc cc c';
   let dayUpperedCase = 'JJJJ JJJ JJ J' || 'CCCC CCC CC C';
   let dayUpperedFirstLetter = 'Jjjj Jjj Jj' || 'Cccc Ccc Cc';

   let monthLoweredCase = 'pppp ppp pp p' || 'nnnn nnn nn n';
   let monthUpperedCase = 'PPPP PPP PP P' || 'NNNN NNN NN N';
   let monthUpperedFirstLetter = 'Pppp Ppp Pp' || 'Nnnn Nnn Nn';

```

**Comment by kylekatarnls** [comment]
Still not sure about the syntax. Maybe some generic filters/functions could be applied on any string: `Cc:MMMM` to Upper the month, `Cc:dddd` to Upper the day, then `cc:` to lower, `CC:` to UPPER. Could be `()`, `=` or `|` instead of `:`.  This way you don't have a lot of new patterns. But the idea itself is interesting.

If it's implemented in moment.js, I will add an equivalent feature in https://github.com/briannesbitt/Carbon

**Comment by DontShootMe** [comment]
> some generic filters / functions

Well why not!
We get the same result and that's what matters!
I did not dare to go in that direction, adding functions in the format will open new perspectives !

**Comment by burritoIand** [comment]
any movement on this? it'd be nice to natively set the letter case in the format like original proposal in this thread...

**Comment by agrounds** [comment]
Just wanted to add that I agree with @kylekatarnls, these presentation concerns should not be Moment's responsibility.

**Comment by marwahaha** [comment]
Thank you for this proposal.

I don't think capitalization preferences should be a concern in Moment.js . 
The presentation of these words should be left to the locale authors, as different conventions may apply in different languages.
