### ISSUE TITLE
In safria, have a bug. eg: var date = moment("2018-3").format("YYYY-MM"); a is undefined.But in chrome, a is 2018-03.

### ISSUE THREAD

**Issue by iJay** [moment/moment#5033]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

**Additional context**

**Comment by iJay** [comment]
var date = moment("2018-3").format("YYYY-MM"); 
In safari, a is undefined.But in chrome, a is 2018-03.

**Comment by ashsearle** [comment]
`moment("2018-3")` leads to a message in the console explaining the problem:

> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers

**Comment by iJay** [comment]
thank you! @ashsearle

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
