### ISSUE TITLE
Time zone offset not consistent with native Date object

### ISSUE THREAD

**Issue by alfechner** [moment/moment#5035]
**Describe the bug**
The date time object created by moment does not correctly represent the local time zone.

**To Reproduce**
It's a bit hard to reproduce since I didn't find a way to modify the environments time zone settings in my test.

I run a German environment. German offset is depending on DST -120 or -60. Have a look at the following test:

```
test('date created by moment represents local time zone', () => {
  expect(
    moment('2018-10-20T12:00:00')
      .toDate()
      .getTimezoneOffset()
  ).toBe(new Date().getTimezoneOffset());
});
```
It fails with

```
Expected: -60
Received: -120
```

**Expected behavior**
At least the behavior should be consistent. The moment.js documentation about parsing says:

> moment(...) is local mode. Ambiguous input (without offset) is assumed to be local time. Unambiguous input (with offset) is adjusted to local time.

From that statement I'd assume that the time zone specific details (like DST) are considered the same way the native `Date()` object does it.

**Comment by alfechner** [comment]
I ran another test:

```
test('to server string', () => {
  const localTimeZoneOffset = moment().utcOffset();
  expect(localTimeZoneOffset).toBe(120);

  expect(moment('2018-10-20T12:00:00').utcOffset()).toBe(localTimeZoneOffset);
  expect(moment('2018-10-20T12:00:00').format('YYYY-MM-DDTHH:mm:ss')).toBe('2018-10-20T12:00:00');
});
```

This one fails with

```
Expected: 120
Received: 60
```

My last test passes and summarizes my findings:

```
test('current behaviour', () => {
  expect(moment().utcOffset()).toBe(60);
  expect(moment('2018-10-20T12:00:00').utcOffset()).toBe(120);
  expect(new Date().getTimezoneOffset()).toEqual(-60);
});
```

**Comment by alfechner** [comment]
Edit:

Ok,

this test case fails as well:

```
  expect(new Date('2018-10-20T12:00:00').getTimezoneOffset()).toEqual(-60);
```

Thats the behavior of Date(), but the moment documentation cle

**Comment by sruthiramakrishnan-svmx** [comment]
I am facing a similar issue while using moment in Cefsharp browser on a Cordova hybrid application on Windows. On changing the device timezone, moment does not respect the change while converting to UTC.

Moment is loaded on IST Indian Standard Time (which is UTC+0530). When I run the below test, it works fine.

test(‘utc value conversion’, () => {
  expect(
    moment("2019-03-23 07:30:00").utc().format("YYYY-MM-DD HH:mm:ss")
  ).toBe("2019-03-23 02:00:00"));
});

Expected 2019-03-23 02:00:00
Received 2019-03-23 02:00:00

Now I change my device timezone to Myanmar UTC+0630 - so now my date value in local time becomes 26/3/2019 08:30 am.

test(‘utc value conversion’, () => {
  expect(
    moment("2019-03-23 08:30:00").utc().format("YYYY-MM-DD HH:mm:ss")
  ).toBe("2019-03-23 02:00:00"));
});

Expected 2019-03-23 02:00:00
Received 2019-03-23 03:00:00

The same code works fine while using moment in Safari browser on the same Cordova hybrid application on iOS.

Can you share your platform details?

**Comment by kylekatarnls** [comment]
Hello, if you're in a DST timezone the offset simply change in summer/winter So 2018-10-20 and now can have a 1 hour offset difference.

**Comment by marwahaha** [comment]
Thanks @kylekatarnls 
Please re-open if you still have issues.
