### ISSUE TITLE
fromNow() showing wrong number of months

### ISSUE THREAD

**Issue by zhangziyi123** [moment/moment#5037]
the time is 2018-11-20

moment('2018-11-20').locale('zh-cn').fromNow()

return 4 months ago, but i think the correct result is 3 months ago

**Comment by abnersajr** [comment]
### Actual Behavior
`moment('2018-11-3').locale('pt-br').fromNow()`
`"há 5 meses"`

### Expected Behavior
`moment('2018-11-3').locale('pt-br').fromNow()`
`"há 4 meses"`

`12, 1, 2, 3` I'm posting on April, 1st. It isn't 5 months. It's almost 5 months. But not completed yet.

**Comment by kylekatarnls** [comment]
I get `há 5 meses` with the same code, did you check the timezone of this moment instance?

**Comment by abnersajr** [comment]
@kylekatarnls the timezone shouldn't interfere here. It's more than 2 days of difference.

**Comment by abnersajr** [comment]
![image](https://user-images.githubusercontent.com/1998649/55335552-ab179d80-5471-11e9-9187-0fe48bf8d25a.png)

![image](https://user-images.githubusercontent.com/1998649/55335627-d00c1080-5471-11e9-9326-0bd638c072c4.png)

**Comment by abnersajr** [comment]
I don't know if the difference between days in one month can cause this. One with 30 other with 31, another with 29 or 28.

**Comment by marwahaha** [comment]
I'm sorry this is happening to you.
Could you provide any examples that are current?
