### ISSUE TITLE
Locales should include their own names

### ISSUE THREAD

**Issue by gubikmic** [moment/moment#5038]
Resolving the locale codes returned by `moment.locales()` is anything but trivial.

I propose each locale should come with its own name in English, e.g. `fr-ca` should come with `French (Canada)`. (Also I hope this will be aligned to the standard and changed to `fr_CA` but that's another issue).
Optionally it could additionally come with the name in the respective language, in this example `français (Canada)`.

If you can suggest a good solution outside of moment.js itself, please share. But since googling for more than 10 minutes did not turn up an exhaustive list I think it would be good to add it to moment itself.

This list turned up: https://github.com/umpirsky/locale-list/blob/master/data/en/locales.json
But even this doesn't cover the following:

```
cv -- undefined
dv -- undefined
en_IL -- undefined
gom_Latn -- undefined
jv -- undefined
ku -- undefined
me -- undefined
mi -- undefined
sd -- undefined
ss -- undefined
tet -- undefined
tg -- undefined
tlh -- undefined
tzl -- undefined
tzm_Latn -- undefined
tzm -- undefined
```

**Comment by gubikmic** [comment]
For reference here is an addition to the list linked from the umpirsky repo above:
```
  cv: 'Chuvash',
  dv: 'Divehi',
  en_IL: 'English (Israel)',
  jv: 'Javanese',
  ku: 'Kurdish',
  mi: 'Maori',
  sd: 'Sindhi',
  ss: 'Swati',
  tg: 'Tagalog',
```

This still leaves a few undefined.


And here's a snippet to resolve them:
```
const moment = require('moment/min/moment-with-locales')
const languageByLocale = require('./language-names').default

const momentLocales = moment.locales()

momentLocales.forEach( momentLocale => {
  const [language, region] = momentLocale.split('-')
  const fixCapitalization = region => {
    if (region.length == 2) {
      return region.toUpperCase()
    } else {
      return region[0].toUpperCase() + region.substr(1).toLowerCase()
    }
  }
  const locale = region ? `${language}_${fixCapitalization(region)}` : language
  console.log(`${locale} -- ${languageByLocale[locale]}`)
})

```

**Comment by marwahaha** [comment]
The data is here:
https://github.com/moment/momentjs.com/blob/master/data/locale.js

We align with ISO country code and language code standards as best we can.

Do you think this data belongs in Moment.js also?

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

You can get the data from the above link if you need it.
