### ISSUE TITLE
in locale "tr", "Do" format is not working

### ISSUE THREAD

**Issue by dogukankotan** [moment/moment#5039]
**Describe the bug**
in locale "tr", "Do" format is not working. Need to test all formats again.
**To Reproduce**
-> moment().locale('tr').format('Do')

**Expected behavior**
It should return suffixes. Ex: for value 15 -> "15inci"

**Screenshots**
- no

**Desktop (please complete the following information):**
 - Browser: any browser

**Smartphone (please complete the following information):**
  - Browser: any browser

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
```
Thu Mar 14 2019 10:12:15 GMT+0300 (GMT+03:00) debugger eval code:1:1
3/14/2019, 10:12:15 AM debugger eval code:2:1
-180 debugger eval code:3:1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0 debugger eval code:4:1
2.24.0
```

**Comment by LukaszGrela** [comment]
I think [this line](https://github.com/moment/moment/blob/develop/src/locale/tr.js#L72) should not be there then (or moved before `default:` line) where suffixes are added.

**Comment by Hiba-moh** [comment]
I would like to work on this, if that's Ok

**Comment by marwahaha** [comment]
Thanks for this request.

Ordinals used to be there. They were asked to be removed in https://github.com/moment/moment/issues/4122#issuecomment-353021460 (that is the locale author) so I am not sure we should add them back. I will close this issue unless there is a strong case to re-open (government source, cldr, or similar)
