### ISSUE TITLE
Unexpected result returned from diff method

### ISSUE THREAD

**Issue by Ahnteve** [moment/moment#5040]
**Describe the bug**
Unexpected results are returned when the date difference between 2019-03-18 and 2019-03-10T00:00Z is found.

**To Reproduce**
https://jsfiddle.net/8jd7yo0e/5/

**Expected behavior**
I expected 8 to be returned because I thought 2019-03-10T00:00Z was the same as 2019-03-10.

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: chrome
 - Version:  73.0.3683.75

**Moment-specific environment**

* The time zone setting of the machine the code is running on
UTC +09:00 Seoul
* The time and date at which the code was run
2019-03-19 11:22
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
Mon Mar 18 2019 11:23:52 GMT+0900 (한국 표준시)
2019. 3. 18. 오전 11:23:52
-540
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
46 2.11.2
```

**Comment by kylekatarnls** [comment]
> I thought 2019-03-10T00:00Z was the same as 2019-03-10

That's the point, `Z` means UTC, no `Z` means *the timezone of the browser* so UTC +09:00 if you run the code in Seoul.

For clarity, you should compare 2 UTC dates, or 2 local dates.

**Comment by Ahnteve** [comment]
Oops, I'm mistaken. Thank you for the information☺
