### ISSUE TITLE
RFC3339 and RFC3339Nano

### ISSUE THREAD

**Issue by mbana** [moment/moment#5045]
How does one parse the formats below. Golang defines `RFC3339` and `RFC3339Nano`, see https://golang.org/pkg/time/#pkg-constants for the documentation and `/usr/local/go/src/time/format.go` for the definition.

```go
...
	RFC3339     = "2006-01-02T15:04:05Z07:00"
	RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"
...
```

---

```javascript
> moment("2006-01-02T15:04:05Z07:00").format()
"Invalid date"
```

---

Raised the same issue in the `luxon` repository, https://github.com/moment/luxon/issues/474.

**Comment by mcandre** [comment]
Yep, let's please define this string in the moment.js library itself, in order to reduce the risk that users introduce a typo when they try to define this themselves.

**Comment by dobromyslov** [comment]
Any news for this?
This format will be helpful to use with Google Firestore.

**Comment by randallmorey** [comment]
It appears that [the examples in the Go docs for RFC3339](https://golang.org/pkg/time/) [are wrong](https://www.ietf.org/rfc/rfc3339.txt).  The format is [really just a profile of ISO8601](https://en.wikipedia.org/wiki/ISO_8601).

The problem with the Go doc examples for this format is that they include both `Z` and an offset together.  This is incorrect.  It is either `Z` (for Zulu or +00:00) _or_ an offset.

If you correct the examples before trying to parse them, they are parseable by Moment.js:

```
> moment("2006-01-02T15:04:05-07:00").format()
'2006-01-02T17:04:05-05:00'
> moment("2006-01-02T15:04:05+07:00").format()
'2006-01-02T03:04:05-05:00'
```

@mbana @dobromyslov

**Comment by marwahaha** [comment]
If RFC3339 is parseable with Moment already, then I don't think we should do this.

**Comment by marwahaha** [comment]
Oh, I see, the two formats are inconsistent at the "T00:00" section. I am not sure RFC3339 always uses "Z" where listed in the Go package documentation.
https://stackoverflow.com/questions/522251/whats-the-difference-between-iso-8601-and-rfc-3339-date-formats

**Comment by marwahaha** [comment]
I may be wrong here. If so, please let me know and I can re-open this issue.
