### ISSUE TITLE
Not able to convert into date from timestamp

### ISSUE THREAD

**Issue by adityay-perpetualny** [moment/moment#5046]
1. Below is the timestamp for which the moment is not able to convert into date. It is throwing as invalid date.
    1560085200

**Comment by thomasnordquist** [comment]
Can you provide a code example?
You should also be aware that the unix time stamps is understood to be in milliseconds.

Tested with 2.24.0 and the timestamp works just fine.
```javascript
moment(1560085200).format()
"1970-01-19T02:21:25+01:00"
```

```javascript
moment(1560085200 * 1000).format()
"2019-06-09T15:00:00+02:00"
```

**Comment by ashsearle** [comment]
@adityay-perpetualny Did you pass the timestamp in as a string instead of an integer?  Did you try using the [`unix()`](https://momentjs.com/docs/#/parsing/unix-timestamp/) method?

```js
// Passing a string to moment constructor
moment('1560085200').toString(); // 'Invalid date'
// Passing a number to moment constructor
moment(1560085200).toString(); // '1970-01-19T02:21:25+01:00'
// Passing a string or a number to unix()
moment.unix('1560085200').toString(); // 'Sun Jun 09 2019 14:00:00 GMT+0100'
moment.unix(1560085200).toString();   // 'Sun Jun 09 2019 14:00:00 GMT+0100' 
```

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
