### ISSUE TITLE
inconsistent parameters

### ISSUE THREAD

**Issue by KES777** [moment/moment#5050]
This is possible:

    moment({ y: year, M: month, d: 1 });

but this not:

    moment().set({ d: 1 })

Allow `d` as argument for `set`

**Comment by marwahaha** [comment]
Probably, you want `D: 1`. 

https://momentjs.com/docs/#/get-set/set/

Please re-open if you still have issues.

**Comment by KES777** [comment]
thanks, I did not notice `date (dates, D)`

but that is still inconsistent that for same things parameters are different `d` VS `D`

**Comment by marwahaha** [comment]
Your code example worked for me. Sorry if I am misunderstanding something.
