### ISSUE TITLE
.diff method shows incorrect day difference.

### ISSUE THREAD

**Issue by akhileshasare** [moment/moment#5051]
**Describe the bug**
.diff method gives 1 day difference in time. 

**To Reproduce**
```
var temp1 = '03-02-2013 7:25:37 PM';
var temp2 = '03-02-2013 9:25:37 PM'
var x = moment.utc(moment(temp2,'MM-DD-YYYY HH:mm:ss A').diff(moment(temp1,'MM-DD-YYYY HH:mm:ss A'))).format('D H m');
console.log(x);
```
**It gives difference as 1 day 2 hrs and 0 min. I tried without UTC and it does not work.**

**Expected behavior**
It should return difference as 2 hrs.

**Screenshots**
![2019-03-25_16-04-11](https://user-images.githubusercontent.com/11653212/54960131-b0786380-4f18-11e9-90f1-030790cf8eaf.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 

**Smartphone (please complete the following information):**

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

**Additional context**

**Comment by ashsearle** [comment]
What do you think this code is doing?

Let's break it down:
```js
var temp1 = '03-02-2013 7:25:37 PM';
var temp2 = '03-02-2013 9:25:37 PM';
var diffInMilliseconds = moment(temp2,'MM-DD-YYYY HH:mm:ss A').diff(moment(temp1,'MM-DD-YYYY HH:mm:ss A')); // 7,200,000 - i.e. 2 hours
var momentFromUnixTimestampInMillis = moment.utc(diffInMilliseconds); // 1970-01-01T02:00:00.000Z
var extractedFields = momentFromUnixTimestampInMillis.format('D H m'); // 1 2 0
```

You could try using `duration` instead:
```js
var duration = moment.duration(diffInMilliseconds);
duration.toISOString(); // 'PT2H'
duration.humanize(); // '2 hours'
duration.hours(); // 2
```

Note: if you create a duration from a milliseconds value > 24 hours you may notice differences between behaviour of `duration.hours()`, `duration.days()` (both of which assume 1 day is 24 hours) and `duration.toISOString()` (which won't treat 24 hours as equivalent to 1 day, and may - for example - represent 48 hours as 'PT48H' instead of 'P2D')

**Comment by marwahaha** [comment]
Thanks @ashsearle 
Please re-open if you still have concerns.
