### ISSUE TITLE
Header comment with version missing in 2.24 release

### ISSUE THREAD

**Issue by sverrirs** [moment/moment#5057]
Hi
In the latest release it looks like the disted moment.js files are missing the rather useful header that was there before. Example:
```
//! moment.js
//! version : 2.18.1
//! authors : Tim Wood, Iskren Chernev, Moment.js contributors
//! license : MIT
//! momentjs.com
```
Having this header is actually useful to have to quickly recognize the release version of the library. I'd really like to see this added back (if only the version number at least).

Related to: #3159, #3234

**Comment by garg3133** [comment]
I would like to work on this issue.

**Comment by Hardik500** [comment]
Does this issue still require a fix?

**Comment by generationXcode** [comment]
I'm not that good at open source but I'd like to start. I would like to work on this. Are those headers comments? What are disted moment.js files? do we have to paste these headers on top of each moment.js file? thanks!

**Comment by generationXcode** [comment]
is this the problem?Is it where we have to add the header comments?
![problem moment](https://user-images.githubusercontent.com/43435971/64906212-28258f00-d701-11e9-9ac4-695643c9dcc2.png)

**Comment by generationXcode** [comment]
I tried to create a pull request

**Comment by maniac-tech** [comment]
Any update on the PR @generationXcode ?

**Comment by generationXcode** [comment]
I'm not sure about what needs to be updated. (:

**Comment by manjeet-thadani** [comment]
I have created PR for this. But looks like the moment doesn't allow modification in moment.js file.

![github](https://user-images.githubusercontent.com/29771798/66512000-ae14da00-eaf5-11e9-854b-7be7c50e1ec3.png)

**Comment by dmattox10** [comment]
Trying to fix this for Hacktoberfest, and it looks like I need to edit the Grunt tasks, including but not limited to "bump_version" but I can't figure out how to "build" to test my changes before submitting a PR?

**Comment by RVMac** [comment]
Hi, I would like to contribute. Any work needs to be done here?

**Comment by harkue** [comment]
Hi, I would like to work on this issue since some PR is tried to fix this but all of them had modified the generated files which should not allowed to.

**Comment by ichernev** [comment]
I don't see a clear reason why the comments were removed. Possibly some package update caused it. The place to fix it is `tasks/transpile.js`, when a suitable fix is found it will be merged.

rollup is not supposed to drop comments, there are plugins for that, but there is something happening automagically, I suppose.

**Comment by marwahaha** [comment]
I think it's back, looking at 2.25.3.
Please re-open if you still have issues.
