### ISSUE TITLE
Error Expected hexadecimal digit in moment-with-locales.min.js at line 1:250337

### ISSUE THREAD

**Issue by marcomarsala** [moment/moment#5058]
Please find below a Sentry screenshot:

![image](https://user-images.githubusercontent.com/5349718/55227472-d99a3c00-5217-11e9-9f68-bd539536db0b.png)

**Comment by ashsearle** [comment]
@marcomarsala You've attached a screenshot for jszip, not moment.

If you upload a new screenshot, perhaps you could also include the moment version?

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
