### ISSUE TITLE
Wrap date in HTML

### ISSUE THREAD

**Issue by konekoya** [moment/moment#5059]
**Is your feature request related to a problem? Please describe.**
Not sure if this has been raised before? I've done a bit search in previous issues but couldn't find anything related to this 😅 

I'm currently building an app that has a special [date format](https://dribbble.com/shots/2451888-ToDo-List) display in the UI (see the date format on the left of that screenshot). I'm using moment.js to get the correct format. Now, I got the right format but not able to change the layout to what I'd like as the date is just a string generated by moment.js

**Describe the solution you'd like**
Wrap day, month and year in HTML tags so that I can style them differently

**Describe alternatives you've considered**
Hmm, if there's an alternative. I'd be very happy to give a shot

**Additional context**
Thanks 😄

**Comment by ashsearle** [comment]
I'm not sure exactly what HTML you want, but you could use `[...]` in the format string:
```js
moment().format('[<span class="date">]DD[</span><span class="month">]MMM[</span><span class="year">]YYYY[</span><span class="day">]dddd[</span>]');
// returns
'<span class="date">04</span><span class="month">Apr</span><span class="year">2019</span><span class="day">Thursday</span>'
```

It'll allow newlines too - e.g. if you want to use a template string:
```js
moment().format(`[<span class="date">]DD[</span>
<span class="month">]MMM[</span>
<span class="year">]YYYY[</span>
<span class="day">]dddd[</span>]`)
// returns
`<span class="date">04</span>
<span class="month">Apr</span>
<span class="year">2019</span>
<span class="day">Thursday</span>`
```

**Comment by konekoya** [comment]
@ashsearle This worked for me! Thanks for the help :)
