### ISSUE TITLE
.fromNow time from now  bug

### ISSUE THREAD

**Issue by xxyuk** [moment/moment#5060]
**Describe the bug**

`moment().subtract(44, 'day').fromNow()` returns `2 months ago`

in the document,

26 to 45 days output should be  `a month ago`

**To Reproduce**
```
moment().subtract(44, 'day').fromNow()
```

**Expected behavior**
result `a month ago`

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser node
 - Version 2.22.1

**Comment by kakasahebKK** [comment]
Reproducible: https://jsfiddle.net/fvxt96o0/ will submit PR soon.

**Comment by kakasahebKK** [comment]
Opps! looks like a bug on the docs too, It should be 26 to 44.

![image](https://user-images.githubusercontent.com/19531557/55712630-b9832d80-5a0c-11e9-83e1-c9af61949e1a.png)

**Comment by xxyuk** [comment]
@kakasahebKK That is to say, is a bug on the docs not moment lib, right?

**Comment by kakasahebKK** [comment]
@xxyuk bug is still there in lib, since even if we correct docs to 44 it should return `a month ago`,  but it does not.

**Comment by marwahaha** [comment]
Thanks for opening this request .I get `a month ago` from the above code and the JSFiddle...

**Comment by mantinone** [comment]
I also get `a month ago` in the JSFiddle.  I played with the numbers, and I don't see `2 months ago` until I make it 47 days.

So, it's still inconsistent with the docs.  

Are other people seeing the same, or different results?
I'm running Chrome v. 79.0.3945.88 on a macbook with High Sierra 10.13.4.
I also wonder if it might give a different result at different times of day.

**Comment by marwahaha** [comment]
I ran this on the fiddle that was linked. 
44, 45 gave 1 month ago
46 gave 2 months ago.

This seems ok. Please re-open if you still have issues or concerns.
