### ISSUE TITLE
Incorrect time is recognized as correct

### ISSUE THREAD

**Issue by seropaski** [moment/moment#5062]
**Describe the bug**
Incorrect date is recognized like correct.

For example I type *12:z13* and get the result that this string is valid for format *HH:mm*

![image](https://user-images.githubusercontent.com/30726708/55478018-3edc9b80-5623-11e9-9b80-553e1e6affe2.png)

Why an incorrect time string recognized like correct?

**Comment by ashsearle** [comment]
Use [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/):

```js
moment('12:z23', 'HH:mm').isValid(); // true
moment('12:z23', 'HH:mm').format('HH:mm'); // '12:23'
moment('12:z23', 'HH:mm', true).isValid(); // false
moment('12:z23', 'HH:mm', true).format('HH:mm'); // 'Invalid date'
```
