### ISSUE TITLE
whatever-99 string is recognized as a date

### ISSUE THREAD

**Issue by marioanloru** [moment/moment#5063]
**Describe the bug**
I receive strings and I have to validate if it is a Date or not, as I have to execute different processes with the type of the string. I don't know the date format I will receive, so I cannot use String + Format predefined. Every string that I get with the format xxxx-yy being yy numbers, will be valid as Date, and they should not.

**To Reproduce**
Execute moment('whatever-99').isValid() and it will return true, as if it were a Date

**Expected behavior**
It should return false

**Comment by ashsearle** [comment]
You're faced with an impossible task: validate a string without knowing the validation rules.

You can't do it.

Is '1' a valid date?

If you don't tell moment what format to use to parse, it generally falls back to using the browser's own Date parsing abilities, which can be... interesting / unpredictable.

e.g. here's some results parsing in Chrome in London.

```js
new Date('1').toISOString(); // "2001-01-01T00:00:00.000Z"
new Date('11').toISOString(); // "2001-11-01T00:00:00.000Z"
new Date('111').toISOString(); // "0111-01-01T00:01:15.000Z"
new Date('1111').toISOString(); // "1111-01-01T00:00:00.000Z"
new Date('11111').toISOString(); // "+011111-01-01T00:00:00.000Z"
new Date('111111').toISOString(); // "+111111-01-01T00:00:00.000Z"
new Date('9').toISOString(); // "2001-08-31T23:00:00.000Z"
new Date('99').toISOString(); // "1999-01-01T00:00:00.000Z"
new Date('999').toISOString(); // "0999-01-01T00:01:15.000Z"
new Date('9999').toISOString(); // "9999-01-01T00:00:00.000Z"
```

Your example produces the same result as parsing '99' on its own:
```js
new Date('whatever-99').toISOString(); // "1999-01-01T00:00:00.000Z"
```

**Comment by marwahaha** [comment]
If you don't specify a parse strategy, then we will make a best guess at parsing.
http://momentjs.com/docs/#/parsing/string/

Please re-open if you still have issues.

see also #5065
