### ISSUE TITLE
Parse bug for dates starting with a +

### ISSUE THREAD

**Issue by aaronryden** [moment/moment#5065]
**Describe the bug**
Invalid date strings with a + in front get parsed

**To Reproduce**

moment('+201412-11-12T05:00:00.000Z').format()
17:56:20.570 "201412-11-12T00:00:00-05:00"
17:57:40.092 moment('+201412-11-12T05:00:00.000Z').format('YYYY MM DD')
17:57:40.100 "201412 11 12"
17:57:54.238 moment('+201412-11-12T05:00:00.000Z').format('YYYY')
17:57:54.246 "201412"

**Expected behavior**
The date should not be valid

**Comment by ashsearle** [comment]
It's valid:

```js
moment('+201412-11-12T05:00:00.000Z').toISOString();
// returns "+201412-11-12T05:00:00.000Z"
```

**Comment by marwahaha** [comment]
If you don't specify a parse strategy, then we will make a best guess at parsing.
http://momentjs.com/docs/#/parsing/string/

Please re-open if you still have issues.
