### ISSUE TITLE
Docker - Daylight Savings Check with Moment - Not Working

### ISSUE THREAD

**Issue by LBorn** [moment/moment#5067]
**Describe the bug**
I am trying to do a daylight savings check in my docker container and the result is always false. I also tried the example code to run in my container on start and they both ended up false.
```
moment([2011, 2, 12]).isDST(); // false, March 12 2011 is not DST
moment([2011, 2, 14]).isDST(); // true, March 14 2011 is DST <--- I'm getting false for this
```
I created a javascript file with moment and was able to get correct output of the above code. False and True respectively.

**To Reproduce**
I installed moment in the package.json.
Created a docker container with the package.json.
Wrote code in the container to determine if a date is daylight savings. 

**Expected behavior**
I expect that the daylight savings check to work in Docker. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave Version: 10.14.4
 - Browser: Chrome Version: 73.0.3683.86

**Moment-specific environment**

* The time zone setting of the machine the code is running on
Eastern Time Zone
* The time and date at which the code was run
Today
* Other libraries in use (TypeScript, Immutable.js, etc)
Just moment right now in the test file. 

Test File: 
```
var moment = require('moment');
moment().format();
console.log('moment([2011, 2, 14]).isDST();',moment([2011, 7, 14]).isDST().toString())
```

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

Locally when i run a simple js file.
Output is: 
```Mon Apr 08 2019 10:45:05 GMT-0400 (Eastern Daylight Time)
4/8/2019, 10:45:05 AM
240
ReferenceError: navigator is not defined
Moment Version: 2.24.0

When i run this in my docker container: 
Mon Apr 08 2019 14:47:13 GMT+0000 (Coordinated Universal Time)
4/8/2019, 2:47:13 PM
0
2.24.0
/usr/src/app/dst/test_dst.js:13
console.log(navigator.userAgent)
            ^

ReferenceError: navigator is not defined

Looks like the offsets are off.

**Additional context**
Add any other context about the problem here.

**Comment by ashsearle** [comment]
Your docker container doesn't appear to inherit your machine's timezone.  Do you need to explicitly [set up timezone in Docker](https://serverfault.com/q/683605)?

**Comment by LBorn** [comment]
@ashsearle Hey i looked into moment-timezone
var tz = 'America/New_York'
var dt = new Date();
console.log('moment.tz(dt,tz).isDST()',moment.tz(dt,tz).isDST());

returns true!
