### ISSUE TITLE
Why moment does not have a weekOfMonth function?

### ISSUE THREAD

**Issue by mfaheemakhtar** [moment/moment#5070]
**Is your feature request related to a problem? Please describe.**
I just want to check if a date, 1, 2, 3, or 30, lies in which week of the month.

**Describe the solution you'd like**
If the date is 3, the week should be 1.
If the date is 8, the week should be 2. 

I'm using:
const week = Math.ceil(moment().date() / 7);

**Additional context**
I've read some answers and issues. Is not it technically correct to consider:
01-07 | week 1
08-14 | week 2 and so on.

I know the week day, Sunday, Monday, etc are different but why not this?

**Comment by ashsearle** [comment]
There are various ways to calculate 'week of year', and 'week of month' would be no different.  Consider that Jan 1st could be part of week 0, 1, 52 or 53, depending on year and week-numbering system.

You can add your own `weekOfMonth()` method by extending the moment prototype exposed via `moment.fn`:

```js
moment.fn.weekOfMonth = function() {
  return Math.ceil(this.date() / 7);
};

console.log(moment('2019-04-11').weekOfMonth()); // 2
console.log(moment('2019-04-28').weekOfMonth()); // 4
console.log(moment('2019-04-29').weekOfMonth()); // 5
```
