### ISSUE TITLE
Adding support for narrow day of week abbreviations

### ISSUE THREAD

**Issue by nkinser** [moment/moment#5071]
Would it be possible to add support for narrow day of week abbreviations, denoted for English [here](https://github.com/unicode-cldr/cldr-dates-modern/blob/master/main/en/ca-generic.json#L115)? Thus, `moment().format([some new keyword])` would return a one letter representation for the day of week. 

I saw a [previous issue](https://github.com/moment/moment/issues/4426) related to this which was closed, but the solution of overriding the abbreviations with `updateLocale` is unrealistic for a website that supports many locales.

**Comment by marwahaha** [comment]
Thanks for suggesting this!

I think it's an interesting idea. Unfortunately, I don't think we will get to this in the near future.

I'll leave it open to see what others think.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

We will not add any new tokens.
