### ISSUE TITLE
when i use ant-design-vue DatePicker,should i Introduction of one date to moment.endOf function,like moment.endOf('2019-04-11')

### ISSUE THREAD

**Issue by babydada** [moment/moment#5072]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by marwahaha** [comment]
Thanks for opening this request. Unfortunately I'm not sure what you're asking here.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
