### ISSUE TITLE
YY should match 2 or 4 digits?

### ISSUE THREAD

**Issue by conartist6** [moment/moment#5077]
Documentation claims that YYYY should match 2 - 4 digit years. In strict parsing however it only matches 4 digit years, and YY only matches 2 digit years.

Not only does the function not do what is documented, it seems like it makes far more sense to require YYYY to be a full 4 digits (so that moment may be used to demand truly unambiguous input), while YY could then be either two or four, similar to how M can be either 01 or 1, as D can be (even in strict mode).

Note that there is also Y, but Y does not have YY's logic of treating 12 as 2012 instead of 0012

**Comment by marwahaha** [comment]
Documentation is updated for YYYY

**Comment by Yokubjon-J** [comment]
Hello! Can I start working on this bug?

**Comment by marwahaha** [comment]
The docs are updated.

I think it makes sense to leave as is -- YY will only accept 2-digit years.

See also https://momentjs.com/docs/#/-project-status/
