### ISSUE TITLE
Locales in pt wrongly and strange defined and packed to the distribution

### ISSUE THREAD

**Issue by azn1viet** [moment/moment#5078]
I'm working with pt, the standard i18n in the latest moment-with-locales.min.js version 2.24.0 distribution is packed to the following:
   
monthNamesShort: ['jan', 'fev', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'set', 'out', 'nov', 'dez'],

while it should be:

monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],

so when I do the formatting like below, it will give "invalid date"::  

moment(dateTime, dateTimeFormat).locale('pt').format('YYYY||MM||DD||HH||mm');

with the modification to look like the same wrongly defined packed, it's working well.

![snip_20190416112320](https://user-images.githubusercontent.com/769104/56224261-51040400-603d-11e9-82d0-1d368d83fb68.png)
![snip_20190416111311](https://user-images.githubusercontent.com/769104/56224281-5b260280-603d-11e9-8099-f8ed3269d6bc.png)

**Comment by ashsearle** [comment]
Where did you get your `moment-with-locales.min.js` from?

**Comment by azn1viet** [comment]
I think the issue I got from our .pt translation override the moment-with-locales.min.js. I checked back the moment-with-locales.min.js downloaded from momentjs.com is right. So no issue with moment-with-locales.min.js.
