### ISSUE TITLE
momentjs returning a different result in browser than in karma unit test

### ISSUE THREAD

**Issue by aubrey-fowler** [moment/moment#5079]
I am writing some unit tests for my AngularJS app with karma and jasmine. I am also using momentjs.

When I call the same function from the moment library in the browser I get a different result than from the karma unit test.

It's breaking my unit tests.

In the browser this is what I get:
![Browser](https://user-images.githubusercontent.com/1875260/56284207-bde5cf80-610b-11e9-958c-4f6f2c609a88.PNG)

In my unit test I get a different result. For example when I call the function to get the start of the month and week I get '1' instead of 53 for the week number.

```
Calendar.data.currentCalendarMonth = moment('01-01-2017', dateFormat).clone().startOf('month');
//showing different results than in the browser
console.log(Calendar.data.currentCalendarMonth.format());
console.log(' week ', Calendar.data.currentCalendarMonth.week());
```

![TEST](https://user-images.githubusercontent.com/1875260/56284254-dc4bcb00-610b-11e9-92cb-da2b604caae3.PNG)

Here is my codepen with the reproduced bug: https://codepen.io/aubz/pen/VNQjgV

Edit: I am using these moment dependencies in my project:

```
"moment-timezone": "0.5.4",
'moment/min/moment-with-locales.js',
'moment-timezone/builds/moment-timezone-with-data.js',
```

**Comment by marwahaha** [comment]
Can you try with the latest versions of moment & moment-timezone?

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.
I don't think the unit test should affect Moment.
