### ISSUE TITLE
Inconsistency between outputs from the same source code

### ISSUE THREAD

**Issue by wellyal** [moment/moment#5083]
**Describe the bug**
I have some weird inconsistency between the code I execute inside my application and the code I just type in chrome dev tools (within momentjs website) 

The following code:
`moment('1989-01-15').locale('pt-br').format('L')`
gives me this output when I put into the console
**output**:
15/01/1989

which is exactly what I expect

But now here comes the magic, when I try to execute the same code inside [CRA](https://github.com/facebook/create-react-app) I have a different result.
**output**:
01/15/1989

**To Reproduce**
1. Create an app with create-react-app 
2. Install momentjs
3. console.log this line of code `moment('1989-01-15').locale('pt-br').format('L')`'
4. Check the output

**Expected behavior**
My output to be in 'DD/MM/YYYY' format which for the current value is 01/15/1989

**Screenshots**
output from console
![image](https://user-images.githubusercontent.com/3047016/56540497-48309800-653f-11e9-8fd0-e4f6c9214281.png)

output from create react app
![image](https://user-images.githubusercontent.com/3047016/56540571-77dfa000-653f-11e9-9a90-2c53670d7a8f.png)

**Desktop (please complete the following information):**
 - OS: [Mac High Sierra ]
 - Browser [chrome]
 - Version [10.13.6]

**Moment-specific environment**
2.24.0

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
Mon Apr 22 2019 10:55:58 GMT-0300 (Horário Padrão de Brasília)
console.log((new Date()).toLocaleString())
22/04/2019 10:55:58
console.log((new Date()).getTimezoneOffset())
180
console.log(navigator.userAgent)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
console.log(moment.version)
moment doen't get exposed to the global context in a react app
```

**Comment by ashsearle** [comment]
This is probably caused by the [webpack config excluding moment locales](https://github.com/facebook/create-react-app/blob/a0030fcf2df5387577ced165198f1f0264022fbd/packages/react-scripts/config/webpack.config.prod.js#L350-L355)

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
