### ISSUE TITLE
Inconsistency between moment/format before 1911-03-11

### ISSUE THREAD

**Issue by nyddogghr** [moment/moment#5085]
**Describe the bug**
Using `moment` and `format` on an ISO date before a particular date (around 1911-03-11) produces strange results.

**To Reproduce**
On the console:
```
moment("1911-03-10T23:51:38.000Z", moment.ISO_8601, true).format()
// "1911-03-11T00:00:59+00:15"

moment("1911-03-10T23:51:39.000Z", moment.ISO_8601, true).format()
// "1911-03-10T23:51:39+00:00"
```

**Expected behavior**
Using `moment(iso_date_string).format()` should give exactly the same ISO date string.

**Desktop:**
 - OS: archlinux 5.0.5-arch1-1-ARCH x86_64
 - Browser: chromium 73 / firefox 66

**Moment-specific environment**

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
Results on chromium:
```
Tue Apr 23 2019 12:10:19 GMT+0200 (Central European Summer Time)
23/04/2019, 12:10:19
-120
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
2.24.0
```
Results on firefox:
```
Tue Apr 23 2019 12:18:46 GMT+0200 (Central European Summer Time) 
4/23/2019, 12:18:46 PM 
-120 
Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0 
2.24.0 
```

**Additional information**

Using `moment.utc("1911-03-10T23:51:38.000Z", moment.ISO_8601, true).format()` works correctly.

**Comment by ashsearle** [comment]
This sounds like its due to historic timezone changes in your locale ([similar issue here.](https://github.com/moment/moment/issues/4694#issuecomment-404094408))

Ignoring the quirky timezone change, you might find `toISOString()` more reliable if your aim is to consistently format in UTC.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
