### ISSUE TITLE
.diff returns wrong values for years

### ISSUE THREAD

**Issue by cdiebolt** [moment/moment#5089]
**Describe the bug**
The difference between (date + 5 days) and (date - 1000 days), rounded to 2 decimals doesn't give always the same number, depending on the date used.

**To Reproduce**
1. Set your timezone to GMT+2 (Central Europe)
2. Evaluate moment(moment('2019-04-25').add(5,'days')).diff(moment('2019-04-25').add(-1000,'days'), "years", true).toFixed(2);
3. Evaluate moment(moment('2019-04-26').add(5,'days')).diff(moment('2019-04-26').add(-1000,'days'), "years", true).toFixed(2);
4. The first statement returns 2.75 and the second 2.76. 

http://jsfiddle.net/cdiebolt/1ja2z9mp/16/

**Expected behavior**
Since we define an interval with a constant length in days, simply based on a different starting day, we would expect the length in years to be constant. In that case: 1005 days, so 2.75342465753 years, considering 365 days in a year.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 73.0.3683.103

**Smartphone (please complete the following information):**

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
Fri Apr 26 2019 15:15:58 GMT+0200 (heure d’été d’Europe centrale)
26/04/2019 à 15:15:58
-120
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
2.24.0

**Additional context**
NA

**Comment by marwahaha** [comment]
I don't know why this calculation would assume 365 days in a year, since that is not always the case.
