### ISSUE TITLE
expected to get February but got March when I set 2 as month

### ISSUE THREAD

**Issue by fengxinming** [moment/moment#5093]
**Describe the bug**
expected to get February but got March when I set 2 as month

**To Reproduce**
1. const date = moment();
2. date.set('year', 2000);
3. date.set('month, 1);
4. console.log(date.format('YYYY-MM-DD')); // => 2000-03-01

**Expected behavior**
console.log(date.format('YYYY-MM-DD')); // => 2000-02-29

**Screenshots**
none

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
Tue Apr 30 2019 11:31:20 GMT+0800 (中国标准时间)
VM147:2 2019/4/30 上午11:31:20
VM147:3 -480
VM147:4 Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Mobile Safari/537.36
@latest
```

**Additional context**

**Comment by marwahaha** [comment]
> Note: Months are zero indexed, so January is month 0.


https://momentjs.com/docs/#/get-set/month/

Please re-open if you still have issues.
