### ISSUE TITLE
Community Invitation to the OpenJS Collaborator Summit + Info

### ISSUE THREAD

**Issue by jorydotcom** [moment/moment#5096]
*Hi all! In an effort to make sure we're fully getting the word out to OpenJS Foundation project communities about the collaborator summit, I'm posting the following message on main or admin repos:* 

This year, the Node Collaborator summit is opening up to include and welcome all former JS Foundation projects. The Collaborator summit is a space where projects and working groups within projects have the dedicated time and space to get together and get work done. We will have project-specific meetings, cross-project meetings on issues like security and standards, and of course meetings to discuss new programs and patterns for the new CPC. 

The event will be in Berlin on May 30-31st at the Courtyard Marriott City Center. It is free to register with the password 'collabsummit.' We are also inviting all projects/attendees to suggest meetings and sessions via our CFP - these are not conference talks, but rather collaborative conversations or meetings you would like to hold with your peers. We ask that you register in advance so that we can allocate meeting room space and resources, and so that we can publish where conversations are scheduled in the day or two leading up to the event.

Links:
* [Session Proposals](https://docs.google.com/forms/d/e/1FAIpQLScneYhY4iqm8x2C2AO9EEzJ5smkOKhLqfxEMQcfNvP5rvXfHg/viewform?usp=sf_link)
* [Registration](https://www.eventbrite.com/e/openjs-collaborator-summit-tickets-55985971548) (password is collabsummit)
* Information on how to apply for the [Travel Fund](https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md)
* [Summit Planning Repo](https://github.com/nodejs/summit/issues)

**Comment by marwahaha** [comment]
Thanks for opening this.

cc @icambron @maggiepint @ichernev et al
