### ISSUE TITLE
Inconsistent moment(object) behaviour when using date: 0 and day: 0

### ISSUE THREAD

**Issue by jnelssonsmith** [moment/moment#5097]
**Describe the bug**
When creating a moment from an object, there is inconsistent behaviour between the use of the `day` and `date` key when setting to `0`

**To Reproduce**
[Jsfiddle here](https://jsfiddle.net/03qfr4y7/8/)

Create moment using object and `day` key set to 0
```js
var momentUsingDayKey = moment({
   day: 0,
  month: 2,
  year: 1990
}).format();    // => Thu Mar 01 1990 00:00:00 GMT+1100
```

**Expected behavior**
Instead this should behave exactly the same as using `day: '0'`, `date: '0'` or `date: 0`
where it is flagged as an invalid date 
```js
var momentUsingDayKey = moment({
   day: 0,
  month: 2,
  year: 1990
}).format();    // => Invalid date
```

**Moment-specific environment**
Moment Version 2.24.0

**Comment by erfanio** [comment]
Hey I’m running into this as well. Would love a fix

**Comment by cslecours** [comment]
`day` is DayOfWeek, it can start from zero ( By default, sunday is `0` and saturday is `6` ).
`date` is DayOfMonth, it **cannot** start from zero.

It's easy to confuse them, but they're not the same thing.
