### ISSUE TITLE
isBetween returns true and false when passed undefined

### ISSUE THREAD

**Issue by chhams** [moment/moment#5100]
**Describe the bug**
The isBetween() function is returning different answers to the same question, when called with an undefined value. 

**To Reproduce**
```
const moment = require('moment');

let i;
for (i = 0; i < 10; i++) {
   console.log(moment().isBetween('2019-01-01T00:00:00.000Z', undefined));
}

```

**Expected behavior**
The code should always print "true"

**Current behavior**
Returned values are randomly true or false, e.g.:
true
true
false
true
false
false
false
false
true
false

**Enviroment**
moment: 2.24.0
node.js: 10.15

**Additional context**
momentjs is used as stated in the docs:
https://momentjs.com/docs/#/query/is-between/

**Comment by kaushikkishore** [comment]
I feel this behavior is correct. As per the document the `undefined` is equivalent to `moment()`, so when the loop is running and both the `moment()` is producing same time then it will be `true` else it will be `false`.
As per the document ** The match is exclusive**

Here is code to justify the answer. 
`const moment = require("moment");

let i;
for (i = 0; i < 10; i++) {
  let x = moment();
  console.log(x.isBetween("2019-01-01T00:00:00.000Z", x));
}`

output 
`false
false
false
false
false
false
false
false
false
false`

and when there is a time gap then it will always print `true`

`const moment = require("moment");
let i;
for (i = 0; i < 10; i++) {
  let x = moment();
  let y = moment().add(1, "s");
  console.log(x.isBetween("2019-01-01T00:00:00.000Z", y));
}`

output 
`
true
true
true
true
true
true
true
true
true
true
`

Conclusion is -> in the loop when two moments are getting time next to each other then it is `true` or when each one is getting same time it is resulting `false`. Its the loop which is causing this. 

I think this is not a _bug_

**Comment by rtroncoso** [comment]
In case anyone is still wondering how to fix this, there's another workaround which is to use the fourth parameter of  `isBetween` that indicates interval inclusion/exclusion.

Here is a jsFiddle demonstrating both behaviors side by side: https://jsfiddle.net/t4s6w5mc/3/

Thanks @kaushikkishore for the insight on this issue!

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
