### ISSUE TITLE
Motivate morale of moment-duration-format

### ISSUE THREAD

**Issue by Noitidart** [moment/moment#5102]
**Is your feature request related to a problem? Please describe.**
https://github.com/jsmreese/moment-duration-format - he did amazing work. I'm worried it might lose support if we don't maintain his morale.

This would resolve https://github.com/moment/moment/issues/1048.

**Describe the solution you'd like**
Pay him regularly for support. Hire him if you're a company. 

**Describe alternatives you've considered**
Searched a lot, nothing competes with this his work.

**Additional context**
none

**Comment by marwahaha** [comment]
Thanks for opening this request.  Tagging @jsmreese so he sees how much you appreciate his work!

Moment.js is an open source project, under the [JS Foundation](https://js.foundation/) (now the OpenJS Foundation). Please use his plugin if you would like!

If anyone have other ideas, feel free to add to this thread.

**Comment by Noitidart** [comment]
Thanks @marwahaha
