### ISSUE TITLE
moment("2019-02-01").date(31).format("YYYY-MM-DD") returns "2019-03-03"

### ISSUE THREAD

**Issue by minddust** [moment/moment#5108]
**Describe the bug**
The [docs state here](https://momentjs.com/docs/#/get-set/date/) that:
> ... when day=31 and current month has only 30 days (the same applies to native JavaScript Date manipulation), the returned date will be the 30th of the current month ...

but this is currently not the case (anymore?)

**To Reproduce**
1. `moment("2019-02-01").date(31).format("YYYY-MM-DD")`
2. See wrong result: `"2019-03-03"`

**Expected behavior**
returns `"2019-02-28"` <-- date with only day replaced (capped at daysInMonth).

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser: Chrome, Safari
 - Version: 2.24.0

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
VM1503:1 Wed May 15 2019 12:37:05 GMT+0200 (Central European Summer Time)
VM1503:2 15/05/2019, 12:37:05
VM1503:3 -120
VM1503:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
VM1503:5 2.24.0
```
Also: i didn't see any tests covering the behaviour described in the docs.

**Comment by ashsearle** [comment]
The docs state:
> Accepts numbers from 1 to 31. If the range is exceeded, _it will bubble up to the months_.

The part you quoted was advice to help when chaining methods together:
```js
moment('2019-02-01').month(2).date(31).format('YYYY-MM-DD'); // 2019-03-31
moment('2019-02-01').date(31).month(2).format('YYYY-MM-DD'); // 2019-03-03
```

**Comment by minddust** [comment]
must have misinterpreted the docs. my bad. thought it was a shortcut for:

```
date_in_feb = moment("2019-02-01")
last_date_in_feb = date_in_feb.date(date_in_feb.daysInMonth())
```

closing this. thanks.

**Comment by ashsearle** [comment]
@minddust That'd be `moment().endOf('month')` (as long as you don't mind the time changing) :smile:

**Comment by minddust** [comment]
@ashsearle I don't! that's what i was looking for xD thanks a lot!
