### ISSUE TITLE
pt-BR localization - month names should not be capitalized

### ISSUE THREAD

**Issue by kendramae** [moment/moment#5109]
Month names should not be capitalized in Portuguese  (See: https://meta.wikimedia.org/wiki/Capitalization_of_Wiktionary_pages#Capitalization_of_month_names) It looks like it originally was correct, but then was changed? (See: https://github.com/moment/moment/pull/4557) -- it may be as simple as reverting that commit.

**Comment by AbidemiT** [comment]
Hello kendramae can I work on this issue?

**Comment by davidrock** [comment]
It depends of the situation. Here in Brasil we need to capitalize when it is an proper noun. 

Common example: "I was born in January":

CORRECT: Eu nasci em _janeiro_.
WRONG: Eu nasci em _Janeiro_.

Proper noun example: "September 11 attacks":
CORRECT:  Ataques de 11 de _Setembro_
WRONG: Ataques de 11 de _setembro_

We also need to capitalize when it is a single word or it is the first word of a phrase/sentence.
To be honest, I don't think it is that important or is something to be "fixed".

**Comment by sayhicoelho** [comment]
Ainda bem que sei usar a pesquisa, porque já estava abrindo uma issue pra isso mesmo. Parece que o jeito é usar toLowerCase().

I'm glad I use the search, because I was already opening an issue for that. It seems like the way to use toLowerCase().

**Comment by sayhicoelho** [comment]
> It depends on the situation. Here in Brasil we need to capitalize when it is an proper noun.
> 
> Common example: "I was born in January":
> 
> CORRECT: Eu nasci em janeiro.
> WRONG: Eu nasci em Janeiro.
> 
> Proper noun example: "September 11 attacks":
> CORRECT: Ataques de 11 de Setembro
> WRONG: Ataques de 11 de setembro
> 
> We also need to capitalize when it is a single word or it is the first word of a phrase/sentence.
> To be honest, I don't think it is that important or is something to be "fixed".

No, it not depends on the situation. 11 de Setembro is not a date, is a historical fact.

We need to capitalize only when the month starts in the beginning of phrase.

Correct: Iniciou em 01 de janeiro.
Wrong: Iniciou em 01 de Janeiro.

Correct: Janeiro foi o dia da viagem.
Wrong: janeiro foi o dia da viagem.

**Comment by kylekatarnls** [comment]
moment should provide the default case as per the locale rule (lower case for pt-BR), and if you have a special case to handle (start of sentence), it's no longer the responsibility of moment (does not depends the locale most of the time and never depends on the date itself) so it should be handled afterward: `.toUpperCase()` on the first letter for example.
