### ISSUE TITLE
Incorrect parsing glued hours/minutes when hour is greater than 24

### ISSUE THREAD

**Issue by juanjoms** [moment/moment#5110]
**Describe the bug**

As per docs: parsing `hmm`, `Hmm`, `hmmss` and `Hmmss` is supported:

```
moment("123", "hmm").format("HH:mm") === "01:23"
moment("1234", "hmm").format("HH:mm") === "12:34"
```

When I try with:
`moment("2523", "hmm").format("HH:mm")` i get` 'Invalid date'`

jsFiddle demostrating the issue: https://jsfiddle.net/ytmk38w9/

If is this intended, how can I achieve the following ouput: `25h 23m //Elapsed time` from the string `"2523"` ?

**Comment by ashsearle** [comment]
That does't need moment at all:

```js
var str = '2523';
console.log(`${str.slice(0, -2)}h ${str.slice(-2)}m`); // 25h 23m
var str = '123';
console.log(`${str.slice(0, -2)}h ${str.slice(-2)}m`); // 1h 23m
```

**Comment by juanjoms** [comment]
Thanks for the response, and right, moment is not necessary for that scenario. This issue can be closed.
