### ISSUE TITLE
moment('1398-02-29').format()

### ISSUE THREAD

**Issue by meysambostak** [moment/moment#5112]
moment('1398-02-29').format()
"Invalid date"

**Comment by sefam-vbastien** [comment]
Hello,
It seems there is no 29 February of the year 1398. It works using moment('1398-02-28').format()
[src](https://www.timeanddate.com/calendar/?year=1398&country=5)

**Comment by meysambostak** [comment]
Hello,
No, this is history in Iran.
[Link](https://www.timeanddate.com/calendar/?year=1398&country=75)

**Comment by sefam-vbastien** [comment]
I may have misread but the source you provided just said that February in 1398 for your country has only 28 days.

**Comment by marwahaha** [comment]
I agree with @sefam-vbastien .

Please re-open if you still have issues.
