### ISSUE TITLE
Add doc warnings for YYYY-MM-DD?

### ISSUE THREAD

**Issue by CoryDanielson** [moment/moment#5114]
I recently discovered that native Date construction with a string in the YYYY-MM-DD format behaves differently than the YYYY-M-D format. This was the root cause of a bug in my code that I've been tracking down over the last 2 days.

```js
new Date('2015-05-05')
// 😱Mon May 04 2015 20:00:00 GMT-0400 (Eastern Daylight Time)

new Date('2015-5-5')
// ✅Tue May 05 2015 00:00:00 GMT-0400 (Eastern Daylight Time)

new Date('2015-5-5').valueOf() === new Date('2015-5-5').valueOf()
// ✅true in FF, Chrome, and my local version of Node

new Date('2015-05-05').valueOf() === new Date('2015-5-5').valueOf()
// 😱false in Chrome, and my local version of Node 
// ✅true in FF
```

This behavior is inconsistent between FireFox and Google Chrome - which seems to introduce a high risk for date-related bugs due to unexpected interactions between Date and Moment.

---

I've filed a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=966076) with Chromium, too

**Comment by ashsearle** [comment]
As this is a problem with `Date`, not `moment` where would you suggest putting this warning?

Note: if you pass `2015-5-5` directly to `moment` you get this deprecation warning:

> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

**Comment by CoryDanielson** [comment]
Hmm, it seems like there could be a section of "gotchyas" under guides, where certain quirks about working with dates could be elaborated or listed? -- but the guides section links out to a few blogs and videos which have that kind of content.

The chromium bug has gotten some attention, hopefully it's addressed soon.
