### ISSUE TITLE
add warning that moment objects are not immutable

### ISSUE THREAD

**Issue by dominikstoetter** [moment/moment#5117]
**Is your feature request related to a problem? Please describe.**
moment objects are not immutable. 
example:
```js
const today = moment.utc()
const yesterday = today.subtract(1, 'day')
```
https://jsfiddle.net/hurwdjkx/3/
today will be mutated to yesterday

**Describe the solution you'd like**
add a warning or document somewhere that moment mutates objects

**Describe alternatives you've considered**
- make moment objects immutable

**Additional context**

**Comment by kylekatarnls** [comment]
From doc of `subtract`, first line:

> Mutates the original moment by subtracting time.

**Comment by kylekatarnls** [comment]
About "make moment objects immutable", it will just break the majority of the applications. Mutability makes sense as the native `Date` object is mutable. Most users rely on this behavior.

**Comment by marwahaha** [comment]
@dominikstoetter Sorry that it caused a problem for you. Please contribute to our documentation at https://github.com/moment/momentjs.com if you would like to make that more visible.
