### ISSUE TITLE
moment(Val1).isSameOrAfter(Val2) fails on Firefox 

### ISSUE THREAD

**Issue by omerpa** [moment/moment#5122]
**Describe the bug**
moment("08-01-2019").isSameOrAfter("06-01-2019") returns true on Chrome but fails on Firefox

**To Reproduce**
Just use the above input 

**Expected behavior**
Should return true always 

**Screenshots**

**Desktop (please complete the following information):**
Desktop machine, OSX, latests build on all 

**Additional context**
 match = extendedIsoRegex.exec(string) || basicIsoRegex.exec(string), - this is the lines that fails , it sets the inernal member isValid to false and thus the test fails

**Comment by ashsearle** [comment]
Those dates aren't in ISO format, and you're therefore relying on browser-dependent behaviour.

This is documented for [`moment(String)`](https://momentjs.com/docs/#/parsing/string/)
> Warning: Browser support for parsing strings is inconsistent. Because there is no specification on which formats should be supported, what works in some browsers will not work in other browsers.

Additionally, you'll get a deprecation warning in the console the first time you try this, with a link to the guide:
> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

**Comment by marwahaha** [comment]
Thanks for opening this request. 
Please re-open if you still have issues.
