### ISSUE TITLE
moment().isValid() not exactly when month start from 100

### ISSUE THREAD

**Issue by huanliooooo** [moment/moment#5126]
**Describe the bug**
moment('2019 99 12 15:21', 'YYYY MM DD HH:mm').isValid() return false. But month start from 100 will return true.
moment('2019 100 12 15:21', 'YYYY MM DD HH:mm').isValid() return true.

**To Reproduce**
Just use the above input

**Expected behavior**
Should return false always

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version: latests build on all

**Comment by ashsearle** [comment]
This is because you're using lenient parsing (by default), which allows moment to match 'MM' against '100' by taking the first two digits '10', and ignoring the rest.

You probably want to use [strict parsing](https://momentjs.com/guides/#/parsing/strict-mode/)

```js
moment('2019 100 12 15:21', 'YYYY MM DD HH:mm', true).isValid(); // false
```

**Comment by huanliooooo** [comment]
Thanks. I got it
