### ISSUE TITLE
2019-05-31 is invalid date

### ISSUE THREAD

**Issue by kiskoza** [moment/moment#5128]
**Describe the bug**
Using the moment() function, it gives invalid date error for 2019 May 31 (which is a valid date today)

**To Reproduce**
1. use moment.js 2.24.0 from cdnjs.com
2. `moment([2019, 5, 30])._isValid` is true
3. `moment([2019, 5, 31])._isValid` is false 

**Expected behavior**
I expect `moment([2019, 5, 31])` to be a valid date

**Desktop:**
 - OS: Linux 18.04
 - Browser: Latest Firefox, Latest Chrome

**Moment-specific environment**

My local timezone on the OS is `Time zone: Europe/Budapest (CEST, +0200)`
I tried to run the code around 2019.05.31 15:00
The error could be reproduced without any other libraries

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
>> Fri May 31 2019 15:16:45 GMT+0200 (Central European Summer Time)
console.log((new Date()).toLocaleString())
>> 5/31/2019, 3:16:58 PM
console.log((new Date()).getTimezoneOffset())
>> -120
console.log(navigator.userAgent)
>> Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
console.log(moment.version)
>> 2.24.0
```

**Comment by csmadhav** [comment]
I guess the month starts from 0 right? so 4 is may `moment([2019, 4, 31])._isValid == true` , and obviously `moment([2019, 5, 30])._isValid` because its june 30th

**Comment by kylekatarnls** [comment]
Indeed `moment([2019, 5, 30]).format('Y-MM-DD')` returns `"2019-06-30"` so to get what you want according to your issue title `2019-05-31`, then you need `moment([2019, 4, 31])`

**Comment by kiskoza** [comment]
Yes, that will be the issue, thanks for you help. (It's a bit confusing that years and days start from one but the others are zero indexed.)

**Comment by kylekatarnls** [comment]
Sadly, it's how the `Date` object itself works in JavaScript. `Date.getMonth` starts with 0, `Date.getDate` starts with 1.
