### ISSUE TITLE
Difference returns NaN

### ISSUE THREAD

**Issue by TheRealAngelus** [moment/moment#5130]
Describe the bug
Difference method returns NaN.

To Reproduce
1. var startObj = moment([2019, 6, 1]);
2. var endObj = moment([2019, 8, 31]);
3. endObj .diff(startObj , "months", true)
4. returns NaN

the other dates work fine
exp:  
1. var startObj = moment([2019, 6, 1]);
2. var endObj = moment([2019, 9, 1]);
3. endObj .diff(startObj , "months", true)
4. returns 3

**Comment by kylekatarnls** [comment]
Hi @TheRealAngelus, 8 is September (0-index due to `Date` native JS object itself) and so 31 september does not exist, it's an invalid date.

**Comment by TheRealAngelus** [comment]
Thank you. I noticed month is zero-based.
