### ISSUE TITLE
Add 1 week to 52 resets back to week 1

### ISSUE THREAD

**Issue by barlowm** [moment/moment#5132]
I saw a closed issue (#3552) but can still reproduce the issue even though I'm using a moment object not a year token:

I've created a [JSFiddle](http://jsfiddle.net/mwbarlow/9c70mrnf/12/) to reproduce this:

```
var week = "2019-50";
var wNum = week.split("-")[1];
var now = moment().day("Monday").week(wNum)
console.log(week, wNum, now.format("YYYY-MM-DD"), now.format("YYYY-WW"))
var wNum = now.week();
var wNum2, yr, str;
for (var i = 1; i < 54; i++) {
  now.add(1, "week");
  wNum2 = now.week();
/*  Uncomment this block to see correct dates
  if (wNum2 < wNum) {
    yr = now.year()+1;
    str = yr + "-" + (wNum2 < 10 ? "0": "") + wNum2;
  }
  else {
    str = now.format("YYYY-WW");
  }
  */
  str = now.format("YYYY-WW");
  console.log(`${now.format("YYYY-MM-DD")} - ${str} - ${wNum} - ${wNum2}`)
  wNum = wNum2;
}
```
Output from above code
```
2019-50 50 2019-12-09 2019-50
2019-12-16 - 2019-51 - 50 - 51
2019-12-23 - 2019-52 - 51 - 52    <------
2019-12-30 - 2019-01 - 52 - 1      <------
2020-01-06 - 2020-02 - 1 - 2
2020-01-13 - 2020-03 - 2 - 3
2020-01-20 - 2020-04 - 3 - 4
2020-01-27 - 2020-05 - 4 - 5
2020-02-03 - 2020-06 - 5 - 6
2020-02-10 - 2020-07 - 6 - 7
```

**Expected behavior**
Adding 1 week to a date close to the end of the year should not return to week one of the current year

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome
 - Version 74.0.3729.169 (Official Build) (64-bit)

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()) - Tue Jun 04 2019 12:46:21 GMT-0400 (Eastern Daylight Time)
console.log((new Date()).toLocaleString()) - 6/4/2019, 12:46:21 PM
console.log((new Date()).getTimezoneOffset()) - 240
console.log(navigator.userAgent) - Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
console.log(moment.version) - 2.24.0
https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js

```

**Comment by martineizayaga** [comment]
The JSFiddle @barlowm made is broken. Here's a [new one](https://jsfiddle.net/kpsayz36/)!

**Comment by raza2022** [comment]
I am facing the same problem @barlowm can you please tell how you solve it

**Comment by ashsearle** [comment]
@barlowm Using `WW` implies you want to use ISO conventions.

To get the correct ISO 'week year' for the week, use `GGGG` instead of `YYYY`.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
