### ISSUE TITLE
Why there is no isWeekend() or something similar?

### ISSUE THREAD

**Issue by bladerunner2020** [moment/moment#5134]
I need to get determine if a particular date is a weekend. The simple solution date.getDay() and compare to 0 or 6 doesn't work for all locales. 

Would be great to have isWeekend(date) that returns true if a date/moment is weekend in the current locale.

**Comment by raghavmac** [comment]
Hi, Would like to contribute on this, Can I?

**Comment by raghavmac** [comment]
[PR](https://github.com/moment/moment/pull/5147) updated! Added couple of locale tests as well for this implementation.
Please let me know if any other changes required! Thanks.

**Comment by milad440550** [comment]
@raghavmac is this feature added, if not I can take a swing at it? 😄

**Comment by raghavmac** [comment]
@milad440550 Please go ahead, also consider @ashsearle comments on the above PR.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

We will not support this feature.
