### ISSUE TITLE
diff() reporting zero, for timestamps that actually differ by 5 minutes

### ISSUE THREAD

**Issue by mcandre** [moment/moment#5135]
The documentation describes a syntax for constructing durations from the difference of two timestamps:

```javascript
var duration = moment.duration(x.diff(y))
```

http://momentjs.com/docs/#/durations/diffing/

However, in practice this results in the wrong duration: 0. In fact, my timestamps have a 5 minute difference, when calculated by hand.

At first, I wondered if the `diff()` method or the `duration()` method have a mismatch of units, like seconds vs milliseconds. But that part seems to be correct.

Then I went back and checked the `diff()` result for my timestamps. Even though my timestamps are `2019-06-06T11:45:09-05:00` and `2019-06-06T11:50:07-05:00` (about 5 minutes apart), `diff()` is calculating *zero* separation between these. So of course the duration becomes zero, as opposed to five minutes.

As a workaround, I am using `subtract()` to mutate the minuend, rendering the post-subtraction object in the desired unit (in my case, milliseconds with `value()`).

**Comment by marwahaha** [comment]
I am not getting the behavior you describe. Can you provide more information?
```
a = moment("2019-06-06T11:45:09-05:00")
b = moment("2019-06-06T11:50:07-05:00")
b.diff(a) // returns 298000, not 0
```

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
