### ISSUE TITLE
subtract() fails on moment timestamp inputs

### ISSUE THREAD

**Issue by mcandre** [moment/moment#5136]
The `subtract()` documentation appears to accept a typical `moment()` timestamp input, for subtracting one time from another.

http://momentjs.com/docs/#/manipulating/subtract/

However, when I try to do this, I get an error and then the minuend fails to be mutated: It remains at the original timestamp rather than the difference.

```console
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: function from (time, withoutSuffix) {
        if (this.isValid() &&
                ((isMoment(time) && time.isValid()) ||
                 createLocal(time).isValid())) {
            return createDuration({to: this, from: time}).locale(this.locale()).humanize(!withoutSuffix);
        } else {
            return this.localeData().invalidDate();
        }
    }, _f: undefined, _strict: undefined, _locale: [object Object]
```

As a workaround, I am taking pains to convert the subtrahend to milliseconds, and then performing `subtract(<ms>, `milliseconds`) on the minuend.

**Comment by marwahaha** [comment]
I don't think `moment.subtract` works with a `Moment` object. If the docs are confusing, please let us know or submit a pull request so we can make it better.

You may want to try using Durations, or `moment.diff`: https://momentjs.com/docs/#/durations/

**Comment by SANJAY072000** [comment]
is this issue still open???
