### ISSUE TITLE
underscores validating?

### ISSUE THREAD

**Issue by chadams** [moment/moment#5140]
**Describe the bug**
Why does the following code return isValid=true?

```
moment("12-25-____", "MM-DD-YYYY").isValid()
```

**Expected behavior**
moment("12-25-____", "MM-DD-YYYY").isValid() === false

**Comment by ashsearle** [comment]
Because parsing is lenient by default.  You need to explicitly request [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/).

```js
moment("12-25-____", "MM-DD-YYYY", true).isValid(); // false
```

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
