### ISSUE TITLE
Archaic numerals in tamil locale

### ISSUE THREAD

**Issue by freezing-arrow** [moment/moment#5142]
The symbol map for tamil numerals is a relic from the medieval times and not in usage. No native speaker would be able to understand them now. Please remove them and use arabic numerals instead which is understood universally by the tamil speakers.

**Comment by naveen-bharathi** [comment]
Those numerals were used atleast 6000 years ago and is not in usage. Please change the numeral system used for tamil.

**Comment by marwahaha** [comment]
thoughts @tk120404 ?

**Comment by tk120404** [comment]
@naveen-bharathi @marwahaha These numerals are still in usage. Please check the government vehicles which uses these numerals in their plate number. So **no changes** will be required.

**Comment by naveen-bharathi** [comment]
These numerals are not used officially in government vehicles. People use these archaic numerals on their own interest in their vehicle number plate. That too is very rare. Have you ever seen tamil archaic numerals being used to display time?? Moment is a date and time library. So tamil archaic numerals can be given as an optional but it must not be default. The default must be 1, 2, 3 not க, கூ, ஞ.
