### ISSUE TITLE
Causing Out-of-Memory crash for users in USA.

### ISSUE THREAD

**Issue by logicware** [moment/moment#5143]
It's causing this error for users in USA, in all browsers on any machine/OS. It works fine for non-US users in any browser on any machine/OS. I am using v2.24.0 in a Reactjs/Nextjs app.

<img width="1271" alt="Screen Shot 2019-06-18 at 12 08 12 PM" src="https://user-images.githubusercontent.com/2248704/59705055-0195ac00-9217-11e9-9e8d-0bcc9b07c28f.png">

**Comment by ashsearle** [comment]
There's not enough information to reproduce or investigate this.

It looks like your application is bundled with webpack, and the problem occurs in a call made from application code in journal-entry.

Do you know what moment-related calls are being made by journal-entry?  Is it one specific call / loop that leads to the out of memory error?

**Comment by logicware** [comment]
@ashsearle It turned out, it wasn't moment.js after all. So no worries. I will close this. Thanks anyway.
