### ISSUE TITLE
Support for humanized times like "5 past 4" or "quarter to 6" etc?

### ISSUE THREAD

**Issue by digitaltoast** [moment/moment#5144]
Does this, or any other library, have support for humanized times like "5 past 4" or "quarter to 6" etc? I'm trying to TTS (speech synthesize) times into something more friendly than "four oh 5" etc.
I've been googling it and found nothing.

**Comment by marwahaha** [comment]
This is a cool idea. Unfortunately, I doubt Moment will support this anytime soon. 
This would be a good project for a Moment plugin.
