### ISSUE TITLE
Getting weird time value when formatting older dates

### ISSUE THREAD

**Issue by LeonidKuznetsov** [moment/moment#5148]
First of all I should say that I'm not sure if it is a bug or expected behavior due to historical reasons or something.

**Bug description**

Parsing date/time string with timezone offset (`YYYY-MM-DDTHH:mm:ssZZ` format) and then formatting it using local timezone produces (seemingly) incorrect value for older dates (prior to ~1920 year, I think) for some timezones.

Example:

Original value:
`1901-05-08T14:15:00+0600`

Formatted values:

*Timezone (UTC+07:00) Bangkok, Hanoi, Jakarta*
`1901-05-08 14:57` - expected something like 15:15 (or 14:45 or 14:15 due to DST or other reasons) - Moment calculated timezone offset for this one as GMT+0642

*Timezone (UTC+06:00) Novosibirsk*
`1901-05-08 13:46` - expected something like 14:15 (or 13:45 or 13:15 due to DST or other reasons) - Moment calculated timezone offset for this one as GMT+0531

*Timezone (UTC-05:00) Eastern Time (US & Canada)*
`1901-05-08 03:15` - this one seems to be fine

**Steps to reproduce the behavior**

Just switch your PC's timezone to one from examples above and run this code in your browser's console on Moment's website:

```language="javascript"

(() => {
  const value = '1901-05-08T14:15:00+0600';
  const inputFormat = 'YYYY-MM-DDTHH:mm:ssZZ';
  const displayFormat = 'YYYY-MM-DD HH:mm';

  console.log(moment(value, inputFormat, true).format(displayFormat));
  console.log(moment(value, inputFormat, true)._d); // I'm not actually using _d in my code. I just noticed while debugging that timezone offset looks weird in there.
})();
```

**Expected behavior**

I'd expect that date/time would be formatted into local date/time with correct timezone offset.

`1901-05-08T14:15:00+0600` - original value
`1901-05-08 15:15` - expected value for UTC+07:00 timezone offset (or maybe 14:45 or 14:15)
`1901-05-08 14:15` - expected value for UTC+06:00 timezone offset (or maybe 13:45 or 13:15)

**Desktop (please complete the following information):**
 - OS: Windows 7 64-bit
 - Browser: Opera
 - Version: 60.0.3255.170

**Moment-specific environment**

* The time zone setting of the machine the code is running on
[(UTC+06:00) Novosibirsk] with DST turned off

* The time and date at which the code was run
2019-06-19 20:30

* Other libraries in use (TypeScript, Immutable.js, etc)
None. Code was executed on Moment's website

Please run the following code in your environment and include the output:
```
Wed Jun 19 2019 21:30:17 GMT+0700 (Novosibirsk Standard Time)
6/19/2019, 9:30:17 PM
-420
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.170
2.24.0
```

**Comment by ZeroCho** [comment]
`new Date('1901-05-08T14:15:00+0600')` gives me Wed May 08 1901 16:42:52 GMT+0827
I think its somewhat related to Javascript's Date object.

**Comment by ZeroCho** [comment]
I found this SO question.

https://stackoverflow.com/questions/50857187/weird-seconds-offset-in-js-date-object-in-chrome

**Comment by LeonidKuznetsov** [comment]
Thank you for the answer. I apologise for the ruckus. I should have dug deeper. This is not a bug then so issue can be closed, right?

**Comment by ZeroCho** [comment]
@LeonidKuznetsov I think it'd be better for members of moment.js to check this issue. As I don't know moment.js follows local mean time.

**Comment by ashsearle** [comment]
Similar issues (#4694 and #5085) have been closed before.

**Comment by marwahaha** [comment]
Thanks for opening this request. Please add to the documentation at https://github.com/moment/momentjs.com if this could be clearer.
