### ISSUE TITLE
Error with moment timezone 

### ISSUE THREAD

**Issue by niyaza3** [moment/moment#5149]
TypeError: V(...).match is not a function
    at vt (moment.js:2424)
    at kt (moment.js:2524)
    at Et (moment.js:2590)
    at Mt (moment.js:2561)
    at St (moment.js:2648)

> import * as momentWithTimeZone from 'moment-timezone';
> 
> const inputFormats = [
>     moment.ISO_8601, 
>     moment.RFC_2822, 
>     'YYYY-MM-DDTHH:mm:ssZ'
> ];
> 
>  momentWithTimeZone.default("2019-06-28T13:30:00+05:30", inputFormats)
>                         .tz(timeZone)
>                         .format(moment.ISO_8601);

**Comment by ZeroCho** [comment]
I think this issue should be put [here](https://github.com/moment/moment-timezone)
