### ISSUE TITLE
Publish typing as a separate package

### ISSUE THREAD

**Issue by PikachuEXE** [moment/moment#5154]
**Is your feature request related to a problem? Please describe.**
`moment` JS size is a big
It's best to exclude it from JS bundle if not used
So in [`pikaday 1.8.0`](https://github.com/Pikaday/Pikaday/releases/tag/1.8.0), `moment` is only included when installed
However since there is no separate typing package for `moment` ([`@types/moment`](https://www.npmjs.com/package/@types/moment) is depreacted)
Many typing packages are including `moment` as dependency instead and this leads to issue of including `moment` in built JS bundle **accidentally**: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/27942

**Describe the solution you'd like**
[As mentioned by member of `DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36252#issuecomment-504637525):
> We generally don't add packages that already have their own types, and I have a feeling we probably won't in this case unless there's been a drastic misunderstanding or exceptional behavior we haven't accounted for.

That means the best way to solve it is to have a separate typing only package (which doesn't include the huge `moment` JS code)
and managed by `moment` team (unless you want to defer the responsibility back to the community, fine for me though)

**Describe alternatives you've considered**
If `moment` team would like other contributors to manage the typing part
Here is an example:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36252
It might be quicker to release fixes/changes this way (based on my past experience with `DefinitelyTyped`

**Additional context**
(none)

**Comment by PikachuEXE** [comment]
Would be good to hear some response so we can discuss about next steps

**Comment by marwahaha** [comment]
I would be ok moving the types to a community-maintained place.

**Comment by marwahaha** [comment]
Someone can publish the typings elsewhere, so you don't need to include moment when you just need its types.
