### ISSUE TITLE
moment.duration().asHoursIntegral()

### ISSUE THREAD

**Issue by dsidirop** [moment/moment#5157]
moment.duration({ hours: 30, minutes: 30 }).asHours()

This returns 30.5. There are cases where we what's being sought after is only the integer part of the total hours. As things stand right now one must write ".asHours() | 0" and of course it works but it feels a bit ... verbose and counter-intuitive especially for someone that's new to momentjs (most people would intuitively resort to .hours() only to be surprised by the fact that they would receive 6 instead of 30).

A direct method like .asHoursIntegral() or something to that effect would help solve this problem.

**Comment by marwahaha** [comment]
I don't think this is necessary. The duration in hours is exactly 30.5 hours. If you want a rounded-down version, you could try
```
Math.floor(moment.duration({ hours: 30, minutes: 30 }).asHours())
```
