### ISSUE TITLE
Any way to get per-locale copies of the whole library?

### ISSUE THREAD

**Issue by ghost** [moment/moment#5159]
I'm using moment in Node/Express, and want to allow visitors to input dates in their default locale date format ("L").  Since the library is global I don't want to set the locale with `moment.locale(...)` as this would mean users stepping on each other's values.

I've tried this:

```javascript
// localeMoment.js
let moment = require("moment");

module.exports = (locale) => {
	return function() {
		let m = moment.apply(moment, arguments);
		
		m.locale(locale);
		
		return m;
	}
}
```

But it doesn't work for parsing, as the locale is set afterwards:

```javascript
let moment = require("./localeMoment")("en-GB");

let m = moment("20/09/1990", "L"); // Invalid date 20/09/1990
```

(This would be valid in en-GB as the days come before the months)

I also don't want to `require("moment")` every time I need a new version of the library, as the `require` would block the app.

**Comment by marwahaha** [comment]
Cool idea.

I don't think we will make any substantial changes to Moment going forward.
https://momentjs.com/docs/#/-project-status/

Perhaps you can change the locale for each moment object.
https://momentjs.com/docs/#/i18n/instance-locale/
