### ISSUE TITLE
moment('Decimal128', 'YYYY-MM-DD').isValid() // true !?

### ISSUE THREAD

**Issue by sam-araiza** [moment/moment#5161]
**Describe the bug**
```moment('Decimal128', 'YYYY-MM-DD').isValid() // true```
It should be false.

**To Reproduce**
```moment('Decimal128', 'YYYY-MM-DD').isValid() // true```

**Expected behavior**
```moment('Decimal128', 'YYYY-MM-DD').isValid()``` should be false

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 75.0.3770.100 (Official Build) (64-bit)

**Moment-specific environment**

* PST
* 2019 July 8 @ 21:56 PM PST

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

```
Mon Jul 08 2019 21:56:52 GMT-0700 (Pacific Daylight Time)
VM44:2 7/8/2019, 9:56:52 PM
VM44:3 420
VM44:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
VM44:5 2.24.0
undefined
```

**Additional context**

**Comment by sam-araiza** [comment]
Note, I'm aware that adding a strict param of true will make this work. Actually looking for loose formatting and would ideally like to get rid of the second param 'YYYY-MM-DD' as well. Date.parse() doesn't work either. Any suggestions for checking if a date is valid for various common date formats? Thanks.

**Comment by harkue** [comment]
> Note, I'm aware that adding a strict param of true will make this work. Actually looking for loose formatting and would ideally like to get rid of the second param 'YYYY-MM-DD' as well. Date.parse() doesn't work either. Any suggestions for checking if a date is valid for various common date formats? Thanks.

You can do it with this:
```js
// strict mode with format array
moment('Decimal 128', ['YYYY-MM-DD', 'DD MM YYYY', ...{more common data formats}], true).isValid()
```

**Comment by marwahaha** [comment]
I agree with @harkue 's suggestion.
Please re-open if you still have issues.
