### ISSUE TITLE
Duration breaks after year 3012

### ISSUE THREAD

**Issue by omarmeky** [moment/moment#5164]
**Describe the bug**

```
moment.duration(moment('3012-11-11').diff(moment('3012-11-05'))).asDays()

6
```

but

```
moment.duration(moment('3013-11-11').diff(moment('3013-11-05'))).asDays()

6.041666666666667
```

**Desktop (please complete the following information):**
 - OS: Mac 10.14
 - Browser chrome
 - Version 74

**Moment-specific environment**

* US East coast
* Right now

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
```
Mon Jul 15 2019 18:55:16 GMT-0400 (Eastern Daylight Time)
7/15/2019, 6:55:16 PM
240
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
2.24.0
```

**Comment by ashsearle** [comment]
0.041666666666667 is basically 1/24th, i.e. 1 hour.

I think this issue is a common one: you've taken the diff between two dates crossing a (predicted) DST change.

**Comment by omarmeky** [comment]
That might be an issue but shouldn't both prompts result in the same output since the months/days are the same?

**Comment by omarmeky** [comment]
I guess if daylight saving dates change between years 🤔

**Comment by kylekatarnls** [comment]
Yes, DST are often between Saturday and Sunday (so not the same day number) and Europe does not change the same time as the USA, and DST can be added/removed by governments. Morocco stopped observing the DST changes in 2018 for example, and Europe countries should stop soon.

Handling dates in 3013 in given timezone is completely unreliable. Such date would make sense only in UTC or fixed timezone (+X hours) but not in US East coast timezone.

**Comment by omarmeky** [comment]
Ok, I still think the `diff` behavior is non-intuitive but that seems like a different issue.
