### ISSUE TITLE
moment.js is behind by 20 seconds right now (2019-07-17T20:28:15.000Z)

### ISSUE THREAD

**Issue by MengRS** [moment/moment#5168]
**Describe the bug**
when I compare the time displayed on https://momentjs.com/ and the time displayed on https://www.time.gov/ (and many other resources).  The time displayed on moment.js is behind by 20 seconds.

**To Reproduce**
1. Go to https://momentjs.com/
2. Go to https://www.time.gov/ 

**Expected behavior**
Time indicated on both websites should be the same in seconds.

**Screenshots**
![Time_Comparisons](https://user-images.githubusercontent.com/7980628/61409343-e4e0a880-a896-11e9-9a8d-b14152ad1c0c.gif)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by MengRS** [comment]
This issue is now fixed (momentjs.com and time.gov now display the same time), but would be curious to see what happened.

**Comment by kylekatarnls** [comment]
momentjs does not give you any server-side time, it uses the date-time of your operating system (via your browser). If you change your date/time/timezone setting on your computer, momentjs.com will instantly show the updated date.

**Comment by MengRS** [comment]
Thank you @kylekatarnls! I just figured that out too.
