### ISSUE TITLE
Wrong string output when using relativeTimeThreshold

### ISSUE THREAD

**Issue by schnetzi** [moment/moment#5170]
**Describe the bug**
When I set the following setting: `moment.relativeTimeThreshold('ss', 0);` and have a duration result of one second it prints out `1 seconds` instead of `1 second`.

**To Reproduce**
https://codepen.io/schnetzi/pen/EqaMrZ?editors=1010

**Expected behavior**
I would expect to get "1 second".

**Screenshots**
Please have a look at the codepen.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser Chrome
 - Version 75

**Moment-specific environment**

* The time zone setting of the machine the code is running on: UTC +1
* The time and date at which the code was run: 20:25 at 19.07.2019

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
"Fri Jul 19 2019 20:29:37 GMT+0100 (Western European Summer Time)"
console.log((new Date()).toLocaleString())
"19/07/2019, 20:30:35"
console.log((new Date()).getTimezoneOffset())
-60
console.log(navigator.userAgent)
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
console.log(moment.version)
"2.24.0"
```

**More information**
Maybe related to that ticket: https://github.com/moment/moment/issues/4757

**Comment by marwahaha** [comment]
All the locales say "seconds" in plural form. I don't think we'd try to figure out when to use singular or plural format.

for example: https://github.com/moment/moment/blob/develop/src/locale/en-au.js#L37
```
            ss: '%d seconds',
````

Will be a huge effort to implement a solution.
