### ISSUE TITLE
moment.js week format will return wrong value when cross year 

### ISSUE THREAD

**Issue by lv-conner** [moment/moment#5175]
**Describe the bug**
moment("2018-12-31").format("YYYY-wo") will return 2018-01周，that was wrong;it should return 
2019-01周 or 2018-52周。

**Comment by ashsearle** [comment]
@lv-conner If you're using `w`, `wo` or `ww` for week of year, you should pair it with `gg` or `gggg` for the matching 'week year'.

**Comment by lv-conner** [comment]
> @lv-conner If you're using `w`, `wo` or `ww` for week of year, you should pair it with `gg` or `gggg` for the matching 'week year'.

thank you！
