### ISSUE TITLE
moment__WEBPACK_IMPORTED_MODULE_2___default.a.minute is not a function

### ISSUE THREAD

**Issue by jimmy-e** [moment/moment#5176]
**Describe the bug**
I get an error when trying to use the minute set function `moment().minute(3)`.

`moment__WEBPACK_IMPORTED_MODULE_2___default.a.minute is not a function`

**To Reproduce**
1. Clone [this repo](https://github.com/jimmy-e/moment_issue)
2. Run `yarn`.
3. Run `yarn build:dev`.
4. Run `yarn start`.
5. Go to localhost:8080
6. Go to the browser console for the error message.

**Expected behavior**
No error appears.

**Code**
index.jsx:
```
import 'babel-polyfill';
import React from 'react';
import moment from 'moment';
import { render } from 'react-dom';

const Spa = () => {
  /* eslint-disable */
  console.log((new Date()).toString())
  console.log((new Date()).toLocaleString())
  console.log((new Date()).getTimezoneOffset())
  console.log(navigator.userAgent)
  console.log(moment.version)
  moment.minute(3); // error occurs for this line
  return <h1>Setting Minute</h1>;
};

render(<Spa />, document.getElementById('app'));
```

**Screenshots**
[Screenshot](https://imgur.com/a/YlpR4RY)

**Comment by ashsearle** [comment]
What exactly are you trying to do?

Normal usage would be to create an _instance_ of moment first, then call `minute` on that:
```js
console.log(moment().minute(3).format());
```

**Comment by shipMatserJack** [comment]
i love u
