### ISSUE TITLE
function format('YYYY-MM-DDThh:mm') alters date data

### ISSUE THREAD

**Issue by markdid** [moment/moment#5177]
**Describe the bug**
When formatting a date in 'YYYY-MM-DDThh:mm' format (the format needed to display in a "datetime-local" form input) the data is altered in a very strange way.

Each time I submit the data being reformatted in that way it subtracts 6 hours.

ex: ```2019-08-07T12:12:00.000Z -> 2019-08-07T06:12```

if the time is PM, it alternates between these two times.
However if the original time is AM, it subtracts 6 hours, but instead of alternating between the same date at different times, it alternates between those two times, and moves backwards in days as well.

ex: ```2019-08-07T08:12:00.000Z -> 2019-08-07T02:12 -> 2019-08-06T08:12-> 2019-08-06T02:12```

**To Reproduce**
format a date in this way: ```let myDate = moment(newDate, 'YYYY-MM-DDTHH:mm:ss.sssZ').format('YYYY-MM-DDThh:mm');```

i'm using moment.js (v2.24.0 latest)

**Expected behavior**
Date should be formatted correctly
ex: ```2019-08-05T02:12:00.000Z -> 2019-08-05T02:12```

**Moment-specific environment**
UTC-07:00 Mountain Time
React (v16.8.6)

Please run the following code in your environment and include the output:
```
Thu Jul 25 2019 16:47:28 GMT-0600 (Mountain Daylight Time)
7/25/2019, 4:47:28 PM
Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Mobile Safari/537.36
2.24.0
```

**Comment by ashsearle** [comment]
@markdid The code you ran from the bug report template shows that you're running timezone is UTC-06:00, not UTC-07:00 (`GMT` is synonymous with `UTC`):
```js
console.log((new Date()).toString())
// Thu Jul 25 2019 16:47:28 GMT-0600 (Mountain Daylight Time)
```

The `Z` in `2019-08-07T12:12:00.000Z` indicates `UTC-00:00`, which is 6 hours different to your local timezone.

If you want to format the date in the UTC timezone, you need to do that explicitly - e.g. using `utc()` before `format`.  Compare your output of:
```js
console.log(moment().format('YYYY-MM-DDThh:mm'));
console.log(moment().utc().format('YYYY-MM-DDThh:mm'));
```

**Comment by markdid** [comment]
@ashsearle Thanks for the reply! Hmm, interesting. I'm running this project on docker, maybe that's why the timezone is different from windows?
Anyway's, I didn't know there is a difference in timezones, but I don't really care which timezone it is as long as the time set stays the same. Adding ```.utc()``` does output the correct time, the same time displayed on windows but now the time stays the same if it is AM, but if the time is PM, it changes it to AM (4:00PM -> 4:00AM)

Checking the data my backend receives confirms it's sending it correctly  (2019-08-05T016:00) and sends it back to the front end correctly as well (2019-08-05T16:00:00.000Z) but then moment re-formats that to 2019-08-05T04:20. Any ideas? Am I missing something?

**Comment by ashsearle** [comment]
Sure: use `HH` (00-23) instead of `hh` (1-12)

**Comment by markdid** [comment]
Oh thank goodness thank you so much all is well
