### ISSUE TITLE
toString() returning GMT+0 and GMT-0 on different systems

### ISSUE THREAD

**Issue by mteitelbaum** [moment/moment#5179]
As explained in https://github.com/moment/moment/issues/1018, `toString()` is intended to produce consistent results regardless of the user's environment.  However, it is currently defined as follows:

```
function toString () {
    return this.clone().locale('en').format('ddd MMM DD YYYY HH:mm:ss [GMT]ZZ');
}
```

This implementation results in subtly different outputs on different systems (+0 vs -0), presumably due to different definitions of the 'en' locale:

```
    -         ng-reflect-date="Mon Jul 22 2019 00:00:00 GMT-0"
    +         ng-reflect-date="Mon Jul 22 2019 00:00:00 GMT+0"
```

I was able to workaround the issue with a variant of what was suggested [here](https://github.com/moment/moment/issues/1018#issuecomment-24568040), redefining the moment.toString as follows for the affected tests:

```
  moment.fn.toString = function toString() {
      return this.format('ddd MMM DD YYYY HH:mm:ss [GMT]');
    };
```

But it seems to me that a better fix would be for toString to not rely on the system locale definition for 'en', for the same reason it does not rely on the system timezone setting.

**Comment by ashsearle** [comment]
Can you provide some more context about what version and plugins you're using?

The `ZZ` formatting token should always produce a 4-digit string (e.g. `0000`), so I suspect it's not the core moment library causing the strange offset output (`+0` / `-0` instead of `+0000`)

**Comment by mteitelbaum** [comment]
Thanks, I've figured it out: `.toString()` was _correctly_ outputting `-0400` and `+0400` respectively but the string was truncated by angular's ng-reflect at an awkward point.  Became clear once I wrote tests using timezones that cross the date line.  

Apologies for the bother and thanks for looking!
