### ISSUE TITLE
Locale- Swahili Translation not proper

### ISSUE THREAD

**Issue by KhadijaMahanga** [moment/moment#5182]
**Describe the bug**
Swahili locale relative translation and formatting is not correct

**Expected behavior**
The statement `7 days ago` should be translated in swahili as `siku 7 zilizopita` and not `tokea masiku 7`
Also 3 hours ago should be `Dakika 3 zilizopita`

**Comment by marwahaha** [comment]
@fadsel thoughts?

**Comment by fadsel** [comment]
I 've just saw this , even though the meanings are the same but it is a better translation , let me pull fix it

**Comment by fadsel** [comment]
https://github.com/moment/moment/pull/5544

**Comment by fadsel** [comment]
Closed that in favor of this one https://github.com/moment/moment/pull/5545
