### ISSUE TITLE
Abbreviation formatting for large numbers (example: 5K, 10M, etc.) across locales

### ISSUE THREAD

**Issue by naeohmi** [moment/moment#5186]
**Is your feature request related to a problem? Please describe.**
Problem: I have an i18n app with l10n formatted numbers and strings with a graph containing large numbers that I want to shorten to display in the tooltip like this: 5M (for 5 million), 10K (for 10 thousand), etc. But I don't want to hard code the 'K', 'M', 'B' because I want to provide translated strings based on locale. 

**Describe the solution you'd like**
I would love a moment.js function where I can pass the large number integer to format as an argument with the user locale and returned a correctly abbreviated number string.

**Describe alternatives you've considered**
This vanilla js solution from [stackoverflow](https://stackoverflow.com/questions/9461621/format-a-number-as-2-5k-if-a-thousand-or-more-otherwise-900) is similar, but does not include i18n / locale support.

```
function kFormatter(num) {
    return Math.abs(num) > 999 ? Math.sign(num)*((Math.abs(num)/1000).toFixed(1)) + 'k' : Math.sign(num)*Math.abs(num)
}
 ```

Thanks!

**Comment by ashsearle** [comment]
`moment` is a library for parsing, manipulating and formatting dates, times and durations; it's not a generic i18n library.

Is this feature relevant to date / time / duration formatting?

**Comment by ashsearle** [comment]
@naeohmi Take a look at [cldr-compact-number](https://github.com/snewcomer/cldr-compact-number), which looks like it matches the bleeding-edge proposal for [`compact` option for `Intl.NumberFormat`](https://v8.dev/features/intl-numberformat#notation)

**Comment by naeohmi** [comment]
Thanks @ashsearle this is exactly what I need, appreciate it! Sorry this feature request wasn't more relevant to date/time/duration formatting - I'll remember for next time 😄
