### ISSUE TITLE
en locale is supposed to be US but startOf week is Monday

### ISSUE THREAD

**Issue by macpham** [moment/moment#5187]
**Describe the bug**
I'm under the impression the default locale `en` is supposed to represent English (United States) since there is no `en-us`. https://github.com/moment/moment/issues/3569#issuecomment-258637893 However when I try to get the start of the week with `en`, I get Monday and in the US and in general North America the week starts on Sunday. `en-CA`, English (Canada) works as expected.

**To Reproduce**
1. Set locale to `en-us`, it goes to `en`
2. Do `moment.startOf('week')` or check `moment.localeData().firstDayOfWeek()`

**Expected behavior**
1. First day of the week in the US should be Monday or day `0` not `1`.

https://github.com/moment/moment/blob/develop/src/lib/units/week.js#L45

![image](https://user-images.githubusercontent.com/1777724/62498675-fb9b6080-b7ad-11e9-9313-e9e500c2cb7a.png)

I'm using moment 2.24.0.

Is this a bug or is my understanding bugged?

As a workaround, I am doing: `moment.updateLocale('en', { week: { dow: 0 } });`

**Comment by ashsearle** [comment]
Are you using an environment or plugin that changes moment locale / locale-data?

Things like fine in a plain [jsfiddle](https://jsfiddle.net/voxfqdzr/)

**Comment by macpham** [comment]
Thanks @ashsearle for checking. I was looking for any other reference to `updateLocale` and I couldn't find anything. Is there another way to update locale / locale data other than that function that I am using to fix this?

This is on MacOS with Chrome Incognito, others working with me experience the same thing so it must be something in our app then.

**Comment by ashsearle** [comment]
If some other code is using `updateLocale` you might be able to see evidence of that by checking `moment.localeData().parentLocale` - it'd normally be `undefined` for the default `'en'` locale.

It's also possible something's directly manipulating the object returned by `localeData()` - that'll be harder to detect (but guess checking your entire app for 'localeData' should narrow down the search.)

**Comment by macpham** [comment]
Very odd, I have no modification to `parentLocale`, its `undefined` and I searched for references to `localeData` in my source code and found none other than the ones to generate this print out below... Perhaps one of my dependencies is doing something to it? There is no other way to influence this value?

![image](https://user-images.githubusercontent.com/1777724/62798000-369ddc80-baab-11e9-902e-a5f67384878d.png)

**Comment by ashsearle** [comment]
i don't _think_ there's any other way to influence this, so I'd definitely search your `node_modules` / dependencies and check if something jumps out.

**Comment by harkue** [comment]
It looks fine for me also. Am I missing something?
```js
const moment = require("moment");
moment.locale("en-ca");
console.log(moment.localeData().firstDayOfWeek()); // 0
```

**Comment by macpham** [comment]
Yes, I found the root cause. It was my app setting the locale again. Thanks guys.
