### ISSUE TITLE
`CHANGELOG.md` Links Broken

### ISSUE THREAD

**Issue by sk364** [moment/moment#5188]
**Describe the bug**
`CHANGELOG.md`: `See Changelog`/`See Full Changelog` links result in `Page Not Found` for all versions >= `2.19.3`

**To Reproduce**
1. Go to [Changelog v2.19.4](https://gist.github.com/marwahaha/d3b7b0ddf4bdae512244f16e8cc59efb).

**Expected behavior**
Should show the changelog of a version.

**Comment by ashsearle** [comment]
Looks like full changelogs are published under a maintainer's own github account (@marwahaha), and their account has (hopefully temporarily) been disabled.

**Comment by sk364** [comment]
Will you then be creating the new links for it or wait for @marwahaha's account to be enabled again?

**Comment by ashsearle** [comment]
@ichernev / @timrwood How is a 'full changelog' created?  Is this information lost forever if a maintainer's account gets shut down?

**Comment by marwahaha** [comment]
I think I've been re-enabled, sorry for the confusion!

@ashsearle the Moment release process is here:
https://gist.github.com/marwahaha/44deb629e81fbf02c599074ffc8a9c46

You can run this locally to get a changelog between two moment versions:
https://gist.githubusercontent.com/marwahaha/deb752493230f4785d32562d7aed8493/raw/
