### ISSUE TITLE
Moment parsing local date as UTC

### ISSUE THREAD

**Issue by dhaliman** [moment/moment#5189]
**Describe the bug**
moment constructor for parsing local date time is parsing date string as utc. I know this because the moment object has _isUTC field set to true.

**To Reproduce**
1. Let the date string be `2019-12-31 23:59`
2. Parse the date using `moment('2019-12-31 23:59', 'YYYY-MM-DD')`
3. Get the js Date object from the above constructor `moment('2019-12-31 23:59', 'YYYY-MM-DD').toDate()`
4. The returned Date Object is `Sun Dec 01 2019 05:30:00 GMT+0530 (India Standard Time)` in my localtime. 

**Expected behavior**
The expected Date Object should have been `Sun Dec 01 2019 00:00:00 GMT+0530 (India Standard Time)` 

**Screenshots**
Not sure if I have relevant screenshots for this.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 2.24.0

**Moment-specific environment**

* The time zone setting of the machine the code is running on - IST
* The time and date at which the code was run - described above
* Other libraries in use - React, Redux 

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
Wed Aug 07 2019 11:14:50 GMT+0530 (India Standard Time)
console.log((new Date()).toLocaleString())
07/08/2019, 11:14:50
console.log((new Date()).getTimezoneOffset())
-330
console.log(navigator.userAgent)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
console.log(moment.version)
2.24.0
```

**Additional context**

**Comment by ashsearle** [comment]
This doesn't sound right.  You're parsing a string representing the 31st December, but expect it to be the 1st December?

**Comment by harkue** [comment]
It seems need more information about the actual result.

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.
