### ISSUE TITLE
Adding 1 week to last week of 2019 reverts to first week of 2019

### ISSUE THREAD

**Issue by benjaminprojas** [moment/moment#5197]
**Describe the bug**
As the title mentions, when you add a week to the last week of 2019, the expected output would be the first week of 2020, but instead its the first week of 2019:
```js
moment('201952', 'YYYYWW').add(1, 'week').format('YYYYWW'); // 201901
```

However if you add two weeks, the output is correct in selecting the second week of 2020:
```js
moment('201952', 'YYYYWW').add(2, 'week').format('YYYYWW'); // 202002
```

**To Reproduce**
1. See above.

**Expected behavior**
The output should be `202001` and `202002` not `201901` and `202002`.

**Desktop (please complete the following information):**
 - OS: Windows 10 - WSL Ubuntu
 - Browser: node
 - Version:

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()) Wed Aug 14 2019 13:36:50 GMT-0400 (Eastern Daylight Time)
console.log((new Date()).toLocaleString()) 8/14/2019, 1:36:50 PM
console.log((new Date()).getTimezoneOffset()) 240
console.log(navigator.userAgent)
console.log(moment.version) 2.24.0
```

**Comment by ashsearle** [comment]
This needs to be in a FAQ:
Use `GGGG` with `WW`, not `YYYY`.

**Comment by benjaminprojas** [comment]
@ashsearle thanks for pointing that out, I had completely missed that in the docs. Sure enough it fixed the problem:
```
moment('201952', 'GGGGWW').add(1, 'week').format('GGGGWW'); // 202001
moment('201952', 'YYYYWW').add(1, 'week').format('GGGGWW'); // 202001
```
