### ISSUE TITLE
Incorrect TS type for toDate()

### ISSUE THREAD

**Issue by dlaub3** [moment/moment#5198]
The TS type for `moment().toDate()` is `Date`, but it's actually a `string`.

**To Reproduce**
- This is a demo of the bug: https://codesandbox.io/s/cocky-merkle-c0gz8?fontsize=14

**Expected behavior**
- I expect the type to show a `string` instead of a `Date` or to get a `Date` instead of a `string`. 

**Desktop:**
 - OS: MAC 10.14.6
 - Browser FireFox 69 and Chrome  76

**Moment-specific environment**
- Moment 2.24.0
```
8/15/2019, 3:20:01 PM 
240
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0 
2.24.0 
```

**Comment by ashsearle** [comment]
The TS type is correct, it's a `Date`:
https://codesandbox.io/s/patient-mountain-dcevx

(You misinterpreted the output of `console.log(date)`, which calls `toString()` on the `Date`)

**Comment by dlaub3** [comment]
You are right @ashsearle . I'm able to call normal `Date` functions on the object. Where did you get the info on `console.log` calling `toString`? I didn't know it could behave that way.

**Comment by ashsearle** [comment]
@dlaub3 My comment on `toString()` was probably a bit misleading:  I meant it as an observation, not referring to any specification.

FWIW: As the string output of `console.log` can be misleading, you might find it useful to check output of `console.dir(thing)`, `console.log(thing.constructor)` and/or `console.log(Object.getPrototypeOf(thing)))` in future.

(side-note: codesandbox doesn't appear to support `console.dir` at the moment, but the output would be visible in the browser's built-in developer tools.)
