### ISSUE TITLE
Invalid weeks returned for the pattern YYYY[W]WW

### ISSUE THREAD

**Issue by ser-shant** [moment/moment#5199]
**Describe the bug**
Every time I try to get a week of the patter "YYYY[W]WW" for the year > 2020 (2021, 2022 ...) I am getting the week increased by one
moment("2022W03", "YYYY[W]WW").week()
result : 04

**To Reproduce**
1. Go to 'moment("2022W03", "YYYY[W]WW").week()'
2. returned "4"
3. Expected result : "3"

**Expected behavior**
Action: _console.log("end of 03 week: " +moment("2022W03", "YYYY[W]WW").week());_
Result: **end of 03 week: 4**
Expected: _end of 03 week: **3**_

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6

**Smartphone (please complete the following information):**
 - Browser Chrome/76.0.3809.100
 - Version /76.0.3809.100

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
Fri Aug 16 2019 12:17:07 GMT+0300 (Moscow Standard Time)
quickorder.js:47 8/16/2019, 12:17:07 PM
quickorder.js:48 -180
quickorder.js:49 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
quickorder.js:50 2.24.0

**Additional context**
Reproducible for all years after 2020

**Comment by ashsearle** [comment]
Use `GGGG` with `WW`
