### ISSUE TITLE
Is it possible to rename locale tg to tj?

### ISSUE THREAD

**Issue by Farkhod** [moment/moment#5200]
Hello

As I know the locale tg refers to the country of Tajikistan which has a code tj
Or is possible to use aliases to tg?

**Comment by ashsearle** [comment]
Technically, you can create aliases like this:
```js
moment.defineLocale('tj', { parentLocale: 'tg' })
```

But... probably better to understand that `moment`s locales are based on [ISO language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), _not_ [country codes](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes).

**Comment by Farkhod** [comment]
> Technically, you can create aliases like this:
> 
> ```js
> moment.defineLocale('tj', { parentLocale: 'tg' })
> ```
> 
> But... probably better to understand that `moment`s locales are based on [ISO language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), _not_ [country codes](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes).

Thank you for your reply.
