### ISSUE TITLE
fr.js French not consistent in monthShort?

### ISSUE THREAD

**Issue by azn1viet** [moment/moment#5201]
monthsShort : 'janv._févr._mars_avr._mai_juin_juil._août_sept._oct._nov._déc.'.split('_'),

so,

 Jan is **janv.** (with dot)

but 

Mar is **mars** (without the dot)

and so on...

**Comment by kylekatarnls** [comment]
Perfectly logical. In French, abbreviated words **MUST** have a dot. But March = mars 4 letters only. No dot because the word is not abbreviated.

mars, mai, juin and août are the complete words (4 letters or less) so no dot.

**Comment by azn1viet** [comment]
But why juli. and sept. got total 5 letters (with dot)?

**Comment by kylekatarnls** [comment]
Then, honestly `janv.` could be `jan.` and `févr.` could be `fév.` it would be clear enough.
But `juil.` cannot be `jui.` else you would think "juin" (June).
Then cutting after a vowel would be unusual so no `avri.`, `octo.`, `nove.`, `déce.`, clear not.

When it comes to languages syllables and common usages are more important than consistency.

And as a French, those short forms are pretty fine to me.

**Comment by azn1viet** [comment]
"juil." and "sept." don't end with vowel nor conflicted with any others. It should be just "juil" and "sept", no?

I'd suggest if 4 letters, then should be "juil" "juin" "sept" and "avri" "octo",... Not some with and some without a dot; some 4, some 5 letters which looked odd to me. When it comes to abreviations, it should be consistent no matter of vowels or consonants.

**Comment by kylekatarnls** [comment]
No, it should be understood first by the speakers of the language.

Then I already explained when dot is needed: it replaces the missing part of the word. If the word is complete, you must not add a dot (mars, mai, juin, août). If you removed letter you must add a dot (janvier, février, avril, juillet, septembre, octobre, novembre, décembre). That's a rule. If you put a dot on all or on none, no matter the length you choose, it will be incorrect.

Secondly, why abbreviated months should all be the same length of letters  (what about Japan, Chinese, Arabic)? The purpose of short form is just to be shorter. And unless you use monospace letters have different sizes so what would be the point of length consistency?
