### ISSUE TITLE
TypeScript definitions for dynamic locale module imports

### ISSUE THREAD

**Issue by ulrichb** [moment/moment#5202]
**Is your feature request related to a problem? Please describe.**

Atm. when importing a locale modules _via ES6 dynamic import_, you get the following TypeScript error.

```TS
async function lazyLoadSomeLocale(): Promise<void> {

  await import("moment/locale/de");
  // => ERROR: "Could not find a declaration file for module 'moment/locale/de'"
}
```

(Note the a "normal" import statement via `import "moment/locale/de";` with enabled `--allowJs` works.)

**Describe the solution you'd like**

Add (empty) declarations for all the locale modules.

For example the following will do the job.

`locale/de.d.ts`:
```TS
export = undefined;
```

**Describe alternatives you've considered**

_Workaround:_ Add a `declare module "moment/locale/de" { }` in the consuming project.

**Comment by marwahaha** [comment]
I'm glad you have a workaround.
If you would like, you can make a PR to our docs at https://github.com/moment/momentjs.com/

I don't think we will change anything TypeScript related now, as we still support TS 1.x..
