### ISSUE TITLE
Moment IsValid() return true when date is invalid

### ISSUE THREAD

**Issue by PaneroEduardo** [moment/moment#5205]
Calling the function isValid like thath moment(date, 'MM/DD/YYYY').isValid() and passing a date like 08/10/20193423 return that the date is valid.

1. Create a moment with date "08/10/20193423" and format "MM/DD/YYYY"
2. Check if moment is valid
3. See fail

**Expected behavior**
Return that the date is invalid

**Actual behavior**
Return that the date valid

**Comment by tiagostutz** [comment]
Hi!
Just added this scenario to the `string nonsensical with format` locally to test within the `is_valid`  context and indeed it is buggy as you reported. 

I'm taking a look at the `isValid()` function to be sure that this is actually a bug and how can it be fixed so I can start working on this.

**Comment by ashsearle** [comment]
Use [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/)

```js
const date = '08/10/20193423';
moment(date, 'MM/DD/YYYY').isValid(); // lenient parsing (default) returns true
moment(date, 'MM/DD/YYYY', true).isValid(); // strict parsing returns false
```
