### ISSUE TITLE
Inconsistent Constructor Behaviour

### ISSUE THREAD

**Issue by NathanCanine** [moment/moment#5213]
```
let m = require("moment");  
const fmt = (x)=>{  
    console.log(`${x.format()}`)  
}  
x = m();  
y = m(undefined);  
z = m(null);  
fmt(x);  
fmt(y);  
fmt(z);  
```
Should be checked by testing the truthiness of the first element of arguments[] in the constructor and the length of arguments.

**Comment by marwahaha** [comment]
Thanks for opening this request.
Not passing arguments is the same as passing undefined.
