### ISSUE TITLE
Crash (only on release build) when locale is not available

### ISSUE THREAD

**Issue by davicorreiajr** [moment/moment#5214]
**Describe the bug**
Moment docs say `You may also specify a list of locales, and Moment will use the first one it has localizations for.`. I'm using moment on a react-native app, and only on release build, if I do:
```
moment.locale(['fr', 'en'])
```
I get an error `Requiring unknown module "./locale/fr".`. So the questions are:
1) Why does it happen only on release build?;
2) Since there is not `fr` (and indeed there is not), shouldn't moment fall back to `en`?

**To Reproduce**
Set moment locale like that `moment.locale(['fr', 'en'])` (or any other language than `fr`) and run the app with release configuration.

**Expected behavior**
To not crash and fall back to `en`.

**Smartphone (please complete the following information):**
 - Device: ios simulator
 - OS: ios

**Comment by vdmtrv** [comment]
This is also happening on an Android TV device with a release version of the app.

**Comment by fbartho** [comment]
@davicorreiajr / @vdmtrv: is #5252 the same issue you two are seeing?

**Comment by vdmtrv** [comment]
@fbartho yes. I'm seeing it on a real Android TV device and not a simulator as you have suggested in your issue description.

**Comment by davicorreiajr** [comment]
@fbartho yes, kind of. The main thing for me is that moment does not fall back to the available locale.

**Comment by fbartho** [comment]
@davicorreiajr -- Ah! I see, it throws an exception instead of continuing on to the next option that you suggested. That makes sense.

**Comment by marwahaha** [comment]
Looks like #5252 was closed.
Please re-open if you still have issues.

**Comment by clems36** [comment]
Hi, sorry to comment on a closed issue but i'm still experiencing the `Requiring unknown module "./locale/fr".` error.
Basically what i'm trying to do is the same. I'm calling `moment.locale('fr')` inside of a redux action. I've added the following imports at the top of my file:
```
import moment from 'moment';
import 'moment/locale/fr';
```
This is happening to me in a react-native project, **only in production**. 
My moment version is the latest - `^2.27.0` - and my react-native version is `https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz` (it's an expo project) which corresponds to `0.62.2`.

Thanks in advance for any help provided!

**Comment by Dat-Mobile** [comment]
only work if I revert to `"moment": "2.18.1"`
