### ISSUE TITLE
Bug: Getting "Invalid Date" for a valid date

### ISSUE THREAD

**Issue by TareqMahbub** [moment/moment#5222]
moment('31-05-1985', 'DD-MM-YYYY')
moment([1985, 5, 31])
First one gives a valid date but second one gives a overflow for 'days'.

**Comment by ashsearle** [comment]
First one is creating a date for May, second one is creating a date for June.

**Comment by TareqMahbub** [comment]
Thank you. 
Really appreciate your help.
Got it.
