### ISSUE TITLE
Polish weekdays should be capitalized 

### ISSUE THREAD

**Issue by alexandraseri** [moment/moment#5230]
When calling for moment.weekdays(), the array of full weekdays names should all be capitalized.

Steps to reproduce:
1. Update local of moment to be Polish - moment.locale('pl')
2. call for moment.weekdays()

Actual behavior: 
returns the following
`["niedziela", "poniedziałek", "wtorek", "środa", "czwartek", "piątek", "sobota"]`

Expected behavior:
returns the following
`["Niedziela", "Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota"]`

Screenshots:
![image](https://user-images.githubusercontent.com/52129638/64967367-0a932980-d8a9-11e9-88fb-5ad55c4e7fe4.png)

Desktop
 - macOS 10.14.6
 - chrome
 - 77.0.3865.75 

Please run the following code in your environment and include the output:
```
Mon Sep 16 2019 17:42:20 GMT+0300 (Israel Daylight Time)
9/16/2019, 5:42:20 PM
-180
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36
2.24.0
```

**Comment by kylekatarnls** [comment]
Months and weekdays should be capitalized only if its an absolute rule in the given language (for English, it's always capitalized even in the middle on a sentence, or German where any noun is capitalized), but as it seems, such rule does not exist in Polish:
https://translate.google.com/#view=home&op=translate&sl=en&tl=pl&text=Monday
So it should rather be like it is now (same as in French, Italian, Spannish, etc.)

**Comment by alexandraseri** [comment]
@kylekatarnls Ok, what about a new feature? Maybe moment.weekdaysCapitalized() will return capitalized weekdays?

**Comment by kylekatarnls** [comment]
We discussed that on other issues, and my position (I'm not a member of moment.js team) is capitalizing words is not the responsibility of a date library. It could be a  I18N tool or a simple string util:

```js
function capitalize(word) {
  return word.substr(0, 1).toUpperCase() + word.substr(1);
}
```

**Comment by quetzalcoatl** [comment]
I absolutely agree. As a native Polish-speaker, I can assure you that there is capitalization rule for weekdays. As a matter of fact, a weekday name is a normal noun, and the general rule is to NOT capitalize normal nouns (unlike for example in German). Only some special kinds of nouns are, for example: proper names (John, Wojtek, Europa).
