### ISSUE TITLE
Safari String Parse Bug on YYYY-M-D

### ISSUE THREAD

**Issue by mvng** [moment/moment#5232]
**Describe the bug**

**To Reproduce**
1. moment.js -> console
2. moment('2014-1-1').isValid() returns false on safari but true in chrome
3. moment('2014-01-01').isValid() returns true for both scenarios

**Expected behavior**
should return true for both cases

**Screenshots**
(Left is Safari, Right is Chrome)
![image](https://user-images.githubusercontent.com/7838263/64999692-97d08100-d89d-11e9-801d-70742e9d8885.png)

**Desktop (please complete the following information):**
 - OS: OSX/iOS/iPadOS
 - Browser Chrome/Safari
 - Version 2.24

**Smartphone (please complete the following information):**
 - Device: macbook pro, iphone, ipad pro
 - OS: IOS13
 - Browser stock browser, safari
 - Version ios13

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
> new Date().toString();

< "Mon Sep 16 2019 16:21:57 GMT-0700 (PDT)"
> new Date().toLocaleString();

< "9/16/2019, 4:22:00 PM"
> new Date().getTimezoneOffset();

< 420
> navigator.userAgent;

< "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15"
> moment.version;

< "2.24.0"
```

**Additional context**
is this intended behavior?

**Comment by peterb0yd** [comment]
+1 - this is causing "invalid date" all over my web app on iOS devices!

**Comment by ashsearle** [comment]
@mvng You should have seen a wordy deprecation message in the console.  See issue #1407.

If you know the date format is going to be `'YYYY-M-D'`: pass it explicitly (and use strict parsing):

```js
moment('2014-1-1', 'YYYY-M-D', true).isValid(); // true in all browsers
```

**Comment by mvng** [comment]
@ashsearle so the solution here is to pad the input to always be 2 digits? we dont know if the date format is going to be YYYY-M-D or YYYY-MM-DD 

- my current fix it to split and rebuild the moment date object via moment({year,month,day})

**Comment by ashsearle** [comment]
@mvng If you know the input is going to match a limited set of formats, you can use the [string + formats](https://momentjs.com/docs/#/parsing/string-formats/) call to try both/all possibilities:

```js
moment('2014-1-1', ['YYYY-M-D', 'YYYY-MM-DD'], true).isValid(); 
```
