### ISSUE TITLE
Invalid parsing of ISO8601 strings, but only in some range of years

### ISSUE THREAD

**Issue by quetzalcoatl** [moment/moment#5236]
**Describe the bug**
For some specific year ranges ISO8601 time is offsetted by -6 minutes.

I discovered this behavior when our system was parsing ISO8601-formatted timestamps and presented them on a calendar. Before that, timestamps are 'normalized' to viewer's local timezone offset. We ensure that input data is already in viewer's timezone offset, so the 'normalization' step is actually superfluous, but it is there, and since input/output offsets are the same, it should not damage the data.

However after parsing it via Moment object, resulting value indicated 1 day before than it should.

``` const input = "1915-08-05T00:00:00+02:00";
const m = moment(input, moment.ISO_8601);
console.log(m.format())
-> "1915-08-04T23:24:00+01:30" // why offset changed? why extra -6 minutes?
```

This 'm' value was then passed around, and later displayed. Since it contained a different offset than local, another component re-normalized it back to local +02:00 and that resulted in `1915-08-04T23:54:00+02:00`. This caused a calendar component to display "1915-08-04" instead "1915-08-05" as the date.

The problem does not lie in the fact that timezone offset was changed back and forth, but in the extra change of -6 minutes.

**To Reproduce**
```
moment("1916-08-05T00:00:00+01:30", moment.ISO_8601).format()
->     "1916-08-05T00:30:00+02:00"
// CORRECT: offset is shifted by 30mins, so is the time -- it's the same absolute point in time

moment("1915-08-05T00:00:00+02:00", moment.ISO_8601).format()
->     "1915-08-04T23:24:00+01:30"
// WRONG: -36 mins difference, -30 from timezone offset (ok), extra -6 out of nowhere (?!)

moment("1915-08-05T00:00:00+01:30", moment.ISO_8601).format()
->     "1915-08-04T23:54:00+01:30"
// WRONG: no offset change, but got -6 minutes (?!)

// strangely, when zero or negative offsets are parsed properly:
moment("1915-08-05T00:00:00+00:00", moment.ISO_8601).format()
->     "1915-08-05T01:00:00+01:00"
moment("1915-08-05T00:00:00-01:00", moment.ISO_8601).format()
->     "1915-08-05T02:00:00+01:00"
moment("1915-08-05T00:00:00-10:00", moment.ISO_8601).format()
->     "1915-08-05T11:00:00+01:00"
// CORRECT: all 3 above are correct

// but the same 3 cases as above, when changed to 1914 are parsed incorrectly:
moment("1914-08-05T00:00:00+00:00", moment.ISO_8601).format()
->     "1914-08-05T01:24:00+01:30"
moment("1914-08-05T00:00:00-01:00", moment.ISO_8601).format()
->     "1914-08-05T02:24:00+01:30"
moment("1914-08-05T00:00:00-10:00", moment.ISO_8601).format()
->     "1914-08-05T11:24:00+01:30"
// WRONG: all absolute times moved by -6 minutes

// same goes for any earlier year:
moment("1492-08-05T00:00:00+00:00", moment.ISO_8601).format()
->     "1492-08-05T01:24:00+01:30"
// WRONG: time moved by -6 minutes
```

**Expected behavior**
When I try to parse a full ISO8601 format with timezone offset information into a Moment object, and when I format it back to ISO8601, I expect to get the same effective point in time.

I expect the Moment object to be set to the date, time, and also to the timezone offset exactly as I specified in the ISO8601 string. However, it would be still OK for the timezone offset to be changed during that roundtrip, if only the absolute time point remained the same.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: most-recent 2.24.0, older versions also exhibit that behavior

**Moment-specific environment**

* The time zone setting of the machine the code is running on
(UTC+01:00) Sarajewo, Skopie, Warszawa, Zagrzeb
and I suppose DST is active, so it's +02:00 now.

* The time and date at which the code was run
2019-09-26 17:44

* Other libraries in use (TypeScript, Immutable.js, etc)
none in repro cases above, TypeScript in original production system

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)

"Thu Sep 26 2019 17:45:15 GMT+0200 (czas środkowoeuropejski letni)"
"26.09.2019, 17:45:15"
-120
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
"2.24.0"
```

**Comment by ashsearle** [comment]
Is it the parsing that's wrong, or the formatting?

Taking one of your 'WRONG' cases, can you check:
```js
moment("1915-08-05T00:00:00+02:00", moment.ISO_8601).format();
moment("1915-08-05T00:00:00+02:00", moment.ISO_8601).toISOString();
moment("1915-08-05T00:00:00+02:00", moment.ISO_8601).utc().format();
```

**Comment by quetzalcoatl** [comment]
```
moment("1915-08-05T00:00:00+02:00", moment.ISO_8601).format(); //     "1915-08-04T23:24:00+01:30"
// wrong, offsetted by -6mins

moment("1915-08-05T00:00:00+02:00", moment.ISO_8601).toISOString(); // "1915-08-04T22:00:00.000Z"
// ok, same timepoint

moment("1915-08-05T00:00:00+02:00", moment.ISO_8601).utc().format(); //"1915-08-04T22:00:00Z"
// ok, same timepoint
```

I suppose it's the parsing, because back then, I checked it by reading out properties `.date()`, `.minutes()` etc like this:

```
const  m = moment("1915-08-05T00:00:00+02:00", moment.ISO_8601);
m.hour()      // -> 23
m.minute()    // -> 24
```

I just noticed that there's a difference between `format` and `toISOString`:
```
moment("1915-08-05T00:00:00+02:00", moment.ISO_8601).format();           // "1915-08-04T23:24:00+01:30"
moment("1915-08-05T00:00:00+02:00", moment.ISO_8601).toISOString();      // "1915-08-04T22:00:00.000Z"
moment("1915-08-05T00:00:00+02:00", moment.ISO_8601).toISOString(false); // "1915-08-04T22:00:00.000Z"
moment("1915-08-05T00:00:00+02:00", moment.ISO_8601).toISOString(true);  // "1915-08-04T23:30:00.000+01:30"
```

So it seems that toISOString returns expected results, and the problem is with the format(), and properties (m.hour(), m.minute()).

**Comment by quetzalcoatl** [comment]
That made me think about one more thing:
```
const m = moment("1915-08-05T00:00:00+02:00", moment.ISO_8601)
console.log(m.format()); // "1915-08-04T23:24:00+01:30"
console.log(m._d); // "Wed Aug 04 1915 23:24:00 GMT+0124 (czas środkowoeuropejski letni)"
```

so it turns out that the internal `_d` date object is initialized to that strange "23:24" time, but in fact that date object has a CORRECT timezone! It's set to +01:24, and that makes the "23:24" time actually present the same absolute time as "00:00:00+02:00" that was parsed.

It's the `.format()` method that produced its output incorrectly: it apparently took hour and minutes from the _d, but it took timezone offset "+01:30" from somewhere else. Had it taken timezone offset from the _d object as well, it would emit "1915-08-04T23:24:00+01:24" and that would be "more correct"! Strange timezone offset, but at least that would be the same point in time.

**Comment by ashsearle** [comment]
Assuming your local timezone is Poland: see [polish timezone changes](https://www.timeanddate.com/time/zone/poland/warsaw) and look at the 1900-1924 period.

Your scenario might be fixed by removing some code that rounds timezone offsets to 15 minutes (originally introduced to fix [a firefox issue](https://github.com/moment/moment/pull/1871).)  I'll create a PR for that.

**Comment by quetzalcoatl** [comment]
> see [polish timezone changes](https://www.timeanddate.com/time/zone/poland/warsaw) and look at the 1900-1924 period.

Thanks! That might be a bit silly of me, but after thinking more and more about that +01:24 it occurred to me that these year range (before 1915) is far enough that either timezone wasn't declared yet, or we may have no information on that, or don't even care -- but what should a library do about this? IMHO, use some astronomical timeoffset more-or-less matching the geographical region.. I checked "local mean sidereal time" and it's result varies somewhere between +0120..+0210 depending on which geographical place I pick within our TZ. So, +0124 might even be OK, it lies somewhere on the eastern edges of this TZ. Fun fact, another TZ mystery solved, probably.
