### ISSUE TITLE
Incorrect hour for timezone

### ISSUE THREAD

**Issue by kainisoft** [moment/moment#5238]
**Describe the bug**
Incorrect result for different months.

**To Reproduce**
```
let a = moment.utc('2019-11-06T13:55:00').tz('Europe/Amsterdam').format('D MMMM YYYY, HH:mm');
// 6 november 2019, 14:55 - Incorrect

let b = moment.utc('2019-10-06T13:55:00').tz('Europe/Amsterdam').format('D MMMM YYYY, HH:mm');
// 6 oktober 2019, 15:55 - Correct
```
How you can see the only difference here is number of month: 11 and 10.

**Expected behavior**
Variable `a` should contain correct hour for given time zone (i.e. 15:55).

**Moment-specific environment**

```
console.log((new Date()).toString())
// Wed Oct 02 2019 13:30:25 GMT+0600 (Kyrgyzstan Time)

console.log((new Date()).toLocaleString())
//10/2/2019, 1:32:21 PM

console.log((new Date()).getTimezoneOffset())
// -360

console.log(navigator.userAgent)
// Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

console.log(moment.version)
// "2.24.0"
```

Please, need advice how can i resolve this issue.

**Comment by ashsearle** [comment]
This behaviour looks correct.

Amsterdam is currently 2 hours ahead of UTC, but will only be 1 hour ahead of UTC in November.

https://www.timeanddate.com/time/zone/netherlands/amsterdam

**Comment by kainisoft** [comment]
Thank you!
