### ISSUE TITLE
relativeTimeThreshold type consistency

### ISSUE THREAD

**Issue by Serrulien** [moment/moment#5239]
**Describe the bug**
The typescript definition of `moment.relativeTimeThreshold(unit)` tells us that it can returns `number | boolean`.

From experience it will return `false` when `unit` is not a valid time unit.

When would `moment.relativeTimeThreshold(unit)` returns `true` ?

Is that an undocumented behavior or a faulty type ?

**Moment version : 2.24.0**

**Comment by ArindamHans** [comment]
`moment.relativeTimeThreshold(unit)   \\ getter` will always either return a `number` or `false`.
But `moment.relativeTimeThreshold(unit, limit)   \\ setter` will always return a `true`, if the limit is valid.

The code might make it more clear -

```
function getSetRelativeTimeThreshold (threshold, limit) {
        if (thresholds[threshold] === undefined) {
            return false;
        }
        if (limit === undefined) {
            return thresholds[threshold];
        }
        thresholds[threshold] = limit;
        if (threshold === 's') {
            thresholds.ss = limit - 1;
        }
        return true;
    }
```

**Comment by ArindamHans** [comment]
`moment.relativeTimeThreshold(unit)   \\ getter` will always either return a `number` or `false`.
But `moment.relativeTimeThreshold(unit, limit)   \\ setter` will always return a `true`, if the limit is valid.

The code might make it more clear -
```
function getSetRelativeTimeThreshold (threshold, limit) {
        if (thresholds[threshold] === undefined) {
            return false;
        }
        if (limit === undefined) {
            return thresholds[threshold];
        }
        thresholds[threshold] = limit;
        if (threshold === 's') {
            thresholds.ss = limit - 1;
        }
        return true;
    }
```
