### ISSUE TITLE
Valid input produces invalid Moment objects

### ISSUE THREAD

**Issue by Slapbox** [moment/moment#5241]
**Describe the bug**
Unlike all other tokens in the formatting system, `a` and `A` require a space before them for `moment` to identify the created object as valid, even though it seems valid and functions as intended in every way I've tested.

OR, it might be rather that time tokens MUST be followed by a space and every token causes this. This seems more likely after a bit more testing.

Additionally I suggest that the dash character `-` should not produce invalid dates, the same way `colon`, `period`, and `comma` work.

```js
// Tokens a/A issue
moment(moment().format('h:mm a MMM D YYYY')).isValid() // true
moment(moment().format('h:mma MMM D YYYY')).isValid() // false

// Dash issue (suggested enhancement)
moment(moment().format('h:mm a MMM. D, YYYY')).isValid() // true
moment(moment().format('h:mm a - MMM. D, YYYY')).isValid() // false
```

**To Reproduce**
See above

**Expected behavior**
Moment can correctly identify that it is actually valid.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Electron
 - Version 6

**Moment-specific environment**

* The time zone setting of the machine the code is running on: `UTC-05:00`
* The time and date at which the code was run: `6:14pm October 3rd, 2019`
* Other libraries in use (TypeScript, Immutable.js, etc): `N/A`

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()): `"Thu Oct 03 2019 18:20:49 GMT-0400 (Eastern Daylight Time)"`
console.log((new Date()).toLocaleString()): `"10/3/2019, 6:21:04 PM"`
console.log((new Date()).getTimezoneOffset()): `240`
console.log(navigator.userAgent): `"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Recollectr/6.0.10 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36"`
console.log(moment.version): `"2.24.0"`
```

**Comment by pmoelgaard** [comment]
I have had to switch to another DateTime implementation in the meantime...
Here is a codepen that shows the issue:
https://codepen.io/pmoelgaard/pen/xxxxyBN?editors=1111

**Comment by marwahaha** [comment]
This is not a bug.

Moment parses objects with a default set of formats. This can be changed. Docs https://momentjs.com/docs/#/parsing/string-format/
```
moment().format('h:mma MMM D YYYY')
```
Works just fine.

So does
```
moment(moment().format('h:mma MMM D YYYY'), 'h:mma MMM D YYYY')
```

Perhaps you missed the deprecation warning when Moment is trying to parse things in formats it does not recognize.
