### ISSUE TITLE
[Translation][PL] "W zeszły" means more than 6 days ago

### ISSUE THREAD

**Issue by ampanasiuk** [moment/moment#5242]
This is a translation issue for polish, tested in momentjs with locales 2.24.0.

    console.log(moment(Date.now()).calendar());
    console.log(moment(Date.now()-1000*60*60*24*3).calendar());
    console.log(moment(Date.now()-1000*60*60*24*(7+3)).calendar());

will be, for example

    Dziś o 23:45
    W zeszły wtorek o 23:45
    24.09.2019

Which is wrong, an example of correct values would be

    Dziś o 23:45
    W ostatni wtorek o 23:45
    W zeszły wtorek o 23:45

Note how "w zeszły" together with a week day means between 7 and 13 days ago.

```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

outputs

```
Fri Oct 04 2019 23:49:55 GMT+0900 (KST)
10/4/2019, 11:49:55 PM
-540
Mozilla/5.0 (Linux; Tizen 4.0; SAMSUNG Emulator) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Mobile Safari/537.36
2.24.0
```

**Comment by michal-lubawy** [comment]
Hi. I'm sorry but I either do not understand the issue described by You. Or I think you might be mistaken. 
For me as a native Polish speaker "Ostatni wtorek" and "Zeszły wtorek" are an equivalent meaning the last Tuesday before today. 
both Wikipedia and Encyclopedia PWN are in agreement with me. 
https://pl.wiktionary.org/wiki/zesz%C5%82y
https://sjp.pwn.pl/sjp/zeszly;2545614.html

**Comment by ampanasiuk** [comment]
I've asked a couple people and they seem to agree with you and disagree with me. That's odd, but not unheard of. The term may have come up too few times around me to clear it up for me after I misunderstood it for the first time.
