### ISSUE TITLE
Calling `moment('2020-02-29').year('2020')` (string value) sets the day to 28.

### ISSUE THREAD

**Issue by mindnektar** [moment/moment#5245]
**Describe the bug**
The docs do specify that the `.year()` method signature expects a number value, but as strings are not outright rejected, I thought I'd report this weird little bug.

It seems to happen only with the year 2020 and no other leap years. Starting from a moment object with its date set to 2020-02-29 and then setting the year to '2020' (with a string value) changes the day to 28. If you pass 2020 as a number, the day stays at 29. If you start off with 2012, 2016, 2024 or 2028 and then set the year to the same value, string or number, the day stays at 29. It only happens with the year 2020 using a string value.

**To Reproduce**
https://jsfiddle.net/y2mrbhzn/

**Expected behavior**
The day stays at 29.

**Comment by arswaw** [comment]
Is this similar to my issue here?

https://github.com/moment/moment/issues/5316
