### ISSUE TITLE
Daylight saving time in Brazil 2019

### ISSUE THREAD

**Issue by cassio-nuke** [moment/moment#5246]
Hi,

Our daylight saving time here in Brasil was cancelled by the president, so we'll not have summer time this year. 

**Steps to reproduce the behavior**
```
moment([2019, 10, 12, 10, 0]).tz("America/Sao_Paulo").toDate()
Tue Nov 12 2019 10:00:00 GMT-0200 (Brasilia Summer Time)
```

**Expected behavior**
```
Tue Nov 12 2019 10:00:00 GMT-0300 (Brasilia Standard Time)
```

**Moment-specific environment**

* The time zone setting of the machine the code is running on -03:00
* The time and date at which the code was run

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()) // Tue Oct 08 2019 15:00:46 GMT-0300 (Brasilia Standard Time)
console.log((new Date()).toLocaleString()) // 10/8/2019, 3:00:46 PM
console.log((new Date()).getTimezoneOffset()) // 180
console.log(navigator.userAgent) // Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
console.log(moment.version) // 2.24.0
```

**Additional context**
Source: https://veja.abril.com.br/economia/bolsonaro-assina-decreto-que-acaba-com-o-horario-de-verao/

**Comment by ashsearle** [comment]
As you're using `tz`, this looks like a moment-timezone issue: moment/moment-timezone#785

Please make sure you're using the the latest available moment-timezone version / data.

**Comment by cassio-nuke** [comment]
Hi @ashsearle ,

Thanks for your answer.
I'm using the latest version of moment & moment timezone.
Although my initial test is using moment tz, without it the problem also appear.

Running the following test without tz shows DST also:
```
moment([2019, 10, 12, 10, 0]).toDate()
```

Result: `Tue Nov 12 2019 10:00:00 GMT-0200 (Brasilia Summer Time)`

**Comment by ashsearle** [comment]
Ah... could be a different issue.  Your O/S might have have out of date timezone information.

From your user-agent string:
```
console.log(navigator.userAgent) // Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
```

macOS 10.13.5 was released June 1, 2018.

I think the president [cancelled DST on 25th April 2019](http://www.planalto.gov.br/ccivil_03/_ato2019-2022/2019/decreto/D9772.htm)?

Avoiding moment altogether, what does this show in your console?:
```js
console.log(new Date("2019-11-12T10:00:00.000-0300"))
```

**Comment by cassio-nuke** [comment]
Hi,

I run it on several machines (Windows & MacOS) and all of them show the same result:

`Tue Nov 12 2019 11:00:00 GMT-0200 (Brasilia Summer Time)`

Not sure why it's still out of date

**Comment by rafaelmmathias** [comment]
Moment is already up to date based on IANA DB. It seems that the problem is in Chrome (please refer to issue https://github.com/moment/moment-timezone/issues/757)

**Comment by ellenaua** [comment]
@rafaelmmathias could you please show the output of this command (if you use mac or linux)
```cat /usr/share/zoneinfo/+VERSION```

**Comment by dotpegaso** [comment]
I've fixed this by updating the following packages in my React Native 0.59.10 application:
```json
"moment": "^2.24.0",
"moment-timezone": "^0.5.27",
```
### **BUT**

This only works when I get Debug Mode turned on. I found [this comment](https://github.com/facebook/react-native/issues/13195) which explain about the differences between JS runtimes in React Native with debug mode on/off and now I don't know what to do to get my GMT working in the right way.

**Comment by ashsearle** [comment]
Where are you running the React Native application?

The first bit of code in your original issue is:
```js
moment([2019, 10, 12, 10, 0]).tz("America/Sao_Paulo").toDate()
Tue Nov 12 2019 10:00:00 GMT-0200 (Brasilia Summer Time)
```

The result of `toDate()` is a `Date`, and `moment` has no influence over how that gets converted to a String.

If the React Native runtime where your application runs doesn't have up-to-date timezone information the native Date->String conversion will be wrong.  But... the `Date` may still represent the right point in time (i.e. `date.getTime()` and `date.valueOf()` return the correct values.) 

If you don't actually care what about native Date->String conversion, ignore the issue.

If the most important thing is to convert your `moment` to a `String` - I suggest using `format` and avoid `toDate` completely.

**Comment by mmCodingjs** [comment]
> Hi,
> 
> Our daylight saving time here in Brasil was cancelled by the president, so we'll not have summer time this year.
> 
> **Steps to reproduce the behavior**
> 
> ```
> moment([2019, 10, 12, 10, 0]).tz("America/Sao_Paulo").toDate()
> Tue Nov 12 2019 10:00:00 GMT-0200 (Brasilia Summer Time)
> ```
> 
> **Expected behavior**
> 
> ```
> Tue Nov 12 2019 10:00:00 GMT-0300 (Brasilia Standard Time)
> ```
> 
> **Moment-specific environment**
> 
> * The time zone setting of the machine the code is running on -03:00
> * The time and date at which the code was run
> 
> Please run the following code in your environment and include the output:
> 
> ```
> console.log((new Date()).toString()) // Tue Oct 08 2019 15:00:46 GMT-0300 (Brasilia Standard Time)
> console.log((new Date()).toLocaleString()) // 10/8/2019, 3:00:46 PM
> console.log((new Date()).getTimezoneOffset()) // 180
> console.log(navigator.userAgent) // Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
> console.log(moment.version) // 2.24.0
> ```
> 
> **Additional context**
> Source: https://veja.abril.com.br/economia/bolsonaro-assina-decreto-que-acaba-com-o-horario-de-verao/

Unfortunately it's an error with Moment.js because of this law decree, I don't think doing a manual conversion would be good, and It's not an error in the code while using moment or tz, this happened just because of this decree :disappointed:
Maybe letting the team aware of this adjustment or creating a pull request should solve this, but all we can do is wait, i guess

**Comment by Rohitkulkarni15** [comment]
Hi, 
I'm also blocked because of this issue .. 
Do we have a timeline in regards to the resolution date on this one ?

**Comment by aravind-sundararajan-e0308** [comment]
Hi,

Do we have any update on the resolution for this one?

**Comment by marwahaha** [comment]
2.25.3 should fix, along with latest versions of the browsers you all are using.

As @ashsearle mentioned, the bug is from Date -> String, so Moment.js should not have any bugs here. The change has been made in moment-timezone.

Please re-open if you still have concerns.
