### ISSUE TITLE
moment(myObj).isValid() returns true for custom objects

### ISSUE THREAD

**Issue by ampratt** [moment/moment#5253]
**Describe the bug**
checking for valid dates in order to format to our necessary format returns isValid == true and converts objects to valid moment objects

`moment(myObject).isValid()`
return true 

`moment(myObject)`
becomes today's date

**To Reproduce**
an object such as:
`let myObject = {
    address: null,
    warehouse: false,
    changeDate: "2019-03-21 15:28:07",
    changeUserId: "ME",
    coordinate: null,
    countryKey: 1,
    daylightEndTime1: null,
    daylightEndTime2: null,
    daylightStartTime1: null,
    daylightStartTime2: null,
    districtKey: 231,
    endDate: "2100-12-31 00:00:00",
    insertDate: "1999-12-01 11:21:16",
    insertUserId: "SIMPSON",
    key: 9,
    startDate: "1999-01-01 00:00:00",
    timediffSysdate: null,
    timezoneGmt: null,
    timezoneName: "Europe/Helsinki",
}`

passes as true
`moment(myObject).isValid()`

**Screenshots**
![image](https://user-images.githubusercontent.com/6746269/66632764-d8f45080-ec11-11e9-84b1-314100a0ae7d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome. Version 77.0.3865.90 (Official Build) (64-bit)
 - Version
    "moment": "^2.22.1",
    "moment-timezone": "^0.5.26",

**Moment-specific environment**

* UTC +3 (Helsinki Finland)
* Other libraries in use (TypeScript)

Fri Oct 11 2019 10:31:16 GMT+0300 (Eastern European Summer Time)
10/11/2019, 10:31:16 AM
-180
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Comment by ashsearle** [comment]
This is semi-documented behaviour for [`moment(object)`](https://momentjs.com/docs/#/parsing/object/):

> You can create a moment by specifying some of the units in an object.
>
> Omitted units default to 0 or the current date, month, and year.

What's weird is that `moment` behaves differently for a completely empty object:
```js
console.log(moment({}).toString()); // current date _and time_ 
console.log(moment({anyProperty:anyValue}).toString()); // current date _start of day_ 
```
