### ISSUE TITLE
Issue with "do" format

### ISSUE THREAD

**Issue by SCCarl** [moment/moment#5254]
**Describe the bug**
When using the "do" format with moment it will display the wrong date, so for example 04/10/2019 would show as the 5th.

**To Reproduce**
1. Visit this code pen https://codepen.io/carlsc/pen/ExxVGdV
2. open the console

**Expected behavior**
I would expect the output for the above to be "Friday 4th Oct 2019"

**Desktop (please complete the following information):**
 - MacOS
 - Firefox
 - 70.0b5

**Moment-specific environment**

* GMT
* 11/10/2018 11:40
* no toher libraries were in use

Please run the following code in your environment and include the output:
```
Fri Oct 11 2019 11:49:54 GMT+0100 (British Summer Time) 
11/10/2019, 11:49:54
-60 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0 
2.13.0  
```

**Comment by ashsearle** [comment]
Try `Do` instead of `do`.

`d` is 'day of week', not day of month.

**Comment by SCCarl** [comment]
Yeah that was it... sorry will close this issue!
