### ISSUE TITLE
Moment returning different offset that my local timezone

### ISSUE THREAD

**Issue by VishalGulati** [moment/moment#5256]
I am using Moment js to format date. I calcuate the current date using javascripts default utility new Date() and pass it to moment for formatting.

To my sheer disbelief, I get the time in the required format but in US timezone.

Here is my code:

```
var currentDate = new Date();
console.log(currentDate)
console.log(moment(currentDate).format('YYYY-MM-DD HH:mm'));
```
Output;
```

Tue Oct 15 2019 09:24:23 GMT+0530 (India Standard Time)
2019-10-14 23:24
```

When I use **.local()** with moment, everything works well.

```
console.log(moment(currentDate).local().format('YYYY-MM-DD HH:mm'));
2019-10-15 09:24
```
I tried logging `moment(new Date()).utcOffset()` and was shocked to see -240. My system is in IST. The date and time on system are on IST. Even consoling new Date shows I am in IST then where is moment getting UTC-4 then? I tried running` tzutil /g `on cmd and it printed IST. What exactly is going behind the scenes?

**Comment by ashsearle** [comment]
Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

**Comment by marwahaha** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
