### ISSUE TITLE
Help with moment function

### ISSUE THREAD

**Issue by emiller74** [moment/moment#5258]
Hello All, 

I've created a method in Vue.js to using the momentjs library to translate a value of seconds into human readable format.

When I console log the property I am attempting to pass to moment it comes out just fine. but when I pass it to the function all I ever get is "a few seconds", which after research seems like another way of saying invalid input. 
```
timeDuration() {
      console.log(this.$moment.duration(this.devicestat.Uptime, "seconds").humanize()); - a few seconds
      console.log(this.devicestat.Uptime); - gives 88601 
    },
```
any input?

**Comment by ashsearle** [comment]
Is `this.devicestat.Uptime` a string?

```js
moment(88601, 'seconds').humanize(); // a day
moment('88601', 'seconds').humanize(); // a few seconds
```

**Comment by emiller74** [comment]
It is coming in as a string...I did not catch that. Thank you. My working code is now this. 

```    timeDuration() {
      var intTime = parseInt(this.devicestat.Uptime, 10);
      return this.$moment.duration(intTime, 'seconds').humanize();
    },
```

**Comment by ashsearle** [comment]
I've no doubt you'll encounter this idiom sooner or later anyway, but just an FYI that you can use [unary +](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Unary_plus_()) to do the same job:

```js
return this.$moment.duration(+this.devicestat.Uptime, 'seconds').humanize();
```

**Comment by emiller74** [comment]
Thank you. That is very helpful

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
