### ISSUE TITLE
humanize() help

### ISSUE THREAD

**Issue by ninopetrovic** [moment/moment#5259]
Hello.

I have this code: `this.moment.duration(this.offsetMinutes, 'minutes').humanize()` to display offset from another date.
Now what I don't like here is that when the offset is bigger... the displayed string is not really accurate (offset of 34 days and offset of 40 days for example show "one month"). Is it possible to somehow change this so that the returned string would always be a number of days and then (globalized unit) day/days?

**Comment by ashsearle** [comment]
You could try [adjusting the relative time thresholds](https://momentjs.com/docs/#/customization/relative-time-threshold/) - e.g. bump up the `'d'` threshold to 365 / 366 or beyond.

If you never never want to see the duration humanized as months or years, you could do:
```js
moment.relativeTimeThreshold('d', Number.MAX_SAFE_INTEGER)
```
