### ISSUE TITLE
Moment-jalali.js having month names with wrong spelling names

### ISSUE THREAD

**Issue by kalvagopinath** [moment/moment#5266]
Hi, Moment-jalali.js having month names with wrong spelling names. fixed it with replacing after reading the value in my controller. any other options ...?

**Comment by ashsearle** [comment]
You could create an issue / raise a pull request in the [moment-jalaali](https://github.com/jalaali/moment-jalaali) project.

**Comment by kalvagopinath** [comment]
thanks ashsearle :)
