### ISSUE TITLE
moment.diff inconsistence

### ISSUE THREAD

**Issue by gitramro** [moment/moment#5268]
**Describe the bug**
The difference in seconds between two dates is incorrect

**To Reproduce**
I have two values

start: 1571946275762  //"2019-10-24T19:44:35.762Z"
end: 1571946279131  //"2019-10-24T19:44:39.131Z"

using this
`.format("YYYY-MM-DD HH:mm:ss")`
the values will look like this:

start: 2019-10-24 12:44:35
end: 2019-10-24 12:44:39

As you can see the difference between the two dates are just 4 seconds

If I want to get the difference in seconds between these two using 

`moment(end).diff(start) `

I get 3369 which is 3 seconds

or if I use it like this

`moment(end).diff(start,'seconds')`

i will get 3 which are the seconds but as you can see the real difference are 4 seconds

Am I missing something?

**Comment by ashsearle** [comment]
You're missing something: what's the difference between 35.762 and 39.131?  Is it 3.369 (full precision), or is it 4 (comparing integers)?

Let's take a slightly different extreme: is the difference between the following timestamps 1 day, or 2 minutes?
```
2019-10-24T23:59:00.000Z
2019-10-25T00:01:00.000Z
```

It depends on how you ask the question: which unit you're using, and whether you're taking an absolute difference or truncating to a chunkier unit before checking the difference.

**Comment by romainsimon** [comment]
I'm having a similar issue.
Here's a simple way to try : just type `moment().add(1, 'hour').diff()`

The answer should always be consistent and return `3600000`.
This is not the case, and on some occasions it returns `3599999`

```
> moment() +' '+ moment().add(1, 'hour').diff()
'1575634352402 3600000'
> moment() +' '+ moment().add(1, 'hour').diff()
'1575634352628 3600000'
> moment() +' '+ moment().add(1, 'hour').diff()
'1575634352835 3600000'
> moment() +' '+ moment().add(1, 'hour').diff()
'1575634353050 3600000'
> moment() +' '+ moment().add(1, 'hour').diff()
'1575634353266 3599999'
> moment() +' '+ moment().add(1, 'hour').diff()
'1575634353476 3600000'
> moment() +' '+ moment().add(1, 'hour').diff()
'1575634353682 3600000'
```

**Comment by ashsearle** [comment]
@romainsimon That's a different issue.  That's like expecting `[new Date(), new Date()]` to contain two instance of the same point in time.

It frequently will, but sometimes it won't.
