### ISSUE TITLE
Duration constructed from moment.diff is imprecise

### ISSUE THREAD

**Issue by kalanzai** [moment/moment#5273]
**Describe the bug**
A duration between two moments which are a year apart is not exactly 1 year.

**To Reproduce**
Issue is reproduced in codesandbox:
[![Edit dazzling-leftpad-6lme4](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-leftpad-6lme4?fontsize=14)

```
import moment from "moment";

const now = moment();
const lastYear = now.clone().subtract(1, "year");

const duration = moment.duration(now.diff(lastYear));
document.getElementById("app").innerHTML = `
<div>now: ${now.format()}</div>
<div>lastYear: ${lastYear.format()}</div>
<div>years: ${duration.years()}</div>
<div>months: ${duration.months()}</div>
<div>totalYears: ${duration.asYears()}</div>
`;
```

**Expected behavior**
The duration between two moments which are 1 year apart should be a year.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina (10.15)
 - Browser Chrome
 - Version 77.0.3865.120

**Smartphone (please complete the following information):**
Did not test on smartphone

**Moment-specific environment**

* "Europe/Copenhagen"
* 2019-10-30T16:18:22+01:00
* No other libraries

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
---
Wed Oct 30 2019 16:23:00 GMT+0100 (Central European Standard Time) 
30/10/2019, 16:23:00 
-60
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 
2.24.0 
```

**Additional context**
Issue was noticed in our development environment which uses moment `2.20.1` and moment-timezone `0.5.13`. However, as I was able to reproduce the issue in codesandbox using moment version `2.24.0` I'm report the issue here.

This might relate to https://github.com/moment/moment/issues/5267

**Comment by ashsearle** [comment]
The values you're seeing are based on the *average* length of a year.

There's more detail in [this comment](2688#issuecomment-149716957).

Not a bug; moment's working as designed, but probably not as you'd like to 🤔

**Comment by kalanzai** [comment]
Yeah I realised that after doing some more testing.  Thank you very much for your input. For our use case where we basically want to know the number of months between two moments I think we should just switch to using `m1.diff(m2, 'months')` rather than constructing a `duration`.
