### ISSUE TITLE
Day followed by Hours with no separator incorrectly parsed

### ISSUE THREAD

**Issue by carconper** [moment/moment#5278]
**Describe the bug**
When parsing a string to a date, using a string containing a date that represents the days with no preceding 0s (ex: '2019Nov1' for 1st of November 2019) followed by the hours and minutes and with no separators (ex: '2019Nov11205' for 12:05 of 1st of November 2019), moment is not capable of identifying the day with no preceding 0s even if the correct pattern is indicated:

**To Reproduce**

1. We have the date string `2019Nov11205` that we wanna convert into a date object
2. We use the pattern `YYYYMMMDkkMM` to be able to parse the string, where:
  YYYY used for 4 digit year
  MMM used for Month representing the month name first 3 characters
  D used for the day of the month with no preceding 0s
  kk used for hours (1 to 24)
  mm used for minutes
3. Run `moment('2019Nov11205', 'YYYYMMMDkkMM')`
4. Result should be `moment("2019-11-01T12:05:00.000")` but we get `moment("2019-11-11T20:05:00.000")` instead

**Expected behavior**
The digit `1` representing the first day of the month should be interpreted as the day 01, but moment is interpreting the first digit of the month as the second digit of the day.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browser: Using Terminal
 - Version N/A

**Moment-specific environment**

> console.log((new Date()).toString())
Fri Nov 01 2019 17:00:54 GMT-0700 (PDT)
> console.log((new Date()).toLocaleString())
2019-11-1 17:00:54
> console.log((new Date()).getTimezoneOffset())
420
> console.log(navigator.userAgent)
**NOTE:** Im using the terminal
> console.log(moment.version)
2.24.0 

**Additional context**
The issue is also reproducible with Day with preceding 0s (DD)

**Comment by ashsearle** [comment]
The examples don't match your description.  You said you're using 'MMM', but that's not given in your example values.

You say '2019111' is 1st November, but it could just as easily be 11th January.

If your date format is ambiguous (it is) you'll never be able to guarantee you're parsing it correctly.

**Comment by carconper** [comment]
@ashsearle Thanks for your quick response. And yes, you are right, my example above was incorrect and there was a mismatch between the pattern and the date-string. I apologize for the confusion 😓 

Nevertheless, that was a **human mistake** when copying and pasting as I tried different combinations to see what the output was for each fo them. I have corrected my mistake in the description above to reflect the actual scenario.

In summary:

```
$ m('2019Nov12205', 'YYYYMMMDkkmm')
moment("2019-11-12T20:05:00.000")

$ m('2019Nov12205', 'YYYYMMMDDkkmm')
moment("2019-11-12T20:05:00.000")

$ m('2019Nov12205', 'YYYYMMM Dkkmm')
moment("2019-11-12T20:05:00.000")

$ m('2019Nov1-2205', 'YYYYMMM-Dkkmm')
moment("2019-11-22T05:00:00.000")

$ m('2019Nov1-2205', 'YYYYMMMDkkmm')
moment("2019-11-01T22:05:00.000")
```

I may be missing something, but I believe there is no ambiguity in the above examples.

Thanks again for taking a look at this.

**Comment by ashsearle** [comment]
There's still ambiguity:
```js
m('2019Nov12205', 'YYYYMMMDkkmm')
```

Could be either:
2019 Nov 1 22 05 
2019 Nov 12 2 05 

Side-note: use [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/)

**Comment by ashsearle** [comment]
Use [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/):

```js
moment('2019Nov11205', 'YYYYMMMDkkmm', true); // Invalid date 
```

Inspecting the moment object reveals that it parses the string left-to-right in a greedy fashion.  It consumes two digits for `D` (because '11' is the longest valid value to parse for `D`.)  This doesn't leave enough characters left to parse the rest of the string.

This might be surprising, and you might think it should use back-tracking like a regular-expression library to exhaustively attempt different ways of parsing the entire string.

It doesn't.

**Comment by carconper** [comment]
Thanks a lot for the clear feedback on this @ashsearle.
It makes sense. We are moving to use the double-digit day to break the ambiguity and it works that way for us. 

Thanks again for your time. I really appreciate your help on this
