### ISSUE TITLE
Brazil Locale DST Error

### ISSUE THREAD

**Issue by luan1992** [moment/moment#5281]
**Describe the bug**

In Brazil location we have error of an hour early, because of the daylight saving time pointed by monet.js. We are not using 'daylight saving time' (+1 hour) this year.

**Comment by Librity** [comment]
It's happening on some windows machines: when we call `new Date()` it returns the time an hour ahead despite our systemtime `Get-Date;`

**Comment by safeerjavidh-zarget** [comment]
Its down to brazil decided not to follow daylight saving time from this year onwards.

So for all conversions with brazil time zone given in the time string, the result comes with +1 hour of actual time.

**Comment by hugoeustaquio** [comment]
You need to update moment-timestamp, the brazilian daylight savetime is updated there.

**Comment by safeerjavidh-zarget** [comment]
@hugoeustaquio where can i find it ?

**Comment by safeerjavidh-zarget** [comment]
@hugoeustaquio how can i do it ? where should i do the update ?

**Comment by marcusvpereira** [comment]
Hello Guys! I'm having same problem that @luan1992 and @safeerjavidh-zarget. It's not only on Windows machines. Same problem on mac. Any idea?

**Comment by luan1992** [comment]
Solved! Moment Team fix It!

**Comment by luan1992** [comment]
Nice work, Moment Team!

**Comment by safeerjavidh-zarget** [comment]
@luan1992 did they release any patch or something ? how do i get the latest fix from moment team ?

**Comment by luan1992** [comment]
@safeerjavidh-zarget  I do not know, just happen happened. 
![moment](https://user-images.githubusercontent.com/22417175/68484474-14d40300-021c-11ea-9082-f4d697fc77c9.png)
