### ISSUE TITLE
nulls cannot be passed as arguments in place of MomentInput

### ISSUE THREAD

**Issue by capaj** [moment/moment#5285]
This commit: https://github.com/moment/moment/commit/5a1843de5a98025aa04437df8d7e4e7200306704

breaks typescript strict mode-it shows a type error whenever I pass `null` into `isAfter` method for example.

Can it be reverted?
Maybe in a next major?

**Comment by harkue** [comment]
It is said as "Replace null/undefined with void in moment.d.ts to fix pre 2.0 typescript users" in the commit log. Maybe reverted in a new major version will be better.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
