### ISSUE TITLE
Could you please correct the language support for Italian? 

### ISSUE THREAD

**Issue by xmou-lucid** [moment/moment#5287]
**Describe the bug**
In current version of Italian language, we have these to calculate lastWeek: 
`calendar : {
            sameDay: '[Oggi alle] LT',
            nextDay: '[Domani alle] LT',
            nextWeek: 'dddd [alle] LT',
            lastDay: '[Ieri alle] LT',
            lastWeek: function () {
                switch (this.day()) {
                    case 0:
                        return '[la scorsa] dddd [alle] LT';
                    default:
                        return '[lo scorso] dddd [alle] LT';
                }
            },
            sameElse: 'L'
        },`
However, I think a better way to say it is: "la domenica scorsa alle..." or "il mercoledì scorso alle...".
Also, 'alle' works for all time except for 1 o'clock for which you would say "all'una" or "all' 1:00". 
Could you please fix that?

**Comment by ODAVING** [comment]
I can work on this!!
