### ISSUE TITLE
Get week ranges for a given month?

### ISSUE THREAD

**Issue by simov** [moment/moment#529]
I needed a way to get the week ranges (start/end day) for a given month. I ended up with this hacky solution:

``` js
function weeks (month) {
    month = moment(month, 'YYYY-MM-DD');

    var first = month.day() == 0 ? 6 : month.day()-1;
    var day = 7-first;

    var last = month.daysInMonth();
    var count = (last-day)/7;

    var weeks = [];
    weeks.push([1, day]);
    for (var i=0; i < count; i++) {
        weeks.push([(day+1), (Math.min(day+=7, last))]);

    }
    return weeks;
}
```

http://jsfiddle.net/simo/xPcEm/
Is there a better (cleaner) way to accomplish this?
Thanks!

**Comment by jtangelder** [comment]
I came up on this issue by searching on Google. Came up with a simple solution for this;

`const weeksInMonth = moment(moment().endOf('month') - moment().startOf('month')).weeks()`

**Comment by jhabdas** [comment]
@jtangelder If `moment('2015-02-01')` is plugged in the function returns `5`. Given Feb 2015 was not a leap-year and [had 28 days](http://www.epochconverter.com/weeks/2015) would you expect this to return `4`?

**Comment by basilinjoe** [comment]
I was using this solution `Math.ceil(moment().daysInMonth()/7)`

**Comment by basilinjoe** [comment]
@jhabdas what about `October 2016 ` your solution returns 5 but it has 6 weeks ,i was using `Math.ceil(moment()).daysInMonth()/7)` and face the same issue

**Comment by jhabdas** [comment]
@basilinhoe If that's the case I'd consider it a bug in Moment Duration. Could you double-check your installed version of Moment and Moment Duration so we can open a new ticket?

**Comment by jhabdas** [comment]
Also need sample Inputs to reproduce.

**Comment by jhabdas** [comment]
@basilinjoe If that's the case I'd consider it a bug in Moment Duration. Could you echo your installed version of Moment and Moment Duration, and provide sample input data to reproduce so we can open a new ticket?

**Comment by UnrealKazu** [comment]
@jhabdas I encountered the same bug as @basilinjoe 

In `October 2016`, moment duration (using your function) returns `5` weeks instead of `6`. I've created a quick CodePen: http://codepen.io/UnrealKazu/pen/jrYVwE

**Comment by jhabdas** [comment]
I'll be damned. Thanks. Will file a bug.

**Comment by UnrealKazu** [comment]
@jhabdas Nice! If you could link the bug report here so that we can track it, that would be great.

**Comment by jhabdas** [comment]
@timrwood thoughts on the above line of questioning before I open a bug? Looking at October on the Calendar it starts on a Sunday and ends on a Monday, covering a 6 week period (and not 5).

My use case personally was to create a bar graph with one bar for each week in the month. This seems it should be a trivial endeavor. But I had difficulty in doing so, and it seems others are as well.

**Comment by polarbirke** [comment]
@jhabdas Did you ever file that bug? I can't seem to find it. I do however have the same issue with October 2017.

**Comment by jhabdas** [comment]
Nope. I decided to quit my job instead.
