### ISSUE TITLE
Day light saving date is showing wrong timezone

### ISSUE THREAD

**Issue by bing4all** [moment/moment#5291]
I have a function which take date as an argument and get the zoneOffset from the date and check whether it is DST or not . It is showing from date only for 2 hours time during nov 3rd .

function formatTimezone(datetime) {
const zoneOffset = moment.parseZone(datetime).utcOffset()
const isDST = moment(datetime).isDST();
   if (!isDST && zoneOffset === -300) return 'EST';
    if (isDST && zoneOffset === -240) return 'EDT';
    if (!isDST && zoneOffset === -360) return 'CST';
    if (isDST && zoneOffset === -300) return 'CDT';
    if (!isDST && zoneOffset === -420) return 'MST';
    if (isDST && zoneOffset === -360) return 'MDT';
    if (!isDST && zoneOffset === -480) return 'PST';
    if (isDST && zoneOffset === -420) return 'PDT';
    if (zoneOffset === +0) return 'UTC';
    return '';
}
formatTimezone('2019-11-03T07:03:00-0700');

When is pass the date it is returning "MST" instead of PDT, i know i have a if condition check which is returning MST but why only that 2 hours and is anything wrong with my function

**Comment by ashsearle** [comment]
This looks like something people would normally use [`moment-timezone`](https://momentjs.com/timezone/docs/#/using-timezones/formatting/) to handle.

Have you tried using that?
