### ISSUE TITLE
MomentInputObject declared type outdated (Typescript)

### ISSUE THREAD

**Issue by TheMattBarnfield** [moment/moment#5295]
The interface for MomentInputObject doesn't allow for strings as values, which was added in version 2.11.0 (https://momentjs.com/docs/#/parsing/object/).
Thus the code
`moment({year:'2019'})`
gives the error
`Argument of type '{ year: string; }' is not assignable to parameter of type 'string | number | void | Date | (string | number)[] | Moment | MomentInputObject | undefined'`

**Comment by marwahaha** [comment]
Fixed in https://github.com/moment/moment/commit/535a72572cbdb3a1473914931e9352adc6a5ad24
