### ISSUE TITLE
moment.duration(a.difference(b,'hours')) returns difference in hours as milliseconds property on resulting object

### ISSUE THREAD

**Issue by hsdonkin** [moment/moment#5297]
**Describe the bug**
Subtracting the difference between two moments results in hours represented as milliseconds on object

a: `'Nov 19, 2019 2:41 PM'`
a: `'2019-11-19T14:41:30-08:00'`
b: `'Nov 18, 2019 1:42 PM'`
b: `'2019-11-18T21:42:01.000Z'`

**To Reproduce**

`let difference = moment.duration(a.diff(b, 'hours'))`

Returns:

```
Duration {
  _isValid: true,
  _milliseconds: 24,
  _days: 0,
  _months: 0,
  _data: {
    milliseconds: 24,
    seconds: 0,
    minutes: 0,
    hours: 0,
    days: 0,
    months: 0,
    years: 0
  },
```

Whereas:
`let difference = moment.duration(a.diff(b))`

Returns:
```
Duration {
  _isValid: true,
  _milliseconds: 89969000,
  _days: 0,
  _months: 0,
  _data: {
    milliseconds: 0,
    seconds: 29,
    minutes: 59,
    hours: 0,
    days: 1,
    months: 0,
    years: 0
  },
```

**Comment by ashsearle** [comment]
Perhaps this explains it:
```js
typeof a.diff(b, 'hours'); // 'number'
typeof a.diff(b); // 'number'
```

Both your examples call [`moment.duration(Number)`](https://momentjs.com/docs/#/durations/creating/); the number is interpreted as milliseconds, as you're not passing in any type information.

Alternative ways to call `duration`:
```js
moment.duration(a.diff(b, 'hours'), 'hours');
moment.duration({ hours: a.diff(b, 'hours') });
```
