### ISSUE TITLE
Invalid date String is accepted as valid date

### ISSUE THREAD

**Issue by patilvikram** [moment/moment#5299]
**Describe the bug**
I am trying to use the following code to determine 

```
d=moment('ABCD 1');
if(d.isValid()){
 alert(true);
}
```

**Expected behavior**

For this,  d should be invalid and isValid() should return false.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Version 78

Mon Nov 25 2019 11:31:35 GMT+0530 (India Standard Time)
(index):36 25/11/2019, 11:31:35
(index):37 -330
(index):38 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
(index):39 2.2.1
```

**Comment by ashsearle** [comment]
If you check the console the first time you try this, you should see a warning:
> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

As it says, it falls back to `new Date('ABCD 1')` which _may_ be parsed as `Mon Jan 01 2001 00:00:00 GMT+0000 (Greenwich Mean Time)` (depending on the browser / JS runtime.)

**Comment by patilvikram** [comment]
@ashsearle  Thanks for the reply. I have ended specifying the format as suggested by a workaround. Any idea which version of the moment will address this issue?

**Comment by ashsearle** [comment]
That's a good way to use moment: parse dates using specific format strings and ensure you have [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/) enabled.

It's not a 'workaround'.

I think it's too late to change moment to reject strings that `new Date(str)` would allow, or to force users to pass the second parameter defining acceptable format(s).

The deprecation warning (often missed) is the most obtrusive the library can be - throwing an `Error` would be unacceptable.
