### ISSUE TITLE
Hidden characters in Arabic locale definition files

### ISSUE THREAD

**Issue by afairbarns** [moment/moment#5300]
There are hidden characters present in the locale definition files for: "**ar**" and "**ar-ma**". 

Testing:
Given a hard-coded list of all the locales available in moment.js, loop through each one, change to that locale e.g `moment.locale('ar-ly')` , get the long date format from the locale data i.e. `moment.localeData().longDateFormat('L')` , then using a moment date object (in the format 'YYYY-MM-DD' format the date to the locale. 

In the cases above the **date was incorrectly formatted** - due to hidden non-readable characters in the definition file. So I had to run a `.replace(/[^\x20-\x7E]+/g, "")` on the long date format string returned from locale data.
``` javascript

  const localeData = ['af','ar-dz','ar-kw','ar-ly','ar-ma','ar-sa',
  'ar-tn','ar','az','be','bg','bm','bn','bo','br','bs','ca','cs',
  'cv','cy','da','de-at','de-ch','de','dv','el','en-SG','en-au',
  'en-ca','en-gb','en-US','en-ie','en-il','en-nz','eo','es-do',
  'es-us','es','et','eu','fa','fa-IR','fi','fil','fo','fr-ca','fr-ch',
  'fr','fy','ga','gd','gl','gom-latn','gu','he','hi','hr','hu','hy-am',
  'id','is','it-ch','it','ja','jv','ka','kk','km','kn','ko','ku','ky',
  'lb','lo','lt','lv','me','mi','mk','ml','mn','mr','ms-my','ms','mt',
  'my','nb','ne','nl-be','nl','nn','pa-in','pl','pt-br','pt','ro','ru',
  'sd','se','si','sk','sl','sq','sr-cyrl','sr-Latn','sr','ss','sv','sw',
  'ta','te','tet','tg','th','tl-ph','tlh','tr','tzl','tzm-latn','tzm',
  'ug','ug-cn','uk','ur','uz-latn','uz','vi','yo','zh-cn','zh-hk','zh-tw']

  const results = localeData.map(localeName => {
      const locale = localeData[localeName];
      moment.locale(localeName); //switch locale
      const testDate = moment('1997-11-30', 'YYYY-MM-DD');

      const dateFormat = moment.localeData().longDateFormat('L');
      const dateFormatReplace = moment.localeData().longDateFormat('L').replace(/[^\x20-\x7E]+/g, '');
      
      return {
        locale: localeName, //locale
        longDateFormat: dateFormat, //long date format from moment locale data
        formatted: testDate.format(dateFormat), //test date formatted with long date format 
        formattedWithReplace: testDate.format(dateFormatReplace), //test date formatted with long date format and corrected for hidden characters
        correct: testDate.format(dateFormat) == testDate.format(dateFormatReplace) //does date format from locale data equal the corrected version with hidden character removed?
      };
  });

  results.map(result => {if (!result.correct) console.log(result)});


```

results:
```javascript
{
	locale:"ar-ly",
	longDateFormat:"D/‏M/‏YYYY",
	formatted:"30/‏11/‏1997",
	formattedWithReplace:"30/11/1997",
	correct:false
}
{
	locale:"ar",
	longDateFormat:"D/‏M/‏YYYY",
	formatted:"٣٠/‏١١/‏١٩٩٧",
	formattedWithReplace:"٣٠/١١/١٩٩٧",
	correct:false
}
```

**Comment by ashsearle** [comment]
Do you mean the [`\u200f`](https://github.com/moment/moment/blob/13a61b285c095bda7ea8e33156090ea5ccfeaef1/src/locale/ar.js#L74) characters?  They're standard Unicode characters used to indicate the month name needs to be written right-to-left.

Or, did you mean something else?

**Comment by afairbarns** [comment]
Ah. Get that for 'ar' which formats as YYYY/MM/DD, but does not explain why the format for 'ar-ly' is output as DD/YYYY/MM? Does right-to-left not apply for the other locale's for ar?

**Comment by marwahaha** [comment]
@afairbarns That is up to the locale authors.
You can contact the author for ar-ly if you think it is incorrect: https://github.com/moment/moment/blob/develop/src/locale/ar-ly.js#L3

Please open a new issue if you wish to do that.
