### ISSUE TITLE
Calculate millisecond difference between two unix values

### ISSUE THREAD

**Issue by Lynxaa** [moment/moment#5302]
Hello, I am trying to obtain the difference in milliseconds between two values derived from epoch to no avail, the results are either always incorrect or result in precision loss; where precision is important for this task.

I have tried to use start.diff(end, 'milliseconds', true) and mulitple different ways to obtain the result.

I don't really know how else to describe my failure here, I'm not sure if it's a me issue or if it's something wrong with moment.js (I highly doubt this.)

I have two samples to work with, one is the current system time since epoch, the other is a regular time since epoch value.

```
const now = moment().unix(); // 1575092551
const then = moment.unix(1575092526);
const delta = now.diff(then, 'milliseconds');
```

With the above snippet and multiple other combinations of essentially the same code none of the results produced are accurate or reliable enough for precise timings.

A few things to note with the unix times (the 'then' time); 'then' is obtained from a response body, I can't do anything to the value to get further precision out of it and the value will always be greater than 'now' at the time of the response, the goal here is to calculate the difference in milliseconds and set a timeout to occur exactly when 'now' is the same as 'then'.

Thanks.

**Comment by Neob91** [comment]
I believe what you want is:

```
const now = moment(); // create a moment with the current time
const then = moment.unix(1575092526); // create a moment with the other time from seconds
const delta = now.diff(then, 'milliseconds'); // get the millisecond difference
```

It works fine for me. Please let me know if you have any more problems with this.

**Comment by marwahaha** [comment]
Thanks @Neob91 
Please re-open if you still have issues.
