### ISSUE TITLE
Reference/Documentation of the source

### ISSUE THREAD

**Issue by sandysandajan** [moment/moment#5304]
Do you have a link/copy of the source where you get all the information used in this github? What i know is that you get it from ISO 8601. But can you provide me the reference in order to establish a proper documentation. Also, when do you update the dates/formatting per country?

**Comment by marwahaha** [comment]
ISO 8601 is a standard.
Some information is on https://en.wikipedia.org/wiki/ISO_8601

You can get the format here: https://www.iso.org/iso-8601-date-and-time-format.html

If you submit a pull request, you can change `src/locale/` and your country/language name. We will discuss the change before merging it in.

Hope this helps.
