### ISSUE TITLE
Diff in weeks give wrong result

### ISSUE THREAD

**Issue by DIbraDev** [moment/moment#5305]
I'm trying to calculate the difference between two dates in weeks

I'm using french locale 'fr', so Monday is the start of week and Sunday is the end of the week.

referenceDate = moment('2019-01-01'); // start of year
now = moment('2019-12-02'); // monday => current week
yesterday = moment('2019-12-01'); // sunday => last week

When I calculate the difference, I got the same value
now.diff(referenceDate, 'weeks'); // return  47
yesterday.diff(referenceDate, 'weeks'); // return 47

It seems the difference is calculated from numbers of days (335/7) instead of considerating the starting and ending intervals.

now.weeks(); // return 49, correct value
But I can't use weeks() function because it's relative to the current year

**Comment by ashsearle** [comment]
The calculation uses the difference in milliseconds, divided by number of milliseconds in a week (based on 7 24-hour days.)

The code below should get you closer to what you want, but may need more logic to handle DST boundaries:
```js
firstDate.clone().startOf('week').diff(secondDate.clone().startOf('week'), 'weeks');
```

**Comment by DIbraDev** [comment]
Thank you @ashsearle for your help. Calculate the difference between the start of week of both dates is working for well.

```javascript
var firstDate = moment('2019-01-01'); // it's Tuesday
var secondDate = moment('2019-12-01'); // it's Sunday

var diff = secondDate.clone().startOf('week').diff(firstDate.clone().startOf('week'), 'weeks') + 1;
// Result : 47 + 1 = 48 => 2019-12-01 is in the 48th calendar week of 2019
```
