### ISSUE TITLE
Inconsistent Year formatting across Chrome and Firefox

### ISSUE THREAD

**Issue by mujib2953** [moment/moment#5306]
**Describe the bug**
I was trying to format date `31-Mar-2017` in `DD-MMM-YYYY` format with moment. It is working fine on chrome as expected but in Firefox the out put is like **`31-Mar--2017`** with extra dash in Year value.

**To Reproduce**
I have created a [sandbox](https://codesandbox.io/s/proto-jntm0) for this issue, open this in both browser (Chrome and Firefox). In the output window you will see the [result](https://jntm0.csb.app/).

**Expected behavior**
On both browser this should be consistent, extra dash should not be added.

**Desktop (please complete the following information):**
 - OS: Windows. Ubuntu
 - Browser Chrome `Version 77.0.3865.90 (Official Build) (64-bit)`, Firefox `70.0.1 (64-bit)`
- moment `version 2.24.0 & 2.22.1`

I have wrote something like below in the above given sandbox
```
moment("31-Mar-2017").format('DD-MMM-YYYY')
```

**Comment by Neob91** [comment]
I will work on this today.

**Comment by Neob91** [comment]
After investigation, this is probably not something we should fix.

The core issue is how `Date` on Firefox parses the date string.
When you do `new Date('31-Mar-2017').getFullYear()` on Firefox, you'll end up with value `-2017`.
This is because parsing dates can be inconsistent across browsers, and it's best to use ISO8601.

**Comment by mujib2953** [comment]
Thanks @Neob91 , I agree with you it is related to **Firefox**, I have opened this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1600902) to Firefox.

Till the time I am using simple hack so that it is consistent across all browser.
```javascript
export const trimDate = (date: string): string => {
    return  date.split("-").filter((d) => d !== "").join("-");
};
```

Thanks buddy.
