### ISSUE TITLE
Improvements made to the Norwegian locale were inadvertently removed

### ISSUE THREAD

**Issue by birdman7260** [moment/moment#5309]
**Describe the bug**
In 2014 a PR was submitted and accepted that fixed the short months for `nb`
Here is the PR: https://github.com/moment/moment/pull/1859
Then a year later in the build 2.11.0 commit it looks like that change was inadvertently removed.
Here is a link that shows the diff: https://github.com/moment/moment/commit/c74a101d549b8b443b72d9a470839eaffea852c2#diff-3fb530186c3e64b559c044cd32c13294

I wasn't able to see any talk about why this change would have been removed. Was this on purpose or can we have this fixed in the next build?

Tagging those involved in the changes here:
@egilkh @ichernev @torvalde

**Comment by marwahaha** [comment]
It comes from 
https://github.com/moment/moment/pull/5165

cc @sigurdga
