### ISSUE TITLE
Setting week/year in the last week of the year results in wrong date

### ISSUE THREAD

**Issue by michael-woodward-spok** [moment/moment#5311]
**Describe the bug**
When constructing a moment object with a date that is in the last week of the year `2019-12-31`, then setting the year or week results in an incorrect date.

**To Reproduce**
1. executing this code: `moment('2019-12-30', "YYYY-MM-DD").year(2019).week(52).format()`
2. results in: `"2020-12-21T00:00:00-06:00"`

Instead of using `format()`, the error can also be seen by calling `.year()`

**Expected behavior**
The last set year and week should be respected.

**Screenshots**
![image](https://user-images.githubusercontent.com/47120433/70182656-df4ef800-16a9-11ea-83e6-18ccf3b3079d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 78.0.3904.108 (Official Build) (64-bit)

**Moment-specific environment**

* The time zone setting of the machine the code is running on: **Central Standard Time**
* The time and date at which the code was run: **3:24PM**
* Other libraries in use (TypeScript, Immutable.js, etc): this can be seen on momentjs.com

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)

Wed Dec 04 2019 15:25:22 GMT-0600 (Central Standard Time)
12/4/2019, 3:25:22 PM
360
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
2.24.0
undefined
```

**Additional context**
I am using this in tests to simulate how moment will format dates during the last week of the year. For example, in my test, I would call `moment('2019-12-31')` instead of `moment()`.

**Comment by ashsearle** [comment]
What does `moment('2019-12-30', "YYYY-MM-DD").week()` return in your environment?

**Comment by michael-woodward-spok** [comment]
Thank you for the information! I was not aware of that / missed seeing `weekYear` in the documentation.  That seems to have helped a lot to understand more what moment does behind the scenes for handling weeks in the year.
