### ISSUE TITLE
Result of startOf, endOf is same when sharing moment instance

### ISSUE THREAD

**Issue by min9nim** [moment/moment#5312]
**Describe the bug**
Result of startOf, endOf is same when sharing moment instance

**To Reproduce**
```javascript
var moment = require("moment")

const month = moment('2020-01', 'YYYY-MM')
const start = month.startOf('month')
const end = month.endOf('month')

console.log('start:' + start.format('YYYY-MM-DD'))  // print "start:2020-01-31"
console.log('end:' + end.format('YYYY-MM-DD'))  // print "end:2020-01-31"
```

**Expected behavior**
```
start:2020-01-01
end:2020-01-31
```

**Screenshots**
![image](https://user-images.githubusercontent.com/6068828/70186677-c426cb80-172f-11ea-8244-df8074019db6.png)
https://runkit.com/embed/m6yca9yxaje9

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version 78.0.3904.108

**Smartphone (please complete the following information):**
N/A

**Moment-specific environment**
N/A

Please run the following code in your environment and include the output:
![image](https://user-images.githubusercontent.com/6068828/70186896-4616f480-1730-11ea-9e85-8e8344e013ef.png)

**Additional context**
N/A

**Comment by min9nim** [comment]
I found the cause.

The variables of month, start, end are all same instance so result is same

**Comment by OnurVar** [comment]
> I found the cause.
> 
> The variables of month, start, end are all same instance so result is same

For those who face this issue, you can create a new instance by `month.clone()`.
