### ISSUE TITLE
 the package weighs a lot

### ISSUE THREAD

**Issue by eeeman1** [moment/moment#5313]
"react": "^16.8.6"
"moment": "^2.24.0"

I connect the component "moment" and see that my file weighs a lot

with import moment├ σ /calendar      356 kB
without import moment├ σ /calendar      7.62 kB

This file weighs more than my entire project. So it should be?

**Comment by arswaw** [comment]
Moment.js is not tree-shakeable and it's therefore difficult to only import the functions you need. I wonder if the team has chosen to make Moment.js more modular.

**Comment by marwahaha** [comment]
Thanks for opening this request.
Without locales, moment is ~18kb when zipped.
For smaller libraries, there are various alternatives, including Luxon, Day.js, date-fns, ...
