### ISSUE TITLE
.diff of new 01/01/2019 to 01/01/2020 gives unusual result.

### ISSUE THREAD

**Issue by arswaw** [moment/moment#5316]
**Describe the bug**
When using .diff off the current date with the argument of some date:

`const initialDate = moment(initialDate)`
`const today = moment(new Date())`

`const timeDiff = moment.duration(today.diff(initialDate))`

returns 0years, 11months, 30days if initialDate = 01/01/2019 and today = 01/01/2020

According to Windows calculator "Difference between dates" the difference is one year. Who is wrong here?

**To Reproduce**
1. Create two moment objects, one 01/01/2019 and one 01/01/2020.
2. Use the 2020 moment object with .diff, pass in argument of 2019 moment object. 
3. Surround with moment.duration()
4. Use .years() .months() .days() off of the above result.
5. Notice that y = 0 and m = 11 and d = 30 

**Expected behavior**
I expected 1y, 0m, 0d. This behavior is reflected if you modify the year to 2021. It also shows 1y if you start from 2020 and go to 2021.

**Screenshots**
Github threw an error when I tried to upload a screenshot.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Opera
 - Version 2.24.0 from CDN

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 9
 - Browser Chrome
 - Version 78

**Moment-specific environment**

* EST
* Today
* No other libraries.

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)

Wed Dec 11 2019 15:28:04 GMT-0500 (Eastern Standard Time)
12/11/2019, 3:28:04 PM
300
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 OPR/65.0.3467.62
2.24.0
```

**Additional context**
I haven't found a date combination that produces this same result. Only 01/01/2019 and 01/01/2020.

**Comment by Priyam1464** [comment]
Can I work on this?

**Comment by arswaw** [comment]
> Can I work on this?

Sure. See if you can replicate it so that I know it isn't just happening to me.

**Comment by Priyam1464** [comment]
Ok cool

**Comment by arswaw** [comment]
> Ok cool

@Priyam1464 Did you find anything?

**Comment by flyingl** [comment]
![1](https://user-images.githubusercontent.com/15870404/72131191-8401db00-33b6-11ea-9c25-a88ac235d2ea.png)

Is moment bug? I was this problem

**Comment by flyingl** [comment]
I had this problem, anybody how dose fix it?

**Comment by flyingl** [comment]
I had this problem, anybody how dose fix it?

**Comment by arswaw** [comment]
> I had this problem, anybody how dose fix it?

@flyingl I see that this repository hasn't been committed to for over 7 months. I'm unsure what the maintenance status is as I see hundreds of issues and pull requests perpetually left open.

That being said, I'd still like to keep this bug report updated with new data for any maintainers to use. 

Can you describe the issue you're having? Is it as I described? Are you seeing it with different dates than 01/01/2019 and 01/01/2020 ?

Thank you.

**Comment by llexa313** [comment]
@arswaw I faced with a similar issue for
`moment.duration(moment('05-01-2020').diff(moment('02-01-2020')))`
it returns
```
days: 29
months: 2
```

**Comment by arswaw** [comment]
> @arswaw I faced with a similar issue for
> `moment.duration(moment('05-01-2020').diff(moment('02-01-2020')))`
> it returns
> 
> ```
> days: 29
> months: 2
> ```

@llexa313 Thank you for commenting. I will try your dates in my testbed and see if I can replicate. Are you expecting to see 3 months and 0 days?

This confirms that my particular set of dates are not the only ways to recreate this bug.

**Comment by llexa313** [comment]
@arswaw yes, my expectation is to see 3 months. 
For example, I have:
`moment.duration(moment().diff(moment().subtract(3, 'M'))).months()`
I substract 3 months, but the difference is 2.

**Comment by arswaw** [comment]
@llexa313 Thanks for your response. I see that the repo has some new updates. I will try again with the new version and see if it's fixed.

**Comment by marwahaha** [comment]
Sorry that you're experiencing an issue.

Could be related to https://github.com/moment/moment/issues/5195
