### ISSUE TITLE
Provide AP Style format for time descriptors “ante meridiem” and “post meridiem”

### ISSUE THREAD

**Issue by sanxac** [moment/moment#5319]
**Is your feature request related to a problem? Please describe.**
Unable to format times using AP style:  "should be abbreviated with lowercase letters and with periods (a.m. and p.m.)"

**Describe the solution you'd like**
Format that includes periods with am & pm

**Describe alternatives you've considered**
Currently using a string replace on formatted string. 

**Additional context**

**Comment by ashsearle** [comment]
Assuming you're talking about doing this for English:

1. You could define your own locale:
```js
moment.defineLocale("en_APStyle", {
  parentLocale: 'en',
  meridiem: function(hour, _, isLower) {
    const m = hour < 12 ? "a.m." : "p.m.";
    return isLower ? m : m.toUpperCase();
  }
});
moment().locale('en').format('a'); // am
moment().locale('en_APStyle').format('a'); // a.m.
```

2. You could modify the default `'en'` locale:
```js
moment.updateLocale("en", {
  meridiem: function(hour, _, isLower) {
    const m = hour < 12 ? "a.m." : "p.m.";
    return isLower ? m : m.toUpperCase();
  }
});
moment().locale('en').format('a'); // a.m.
```
