### ISSUE TITLE
dec28Of2019MomentObject.add(1, 'week').('YYYY-ww') is bad

### ISSUE THREAD

**Issue by szedlakmate** [moment/moment#5321]
1. Create a moment object (momentDate) with the date 2019-12-28

1. momentDate.add(1, 'week').format('YYYY-ww') => "2019-01" which is a bug!

**Comment by ashsearle** [comment]
Not a bug.

You need to look for 'week year' in the documentation, and make sure you're using the appropriate 'week year' token when formatting: e.g. `'gggg-ww'` instead of `'YYYY-ww'` (or, for ISO week numbering: `'GGGG-WW'`)

**Comment by szedlakmate** [comment]
Thanks for the workaround! But please, could you describe me why Locale week of year is different than ISO week numbering? Those should match and they don't

**Comment by ashsearle** [comment]
ISO has a specific set of rules:
- first day of the week is Monday
- first week of the year contains January 4th

Your locale may have different rules: e.g. your week may start on a Sunday.
