### ISSUE TITLE
moment().utcOffset with isBetween returning absurd results.

### ISSUE THREAD

**Issue by sirajalam049** [moment/moment#5322]
moment with utcOffset isBetween giving absurd results. Both True and false only on changing the format.

**To Reproduce**
```
let today = moment().utcOffset(120);
moment(today).isBetween(moment("1700", "HHmm"), moment("2300", "HHmm")); // true
moment(today.format("HHmm"),  "HHmm").isBetween(moment("1700", "HHmm"), moment("2300", "HHmm")); // false
```

**Expected behavior**
Should have given the same results on both the cases.

**Desktop:**
 - OS: MacOS Mojave 10.14.6
 - Browser Google Chrome Version 78.0.3904.108

**Moment-specific environment**
I directly checked in the console of the browser on https://momentjs.com/

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)

Tue Dec 17 2019 20:03:59 GMT+0530 (India Standard Time)
VM3331:2 17/12/2019, 20:03:59
VM3331:3 -330
VM3331:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
VM3331:5 2.24.0
```

**Comment by ashsearle** [comment]
What do you get for:
```js
moment().format('HHmm')
```

vs.
```js
moment().utcOffset(120).format('HHmm')
```

**Comment by sirajalam049** [comment]
`moment().format('HHmm')`
"2028"
`moment().utcOffset(120).format('HHmm')`
"1658"

**Comment by ashsearle** [comment]
I'm not too sure how to explain this.

The problem isn't that you've changed the format, the problem is you've lost the UTC offset information.

```js
let today = moment().utcOffset(123); // deliberate weird offset
console.log(moment(today).utcOffset()); // 123
console.log(moment(today.format('HHmm'), 'HHmm').utcOffset()); // not 123
```

**Comment by sirajalam049** [comment]
I also thought that.
But this isn't the case confirmed by this

moment().utcOffset(120).isBetween(moment("1900", "HHmm"), moment("2300", "HHmm"));

**Comment by sirajalam049** [comment]
Well, I understood your point, but still the problem is with utcOffset().isBetween.

Do I need to remove the utc info before using isBetween?

**Comment by ashsearle** [comment]
The moments with/without utcOffset represent different points in time:
```js
let today = moment().utcOffset(123);
moment(today.format('HHmm'), 'HHmm').diff(today, 'minutes', true); // 122.something
```

**Comment by sirajalam049** [comment]
Well, here I'm comparing a time zone with not another timezone but with a value of hours. So here I'm expecting it tells that the given time is in the range of those hours or not.

If I'm taking the good approach, please let me know what is the correct way of doing this.

**Comment by ashsearle** [comment]
`isBetween` tells you whether a point in time is between two other points in time.

If you want to compare time-of-day ignoring the date you can pull the values out of the `moment` and use numeric or string comparison to do what you want:

```js
moment.prototype.isTimeBetween = function(startTime, endTime) {
  const time = this.format("HHmm");
  // Note: you may want to change '<=' and '<' to meet your own requirements
  return startTime <= time && time < endTime;
};
moment().isTimeBetween('1700', '2300');
```

**Comment by marwahaha** [comment]
I recommend @ashsearle 's information.

Please re-open if you still have concerns.
