### ISSUE TITLE
Historic DST differences for The Netherlands

### ISSUE THREAD

**Issue by huubhermsen** [moment/moment#5323]
**Describe the bug**
On Safari all (summertime) dates before 1977 return true when calling isDST() on moment object.

**To Reproduce**
1. Open a Safari and Chrome browser
2. Create a Date object new Date(1948, 5, 19, 0, 0, 0);
3. Pass object to moment and call isDST(): moment(new Date(1948, 5, 19, 0, 0, 0)).isDST();
4. Log result

**Expected behavior**
It should return false on Safari

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Safari
 - Version: 13.0.3

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)

[Log] Tue Dec 17 2019 16:24:51 GMT+0100 (CET)
[Log] 17-12-2019 16:24:51
[Log] -60
[Log] Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
[Log] 2.24.0
```

**Additional context**
Is this an issue with moment or can be resolved with moment? Or should this be reported to the maintainers of Safari? 

DST was re-implemented in the Netherlands in 1977

**Comment by ashsearle** [comment]
By default moment will rely on the host JavaScript runtime, which _may_ rely on the O/S for timezone data.

Most software will use the IANA timezone database, but may subset it to save space.

If you want to use IANA timezone data client-side, you could look at [moment-timezone](https://momentjs.com/timezone/) (and note the different download bundle for including 10 years, data after 1970 or complete datasets.)

**Comment by huubhermsen** [comment]
Thank you @ashsearle for your reply, I'll check it out.
