### ISSUE TITLE
Rename locale (me) to (cnr)

### ISSUE THREAD

**Issue by AlsoScratch** [moment/moment#5325]
I noticed that you have a file named `me.js`. But according to Wikipedia, `me` is not a valid 2-letter ISO 639-1 code. Did you mean to use a 3-letter code for this language?

**Comment by ashsearle** [comment]
Looks like [montenegrin](https://github.com/moment/moment/blob/develop/src/locale/me.js#L2).

It also looks like `'me'` _was_ the right code to use when the file was created (see [comments](https://github.com/moment/moment/pull/2136#issuecomment-68350852))

I could see an argument for calling the locale `'cnr'` if it didn't already exist; but feels like it'd be a breaking change to rename the locale now.

**Comment by AlsoScratch** [comment]
Although `me` is currently not an ISO 639-1 code that's in use, that means it's possible for `me` to become allocated for another language in the future that may or may not be Montenegrin.
Not saying that it's likely though.

**Comment by AlsoScratch** [comment]
> It also looks like `'me'` _was_ the right code to use when the file was created (see [comments](https://github.com/moment/moment/pull/2136#issuecomment-68350852))

Okay, I just checked the comment and it mentions [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) but that is for countries and territories but not languages. For languages, it's [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) that you may need and what I believe is the intended naming for the locale files.

**Comment by ashsearle** [comment]
@AlsoScratch You're probably right: locale files are named after ISO 639-1 where a 2-character code is available, and ISO 639-2 or ISO 639-3 if not.

In this case, the `'cnr'` ISO 639-3 wasn't registered at the time the locale was contributed to moment, so couldn't follow ISO 639 naming convention.  And now... it's a breaking change to rename it.

https://iso639-3.sil.org/code/cnr

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
