### ISSUE TITLE
15 tests failed. locale:ja:calendar next week (1442.1) locale:ja:calendar next week (1442.2) locale:ja:calendar next week (1442.3) locale:ja:calendar next week (1442.4) locale:ja:calendar next week (1442.5) locale:ja:calendar next week (1442.6) locale:ja:calendar next week (1442.7) locale:ja:calendar next week (1442.8) locale:ja:calendar next week (1442.9) locale:ja:calendar next week (1442.10) locale:ja:calendar next week (1442.11) locale:ja:calendar next week (1442.12) locale:ja:calendar next week (1442.13) locale:ja:calendar next week (1442.14) locale:ja:calendar next week (1442.15) 

### ISSUE THREAD

**Issue by versusvoid** [moment/moment#5327]
### Client info
```
Date String   : Fri Dec 27 2019 08:10:20 GMT+0300 (Москва, стандартное время)
Locale String : 27.12.2019, 08:10:20
Offset        : -180
User Agent    : Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0
Moment Version: 2.24.0
```

====

### locale:ja:calendar next week (1442.1) 

Today + 2 days current time

```javascript
// Expected 来週日曜日 08:10
// Actual   日曜日 08:10
"日曜日 08:10" === "来週日曜日 08:10"
```

====

### locale:ja:calendar next week (1442.2) 

Today + 2 days beginning of day

```javascript
// Expected 来週日曜日 00:00
// Actual   日曜日 00:00
"日曜日 00:00" === "来週日曜日 00:00"
```

====

### locale:ja:calendar next week (1442.3) 

Today + 2 days end of day

```javascript
// Expected 来週日曜日 23:59
// Actual   日曜日 23:59
"日曜日 23:59" === "来週日曜日 23:59"
```

====

### locale:ja:calendar next week (1442.4) 

Today + 3 days current time

```javascript
// Expected 来週月曜日 08:10
// Actual   月曜日 08:10
"月曜日 08:10" === "来週月曜日 08:10"
```

====

### locale:ja:calendar next week (1442.5) 

Today + 3 days beginning of day

```javascript
// Expected 来週月曜日 00:00
// Actual   月曜日 00:00
"月曜日 00:00" === "来週月曜日 00:00"
```

====

### locale:ja:calendar next week (1442.6) 

Today + 3 days end of day

```javascript
// Expected 来週月曜日 23:59
// Actual   月曜日 23:59
"月曜日 23:59" === "来週月曜日 23:59"
```

====

### locale:ja:calendar next week (1442.7) 

Today + 4 days current time

```javascript
// Expected 来週火曜日 08:10
// Actual   火曜日 08:10
"火曜日 08:10" === "来週火曜日 08:10"
```

====

### locale:ja:calendar next week (1442.8) 

Today + 4 days beginning of day

```javascript
// Expected 来週火曜日 00:00
// Actual   火曜日 00:00
"火曜日 00:00" === "来週火曜日 00:00"
```

====

### locale:ja:calendar next week (1442.9) 

Today + 4 days end of day

```javascript
// Expected 来週火曜日 23:59
// Actual   火曜日 23:59
"火曜日 23:59" === "来週火曜日 23:59"
```

====

### locale:ja:calendar next week (1442.10) 

Today + 5 days current time

```javascript
// Expected 来週水曜日 08:10
// Actual   水曜日 08:10
"水曜日 08:10" === "来週水曜日 08:10"
```

====

### locale:ja:calendar next week (1442.11) 

Today + 5 days beginning of day

```javascript
// Expected 来週水曜日 00:00
// Actual   水曜日 00:00
"水曜日 00:00" === "来週水曜日 00:00"
```

====

### locale:ja:calendar next week (1442.12) 

Today + 5 days end of day

```javascript
// Expected 来週水曜日 23:59
// Actual   水曜日 23:59
"水曜日 23:59" === "来週水曜日 23:59"
```

====

### locale:ja:calendar next week (1442.13) 

Today + 6 days current time

```javascript
// Expected 来週木曜日 08:10
// Actual   木曜日 08:10
"木曜日 08:10" === "来週木曜日 08:10"
```

====

### locale:ja:calendar next week (1442.14) 

Today + 6 days beginning of day

```javascript
// Expected 来週木曜日 00:00
// Actual   木曜日 00:00
"木曜日 00:00" === "来週木曜日 00:00"
```

====

### locale:ja:calendar next week (1442.15) 

Today + 6 days end of day

```javascript
// Expected 来週木曜日 23:59
// Actual   木曜日 23:59
"木曜日 23:59" === "来週木曜日 23:59"
```

**Comment by terrencew97** [comment]
This is a bug in ja locale file when getting nextWeek when day reaches the last week of the year. And I have fixed it in 98b666b.
