### ISSUE TITLE
15 tests failed. locale:ja:calendar next week (1442.1...

### ISSUE THREAD

**Issue by Amereth** [moment/moment#5328]
### Client info
```
Date String   : Fri Dec 27 2019 21:07:55 GMT+0200 (Восточная Европа, стандартное время)
Locale String : 27.12.2019, 21:07:55
Offset        : -120
User Agent    : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Moment Version: 2.24.0
```

====

### locale:ja:calendar next week (1442.1) 

Today + 2 days current time

```javascript
// Expected 来週日曜日 21:07
// Actual   日曜日 21:07
"日曜日 21:07" === "来週日曜日 21:07"
```

====

### locale:ja:calendar next week (1442.2) 

Today + 2 days beginning of day

```javascript
// Expected 来週日曜日 00:00
// Actual   日曜日 00:00
"日曜日 00:00" === "来週日曜日 00:00"
```

====

### locale:ja:calendar next week (1442.3) 

Today + 2 days end of day

```javascript
// Expected 来週日曜日 23:59
// Actual   日曜日 23:59
"日曜日 23:59" === "来週日曜日 23:59"
```

====

### locale:ja:calendar next week (1442.4) 

Today + 3 days current time

```javascript
// Expected 来週月曜日 21:07
// Actual   月曜日 21:07
"月曜日 21:07" === "来週月曜日 21:07"
```

====

### locale:ja:calendar next week (1442.5) 

Today + 3 days beginning of day

```javascript
// Expected 来週月曜日 00:00
// Actual   月曜日 00:00
"月曜日 00:00" === "来週月曜日 00:00"
```

====

### locale:ja:calendar next week (1442.6) 

Today + 3 days end of day

```javascript
// Expected 来週月曜日 23:59
// Actual   月曜日 23:59
"月曜日 23:59" === "来週月曜日 23:59"
```

====

### locale:ja:calendar next week (1442.7) 

Today + 4 days current time

```javascript
// Expected 来週火曜日 21:07
// Actual   火曜日 21:07
"火曜日 21:07" === "来週火曜日 21:07"
```

====

### locale:ja:calendar next week (1442.8) 

Today + 4 days beginning of day

```javascript
// Expected 来週火曜日 00:00
// Actual   火曜日 00:00
"火曜日 00:00" === "来週火曜日 00:00"
```

====

### locale:ja:calendar next week (1442.9) 

Today + 4 days end of day

```javascript
// Expected 来週火曜日 23:59
// Actual   火曜日 23:59
"火曜日 23:59" === "来週火曜日 23:59"
```

====

### locale:ja:calendar next week (1442.10) 

Today + 5 days current time

```javascript
// Expected 来週水曜日 21:07
// Actual   水曜日 21:07
"水曜日 21:07" === "来週水曜日 21:07"
```

====

### locale:ja:calendar next week (1442.11) 

Today + 5 days beginning of day

```javascript
// Expected 来週水曜日 00:00
// Actual   水曜日 00:00
"水曜日 00:00" === "来週水曜日 00:00"
```

====

### locale:ja:calendar next week (1442.12) 

Today + 5 days end of day

```javascript
// Expected 来週水曜日 23:59
// Actual   水曜日 23:59
"水曜日 23:59" === "来週水曜日 23:59"
```

====

### locale:ja:calendar next week (1442.13) 

Today + 6 days current time

```javascript
// Expected 来週木曜日 21:07
// Actual   木曜日 21:07
"木曜日 21:07" === "来週木曜日 21:07"
```

====

### locale:ja:calendar next week (1442.14) 

Today + 6 days beginning of day

```javascript
// Expected 来週木曜日 00:00
// Actual   木曜日 00:00
"木曜日 00:00" === "来週木曜日 00:00"
```

====

### locale:ja:calendar next week (1442.15) 

Today + 6 days end of day

```javascript
// Expected 来週木曜日 23:59
// Actual   木曜日 23:59
"木曜日 23:59" === "来週木曜日 23:59"
```

**Comment by marwahaha** [comment]
@baryon could you look into this?
