### ISSUE TITLE
Parsing ignores some format options when using a different locale.

### ISSUE THREAD

**Issue by turtleguyy** [moment/moment#5344]
I'm not sure of the extensiveness of the issue, but for my use-case, parsing seemed to be ignoring my meridiem format specifier because my selected locale doesn't use them.

**To Reproduce**
```
moment.locale('zh-cn');
moment('02:00 PM', 'hh:mm A').format('LT'); // 02:00
```

**Expected behavior**
Parse should recognize the 'A' option in the format argument and correctly parse the above time to 14:00. Yes, leaving the global locale as English and setting the local locale to Chinese before formatting is a workaround, but that's all it is — a workaround.

**Desktop:**
 - OS: MacOS 10.15.2
 - Browser: Chrome 79.0.3945.88

**Moment-specific environment**
Tested directly in the console on https://momentjs.com/. 

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)

Thu Jan 09 2020 17:28:44 GMT-0600 (Central Standard Time)
1/9/2020, 5:28:44 PM
360
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
2.24.0
```

**Comment by ashsearle** [comment]
If you know you're parsing dates with English meridiem format, use `en` explicitly when parsing, then reset the instance locale immediately after parsing:

```js
moment('02:00 PM', 'hh:mm A', 'en').locale(false).format('LT');
```

**Comment by turtleguyy** [comment]
Thanks, that's better than my workaround, but still feels like workaround. The issue remains: I'm passing in exactly what format the time will be in, why is it seemingly ignoring the `A` option?

**Comment by turtleguyy** [comment]
💡 _everything clicks into place and I realize the error of my ways_

It's not ignoring the meridiem at all, is it? It just doesn't know understand the _English_ AM/PM because I'm telling it to expect Chinese characters. Bother. Alright then, @ashsearle's comment is probably the cleanest way to handle this, then.

I know you guys were probably worried I had found a world-shattering, game-changing bug with moment, but have no fear — just another case of PEBKAC. Feel free to turn off the alarms, reset the lockdown at Moment HQ, and go about your day.

**Comment by marwahaha** [comment]
Glad you figured out your issue.
Have a nice day.
