### ISSUE TITLE
Using moment to get the date of today, but it gets the date of yesterday

### ISSUE THREAD

**Issue by Z1hgq** [moment/moment#5346]
**Describe the bug**
I loaded a page yesterday but did not close it. Today, I clicked a button on that page to use moment to get the date of today,  it got the date of yesterday

**Comment by ashsearle** [comment]
If you mean:
```js
const today = moment();
// ...time passes, and the next day:
console.log(today.format());
```

It's expected that you'd see yesterday's date if that _instance_ was created yesterday.

**Comment by Z1hgq** [comment]
> If you mean:
> 
> ```js
> const today = moment();
> // ...time passes, and the next day:
> console.log(today.format());
> ```
> 
> It's expected that you'd see yesterday's date if that _instance_ was created yesterday.

Yes, I recognized that and I used a IIFE to solve it
