### ISSUE TITLE
zh_TW locale formatted with DDD MMM is missing the day indicator

### ISSUE THREAD

**Issue by scottdickerson** [moment/moment#5350]
**Describe the bug**
To see the problem, set your locale to moment.locale('zh_TW').
Then moment format a date with
moment().format('DDD MMM')

instead of getting:
7日1月
You get
7 1月
Which is incorrect according to our testers

**Moment-specific environment**
Trying to test in zh_TW
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
Wed Jan 15 2020 14:50:54 GMT-0600 (Central Standard Time)
1/15/2020, 2:50:54 PM
360
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
2.24.0

**Additional context**

**Comment by ashsearle** [comment]
`DDD` represents the day of the year (1..366), not the day of the month.

I'm guessing you want `Do MMM` instead?

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
