### ISSUE TITLE
When I use MacOS to switch the system language to Traditional Chinese, the language of the plugin package is garbled

### ISSUE THREAD

**Issue by Famer-Y** [moment/moment#5355]
**Describe the bug**
When I use MacOS to switch the system language to Traditional Chinese, the language of the plugin package is garbled

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser Chrome 
 - Version 79.0.3945.117

Please run the following code in your environment and include the output:
```
moment.js:4988 Uncaught SyntaxError: Invalid regular expression: missing /
```

**Comment by ashsearle** [comment]
Which plugin?

**Comment by Famer-Y** [comment]
moment.js

**Comment by Famer-Y** [comment]
I used it in Chrome extension

**Comment by marwahaha** [comment]
Hi! Thanks for filing this issue! Unfortunately, I can't reproduce this. Could you provide any other information?

**Comment by marwahaha** [comment]
duplicate of https://github.com/moment/moment/issues/5355
