### ISSUE TITLE
Bug Add Minute to Date

### ISSUE THREAD

**Issue by ctgroupgit** [moment/moment#5359]
Describe the bug
Everytime when I run this script for add minutes to date from October to infinite it returns always the same date. When the day come is 2020-10-25 02:00:00 .

const moment = require('moment');
const dt = new Date();
require("moment/min/locales.min");

moment.locale('it');

let end = 2000000;
let start = 0;
let startData = '2020-10-25 00:00:00';
let newDataForStorage = startData;
while (start <= end)
{
    newDataForStorage = moment(newDataForStorage).add(1 , 'minute').format('YYYY-MM-DD HH:mm:ss');;
    start++;
    console.log(newDataForStorage, start, end);
}

To Reproduce

Run the script
Check the data and time from 2010-10-25 01:59:00 you see that always repeat the same date when the time come from 01:00:00  to 02:59:00.

Moment-specific environment

Please run the following code in your environment and include the output:

**Comment by ashsearle** [comment]
More information please: which version of moment are you using?  Which browser / node runtime?  What's your location / timezone?

**Comment by ricardoff5** [comment]
Same problem here, but when add 1 day to a date.
im using node with express.
Debian 9
time: Wed 08 Apr 2020 05:32:19 PM -03

```
routes.get("/testseeddate", (req, res) => {
    let arrayOfDates = [];
    let dateInit = "2016-01-01";
    let dateEnd = "2022-12-31";
    let moment_day = moment(dateInit, 'YYYY-MM-DD');
   while (!moment_day.isSame(moment(dateEnd, 'YYYY-MM-DD'))) {
        console.log("---- moment_day", moment_day.format());
        moment_day_one_current_month = moment_day.startOf('month');
        arrayOfDates.push({
            did: parseInt(moment_day.format('YYYYMMDD')),
            text: moment_day.format('YYYY-MM-DD'),
            day: moment_day.date(),
            month: moment_day.month(),
            year: moment_day.year(),
            half: (moment_day.month >= 7 ? 2 : 1),
            quarter: moment_day.quarter(),
            weekOfMonth: Math.ceil((moment_day.date() + moment_day_one_current_month.day()) / 7),
            weekOfYear: moment_day.week(),
            dayOfYear: moment_day.dayOfYear(),
            dayOfWeek: moment_day.day(),
            createdAt: new Date(),
            updatedAt: new Date()
        });
        moment_day.add(1, 'days');
    }
    res.json(arrayOfDates);
});
```

**OUTPUT**

---- moment_day 2016-01-01T00:00:00-03:00
---- moment_day 2016-01-02T00:00:00-03:00
---- moment_day 2016-01-02T00:00:00-03:00
---- moment_day 2016-01-02T00:00:00-03:00
---- moment_day 2016-01-02T00:00:00-03:00
---- moment_day 2016-01-02T00:00:00-03:00
---- moment_day 2016-01-02T00:00:00-03:00
---- moment_day 2016-01-02T00:00:00-03:00
---- moment_day 2016-01-02T00:00:00-03:00
---- moment_day 2016-01-02T00:00:00-03:00

**Comment by ashsearle** [comment]
@ricardoff5 That's a different issue.  Your while loop is similar to:

```js
const moment_day = ...;
while (...) {
  console.log("---- moment_day", moment_day.format());
  // moment_day.startOf("month");
  // moment_day.add(1, "days");
  moment_day.date(2);
}
```

i.e. the end of the loop never advances `moment_day`, it just keeps setting it to the same instant.

**Comment by ricardoff5** [comment]
> @ricardoff5 That's a different issue. Your while loop is similar to:
> 
> ```js
> const moment_day = ...;
> while (...) {
>   console.log("---- moment_day", moment_day.format());
>   // moment_day.startOf("month");
>   // moment_day.add(1, "days");
>   moment_day.date(2);
> }
> ```
> 
> i.e. the end of the loop never advances `moment_day`, it just keeps setting it to the same instant.

Sr, if it is a different problem, may you answer my topic at #5439 to keep this with focus on ctgroupgit problem?

I dont understand your answer, its a bug or expected result?
This command set day fix to 2:
moment_day.date(2)

This command add 1 day to current date:
moment_day.add(1, "days");
so every loop it might give a different number

To me this two functions might have 2 great different results

**Comment by ashsearle** [comment]
@ctgroupgit I should have noticed this immediately: you must be in a timezone where daylight-savings-time ends on the last Sunday of October, so that the local time goes from 01:59 to 01:00, as the clocks move back.

The problem with your original code is that you're formatting the date-time without any timezone information, and the timezone info is essential to distinguish the first instance of 01:00 from the second on the day the clocks 'fall back'.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
