### ISSUE TITLE
Iso year format option

### ISSUE THREAD

**Issue by toxaq** [moment/moment#536]
I couldn't find an Iso year format option in the documentation which makes the week option quirky for some dates:

```
> moment([2012,11,31]).format('w YYYY')
> "1 2012" 
```

The equivalent in postgresql is:

```
> SELECT EXTRACT(WEEK FROM DATE '2012-12-31') || ' ' || EXTRACT(ISOYEAR FROM DATE '2012-12-31');
> "1 2013"
```

As you can see the year is wrong. So the week is the right week but I couldn't find a way to get the matching year.

**Comment by christiaanwesterbeek** [comment]
Today you would do: `moment().format('GGGG[W]WW')` ([iso](https://en.wikipedia.org/wiki/ISO_8601)) or `moment().format('W GGGG')` as asked in the first comment.
