### ISSUE TITLE
moment start of time 'year' set Sat Feb 01 2020 00:59:59 GMT+0100

### ISSUE THREAD

**Issue by p4cm4n972** [moment/moment#5360]
**Describe the bug**
moment start of time 'year' set to  Sat Feb 01 2020 00:59:59 GMT+0100

**To Reproduce**
const firstDayOfYear: moment.Moment = moment().startOf('year') ==> Sat Feb 01 2020 00:59:59 GMT+0100

**Expected behavior**
it would set to January 1st, 12:00 am this year

 - OS: Windows 10
 - Browser: chrome

console.log((new Date()).toString()) ==> Thu Jan 23 2020 15:52:29 GMT+0100 (Paris, Madrid)
console.log((new Date()).toLocaleString()) ==>  2020-1-23 15:52:29
console.log((new Date()).getTimezoneOffset()) ==> -60
console.log(navigator.userAgent) ==> "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
console.log(moment.version) ==> 2.22.2
```

**Comment by ashsearle** [comment]
There are a lot of `startOf` / `endOf` fixes in 2.24.0

Please check if the you have problems using the latest version.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
