### ISSUE TITLE
Wrong translation of days in Portuguese

### ISSUE THREAD

**Issue by swapnesh** [moment/moment#5361]
**Describe the bug**
Dates text in a Portuguese calendar displaying numeral characters instead of short day text.
Day name text in Portuguese contains some digits like 2a, 3a etc.

CodeLink - https://codesandbox.io/s/funny-yalow-nsd9b
https://github.com/airbnb/react-dates/issues/1906

**To Reproduce**
Steps to reproduce the behaviour:
CodeLink - https://codesandbox.io/s/funny-yalow-nsd9b

**Expected behavior**
It should translate to text other than numerals.

**Screenshots**
<img width="669" alt="React-Dates-PT" src="https://user-images.githubusercontent.com/555540/73060207-5724ec00-3ebd-11ea-8dc4-07f87fc97908.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser Chrome
 - Version 79

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
Output - Fri Jan 24 2020 15:24:22 GMT+0530 (India Standard Time)

console.log((new Date()).toLocaleString())
Output - 24/01/2020, 15:24:42

console.log((new Date()).getTimezoneOffset())
Output - -330

console.log(navigator.userAgent)
Output - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36

console.log(moment.version)
Output - 2.21.0
```

**Additional context**
Seems like a moment issue - https://github.com/airbnb/react-dates/issues/1906

**Comment by ashsearle** [comment]
What makes you say it's the wrong translation?  Do you have an alternative suggestion for Portuguese?

Vietnamese (vi) and Swahili (sw) are two other locales that use numbers as part of the minimal (2-character) version of weekday names.

If you really don't like it, you can override it: e.g.
```js
moment.updateLocale('pt', {
    weekdaysMin : 'dom._seg._ter._qua._qui._sex._sáb.'.split('_')
});
```

**Comment by swapnesh** [comment]
@ashsearle : Thx a lot for the tip ..it works for me.
