### ISSUE TITLE
Wrong short date conversion for locale de? 

### ISSUE THREAD

**Issue by Smaug333** [moment/moment#5362]
in a react enviroment, I am trying to convert into a short date like this:

```
import "moment/locale/pt-br";
import moment from "moment";

  const test = moment("2019-07-23T04:32:00Z", "YYYY.MM.DD")
    .locale("en")
    .format("MMMM Do");

  console.log(test); //July 23rd
```
the english version is working as expected, the german version however is not:
```
  const test = moment("2019-07-23T04:32:00Z", "YYYY.MM.DD")
    .locale("de")
    .format("MMMM Do");

  console.log(test); //Julho 23º
```
it should be Juli 23 - Julho 23° must be some other, to me unknown language.

Where is my mistake?

Thanks for helping!

**Comment by ashsearle** [comment]
`'Julho'` is from the pt-br locale, which you showed you loaded:
```js
import "moment/locale/pt-br";
```

Do you also load the `de` locale, or did you forget?

**Comment by Smaug333** [comment]
Yes, that solved it.
Got "moment/locale/pt-br" from a tutorial which was wrong in this point. Thanks a lot!
