### ISSUE TITLE
Incorrect month diff in April 1893 with german locale

### ISSUE THREAD

**Issue by hs-rhelm** [moment/moment#5364]
```
> moment([1893, 3]).diff(moment([1893, 4]), "months");
0
```
Expected result: -1

Without truncating:
```
> moment([1893, 3]).diff(moment([1893, 4]), "months", true);
-0.9998487654320988
```

Other differences are fine:
```
> moment([1893, 4]).diff(moment([1893, 3]), "months");
1
> moment([1893, 2]).diff(moment([1893, 3]), "months");
-1
> moment([1893, 2]).diff(moment([1893, 5]), "months");
-3
```

When using .utc() it's also fine:
```
> moment.utc([1893, 3]).diff(moment.utc([1893, 4]), "months");
-1
```

I'm in Germany and apparently the Timezone was changed in April 1893 from LMT to CET:
https://www.timeanddate.com/time/zone/germany/berlin

```
> moment([1893, 3]).toString()
'Sat Apr 01 1893 00:06:32 GMT+0100'
```

However I would not expect this to affect the month difference.

My environment:
* macOS Mojave 10.14.6
* node v12.10.0
```
> (new Date()).toString()
'Mon Jan 27 2020 16:56:14 GMT+0100 (Central European Standard Time)'
> (new Date()).toLocaleString()
'1/27/2020, 4:56:14 PM'
> (new Date()).getTimezoneOffset()
-60
> moment.version
'2.24.0'
```

**Comment by marwahaha** [comment]
I think the amount of time is reduced when the time zone changed. So, it is not 1 full month, but slightly less. 

Using UTC avoids these sorts of problems, as you noticed.

Please re-open if you still have issues.
