### ISSUE TITLE
Swahili is showing 24 hour clock when I would expect a 12 hour clock (am/pm)

### ISSUE THREAD

**Issue by arambrosius** [moment/moment#5366]
**Describe the bug**
I am using the Swahili locale and it is showing a 24 hour clock. When I look around online and when I talk to people in Kenya they are expecting it to be a 12 hour clock (am/pm).

**To Reproduce**
Set your app to use Swahili locale. 
Display `moment.format('LT')`

**Expected behavior**
It should show 1:00 pm but shows 13:00.

moment v2.24.0

**Article talking about Swahili time**
http://www.localeplanet.com/icu/sw/index.html
https://en.wikiversity.org/wiki/Swahili_I/Numbers_and_Time

**Comment by Alanscut** [comment]
@arambrosius See https://momentjs.com/docs/#/displaying/format/, You can try the following code.

```javascript
console.log('pm:', moment().format('hh:mm a')); 
```

**Comment by marwahaha** [comment]
@fadsel thoughts on using a meridiem?

**Comment by fadsel** [comment]
It is just a matter of preference, In Tanzania for instance we use both formats , let me `reproduce` the issue and see where the error is , expect a PR soon

**Comment by marwahaha** [comment]
any updates @fadsel  ?

**Comment by fadsel** [comment]
Caught up with some work, will try to to squeeze in time today and submit PR , 

On a side note, it appears that `LT` is expected to show the `24 Hrs` format since it is `HH:mm` , Will check into it again later before I submit the PR , perhaps a `hh:mm a` will do

**Comment by marwahaha** [comment]
`LT` shows `hh:mm A` by default.

**Comment by fadsel** [comment]
Have a look at it now, the tests are also okay :+1:
