### ISSUE TITLE
moment.utc(date) vs moment().utc(date)

### ISSUE THREAD

**Issue by jdolearydl** [moment/moment#5367]
**Describe the bug**
`moment.utc(date)` and  `moment().utc(date)` return different dates.

**To Reproduce**
```js
moment('2020-01-01T00:00:00.000Z').toISOString();
//      returns "2020-01-01T00:00:00.000Z"
moment.utc('2020-01-01T00:00:00.000Z').toISOString();
//      returns "2020-01-01T00:00:00.000Z"
moment().utc('2020-01-01T00:00:00.000Z').toISOString();
// bug: returns "2020-01-29T14:34:54.340Z"
```

**Expected behavior**
In the docs, there is only an explanation of the form `moment.utc(date)`.  Given `moment().utc()`, I would expect `.utc(date)` to override the "current time" date created by `moment()`.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Firefox
 - Version 72.0.2

**Moment-specific environment**

* The time zone setting of the machine the code is running on: EST
* The time and date at which the code was run: EST

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
output:
```
Wed Jan 29 2020 14:42:31 GMT-0500 (Eastern Standard Time)
1/29/2020, 2:42:31 PM
300
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0 
2.24.0
```

**Comment by svltmccc** [comment]
`moment.utc` and `moment().utc` are not the same, look at these definitions:

**moment.utc**
https://github.com/moment/moment/blob/0aae7249928ae0dacad94de30d68434cabc03844/moment.d.ts#L624

**moment().utc**
https://github.com/moment/moment/blob/0aae7249928ae0dacad94de30d68434cabc03844/moment.d.ts#L447

**Comment by jdolearydl** [comment]
That's helpful, maybe we could add a blurb to the docs to that effect?  It's easily confusing for people not using typescript.

**Comment by svltmccc** [comment]
It's described by docs here:
`moment.utc`: https://momentjs.com/docs/#/parsing/utc/
`moment().utc`: https://momentjs.com/docs/#/parsing/unix-timestamp/
