### ISSUE TITLE
isValid is returning true for invalid data as well

### ISSUE THREAD

**Issue by nishantdongare** [moment/moment#5368]
**Describe the bug**
`moment('13/12/12/06/1991 12:2220:2230', 'DD/MM/YYYY HH:mm:ss', true).isValid()`
In the above code it should return false as i am giving invalid date and time. Still it is returning true.

**To Reproduce**
1. Go to this fiddle `https://jsfiddle.net/remus/rLjQx/`
2. Remove existing code.
3. Add above code.

**Expected behavior**
It should return false as date and time are invalid.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 79.0.3945.130 (Official Build) (64-bit)

* IST
* 31 January 2020 11:33:00 AM

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())  // Fri Jan 31 2020 11:35:00 GMT+0530 (India Standard Time)
console.log((new Date()).toLocaleString()) // 31/01/2020, 11:35:31
console.log((new Date()).getTimezoneOffset()) // -330
console.log(navigator.userAgent) // Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
console.log(moment.version) // 2.2.1
```

**Comment by ashsearle** [comment]
Looks OK to me with the latest version (2.24.0)

Can you update?

**Comment by wboka** [comment]
the following returns a valid date in MomentJS 2.24.0:

## code

```js
let dateTime = "BAD 123 - 1date";
let isAValidDate = moment(dateTime, "YYYY-MM-DD HH:mm:ss").isValid();

console.log(dateTime);
console.log(isAValidDate);
console.log(moment.version);
```

## working example

https://jsfiddle.net/fvmg23pu/3/

**Comment by ashsearle** [comment]
@wboka Use [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/):

```js
let dateTime = "BAD 123 - 1date";
let isAValidDate = moment(dateTime, "YYYY-MM-DD HH:mm:ss", true).isValid();
console.log(isAValidDate); // false
```

**Comment by wboka** [comment]
Perfect! Thanks!

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
