### ISSUE TITLE
moment().fromNow() "a few seconds ago"

### ISSUE THREAD

**Issue by renansantos** [moment/moment#537]
moment().fromNow() is returning "a few seconds ago".
Why not "just now" ?

**Comment by kiki-le-singe** [comment]
@timrwood thanks for your tips

**Comment by con-cso** [comment]
it's actually `moment.langData('en')._relativeTime.s = "just now"` if you want to replace said string.

I am humanizing dates (without time information), so changing _relativeTime.s to the equivalent of "today" for all locales was my solution.

**Comment by puneet94** [comment]
fromNow(true) returns "2 minutes ago","2 hours ago","a few seconds ago".
 How can you do something like "2m" or "2h" or "2s" or "2d"?.

**Comment by stoufa88** [comment]
@puneet94 You can update your locale strings with https://momentjs.com/docs/#/customization/relative-time/

**Comment by richardszalay** [comment]
FWIW, I was able to apply "just now" using 2.12.0 by specifying a function for `past`:

```js
moment.updateLocale('en', {
    relativeTime : {
        past: function(input) {
          return input === 'just now'
            ? input
            : input + ' ago'
        },
        s  : 'just now',
        future: "in %s",
        ss : '%d seconds',
        m:  "a minute",
        mm: "%d minutes",
        h:  "an hour",
        hh: "%d hours",
        d:  "a day",
        dd: "%d days",
        M:  "a month",
        MM: "%d months",
        y:  "a year",
        yy: "%d years"
    }
});
```

**Comment by chohonest** [comment]
@richardszalay what date format are you using with this and how do you apply this? 
I have a date string time = 1560955417474,
and want to display it within a text tag
`<Text>{time}</Text>`

**Comment by aakash-mohan** [comment]
moment().fromNow() is returning "in 2 minutes".

Shouldn't it be "2 minutes ago"?
