### ISSUE TITLE
Incorrect first day of week for Indonesian locale

### ISSUE THREAD

**Issue by kstinson14** [moment/moment#5370]
Currently, the [Indonesian locale](https://github.com/moment/moment/blob/develop/src/locale/id.js#L71) has Monday listed as the first calendar day of the week.  My i10n team has said that this is incorrect, and Sunday should be the first day instead.  

Searching for the correct answer gave me some mixed results, but I found that the [Unicode Common Locale Data Repository](https://github.com/unicode-org/cldr/blob/3fb31016d122bbd4d001b185fb2069f5e9c74dda/common/supplemental/supplementalData.xml#L4712) supports the case for using Sunday instead of Monday.  Windows also follows this configuration.  When selecting Indonesian as your locale on Windows 10, Sunday is the default option for first day of the week.

![Screen Shot 2020-02-03 at 10 58 12 AM](https://user-images.githubusercontent.com/17748358/73668610-1aeb4b80-4674-11ea-9aee-8bad446bf21f.png)

I could submit a PR to change this if desired.

@tyok

**Comment by tyok** [comment]
Both can be used as the first day. In the popular children's song "nama-nama hari" it is Monday while in the official dictionary it is Sunday (https://kbbi.kemdikbud.go.id/entri/Minggu).

I think Sunday-first is more popular in the digital context, since that's the behavior in Windows and Android Calendar.

**Comment by kstinson14** [comment]
Ah, ok.  Do you think it would make sense to change here then?

**Comment by tyok** [comment]
Sorry for not being clear, yeah I think it's ok to change it.

**Comment by mantinone** [comment]
Hi, I'm trying to get into doing regular open source contributions and am looking for issues to pick up.  May I claim this issue?

**Comment by kstinson14** [comment]
@mantinone Sounds good, I'll hold off on PR if you'd like to grab this one 👍

**Comment by mantinone** [comment]
@kstinson14 
Thank you!

I thought this would be a pretty trivial change, but there's more to this than I thought, and I've got questions about what changes need to be made. (and maybe I should tag @tyok here.).  It seems that the doy (the day in January that marks the first week of the year) needs to be changed as well as the first day of the week, and I'm not sure what it should be changed to and what the tests should look like.

The example failing test Grunt gives me is `weeks year starting sunday formatted
Jan  8 2012 should be week 2`

```Actual value:
3 03 3
Expected value:
2 02 2```

Previously `src/locale/id.js` had `dow: 1 //Monday` and `doy: 7 //week containing January 7th`.
I did a search for all locales with `dow: 0 //Sunday` and found that none of them have `doy: 7`.    
`doy: 6` is fairly common, though.  So should this be changed to Jan 6th as well?

**Comment by kstinson14** [comment]
@mantinone Sorry for the delayed response.

Yeah, I think this is a @tyok question.  I'm not sure what decides the `doy` value in this locale. ([here](https://github.com/moment/momentjs.com/issues/279) is an issue talking a bit about how it's determined) but I think he would know.

**Comment by mantinone** [comment]
Perhaps it's a good time to ping @tyok again?

Or maybe another contributor, since this seems like a more general question about how moment defines First Week of the year.  I'm not sure who to tag, though.  @timrwood maybe?

**Comment by mantinone** [comment]
Does anyone know who would be a good person to ask about this question, or where there's documentation talking about it?

Should I just make a guess and do a pull request?  The changes are fairly straightforward.  I just don't know precisely what changes to make.

**Comment by marwahaha** [comment]
Thanks for offering to make this change.

Need to change src/locale/id.js and associated tests.

Docs for this change are at
https://momentjs.com/docs/#/customization/dow-doy/

Probably, (dow, doy) go to (0, 6) based on formula listed in docs.

You can ping me if you need help.

**Comment by mantinone** [comment]
Thank you for pointing out the part in the docs that I missed that explains this!  
The formula is still confusing to me because I'm not sure how they're determining what `janX` is.

I went ahead and submitted the PR with doy as 6.
