### ISSUE TITLE
Can not get whole moment object

### ISSUE THREAD

**Issue by makiBaraba** [moment/moment#5371]
Hi, I am currently developing one chrome browser extension and I am using moment.js.

My problem is, when I set the object property to chrome.storage with Chrome API as moment object, when I want to retrieve it, it comes without _d property and I can not get DateTime from it. Check it out.

`let now = moment();
    let endDate = moment().add(30, 'days');

    console.log("Now ", now);
    console.log('Enddate ', endDate);

    chrome.storage.local.set({
      startDate: now,
      endDate: endDate,
      remainingCredits: 20,
    }, () => {
      chrome.storage.local.get(null, (result) => {
        console.log("Now after", result.startDate);
        console.log("Enddate after", result.endDate);
        resolve(result);
      });
    });`
![Screenshot_1](https://user-images.githubusercontent.com/27204757/73687625-c0c9a500-46ca-11ea-9980-36434fc9b4e1.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/27204757/73687626-c1623b80-46ca-11ea-8e77-3da5edb12cae.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/27204757/73687627-c1623b80-46ca-11ea-8e63-0a7f34b4e0f7.jpg)

**Comment by Beamanator** [comment]
Have you tried just storing the `moment` dates as strings, then converting them back to `moment` objects when you retrieve the data? Example:

```javascript
let now = moment();
let endDate = moment().add(30, 'days');

chrome.storage.local.set({
  startDate: now.toString(),
  endDate: endDate.toString(),
}, () => {
  chrome.storage.local.get(null, (result) => {
    console.log("Now after", moment(result.startDate));
    console.log("Enddate after", moment(result.endDate));
    resolve(result);
  });
});`
```

**Comment by ashsearle** [comment]
I'd avoid `toString()`.  Use `toJSON()` or `toISOString()` to store as a string, or `valueOf()` to store as unix timestamp in milliseconds.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
