### ISSUE TITLE
Inconsistent date time when creating date time with timezone which contain "AM" or "PM"

### ISSUE THREAD

**Issue by QuanTran91** [moment/moment#5372]
Hi all, I have an issue when using moment.tz function

moment.tz('2019-01-01 **06:30:00**','Pacific/Honolulu').toISOString() return "019-01-01T**16:30:00**.000Z"
but 
moment.tz('2019-01-01 **06:30:00 AM**','Pacific/Honolulu').toISOString() return "2019-01-01T**06:30:00**.000Z"

Do you know why we have this inconsistency here?

Thanks.

**Comment by ashsearle** [comment]
Check your console, you should see a deprecation warning message like this:

> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

If you want to parse that date format reliably, you need to tell moment what format the string is in.  Something like:

```js
moment.tz('2019-01-01 06:30:00 AM','YYYY-MM-DD HH:mm:ss A', true, 'Pacific/Honolulu')
```
