### ISSUE TITLE
[Error] Different day from what selected on GUI

### ISSUE THREAD

**Issue by ghassen1khalil** [moment/moment#5374]
**[Context]**
I'm using a company-private Angular UI components (similar to [VMWare Clarity](https://github.com/vmware/clarity) lib) and I'm using a `DatePicker `component that's relying on Moment.js as a `DateAdapter`.

**[Actual]**
When I select a day on my DatePicker component (eg. 11/02/2020) and I try to print it (in real case send it to backend) I get an incorrect date `2020-02-10T23:00:00Z`

**[Expected]** 
Get the right day wich selected on the GUI `2020-02-11`

**Comment by troyamelotte** [comment]
@ghassen1khalil We're noticing something similar. Are you getting the same issue on older versions of chrome or firefox? For us endOf doesn't work correctly in the newest chrome v80.0.3987.87. It does the end of the day prior.

**Comment by BenGrabowski** [comment]
@ghassen1khalil I'm experiencing a similar issue with an app I have deployed using Zeit. The dates are fine when I run my app locally, but when I deploy it, the dates are showing as 1 day prior.

**Comment by JuanDavidSolano** [comment]
@ghassen1khalil Hi, the date is different because the **timezone**, moment has an offset you can read it in the [docs](https://momentjs.com/guides/). I fix it using `moment.utc(date)` that removes the offset for me.

**Comment by marwahaha** [comment]
Thanks @JuanDavidSolano 
Please re-open if you still have issues.
