### ISSUE TITLE
moment('2019-01-21T00:00:00.000Z').isUtc() === false

### ISSUE THREAD

**Issue by ggrnd0** [moment/moment#5375]
**Describe the bug**
moment('2019-01-21T00:00:00Z').isUtc() === false
moment('2019-01-21T00:00:00.000Z').isUtc() === false

**To Reproduce**
moment('2019-01-21T00:00:00Z').isUtc() === false
moment('2019-01-21T00:00:00.000Z').isUtc() === false

**Expected behavior**
moment('2019-01-21T00:00:00Z').isUtc() === true
moment('2019-01-21T00:00:00.000Z').isUtc() === true

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Opera
 - Version 66.0.3515.36

**Moment-specific environment**

* The time zone setting of the machine the code is running on 
UTC+3:00 Moscow
* The time and date at which the code was run
Tue Feb 11 2020 16:26:23 GMT+0300 (Moscow Standard Time)
* Other libraries in use (TypeScript, Immutable.js, etc)
no

Please run the following code in your environment and include the output:
Tue Feb 11 2020 16:26:23 GMT+0300 (Moscow Standard Time)
 2/11/2020, 4:26:23 PM
-180
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36 OPR/66.0.3515.36
2.24.0

**Additional context**

**Comment by ashsearle** [comment]
See https://github.com/moment/moment/issues/3687#issuecomment-269555870

**Comment by marwahaha** [comment]
Thanks @ashsearle 
Please re-open if you still have issues.
