### ISSUE TITLE
Is "moment" & "moment.utc" is same?

### ISSUE THREAD

**Issue by mudivili** [moment/moment#5379]
In browser console of `https://momentjs.com/`, when I run `moment().diff(moment.utc(), 'milliseconds')`, I get `0` as output.

Does that mean `moment()` & `moment.utc()` is same? Or what is the actual difference?

**Comment by Alanscut** [comment]
@mudivili See https://momentjs.com/docs/#/parsing/utc/.

**Comment by marwahaha** [comment]
See the `Please Read` section of 
https://momentjs.com/docs/#/parsing/
