### ISSUE TITLE
Calculations on leap years

### ISSUE THREAD

**Issue by matiasmicheletto** [moment/moment#5389]
I'm not sure this is a bug or an expected behaviour, but I think the result of the following procedure is wrong:

```javascript
var today = moment("29/02/2020", "DD/MM/YYYY");
var withinAYear = today.add(1,'year');
var isToday = withinAYear.subtract(1,'year').format("DD/MM/YYYY");
console.log(isToday);
```
It displays "28/02/2020" when it should be "29/02/2020", that is, "today".

This single line instruction should display the initial argument:
```javascript
moment("29/02/2020", "DD/MM/YYYY").add(1,'year').subtract(1,'year').format("DD/MM/YYYY");
```
Maybe the definition of "within a year" is ambiguous for leap years, because you don't know whether to add 365 days or just increment in 1 the number of the year.

**Comment by ashsearle** [comment]
Expected behaviour: `moment` doesn't have a memory.

This 'problem' is the same as adding then subtracting 1 month:
```js
moment("31/03/2020", "DD/MM/YYYY")
  .add(1, "month")
  .subtract(1, "month")
  .format("DD/MM/YYYY");
// Result: 30/03/2020, not 31/03/2020
```

**Comment by matiasmicheletto** [comment]
Thanks for your answer @ashsearle. There is indeed an issue with the definition of "adding n years (or n months) to a given date", as the years (months) duration is not constant. The question that users should ask themselves is: Should the number of the year (month) be increased by n or should we add n*365 (n*30) days to the current date? The last operation, unlike the first, is reversible.
