### ISSUE TITLE
Links are flip flopped on the docs

### ISSUE THREAD

**Issue by toymachiner62** [moment/moment#5393]
I think this links are flip flopped on the docs.

https://momentjs.com/docs/#/manipulating/max/

![image](https://user-images.githubusercontent.com/485782/75052679-9a12b900-5495-11ea-9c99-a1d5215da3e3.png)

**Comment by marwahaha** [comment]
Thanks for opening this request @toymachiner62 

Yes, this is intentional.
> Limits the moment to a maximum of another moment value. So a.max(b) is the same as a = moment.min(a, b) (note that max is converted to min).
