### ISSUE TITLE
Unofficial Documentation to help new contributors

### ISSUE THREAD

**Issue by thepenguinco** [moment/moment#5395]
[Unofficial Documentation Guide](https://demo3.gethyperdoc.com/?folder=vscode-remote%3A%2Fhome%2Fcoder%2Fmoment)

We found that it was difficult for people who wanted to contribute to open source to actually start 
contributing since searching and finding relevant existing documentation related to the code itself was tough (which is important for new contributors, since they don't really know the codebase).

We built Hyperdoc, a documentation tool to help solve this problem and used it to write a code walkthrough guide for Moment.js to show how it works.

You can use the links in Hyperdoc to step through the guide.

**Comment by marwahaha** [comment]
Thanks @thepenguinco , unfortunately the link timed out.
