### ISSUE TITLE
moment add year is showing a wrong date on 29 Feb.

### ISSUE THREAD

**Issue by droidwizard** [moment/moment#5396]
I have been created a format date with add year(+543) and selected date at 29 Feb then result date is 28 Fab. see more code below.
`
moment.locale('th');
moment('2020-02-29').add(543, 'years').format('LL');
`

The result is 28 กุมภาพันธ์ 2563

**Comment by ashsearle** [comment]
What date did you expect?

**Comment by droidwizard** [comment]
> What date did you expect?

Correct date is **29 กุมภาพันธ์ 2563**

**Comment by ashsearle** [comment]
@droidwizard You're going to have to show me your calendar.  Pretty sure that in a Gregorian calendar, the year 2563 isn't a leap year, and therefore 29th February (กุมภาพันธ์) does not exist.

**Comment by marwahaha** [comment]
Thanks @ashsearle
Please re-open if things are unclear!
