### ISSUE TITLE
Use relativeTimeRounding function also in moment.diff

### ISSUE THREAD

**Issue by frx08** [moment/moment#5401]
moment.diff is always using absFloor function to round results.

it would be nice to be able to set the rounding function like relativeTimeRounding for duration

I see that defaults for duration relativeTimeRounding (Math.floor) and moment.diff (absFloor) are different so the function cannot be reused

**Comment by marwahaha** [comment]
Hi, thanks for this request.

I don't think we have to implement this in Moment.js; for example, you can use the "asFloat" argument, then round it yourself.
```
moment().diff(moment([2007, 0, 29]), 'days')
// 5000
moment().diff(moment([2007, 0, 29]), 'days', true)
// 5000.210074699074
```

There may not be many more changes to Moment.js; see https://momentjs.com/docs/#/-project-status/ .

Best of luck!
