### ISSUE TITLE
moment("1111.11", 'DD.MM.YYYY').isValid(); // return True

### ISSUE THREAD

**Issue by kostarev** [moment/moment#5402]
This code
moment("1111.11", 'DD.MM.YYYY').isValid();
return true, but should return false

**Comment by Michael1993** [comment]
Moment's parser is very forgiving, and this can lead to undesired/unexpected behavior.

For example, the following behavior can be observed:

```
moment('2016 is a date', 'YYYY-MM-DD').isValid() //true, 2016 was matched
```

As of version 2.3.0, you may specify a boolean for the last argument to make Moment use strict parsing. Strict parsing requires that the format and input match exactly, including delimeters.

```
moment('It is 2012-05-25', 'YYYY-MM-DD').isValid();       // true
moment('It is 2012-05-25', 'YYYY-MM-DD', true).isValid(); // false
moment('2012-05-25',       'YYYY-MM-DD', true).isValid(); // true
moment('2012.05.25',       'YYYY-MM-DD', true).isValid(); // false
```

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
