### ISSUE TITLE
Still maintained? Should we consider Luxon?

### ISSUE THREAD

**Issue by KayakinKoder** [moment/moment#5405]
Hi folks, this looks like a great library, thank you for it.

Please don't take this the wrong way, but we're wondering about the future of moment. Based on the previous commit being ~8 months ago, most recent release over a year ago, and no commits on the v3 branch since 2017, it seems like long term plans are up in the air.

Thanks again

**Comment by Yohandah** [comment]
I recommend date-fns https://github.com/date-fns/date-fns#readme

It is lighter than moment, supports tree shaking, and still active.

If you're looking for something more familiar with moment you have DayJS which is really light https://github.com/iamkun/dayjs

**Comment by xxyuk** [comment]
I would recommend Day.js https://github.com/iamkun/dayjs.

It's just exactly the same as moment.js but only 2KB!!!

**Comment by marwahaha** [comment]
Hiya, thanks for opening this.

Moment is a mature library. There are many, many projects that depend on this codebase.
As a result, updates are not as frequent as rapidly-developing libraries.
That does not mean the code will lose correctness over time.
Of course, there are several alternatives to Moment (some mentioned here). Please use what best fits your needs.

**Comment by tukusejssirs** [comment]
@marwahaha, Moment might be mature, but it has many (tens to hundreds) unfixed bugs (according to the [Moment issues](https://github.com/moment/moment/issues).

>  That does not mean the code will lose correctness over time.

That statement might not be always true as the grammer of any language might change over the years. Just look at the German grammar. I don't say that it happens frequently, but it happens.

@xxyuk, indeed, `dayjs` looks much better from the size point of view, but currently its tests are implemented as a comparison of its output with the output of Moment, i.e. when Moment has a bug, `dayjs` has the very same bug too. Actually, this is how I have found the #5408 issue (you can follow the iamkun/dayjs#831 issue). And the issue in there I have found via [romcal](romcal/romcal#186).

All I want is a correct output in any case. I know that English grammar is much different (and easier) that the Slovak one, but that must not be an excuse for keeping bugs as known issues.
