### ISSUE TITLE
Parsing datetimes in forgiving mode cares about delimiters if it has other parsing options.

### ISSUE THREAD

**Issue by AncientSwordRage** [moment/moment#5406]
**Describe the bug**
Parsing formats can care about delimiters if a certain array of allowed formats are used.

**To Reproduce**
`moment('24/12/2019 09:15:00', ["DD MMM YYYY hh:mm:ss", "DD MM YYYY hh:mm:ss"])`
Returns "Sat Jan 24 2009 15:00:00" because it matches the format with MMM without delimiters. (incorrect)
`moment('24 12 2019 09:15:00', ["DD MMM YYYY hh:mm:ss", "DD MM YYYY hh:mm:ss"])`
Returns "Tue Dec 24 2019 09:15:00" because it matches the format with MM regardless of delimiters. (correct)

**Expected behavior**
`moment('24/12/2019 09:15:00', ["DD MMM YYYY hh:mm:ss", "DD MM YYYY hh:mm:ss"])`
Returns "Tue Dec 24 2019 09:15:00" because it matches the format with MM regardless of delimiters.

**Desktop (please complete the following information):**
 - OS: Linux/Windows 10
 - Browser: Node/Chrome

**Moment-specific environment**

* The time zone setting of the machine the code is running on: GMT
* The time and date at which the code was run: N/A
* Other libraries in use (TypeScript, Immutable.js, etc): N/A

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()) - N/A
console.log((new Date()).toLocaleString()) - N/A
console.log((new Date()).getTimezoneOffset()) - 0
console.log(moment.version) - 2.24.0
```

**Additional context**

**Comment by marwahaha** [comment]
Thanks for opening this request.

I'm not sure I see this as a bug. If you want to be careful about delimiters, you can add them in your allowed formats.

**Comment by AncientSwordRage** [comment]
What confused me was the guide says:

> The parser ignores non-alphanumeric characters, so both of the following will return the same thing.
> `moment("12-25-1995", "MM-DD-YYYY");`
> `moment("12/25/1995", "MM-DD-YYYY");`

I was assuming that the space was non-alphanumeric?  ¯\_(ツ)_/¯

I was using this in an environment where I can't enforce all the delimiters a user inputs, so I was really happy moment was smart enough to parse this properly. 

Can the website be updated or this re-opened to reconsider this choice?

**Comment by marwahaha** [comment]
If you like, you can update the documentation at 
https://github.com/moment/momentjs.com/

The space is likely throwing off the parsing:
```
moment('24/12/2019 09:15:00', ["DD MM YYYY hh:mm:ss"]).format()
> "2015-09-24T00:00:00-07:00"
```

**Comment by AncientSwordRage** [comment]
It looks like its the space and the time is what throws it off:

```js
const wtime = moment('24/12/2019 09:15:00', ["DD MM YYYY hh:mm:ss"]);
const swtime = moment('24 12 2019 09:15:00', ["DD MM YYYY hh:mm:ss"]);
const wotime = moment('24/12/2019', ["DD MM YYYY"]);
console.log(`${wtime},\n${wotime},\n${swtime}`);
//Thu Sep 24 2015 00:00:00 GMT+0100,
//Tue Dec 24 2019 00:00:00 GMT+0000,
//Tue Dec 24 2019 09:15:00 GMT+0000
```

No longer sure if this is a documentation problem or a parsing problem?

Why does it try to fill in the time part and not the date part?
