### ISSUE TITLE
moment(1568959200000).format("YYYY-MM-DD HH:mm") not right

### ISSUE THREAD

**Issue by sunny635533** [moment/moment#5407]
**Describe the bug**
when i use :
moment(1568959200000).format("YYYY-MM-DD HH:mm") ,
（1568959200000 is millisecond）i get the result  is  "2019-09-20 06:00" , it is not correct.  it should be " 2019-09-20 14:00 " . i dont know why it is 2019-09-20 06:00???

**Expected behavior**
i hope use moment's method can get " 2019-09-20 14:00 ".

**Moment-specific environment**
version:  moment@2.24.0

* The time zone setting of the machine the code is running on 
   Beijing
* The time and date at which the code was run 
   moment(1568959200000).format("YYYY-MM-DD HH:mm")
* Other libraries in use (TypeScript, Immutable.js, etc) 👍 
   TypeScript with react-native
Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())  //  Wed Mar 11 2020 09:34:36 GMT+0800 (CST)
console.log((new Date()).toLocaleString())  //  3/11/2020, 9:34:36 AM
console.log((new Date()).getTimezoneOffset()) // -480
console.log(navigator.userAgent) // undefined
console.log(moment.version) // 2.24.0
```

**Additional context**
no.

**Comment by Alanscut** [comment]
@sunny635533 I get the result is  `2019-09-20 14:00`. version: moment@2.24.0
## Moment-specific environment
* Other libraries in use (TypeScript, React, etc) 

![issue_5407](https://user-images.githubusercontent.com/21104054/79625896-b44bd900-815e-11ea-80ba-fa4917670540.PNG)

**Comment by marwahaha** [comment]
Thanks @Alanscut 
Please re-open if you still have issues.

**Comment by sunny635533** [comment]
> @sunny635533 I get the result is `2019-09-20 14:00`,You probably used UTC (instead of the original moment time) to display the moment.
> 
> ## Moment-specific environment
> * Other libraries in use (TypeScript, React, etc)
> 
> ```js
>  console.log('时间：',  moment(1568959200000).format("YYYY-MM-DD HH:mm")) // 2019-09-20 14:00
>  console.log('时间UTC：',  moment(1568959200000).utc().format("YYYY-MM-DD HH:mm")) // 2019-09-20 06:00
> ```
> 
> ![issue_5407](https://user-images.githubusercontent.com/21104054/79626325-eca0e680-8161-11ea-85b3-997dcbad5f69.PNG)

Thanks！Now i know why，thank very much！
