### ISSUE TITLE
Need date format support for 2013-02-08 09:30:26+07 

### ISSUE THREAD

**Issue by priyagnanaprakasam** [moment/moment#5412]
To be able to format zone for +-HH:00

**Comment by Alanscut** [comment]
@priyagnanaprakasam Do you need this format? You can also customize the format, which is a very cool feature provided by `moment`.
https://momentjs.com/docs/#/displaying/format/
```javascript
console.log(moment().format('YYYY-MM-DD HH:mm:ss+HH')) // 2020-04-18 09:27:17+09
```

**Comment by marwahaha** [comment]
Thanks @Alanscut 
Please re-open if you still have issues.
