### ISSUE TITLE
Incorrect number of days in the leap year

### ISSUE THREAD

**Issue by rezerford** [moment/moment#5413]
**Describe the bug**
I am not sure that it is the bug but anyway i will describe you my issue. First of all i got the date 1 month ago from now using subtract method. It works well without any issues. Then i tried getting number of days between one month ago and nowdays. I noticed if I overlaped the February when applying diff method it returned me incorrect number of days in this month. As fas as you understand the leap year has 29 days in February instead of 28 in a non-leap year. Might be i used your library incorrectly or i am not aware something but i think in my opinion i expect right number of days in February and in a year in the leap year when i use diff method.
Thanks for your assistant.

**Expected behavior**
I expect 29 days and 366 days in the leap year when i use diff method after applying subtract method subtract(1, 'month') or subtract(1, 'year').

**Comment by Sanyusha** [comment]
I believe that I see the same issue. The bold expression returns clearly a wrong result.

_moment('2020-03-28').subtract(1, 'month').format('YYYY-MM-DD')
"2020-02-28"
moment('2020-03-28').subtract(1, 'month').year('2020').format('YYYY-MM-DD')
"2020-02-28"
moment('2020-03-29').subtract(1, 'month').format('YYYY-MM-DD')
"2020-02-29"
**moment('2020-03-29').subtract(1, 'month').year('2020').format('YYYY-MM-DD')
"2020-02-28"**_

**Comment by marwahaha** [comment]
Hi! Thanks for filing this issue! Unfortunately, I can't reproduce this. Could you provide any other information? What time zone are you in?

**Comment by marwahaha** [comment]
Sorry you had an issue.
Please re-open if you still have concerns.
