### ISSUE TITLE
moment.calendar has wrong translate in [thisWeek] by 'zh-cn'

### ISSUE THREAD

**Issue by uu109** [moment/moment#5414]
Today is Thursday is my location when I write this.

```
moment.local('zh-cn');
moment().add(2,'days').calendar();  // 下星期六11:11"
```
It is wrong text. The "下星期六" meaning is next week Saturday, but it should be this week Saturday, for example ”本星期六“.

**Comment by marwahaha** [comment]
could be related to https://github.com/moment/moment/issues/4097
