### ISSUE TITLE
PL locale - wrong day name returned as the first day of week

### ISSUE THREAD

**Issue by sossilica** [moment/moment#5417]
Hi,

I just noticed that when using 'pl' as locale, moment returns 'niedziela' (Sunday) as the first day of the week when correctly this should be 'poniedziałek' (Monday).
You can also find proof on wikipedia: https://en.wikipedia.org/wiki/Names_of_the_days_of_the_week#Days_numbered_from_Monday

**To Reproduce** and **Expected behavior**
```
test("beginning of week", () => {
  expect(
    moment()
      .locale("pl")
      .day(0)
      .format("dddd")
  ).toBe("poniedziałek");
});
```

**Desktop (please complete the following information):** and **Moment-specific environment**
- OS: iOS; Browser: chrome;
- my timezone: GMT +1
- I'm using typescript

You asked for some console logging. I added the output results as comments below:
```
console.log((new Date()).toString()) \\Tue Mar 24 2020 12:28:35 GMT+0100 (czas środkowoeuropejski standardowy)
console.log((new Date()).toLocaleString()) \\24.03.2020, 12:28:35
console.log((new Date()).getTimezoneOffset()) \\ -60
console.log(navigator.userAgent) \\Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.12.0
console.log(moment.version) \\2.24.0
```

**Comment by krzysztofrewak** [comment]
You can always reconfigure your moment for rearraning days of week:

```js
moment.locale('en', {
    week: {
        dow: 6
    }
})
```

**Comment by marwahaha** [comment]
thoughts @evoL ?

**Comment by evoL** [comment]
Hello!
In Moment, numbers representing days of week are always fixed no matter the locale — Sunday is 0, Monday is 1 etc. [The docs for `moment().day(Number)`](https://momentjs.com/docs/#/get-set/day/) describe this.

This means that your example always asks for the translated name of Sunday and therefore works as expected. To return the locale-specific day of week, use [`moment().startOf('week')`](https://momentjs.com/docs/#/manipulating/start-of/):

```js
moment().locale('pl').startOf('week').format('dddd')
```

The above returns "poniedziałek" (Monday), as expected.
