### ISSUE TITLE
isValid returns true if matched against ISO_8601

### ISSUE THREAD

**Issue by AckermannM** [moment/moment#5422]
**Describe the bug**
`moment("4173154", moment.ISO_8601, true).isValid()` returns `true`

**Expected behavior**
Validation against ISO_8601 should return false, when just an integer is provided.

**Environment:**
 - Node.js
 - Version 13.11.0

**Moment-specific environment**

* The time zone setting of the machine the code is running on: UTC+1
* The time and date at which the code was run: 2020-03-27T10:40:02.213Z
* Other libraries in use: none

Please run the following code in your environment and include the output:
```
Fri Mar 27 2020 11:41:19 GMT+0100 (Central European Standard Time)
3/27/2020, 11:41:19 AM
-60
2.24.0
```

**Comment by ashsearle** [comment]
That's not 'just an integer', it's a string matching the "YYYYDDD" [ordinal date](https://en.wikipedia.org/wiki/Ordinal_date) format.

**Comment by TimBeyer** [comment]
`0000` is also passing, but does not seem to be a valid ordinal date.  
Looks like a bug to me.

**Comment by ashsearle** [comment]
@TimBeyer That's a valid year-only date.

**Comment by AckermannM** [comment]
The problem here is just that `moment.ISO_8601` is too vague of a matcher. My solution was to just validate against a string thats specific enough.

**Comment by TimBeyer** [comment]
I see. In any case, this should have probably been changed on a major version bump.
This caused a lot of test failures all over the place for us relying on the previous behavior.
