### ISSUE TITLE
moment locale 'nl-be' format LT not showing correct time

### ISSUE THREAD

**Issue by Sireini** [moment/moment#5423]
**Describe the bug**
I am trying to show the created time of some record. I was trying it like this: moment().locale("nl-be").format("LT") this outputs me GMT time and not GMT +1

**Expected behavior**
It should output a time of GMT+1

**Comment by Alanscut** [comment]
@Sireini  If you want to get the time in different time zones, you should use `timezone`.I hope I understand your purpose correctly.
https://momentjs.com/timezone/

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
