### ISSUE TITLE
Strange add 'minutes' behaviour connected to summer/winter hours shift

### ISSUE THREAD

**Issue by BotanMan** [moment/moment#5424]
**Describe the bug**
Strange add(X, 'm') behaviour

**To Reproduce**
`moment().startOf('day').format('HH:mm')` returns `00:00`
`moment().startOf('day').add(600, 'm').format('HH:mm')` returns `11:00` in CET +1
while it returns `10:00` in +3 timezone

**Expected behavior**
Consisten behaviour

**Screenshots**
**Moscow Time (-180)**
![image](https://user-images.githubusercontent.com/1064923/77844920-cd3e1b80-71aa-11ea-8af0-896a2edda7cb.png)
**CET (-120)**
![image](https://user-images.githubusercontent.com/1064923/77844436-15f3d580-71a7-11ea-9393-4146e0e2c862.png)

**Moment-specific environment**
* The time zone setting of the machine the code is running on (tried in 2 timezones -180 and -120)
* The time and date at which the code was run (29 of March, 11:22 Moscow)

Please run the following code in your environment and include the output:
![image](https://user-images.githubusercontent.com/1064923/77844468-797e0300-71a7-11ea-94ae-c6d7ff71ea10.png)
![image](https://user-images.githubusercontent.com/1064923/77844451-59e6da80-71a7-11ea-9611-265462c14023.png)

**Comment by ashsearle** [comment]
That's expected behaviour.

Clocks went forward 1-hour, changing from CET to CEST at 02:00 on Sun March 29th 2020.

**Comment by BotanMan** [comment]
@ashsearle thanks!
What us the possible solution?
Using `proper timezone` or `moment.utc`?

**Comment by ashsearle** [comment]
What's the problem?

If you add 1 minute to 01:59, you get to 03:00 instead of 02:00 (on Sun 29th March), because the local timezone changes from CET to CEST.

That's the correct behaviour.

Why do you want different behaviour?

**Comment by BotanMan** [comment]
@ashsearle 
I need not a different behaviour.

I think it's more about use case. 

In my case I need to get 10:00 all the time I add 600 minutes to the beginning of the day because it has no connection to timezone, it's time of the shop to be opened.

**Comment by ashsearle** [comment]
Instead of:
```js
moment().startOf('day').add(600, 'm').format('HH:mm');
```

try:
```js
moment().hour(10).startOf('hour').format('HH:mm');
```

**Comment by marwahaha** [comment]
Thanks @ashsearle 
Please re-open if you still have issues.
