### ISSUE TITLE
Moment chaining is giving different results for Asia/Singapore Timezone

### ISSUE THREAD

**Issue by theajr** [moment/moment#5425]
**Describe the bug**
I am using moment 2.8.x version in production but this issue is reproducible in current version as well.

Here I am trying 2 ways to create and format a moment object for 1933, Jan 1st.
- If we construct a moment object with ```moment.tz([1933,0,1], "Asia/Singapore")``` and format with ```DD/MM/YYYY``` it's changing the date to ```1932, Dec, 31```. 
- If we construct a moment object with ``` moment([1933, 0,1]).tz("Asia/Singapore")``` and format it with ```DD/MM/YYYY``` it's working fine.

**To Reproduce**
1. Go to https://momentjs.com/docs/
2. Open developer tools and console
3. Execute the above code snippets(same shown in the screenshot)
4. See the behavioral difference.

**Expected behavior**
The date should not be changed. I guess the chaining of the moment may be taking some kind of precedence or something.

**Screenshots**
<img width="495" alt="Screenshot 2020-03-30 at 8 40 37 AM" src="https://user-images.githubusercontent.com/11477078/77871616-4f3d4b80-7262-11ea-816d-96eb74984418.png">

**Desktop (please complete the following information):**
 - OS: **Mac/Windows**
 - Browser **Chrome**
 - Version  **2.8.x to 2.24.0 (current)**

* The time zone setting of the machine the code is running on : **Asia/Calcutta**
* The time and date at which the code was run: **March 30, 2020, 8:30 AM IST**
* Other libraries in use (TypeScript, Immutable.js, etc): None

<img width="858" alt="Screenshot 2020-03-30 at 8 44 14 AM" src="https://user-images.githubusercontent.com/11477078/77871803-d8548280-7262-11ea-983b-44cffe33372e.png">

**Comment by marvec** [comment]
I believe that we hit the same hidden issue. With moment.js version 2.24.0.

`   const f = "YYYY-MM-DD";  
  const fd = "2019-04-17";
  const fs = moment(fd, f).toISOString();
  console.log(fs);
  const fl = moment(fs, f).format();
  console.log(fl);`

When running in CEST timezone (+0200), it produces:
`2019-04-16T22:00:00.000Z
2019-04-16T00:00:00+02:00`

The second line should read: `2019-04-17T00:00:00+02:00`

Play with it here: https://codepen.io/marvec/pen/mdJZPQj

**Comment by marwahaha** [comment]
Try using `moment.utc`:
https://momentjs.com/docs/#/parsing/

Does that help?

**Comment by marwahaha** [comment]
Looks like this timezone had offset +0700 for 1932 and +0720 for 1933.
At the boundary, it is supposed to use the 1933 offset but refers to a time in 1932, so the display instead shows the 1932 offset.

I think it's a bug, but not an unreasonable thing for Moment.js to have.
We would look at a PR for this.

Docs might need an update:

https://momentjs.com/timezone/docs/#/using-timezones/parsing-in-zone
https://momentjs.com/timezone/docs/#/using-timezones/converting-to-zone/

**Comment by theajr** [comment]
> Try using `moment.utc`:
> https://momentjs.com/docs/#/parsing/
> 
> Does that help?

I just passed `Date.UTC(1933, 0, 1)` object to moment, it fixed the issue. I guess `moment.utc` could work, but I didn't try.
