### ISSUE TITLE
moment('1_/__/____', 'MM/DD/YYYY').isValid() returns true

### ISSUE THREAD

**Issue by dmitriyaa** [moment/moment#5430]
Hi, I think the title pretty much explains the issue.
Is it intended that below code returns `true`?
```
moment('1_/__/____', 'MM/DD/YYYY').isValid()
```

**Comment by ashsearle** [comment]
Yes.

Use [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/) if you don't want that:
```js
moment('1_/__/____', 'MM/DD/YYYY', true).isValid(); // false
```

**Comment by dmitriyaa** [comment]
But what is the reasoning behind this logic?

**Comment by ashsearle** [comment]
Guessing: original developers had a choice between making the default parsing behaviour lenient or strict, and they chose to make it lenient.

It's too late to change the _default_ behaviour now (as it'd break a lot of code.)

**Comment by dmitriyaa** [comment]
Thanks for the explanation ❤️
