### ISSUE TITLE
不同时区解析同一个时间格式会得到不同的时间戳

### ISSUE THREAD

**Issue by JayenLee** [moment/moment#5431]
**Describe the bug**
moment.js日期解析有一个很大的bug
比如：我需要解析日期是北京时间：  02/Apr/2020:08:40:37
我的本地时区也是北京时区：所以使用moment('02/Apr/2020:08:40:37','DD/MMM/YYYY:HH:mm:ss').unix()得到的时间戳是正常的。
但是：我服务器时区是utc时区，在服务器上解析，这个日期的时候得到的时间戳整整多出了8个小时。
而我找了整个文档都没有一个能够先同步时区之后再进行解析的函数。希望是否能够先把时区统一了再做日期解析的函数？
为何一定要依赖系统环境的时区？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

**Additional context**

**Comment by ashsearle** [comment]
From the manual:
> Unless you specify a time zone offset, parsing a string will create a date in the current time zone.

```js
moment("2010-10-20 4:30",       "YYYY-MM-DD HH:mm");   // parsed as 4:30 local time
moment("2010-10-20 4:30 +0000", "YYYY-MM-DD HH:mm Z"); // parsed as 4:30 UTC
```

You could try:
```js
moment('02/Apr/2020:08:40:37 +0800','DD/MMM/YYYY:HH:mm:ss Z').unix();
```
