### ISSUE TITLE
获取当前周时间错误

### ISSUE THREAD

**Issue by lovewmf** [moment/moment#5436]
**Describe the bug**
 moment(moment().week(moment().week()).startOf('week').add(1, 'days').valueOf()).format('YYYY-MM-DD')
获取当前周的周一时间（2020-03-30）
而实际获取到的是2020-04-06下周一时间

**Comment by Alanscut** [comment]
@lovewmf  I use `moment` to get the following result. The version of` moment` is 2.24.0, which should be related to the global locale.

```javascript
    moment.locale('zh-cn');
   // 2020-03-31
    let now1 = moment(moment().week(moment('2020-04-05').week()).startOf('week').add(1, 'days').valueOf()).format('YYYY-MM-DD');
    moment.locale('zh-hk');
   // 2020-04-06
    let now2 = moment(moment().week(moment('2020-04-05').week()).startOf('week').add(1, 'days').valueOf()).format('YYYY-MM-DD');
   // 2020-03-30
    let now3 = moment(moment().week(moment('2020-04-04').week()).startOf('week').add(1, 'days').valueOf()).format('YYYY-MM-DD');
```

**Comment by marwahaha** [comment]
Hi! Thanks for filing this issue! Unfortunately, I can't reproduce this. Could you provide any other information?

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.
