### ISSUE TITLE
Doesn't convert days of week

### ISSUE THREAD

**Issue by maxkopych** [moment/moment#5437]
Trying convert ddd to dddd format.
moment( 'Sun','ddd').format('dddd') returns 'Monday'

**Comment by beso9595** [comment]
It works on latest versions, but i could reproduce it on `1.6.2`. It is fixed in `1.7.0`. So the question is, what is the version you're using? Version upgrade will help. Btw `1.6.2` is a pretty old version.

**Comment by maxkopych** [comment]
@beso9595 weird I can't replicate problem any more. But I'm using `2.24.0` .
It might was a conflict with moment-timezone package.
Anyway thank you for you response.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
