### ISSUE TITLE
Locale for Tigrinya (ti) is not supported

### ISSUE THREAD

**Issue by maxammann** [moment/moment#5438]
**Describe the bug**
The locales for Tigrinya are missing.

**To Reproduce**
1. Requesting the ti locale fails

**Expected behavior**
The ti locale should be supported.

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any
 - Version: any

**Moment-specific environment**

* The time zone setting of the machine the code is running on: Europe/Berlin
* The time and date at which the code was run: 07. Aril 2020
* Other libraries in use (TypeScript, Immutable.js, etc): none

`require('moment').locale('ti')` returns 'en'

**Additional context**
none

**Comment by Alanscut** [comment]
@maxammann  you should create a locale setting with your customizations.this is a very cool feature provided by `moment`.
https://momentjs.com/docs/#/customization/

**Comment by maxammann** [comment]
Problem is that I do not speak Tigrinya but our app should support it.

Maybe we can find somebody knowledgeable :)

**Comment by Alanscut** [comment]
The authors and members of this library may be busy with other work. This is a very awkward situation. Maybe we can use a translator :).

**Comment by maxammann** [comment]
I'll discuss this within our project. Maybe we can do something

**Comment by maxammann** [comment]
I think we can make a proposal and let it check by a professional translator: https://lh.2xlibre.net/locale/ti_ER/

**Comment by maxammann** [comment]
Is there a procedure from the moment.js for adding locales? My current Idea would be to create the locale and then generate sample sentences which can be checked by non-tech professional translators.

**Comment by Alanscut** [comment]
You can express your thoughts on `gitter` : (https://gitter.im/moment/moment?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by yosiasz** [comment]
Amharic Tigrinya Speaker here. How can I help

**Comment by Alanscut** [comment]
@yosiasz See https://github.com/moment/moment/blob/develop/src/locale/en-ie.js and https://momentjs.com/docs/#/i18n/ . Add `Tigrinya` internationalization support.

**Comment by marwahaha** [comment]
Sure, we'd look at a PR for this.
I closed it in favor of https://github.com/moment/moment/issues/4949
