### ISSUE TITLE
Durations as units of time

### ISSUE THREAD

**Issue by dawaltconley** [moment/moment#5440]
I'd love to be able to use durations as units of time in other methods. This is mostly a convenience thing, but it would help when working with APIs that insist on returning time intervals as strings.

```
const t1 = moment('2020-01-01T00:00:00')
const t2 = moment('2020-01-01T12:00:00')
const t3 = moment('2020-01-01T12:15:00')
const hour = moment.duration('01:00:00')

t2.diff(t1, hour) // returns 12
t2.isSame(t3, hour) // returns true
```

This could be only for durations that are _exactly_ some unit of time, or for any duration that humanizes to one unit of time, i.e. `moment.duration('01:00:01')` counts as 'an hour.' Or methods like `diff` and `isSame` could take a number of milliseconds as well as a string (seems harder to implement).

**Comment by marwahaha** [comment]
Thanks for opening this request.

For now, we will not take this change.
Perhaps this would be best as a plugin for Moment.js.
https://momentjs.com/docs/#/plugins/

If you do work out a solution, you could post it here, or make a PR to https://github.com/moment/momentjs.com/ .

Best of luck.
