### ISSUE TITLE
Difference in coherent formatted time

### ISSUE THREAD

**Issue by notmutiny** [moment/moment#5441]
When I have one year and one day of a difference in time, the formatted output I want is NOT 1 year and 366 days. That's stupid, and so is this design. It should be 1 year and 1 day (which is the actual difference).

There needs to be a way to return the difference in times in a legible format because as it is now, the only reason why I was intending to use moment doesn't work properly and it's clear that this library doesn't do dates well despite is claiming otherwise.

Thanks.

**Comment by ashsearle** [comment]
Feel free to share your code.

**Comment by notmutiny** [comment]
The issue is a lack of code provided by this library for a common use case. Sample code is the following:

`const startTime = moment("12:00:00 am", "HH:mm:ss a");
const endTime = moment("06:30:45 pm", "HH:mm:ss a");
const duration = moment.duration(endTime.diff(startTime));`

Trying to get the Hours and Minutes from the duration object will return in 18 hours and 1110 minutes. There's no way to get a coherent string back where the hours are subtracted from the minutes. This is made much worse when dealing with centuries, years, days, etc.

If the user has to do math on your result, the library is failing the purpose of handling dates and there's no reason to use Moment.js over the standard Date class which can subtract dates and return milliseconds.

**Comment by notmutiny** [comment]
A simpler example which I provided in my original post:

```js
const startTime = moment("20200101", "YYYYMMDD");
const endTime = moment("20210101", "YYYYMMDD");
const duration = moment.duration(endTime.diff(startTime));
```

The result will be 1 year and 366 days, rather than 1 year and 365 days. If the end user has to do math to fix the output of this library, then the purpose of the library is defeated and the default Date class can be used instead.

**Comment by ashsearle** [comment]
It sounds like you're using `asDays` and `asYears` - but you don't include either in your code.

Try using `days` and `years`:
```js
const startTime = moment("2020-01-01", "YYYY-MM-DD");
const endTime = moment("2021-01-02", "YYYY-MM-DD");
const duration = moment.duration(endTime.diff(startTime));

duration.years(): // 1
duration.months(); // 0
duration.days(); // 1
```

**Comment by notmutiny** [comment]
Wow you're correct and that works great — thank you for providing the solution. I apologize for my rudeness. Next time I'll read the documentation before assuming the worst.
