### ISSUE TITLE
moment is not a function?

### ISSUE THREAD

**Issue by mathritter** [moment/moment#5444]
Can't even execute the example shown in https://momentjs.com/docs/#/use-it/typescript/
Any help or advice? Seems like a bug
![image](https://user-images.githubusercontent.com/6000689/79233059-b51efb00-7e3e-11ea-9f9f-f7e06e1a3945.png)

error: 

moment is not a function. (In 'moment()', 'moment' is an instance of Object)
* components\Calendar.tsx:25:20 in prepareMomentJS
* components\Calendar.tsx:21:4 in componentDidMount
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17028:11 in commitLifeCycles
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:20001:23 in commitLayoutEffects
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:306:6 in invokeGuardedCallbackImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:530:2 in invokeGuardedCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19766:6 in commitRootImpl
* [native code]:null in commitRootImpl
- node_modules\scheduler\cjs\scheduler.development.js:642:6 in unstable_runWithPriority
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19588:6 in commitRoot
* [native code]:null in commitRoot
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18708:6 in runRootCallback
* [native code]:null in runRootCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5641:13 in runWithPriority$argument_1
- node_modules\scheduler\cjs\scheduler.development.js:642:6 in unstable_runWithPriority
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5637:18 in flushSyncCallbackQueueImpl
* http://192.168.0.30:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:197263:35 in flushSyncCallbackQueue
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18794:29 in batchedUpdates$1
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2708:6 in batchedUpdates
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2793:13 in _receiveRootNodeIDEvent
* http://192.168.0.30:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:195186:34 in receiveTouches
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:432:6 in __callFunction
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:110:17 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:383:10 in __guard
* http://192.168.0.30:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:215840:21 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

**Comment by Alanscut** [comment]
@mathritter Please see `stackoverflow` here for the complete solution.
https://stackoverflow.com/questions/56503281/typescript-import-as-moment-from-moment-vs-import-moment-from-moment

**Comment by marwahaha** [comment]
I'll take a PR at https://github.com/moment/momentjs.com/

**Comment by marwahaha** [comment]
The docs are updated.
Please re-open if you still have concerns.
