### ISSUE TITLE
Date resolution error

### ISSUE THREAD

**Issue by WebHero0544** [moment/moment#5446]
moment('1900-01-01 00:00', 'YYYY-MM-DD HH:mm').add(8760, 'hour').format('YYYY-MM-DD HH:mm')
"1900-12-31 23:54"
moment('1900-01-01 00:00', 'YYYY-MM-DD HH:mm').add(8759, 'hour').format('YYYY-MM-DD HH:mm')
"1900-12-31 23:00"

**Comment by Alanscut** [comment]
@ WebHero0544  Maybe you should use `UTC()` to parse the date.

```javascript
// 1901-01-01 00:00
console.log('UTC-1900', moment.utc('1900-01-01 00:00', 'YYYY-MM-DD HH:mm').add(8760, 'hour').format('YYYY-MM-DD HH:mm')) 

 // 1902-01-01 00:00
console.log('moment-1901', moment('1901-01-01 00:00', 'YYYY-MM-DD HH:mm').add(8760, 'hour').format('YYYY-MM-DD HH:mm'))
```

## JavaScript Date objects
#### Unused `Date.UTC ()`
![issue_5446](https://user-images.githubusercontent.com/21104054/79631107-60a2b500-8189-11ea-92ca-3a2adac46a48.PNG);

#### Use `Date.UTC ()`
![issue_5446_utc](https://user-images.githubusercontent.com/21104054/79631289-d78c7d80-818a-11ea-87f8-12b2430204d4.PNG);

**Comment by WebHero0544** [comment]
Um, um, I tried. No problem. Thank you very much

**Comment by marwahaha** [comment]
@WebHero0544 this could have to do with an unusual historic time zone offset in your area. Setting to UTC (as @Alanscut suggested) should avoid this problem.

Please re-open if you still have issues.
