### ISSUE TITLE
Typescript instructions in docs just results in error

### ISSUE THREAD

**Issue by jeremypeters** [moment/moment#5449]
Following the Typescript instructions (https://momentjs.com/docs/#/use-it/typescript/) results in the error:

`TS2349: This expression is not callable.
    Type 'typeof moment' has no call signatures.`

**Comment by Alanscut** [comment]
@jeremypeters See issue #5444 .

**Comment by jeremypeters** [comment]
If the steps in the documentation result in an error, then it is wrong and needs updating.

**Comment by marwahaha** [comment]
duplicate of #5444
