### ISSUE TITLE
Duration locale data

### ISSUE THREAD

**Issue by colemars** [moment/moment#5451]
There seems to be no non-global way to update locale data for use with Duration?

Based on `.locale` and `.updateLocale` I would assume 

```
const en = moment
  .duration(1, "minutes")
  .locale("en", {
    relativeTime: {
      future: "in %s",
      past: "%s ago",
      s: "few seconds",
      ss: "%d seconds",
      m: "minute",
      mm: "%d minutes",
      h: "hour",
      hh: "%d hours",
      d: "day",
      dd: "%d days",
      M: "month",
      MM: "%d months",
      y: "year",
      yy: "%d years"
    }
  })
  .humanize();
```

Might work but it seems the full locale object isn't exposed to `.duration`. 

`.duration` is also not available to a `moment()` instance so updating locale that way would not work either. 

Am I missing something here?

**Comment by marwahaha** [comment]
I'm not sure what you're asking here.
You can get or set the duration's locale here: https://momentjs.com/docs/#/durations/locale/

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.
