### ISSUE TITLE
moment().format("YYYY-MM-DD HH:mm:ss") gets weird strings.

### ISSUE THREAD

**Issue by jacky-ew** [moment/moment#5468]
**Describe the bug**
moment().format("YYYY-MM-DD HH:mm:ss") returns "\u1042\u1040\u1042\u1040-\u1040\u1044-\u1042\u1043 \u1041\u1048:\u1040\u1040:\u1044\u1042"

**To Reproduce**
1. declare moment().format("YYYY-MM-DD HH:mm:ss")
2. gets "\u1042\u1040\u1042\u1040-\u1040\u1044-\u1042\u1043 \u1041\u1048:\u1040\u1040:\u1044\u1042" as result. which is not what expected

**Expected behavior**
gets the moment in given format

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome
 - Version 81

**Smartphone (please complete the following information):**
 - Device: Iphone
 - OS: ios 12

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

**Additional context**

**Comment by Alanscut** [comment]
@jacky-ew What environment are you running this in: which browser, node version, moment version etc, and are you using any plugins?

I execute the following code to get the expected result, version 2.24.0 of `moment`.
```javascript
import moment from  'moment';
console.log('issue_5468', moment().format("YYYY-MM-DD HH:mm:ss"));  // 2020-04-27 16:07:19
```

**Comment by jacky-ew** [comment]
Hi sorry for late reply. just found out that some iphone user uses arabic as main language. Causing the date time string returned in arabic format. Solved with `moment().locale("en")`
