### ISSUE TITLE
hi, i'm trying create a date format

### ISSUE THREAD

**Issue by jensysantana** [moment/moment#5478]
hi, i'm trying create a date format like this.
if year less than one year just show:
like 9 mounts.

if year is more than one year show:
one year and two mounts.

i would like to know if have a way to make it.

**Comment by ichernev** [comment]
@jensysantana you could use this plugin: https://github.com/jsmreese/moment-duration-format
It is not supported in core moment.

**Comment by jensysantana** [comment]
ok. thank you so much i'm already fixed but definitely  is better way using that plugin:
my solution

const addressLong = (iterator)=>{
        let nowfrom = moment(iterator.from);
        let nowTo = moment(iterator.to);
        if (nowfrom.isSame(nowTo)) {
            return '0 month';
        }

        let months = nowTo.diff(nowfrom, 'M');
        let dateArr = `${months / 12}`.split('.');
        let getYears = '';
        if (dateArr[0] === '0') {
            getYears +=  months > 1 ? months+' months' : months + ' month';
        }else{
            
            if (dateArr[0] >= 1) {
                
                if (dateArr.length >= 1 && dateArr[1] !== undefined) {
                    getYears = dateArr[0] > 1 ? dateArr[0]+ ' years and ' : dateArr[0] +' year and ';
                }else{
                    getYears = dateArr[0] > 1 ? dateArr[0]+ ' years ' : dateArr[0] +' year ';
                }
            }
            
            if (dateArr.length > 1) {
                let randomx = dateArr[1].substr(0, 1);
                randomx = parseInt(randomx);
                randomx = randomx+1;
                getYears +=  randomx > 1 ? randomx+ ' months' :  randomx+ ' month';
            }
        }
        return getYears;
    }
