### ISSUE TITLE
Amharic locale

### ISSUE THREAD

**Issue by yosiasz** [moment/moment#5479]
Describe the bug
The locales for Amharic are missing.

To Reproduce

Requesting the am locale fails
Expected behavior
The am locale should be supported.

Desktop (please complete the following information):

OS: any
Browser any
Version any
Smartphone (please complete the following information):

Device: any
OS: any
Browser any
Version: any
Moment-specific environment

The time zone setting of the machine the code is running on: Seattle/USA
The time and date at which the code was run: May 1st, 2020
Other libraries in use (TypeScript, Immutable.js, etc): none
require('moment').locale('am') returns 'en'

Additional context
none

**Comment by ichernev** [comment]
We never had Amharic locale to begin with. You can send a Pull Request to add support.
