### ISSUE TITLE
Both en-sg and en-SG locales exist

### ISSUE THREAD

**Issue by gmurphey** [moment/moment#5480]
**Describe the bug**
Both `en-sg.js` and `en-SG.js` locales exist on the latest release (`2.25.0`).

This is causing issues for our builds (using broccoli) as it can't resolve the conflicting capitalizations.

**Comment by sovietspaceship** [comment]
I'm having the same issue, and it's blocking me as several dependencies are pulling this version of moment.

**Comment by vor89** [comment]
Same, so I submitted a pr

**Comment by ichernev** [comment]
Yes, we don't have anything in place to remove renamed locale files, as we never renamed locales before. Will release in a new patch version soon!

**Comment by ichernev** [comment]
2.25.1 released
