### ISSUE TITLE
npm can't find package after 2.25.0 release

### ISSUE THREAD

**Issue by Jon2211** [moment/moment#5481]
**Describe the bug**
Our drone piepline and local builds started failing with cannot find moment around the time of 2.25.0 release.  Problem is with 2.24.0 and 2.25.0 (haven't tried anything else

**To Reproduce**
1.  run ng build --prod in angular project using moment
2. Get build error can't find package moment

**Expected behavior**
expect to not have build error

I have no idea what's causing this, could be coincidence.

**Comment by Mister-Hope** [comment]
I got this error too.

[Commit which update to 2.25.0](https://github.com/Mister-Hope/vuepress-theme-hope/commit/57bad0ac6593ebcd7efee7e0c5c64eb0a11a3888)

[Build log](https://github.com/Mister-Hope/vuepress-theme-hope/runs/635332006)

**Comment by bsoulier** [comment]
Same problem for me, deployments started fo fail as dependency as soon as it picked up the new version. Fixing dependency Verizon to 2.24 fixed it temporarily 👍

**Comment by Yama-Tomo** [comment]
probably `ts3.1-typings` directory is missing from the artifacts

**Comment by Jon2211** [comment]
We were already using 2.24.0, so not a universal workaround, at least for us

**Comment by usmansbk** [comment]
It doesn't work with `moment-recur` package anymore.
`moment().recur()` method is undefined

**Comment by Rapiz1** [comment]
Downgrade to 2.24.0 works

**Comment by ephoton** [comment]
How to Downgrade @Rapiz1

**Comment by lc-brunomonteiro** [comment]
I am having the same issue in my CI environment, with the error message:

`Critical dependency: the request of a dependency is an expression`

**Comment by clabough** [comment]
Cannot find module 'moment'.

import * as moment from "moment";

**Comment by kenmueller** [comment]
Same issue here. I downgraded to 2.24.0 in the meantime.

**Comment by arshaw** [comment]
typescript can't resolve the type definitions. as @Yama-Tomo pointed out, the `ts3.1-typings` dir is missing. The [package.json](https://github.com/moment/moment/blob/2.25.0/package.json#L32) references it but it's not in the npm-published files.

When I temporarily delete that line in my `node_modules/moment/package.json` and rerun `tsc`, things work.

Of course that's not a real solution. The best solution for not is to downgrade to `2.24.0` until this gets fixed.

**Comment by abhinavsingi** [comment]
Is this being fixed?
[moment-timezone](https://github.com/moment/moment-timezone/blob/develop/package.json#L30) uses 
`		"moment": ">= 2.9.0"
`
It breaks

**Comment by nikkonduru88** [comment]
Our team also has moment-timezone dependency and it is breaking. What is the eta of this issue being fixed?

**Comment by abhinavsingi** [comment]
Can try with resolutions field in package.json

Add

> "resolutions": {
>     "moment": "2.24.0"
> }

**Comment by ichernev** [comment]
OK, so I'll include the ts3.1 bindings, as @arshaw pointed out. I hope that fixes the build for everyone.

**Comment by Jon2211** [comment]
Ah, yes 2.24.0 does work.  Just realized that we had ^ instead of ~ so we were pulling 2.25.0 regardless of what package.json said.

**Comment by ichernev** [comment]
2.25.1 addresses all raised problems. And this issue is just a bad collection of legitimate issues and crap...

**Comment by agrohs** [comment]
Why are these issues closed...2.25 has some major issues

**Comment by tonix-tuft** [comment]
@ichernev 2.25.1 does not fix the `Cannot find module './locale'`  issue. Only downgrading to `2.24.0` works for now. Are there any updates? Thank you.
