### ISSUE TITLE
incorrect typeof checks in a few places causing unintended behaviour

### ISSUE THREAD

**Issue by jokeyrhyme** [moment/moment#5483]
**Describe the bug**

moment's code include incorrect uses of `typeof` that are causing the `Symbol` support check to fail in Node.js 0.10.x, and maybe causing issues with the use of `__dirname`

```
moment.js
2093:                    (typeof __dirname !== undefined ? __dirname : '.') +
4917:    if (typeof Symbol !== undefined && Symbol.for != null) {

min/moment-with-locales.js
2087:                    (typeof __dirname !== undefined ? __dirname : '.') +
4911:    if (typeof Symbol !== undefined && Symbol.for != null) {

src/lib/moment/prototype.js
61:if (typeof Symbol !== undefined && Symbol.for != null) {

src/lib/locale/locales.js
79:                (typeof __dirname !== undefined ? __dirname : '.') +
```

Note that [`typeof`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) returns a string, and the above checks are comparing the result of `typeof` against the `undefined` value, not the `"undefined"` string

**To Reproduce**
1. `require('moment')` using a version of Node.js that doesn't implement `Symbol`
2. observe the following error:

```
if (typeof Symbol !== undefined && Symbol.for != null) {
ReferenceError: Symbol is not defined
```

**Expected behavior**
This should load just fine without any exceptions or errors

**Screenshots**
n/a

**Comment by jokeyrhyme** [comment]
ESLint has a rule to check for invalid uses of `typeof` that you may find useful: https://eslint.org/docs/rules/valid-typeof

**Comment by ichernev** [comment]
@jokeyrhyme we have eslint and we use `"extends": "eslint:recommended"` and it still didn't catch it. Maybe you can investigate.

I'll fix the typeof problems and release shortly.
