### ISSUE TITLE
'ISO_8601' is not exported from 'moment'

### ISSUE THREAD

**Issue by andrewchukwu** [moment/moment#5488]
Attempted import error: 'ISO_8601' is not exported from 'moment' (imported as 'moment').

My application is getting the following error upon using the latest release: 2.25.0

import * as moment from 'moment'
....

moment.ISO_8601, 'HH:mm')

**Comment by InonDv** [comment]
I have the same issue

**Comment by alexlafroscia** [comment]
Seeing this in our app too -- `moment.ISO_8601` is `undefined`

**Comment by Alanscut** [comment]
This bug has been fixed in the latest version.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
