### ISSUE TITLE
[feature] Revamp moment, locale bundling

### ISSUE THREAD

**Issue by ichernev** [moment/moment#5492]
OK, so ever since the ES Modules came around and the JS packagers were updated to fit the situation for moment became unbearable.

The biggest offender is the logic that automatically requires locales, which is supposed to work only on node.js (at least that was how it was conceived), where all files are local and it is a cheap operation.

So here is an overview of how I thing this problem can be solved going forward.
- moment locales should be "independent" of moment. They should be a collections of data and code (functions) that do not directly depend (read, require/import) on moment. Such a PR is currently pending in the PRs: https://github.com/moment/moment/pull/5119
```
module.export = {
  abbr: 'de',
  months: ['Jan', /* ... */
  /* ... */
}
```
- moment itself should not try to load locales, because then some packagers (like webpack) go ape shit trying to load every single locale just in case. Thus, using standalone locales, one has to first aquire the locale data somehow, and then give it to moment, which will then register this locale:
```
var de = require('moment/locale-data/de'); // or through some other means
moment.defineLocale(de); // now moment "learns" de
moment.locale('de'); // ok, now we can switch to 'de', because we know it
moment.locale('fr'); // nope, we don't know what 'fr' is (yet) -- throw exception
```
- to make the situation more palatable we can have plugins/helpers that help with loading locales in the appropriate way for different environments, but hey should be strictly per-environment/use case, and not part of moment core.
```
// for node.js
var moment = require('moment');
var momentLocaleNode = require('moment-locale-node');
momentLocaleNode.setup(moment); // hook auto-locale loading for node.js
moment.locale('de'); // this loads the 'de' locale data via require, in a nodejs (or similar) env
moment.locale('deee'); // this throws an exception because the 'deee' locale is not present and can not be loaded

// for async style, in browser loading
var moment = require('moment');
var momentAsyncLocaleLoader = require('moment-async-loader');
momentAsyncLocaleLoader.setup(moment);
moment.asyncLocale('de').then(function (moment) {
  // locale de is loaded at this point
});
moment.locale('de') // this will either return normally if the locale is already loaded and available for use or throw an exception if 'de' is not available yet in this scenario
```

Obviously all of this has to be a new major release, because it is fundamentally changing how locales work. Also, it will be great if the loaders are tested under the respective environments (I hope that moment will become env agnostic, once this is resolved).

**Comment by BARICISSE** [comment]
Hi, I am a beginner, I am available to work on this. may I?

**Comment by marwahaha** [comment]
Hi @BARICISSE , thanks for offering. This may not be a good first issue for a beginner.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
