### ISSUE TITLE
"export 'weekdays'  was not found in 'moment' after 2.25.1 upgrade

### ISSUE THREAD

**Issue by bobskigit** [moment/moment#5493]
I have just upgraded to 2.25.1 and get the following errors

export 'locale' (imported as 'moment') was not found in 'moment'

AND

"export 'weekdays' (imported as 'moment') was not found in 'moment'

Reverting back to 2.24

**Comment by RonnieRocket147** [comment]
Same for me with **updateLocale**:

`"export 'updateLocale' (imported as 'moment') was not found in 'moment'`

**Comment by J1445** [comment]
I wonder how they released a version of a library which is used by 1.4 million projects, so blindly   without a CI  testing

**Comment by way2key** [comment]
Same for me with moment-duration-format I got this error:
"export 'duration' (imported as 'moment') was not found in 'moment'
I posted something on stackoverflow [here](https://stackoverflow.com/questions/61560427/import-moment-js-2-25-1-in-angular2) I hope it will be usefull

**Comment by alex-albericio** [comment]
Same issue with isDate. Works fine in 2.24.0

**Comment by huineng** [comment]
same with utc 

```
"export 'utc' (imported as 'moment') was not found in 'moment'
    at HarmonyImportSpecifierDependency._getErrors
```

**Comment by bobskigit** [comment]
Latest 2.25.3 fixes the issues, many thanks

**Comment by liangzhuang327** [comment]
May 3 found that the 2.25.1 version has es6 syntax so far, toss edit edited for 3 days, the last attempt actually found the new version, I knew, the developer urgently modified the error

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
