### ISSUE TITLE
Running array.sort() on an array of moment instances do not produce a sorted array

### ISSUE THREAD

**Issue by FelixZY** [moment/moment#5496]
**Describe the bug**
I have an array of moment instances that I want to sort in order. Calling `.sort()` on the array does not produce a sorted array.

**To Reproduce**
```
[moment("2020-05-05"), moment("2020-05-06"), moment("2020-05-07")].sort().map(it => it.format("YYYY-MM-DD"))
```

**Expected behavior**
```
["2020-05-05", "2020-05-06", "2020-05-07"]
```

**Actual behavior**
```
["2020-05-07", "2020-05-05", "2020-05-06"]
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - Browser: chrome
 - Version: 80.0.3987.163 (Official Build) (64-bit)

**Moment-specific environment**

Timezone: `Europe/Stockholm`
Executed on: 2020-05-02 around 17:15

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
---
Sat May 02 2020 17:18:06 GMT+0200 (Central European Summer Time)
5/2/2020, 5:18:06 PM
-120
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
```

**Comment by FelixZY** [comment]
I believe this stems from the definition of `.sort()` in JS. to quote [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort):

> The sort() method sorts the elements of an array in place and returns the sorted array. The default sort order is ascending, **built upon converting the elements into strings, then comparing their sequences of UTF-16 code units values.**

Looking at the output from
```
>>> [moment("2020-05-05"), moment("2020-05-06"), moment("2020-05-07")].map(it => it.toString())
["Tue May 05 2020 00:00:00 GMT+0200", "Wed May 06 2020 00:00:00 GMT+0200", "Thu May 07 2020 00:00:00 GMT+0200"]
```

it looks like `.sort()` is just looking at the day value and basing its order on that.

**Comment by J1445** [comment]
https://stackblitz.com/edit/moment-js-playground-w3ubtk?file=index.ts  

http://www.ecma-international.org/ecma-262/6.0/#sec-sortcompare 

>>>Unless the sort order is specified above to be implementation-defined, the returned object must have the following two characteristics:

>>>There must be some mathematical permutation π of the nonnegative integers less than len, such that for every nonnegative integer j less than len, if property old[j] existed, then new[π(j)] is exactly the same value as old[j]. But if property old[j] did not exist, then new[π(j)] does not exist.

>>>Then for all nonnegative integers j and k, each less than len, if SortCompare(old[j], old[k]) < 0 (see SortCompare below), then new[π(j)] < new[π(k)].

Since date comparison is neither of the category you are supposed to pass the stringcmp function to evaluate the date sequence with another

**Comment by marwahaha** [comment]
Nice find @FelixZY 
You could add a compare function, like below:
```
[moment("2020-05-05"), moment("2020-05-06"), moment("2020-05-07")].sort((a, b) => a.format("YYYY-MM-DD") > b.format("YYYY-MM-DD")).map(it => it.format("YYYY-MM-DD"))
```

**Comment by FelixZY** [comment]
Ok, I know this isn't a bug in moment per se, but I still think this is something that should be fixed @marwahaha .

This is an easy mistake to make, that is hard to debug for a novice and with an ugly solution.

I would propose making `.toString` return an ISO8601 formatted date. That would solve the problem and make more sense in general in my opinion.

**Comment by marwahaha** [comment]
Although this is a nice idea,
For now, we will not take this change.
Consider `Date().toString()` which prints something very similar to moment.
Best of luck.
