### ISSUE TITLE
[2.25.0 / 2.25.1] WebpackError: Cannot find module './locale'

### ISSUE THREAD

**Issue by jakeherp** [moment/moment#5497]
I am using moment in a Gatsby / React project and get the following webpack errors during build:

```
> 1 | import { Moment } from './constructor';
    | ^
  2 | 
  3 | var proto = Moment.prototype;
  4 | 


  WebpackError: Cannot find module './locale'
  
  - prototype.js:1 webpackMissingModule
    node_modules/moment/src/lib/moment/prototype.js:1:1
  
  - prototype.js:1 Module../node_modules/moment/src/lib/moment/prototype.js
    node_modules/moment/src/lib/moment/prototype.js:1:1
  
  - moment.js:1 Module../node_modules/moment/src/lib/moment/moment.js
    node_modules/moment/src/lib/moment/moment.js:1:1
  
  - moment.js:1 Module../node_modules/moment/src/moment.js
    node_modules/moment/src/moment.js:1:1
```

Looking at the changes in 2.25.0 it seems like the way moment gets exported has changed, which should be a major version bump if this is in fact the desired outcome.

**Comment by jakeherp** [comment]
Might be related to #5495

**Comment by outlawpractice** [comment]
I have 2.24, and today my build is dead in the water with this same issue:

./node_modules/moment/src/lib/locale/locales.js
Module not found: Can't resolve './locale' in '/Users/john/projects/outlawpractice/client/node_modules/moment/src/lib/locale'

**Comment by jakeherp** [comment]
@outlawpractice did you upgrade to 2.25.x at some point? 
`yarn --force` fixed it for me, as a regular install doesn't get rid of the references to 2.25.x in the lock file.

**Comment by leantide** [comment]
A full reinstall using moment: ^2.24.0 still gave the error, even with npm --force.

Resolved after I deleted my node_modules directory and also my npm package-lock file, and used "moment": "2.24.0" (without the ^) in package.json, and performed an npm install. 

Then I added my ^ back, and 'npm outdated' indicated that I should update to moment 2.25.1 - and after thinking for a MOMENT, I decided not to do.

**Comment by jakeherp** [comment]
> A full reinstall using moment: ^2.24.0 still gave the error, even with npm --force.
> 
> 
> 
> Resolved after I deleted my node_modules directory and also my npm package-lock file, and used "moment": "2.24.0" (without the ^) in package.json, and performed an npm install. 
> 
> 
> 
> Then I added my ^ back, and 'npm outdated' indicated that I should update to moment 2.25.1 - and after thinking for a MOMENT, I decided not to do.

That makes sense as the ^ will allow to install a higher minor version. ~ would install only higher patch versions.

**Comment by BhanukaUOM** [comment]
Update package.json. This was fixed for me.

`"moment": "2.24.0"`

**Comment by hktr92** [comment]
> Update package.json. This was fixed for me.
> 
> `"moment": "2.24.0"`

not for me. having 2 libs that enforces version by caret and can't control the installed version.

**Comment by mKlus** [comment]
We are facing the same issue. Most of out ci develop builds are failing. Hope this can be resolved soon.

**Comment by ichernev** [comment]
2.25.2 addresses this. Make sure to exclude the locale files from being auto-bundled via webpack configuration.

**Comment by mKlus** [comment]
Thanks. Works fine now.
