### ISSUE TITLE
Formatting issue: from HH:mm:ss to hh:mm A

### ISSUE THREAD

**Issue by HarryTrue** [moment/moment#5498]
moment('03/22/2001 07:10:10', 'MM/DD/YYYY HH:mm:ss').format('hh:mm A')

the result is 07:10 PM even though expecting 07:10 AM

**Comment by yosiasz** [comment]
https://momentjs.com/docs/ says capital A is for PM, so it is doing as deisgned.

a A | am pm

**Comment by HarryTrue** [comment]
> https://momentjs.com/docs/ says capital A is for PM, so it is doing as deisgned.
> 
> a A | am pm

@yosiasz , actually I meant something else in the original comment above. I meant that I was expecting AM instead of PM since time is 07:10:10 and not 19:10:10.
Anyways, I found out that  I was using older version of momentjs. This issue is fixed in new one.
Thanks anyway!
