### ISSUE TITLE
Building custom meridiem Amharic Locale 

### ISSUE THREAD

**Issue by yosiasz** [moment/moment#5499]
Greetings,

In Amharic, I want to define my own custom meridiem.
am is ከጠዋቱ
pm is ከምሽቱ

But then how do I use this in testing the formatting so that it works as you do when using dddd ? Is there one for meridiem ?
'[ያለፈው] dddd meridiem LT [ሰዓት]'

So last Monday 5am would be transliterated in English to

**[Last]** Monday am 5 hour.

**Comment by yosiasz** [comment]
@Alanscut Could you please provide direction on this? Ready to submit a pull request for Amharic but stuck on this issue.

**Comment by marwahaha** [comment]
I'm not sure what you mean.
If you are trying to customize the meridiem function, please use https://momentjs.com/docs/#/customization/am-pm/
If you are trying to display the meridiem, use "A" or "a": https://momentjs.com/docs/#/displaying/format/

**Comment by yosiasz** [comment]
Thank you @marwahaha, your input helped me sort out the issue I was encountering.
