### ISSUE TITLE
WARNING in ./node_modules/moment/src/lib/locale/locales.js

### ISSUE THREAD

**Issue by vinodhboston** [moment/moment#5500]
when running npm start, warning errors throws and application is not running.
i have tried following steps to resolve this issue, but still it is not yet fixed.

1.  I have changed the path and checked, Still not working. Screenshot below
![image](https://user-images.githubusercontent.com/64720536/80907086-30cee200-8d31-11ea-8ddd-6bd24d5574f9.png)

Locales.js path: 

![image](https://user-images.githubusercontent.com/64720536/80907128-a9ce3980-8d31-11ea-920f-9a57b466ad7d.png)
![image](https://user-images.githubusercontent.com/64720536/80907887-31b74200-8d38-11ea-9bc3-9fcc23ea9dae.png)

2. imported DLL - import * as moment from "moment/moment.js". Still not working

3. installed yarn upgrade, npm install moment. Still not working. 

Kindly help us to fix this issue.

Below is the error while running npm start

![image](https://user-images.githubusercontent.com/64720536/80906131-c8800080-8d30-11ea-957b-c535f778d0d8.png)

Below is error while running my application:

![image](https://user-images.githubusercontent.com/64720536/80906963-054bf780-8d31-11ea-835d-fac1d86f3d6e.png)

my package.json file

![image](https://user-images.githubusercontent.com/64720536/80907841-c0778f00-8d37-11ea-8285-282307266756.png)
![image](https://user-images.githubusercontent.com/64720536/80907862-f7e63b80-8d37-11ea-8a68-0e267649c881.png)
![image](https://user-images.githubusercontent.com/64720536/80907869-02a0d080-8d38-11ea-9000-8d656d58a344.png)

**Comment by ichernev** [comment]
2.25.2 should fix this. You might need to exclude moment locales from auto-bundling with moment via webpack configuration.

**Comment by ChrisWiles** [comment]
Running 2.25.2 and get this

<img width="1036" alt="Screen Shot 2020-05-04 at 9 59 57 AM" src="https://user-images.githubusercontent.com/9455409/80980587-6b4a8480-8dee-11ea-849e-69404b574f13.png">
