### ISSUE TITLE
Error: Cannot find module './locale'

### ISSUE THREAD

**Issue by whwan2008** [moment/moment#5501]
When I create a new React,install antd and import ./antd/dist/antd.css,after I run this demo,the cilent throw an error like this:

Error: Cannot find module './locale'
▼ 2 stack frames were expanded.
webpackMissingModule
D:/ReactDemo/demo04/node_modules/rc-picker/node_modules/moment/src/lib/moment/prototype.js:1
Module../node_modules/rc-picker/node_modules/moment/src/lib/moment/prototype.js
D:/ReactDemo/demo04/node_modules/rc-picker/node_modules/moment/src/lib/moment/prototype.js:1
▲ 2 stack frames were expanded.
__webpack_require__
D:/ReactDemo/demo04/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
fn
D:/ReactDemo/demo04/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../node_modules/rc-picker/node_modules/moment/src/lib/moment/moment.js
D:/ReactDemo/demo04/node_modules/rc-picker/node_modules/moment/src/lib/moment/moment.js:1
__webpack_require__
D:/ReactDemo/demo04/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
fn
D:/ReactDemo/demo04/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../node_modules/rc-picker/node_modules/moment/src/moment.js
D:/ReactDemo/demo04/node_modules/rc-picker/node_modules/moment/src/moment.js:1
__webpack_require__
D:/ReactDemo/demo04/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
fn
D:/ReactDemo/demo04/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../node_modules/rc-picker/es/generate/moment.js
D:/ReactDemo/demo04/node_modules/rc-picker/es/generate/moment.js:1
__webpack_require__
D:/ReactDemo/demo04/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
fn
D:/ReactDemo/demo04/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../node_modules/antd/es/calendar/index.js
D:/ReactDemo/demo04/node_modules/antd/es/calendar/index.js:1
__webpack_require__
D:/ReactDemo/demo04/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
fn
D:/ReactDemo/demo04/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../node_modules/antd/es/index.js
D:/ReactDemo/demo04/node_modules/antd/es/index.js:3
__webpack_require__
D:/ReactDemo/demo04/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
fn
D:/ReactDemo/demo04/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../src/ToDoList.js
http://localhost:3000/static/js/main.chunk.js:16:62
__webpack_require__
D:/ReactDemo/demo04/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
fn
D:/ReactDemo/demo04/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../src/index.js
http://localhost:3000/static/js/main.chunk.js:68:70
__webpack_require__
D:/ReactDemo/demo04/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
fn
D:/ReactDemo/demo04/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1
http://localhost:3000/static/js/main.chunk.js:93:18
__webpack_require__
D:/ReactDemo/demo04/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
checkDeferredModules
D:/ReactDemo/demo04/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
D:/ReactDemo/demo04/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:65
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

Here is my package.json:
{
  "name": "demo04",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "antd": "4.2.0",
    "locale": "^0.1.0",
    "moment": "2.24.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

How can I fix this?

**Comment by yosiawan** [comment]
I ran into similar issue with my React app. I have tried using v 2.18 and v. 2.24 and also noticed that this only happens in the following environment:

- MacOS
-- Safari (Version 13.0.5 (15608.5.11))
-- Chrome (Version 80.0.3987.149 (Official Build) (64-bit))

-iOS
-- Safari 
-- Chrome 

Linux Manjaro 
-- Chrome

These are my dependencies
```
"dependencies": {
    "@livechat/ui-kit": "^0.4.0-5",
    "@material-ui/core": "^4.5.2",
    "@material-ui/icons": "^4.5.1",
    "@material-ui/lab": "^4.0.0-alpha.39",
    "@sentry/browser": "^5.5.0",
    "analytics-js-without-segment": "^1.0.0",
    "apollo-boost": "^0.4.3",
    "apollo-client": "^2.6.4",
    "apollo-link-error": "^1.1.12",
    "apollo-link-retry": "^2.2.15",
    "apollo-link-ws": "^1.0.18",
    "apollo-upload-client": "^11.0.0",
    "clsx": "^1.0.4",
    "date-fns": "^1.30.1",
    "graphql": "^14.5.4",
    "graphql-tag": "^2.10.1",
    "lodash": "^4.17.15",
    "moment": "^2.18.0",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-apollo": "^3.1.3",
    "react-dom": "^16.12.0",
    "react-infinite-scroller": "^1.2.4",
    "react-linkify": "^1.0.0-alpha",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
    "react-toastify": "^5.5.0",
    "react-window": "^1.8.5",
    "subscriptions-transport-ws": "^0.9.16",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "@apollo/react-testing": "^3.1.0",
    "@testing-library/react": "^9.3.0",
    "@types/apollo-upload-client": "^8.1.3",
    "@types/date-fns": "^2.6.0",
    "@types/enzyme": "^3.9.3",
    "@types/enzyme-adapter-react-16": "^1.0.5",
    "@types/jest": "23.3.13",
    "@types/lodash": "^4.14.144",
    "@types/material-ui": "^0.21.6",
    "@types/node": "10.12.18",
    "@types/prop-types": "^15.7.3",
    "@types/react": "^16.9.2",
    "@types/react-dom": "^16.9.0",
    "@types/react-infinite-scroller": "^1.2.1",
    "@types/react-linkify": "^1.0.0",
    "@types/react-router": "^5.1.3",
    "@types/react-router-dom": "^4.3.5",
    "@types/uuid": "^3.4.5",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "enzyme-to-json": "^3.3.5",
    "node-sass-chokidar": "^1.3.5",
    "npm-run-all": "^4.1.5",
    "react-scripts": "^3.3.0",
    "redux-devtools-extension": "^2.13.8",
    "tslint": "^5.14.0",
    "typescript": "^3.7.2"
  },
```
PS: Will update with more info when available

**Comment by BhanukaUOM** [comment]
Update package.json. This was fixed for me.

`"moment": "2.24.0"`

**Comment by angie-markov** [comment]
Could you please outline how you  did this? I'm changing both package and package-lock to 2.24.0, reinstalling Moment and it still reverts to 2.25.1 :(

**Comment by BhanukaUOM** [comment]
`npm uninstall moment`

Then

`npm install --save moment@2.24.0`

**Comment by angie-markov** [comment]
Thank you, much appreciated!

**Comment by dev-sareno** [comment]
Same here, I was able to fix it temporarily by downgrading to `v2.24.0`

**Comment by abrcdf1023** [comment]
The same here, maybe it cause by Webpack configure problem. I am use react-script v3.4.0.

**Comment by aliidrees** [comment]
Same here, I used `"moment": "~2.24.0"` to avoid minor upgrades

**Comment by hktr92** [comment]
this update totally broke my whole frontend. 
2 libraries are using momentjs: bootstrap-daterangepicker and chart.js

i'm just gonna go and `yarn remove moment` for this one.

**Comment by Arjun3023** [comment]
Install moment: "2.24.0". It'll fix the issue and let's hope they release a stable build asap

**Comment by ichernev** [comment]
2.25.2 should address this issue, you might need to change webpack config to exclude the now-autobundled locales.

**Comment by silverwind** [comment]
[This](https://github.com/facebook/create-react-app/blob/5a019e6ce20cd9dd1ff67009d8dedf4daa6abab2/packages/react-scripts/config/webpack.config.js#L684) should still suffice to exclude locales, right?
