### ISSUE TITLE
Sometimes show "0 seconds"

### ISSUE THREAD

**Issue by Hugovidafe** [moment/moment#5504]
When `moment.duration is "604800000"` it shows `1 week`, but when `moment.duration is "604800100"`, it shows `0 seconds` instead of `1 week, 0 days, 0 hours, 0 minutes and 1 second`.

**Comment by Hugovidafe** [comment]
I don't know why, but is resolved, sorry for the inconvenience...

**Comment by Hugovidafe** [comment]
![image](https://user-images.githubusercontent.com/37117197/80928055-48927e80-8da2-11ea-8e55-7fd9c2ea15ec.png)
![image](https://user-images.githubusercontent.com/37117197/80928073-619b2f80-8da2-11ea-8d2a-c6312f00fcfa.png)

I don't understand... Why is it failing?

**Comment by Hugovidafe** [comment]
Sometimes, the result is `0 seconds`

**Comment by Alanscut** [comment]
@Hugovidafe It should be "1 millisecond".

<img width="251" alt="issue_5504" src="https://user-images.githubusercontent.com/21104054/81468454-4b61f900-9212-11ea-9484-8423340f8578.png">

**Comment by Alanscut** [comment]
@Hugovidafe It should be "1 millisecond".

 ![image](https://user-images.githubusercontent.com/21104054/81468454-4b61f900-9212-11ea-9484-8423340f8578.png)

**Comment by Hugovidafe** [comment]
> ![image](https://user-images.githubusercontent.com/37117197/80928055-48927e80-8da2-11ea-8e55-7fd9c2ea15ec.png)
> ![image](https://user-images.githubusercontent.com/37117197/80928073-619b2f80-8da2-11ea-8d2a-c6312f00fcfa.png)
> 
> I don't understand... Why is it failing?

See in the second photo, the numbers are time in milliseconds...

**Comment by Alanscut** [comment]
@Hugovidafe I am using the latest version
```
let du = moment.duration(3661000).seconds()
console.log('ISO_8601:', du) // 1 
```
<img width="244" alt="Snipaste_2020-05-09_17-38-59" src="https://user-images.githubusercontent.com/21104054/81470184-1064c300-921c-11ea-9fcf-7e2906978a1f.png">

**Comment by marwahaha** [comment]
@Hugovidafe I'm pretty confused by this setup.
Could you copy-paste some code so that someone else can reproduce?

**Comment by Hugovidafe** [comment]
```
const moment = require("moment");
require("moment-duration-format");
moment.updateLocale('en', {
    durationLabelsStandard: {
        s: langs.__({phrase: 'time.second', locale: database.getUserInfo('user.lang')}),
        ss: langs.__({phrase: 'time.seconds', locale: database.getUserInfo('user.lang')}),
        m: langs.__({phrase: 'time.minute', locale: database.getUserInfo('user.lang')}),
        mm: langs.__({phrase: 'time.minutes', locale: database.getUserInfo('user.lang')}),
        h: langs.__({phrase: 'time.hour', locale: database.getUserInfo('user.lang')}),
        hh: langs.__({phrase: 'time.hours', locale: database.getUserInfo('user.lang')}),
        d: langs.__({phrase: 'time.day', locale: database.getUserInfo('user.lang')}),
        dd: langs.__({phrase: 'time.days', locale: database.getUserInfo('user.lang')}),
        w: langs.__({phrase: 'time.week', locale: database.getUserInfo('user.lang')}),
        ww: langs.__({phrase: 'time.weeks', locale: database.getUserInfo('user.lang')}),
        M: langs.__({phrase: 'time.month', locale: database.getUserInfo('user.lang')}),
        MM: langs.__({phrase: 'time.months', locale: database.getUserInfo('user.lang')}),
        y: langs.__({phrase: 'time.year', locale: database.getUserInfo('user.lang')}),
        yy: langs.__({phrase: 'time.years', locale: database.getUserInfo('user.lang')})
    },
})
const duration = moment.duration(message.client.uptime).format(`y __, M __, w __, d __, h __, m __ [${langs.__({phrase: 'time.and', locale: database.getUserInfo('user.lang')})}] s __`);

console.log(duration)
```

**Comment by Hugovidafe** [comment]
```
const moment = require("moment");
require("moment-duration-format");
moment.updateLocale('en', {
    durationLabelsStandard: {
        s: second,
        ss: seconds,
        m: minute,
        mm: minutes,
        h: hour,
        hh: hours,
        d: day,
        dd: days,
        w: week,
        ww: weeks,
        M: month,
        MM: moths,
        y: year,
        yy: years
    },
})
const duration = moment.duration(message.client.uptime).format(`y __, M __, w __, d __, h __, m __ [and] s __`);

console.log(duration)

```

**Comment by marwahaha** [comment]
Thanks for opening this request.
This might be an issue with the plugin https://github.com/jsmreese/moment-duration-format
I would check with them first.
Best of luck.
