### ISSUE TITLE
Getting error on install Error: Cannot find module './locale'

### ISSUE THREAD

**Issue by ifen** [moment/moment#5506]
Seems like an error introduced in version 25.

It's affecting all installations across all versions, please resolve this, as I would like to use the latest moment version :( I will downgrade temporarily to version 24.

**Comment by RedShift1** [comment]
Here's the error I'm getting:

```
 INFO  Starting development server...
98% after emitting CopyPlugin

 WARNING  Compiled with 1 warnings                                                                                                                                                                                                                               11:28:56

 warning  in ./node_modules/moment/src/lib/locale/locales.js

Module not found: Error: Can't resolve './locale' in 'C:\Users\<redacted>\Documents\GitHub\<redacted>\node_modules\moment\src\lib\locale'
```

**Comment by Mokette** [comment]
Hi !
Got the same error with version 2.25.1 (have to rollback to version 2.24 for all working well)
Regards

**Comment by Arjun3023** [comment]
Change the version to "2.24.0". It'll work. Keep on checking for the latest fixes though. Until then, use 2.24.0 version :)

**Comment by ichernev** [comment]
2.25.2 addresses this issue. If this is about a bundler, now that it finds the locales it will also probably autobundle them. If you don't want that you'll need to change your bundler configuration.
