### ISSUE TITLE
export 'duration' (imported as 'moment') was not found in 'moment

### ISSUE THREAD

**Issue by 2RajShaikh** [moment/moment#5507]
In .ts file, we have imported moment as mentioned below

`import * as moment from 'moment';`

and then in the same file, we are using moment as 
`moment.duration(totalTimeSpent).humanize()`

This was used to work on 2.24.* releases but due to latest 2.25 release we are getting below error message,

```
ERROR in '.ts'
"export 'duration' (imported as 'moment') was not found in 'moment'
```

**Comment by Mokette** [comment]
Hi !
Got the same error with version 2.25.1 (have to rollback to version 2.24 for all working well)
Regards

**Comment by 2RajShaikh** [comment]
Thank you @Mokette 
Your suggestion works fine for now.
But, is this a bug in 2.25? or I need to modify my code to get it working?
Can someone please help? I do not want to add a hard dependency on 2.24.

**Comment by Mokette** [comment]
I think it's a small bug which gonna be fix by the dev team of this project
Cause several issues are open regarding the 2.25.1 version 

 - this one, the https://github.com/moment/moment/issues/5506, the https://github.com/moment/moment/issues/5501, the https://github.com/moment/moment/issues/5500, and maybe some others (haven't check all recently open issues, but i guess when one will be fix it's gonna solved many of them)

**Comment by tuuling** [comment]
Can confirm that this bug still exists on 2.25.2

**Comment by tuuling** [comment]
So.. a "fix" for this is to:
use `import moment from 'moment'` instead of `import * as moment from 'moment';`
and enable flags in tsconfig compilerOption ( "esModuleInterop" only should work but my IDE/ESLint wanted both)
```
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
```
This seems to be actually the prefered way since TS2.7 read the "`Support for import d from "cjs"` " part https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html 

I also had to tweak my ESlint settings for import:
```
    "import/no-duplicates": "off",
    "import/default": "off",
```
because stuff like this triggered both errors:
```
import moment from 'moment';
import { Duration, Moment } from 'moment';
```

**Comment by marwahaha** [comment]
Does this work on 2.25.3 ?

**Comment by Mokette** [comment]
It works well with 2.25.3
And i haven't change my compiler otpion or the way to import it to make it works
`import * as moment from 'moment';`
i don't use an humanize on my duration, but the .duration works well too
`moment.duration(momentEnd.diff(momentStart))`

**Comment by marwahaha** [comment]
Please re-open if you still have issues.

**Comment by pra-richardg2-sportsbet** [comment]
I am getting this with 2.3.2
