### ISSUE TITLE
moment.momentProperties is undefined in version 2.25.2 (all 2.25 versions)

### ISSUE THREAD

**Issue by benneq** [moment/moment#5509]
**Describe the bug**
After upgrade from `2.24.0` to `2.25.x` (tested all 2.25 versions) `fullcalender 3.10.1` throws error `Cannot read property 'push' of undefined` for this line:
```
var momentProperties = moment.momentProperties;
momentProperties.push('_fullCalendar');
```

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Browser: Chrome 81

**Additional context**
Didn't find any mention of a breaking change in CHANGELOG.md

**Comment by ichernev** [comment]
WTF is momentProperties?

**Comment by benneq** [comment]
I don't know. But it's in the source code: https://github.com/moment/moment/search?q=momentProperties&unscoped_q=momentProperties

**Comment by marwahaha** [comment]
@benneq  - can you try 2.25.3 ?

**Comment by benneq** [comment]
@marwahaha Thanks for the hint! Seems to work with version 2.25.3
