### ISSUE TITLE
moment.version is undefined in version 2.25.2

### ISSUE THREAD

**Issue by santosh-1987** [moment/moment#5510]
**Describe the bug**
 moment-timezone is breaking as moment.version returns undefined in version 2.25.2
**To Reproduce**
Easily Reproducible with moment-timezone

**Screenshots**
<img width="664" alt="Screenshot 2020-05-04 at 8 11 33 PM" src="https://user-images.githubusercontent.com/1287616/80979423-f48ca600-8e44-11ea-9a66-911c2f4df603.png">

**Desktop (please complete the following information):**
 - OS:  ALL
 - Browser ALL
 - Version 2.25.2

**Comment by YoannDelpierre** [comment]
There is already an issue too on moment timezone https://github.com/moment/moment-timezone/issues/838

**Comment by faeron** [comment]
Had the same issue, should be fixed now in 2.25.3

**Comment by marwahaha** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
