### ISSUE TITLE
moment.locale("fr") working in 2.24.0 but not since 2.25.0

### ISSUE THREAD

**Issue by flahol** [moment/moment#5511]
**Describe the bug**
As the title suggests moment.locale("fr") is not working since 2.25.0

**To Reproduce**
in v 2.24.0
moment.locale('fr');
if date is 2020-05-04 (y-m-d)
moment.utc(date).local().format("L") returns 04/05/2020, correct

in v 2.25.0, without changing any code
moment.utc(date).local().format("L") returns **05/04**/2020, wrong should be 04/05/2020

**Additional context**

 ```
    "dependencies": {
        "@vue/composition-api": "^0.3.4",
        ...,
        "moment": "2.24.0",
        "vue": "^2.6.11",
        "vue-i18n": "^8.17.4",
        "vue-router": "^3.1.6",
        "vuetify": "^2.2.26",
        "vuex": "^3.3.0",
        "webpack": "^4.43.0"
    },
    "devDependencies": {
        "@mdi/js": "^5.1.45",
        "@vue/cli-plugin-babel": "^4.3.1",
        "@vue/cli-plugin-eslint": "^4.3.1",
        "@vue/cli-plugin-router": "^4.3.1",
        "@vue/cli-plugin-vuex": "^4.3.1",
        "@vue/cli-service": "^4.3.1",
        "@vue/eslint-config-prettier": "^6.0.0",
        "babel-eslint": "^10.1.0",
        "eslint": "^6.8.0",
        "eslint-plugin-prettier": "^3.1.3",
        "eslint-plugin-vue": "^6.2.2",
        "moment-locales-webpack-plugin": "^1.2.0",
        "prettier": "^1.19.1",
        "sass": "^1.26.5",
        "sass-loader": "^8.0.2",
        "vue-cli-plugin-vuetify": "^2.0.5",
        "vue-template-compiler": "^2.6.11",
        "vuetify-loader": "^1.4.3"
    }
```

**Comment by rhyanrandolph** [comment]
I'm having the same issue since updating from 2.24.0 to 2.25.2.

**Comment by hong823** [comment]
We also have this similar issue when our dependency automatically upgraded to `2.25.2` and it breaks our application as well without changing any code or upgrading any of our dependencies.

The dependency we were using is https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/package.json

Specifically, our dependencies would do an automatic upgrade as shown below.

```
  "dependencies": {
    ...
    "moment": "^2.10",
    ...
  },
```

We had to rollback our previous to fix this breaking changes temporarily.

**Comment by hong823** [comment]
Upgrade to `2.25.3` seems to fix the issue now.

**Comment by flahol** [comment]
I confirm that `2.25.3` solve the problem.
