### ISSUE TITLE
.format() not completing before thread continues!

### ISSUE THREAD

**Issue by PowrSlave** [moment/moment#5516]
Imagine this simple code: 

items.forEach(function(item){
        item.prettyCreatedDate = moment(item.createdAt).format('ddd, MMM Do'); //this is not really synchronous?
        switch (item) {
          case 'fruit':
            fruits.push(item)
            break;
          case 'veggie':
            veggies.push(item)
            break;
        }
      });
      console.log(items); //duplicates first several array items, but not all of them

The switch statement after the moment.format() is pushing duplicate elements. If I comment out the monent.format() line, the resultant array is correct and has no duplicates. What the heck is going on here?

I created a plunker, but sadly, it works as expected: https://codepen.io/zachariah-michaelonious-aquinas/pen/BaoYLgW

**Comment by marwahaha** [comment]
Thanks for opening this request.
I also can't reproduce this.
I don't think there is any asynchronous code in Moment.
Perhaps `items` has duplicate items in the list, so `fruits` and `veggies` are also getting duplicates.

Best of luck with your debugging!
