### ISSUE TITLE
moment().format('DD/MMMM/YY') error in MMMM

### ISSUE THREAD

**Issue by moshab97** [moment/moment#5517]
**Describe the bug**
when trying to use moment().format('DD/MMMM/YY') and it gives me error in the MMMM month format with the following message "Cannot read property '3' of undefined", the number belongs to the month of the trying to convert

I use the npm package

**To Reproduce**
Write moment().format('DD/MMMM/YY')

**Expected behavior**
return the date with expected format

![image](https://user-images.githubusercontent.com/44683202/81254198-078fa980-8ff0-11ea-96cd-eb3f464672e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chromium Microsoft Edge
 - 81.0.416.68

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()): "Wed May 06 2020 22:15:08 GMT-0500 (Central Daylight Time)"
console.log((new Date()).toLocaleString()): "5/6/2020, 10:15:29 PM"
console.log((new Date()).getTimezoneOffset()): 300
console.log(navigator.userAgent): "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 Edg/81.0.416.68"
console.log(moment.version): 2.25.3
```

I  use the npm package

**Comment by PathfinderX** [comment]
moment().format('DD/MMMM/YY')

**Comment by moshab97** [comment]
> moment().format('DD/MMMM/YY')

Sorry, i forgot write this in the issue
