### ISSUE TITLE
[BUG]Executing npm run coveralls error in windows

### ISSUE THREAD

**Issue by Alanscut** [moment/moment#5528]
**Describe the bug**
Executing `npm run coveralls` error in windows, this seems to be a common error, and no clear solution has been found in the community.

**To Reproduce**
```
 npm run coveralls
```
**Screenshots**

<img width="619" alt="coveralls_bug" src="https://user-images.githubusercontent.com/21104054/81652157-e0a8fb80-9465-11ea-84b5-c8022bf172ae.png">

**Expected behavior**
Should not report an error

**Possible solution (optional, but very helpful)**
Personally, I can use `codecov` instead of `coveralls`. I tested it locally and it works very well，maybe Can fix the problems mentioned in `.travis.yml`, what do you think  @ichernev @marwahaha  😄?

**Comment by Alanscut** [comment]
See https://stackoverflow.com/questions/31966582/travis-ci-and-coveralls

**Comment by marwahaha** [comment]
I prefer Coveralls. Do you think there is a way forward?
I don't think it's necessary that developers use Coveralls locally, since it runs on Travis...

**Comment by Alanscut** [comment]
I have a comparison between codecov and coveralls. There is not much difference between them. I will close the issue.
