### ISSUE TITLE
[locale] capitalize month and day names in FR-* locales

### ISSUE THREAD

**Issue by alabenkhlifa** [moment/moment#5541]
**Describe the bug**
In EN Locals, the month name and day of week name are capitalized but in FR locals they aren't capitalized.

**To Reproduce**
1. Check any date with EN locals
2. Check any date with FR locals

**Expected behavior**
FR month name or day of week name are Capitalized

**Comment by marwahaha** [comment]
cc @jfroffice thoughts?

**Comment by marwahaha** [comment]
Please tag the locale author if you have a locale-specific question.

**Comment by agrounds** [comment]
It is expected that names of days of the week and months are _not_ capitalized in French. In French, these are not proper nouns, so they don't have to be capitalized, as opposed to English in which they are always capitalized.

I vote to close

**Comment by jfroffice** [comment]
+1 to close
