### ISSUE TITLE
Moment from object returns wrong date (2.25.3)

### ISSUE THREAD

**Issue by shashane** [moment/moment#5542]
**Describe the bug**
Create moment instance from object returns wrong date

**To Reproduce**
```
var m = moment({day: 1, month: 4, year: 2020})
console.log(m.format('DD/MM/YYYY') // Writes output 31/05/2020
```

**Expected behavior**
01/05/2020

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [2.25.3]

**Moment-specific environment**
node JS

* Other libraries in use (TypeScript, Immutable.js, etc)
vue js
moment_recur

**Comment by marwahaha** [comment]
Thanks for opening this request.
Hi! Thanks for filing this issue! Unfortunately, I can't reproduce this. Could you provide any other information? Like your timezone, locale, and so on.

**Comment by shashane** [comment]
Hi,

Sorry, I just restore 2.25.3 version in my project but cannot reproduce it anymore.

So, Either I'm tired or just a side effect in dirty code ;-)

Next time, I will test better !!

Best regards.
