### ISSUE TITLE
A function to dehumanize dates

### ISSUE THREAD

**Issue by prateek3255** [moment/moment#5549]
**Is your feature request related to a problem? Please describe.**
I am in a situation where I have dates in humanize form like 'a day ago' and I want a moment date object from this string.

**Describe the solution you'd like**
Create a function called `moment.dehumanize`, which takes in a string argument specifying the humanized date and return a moment date object. I  know this will be very inaccurate in cases like a year ago, but maybe we can give the user an option for a threshold and return Invalid date if the date does not satisfy that threshold.

P.S. I would love to work on it if you're moving forward with this feature.

**Comment by marwahaha** [comment]
Hi, nice idea. 
I think this would be best suited as a Moment.js plugin. People will get different results for this based on their relativeTimeThresholds -- and the calculations would be very approximate.
If you make a plugin, then people can use it if they desire. 
https://momentjs.com/docs/#/plugins/

**Comment by prateek3255** [comment]
Thanks, @marwahaha . I'll try and create a plugin for it.
