### ISSUE TITLE
Is it possible to access `fromNow` with localized locale data?

### ISSUE THREAD

**Issue by colemars** [moment/moment#5550]
Like with Duration we have `moment.duration().locale(String);`. 

Essentially to be able to display a list of moments with different locale data:

```
<div>moment.fromNow(string).locale(en)</div>
<div>moment.fromNow(string).locale(fr)</div>
<div>moment.fromNow(string).locale(hu)</div>
```

**Comment by marwahaha** [comment]
I'm not sure what you mean.
Do you want to display fromNow in different locales?
Try 
```
<div>moment..locale(en).fromNow(string)</div>
<div>moment.locale(fr).fromNow(string)</div>
<div>moment.locale(hu).fromNow(string)</div>
```

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.
