### ISSUE TITLE
TypeScript error TS2430: Interface 'Moment' incorrectly extends interface 'Object'.

### ISSUE THREAD

**Issue by Taytay** [moment/moment#5559]
I get the following error when using moment with the the latest version of Typescript (3.9.3) and Moment (2.26.0): 

`TypeScript error TS2430: Interface 'Moment' incorrectly extends interface 'Object'.`

This was reported in #4459, but closed because it was expected to be fixed in Typescript 3. Is this considered a known issue?

```
../node_modules/moment/ts3.1-typings/moment.d.ts:426:13 - error TS2430: Interface 'Moment' incorrectly extends interface 'Object'.
  The types returned by 'valueOf()' are incompatible between these types.
    Type 'number' is not assignable to type 'Object'.

426   interface Moment extends Object {
```

Silly question: Does Moment actually need to extend `Object` here?

**Comment by marwahaha** [comment]
Sorry you are experiencing this.
I don't know how to fix this that still supports TS users of 1.x, 2.x, 3.x.

This may help in the meantime: https://github.com/moment/moment/issues/4459#issuecomment-461077403

We will look at PRs in this area.

**Comment by Alanscut** [comment]
@Taytay See [FAQ.md](https://github.com/moment/moment/blob/develop/FAQ.md), Maybe related to #5348 .

**Comment by Alanscut** [comment]
@Taytay I can't reproduce this problem，Can you please create a [codepen](https://codepen.io/pen) demonstrating the issue? I am very interested in the problem, thanks 😄 .

##  Environment
React@16.9.0 + typescript@3.9.3 + moment@2.26.0

## tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}
``` 

## Code 
```typescript
import moment, { Moment } from "moment";
import "moment/locale/zh-cn";

export function fixIssue5559() {
  const start: Moment = moment("2017-01-05");
  console.log("toString", typeof start.toString());
  console.log("valueOf", typeof start.valueOf());
}
```

**Comment by Taytay** [comment]
Oh! That might indicate I'm doing something wrong on my end! I'll take another look and let you know when/if I can repro. Thank you!

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.
