### ISSUE TITLE
Typescript 3.8.3 + Angular 9 - moment"' has no exported member 'default'.

### ISSUE THREAD

**Issue by xyakayx** [moment/moment#5563]
1 - Install the package 

` npm install moment   
`

2 - Load the module
```
import {MAT_MOMENT_DATE_FORMATS, MomentDateAdapter} from '@angular/material-moment-adapter';
import {DateAdapter, MAT_DATE_FORMATS, MAT_DATE_LOCALE} from '@angular/material/core';

// Depending on whether rollup is used, moment needs to be imported differently.
// Since Moment.js doesn't have a default export, we normally need to import using the `* as`
// syntax. However, rollup creates a synthetic default module and we thus need to import it using
// the `default as` syntax.

import * as _moment from 'moment';
// tslint:disable-next-line:no-duplicate-imports
import {default as _rollupMoment} from 'moment';

const moment = _rollupMoment || _moment;
```

Tsconfig file

```
 "moduleResolution": "node",
"allowSyntheticDefaultImports": true,
```

package.json:

`  "dependencies": {
    "@angular/animations": "^9.1.7",
    "@angular/cdk": "^9.2.3",
    "@angular/common": "^9.1.7",
    "@angular/compiler": "^9.1.7",
    "@angular/core": "^9.1.7",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^9.1.7",
    "@angular/material": "^9.2.3",
    "@angular/material-moment-adapter": "^9.2.4",
    "@angular/platform-browser": "^9.1.7",
    "@angular/platform-browser-dynamic": "^9.1.7",
    "@angular/router": "^9.1.7",
    "@ng-idle/core": "^8.0.0-beta.4",
    "@ng-idle/keepalive": "^8.0.0-beta.4",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-cc-library": "^2.0.1",
    "angular2-text-mask": "^9.0.0",
    "bootstrap": "^4.5.0",
    "core-js": "^3.6.5",
    "file-saver": "^2.0.2",
    "jquery": "^3.5.1",
    "moment": "^2.26.0",
    "ng-broadcaster": "^9.1.1",
    "ng2-pdf-viewer": "^6.3.0",
    "ng2-pdfjs-viewer": "^5.0.7",
    "ngx-cookie-service": "^3.0.4",
    "ngx-currency": "^2.3.3",
    "ngx-filter-pipe": "^2.1.2",
    "ngx-google-places-autocomplete": "^2.0.4",
    "ngx-markdown": "^9.1.0",
    "ngx-mask": "^9.0.2",
    "ngx-smart-modal": "^7.4.0",
    "ngx-smart-popover": "^1.4.0",
    "ngx-spinner": "^9.0.2",
    "ngx-uploader": "^8.0.0",
    "ngx-validators": "^5.2.1",
    "node-sass": "^4.14.1",
    "rxjs": "^6.5.5",
    "text-mask-addons": "^3.8.0",
    "tslib": "^2.0.0",
    "uuid": "^8.0.0",
    "zone.js": "^0.10.3"
  },`

Error:

Module '".... node_modules/moment/ts3.1-typings/moment"' has no exported member 'default'.ts(2305)

**Comment by marwahaha** [comment]
What is `_rollupMoment`?

**Comment by Alanscut** [comment]
@xyakayx  See [FAQ.md](https://github.com/moment/moment/blob/develop/FAQ.md), Maybe related to #5348 .

**Comment by marwahaha** [comment]
I don't think this issue should be fixed in Moment.js.
