### ISSUE TITLE
Dates without leading zeroes parsed incorrectly in Firefox & Safari

### ISSUE THREAD

**Issue by kaitlynbrown** [moment/moment#5564]
When moment.js is used to parse a date with a leading zero missing in the day (eg "1979-07-4" instead of "1979-07-04"), it seems to work fine in chromium-based browsers (tested in Chrome, Edge & Brave), but in Firefox the parsed date is one day earlier (it shows up as 1979-07-03), and in Safari, moment is unable to parse the date, considering it to be an invalid date.

A big part of the reason for using moment.js is to avoid these kinds of differences between browsers, so it's surprising to me to see this behaviour differ between chromium-based browsers and other browsers.

Another big part of the reason for using moment.js is its ability to handle dates in almost any format, so it's also surprising to me that something as simple as a missing leading zero would trip it up so badly. It should be capable of handling these sorts of minor inconsistencies when the date is still clearly and unambiguously parseable, as the above date is.

**Comment by marwahaha** [comment]
Sorry you're experiencing an issue.

Did you see the deprecation warning? It should happen the first time you try it:
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
```

I would recommend passing a number of acceptable formats in when you parse dates:
https://momentjs.com/docs/#/parsing/string-formats/

**Comment by kaitlynbrown** [comment]
I've already fixed the issue on my end by fixing the formatting of the dates we had stored, I'm just making a bug report here because this seems like something moment.js should be able to handle better (indeed, a big part of the reason to use moment.js is to more gracefully handle situations like this)

**Comment by marwahaha** [comment]
Thanks for the report. I'll mark it accordingly.

**Comment by greddyatpt** [comment]
While passing in a list of patterns is very useful and can be used as a workaround for this common issue, [Java](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html) solves it elegantly by interpreting a single pattern letter as: 2 or 4 digit year; 1 or 2 digit month;  1 or 2 digit day.  This applies to both parsing and formatting.  When implemented in moment.js, the pattern "Y年M月D日" would stand in for the following 8 patterns:  
```
"YY年M月D日"
"YY年M月DD日"
"YY年MM月D日"
"YY年MM月DD日"
"YYYY年M月D日"
"YYYY年M月DD日"
"YYYY年MM月D日"
"YYYY年MM月DD日"
```
In the absence of this, it's tempting to use the FORGIVING mode, which is too forgiving IMHO (123 is a valid year!?).  The STRICT mode could use a couple of things from the FORGIVING mode though:  ignore spaces and recognize embedded values as in "abc 2020/10/24 xyz".  If compatibility is important, then a new SMART mode please:
- Single pattern letters with the above Java-like semantics
- Discard spaces before after datetime fields as in "2020 年 12 月 2 日" (with "Y年M月D日" as the pattern) but NOT within fields as in "20 20年1 2月 2 日".
- Recognize embedded values as in "abc 2020/10/24 xyz"

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
