### ISSUE TITLE
parseZone does not work as documented for ambiguous offset

### ISSUE THREAD

**Issue by samherrmann** [moment/moment#5569]
**Describe the bug**

Consider the following [documentation](https://github.com/moment/momentjs.com/blob/75f131855b96252b0d2ccaf2431c5ac929428a11/docs/moment/01-parsing/00-intro.md):
> `moment.parseZone()` keep the input zone passed in. If the input is ambiguous, it is the same as local mode.

The following two lines have an ambiguous input (without offset):
```js
moment('2020-05-28T02:54:09').utcOffset() // returns the local UTC offset (-240 in my case)
moment.parseZone('2020-05-28T02:54:09').utcOffset() // returns 0
```

**To Reproduce**
https://stackblitz.com/edit/js-8bpdev

**Expected behavior**
Based on the documentation I would expect `moment.parseZone(...)` to return the local UTC offset, the same as `moment(...)`, when the input does not specify an offset.

Additionally, if the input is ambiguous and therefore treated as local, then I would expect `moment.parseZone(...).isLocal()` to return `true` but it currently returns `false`.

**Moment-specific environment**

```
Thu May 28 2020 12:55:35 GMT-0400 (Eastern Daylight Time)
5/28/2020, 12:55:35 PM
240
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
2.26.0
```

**Comment by marwahaha** [comment]
Thanks for opening this request.
Perhaps the documentation is wrong. Maybe someone can trace the logic of `parseZone`; it looks like it parses in UTC when the offset is not given.

**Comment by Rich-Wu** [comment]
I would like to work on this issue.

**Comment by Rich-Wu** [comment]
Current tests indicate that the current behavior (setting offset to 0 when no offset is provided) is intended behavior, but conflicts with the documentation. Please clarify

**Comment by marwahaha** [comment]
@Rich-Wu Please update the documentation, let's leave the existing functionality.
