### ISSUE TITLE
UTC offset is not being validated

### ISSUE THREAD

**Issue by samherrmann** [moment/moment#5572]
**Describe the bug**
The UTC offset in a date/time string is not being validated.

**To Reproduce**

Example: UTC offset of `-99:00`:
```
console.log(moment.parseZone('2020-05-28T02:54:09-99:00').isValid())
// Returns true
```
https://stackblitz.com/edit/js-pajunu

**Expected behavior**
I would expect that the return value in the example above would return false.

**Moment-specific environment**

```
Fri May 29 2020 17:59:23 GMT-0400 (Eastern Daylight Time)
5/29/2020, 5:59:23 PM
240
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
2.26.0
```

**Comment by marwahaha** [comment]
Why would this be false?

**Comment by samherrmann** [comment]
I think I see why you are asking this question and why you could argue that an offset of `-99:00` is in fact valid. But if you say that an offset of `-99:00` is valid, then I ask why is `2020-05-28T02:54:99-99:00` (i.e. note the `99` seconds) not valid? That is just one example. You could ask the same question about minutes, hours, days, months, or years.

**Comment by samherrmann** [comment]
Here are some examples that I was playing around with:

```
2020-01-01T00:00:00-99:00 - valid? true
2020-01-01T00:00:00-00:99 - valid? true
2020-01-01T00:00:99-00:00 - valid? false
2020-01-01T00:99:00-00:00 - valid? false
2020-01-01T99:00:00-00:00 - valid? false
2020-01-99T00:00:00-00:00 - valid? false
2020-99-01T00:00:00-00:00 - valid? false
```
https://stackblitz.com/edit/js-3m1qkb

**Comment by marwahaha** [comment]
Thanks for the examples.
How do you represent a UTC offset above 24 hours? 
For example, with 99 seconds, you can use minutes; with 99 minutes, you can use hours; etc.

**Comment by samherrmann** [comment]
I would expect it to roll over the day:

2020-01-**01**T01:00:00<b>+24:00</b> === 2020-01-**02**T01:00:00<b>+00:00</b>
2020-01-**01**T01:00:00<b>+25:00</b> === 2020-01-**02**T01:00:00<b>+01:00</b>
2020-01-**01**T01:00:00<b>+26:00</b> === 2020-01-**02**T01:00:00<b>+02:00</b>

I do have to admit that I am by no means a "time expert". The more time I spend looking into this (no pun intended 😄 ), the more I discover that is completely new to me. For example, I always thought that time zones ranged from UTC-12:00 to UTC+12:00, but they actually range from [UTC-12:00 to UTC+14:00](https://en.wikipedia.org/wiki/List_of_UTC_time_offsets). So doesn't that mean that the allowable offset should be -12 to +14?

**Comment by marwahaha** [comment]
What if countries change their offset beyond -12 or +14?

For default parsing, we eventually defer to ISO 8601 or the browser-specific Date() constructors.
https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC

Because the offset range is not specified (unlike seconds, minutes, hours), I think -99 to +99 is ok.

So I don't think Moment.js should change behavior here.

Please re-open if you still have thoughts.
