### ISSUE TITLE
moment().calendar() returns current time when parsing an ISO 8601 formatted string

### ISSUE THREAD

**Issue by fuzzbomb7** [moment/moment#5577]
I'm using moment().format() to output a string in ISO 8601 format, and storing that string to the db. When I recall that string later and parse it using moment(), and pass the resulting moment object to the moment().calendar() function, it seems not to recognize the time, returning the current time instead. I'm using moment 2.14.1.

Here's the example code:

```
let time = "2020-06-01T19:00:00-05:00";
let momentTime = moment(time);
let calendarTime = moment().calendar(momentTime);
console.log(momentTime.format());
console.log(calendarTime);
```

Example output:

```
"2020-06-01T19:00:00-05:00"
"Today at 6:33 PM"
```

Expected output:

```
"2020-06-01T19:00:00-05:00"
"Today at 7:00 PM"
```

 - OS: Windows
 - Browser: Chrome
 - Version: 83

**Comment by fuzzbomb7** [comment]
Okay, so after some additional research, I discovered that I was passing the time to the wrong function. This code produces the expected output:

```
let time = "2020-06-01 19:00";
let momentTime = moment(time);
let calendarTime = moment(momentTime).calendar();

Output: "Today at 7:00 PM"
```

However, the documentation does not make it clear that this is the correct syntax to generate a calendar time relevant to the current moment for a given date. I even tried googling for examples. Perhaps add a few usage examples for this function to make our lives easier?

**Comment by marwahaha** [comment]
Sorry this caused you frustration.

I think the [docs](https://momentjs.com/docs/#/displaying/calendar-time/) are ok for now (call .calendar() on the existing moment object). I don't know how to make it clearer, but you are welcome to contribute to 
https://github.com/moment/momentjs.com/ .
