### ISSUE TITLE
TS2307 Cannot find module 'moment/min/moment-with-locales'

### ISSUE THREAD

**Issue by sergeyshmakov** [moment/moment#5578]
**Describe the bug**
Cannot import `moment/min/moment-with-locales` because of Typescript error.

**To Reproduce**
Open any project with latest Typescript
Type `import moment from "moment/min/moment-with-locales";`
Run `tsc`
See the error `TS2307 Cannot find module 'moment/min/moment-with-locales'`

**Expected behavior**
Import without error with full types support.

**Screenshots**
![image](https://user-images.githubusercontent.com/7429684/83497710-4cfea400-a4d4-11ea-8456-b1f32f59f2b6.png)

![image](https://user-images.githubusercontent.com/7429684/83497736-54be4880-a4d4-11ea-864e-251f0a5762b9.png)

Without any types definitions:

![image](https://user-images.githubusercontent.com/7429684/83497764-5f78dd80-a4d4-11ea-9c84-c84703da94d9.png)

**Version:**
 - From `2.25.0` to  `2.26.0`

The last working version for this bug is `2.24.0`

#4946

**Comment by Alanscut** [comment]
I use `require` and it will no longer report an error and work very well, but I don’t understand why this phenomenon exists. can someone tell this problem? Thanks in advance!

```TypeScRIPT
const moment = require('moment/min/moment-with-locales');
```

**Comment by marwahaha** [comment]
You may want to ask on StackOverflow.
