### ISSUE TITLE
date.startOf('day') modifying date object

### ISSUE THREAD

**Issue by vivex** [moment/moment#5582]
**Describe the bug**
I am using moment timezone and facing the following issue:

i created the date object using following code:
```js
let date = moment('2020-06-04T11:00:00.000+0000').tz('Asia/Calcutta');
```
and then for some computations i am using `date.startOf('day')` and then afterwards i am trying to get time from this date object `date.format('h:mm A')` which is always coming `12:00AM`, mean that date.startOf is modifying my date object, i was assuming that i wont modify and will just return the new object.

This behaviour is very confusing, 
Using date.clone().startOf() will solve the problem,

**Comment by Alanscut** [comment]
Hi vivex, Please see the [official website](https://momentjs.com/docs/#/manipulating/start-of/) and [source code](https://github.com/moment/moment/blob/develop/src/lib/moment/start-end-of.js#L34), `moment().startOf('day')` will set to 12:00 AM today and modifying `_d` attribute.

<img width="245" alt="moment" src="https://user-images.githubusercontent.com/21104054/83989002-90935b00-a977-11ea-8b90-299cca3a9950.png">
