### ISSUE TITLE
Add a token for days across multiple years similar to day of year.

### ISSUE THREAD

**Issue by RohanAntony** [moment/moment#5585]
**Is your feature request related to a problem? Please describe.**
I have daily data across multiple years in a dataset which is parsed asynchronously and stored into db. I need to order the data in a simple way while reading from the database using just numbers instead of ordering based on dates.

**Describe the solution you'd like**
A token like "DU" or "DDU" which generates the number of days from Jan 1st 1970. This would be a smaller number compared to the timestamp and easier to store. There is already an existing similar token "DDD" for day of the year. This token would be ideal across multiple years.

**Describe alternatives you've considered**
I use a unix timestamp which seems like an overkill as the value is much more larger than required. Alternative is to use combination of 2 fields "YYYY" and "DDD" for ordering.

**Additional context**
![image](https://user-images.githubusercontent.com/5779016/83939215-d83fa880-a7f8-11ea-85a2-fe9a494020a2.png)

**Comment by Alanscut** [comment]
@RohanAntony  You can try the following code，it should meet you needs.

```javascript
var a = moment('1970-01-01');
var b = moment('2020-06-09');
var c = moment('2020-06-10');
console.log('day1 = ', b.diff(a, 'days')); // day1 =  18422
console.log('day2 = ', c.diff(a, 'days')); // day2 =  18423
```

I'm not sure if we should add new tokens, what do you think @marwahaha @ichernev ? If necessary, I will be happy to submit a pull request😄.

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

We will not add new tokens.
