### ISSUE TITLE
.fromNow() and .from(new Date()) yielding different results

### ISSUE THREAD

**Issue by Floriferous** [moment/moment#5588]
**Describe the bug**

I'm running into trouble when trying to format a date relative to now. The date is sent from the client to our node server, and so it has just been set to `new Date()`. 

```js
moment(date).fromNow(); // In 2 hours - wrong by our local UTC offset

moment(date).from(new Date()); // A few seconds ago - The result I expect
```

I'm not sure I understand why I have to use the 2nd version. I'd expect both to yield the exact same result.

Here's what our node server returns for the console.logs:
```js
Tue Jun 09 2020 16:12:02 GMT+0200 (Central European Summer Time)
6/9/2020, 16:12:02
-120
undefined
2.25.3
```

**Comment by marwahaha** [comment]
Unfortunately, I cannot reproduce this.

Perhaps it has to do with the time on the node server.

You may want to try UTC mode.

Please re-open if you have more information we can help you with.
