### ISSUE TITLE
Getting Next/Previous Specific Month, Next/Prev Quarter, Next/Prev Specific Quarter

### ISSUE THREAD

**Issue by nycitt** [moment/moment#559]
I am writing some scripts to figure out the "next" or "previous" occurrence of a specific month, quarter, etc.

For example, I wrote a function for next occurrence of month

```
     /**
        @var date is a JS date or moment
        @var month is the month in the 0-11 format
     */
    var getNextMonthOccurrence: function(date, month){
        var m = moment(date);

        var this_year = new Date(m.year(), month, 1);
        var next_year = new Date(m.year() + 1, month, 1);

        return this_year > m ? this_year : next_year;
    }
```

It would be great if there were also function for:
- next xth quarter (ex: Now it's Jan 1 (1st Quarter). I would like to ask next 3rd quarter. It would return July 1.
- next quarter (ex: Now it's Jan 1 (1st Quarter). I would like to ask next quarter. It would return April 1 (start of 2nd Quarter)

**Comment by KongoSalim** [comment]
$m = date('m');
$qtr =  floor(($m - 1) / 3);
$m = ($qtr == 3) ? 1 : $qtr + 2;

I hope this is helpful.

Thanks,
Salim

**Comment by maxiejbe** [comment]
Probably too late :smile: @timrwood function has a little but important bug:

```
function nextMonth(date, month) {
  var input = moment(date);
  var output = input.clone().startOf('month').month(month);
  return output > input ? output : output.add(1, 'years');
}
```
Note that I'm cloning input, as moment objects are mutable.
Thanks!
