### ISSUE TITLE
duration() is "not a function" in 2.26.0

### ISSUE THREAD

**Issue by dylanh724** [moment/moment#5590]
in `2.26.0` (latest), I can type the following np:
```
const moment = require('moment');
const m = new moment(); // console prints the raw date
```
### However, if I want to add the duration...
`const d = m.duration();`
This results in **TypeError: (intermediate value).duration is not a function**

![image](https://user-images.githubusercontent.com/8840024/84232968-fb819500-ab23-11ea-8d59-616cdeaa1495.png)
![image](https://user-images.githubusercontent.com/8840024/84232758-8e6dff80-ab23-11ea-9032-dec9f72ba425.png)
^ Notice how `m` prints fine standalone on 1st log, but `m.duration()` crashes it on 2nd.

I also tried `moment.duration(100); // 100 milliseconds` from the docs, resulting in same err.

**Comment by Alanscut** [comment]
wrong usage of `moment`, if you want to create a `duration`, the right way is `var dur = moment.duration()`

**Comment by dylanh724** [comment]
I don't understand -- you're saying `const` causes weird things? `new` keyword shouldn't be added? `duration()` must be chained to the initial call?

**Comment by Alanscut** [comment]
if you would like to create or manipulate a Date object, then you should use moment constructor to create a Moment object first.
but the `duration` function is passed moment through hooks, so it can only be used through `moment.duration()`

maybe these example help you a lot: 
* https://momentjs.com/docs/#/durations/creating/
* https://momentjs.com/docs/#/durations/diffing/
* https://momentjs.com/docs/#/durations/creating/
```javascript
  var moment = require('moment');
  var x = new moment();
  var y = new moment();
  var duration = moment.duration(x.diff(y));
  // returns duration object with the duration between x and y
```

**Comment by marwahaha** [comment]
If there's a way to improve the documentation, please leave us a PR at https://github.com/moment/momentjs.com/
