### ISSUE TITLE
the reuslt of `moment.duration(1, 'year').subtract(1, 'hour').hours()` is not consistent with `1 year = 365.2425 days`

### ISSUE THREAD

**Issue by Alanscut** [moment/moment#5594]
**Describe the bug**
Hi @marwahaha ,there are some contradictory results in the `duration().subtract` method, which caused by bubble.js, #2928 has the similar problem. I have to say that duration processing is a tricky business, but I hope and am handling this issue.

before I submitting a PR,  I hope to get your opinion and guidance.

**To Reproduce**
from the testcase:
```
d = moment.duration(1, 'year').subtract(1, 'day').days(); 
// 30,  if we treat `year` as `365.2425 days`, then it shouldn't be 30, but should be 29
```
```
d = moment.duration(1, 'year').subtract(1, 'hour');

assert.equal(d.hours(), 23, '1 year - 1 hour == 23 hours (component)');  // may be wrong?
// shouldn't be 23 hours,
// 1 year = 11 month + 30 days + 0.436875 days
// 0.436875 days = 0.436875 * 24 hour = 10.485 hour = 10 hour, 29 minutes, 6 seconds
// so '1 year - 1 hour' = 11 months, 30 days, 9 hours, 29 minutes, 6 seconds


assert.equal(d.days(), 30, '1 year - 1 hour == 30 days (component)'); // ok
assert.equal(d.months(), 11, '1 year - 1 hour == 11 months (component)'); // ok
assert.equal(d.years(), 0, '1 year - 1 hour == 0 years (component)'); // ok
```

**Expected behavior**
as described above.

**Screenshots**

Please run the following code in your environment and include the output:
```
Thu Jun 11 2020 21:05:26 GMT+0800 (GMT+08:00)
2020-6-11 9:05:26 PM
-480
2.26.0
```

**Comment by ichernev** [comment]
Yes, moment doesn't handle duration just the way you want it to. We've had countless discussions in the past, and there is always somebody unhappy with the current situation.

If you want a year to be treated to 365.2425 days, just do the multiplication yourself.
