### ISSUE TITLE
day of week is wrong

### ISSUE THREAD

**Issue by anthonywebster** [moment/moment#5602]
![image](https://user-images.githubusercontent.com/3496319/84934977-502d8e80-b095-11ea-859b-6c6b7a0e83f1.png)

should return **2020-06-15** and returned **2020-06-14**

**Comment by MinusFour** [comment]
You are using a different locale from `us`? You should be using the locale version of the week day. E.g. if it's spanish, it's should be `lunes`.

**Comment by anthonywebster** [comment]
@MinusFour you have reason, Thank you.
