### ISSUE TITLE
The pt-Br locale should not be lowercase

### ISSUE THREAD

**Issue by GabrielGMartinsBr** [moment/moment#5617]
**Describe the bug**
For some reason the month names and the week days names got lowercased, as suggested by 
[this answer](https://stackoverflow.com/questions/35913934/uppercasing-monthnames-in-momentjs) on stackoverflow I'm opening this issue to request that this decision be reviewed, cause I think that this data should be capitalized as it was before.

**To Reproduce**
```
import * as moment from 'moment';
import 'moment/locale/pt-br';

console.log(moment.months());
```

or

```
const moment = require('moment');
require('moment/locale/pt-br');

console.log(moment.months());
```

The result is:

> (12) ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"]

**Expected behavior**
> (12) ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"]

**Moment-specific environment**
The time zone: **GMT-3**
Time and date at which the code was run: **Wed Jun 24 2020 02:32:01 GMT-0300 (Horário Padrão de Brasília)**
Moment Version: **2.26.0**

**Comment by beatrizrezener** [comment]
Hello @GabrielGMartinsBr,

For curiosity, is there a specific reason why you think that months in Portuguese should be capitalized?
I'm asking because according to Brazilian Portuguese language rules, the names of months and week days are written in lower case (Source: [Portuguese Language Website](http://www.portaldalinguaportuguesa.org/acordo.php%3Faction%3Dacordo%26id%3D16-49%26version%3D1943))

**Comment by GabrielGMartinsBr** [comment]
Hi @beatrizrezener ,

It’s because every calendar in Portuguese I’ve ever seen, the names of the months are all in uppercase or capitalized,
I made a schedule chart using moment, and the English version of this schedule the names of the months are capitalized, but in the Portuguese version, the names are all in lowercase, and it didn't feel right to me.

And also because I have the impression that in Portuguese it would only make sense to leave the names of the months in lowercase if they were being used in the middle of a sentence, but perhaps I am mistaken, since I am not sure which context the moment functions are expected to be called.

**Comment by leoviveiros** [comment]
It´s been capitalized on this library for all these years, why to change it now?

**Comment by marwahaha** [comment]
I don't think we would change it now; there seem to be a lot of sources preferring lowercase (from https://github.com/moment/moment/pull/4824)
