### ISSUE TITLE
PT - Weekdays should be lowercase

### ISSUE THREAD

**Issue by chenei** [moment/moment#5618]
Hi,
I looked at the issues and PRs and I found this PR:
https://github.com/moment/moment/pull/3989/files

I saw that it merged but looking into the locale file, I see that it's still lowercase.
https://github.com/moment/moment/blob/develop/locale/pt.js#L19

Is there any chance to fix it?

**Comment by marwahaha** [comment]
@jalex79 ?

**Comment by marwahaha** [comment]
@chenei I don't understand. What do you want to change?

The weekdays are not lowercase, but "feira" is lowercased in 
Segunda-feira

**Comment by marwahaha** [comment]
Please re-open if there is still an issue.
