### ISSUE TITLE
`defineLocale` for `en` errors with partial `relativeTime` customization

### ISSUE THREAD

**Issue by pvinis** [moment/moment#5619]
**Describe the bug**

I tried to define a locale with a parent, and only customize some of the `relativeTime` things like `dd`.

When the parent was `fr`, everything worked well. When the parent was `en`, I was getting an error `TypeError: format is undefined`.

**To Reproduce**
Links for repro:

Working (using `fr`): https://jsfiddle.net/3cf0p74b/3/

Failing (using `en`): https://jsfiddle.net/qhpnj5z1/

The main code there is
```
moment.defineLocale('en-custom', {
  parentLocale: 'en',
  relativeTime: {
    dd: "%d wowwwwwwww"
  }
})
```

Interestingly, if I add all the fields for `en`, then it works. Link: https://jsfiddle.net/3cf0p74b/6/

**Expected behavior**
I should be able to define a locale using a parent and some customization, only the parts and subparts I want to change, like just the `dd` string from `relativeTime` based on `en`.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 77

**Moment-specific environment**
```
"Wed Jun 24 2020 19:43:27 GMT+0200 (Central European Summer Time)"
"24/06/2020, 19:43:27"
-120
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0"
"2.13.0"
```

**Comment by MinusFour** [comment]
`defineLocale` does seem to be working properly. I have no idea why that build of `moment-with-locales` doesn't have a complete `en` locale but if you use a recent one, like this one:

https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment-with-locales.min.js

It does work.

**Comment by pvinis** [comment]
Iiiiiinteresting. I didn't even notice it was an old version 🤦. Thank you for the quick response. The new one does work correctly. I will close this.
