### ISSUE TITLE
Syntax error in Internet Explorer

### ISSUE THREAD

**Issue by derweise** [moment/moment#5621]
Hi,

I am using moment.js with Vue project.

When I run my application in Chrome, Firefox, etc.. everything works fine. But when I run in Internet Explorer, I get following error:

```
SCRIPT1002: Syntax error
chunk-vendors.6c81b9f3.js (221,42201)
```

The code it is referring to is always the line:

`toLocaleString(e):!0===e&&(n=t.toLocaleString()),n}`

So there is something wrong with the function `toLocaleString` in Internet Explorer. I tried to remove the language package `zw-th` from moment package in node in order to remove the error, but the next time the `toLocaleString` was again in another language `bn` and alter in arabic too (after I had also removed `bn`)

**Comment by MinusFour** [comment]
There's a single instance in this repo where `toLocaleString` shows up and it's for the github issue template. This doesn't look exactly like a problem with `moment`.

**Comment by derweise** [comment]
This is the generated js from Vure project: Search for string "toLocalString"

//! moment.js locale configuration
var e=t.defineLocale("zh-tw",{months:"一月_二月_三月_四月_五月_六月_七月_八月_九月_十月_十一月_十二月".split("_"),monthsShort:"1月_2月_3月_4月_5月_6月_7月_8月_9月_10月_11月_12月".split("_"),weekdays:"星期日_星期一_星期二_星期三_星期四_星期五_星期六".split("_"),weekdaysShort:"週日_週一_週二_週三_週四_週五_週六".split("_"),weekdaysMin:"日_一_二_三_四_五_六".split("_"),longDateFormat:{LT:"HH:mm",LTS:"HH:mm:ss",L:"YYYY/MM/DD",LL:"YYYY年M月D日",LLL:"YYYY年M月D日 HH:mm",LLLL:"YYYY年M月D日dddd HH:mm",l:"YYYY/M/D",ll:"YYYY年M月D日",lll:"YYYY年M月D日 HH:mm",llll:"YYYY年M月D日dddd HH:mm"},meridiemParse:/凌晨|早上|上午|中午|下午|晚上/,meridiemHour:function(t,e){return 12===t&&(t=0),"凌晨"===e||"早上"===e||"上午"===e?t:"中午"===e?t>=11?t:t+12:"下午"===e||"晚上"===e?t+12:void 0},meridiem:function(t,e,n){var r=100*t+e;return r<600?"凌晨":r<900?"早上":r<1130?"上午":r<1230?"中午":r<1800?"下午":"晚上"},calendar:{sameDay:"[今天] LT",nextDay:"[明天] LT",nextWeek:"[下]dddd LT",lastDay:"[昨天] LT",lastWeek:"[上]dddd LT",sameElse:"L"},dayOfMonthOrdinalParse:/\d{1,2}(日|月|週)/,ordinal:function(t,e){switch(e){case"d":case"D":case"DDD":return t+"日";case"M":return t+"月";case"w":case"W":return t+"週";default:return t}},relativeTime:{future:"%s後",past:"%s前",s:"幾秒",ss:"%d 秒",m:"1 分鐘",mm:"%d 分鐘",h:"1 小時",hh:"%d 小時",d:"1 天",dd:"%d 天",M:"1 個月",MM:"%d 個月",y:"1 年",yy:"%d 年"}});return e}))},9112:function(t,e,n){var r=n("83ab"),i=n("9bf2"),a=n("5c6c");t.exports=r?function(t,e,n){return i.f(t,e,a(1,n))}:function(t,e,n){return t[e]=n,t}},"91f4":function(t,e,n){},9263:function(t,e,n){"use strict";var r=n("ad6d"),i=n("9f7f"),a=RegExp.prototype.exec,s=String.prototype.replace,o=a,u=function(){var t=/a/,e=/b*/g;return a.call(t,"a"),a.call(e,"a"),0!==t.lastIndex||0!==e.lastIndex}(),c=i.UNSUPPORTED_Y||i.BROKEN_CARET,l=void 0!==/()??/.exec("")[1],d=u||l||c;d&&(o=function(t){var e,n,i,o,d=this,h=c&&d.sticky,f=r.call(d),p=d.source,m=0,_=t;return h&&(f=f.replace("y",""),-1===f.indexOf("g")&&(f+="g"),_=String(t).slice(d.lastIndex),d.lastIndex>0&&(!d.multiline||d.multiline&&"\n"!==t[d.lastIndex-1])&&(p="(?: "+p+")",_=" "+_,m++),n=new RegExp("^(?:"+p+")",f)),l&&(n=new RegExp("^"+p+"$(?!\\s)",f)),u&&(e=d.lastIndex),i=a.call(h?n:d,_),h?i?(i.input=i.input.slice(m),i[0]=i[0].slice(m),i.index=d.lastIndex,d.lastIndex+=i[0].length):d.lastIndex=0:u&&i&&(d.lastIndex=d.global?i.index+i[0].length:e),l&&i&&i.length>1&&s.call(i[0],n,(function(){for(o=1;o<arguments.length-2;o++)void 0===arguments[o]&&(i[o]=void 0)})),i}),t.exports=o},9483:function(t,e,n){"use strict";n.d(e,"a",(function(){return a}));var r,i=function(){return Boolean("localhost"===window.location.hostname||"[::1]"===window.location.hostname||window.location.hostname.match(/^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/))};function a(t,e){void 0===e&&(e={});var n=e.registrationOptions;void 0===n&&(n={}),delete e.registrationOptions;var a=function(t){var n=[],r=arguments.length-1;while(r-- >0)n[r]=arguments[r+1];e&&e[t]&&e[t].apply(e,n)};"serviceWorker"in navigator&&r.then((function(){i()?(u(t,a,n),navigator.serviceWorker.ready.then((function(t){a("ready",t)}))):(o(t,a,n),navigator.serviceWorker.ready.then((function(t){a("ready",t)})))}))}function s(t,e){navigator.onLine||t("offline"),t("error",e)}function o(t,e,n){navigator.serviceWorker.register(t,n).then((function(t){e("registered",t),t.waiting?e("updated",t):t.onupdatefound=function(){e("updatefound",t);var n=t.installing;n.onstatechange=function(){"installed"===n.state&&(navigator.serviceWorker.controller?e("updated",t):e("cached",t))}}})).catch((function(t){return s(e,t)}))}function u(t,e,n){fetch(t).then((function(r){404===r.status?(e("error",new Error("Service worker not found at "+t)),c()):-1===r.headers.get("content-type").indexOf("javascript")?(e("error",new Error("Expected "+t+" to have javascript content-type, but received "+r.headers.get("content-type"))),c()):o(t,e,n)})).catch((function(t){return s(e,t)}))}function c(){"serviceWorker"in navigator&&navigator.serviceWorker.ready.then((function(t){t.unregister()}))}"undefined"!==typeof window&&(r="undefined"!==typeof Promise?new Promise((function(t){return window.addEventListener("load",t)})):{then:function(t){return window.addEventListener("load",t)}})},"94ca":function(t,e,n){var r=n("d039"),i=/#|\.prototype\./,a=function(t,e){var n=o[s(t)];return n==c||n!=u&&("function"==typeof e?r(e):!!e)},s=a.normalize=function(t){return String(t).replace(i,".").toLowerCase()},o=a.data={},u=a.NATIVE="N",c=a.POLYFILL="P";t.exports=a},"94df":function(t,e,n){"use strict";const r=["B","kB","MB","GB","TB","PB","EB","ZB","YB"],i=["b","kbit","Mbit","Gbit","Tbit","Pbit","Ebit","Zbit","Ybit"],a=(t,e)=>{let n=t;return"string"===typeof e?n=t.toLocaleString():!0===e&&(n=t.toLocaleString()),n};t.exports=(t,e)=>{if(!Number.isFinite(t))throw new TypeError(`Expected a finite number, got ${typeof t}: ${t}`);e=Object.assign({bits:!1},e);const n=e.bits?i:r;if(e.signed&&0===t)return" 0 "+n[0];const s=t<0,o=s?"-":e.signed?"+":"";if(s&&(t=-t),t<1){const r=a(t,e.locale);return o+r+" "+n[0]}const u=Math.min(Math.floor(Math.log10(t)/3),n.length-1);t=Number((t/Math.pow(1e3,u)).toPrecision(3));const c=a(t,e.locale),l=n[u];return o+c+" "+l}},"957c":function(t,e,n){(function(t,e){e(n("c1df"))})(0,(function(t){"use strict";

**Comment by MinusFour** [comment]
That specific code in this chunk has nothing to do with `moment`. From what I can tell this is from a module called `pretty-bytes`.

https://github.com/sindresorhus/pretty-bytes/blob/master/index.js#L46

**Comment by derweise** [comment]
Thanks a lot! That helps
