### ISSUE TITLE
suppressDeprecationWarnings is not exposed as a typescript property

### ISSUE THREAD

**Issue by PizzaPartyInc** [moment/moment#5629]
**Describe the bug**
It is not possible to cleanly change suppressDeprecationWarnings value when working in context of a typescript file.

**To Reproduce**
Type this inside some typescript file, e.g. index.ts

```ts
import * as moment from 'moment';
moment.suppressDeprecationWarnings = true;
```
suppressDeprecationWarnings  will be underlined red with typescript error

**Expected behavior**
suppressDeprecationWarnings is exposed and modifiable.

**Screenshots**
![image](https://user-images.githubusercontent.com/37663061/86090249-6b939300-bab2-11ea-97c4-82b5c4d9f968.png)

**Additional context**
Moment version 2.27.0

**Current workarounds are not pretty**

```ts
import * as moment from 'moment';
(moment as any).suppressDeprecationWarnings = true;
```

or 

```ts
import * as moment from 'moment';
// To avoid linting `Unexpected any. Specify a different type.` linting error
const moments = (moment as unknown) as { suppressDeprecationWarnings: boolean; };
moments.suppressDeprecationWarnings = true;
```

**Comment by Alanscut** [comment]
The `TypeScript` type declaration file of `moment` has other unexposed property, such as `deprecationHandler`, I am working hard and preparing to submit a pull request.

**Comment by maxius122-bit** [comment]
Yeah it great

[]()
