### ISSUE TITLE
License issue 

### ISSUE THREAD

**Issue by nhunh585** [moment/moment#5630]
I used BlackDuck to scan source code and get the license risks with moment. Moment is using MediaWiki under GPL license. Is that right ?

![image](https://user-images.githubusercontent.com/25640067/86104549-60f3f080-bae8-11ea-8a70-86d096400b67.png)

**Comment by woahitsraj** [comment]
Moment is under MIT License. Your scanning software is wrong
https://github.com/moment/moment/blob/develop/LICENSE
