### ISSUE TITLE
When using .to() I get different translations pre and post webpack build

### ISSUE THREAD

**Issue by geoffreyrichey** [moment/moment#5631]
### When using .to() I get different results pre and post webpack build
I'm guessing this is a translation build/packaging issue with webpack but any support would be appreciated
 
**To Reproduce**

The same code:
```moment().to(moment('2020-07-03'), true)```
1. Running webpack dev server yields: **2 days**

2. After build the same code produces: **2d**

**Expected behavior**
The format would be the same both pre and post build

**Moment-specific environment**
moment 2.24.0

**Comment by Alanscut** [comment]
I can't reproduce your problem, can you provide an example that can reproduce the problem?

**Comment by geoffreyrichey** [comment]
You know what...after researching this some more go ahead and close this out as a bug with the moment library. I realized that I was actually using:

[vue-cli-plugin-moment](https://github.com/scottbedard/vue-cli-plugin-moment)

To leverage the pluginOptions to limit the bundle size as I only needed en translations. As this plugin hasn't been updated in 2 years I'm pretty sure that the issue I'm hitting is related to a mismatch of my moment version and/or the locale bundling with the plugin and not the moment library itself.

After adding some additional logging to my component I can see that the correct **en** locale is set but the localeData differs:
```
const locale = moment.locale()
console.log(locale)
const localeData = moment.localeData()
console.log(localeData)
```

Output from webpack dev server (most likely loads all locales):
![localdev](https://user-images.githubusercontent.com/1072531/86200285-daf49b80-bb21-11ea-8b12-dfa26b944391.png)

Output from built application:
![localbuild](https://user-images.githubusercontent.com/1072531/86200386-1c854680-bb22-11ea-950b-ca3169e47c9e.png)

I'll play around with the plugin some more and comment any solution I find for others but I'll probably just look at bundling only the specific locales I want with webpack and ditching the cli plugin if needed.

**Comment by geoffreyrichey** [comment]
Update on this...

Previous developer (no longer with us...hah) was globally overriding the relativeTime config for a single module instead of doing a local customization. Makes sense that the dev server would not be affected but the build would.
