### ISSUE TITLE
Is it possible to write date instanceof Moment?

### ISSUE THREAD

**Issue by CJDennis** [moment/moment#5636]
A `moment.js` object is described as class `Moment` when I inspect it in the console:

```
Moment {_isAMomentObject: true, _isUTC: false, _pf: {…}, _locale: Locale, _d: Wed Jul 01 2020 13:31:44 GMT+1000 (Australian Eastern Standard Time), …}
```

However, writing something like `date instanceof Moment` generates an error:

```
Uncaught ReferenceError: Moment is not defined
```

I've been using `moment.isMoment(date)`, but that's a bit clumsy. Is it possible to write `date instanceof Moment` instead?

**Comment by Alanscut** [comment]
@CJDennis This constructor `Moment` is not exported to the outside, so you will get an error when using it.

**Comment by marwahaha** [comment]
Thanks to Alanscut for answering the question.
