### ISSUE TITLE
Display custom message based on difference between datetimes: Momentjs

### ISSUE THREAD

**Issue by vjr12** [moment/moment#5639]
I am trying to format the date based on the difference between current and the input date:

Example:

Based on the difference

30 seconds ago(if its less than a minute)

13 minutes ago ( less than 60 minutes)

3 hours ago ( less than 24 hours)

40 days ago (more than 24 hours)

I tried the following, it does not format the way I want
````
let current = moment();
let input = "21-03-2020 10:34:25";
console.log(moment(input, "DD-MM-YYYY hh:mm:ss").fromNow());
````

**Comment by jamalroger** [comment]
Use duration
