### ISSUE TITLE
String + Format ISO_8601 parsing of `1262196` returns a valid date in strict mode and should not

### ISSUE THREAD

**Issue by mbolesta** [moment/moment#5642]
**Describe the bug**
`moment('1262196', moment.ISO_8601, true).isValid()` returns true

**To Reproduce**
`moment('1262196', moment.ISO_8601, true).isValid()` returns true

**Expected behavior**
isValid() should return false as '1262196' is not an ISO8601 date format

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83

**Smartphone (please complete the following information):**

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
```
Wed Jul 08 2020 09:50:02 GMT-0400 (Eastern Daylight Time)
7/8/2020, 9:50:25 AM
240
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2.24.0
```

**Additional context**

**Comment by MinusFour** [comment]
That matches the `YYYYDDD` ordinal date format. Which means year 1262 day 196.

**Comment by mbolesta** [comment]
> That matches the `YYYYDDD` ordinal date format. Which means year 1262 day 196.

But I’m specifying strict format and ISO_8601? Not ‘YYYYDDD’

**Comment by MinusFour** [comment]
> But I’m specifying strict format and ISO_8601? Not ‘YYYYDDD’

'YYYDDD' is part of the [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601#Ordinal_dates).

**Comment by mbolesta** [comment]
> > But I’m specifying strict format and ISO_8601? Not ‘YYYYDDD’
> 
> 'YYYDDD' is part of the [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601#Ordinal_dates).

I see now. Thank you for the help. I’ll switch to a more specific date format.
