### ISSUE TITLE
moment.weekday()  get wrong result BY Today

### ISSUE THREAD

**Issue by bbat2008** [moment/moment#5643]
weekday was worked OK, but we find it went wrong today,
TEST result here
```js
moment(new Date()).weekday()    => 3
moment(new Date()).day()    => 4
moment(new Date()).isoWeekday()    => 4
new Date().getDay()    => 4
```

Our env is chrome, Locale is chinese

**Comment by marwahaha** [comment]
Unfortunately I cannot reproduce this.

In zh-cn, I think this is correct behavior. Weekday() is locale aware: https://momentjs.com/docs/#/get-set/weekday/
and Monday is first day of week https://github.com/moment/moment/blob/develop/src/locale/zh-cn.js#L115
So today, Monday is weekday 0 but day 1.


```
moment().weekday()
0
moment().day()
1
```
