### ISSUE TITLE
How to get locale code from zone name?

### ISSUE THREAD

**Issue by Soullighter** [moment/moment#5645]
I was trying to find how to get code `fr` from zone name `’Europe/Paris'` all day, but with no luck.

I read all docs and couldn't find that function either, so i need help on this one.

Closest what i found is this. I need [This](https://momentjs.com/timezone/docs/#/using-timezones/getting-country-zones/)  function but in reverse, to pass country name and get country code.

**Comment by cmalard** [comment]
https://github.com/moment/moment-timezone/issues/289#issuecomment-354585784

**Comment by Soullighter** [comment]
That is great, but i don't use webpack right now.
Luckily i found solution
`moment.tz.zone(tz_guess).countries()`
This will get you `array` so you guys can easily pass that value to `locale()`

**Comment by marwahaha** [comment]
Glad you have found a solution.
