### ISSUE TITLE
Force out an ISO format date at midnight

### ISSUE THREAD

**Issue by Niffy** [moment/moment#5646]
Hi, I want to be able to take a given date and no matter what get the day, month, year and have the time at midnight in ISO format

E.g the input is `Wed Jul 01 2020 12:00:00 GMT+1300 (Pacific Auckland Standard Time)`
And I want the output to be `2020-07-01T00:00:00.000Z`

I just can't seem to force out anyway other than using `format('YYYY-MM-DD')` and adding `T00:00:00.000Z` manually
Thanks

**Comment by marwahaha** [comment]
You can remove the hour/minute/seconds/ms data with
moment().hours(0).minutes(0).seconds(0).milliseconds(0).format()

Then it will preserve your time offset.
