### ISSUE TITLE
calendar() and calendarFormat() displaying wrong days

### ISSUE THREAD

**Issue by vHeemstra** [moment/moment#5648]
**Describe the bug**
If you use the `.calendar()` or `.calendarFormat()` function to display a date, there's something strange happening due to the difference calculation. To be more precise: it displays 'today' when both moments are within 24 hours, although the dates are different. This happens even when the timezones are set to the same one.
I couldn't quite track down what is going wrong, but I suspect it has something to do with the `.diff()` calculation.

**To Reproduce**
1. Run the following code:
```
let moment_now = moment('2020-07-11 03:00:00+0200');
let moment_stamp = moment('2020-07-12 02:00:00+0200'); // same timezone, next day, but within 24 hours
console.log( moment.calendarFormat(moment_stamp, moment_now) );
```
2. Output: sameDay

**Expected behavior**
Output should be: nextDay

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, version 83.0.4103.116
 - Moment: version 2.27.0

**Moment-specific environment**

* The time zone setting of the machine the code is running on: GMT +2 (NL)
* The time and date at which the code was run: 11-07-2020 @ 03:00 (GMT+2)
* Other libraries in use: run from TypeScript

Please run the following code in your environment and include the output:
```
Sat Jul 11 2020 03:40:07 GMT+0200 (Midden-Europese zomertijd)
11-7-2020 03:40:07
-120
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2.27.0
```

**Possible fix / work-around**
I noticed, when I used the following pre-filter method for the `moment`s, the `.diff()` calculation gives the right result:
```
let moment_stamp = moment('2020-07-12 02:00:00+0200').hours(0).minutes(0).seconds(0).milliseconds(0);
let moment_now = moment('2020-07-11 03:00:00+0200').hours(0).minutes(0).seconds(0).milliseconds(0);
console.log( moment.calendarFormat(moment_stamp, moment_now) );
```
It basically sets all time information to zero, leaving the dates as is, forcing a per-24-hours comparison.

**Comment by renjith-jr** [comment]
hi @vHeemstra ,
please try this
let moment_now = moment('2020-07-11 03:00:00+0200');
let moment_stamp = moment('2020-07-12 02:00:00+0200'); // same timezone, next day, but within 24 hours
console.log( moment(moment_now).calendar(moment_stamp) )

**Comment by vHeemstra** [comment]
@renjith-jr , yes, that gives a different result ("yesterday at 3"), but that's a different function from the one that has the bug.

This issue was just to give notice of the problem in the source code.

**Comment by marwahaha** [comment]
This seems strange, I agree.
I am not going to change the default calendarFormat function, which is documented here: https://momentjs.com/docs/#/customization/calendar-format/

Thanks for reporting.
