### ISSUE TITLE
TypeError: moment__WEBPACK_IMPORTED_MODULE_18___default(...) is not a function

### ISSUE THREAD

**Issue by taiphamv** [moment/moment#5651]
**Describe the bug**
- I installed moment in to my project and used the below command to import:
`import moment from 'moment';`
- I used moment to format date string: `moment(dateValue).format('MM/DD/YYYY');`
- The error display: TypeError: moment__WEBPACK_IMPORTED_MODULE_18___default(...) is not a function
I must import moment by: `import moment from 'moment/moment';`
It works as expect.

Can we import by `import moment from 'moment';` instead of `import moment from 'moment/moment';`?

**Comment by pschlan** [comment]
```import moment from 'moment';``` works fine for me.

**Comment by taiphamv** [comment]
> `import moment from 'moment';` works fine for me. Do you have any more details about your environment?

Hi @pschlan , I used  React to build them for wordpress. This is my webpack config:
```
const defaults = require("@wordpress/scripts/config/webpack.config");
module.exports = {
  ...defaults,
  externals: {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  module: {
		...defaults.module,
		rules: [
      ...defaults.module.rules,
    ]
  }
};
```
Thank you!

**Comment by taiphamv** [comment]
Thank you @pschlan . This issue related babel configuration. I resolved this issue.
