### ISSUE TITLE
Import of Individual locals does not work with SystemJS

### ISSUE THREAD

**Issue by ajaybeniwal** [moment/moment#5653]
**Describe the bug**
If I try to load a single locale using SystemJS using SystemJS.import("https://cdn.jsdelivr.net/npm/moment@2.27.0/locale/ja.min.js") it fails to download the momentjs marked as dependecy  because in the code the dependency is defined as require("../moment"), i was thinking should not it  be require("moment") for umd min files.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

**Additional context**

**Comment by MinusFour** [comment]
It might be a problem on SystemJS and its loader. There is a `moment.js` in the [CDN](https://cdn.jsdelivr.net/npm/moment@2.27.0/moment.js). So if SystemJS is indeed handling a require call it should be able to resolve it correctly.

**Comment by marwahaha** [comment]
I'm not sure Moment.js can do anything about this.
