### ISSUE TITLE
moment(arg).isAfter(some-date) returns true if arg is undefined regardless of the value of some-date

### ISSUE THREAD

**Issue by Pietrrrek** [moment/moment#5655]
**Describe the bug**
`moment(<var>).isAfter(date)` returns `true` if var is undefined
**To Reproduce**
Run `moment().isAfter(new Date().getDate())` or
`moment(undefined).isAfter(new Date().getDate())`
 
The argument to `isAfter` does not have any influence on the result.

**Expected behavior**
IMO in this specific case isAfter should return false.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 83.0.4103.116

**Moment-specific environment**

* The time zone setting of the machine the code is running on
UTC+01:00
* The time and date at which the code was run
16/07/2020 12:51

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
```
Thu Jul 16 2020 12:48:48 GMT+0200 (Centraleuropæisk sommertid)
16.7.2020 12.48.48
-120
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
2.10.6
```

**Comment by MinusFour** [comment]
That's an old version of moment. [`Date.prototype.getDate`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDate) returns the day of the month which gets fed as a timestamp to moment which puts you back at Jan 1st 1970. Your clock is most likely to return a date after therefore that moment instance is indeed after that.

I tried `moment().isAfter()`, `moment().isAfter(moment())` and `moment().isAfter(moment(new Date()))` and it seems to be working just fine, it returns `false`.

**Comment by marwahaha** [comment]
Thanks for MinusFour for answering the question.
