### ISSUE TITLE
How can I find how many seconds are between 2 dates?

### ISSUE THREAD

**Issue by 7--** [moment/moment#5656]
I'm trying to make a countdown timer for the end of the day, week and month in UTC time.

I'm able to do it with unix time, since unix is measured in seconds `moment().endOf("day").unix() -  moment().unix();` as show here:
http://jsfiddle.net/whatthephil/fbhrLaxy/120/

I read the the moment.js examples, but I didn't see a way to do this with UTC time. I see I can add/subtract from a datetime, but I'm trying to find the time between two datetimes.

**Comment by mullinsmikey** [comment]
Hi, you can use `moment().diff()` to get seconds.
See more: [simple implementation](https://codepen.io/mullinsmikey/pen/Yzwdody), **[docs](https://momentjs.com/docs/#/displaying/difference/)**

**Comment by 7--** [comment]
Thank you. It's working with this `var dailyCloseSeconds = moment.utc().endOf("day").diff(moment.utc(), 'seconds');`
