### ISSUE TITLE
moment('2020-07-21').toISOString() and .format('YYYY-MM-DD') return 2020-07-22 via VS Code Remote SSH

### ISSUE THREAD

**Issue by donCarlosOne** [moment/moment#5658]
**Describe the bug**
Both toISODate and format('YYYY-MM-DD') are returning 2020-07-22 when the specified moment object has a date of 2020-07-21

**To Reproduce**

1. Assign the date 2020-07-21 to a variable as a moment object:
```
let startDate = moment('2020-07-21');
```
2. Evaluate startDate:
```
startDate
Moment {_isAMomentObject: true, _i: '2020-07-21', _f: 'YYYY-MM-DD', _isUTC: false, _pf: {…}}
```
3. Format startDate as an ISO string with toISOString():
```
startDate.toISOString()
'2020-07-22T00:00:00.000Z'
```
4. Format startDate with .format('YYYY-MM-DD'):
```
startDate.format('YYYY-MM-DD')
'2020-07-22'
```
**Expected behavior**
Both toISOString() and format('YYYY-MM-DD') should return the correct date ('2020-07-21')

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.5 VS Code remote ssh session on Ubuntu 18.04 in NodeJS app
 - Browser N/A

**Moment-specific environment**
```
Ubuntu date: Tue Jul 21 08:36:28 UTC 2020
Tue Jul 21 08:36:28 UTC 2020
Many, but not applicable
```

Please run the following code in your environment and include the output:
```
(new Date()).toString(): Tue Jul 21 2020 08:37:55 GMT+0000 (Coordinated Universal Time)
(new Date()).toLocaleString(): 7/21/2020, 8:37:55 AM
(new Date()).getTimezoneOffset(): 0
navigator.userAgent: N/A
moment.version: 2.27.0
```

**Additional context**

This appears to be unique to the date 2020-07-21.  Other tested dates (2020-07-16) return the correct date:
```
startDate = moment('2020-07-16')
Moment {_isAMomentObject: true, _i: '2020-07-16', _f: 'YYYY-MM-DD', _isUTC: false, _pf: {…}}
startDate.toISOString()
'2020-07-16T00:00:00.000Z'
```

Strangely, this issue does NOT occur when the same code is run directly on the same server.

My concern is that OTHER dates may be affected by this during development/debugging!

**Comment by MinusFour** [comment]
I couldn't reproduce it. Some steps seem unclear, what's the purpose of evaluating the `moment` object? Are you perhaps serializing the moment object and evaluating on the server?

**Comment by dwheale** [comment]
I can't reproduce this either

**Comment by marwahaha** [comment]
Unfortunately I cannot reproduce it.  Perhaps the remote server has a very strange timezone.

You can use https://momentjs.com/docs/#/parsing/utc/ if it works for you.
