### ISSUE TITLE
unix().format('YYYY-MM-DD HH:MM:SS') returns wrong value

### ISSUE THREAD

**Issue by nikita-fuchs** [moment/moment#5663]
**Describe the bug**
The Minutes returned are wrong.

**To Reproduce**
You can run this JSfiddle: http://jsfiddle.net/zfe6x5rL/
   ```
   var show = {startTime: {seconds: 1596122137 }}
   
   var startTime = moment.unix(show.startTime.seconds).format('YYYY-MM-DD HH:MM:SS')
   var remindTime = moment.unix(show.startTime.seconds - 600).format('YYYY-MM-DD HH:MM:SS')
    
    console.log("Starts at: ", startTime)
    // "2020-07-30 17:07:00" <- wrong
    console.log('Remind at: ', remindTime)
    // "2020-07-30 17:07:00" <- wrong
```
**Expected behavior**
Displaying the correct time in UTC formatting

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Catalina
 - Browser: Chrome 84.0.4147.89 (same behaviour in Node)

**Moment-specific environment**

* The time zone setting of the machine the code is running on
Berlin 

Requested output:
```
"Mon Jul 27 2020 10:32:45 GMT+0200 (Mitteleuropäische Sommerzeit)"
"27.7.2020, 10:32:45"
-120
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
"2.2.1"
```

**Comment by MinusFour** [comment]
This is most likely a bug with your code. `MM` and `SS` are not used for minutes and seconds. You would use `mm` and `ss` for the 0 padded versions of minutes and seconds.

**Comment by V-Gutierrez** [comment]
Agreed with @MinusFour; I believe the correct use is HH:mm:ss

**Comment by nikita-fuchs** [comment]
You were absolutely right, my bad. Thanks for the pointer.

Victor Gutierrez <notifications@github.com> schrieb am Do., 3. Sep. 2020,
19:42:

**Comment by V-Gutierrez** [comment]
I'm glad to help you!

**Comment by marwahaha** [comment]
I am glad the issue is solved!
