### ISSUE TITLE
Random string returned as valid dates when parsed in a format

### ISSUE THREAD

**Issue by mayank-tavisca** [moment/moment#5671]
**Describe the bug**

When checking the validity of some random strings parsed in a format, the isValid function returns true.

**To Reproduce**
Ex 1
1) const tempDate = moment('JXPQLX1', "DD/MM/YYYY hh:mm:ss A");
2) tempDate.isValid()

Ex 2
1) const tempDate = moment('V9W7U1B091A7LKC5RSIH2L', "DD/MM/YYYY hh:mm:ss A")
2) tempDate.isValid()

Ex 3 
1) const tempDate = moment('DR7BSH5', "DD/MM/YYYY hh:mm:ss A")
2) tempDate.isValid()
 
isValid() function returning true

**Expected behavior**
False must be returned for invalid date strings.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 84.0.4147.105

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()) - Fri Aug 07 2020 16:08:52 GMT+0530 (India Standard Time)
console.log((new Date()).toLocaleString()) - 07/08/2020, 16:08:52
console.log((new Date()).getTimezoneOffset()) - -330
console.log(navigator.userAgent) - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
console.log(moment.version) - 2.24.0
```

**Comment by marwahaha** [comment]
Thanks for opening this request.

Try https://momentjs.com/guides/#/parsing/strict-mode/

Then `isValid()` will return false.
