### ISSUE TITLE
Named import

### ISSUE THREAD

**Issue by FrankEssenberger** [moment/moment#5679]
**Describe the bug**

In our project we include the eslint rule `import/named` so that only named imports are allowed to be added. This leads currently to error for moment imports like this:

```
import { isMoment, Moment } from 'moment';
```

and error that ` Moment not found in 'moment'  import/named`. I can do two things to overcome this issue:

1. Import as `import * as moment from 'moment';` and use it like `moment.isMoment()` in the implementation. However, this is a bit ugly and long to use.
2. Import as `import { isMoment } from 'moment/ts3.1-typings/moment';` and use it like `isMoment(). The reason this works is the [export as namespace](https://github.com/moment/moment/blob/2c0b063b3bf95a285f9b38c173e262b6416c2e7f/ts3.1-typings/moment.d.ts#L752) which is only present in the ts3.1-typings/moment.d.ts and not in the one in the root level [moment.d.ts](https://github.com/moment/moment/blob/develop/moment.d.ts)

See [here](https://stackoverflow.com/questions/44847749/explain-export-and-export-as-namespace-syntax-in-typescript) for some explanations: 

**To Reproduce**
1. import moment as mentioned above: `import { isMoment, Moment } from 'moment'`
2. run eslint with rule import/named enabled

**Expected behavior**
The import `import { isMoment, Moment } from 'moment';` should be working without producing lint errors. If you see no objections, is it possible to add the `export as namespace` also to the root `moment.d.ts`? Perhaps you can also explain why there are two type definition I am curious.

**Comment by marwahaha** [comment]
I'm not a TypeScript expert, but I don't think we can add export as namespace because it broke various users in the past (i.e. TS 1.x users.)

I'm not sure we would change  the typings, but perhaps there is a way in your codebase to prefer one typings file over another.
