### ISSUE TITLE
when using add() in string literals multiple times it continuously increases the date

### ISSUE THREAD

**Issue by buhaytza2005** [moment/moment#5682]
**Describe the bug**
When using a moment object repeatedly in a string literal it repeats the addition.
**To Reproduce**
1. Create a js file with the following code:

<code>
const moment = require("moment");
let strDate = "22/10/2020"
let startDate = moment(strDate, "DD/MM/YYYY")
console.log(startDate.format("DD/MMM/YYYY"))
console.log(`${startDate.add(1, "d").format("DD MMM YYYY")} ${startDate.add(1, "d").format("DD MMM YYYY")}`)
</code>
2. Running the js file with node  produces the output:
<code>
22/Oct/2020
23 Oct 2020 24 Oct 2020
</code>

**Expected behavior**
I would have expected the output:
<code>
22/Oct/2020
23 Oct 2020 23 Oct 2020
</code>

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Electron Chromium and in Node.js terminal

**Comment by MinusFour** [comment]
This behavior [is intended](https://momentjs.com/docs/#/manipulating/add/):

> Mutates the original moment by adding time.

You'll have to [`clone`](https://momentjs.com/docs/#/parsing/moment-clone/) at each step.

**Comment by buhaytza2005** [comment]
I see... apologies for the confusion and thanks for the response.
