### ISSUE TITLE
Wrong month translation - not UTF-8?

### ISSUE THREAD

**Issue by Diogo1995** [moment/moment#5683]
Hi,

When using moment.months() to get all months translated to the correct language, it looks like its not using UTF-8. For example in portuguese, the month March that should be written Março, it comes like marÃ§o.

This is only happening when the code runs on the server and not in localhost so I believe that I need to add something to the request but im not sure of what... Can someone please help me with this? 

Thanks!!

**Comment by raspyweather** [comment]
Can you add some more information? 
From your description it's very hard to point out anything particular. You might be using a Terminal application which doesn't support UTF-8 or might have a wrongly set encoding header, or somehow changed the encoding of source files.

**Comment by Diogo1995** [comment]
Im using moment v2.27.0 in Angular. Wich is installed and I think im not getting anything from outside that instalation? Im trying to find any Request where those translated texts come from but im not being able to find it.

In localHost its all ok, but when I use the server hosted on Azure it gives me that problem... Im not sure what other info I can provide.

Thanks!

**Comment by raspyweather** [comment]
Do your html files specify UTF-8 as encoding?

**Comment by Diogo1995** [comment]
Yes, the html specifies the charset as UTF-8 and even when I try to see the raw output it comes with the wrong chars.

As you can see, when I call the moment.getMonths(), while debugging and inside that function, this is what I get:

![Untitled](https://user-images.githubusercontent.com/23064079/91594428-d3067b80-e959-11ea-8a66-652bc053238f.png)

I'm out of ideas for what it might be or the steps I need to take to try and figure it out :(

**Comment by Diogo1995** [comment]
@raspyweather Do you have any suggestion on how to solve this problem?

**Comment by marwahaha** [comment]
Sorry you are still having issues. This does not look like an issue with the library, but with code point translation. You could try a different translation but I am not a code point expert. It reminds me of this blog; https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/

This might be best resolved on StackOverflow.
