### ISSUE TITLE
Incorrect data with timestamp initialization

### ISSUE THREAD

**Issue by leobragatti** [moment/moment#5691]
**Describe the bug**
A new instance of moment, when using timestamp is returning wrong data about the date

**To Reproduce**
```
var date = moment(1597968000000)
undefined
date.toISOString()
"2020-08-21T00:00:00.000Z"
date.date()
20
```

**Expected behavior**
date.date() should return 21 instead of 20

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Vivaldi 
 - Version 3.2.1967.41

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
Fri Aug 21 2020 11:43:44 GMT-0300 (Brasilia Standard Time)
console.log((new Date()).toLocaleString())
8/21/2020, 11:43:44 AM
console.log((new Date()).getTimezoneOffset())
180
console.log(navigator.userAgent)
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.108 Safari/537.36
console.log(moment.version)
2.27.0
```

**Comment by marwahaha** [comment]
This is probably because of your timezone.

You can do 
```
moment.utc(1597968000000).date()
```
and get the correct result (21 I think).

**Comment by leobragatti** [comment]
Thanks @marwahaha!
Still, it's a strange behaviour. When date.date() is called, the timezone is applied? But the same does apply to date.toString()?

**Comment by marwahaha** [comment]
It has to do with creating dates in local time vs UTC .

For example, in my offset (California):
```
date = moment(1597968000000)
Object { _isAMomentObject: true, _i: 1597968000000, _isUTC: false, _pf: {…}, _locale: {…}, _d: Date Thu Aug 20 2020 17:00:00 GMT-0700 (Pacific Daylight Time), _isValid: true, _z: null }

date.toString()
"Thu Aug 20 2020 17:00:00 GMT-0700"
```
