### ISSUE TITLE
Support Local Time Formats with Milliseconds

### ISSUE THREAD

**Issue by raspyweather** [moment/moment#5697]
**Is your feature request related to a problem? Please describe.**
Currently - as far as I'm aware of - there is `LT` and `LTS` for formatting into local time. 
It is currently not possible to include milliseconds into a locally formatted time. `LTS.SSS` results in `11:48:21.232` for German which is correct, but `11:48:21 AM.232` in English which looks rather odd. 

**Describe the solution you'd like**
Would be nice if something like ```.format("LTSS")``` would exist for this purpose and would be a documented feature.

```
moment(new Date()).locale('de').format("LTSS"); // 11:48:21.232
moment(new Date()).locale('en').format("LTSS"); // 11:48:21.232 AM
```

If I'm missing a point somewhere, feel free to let me know, I'm not an i18n expert anyway.

**Comment by marwahaha** [comment]
This is a nice request. 
Unfortunately, I don't think it is a good idea to retrofit this to Moment.js .
