### ISSUE TITLE
53 Week Years

### ISSUE THREAD

**Issue by TylerSmart** [moment/moment#5699]
**Describe the bug**
Moment doesn't appear to calculate 53 weeks correctly, which causes some cascading effects.

**To Reproduce**
```
let yearWith53 = moment('2020-01-01').startOf('week');
console.log(`Week Number: 1 ${yearWith53.week(1).format('YYYY-MM-DD ddd')}`);
	// Week Number: 1 2019-12-29 Sun
console.log(`Week Number: 52 ${yearWith53.week(52).format('YYYY-MM-DD ddd')}`);
	// Week Number: 52 2020-12-20 Sun
console.log(`Week Number: 53 ${yearWith53.week(53).format('YYYY-MM-DD ddd')}`);
	// Week Number: 53 2020-12-27 Sun

let yearWith52 = moment('2021-01-01').startOf('week');
console.log(`Week Number: 1 ${yearWith52.week(1).format('YYYY-MM-DD ddd')}`);
	// Week Number: 1 2020-12-27 Sun
```

**Expected behavior**
According to ISO 8061, a week belongs to a particular year if the Thursday of that week falls in it. December 31, 2020 is a Thursday, but Moment returns that week as the first week of 2021.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Node
 - Version v12.18.3

**Moment-specific environment**

* Mountain Daylight Time
* Run on Wed Aug 26, 2020
* Only Moment included.

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
	// Wed Aug 26 2020 15:39:39 GMT-0600 GMT-600 (Mountain Daylight Time)
console.log((new Date()).toLocaleString())
	// 8/26/2020 3:39:39 PM
console.log((new Date()).getTimezoneOffset())
	// 360
console.log(navigator.userAgent)
	// N/A
console.log(moment.version)
	// 2.27.0
```

**Comment by MinusFour** [comment]
> Expected behavior
> According to ISO 8061, a week belongs to a particular year if the Thursday of that week falls in it. December 31, 2020 is a Thursday, but Moment returns that week as the first week of 2021.

The default is not ISO 8601 compliant.

https://github.com/moment/moment/blob/2c0b063b3bf95a285f9b38c173e262b6416c2e7f/src/lib/units/week.js#L48-L51

But the website included in the [documentation](https://momentjs.com/docs/#/customization/dow-doy/) on how to change it:

> ```
> // ISO-8601, Europe
> moment.updateLocale("en", { week: {
>   dow: 1, // First day of week is Monday
>   doy: 4  // First week of year must contain 4 January (7 + 1 - 4)
> }});
> ```

**Comment by ashsearle** [comment]
moment handles ISO weeks and locale-aware weeks

You don't have to change your locale; you can use the `isoWeek` unit:
```
moment().startOf('isoWeek'); // set to the first day of this week according to ISO 8601, 12:00 am
```

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.

**Comment by JeremyLoy** [comment]
This issue should be reopened.

January 1st 1987 is a Thursday. According to ISO 8601, this should be the 53rd week of 1986.

Moment gets this date (and all similar dates) incorrect in various different ways.

```
const m = moment.utc().startOf('isoWeek').year(1987).month(0).date(0)
console.log(m) // Moment<1986-12-31T00:00:00Z> Wrong. Should by 1987-01-01T00:00:00Z
console.log(m.format('YYYYWW')) // 198601 Got the year wrong, but the week correct
console.log(`${m.isoWeekYear()}${m.isoWeek()}`) // 19871 both year and week incorrect
console.log(`${m.weekYear()}${m.week()}`) // 19871 both year and week incorrect
```

An example using MySQL that gets this correct
[The parameter 4 sets the function to ISO8601 0 indexed](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_week)

```
SELECT YEARWEEK('1987-01-01T00:00:00', 4) // 198653
```

**Comment by ashsearle** [comment]
@JeremyLoy There are several mistakes in the code:

You used `.date(0)` instead of `.date(1)` - which moved the moment instance backwards to the last day of the previous month, which happens to be the previous year, so all your tests from this point on are broken.

You used `YYYYWW`, which mixes ISO and non-ISO formatting codes.  You should use `GGGGWW` to get the right ISO "Week Year" to match the ISO Week.

If Jan 1st is a Thursday, then that's in ISO Week 1 by definition.  I'm not sure what you read that said it belongs to final week of the previous year?  (Probably worth a reminder that ISO week runs from Monday to Sunday.  If Thursday is Jan 1st 1987, then that means the majority (4 days) of the week are in 1987, so that's ISO week 1 of ISO Week Year 1987.)

https://www.epochconverter.com/weeks/1987

**Comment by JeremyLoy** [comment]
Correct, I did have an off by one error. My mistake.

Regardless, every date from 1986-12-29 -> 1987-1-4 should be the 198653 They are outputting 198701

**Comment by ashsearle** [comment]
@JeremyLoy moment is correct.  198701 is the right output for *ISO week numbering*
