### ISSUE TITLE
(typescript) RelativeTimeSpec type is missing key `ww` that is described in the docs

### ISSUE THREAD

**Issue by chadlavi-casebook** [moment/moment#5700]
**Describe the bug**
at https://momentjs.com/docs/#/customization/relative-time/, the following example code is given:

```ts
moment.updateLocale('en', {
    relativeTime : {
        future: "in %s",
        past:   "%s ago",
        s  : 'a few seconds',
        ss : '%d seconds',
        m:  "a minute",
        mm: "%d minutes",
        h:  "an hour",
        hh: "%d hours",
        d:  "a day",
        dd: "%d days",
        w:  "a week",
        ww: "%d weeks",
        M:  "a month",
        MM: "%d months",
        y:  "a year",
        yy: "%d years"
    }
});
```

however, the type `RelativeTimeSpec` is missing key `ww`, so attempting week locale updates results in a type error. 

**To Reproduce**
1. in a Typescript React app, try to use the example code above
2. You'll get a type error on the key `ww`

**Expected behavior**
Should be able to update localization for weeks.

**Screenshots**
<img width="895" alt="Screen Shot 2020-08-27 at 4 27 03 PM" src="https://user-images.githubusercontent.com/45078010/91491641-59e82500-e882-11ea-913e-225edd1d66a6.png">

<img width="806" alt="Screen Shot 2020-08-27 at 4 27 14 PM" src="https://user-images.githubusercontent.com/45078010/91491654-5ce31580-e882-11ea-9253-7c91530c6b6f.png">

**Comment by PatrickMackridge** [comment]
Hi, I would be happy to pick this up if no-one is currently looking at it. From what I can tell it should just be a case of updating `RelativeTimeSpec` in the moment.d.ts file? Thanks

**Comment by marwahaha** [comment]
@PatrickMackridge I think so!
