### ISSUE TITLE
moment gives deprecation warning value provided is not in a recognized RFC2822 or ISO format

### ISSUE THREAD

**Issue by aviralgoyal** [moment/moment#5701]
**ISSUE 1 :** When I provide the date in default SQL Server format that is 2007-04-07T00:00:00.000Z I receive deprecation warning.

**To Reproduce**
```
moment('2007-04-07T00:00:00.000Z').isValid() 
```

It does read it as a valid date format but I get the warning

> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release.

**but if I use this** 

```
moment('2007-04-07T00:00:00.000Z', moment.ISO_8601).isValid()
```

Warning disappears

**Also if I use this**
```
moment('2007-04-07T00:00:00.000Z', moment.ISO_8601).isUTC()
```

returns false

I don't know whether this will be considered a bug or not, but isn't this date format already ISO Format? Do I need to specify moment.ISO_8601 every time I parse a date using moment adapter?

**ISSUE 2:**  moment(1).isValid() returns true

Is it supposed to return true in this case? Just want to understand.

**Moment-specific environment**

* The time and date at which the code was run : 28 Aug 2020
* Other libraries in use (TypeScript, Immutable.js, etc) : TYPESCRIPT

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
Fri Aug 28 2020 10:40:14 GMT+0530 (India Standard Time)
console.log((new Date()).toLocaleString())
8/28/2020, 10:40:14 AM
console.log((new Date()).getTimezoneOffset())
-330
console.log(navigator.userAgent)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
console.log(moment.version)
2.24.0
```

**Comment by MinusFour** [comment]
It must have been fixed already because this doesn't happen on the latest version. I'm unsure about `isUTC` but I believe that only checks if it's in UTC mode (e.g. created with `moment.utc`).

**Comment by marwahaha** [comment]
I don't see this issue.
I'm glad it's fixed for you too.

**Comment by ShubhamKumar2106** [comment]
I am getting a deprecation warning
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2/8/2024, 10:11:14 AM, _f: undefined, _strict: undefined, _locale: [object Object]



I am doing something with date time 
@marwahaha 
const modifiedDate = moment.utc(lastModifiedDate, "ddd MMM DD HH:mm:ss UTC YYYY");
        if (modifiedDate !== null || modifiedDate !== undefined) {
            const result = moment.tz(modifiedDate, TIMEZONE_NAME);
            const resultFormatter = result.format();
            if (resultFormatter !== DateTimeEnum.INVALIDDATE) {
                const splitDateTime = resultFormatter.split("T", 2);
                const splitTime = splitDateTime[1].includes("+")
                    ? splitDateTime[1].split("+", 2)
                    : splitDateTime[1].split("-", 2);
                date = splitDateTime[0];
                const time = splitTime[0];
                const dateTime = `${date} ${time}`;
                const start: any = moment(dateTime).add(744, "h");
                const end: any = moment(
                    new Date().toLocaleString("en-US", { timeZone: TIMEZONE_NAME })
                );
                const hour = start.diff(end, "hours");
                setRecentDateTime(date);
                setIsShipAddBtnEnabled(hour <= 0);
            }
        }

**Comment by jahir-p** [comment]
I am getting a deprecation warning. 

Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non-RFC2822/ISO date formats are discouraged. 
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: september, 1 2025, _f: undefined, _strict: undefined, _locale: [object Object]

const month = moment(`${delivery_month}, 1 ${delivery_year}`).format('MMM-YY')

**Comment by JahirPendhari09** [comment]
I am getting a deprecation warning.

Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non-RFC2822/ISO date formats are discouraged.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: september, 1 2025, _f: undefined, _strict: undefined, _locale: [object Object]

const month = moment(${delivery_month}, 1 ${delivery_year}).format('MMM-YY')

**Comment by ramusarithak** [comment]
i resolved this error , 
here i mentioned entity in string thereafter I using moment to check valid that time it has happened that error
