### ISSUE TITLE
Possible performance improvement

### ISSUE THREAD

**Issue by jfstephe** [moment/moment#5702]
**Describe the bug**
isSameOrBefore/isSameOrAfter functions could use !isAfter()/!isBefore() internally without doing the 'isSame' check and therefore reduce the number of comparisons and increase performance. 

**To Reproduce**
Run this fiddle 
http://jsfiddle.net/L384v2kp/1/

**Expected behavior**
It not to do unnecessary work :-).

**Desktop (please complete the following information):**
- Everywhere

**Smartphone (please complete the following information):**
- Everywhere

**Moment-specific environment**
N/A

**Additional context**
These are the lines, happy to raise a PR as should be a straight-forward change but wanted to check my logic.
https://github.com/moment/moment/blob/2c0b063b3bf95a285f9b38c173e262b6416c2e7f/src/lib/moment/compare.js#L66

**Comment by jfstephe** [comment]
Hmmmm.... ok, turns out my spidey-sense was right when I thought this wasn't going to be quite as straight forward as I'd hoped. I am creating a PR (I've not published yet as it's not ready) but things are getting complicated as the validity of the moment objects is compared. So if momentA and momentB are being compared and momentB is invalid, then momentA.isAfter(momentB) returns *false*. So, assuming I inverted the logic inside the isSameOr* functions as I was proposing, if I  subsequently called moment with momentA.isSameOrBefore(momentB) then this would return *true*, as internally I would be doing:
`
return !momentA.isAfter(momentB);
`
which means the isAfter returns false as it's invalid, but I invert it and it becomes true?!

So I could start checking the validity of the parameters but I think I'd lose the performance benefits I'm trying to achieve and also I think there's a fundamental problem here that the comparison functions should *NOT* return false if the parameters are invalid. I'd suggest that they should through an exception.

I for one am inverting the logic in my projects ATM and was blindly unaware of this surprising behaviour, which may be causing all sorts of nasties in my app, and I suggest that throwing an exception is the least surprising behaviour, but this would be quite a big breaking change.

Can I get some guidance on this please? Happy to do the work as I need to change this. I either do it in a wrapper around momentjs in my project or fix the core problem here and contribute to this awesome library :-).

**Comment by marwahaha** [comment]
Thanks for looking at this. Sorry it got so complicated.
I'll close this in favor of https://github.com/moment/moment/issues/4638

We are reticent to take any substantial changes to Moment.js: https://momentjs.com/docs/#/-project-status/
