### ISSUE TITLE
Option to set strict mode as default across codebase

### ISSUE THREAD

**Issue by vegerot** [moment/moment#5703]
**Is your feature request related to a problem? Please describe.**
Strict mode offers many benefits to ensuring stable code.  I would like to have strict mode enabled across our whole project so that developers don't need to remember to use strict mode everywhere

**Describe the solution you'd like**
This is a good question.  I'm not quite sure how I'd design this.  Maybe in our project we could export our own moment, and have something like

```ts
import * as baseMoment from 'moment'
function moment(...args) { baseMoment(args[0], args[1], true) }
export { moment };
```

Another option is that you all could do this in the moment repo, and with ES6 modules we can do 

```ts
import {StrictMoment as moment} from 'moment';
```

**Describe alternatives you've considered**
Besides the above, I have considered writing an ESLint rule to enforce setting strict mode.
The advantage of doing it my first method is I could export strict mode in development and lazy mode in production.

**Additional context**
Of course, the best way would just be if moment moved to Strict mode by default like they've been saying they'd do soon for years.

**Comment by marwahaha** [comment]
This is a nice idea. I don't know how hard it will be to implement.

**Comment by marwahaha** [comment]
I've decided we should not implement this.
See https://momentjs.com/docs/#/-project-status/
Hopefully you can make that ESLint rule.

**Comment by vegerot** [comment]
Sad to see Moment go.  Need to figure out how to get started on ESLint

**Comment by vegerot** [comment]
Thank you for all your hard work
