### ISSUE TITLE
"startOf" doesn't work correct

### ISSUE THREAD

**Issue by WuglyakBolgoink** [moment/moment#5704]
**Describe the bug**
`startOf` doesn't work correct.

In docu (https://momentjs.com/docs/#/manipulating/start-of/) stay:

> moment().startOf('hour');    // set to now, but with 0 mins, 0 secs, and 0 ms

**To Reproduce**
```js
console.log(moment().startOf('hour').format('DD.MM.YYYY hh:mm:ss'))
console.log(moment().minutes(0).seconds(0).milliseconds(0).format('DD.MM.YYYY hh:mm:ss'))
```

give back 

```
"01.09.2020 08:00:00"
"01.09.2020 08:00:00"
```

**Expected behavior**

```
"01.09.2020 00:00:00"
"01.09.2020 00:00:00"
```
 

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version [84.0.4147.135]

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

```
"Tue Sep 01 2020 20:37:00 GMT+0200 (Mitteleuropäische Sommerzeit)"
"1.9.2020, 20:37:00"
-120
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
"2.27.0"
```

**Comment by TedKoker** [comment]
It seems that the expected result of startOf('hour') at  "20:37:00" would be "20:00:00", or "8:00:00".
Did you mean that the expected behavior was "8:00:00" and you got "00:00:00"?

**Comment by AlanH3160** [comment]
This is the correct behaviour. The docs say the mins, seconds, and ms will all be set to 0. The hour is set to whatever hour you are currently in. If you want the format to be 24 hours you need 'HH:mm:ss'. Your expected behaviour would be for startOf('day')

**Comment by WuglyakBolgoink** [comment]
@AlanH3160 I'm sorry.. my bad.. forgot about  diff between `hh` and `HH`

**Comment by WuglyakBolgoink** [comment]
Hallo @TedKoker,

no. It was always `12:00:00`, and it was I think in case of using `PM`-time value, because I used `hh:mm:ss`-formatting. In case of 24h with `HH:mm:ss`-formatting I got correct value `00:00:00`. ^_^
