### ISSUE TITLE
Option to format in place

### ISSUE THREAD

**Issue by aswinkumar863** [moment/moment#5705]
**Is your feature request related to a problem? Please describe.**
`format()` method returns formatted date only. But I want to format the date in place of the input string and return a full string. 

For example

```
let textData = "Today is 2020-09-02 09:32:00+00:00"
let format = moment(textData, "YYYY-MM-DD HH:mm:ssZ").format("MMM. DD, YYYY hh:ss A")
```

I want the output to be like this. `Today is Sept. 02, 2020 9:32 PM
`
 
**Describe the solution you'd like**
A new token/method to format date in place. 

**Describe alternatives you've considered**

As a temporary workaround, I'm using
```
var textData = "Today is 2020-09-02 09:32:00+00:00"
let mdate = moment(textData, "YYYY-MM-DD HH:mm:ssZ");

console.log(mdate._pf.unusedInput.concat('').join(mdate.format("MMM. DD, YYYY hh:ss A")))
```

**Additional context**
Query raised in StackOverflow
https://stackoverflow.com/questions/63706487/how-to-convert-to-a-date-with-a-format-i-want-when-the-retrieve-data-has-a-text

**Comment by MinusFour** [comment]
This feature already exists. You can use square brackets to give text its literal meaning (e.g. not as a display token):

```
let textData = "Today is 2020-09-02 09:32:00+00:00"
let format = moment(textData, "YYYY-MM-DD HH:mm:ssZ").format("[Today is] MMM. DD, YYYY hh:ss A")
```

**Comment by aswinkumar863** [comment]
@MinusFour 

But here the input string is a dynamic statement. For example 

```
"Today is 2020-09-02 09:32:00+00:00"
"Yesterday is 2020-09-01 08:01:00+00:00"
"2020-09-25 00:00:00+00:00 is holiday"
"Due ends 2020-09-30 00:00:00+00:00 of this month"
```

**Comment by marwahaha** [comment]
This is an interesting request.
I think you have a solution that works for you.
If many other people want a token, we can consider it.
Thanks for opening this.
