### ISSUE TITLE
.isValid() returns true for "ÀxÇ¼Çnà23ò"

### ISSUE THREAD

**Issue by hunterInt** [moment/moment#5707]
**Describe the bug**
`moment("ÀxÇ¼Çnà23ò", 'YYYY:MM:DD kk:mm:ss').isValid() === true`

**To Reproduce**
1. Just `console.log` this: `moment("ÀxÇ¼Çnà23ò", 'YYYY:MM:DD kk:mm:ss').isValid()`

**Expected behavior**
This I suppose might possible not be a bug because I tell moment the format the date is in, but I still think that moment should not say that it is a valid date, because it is not, especially since the date moment returns is in `2023`. 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 85

**Moment-specific environment**

* The time zone setting of the machine the code is running on: Mountain Time
* The time and date at which the code was run: September 6th 2020

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
```
Sun Sep 06 2020 19:13:17 GMT-0600 (Mountain Daylight Time)
VM10023:2 9/6/2020, 7:13:17 PM
VM10023:3 360
VM10023:4 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
2.27.0
```

**Comment by marwahaha** [comment]
Sorry you are experiencing an issue.

Try strict mode:
https://momentjs.com/guides/#/parsing/strict-mode/

```
moment("�À��x��Ç¼��Çnà23�ò", 'YYYY:MM:DD kk:mm:ss', true).isValid()
```

**Comment by hunterInt** [comment]
@marwahaha oh no worries, I just wanted to report the bug. Setting strict mode to `true` fixed this issue. Thanks!
