### ISSUE TITLE
diff / weekday 

### ISSUE THREAD

**Issue by maquejp** [moment/moment#5708]
Hello,

It would be great if the DIFF function could be set to return the number of working days between the two dates (mon->fri excl sat/sun).
e.g.
Between 01-Sep-2020 and 07-Sep-2020
d1= Tue Sep 01 2020 00:00:00 GMT+0200 (Central European Summer Time)
d2= Mon Sep 07 2020 00:00:00 GMT+0200 (Central European Summer Time)
d2.dif(d1, days) => 6 (I count 7 as  I include the 1st)

As there is one week-end between the 2 dates, it would return 4 (I will count 5 as I include the 1st)

**Comment by marwahaha** [comment]
Hi, thanks for this suggestion.
I don't think this is a good idea for Moment.js.
However, it could be useful as a plugin for Moment.js.
Perhaps the "business" plugin might solve your issue.
https://momentjs.com/docs/#/plugins/moment-business/

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.

**Comment by maquejp** [comment]
I will take a look. Thank you.
