### ISSUE TITLE
invalid date is considered valid

### ISSUE THREAD

**Issue by sadiqkhoja** [moment/moment#5709]
**Describe the bug**
Moment is parsing ISO_8601 incorrectly and considering '701901' as valid

**To Reproduce**
https://jsfiddle.net/sadiqkhoja/m0fjyb45/1/

**Expected behavior**
isValid() should return false

Please run the following code in your environment and include the output:
```
console.log(moment('701901', moment.ISO_8601, true).isValid());
```

**Additional context**
Moment Version: 2.27.0

**Comment by PriyaBihani** [comment]
Can i try this?

**Comment by MinusFour** [comment]
This is sort of a duplicate of #5622. It's unclear if `YYYYMM` is a valid format.

**Comment by marwahaha** [comment]
closing as dupe of #5622, thank you minusfour

PriyaBihani, this may not be a good first issue, but thanks for asking!
