### ISSUE TITLE
`moment('W01 2020', '[W]WW YYYY').format('[W]WW YYYY');`  resolves to `W01 2019`

### ISSUE THREAD

**Issue by MouseZero** [moment/moment#5714]
Is this a bug that others can observe or am I misunderstanding the format here?

**Comment by marwahaha** [comment]
This gets parsed to the ISO week of year, which does not start in 2020.
```
moment('W01 2020', '[W]WW YYYY').format()
"2019-12-30T00:00:00-08:00"
```

**Comment by MouseZero** [comment]
Thank you so much @marwahaha your amazing! This one had me upside down for a while.
