### ISSUE TITLE
I'm having an issue with local time zone conversions

### ISSUE THREAD

**Issue by fdevGit** [moment/moment#5721]
**Describe the bug**
There is an incompatibility in time zone to local transformations. I'm testing the timezone Turkey.

**To Reproduce**
https://jsfiddle.net/fdev1/op0qzm4x/11/

**Expected behavior**
Calculation should be made with the same time frame on all lines

**Screenshots**
![timezone](https://user-images.githubusercontent.com/53165808/93325320-d043cb80-f81f-11ea-81e5-76fb90a19533.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version last version

**Moment-specific environment**
![image](https://user-images.githubusercontent.com/53165808/93325456-0bde9580-f820-11ea-8348-5a94cfb99888.png)

**Comment by marwahaha** [comment]
Sorry you are having an issue.
This is probably related to DST. On some days you specify (typically in summer), Turkey observes daylight savings, so it is  +03.


https://en.wikipedia.org/wiki/Summer_time_in_Europe#Turkey
https://en.wikipedia.org/wiki/Summer_time_in_Europe

Please re-open if you have other questions.

**Comment by fdevGit** [comment]
Have you looked at the printout in the photos? 1996-10-10 time zone shows +3, 1995-10-10 date +2 time zone value.

**Comment by marwahaha** [comment]
> Since 1981 each directive has specified a transition time of 01:00 UTC and a start date of the last Sunday in March, but the end dates have differed. Successive Directives laid down two dates for the end: one on the last Sunday in September applied by the continental Member States, and the other on the fourth Sunday in October for the United Kingdom and Ireland.[1] In 1996 the end date was changed to the fourth Sunday in October for all countries.[2] In 1998 the end date was changed to the last Sunday in October; this happened to be the same as the previous rule for 1996 and 1997.[3] The ninth directive, Directive 2000/84/EC, currently (2018) in force, specifies this rule.[4] 

https://en.wikipedia.org/wiki/Summer_time_in_Europe#History

>
