### ISSUE TITLE
Remove Black Lives Matter propaganda from site banner

### ISSUE THREAD

**Issue by fionic** [moment/moment#5729]
Please remove black lives matter propaganda from the website.
I'm trying to do my job and live in peace and would rather not have political ideology pushed onto me by you when I visit a programming website for documentation.
It has always been my understanding that black lives are equal to the rest of lives and if you feel the need to put a banner on a site then you are in-fact the racist yourself because you don't believe that black lives are equal.
Since you're obviously liberals, I'm sure you would not like to have a large banner that says "Trump 2020" every time you visit npmjs.org
So please leave the politics out of it.
Thanks.

**Comment by marwahaha** [comment]
This is open-source software. If you don't like it, you can try something else.
I don't think Black people are treated fairly in the US; try these links for more details:
* https://en.wikipedia.org/wiki/Negrophobia
* https://en.wikipedia.org/wiki/Jim_Crow_laws
* https://www.medicalnewstoday.com/articles/white-fragility-definition#summary
* https://en.wikipedia.org/wiki/Police_brutality_in_the_United_States

**Comment by fionic** [comment]
Well I definitely would opt out of this software if I didn’t work at a larger organization that uses it. But thanks for making my point, this is open source software, this is not (or shouldn’t be because it certainly seems to be) your personal platform for expressing your propaganda viewpoints. The rest of us want to do our jobs, build software open to everyone, and stay out of your politics. Thanks for posting the links (which I’m sure are very informative) that I’m never going to read.

**Comment by fionic** [comment]
Well I definitely would opt out of this software if I didn’t work at a larger organization that uses it. But thanks for making my point, this is open source software, this is not (or shouldn’t be because it certainly seems to be) your personal platform for expressing your propaganda viewpoints. The rest of us want to do our jobs, build software open to everyone, and stay out of your politics. Thanks for posting the links (which I’m sure are very informative) that I’m never going to read.
