### ISSUE TITLE
moment.format('DD-MM-YYYY HH:MM:SS) giving different result.

### ISSUE THREAD

**Issue by AjayJha7** [moment/moment#5730]
moment('2020-01-11 00:00:00.0).format('DD-MM-YYYY HH:MM:SS) given output as 01-11-2020 00:00:00

Thee are other date as well where we have seen input and output date is not matching.

What could be the possible issue and how can we resolve that.

**Comment by marwahaha** [comment]
Sorry you are having an issue.
The library is doing what you configured it to do.
DD-MM-YYYY HH:MM:SS puts days, then months, then years. You can change it if you'd like (i.e. YYYY-MM-DD)
