### ISSUE TITLE
Moment gives unexpected results in hindi locale 

### ISSUE THREAD

**Issue by GuptaPurujit** [moment/moment#5739]
**Describe the bug**
While using this library for my project, I found out that some of the Hindi months are being parsed incorrectly for eg. 
 `moment("16 फरवरी 2020", ["DD MMMM YYYY"], "hi").format("MMMM")`.
This should return:
expected : `"फरवरी"`
but it actually returns : `"जनवरी"`

On more testing I found out that this issue only occurs when I try to parse फरवरी (February), सितंबर (September), नवंबर (November). दिसंबर (December)

**To Reproduce**
`console.log(moment("16 फरवरी 2020", ["DD MMMM YYYY"], "hi").format("MMMM"))`
`console.log(moment("16 सितंबर 2020", ["DD MMMM YYYY"], "hi").format("MMMM"))`
`console.log(moment("16 नवंबर 2020", ["DD MMMM YYYY"], "hi").format("MMMM"))`
`console.log(moment("16 दिसंबर 2020", ["DD MMMM YYYY"], "hi").format("MMMM"))`

**Expected behavior**
 `moment("16 फरवरी 2020", ["DD MMMM YYYY"], "hi").format("MMMM")`.
This should return:
expected :  `फरवरी` (February), `सितंबर` (September), `नवंबर` (November). `दिसंबर` (December)
but it actually returns : `"जनवरी"` for all the above inputs.

**Comment by rahul-sangvikar** [comment]
@GuptaPurujit , you're passing the wrong names (or at least passing the names differently than what the locale is expecting). Here is the list of all the valid months
`["जनवरी", "फ़रवरी", "मार्च", "अप्रैल", "मई", "जून", "जुलाई", "अगस्त", "सितम्बर", "अक्टूबर", "नवम्बर", "दिसम्बर"]`
I agree that displaying just `जनवरी` can be misleading, but I am not sure whether moment should throw an error or accept multiple valid full names for a month. Thoughts?

**Comment by GuptaPurujit** [comment]
Yeah you're right , but these aren't wrong spellings these are just another ways of writing these months . On digging deeper I found out that Hindi language is highly inflected that's the reason parser doesn't work.
#5692 is a similar issue to this one , but it already has an approved PR(#5728) associated with it , but isn't merged yet with the master branch. I tried to run code(#5728) within that PR and it works fine handling the inflections as well thus resolving the issue. 

@rahul-sangvikar what do you think about it?

**Comment by Kartik18g** [comment]
@GuptaPurujit (#5728) did solve this issue.

**Comment by rahul-sangvikar** [comment]
@GuptaPurujit , if you have to deploy your app in production, as @Kartik18g said, you can use the workaround till the [PR](https://github.com/moment/moment/pull/5728) is merged.

**Comment by Kartik18g** [comment]
@GuptaPurujitt @rahul-sangvikar  As far as i can see PR(#5728) is already approved but is waiting for approval by one more  hindi speaker, we are hindi speakers can we do something ?

**Comment by rahul-sangvikar** [comment]
@Kartik18g , I haven't contributed to moment yet, so idk if there are any standard pre-requisites that a PR should follow before getting an approval. I suggest you ask someone who is acquainted with the procedure.

**Comment by marwahaha** [comment]
It sounds like you all think the fix is correct. So I will merge it.
