### ISSUE TITLE
moment("TEST 451") produces a valid date.

### ISSUE THREAD

**Issue by petrell9** [moment/moment#5743]
**Describe the bug**
Creating a moment date with some text followed by whitespace and then ending with a number will produce a valid date.
(i.e. something like `/\s*\d*$/`). Removing the whitespace before the number seems to fix it, also numbers from 20-29 (e.g. `moment("Test 23"`)) will correctly produce an invalid date.

**To Reproduce**
`moment("TEST 451")` results in `Sun Jan 01 0451 00:00:00 GMT-0528`
`moment("h e l l o 2")` results in `Thu Feb 01 2001 00:00:00 GMT-0500`

**Expected behavior**
This should be an invalid date.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome 
 - 85.0.4183.121

**Moment-specific environment**
* Other libraries in use (TypeScript, Immutable.js, etc)
Tested with TypeScript and just a vanilla JS environment.

Please run the following code in your environment and include the output:
``` js
>>> console.log((new Date()).toString())
'Fri Oct 02 2020 09:56:36 GMT-0400 (Eastern Daylight Time)'
>>> console.log((new Date()).toLocaleString())
'10/2/2020, 09:56:36 AM'
>>> console.log((new Date()).getTimezoneOffset())
240
>>> console.log(navigator.userAgent)
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36'
>>> console.log(moment.version)
'2.29.0'
```
I may be mistaken but I'm pretty sure this is a bug. I hope this is enough info to reproduce, if I omitted anything important just let me know and I'll add it ASAP. Thanks!

**Comment by rahul-sangvikar** [comment]
@petrell9 , I debugged the issue and it's using a deprecated function which says that `Non RFC2822/ISO date formats` will be removed in the upcoming major release.
```
hooks.createFromInputFallback = deprecate(
       'value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), ' +
        'which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are ' +
        'discouraged and will be removed in an upcoming major release. Please refer to ' +
        'http://momentjs.com/guides/#/warnings/js-date/ for more info.',
        function (config) {
            config._d = new Date(config._i + (config._useUTC ? ' UTC' : ''));
        }
    );
```
PS: I am not a contributor yet, just debugged out of curiosity

**Comment by marwahaha** [comment]
Thanks for opening this request. This is known behavior.
Without using strict mode, some strings may be parsed as dates, like the one you mention.
I recommend using strict mode: https://momentjs.com/guides/#/parsing/strict-mode/

All the best with your project.
