### ISSUE TITLE
moment().dayOfYear() slow in iOS(React-Native)

### ISSUE THREAD

**Issue by rimzici** [moment/moment#5747]
**Describe the bug**
Calling the method moment().dayOfYear() inside a loop, which seem to slow down the app.

I suspect it is related to JS Core used in iOS. Because the issue occurs only in iOS devices(tested in simulator as well real device, have not tested the release build though). And when debug using chrome is enabled it works fine, as JS Code now runs on chrome. Always works fine in Android.

**Expected behavior**
Should behave across all platforms(iOS & Android), without noticeable delay.

**Smartphone (please complete the following information if applicable):**
 - Device:  iPhone11
 - OS: iOS14
 - Browser react-native(v0.63.3)
 - moment(v2.27.0)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()) -> Mon Oct 05 2020 13:44:03 GMT+0530 (IST)
console.log((new Date()).toLocaleString()) -> 10/5/2020, 1:44:03 PM
console.log((new Date()).getTimezoneOffset()) -> -330
console.log(navigator.userAgent) -> undefined
console.log(moment.version) ->  2.27.0
```

Thanks!

**Comment by marwahaha** [comment]
Thanks for the bug report.
Unfortunately, this doesn't seem like a bug in Moment.js . So I think it is best to report the issue somewhere else, for example where "JS Core" is made. 
Perhaps, do you mean this project? https://github.com/zloirock/core-js Then you can open an issue there.
Best of luck!
