### ISSUE TITLE
endOf('m'): return wrong timezone

### ISSUE THREAD

**Issue by thuthuatna** [moment/moment#5751]
moment({year:2020, month:9}).startOf('month').format() ==> 2020-10-01T00:00:00+02:00"
moment({year:2020, month:9}).endOf('month').format() ==> "2020-10-01T00:00:00+01:00"

Wrong timezone, it appear when I set timezone local is +2, (paris-France). 
Browser: Chrome.

**Comment by marwahaha** [comment]
Hi, sorry I cannot reproduce this. Why does endOf('month') report 2020-10-01 ?

I see 
```
moment({year:2020, month:9}).endOf('month').format()
"2020-10-31T23:59:59-07:00"
```

**Comment by marwahaha** [comment]
I see you also got this result.
https://github.com/moment/moment/issues/5750

If you have more issues, please re-open.
