### ISSUE TITLE
Wrong short date tranlation for locale tr

### ISSUE THREAD

**Issue by gulcenes** [moment/moment#5753]
**Describe the bug**
According to Turkish Language Association.
Translations are wrong for short versions of Monday and Saturday in Turkish.

Case -> Pts and Cts.

**Expected behavior**
Monday : Pzt instead of Pts
Saturday: Cmt instead of Cts

**Screenshots**
![image](https://user-images.githubusercontent.com/51911921/95734473-2cb5d180-0c8c-11eb-9553-b284988a0245.png)

**Comment by DiegoBousfield** [comment]
Does the changes on this PR #5756 fix the problem?

**Comment by gulcenes** [comment]
@DiegoBousfield Yes.
