### ISSUE TITLE
Z works but not z

### ISSUE THREAD

**Issue by SeanDez** [moment/moment#5757]
Most of my time time string is working except `z`:

```
Oct 18, 2020 at 1:10 AM (+07:00 )
```
Before the end `)` there should be `ICT`. Here is how I am formating the above date:

```
moment(start_timestamp).format('MMM D[,] YYYY [at] H:MM A [(]Z z[)]'
```

Is something being done wrong to cause big Z to work but not little z?

**Comment by marwahaha** [comment]
@SeanDez sorry this is happening to you. You probably need to check you are using Moment Timezone, not just regular moment.

Without moment timezone:
```
moment().format('MMM D[,] YYYY [at] H:MM A [(]Z z[)]')
```
> "Oct 19, 2020 at 16:10 PM (-07:00 )"


With moment timezone:
```
moment.tz([2012, 0], 'America/New_York').format('MMM D[,] YYYY [at] H:MM A [(]Z z[)]')
```
> "Jan 1, 2012 at 0:01 AM (-05:00 EST)"

**Comment by marwahaha** [comment]
Please re-open if you still have concerns.
