### ISSUE TITLE
stop BLM propaganda

### ISSUE THREAD

**Issue by Alino** [moment/moment#5759]
I think our industry should be neutral and not support any political propaganda and unrelated movements to our projects.

I know this is going to get closed without discussion.

So for anyone who reads this and feels like me -> there is an alternative to this library which uses native Dates 

> date-fns

https://date-fns.org/

**All lives matters equally.**

**Comment by NickMaev** [comment]
Agree.
BLM is a terroristic movement that advocates violence against non black people.
Most software developers are whites.
Stop BLM propaganda.
All lives matter.

**Comment by AlejandroMut** [comment]
Completely agree. Stop politicizing everything!

**Comment by politicsruinseverything** [comment]
When you announce support for a political organization, especially one that calls for violence, all code associated with you becomes suspect. Would you knowingly install software from someone who openly supports subversion? It is irresponsible to your customers and to your employer to utilize software from people like this. Might as well just install viruses, trojan horses, worms and the like. And now I'm even suspicious of the 4 or so libraries recommended as alternatives to moment. Guilty by association.

**Comment by MarcGodard** [comment]
I agree why are you guys being political. You are a stupid js library. wtf?

Why do you guys promote violence? And a violent movement that only rich white people agree with. Not a single black person in any community that I have ever worked with would agree to blm. Only the rich white people agree with this crap.

Why would I want to use your stupid library now?
