### ISSUE TITLE
date format invalid for single digit dates

### ISSUE THREAD

**Issue by suhail339** [moment/moment#5763]
Hello, thanks for this wonderful project.
I am using CDN https://momentjs.com/downloads/moment.js
**Problem**
I am facing validation issue on below formats, looks a bit weird.

true : moment("Thursday, October 12, 2020", "dddd, MMMM DD, YYYY", true).isValid();
false : moment("Thursday, October 1, 2020", "dddd, MMMM DD, YYYY", true).isValid();

Any help or reference will be appreciated.

Thanks for your time.

**Comment by marwahaha** [comment]
Use `D` for 1-31 (no leading zeros), `DD` for 01-31 (two-digits)
https://momentjs.com/docs/#/parsing/string-format/

For example:
```
moment("Monday, October 5, 2020", "dddd, MMMM D, YYYY", true).isValid();
```

**Comment by suhail339** [comment]
@marwahaha thanks alot. stupid of me.
