### ISSUE TITLE
Cannot import modules under directory "dist/locale/" directly, in browser

### ISSUE THREAD

**Issue by fuweichin** [moment/moment#5767]
**Describe the bug**

Cannot import modules under directory "dist/locale/" directly in browser.

**To Reproduce**

1. I want to import momentjs lib and one of its locale directly in browser

   ```html
   <script type="module">
   import moment from '/node_modules/moment/dist/moment.js';
   let lang='zh-cn';
   import('/node_modules/moment/dist/locale/'+lang+'.js');
   // ...
   </script>
   ```

**Actual result**

404 Not Found /node_modules/moment/dist/moment

The request is initiated by this line

http://localhost:8080/node_modules/moment/dist/locale/zh-cn.js:7

 `import moment from '../moment';`

**Expected behavior**

Use momentjs directly in browser without any compiler / transformer / bundler.

**Possible solutions**

+ for project maintainers: ensure the `.js` extension present in files under 'dist/locale/', say `import moment from '../moment.js';` 
+ for momentjs users : configure your web server to try `.js` extension, like Nginx `try_files $uri $uri.js;` as a workaround 

**Additional context**

 - Browser: any
 - Version 2.29.1

**Comment by ashsearle** [comment]
If you're playing around importing packages from a CDN like unpkg, you can omit the .js extension:

```html
<script type="module">
  import moment from "https://unpkg.com/moment@2.29.1/dist/moment";
  import "https://unpkg.com/moment@2.29.1/dist/locale/zh-cn";
  console.log(moment.version, moment.locales()) // 2.29.1, ['en', 'zh-cn']
</script>
```

This doesn't work without the `@version` present in the URL as unpkg responds with a redirect, which causes a mismatch between the explicit import for moment vs import used inside the locale file:

```html
<script type="module">
  /* First import gets redirected to
   * https://unpkg.com/moment@2.29.1/dist/moment
   * then https://unpkg.com/moment@2.29.1/dist/moment.js
   */
  import moment from "https://unpkg.com/moment/dist/moment";

  /* Second import gets redirected to
   * https://unpkg.com/moment@2.29.1/dist/locale/zh-cn
   * then https://unpkg.com/moment@2.29.1/dist/locale/zh-cn.js
   */
  import "https://unpkg.com/moment/dist/locale/zh-cn";

  /*
   * The locale file imported moment using a relative path:
   * import '../moment'
   * which resolved to https://unpkg.com/moment@2.29.1/dist/moment
   * and was redirects to https://unpkg.com/moment@2.29.1/dist/moment.js
   *
   * Because "https://unpkg.com/moment@2.29.1/dist/moment" !== "https://unpkg.com/moment/dist/moment"
   * the browser treats these as separate modules, so the locale augments
   * an inaccessible second copy of the moment module that we don't have
   * access to.
   *
   * This means the moment does not get enhanced with the loaded locale:
   */
  console.log(moment.version, moment.locales()) // 2.29.1, ['en']
</script>
```
