### ISSUE TITLE
Date is not properly set , niether is the output correct

### ISSUE THREAD

**Issue by abhishekwebcode** [moment/moment#5771]
I use momentJS to get date formatted string, coming straight to the point, when I Run...

`moment().tz('Asia/Kolkata').date(31).month(9).year(2020).format('Do MMM YYYY') `

It gives me "**1st Oct 2020**"

Is there something wrong on my machine ?

Expected Result: "**31st Oct 2020**"

**Comment by ashsearle** [comment]
You've created a `moment()` for now (in November), then set it to the 31st of the month.  As November only has 30 days, that rolls over and sets the date to 1st December.

```js
moment().tz('Asia/Kolkata').format('Do MMM YYYY') // 2nd Nov 2020
moment().tz('Asia/Kolkata').date(31).format('Do MMM YYYY') // 1st Dec 2020
```

Try changing the order you set things:
```js
moment().tz('Asia/Kolkata').year(2020).month(9).date(31).format('Do MMM YYYY')
```

**Comment by abhishekwebcode** [comment]
@ashsearle thanks :smiley:
