### ISSUE TITLE
[FEATURE-REQUEST] Complete removal of time / date units from a moment string

### ISSUE THREAD

**Issue by DavidVainer** [moment/moment#5784]
Sometimes when we get a time / date string, there's a need to remove some parts of it .  
To do so we need to determine the string's format, and then reformat it again.  
So in order to remove year for example:
````
Moment('05-03-2020 12:20', 'MM-DD-YYY hh:mm).format('MM-DD hh:mm');
````
I find it a little potentially unnecessary.  
Maybe a better will be something like:
````
Moment('05-03-2020 12:20', 'MM-DD-YYY hh:mm).remove('year');
````
and the output will be:
````
05-03 12:20
````

If there's a positive response, I'd be happy to add that feature.   
**B.T.W** - I'm kinda new to this package, so if there IS an existing way to achieve that - do tell :)

**Comment by ichernev** [comment]
1. It is not clear how this could be implemented. You'll have to find punctuation characters around the thing you're removing and remove those too, in certain circumstances.
2. I don't think it is useful enough.
3. we're kinda feature frozen at (the) moment, so ... 

NO
