### ISSUE TITLE
'Moment::set' return a Number when passing undefined to value argument

### ISSUE THREAD

**Issue by Deliay** [moment/moment#5791]
**Describe the bug**
```js
const result = moment().set('hours', void 0);
console.log(typeof result);
// number
```

**Expected behavior**
Throw an error or return a moment instance

**Moment-specific environment**
Test on moment official website
https://momentjs.com/

Please run the following code in your environment and include the output:
```
Mon Dec 07 2020 17:00:59 GMT+0800 (China Standard Time)
12/7/2020, 5:00:59 PM
-480
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.52
```

**Comment by marwahaha** [comment]
`moment().set('hours', undefined)` is like running `moment().set('hours')` which returns a Number.
