### ISSUE TITLE
week display error

### ISSUE THREAD

**Issue by donley828** [moment/moment#5796]
**Describe the bug**
moment('2019-12-30').format('YYYY-wo') // 2019-1st expect 2019-53st
moment('2019-12-30').week('w') // 1    expect 53

**To Reproduce**
[https://codesandbox.io/s/ecstatic-curran-dvyhs?file=/src/index.js:329-505](codesandbox)
please view console

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Browser chrome
 - Version 87.0.4280.88

**Moment-specific environment**
moment v2.29.1

Please run the following code in your environment and include the output:
```
console.log(moment("2019-12-30").format("YYYY-wo"));
console.log(moment("2019-12-30").year(), moment("2019-12-30").week());
console.log(moment("2020-01-03").format("YYYY-wo"));
```

**Additional context**

**Comment by kkojot** [comment]
Same problem here. The following code:
```javascript
console.log(moment("2020-12-28").isoWeekday(7).format("WYY"));
console.log(moment("2021-01-01").isoWeekday(7).format("WYY"));
console.log(moment("2021-01-03").isoWeekday(7).format("WYY"));
```
returns `5321` which means a 53 week of 2021.  I'm not sure what the correct value should be, maybe `5320` or `121`. Similar Java code returns `020` which looks incorrect to me too lol, but `5321` is definitely incorrect.

**Comment by GrayFrost** [comment]
> Same problem here. The following code:
> 
> ```js
> console.log(moment("2020-12-28").isoWeekday(7).format("WYY"));
> console.log(moment("2021-01-01").isoWeekday(7).format("WYY"));
> console.log(moment("2021-01-03").isoWeekday(7).format("WYY"));
> ```
> 
> returns `5321` which means a 53 week of 2021. I'm not sure what the correct value should be, maybe `5320` or `121`. Similar Java code returns `020` which looks incorrect to me too lol, but `5321` is definitely incorrect.

Excuse me, did you get the correct way to solve this problem. I met same problem.

**Comment by kkojot** [comment]
To be honest, no, but I hope this issue is going to be solved soon ;-)

**Comment by GrayFrost** [comment]
> To be honest, no, but I hope this issue is going to be solved soon ;-)

Try this [solution](https://stackoverflow.com/questions/25631682/moment-js-thinks-that-2013-12-31-is-week-1-not-week-53)。Use 'GGGG' instead of 'YYYY'。

**Comment by ashsearle** [comment]
Code in the original issue uses `w` which is the locale-aware week, so for completeness:
* Use `gggg` with `w`, `ww` or `wo`
* Use `GGGG` with `W`, `WW` or `Wo`
