### ISSUE TITLE
Incorrect Date format

### ISSUE THREAD

**Issue by maisans-maid** [moment/moment#5797]
**Describe the bug**
When formatting a date from a string, output is incorrect.

**To Reproduce**
```js
const moment = require('moment.js');

// format date from string
const date = moment('12-12-1999', 'DD-MM-YYYY');

// check if format is valid
date.isValid() // expected outcome 'true'

// format date
const formatted = date.format('do MM YYYY')// returns 0th December 1999, expected 12th December 1999

```
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A -> Nodejs
 - Version: 14.x

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

**Additional context**

**Comment by incode-sd** [comment]
@maisans-maid To get your preferred output, use `date.format('Do MM YYYY')` . 
If it doesn't works, find more details & examples below:-

Tested in Moment 2.29.1. You can use the below format as per your output need.

```
console.log(date.format('Do MMMM YYYY')); // o/p : 12th December 1999
console.log(date.format('Do MMM YYYY')); // o/p : 12th Dec 1999
console.log(date.format('Do MM YYYY')); // o/p : 12th 12 1999
```
Desktop information:

- OS: Arch Linux
- Browser: N/A -> Nodejs
- Version: v12.16.1

Outputs in my Environment:-
```
console.log((new Date()).toString()); // o/p : Wed Dec 23 2020 15:59:03 GMT+0000 (Coordinated Universal Time)
console.log((new Date()).toLocaleString()); // o/p : 12/23/2020 3:59:03 PM
console.log((new Date()).getTimezoneOffset()); // o/p : 0
//console.log(navigator.userAgent); // o/p : navigator is not defined
console.log(moment.version); // o/p : 2.29.1
```

**Comment by maisans-maid** [comment]
yeah, seems like a mistake on my end. Thanks
