### ISSUE TITLE
I want to know how much smaller moment3.x is than moment2.x

### ISSUE THREAD

**Issue by a951055** [moment/moment#5798]
Although 3.x has not been developed yet, but i want to know how much smaller moment3.x is than moment2.x.
For example, does it include module loading like dayjs. After all, 2. X is too heavy now.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by michaeljaltamirano** [comment]
@a951055 https://momentjs.com/docs/#/-project-status/
