### ISSUE TITLE
Best way to override meridiem for short am/pm format.

### ISSUE THREAD

**Issue by niemyjski** [moment/moment#580]
Is there a best practice for changing the meridiem behavior to return a or p instead of am/pm without side effects?

I get that I can change the function to return lowercase p/a and have done so (http://momentjs.com/docs/#/customization/). But I was wondering if there was a better way to do so or if we could implement a new format character for shorthand am/pm. .NET allows this via the t character (http://msdn.microsoft.com/en-us/library/8kb3ddd4.aspx section: The "t" custom format specifier )

**Comment by jemartin80** [comment]
I stumbled across this, and it's been updated since 2013. The best way to do this now is 

```javascript
    moment.updateLocale('en', {
        meridiem: function (hours, minutes, isLower) {
            if (hours > 11) {
                return isLower ? 'p' : 'P';
            } else {
                return isLower ? 'a' : 'A';
            }
        }
    });
````

**Comment by aleen42** [comment]
With using `moment@2.22.2`, `moment.updateLocale` is not a way to update as `moment` won't merge configuration if we have load `en` before.
