### ISSUE TITLE
Incorrect year when adding days

### ISSUE THREAD

**Issue by atkach** [moment/moment#5800]
**Describe the bug**
If you try to add more days that left in the year then the year should be incremented, but it's stays the same, although month is correctly incremented

**To Reproduce**
1. Create a Moment date, if today is December 31 then just 
`const date = moment();`
otherwise
` const date = moment('2020-12-31');`
2. Add a day to date
`date.add(1, 'd');`
3. Output date
`const output = date.format('GGGG-MM-DD');`
 
**Expected behavior**
Date should be `2021-01-01`

**Actual behavior**
Date is` 2020-01-01`

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()) // Thu Dec 31 2020 14:26:04 GMT+0200 (Eastern European Standard Time)
console.log((new Date()).toLocaleString()) // 12/31/2020, 2:26:04 PM
console.log((new Date()).getTimezoneOffset()) // -120
console.log(navigator.userAgent) // Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.12.0
console.log(moment.version) // 2.24.0
```

**Comment by incode-sd** [comment]
@atkach To get your preferred output, use `const output = date.format('YYYY-MM-DD');` .
`GGGG` is the year of the ISO week and not the actual year. An ISO week-numbering year has 52 or 53 full weeks. 
That is 364 or 371 days instead of the usual 365 or 366 days. 

For more info, you can refer the moment [docs](https://momentjs.com/docs).

Tested in Moment 2.29.1. You can use the below format as per your output need.
```
const output = moment('2020-12-31').add(1, 'd').format('YYYY-MM-DD');
console.log(output); // o/p : 2021-01-01
```

**Comment by atkach** [comment]
> @atkach To get your preferred output, use `const output = date.format('YYYY-MM-DD');` .
> `GGGG` is the year of the ISO week and not the actual year. An ISO week-numbering year has 52 or 53 full weeks.
> That is 364 or 371 days instead of the usual 365 or 366 days.
> 
> For more info, you can refer the moment [docs](https://momentjs.com/docs).
> 
> Tested in Moment 2.29.1. You can use the below format as per your output need.
> 
> ```
> const output = moment('2020-12-31').add(1, 'd').format('YYYY-MM-DD');
> console.log(output); // o/p : 2021-01-01
> ```

Thanks, it solved my issue.
