### ISSUE TITLE
corresponding translation of the Yoruba numeral system.

### ISSUE THREAD

**Issue by Caleb335** [moment/moment#5801]
**Is your feature request related to a problem? Please describe.**
While going through the documentation of moment.js on the website, I tried clicking the Yoruba language translation, though it worked, the point where it translates the relative time, there shouldn't be a typical number, but a Yoruba representation of that number.

**Describe the solution you'd like**
The correct usage of the Yoruba numeral.

**Describe alternatives you've considered**
I'd love to work on this issue if you'd allow me.
The approach I'd be using would have to do with me inputting the numerals myself. I was thinking of fetching Data from an API, but I haven't come across any.

**Additional context**
![Screenshot from 2021-01-02 15-17-47](https://user-images.githubusercontent.com/48127194/103459221-ec577400-4d0d-11eb-8721-ee618398379d.png)
![Screenshot from 2021-01-02 15-16-49](https://user-images.githubusercontent.com/48127194/103459232-f2e5eb80-4d0d-11eb-9f5a-336724363296.png)

**Comment by marwahaha** [comment]
Perhaps we can add a symbolMap and numberMap as in Hindi and Arabic:
https://github.com/moment/moment/blob/develop/src/locale/hi.js#L7

**Comment by Caleb335** [comment]
I went through the link to the file you replied with and  Yes, that should work fine too...

**Comment by ashsearle** [comment]
I think this might be far more complex than that.  It looks like Yoruba numeral system is base-20 instead of base-10?

See https://core.ac.uk/download/pdf/186756092.pdf

**Comment by Caleb335** [comment]
@ashsearle Thanks for sharing this info with me. I literally had no idea about the numeral base system lol 😃

I had already started going through the journal. I hope to integrate the knowledge I get from it into this issue.

**Comment by marwahaha** [comment]
Because this will require a new numeral system, I recommend implementing this as a plugin: https://momentjs.com/docs/#/plugins/
