### ISSUE TITLE
Moment.format('W-Y') returns an output that returns invalid date when parsed with moment(str, 'W-Y')

### ISSUE THREAD

**Issue by nirshabi10** [moment/moment#5802]
**Description**
Moment returns a string that returns an invalid date when parsed with moment

**To Reproduce**
1. take a date that starts from "2021-01-01T00:00:00.000Z" to "2021-01-03T23:59:59.999Z"
2. use the format 'W-Y'
3. use moment(date).format(format) --> const momentStr = moment("2021-01-01T00:00:00.000Z").format('W-Y')
4. Try to use moment to parse the new string -moment(momentStr, 'W-Y')
5. See the error: moment.invalid(/* 53-2021 */)

**Expected behavior**
Should return a valid string that can be parsed by moment with the same format

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()) - Sun Jan 03 2021 13:15:08 GMT+0200 (Israel Standard Time)
console.log((new Date()).toLocaleString()) - 1/3/2021, 1:15:19 PM
console.log((new Date()).getTimezoneOffset()) - -120
console.log(navigator.userAgent) - not relevant, using node on terminal
console.log(moment.version) - 2.24.0
```

**Additional context**

**Comment by ashsearle** [comment]
Use a 'week year' format string instead of a the calendar year.

You're currently mixing ISO Week numbers with the calendar year (instead of the ISO Week Year.)  This is impossible to parse, as the start and end of the year may have the same week number:
```js
moment('2022-01-01').format('W-Y'); // 52-2022
moment('2022-12-31').format('W-Y'); // also 52-2022
```

Use `GGGG` to format (and parse) the ISO Week Year:
```js
moment('2022-01-01').format('W-GGGG'); // 52-2021 (i.e. belongs to a week that started in the last calendar year)
moment('2022-12-31').format('W-GGGG'); // 52-2022
```

If you want to use locale aware weeks rather than ISO weeks for some reason, you can do that too with `w-gggg`:
```js
['en-us', 'de'].forEach((locale) => {
    moment.locale(locale);
    ['W-Y', 'W-GGGG', 'w-gggg'].forEach((formatStr) => {
        const formatted = moment('2021-01-01T00:00:00.000Z').format(formatStr);
        const reparsed = moment(formatted, formatStr, true).toString();
        console.log({ locale, formatStr, formatted, reparsed });
    });
});
/*
outputs:
{
  locale: 'en-us',
  formatStr: 'W-Y',
  formatted: '53-2021',
  reparsed: 'Invalid date'
}
{
  locale: 'en-us',
  formatStr: 'W-GGGG',
  formatted: '53-2020',
  reparsed: 'Mon Dec 28 2020 00:00:00 GMT+0000'
}
{
  locale: 'en-us',
  formatStr: 'w-gggg',
  formatted: '1-2021',
  reparsed: 'Sun Dec 27 2020 00:00:00 GMT+0000'
}
{
  locale: 'de',
  formatStr: 'W-Y',
  formatted: '53-2021',
  reparsed: 'Invalid date'
}
{
  locale: 'de',
  formatStr: 'W-GGGG',
  formatted: '53-2020',
  reparsed: 'Mon Dec 28 2020 00:00:00 GMT+0000'
}
{
  locale: 'de',
  formatStr: 'w-gggg',
  formatted: '53-2020',
  reparsed: 'Mon Dec 28 2020 00:00:00 GMT+0000'
}
*/
```
