### ISSUE TITLE
when validating date in strict mode, "3:30 A / 3:30 P" is a valid time ( I would expect that 3:30 "AM" or "PM" are the only possible abbreviations)

### ISSUE THREAD

**Issue by kac3nka** [moment/moment#5803]
**Describe the bug**

Moment('01/24/2022 3:35 A', 'MM/DD/YYYY h:mm A', true).isValid() -> in strict mode returns true, even though the abbreviation for meridiem is not correct

when browsing in Moment.js source code, I found this regExp which makes the M optional, but Moment documentation states that only AM/PM is valid meridiem ->
Moment.js source code:
defaultLocaleMeridiemParse = /[ap]\.?m?\.?/i

**To Reproduce**
1. use the isValid method -> in my example Im validating english format with AM/PM: 
Moment('01/24/2022 3:35 A', 'MM/DD/YYYY h:mm A', true).isValid() 
2. returns true instead of false

**Expected behavior**
Expected result -> "isValid" method shall return "false", because the correct meridiem abbrevation is missing (AM/PM) 

**Screenshots**
![image](https://user-images.githubusercontent.com/26040601/103551184-468d3c00-4eaa-11eb-95a0-acce2cd5539d.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version "moment": "2.18.1"

**Comment by ashsearle** [comment]
This is [documented](https://momentjs.com/docs/#:~:text=Post%20or%20ante%20meridiem) under [String + Format](https://momentjs.com/docs/#/parsing/string-format/):
> Post or ante meridiem (Note the one character a p are also considered valid)
