### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by danadalleh** [moment/moment#5806]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information if applicable):**
 - Browser [e.g. firefox, safari]

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

**Additional context**

**Comment by danadalleh** [comment]
This night

**Comment by NotMoni** [comment]
@marwahaha I feel there are many issues like these that are just spam at this point. I feel someone should clean up these issues. I am interested in this project and ask if I can clean up issues like these.

**Comment by marwahaha** [comment]
@NotMoni - sure. Can you tag me in more issues that should be cleaned up?

@danadalleh I will close this issue because I don't understand the question. Please open a new issue if you still have questions.

**Comment by R5517** [comment]
Hi

**Comment by R5517** [comment]
Hi
