### ISSUE TITLE
.week() and locale('de) and Year 2021 returns data from 2020

### ISSUE THREAD

**Issue by Dettenrocks** [moment/moment#5808]
Hello,

incorrect data is returned with locale 'de' and .week().

with locale 'en', i have no problems.

incorrect data is returned

`console.log(moment('2020-01-01').week(2).startOf('week').format('YYYY-MM-DD'));`
`console.log(moment('2020-01-01').week(2).endOf('week').format('YYYY-MM-DD'));`

with locale('de')
2020-01-06
2020-01-12

with locale('en')
2021-01-03
2021-01-09

Information:

`console.log((new Date()).toString());`
`console.log((new Date()).toLocaleString());`
`console.log((new Date()).getTimezoneOffset());`
`console.log(moment.version);`

de
Mon Jan 11 2021 11:01:12 GMT+0100 (GMT+01:00)
2021-1-11 11:01:12
-60
2.29.1

**Comment by Dettenrocks** [comment]
i make a check for the year 1950 until 2050.

this year are wrong:

`moment = require('moment');
moment.locale('de');

for (var i = 1950; i < 2050; i++) {
  let search = i.toString();
  let result = moment(i.toString()).week(5).startOf('week').format('YYYY');
  if (search !== result) {
    console.log(search + ' != ' + result);
  }
}`

year -> result

1950 != 1949
1954 != 1953
1955 != 1954
1956 != 1955
1960 != 1959
1961 != 1960
1965 != 1964
1966 != 1965
1967 != 1966
1971 != 1970
1972 != 1971
1977 != 1976
1978 != 1977
1982 != 1981
1983 != 1982
1984 != 1983
1988 != 1987
1989 != 1988
1993 != 1992
1994 != 1993
1995 != 1994
1999 != 1998
2000 != 1999
2005 != 2004
2006 != 2005
2010 != 2009
2011 != 2010
2012 != 2011
2016 != 2015
2017 != 2016
2021 != 2020
2022 != 2021
2023 != 2022
2027 != 2026
2028 != 2027
2033 != 2032
2034 != 2033
2038 != 2037
2039 != 2038
2040 != 2039
2044 != 2043
2045 != 2044
2049 != 2048

**Comment by DanielASMPT** [comment]
I guess i got the same problem.
Last year this code would give me the current start date of the actual calender week:

`moment().day("Monday").year(moment().year()).week(moment().isoWeek()).startOf('day');`
Output:
`Mon Jan 04 2021 00:00:00 GMT+0100`
Exptected Output:
`Mon Jan 11 2021 00:00:00`

But this year it is shifted back by one week.

**Comment by ashsearle** [comment]
@DanielASMPT / @Dettenrocks You're missing the concept of a [week year](https://momentjs.com/docs/#/get-set/week-year/).

When you call `week(x)` the date is adjusted within the current *week year*, which may not be the same as the calendar year for the first few days of Jan or last few days of December.

```js
moment = require('moment');
moment.locale('en-gb');

for (var i = 2020; i < 2030; i++) {
  const jan1st = moment(`${i}-01-01`);
  const dec31st = moment(`${i}-12-31`);
  if (jan1st.year() !== jan1st.weekYear()) {
    console.log(`${jan1st.format('ddd Do MMM YYYY')} belongs to week year ${jan1st.weekYear()}`);
  }
  if (dec31st.year() !== dec31st.weekYear()) {
    console.log(`${dec31st.format('ddd Do MMM YYYY')} belongs to week year ${dec31st.weekYear()}`);
  }
}
/*
Fri 1st Jan 2021 belongs to week year 2020
Sat 1st Jan 2022 belongs to week year 2021
Sun 1st Jan 2023 belongs to week year 2022
Tue 31st Dec 2024 belongs to week year 2025
Wed 31st Dec 2025 belongs to week year 2026
Fri 1st Jan 2027 belongs to week year 2026
Sat 1st Jan 2028 belongs to week year 2027
Mon 31st Dec 2029 belongs to week year 2030
*/
```

If you want to avoid all the locale variations, use `isoWeekYear()` with `isoWeek()`.

Note: you can format locale-aware week year with `format('gggg')` and ISO week year with `format('GGGG')`
