### ISSUE TITLE
Why is moment("02//2021", "L")  => 02/20/2021 and valid?

### ISSUE THREAD

**Issue by finalist-io** [moment/moment#5812]
Hello community 🙂

I'm trying to parse a string based on the locale of the user,
so I can't really pass the format as "MM/DD/YYYY" because the day and month are different in other countries. 
So I read that I can just use "L" as a format 
But when I try to parse "02//2021" its valid and the result is "02/20/2021".
Where does the day 20 come from?
And how do I parse a string based on the locale?

**Comment by ashsearle** [comment]
The docs for [String + Format](https://momentjs.com/docs/#/parsing/string-format/) say:
> The parser ignores non-alphanumeric characters by default, so both of the following will return the same thing.
>
> moment("12-25-1995", "MM-DD-YYYY");
> moment("12/25/1995", "MM-DD-YYYY");

And the `YYYY` token is treated as:
> 4 or 2 digit year. Note: Only 4 digit can be parsed on strict mode
> ...YYYY from version 2.10.5 supports 2 digit years, and converts them to a year near 2000 (same as YY).

You're *not* using strict mode, so year can be parsed as 2-digits.

When parsing "L" is replaced by the locale's specific format string: e.g. "MM/DD/YYYY".  So:
```js
moment("02//2021", "L"); // is like...
moment("02//2021", "MM/DD/YYYY"); // is like...
moment("022021", "MMDDYYYY");
```

The date gets parsed as: MM: 02, DD: 20, YYYY: 21, and year then gets converted to 2021.
