### ISSUE TITLE
moment("02/29/2001").isValid() s/b false

### ISSUE THREAD

**Issue by allenabc** [moment/moment#5813]
**Describe the bug**
 moment("02/29/2001").isValid() returns true
 moment("02/29/2001") returns March 1, 2001,

**To Reproduce**
> moment("02/29/2001").isValid()
true
> moment("02/29/2001")
Moment<2001-03-01T00:00:00-07:00>

**Expected behavior**

moment("02/29/2001").isValid() should return false

moment("02/29/2001") returns March 1, 2001, should 
return Invalid date

The Expected behavior using day 35 of February as an example
> moment("02/35/2001")
Moment Invalid date

**Screenshots**
None

**Desktop (please complete the following information):**
Ubuntu 20.4 using Node.js

**Smartphone (please complete the following information if applicable):**
None

**Moment-specific environment**

Please run the following code in your environment and include the output:
> console.log((new Date()).toString())
Sun Jan 17 2021 16:28:51 GMT-0700 (Mountain Standard Time)
undefined
> console.log((new Date()).toLocaleString())
1/17/2021, 4:28:51 PM
undefined
> console.log((new Date()).getTimezoneOffset())
420
undefined
> console.log(navigator.userAgent)
Uncaught ReferenceError: navigator is not defined
> console.log(moment.version)
2.29.1
undefined
> ```

**Additional context**
None

**Comment by ashsearle** [comment]
Try this in a browser console:
```js
moment("02/29/2001");
```

You'll see a warning:
> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

i.e. you're complaining about the behaviour of `new Date(string)`

```js
new Date('02/28/2001'); // February 28th 2001
new Date('02/31/2001'); // March 3rd 2001
new Date('02/32/2001'); // Invalid Date

new Date('04/30/2001'); // April 30th 2001
new Date('04/31/2001'); // May 1st 2001
new Date('04/32/2001'); // Invalid Date
```
