### ISSUE TITLE
StartOf() documentation

### ISSUE THREAD

**Issue by Blodhgard** [moment/moment#5814]
In the startOf() documentations, the comments in the code suggest that the time is set to the 12:00 AM
https://momentjs.com/docs/#/manipulating/start-of/

This is not true since the startOf() set the time to the 00:00:00 AM

**Comment by ashsearle** [comment]
The presence of "AM" or "PM" indicates the use of a 12-hour clock.

```js
// Use 'hh' for 12-hour format:
moment().startOf('day').format('hh:mm A'); // 12:00 AM
moment().startOf('day').add(12, 'hours').format('hh:mm A'); // 12:00 PM

// Use 'HH' for 24-hour format:
moment().startOf('day').format('HH:mm'); // 00:00
moment().startOf('day').add(12, 'hours').format('HH:mm'); // 12:00
```

**Comment by Blodhgard** [comment]
This is the line of code in the documentation:
moment().startOf('month');   // set to the first of this month, 12:00 am

I think it is confusing, it seems the function set it to 12:00 am of the first day of the month.
I suggest removing the ", 12:00 am" part.

**Comment by ashsearle** [comment]
That's significant information though, to distinguish it from:

```js
moment().date(1); // set to the first of this month.
```

**Comment by Blodhgard** [comment]
It could be
`moment().startOf('month'); // set to the first of this month, 00:00:00:000`
or something similar.
