### ISSUE TITLE
IMPORTANT Parsing bug with specific dates.

### ISSUE THREAD

**Issue by TheNewSound** [moment/moment#5819]
**Describe the bug**
When initializing a moment, given an array of possible parsing formats, momentjs takes the wrong parsing method even though based on the given data, the correct method should be clear. Happens only to specific dates.

**To Reproduce**
See JSFiddle: http://jsfiddle.net/kuxn7hcs/2/

```javascript
var now = moment("20090102",["DD-MM-YYYY","YYYYMMDD"]);
alert(now.year()); // SHOULD PRODUCE 2009 but produces 102 instead.
var now = moment("20180102",["DD-MM-YYYY","YYYYMMDD"]);
alert(now.year()); // CORRECTLY PRODUCES 2018
var now = moment("20090102",["YYYYMMDD","DD-MM-YYYY"]);
alert(now.year()); // CORRECTLY PRODUCES 2009
var now = moment("20180102",["YYYYMMDD","DD-MM-YYYY"]);
alert(now.year()); // CORRECTLY PRODUCES 2018
```

**Expected behavior**
See above

**Screenshots**
**Moment-specific environment**
```
Tue Jan 26 2021 04:14:46 GMT+0100 (Central European Standard Time)
1/26/2021, 4:14:46 AM
-60
NodeJS environment + browser same issue
2.29.1
```

**Additional context**

**Comment by ashsearle** [comment]
You could use [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/) to avoid this:

```js
var now = moment("20090102",["DD-MM-YYYY","YYYYMMDD"], true);
alert(now.year()); // is 2009
```

Without using strict mode (as in your original code), moment will try parses 20090102 as 20-09-0102:

> The parser ignores non-alphanumeric characters by default, so both of the following will return the same thing.
>
> moment("12-25-1995", "MM-DD-YYYY");
> moment("12/25/1995", "MM-DD-YYYY");

**Comment by TheNewSound** [comment]
> You could use [strict mode](https://momentjs.com/guides/#/parsing/strict-mode/) to avoid this:
> 
> ```js
> var now = moment("20090102",["DD-MM-YYYY","YYYYMMDD"], true);
> alert(now.year()); // is 2009
> ```
> 
> Without using strict mode (as in your original code), moment will parse 20090102 as 20-09-0102:
> 
> > The parser ignores non-alphanumeric characters by default, so both of the following will return the same thing.
> > moment("12-25-1995", "MM-DD-YYYY");
> > moment("12/25/1995", "MM-DD-YYYY");

Thanks! Quite weird that when specifying a format and deciding which one is more applicable, the parser doesn't take the whole format into account and strips useful things from it, causing this odd behaviour.

**Comment by TheNewSound** [comment]
The fact that interpretation is dependent on the date (numbers) given, makes this library extremely unreliable! Took me quite some time to figure out this root cause in my data analysis, especially because I'm dealing with a lot of data.
When I tried parsing a sample date I assumed it worked for every other value in the same manner, it didn't! Major issue!

**Comment by ashsearle** [comment]
You're not alone.  A lot of people (including maintainers) wanted to change moment to use strict mode by default (see issue #3722) - but it would have been a major breaking change.

Given the [project status](https://momentjs.com/docs/#/-project-status/), this will never change.
