### ISSUE TITLE
Default Timezone

### ISSUE THREAD

**Issue by niemyjski** [moment/moment#582]
I looked through the code and the customization documentation and couldn't figure out how to set a default timezone. I looked over the docs and it also wasn't very clear how to even change the time zone of a moment date.

So here is some context. I have a reporting application that I'm building. All dates are stored in UTC and returned from a web api (rest) call in UTC ('2012-12-14T00:29:40.276Z' <-- no time zone info). Multiple different users might be using the application and all data displayed needs to be and sometimes posted in a specific time zone (determined by the project). So the user may not be in the right timezone.

I noticed that doing:

console.log(moment.utc('2012-12-14T00:29:40.276Z')); 
{_d: Thu Dec 13 2012 18:29:40 GMT-0600 (Central Standard Time), _isUTC: true,

console.log(moment.utc('2012-12-14T00:29:40.276Z').format());
2012-12-14T00:29:40+00:00

console.log(moment.utc('2012-12-14T00:29:40.276Z').toDate());
Thu Dec 13 2012 18:29:40 GMT-0600 (Central Standard Time)

creates a date that is stored internally as utc but is displayed as my browsers timezone as shown above. Is there an config option or a setting I can set that sets a default timezone (via offset or zone) for all instances of moment e.g. moment().format() and moment.utc('2012-12-14T00:29:40.276Z').format() would display this time in a specific time zone.

**Comment by coreyzev** [comment]
This is what i'm doing now, right after I call moment, I call this:

```javascript
var tz_offset = -7;
moment.updateOffset = function (m) {
    return m.utcOffset(tz_offset);
};
```

every moment created after that is in the correct timezone.

**Comment by mj1856** [comment]
@coreyzev - that doesn't work when offsets change for DST (or other reasons).  See [my response to your other comment](https://github.com/moment/moment-timezone/issues/15#issuecomment-150847080).
