### ISSUE TITLE
Wrong Timezone (not DST)

### ISSUE THREAD

**Issue by idrisonehub** [moment/moment#5821]
**Wrong Timezone (not DST)**
I got the wrong timezone when deactivating Daylight Saving Time in Windows 10.

**To Reproduce**
1. Open 'Date & time settings'
2. Set time automatically to active
3. Set time zone automatically to non-active
4. Time zone is '(UTC+10:00) Canberra, Melbourne, Sydney'
5. Deactivating 'Adjust for daylight saving time automatically'
6. Run `moment().format()` in your code and got UTC-10:00

**Desktop:**
 - OS: Windows 10 Home Single Language
 - Browser: chrome
 - Version 88.0.4324.104 (Official Build) (64-bit)

Can you help me to show correct date?
Looks like the problem is in the chrome browser.

**Comment by CShot** [comment]
This is a google chrome browser issue.
https://bugs.chromium.org/p/chromium/issues/detail?id=1168528

**Comment by idrisonehub** [comment]
Thank you very much @CShot

**Comment by idrisonehub** [comment]
It looks like this problem has been fixed by Google Chrome with the latest version 88.0.4324.146 (Official Build) (64-bit)
