### ISSUE TITLE
a little issue 

### ISSUE THREAD

**Issue by lionshushu** [moment/moment#5823]
i found time is different in  before16:00 and after , i use moment  when form submit . (fireDate is a field)
code is likelly:
 data.fireDate = moment(
        form
          .getFieldValue('fireDate')
          .subtract(-8, 'hours')
          .format('YYYY-MM-DD HH:mm:ss')
      );
before 16:00  ,i found in network fireDate is right;
but after 16:00 ,  fireDate is next day.
This question is only happend to in  form submit.
My code is wrong ?  
thanks all .

**Comment by marwahaha** [comment]
Why are you subtracting 8 hours?
You can look at the difference between local mode and UTC mode: https://momentjs.com/docs/#/parsing/
