### ISSUE TITLE
Unix conversion returns Nan if the date is in locale format

### ISSUE THREAD

**Issue by MercyJS** [moment/moment#5824]
**Describe the bug**
Unix conversion returns Nan if the date is in locale format

**To Reproduce**
The below returns Nan

moment("04 de feb. de 2021").endOf("day").unix() NaN

**Expected behavior**

It should return the unix timestamp

**Comment by hemang249** [comment]
I think the way you are trying to use it is incorrect. If you go throught the docs, when using a specific locale format you need to provide a format string that.

The correct way to use this would be :

`
  moment("04 de feb. de 2021", 'de').endOf("day").unix()  // 'de' is the specific format
`
