### ISSUE TITLE
Months coming completely wrong when explicit parsing format is provided

### ISSUE THREAD

**Issue by aswinfrancis** [moment/moment#5830]
![image](https://user-images.githubusercontent.com/75744387/108162910-15906000-7114-11eb-8f89-90801b7b2592.png)
I am trying to understand why when an explicit format is given, June becomes Jan and when it is removed, it works fine.

**Comment by benzispawn** [comment]
I tested in the 2.29.1 version and don't get the same problem. Which version you are using?

**Comment by aswinfrancis** [comment]
I am on version 2.15.1. We use localization though. So moment.locale() would return "fr" in the same console but the date is coming from a separate code flow as seen in the first parameter to moment().

**Comment by marwahaha** [comment]
Moment.js doesn't guarantee that the date will be parsed correctly if you do not use the correct format. I would recommend
```
moment("Jun 16 2021", "MMM DD YYYY").toDate()
```

**Comment by aswinfrancis** [comment]
![image](https://user-images.githubusercontent.com/75744387/109260567-5ed36480-7824-11eb-8113-27eb14676dca.png)
Even then its coming wrong :(

**Comment by marwahaha** [comment]
What is your locale? For example, if you want to parse dates in English, please ensure you are using the English locale.

```
moment.locale('en')
```
