### ISSUE TITLE
fromNow() with Threshold

### ISSUE THREAD

**Issue by injecteer** [moment/moment#5832]
I want to display my dates according to a simple rule:

if the date is older than **n** days -> I want to display it in a dd-MM-yyyy format.
If the date is younger than **n** days -> I want to display it in fromNow() format, i.e. "4 hours ago"

I could craft my own function like:
```
function displayDate( time, threshold ){
    return time.isBefore(moment().subtract(threshold,'days')) ? moment.format() : time.fromNow();
}
```
but this looks like a very generic functionality which the library should provide out-of-box.

**Comment by marwahaha** [comment]
This is a neat idea; however, as per [this statement](https://momentjs.com/docs/#/-project-status/), we are not taking new features.
