### ISSUE TITLE
Moment.js accecpt  "11-03-2021 14:58:P" inside converting string to moment object in format DD-MM-YYYY HH:mm:A

### ISSUE THREAD

**Issue by wesly12345678** [moment/moment#5843]
code:
![image](https://user-images.githubusercontent.com/52520977/110749052-8c37fd80-827b-11eb-810f-c9cd0ad8ca8b.png)
Result:
![image](https://user-images.githubusercontent.com/52520977/110749146-aa056280-827b-11eb-921d-6a577c5aa0b2.png)

Is this normal because it was very strange to have output 11-03-2021 14:58:P as moment object ?

**Comment by marwahaha** [comment]
You are printing out the Moment object, which stores many things. You can try calling .format() . I would also recommend "strict mode".https://momentjs.com/guides/#/parsing/strict-mode/
