### ISSUE TITLE
Incorrect string parsing via template

### ISSUE THREAD

**Issue by muturgan** [moment/moment#5850]
**Describe the bug**
I getting a dateString from a public api with the following pattern: "MM/DD/YYYY".
For example "06/24/1983".
I passing this dateString and a pattern to the moment function then formatting but getting an incorrect result.

**To Reproduce**
1. run the following code:
```
const moment = require('moment');
const date = "06/24/1983";
console.log(moment(date, 'ММ/DD/YYYY').format('YYYY-MM-DD')); // 1983-01-24
```

**Workaround**
This is a way to get an correct result, but this is a crutch:
`console.log(moment(moment(date, "MM/DD/YYYY").toDate()).format('YYYY-MM-DD')); // 1983-06-24`

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser: node 14.16.0
 - Version: 2.29.1

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()) // Fri Mar 12 2021 23:33:27 GMT+0300 (Moscow Standard Time)
console.log((new Date()).toLocaleString()) // 3/12/2021, 11:33:27 PM
console.log((new Date()).getTimezoneOffset()) // -180
console.log(navigator.userAgent) // ----------
console.log(moment.version) // 2.29.1
```

**Comment by marwahaha** [comment]
Hi,
If something is working strangely, do try strict mode: https://momentjs.com/guides/#/parsing/strict-mode/

Something is unusual about the "М" character you are using (as compared to the default "M"). I think it is because it is [Cyrillic](https://en.wikipedia.org/wiki/Em_(Cyrillic)), not [Latin](https://en.wikipedia.org/wiki/M).

Try copy-pasting this: 
```
moment('06/24/1983', "MM/DD/YYYY", true).format()
```

The

**Comment by muturgan** [comment]
I'm sure that it was a latin letter.
What about strict mode - I'll try it at evening.
Thank you very much for this tip!
