### ISSUE TITLE
Custom the error message

### ISSUE THREAD

**Issue by Jeje2201** [moment/moment#5861]
**Is your feature request related to a problem? Please describe.**
I have a problem where I want to write a custom message if the date is invalid, sometime I want it to be blank, sometime "there is no date" not a static message that is always the same "Invalid Date"

**Describe the solution you'd like**
It would be very helpfull is there was a function to customise the error message like
`moment(...).IfError('this message is show if the date is invalid')`

**Describe alternatives you've considered**
I created a function to solve this, but not the best solution
```js
 function MomentError(date, ErrorMessage) {

  if (date === "Invalid date") {
    return ErrorMessage
  } else {
    return date
  }
```

**Additional context**
No need I think

**Comment by marwahaha** [comment]
Thanks for sharing this.
If you want to change the string to something else, you can update the locale: https://momentjs.com/docs/#/customization/invalid-date/
