### ISSUE TITLE
'isSame' function is not working as expected for 2011 year and older

### ISSUE THREAD

**Issue by D0HaTeJIJI0** [moment/moment#5869]
for years above 2011:
moment("2021-01-23T21:00:00Z").isSame(moment("2021/01/24", "YYYY/MM/DD"), "day") -> true

for years under 2011:
moment("2010-01-23T21:00:00Z").isSame(moment("2010/01/24", "YYYY/MM/DD"), "day") -> false

**Comment by juicelink** [comment]
code is working on my side. what is your timezone?

**Comment by marwahaha** [comment]
Most likely, your time zone in the place you are running your code changed around 2011. 

To compare to UTC dates:
```
moment.utc("2021-01-23T21:00:00Z").isSame(moment.utc("2021/01/23", "YYYY/MM/DD"), "day")
moment.utc("2010-01-23T21:00:00Z").isSame(moment.utc("2010/01/23", "YYYY/MM/DD"), "day")
```
