### ISSUE TITLE
Nginx time parsing issue

### ISSUE THREAD

**Issue by egorvas** [moment/moment#5876]
**Describe the bug**
Hi, I faced with error of parsing nginx standard time format.

**To Reproduce**
1. console.log(moment("22/Apr/2021:03:46:37 +0700", "DD/MMM/YYYY:hh:mm:ss Z"))

**Expected behavior**
Date should be parsed as: Moment<2021-04-22T03:46:37+07:00>
But the result is: Moment<2021-04-22T00:00:00+03:00>

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

Mon Apr 26 2021 20:33:24 GMT+0300 (Moscow Standard Time)
4/26/2021, 8:33:24 PM
-180
undefined
2.29.1

**Comment by FatemeMirzaeii** [comment]
have you found why?
I have same problem some how;
moment('2021-03-22').format('YYYY-MM-DD') returns '2021-03-21'!
