### ISSUE TITLE
Incorrect error moment.min() -> moment.min

### ISSUE THREAD

**Issue by IsaiahJTurner** [moment/moment#5879]
Currently the errors read like this:

> Deprecation warning: moment().max is deprecated, use moment.min instead. http://momentjs.com/guides/#/warnings/min-max/

This error should read:

> Deprecation warning: moment().max is deprecated, use moment.max instead. http://momentjs.com/guides/#/warnings/min-max/

**Comment by marwahaha** [comment]
The functionality changed; actually the docs are correct. https://github.com/moment/moment/issues/3389
