### ISSUE TITLE
Cross browser issue  

### ISSUE THREAD

**Issue by atrost** [moment/moment#5882]
**Describe the bug**

After having bumped up the versions of moment and moment-timezone to the latest (2.29.1 and 0.5.33 respectively), moment date formatting stopped working in some browsers while it does work in other browsers. moment interpret server-side-generated date time as invalid which further results with moment-timezone failing to format the datetime to the local date and time.  

Works in Chrome and Opera. 
Does not work in Firefox or Safari.
 
**To Reproduce**

1. In Firefox:

> moment("2021-04-28 13:07:45 -0700").isValid()
> **false**

> moment("2021-04-28 13:07:45 -0700").tz(moment.tz.guess()).format('MM/DD/YYYY LTS z')
> "**Invalid date"**

2. In Chrome:

> moment("2021-04-28 13:07:45 -0700").isValid()
> **true**

> moment("2021-04-28 13:07:45 -0700").tz(moment.tz.guess()).format('MM/DD/YYYY LTS z')
> "**04/28/2021 1:07:45 PM PDT**"

**Expected behavior**
Moment date is correctly parsed and formatted in the Firefox browser
   
**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Safari 88
 
**Environment test**
```
console.log((new Date()).toString())
Mon May 03 2021 12:14:58 GMT-0700 (Pacific Daylight Time)

console.log((new Date()).toLocaleString())
5/3/2021, 12:15:16 PM

console.log((new Date()).getTimezoneOffset())
420

console.log(navigator.userAgent)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:88.0) Gecko/20100101 Firefox/88.0console.log(moment.version)
```

**Additional context**

**Comment by marwahaha** [comment]
Without specifying a format, the parsing depends on the browser. I recommend adding a format: https://momentjs.com/docs/#/parsing/string-format/

There is a warning generated:
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2021-04-28 13:07:45 -0700, _f: undefined, _strict: undefined, _locale: [object Object]
deprecate/<@https://momentjs.com/static/js/global.js:319:25
configFromString@https://momentjs.com/static/js/global.js:2536:19
configFromInput@https://momentjs.com/static/js/global.js:2977:29
prepareConfig@https://momentjs.com/static/js/global.js:2960:28
createFromConfig@https://momentjs.com/static/js/global.js:2927:44
createLocalOrUTC@https://momentjs.com/static/js/global.js:3021:16
createLocal@https://momentjs.com/static/js/global.js:3025:16
hooks@https://momentjs.com/static/js/global.js:16:29
@debugger eval code:1:7
```

**Comment by atrost** [comment]
Thanks! That solved the issue.
