### ISSUE TITLE
Minifying the moment.js.

### ISSUE THREAD

**Issue by RDKRACZ** [moment/moment#5891]
**Is your feature request related to a problem? Please describe.**
According to the Google PageSpeed results minifying the moment.js will cut the file size by 11.2 KiB from 27.4 KiB which looks like a big difference to page loading speed.
https://web.dev/unminified-javascript/

**Describe the solution you'd like**
Alternative package?

Did I get something wrong? Is there any solution for this problem for the end-user?

**Comment by marwahaha** [comment]
You can use `moment.min.js` instead, if you prefer.
https://github.com/moment/moment/blob/develop/min/moment.min.js
