### ISSUE TITLE
How do I get a Date object on MomentJS but as UTC (prevent `toDate()` from being `locale`)?

### ISSUE THREAD

**Issue by ItzaMi** [moment/moment#5915]
First of all, I really need a `Date object` because I'm using `ReactDatePicker` and the `selected` prop requires it. And I also really have to use `momentjs`.

The bit of code I need to work with is this:

```javascript
// this logs a Moment object
const date = moment(moment.utc().format())

// this logs something like
// Tue Jul 20 2021 17:08:28 GMT+0100 (Western European Summer Time)
const dateObj = date.toDate()
```

As you can see, no matter the amount of times that I convert my `moment()` into `UTC`, `toDate()` always converts it back to `locale time` and I need to prevent this while still keeping a `Date object` that comes from `.toDate()`.

How can I do this?

**Comment by marwahaha** [comment]
I feel that this is a duplicate issue of #5916. But if you have another question do let me know.

**Comment by ItzaMi** [comment]
@marwahaha , both issues are somewhat related but they are different. #5916 is intended to show that I get different results from the same method.

This one here I filed to get a better understanding on how I can get a `Date object` but on `UTC`. I guess that you ended up answering there that I could use `toUTCString()`. However, that doesn't seem to work for me. While using TypeScript, I get that the end result of `dateObj.toUTCString()` is a `string` and I need to have it as a `Date object` due to `react-datepicker`

**Comment by marwahaha** [comment]
Moment can return the Date object it has access to. 
From there, you can decide what to do with it outside of Moment.
There are some approaches to change it like here: https://stackoverflow.com/a/6777470
