### ISSUE TITLE
Site hacked

### ISSUE THREAD

**Issue by chaimochs** [moment/moment#5920]

**Comment by ryantheleach** [comment]
On the assumption that you are reporting this in fair play, and not as a form of protest. 

It's clear that moment has not been hacked, and they are simply joining the protest.

**Comment by chaimochs** [comment]
Thank you so much for clarifying (and for giving me the benefit of the doubt). 
With international cybercrime on the rise these days, one can never be too sure. 

Now that I learn that you have indeed joined the protest, I will begin purging my applications of any reference to moment.js and migrate to luxon.js or some similar alternative. 
While I am sure you joined this destructive, derisive, corrupt, Marxist, anarchist, racist, anti-semitic, criminal enterprise in the guise of a legitimate organization with good intentions, I cannot in good faith be party to such associations. 
Best of luck in software development.
