### ISSUE TITLE
moment subtraction & diffs don't consider UTC daylight savings

### ISSUE THREAD

**Issue by alita-moore** [moment/moment#5922]
**Describe the bug**
when I subtract 170 days from a date that then overlaps with the UTC daylight savings it causes the time to be one hour ahead (which is expected behavior, I believe because this is true in absolute time). But then when I try to compare or take a diff of that with the moment diff it fails to consider this and so my diff is 1 hour off.

**To Reproduce**
```node
> 170 * 24 * 60 * 60 * 1000
14688000000  <-- 170 days in milliseconds
> moment().toISOString()
'2021-08-17T17:52:29.267Z'
> moment().subtract(14688000000, "ms").toISOString()
'2021-02-28T17:52:41.598Z'
> moment().subtract(170*24*60*60, "seconds").toISOString()
'2021-02-28T18:00:24.266Z'
> moment().subtract(170*24*60, "minutes").toISOString()
'2021-02-28T17:59:48.128Z'
> moment().subtract(170*24, "hour").toISOString()
'2021-02-28T17:57:26.661Z'

// below is different
> moment().subtract(170, "days").toISOString()
'2021-02-28T18:53:13.238Z' 
```

**Expected behavior**

```node
const milliInDay = 24 * 60 * 60 * 1000
moment().subtract(170, "days").toISOString() !== moment().subtract(milliInDay * 170, "ms").toISOString()
```

**Moment-specific environment**
```
Tue Aug 17 2021 13:04:11 GMT-0500 (Central Daylight Time)
8/17/2021, 1:04:11 PM
300
2.29.1
```

**Comment by marwahaha** [comment]
Hi,
I think this is intended behavior: https://momentjs.com/docs/#/manipulating/add/

> There are also special considerations to keep in mind when adding time that crosses over daylight saving time. If you are adding years, months, weeks, or days, the original hour will always match the added hour.
> If you are adding hours, minutes, seconds, or milliseconds, the assumption is that you want precision to the hour, and will result in a different hour.

**Comment by alita-moore** [comment]
I see, @marwahaha the only issue is that in the behavior I describe above it's the other way around. the milliseconds are to the same hour and the day is not.

**Comment by marwahaha** [comment]
@alita-moore
Sorry for the misunderstandings.
When you add and subtract units smaller than days, we will keep track of hour precision for you.
Let's look at the example in the docs.
```
var m = moment(new Date(2011, 2, 12, 5, 0, 0));
undefined
m.toString()
"Sat Mar 12 2011 05:00:00 GMT-0800"
m.toISOString()
"2011-03-12T13:00:00.000Z"
m.add(24, 'hours')
Object { _isAMomentObject: true, _i: Date Sat Mar 12 2011 05:00:00 GMT-0800 (Pacific Standard Time), _isUTC: false, _pf: {…}, _locale: {…}, _d: Date Sun Mar 13 2011 06:00:00 GMT-0700 (Pacific Daylight Time), _isValid: true, _z: null }

m.toString()
"Sun Mar 13 2011 06:00:00 GMT-0700"
m.toISOString()
"2011-03-13T13:00:00.000Z"
```

So the hour precision is kept, even as we cross the daylight savings boundary for the United States. However, one thing about UTC is that it doesn't have a daylight savings mode. So "keeping the same hour" in UTC means we have hour precision. But in the local time zone the hour changes. So "keeping the same hour" in your local time zone means we lose hour precision.

Sorry that the documentation is confusing. If this makes sense to you could you make a pull request to make the documentation clearer? https://github.com/moment/momentjs.com/
