### ISSUE TITLE
Subtract logic failed in the month way when the last day of the month was involved.

### ISSUE THREAD

**Issue by Mifrill** [moment/moment#5927]
**Describe the bug**
The `subtract` function returns an incorrect output when the last day of month is `30`.

**To Reproduce**

```JS
moment("2021-06-30").subtract(1, 'month').toString();
```
**Expected behavior**
```
"Sun May 31 2021 00:00:00 GMT+0500"
```
Actual:
```
"Sun May 30 2021 00:00:00 GMT+0500"
```

**Moment-specific environment**

```
moment@^2.10.2:
  version "2.29.1"
  resolved "https://registry.yarnpkg.com/moment/-/moment-2.29.1.tgz#b2be769fa31940be9eeea6469c075e35006fa3d3"
```

**Additional context**
Btw, it's working correctly on Feb:
```JS
moment("2021-03-31").subtract(1, 'month').toString();
// "Sun Feb 28 2021 00:00:00 GMT+0500"
```
Also, it's working fine for `add` function:
```JS
moment("2021-05-31").add(1, 'month').toString();
// "Wed Jun 30 2021 00:00:00 GMT+0500"
```

**Comment by Mifrill** [comment]
It looks like applyeble to `add` function too:
```JS
moment("2021-04-30").add(1, 'month').toString();
// "Sun May 30 2021 00:00:00 GMT+0500"
```
should be `"Sun May 31 2021 00:00:00 GMT+0500"` I guess

**Comment by ichernev** [comment]
This can't happen. If you want end-of-month, just cal the right methods. Subtracting 1 month is a best effort op.
