### ISSUE TITLE
convert string to number when moment.weekdays is called

### ISSUE THREAD

**Issue by guimap** [moment/moment#5933]
> I'm not sure if this is a bug or an improvement, if its wrong, sorry for that, this is my first pull request for an open source repo.

When `moment.weekdays` receive a string value as parameter, the output is different, for example

```js
 moment.weekdays(5) // Friday
 moment.weekdays("5") // Monday
```
Here my [jsFiddle](https://jsfiddle.net/guiihpr/rfbeL0q8/5/)

For me this is frustared when i receive a value which is a string

My suggestion is on file [src/lib/locale/list.js:42](https://github.com/moment/moment/blob/develop/src/lib/locale/lists.js#L41) and [src/lib/locale/list.js:52](https://github.com/moment/moment/blob/develop/src/lib/locale/lists.js#L52) add an extra condition like this:
```js
 if (isNumber(format) || !Number.isNaN(parseInt(format))) {
```

This is my PR [#59325](https://github.com/moment/moment/pull/5934)

I did this PR [#59325](https://github.com/moment/moment/pull/5934) to fix this problem

![Screenshot from 2021-09-16 18-03-08](https://user-images.githubusercontent.com/6060537/133685341-db624c3b-992f-4412-af87-b1d72be8fff9.png)

**Comment by ichernev** [comment]
I don't think you're supposed to use it this way.

```
  export function weekdays(): string[];
  export function weekdays(index: number): string;
  export function weekdays(format: string): string[];
  export function weekdays(format: string, index: number): string;
  export function weekdays(localeSorted: boolean): string[];
  export function weekdays(localeSorted: boolean, index: number): string;
  export function weekdays(localeSorted: boolean, format: string): string[];
  export function weekdays(localeSorted: boolean, format: string, index: number): string;
```

This function has a lot of overloads, but you can't pass a number as string and expect it to work.

I mean this API is completely batshit crazy, but we're not changing it :)
