### ISSUE TITLE
Incorrect number of seconds in a minute 

### ISSUE THREAD

**Issue by PascalFlierman** [moment/moment#5941]
Using Moment().format('DD/MM/YYYY HH:MM:SS') in combination with TypeScript will give more than 60 seconds. E.g. time was formatted to 01/10/2021 09:10:**93**.

**Comment by jeremywall-davis** [comment]
"SS" is the format code for fractional second, you want to use "ss" for 2 character padded seconds ... the docs for format string patterns is at https://momentjs.com/docs/#/displaying/format/

**Comment by jeremywall** [comment]
"SS" is the format code for fractional second, you want to use "ss" for 2 character padded seconds ... the docs for format string patterns is at https://momentjs.com/docs/#/displaying/format/

**Comment by jeremywall** [comment]
You also need to change to "mm" for minutes

**Comment by PascalFlierman** [comment]
Thanks and sorry!
