### ISSUE TITLE
expressions in require() - browserify 

### ISSUE THREAD

**Issue by jakeluck** [moment/moment#595]
browserify is doesnt like computed require as it complicates dependency tracking, so including 

``` javascript
var moment      = require('moment');
```

results 

``` javascript
Expressions in require() statements:
    require('./lang/' + key)
```

this warning does not appear to affect function, is there a cleaner way to quiet it?

**Comment by szwacz** [comment]
You can also monkey patch this problem with [Aliasify](https://github.com/benbria/aliasify).
```
"aliasify": {
    "aliases": {
        "moment": "./node_modules/moment/min/moment-with-locales.js"
    }
},
```
