### ISSUE TITLE
format('Do') will not produce '31st' 

### ISSUE THREAD

**Issue by NickKotte** [moment/moment#5951]
**Describe the bug**
I want to provide moment with values 1-31 and format it into 1st, 2nd, ..., 31st.
I use this code: `moment( i, 'D' ).format('Do')` where i is an integer from 1-31.

Strangely, it correctly formats every value except for 31.
`moment(31, 'D').format('Do')` => 'Invalid date'

Even though these work:
`moment(1, 'D').format('Do')` => '1st'
`moment(15, 'D').format('Do')` => '15th'

**To Reproduce**
1. type `moment(31, 'D').format('Do')`
2. See that gives Invalid date

**Expected behavior**
It should produce the value '31st'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version "moment": "^2.29.1"

**Smartphone (please complete the following information if applicable):**
 - Browser [e.g. firefox, safari]

**Moment-specific environment**

* Eastern Daylight Time
* 11/2/2021 2:30 PM

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()) // Tue Nov 02 2021 14:33:15 GMT-0400 (Eastern Daylight Time)
console.log((new Date()).toLocaleString()) // 11/2/2021, 2:33:29 PM
console.log((new Date()).getTimezoneOffset()) // 240
console.log(navigator.userAgent) // Uncaught ReferenceError: navigator is not defined
console.log(moment.version) // 2.29.1
```

**Additional context**

**Comment by ashsearle** [comment]
Looks like you tried this code in November, which only has 30 days.

Without any other fields to work with `moment(31, 'D')` tries to create a moment set to the 31st of the current month.  As November doesn't have a 31st you ended up with an invalid date.

Make sure you create your moments for a month with 31 days - e.g. January:
```js
moment({ month: 0, day: 31 }).format('Do') // "31st"
```

**Comment by NickKotte** [comment]
I see. That makes a lot of sense now thank you!
