### ISSUE TITLE
a new function logic about add months

### ISSUE THREAD

**Issue by classmatewu** [moment/moment#5956]
[background]
In most business scenarios, in order to consider the interests of users, adding one month is generally "month end to month end".
For example, the validity period of some resource packs.

[example]
moment('2022-2-28').newAdd(1, 'months').format('YYYY-MM-DD') => 2022-3-31

**Comment by ashsearle** [comment]
You can add your own function to do this: 

```js
moment.fn.newAdd = function (number, period) {
  if (
    ["month", "months", "M"].includes(period) &&
    this.date() == this.daysInMonth()
  ) {
    return this.date(this.date(1).add(number, period).daysInMonth());
  }
  return this.add(number, period);
};
```

**Comment by classmatewu** [comment]
> 

Yes, but I think this might be a general scenario

**Comment by ashsearle** [comment]
The point is it doesn't take a lot of lines to do a basic implementation yourself, and this gives you the control over how to handling edge-cases that arise with this type of method.

e.g. if you want to use `newAdd(1, 'month')` repeatedly to generate dates for the next 12 months, but you happen to start on 28th of a month.  You'll get a series of 28th of month X until you hit February, and then the behaviour suddenly changes to stick to the last day of the month.

One response to edge cases would be to say "I would only use `newAdd` in specific scenarios where I know I won't hit these edge cases" - but that means it's not really a general method after all.

**Comment by classmatewu** [comment]
thanks a lot
