### ISSUE TITLE
Formatting date with fractional seconds fails in specific scenarios

### ISSUE THREAD

**Issue by atlanteh** [moment/moment#5957]
**Describe the bug**
Moment returns invalid date in seemingly random dates when using the following code:
```
moment('2021-11-29T18:56:10.724881Z', ['YYYY-MM-DD[T]HH:mm:ss.ssssssTZD']).toString() // invalid date
moment('2021-11-29T18:56:10.724811Z', ['YYYY-MM-DD[T]HH:mm:ss.ssssssTZD']).toString() // valid

moment('2021-11-29T18:55:42.84Z', 'YYYY-MM-DD[T]HH:mm:ss.ssTZD').toString() // invalid date
moment('2021-11-29T18:55:42.34Z', 'YYYY-MM-DD[T]HH:mm:ss.ssTZD').toString() // valid
```

**Desktop (please complete the following information):**
 - OS: linux/mac
 - Browser chrome/nodejs
 - Version 2.29.1

**Comment by ashsearle** [comment]
It looks like you're using 'ssssss' to parse fractional seconds when you should be using 'SSSSSS'. 

Does using S instead of s after the . make things more reliable?

**Comment by atlanteh** [comment]
@ashsearle Yes! wow thanks! that works!
