### ISSUE TITLE
v2.29.2 of moment with locales doesn't exist on CDNJS

### ISSUE THREAD

**Issue by o355** [moment/moment#5991]
Trying to upgrade to v2.29.2 of moment.js, and CDNJS has no data for this URL, so moment.js can't be loaded in properly.
https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.2/moment-with-locales.min.js

Without locales loads in fine, and v2.29.1 with locales also loads in fine from CDNJS.

**Comment by zhaoning0228** [comment]
We got the same issue, waiting to be solved.

**Comment by ichernev** [comment]
Is there a way to upstream the issue there? I don't think our "release" process includes anything related to CDNJS, it probably picks stuff up from npm?

**Comment by ichernev** [comment]
Hm, works on 2.29.3, so just update to that :)
