### ISSUE TITLE
Moment objects should be comparable

### ISSUE THREAD

**Issue by paddor** [moment/moment#5992]
**Is your feature request related to a problem? Please describe.**
I need moment objects to be comparable so my table can be dynamically sorted by the timestamp column.
I currently can't just convert all the moment objects to integers, as the table is generic.

**Describe the solution you'd like**
Moment objects should be comparable so that `Array.sort()` or `sort()`  from `@ember/object/computed`  just works.

**Describe alternatives you've considered**
I've considered adding fake properties on the sorted objects like `sortable_<property>` but it brings chaos to everything else.
I've considered implementing my own search function but then I still have to do type checks and don't get all the benefits from Ember.

**Additional context**
My main language is Ruby and maybe I'm biased. Time objects should be sortable.

**Comment by ichernev** [comment]
@paddor how do you suggest we do that? Maybe there is a fancy feature in newer JS releases, back in the old days you didn't have a way to override the comparison. Moment supports `valueOf()`, so you can sort by just comparing `+m1 < +m2`. Also, the code should be backwards compatible with ES5, so no fancy new syntax allowed :) Just write once a comparator (using `+` and use it everywhere you sort).

**Comment by paddor** [comment]
Thank you. We use integers (Unix milliseconds) internally now and use moment only for display. 👍
