### ISSUE TITLE
ES5 support is broken with the addition of const in 2.29.2

### ISSUE THREAD

**Issue by jamesf91** [moment/moment#5996]
Version 2.29.2 of Moment,JS introduced a few const keywords in locale.js which has broken ES5 support for older browsers (e.g. IE11).

Would it be possible to revert these "const" to "var" to retain ES5 support?

**Comment by theboolean** [comment]
Hi @jamesf91, I already opened a PR for this issue: #5995

**Comment by ichernev** [comment]
Fixed in 2.29.3
