### ISSUE TITLE
Change the timezone name from Kiev to Kyiv

### ISSUE THREAD

**Issue by anastasiagoncharova** [moment/moment#6008]
Check moment.tz.names()

Expected result

(GMT +03:00) Europe/Kyiv

Actulal result

(GMT +03:00) Europe/Kiev

**Comment by chozandrias76** [comment]
I think you want to raise your issue with the Javascript community, because it doesn't seem like moment controls that. Checking the `Date` class:
```js
function changeTimezone(date, ianatz) {

  // suppose the date is 12:00 UTC
  var invdate = new Date(date.toLocaleString('en-US', {
    timeZone: ianatz
  }));

  // then invdate will be 07:00 in Toronto
  // and the diff is 5 hours
  var diff = date.getTime() - invdate.getTime();

  // so 12:00 in Toronto is 17:00 UTC
  return new Date(date.getTime() - diff); // needs to substract

}

// E.g.
var here = new Date();
var there = changeTimezone(here, "Europe/Kyiv");

console.log(`Here: ${here.toString()}\nKyiv: ${there.toString()}`);
```

```js
VM346:4 Uncaught RangeError: Invalid time zone specified: Europe/Kyiv
    at Date.toLocaleString (<anonymous>)
    at changeTimezone (<anonymous>:4:31)
    at <anonymous>:19:13
```

**Comment by gilmoreorless** [comment]
This was fixed in `moment-timezone` 0.5.36

**Comment by gilmoreorless** [comment]
Both `Europe/Kiev` and `Europe/Kyiv` are present as names in the IANA time zone database, and therefore Moment Timeonze. `Kiev` is a legacy link to `Kyiv` for backwards compatibility.

**Comment by gilmoreorless** [comment]
You're going to have to manually filter the list somehow anyway, regardless of Kiev/Kyiv. There are many, many deprecated names that are links to other names. See https://github.com/moment/moment-timezone/issues/227 for an old discussion about this in Moment Timezone, and https://github.com/tc39/proposal-temporal/issues/2509 for a (much longer) discussion for TC39's Temporal proposal.

**Comment by gilmoreorless** [comment]
I do want to fix this confusion at some point in Moment Timezone, but it requires some hefty changes to the build process.
