### ISSUE TITLE
[Documentation] Text Color Is Too Light To Read

### ISSUE THREAD

**Issue by Rubix982** [moment/moment#6017]
**Describe the bug**
The current text on momentjs.com is really hard to read, as can be seen the below image,

![image](https://user-images.githubusercontent.com/41635766/174428793-e08136b2-6606-444d-a2e7-e625e5446c03.png)

**To Reproduce**
Steps to reproduce is to visit the website.

**Expected behavior**
Text is expected to be more readable.

**Screenshots**
![image](https://user-images.githubusercontent.com/41635766/174428817-0142222c-5d21-4378-88b8-3a6f3cde91bc.png)

**Desktop (please complete the following information):**
 - Browser: Brave Browser 102.1.39.122

**Smartphone (please complete the following information if applicable):**
 - Browser: Brave Browser 102.1.39.122

**Moment-specific environment**
Not applicable.

**Additional context**
Not applicable.

**Comment by AakashRaj20** [comment]
Hi @Rubix982 can I try thiss issue?

**Comment by Rubix982** [comment]
> Hi @Rubix982 can I try thiss issue?

Yes! Feel free  😀

**Comment by AakashRaj20** [comment]
> > Hi @Rubix982 can I try thiss issue?
> 
> Yes! Feel free grinning

Hey @Rubix982 I went to the website to see the issue, but I did not find any, the text is readable.

**Comment by Mohit-Aasirwal** [comment]
hey @Rubix982, I want to fix this issue. is it not fixed yet?

**Comment by Rubix982** [comment]
Hi, @AakashRaj20! I'm sorry, I forgot to reply here.

Yes, the issue seems to have been solved.

Thanks for the volunteering, @Mohit-Aasirwal! The issue is no longer present. This can be safely closed.
