### ISSUE TITLE
Date is coming different on localhost and on prod env.

### ISSUE THREAD

**Issue by minnat65** [moment/moment#6024]
When I am selecting a past date from calender then it is showing correct output at first place(fig-1).
![image](https://user-images.githubusercontent.com/79779279/178967613-d1f22d29-299e-4c29-8208-307edffad44b.png)

But when I am printing that same date on pdf from backend then it is showing one day back(fig-2)
![image](https://user-images.githubusercontent.com/79779279/178967924-78f9e881-f83b-4a80-951c-9e88e2dad493.png)

But it is working fine in local env but not working fine in Test & Prod env.

**Comment by xpanvictor** [comment]
Check well with your configs. It's likely the logic.

**Comment by minnat65** [comment]
Thanks @xpanvictor 
You were right, moment was giving default host time zone.

To Fix it:
1. We can use moment(time in milliseconds).utcOffset(330). To know more refer [this](https://momentjscom.readthedocs.io/en/latest/moment/03-manipulating/09-utc-offset/)
   Here 330 minutes mean utc time + 5:30(it is Indian Standard Timezone)
2. We can use moment timezone package.
