### ISSUE TITLE
moment.utc(date, "YYYY-MM-DD HH:mm:ss Z" ) is giving wrong date for Hawaii-Aleutian Standard Time

### ISSUE THREAD

**Issue by nikhiltiware** [moment/moment#6028]
For input given in Hawaii-Aleutian Standard Time is giving wrong date output for `moment.utc`

eg. 
Input in Hawaii-Aleutian Standard Time:
`Wed Jun 01 2022 00:00:00 GMT-1000 (Hawaii-Aleutian Standard Time)`
Output - 
`Mon Oct 01 2001 00:00:00 GMT+0000`

but for Pacific time zone to gives output as `Invalid Date`. There should be consistent `Invalid Date` output instead of resulting in wrong date.

Input in Pacific timezone:
`Thu Jun 01 2022 00:00:00 GMT-0700 (Pacific Daylight Time)`

Output:
`Invalid date`

Fiddle playground - https://jsfiddle.net/6qgLv4d1/

**Comment by IvaTsu** [comment]
Hey @nikhiltiware,

It looks like there's a problem with the date formats you are passing in. It's neither recognized RFC2822 nor ISO format.

I would suggest you to check this issue thread for more information: https://github.com/moment/moment/issues/1407, specifically [this comment](https://github.com/moment/moment/issues/1407#issuecomment-155630060) gives the exact answer to your problem.
