### ISSUE TITLE
moment.tz("Etc/GMT+X") creates object in timezone Etc/GMT-X instead of Etc/GMT+X

### ISSUE THREAD

**Issue by ohyeaah** [moment/moment#6031]
**Describe the bug**
Creating a date object using moment.tz("Etc/GMT+X") results in a date object in timezone Etc/GMT-X.

**To Reproduce**
I am using moment-with-locales.js and moment-timezone-with-data-10-year-range.js.

The code to reproduce is:

moment.tz("Etc/GMT+5").format();

**Expected behavior**
The expected output is 2022-07-24T**17**:24:17+05:00
But the actual output is 2022-07-24T**07**:24:17-05:00

As you can see the hour and the timezone of the output is wrong.

**Screenshots**
no screenshots

**Desktop (please complete the following information):**
 - OS: debian
 - Browser firefox
 - Version 91.11.0esr

**Smartphone (please complete the following information if applicable):**
not tested on smartphone

**Moment-specific environment**

* (should not matter) GMT+2
* July 24 2022
* no other libraries

Please run the following code in your environment and include the output:
```
Sun Jul 24 2022 14:31:00 GMT+0200 (Mitteleuropäische Sommerzeit) [test.html:10:10](file:///home/user1/Schreibtisch/test.html)
24.7.2022, 14:31:00 [test.html:11:9](file:///home/user1/Schreibtisch/test.html)
-120 [test.html:12:9](file:///home/user1/Schreibtisch/test.html)
Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0 [test.html:13:9](file:///home/user1/Schreibtisch/test.html)
2.29.4
```

**Additional context**

**Comment by gilmoreorless** [comment]
This is expected behaviour. From [the documentation](https://momentjs.com/timezone/docs/#/zone-object/offset/):

> POSIX compatibility requires that the offsets are inverted. Therefore, Etc/GMT-X will have an offset of `+X` and Etc/GMT+X will have an offset of `-X`. This is a result of IANA's [Time Zone Database](https://github.com/eggert/tz/blob/2017b/etcetera#L36-L42) and not an arbitrary choice by Moment.js. Thus, using locality based identifiers is preferred over fixed-offset identifiers.

Also described on the [Wikipedia entry for the database](https://en.wikipedia.org/wiki/Tz_database#Area):

> The special area of "Etc" is used for some administrative zones, particularly for "Etc/UTC" which represents [Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time). In order to conform with the [POSIX](https://en.wikipedia.org/wiki/POSIX) style, those zone names beginning with "Etc/GMT" have their sign reversed from the standard [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC) convention. In the "Etc" area, zones west of GMT have a positive sign and those east have a negative sign in their name (e.g "Etc/GMT-14" is 14 hours ahead of GMT).
