### ISSUE TITLE
Get moment.js default date(year) by constant?

### ISSUE THREAD

**Issue by DainisVerdins** [moment/moment#6042]
**Is your feature request related to a problem? Please describe.**
Some times you need default values of moment library on witch point is starting "ticking". Like gor Unix systems start date is 1970 for moment.js library it is 2001.

**Describe the solution you'd like**
Some properties of moment object  or constants in library itself to get start values of the library.(In case of moment js it is 2001 year)

**Describe alternatives you've considered**
Using this kind of `crutch` to get moment.js default year, It breaks moment but create instead new Date object what have 2001 year  
```javascript
const momentDefaultYear = moment('1').year() as number;
```
but it rises warning message in console Warning message
![image](https://user-images.githubusercontent.com/55252915/187891528-2a35ebe8-b71c-4a79-be29-b96443072880.png)
and need to turn it off somehow
Or
You can set as a constant 
```javascript
const foo= moment('2001-01-01').year() as number;
```
but if by some means moment.js start counting not from 2001 it will break all the logic of depending functions

**Additional context**
None

**Comment by RedShift1** [comment]
What do you mean with start counting from 2001? Internally it's stored as a unix timestamp in milliseconds which counts from 1970-01-01 00:00 (UTC).

**Comment by ichernev** [comment]
The default year is the current year (when you pass the time and not specify the date/year). It stores dates internally using the `Date` object. All time libs support unix timestamps, if you're into that.
