### ISSUE TITLE
TypeError: moment__WEBPACK_IMPORTED_MODULE_15___default(...)(...).tz is not a function when upgrade from moment2.29.1 to moment 2.29.4

### ISSUE THREAD

**Issue by galaxy-dot** [moment/moment#6087]
**Describe the bug**
I tried to upgrade moment from `2.29.1` to `2.29.4` to fix ReDos vunl (I think this is [the same reason](https://github.com/moment/moment/blob/develop/CHANGELOG.md#2294) why 2.29.4 is release)

**To Reproduce**
1. In package.json,  "dependencies": {  ..., moment: "^2.27.0", ...}
2. In Terminal, type "yarn upgrade moment@2.29.4" to bump version
3. Can see 2.29.4 is download in node_modules and yarn.lock is updated automatically
4. Tried to build and start the app, failed.
5. Tried to console.log error, see `TypeError: moment__WEBPACK_IMPORTED_MODULE_15___default(...)(...).tz is not a function`

**Expected behavior**

**Screenshots**
with `2.29.1`, moment() object has 7 properties, see screenshot 
<img width="802" alt="Screen Shot 2023-01-13 at 4 40 09 pm" src="https://user-images.githubusercontent.com/52882034/212250200-c1f93f2d-904e-4b95-8596-5d1821b282ab.png">

with `2.29.4`, moment() object has 6 properties, does not have the last '_z' property. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information if applicable):**
 - Browser [e.g. firefox, safari]

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()) //Fri Jan 13 2023 17:08:38 GMT+1100 (Australian Eastern Daylight Time)

  console.log((new Date()).toLocaleString()) //13/01/2023, 17:08:38
  console.log((new Date()).getTimezoneOffset()) //-660
  console.log(navigator.userAgent); //Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
  console.log(moment.version); // 2.29.4
```

**Additional context**
Code snippet
```
// helper.js

import moment from 'moment';

export const currentTZ = () => {
  // console.log(Object.keys(moment()));   // with 2.29.1, this works; the object has 7 properties, last one is "_z". with 2.29.4, this does not work; the object has 6 properties, does not have "_z" property.

  return moment().tz("Australia/Sydney")
    .format('Z') === '+11:00' ? 'AEDT' : 'AEST';
}

```
Any help is appreciated!

**Comment by gilmoreorless** [comment]
Your code snippet doesn't seem to be importing `moment-timezone` anywhere, so it makes sense that `.tz` isn't available.

That said, if it worked before, I suspect there's a separate piece of code in your project that imports `moment-timezone`, which in turn mutates the underlying (and shared) `moment` object. With the upgrade to the newer `moment` version, that reference link might now be broken. See https://github.com/moment/moment-timezone/issues/982#issuecomment-1119540905 for a more detailed explanation of how there can be different versions of `moment` in the same project.

**Comment by galaxy-dot** [comment]
Thanks @gilmoreorless , it's very detailed explanations and great direction. Appreciated your help! 

I am able to fix the issue by following steps:
1. In package.json -> "dependencies" -> remove removed "moment": "^2.27.0"; keep "moment-timezone": "^0.5.33"; then de-duplicate version, as suggested in [How to fix it section in this thread](https://github.com/moment/moment-timezone/issues/982). I ran below cmds in sequence.
```
$ yarn remove moment
$ npx yarn-deduplicate --packages moment
$ yarn install
```
2. In helper.js, updated the OLD imports to NEW imports
```
// OLD imports in helper.js 

import moment from 'moment';  // <- removed this import
import momentTimezone from 'moment-timezone';
```

```
// NEW imports in helper.js

import moment from 'moment-timezone'; // <- update to only use one import from 'moment-timezone'
```
3. All unit tests are passing and build is successful now.
