### ISSUE TITLE
(Feature request) I want the script to display the initial timestamps without needing to mouse hover 

### ISSUE THREAD

**Issue by HappySama** [moment/moment#6090]
So i just want to edit this script 
(https://greasyfork.org/en/scripts/21550-rarbg-convert-torrent-timestamps-to-relative-format)
so that it shows like this 
<img width="569" alt="image" src="https://user-images.githubusercontent.com/75913039/214226475-516aa0d4-7d54-4145-9135-fc35af5b40eb.png">
(but of course, in my local timezone since this is UTC+1 and my timezone is GMT+3)
instead of how it normally showes when enabling the script (i disabled it above to show what i mean), 
here is how it shows with the script
<img width="568" alt="image" src="https://user-images.githubusercontent.com/75913039/214226667-6bc4c52a-f27b-420a-800d-e09fc942deea.png">
What i mean is that instead of seeing the initial torrent timestamps on mouse hover, i want to see it instead of the "6 hours ago" or "1 month ago" (or if you could merge them together in the same box, it'll be even better !)
i hope someone understands what i mean, Thanks in advance !

**Comment by gilmoreorless** [comment]
This project's issue tracker is not a general coding advice forum.
