### ISSUE TITLE
Remove Day.js from recommended alternatives to Moment.js

### ISSUE THREAD

**Issue by sulkaharo** [moment/moment#6102]
Hi! Please remove Day.js from the recommended alternatives to Moment. The library has terrible bugs with time zone handling (see for example https://github.com/iamkun/dayjs/issues/1805) and the maintainer is completely unresponsive in responding to the bug reports. I know several developers have followed the advice in the Moment docs and have realised the library is unusable only after spending considerable effort in taking it into use.

**Comment by ichernev** [comment]
There is a date library more buggy than moment? Wow, the competition is fierce.

I'll look into it.
