### ISSUE TITLE
Problem with tz methods and daylight change in America

### ISSUE THREAD

**Issue by adrianmarinwork** [moment/moment#6108]
Hello, I've added an issue in the moment/moment-timezone repository but, I'm adding this issue in order to gain visibility and because I saw that @gilmoreorless fixed the next [issue](https://github.com/moment/moment/issues/6107) which is pretty similar to the one I'm having.
Link to the [issue](https://github.com/moment/moment-timezone/issues/1042).
Sorry to disturb everyone.
Thank you very much.

**Comment by gilmoreorless** [comment]
Just one issue is enough. Timezone-related problems should stay in the `moment-timezone` issue tracker, so I'll close this one and continue the discussion on the other one.
