### ISSUE TITLE
Timezones like US/Pacific, America/Los_Angeles are not switching between PST and PDT

### ISSUE THREAD

**Issue by mimen** [moment/moment#6111]
**Describe the bug**

I am unsure if this started recently (I believe it has, because we suddenly got multiple support tickets regarding this in the last 24 hours) but it appears that locale based timezones are not automatically switching to PDT. In the Heroku Dashboard, we are seeing all locale based timezones showing standard timezones (PST, EST, MST, etc.) rather than the daylight timezones despite currently being in Daylight Savings Time as of a few weeks ago.

**Expected behavior**
These timezones should be automatically switching between PST and PDT at daylight savings.

**Screenshots**
<img width="604" alt="Screen Shot 2023-03-29 at 11 11 46 AM" src="https://user-images.githubusercontent.com/6692349/228629859-56c7983a-f0fc-4bd5-b7ce-e51bd8c90ea3.png">

Label shows PST, and all times are off by one hour.

**Moment-specific environment**

US/Pacific
11:13AM PDT
Ember
```
Wed Mar 29 2023 11:12:37 GMT-0700 (Pacific Daylight Time)
VM291:2 3/29/2023, 11:12:37 AM
VM291:3 420
VM291:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
VM291:5 2.29.4```

**Comment by daniellecrasiuc** [comment]
Hi, can I be assigned to this issue?

**Comment by sanchej** [comment]
Hi, can I be assigned to work on this issue?

**Comment by kalina559** [comment]
Hi,

Having the same issue with 'Europe/Copenhagen' timezone. It looks like moment.js is still using the Standard Time (+01:00) instead of DST (+02:00)

**Comment by kenyaplenty** [comment]
Hi @kalina559, are you still having this issue in local development or just production?

**Comment by kalina559** [comment]
@kenyaplenty in both

**Comment by kenyaplenty** [comment]
@kalina559 are you doing any specific checks between DST and standard time?

**Comment by kalina559** [comment]
@kenyaplenty nope, just calling tz() on a utc date

**Comment by ismurray** [comment]
This is something I'm also seeing for a number of different timezones. It seems that moment is not currently supporting DST at all for 2023 and beyond.

Example:
```js
> let timeZone = 'America/Los_Angeles';
let winterDateStr = '2022-12-04T17:05';
let summerDateStr = '2022-06-04T17:05';
console.log('2022 Winter ISO Time  ' + moment.tz(winterDateStr, timeZone).toISOString());
console.log('2022 Winter is DST  ' + moment.tz(winterDateStr, timeZone).isDST());
console.log('2022 Summer ISO Time  ' + moment.tz(summerDateStr, timeZone).toISOString());
console.log('2022 Summer is DST  ' + moment.tz(summerDateStr, timeZone).isDST());

winterDateStr = '2023-12-04T17:05';
summerDateStr = '2023-06-04T17:05';
console.log('2023 Winter ISO Time  ' + moment.tz(winterDateStr, timeZone).toISOString());
console.log('2023 Winter is DST  ' + moment.tz(winterDateStr, timeZone).isDST());
console.log('2023 Summer ISO Time  ' + moment.tz(summerDateStr, timeZone).toISOString());
console.log('2023 Summer is DST  ' + moment.tz(summerDateStr, timeZone).isDST());

> 2022 Winter ISO Time  2022-12-05T01:05:00.000Z
 2022 Winter is DST  false
 2022 Summer ISO Time  2022-06-05T00:05:00.000Z
 2022 Summer is DST  true
 2023 Winter ISO Time  2023-12-05T01:05:00.000Z
 2023 Winter is DST  false
 2023 Summer ISO Time  2023-06-05T01:05:00.000Z
 2023 Summer is DST  false
```

This also seems related to this similar issue: https://github.com/moment/moment/issues/6114

**Comment by sanchej** [comment]
@ismurray This is weird, but when I ran your code in my own environment, I received the following output:

```
2022 Winter ISO Time  2022-12-05T01:05:00.000Z
2022 Winter is DST  false
2022 Summer ISO Time  2022-06-05T00:05:00.000Z
2022 Summer is DST  true
2023 Winter ISO Time  2023-12-05T01:05:00.000Z
2023 Winter is DST  false
2023 Summer ISO Time  2023-06-05T00:05:00.000Z
2023 Summer is DST  true
```
I also tried it with 'Europe/Copenhagen' to test @kalina559 's issue and I got:
```
2022 Winter ISO Time  2022-12-04T16:05:00.000Z
2022 Winter is DST  false
2022 Summer ISO Time  2022-06-04T15:05:00.000Z
2022 Summer is DST  true
2023 Winter ISO Time  2023-12-04T16:05:00.000Z
2023 Winter is DST  false
2023 Summer ISO Time  2023-06-04T15:05:00.000Z
2023 Summer is DST  true
```
Am I perhaps missing something? Could you try running your code again to see if the error is still occurring?

**Comment by ismurray** [comment]
@sanchej this may seem like a silly question, but are you potentially using `moment-timezone` instead of `moment`? I ask because this works correctly for me with `moment-timezone`, but not with `moment`. 

**moment:**
```js
import moment from 'moment';
// ...

> let timeZone = 'America/Los_Angeles';
let winterDateStr = '2022-12-04T17:05';
let summerDateStr = '2022-06-04T17:05';
console.log('2022 Winter ISO Time  ' + moment.tz(winterDateStr, timeZone).toISOString());
console.log('2022 Winter is DST  ' + moment.tz(winterDateStr, timeZone).isDST());
console.log('2022 Summer ISO Time  ' + moment.tz(summerDateStr, timeZone).toISOString());
console.log('2022 Summer is DST  ' + moment.tz(summerDateStr, timeZone).isDST());

winterDateStr = '2023-12-04T17:05';
summerDateStr = '2023-06-04T17:05';
console.log('2023 Winter ISO Time  ' + moment.tz(winterDateStr, timeZone).toISOString());
console.log('2023 Winter is DST  ' + moment.tz(winterDateStr, timeZone).isDST());
console.log('2023 Summer ISO Time  ' + moment.tz(summerDateStr, timeZone).toISOString());
console.log('2023 Summer is DST  ' + moment.tz(summerDateStr, timeZone).isDST());

> 2022 Winter ISO Time  2022-12-05T01:05:00.000Z
 2022 Winter is DST  false
 2022 Summer ISO Time  2022-06-05T00:05:00.000Z
 2022 Summer is DST  true
 2023 Winter ISO Time  2023-12-05T01:05:00.000Z
 2023 Winter is DST  false
 2023 Summer ISO Time  2023-06-05T01:05:00.000Z
 2023 Summer is DST  false
```


**moment-timezone:**
```js
import moment from 'moment-timezone';
// ...

let timeZone = 'America/Los_Angeles';
let winterDateStr = '2022-12-04T17:05';
let summerDateStr = '2022-06-04T17:05';
console.log('Winter ISO Time  ' + _momentTimezone.tz(winterDateStr, timeZone).toISOString());
console.log('Winter is DST  ' + _momentTimezone.tz(winterDateStr, timeZone).isDST());
console.log('Summer ISO Time  ' + _momentTimezone.tz(summerDateStr, timeZone).toISOString());
console.log('Summer is DST  ' + _momentTimezone.tz(summerDateStr, timeZone).isDST());

winterDateStr = '2023-12-04T17:05';
summerDateStr = '2023-06-04T17:05';
console.log('Winter ISO Time  ' + _momentTimezone.tz(winterDateStr, timeZone).toISOString());
console.log('Winter is DST  ' + _momentTimezone.tz(winterDateStr, timeZone).isDST());
console.log('Summer ISO Time  ' + _momentTimezone.tz(summerDateStr, timeZone).toISOString());
console.log('Summer is DST  ' + _momentTimezone.tz(summerDateStr, timeZone).isDST());

> Winter ISO Time  2022-12-05T01:05:00.000Z
 Winter is DST  false
 Summer ISO Time  2022-06-05T00:05:00.000Z
 Summer is DST  true
 Winter ISO Time  2023-12-05T01:05:00.000Z
 Winter is DST  false
 Summer ISO Time  2023-06-05T00:05:00.000Z
 Summer is DST  true
```

**Versions:**
```
    "moment": "2.29.4"
    "moment-timezone": "0.5.43"
```

running in Chrome Version 111.0.5563.146 (Official Build) (arm64)

**Comment by mimen** [comment]
Has anybody been able to find the underlying issue inside of moment.js? @daniellecrasiuc @sanchej

**Comment by sanchej** [comment]
Hey @ismurray , sorry I was busy but yes I was running moment timezone, I will continue to look into moment

**Comment by sanchej** [comment]
@mimen  I will continue to look into it, being transparent, I am taking a class that wants us to contribute to an open-source project so I will try to tackle this soon.

**Comment by gilmoreorless** [comment]
Moment Timezone includes OLD AND **DEPRECATED** files called `moment-timezone-with-data-2012-2022.js` (and `.min.js`). As the filename indicates, they only have data up to and including the year 2022. Given the number of reports of "broken" code as we've hit 2023, I'm guessing that a lot of people are using these files without realising that their code should have been changed years ago. The most recent versions of Moment Timezone have added deprecation warnings to these files, and they'll be completely removed in a future release.

Here are my suggestions for everyone with issues around incorrect DST rules starting this year:
1. Check if you're actually using `moment-timezone`, not core `moment`. If your code says `moment.tz()`, you're using `moment-timezone`. Core `moment` doesn't include _any_ time zone rules, and just relies on the native `Date` object.
2. Check _how_ you're including `moment-timezone`. If you're including a file called `moment-timezone-with-data-2012-2022.min.js` or similar, **this is the problem.**
    1. You'll need to change the reference to `moment-timezone-with-data-10-year-range` instead. This is a rolling 10-year range that is updated on every release. For example, any release built in 2023 will include data from 2018 to 2028.

**Comment by mimen** [comment]
Thanks so much @gilmoreorless for providing this info.

For reference for others, I was able to fix this by including this file at the end of my `ember-cli-build.js` file.

``` 
app.import('node_modules/moment-timezone/builds/moment-timezone-with-data-10-year-range.min.js');
```

**Comment by syonfox** [comment]
Hi it apears using moment from the website this is not working still 

demo working 

https://time-to-style.freemap.win/countdown?datetime=2024-05-06T18%3A00&timezone=America%2FLos_Angeles


demo not working 
https://time-to-style.freemap.win/countdown?datetime=2024-05-06T18%3A00&timezone=PDT

See console for error its not finding the abbreviation only the full name

**Comment by gilmoreorless** [comment]
> its not finding the abbreviation only the full name

Moment Timezone doesn't support finding a time zone by its abbreviation, and never has. Abbreviations are not globally unique (e.g. "CST" can map to _at least_ 3 different zones).

**Comment by syonfox** [comment]
Cool this should allow user to select between the ambiguous options. but maybe that's for a future project.

**Comment by Lonz8576** [comment]
Thank you for feedback 😃
If you have any suggestions let me know. I xan change it now that the
project is over. It was a school project that was only allowed certain
attributes.
