### ISSUE TITLE
Issues when parsing ISO week format (WW) - always uses current year

### ISSUE THREAD

**Issue by stefandesu** [moment/moment#6112]
**Describe the bug**
When using the ISO week format WW (e.g. `gggg-[W]WW`) when parsing a date, it always uses the current year instead of the supplied year.

```js
moment("2020-W13", "gggg-[W]WW")
// Returns Moment<2023-03-27T00:00:00+02:00>
```

**To Reproduce**
See example above. You could also add the following test case:

```js
test('get date for gggg-[W]WW format', function (assert) {
    var date = moment("2020-W13", "gggg-[W]WW")
    assert.equal(date.year(), "2020")
})
```

**Expected behavior**
The supplied year (in the example above 2020) should be used.

Possibly related to #6072.

(I know that Moment.js is not maintained anymore, but this was a HUGE pain point for me with the Calendar plugin in Obsidian. Switching to `gggg-[W]ww` worked for me, but other people might encounter this issue as well.)

**Comment by ichernev** [comment]
ISO week year is capital `G`, small `g` is locale-specific week year.

**Comment by stefandesu** [comment]
Thanks @ichernev, I missed that somehow. Still weird that using `gggg` will **always** result in the **current** year to be used (instead of interpreting the value based on the system's locale), but as I'm never going to use the non-ISO week format, I'm not going to look deeper into it. 🤷
