### ISSUE TITLE
Moment js is not working in daylight savings and its showing the timezone as GMT instead of BST in UK

### ISSUE THREAD

**Issue by ThilakGuna** [moment/moment#6114]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information if applicable):**
 - Browser [e.g. firefox, safari]

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

**Additional context**

**Comment by gilmoreorless** [comment]
See https://github.com/moment/moment/issues/6111#issuecomment-1501105788

Also, next time you raise an issue, please fill in all the details requested.
