### ISSUE TITLE
formatting time in HH:mm shorts 1 hour 

### ISSUE THREAD

**Issue by Dipali-arup** [moment/moment#6124]
**Describe the bug**
Moment.js timezone function returns correct date and  time but at time of formating it using format function, returns 1 hr short

**To Reproduce**
execute below line:
moment().tz("Europe/London")
it returns  _d: Wed May 03 2023 11:13:02 GMT+0100 (British Summer Time)
now execute moment().tz("Europe/London").format('HH:mm')
it returns '10:13'

**Expected behavior**
moment().tz("Europe/London").format('HH:mm') should return '11:13' as moment().tz("Europe/London") returns date obeject with  time 11:13:02

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information if applicable):**
 - Browser [e.g. firefox, safari]

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
11:15:37.206 VM1227:1 Wed May 03 2023 11:15:37 GMT+0100 (British Summer Time)
11:15:37.215 VM1227:2 03/05/2023, 11:15:37
11:15:37.215 VM1227:3 -60
11:15:37.215 VM1227:4 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.64
11:15:37.216 VM1227:5 2.21.0
11:15:37.217 undefined
```

**Additional context**

**Comment by tobslob** [comment]
@Dipali-arup Thanks for reporting this issue, I have picked this up and I will push a fix to it soon. Cheers!

**Comment by tobslob** [comment]
Hi @Dipali-arup, I am working on finding a solution. I will address it as soon as possible. But I don't have an exact timeframe at the moment.

**Comment by Dipali-arup** [comment]
hello @tobslob ,
I wonder whether the fix has been released yet?
thank you.

**Comment by harshsapra92** [comment]
Hi @tobslob can I pick this up?

**Comment by tobslob** [comment]
Yes, you can 👍

**Comment by harshsapra92** [comment]
@tobslob looks like it is running fine for me with the below versions:
moment: 2.21.0
moment-timezone: 0.5.43

We don't know what the exact version of moment-timezone @Dipali-arup is using

**Comment by ichernev** [comment]
Don't look at `_d`, it's a hidden property. Also it's not "accurate" when you use `tz`, but the formatting methods are accurate.
