### ISSUE TITLE
week number is not compliant with ISO standard

### ISSUE THREAD

**Issue by thesmart** [moment/moment#613]
I found a bug today, assuming that `moment('Jan 1, 2005').format('YYYY-\\Www-d')` would follow the ISO 8601 standard.  The code sample would return:

```
> moment('Jan 1, 2005').format('YYYY-\\Www-d')
'2005-W53-6'
```

but this is the expected output:

```
'2004-W53-6'
```

http://en.wikipedia.org/wiki/ISO_week_date#Examples

**Comment by sahanDissanayake** [comment]
``
moment().week()
``
breaks when 

``
moment.lang('zh-cn', {
    week : {
        dow : 1 // Monday is the first day of the week
    }
});
``

this is done

**Comment by mysticman** [comment]
Here is the the solution, for the correct week days order, since the last version of moment.js

moment.weekdays(true); 
moment.weekdaysShort(true);
moment.weekdaysMin(true);

https://jsfiddle.net/Chopperbp/pn79ptqx/
