### ISSUE TITLE
Is this project following sem versioning ?

### ISSUE THREAD

**Issue by alberto-f** [moment/moment#6130]
Is this project following sem versioning ?
https://docs.npmjs.com/about-semantic-versioning

Is that said anywhere ? Should I expect breaking changes between version 2.22.0 and 2.29.4 ?

**Comment by gilmoreorless** [comment]
I don't think it's explicitly stated anywhere, but yes, this project uses semver. There shouldn't be any breaking changes within the 2.x.y range, but you can [check the changelog](https://github.com/moment/moment/blob/develop/CHANGELOG.md) to be sure.
