### ISSUE TITLE
monthsShort and format() is returning different values for month names

### ISSUE THREAD

**Issue by iamsank8** [moment/moment#6134]
**Describe the bug**
monthsShort and format() is returning different values for month names.

**To Reproduce**
[https://stackblitz.com/edit/playground-moment-js-qg4ddk?file=index.ts,index.html,node_modules%2Fmoment%2Fts3.1-typings%2Fmoment.d.ts](https://stackblitz.com/edit/playground-moment-js-qg4ddk?file=index.ts,index.html,node_modules%2Fmoment%2Fts3.1-typings%2Fmoment.d.ts)

**Expected behavior**
Both short month names and format using _MMM_ should give same result.

Please run the following code in your environment and include the output:
```
Fri May 26 2023 12:32:33 GMT+0530 (India Standard Time)
preview-8a50ca9ec0a6a.js:2 5/26/2023, 12:32:33 PM
preview-8a50ca9ec0a6a.js:2 -330
preview-8a50ca9ec0a6a.js:2 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
preview-8a50ca9ec0a6a.js:2 2.29.4
```

**Comment by erktyu2** [comment]
According to your stackblitz example, I am getting the same format from both, 3-lettered-month names. Can you explain it more? 

This is what I am getting:
`console.log(moment.monthsShort());` --> `["ene.", "feb.", "mar.", "abr.", …]`

`console.log(moment('2023-01-01').format('DD-MMM-YYYY')); `--> `01-ene-2023`

**Comment by iamsank8** [comment]
hi @erktyu2
In the monthsShort, I can see `dot(.)` being shown, but when I use that in format using `MMM` it gets disappeared.

Is this how its supposed to work?

**Comment by erktyu2** [comment]
Hi, it seems like it is a Spanish word abbreviations standard, which is probably why it ends with a dot(.) in Spanish. What I could find on an official site about Spanish Abbreviations is the following university site. You can read more about that there.
https://www.uoc.edu/portal/es/servei-linguistic/convencions/abreviacions/abreviatures/index.html

And moment.js chose to remove the dot in date formatting since it might be another standard. 

But why/where do you need to compare these 2 months' formats?

**Comment by iamsank8** [comment]
Hi, Thank you for the resource link.

In my webpage there are different widgets/components, some shows only **Month and Year** name and some shows **DD-MMM-YYYY**

When the end user sees this data at a glance, it raises the question on why these 2 dates have different month name.

**Comment by ichernev** [comment]
You can tweak the short months via updateLocale method. Other than that locales can impose rules to tweak formatting in specific formats (i.e if it's MMM alone -- one way, if it's in a combination -- another way).
