### ISSUE TITLE
subtract get last week is wrong

### ISSUE THREAD

**Issue by yidong002** [moment/moment#6136]
当前时间是 2023年06月01日
// 上周开始时间
const lastWeekStart = moment().subtract(1, 'weeks').startOf('week').format('YYYY-MM-DD')
// 上周结束时间
const lastWeekEnd = moment().subtract(1, 'weeks').endOf('week').format('YYYY-MM-DD')

结果为
![image](https://github.com/moment/moment/assets/46306435/316e71f5-a16c-4a11-8e62-21f1d4087a04)

**Comment by soredtrose** [comment]
设置一下local，默认一周开始时间是周日

**Comment by shanhexi** [comment]
hello [soredtrose](https://github.com/soredtrose)

**Comment by ichernev** [comment]
Check your locale dow (start of week). Otherwise I don't see anything wrong.
