### ISSUE TITLE
moment is not returning correct unix string.

### ISSUE THREAD

**Issue by dharmendrasha** [moment/moment#6140]
**Describe the bug**
Moment is not returning correct unix stripe in single liner

**To Reproduce**

I have this line in my code
🟥 
```javascript
import * as DateMoment from 'moment'

DateMoment(new Date()).add(1, 'M').unix() // returns current date in unix number
```

But when i write the lines like this
✅ 
```javascript
import * as DateMoment from 'moment'

const mom = DateMoment(new Date()).add(1, 'M')
mom.unix() // returns correct date in unix numbers
```

I am using moment in node js
Moment version : **version: 2.29.4**
Node Js version: **v18.16.0**
Pnpm version: **8.6.1**
OS: **macos 13.2.1 (22D68)**

**I really do find this weird because in theory they both are basically the same syntax?**

**Comment by ichernev** [comment]
Even if this were the case, I don't see how moment is responsible for the same 2 expressions returning different outputs.
