### ISSUE TITLE
Date Undefined Get True - moment(undefined).isValid()

### ISSUE THREAD

**Issue by LJosephktg** [moment/moment#6144]
const _date = undefined

const isValidDate = moment(_date).isValid();

**Expected behavior -  False**

**_Actual behavior -  True_**

Kindly fix this.

**Comment by MrJithil** [comment]
As per the current implementation, if we pass `undefined` as an argument or not even passing anything ( it will be `undefined` concepts), we will create the Moment object using the current datetime.

In short, `moment()` is equals to `moment(undefined)`.

If you want to handle this in your code by populating Invalid Date for some arguments, use empty string or `null`.

Eg: `moment('')`  or `moment(null)`

```
const isValidDate = moment('').isValid(); // will be false
const isValidDate = moment(null).isValid(); // will be false
```

We can close this ticket.

**Comment by ichernev** [comment]
moment() and moment(undefined) are the same, so yeah. If you're worried about undefined, check it yourself.
