### ISSUE TITLE
Vulnerable dependencies (indirect security issues)

### ISSUE THREAD

**Issue by davidz1337** [moment/moment#6145]
Hello maintainers,

I wanted to bring to your attention that after installing the package, I ran a vulnerability scan with vulert abom on the lock file and discovered that there are over 37 vulnerable dependencies present. As these vulnerabilities can potentially impact the security of the entire project, I am unsure whether to report this under responsible disclosure.

For your reference, here is a link to the report of the package-lock file I scanned: https://vulert.com/vuln-scan/list/e4b772cc-4f6b-418b-87fe-ed545921dde6

I recommend that we take immediate action to address these vulnerabilities and ensure the security of the project. Please let me know if you require any further information.

P.S. this is the lock file i scanned: https://github.com/moment/moment/blob/develop/package-lock.json

Thank you.

**Comment by ichernev** [comment]
moment doesn't have any dependencies, not sure how you're installing it, but all it's deps are dev deps.
