### ISSUE TITLE
Error in the English output of the fromNow() method

### ISSUE THREAD

**Issue by jguipi** [moment/moment#6147]
**Describe the bug**
Whenever the function `fromNow()` is use with a date and a `locale` the English string that is generated produce a duplicate. 

**To Reproduce**
Use the following method with those parameters : 

Function: 
```js
Moment(publishedAt).locale(i18n.language).fromNow()
```

Parameters: 
```
- publishedAt   = 2023-07-17
- i18n.language = "en"
```

Result:
<img width="71" alt="image" src="https://github.com/moment/moment/assets/11049349/c760ab9f-b3c9-4bb2-9940-08641dba9d22">

the "ago ago" string is return two time

On the other hand, only using the following method work: 
```js
Moment(publishedAt).fromNow()
```

Results: 
<img width="71" alt="image" src="https://github.com/moment/moment/assets/11049349/a91323fe-f57c-4e82-b65a-a5260a32fbec">

**Expected behavior**
A well formatted string based on the language provided 

**Screenshots**

**Smartphone (please complete the following information if applicable):**
 - Device: iPhone 11 Pro
 - OS:  iOS 16.4
 - "react-native": "0.72.1"
 - "moment": "2.29.4",

**Moment-specific environment**

* The time zone setting of the machine the code is running on : Eastern Daylight Saving time
* The time and date at which the code was run: every day since 6 months

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

```text
 LOG  ________________________________
 LOG  Tue Jul 18 2023 00:08:38 GMT-0400
 LOG  7/18/2023, 12:08:38 AM
 LOG  240
 LOG  2.29.4
 LOG  ________________________________
```

**Additional context**

**Comment by rohitv007** [comment]
Hey @jguipi, the cases mentioned above are working fine for me. Could you please elaborate more or check if the issue still persists?
(CASE-1 and CASE-2 are respective outputs)
![image](https://github.com/moment/moment/assets/66072894/8b6130b3-d3fe-4f40-8923-55d609cd3b90)
[](url)
![index_ss](https://github.com/moment/moment/assets/66072894/e0cc43a3-b272-498d-b69a-ab6c7173875b)

**Comment by jguipi** [comment]
Sorry everyone, just got back from vacation. 

That's very strange, unfortunately I can't share my code since it's part of the business code... 

I upgraded to the latest version, and it seems like it still happen. If I'm the only one that face that issues, I guess we can close it. I'll investigate on my side and see if I can found the solution and post it here.
