### ISSUE TITLE
.diff() returning NaN sometimes when format is "MMMM YYYY"

### ISSUE THREAD

**Issue by DarthSonic** [moment/moment#6148]
**Describe the bug**
NaN for some, but not all, .diff() when using "MMMM YYYY" formatted moments.

**To Reproduce**
```
const startMoment = moment("Mai 2022", "MMMM YYYY");
const endMoment = moment("April 2023", "MMMM YYYY");
const duration = endMoment.diff(startMoment, "months", true);
console.log(duration); // NaN
```

```
const startMoment = moment("Juni 2022", "MMMM YYYY");
const endMoment = moment("April 2023", "MMMM YYYY");
const duration = endMoment.diff(startMoment, "months", true);
console.log(duration); // 10
```

**Expected behavior**
duration should be numeric value in all cases.

**Screenshots**
![image](https://github.com/moment/moment/assets/3968605/c8567eda-4940-4cdc-a3b7-8e0887c941ab)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 114

**Moment-specific environment**

* de-DE / GMT+0200

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString()) > Fri Jul 21 2023 20:31:05 GMT+0200 (Mitteleuropäische Sommerzeit)
console.log((new Date()).toLocaleString()) > 21.7.2023, 20:31:05
console.log((new Date()).getTimezoneOffset()) > -120
console.log(navigator.userAgent) > Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.86
console.log(moment.version) > 2.29.4
```

**Comment by arswaw** [comment]
What is the purpose of misspelling the month names?

**Comment by DarthSonic** [comment]
Why misspelling? Mai is German of May if you meant that one.

**Comment by ichernev** [comment]
When you submit a bug report, try to do a minimal reproduction. Is the problem the date parsing from German? Maybe. Is it in diff function? Maybe. I can't really tell. The diff should be solid, so my money is on the parsing. Make sure you have the right locale set up.
