### ISSUE TITLE
 Which one is the official CDN link?

### ISSUE THREAD

**Issue by hcxmj** [moment/moment#6150]
I want to use the umd+externals method of webpack to introduce moment to reduce the package size, but I don’t see a standard CDN link in the official document, and I can’t tell which one is official in some posts in the community

**Comment by raman-saluja** [comment]
Official CDN link given in Documentation  - https://momentjs.com/docs/#/use-it/browser/

**Comment by ichernev** [comment]
I don't think have "official" cdn, just a bunch of CDNs pick up the releases and bundle them. You can download from npm or the web (but from the web it uses github pages, so not likely to be blazing fast).
