### ISSUE TITLE
Czech republic localization

### ISSUE THREAD

**Issue by JonasJonny** [moment/moment#6153]
**Months (standalone and format) are switched – /locale/cs.js**

_Standalone_ format for months is.
`leden_únor_březen_duben_květen_červen_červenec_srpen_září_říjen_listopad_prosinec`

_Format_ then should be
`ledna_února_března_dubna_května_června_července_srpna_září_října_listopadu_prosince`

You can check the right format ["Názvy měsíců v roce v různých jazycích"](https://kalendar.beda.cz/nazvy-mesicu-v-roce-v-ruznych-jazycich). 
I don't know where else this is used?

**To Reproduce**
1. moment('01/20/2023').format('LLLL'); // pátek 20. ledna 2023 0:00
2. moment('01/20/2023').format('MMMM'); // ledna

**Expected behavior**
1. moment('01/20/2023').format('LLLL'); // pátek 20. leden 2023 0:00 (Easier) | pátek 20. ledna 2023 0:00 ([cs_CZ](https://metacpan.org/dist/DateTime-Locale/view/lib/DateTime/Locale/cs_CZ.pod))
2. moment('01/20/2023').format('MMMM'); // leden

**Comment by JonasJonny** [comment]
Please @ichernev, can you fix it?
This commit https://github.com/moment/moment/commit/75e2ac573e8cd62086a6bc6dc1b8d271e2804391 makes Moment unusable in newer versions.

**Comment by KristjanESPERANTO** [comment]
Since moment is no longer under active development [1], I've moved my projects to alternatives [2]. Have you considered that?

[1] https://momentjs.com/docs/#/-project-status/
[2] https://blog.logrocket.com/4-alternatives-to-moment-js-for-internationalizing-dates/

**Comment by JonasJonny** [comment]
@KristjanESPERANTO I considered it but I need to use another package which depends on it.

**Comment by KristjanESPERANTO** [comment]
Given the many open PRs and issues, I wouldn't assume that your issue will be resolved at any point.

Have the maintainers of that package you depend on considered migrating? If that's not clear, create a PR or open an issue there.

**Comment by ichernev** [comment]
Just submit a PR. Others could use it and it could be merged eventually. Also make sure it's CLDR compliant.
