### ISSUE TITLE
Unexpected behaviour with 'days' unit when using moment.duration?

### ISSUE THREAD

**Issue by clementrcheng** [moment/moment#6157]
When creating a duration object in these two examples, the behaviour is how I expected it to be as the units are converted:

a)
const duration = moment.duration({seconds:150});
const minutes = duration.minutes();
// 2
const seconds = duration.seconds();
// 30

b)
const duration = moment.duration({minutes:150});
const minutes = duration.hours();
// 2
const seconds = duration.minutes();
// 30

However, when passing in days, I'm getting these results:
c)
const duration = moment.duration({days:9});
const weeks = duration.weeks();
// 1
const days = duration.days();
// expected value: 2
// actual result: 9

Because the value for weeks is 1, I would expect the value for days to be 2 in this case - similar to how the units get converted in the first 2 examples. 

I'm getting around this by doing the following:

const rawDays = duration.days();
const actualDays = rawDays >= 7 ? rawDays % 7 : rawDays;

I was wondering if this is actually a bug or if it's how it's intended to work?
Thanks!

**Comment by ichernev** [comment]
use `.asDays()` -- this gives you total days, `.days()` gives you reminder days after the higher units are processed.
