### ISSUE TITLE
cdnjs advertises v2.29.4 with invalid integrity hash

### ISSUE THREAD

**Issue by veselov** [moment/moment#6158]
Not sure what's going on here.

https://cdnjs.com/libraries/moment.js/2.29.4
The first entry is:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"
 integrity="sha512-CryKbMe7sjSCDPl18jtJI5DR5jtkUWxPXWaLCst6QjH8wxDexfRJic2WRmRXmstr2Y8SxDDWuBO6CQC6IE4KTA==" 
crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```

But SHA512 of the download file is different:

```
$ curl -o /tmp/x https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js
$ openssl sha512 /tmp/x | awk '{print $2}' | xxd -r -p | base64
+H4iLjY3JsKiF2V6N366in5IQHj2uEsGV7Pp/GRcm0fn76aPAk5V8xB6n8fQhhSonTqTXs/klFz4
D0GIn6Br9g==
```

Using the tag in the browser gives the same error:
> Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js' with computed SHA-512 integrity '+H4iLjY3JsKiF2V6N366in5IQHj2uEsGV7Pp/GRcm0fn76aPAk5V8xB6n8fQhhSonTqTXs/klFz4D0GIn6Br9g=='. The resource has been blocked.

**Comment by gilmoreorless** [comment]
Hrm, I don't think anyone on this project has any control over CDNJS. You might need to raise an issue with them at https://github.com/cdnjs/cdnjs

**Comment by veselov** [comment]
I sort of expected that moment.js maintainers publish their released to CDNJS, and that's there the hash is specified to avoid MITMAs.

However, considering https://github.com/cdnjs/cdnjs/issues/14080, it seems that this happens every now and then, and CDSNJS does generate their own SRIs.

I've opened https://github.com/cdnjs/cdnjs/issues/14214

**Comment by gilmoreorless** [comment]
https://github.com/cdnjs/cdnjs/issues/14210 has been resolved, so I'm closing this issue.
