### ISSUE TITLE
Socket Security: Obfuscated require

### ISSUE THREAD

**Issue by karlhorky** [moment/moment#6159]
Hi there, first of all, thanks for Moment.js and the great community around it!

**Describe the bug**

I wanted to report [the "Obfuscated require" security problem with `moment@2.29.4`](https://socket.dev/npm/package/moment) that is reported by @feross' new Socket Security platform:

> Obfuscated require
> SEVERITY: High
> DESCRIPTION: Package accesses dynamic properties of require and may be obfuscating code execution.
> SUGGESTION: The package should not access dynamic properties of module. Instead use import or require directly.

![Screenshot 2023-08-27 at 18 07 38](https://github.com/moment/moment/assets/1935696/fe6cef1d-53b1-433b-b733-e7814172f925)

Files containing the vulnerability:

- `dist/moment.js`
- `min/moment-with-locales.js`
- `moment.js`
- `src/lib/locale/locales.js`

Even if this isn't a real security issue, it may be worth it to try to avoid generating this warning, to avoid users seeing it and either reporting it again or looking for an alternative.

**To Reproduce**

1. Go to https://socket.dev/npm/package/moment
2. See security vulnerability warning

**Expected behavior**

No security vulnerability warnings for `moment`

**Screenshots**

Included above

**Desktop (please complete the following information):**

Not applicable

**Smartphone (please complete the following information if applicable):**

Not applicable

**Moment-specific environment**

Not applicable

**Additional context**

--

**Comment by ichernev** [comment]
I have no idea what we're accessing. Probably to load locales. In any case, it's not changing, but if you really want to try -- submit a PR

**Comment by karlhorky** [comment]
Hm ok, maybe this issue can stay open until the root cause it at least determined, if you can't understand the report above? Having a false positive would also be a resolution here, but would be good to first understand why it's happening. (and fix it in Socket)

cc @feross @bmeck @jhiesey @charliegerard @101arrowz if someone from the Socket team could also comment here, that would be great. (or even better - make the error messages more understandable and actionable)
