### ISSUE TITLE
Feb29's month is returning as 2 instead of 1

### ISSUE THREAD

**Issue by syedsanahassan** [moment/moment#6165]
**Describe the bug**
When I try to get month for "Feb29" as a date I get value as 2 instead of 1 (which is correct)

JSFiddle to reproduce the bug is at https://jsfiddle.net/8ru2hxv9/

**Expected behavior**
The month for Feb29 should be correctly returned as 1

```
var t1 = moment("Jan 29, 2023")
console.log("Jan: ", t1.month())
let t2 = moment("Feb 29, 2023")
console.log("Feb: ", t2.month())
let t3 = moment("Mar 29, 2023")
console.log("Mar: ", t3.month())
```

You can check the above fiddle where the output for t2.month() shows up as 2 instead of 1.

**Additional context**

**Comment by MrJithil** [comment]
The fiddle doesn't have any scripts. Please check and update the minimal reproduce steps.

**Comment by syedsanahassan** [comment]
@MrJithil updated fiddle and also updated the initial description

**Comment by syedsanahassan** [comment]
FYI I know Feb29, 2023 is not a valid date but still the month being returned isn't right. Either return an error or return 1, would you agree?

**Comment by MrJithil** [comment]
As per the whatwg and MDN, this is an expected behaviour. New date will be adjusted to the next available date in case the day limit is in valid range. 
MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

```
['Feb 29 2023', 'Feb 30 2023', 'Feb 31 2023', 'Feb 29 2024', 'Feb 30 2024', 'Feb 32 2024'].forEach(
    (date) =>
        console.log(
            `${date} => ${new Date(date).toLocaleDateString('en', {
                year: 'numeric',
                month: 'short',
                day: 'numeric',
            })}`
        )
);
```

Fiddle: https://jsfiddle.net/jithil/Lr3q0ghv/

**Comment by MrJithil** [comment]
So, we can close this issue.
