### ISSUE TITLE
moment.tz.guess(true) is not giving the changed time zone as part of DST changes, still giving the actual server time zone with which node application started

### ISSUE THREAD

**Issue by Ganeshfair** [moment/moment#6167]
Description:
Moment.tz.guess(true) is not fetching the modified timezone as part of DST changes

1. Start a node js application with local machine time, lets say IST (UTC+5"30).
2. Once application started change the time zone of the machine to Bangkok zone (UTC+7:00)
3. moment.tz.guess(true) is giving the old time zone value of IST itself.
5. only after restart of node application, modified time zone is effected by this line of code.
6. Note - Observed this behavior in windows and hoping same in Unix also.

**Expected behavior**
As mentioned in the documentation of moment. guess(true) method should give the  machines latest time zone modified.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Node JS applciation
 - NodeJS v18.17.0

**Moment-specific environment**
moment : "2.29.1"
moment-timzone : "0.5.33"

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```
Output:
Tue Sep 05 2023 15:10:01 GMT+0530 (India Standard Time)
9/5/2023, 3:10:01 PM
-330
2.29.1

**Additional context**

**Comment by gilmoreorless** [comment]
This is expected. NodeJS only uses the environment variables that it was started with, including time zone. It doesn't update the current time zone dynamically.
Try logging `new Intl.DateTimeFormat().resolvedOptions().timeZone` in NodeJS in the same scenario and you'll see that it only changes after a restart. This is common behaviour for a lot of language runtimes.
