### ISSUE TITLE
2023-05-26 - 'Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date()'

### ISSUE THREAD

**Issue by BKSnake** [moment/moment#6174]
**Describe the bug**
I'm using moment and getting next problem:
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2023-05-26 , _f: undefined, _strict: undefined, _locale: [object Object]
```

it's happened from time to time, I can't why it heppend.

**To Reproduce**
Steps to reproduce the behaviour :
1. const date = moment('2023-05-26').valueOf();

**Expected behavior**
I would like didn't get error if 2023-05-26 is normal.

**Desktop (please complete the following information):**
 - AWS Lambda
 - NodeJs 18
 - Version moment: 2.29.4

Additional lib:
moment-range: "4.0.2",
moment-timezone: "0.5.43"

**Comment by MrJithil** [comment]
Which browser / OS you are using ? Its not reproducible in Mac Chrome/Safari.

**Comment by ichernev** [comment]
Just pass a format string. It's not hard. Otherwise you depend on your environment, which can lead to unexpected results.

**Comment by nguyenductu0703** [comment]
Can you give me an example?
