### ISSUE TITLE
parseZone() seems to have unexpected handling of ambiguous input 

### ISSUE THREAD

**Issue by artchen-db** [moment/moment#6178]
**Describe the bug**

Based on the documentation:

* `moment.utc(...)` is utc mode. **Ambiguous input is assumed to be UTC.** Unambiguous input is adjusted to UTC.
* `moment.parseZone()` keep the input zone passed in. **Ambiguous input is assumed to be UTC.**

Since for ambiguous input the wording is exactly the same, I assumed they would produce the exact same result. For example I expect this line of code to return true:

```
moment.utc('1900-01-01').isSame(moment.parseZone('1900-01-01'));
```

However, when running this line of code with system / browser timezone set to Asia/Shanghai, Asia/Kolkata, Europe/Moscow, or perhaps many other ones, the result would be false.

Also noting that more modern time like `2000-01-01` doesn't have this issue.

This looks like a bug to me, since the documentation indicates the result should be agnostic to local timezone. If this is not a bug, I would appreciate any help to understand the reason, and perhaps have the quirk documented somewhere.

**To Reproduce**

Run `moment.utc('1900-01-01').isSame(moment.parseZone('1900-01-01'));` when local timezone is `Asia/Shanghai`. You can either change OS timezone or use Chrome dev tools to override.

<img width="421" alt="image" src="https://github.com/moment/moment/assets/143461729/90204bbc-ec4d-4c3a-af76-7b221c6888b4">

**Expected behavior**

This line `moment.utc('1900-01-01').isSame(moment.parseZone('1900-01-01'));`  should return true, in other words, moment.utc and moment.parseZone should have the same output when input is offset-ambiguous.

**Screenshots**

<img width="459" alt="image" src="https://github.com/moment/moment/assets/143461729/45ba75f6-e1a9-4d60-8e3c-78a014359f3b">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Version 117.0.5938.149 (Official Build) (arm64)

**Smartphone (please complete the following information if applicable):**

I didn't test on mobile.

**Moment-specific environment**

* The time zone setting of the machine the code is running on: `Asia/Shanghai`
* The time and date at which the code was run: now
* Other libraries in use (TypeScript, Immutable.js, etc): N/A, I can repro on momentjs.com in Chrome console

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

```
Fri Oct 13 2023 01:59:51 GMT+0800 (中国标准时间)
2023/10/13 01:59:51
-480
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2.29.4
```

**Additional context**
N/A

**Comment by shridhar2656** [comment]
If you are running the code in Asia example I am running in INDIA, moment.js will use the Asia/Kolkata timezone. Therefore, the moment.parseZone() function will parse the date string 1900-01-01 in Asia/Kolkata time, which will create a Moment object that represents the date and time 1900-01-01 05:30:00 UTC.
 
 he moment.utc() function will create a new Moment object in UTC time, which will create a Moment object that represents the date and time 1900-01-01 00:00:00 UTC.
 
 so the output would be false

**Comment by artchen-db** [comment]
Thanks @shridhar2656. What your experiment shows is that `parseZone` will parse ambiguous inputs in local timezone, that contradicts with the documentation:

<img width="738" alt="image" src="https://github.com/moment/moment/assets/143461729/58c40a8f-4fef-4504-ba65-9ce22bb45ed9">

**Comment by artchen-db** [comment]
The doc was updated in 2020 specifically to change from mentioning local mode to UTC: https://github.com/moment/momentjs.com/commit/af673359476388d94cd36807d157a525037ccfc6.
