### ISSUE TITLE
Add support for startOf(multiple, "interval") or startOf(Duration) to get a beginning of the interval as multiple units #5831

### ISSUE THREAD

**Issue by tx0c** [moment/moment#6183]
latest postgres (14+) above has a SQL function called `date_bin` can for example,

    date_bin('15 minutes', timestamp)

to get beginning to a multiple of the interval `15 minutes`

[9.9.3. date_bin](https://www.postgresql.org/docs/14/functions-datetime.html#FUNCTIONS-DATETIME-BIN)

but some applications still running older Postgres versions, or other SQL variants, want to simulate this feature from application layer with momentjs:

    .startOf(15, "minute")
    .startOf(moment.duration(2, 'd'))    <= Duration

**Comment by ichernev** [comment]
convert object to unix ms timestamp and duration to ms, then `startOf = function (mom, dur) { return moment(+mom - (+mom % dur.asMilliseconds())) }`
