### ISSUE TITLE
gets wrong date from date string

### ISSUE THREAD

**Issue by kriit24** [moment/moment#6184]
**Describe the bug**
gets wrong date from date string

**To Reproduce**
`
Moment.locale('ee');
var dt = '2016-05-02';

console.log(Moment(dt).format('d.m.Y'));
`

**Expected behavior**
02.05.2016

**Real output**
1.0.2016

**Comment by carloskim123** [comment]
try this other way:
`const moment = require("moment")

moment.locale('ee');
var dt = '2016-05-02';

console.log(moment(dt, 'YYYY-MM-DD').format('DD.MM.YYYY'));
`

**Comment by amitkumarannex** [comment]
Please set your device time to automatic

**Comment by carloskim123** [comment]
What do you mean
