### ISSUE TITLE
format YYYY-MM-DD issues

### ISSUE THREAD

**Issue by Duack** [moment/moment#6192]
**Describe the bug**

**Run code formatted as YYYY-MM-DD, should output four digit years**

moment("20223-01-01").format("YYYY-MM-DD")

![Snipaste_2023-12-21_11-37-31](https://github.com/moment/moment/assets/37917976/acd87465-4156-439c-805b-c342d7ef4638)

**To Reproduce**
1. Go to use 【 moment("20223-01-01").format("YYYY-MM-DD") 】 code

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information if applicable):**
 - Browser [e.g. firefox, safari]

**Moment-specific environment**

* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

Please run the following code in your environment and include the output:
```
console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
```

**Additional context**

**Comment by ichernev** [comment]
YYYY means display at least 4 digits. If your year has 5 digits it won't truncate  it. If you have such weird dates in your app you should handle them manually.
