### ISSUE TITLE
New patch version 2.30.0 breaks types toISOString now returns null

### ISSUE THREAD

**Issue by rluvaton** [moment/moment#6194]
**Describe the bug**
The newly deployed version 2.30.0 breaks a lot of services and libs for us, as `toISOString` now returns null

https://github.com/moment/moment/commit/c6d26079326c65e8d9804abb9b12484694972922

https://github.com/moment/moment/blob/ddd680908c23797a3ed22007838634518bb14705/ts3.1-typings/moment.d.ts#L578

**Comment by ichernev** [comment]
it always had the option of returning null, if the date is invalid. Now it's just specified properly.

**Comment by rluvaton** [comment]
I agree but all the types are now breaking...

**Comment by ichernev** [comment]
I'll release 2.30.1 in a bit. Just waiting for some other complaints...  From all the shit I changed I didn't see this one coming (also I'm not a TS user).

**Comment by ichernev** [comment]
2.30.1 is out, @rluvaton close the issue after testing, please.

**Comment by rluvaton** [comment]
Yes, it's working now, thanks!

**Comment by TWiStErRob** [comment]
So how can this be changed? Anyone who's using this doesn't have type safety, i.e. potential runtime error.

**Comment by 2colours** [comment]
> So how can this be changed? Anyone who's using this doesn't have type safety, i.e. potential runtime error.

@TWiStErRob well, from what I understand, the change only revolved around the TS declarations for the whole time. So it didn't get better or worse. If somebody doesn't have type safety now, they didn't have earlier either. Maybe that should be a different issue, if there isn't one already.

**Comment by TWiStErRob** [comment]
> Anyone who's using this doesn't have type safety, i.e. potential runtime error.

By this I meant more that in TS, if you're using this function we were compiling against a "lie", and therefore the code might be inherently buggy. This is known now, but reverted. I'm not fully versed in JS's semver conventions, but I find this confusing.

In Kotlin there's a @RecentlyNullable annotation that changes the compiler behavior to warn on those null dereferences instead of error. I wonder if there's a similar in TS that can be used to aid migration.

**Comment by Zandor300** [comment]
There is a `3.x` branch that is 7 years old. Maybe reintroduce the reverted change in an updated v3 branch so when the time comes this can be fixed then?
