### ISSUE TITLE
Wrong week() and isoWeek() for 2024-12-30 and 31

### ISSUE THREAD

**Issue by elauria** [moment/moment#6196]
For dates '2024-12-30' and '2024-12-31' the .week() and .isoWeek() return '1' instead of '53'. December 30 is a Monday, 31 is Tuesday, so they should be week 53.

**To Reproduce**
1. const moment = require("moment")
2. const d = moment("2024-12-30")
3. d.week()
=> 1

**Expected behavior**
Expect it to return 53 instead of 1

- Version 2.30.1
- Tried in different timezones (GMT, GMT+3) and systems (Archlinux, OS X), same result

**Comment by ichernev** [comment]
https://www.calendar.best/images/2024/week-numbers/2024-calendar-with-iso-week-numbers-landscape-blue.jpg

This ISO-week calendar begs to differ.

Iso-weeks starts with the Thursday, Thursday of that week is in 2025, so the week starting in 30th Dec is week 1 of the 2025 iso week year.
