### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by Hu1a1a** [moment/moment#6212]
Hi Sir,

I got the follow warning that not affecting in the normal work of the dependency, but I hope it can be fixed.

Error mensaje is:
``moment.min.js:1 Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.``

**Comment by antarilos** [comment]
That message is shown probably because the method `defineLocale` is being used in your code to update an already existing locale.
Please, refer to the info in the link http://momentjs.com/guides/#/warnings/define-locale/ to properly remove that warning from your code.
