### ISSUE TITLE
Changed timezone 'Asia/Almaty' wat +6 => now +5

### ISSUE THREAD

**Issue by kholovyun** [moment/moment#6220]
**Describe the bug**
In my country (Kazakhstan by the way) changed timezone 'Asia/Almaty' was +6 => now +5

**To Reproduce**
1. Get a 'Asia/Almaty' timezone 
2. See that is +6
3. Should be +5

**Expected behavior**
"Asia/Almaty" should be +5

**Comment by caryyu** [comment]
@ichernev any thoughts on this? guess it's a universal issue.

**Comment by gilmoreorless** [comment]
If you're using just Moment by itself, it will use whatever time zone definitions are provided by the host environment (browser, NodeJS, etc.). If you're using the Moment Timezone addon, the latest version handles the Kazakhstan changes correctly.
