### ISSUE TITLE
Security issue with the usage of \\ inside replace method

### ISSUE THREAD

**Issue by srini3793** [moment/moment#6237]
**Describe the bug**
Their is a security vulnerability with the direct usage of \\ in replace method mentioned in this file https://github.com/moment/moment/blob/18aba135ab927ffe7f868ee09276979bed6993a6/src/lib/parse/regex.js#L69 it has to be appropriately sanitized with below logic for ex

function unescapeFormat(s) {
    return regexEscape(
        s
            .replace('\\', '')
 with 
 
 function unescapeFormat(s) {
    return regexEscape(
        s
            .replace(/\\/g, '') 

at all occurences of replace and \\ usage.
**To Reproduce**
go to https://github.com/moment/moment/blob/18aba135ab927ffe7f868ee09276979bed6993a6/src/lib/parse/regex.js#L69

**Expected behavior**
JS characters to be appropriately sanitized in replace method.

**Screenshots**

**Comment by gilmoreorless** [comment]
There are some key details missing here. What is the actual vulnerability you're reporting? What is the impact? Is there a link to a vulnerability report somewhere?

**Comment by srinivas3793** [comment]
@gilmoreorless Pls check the codeql link for the issue description https://codeql.github.com/codeql-query-help/javascript/js-incomplete-sanitization/

Moment pkg file which I'm reporting is violating above security checks in the file https://github.com/moment/moment/blob/18aba135ab927ffe7f868ee09276979bed6993a6/src/lib/parse/regex.js#L69

**Comment by gilmoreorless** [comment]
I think you've misunderstood what the linked code does. The CodeQL link is warning about incomplete **escaping**, but the `unescapeFormat` function does the _opposite_ of escaping — it's stripping away certain escaping characters **then passing them to the `regexEscape` function** to do the proper escaping.

Additionally, `unescapeFormat` only runs on small tokens that have already been broken apart by the regex at https://github.com/moment/moment/blob/18aba135ab927ffe7f868ee09276979bed6993a6/src/lib/format/format.js#L4-L5

Static code analysers can only make inferences based on patterns, but won't always know the full context of the code. They're very helpful for catching potential bugs, but they do also have false positives. This is one of those times.
Blindly following the reports of a static analyser 100% can sometimes lead to problems, in the same way as completely ignoring them. Context always has to be taken into account.
