### ISSUE TITLE
Glob version deprecated

### ISSUE THREAD

**Issue by ChronoBoot** [moment/moment#6245]
**Describe the bug**
The glob version is deprecated

**To Reproduce**
```
npm i moment --save
```

**Expected behavior**
No warning

**Screenshots**
```npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

**Desktop (please complete the following information):**
 System:
    OS: macOS 14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Binaries:
    Node: 22.3.0 - ~/.nvm/versions/node/v22.3.0/bin/node
    Yarn: 1.22.22 - ~/.yarn/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v22.3.0/bin/npm
    pnpm: 6.11.0 - ~/.nvm/versions/node/v14.19.0/bin/pnpm
  npmPackages:
    jest: ^29.7.0 => 29.7.0

**Additional context**

**Comment by gilmoreorless** [comment]
Moment doesn't use `glob` directly. It's brought in by other packages, which Moment only specifies in `devDependencies`. This means they're only installed when working in the `moment` project root — they are not installed when `moment` is installed as a dependency.
