### ISSUE TITLE
Module not found: TypeCannot read properties of undefined (reading 'startsWith') 

### ISSUE THREAD

**Issue by bigbizze** [moment/moment#6259]
```
./node_modules/moment/moment.js
Module not found: TypeCannot read properties of undefined (reading 'startsWith')

Import trace for requested module:
./node_modules/moment/moment.js
./node_modules/moment-timezone/moment-timezone.js
./node_modules/moment-timezone/index.js
./node_modules/date-holidays-parser/src/Equinox.js
./node_modules/date-holidays-parser/src/CalEventFactory.js
./node_modules/date-holidays-parser/src/DateFn.js
./node_modules/date-holidays-parser/src/Holidays.js
./node_modules/date-holidays-parser/src/index.js
./node_modules/date-holidays/src/Holidays.js
./node_modules/date-holidays/src/index.js
```

I am not sure what is causing this issue, I'm assuming it's some dependency thing between `date-holidays`, `date-holidays-parser`, `moment-timezone` and `moment`. 

----

I have my resolutions set to:

```json
  "resolutions": {
    "date-holidays-parser": "^3.4.4",
    "moment": "^2.29.4",
    "moment-timezone": "0.5.43"
  },
```

and i am using `date-holidays@3.23.12`

----

date-holidays issue: https://github.com/commenthol/date-holidays/issues/487
date-holidays-parser issue: https://github.com/commenthol/date-holidays-parser/issues/59
moment-timezone issue: https://github.com/moment/moment-timezone/issues/1122

**Comment by gilmoreorless** [comment]
See https://github.com/moment/moment-timezone/issues/1122#issuecomment-2439968531

**Comment by q-o-ap** [comment]
holiday is not in the calenders because there is 3days holiday

**Comment by q-o-ap** [comment]
{{ issue.MW check-in
Datetime.setTimeZone("localetime")
     }}
