### ISSUE TITLE
Default year should be this year

### ISSUE THREAD

**Issue by brianmhunt** [moment/moment#635]
It would make sense to me if the default "guessed" year would be this year, i.e.

```
moment("jan 15").year() == 2013
```

would be true.

However the year seems to default to 2001 when not supplied.

The functionality as-is might be a design choice, but I thought to mention it just in case.

Cheers

**Comment by vinod-sai** [comment]
Any example of how to use this ? default year still seems to be 2001 @ichernev 

![image](https://user-images.githubusercontent.com/31060763/95974935-2ca40600-0e33-11eb-82db-7e91d73e5d23.png)

**Comment by C5H8NNaO4** [comment]
+1 - The default year is 2001, not the current year

**Comment by nicholaszuccarelli** [comment]
+1 for this. I'm in the same situation as @vinod-sai where they can enter any string without a year and I need to to default to the current year too.

**Comment by vinod-sai** [comment]
@nicholaszuccarelli try this :) 
![image](https://user-images.githubusercontent.com/31060763/102211249-5c39c200-3ef9-11eb-9f94-8670294c6518.png)

**Comment by nicholaszuccarelli** [comment]
> @nicholaszuccarelli try this :)
> ![image](https://user-images.githubusercontent.com/31060763/102211249-5c39c200-3ef9-11eb-9f94-8670294c6518.png)

Haha no joke I actually wrote something very similar to this within the last half hour and it works perfectly. 
Thanks for the help anyway :)

**Comment by tounsoo** [comment]
But what if someone is actually selecting `2001`? 😢
