### ISSUE TITLE
Throw exception on invalid time intervals

### ISSUE THREAD

**Issue by edzhelyov** [moment/moment#688]
`moment.duration` will silently return 0 is you misspell the time interval.
Please change that and throw Exception. This applies to other methods that rely on String
for determining the interval.

**Comment by Strajk** [comment]
Hi, any update on this?

I just found a totally hidden bug in my app, API changed from returning a number to an object and moment just silently ignored it. I know I should have had tests, but still I would notice exception as we are logging them.

moment().subtract({nonsense: "total"}, "hours") => return current date

I agree on opt-in solution :)

**Comment by ma-df** [comment]
Bump, is there a way to optionally throw an error on absurd input? Apologies if i'm beating a dead horse.

```
moment().startOf("bananaphone").isValid() === true
```
