### ISSUE TITLE
On Android 4.0.4 Moment.js 2.0.0 produces errors because of a JavaScript problem

### ISSUE THREAD

**Issue by googol7** [moment/moment#724]
On this Android 4.0.4 device:

Model number LT28h
Android 4.0.4
Build-Nummer: 6.1.E.0.233
AppleWebKit/534.30 (KHTML, like Gecko)
Version/4.0 Mobile Safari/534.30

this code produces these results:

y = new Date();
y.setHours(0,0,0,0);
y.setFullYear(XXXX,1,1);
alert(y.getSeconds());

For XXXX you insert these values und get these results:

input: 1901 | result: 52
input: 1902 | result: 0

input: 2037 | result: 0
input: 2038 | result: 7

It should always return 0 because we set y.setHours(0,0,0,0);

A workaround could be that if you only analyse a time like this:
var test = moment( '12:00:32', 'HH:mm:ss');
You also provide JavaScript with a date like 01.01.1970 so that getSeconds() always returns the correct value.

**Comment by kuznetsov0209** [comment]
I've manage to fix it by converting date format for moment.
You need to use
```moment("2015/05/18 14:08:50").format()``` 
instead of
```moment("2015-05-18T14:08:50").format()```

You also may use this approach:
```js
String.prototype.dateFormatFix = function() {
	return this.toString().replace('T', ' ').replace(/[\-]+/g, '/');
}

var date = "2015-05-18T14:08:50";
moment(date.dateFormatFix()).format()
```
