### ISSUE TITLE
startOf/endOf("week") are not locale aware

### ISSUE THREAD

**Issue by fuwaneko** [moment/moment#727]
When I set week.dow to 1 and let's assume it's Saturday 14th April today and I say

```
moment().startOf("week")
```

It gives me today instead of Monday 8th April.

http://jsfiddle.net/zQx23/

**Comment by kimmobrunfeldt** [comment]
I'm using moment 2.8.4 and setting locale works for me:

```javascript
$ node
> var moment = require('moment');
undefined
> console.log('Version', moment.version);
Version 2.8.4
undefined
> moment.locale('en', {
>     week: {
>         dow: 1 // Monday is the first day of the week.
>     }
> });
'en'
> moment().startOf('week').format('dddd');
'Monday'
>
```

It also seems that .lang is now deprecated:

```javascript
> moment.lang('en', {
>     week: {
>         dow: 1 // Monday is the first day of the week.
>     }
> });
Deprecation warning: moment.lang is deprecated. Use moment.locale instead.
```

**Comment by sahanDissanayake** [comment]
Guys this solution seems to break, the following code to get the current week number

```
moment().week() // NaN 
```

**Comment by uriklar** [comment]
@sahanDissanayake Could you please explain why you set doy to 6? The docs say it should be set to 4

**Comment by sahanDissanayake** [comment]
oh mate I'm not sure, At the time it seemed alright, I have moved on to other projects now.

**Comment by sahanDissanayake** [comment]
@uriklar I know why I did this, because without setting this, when you do moment().week() you get NaN error

**Comment by sahanDissanayake** [comment]
@uriklar I got the 6 from here https://github.com/moment/moment/blob/develop/moment.js#L2540

**Comment by sahanDissanayake** [comment]
is this solved ?? 
Im using v2.13.0

I tried to do `moment.weekdays()` but still the start day is Sunday..

**Comment by RomainSF** [comment]
this is ridiculous, can someone fix this?

**Comment by fuwaneko** [comment]
@RomainSF @sahanDissanayake I think you should file separate bug for moment.weekdays() since startOf/endOf("week") work properly.

**Comment by offirpeer** [comment]
I am using version : 2.15.2 and

moment().subtract(1, 'weeks').startOf('week') return sunday , and when I change my ip to united states I still get sunday when I expect to get mondy. 
any solution for that?

**Comment by butterflyhug** [comment]
@offirpeer Moment supports a wide range of locales, but you will need to explicitly select the locale that is most appropriate for your application in a particular location.  A bunch of folks use `moment.locale(window.navigator.language)` to autodetect an appropriate locale in most circumstances, but that's based on the locale settings of the user's computer and browser -- not their IP address.

Also, note that `.startOf('week')` is Sunday in the default U.S. locale -- U.S. calendars generally print Sunday as the first day of the week.  If none of the built-in locale definitions will meet your needs, you can always create a custom locale (as described in the docs) and then select that for use on your site.

Please open a new issue or reach out on Gitter if you still have questions.

**Comment by efroim102** [comment]
@offirpeer Use 'isoweek' instead of 'week' if your week starts on Monday.

**Comment by seltix5** [comment]
Hello,
I found this problem too, in my case I wanted the startOf Day using moment-with-locales.min.js 2.21.0

```
var a = moment("2018-03-25T22:24:03+01:00");
a.format()
 // 2018-03-25T22:24:03+01:00

var b = a.startOf('day');
b.format()
 // 2018-03-25T00:00:00+00:00
```

after using "startOf" the timezone is set to zero.
I reported the same problem here : https://github.com/moment/moment-timezone/issues/208
