### ISSUE TITLE
Recommended way to get uppercase short month name?

### ISSUE THREAD

**Issue by paulyoung** [moment/moment#765]
To get this format `02-MAY-2013` I'm currently doing this:

``` JavaScript

moment().format('DD-MMM-YYYY').toUpperCase();
```

Is there a better way?

I'm aware that I could introduce some custom [month abbreviations](http://momentjs.com/docs/#/customization/month-abbreviations/), but I currently only want to apply the formatting to this instance of the date.

**Comment by mcandre** [comment]
:/
