### ISSUE TITLE
calendar() display with time OR without time

### ISSUE THREAD

**Issue by mgray88** [moment/moment#778]
Sometimes I want to display the calendar date without the time, such as 'Today' instead of 'Today at 12:00 AM'

I realize you can edit the localization strings, but then this prevents the possibility of also occasionally using calendar() to display _with_ the time

I think there should be an option, or a sibling function to be able to do this

**Comment by milottit** [comment]
So it had been implemented eventually?

**Comment by carmenchapa** [comment]
Is this still not implemented?

**Comment by ArunimaSharma1909** [comment]
Do we have a solution as of now?
It creates an inconsistency as it does show time for recent days and just gets rid of the time for distant past/future dates.

Has anybody found a flag that can be set for including the time for distant dates as well.

**Comment by ArunimaSharma1909** [comment]
Found a fix for Ember here:
https://github.com/stefanpenner/ember-moment/issues/176


The PR for the same is:
https://github.com/stefanpenner/ember-moment/pull/179/commits/6d03b3f092a3f5d9aea16e83e56eaacc008b3b4c

**Comment by htmnk** [comment]
I've created a custom wrapper function around the calendar() , for 37 languages that I use [here](https://stackoverflow.com/a/65319457/3528132). Hope it helps.
