### ISSUE TITLE
Why does `startOf` modify object itself?

### ISSUE THREAD

**Issue by soswow** [moment/moment#832]
I am not is it a bug or a feature. If later one, than I don' see any point to make one.

```
m = moment("2013-05-31").subtract(1, 'month')
m.toDate()  //->Tue Apr 30 2013 00:00:00 GMT+0300 (EEST)
m2 = m.startOf('month')
m.toDate() //-> Mon Apr 01 2013 00:00:00 GMT+0300 (EEST)
```

Methods like `startOf` should only create new object. This is even semantically not right. I mean if you want to change object inplace the method should be like `setStartOf` or something.
I totally frustrated, that it doesn't create a copy by default. That I need to add .clone() all over the place.

**Comment by luisegr** [comment]
I was looking for that clone() function, this change everything, thanks!

**Comment by alfonmga** [comment]
This is crazy. I think documentation should have a warning message or smth.

**Comment by stefan-grigore** [comment]
This is absolutely mental. How the entire planet uses this library is beyond me.
