### ISSUE TITLE
Get a list of available locales

### ISSUE THREAD

**Issue by a701440** [moment/moment#843]
The page needs to initialize the moment.lang(xxx). There is no way to find out which languages are available and implement a fall back strategy.

**Comment by mj1856** [comment]
Reopening, since having a fallback still doesn't provide the functionality of listing the possible locales.

There should be a simple function, `moment.locales()` that returns an array of locale codes that have been loaded.

Ref: http://stackoverflow.com/q/31109303/634824

**Comment by jisaacks** [comment]
I agree, it would make things like [this test](https://github.com/moment/moment/blob/develop/src/test/moment/format.js#L337-L343) more maintainable.

**Comment by riderodd** [comment]
+1

**Comment by magicgrl111** [comment]
+1

**Comment by acdx** [comment]
+1

**Comment by dhonions** [comment]
+1

**Comment by k7sleeper** [comment]
+1

**Comment by jisaacks** [comment]
I could probably find some time to do this next week.

**Comment by mj1856** [comment]
Closing issue.  Tracking in PR #2932

**Comment by StefansArya** [comment]
I will left [this link](https://gist.github.com/StefansArya/1a9423fab2b966a08ea672a864a98333) here, in case if anyone looking a way to dynamically load the locales..

**Comment by tonix-tuft** [comment]
Sorry guys, I didn't understand. How can we list all the available locales of moment (all the supported ones, not `moment.locales()` which just returns those that were loaded) without loading all the locales at all and without hardcoding them in our code? Thanks!

**Comment by kuzdogan** [comment]
Found this list https://stackoverflow.com/questions/31109303/how-to-obtain-a-list-of-available-locale-keys-from-momentjs-with-locale
