### ISSUE TITLE
Switching timezone of moment without changing the values?

### ISSUE THREAD

**Issue by amitava82** [moment/moment#849]
Use case: User has a different timezone in app preference than local browser timezone. Using a jQuery datetime picker, user selects a date and time which is in local timezone (different from preference timezone). I want to change the timezone of the selected date without altering actual date and time selected by the user then of course I can convert it to UTC and send back to server.

```
moment(selectedDate) //convert javascript date to moment
moment.setTimezone('+0200')  // this should change timezone keeping the date and time unchanged
moment.utc().toJSON() //back to server
```

**Comment by absalonv** [comment]
is there a way to do 
 `moment('2015-04-20T07:00:00.427').format();`
 and
` moment('2015-04-20T07:00:00.427').zone(-120).format(); `

to get the same date and time but with different timezone?

`2015-04-20T07:00:00-07:00`
`2015-04-20T07:00:00+02:00`

**Comment by mj1856** [comment]
@absalonv see http://stackoverflow.com/a/28615654/634824

**Comment by nhuyk56** [comment]
> is there a way to do
> `moment('2015-04-20T07:00:00.427').format();`
> and
> `moment('2015-04-20T07:00:00.427').zone(-120).format();`
> 
> to get the same date and time but with different timezone?
> 
> `2015-04-20T07:00:00-07:00`
> `2015-04-20T07:00:00+02:00`
> 
> Right now is adjusting the time in the second option

BIG THANKS

**Comment by SteFF1997** [comment]
**zone is deprecated**
`import moment from 'moment-timezone';`
`const date = moment(startDate);` <- date have your local timezone
`date.tz('Europe/Amsterdam', true).format()` <- now date have Europe/Amsterdam, but time dont changed, thats all)

**Comment by triptizeus** [comment]
> **zone is deprecated**
> `import moment from 'moment-timezone';`
> `const date = moment(startDate);` <- date have your local timezone
> `date.tz('Europe/Amsterdam', true).format()` <- now date have Europe/Amsterdam, but time dont changed, thats all)

Thanks

**Comment by irfaan008** [comment]
To people who are coming on this 7 years old issue, Please use 
.utcOffset to set your desired timezone.
Ex - 
`
 let date=moment(datetime);
 date.utcOffset(0) // sets the timezone to GMT
`

**Comment by rajuashok** [comment]
Where can we get some documentation for this? This took me hours to find and seems like an obvious use case.

**Comment by rajuashok** [comment]
> To people who are coming on this 7 years old issue, Please use
> .utcOffset to set your desired timezone.
> Ex -
> `let date=moment(datetime); date.utcOffset(0) // sets the timezone to GMT`

This isn't ideal as you need to know the offset of your timezone.

**Comment by amitava82** [comment]
Alright, this is a very old issue and I've been using [moment-timezone](https://momentjs.com/timezone/docs/#/using-timezones/converting-to-zone/) for many years for this usease. Well, pretty much for every project that involves timezones. Here is how you'd do it. 
```
const localDateTime = new Date();
const userTimezone = 'America/Chicago';
const userDateTime = moment(localDateTime).tz(userTimezone, true);
```

**Comment by RobCubed** [comment]
> 
> 
> Alright, this is a very old issue and I've been using [moment-timezone](https://momentjs.com/timezone/docs/#/using-timezones/converting-to-zone/) for many years for this usease. Well, pretty much for every project that involves timezones. Here is how you'd do it.
> 
> ```
> const localDateTime = new Date();
> const userTimezone = 'America/Chicago';
> const userDateTime = moment(localDateTime).tz(userTimezone, true);
> ```

This still changes the date. I have a EST/EDT date coming back (out of my control unfortunately) and I need to convert it to the local client time.

```
export const convertMomentToLocal = dateTime => {
  console.log('incoming dateTime', dateTime)
  const estTimeZone = 'America/New_York';
  const estMoment = moment(dateTime).tz(estTimeZone, true);
  console.log('est:', estMoment.format())
  const utcMoment = moment.utc(estMoment)
  console.log('utc:', utcMoment.format())
}
```

Outputs:

```
incoming dateTime 2020-07-13T15:18:10.79Z
est: 2020-07-13T10:18:10-04:00
utc: 2020-07-13T14:18:10Z
```

So it's still assuming the incoming date is a UTC time instead of an EST/EDT time. I feel pretty dumb for not being able to figure this out, and I feel like it's a fairly common use case.

**Comment by mcoevert** [comment]
@RobUnderscore It really is a pain. Had the same confusion. I figured out you would first need to load the time as UTC, not zulu. So based on your example, this should work:
`const estMoment = moment.utc(dateTime).tz(estTimeZone, true);`
