### ISSUE TITLE
Duration Add/Subtract/Format

### ISSUE THREAD

**Issue by dcc635** [moment/moment#879]
I am using moment.js to create a countdown timer. Durations seem to be a better solution than moments as durations represent a date-less time as opposed to moments. However, since there are no Add/Subtract/Format operations on durations, I'm forced to do a lot of converting between moment objects and duration in order to take advantage of moment's Add/Subtract/Format methods. Has there been any thought in creating these methods for durations?

**Comment by GarimaBathla** [comment]
I am sorry for reviving an old thread but I have a question directly related to this api. 

I created a moment object 
let now = moment().utc(false);

and then I create a duration object 
moment.duration(2,"days");

now when I want add duration to moment - it doesn't work;

now.add(duration)  -- does not change the date to 2 days in future.

**Comment by GarimaBathla** [comment]
Oh never mind. I am sorry; Looks like duration does work. But only thing is lets say my duration was like 

moment.duration(24.6789,"days"); 

and I do moment.add(duration); => this will only add 24 hours, fractions in duration are not supported. I understand this is by design.
