### ISSUE TITLE
Moment format vs jQuery UI datepicker format

### ISSUE THREAD

**Issue by pahlers** [moment/moment#890]
It's not a bug, but more a feature request or something to think about.

I use Moment and the jQuery UI datepicker. I have to support i18n and so formatting is a big deal for me.

I wish to use the format of Moment to control the format of the datepicker. But sadly there is a different in formatting. I can't exchange the formats.

For example, 'Day of month' is in Moment 'DD', but in the datepicker 'dd'. '4 digit year' is in Moment 'YYYY', but in the datepicker 'yy'.

MM/DD/YYYY is 07/09/2013 in Moment, but July/Tuesday/YYYY in the datepicker.

Format Moment: http://momentjs.com/docs/#/parsing/string-format/
Format datepicker: https://github.com/jquery/jquery-ui/blob/master/ui/jquery.ui.datepicker.js#L1272

It would be nice for every one when the format is the same in every library.

**Comment by Federico-G** [comment]
I found this answer. Hope it helps:
http://stackoverflow.com/a/24500727

**Comment by tohood87** [comment]
May not be relevant so apologies if this isn't of any help.

I once had an input field share the functionality of the jQuery Full Calendar with Moment.js and the jQuery UI Date Picker:

I called the date picker first and set the dateFormat: 
- $(".datepick").datepicker({ dateFormat: "dd/mm/yy"});
- http://api.jqueryui.com/datepicker/#utility-formatDate

Then on the Full Calendar dayClick function I matched the formatting to achieve the desired joint functionality:
- var myday = event.format();
- $("#startTime").val(moment(myday).format("DD/MM/YYYY"));
- <input id="startTime" class="datepick" />

I know its limited but you can match a few up like:
1) dateFormat: "d.m.y" with: format("D.M.YY")
=  20.11.15
2) dateFormat: "dd MM y" with: format("Do MMMM YY")
= 19 November 2015 & 19th November 2015

The second example above has one of the items missing the "th" on 19. So this will require a little extra script to produce the "st, nd, rd, th" etc.
- http://stackoverflow.com/questions/8199204/adding-st-nd-rd-th-to-jquery-datepicker

$("#datepicker").datepicker({
    altField: "#alternate",
    altFormat: "DD, MM d",
    minDate: +0,
    onSelect: function(dateText, inst) {
        var suffix = "";
        switch(inst.selectedDay) {
            case '1': case '21': case '31': suffix = 'st'; break;
            case '2': case '22': suffix = 'nd'; break;
            case '3': case '23': suffix = 'rd'; break;
            default: suffix = 'th';
        }
        $("#alternate").val($("#alternate").val() + suffix);
    }
});

Hopefully future releases of date picker will follow in moment js formatting.
