### ISSUE TITLE
add() unexpectedly mutates the original object.

### ISSUE THREAD

**Issue by ssoroka** [moment/moment#955]
eg:

```
m = moment() # lets say it's Oct 3rd.
oct6 = m.add('days', 3)
```

oct6 is now oct 6th, as expected, but m has also changed, unexpectedly

```
oct7 = m.add('days', 4)
```

if add() had operated in a functional manner without mutating state, oct7 would in fact be set to october 7th, but because add() mutated the state of m, it's set to october 10th!

in fact, oct6 and oct7 are now the same object, m, and both reference october 10th.

this seems really unintuitive and can easily cause unintended consequences when moment objects are passed around in non-trivial applications.

**Comment by KristjanESPERANTO** [comment]
@akenverus As moment is no longer being actively developed, it is advisable to switch your projects to another library.

<https://momentjs.com/docs/#/-project-status/>
